### ISSUE TITLE
cookie is added to response without the 'secure' flag being set.

### ISSUE THREAD

**Issue by amarlearning** [TEAMMATES/teammates#10019]
cookies are added to response without the 'secure' flag being set.

https://github.com/TEAMMATES/teammates/blob/e01257fdd6870d5b9c569c26e55e33f6ad6a1875/src/main/java/teammates/ui/webapi/action/JsonResult.java#L52-L64

**Comment by tkech17** [comment]
i'll do it

**Comment by tkech17** [comment]
As i can write only one task assigned as FirstTimers, please assign it two me

**Comment by madanalogy** [comment]
> As i can write only one task assigned as FirstTimers, please assign it two me

You can proceed to submit a PR to address this issue. If anyone else would like to work on it they will check in with you first (if you have yet to submit a PR) so don't worry.

Also, take note of https://github.com/TEAMMATES/teammates/issues/10021#issuecomment-613499993. All the best! Let us know if you need any help :)

**Comment by madanalogy** [comment]
It appears that adding the secure flag impacts the e2e testing being performed as seen in #10024, therefore upgrading this to a contributor level difficulty

**Comment by amarlearning** [comment]
I would like to take this one if no one is taking

**Comment by sandysingh11918** [comment]
can anyone explain how it is effecting e2e testing or can provide more details on that? I am firstTimer here.

**Comment by madanalogy** [comment]
> can anyone explain how it is effecting e2e testing or can provide more details on that? I am firstTimer here.

@amarlearning has already indicated that he will be working on this issue. Managing the e2e testing is more complicated than advisable for first timers. Maybe you can consider working on a first timer issue instead? We have a first timer epic you could take a shot at contributing to in #10042
