### ISSUE TITLE
Add "Search bar" & "Sort By" in Student-Course-Details-Page

### ISSUE THREAD

**Issue by AdamPanag** [TEAMMATES/teammates#10015]
- **Environment**: Student-Course-Details-Page

**Description of feature/enhancement**

Here is an indicative screenshot of how I think it could look like (in the red rectangle is my addition):

![s2](https://user-images.githubusercontent.com/44143668/78723846-df4f5500-7934-11ea-8194-466eea4bc464.png)

**Justification**
The main benefit would be that the students will be able to find a specific teammate faster or sort them if they prefer to do so.

**Assigment**
As you can see I have already worked on it, writing some HTML! If you agree, I can go ahead with it! Please, let me know!

**Comment by AdamPanag** [comment]
Hello, I am working on this!

**Comment by hamza67100** [comment]
Hello, this issue is already fixed or can I work on it ?

**Comment by AdamPanag** [comment]
> Hello, this issue is already fixed or can I work on it ?

Hello, check this pr first #10030. You can try to sort students when the page is loaded or add the search bar. Or both of them :)

**Comment by hamza67100** [comment]
Ok nice I'll try to make the search bar and if it was enough esay to make the sort when the page is loaded :)

**Comment by wkurniawan07** [comment]
Closing as this is not a priority right now
