### ISSUE TITLE
Potential overflow before it is converted to long

### ISSUE THREAD

**Issue by amarlearning** [TEAMMATES/teammates#10020]
The variable `numberOfEmailsSent` and `emailIntervalMillis` are declared as `int` and the assignment variable is declared as `Long`. Potential overflow in `int multiplication` before it is converted to long by use in an assignment context.

https://github.com/TEAMMATES/teammates/blob/e01257fdd6870d5b9c569c26e55e33f6ad6a1875/src/main/java/teammates/logic/api/TaskQueuer.java#L224-L228

**Comment by tkech17** [comment]
i'll do it
