### ISSUE TITLE
Add "Enroll this student to a course" button in Student-Profile page

### ISSUE THREAD

**Issue by Aliki-Ntouzgou** [TEAMMATES/teammates#10029]
- **Environment**: Student-Profile-Page, Instructor-Courses-Page & Instructor-Course-Enroll-Page

**Description of feature/enhancement**
I already made locally the pages in order to show you how it could look like:
So, I am thinking about adding here this button, which will appear whenever an instructor is searching for a student:
![2020-04-12 (9)](https://user-images.githubusercontent.com/61196321/80514738-99ad0780-8989-11ea-9226-4def369154d3.png)

Whenever the instructor wants to enroll this student to a course, he/she will press this button and get to the courses page and will select "Enroll" in the course he wants the student to be enrolled:
![2020-04-13 (4)](https://user-images.githubusercontent.com/61196321/80514992-f4defa00-8989-11ea-8e62-9d3e03ff0dd5.png)

Finally, after selecting the course the instructor will be directed to the "Enroll students to course" page and the student's name and email will automatically be saved there:
![2020-04-13 (1)](https://user-images.githubusercontent.com/61196321/80515149-28218900-898a-11ea-9c22-385985b01000.png)

 **Justification**
I believe, since everything nowadays is getting even more and more operated automatically,  this enhancement can add value to the instructor's role and save him time and trouble, by enabling the instructor to enroll a student to a course without having to search in his files for the attributes of the student, or copy-paste an excel file, just by searching for this certain student and adding him to a course.

As you can see, I feel really motivated to implement this enhancement and add my mark to this project, so I would be extremely happy If you agree with it!

Thank you.

**Comment by Aliki-Ntouzgou** [comment]
Hello again, I am working on it!

**Comment by madanalogy** [comment]
This seems like quite a big undertaking, do let us know if you need any help yea

**Comment by Aliki-Ntouzgou** [comment]
> This seems like quite a big undertaking, do let us know if you need any help yea

Thank you so much for your reply and the offer of help! Will definitely let you know

**Comment by edwardkang0925** [comment]
Hello again, can my group try to add this feature?

**Comment by madanalogy** [comment]
> Hello again, can my group try to add this feature?

You're welcome to give it a go, but it is indeed quite complex so do ask for help if/when you get stuck :)

**Comment by damithc** [comment]
Sorry to chime in late on this. I missed this earlier. Adding a single student from one course to another is a very rare case and doesn't help in saving any time for the instructor because the remaining students need to be added to the course the normal way (might as well add all of them the normal way). I don't think this feature is worth supporting.

**Comment by madanalogy** [comment]
See https://github.com/TEAMMATES/teammates/pull/10217#issuecomment-647494793
