### ISSUE TITLE
Long error message when invalid inputs used for enrolling students

### ISSUE THREAD

**Issue by t-cheepeng** [TEAMMATES/teammates#10038]
- **Environment**: `master` branch at commit 2918cc169ceb9f6d585c1cc6d645b9a6f2ea7593

**Description of feature/enhancement**
![image](https://user-images.githubusercontent.com/28994607/81538570-7b8bd200-93a1-11ea-8b90-d6acae6bd85d.png)

Currently, error message for invalid inputs on the enrolling students page is very long. Furthermore, the message disappears in a few seconds when the instructor probably has not finish reading it.

Suggest either shortening the message or make the message persist at the top of the page. 

thoughts on solutions?

**Justification**
Instructors will benefit from this and know the proper format of the inputs

**Comment by madanalogy** [comment]
Persistence sounds like a good idea. Could either have it as a dismissible modal or text added to the page at the top. I'm not keen on shortening the message because there are no granular checks as far as I'm aware. 

Would you like to work on this issue? You can suggest implementation designs here for review first so you don't waste time coding something that might not be adopted :)

@xpdavid @wkurniawan07 fyi for any comments

**Comment by damithc** [comment]
IIRC, I raised this as a general issue earlier: error messages need to persist in most cases. Probably need to fix site-wide. 
Likely not needed to be a modal in most cases though, as modals require an additional click. Perhaps use modals only if we need some response from the user?

**Comment by t-cheepeng** [comment]
I wouldn't mind working on the issue. But I will have to take some time to get up to speed on the Angular framework before proposing any concrete details.

**Comment by madanalogy** [comment]
> IIRC, I raised this as a general issue earlier: error messages need to persist in most cases. Probably need to fix site-wide.
> Likely not needed to be a modal in most cases though, as modals require an additional click. Perhaps use modals only if we need some response from the user?

I was thinking optional persistence might require an additional click anyway to remove the error message, but yes worth considering to start an epic for this to be implemented site-wide and gain more comments for implementation

**Comment by xpdavid** [comment]
Yup. I think we can do this with an abstraction made in `statusMessageService`.
