### ISSUE TITLE
Server error when add new instructor by admin

### ISSUE THREAD

**Issue by Derek-Hardy** [TEAMMATES/teammates#10040]
- **Environment**: `master` branch at commit 2918cc169ceb9f6d585c1cc6d645b9a6f2ea7593
- **Browser**: Google Chrome
- **Server**: `dev server` listening at `localhost:8080`

- **Issue 1**: action to add instructor fails at `http://localhost:8080/web/admin/home`
<img width="887" alt="server error" src="https://user-images.githubusercontent.com/32880438/81570289-f6b9ac00-93d2-11ea-851b-840a2089be4b.png">

- **Error message**: 
```
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
        at com.google.appengine.tools.development.IsolatedAppClassLoader.loadClass(IsolatedAppClassLoader.java:208)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 65 more
```

However, the new instructor can still be found at `http://localhost:8080/web/admin/search`

<img width="1157" alt="instructor-list" src="https://user-images.githubusercontent.com/32880438/81571186-303ee700-93d4-11ea-960c-6e56302661a4.png">

- **Issue 2**: the join link does not work when entered as URL.

<img width="1041" alt="Screenshot 2020-05-11 at 21 54 39" src="https://user-images.githubusercontent.com/32880438/81571335-62504900-93d4-11ea-8793-dbf07016c914.png">

Following the warning, either I log in through **instructor login button** or **masquerade mode**, the error occurs.

<img width="1051" alt="Screenshot 2020-05-11 at 21 57 03" src="https://user-images.githubusercontent.com/32880438/81571633-c83cd080-93d4-11ea-9044-74488c5c74f2.png">

- **Problem**: due to the above issues, I am not able to interact with the application in instructor/student mode in the dev server. 

- **Setup status**: 
    * front & back-end are built successfully
    * run component test with 5 failed test cases
    * `staging server` is not yet deployed

**Comment by ccyccyccy** [comment]
Are you using JDK 8? I faced a similar problem as well when I used JDK 11.

**Comment by Derek-Hardy** [comment]
Many thanks to @ccyccyccy !

**Cause**: mismatched JDK (local: Java SE 9.0.1)

**Solution**: (for Mac OS X)
* run `/usr/libexec/java_home -V` on the terminal
* look for the path for Java SE 8 (Mac default version) `/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home` (in my case)
* in the root directory of the project, open `gradle.properties`, paste the line `org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home`
* open a new terminal, `cd` to the project folder, re-run the command `./gradlew createConfigs`

**Result**:
The above solution resolves the issue.
<img width="1302" alt="Screenshot 2020-05-12 at 10 45 21" src="https://user-images.githubusercontent.com/32880438/81633311-066eda00-943f-11ea-8096-ab02503657f1.png">

**Comment by Derek-Hardy** [comment]
Server error issue is resolved.
