### ISSUE TITLE
Apply Builder Pattern to LNPSpecification class

### ISSUE THREAD

**Issue by daekoon** [TEAMMATES/teammates#10041]
- **Environment**: Master branch 2918cc169ceb9f6d585c1cc6d645b9a6f2ea7593

**Description of feature/enhancement**
In the PR #10022, the L&P (Load and Performance) specification class was created to ensure Single Responsibility Principle - preventing the L&P class from handling both the testing and the verification of results. Currently the L&P testing class calls the constructor of L&P directly - this can be improved by applying the Builder pattern instead.

**Comment by Derek-Hardy** [comment]
I am interested to work on this issue.

**Comment by daekoon** [comment]
> 
> 
> I am interested to work on this issue.

Sure, I'll assign you to this.
