### ISSUE TITLE
Lift up "Add New Course" and "Sort By" buttons from table

### ISSUE THREAD

**Issue by Derek-Hardy** [TEAMMATES/teammates#10065]
- **Environment**: master branch a89c9825b656535b35cc8fc28955bd0627058e54

**Description of feature/enhancement**
The row including `Add New Course` and `Sort by` related buttons are too close to the table.

**Current**:
<img width="1200" alt="Screenshot 2020-05-18 at 10 38 38" src="https://user-images.githubusercontent.com/32880438/82169587-8213cf80-98f4-11ea-98d8-e957c31e1770.png">

**Expect**:
<img width="1206" alt="Screenshot 2020-05-18 at 10 38 11" src="https://user-images.githubusercontent.com/32880438/82169603-8c35ce00-98f4-11ea-935c-1b790f2c8e57.png">

**Comment by R4nKF1v3** [comment]
Hi, i'd like to tackle this issue
