### ISSUE TITLE
Add a dropdown button for the actions in the Instructor Courses table

### ISSUE THREAD

**Issue by Aliki-Ntouzgou** [TEAMMATES/teammates#10079]
**Environment**: Instructor Courses Page

**Description of feature/enhancement**:
What I suggest is combining all the actions, except the "Enroll" action as a main action, into a dropdown button.

**Pros**:
Improved UI, more 'clean' space, saving space.

**Cons**:
Requires one more click.

**This is how it looks now**:
![2020-05-16 (1)](https://user-images.githubusercontent.com/61196321/82360509-2f303a00-9a12-11ea-98c8-0b59772acb13.png)

**This is how I suggest it looks like after the enhancement**:
![2020-05-16 (3)](https://user-images.githubusercontent.com/61196321/82360568-42430a00-9a12-11ea-869f-aa02c68b3088.png)

Let me know what you think! :)

**Comment by madanalogy** [comment]
Enhancement looks good, suggest using title case for `Other Actions`. Am I right to assume you want to work on this?

**Comment by Aliki-Ntouzgou** [comment]
> Enhancement looks good, suggest using title case for `Other Actions`. Am I right to assume you want to work on this?

Yes, I would like to work on it!
