### ISSUE TITLE
Course Details page text should be aligned to the left

### ISSUE THREAD

**Issue by t-cheepeng** [TEAMMATES/teammates#10087]
- **Environment**: `master` branch at commit d10fa9cd9b2a97440f1fa92f81f3df6e373bf05f

**Steps to reproduce**
Text are all centered in the box
![image](https://user-images.githubusercontent.com/28994607/82430322-c0a9b580-9abf-11ea-95cf-5cd0a754bcb0.png)

**Expected behaviour**
Suggest shifting so it is left aligned which is what most other pages are showing at the moment
![image](https://user-images.githubusercontent.com/28994607/82432057-0ebfb880-9ac2-11ea-83ee-0ce2a3340032.png)

**Comment by damithc** [comment]
The second screenshot doesn't seem to be left-aligned enough. There's still some center-aligning going on.

**Comment by t-cheepeng** [comment]
updated with a better screenshot
