### ISSUE TITLE
Improve font size on instructor help page

### ISSUE THREAD

**Issue by Derek-Hardy** [TEAMMATES/teammates#10081]
- **Environment**: ff1abd25c3b77a1279bb09cffc041f1a57783563

**Description of feature/enhancement**:

The font sizes of **Section Name**(e.g. Sessions) and **Sub-section Name**(e.g. Setting Up Sessions) are too close. The **Section Name** loses its intended separation visual impact. Colour highlight does not seem enough.

<img width="565" alt="Screenshot 2020-05-20 at 12 02 34" src="https://user-images.githubusercontent.com/32880438/82403736-20896780-9a92-11ea-9012-1ed427123b12.png">

**Proposal**:
Reduce the font size of sub-section name to make section name stand out more.

**Comment by pablo-arroyo** [comment]
I see there's a PR for this issue, however seeing the commit it only changes the session part, I believe the update needs to be done on all sections, I'd like to work on this as a first timer, please let me know if it's available or if the person who submitted the PR will need to do the respective changes

**Comment by Derek-Hardy** [comment]
The snapshot in the issue is only an illustration of the problem. 

Font size should be updated across the `instructor-help-page` for obvious consistency.

**Comment by WaterHashira** [comment]
can i take this issue ??

**Comment by Derek-Hardy** [comment]
You are welcome to attempt on fixing this issue @WaterHashira .

However, do note the previous comment and the problem with the open PR so you do not just fix the issue partially.

**Comment by rushilp2311** [comment]
Hi I am new to open source. Any suggestions on how do i start.
The docs says to start with the d.firstcomers

**Comment by t-cheepeng** [comment]
@rushilp2311 Thank you contributing to the TEAMMATES project. Might i suggest you to take a look at #10042 and go through the application to see which pages you can optimize for mobile views. You are also welcome to make a new PR. In the future, please do comment on the issue that you are trying to solve/work on so that no one is doing double work.

**Comment by hamza67100** [comment]
Hello,
I'm new and I want to learn, I would like to know how can I start this issue and if this issue is already done. Even if it's already done I want to know how this issue was fixed.
Thank you :)
