### ISSUE TITLE
Add "Sort by" for unregistered students and "Remind students to join" option in the Instructor-Courses-Page

### ISSUE THREAD

**Issue by Aliki-Ntouzgou** [TEAMMATES/teammates#10096]
- **Environment**: Instructor-Courses-Page

**Description of feature/enhancement**
So, I was thinking about adding one more "Sort by", where the instructor can sort his courses by the  number of unregistered students of each course and then give him the option to remind them to join via email directly. I am thinking about two possible ways to remind the students: 1)add a "Remind students to join" link reference in the number of the unregistered students or 2)add one more button in the dropdown menu named "Remind" for the instructor to automatically send a "remind" email to his students.

**Justification**
I noticed that the instructor doesn't have an option where he can see the courses ordered by the number of unregistered students, which I believe can cause inconvenience when an instructor has to handle more than 2-3 courses. Also, if the instructor wants to remind his students to join the course he has to do it from the "View" page (which is 3 clicks until he gets to "Remind students to join").
The first way of "remind" only requires 1 click instead of 3 and the second way requires only 2 clicks instead of 3.

I think this can really enhance an instructor's experience when it comes to handling it students and courses and I would like to start working on it!

**Comment by damithc** [comment]
Thanks for the suggestion @Aliki-Ntouzgou 
Indeed it can be useful in cases where an instructor is handling many courses. However, based on our experience, that is a rare case. Most teachers teach 1-2 courses at any time. Furthermore, 'registering' is optional and almost no instructor requires students to register in a course. Instead, students submit responses using the submission links sent by TEAMMATES.

Given the above, we are unlikely to implement this enhancement in the near future.

**Comment by Aliki-Ntouzgou** [comment]
> Thanks for the suggestion @Aliki-Ntouzgou
> Indeed it can be useful in cases where an instructor is handling many courses. However, based on our experience, that is a rare case. Most teachers teach 1-2 courses at any time. Furthermore, 'registering' is optional and almost no instructor requires students to register in a course. Instead, students submit responses using the submission links sent by TEAMMATES.
> 
> Given the above, we are unlikely to implement this enhancement in the near future.
I completely understand, thank you for your time!

**Comment by Aliki-Ntouzgou** [comment]
> > Thanks for the suggestion @Aliki-Ntouzgou
> > Indeed it can be useful in cases where an instructor is handling many courses. However, based on our experience, that is a rare case. Most teachers teach 1-2 courses at any time. Furthermore, 'registering' is optional and almost no instructor requires students to register in a course. Instead, students submit responses using the submission links sent by TEAMMATES.
> > Given the above, we are unlikely to implement this enhancement in the near future.

I completely understand, thank you for your time!

**Comment by wkurniawan07** [comment]
Closing as this is not a priority right now
