### ISSUE TITLE
Make status message over comment modal

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#10101]
- **Environment**: master

**Steps to reproduce**
- Go to instructor result page per question view
- Open comment modal
- Click 'Add'

**Expected behaviour**
Error status message should be over the modal.

**Actual behaviour**
![image](https://user-images.githubusercontent.com/13977235/82745921-a92c3000-9d3e-11ea-93c2-fe33a4034662.png)

**Additional info**
Hint: Should be a simple CSS fix.

**Comment by Nimisha94** [comment]
Hello, I can take this up!
