### ISSUE TITLE
Do not apply removeAnonymousHash method for instructor result page

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#10123]
Due to #6092, we remove the anonymous hash for student page.

However, the operation should not be applied to instructor result page. The current implementation logic requires giver/recipient name to be unique for the views to function correctly.

https://github.com/TEAMMATES/teammates/blob/0e168752753ffdd1f1a85e71c15878edb5ae9a1d/src/main/java/teammates/ui/webapi/output/SessionResultsData.java#L160-L182

Hint: You only need to change two lines

**Comment by ccyccyccy** [comment]
> However, the operation should not be applied to instructor result page. The current implementation logic requires giver/recipient name to be unique for the views to function correctly.

Can I have some clarifications? What does "current implementation logic" refer to? Frontend or backend?

**Comment by xpdavid** [comment]
Both the frontend and the backend.
