### ISSUE TITLE
Can't run back-end server ( com.google.cloud.tools.appengine.AppEngineException )

### ISSUE THREAD

**Issue by adi282123** [TEAMMATES/teammates#10132]
- **Operating System:** Windows
- **JDK Version:**1.8
- **Node.js Version:** 14.3.0
- **Google Cloud SDK Version:** 294.0.0

Hello! I am new here. I have a problem with starting the back-end server. 
I set up the project according to the documentation.

It is my exception: 

> Execution failed for task ':appengineStart'.
> com.google.cloud.tools.appengine.AppEngineException: com.google.cloud.tools.appengine.operations.cloudsdk.process.ProcessHandlerException: Timed out waiting for the success message: '.*(Dev App Server is now running|INFO:oejs\.Ser
ver:main: Started).*'

This exception shows when I use `./gradlew appengineStart` command.

At the beginning, I was trying with **JDK 14** and **Gradle 6.3-rc-4**, but failed.

I was looking for a resolution on the Internet but all that I found don't repair my problem.

Thanks for help.

**Comment by wkurniawan07** [comment]
@adi282123 can you check if adding this line [here](https://github.com/TEAMMATES/teammates/blob/c2ce258fd591f3c983627cecc98b7f71426c315a/build.gradle#L260-L261) helps:
```patch
        port = 8080
+       startSuccessTimeout = 40
        jvmFlags = ["-Xss2m", "-Dfile.encoding=UTF-8",
```

Using Java that is not 8 is not expected to work. Gradle version should not be relevant since we're using wrapper here.

**Comment by adi282123** [comment]
It's working
