### ISSUE TITLE
Fill the rest of example boxes in help page

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#10144]
As we have almost all Angular components available, one could add them in the help page with dummy data and complete the migration for it.

The only example box that cannot be migrated is related to #10140, we will wait for the task to be done. We could also do it together with the PR to #10140.

**Comment by Derek-Hardy** [comment]
**Completed**:
- :white_check_mark: create a comment for a response (session section)

**Ongoing**:
- :construction: numerical question stats (question section)
- :construction: distribute point among options stats (question section)

**What's still left**:
- group-by, show/hide stats, view missing response and filter (**session section**)
- result sorted by GRQ (**session section**)
- student view of session's result (**session section**)
- search result (**session section**)
- team contribution question stats (**question section**)
- rubric question stats (**question section**)
- rank recipients question stats (**question section**)

**Comment by ccyccyccy** [comment]
Will work on:

- group-by, show/hide stats, view missing response and filter (session section)
- result sorted by GRQ (session section)
- student view of session's result (session section)

**Comment by Derek-Hardy** [comment]
Will handle the rest of question section `example box`

**Comment by madanalogy** [comment]
> * search result (**session section**)

This is the only one left right?

**Comment by Derek-Hardy** [comment]
Yup @madanalogy

**Comment by madanalogy** [comment]
I'll take this last box then and close the issue in my PR
