### ISSUE TITLE
Moment timezone data not loaded

### ISSUE THREAD

**Issue by ccyccyccy** [TEAMMATES/teammates#10152]
- **Environment**:  `master` branch

**Steps to reproduce**

1. Go to any instructor student record page with instructor comments on their feedback.
2. Expand the feedback 

**Expected behaviour**

No error.

**Actual behaviour**

Error appearing in the console.

<img width="1787" alt="image" src="https://user-images.githubusercontent.com/32454748/83489371-e0d66d00-a4e0-11ea-956b-84a4ed01573f.png">

Time presented on the UI seems to be accurate even though errors are printing on the console.

**Additional info**

Removing the following lines from `tsconfig.json` seems to solve the issue, but I'm not sure what it is doing.

```
"paths": {
      "moment-timezone": [
        "./node_modules/moment-timezone/builds/moment-timezone.min.js"
      ]
    },
```

**Comment by xpdavid** [comment]
We need to load the moment timezone database.

Previously we do this by using hack (1. inject timezone service, 2. call dummy method). Maybe it is time to standardize this.

**Comment by ccyccyccy** [comment]
From their [documentation](https://momentjs.com/timezone/docs/#/use-it/node-js/), it seems that the data is already loaded. So I think we don't need that hack anymore?

**Comment by xpdavid** [comment]
Nope. The time zone data not ship with the package (we choose not to do so) and is stored in `timezone.json`. Thus it need to be programmatically loaded.

**Comment by ccyccyccy** [comment]
What is the reasoning for not loading the time zone data when importing the package?

**Comment by wkurniawan07** [comment]
We want full control of what time zone setting is used in both back-end and front-end (e.g. right now we are using `2019c`; it is outdated, but it's another story). Coupling the information to the library takes away that from us.
