### ISSUE TITLE
Add sort function for question stats

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#10155]
This is an epic issue and can be solved by multiple PR.

Rank options:
![image](https://user-images.githubusercontent.com/13977235/83555790-ae6a4700-a4c3-11ea-8ac1-b02f4c6d6a3a.png)
![image](https://user-images.githubusercontent.com/13977235/83555766-a14d5800-a4c3-11ea-9618-8fe54a9330ce.png)

Rank recipients:
![image](https://user-images.githubusercontent.com/13977235/83555876-d48fe700-a4c3-11ea-9448-33435a6485c4.png)
![image](https://user-images.githubusercontent.com/13977235/83555849-c8a42500-a4c3-11ea-9363-efed1b004e09.png)

Rubric:
![image](https://user-images.githubusercontent.com/13977235/83555960-f6896980-a4c3-11ea-8173-6b746ae7e75f.png)
![image](https://user-images.githubusercontent.com/13977235/83555979-0143fe80-a4c4-11ea-90b8-409a4c3b156c.png)

Contribution:
![image](https://user-images.githubusercontent.com/13977235/83556055-20429080-a4c4-11ea-9e2d-bb5452277262.png)
![image](https://user-images.githubusercontent.com/13977235/83556096-2c2e5280-a4c4-11ea-8de0-109e9c761c73.png)

Constsum (recipients):
![image](https://user-images.githubusercontent.com/13977235/83556124-35b7ba80-a4c4-11ea-960d-7a77b39e42a3.png)
![image](https://user-images.githubusercontent.com/13977235/83556175-4bc57b00-a4c4-11ea-85c1-c54ff6a8a691.png)

Constsum (options):
![image](https://user-images.githubusercontent.com/13977235/83556253-6e579400-a4c4-11ea-8926-ee545e0aa1ff.png)
![image](https://user-images.githubusercontent.com/13977235/83556244-68fa4980-a4c4-11ea-9ba4-130d58097910.png)

MSQ:

![image](https://user-images.githubusercontent.com/13977235/83556516-e7ef8200-a4c4-11ea-8d15-f548ddbd82d4.png)
![image](https://user-images.githubusercontent.com/13977235/83556545-f178ea00-a4c4-11ea-845f-cb014b550608.png)

MCQ:
![image](https://user-images.githubusercontent.com/13977235/83556459-c8f0f000-a4c4-11ea-8683-feda3d1549cc.png)
![image](https://user-images.githubusercontent.com/13977235/83556445-c2fb0f00-a4c4-11ea-8bdb-fcef29c63033.png)

Numerical scale:
![image](https://user-images.githubusercontent.com/13977235/83556619-12413f80-a4c5-11ea-8a08-712c5426e4ce.png)
![image](https://user-images.githubusercontent.com/13977235/83556604-0a819b00-a4c5-11ea-9ebe-2599b30d3982.png)

**Comment by Derek-Hardy** [comment]
I will be working on **Numerical Scale** response summary.

**Comment by ccyccyccy** [comment]
Will work on MCQ response summary.

**Comment by markkulube** [comment]
I will work on Question 10, Constsum (recipients).

**Comment by t-cheepeng** [comment]
@markkulube Thank you for wanting to contribute to the TEAMMATES project. As this issue is not labelled with `d.*` labels, you should find first timer issues which have the label `d.FirstTimers` to start contributing

**Comment by ccyccyccy** [comment]
Will do `rank options`, `rank recipients` and `rubric`

**Comment by markkulube** [comment]
@t-cheepeng Yes, I was on phase C of the Contributing Guide and so searched for d.* issues. However the 3 d.FirstTimers issues seem to be already resolved or in the process of being resolved based on the respective comment threads.

Since it seems there are no unresolved d.FirstTimers issues I was brought here by the Contributing Guide, phase C recommends:
"In the event that you cannot find a d.FirstTimers-labelled issue, you can start with a d.Contributors-labelled issue. You can consult the e.* label, if it is present, to estimate the difficulty. Lower number generally means less amount of work required."

I am now confused then, so please point me the right direction given there are currently no first timers issues at the moment.

**Comment by t-cheepeng** [comment]
@markkulube You can take a look at #10042. There are still some pages that are not very mobile friendly. You can go through the application and find out which pages are not mobile optimized. After which, you can comment on the issue on which pages you are working on. A good place to start would be the session submission page which has not seen much progress for the past few weeks

**Comment by markkulube** [comment]
@t-cheepeng okay, thanks I will do that!

**Comment by t-cheepeng** [comment]
Will do `constsum (recipients)` and `constsum (options)`

**Comment by ccyccyccy** [comment]
Will do the rest (`Contribution` and `MSQ`)
