### ISSUE TITLE
Result Page: Collapsable box UI issues

### ISSUE THREAD

**Issue by ccyccyccy** [TEAMMATES/teammates#10153]
**In general**

The clickable parts of the boxes should change the cursor to a pointer when hovered over. This is a common issue at many places, e.g. `instructor-student-list-page`, `instructor-student-records-page`, and `instructor-session-result-page` as well.

**Instructor session result page**

1. When grouped by questions, clicking on the text does not collapse the box. However, clicking on the text collapses the box when grouped by any other way.
![output](https://user-images.githubusercontent.com/32454748/83506132-52bab080-a4f9-11ea-9103-d1fb2fdc3496.gif)

2. When grouped by questions at an MCQ question, click on "more" and try to expand the box. Only certain parts of the box is clickable.
![output](https://user-images.githubusercontent.com/32454748/83506778-33705300-a4fa-11ea-918a-def71aac1a9f.gif)

**Comment by Adrian27045** [comment]
Hello, I can take this up!

**Comment by ccyccyccy** [comment]
Sure go ahead. Let us know if you need any help :)

**Comment by Adrian27045** [comment]
I have a question about it: `When grouped by questions, clicking on the text does not collapse the box. However, clicking on the text collapses the box when grouped in any other way.`

The box should collapse when a user clicks text?

**Comment by ccyccyccy** [comment]
The `other way` means other grouping like `Group by - Giver > Recipient > Question`. There's more options in the dropdown menu:

<img width="646" alt="image" src="https://user-images.githubusercontent.com/32454748/83618539-29635880-a5bd-11ea-9320-8376b6299731.png">

<br/>

> The box should collapse when a user clicks text?

Yes, to make it consistent with the rest of the grouping. However, clicking buttons like the `[more]` button within the box should not collapse the box.
