### ISSUE TITLE
Instructor help page components: extract data out to dedicated file

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#10161]
Some instructor help page components, such as `instructor-help-questions-section.component.ts`, `instructor-help-sessions-section.component.ts`, and `instructor-help-students-section.component.ts`, have a lot of data defined in it as field. It works but is not a good practice as it pollutes application code with too much data.

The data should be extracted out into a dedicated `.ts` or `.json` file and then used via import. This would also enable reuse across different help page sections.

**Comment by manzurayusup** [comment]
@wkurniawan07 Hello, can my team work on this issue?

**Comment by wkurniawan07** [comment]
@manzurayusup you're welcome to.
