### ISSUE TITLE
Scrutinise unit test annotation and execution

### ISSUE THREAD

**Issue by madanalogy** [TEAMMATES/teammates#10163]
During the development of https://github.com/TEAMMATES/teammates/pull/10150/commits/a57439132b3515e51c953bc044623d5010ec68f7 I noticed that the access control tests were never called because they were not `public`. Fixing the access modifier led to the test case failing (which I then subsequently fixed). I suspect this might be happening on other unit tests and should thus be investigated when possible (probably after v7 initial release).

EDIT: Root cause was not the access modifier but rather the import of `Test` from `JUnit` instead of `testng`.

**Comment by xpdavid** [comment]
We should update the checkstyle rule to disallow the import of `@Test` from Junit. `org.junit.Test`
