### ISSUE TITLE
Data fails to load infrequently

### ISSUE THREAD

**Issue by ccyccyccy** [TEAMMATES/teammates#10187]
Environment: OSX Firefox

When you go to a page, the data are not loaded. E.g. the sessions page shows no sessions even though there are sessions. Can be fixed with a refresh to the page.

This issue occurs quite rarely and is hard to reproduce. No error is printed to the console.

Affects many pages
- Session page
- Session edit page
- Courses page 
- Home page

Needs further investigation.

**Comment by wkurniawan07** [comment]
https://stackoverflow.com/questions/27740692/request-stalled-for-a-long-time-occasionally-in-chrome

**Comment by wkurniawan07** [comment]
Resolved in V8
