### ISSUE TITLE
Implement proper error code response

### ISSUE THREAD

**Issue by ccyccyccy** [TEAMMATES/teammates#10180]
**Steps to reproduce**

Go to invalid page, e.g. http://localhost:8080/web/instructor/home/asda

**Expected behaviour**

404 error should be returned

**Actual behaviour**

200 returned

**Comment by hamza67100** [comment]
In which part of the code could I find the management of this problem?

**Comment by t-cheepeng** [comment]
@hamza67100 Thank you for wanting to contribute to the TEAMMATES project. It seems like this is your first time contributing to the project. Might I suggest you to look at #10042 or #10081 as first timer issue to work on

**Comment by wkurniawan07** [comment]
This is not a simple thing to do. `/web/*` as far as the Java servlet is concerned is a valid endpoint and the back-end does not know (nor it should know) the actual web page structure in the front-end.

**Comment by wkurniawan07** [comment]
This is not possible for SPA application. Reference: <https://stackoverflow.com/questions/43135184/how-can-you-return-status-code-404-from-angular-pagenotfoundcomponent>.

If we really, really need this kind of status code provision, we need an SSR implementation like Angular Universal, but that's a beast on its own.
