### ISSUE TITLE
Instructor Help Page button text is centre-aligned

### ISSUE THREAD

**Issue by Derek-Hardy** [TEAMMATES/teammates#10197]
**Reproduce**
- Log in as instructor, go to Help page.
- set the window size as mobile.
- observe the button with long text

**Expected behaviour**

For the long button text, it should break lines and be left aligned in the mobile screen.

**Actual behaviour**

<img width="367" alt="Screenshot 2020-06-17 at 09 26 01" src="https://user-images.githubusercontent.com/32880438/84844370-c2de4000-b07c-11ea-919a-f08972c21c40.png">

After line break, the long text is centrally aligned, which looks inconsistent with the rest of buttons.

**Comment by telvinzhong** [comment]
I'm happy to work on this! I'm a beginner but have some css experience. Would simply submitting a fixed pull request be enough to solve this issue?

**Comment by madanalogy** [comment]
> I'm happy to work on this! I'm a beginner but have some css experience. Would simply submitting a fixed pull request be enough to solve this issue?

We would ideally also like for you to take a screenshot of your fix for manual verification. This means setting up the development server and navigating to the page where your fix is applied. For more information, you can read our [development guide](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md).

**Comment by hamza67100** [comment]
Hello can I take this issue ? I'm beginner and want to learn to improve my experience :)

**Comment by telvinzhong** [comment]
I'm already working on this issue but if there are any further beginner friendly bugs I can forward them to you if you'd like

**Comment by hamza67100** [comment]
I just finished the issue haha how can I PR ?

**Comment by madanalogy** [comment]
> I just finished the issue haha how can I PR ?

@hamza67100 Please note that someone else had already indicated that they were working on the issue. This means that your PR might be put on hold if said person submits their PR before yours is merged.

@telvinzhong I would recommend submitting your PR soon (preferably within the next 24 hours), it will be given priority for consideration as you had indicated that you would be working on the issue. However, we cannot wait indefinitely as well. Without a PR from you we will go ahead and process the submitted PR.
