### ISSUE TITLE
Migrate student list CSV to frontend 

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#10220]
Sub-issue of #10156

**You should make changes against `csv-migration` branch and send PR against it**

In V6 we generate the CSV in the backend as `GetStudentsAsCsvAction`.

Now, since we have RESTFul endpoint called `GetStudentsAction`, we can fetch students as JSON array and generate the CSV in the frontend.

Hints:
- You will need to write code in `student.service.ts` (Free feel to create another service if think it is more appropriate)
- You can take a look of `session-result-csv.service.ts` to see how the CSV is generate for session result. `csv-helper.ts` is the key (You don't need `sanitizeForCsv` and `,`-concatenation as `convertCsvContentsToCsvString` will do this for you).
- Your logic in the frontend should mimic the backend CSV generation logic. You can trace it down in `GetStudentsAsCsvAction`
- You should write tests for it. You will need to migrate test for `GetStudentsAsCsvAction` and `CourseLogic#getCourseStudentListAsCsv`. You don't need to migrate everything but just make sure the scenarios are all covered.
- Your test should be written as snapshots testing to verify the CSV content (see `session-result-csv.service.spec.ts` for examples).
- Don't forget to delete the CSV generation code in the backend after you finish it

**Comment by madanalogy** [comment]
Resolved with #10235
