### ISSUE TITLE
Standardize the use of styles in V7

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10243]
In general, we should use a neutral color scheme across the site to cover most of the UI (e.g., black/grey or the light blue as we did in V6) and use built in color schemes (i.e., primary, info, warning, danger) to give subtle hints only when necessary. e.g., use 'danger' style only when indicating a dangerous action and use the 'warning' style only when warning the user about something. Indiscriminate or overuse of those style can diminish their meaning.

As an example, this panel has either low or too much contrast between buttons and the background. We may have to use the 'dark' theme for important panels (and 'secondary' for less important panels) so that all other style buttons can look good when embedded inside a panel heading. Something to think about when doing site-wide style tweaks later.

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/32454748/85823683-97600180-b7b0-11ea-900d-17873d5f2f0f.png">

We should not use arbitrary colors for buttons. It makes sense for delete button to be red (I'd rather make the button a neutral color and use red only for the icon though) but I don't think we should use different colors for the duplicate and edit buttons.

**Comment by ccyccyccy** [comment]
I think for buttons against darker backgrounds, we can put a white outline around the box, while for buttons against light backgrounds, we can use a grey outline. This is to prevent the buttons from blending in with the background

Dark background:
![image](https://user-images.githubusercontent.com/32454748/86775389-ec8df400-c089-11ea-936f-3c3c3ed25120.png)

Light background:
![image](https://user-images.githubusercontent.com/32454748/86778063-822a8300-c08c-11ea-9e9c-70c33274f71f.png)

For buttons like delete, I think we can use the full red button while it is hovered, but it should look the same as its neighbouring buttons.

![image](https://user-images.githubusercontent.com/32454748/86777769-252ecd00-c08c-11ea-8cfc-fa41ddf07854.png)

**Comment by damithc** [comment]
> I think for buttons against darker backgrounds, we can put a white outline around the box, while for buttons against light backgrounds, we can use a grey outline. This is to prevent the buttons from blending in with the background

That might work. Keep in mind that we are adding an entirely new visual element, increasing the 'business' of the visual. I think this looks better?
![image](https://user-images.githubusercontent.com/1673303/86804141-43ef8c80-c0a9-11ea-90ce-ee4398852710.png)


> For buttons like delete, I think we can use the full red button while it is hovered, but it should look the same as its neighbouring buttons.

Yes, for 'danger' buttons we can use that. No need for other buttons.

**Comment by ccyccyccy** [comment]
> That might work. Keep in mind that we are adding an entirely new visual element, increasing the 'business' of the visual. I think this looks better?
> ![image](https://user-images.githubusercontent.com/1673303/86804141-43ef8c80-c0a9-11ea-90ce-ee4398852710.png)

Isn't that the same as current implementation? So we should just keep it as it is?

My issue with the current implementation is that it blends into the background with its flat design, which would lead users to glance over it. Maybe we can adjust the contrast such that outline does not pop out too much? 

Something like this

![image](https://user-images.githubusercontent.com/32454748/86872572-41c01900-c10f-11ea-83c5-16688ad7620e.png)

**Comment by damithc** [comment]
> Isn't that the same as current implementation? So we should just keep it as it is?

Yes.

> My issue with the current implementation is that it blends into the background with its flat design, which would lead users to glance over it. Maybe we can adjust the contrast such that outline does not pop out too much?

Based on recent GitHub UI tweaks, seems that's not an issue. They removed border and there is no change in bg color. 

![image](https://user-images.githubusercontent.com/1673303/86873266-88fad980-c110-11ea-877f-412e301c7479.png)

Let's go without border first. We can add a light border (or do something else) after some dogfooding later.

**Comment by wkurniawan07** [comment]
Superseded by #10976
