### ISSUE TITLE
API Output Data Privacy Review

### ISSUE THREAD

**Issue by madanalogy** [TEAMMATES/teammates#10264]
Anonymize/Encrypt/Omit the following fields from API Output whenever applicable and where applicable ensure that the process is covered by unit tests:
- Feedback response ID
- Feedback question ID, if necessary
- Response comment ID, if necessary
- User email/name/Google ID, if anonymity is required
- Feedback session grace period (e.g. students should not know the grace period of any feedback session)

Legend:
❕= good to hide/encrypt
❗= needs to be hidden/encrypted

**Comment by wkurniawan07** [comment]
From various student-facing pages, as far as I can tell:

`/courses?entitytype=student`:
❕`creationTimestamp`, `deletionTimestamp`

`/sessions?entitytype=student&courseid=...`:
❕`createdAtTimestamp`

`/students?courseid=...&teamname=...`:
❗ `googleId`

`/result?courseid=...&fsname=...&intent=STUDENT_RESULT`:
❗❗❗ `responseId`

`/responses?questionid=...&intent=STUDENT_SUBMISSION`:
❕`feedbackResponseId`

**Comment by madanalogy** [comment]
Since `feedbackResponseCommentId` is a `long` primitive, there might not be much benefit in obfuscating the value? This is as opposed to the cost of first having to convert it to a string representation for encryption then subsequently decrypting it when received as an input.

**Comment by madanalogy** [comment]
>`/search/students?searchkey=...` (if used by instructor):
❗`googleId`
❗`key`
❕`institute`

I think this was a side effect of performing an instructor search while also an admin. Should be fixed in #10273

**Comment by xpdavid** [comment]
`/questions`
- questionDetails
    - MSQ/MCQ/Rubric: Weights (should hide for students)
