### ISSUE TITLE
API Endpoint Access Control Review

### ISSUE THREAD

**Issue by madanalogy** [TEAMMATES/teammates#10263]
Review all api endpoints and generated actions for appropriate access control measures and ensure that they are all covered by the corresponding unit test. Special focus on publicly accessible endpoints as follows:

Public GET Endpoints:
- /auth
- /auth/regkey
- /nationalities
- /student
- /instructor
- /session
- /result
- /questions 
- /question/recipients
- /responses
- /responsecomment

Public POST Endpoints:
- /errorreport
- /sessionlinksrecovery
- /response
- /responsecomment
- /submission/confirmation

Public DELETE Endpoints:
- /response
- /responsecomment

**Comment by xpdavid** [comment]
Another important point is to review the fields in the API response. This might be more business-requirement involved. Feel free to raise question if in doubt.

For example, when instructors try to get the students in a course. He should not know the `googleId` of the each student (while this seems to be true now so we should fix that)

**Comment by wkurniawan07** [comment]
> to review the fields in the API response.

This is covered under #10264.
