### ISSUE TITLE
Update supported browsers

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10278]
![image](https://user-images.githubusercontent.com/1673303/86532830-6cd41e00-beff-11ea-80ab-6d22b92f035e.png)

The above shows up when I access V7 using Edge. Should add support for Edge? Also, should we drop support for IE?

**Comment by wkurniawan07** [comment]
https://angular.io/guide/browser-support
https://getbootstrap.com/docs/4.0/getting-started/browsers-devices

Edge support can be listed down. IE support is not necessary to be dropped.

But in general, browser support is difficult to quantify precisely. Unless we want to put resources to test on every single version of every single major browser in the world (I don't think any company in the world would do this), the above list serve as just approximation, not precise requirement.
