### ISSUE TITLE
Clear Objectify DB

### ISSUE THREAD

**Issue by nodermatt** [TEAMMATES/teammates#10272]
Help Request: Clear objectify db of entries

- **Commit SHA: a26255521fecddcfa1e14df261ccd576a56dac23
- **Operating System: Windows 10
- **JDK Version: 1.8.0_251
- **Node.js Version: v12.16.1
- **Google Cloud SDK Version: not found

**What I was trying to do / What I need help with**
I am trying to clear the teammates db of all entries as I somehow created a corrupt entry. This prevents me from adding users to courses, that's to say when I click their invite link the following screen is displayed after logging in. Afterwards the status of the student remains "Yet to join" on the session page.
![image](https://user-images.githubusercontent.com/1467464/86347562-bf42df80-bc5e-11ea-96d4-9c5b133fbdb2.png)

I can't see any exceptions in the console so it is unclear what exactly is going wrong.

I am not familiar with Objectify and thus don't know how to browse the datastore. As far as I know, there is no plugin for IntelliJ that would allow me to easily browse the data, similar to MongoDB or SQL.

**Attempts to resolve the problem**
I tried to search for a system folder that would contain the teammates files but couldn't find any.

**Comment by madanalogy** [comment]
If you just want to reset the db, you can delete the `local_db.bin` file in the folder `appengine-generated` which is created in the root of your teammates project folder when you run the appengine dev server.

**Comment by wkurniawan07** [comment]
While what @madanalogy said is true, the error message said: "Error: invalid entity type" and it does not sound like something that is caused by broken DB. @nodermatt can you paste the invite link you're using here?

**Comment by nodermatt** [comment]
@madanalogy Thanks for the hint. I found the file and could start fresh by deleting it.
@wkurniawan07 I am sorry I didn't see your message in time. I have already deleted the database and can't reproduce the error now. When I use one the previous invite links, I do get the error message "No student with given registration key" which is expected as this particular student doesn't exist anymore
e.g
http://localhost:4200/web/join?key=38059BED6276E8D0875EF6FBFDF363845E6F2E85870C4924EDA64F8F07187EB808FBF38A6F847861788225D312C32A4E23CBA9833440F74E0483A50F34F34F5F67B1B139DCE91B2989B30F86775F818A&studentemail=howard.fizzlegear@students.hogwarts.co.uk&courseid=10042-mobile&entitytype=student

Let me know if that helps anyway, I'll close the issue once you've seen my update

**Comment by wkurniawan07** [comment]
That link shouldn't produce the error message "Error: invalid entity type" even before your DB got corrupted (if it ever was). I suspect you copied the link wrongly and left out the `entitytype` at the end, that's the only way to trigger the error you have seen before.

**Comment by nodermatt** [comment]
Thanks for the follow-up @wkurniawan07. Closing this issue now.
