### ISSUE TITLE
Link recovery: submission link ends up in session results page

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10302]
Tried to retrieve submission links. Received this:
![image](https://user-images.githubusercontent.com/1673303/87242229-52e58e80-c45d-11ea-9fb5-8c0e20f2829a.png)

Clicking on the link resulted in this:
![image](https://user-images.githubusercontent.com/1673303/87242240-6d1f6c80-c45d-11ea-9edd-1d3b8d5f6017.png)

Note that I've already joined the course and I'm also an instructor in that course, if that is relevant. I can access the submission page via my student home page.

**Comment by wkurniawan07** [comment]
@damithc what is the exact URL attached in the link there?

**Comment by damithc** [comment]
`https://teammates-uat.et.r.appspot.com/web/sessions/submission?courseid=damith.gma-demo&fsname=First+session&key=DCCBC69C8891A45C00E6ABAA9EE58F16418FEABBC2452DCC602690279B934346A146CFF757A28982B93E7825FA47FFXX&studentemail=damith%40gmail.com`

I changed the key slightly. Can email you the exact link if needed.

**Comment by wkurniawan07** [comment]
@damithc there is no way that link ends up in session results page. Try again?

**Comment by damithc** [comment]
> @damithc there is no way that link ends up in session results page. Try again?

Still the same:
![image](https://user-images.githubusercontent.com/1673303/87280808-2137fa80-c525-11ea-929b-f1d798215375.png)

I wonder if any of these has an effect:
* I also have admin rights
* I'm also an instructor in that course
* I have joined the module

**Comment by damithc** [comment]
> I wonder if any of these has an effect:
> 
> * I also have admin rights
> * I'm also an instructor in that course
> * I have joined the module

I tired another case where those three conditions are false. Worked as expected. So, one of these three conditions are causing the problem.
