### ISSUE TITLE
Instructor adding questions: new question does not inherit setting from the previous question

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10304]
V7

When adding a new question to a session, the question is supposed to inherit path and visibility setting from the question just above it. This doesn't seem to be the case in V7.

**Comment by wkurniawan07** [comment]
I don't think we (or at least, I) know this feature. Is it a deliberate product decision?

**Comment by damithc** [comment]
> I don't think we (or at least, I) know this feature. Is it a deliberate product decision?

Yes, based on the observation that often the path/visibility of questions in a session follow a similar pattern. If our guess is correct, the user has less work to do (a pleasant surprise for her). If our guess is wrong, the user has to change the settings but that's no different even if we didn't guess.
