### ISSUE TITLE
Services should not be accessing component related models

### ISSUE THREAD

**Issue by t-cheepeng** [TEAMMATES/teammates#10315]
In `search.service`, there are many instances where the service transforms data into component related models. This breaks reusability of the services as it is tightly linked to the component.

**Task**
- Define new interfaces for the service to decouple them from component models
- Have the components accept these new interfaces and transform them to their respective models for use

**Comment by moziliar** [comment]
Hi, may I learn more about this issue? Would love to know if making a factory for this is enough.

**Comment by t-cheepeng** [comment]
@moziliar Hi, if you take a look at https://github.com/TEAMMATES/teammates/blob/164b161e398ea922dce2b21772976f57a934627d/src/web/services/search.service.ts#L478-L480

The `search.service`  transforms the data into the models used by the components(The `SearchXXXTable`). We wish to avoid this. So we want to shift the transformation of data to the components and you can do so by creating an interface for the search service to return and placing the transformation code in the respective components that use this service

**Comment by moziliar** [comment]
@t-cheepeng I see. So basically, the returned search result should be in its raw form (the new interface to be defined), whereas the transformation logic should only reside in the components that uses it?

**Comment by t-cheepeng** [comment]
@moziliar 
> the returned search result should be in its raw form (the new interface to be defined), whereas the transformation logic should only reside in the components that uses it

Yes, that is correct.

> become bloated as more possible form of results

You really only have to do this for `InstructorSearchResult`. The rest of the method in this service have been decoupled 

> components using such raw interface to do the extra work that was previously done in the search.service.

We wish to make the service return the data as is. If we confine it to some component model, it will be inflexible

**Comment by moziliar** [comment]
@t-cheepeng Yup. I roughly understand the intent and the expectation of this refactoring. Will do up a PR for vetting.

One point I have in doubt still is that: the whole point of this refactor is to make these search functions more flexible for future extension (higher extensibility). This is the part about what I say that the bloatedness of the new "raw data" interface could get: it would need to house more data types. As I come from a GoLang background where interface is pretty different in definition, this issue appeared slight odd to me. 

I assume that the new interface would only have 1 field: the raw content, where the exact schema of it must be validated by the component using it?
