### ISSUE TITLE
Instructor course details page: cells should be left-aligned

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10336]
Current:
![image](https://user-images.githubusercontent.com/1673303/87855029-3ad3aa80-c948-11ea-8039-5b76fe267bc2.png)

For easier readability, columns such as team, name, email should be left-aligned.
Might apply to other tables as well.

**Comment by ccyccyccy** [comment]
> For easier readability, columns such as team, name, email should be left-aligned.

Is the criteria mainly variable length columns?

**Comment by damithc** [comment]
> Is the criteria mainly variable length columns?

I think it's more to do with the actual content. I guess we can left-align by default?

**Comment by ccyccyccy** [comment]
> I think it's more to do with the actual content. I guess we can left-align by default?

Sounds good. I think the buttons should be center align though.

**Comment by damithc** [comment]
> Sounds good. I think the buttons should be center align though.

Sure.
