### ISSUE TITLE
Instructor courses page: drop-down tooltip is too narrow

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10333]
Current:
![image](https://user-images.githubusercontent.com/1673303/87854675-15de3800-c946-11ea-8bad-f578e2582383.png)
The tooltip width seem to follow the width of the drop-down. Makes the tip harder to read.

Might apply to other places well.

**Comment by madanalogy** [comment]
@ccyccyccy does this get fixed with #10321?

**Comment by ccyccyccy** [comment]
> @ccyccyccy does this get fixed with #10321?

Nope it doesn't
