### ISSUE TITLE
Instructor courses page: hard to see the sorting order

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10332]
Current:
![image](https://user-images.githubusercontent.com/1673303/87854554-5a1d0880-c945-11ea-9086-1d331b6966a2.png)

![image](https://user-images.githubusercontent.com/1673303/87854618-c6980780-c945-11ea-8b3b-ad0bbd5e4f48.png)

Not only the highlighted arrows blends into the background, the arrow direction seems to be wrong too.

Might be applicable to tables in other places as well.

**Comment by ccyccyccy** [comment]
> the highlighted arrows blends into the background

What do you mean by "blend into the background"? I think white seems like a good contrast against blue? Or do you want the non-active sorting arrow to show as black?

**Comment by niqiukun** [comment]
> What do you mean by "blend into the background"? I think white seems like a good contrast against blue? Or do you want the non-active sorting arrow to show as black?

I think in V6, grey colour means non-active while black means active. So following the same logic in V7 the active colour becomes blue which "blends into the background". But in fact we are using white as the active colour instead.

**Comment by damithc** [comment]
> I think in V6, grey colour means non-active while black means active. So following the same logic in V7 the active colour becomes blue which "blends into the background". But in fact we are using white as the active colour instead.

That's right. If white is the active color, it's confusing to see a whole bunch of white arrows in every column. The user has to look for the _solo_ white arrow to figure out the sorting order. It can be made more obvious if only the sorted column and the sorted direction is in the active color.

**Comment by ccyccyccy** [comment]
Seems like we need the pro version of font awesome? https://fontawesome.com/icons/sort-up?style=duotone 
Unless we write our own

**Comment by damithc** [comment]
I wonder if we can get what we want by overlaying these one over the other :-p
![image](https://user-images.githubusercontent.com/1673303/88643466-4ebf9f00-d0f4-11ea-8879-d1b32d5d1eeb.png)

e.g., `up` in _active_ color overlaid on top of `sort` in _inactive_ color.

alternatively, we can use `sort` in inactive color (`text-secondary`?) and `up` and `down` in active color (`text-dark`?) with no overlaying?

Do some mockups to see how/

**Comment by ccyccyccy** [comment]
Something like this?

![output](https://user-images.githubusercontent.com/32454748/88656385-cd233d80-d102-11ea-8efe-2cff6180dc81.gif)

**Comment by damithc** [comment]
> Something like this?

Yes. Looks good. 👍
