### ISSUE TITLE
Instructor delete student: modal uses inconsistent styles

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10339]
Current:
![image](https://user-images.githubusercontent.com/1673303/87855302-e92c1f80-c949-11ea-90dd-049179fde2e8.png)

This modal is inconsistent with others in almost all aspects. In particular, the text should not be bold and blue should not be used to mark words (blue text is supposed to be hyper links)

**Comment by ccyccyccy** [comment]
Closed by https://github.com/TEAMMATES/teammates/pull/10293
