### ISSUE TITLE
Instructor: view instructor details: modal header missing

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10345]
![image](https://user-images.githubusercontent.com/1673303/87855960-63f73980-c94e-11ea-9179-7349763adb4f.png)

V6:
![image](https://user-images.githubusercontent.com/1673303/87855972-82f5cb80-c94e-11ea-9b9d-9dba56ff9489.png)

Even better if the instructor's name can be shown in the header

**Comment by wkurniawan07** [comment]
@damithc adding instructor's name doesn't make sense because this is generic permission listing

**Comment by damithc** [comment]
> @damithc adding instructor's name doesn't make sense because this is generic permission listing

Right. No need in that case.
