### ISSUE TITLE
Multiple tooltips shown at times

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10349]
![image](https://user-images.githubusercontent.com/1673303/87856928-1cc07700-c955-11ea-9cc0-1bab6d44dccf.png)

e.g., 
1. Hover over a button
1. Click on the button to open a modal
1. Close the modal
1. Hover over another button

Result: tooltip for the previous button remains while the one for the new button shows up as well

**Comment by hamza67100** [comment]
Hello, I'm looking for which files I need to change if you already know it that could be cool for me :)

**Comment by madanalogy** [comment]
@ccyccyccy does this get fixed with #10321?

**Comment by hamza67100** [comment]
@madanalogy 
![Screenshot_18](https://user-images.githubusercontent.com/50500740/88077611-c1240280-cb7b-11ea-92a8-a0a600073730.png)
It's what I have

**Comment by ccyccyccy** [comment]
> @ccyccyccy does this get fixed with #10321?

Nope it doesn't.
