### ISSUE TITLE
Instructor course details page: 0 is shown before the actual numbers appear

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10340]
![image](https://user-images.githubusercontent.com/1673303/87855364-53dd5b00-c94a-11ea-8efe-8b9a61d9423a.png)

These appear as `0` momentarily before the actual numbers appear. It's best not to show incorrect data even momentarily. Show loading indicators?

**Comment by niqiukun** [comment]
Issue fixed by #10309.
