### ISSUE TITLE
Instructor view all records page: tweak line style

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10344]
![image](https://user-images.githubusercontent.com/1673303/87855800-3c53a180-c94d-11ea-9255-bb2f201e15b1.png)

Line style can be tweaked to emphasize the hierarchy of elements. e.g.,
![image](https://user-images.githubusercontent.com/1673303/87855817-5f7e5100-c94d-11ea-951e-de49fdfea7c7.png)

**Comment by ccyccyccy** [comment]
Fixed by https://github.com/TEAMMATES/teammates/pull/10395

Looks like this currently

![image](https://user-images.githubusercontent.com/32454748/89170592-7316f200-d5b2-11ea-938c-9dd9265ba491.png)
