### ISSUE TITLE
Instructor view results: inconsistency in contribution questions

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10357]
v7:
![image](https://user-images.githubusercontent.com/1673303/87858910-e9d1af80-c963-11ea-81c2-2b2379dceeb8.png)

v6:
![image](https://user-images.githubusercontent.com/1673303/87858845-77f96600-c963-11ea-9c0a-50ee0cfab77d.png)

Values are totally different. I remember discussing this with @wkurniawan07 but I'm not sure if we should change the behavior from v6 to v7. I think we should show normalized values here or else it won't match with the summary table above.

**Comment by wkurniawan07** [comment]
> I think we should show normalized values here

Copying the discussion here:
- Not showing the raw value here will cause inconsistency when instructor moderates the response
- Showing the raw value here does cause inconsistency with the summary table, but summary table is not meant to be the exact same. Summary table, as the name says, shows the value after all the normalization and what-nots happen, so we can give as many extra context as necessary there.

**Comment by damithc** [comment]
> * Not showing the raw value here will cause inconsistency when instructor moderates the response
> * Showing the raw value here does cause inconsistency with the summary table, but summary table is not meant to be the exact same. Summary table, as the name says, shows the value after all the normalization and what-nots happen, so we can give as many extra context as necessary there.

In that case we should show both (i.e., add a column for raw values or show within brackets)? Raw values are not useful (even misleading) for interpreting the values received and the table is used more for interpreting rather than moderating. Our current users are used to seeing the normalized values in that table.

**Comment by damithc** [comment]
Discovered that this really needs to go back to the original (or at least show both values). If not, there is no way to get the individual normalized value from the csv file. The summary table does not show specifically who gave which normalized value to whom. In my module, I have grading scripts that depend on that value to be there in the csv file. Raw value is useless for any kind of analysis as each student is possibly using a different raw scale.
