### ISSUE TITLE
Instructor view results: MCQ summary order is different from the question

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10355]
![image](https://user-images.githubusercontent.com/1673303/87858204-c35d4580-c95e-11ea-9ebb-e7017300accf.png)

This order is different from the order used in the question.

**Comment by niqiukun** [comment]
Is this because the response summary is sorted by percentage by default?

**Comment by damithc** [comment]
> Is this because the response summary is sorted by percentage by default?

Possibly. In that case, the default sorting should be based on option because options might have some meaningful order.
