### ISSUE TITLE
Inconsistent padding around modals

### ISSUE THREAD

**Issue by niqiukun** [TEAMMATES/teammates#10372]
https://github.com/TEAMMATES/teammates/pull/10293 has standardised the colour scheme and format of modals. Yet some of the modals seem to have paddings around them while others don't. It seems that displaying a modal without padding leads to subsequent modals displayed to not have the padding as well.

Personally I think we should remove paddings for all modals for greater clarity.

**Steps to reproduce:**

1. Go to instructor courses page, try to delete one active course. The modal is as follows: 
![image](https://user-images.githubusercontent.com/5328196/87952654-a8184480-cadc-11ea-9930-27aa678c3715.png)
2. Go to instructor students page, for the default course (Sample Course 101), click enroll students. A modal is displayed as follows:
![image](https://user-images.githubusercontent.com/5328196/87952801-d007a800-cadc-11ea-9788-9f4890bfd3a7.png)
3. Now go back to instructor courses page and try to delete one active course again. For some reason the padding disappears:
![image](https://user-images.githubusercontent.com/5328196/87952866-e6adff00-cadc-11ea-9e77-0aa46117ef27.png)

**Comment by damithc** [comment]
I like the version without the padding myself.
