### ISSUE TITLE
Feedback submission propagates invalid question responses

### ISSUE THREAD

**Issue by madanalogy** [TEAMMATES/teammates#10397]
Distribute points (among recipients) successfully submits results that don't distribute all the points.

**Steps to reproduce**
Create a feedback session with a question on distribute points (among recipients) and distribute points in a manner that does not adhere to the question constraints (e.g. do not distribute all points).

**Expected behaviour**
Invalid submission does not get propagated to backend.

**Actual behaviour**
Invalid submission is propagated to backend.

**Additional info**
This is a followup from #10396 and #10299. Frontend validation is necessary since each option in a distribute points question is treated as a separate response that is sent to the backend api endpoint. This means that backend validation is difficult to achieve as the API treats each response independently from each other.

**Comment by wkurniawan07** [comment]
This is not `t-Angular`. This is a big story that cuts across both back-end and front-end.

**Comment by damithc** [comment]
What's the plan for this? Can't we at least disable the submit button in the form? That is, use front-end validation until we figure out how to also do the same on the backend?

**Comment by madanalogy** [comment]
> What's the plan for this? Can't we at least disable the submit button in the form? That is, use front-end validation until we figure out how to also do the same on the backend?

That's what I'm trying to do in #10398, but I had it on a lower priority as opposed to #10555. Let me know if that priority needs to change. Alternatively, if anyone with time on their hands is willing to pick this up, just let me know so I don't unnecessarily duplicate work :P

**Comment by damithc** [comment]
I think this is higher priority than #10555 because this is a feature not working as expected (i.e., a broken promise to the user) whereas copying to multiple courses is rare and can be done using V6 (or using V7 repeatedly). This one will affect everyone using this type of questions.
