### ISSUE TITLE
Inconsistent URL encoding 

### ISSUE THREAD

**Issue by jtankw3** [TEAMMATES/teammates#10400]
- **Environment**: `master` branch at commit 33d28f8400bc3d904910975dc3d71f0c1198fd52

**Steps to reproduce**
Preview as student in instructor feedback edit page with a session that has spacing in its name. 
_or_
Create `AppUrl` with session name that has spacing. 

**Expected behaviour**
Url spacing should be encoded `%20`

**Actual behaviour**
Spacing is encoded as `+`

**Additional info**
![url error](https://user-images.githubusercontent.com/31800234/88369005-b22e9180-cdc1-11ea-8411-935c32f55ae0.PNG)

**Comment by madanalogy** [comment]
Your screenshot shows that the session name is `First+Session` not `First Session`. The value `+` is purposely encoded in that manner as per https://github.com/TEAMMATES/teammates/pull/10313. I couldn't replicate your bug for sessions with spacing in their name in either the dev server or staging server.

Dev Server:
<img width="1269" alt="Screenshot 2020-07-24 at 3 49 02 PM" src="https://user-images.githubusercontent.com/42177597/88370759-44846480-cdc5-11ea-8fed-ac984f81301b.png">

Staging Server:
<img width="1506" alt="Screenshot 2020-07-24 at 3 45 36 PM" src="https://user-images.githubusercontent.com/42177597/88370784-4f3ef980-cdc5-11ea-9511-e8cc81893a20.png">

**Comment by jtankw3** [comment]
@madanalogy o that's weird. Actually the session I used is below: Not sure whats the difference between yours and mine.

![image](https://user-images.githubusercontent.com/31800234/88372992-9929de80-cdc9-11ea-8bc4-9d15909462ba.png)
