### ISSUE TITLE
Version shown in the footer doesn't match the actual version

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10407]
![image](https://user-images.githubusercontent.com/1673303/88459178-e8553980-cec5-11ea-95a8-50c82b88a107.png)

**Comment by wkurniawan07** [comment]
@damithc in the spirit of separate front-end and back-end, those two numbers are separately configured. The one in the footer is from `config.ts`.

**Comment by damithc** [comment]
I see. Got it.
