### ISSUE TITLE
Placeholder text not dim enough

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10409]
Placeholder text not dim enough (not much different to regular text)

![image](https://user-images.githubusercontent.com/1673303/88459904-12f5c100-cecb-11ea-816e-8183148b0958.png)

V6 for reference:
![image](https://user-images.githubusercontent.com/1673303/88459920-302a8f80-cecb-11ea-84e7-c967590e08d4.png)

**Comment by t-cheepeng** [comment]
![image](https://user-images.githubusercontent.com/28994607/88880344-112b5500-d25f-11ea-9989-2dc2eaf7ce6c.png)

@damithc  Something like this?

**Comment by damithc** [comment]
> @damithc Something like this?

Yes. BTW,  the `38 characters left` seems to have a tooltip. Is that intended?

**Comment by t-cheepeng** [comment]
> 38 characters left seems to have a tooltip

That tooltip is for the input field. I believe its intended. Or would placing it at the `Session Name` text be better?

**Comment by damithc** [comment]
> That tooltip is for the input field. I believe its intended. Or would placing it at the `Session Name` text be better?

Yes, to be consistent with other fields.
