### ISSUE TITLE
Instructor add session: Q2 visibility varies from V6

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10412]
Steps: Add a new session using the default session template
Problem: Q2 visibility description varies from v6

V6:
![image](https://user-images.githubusercontent.com/1673303/88460325-fe66f800-cecd-11ea-99ba-12e21282f971.png)

V7:
![image](https://user-images.githubusercontent.com/1673303/88460334-16d71280-cece-11ea-900f-747ca89e8183.png)

EDIT: applies to a few other questions in that session

**Comment by wkurniawan07** [comment]
The recipient type is "Giver". Showing "The recipient's team members" is a repetition over "Your team members".

**Comment by damithc** [comment]
> The recipient type is "Giver". Showing "The recipient's team members" is a repetition over "Your team members".

👍
