### ISSUE TITLE
Instructor add session: success message doesn't say long enough to read

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10410]
V6 success message for reference.
![image](https://user-images.githubusercontent.com/1673303/88460065-18074000-cecc-11ea-832b-65f6891264db.png)

In V7, this message doesn't stay long enough to read. Should we increase the delay of such messages site-wide? No harm keeping longer, right? Especially, if there is a way to dismiss the message manually (if needed).

**Comment by damithc** [comment]
> Currently they are all 5 seconds. I think it is long enough? Or maybe we can reset the autohide timer whenever the user hovers their cursor over the toast?

What's the downside of having a longer timeout? e.g., 10 seconds.

**Comment by ccyccyccy** [comment]
Thought it might be annoying to users. But I think it's fine being longer as well. Will change to 10 seconds

**Comment by damithc** [comment]
> Thought it might be annoying to users. But I think it's fine being longer as well. Will change to 10 seconds

If possible, add an `x` to dismiss.

BTW, what happens if the user performs another action during that period, which produces another toast message?

**Comment by ccyccyccy** [comment]
> BTW, what happens if the user performs another action during that period, which produces another toast message?

It will replace the old one

**Comment by damithc** [comment]
> > BTW, what happens if the user performs another action during that period, which produces another toast message?
> 
> It will replace the old one

OK, in that case no downside on that front either.
