### ISSUE TITLE
Instructor moderating submissions goes into student's home page

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10419]
V7: When instructor submits on behalf of a student, she is taken to instructors own 'student page'. This doesn't exactly make sense as instructor's student view is not involved in this task at all.
![image](https://user-images.githubusercontent.com/1673303/88462221-61f82200-cedc-11ea-9884-bd48773493fc.png)

V6: uses a stand-alone submission page
![image](https://user-images.githubusercontent.com/1673303/88462286-dc28a680-cedc-11ea-9a13-b09715c5498a.png)

**Comment by xpdavid** [comment]
Looks like a bug: We should use the moderation link to `/web/sessions/submission` not `/web/student/sessions/submission`

After fix it, nothing will be shown in the menu bar.

@damithc It is OK if we show nothing in the menu bar?

![image](https://user-images.githubusercontent.com/13977235/88463365-1e170580-ce67-11ea-9b5d-b2d5debd24d9.png)

**Comment by damithc** [comment]
> @damithc It is OK if we show nothing in the menu bar?

Yes, it should be fine that way.
