### ISSUE TITLE
visibility options vary for 'for nobody specific' path

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10414]
V6:
![image](https://user-images.githubusercontent.com/1673303/88461259-9ff14800-ced4-11ea-9954-ad21b08e99c6.png)

V7:
![image](https://user-images.githubusercontent.com/1673303/88461240-7afcd500-ced4-11ea-8cc1-70960f24776e.png)

UPDATE: applies to a few other feedback paths as well.

**Comment by wkurniawan07** [comment]
The recipient is "Nobody specific", which means any reference to "recipient" under "visibility options" is automatically redundant.

**Comment by damithc** [comment]
> The recipient is "Nobody specific", which means any reference to "recipient" under "visibility options" is automatically redundant.

👍
