### ISSUE TITLE
Submit responses to MSQ questions: multiple toast messages when restrictions violated

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10428]
When a restriction to an MSQ question is violated (example below), there are multiple green and red toast messages (followed by a modal).

![image](https://user-images.githubusercontent.com/1673303/88472694-39a60d00-cf48-11ea-8632-162bf8a62bf2.png)

Ideally, there shouldn't be any toasts as there is a modal later?

**Comment by madanalogy** [comment]
I think I could work on this in #10398

**Comment by wkurniawan07** [comment]
Since #10398 will not finish any time soon and this actually can cause some annoyance to user, I will take over this and finish this fast.
