### ISSUE TITLE
Instructor edit session: restrict MCQ/MSQ options to plain text only

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10420]
While it is in our todo list to support rich text for MCQ/MSQ question options, we need to figure out how to support it across the system e.g., results page, csv file etc. Until then, maybe better to restrict to plain text

![image](https://user-images.githubusercontent.com/1673303/88462503-59a0e680-cede-11ea-8a9f-85b70bcf3bf5.png)

**Comment by wkurniawan07** [comment]
It's already a working feature for MCQ, there's no reason to drop support for it. What is observed here is only a one-off occurrence.

**Comment by xpdavid** [comment]
Some context here: the feature is new in V7 and get merged before the question stats is migrated (and therefore that's why this is the only place).

**Comment by damithc** [comment]
What's our approach here? In most cases, the user means to enter plain text values. In those cases, the user doesn't expect to see html markup in the results. Perhaps we can strip markup from summary view and csv file completely?
![image](https://user-images.githubusercontent.com/1673303/88470557-5898a500-cf30-11ea-9528-57aba4ba143c.png)

An alternative is to let user enter a plain text option heading and rich text description (optional) but I don't think we have time to do that now.

**Comment by wkurniawan07** [comment]
> plain text option heading and rich text description (optional)

This is breaking down the option field to two which is a big, DB-modifying change.

**Comment by damithc** [comment]
> This is breaking down the option field to two which is a big, DB-modifying change.

Yes, unless we store it as one value but the first line is considered the heading (or use some other delimiter to separate the two). Even then, a lot of changes required I guess. Now may not be the time to do it.

**Comment by wkurniawan07** [comment]
> What's our approach here? In most cases, the user means to enter plain text values

The CSV should only display the text content. It's not anywhere near difficult to achieve it, just that this is a missed case.

**Comment by damithc** [comment]
> The CSV should only display the text content. It's not anywhere near difficult to achieve it, just that this is a missed case.

Sounds good. Let's do that then.

**Comment by wkurniawan07** [comment]
@damithc I was under the impression that V6 already supports rich text in MCQ options. I was mistaken here. With this in mind, I'd agree that we need to restrict to plain text for the time being.

**Comment by damithc** [comment]
> @damithc I was under the impression that V6 already supports rich text in MCQ options. I was mistaken here. With this in mind, I'd agree that we need to restrict to plain text for the time being.

Yes, I think it's the prudent thing for now, given the time pressure.
