### ISSUE TITLE
Submit responses: Show MSQ restrictions more prominently

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10427]
Current:
![image](https://user-images.githubusercontent.com/1673303/88472608-4118e680-cf47-11ea-9977-50761915ac80.png)

V6:
![image](https://user-images.githubusercontent.com/1673303/88472615-5db51e80-cf47-11ea-8e7f-f256c43155d9.png)

V6 is slightly better in terms of layout. 
Suggestion: Also use different colors to draw attention to the restrictions.

**Comment by ccyccyccy** [comment]
@damithc Something like this?

 ![image](https://user-images.githubusercontent.com/32454748/88527790-51f15700-d030-11ea-9b89-aef48cd6ffbc.png)

**Comment by damithc** [comment]
Yes, that works. Remember to be consistent if there are other places where we have to show this kind of restrictions.
`cannot` -> `should not`? Also, remove the `:`. In fact, how about this?
>Choose **no more than 3** options
>Choose **at least 2** options

**Comment by ccyccyccy** [comment]
> Choose **no more than 3** options
> Choose **at least 2** options

Yup seems good.
