### ISSUE TITLE
csv download: preserve line breaks in text comments

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10424]
Current: 
![image](https://user-images.githubusercontent.com/1673303/88471380-5ee04e80-cf3b-11ea-93d9-e58417835176.png)

It would be nice to replace this with an actual line break.

For reference, V6 doesn't preserve line breaks either, but it doesn't show this special char either.

**Comment by wkurniawan07** [comment]
@damithc this is not a response comment. A response comment won't belong in the same row where "No Response" belongs. Is this MCQ choice which is a rich text?

**Comment by damithc** [comment]
> @damithc this is not a response comment. A response comment won't belong in the same ~row~ column where "No Response" belongs. Is this MCQ choice which is a rich text?

Yes, looks like it.
