### ISSUE TITLE
Difference in visibility info

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10439]
V7: 
![image](https://user-images.githubusercontent.com/1673303/88475576-e9d53f00-cf63-11ea-938b-41573273ead1.png)

V6:
![image](https://user-images.githubusercontent.com/1673303/88475579-f5c10100-cf63-11ea-9f75-aa0098cb9326.png)

**Comment by wkurniawan07** [comment]
Slight redundancy because "The receiving instructor" can obviously see "the name of the recipient", but not inaccurate otherwise.
