### ISSUE TITLE
Submit MCQ responses: tweak layout

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10430]
Current:
![image](https://user-images.githubusercontent.com/1673303/88473708-d79ed500-cf52-11ea-9c62-078de9a25796.png)

Suggestion: 
* Indent options under each student so that the parent-child relationship is clearer
* The gap between two student should be wider than the gap between options

**Comment by ccyccyccy** [comment]
> The gap between two student should be wider than the gap between options

The gap is due to the `<p>` tag from the rich text editor. Since we are disabling it, i don't think this is an issue.

> Indent options under each student so that the parent-child relationship is clearer

@damithc How about we indent everything as well?

![image](https://user-images.githubusercontent.com/32454748/88786934-b691ea80-d1c5-11ea-92de-b34b2e8a60fd.png)

**Comment by damithc** [comment]
> @damithc How about we indent everything as well?

@ccyccyccy not sure what you mean. Can show a side-by-side comparison?

**Comment by ccyccyccy** [comment]
@damithc Here are some side-by-side comparisons. Basically all the options under a recipient will be indented.

![Untitled](https://user-images.githubusercontent.com/32454748/88791679-b21d0000-d1cc-11ea-8fd4-c055cecce87e.png)

**Comment by damithc** [comment]
The right hand side version is better because it is a better representation of the hierarchy of elements.
