### ISSUE TITLE
Instructor view results: Use fixed-width floating numbers

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10433]
V7:
![image](https://user-images.githubusercontent.com/1673303/88474201-de2f4b80-cf56-11ea-83e6-464edc2e75c3.png)

V6:
![image](https://user-images.githubusercontent.com/1673303/88474221-f1421b80-cf56-11ea-8728-fa992bca29bd.png)

**Comment by nk183** [comment]
@damithc ,is it still open??

**Comment by moziliar** [comment]
@nk183 I am not working on this issue anymore.

**Comment by daniel-nuon** [comment]
@damithc What are the steps to reproduce this issue? Unless I'm working the UI incorrectly, I'm not finding the "Per Recipient Statistic" in the instructor view results page.

**Comment by damithc** [comment]
> @damithc What are the steps to reproduce this issue? Unless I'm working the UI incorrectly, I'm not finding the "Per Recipient Statistic" in the instructor view results page.

@daniel-nuon From what I can see, the screenshot is from an MCQ question that has weights attached to each option.

**Comment by swood049** [comment]
I believe that you may close this issue. After a little investigating, I have found that this is currently as described (see photo).

![image](https://user-images.githubusercontent.com/38500060/97867523-09ef6980-1cdc-11eb-9e13-86db4ad8f638.png)

**Comment by sofefr** [comment]
Does this still need to be worked on?

**Comment by anshuman-dev** [comment]
Can i take this issue? or anyone is working on it already?

**Comment by moziliar** [comment]
@anshuman-dev feel free to work on it.
