### ISSUE TITLE
distribute points among instructors: recipient count in not applicable

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10438]
V7:
![image](https://user-images.githubusercontent.com/1673303/88475532-48e68400-cf63-11ea-8264-515445cdca51.png)

Seems to be a new feature added to V7. In this case, this setting is not applicable because points should be distributed among _all_ recipients.

**Comment by wkurniawan07** [comment]
This is not a new feature. This is a generic feature for all question types, if the recipient type can potentially result in a large list of participants (specifically: students, teams, instructors).

**Comment by damithc** [comment]
> This is not a new feature. This is a generic feature for all question types, if the recipient type can potentially result in a large list of participants (specifically: students, teams, instructors).

Correct. Didn't realize it.
