### ISSUE TITLE
Submit responses to team contribution questions: tweak layout, add tooltip

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10449]
V7: ![image](https://user-images.githubusercontent.com/1673303/88478967-b48a1a80-cf7e-11ea-9c3c-c96de1ae2680.png)

V6:
![image](https://user-images.githubusercontent.com/1673303/88478982-c966ae00-cf7e-11ea-930d-a85098d81a14.png)

Suggestions:

1. move `evaluee/recipient` closer to dropdowns (also missing in V6)
1. add tooltip to the above
1. increase gap between students

**Comment by ccyccyccy** [comment]
Regarding the tooltip, I think there's a tooltip there already, just that it is not underlined due to https://github.com/TEAMMATES/teammates/issues/10522
