### ISSUE TITLE
View responses of rubric questions: slight difference in summary stats

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10454]
V7:
![image](https://user-images.githubusercontent.com/1673303/88479783-3d578500-cf84-11ea-84ac-93ff3110bca9.png)

V6:
![image](https://user-images.githubusercontent.com/1673303/88479775-29ac1e80-cf84-11ea-9e80-34a4eac636c6.png)

Difference possibly due to rounding off?

**Comment by wkurniawan07** [comment]
13% is right because it is 1 response out of 8, 1/8 = 12.5%, rounded up to 13%.

I would even argue that this should not be rounded to the nearest integer, but rather to the 2 d.p. just like the average.

**Comment by damithc** [comment]
> 13% is right because it is 1 response out of 8, 1/8 = 12.5%, rounded up to 13%.

Not sure how it got rounded to 12% earlier (may be rounding by different languages Java vs JS?). Although 12% adds up to 100% while 13% adds up to 101%.
The previous library was probably using the [odd-even rule of rounding](https://blogs.sas.com/content/iml/2019/11/11/round-to-even.html#:~:text=This%20familiar%20rule%20is%20used,ODD%2C%20round%20away%20from%20zero.). This one is an example of the advantage of that rule.

> I would even argue that this should not be rounded to the nearest integer, but rather to the 2 d.p. just like the average.

100 is a wide range. 1dp should be enough.
