### ISSUE TITLE
Submit response: improve style of visibility info

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10450]
Current:
![image](https://user-images.githubusercontent.com/1673303/88479070-527de500-cf7f-11ea-8046-94f393202798.png)

Suggestions:
1. Increase top margin
1. Put inside a headless borderless box with a very light grey background so that it shows up as a block element instead of blending in with the question body.

**Comment by t-cheepeng** [comment]
@damithc  does this look fine?

![image](https://user-images.githubusercontent.com/28994607/88769569-28126e80-d1af-11ea-8276-fb0d8d625ad9.png)

**Comment by damithc** [comment]
> @damithc does this look fine?

Yes, looks good.
