### ISSUE TITLE
Instructor courses page: sort course list by descending creation time

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10467]
Sort the course list by creation time by default, in descending order, so that newly created courses appear at the top of the list whenever a new course is added.

**Comment by ccyccyccy** [comment]
The active course is already sorted by creation time by default in descending order.

@damithc Do you want both archived course and deleted courses to be sorted similarly as well?
I think it's better for deleted courses to be sorted by deletion date though?

**Comment by damithc** [comment]
> The active course is already sorted by creation time by default in descending order.
> 
> @damithc Do you want both archived course and deleted courses to be sorted similarly as well?
> I think it's better for deleted courses to be sorted by deletion date though?

@ccyccyccy Turns out this is usually the case but not when you add a new course (that's the time you need this feature the most). After adding a new course, the table reloads in some other sorting order.

**Comment by ccyccyccy** [comment]
> @ccyccyccy Turns out this is usually the case but not when you add a new course (that's the time you need this feature the most). After adding a new course, the table reloads in some other sorting order.
Ok will fix that

@damithc What about deleted and archived courses?

**Comment by damithc** [comment]
> @damithc What about deleted and archived courses?

I wouldn't mind not sorting them by default as long as the tables are sortable by the user. As they are rarely used, it might be a waste of cpu cycles to sort them every time the page loads.

**Comment by wkurniawan07** [comment]
> It might be a waste of cpu cycles to sort them every time the page loads.

Sorting is negligible in terms of load unless we're talking about thousands/millions of items.
