### ISSUE TITLE
V6 instructor join link incompatible with V7

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10470]
Problems:
1. After switching to V7, instructor join links sent by V6 will no longer work. This is going to affect those who had accounts created just prior to the switchover.
2. Even those who have joined already, sometimes dig up the old join link and click on it simply as a way to reach TEAMMATES. Will that continue to work?

Is it possible to bake in something into V7 to take care of the above, at least fail gracefully and guide user to v7?

**Comment by madanalogy** [comment]
If I'm not wrong the only reason the v6 join links won't work is because we added institute validation in v7 (see #4854)

> Is it possible to bake in something into V7 to take care of the above, at least fail gracefully and guide user to v7?

I think an informational message should be sufficient, let them know that their URL is no longer valid and that they should request for a new instructor account via the v7 join form. Any other alternative would make redundant the institute validation in my opinion.

**Comment by damithc** [comment]
> If I'm not wrong the only reason the v6 join links won't work is because we added institute validation in v7

The URL itself is different. V6 `https://teammatesv4.appspot.com/page/instructorCourseJoin?key=...`

**Comment by madanalogy** [comment]
> The URL itself is different. V6 `https://teammatesv4.appspot.com/page/instructorCourseJoin?key=...`

We might need to manually route `/page/instructorCourseJoin` to `/web/join` I think. @xpdavid @wkurniawan07 any alternative suggestions? I'm not sure if that's even possible, I'm not very familiar with routing in angular.

**Comment by wkurniawan07** [comment]
Routing is not an issue. As I mentioned before any link sent in V6 via email will work. The problem remains with the institute validation.

**Comment by madanalogy** [comment]
> Routing is not an issue. As I mentioned before any link sent in V6 via email will work. The problem remains with the institute validation.

The solution for this is to get them to request for a new link, but they first need to know where to go, so I will just add a route from the old join link to the current join endpoint (which should then trigger the notice to get a new join link)

**Comment by damithc** [comment]
> Right now it won't work like that. Do you consider it a "feature" or a bug that needs to be fixed?

This was the behavior in V6. 
![image](https://user-images.githubusercontent.com/1673303/88612374-a7277a00-d0bd-11ea-811d-2653d6014a48.png)

Good if we can continue to have something similar in V7. It's lost feature or a regression, whichever way we choose to look at it.

**Comment by damithc** [comment]
> Good if we can continue to have something similar in V7. It's lost feature or a regression, whichever way we choose to look at it.

Having said that, the need for this 'feature' is less in V7 because V7 sends a regular link to users when they join as an instructor. We didn't have that link in V6 counterpart email.
![image](https://user-images.githubusercontent.com/1673303/88612875-c07cf600-d0be-11ea-9597-37c357d96988.png)

Still, it's a nice-to-have feature if the user clicks on the join link rather than the above link.
