### ISSUE TITLE
Instructor/admin search/help page: Search text is highlighted yellow in V6 but not in V7

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#10480]

**Comment by egorovak** [comment]
@wkurniawan07 Hi, is this issue still active/relevant?

**Comment by tau-bar** [comment]
I'd like to work on this issue. It seems to still be existing currently.

**Comment by fsgmhoward** [comment]
@tau-bar  Sure. Please go ahead.
