### ISSUE TITLE
Non-secure connection problem

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10483]
A user (on v6) is reporting this problem. Apparently, tried with different browsers but no luck.
![image](https://user-images.githubusercontent.com/1673303/88614126-a7297900-d0c1-11ea-942d-7b84fbfde9fc.png)

**Comment by madanalogy** [comment]
You need to remove the `www` if you want to connect via `https` (i.e. `www.teammatesv4.appspot.com` only serves over `http`). I don't know if this is a problem with GAE/appspot domain configuration but I had a similar problem on my own site and had to configure a dns redirect for `www` prefixes

**Comment by damithc** [comment]
> You need to remove the `www` if you want to connect via `https` (i.e. `www.teammatesv4.appspot.com` only serves over `http`). I don't know if this is a problem with GAE/appspot domain configuration (it's actually a SSL certificate configuration problem iirc) but I had a similar issue on my own site and had to configure a dns redirect for `www` prefixes

Thanks @madanalogy That indeed seems to be the problem. `teammatesv4` is the sub-domain already. There should not be a `www`. I wonder how it got added to the URL though. Unlikely the user typed it in.

**Comment by wkurniawan07** [comment]
Closing as this is a user error.
