### ISSUE TITLE
Update site data for V7

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#10498]
- ~Submissions count and rate of addition~ done
- ~Testimonials (if there are any new ones)~
- Universities/Institutes list (to defer)
- ~Documentation that still refer to old page structure (i.e. `*.jsp`)~
- ~Team members list~ done

**Comment by wkurniawan07** [comment]
@damithc need your help for the first two. The new institutes list may be long because it was last updated Jun 2019; can send the list to me via email.

**Comment by damithc** [comment]
> * Submissions count and rate of addition

20 million, increasing about 5 million per year

> * Testimonials (if there are any new ones)

Let's go with the existing one. I stopped keeping records a while back. Will take a while to dig through emails to find them.

> * Universities/Institutes list

I do have a list generated by a script, but someone needs to clean it up (a lot of eyeballing needed). Go with the existing one?

**Comment by damithc** [comment]
> @damithc need your help for the first two. The new institutes list may be long because it was last updated ~Jun~ May 2019; can send the list to me via email.

I'll email it later today
