### ISSUE TITLE
Instructor courses page: some items don't show spinners

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10508]
Current: The courses page has three tables that seem to load independently of each other. However, only one spinner is shown.
![image](https://user-images.githubusercontent.com/1673303/89115366-27811d00-d4ba-11ea-8bcb-2709510a47be.png)

Suggestion: Add a spinner for each.

**Comment by wkurniawan07** [comment]
It's not the same problem. Archived courses and deleted courses won't be shown at all if there are none of them, as opposed to the active courses page which will show something like "You do not have any active courses" if there is none, so the spinner might end up into nothingness which is weird.

**Comment by damithc** [comment]
> It's not the same problem. Archived courses and deleted courses won't be shown at all if there are none of them, as opposed to the active courses page which will show something like "You do not have any active courses" if there is none, so the spinner might end up into nothingness which is weird.

I think empty tables should be shown even if there are no deleted/archived items. That's more consistent with our policy that even disabled items are shown to let users know where things are.

**Comment by wkurniawan07** [comment]
> I think empty tables should be shown even if there are no deleted/archived items.

I'll just leave a note that V6 didn't do this.

**Comment by rexong** [comment]
Hi, can I start a PR for this?

**Comment by domlimm** [comment]
@rexong Sure, feel free to submit a PR!
