### ISSUE TITLE
Modal shows a scrollbar

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10511]
![image](https://user-images.githubusercontent.com/1673303/89115525-b3e00f80-d4bb-11ea-83af-9eb9439ecdc9.png)

**Comment by wkurniawan07** [comment]
Which browser and OS is this?

**Comment by damithc** [comment]
> Which browser and OS is this?

Chrome and Win10

**Comment by xpdavid** [comment]
I can reproduce the issue actually on MacOS (10.15.6 (19G73)) + Version 84.0.4147.105 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/13977235/89600165-31868100-d816-11ea-86d8-2febfdd30d7d.png)
