### ISSUE TITLE
Preview as instructor link not working

### ISSUE THREAD

**Issue by jtankw3** [TEAMMATES/teammates#10517]
- **Environment**: `master` branch at commit 6b91a5781369b0b298c8389e4d17a0fb849a88ac

**Steps to reproduce**
1) Edit any feedback session 
2) Click `Preview as instructor` button

**Expected behaviour**
Opens new submission page window

**Actual behaviour**
Nothing happens

**Comment by damithc** [comment]
Confirmed.
