### ISSUE TITLE
Features page: reduce indentation

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10516]
Reduce indentation here?
![image](https://user-images.githubusercontent.com/1673303/89115850-9ad95d80-d4bf-11ea-8a38-1b1bf555f7da.png)

Also, maybe move the 'raised edge' a little bit to the left, like this?
![image](https://user-images.githubusercontent.com/1673303/89115886-0e7b6a80-d4c0-11ea-8ed1-d248f8ea8a3f.png)

**Comment by wkurniawan07** [comment]
Leaving a note here that both are V6 problems.

**Comment by moziliar** [comment]
I'd like to fix this for a start.
