### ISSUE TITLE
Instructor results page: improve buttons

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10513]
![image](https://user-images.githubusercontent.com/1673303/89115628-26052400-d4bd-11ea-9cb7-ab30d160b237.png)

Suggestions:
* Reduce button width
* Add icons for each button

**Comment by wkurniawan07** [comment]
> Add icons for each button

V6 doesn't have icons either. Which icons can be used here?

**Comment by damithc** [comment]
> V6 doesn't have icons either. Which icons can be used here?

Can pick something suitable from fontawesome.
I set it as p.veryLow because no need to include in v7
