### ISSUE TITLE
Instructor home page: delete confirmation should be in danger style

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10526]
V7:
![image](https://user-images.githubusercontent.com/1673303/89126512-a60ca780-d518-11ea-9f1f-0eb1a7018e4d.png)

V6:
![image](https://user-images.githubusercontent.com/1673303/89126521-b6bd1d80-d518-11ea-9076-9f2a531bc044.png)

However, this is not a irreversible operation. It's OK to show a warning if that is the policy we are following i.e., use _danger_ only if the operation is irreversible

BTW, the new dialog seems to have less info than V6

**Comment by ccyccyccy** [comment]
> However, this is not a irreversible operation. It's OK to show a warning if that is the policy we are following i.e., use _danger_ only if the operation is irreversible

Seems like this is the criteria for modals. Functionally speaking, deleting a session is no different from archiving a course.

> BTW, the new dialog seems to have less info than V6

You mean the "action can be reverted" part? I think the toast right after deleting it conveys that information already.
![image](https://user-images.githubusercontent.com/32454748/89163829-ce43e700-d5a8-11ea-971d-1b3c2508d68c.png)

**Comment by damithc** [comment]
> You mean the "action can be reverted" part? I think the toast right after deleting it conveys that information already.

This info should be given _before_ the action is performed, as it is relevant to the decision at hand.
