### ISSUE TITLE
Edit session button should open the sessions page in edit mode

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10523]
When the user clicks on this button, the next page should show the session form already in edit mode.
![image](https://user-images.githubusercontent.com/1673303/89126115-c4bd6f00-d515-11ea-9c74-b9f6aa0f500e.png)

Current: the user has to click on the `edit` button again to go into the edit mode.

**Comment by prakash-bidgely** [comment]
@damithc @wkurniawan07 Can I work on this issue?

**Comment by damithc** [comment]
@prakash-bidgely sure.

**Comment by nk183** [comment]
@damithc @wkurniawan07 if it is still open can I work on this issue?

**Comment by lhsrebel72** [comment]
@damithc  I was taking a look at this and on the edit page there are 4-5 different panel(Questions) and they each have their own edit button. Should these all be turned on from the beginning and if so, what is the point of the individual Edit buttons on each panel? Should they always be available to edit?

**Comment by damithc** [comment]
> @damithc I was taking a look at this and on the edit page there are 4-5 different panel(Questions) and they each have their own edit button. Should these all be turned on from the beginning and if so, what is the point of the individual Edit buttons on each panel? Should they always be available to edit?

Only the top panel containing the session info. Does not apply to individual questions.
