### ISSUE TITLE
Instructor home page: show underline for tooltipped cells

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10522]
Not sure if this is captured elsewhere or WIP already.

![image](https://user-images.githubusercontent.com/1673303/89126031-17e2f200-d515-11ea-885a-70cf292dfb50.png)

V6:
![image](https://user-images.githubusercontent.com/1673303/89126038-2d581c00-d515-11ea-9646-c566515526a6.png)

**Comment by ccyccyccy** [comment]
It is supposed to be working already. Just tested on master branch for firefox and chrome. @damithc Can I know the browser and the OS used?

**Comment by damithc** [comment]
> It is supposed to be working already. Just tested on master branch for firefox and chrome. @damithc Can I know the browser and the OS used?

When was it merged? Maybe it was merged after I deployed the version I was testing.

**Comment by wkurniawan07** [comment]
This was merged long ago (~2 weeks). I don't think it's an exaggeration to say that both me and @ccyccyccy are surprised that this is an issue now.

**Comment by damithc** [comment]
I'm seeing the problem in both firefox and chrome. Same for the issue with modals having scrollbars. I wonder if it is something to do with my deployment. These are the commands I use to deploy:
```
gradlew generateTypes
npm run build
gradlew appengineDeployAll
```
Am I missing anything?

**Comment by wkurniawan07** [comment]
Modals having scrollbars is an entirely different problem

**Comment by damithc** [comment]
The tooltip indicators appear in my dev server but not in the live server. Perhaps you can deploy to staging serve to see if you can reproduce the same?
Howevever, the modal scrollbar problem appears in both servers.

**Comment by wkurniawan07** [comment]
@damithc let's not bring up the modal's scrollbar problem here. There's an entire issue dedicated for that.

**Comment by wkurniawan07** [comment]
Found the issue. As it turns out, production build strips all `ng-reflect-*` attributes from all HTML elements.
@ccyccyccy we may need to fall back to the previous method of adding classes to decorate the items to be tooltip-ed, until we have a better solution.

**Comment by ccyccyccy** [comment]
> `ng-reflect`

Yup I don't see any other way. Will apply the class to all the container elements.
