### ISSUE TITLE
Instructor preview session as student: incorrect state shown while loading

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10524]
![image](https://user-images.githubusercontent.com/1673303/89126355-a6587300-d517-11ea-8819-4516a1f311ab.png)

After clicking this button, the next page shows incorrect intermediate state while waiting for the final state.

**Comment by madanalogy** [comment]
@damithc Do you happen to have a screenshot of what the intermediate state is?

**Comment by damithc** [comment]
> @damithc Do you happen to have a screenshot of what the intermediate state is?

Typically, it's a message stating 'no courses/sessions/questions to see'. In this case, `There are no questions for you to answer here`.
