### ISSUE TITLE
Instructor view results: some empty panels missing

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10534]
For this setting,
![image](https://user-images.githubusercontent.com/1673303/89128114-e161a300-d525-11ea-9346-70d5f8bc78ef.png)

V7 is missing empty panels such as these:
![image](https://user-images.githubusercontent.com/1673303/89128128-f50d0980-d525-11ea-9c0b-639939783f13.png)

**Comment by wkurniawan07** [comment]
Those are not missing. They however have the same primary header as when there are existing responses.

**Comment by damithc** [comment]
> Those are not missing. They however have the same primary header as when there are existing responses.

So, a bug in V6?

**Comment by wkurniawan07** [comment]
It depends. If "participant with no responses given should be in light grey panel" is a design requirement, then it's a something to improve in V7.

**Comment by damithc** [comment]
> It depends. If "participant with no responses given should be in light grey panel" is a design requirement, then it's a something to improve in V7.

It's better to include. Instructors often want to know who didn't give/receive responses as those indicate problem cases, plus the 'show missing responses' setting is enabled.

**Comment by wkurniawan07** [comment]
> It's better to include

The problem is misunderstood. It's not whether it's included or not; the "show missing responses" setting is respected. It's just that the panel is of the same color.

**Comment by damithc** [comment]
V7: 
![image](https://user-images.githubusercontent.com/1673303/89128842-0c022a80-d52b-11ea-963c-b2d3e6ab05b1.png)

V6:
![image](https://user-images.githubusercontent.com/1673303/89128826-f7be2d80-d52a-11ea-893e-0d298e622171.png)

The 4th primary panel differs, but that's due to a different V6 bug. In addition, V6 seems to have additional grey panels.

And yes, it's good to show empty panels in a different color to save the user the trouble of opening them.

**Comment by wkurniawan07** [comment]
That screenshot to me looks like serious issues in V6

**Comment by damithc** [comment]
> That screenshot to me looks like serious issues in V6

Yes, a bug, possibly related to the other bug i.e., it gets team names mixed up when a person is both an instructor and a student. I suspect it only crops up when a session contains a question targeting instructors, which is rare. In the below, `Team 1` should be `Instructors` instead.

![image](https://user-images.githubusercontent.com/1673303/89143971-fa4a7280-d57e-11ea-8648-2e6f041048d8.png)

**Comment by wkurniawan07** [comment]
Then those are V6 problems that by now we should be relieved because they are fixed?

**Comment by damithc** [comment]
> Then those are V6 problems that by now we should be relieved because they are fixed?

Yup. That seems to be the case.
