### ISSUE TITLE
Instructor moderate responses: incorrect state shown during loading

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10535]
After clicking this button, the next page shows an incorrect state while loading data.
![image](https://user-images.githubusercontent.com/1673303/89128341-9b0d4380-d527-11ea-9e12-b6eb6a819e07.png)

**Comment by madanalogy** [comment]
@damithc Do you happen to have a screenshot of what the intermediate state is?

**Comment by damithc** [comment]
> @damithc Do you happen to have a screenshot of what the intermediate state is?

Similar to #10524

**Comment by wkurniawan07** [comment]
@madanalogy don't be fixated on what's the wrong intermediate state is. The gist of the problem is you need to add loading indicator.

**Comment by madanalogy** [comment]
> @madanalogy don't be fixated on what's the wrong intermediate state is. The gist of the problem is you need to add loading indicator.

Yea I know that, just wondering where to put the indicator haha
