### ISSUE TITLE
Instructor homepage: buttons overflow

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10545]
![image](https://user-images.githubusercontent.com/1673303/89199775-a3c25000-d5e1-11ea-9e7a-4ad91423be9b.png)

Probably due to recent margin/padding adjustments? The button text seem bigger than normal text and there is too much space between buttons too?

**Comment by wkurniawan07** [comment]
> The button text seem bigger than normal text

Definitely not the case. Upon inspection you'll find that both have the same font sizes.

> there is too much space between buttons too

This one's probably true.
