### ISSUE TITLE
Reduce the number of link styles

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10561]
![image](https://user-images.githubusercontent.com/1673303/89714107-f24f6000-d9ce-11ea-8807-8f83006dab97.png)

If cannot use one style for _all_ links, we can use one style for dark backgrounds and one for light. This one seems to be a third style.

**Comment by sofefr** [comment]
Does this issue still need to be worked on?

**Comment by damithc** [comment]
The text in the screenshot doesn't exist anymore. Closing for now. Will reopen if I spot a similar problem again.
