### ISSUE TITLE
Instructor courses page: spinner looks jagged

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10560]
The spinner that appears when clicking on this `show` seems jagged (see the leading edge of the spinner) compared to other pages. 
![image](https://user-images.githubusercontent.com/1673303/89713949-cd0e2200-d9cd-11ea-8bab-b11ee1814117.png)

![CBB152B4-9BAE-4CF7-8774-CA1AC2F571E3](https://user-images.githubusercontent.com/1673303/89714051-8a991500-d9ce-11ea-9441-2b0365991163.GIF)

Perhaps we are still using the animated gif spinner here instead of the boostrap one?

**Comment by wkurniawan07** [comment]
![0OEElkiCcv](https://user-images.githubusercontent.com/7261051/89730863-3301b480-da75-11ea-9acb-eead408c0818.gif)

Not for me.

**Comment by wkurniawan07** [comment]
Closing as:
- The reproduction scenario/condition is not well-defined
- "Perhaps we are still using the animated gif spinner here instead of the bootstrap one?" is false
