### ISSUE TITLE
Admin bulk-adding instructors: allow separation by tabs

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10568]
![image](https://user-images.githubusercontent.com/1673303/89797578-ab43a500-db5d-11ea-8a9c-6a14e04b5a31.png)

This button doesn't seem to do anything.

**Comment by wkurniawan07** [comment]
What do you mean not do anything? Not even adding the new instructors to the list to be added?

**Comment by damithc** [comment]
> What do you mean not do anything? Not even adding the new instructors to the list to be added?

Yes, no effect. But the other form works.

**Comment by wkurniawan07** [comment]
This is not reproducible locally. This page is even guarded by a full suite of tests - back-end unit, front-end unit, and E2E. Does the console mention anything?

**Comment by damithc** [comment]
> This is not reproducible locally. This page is even guarded by a full suite of tests - back-end unit, front-end unit, and E2E. Does the console mention anything?

I thing I figured out the problem. This version doesn't seem to work when the values are separated by tabs (which is the case when copy-pasting values from a spreadsheet). It works if I use `|` to separate the values.

**Comment by wkurniawan07** [comment]
> This version doesn't seem to work when the values are separated by tabs (which is the case when copy-pasting values from a spreadsheet). It works if I use `|` to separate the values.

It is indeed the case. Is it important to allow separation by tabs?

**Comment by damithc** [comment]
> It is indeed the case. Is it important to allow separation by tabs?

Not urgent. I can write an excel formula to get the values in |-separated format.
