### ISSUE TITLE
Changing feedback path resets visibility

### ISSUE THREAD

**Issue by ccyccyccy** [TEAMMATES/teammates#10579]
Not sure if intended?

![Screen Recording 2020-08-12 at 7 29 47 PM](https://user-images.githubusercontent.com/32454748/90010423-65f4b400-dcd2-11ea-8dcf-5b16bff4e918.gif)

**Comment by wkurniawan07** [comment]
I do believe the feedback path and the visibility option are tightly related.

**Comment by damithc** [comment]
> I do believe the feedback path and the visibility option are tightly related.

I guess it is OK but is there a need to reset? This could cause extra work for the user and in the worst case the user might not notice the resetting and end up with the wrong outcome. If there is no technical obstacle, better to retain the visibility?

**Comment by wkurniawan07** [comment]
> I guess it is OK but is there a need to reset

There is. When you changed from student giver to instructor giver, for example, "Giver's team members" stop making sense as an option under visibility options.

> in the worst case the user might not notice the resetting and end up with the wrong outcome

I don't think it's likely given that the configuration places are next to each other.

**Comment by xpdavid** [comment]
> If there is no technical obstacle, better to retain the visibility?

There is and that is why I just reset it when I migrate it. V6 tries to do the guess but causes many inconsistencies. It is worth exploring to find a way to ensure the consistency and make it smarter.

There are a lot of rules to follow:  https://github.com/TEAMMATES/teammates/blob/master/src/web/services/visibility-state-machine.ts#L54

**Comment by damithc** [comment]
Noted. Let's keep it this way for the time being.

**Comment by wkurniawan07** [comment]
Closing as this is not a priority right now
