### ISSUE TITLE
Fix styling for error report modal

### ISSUE THREAD

**Issue by jtankw3** [TEAMMATES/teammates#10573]
- Environment: `V7.0.2`

Too little spacing for title and `Send Error Report` button.
 
![error report](https://user-images.githubusercontent.com/31800234/89979919-62960400-dca3-11ea-9722-0b0c7561999b.PNG)

**Comment by hamza67100** [comment]
Hello, which page can show this modal ? I'm sorry I can't find my way in every files of this project :')

**Comment by jtankw3** [comment]
Hi @hamza67100, the relevant component for this modal is the `ErrorReportComponent` which can be found at https://github.com/TEAMMATES/teammates/tree/master/src/web/app/components/error-report

You can search around for pages that use `ErrorReportComponent`, such as the `UserJoinPageComponent`.

**Comment by hamza67100** [comment]
Thank you for your fast answer I'll do my best to fix it :)
