### ISSUE TITLE
New MCQ questions initializes with a space for first 2 questions

### ISSUE THREAD

**Issue by ccyccyccy** [TEAMMATES/teammates#10577]
![image](https://user-images.githubusercontent.com/32454748/90008429-e3b6c080-dcce-11ea-9ff1-666dc60b45aa.png)

**Comment by wkurniawan07** [comment]
This is perhaps because MCQ/MSQ questions are initialized with two `' '` as default options. What happened up there is the first two options that is propagated to the DB has leading space.

@xpdavid I forgot if I have asked this before. Is there a reason to use one space instead of purely empty string as the default options?

**Comment by ccyccyccy** [comment]
> This is perhaps because MCQ/MSQ questions are initialized with two `' '` as default options.

It doesn't happen for MSQs.

> What happened up there is the first two options that is propagated to the DB has leading space.

I don't think anything is propagated to the DB when the user initially adds the question (by clicking the "Add New Question" -> "MCQ" button). It only send a network request after the user edits and saves the new question.

**Comment by wkurniawan07** [comment]
> It only send a network request after the user edits and saves the new question.

What I meant was after initially adding the two questions, user simply writes on top of the default option without realizing that it is one space character instead of empty string.

**Comment by wkurniawan07** [comment]
> It doesn't happen for MSQs.

https://github.com/TEAMMATES/teammates/blob/8125949fc1d2372648f520e4afb495deeef29f1f/src/web/app/components/question-types/question-edit-details-form/mcq-question-edit-details-form.component.html#L33

https://github.com/TEAMMATES/teammates/blob/8125949fc1d2372648f520e4afb495deeef29f1f/src/web/app/components/question-types/question-edit-details-form/msq-question-edit-details-form.component.html#L31

I don't know whether it is a hack or it is the right way to do it, but MCQ and MSQ getting different treatment here is a cause of concern.

**Comment by xpdavid** [comment]
> Is there a reason to use one space instead of purely empty string as the default options

I don't think so. It was added in https://github.com/TEAMMATES/teammates/pull/9628/files#diff-9f6562ce376340075dddda3782a7255bR333

V6 use empty string though.

**Comment by xpdavid** [comment]
> I don't know whether it is a hack or it is the right way to do it, but MCQ and MSQ getting different treatment here is a cause of concern.

Yeah, `.trim()` should be here.

**Comment by wkurniawan07** [comment]
> Yeah, `.trim()` should be here.

On the contrary, I don't think `trim()` should be there. Instead the models should be initialized with empty string instead of one space, if there's no reason to do the latter.

**Comment by damithc** [comment]
> On the contrary, I don't think `trim()` should be there. Instead the models should be initialized with empty string instead of one space, if there's no reason to do the latter.

Yes, the space should not be there in the first place.

In addition, we can still consider trimming all textbox inputs as users can leave leading/trailing spaces by mistake.

**Comment by xpdavid** [comment]
Sorry about the confusion. I mean "`.trim()` should not be there" :P
