### ISSUE TITLE
Update error message for incorrect email format

### ISSUE THREAD

**Issue by t-cheepeng** [TEAMMATES/teammates#10581]
- **Environment**: V7.0.2

![image](https://user-images.githubusercontent.com/28994607/90011230-ce906080-dcd3-11ea-8b32-14e47fc6c555.png)
Error message for incorrect email should be updated to include check for top level domain

**Comment by hamza67100** [comment]
Hello, I'm new and I want to know what message should be put in place of the current message? :)
