### ISSUE TITLE
No loading indicator when copying sessions

### ISSUE THREAD

**Issue by madanalogy** [TEAMMATES/teammates#10586]
No loading indicator when copying session from instructor home page or instructor sessions page. The page displays as normal and users can click on other items while the copying is happening.

#10543 only adds a loading indicator to the session edit page

**Comment by ccyccyccy** [comment]
I added a lot of missing loading indicator issues for the sessions page here https://github.com/TEAMMATES/teammates/issues/10569

**Comment by madanalogy** [comment]
> I added a lot of missing loading indicator issues for the sessions page here #10569, including this one. Can maybe form a big issue thread regarding loading indicator issues? I'm sure there's a lot more other loading issues.

Ah okay sorry i didn't realise, I'll close this and raise the priority of the bigger issue
