### ISSUE TITLE
Numerical scale question issues

### ISSUE THREAD

**Issue by ccyccyccy** [TEAMMATES/teammates#10588]
2 issues here

1. Question saving is still successful despite the frontend validation error.
    1. The question submission page displays incorrect valid values prompts as well

![image](https://user-images.githubusercontent.com/32454748/90107175-06061800-dd7b-11ea-9f76-ab1b9cd73309.png)
![image](https://user-images.githubusercontent.com/32454748/90107034-d5be7980-dd7a-11ea-9ec1-1e4b5592cfb2.png)

2. Floating points aren't handled well (even when the question is valid)
    1. Range from [1, 8] with steps of 0.7
![image](https://user-images.githubusercontent.com/32454748/90107697-c855bf00-dd7b-11ea-84a3-28d09b69f065.png)

**Comment by wkurniawan07** [comment]
(1) can be viewed as a bug, but can also be viewed as not. In the screenshot above, the intention might be that the max acceptable number is `6.6` (for example), but since the min/max can only be integers, this is the closest anyone can get.

**Comment by ccyccyccy** [comment]
> (1) can be viewed as a bug, but can also be viewed as not. In the screenshot above, the intention might be that the max acceptable number is `6.6` (for example), but since the min/max can only be integers, this is the closest anyone can get.

My issue with (1) is that the prompt shows 6.3 instead of 6.6, and that the frontend validation contradicts the actual submission behavior. Definitely think they are bugs.

**Comment by wkurniawan07** [comment]
> My issue with (1) is that the prompt shows 6.3 instead of 6.6, and that the frontend validation contradicts the actual submission behavior. Definitely think they are bugs.

Ok, I see the issue now.

**Comment by jtankw3** [comment]
I encountered the following error and think it is related to this issue.
Environment: `master` branch at commit 09a4bfec1884d4a099fecb422fcce4ec6879d9ce

Max is set at 10 but response with 10 cannot be submitted. Same problem encountered when increment is set to 0.2 but not encountered when it is set to 0.5.
![numscale](https://user-images.githubusercontent.com/31800234/90417875-e9554180-e0e6-11ea-9d52-fd1b6feea991.PNG)

**Comment by wkurniawan07** [comment]
Apparently, in Java, for God knows what reason:
```
> 9 % 0.2
0.1999999999999995
```
Lesson learnt: don't ever use that `%` operator for non-integer divisors.
