### ISSUE TITLE
Student view team page: Loading Indicator for loading teammates not centralised

### ISSUE THREAD

**Issue by t-cheepeng** [TEAMMATES/teammates#10580]
- **Environment**: V7.0.2

**Steps to reproduce**
1. Go to student view team page and see the indicator be left aligned

**Comment by EduardoFLima** [comment]
I'd like to work on this issue

**Comment by jfrairigh** [comment]
I believe I found a fix for this issue. I'm re-reading the process.md document just to make sure I'm not missing a step. Hopefully, I will have a PR up by the end of the day.
