### ISSUE TITLE
Remind all modal from session results page cannot scroll

### ISSUE THREAD

**Issue by madanalogy** [TEAMMATES/teammates#10584]
The remind all modal from the session results page cannot be scrolled to select the `Submit` button when number of students in the session overflows past the page (see screenshot)

![Screenshot 2020-08-13 at 1 30 50 PM](https://user-images.githubusercontent.com/42177597/90097901-99365200-dd69-11ea-91ac-c778606ebcf8.png)

**Environment**: Deployed production environment on v7-0-2 on Safari, MacOS

**Steps to reproduce**
Have a course with lots of students (necessary size dependent on user screen resolution) and click "Remind All" from a session result page

**Expected behaviour**
Able to scroll down to select the "Submit" button

**Actual behaviour**
Cannot scroll down

**Comment by wkurniawan07** [comment]
![ORQOcbxg07](https://user-images.githubusercontent.com/7261051/90152504-74b69600-ddba-11ea-946f-8ef52a6b2567.gif)

Are you referring to cannot scroll without touchpad or mouse scroll wheel? Only then the issue is valid.

**Comment by madanalogy** [comment]
> Are you referring to cannot scroll without touchpad or mouse scroll wheel? Only then the issue is valid.

I'm saying cannot scroll on Safari sorry, should have been more explicit. The issue is not valid for Chrome

**Comment by damithc** [comment]
> I'm saying cannot scroll on Safari sorry, should have been more explicit. The issue is not valid for Chrome

@madanalogy You mean the main scrollbar of the browser Window doesn't appear? That part is not shown in your screenshot.

**Comment by niqiukun** [comment]
> You mean the main scrollbar of the browser Window doesn't appear? That part is not shown in your screenshot.

I checked that the modal is not scrollable in Safari, not the main window.

**Comment by damithc** [comment]
In chrome, modal scrolling is done using the main scroll bar. Not sure about Safari though.
![image](https://user-images.githubusercontent.com/1673303/90210966-0ad1d700-de22-11ea-8f2b-4cc167c99ddf.png)

**Comment by niqiukun** [comment]
> In chrome, modal scrolling is done using the main scroll bar. Not sure about Safari though.

V6 and V7 modal handles the scrolling differently. In V7 currently the scrolling is set within the modal with `overflow-y: scroll`. Removing that line will make it into V6 style which uses main window scroll bar and resolves Safari issue. But not sure if there is any side effect on Windows since only tested it on macOS.

**Comment by wkurniawan07** [comment]
> In V7 currently the scrolling is set within the modal with `overflow-y: scroll`. Removing that line will make it into V6 style which uses main window scroll bar and resolves Safari issue. But not sure if there is any side effect on Windows since only tested it on macOS.

I was the one who implemented `overflow-y: scroll`. It was to keep the modal within the container (i.e. there will always be a bottom padding), but it is not so important compared to restoring the scroll function. @niqiukun if you want to submit a change (maybe along with some other issues?), feel free to.
