### ISSUE TITLE
FeedbackSession giver/recipient options: 'Other teams/students' don't always make sense

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#1059]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on July 27, 2013 17:33:10_

For example, if the giver is selected as 'instructors', 'other teams' doesn't make sense as a recipient. 
However, solving this might make more effort than it is worth.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1060_

**Comment by JosephineKwa** [comment]
@damithc  should I add `Fixes #1059` to PR #5820 as well? However that PR does not remove the feedback path mentioned in this issue, i.e. "Instructors" to "Other teams", as it is a valid feedback path.

**Comment by damithc** [comment]
I think this issue is about the suitability of the phrasing rather than the validity of the path. So this can remain open.

**Comment by damithc** [comment]
Old issue. closing.
