### ISSUE TITLE
MSQ question: Other option counts as 2 selections

### ISSUE THREAD

**Issue by jtankw3** [TEAMMATES/teammates#10607]
- **Environment**: `V7.0.2`

**Steps to reproduce**
Set max options for MSQ option as 2
Try to submit 2 options including other.

OR

Set min options for MSQ option as 2
Try to submit only other option.

**Expected behaviour**
Succeed for first case and fail for second case

**Actual behaviour**
Fails for first case and succeeds for second case

**Additional info**
When max is set to 3 and 2 options including other is picked, it succeeds.
All three scenarios lead me to believe other counts as 2 selections.

3 selected but fails when max is 3
![other-option](https://user-images.githubusercontent.com/31800234/90311658-f24fe280-df2f-11ea-80bc-56fed7555c25.PNG)

1 selected but succeeds when min is 2
![other-option-min](https://user-images.githubusercontent.com/31800234/90311659-f54ad300-df2f-11ea-9251-c9e1ee23ba5d.PNG)

**Comment by wkurniawan07** [comment]
> All three scenarios lead me to believe other counts as 2 selections.

You happened to be right.
