### ISSUE TITLE
Optimize UI of session submission page for mobile

### ISSUE THREAD

**Issue by niqiukun** [TEAMMATES/teammates#10612]
Previous PRs (like #10042) have addressed many compatibility issues for various pages on mobile, but the experience is still far from optimised. I think we should focus on enhancing the UI of session submission page on mobile because it is more likely for students to use mobile phones to submit feedbacks, compared to other mobile senarios such as instructors accessing TEAMMATES from mobile. Here are some examples of how current UI can be further optimised:

![90326974-90d85400-dfc1-11ea-907f-24ac3cb6863a](https://user-images.githubusercontent.com/5328196/90327108-cd587f80-dfc2-11ea-9ed0-6f8c0f2b9f08.png)
- Reduce/remove paddings in red
- Hide the note in yellow or display it as modal upon entering the page?

![90327043-368bc300-dfc2-11ea-901a-2ce55b0a28cf](https://user-images.githubusercontent.com/5328196/90327114-d8131480-dfc2-11ea-8d34-534b67a25334.png)
- Reduce/remove paddings in red
- Hide the note in yellow and replace with a link such as "Who can see my responses?" Display a modal showing the details if user clicks the link.
- Hide the top and bottom bar of rich text editor (actually disable rich text functionality) since it's rare for users to enter rich text on mobile

There may be other optimisations possible depending on the question type. Also, while the page is optimised for mobile there should not be any changes to the UI of desktop site. So either we apply condition-based styling or create a new mobile friendly page?

**Comment by madanalogy** [comment]
I think the current UI uses conditioned based styling using Bootstrap's grid system (https://getbootstrap.com/docs/4.0/layout/grid/) so maybe we can just consider how to extend that approach for the removal of unnecessary padding in mobile widths?

**Comment by niqiukun** [comment]
> I think the current UI uses conditioned based styling using Bootstrap's [grid system](https://getbootstrap.com/docs/4.0/layout/grid/) so maybe we can just consider how to extend that approach for the removal of unnecessary padding in mobile widths?

I think most paddings highlighted in the above two pictures are coded in css (e.g. `main-content` and `evaluee-col`). Need to change these such that they are applied conditionally based on screen size.

**Comment by moziliar** [comment]
Hi, can I try to work on this? And, would it be an idea to set separate css for mobile view?
