### ISSUE TITLE
Instructor view results: add space after the spinner in the download button

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10615]
![image](https://user-images.githubusercontent.com/1673303/90328795-d3a22800-dfd1-11ea-9896-f8370344b10c.png)

In the `Download results` button, add a space between the spinner and the button label when a download is in progress.

**Comment by niqiukun** [comment]
Possible to work on https://github.com/TEAMMATES/teammates/issues/10425 instead for a neater look.

**Comment by bcbabrich** [comment]
I would like to claim this issue if possible. I am new to open source work so I may take a while. I'll move on to #10425 afterwards if I'm successful with this one.

**Comment by dshah2012** [comment]
I can work on it if @bcbabrich is still stuck. I fixed it and tested it locally. I can create a pull request.

**Comment by madanalogy** [comment]
> I would like to claim this issue if possible. I am new to open source work so I may take a while. I'll move on to #10425 afterwards if I'm successful with this one.

Sure, please read our contributing guide and development guide, then submit a PR when you're ready. Let us know if you need any help.

**Comment by AbhishekKakad12** [comment]
I am new to open source so can You tell me In which file download button located?

**Comment by ripudaman1320** [comment]
Hi @madanalogy / @damithc 

I would like to work on this issue as part of #Hacktoberfest. May I know if there's a channel available for communications ?

Thanks!
-Ripu

**Comment by t-cheepeng** [comment]
Hi @ripudaman1320 , you can work on this issue since the previous person has not responded/opened a PR for some time. You can communicate with us using this issue's conversations. All the best! Let us know if you require any help

**Comment by ripudaman1320** [comment]
I have few doubts -
a. Do i need to start off with my master branch only to make changes or do i need to create a feature branch for the same? 

https://github.com/TEAMMATES/teammates/blob/master/docs/process.md

> For brevity, this instruction set will use master branch as the base branch. Any reference to the master branch should be replaced with the base branch that applies to your case.

>1. Start off from your master branch and make sure it is up-to-date with the latest version of the main repo's master branch.

>git checkout master
>git pull
>2. Create a new branch to push your commits into. If you have commit access and need to push into the main repo for some reason, name it {IssueNumber}-{some-keywords}, where some-keywords are representative keywords taken from the issue title.

>git checkout -b 3942-remove-unnecessary-println

b. Can you paste the link of the issue or steps to replicate the same on my dev server.

**Comment by t-cheepeng** [comment]
@ripudaman1320 
> a. Do i need to start off with my master branch only to make changes or do i need to create a feature branch for the same?

You would need to start from your master branch and checkout a new branch as stated in the process guide

> b. Can you paste the link of the issue or steps to replicate the same on my dev server.

Once you have set up your dev server, go to any sessions > click on Results > click on View Results > click on Download Results

**Comment by ayush015** [comment]
if this issue is still up for grabs I would like handle it !

**Comment by ripudaman1320** [comment]
> @ripudaman1320
> 
> > a. Do i need to start off with my master branch only to make changes or do i need to create a feature branch for the same?
> 
> You would need to start from your master branch and checkout a new branch as stated in the process guide
> 
> > b. Can you paste the link of the issue or steps to replicate the same on my dev server.
> 
> Once you have set up your dev server, go to any sessions > click on Results > click on View Results > click on Download Results

Thanks @t-cheepeng

**Comment by ripudaman1320** [comment]
@t-cheepeng , I'm logged-in as admin but when i go to sessions, i don't see any ongoing session. Also i tried to filter by Range but still nothing showed up. 
![Capture](https://user-images.githubusercontent.com/16226387/95653989-6ebf0600-0b1a-11eb-8df2-7f72be8798c6.JPG)

**Comment by t-cheepeng** [comment]
@ripudaman1320 Follow the guide [here](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md). You would have to create instructors first.

**Comment by ripudaman1320** [comment]
I have opened a PR. Please have a look. Thanks!

**Comment by mbrat06** [comment]
Hello, we are a group of students new to open-source and tried to fix this issue. Would you please have a look ? Thanks !
