### ISSUE TITLE
NumScale question: decimal increment not working

### ISSUE THREAD

**Issue by jtankw3** [TEAMMATES/teammates#10610]
- **Environment**: `V7.0.2`

**Steps to reproduce**
1) Create a NumScale question with increment 0.1
2) Question is created but not able to submit a response

**Additional info**
Increment of whole number and 0.5 seems to be working

![NumericScale decimal](https://user-images.githubusercontent.com/31800234/90314915-e40ec000-df49-11ea-9ade-ab784ad8d7e2.PNG)

**Comment by wkurniawan07** [comment]
This is already reported in #10588 and fixed.
