### ISSUE TITLE
Weighted rubric questions: also give average per recipient

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10621]
Current: in statistics of weighted rubric questions, we provide average per recipient per criterion
Suggestions: Also provide average per recipient

Notes:
* Assume all criteria are equally weighted
* The features should cover both UI and csv
* To be done after V7 is stable

**Comment by moziliar** [comment]
This looks good. Can I help with this?

**Comment by moziliar** [comment]
Hi prof @damithc can I learn more about the UI layout?

![image](https://user-images.githubusercontent.com/19870898/95650801-7d0c2280-0b18-11eb-9fbf-694bdceeec49.png)

Do you have preference over where the overall average for individual participant?

My suggestion would be to have one more table to display it, which would be at most as big as per criterion per participant stats table.

**Comment by damithc** [comment]
> My suggestion would be to have one more table to display it, which would be at most as big as per criterion per participant stats table.

Sounds good @moziliar
