### ISSUE TITLE
Migrate design diagrams from Powerpoint to PlantUML

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#10623]
The design diagrams in our repo are created using Powerpoint. This is not ideal because:
- Not version controllable, or to be precise, we cannot track the diffs
- Powerpoint is not exactly created for this kind of documentation, so a lot of standard UML diagram components are self-created, which are inconsistent in many parts. Non-trivial effort needs to be taken if we are to create new UML diagrams.
- Require anyone who has to modify them to have Powerpoint

We need a better solution for creating the design diagrams. [PlantUML](https://plantuml.com/api) is a very good one because:
- It is free
- It works by transforming text-based DSLs to diagram, which makes the diagram version control-friendly
- It has sufficient diagram coverage for all our use cases
- It can generate the necessary PNG files online (<http://plantuml.com/plantuml>) so it is entirely optional to set up anything related to PlantUML

Other solutions can be considered but PlantUML should give an idea of what we need.

**Comment by rhit-namburs** [comment]
Hi could I try and do this issue

**Comment by u6867511** [comment]
Hello, are there any more diagrams that need to converted?

**Comment by fsgmhoward** [comment]
@u6867511 There are some remaining but PlantUML is probably not sufficient to represent the information according to comments in #11956. I think all the convertible ones are done already.

@damithc Would this issue be good to be closed?

**Comment by wkurniawan07** [comment]
We will still keep the issue open.
- `RolesAndTechnologies.png` is still relevant, but we really do not need a dedicated PPTX for that. This can be replaced with simple table such as:
   | Tool | Front-end Developer | Back-end Developer |
   | :--- | :--- | :--- |
   | Git | ✅ | ✅ |
   | HTML | ✅ | |
   | Java | | ✅ |
   | ... | ... | ... |
- `workflow.png` can actually be converted to a sequence diagram; one just needs to be creative at it.
