### ISSUE TITLE
SearchResultBundle.java comment is potentially inaccurate

### ISSUE THREAD

**Issue by konkos** [TEAMMATES/teammates#10632]
In the constructor the comment suggests that the class should not be instantiated. However that is not handled properly, class should probably be abstract or change the comment.

**Comment by konkos** [comment]
Apologies.this is actually the first open source project i have been involved in so any comments are welcome.

**Comment by madanalogy** [comment]
Something like this:
https://github.com/TEAMMATES/teammates/blob/7c0bb45477a0d0f33bb35821f360bbf640c76196/src/main/java/teammates/common/datatransfer/SearchResultBundle.java#L10-L12

You can get that by navigating to the code in the repo and copying the permalink. See: https://docs.github.com/en/github/managing-your-work-on-github/creating-a-permanent-link-to-a-code-snippet

**Comment by konkos** [comment]
In trying to fix this issue I found that my pull request would never pass all the tests since abstract classes must have abstract methods and SearchResultBundle.java contains none.
