### ISSUE TITLE
Student session results page statistic bugs

### ISSUE THREAD

**Issue by jtankw3** [TEAMMATES/teammates#10647]
- **Environment**: `V7.0.1`
- Team name is undefined for numscale question
- Self-evaluation is not included for numscale and rubric questions

**Numscale question:**
V6
![Numscale](https://user-images.githubusercontent.com/31800234/91076296-de178e00-e671-11ea-90c2-af3e31c6229b.PNG)

V7
![Numscale - v7](https://user-images.githubusercontent.com/31800234/91076307-dfe15180-e671-11ea-9468-4a6e35d7ad70.PNG)

**Rubric question:**
V6
![Rubric](https://user-images.githubusercontent.com/31800234/91076462-233bc000-e672-11ea-9637-5b3d3fa5a427.PNG)

V7
![Rubric - v7](https://user-images.githubusercontent.com/31800234/91076478-2931a100-e672-11ea-8567-5c046f87b4a7.PNG)

**Comment by wkurniawan07** [comment]
@damithc is there a reason why in V6 self responses are displayed here (light blue panel; responses given by self):

<img width="1157" alt="Screen Shot 2020-08-25 at 1 59 00 PM" src="https://user-images.githubusercontent.com/7261051/91128711-3cc52200-e6db-11ea-8147-b813e6a8ca06.png">

And not here (dark blue panel; responses received by self):

<img width="1152" alt="Screen Shot 2020-08-25 at 1 59 12 PM" src="https://user-images.githubusercontent.com/7261051/91128721-40f13f80-e6db-11ea-885d-efeac4ce148e.png">

Or both?

**Comment by damithc** [comment]
The page contains given as well as received responses. I think we wanted to distinguish between the two. It was an easier solution compared to giving a way to hide given responses or have two different pages for given and received responses.

**Comment by wkurniawan07** [comment]
> I think we wanted to distinguish between the two.

That didn't answer the question, because self evaluations fall under both.

**Comment by damithc** [comment]
> That didn't answer the question, because self evaluations fall under both.

Basically, you already know what you submitted, hence, can be skipped when reading the page. So, self evaluations should be styled less prominent than responses received from others.

Does that policy match the example you've given?

**Comment by wkurniawan07** [comment]
In the absence of other explanations, I would say so

**Comment by wkurniawan07** [comment]
@damithc the problem here is the requirement becomes conflicted:
- Statistics is based on responses displayed under "responses received by self" (by right, dark blue panels)
- Self-evaluation is displayed under "your own responses" (light blue panel)

Is it not a source of confusion?

**Comment by damithc** [comment]
True. Perhaps show self-evaluations in a different color altogether? e.g., grey
I'm OK to show it in dark blue too. I don't think it's a big problem if we did that.
