### ISSUE TITLE
Instructor help page: broken link

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10651]
A user reported that this link is broken.
![image](https://user-images.githubusercontent.com/1673303/91440192-c96d0d00-e8a0-11ea-9354-03642d99d65a.png)

**Comment by wkurniawan07** [comment]
![kgg6o9nMJr](https://user-images.githubusercontent.com/7261051/91508851-31583d80-e90b-11ea-8c0f-1306ca96609b.gif)

**Comment by damithc** [comment]
User probably right-clicked it and opened in a new tab?

**Comment by wkurniawan07** [comment]
That's not expected to work; this is a modal dialog

**Comment by damithc** [comment]
Well, it looks like a normal link to users. So, either we have to make it work both ways or disable the right-click for modal links.

**Comment by wkurniawan07** [comment]
> it looks like a normal link to users.

So what would something that triggers a modal dialog look like?

**Comment by damithc** [comment]
> So what would something that triggers a modal dialog look like?

![image](https://user-images.githubusercontent.com/1673303/93668722-00f66000-fac1-11ea-9d31-e1fbb7483cd5.png)

MarkBind uses dashed underlines (instead of regular blue text used for links) and also does not give the 'open in new tab/window' option when right-clicked. I think the latter is more important as the user is unlikely to know the special notation we use for modals even if were to use one.

**Comment by madanalogy** [comment]
@damithc @wkurniawan07 could we possibly use `ngb-tooltip-class` for the styling of this popup modal link? I was taking a look at https://github.com/TEAMMATES/teammates/issues/8465#issuecomment-741985931 and realise that it's similar to the screenshot of MarkBind's modal dialog trigger

**Comment by damithc** [comment]
> @damithc @wkurniawan07 could we possibly use `ngb-tooltip-class` for the styling of this popup modal link? I was taking a look at [#8465 (comment)](https://github.com/TEAMMATES/teammates/issues/8465#issuecomment-741985931) and realise that it's similar to the screenshot of MarkBind's modal dialog trigger

How does it look like? And does the mouse icon change appropriately to indicate a clickable element when hovering over it?

**Comment by madanalogy** [comment]
> How does it look like?

Dashed underlines like the screenshot you posted above. TEAMMATES however uses this styling to indicate a tooltip. What we can do is have modal popups be changed to also use this styling, with the tooltip "Click here for popup"

**Comment by Jellwood** [comment]
I've been trying to figure out a style that would be different enough to distinguish, could there be a case for changing the color on all of the modal links to distinguish them from a hyperlink? I know the dashed underline style is already used for tooltips and I was not sure if it would make more sense to just use an entirely different style for modal windows?

**Comment by madanalogy** [comment]
> What we can do is have modal popups be changed to also use this styling, with the tooltip "Click here for popup"

I'm thinking this should be good enough. @damithc any thoughts?

**Comment by damithc** [comment]
> I'm thinking this should be good enough. @damithc any thoughts?

Yes. Also, the mouse icon can change on hover to indicate that the text is clickable, which is not the case for tooltips.

**Comment by damithc** [comment]
> Yes. Also, the mouse icon can change on hover to indicate that the text is clickable, which is not the case for tooltips.

For good measure, we can use dotted underline for tooltips and dashed underline for modals as an added differentiation on top of other things.

**Comment by Jellwood** [comment]
I can get started on trying to get a solution for this! I just wanted to check and make sure that the discussion earlier was still relevant, since the discussion just got re-opened.

**Comment by Jellwood** [comment]
So I have the modal windows on the instructor help page working and differentiated from the other links, is the next step to get this across the website or is this page the only one for now?

**Comment by madanalogy** [comment]
You can put up a PR targeting just this page
