### ISSUE TITLE
Responses of a session seem to have dissappeard

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10658]
An instructor user reported that after he submitted some responses on behalf of students, all responses seem to have disappeared. This class happens to be a huge one, 888 students.
![image](https://user-images.githubusercontent.com/1673303/91650620-5dfb8900-eab4-11ea-88f7-586499457f1d.png)

As per the screenshot, 358 students have submitted. But when I search in the database console, only 16 responses are in the database (there should be more than 1000 responses if 300+ students have submitted -- there are multiple questions in the session)

![image](https://user-images.githubusercontent.com/1673303/91650661-d06c6900-eab4-11ea-8fb5-12be8a9bd938.png)

These 16 could very well be the ones submitted by the instructor as the timestamp is after the deadline.

Any idea what could have caused this scenario. Anything the instructor could have done to delete all the responses accidentally, for example?

**Comment by damithc** [comment]
There was another case where a student reported that all his team members gave feedback to him but only one response was in the database. But in that case, about half of the expected number of responses were still in the database so I assumed the student was mistaken. Is it possible that some action (e.g., instructor saving responses on behalf of a student) can wipe out all existing responses -- seems not possible.

**Comment by damithc** [comment]
Digging through the log of that instructor, I came across this:
![image](https://user-images.githubusercontent.com/1673303/91650836-4671cf80-eab7-11ea-857b-da29582c51ce.png)

I assume this is a case of the instructor moderating responses of a student. The responding student list seems to contain a long list of email addresses? Is it supposed to be like that?

**Comment by damithc** [comment]
Here's the bottom of that log message:
![image](https://user-images.githubusercontent.com/1673303/91650905-4c1be500-eab8-11ea-9407-3a1435edfcf8.png)

Why is the session instructions are being mentioned? Feels like some session level reset is happening when the instructor is moderating responses.

**Comment by wkurniawan07** [comment]
There's a bit of logic lapse here that I couldn't pinpoint exactly where yet. For now can you redeploy while commenting out all of these lines:
https://github.com/TEAMMATES/teammates/blob/c991210739a1705281ab7bbaae46786e360bd07c/src/main/java/teammates/ui/webapi/action/SubmitFeedbackResponsesAction.java#L96-L99

**Comment by damithc** [comment]
> There's a bit of logic lapse here that I couldn't pinpoint exactly where yet. For now can you redeploy while commenting out all of these lines:

I'm on it.

**Comment by damithc** [comment]
> > There's a bit of logic lapse here that I couldn't pinpoint exactly where yet. For now can you redeploy while commenting out all of these lines:
> 
> I'm on it.

Done

**Comment by damithc** [comment]
Not urgent, but exactly which situations would this bug occur? I would like to get some estimate of how often it came into play during the past week.

**Comment by xpdavid** [comment]
I think we might just want to remove the chunk for the reasons below:

https://github.com/TEAMMATES/teammates/blob/c991210739a1705281ab7bbaae46786e360bd07c/src/main/java/teammates/ui/webapi/action/SubmitFeedbackResponsesAction.java#L96-L99

- Without the shortcut, the remaining code will achieve the same effect
- The shortcut is calling the WRONG methods. It does **NOT DELETE** all responses for the recipients, it DELETE **ALL** responses of the question.

**Comment by wkurniawan07** [comment]
It is exactly the case. I think I included it in the earlier versions when I was designing the API (which was also not right anyway, but that's beside the point), but it lost its usage in the final version.

**Comment by damithc** [comment]
Guys, there is another user who says she lost most of the responses in one specific question (other questions are OK). She says she did try the 'moderate' feature but only after the responses disappeared already. She could be mistaken but that needs a thorough search of logs to confirm.
In the meantime, is there a possibility that traces of this flaw remains in other places or could have affected features other than moderating responses?

**Comment by wkurniawan07** [comment]
From the description, it did sound like the bug that has been fixed. If the responses has disappeared then clearly moderating will not help bringing anything back.

**Comment by damithc** [comment]
> From the description, it did sound like the bug that has been fixed. If the responses has disappeared then clearly moderating will not help bringing anything back.

Yes, moderating doesn't bring them back. My understanding was, it's the moderating that makes them disappear in the first place. Are there any other user actions that could have triggered the faulty code? My purpose is to cross check with the user to confirm which user action caused the accidental deletion and confirm that it's an action we already know as faulty during that period.

If moderation is the only user-action can cause this to happen and the user says responses disappeared before she used that action, either she is mistaken or we have missed something. Need to find out which.

**Comment by madanalogy** [comment]
The `SubmitFeedbackResponsesAction` operates on a per-question basis and the bug would have been triggered as long as an empty response set in the API request call is made to the endpoint. These conditions appear to have been met when moderating but I'm not sure if there is anywhere else that these conditions would have been met (or if we're sure that there's nowhere else it could have occured).
