### ISSUE TITLE
Student submit responses: Improve error message for no-receiver specified

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10659]
![image](https://user-images.githubusercontent.com/1673303/91651079-8e462600-eaba-11ea-994f-090684796ce7.png)

Leaving this empty results in 'not authorized to access resource' which may not make sense to the user.

**Comment by wkurniawan07** [comment]
The fact that it triggered `403` instead of `400` spells another problem.

**Comment by helloImHai** [comment]
I can look into this

**Comment by ripudaman1320** [comment]
Can i work on this issue?

**Comment by g-lilian** [comment]
Is this issue still relevant? When I tried previewing this type of question (rubric question), it automatically generates all team members instead of having the user select the recipient.
![Screenshot_1](https://user-images.githubusercontent.com/50647023/101636695-a7218880-3a66-11eb-973a-b8d81983e84d.jpg)

**Comment by damithc** [comment]
> Is this issue still relevant? When I tried previewing this type of question (rubric question), it automatically generates all team members instead of having the user select the recipient.

The dropdown will appear if you set fix the number of recipients.
![image](https://user-images.githubusercontent.com/1673303/119323668-8ade7480-bcb1-11eb-90b0-639e176ef880.png)

**Comment by hhdqirui** [comment]
Hello! Is this issue still relevant? I tried to replicate and instead of "not authorized to access resources" I get an error message that makes sense to user.
![image](https://user-images.githubusercontent.com/53338059/120601710-e01e4100-c47c-11eb-842d-4e89f6be48d0.png)

**Comment by damithc** [comment]
> Hello! Is this issue still relevant? I tried to replicate and instead of "not authorized to access resources" I get an error message that makes sense to user.

Yes, seems to be fixed now. Thanks for checking @hhdqirui
