### ISSUE TITLE
Instructor copying sessions: essay questions cannot be copied if recommended length is not set 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10656]
Recommended length is supposed to be optional but when copying a session from one course to another, the operation fails with the error message that recommended length is not set.

![image](https://user-images.githubusercontent.com/1673303/91629149-eae10c80-e9f8-11ea-8547-01b6fec4e6fa.png)

**Comment by rrtheonlyone** [comment]
How do I go about reproducing this issue? 

I tried:
- creating a brand new session from template : works
- adding a new empty essay question with a name : works

I initially had this problem with my dev environment but once I cleared my local database and reran the application, it seemed to work. 

I did some digging and it looks like we only check for the recommended length field being < 1 if it is not null.

**Comment by wkurniawan07** [comment]
@xpdavid looks like we're digging our own grave here: https://github.com/TEAMMATES/teammates/pull/10316/files#r459836557

**Comment by wkurniawan07** [comment]
> once I cleared my local database and reran the application, it seemed to work.

@rrtheonlyone on a general note, if this resolves any kind of problem faced, it may likely be caused by legacy data format (as what has happened here). Not a pleasant thing to do, but needs to be done.

**Comment by damithc** [comment]
Yes, could be a legacy data issue. This session was created by V6.

**Comment by damithc** [comment]
Guys, this is likely to cause most session-copy operations to fail (as most would contain essay questions and almost all existing sessions were created by V6) right? In that case, shouldn't we hot fix this quickly?

**Comment by xpdavid** [comment]
The problem is that we are too aggressive when making `recommended` length optional.

https://github.com/TEAMMATES/teammates/blob/34fb6e681faa36638e6c50f442f57e580384574a/src/main/java/teammates/common/datatransfer/questions/FeedbackTextQuestionDetails.java#L31-L38

We should not enforce `recommendedLength` to be bigger than 1 as the legacy data has them **set** but has zero value.

**Comment by damithc** [comment]
Lets fix quickly as those who use the copy-session feature are long-time/heavy users of TEAMMATES and we don't want to make them unhappy.

**Comment by wkurniawan07** [comment]
@xpdavid I don't think we should change the validation logic. A better way is to change the legacy format when we're getting the questions information; that way, any subsequent update request will send the correct format.

**Comment by xpdavid** [comment]
Sure. Anyway, one might want to do the abstraction in `FeedbackQuestionData` and create a data migration task targeted on this.

**Comment by madanalogy** [comment]
> @xpdavid I don't think we should change the validation logic. A better way is to change the legacy format when we're getting the questions information; that way, any subsequent update request will send the correct format.

This might take some time though, maybe just revert the validation logic for now and add a TODO for after data migration?

**Comment by damithc** [comment]
An external user reported this problem today. I asked him to use V6 just for copying.
Yes, I think we should drop the validation logic for now or update it to 'null or positive integer'
