### ISSUE TITLE
Masquerade mode doesn't work when using right-click menues

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10662]
Suppose the admin is masquerading as an instructor and is in the instructor home page.
Clicking on a menu item or a button (e.g., view students of a course) works as expected -- i.e., can masquerade
But accessing a page via right-clicking the same item seems to cause an access error

**Comment by damithc** [comment]
Also doesn't seem to work when using the back button of the browser

**Comment by damithc** [comment]
Can't 'preview' sessions as student/instructor when masquerading as an instructor either. This one is a bigger problem than the other two because there is no way around it.

**Comment by rrtheonlyone** [comment]
@damithc how do I reproduce this issue? 

What happens now when we try to click 'preview' on the edit feedback session page?

**Comment by damithc** [comment]
> @damithc how do I reproduce this issue?

1. Login as admin. 
1. Search for another instructor.
1. Try to masquerade as that instructor.

> What happens now when we try to click 'preview' on the edit feedback session page?

Preview page opens but the login changes to my own account (no longer masquerading) and the page throws an error because I'm not the actual instructor for that student.

So, when I say 'not working', I mean the page try to load under my own account instead of masquerading as the other instructor (and throws an unauthorized access error) .

**Comment by ccyccyccy** [comment]
The reason is that the URL query param for masquerading is not preserved when opening new tabs. Can refer to `SessionEditFormComponent#sessionHelpHandler` for an implementation that works.

Will try to fix this soon.

**Comment by wkurniawan07** [comment]
Lowering priority as masquerade mode can still be triggered by entering `user` param manually
