### ISSUE TITLE
Instructors cannot give feedback to teams

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10665]
Question setting:
![image](https://user-images.githubusercontent.com/1673303/91736594-7ff22a00-ebe0-11ea-8581-d67194ba0db9.png)

When previewed as an instructor:
![image](https://user-images.githubusercontent.com/1673303/91736661-9d26f880-ebe0-11ea-838e-6a0532781178.png)

In V6:
![image](https://user-images.githubusercontent.com/1673303/91736726-b465e600-ebe0-11ea-8f9f-ca1bb8347f20.png)

**Comment by damithc** [comment]
Tagging as high because a user is waiting on this. But it cannot be fixed in a hurry, we can lower the priority and inform the user to use V6.

**Comment by madanalogy** [comment]
The frontend is receiving an empty recipient set and it seems like there's a problem with the backend:

https://github.com/TEAMMATES/teammates/blob/ff651e918c08a8cc40b67f501e81ba1c8751255c/src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java#L419-L432

**Comment by madanalogy** [comment]
> Tagging as high because a user is waiting on this. But if it cannot be fixed in a hurry, we can lower the priority and inform the user to use V6.

My PR should fix it. We can either do a v7.0.3 release or you can redeploy by swapping the boolean condition in 

https://github.com/TEAMMATES/teammates/blob/ff651e918c08a8cc40b67f501e81ba1c8751255c/src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java#L420

to `!instructorGiver.isAllowedForPrivilege`

**Comment by damithc** [comment]
I'll redeploy as soon as the PR is merged.
