### ISSUE TITLE
Student trying to access non-existent session: give a better error message

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10664]
Current:
![image](https://user-images.githubusercontent.com/1673303/91695648-0f77e880-eba1-11ea-98a6-254ee55f1ac2.png)

Suggestion: 
* Give a better error message e.g., `The session does not exist (most likely has been deleted by the instructor after the submission link was sent out)`. 
* Not show the partially loaded page?

**Comment by SumitWankhede** [comment]
How can we replicate this issue?

**Comment by damithc** [comment]
> How can we replicate this issue?

My guess: take a working submission link and alter the link subtly so that it points to a non-existent session

**Comment by sjkadali** [comment]
Can I work on this issue?

**Comment by ChooJeremy** [comment]
@sjkadali Sure, go ahead

**Comment by sjkadali** [comment]
On logging in as student and trying to access the non-existent session, its showing this error message. 

![Screenshot from 2020-09-28 09-28-25](https://user-images.githubusercontent.com/39105848/94460645-0b7ebc80-0187-11eb-8b55-56c6f5d3ec14.png)

So is it okay to stop loading the session page and redirect it to this student home page?

![Screenshot from 2020-09-28 12-41-17](https://user-images.githubusercontent.com/39105848/94461354-079f6a00-0188-11eb-9b85-b3382d732ab1.png)

**Comment by damithc** [comment]
@sjkadali 
No need to say `permanently deleted`, just `deleted` is enough (as students are not aware of the distinction between soft deletion and permanent deletion). Perhaps no need for `and no longer accessible` as it doesn't add any value.
In fact, an error message to use was suggested in the issue description. Just follow that?

**Comment by sjkadali** [comment]
@damithc thanks, will update the error message as suggested in the issue description.
