### ISSUE TITLE
Problem while enrolling students

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10675]
Received from a user

>I am trying to log into teammates for one of my classes, but the page linked below keeps popping up, and when I click "send error report" it won't let me. 

![image](https://user-images.githubusercontent.com/1673303/91794076-ac439000-ec4c-11ea-942e-0b1096ebae1f.png)

Seems like there are two issues:
* the problem with enrolling
* unable to send error report

**Comment by wkurniawan07** [comment]
There's no problem with either. "Missing CSRF token" is a different problem altogether.

**Comment by wkurniawan07** [comment]
Did the user disable cookies or happen to clear browser cookies before doing the above?

**Comment by damithc** [comment]
> Did the user disable cookies or happen to clear browser cookies before doing the above?

I'll ask.

**Comment by damithc** [comment]
Regarding the 2nd problem, can the missing token also cause the error report submission to fail?

**Comment by wkurniawan07** [comment]
It does. Submitting error report is a POST action. It's like that since V6.

**Comment by damithc** [comment]
> It does. Submitting error report is a POST action. It's like that since V6.

While it is a corner case, we need to find a solution as this can be doubly-frustrating to the user. Perhaps simply add  `Alternatively, let us know bout this problem by emailing ...` to the form? The better solution is to detect that it is a token problem and provide an alternative method to submit the error report (i.e., not show the form that will not work anyway) but not sure how much extra work that is.

**Comment by damithc** [comment]
Closing in favor of #10700
