### ISSUE TITLE
Maximum receiver count has no effect

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10681]
Reported by a user.
This setting doesn't seem to have any effect. All students are listed irrespective of this number.
![image](https://user-images.githubusercontent.com/1673303/91982178-7097eb80-ed5c-11ea-8820-d9ee23257b7b.png)

**Comment by damithc** [comment]
If possible, let's fix this quickly as the user's session is about to open soon. Plus this is likely to affect many other users.

**Comment by rrtheonlyone** [comment]
Yup, it looks like we completely ignore the max entities here in this function: https://github.com/TEAMMATES/teammates/blob/dc2fbb5425ef8b85cca067b3503be7f761455c0c/src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java#L342

What should be the expected behaviour here? 

If there is `x` available entities and `x > max_number`, should we randomly sample `max_number` of students and show it instead?

**Comment by damithc** [comment]
> If there is `x` available entities and `x > max_number`, should we randomly sample `max_number` of students and show it instead?

No need to pre-select. Just show x drop-downs with no value selected.

**Comment by rrtheonlyone** [comment]
Isn't that the current behaviour? At least locally for me, it shows `x` drop-downs with no value selected.

**Comment by damithc** [comment]
> Isn't that the current behaviour? At least locally (from current master branch) for me, it shows `x` drop-downs with no value selected.

On the live server, it shows the entire class as drop downs, not limited to `x`. I tested it on a rubric question and the user seems to have experienced it in an MCQ question.

**Comment by rrtheonlyone** [comment]
Okay understood! If a class has 100 students and we set the max to be 20, we should see 20 drop-downs with no value selected. 

I think I should be able to fix this. I will try it out.

**Comment by xpdavid** [comment]
What the settings used to reproduce the issue?

**Comment by damithc** [comment]
> What the settings used to reproduce the issue?

The original screenshot is from the user's course.
Here's the one I used.

![image](https://user-images.githubusercontent.com/1673303/92059471-e3887d00-edc3-11ea-9c03-c7d5ff30f111.png)

Output has more than 3 dropdowns:
![image](https://user-images.githubusercontent.com/1673303/92059551-1cc0ed00-edc4-11ea-893a-caf1414686d0.png)

**Comment by rrtheonlyone** [comment]
@damithc from tracing the code, it looks like the bug only happens when you are in `preview` mode. Is that true?

**Comment by xpdavid** [comment]
I think so. We do have logic to take care of the case for real submission.

**Comment by xpdavid** [comment]
@rrtheonlyone 

https://github.com/TEAMMATES/teammates/blob/667bf95968edcb4500e218ae83701f870646531f/src/web/app/pages-session/session-submission-page/session-submission-page.component.ts#L388-L401

We should cap the `recipientSubmissionForms` here

**Comment by damithc** [comment]
> @damithc from tracing the code, it looks like the bug only happens when you are in `preview` mode. Is that true?

That's possible. Both the actual user and myself are using the preview mode.

**Comment by damithc** [comment]
Lowering priority as only applies to preview. But now that we have started fixing it. let's carry on and release a hot fix as soon as it's merged.
