### ISSUE TITLE
Essay questions: make rich text support for answers configurable

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10693]
In some cases, instructors may not want to receive rich text answers as it complicates further processing.

Suggestion: Give an option to 'allow rich formatting' which can be ticked by default. If not ticked, give respondents just a plain text box to enter the answer.

**Comment by moziliar** [comment]
I could try doing this issue!

**Comment by moziliar** [comment]
@damithc could such preference be propagated to the BE or even the DB as an attribute of the question?

**Comment by damithc** [comment]
> @damithc could such preference be propagated to the BE or even the DB as an attribute of the question?

Yes, I didn't think there is any other option. Is there?

**Comment by moziliar** [comment]
@damithc ok. I'll just create such param throughout FE/BE.
