### ISSUE TITLE
Unable to add instructor on dev-server

### ISSUE THREAD

**Issue by JimGalvan** [TEAMMATES/teammates#10701]
- **Commit SHA:** 
![Capture](https://user-images.githubusercontent.com/58128571/92427098-7288f280-f140-11ea-98d3-9ddbf8ce9df3.PNG)
- **Operating System:** Windows 10
- **JDK Version: javac**1.8.0_251
- **Node.js Version:** v12.18.3
- **Google Cloud SDK Version:** Google Cloud SDK 303.0.0
- **IntelliJ Version (if applicable):** 2020.2
- **Firefox / Chrome Version (if applicable):** 80.0.1 (64-bit)

**What I was trying to do / What I need help with**
I am trying to add an instructor but I keep getting the error from the image.

**Attempts to resolve the problem**
I already follow all the steps from _Setting up a development environment_ and _Development Guidelines_ to set up a dev-server but I keep getting this error.

I upload this picture to see if it helps in something:
![Capture2](https://user-images.githubusercontent.com/58128571/92428783-f04efd00-f144-11ea-9174-029ad76100a1.PNG)

**Comment by ccyccyccy** [comment]
Sounds similar to this issue. https://github.com/TEAMMATES/teammates/issues/10040

> ![Capture2](https://user-images.githubusercontent.com/58128571/92428783-f04efd00-f144-11ea-9174-029ad76100a1.PNG)

Could you uncomment the line with `org.gradle.java.home` and point it to the path of your JDK 8?

**Comment by JimGalvan** [comment]
Thanks! @ccyccyccy 
Uncommenting that line and the one for the Gcloud solved my problem!
I just had to restart the server, and it downloaded some files, and after that it began working!

![Capture](https://user-images.githubusercontent.com/58128571/92669115-7bef9780-f2c5-11ea-9dc8-7318774b8d89.PNG)

**Comment by damithc** [comment]
Thx for the help @ccyccyccy
