### ISSUE TITLE
Handle CSRF token problem better

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10700]
Consider cases like the below:
![image](https://user-images.githubusercontent.com/1673303/91794076-ac439000-ec4c-11ea-942e-0b1096ebae1f.png)

Suggestions:
* Make the error message more understandable to users
* Explain workarounds/remedies to the user
* Do not present the submission form to the user (as it is going to fail as well). Instead, give our support email address.

**Comment by halfwhole** [comment]
Hi, I'm attempting to work on this issue currently. Would an error message like this be more understandable or appropriate? 

![teammates-csrf-problem](https://user-images.githubusercontent.com/41856541/107234507-b620b900-6a5e-11eb-8838-735e6984ea3f.png)

**Comment by damithc** [comment]
Perhaps no need to mention CSRF token to the user?

**Comment by halfwhole** [comment]
Might this work better?

---

### Uh oh! Something went wrong.

We are sorry for the error. It is likely that your browser could not create or access cookies for authorization. If cookies are disabled in your browser, please turn on your cookies before trying again.

For further support, please email us at teammates@comp.nus.edu.sg.

**Comment by damithc** [comment]
Yes, better. If applicable, we can also suggest other solutions such as emptying cache or trying a different browser?

**Comment by halfwhole** [comment]
Sure thing, I've added it here:

---

### Uh oh! Something went wrong.

We are sorry for the error. It is likely that your browser could not create or access cookies for authorization. If cookies are disabled in your browser, please turn on your cookies before trying again. Alternatively, you could also try emptying your browser's cache, or switching to a different browser.

For further support, please email us at teammates@comp.nus.edu.sg.

**Comment by damithc** [comment]
Looks OK to me but do get opinions from others as well. Make sure these suggested solutions actually work (I don't know myself).
