### ISSUE TITLE
Invalid links redirecting the user to the Google login page

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10705]
Current: In some cases, when the link used by a student is no longer valid, the user is redirected to the Google login page. 
Example: When the student is no longer in the course
Expected: show error message

**Comment by wkurniawan07** [comment]
Unclear here. "When the student is no longer in the course" doesn't tell which links are invalidated.

**Comment by damithc** [comment]
> Unclear here. "When the student is no longer in the course" doesn't tell which links are invalidated.

Suppose a student was deleted from a course. Any link sent to the student (e.g., a submission link) before the deletion will be invalid now, right? The most recent case I encountered was like that. The student is trying to access a link received from TEAMMATES but his email is no longer in the class list. As the email is our primary key, effectively he is no longer in the class.

**Comment by wkurniawan07** [comment]
> link sent to the student (e.g., a submission link)

Yes, this is important to specify which links exactly. "Link used by a student" is virtually any link, but there are only so few "link(s) sent to the student".

**Comment by wkurniawan07** [comment]
Fixed in #10719
