### ISSUE TITLE
Instructor changing visibility of questions: incorrect warning

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10703]
An instructor changing the visibility (when there are responses already) does not actually delete existing responses. However, the warning message state existing responses will be deleted. Instead, the warning message should only state that it is not recommended because the existing responses were submitted under a different visibility 'promise'.

However, changing the feedback path does result in the deletion of existing responses and users should be warned as such.

**Comment by helloImHai** [comment]
May I take up this ticket?

**Comment by jtankw3** [comment]
Hi @helloImHai, yes please go ahead.

**Comment by xpdavid** [comment]
More information here, see code implementation for details
- Changing feedback path will delete ALL responses
- Changing question details **may** delete responses
- Changing visibility options will NOT delete responses

Previously we just be lazy to say that responses **may** get deleted :P

**Comment by helloImHai** [comment]
Hi @xpdavid, from what I understand, when there are changes made to the question, there will be a `isChanged` flag that is set to true. And on saved, this flag will trigger a generic confirmation model to open upon clicking save. For this ticket, would we want to:
1. Edit the generic confirmation model to explain the nuances of what is changed?
2. OR, would we want to handle state changes differently so that we can open different confirmation models depending on the changes made? Eg. Have something like a `responsesMayBeDeleted` flag that is separate from the `isChanged` flag

**Comment by xpdavid** [comment]
Needs your inputs on interactions Prof @damithc 

Either way, yes, we might need another flag to detect the changes. Another way (recommenced, less code, easier) to do this is to compare the edited modal and the original question and figure out what is changes. 

BTW, you don't want the variable naming to confine itself to the result it indicated like `responsesMayBeDeleted`. If we want to go for the flag way, `isFeedbackDeatilsChange` is a better name.

**Comment by damithc** [comment]
Ideal (for changing question details, not path or visibility):
* When the change to the question clearly invalidates the existing responses (e.g., the total points to distribute among members is changed), we have to clearly say the responses will be deleted and actually delete the responses.
* If the change does not technically make the responses invalid, we have to warn the user that we are keeping the responses but if the instructor thinks the existing responses should not be kept, there should be an option to delete them. e.g., when the instructor changes the phrasing of the question such that previous responses are no longer correct. This decision can only be made by the instructor.

Not sure if it is practical to go for the above though. It requires to think though all question types and all possible changes. Is it too big of a change to do in this PR? Perhaps do one question type at a time?

**Comment by xpdavid** [comment]
I think let's delivery these features first:
- If the change does not technically make the responses invalid (i.e. editing visibility option, there are other cases but let's put them aside), we have to warn the user that we are keeping the responses
- When the change to the question clearly invalidates the existing responses (i.e. changing feedback path, there are other cases but let's put them aside), we have to clearly say the responses will be deleted and actually delete the responses.

We left these for future improvement:
- There are some modification which will invalidates responses while will not. See backend for more details. If we want to tackle these cases, we might need a new API. <- separated epic issue
- but if the instructor thinks the existing responses should not be kept, there should be an option to delete them. <- separated issue

**Comment by damithc** [comment]
> We left these for future improvement:
> 
> * There are some modifications which will invalidates responses while some will not. See backend for more details. If we want to tackle these cases, we might need a new API. <- separated epic issue
> * but if the instructor thinks the existing responses should not be kept, there should be an option to delete them. <- separated issue

How do we handle these cases in the interim? What warning do we give to the user? Will the responses be deleted?

**Comment by helloImHai** [comment]
Hi Prof and David, hmmm, taking all this into account, I think we should leave the `isChanged` variable as it is, and make it such that the visibility alone will not set this flag true. Instead, I'll make a `isVisibilityChanged` boolean that will be changed when visibility is changed, so that if only visibility is changed, we'll render a separate warning model so the user knows that responses will not be deleted.

This is also for modularity so that the warning of deletion for feedback change can be done at a later date.

Is this approach okay? I'll start making the changes and open the PR.

**Comment by xpdavid** [comment]
> How do we handle these cases in the interim? What warning do we give to the user? Will the responses be deleted?

More straight-forward plan
1. feedback path change -> show modal that responses are going to be deleted
2. visibility change -> show model that "you are breaking promises but we will not delete responses"
3. other cases (which is between delete or not) -> show model that "responses may get deleted" (this is the behavior of case 1 and 2 in the current master)

> Instead, I'll make a isVisibilityChanged boolean that will be changed when visibility is changed, so that if only visibility is changed, we'll render a separate warning model so the user knows that responses will not be deleted.

Why not make it on demand (i.e. check if there are anything changed when the save button is clicked).

**Comment by helloImHai** [comment]
> Why not make it on demand (i.e. check if there are anything changed when the save button is clicked).
I'm not sure how we would do this when the question form is re-rendered every time a change is made? Unless we always pass down to the child component the "original" question state?

**Comment by xpdavid** [comment]
See my edited answer. Let's follow the current way
