### ISSUE TITLE
Instructor enrolling students: trim cell values before using them

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10708]
In some cases, spreadsheets of student lists generated by other software can contain extra white space characters. Here's an example from a case reported by a user.
![image](https://user-images.githubusercontent.com/1673303/93010137-a25e4d00-f5bb-11ea-8122-1c8d71490380.png)
At other times, users might add such spaces by mistake.

In these cases, users will be frustrated because it is not possible to figure out the problem based on the error message given.
![image](https://user-images.githubusercontent.com/1673303/93010167-008b3000-f5bc-11ea-8a68-d171c8f7d1db.png)

Suggestion: trim cell values before using them as there are no legit situations where a user might want leading/trailing white space in this use case.

**Comment by damithc** [comment]
Increasing the priority as more users are sending support requests related to this issue. Pointing out the problem is in their own data doesn't make them any happier :-p

**Comment by helloImHai** [comment]
Hi Prof, I can start looking into this

**Comment by damithc** [comment]
> Hi Prof, I can start looking into this

Great. Go ahead @helloImHai
