### ISSUE TITLE
Instructor viewing results: No responses shown for Recipient > Question > Giver

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10715]
Reported by a user:
No responses shown for the view Recipient > Question > Giver
![image](https://user-images.githubusercontent.com/1673303/93596458-eef6bd80-f9eb-11ea-9694-020aa4e36c72.png)

But responses appear for the 'Question' view:
![image](https://user-images.githubusercontent.com/1673303/93596533-1188d680-f9ec-11ea-9bd7-4c910f7975cc.png)

When I tested this in my own session, I don't have the same problem.
![image](https://user-images.githubusercontent.com/1673303/93596634-3d0bc100-f9ec-11ea-9f0d-87e08b9c03a2.png)

I'm trying to figure out what's the difference between my session and this user's session.

The first thing I noticed is that all my students are in sections but all his students don't have any sections. Could that be the reason? If not, I'll dig deeper to find other differences.

**Comment by wkurniawan07** [comment]
Found the issue. Yes, it's related to section name.

**Comment by wkurniawan07** [comment]
Fixed in #10716
