### ISSUE TITLE
Tweak flow when a student clicks a submission link while logged into a Google account

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10718]
Situation: A student clicks on a submission link while logged into a Google account. The Google account is not linked to the TEAMMATES account.

Current: shows not-authorized message

Suggested (also V6):
* Ask student if she would like to use the current logged-in Google account to join TEAMMATES
  * If user agrees, 'join' the student into the course using the Google account and go to the submission page. The dialog should inform the user that joining is optional and what happens if she choose not to.
  * If user chooses not to, logout from the Google account and go the submission page

Marking as priority medium because this is generating user support requests
The dialog text can be copied over from V6. IIRC, it had some detailed instructions to the user.

**Comment by wkurniawan07** [comment]
Not even the suggestion (by extension, V6) is ideal. Why does the student need to be logged out first, if the submission link is valid for anyone anyway?

**Comment by damithc** [comment]
> Why does the student need to be logged out first, if the submission link is valid for anyone anyway?

I suspect that it was taken as a shortcut to avoid some technical difficulty. It's even better if logging out is not necessary.

**Comment by wkurniawan07** [comment]
Fixed in #10719
