### ISSUE TITLE
Missing call to AuthService.getAuthUser for public pages

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#10723]
https://github.com/TEAMMATES/teammates/blob/12e8e9b9c6c3b6d3ee1cfd0a5ea8a2ab44fec33d/src/web/app/public-page.component.ts#L14-L21

Unlike all other skeleton pages (static, student, instructor, admin), `AuthService.getAuthUser` is not called here. This results in two serious mistakes:
- Masquerade mode can be activated in the front-end without checking for admin permission. Fortunately, API calls using unauthorized masquerade mode will still be blocked by back-end.
- User will not obtain CSRF token. This must be the reason for the large number of "request failed origin check" occurrences.

Affects join page, student submission page, student result page, the latter two only when visited via public URL. Student result page technically should not be affected since there is no DB-modifying operation there.

**Comment by madanalogy** [comment]
Fixed by #10724
