### ISSUE TITLE
I get errors while executing the "npm run start" command

### ISSUE THREAD

**Issue by clare0901** [TEAMMATES/teammates#10728]
- Commit SHA: 2194d4a71997a0b74a0e085cb24ca41ff0732340  
- Operating System: Windows
- JDK Version: 1.8.0_221
- Node.js Version: v12.16.2

- **Google Cloud SDK Version:**
- **IntelliJ Version (if applicable):**
- **Firefox / Chrome Version (if applicable):**

I get a bunch of errors while i run the  `npm run start ` command

Screenshot of the error:

![image](https://user-images.githubusercontent.com/58616834/94331698-6203c380-ffec-11ea-9b24-87c86ff5c8c4.png)
![image](https://user-images.githubusercontent.com/58616834/94331706-76e05700-ffec-11ea-865f-0b959f5f948b.png)

**Comment by madanalogy** [comment]
I'm not too familiar with Windows, could you try taking a look at step 3 in https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md

**Comment by wkurniawan07** [comment]
```txt
An unhandled exception occurred: NGCC failed.
See "C:\Users\toshiba\AppData\Local\Temp\ng-EFsHWZ\angular-errors.log" for further details.
```
What does this file contain?

**Comment by clare0901** [comment]
> ```
> An unhandled exception occurred: NGCC failed.
> See "C:\Users\toshiba\AppData\Local\Temp\ng-EFsHWZ\angular-errors.log" for further details.
> ```
> 
> What does this file contain?

[angular-errors.log](https://github.com/TEAMMATES/teammates/files/5313618/angular-errors.log)

**Comment by damithc** [comment]
Old issue. Closing.
