### ISSUE TITLE
Student submitting responses: show own name more prominently

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10725]
When students submit responses, the student name (see below) can be shown more prominently (bigger letters, bold, different color etc.)
![image](https://user-images.githubusercontent.com/1673303/94099924-b6793880-fe5e-11ea-8a2f-743f053655e0.png)

This is for students to self-detecting when submitting responses using other people's links. Despite our warning of not to do so, sometimes students share their submission links.

**Comment by RohitDhatrak** [comment]
I would like to work on this issue.

**Comment by ankita2210** [comment]
Hi @damithc  Can you assign this issue to me . Can I work on this ?

**Comment by damithc** [comment]
@ankita2210 Go ahead and submit a PR. No need to assign the issue.

**Comment by ankita2210** [comment]
> @ankita2210 Go ahead and submit a PR. No need to assign the issue.

Thanks. I will be working on this
