### ISSUE TITLE
TEAMMATES cannot be reached from Phillipines

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10720]
![image](https://user-images.githubusercontent.com/1673303/93730399-0061e480-fbfb-11ea-8b85-c3f8260d26c6.png)

A number of users from the Philippines have reported that TEAMMATES is not accessible. Normally, a problem like this (if it is a DNS problem) goes away after a while but this time it doesn't seem to rectify itself even after a week. The users are not from the same university but all from Philippines. 

Not sure what we can do either.

**Comment by wkurniawan07** [comment]
I tried connecting via VPN and there is no issue.

> The users are not from the same university but all from Philippines.

This doesn't really tell the magnitude of the problem. We know that given a user face this problem, s/he is from Philippines. What we need is given a user is from Philippines, how many will face this problem. How many different universities have reported this?

**Comment by damithc** [comment]
> This doesn't really tell the magnitude of the problem. We know that given a user face this problem, s/he is from Philippines. What we need is given a user is from Philippines, how many will face this problem. How many different universities have reported this?

So far 4 users reported this problem over a week; from at least 3 different universities -- all instructors. One of them said most of her colleagues cannot access but some can. No data on how many from Philippines can and cannot access. We don't have many Philippine universities actively using TEAMMATES (less than 10 I believe). While the number is not high, it's worrying that the problem persists over a week. Also, there is no workaround we can offer to the affected users which means they'll have to stop using TEAMMATES.  

I suspect one of the main ISP's in Philippines is unable to connect to TEAMMATES (due to some DNS problem?)

**Comment by damithc** [comment]
I asked one user to try https://ga-dev-tools.appspot.com/  and she says that's not accessible either. Looks like it's an appspot.com problem. I'll try to get a confirmation from another user.

**Comment by wkurniawan07** [comment]
This has been determined as user issue and will not be addressed.
