### ISSUE TITLE
"cannot find module api-"...

### ISSUE THREAD

**Issue by jfrairigh** [TEAMMATES/teammates#10749]
- **Commit SHA:** 4cce50f625ceb0e411d34168424bab7c546cca3a
- **Operating System:** Linux Mint
- **JDK Version:** 1.8.0_251
- **Node.js Version:** 12.18.4
- **Google Cloud SDK Version:** 311.0.0
- **IntelliJ Version (if applicable):**
- **Firefox / Chrome Version (if applicable):** 68.0.1

**What I was trying to do / What I need help with**
When running front-end component tests a large number of the test suites failed to run. Here is a small sample of the error messages received:
_____________________________________________________________________________________________________
FAIL  teammates/src/web/app/pages-admin/admin-search-page/admin-search-page.component.spec.ts
  ● Test suite failed to run

    teammates/src/web/services/account.service.ts:3:35 - error TS2307: Cannot find module '../types/api-endpoints'.

    3 import { ResourceEndpoints } from '../types/api-endpoints';
                                        ~~~~~~~~~~~~~~~~~~~~~~~~
    teammates/src/web/services/account.service.ts:4:50 - error TS2307: Cannot find module '../types/api-output'.

    4 import { Account, JoinLink, MessageOutput } from '../types/api-output';
                                                       ~~~~~~~~~~~~~~~~~~~~~
    teammates/src/web/services/account.service.ts:5:38 - error TS2307: Cannot find module '../types/api-request'.

    5 import { AccountCreateRequest } from '../types/api-request';
_____________________________________________________________________________________________________

<!-- e.g. if you were setting up the project, tell us the step in the setting up guide at which you are stuck. -->
<!-- e.g. if you were resolving test failures, tell us which tests are failing. -->
<!-- Include information such as screenshots, error stack traces, or console messages to help us troubleshoot. -->



**Attempts to resolve the problem**
<!-- Tell us the steps you have taken to try to (unsuccessfully) resolve the problem and the outcomes. -->
Steps Taken:
1.) I found a closed issue (##9681) which described this problem. Someone reminded him to run the command "./gradlew generateTypes" which worked for him, but it has not worked for me. 

2.) I read through a thread on stackflow that suggested removing the entire node_modules folder, do a npm cache clean, removing the package-lock.json,  re-installing npm.

Note: the node modules are stored in the root directory of my local repository
![Screenshot ](https://user-images.githubusercontent.com/67874354/94950584-78a49180-04a8-11eb-89c0-225f3dff1cf6.png)

**Comment by wkurniawan07** [comment]
> 1.) I found a closed issue ### (#9681) which described this problem. Someone reminded him to run the command "./gradlew generateTypes" which worked for him, but it has not worked for me.

How exactly does it not work for you?

**Comment by jfrairigh** [comment]
Even after running  "./gradlew generateTypes" . The test still fail to run
and produce the same error messages. It does not work in that it does not
change the outcome.

Jessica Rairgh
Computer Science 10/01/19
Student ID: 001198235
Mentor: Stephenie Bozdogan
256-710-8956
Central Standard Time
jrairig@wgu.edu

**Comment by wkurniawan07** [comment]
Unfortunately that doesn't tell anything new.

> The "/gradlew generateTypes" command itself runs successfully.

Do you have the file `src/web/types/api-output.ts`?

**Comment by jfrairigh** [comment]
yes

**Comment by jfrairigh** [comment]
Here is a screenshot of the contents of the src/web/types folder:
![image](https://user-images.githubusercontent.com/67874354/95024294-b4299200-0647-11eb-95cd-6b3689fb4a69.png)

**Comment by wkurniawan07** [comment]
The folder looks perfectly fine. Maybe we shouldn't worry about testing first. Does `npm run start` and `npm run build` work for you?

**Comment by jfrairigh** [comment]
yes

**Comment by jfrairigh** [comment]
@wkurniawan07 I think it may be a path issue. It seems like the tests that are failing do not know how to find these module files. Is there a configuration file I could use to verify the path that has been given to these tests that are failing?

**Comment by wkurniawan07** [comment]
I'm out of ideas myself so that's probably what happened, and this is the first time I heard it happened. It's also weird given that your `npm run start` and `npm run build` can run but not this where there should not be any difference (i.e. it should be all fail or all success).
The only places whereby paths are set are [here](https://github.com/TEAMMATES/teammates/blob/1c2b94d63a7be533d96e149223c0f4368bcea1cd/tsconfig.json#L4) and [here](https://github.com/TEAMMATES/teammates/blob/1c2b94d63a7be533d96e149223c0f4368bcea1cd/jest.config.js#L3-L6) but I doubt any of them will cause whatever you observed.

**Comment by jfrairigh** [comment]
You are correct there was no reason for me to have git/teammates/teammates as a directory. A couple hours after I closed this issue that occurred to me as well. I deleted it and the test are all passing still.
