### ISSUE TITLE
Separate out L&P tests from E2E tests

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#10741]
Currently L&P tests are situated in the same package as E2E tests. However, there is almost no commonality between the two other than the usage of `BackDoor`, and the purpose of the tests are entirely different, so they should reside in entirely different package/directory.

**Comment by VinodKW** [comment]
Hi @wkurniawan07, I wanna give it a shot. 

One question, is there any fixed name that I should keep in mind while making the changes?

**Comment by wkurniawan07** [comment]
@VinodKW, thanks for offering help. Unfortunately I have started and almost finished this, and even if I have not this requires a decent knowledge of the system architecture/operations which I don't dare to put on new contributors.

If you'd like to help/get Hacktoberfest credits, there are plenty of open issues.

**Comment by VinodKW** [comment]
@wkurniawan07 no problem.
