### ISSUE TITLE
Section selection in session results show duplicate options

### ISSUE THREAD

**Issue by madanalogy** [TEAMMATES/teammates#10753]
The section selection dropdown in the session results page duplicates options for "None" and "No specific section". The dropdown should only show "No specific section" which translates to the default system provided section label of "None".

![Screenshot 2020-10-04 at 5 49 55 PM](https://user-images.githubusercontent.com/42177597/95012381-a1748480-066a-11eb-9d99-a56415054342.png)

See discussion in #10595 for more information.

**Comment by gabrielatricak** [comment]
Hi i would like to work on this. Can I be assigned to this?

**Comment by madanalogy** [comment]
> Hi i would like to work on this. Can I be assigned to this?

You can submit a PR that addresses this issue. If anyone else submits a PR before you, we will give you 24 hours to do the same and prioritise your PR for review due to your communication of intent on the issue tracker. I hope that clarifies the matter, let us know if you have any additional questions

**Comment by davidlevinwork** [comment]
Hi! 
I want to help with this issue, probably will finish this today..
This is still relevant?
How do i get this specific file?

**Comment by t-cheepeng** [comment]
Hi @davidlevinwork 
As per the second comment, you can submit a PR for this issue but may not be prioritised.
You can refer to the [developer guide](https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md) for set up instructions

**Comment by EmberCS15** [comment]
Seems like the thread has gone cold. Can I work on it ?
I have the solution ready at hand.

**Comment by madanalogy** [comment]
> Seems like the thread has gone cold. Can I work on it ?
> I have the solution ready at hand.

We recommend not doing more than one issue labelled `good first issue` as their difficulty is specifically targeted towards first-time contributors. However, since we haven't updated the contributing guide for recent changes to the label names, just take note of this when you're looking for new issues to work on (we'll still review your PR if @gabrielatricak doesn't put one up in 24 hours). Let me know if you have any further questions or concerns yea.

**Comment by EmberCS15** [comment]
Copy, thanks for the information.

**Comment by danyshay** [comment]
Hello, 
I would like to work on this and would like to know if there are any PRs done for this?
