### ISSUE TITLE
Cache DB read results between access control check and execution

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#10764]
Due to complete separation of access control check logic and execution logic, there are many repeated operations in between those two groups of action (many of which is DB read). We can consider internally caching the DB read results in order to reduce the number of DB reads.

Using a very simple example of `GetCourseAction`:
Access control check:
https://github.com/TEAMMATES/teammates/blob/1c2b94d63a7be533d96e149223c0f4368bcea1cd/src/main/java/teammates/ui/webapi/GetCourseAction.java#L20-L44
Execution:
https://github.com/TEAMMATES/teammates/blob/1c2b94d63a7be533d96e149223c0f4368bcea1cd/src/main/java/teammates/ui/webapi/GetCourseAction.java#L45-L53

If the access control check passed, we know for sure that the course exists, thus the entire of execution logic (L47-L51) can be skipped. The course object can be cached after being retrieved in the access control check logic, and the execution logic will act based on whether a cached object exists.

This is a very simple example whose cost saving is negligible at best, but there may be actions whose cost saving will be greater when this technique is employed.

**Comment by EmberCS15** [comment]
@wkurniawan07 I had a few questions - 

1. Is the requirement to put another layer in between the DB and the actual client of the DB for caching? If so, a lot of places which interact with the DB would have to be changed.

2. Which DB is being used? Does the DB itself support caching, and are there any side - effects to enabling caching on the DB?

**Comment by wkurniawan07** [comment]
I was not talking about DB caching (maybe I should not use the term "caching" at all). I was talking about just saving the intermediate operation result within the object itself. Caching (in the way that is probably more widely used in the industry) is a different topic altogether.

**Comment by EmberCS15** [comment]
Got it, thanks @wkurniawan07 
I would like to pick this up
Let me go through the code for sometime and if I have more questions I will bug you on the issue a little bit :)

**Comment by EmberCS15** [comment]
So what I can see is that we want to store the result of `logic.getCourse` in the object itself, so that multiple calls can be prevented by simply checking the object first. Seems like a small change.

**Comment by wkurniawan07** [comment]
> Seems like a small change.

It is because I deliberately pick a simple example just to demonstrate the issue. Many other action objects will be way more complicated than this.

**Comment by EmberCS15** [comment]
I have two approaches which all depend on whether courseId to object is a 1:1 mapping or not.

#### If courseId to object is 1:1
We can simply store the Course object in a private variable of Course type.
When retrieving we do the following

```
private final Course course;
.
.
.
.
getCourse(String courseId) {
    if (Objects.isNull(course)) {
        return logic.getCourse(courseId);
    }
    return this.course;
}
```

#### If course to object is a many to 1 mapping

```
private Map<String, Course> courseIdToCourseMap;
.
.
.
.
getCourse(String courseId) {
    if (!this.courseIdToCourseMap.containsKey(courseId)) {
        Course course = logic.getCourse(courseId);
        this.courseIdToCourseMap.put(courseId, course);
        return course;
    }
    return this.courseIdToCourseMap.get(courseId);
}
```

Let me know of any suggestion for these approaches :)

**Comment by wkurniawan07** [comment]
I think you need more understanding on (1) how the action classes work and (2) how many different actions there are. Right now your illustration and probably your design is confined to just the example I gave. In reality, it could be either one of those cases, and it is not necessarily just course objects. It could be feedback session object, student object, instructor object, and many others.

**Comment by EmberCS15** [comment]
Thanks @wkurniawan07 for the feedback

So what I could understand is we need a solution which is modular and adapts for all the actions.

I need some help on the following questions - 

1. What if we introduce the caching at the indivisual logic levels ? I see that Logic is the place where we either update or retrieve the elements.
2. Is the caching required on all results fetched via the logic calls ? Will this caching create some consistency issues for any of the actions if the data in the DB changes and the cache is not updated ?

**Comment by wkurniawan07** [comment]
> we need a solution which is modular and adapts for all the actions.

Not really. I would in fact be (pleasantly) surprised if there is one.

> 1. What if we introduce the caching at the individual logic levels

No. Caching at this layer is already at the realms of proper Redis/Memcached-like caching.

**Comment by EmberCS15** [comment]
Hmm .... That leaves me a little confused. So am I supposed to store each of the read calls on the Indivisual Action level, as an example, the GetCourseAction approaches that I suggested would be similarly applied to all the indivisual actions ?

**Comment by wkurniawan07** [comment]
> So am I supposed to store each of the read calls on the Individual Action level, as an example, the GetCourseAction approaches that I suggested would be similarly applied to all the individual actions ?

Exactly, if caching can save read ops

**Comment by EmberCS15** [comment]
Thanks @wkurniawan07 I will work on it and raise a PR.

In case of any more questions I will reach out to you :)

**Comment by EmberCS15** [comment]
@wkurniawan07 I was going through the unit tests and wanted to see if I could use mockito, is it ok to introduce mockito using gradle ?

**Comment by wkurniawan07** [comment]
After looking at some improvements on #10770 it doesn't look like the improvement will be enough to justify the amount of caching logic added to the code. This issue shall be rendered as invalid.
