### ISSUE TITLE
Add a banner with configurable content

### ISSUE THREAD

**Issue by madanalogy** [TEAMMATES/teammates#10782]
Add a banner to the index page as well as home pages for students and instructors that can have its contents easily configurable. Banner should be dismissible for the user and whether it is displayed at all or not should also be configurable. See discussion in #10780 for more information and https://github.com/TEAMMATES/teammates/pull/10869#issuecomment-748183065 for important discussion points.

**Comment by wkurniawan07** [comment]
Closing as this is not well-defined
