### ISSUE TITLE
subsequent steps can be fused into Stream API chain

### ISSUE THREAD

**Issue by abdullahcevik** [TEAMMATES/teammates#10793]
Hi, I saw some code statements, I think this statements fused subsequent steps into the Stream API chain.

For example:
https://github.com/TEAMMATES/teammates/blob/d2f3d0bb06c4ad45ad2d2ef1f36e47ac54fb55d7/src/e2e/java/teammates/e2e/cases/e2e/FeedbackSubmitPageE2ETest.java#L216

https://github.com/TEAMMATES/teammates/blob/7aff65283ab51cdb8e28cdeb06f5e58d6f540767/src/e2e/java/teammates/e2e/util/BackDoor.java#L617

**Comment by wkurniawan07** [comment]
This is too minor of a change request to be a standalone issue, and the effect to readability/execution speed is marginal at best.
