### ISSUE TITLE
[UI issue][Help for instructor page][Questions section] non uniformity in the full stop at the end of the sentence

### ISSUE THREAD

**Issue by gulshankk** [TEAMMATES/teammates#10806]
[UI issue][Help for instructor page][Questions section] non uniformity in the full stop at the end of the sentence

LIVE TEAMMATES V7.3.1

Steps to reproduce:
1. https://teammatesv4.appspot.com/web/front/help/instr
2. Go to the Questions section

Expected results:
Uniformity in all the answers in the page
The other answers have full stop at the end of the sentence

Actual results:
The full stops are missing in the answers under questions section
<img width="1087" alt="Screenshot 2020-10-23 at 16 36 31" src="https://user-images.githubusercontent.com/73334346/97017785-a08a9080-154e-11eb-9e29-252785f2dfce.png">
<img width="1138" alt="Screenshot 2020-10-23 at 16 36 26" src="https://user-images.githubusercontent.com/73334346/97017795-a2545400-154e-11eb-88f3-ab0805f01944.png">

**Comment by Amit-Anveri** [comment]
The link seems to be not valid ?

**Comment by RestartDK** [comment]
**Does it mean for the text above a full stop should be made after each of those points?**
For example:

Essay questions are open-ended questions that allow respondents to give text feedback about a question.
To set up an essay question:

Specify the question text.
(Optional) Add a description of the question.
Specify the feedback path that should be used to generate the appropriate feedback recipients.

**Comment by Aditya-Ramachandran** [comment]
Hi, I would like to work on this issue, can you suggest me ways get started?

**Comment by rrtheonlyone** [comment]
Hi @Aditya-Ramachandran , there is already an open PR addressing this issue - please take a look at the other open issues we have available!

**Comment by Aditya-Ramachandran** [comment]
Oh okay @rrtheonlyone, I will take a look at the other ones.
Thank you!
