### ISSUE TITLE
User map_Zooming the map and then clicking on the country can list the institutes also along with the number of institutes

### ISSUE THREAD

**Issue by gulshankk** [TEAMMATES/teammates#10803]
- **Environment**: 

**As a user when I would like to know which are all the institutes are present in a selected country along with the number of institutes.**

**Justification**

<img width="1285" alt="Screenshot 2020-10-23 at 14 52 19" src="https://user-images.githubusercontent.com/73334346/97005962-6c5ba380-153f-11eb-8bd2-b2d893f51567.png">

**Comment by madanalogy** [comment]
@damithc need your input on whether this might be a feature we want to support

**Comment by damithc** [comment]
While this is good to have, we work with individual instructors, not institutions. Hence, it would not be appropriate to name the institutions without getting their consent first, which I don't want to get into. 
Nevertheless, thanks for the suggestion @gulshankk
