### ISSUE TITLE
student viewing results: 'not authorized' error shown even if the link is correct

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10802]
Suppose a student in logged into a Google account but has not joined TEAMMATES. Now, she clicks on a ~~submission~~/results link sent by TEAMMATES.

Current: TEAMMATES shows the 'not authorized' error

Suggested: 
* show the page (because the link is correct)
* if the above is not practical to implement, auto-logout the user first and then show the page (we can ask the user first if she wants to join using the current logged-in account -- the logout can be done only if the user doesn't want to join).

**Comment by wkurniawan07** [comment]
> Now, she clicks on a submission/view link sent by TEAMMATES.

@damithc Was this from the same error reported some time back? That one applied to only view results link. The submissions page will act correctly and show the page.

**Comment by damithc** [comment]
> @damithc Was this from the same error reported some time back? That one applied to only view results link. The submissions page will act correctly and show the page.

Ah, I thought it applies to both cases. I've updated the issue to narrow it down to the results page only.
