### ISSUE TITLE
Instructor editing sessions: rename the 'done editing' button

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10809]
![image](https://user-images.githubusercontent.com/1673303/97066361-75a04b00-15e7-11eb-8bac-dc65705a79c8.png)

One user mistook the `Done editing` button to be equivalent to be _Save all edits_.  The confirmation dialog warns that the edits will be lost but apparently, users just click yes without reading.

Perhaps we should rename it `Discard unsaved edits`?

**Comment by thomaslian** [comment]
Hi, there are multiple pages containing this three buttons. I am assunimg that the path below leads to the correct file?

teammates/src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html

**Comment by Suiiyush** [comment]
If no one's currently doing it, Can I work on this issue?

**Comment by rrtheonlyone** [comment]
Hi @damithc , some UI discussion on this change.

What would be the flow to add questions after this change?

<img width="875" alt="Screenshot 2020-12-09 at 9 50 51 AM" src="https://user-images.githubusercontent.com/10579415/101563361-14500200-3a04-11eb-9576-5c022b992688.png">

(4) Might have to be changed to : "You can now click `Discard Unsaved Edits` to remove any unsaved changes you made to the session"

Also on a UX/UI note, is there a real reason to have this feature here in the first place? Nothing wrong but simply navigating away to home (just as you would after "Saving" each question after this change) will remove the unsaved edits.

**Comment by damithc** [comment]
> Also on a UX/UI note, is there a real reason to have this feature here in the first place? Nothing wrong but simply navigating away to home (just as you would after "Saving" each question after this change) will remove the unsaved edits.

Yes, I think so too. Remove it altogether then?

**Comment by rrtheonlyone** [comment]
> Yes, I think so too. Remove it altogether then?

Yes I agree and then we can remove the 4th point completely from below.

<img width="875" alt="Screenshot 2020-12-09 at 9 50 51 AM" src="https://user-images.githubusercontent.com/10579415/101563361-14500200-3a04-11eb-9576-5c022b992688.png">

**Comment by ANANYA7566** [comment]
This issue is still open that means it has not been fixed yet?

**Comment by Derek-Hardy** [comment]
Hi, @damithc. After adding & saving changes to the question, clicking `Done Editing` will often pop out "Discard unsaved fields".

In fact, we need to click `Save` / `Save changes` at the very top of the page to actually "save all edits" for the session before clicking `Done Editing` button to exit, which happens to be at the very bottom.

This counter-intuitive workflow is worsened when there are many questions expanded and also reflected in another request #10819 

In my opinion, a scroll-up button is sensible; and exit button (if there's still one) should be right next to final `Save`.

**Comment by damithc** [comment]
> In fact, we need to click `Save` / `Save changes` at the very top of the page to actually "save all edits" for the session before clicking `Done Editing` button to exit, which happens to be at the very bottom.

Actually, the `save` button at the top is to save settings only. I don't think it saves any questions.
Each question, if edited, needs to be saved individually.
So, I don't think a 'scroll to top' button is needed in this page as the workflow doesn't require the user to scroll to the top at the end of editing.
The 'Done editing' button adds to the confusion without adding much value and in some cases can mislead the user. So, I think the first step is to remove that button entirely. Any further improvements to the save buttons can be done separately.
