### ISSUE TITLE
Browse by topic listing comes over the text

### ISSUE THREAD

**Issue by gulshankk** [TEAMMATES/teammates#10805]
[Help for instructions page][small screen mode]Browse my topic listing comes over the text

LIVE TEAMMATES V7.3.1

Steps to reproduce
1. Go to this page: https://teammatesv4.appspot.com/web/front/help/instructor
2. Reduce the size of the browser

Expected results:
Browse by topics words should not overlap with the info text

Actual results:
Browse by topics words overlaps with the info text

SCREENSHOT attached!

<img width="477" alt="Screenshot 2020-10-23 at 15 54 53" src="https://user-images.githubusercontent.com/73334346/97012393-1a6b4b80-1548-11eb-9871-47ac52c8d6cf.png">

**Comment by madanalogy** [comment]
Recommended fix: hide "Browse by topic" for small screen widths

**Comment by Suiiyush** [comment]
If no one's currently working on this, can I work on this issue?

**Comment by madanalogy** [comment]
> If no one's currently working on it, can I work on this issue?

Sure go ahead, let us know if you need any help

**Comment by Suiiyush** [comment]
Okay so when I try to start the server it says Could not find the module “@angular-devkit/build-angular”, even though I did install the recommended Angular CLI version 9 globally, I have been stuck here since yesterday.

**Comment by Suiiyush** [comment]
Okay I found a StackOverflow discussion about it and this command 

`npm install --save-dev @angular-devkit/build-angular`

helped me fix that error and the server runs now

**Comment by ANANYA7566** [comment]
Hi, is the problem fixed?

**Comment by madanalogy** [comment]
> Hi, is the problem fixed?

There is currently an open PR addressing this issue
