### ISSUE TITLE
[Help for Instructors page][Search field]Enter a word "course" and click on enter twice, the outcome results changes from 31 to 0 search items

### ISSUE THREAD

**Issue by gulshankk** [TEAMMATES/teammates#10804]
[Help for Instructors page][Search field]Enter a word "course" and click on enter twice, the outcome results changes from 31 to 0 search items

LIVE TEAMMATES V7.3.1

Steps to reproduce:
1. Go to this page - https://teammatesv4.appspot.com/web/front/help/instructor
2. Enter "course" in the search field
3. Click on the enter button once
4. First time you will see - 31 results found
5. Now click on the enter button again
6. Search results will be now 0 results found

Expected results:
The search results must same

Actual results:
The search results vary when clicking on the enter button twice

**Comment by sjkadali** [comment]
Hi, I would like to work on this.
