### ISSUE TITLE
Requesting information on missing functionalities

### ISSUE THREAD

**Issue by Duff97** [TEAMMATES/teammates#10814]
Hello!
We're a group of software engineering students of l'ÉTS located in Montreal and we'd like to use Teammates as a subject for one of our projects. 
To put it briefly, we have to analyse and find a solution for a current engineering problem.
For starters, we'd like to know if there are any functionalities that are missing or if users are experiencing specific issues or inconveniences while using Teammates.
We're not looking for a existing bug in the program (we can find plenty in the issue tracker), more like a user inconvenience that could be solved with a new feature or the improvement of a current feature.

If any of you could help us, that would be greatly appreciated!

**Comment by ChooJeremy** [comment]
For this purpose, you can also look through the issue tracker - users do post pain points and feedback into the issue tracker as well, and our admin @damithc posts them as well based on support requests from users.
