### ISSUE TITLE
rich-text boxes: support/disable image uploads

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10815]
Current: when clicking on the image-upload button in a rich-text box input, the user sees this dialog:
![image](https://user-images.githubusercontent.com/1673303/97107778-47fcf400-1704-11eb-9fad-24d252defd8d.png)

Users may not know how to proceed. We might have to improve the UX here, or disable the image upload feature. Note that images uploaded will continue to add to our cost as they will stay in our file storage forever. Perhaps just disable it?

**Comment by wkurniawan07** [comment]
That's not uploading image. That's adding image as link, much like `<img>` tag in HTML.

**Comment by damithc** [comment]
I see. Is there anything we can do to avoid the wrong impression that it's for uploading images? Non-tech users are not usually familiar with 'inserting images by URL' and they will assume it's for uploading an image.

**Comment by wkurniawan07** [comment]
Nope. The entire UI is provided by tinymce. Unless writing/building our own tinymce from scratch is an option.

**Comment by damithc** [comment]
I see. I guess nothing we can do then.
