### ISSUE TITLE
Instructor edit session page: Add scroll to top button

### ISSUE THREAD

**Issue by jasonbch** [TEAMMATES/teammates#10819]
- **Environment**: V7.4.0

**Description of feature/enhancement**
In Instructor Edit Feedback Session in Figure 1.3.1 and Figure 1.3.2, there is no feature to scroll back up if the user is at the bottom of the page. In a Feedback Session with fewer questions, it is not a big issue to scroll back to the top when the user finished with the questions. However, if there are many questions in the session and the questions are expanded, it may take the user a long time to get back to the top of the page. The expand questions button is also located on the top of the page, it means the user only has one way to get back to the top which is by scrolling. 

**Justification**

By adding a scroll to the top button in this page, the user can quickly get back to the top if the user wants to quickly get to other questions at the top of the page. The scroll to top button is implemented to be in the bottom right of the page. It should only show if the user has scrolled a certain amount of the page’s length. The button should also change color if the user hovers on it.

**Existing similar features and their shortcomings**

**Comment by Suiiyush** [comment]
Can you point me to the page where this needs to be added?

**Comment by Suiiyush** [comment]
I want to work on this issue if it's up for the grabs, also can you elaborate on exctly which pages need these features or should I add it to all the pages that require it

**Comment by Moi9** [comment]
Hello, we're a small group of students wanting to work on Teammates, we'd like to tackle this issue as a first contribution is it's still available.

**Comment by tamrakarsweta220** [comment]
Hi, me and my friend want to work on this issue as our first contribution. Can you let me know if we can still work on this?

**Comment by halfwhole** [comment]
@tamrakarsweta220 Sure, please go ahead!
