### ISSUE TITLE
Student submitting responses to MCQ questions: previous comments not shown

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10828]
Steps:
1. A student answers an MCQ question and also gives an explanatory comment with it
2. The student loads the submission page again.
3. Problem: the answers are shown, but not the comments. If the student tries to submit a new comment, an error is shown. Because of this, it's not possible to delete or edit comments given earlier. However, the instructor can see those comments.

**Comment by madanalogy** [comment]
Preliminary investigation shows that the comment is not included in the server response when calling the `/responses` API. Problem is likely in the backend somewhere. Session results call the `/result` endpoint which has the comments included.

**Comment by wkurniawan07** [comment]
Regression due to #10792.

https://github.com/TEAMMATES/teammates/blob/cc625930a011e702f65782bd5fc9edc7b6f9bb46/src/main/java/teammates/ui/webapi/GetFeedbackResponsesAction.java#L80-L91

Line 87 is not accurate because the `FeedbackResponsesData` constructor encrypts the response ID.

**Comment by madanalogy** [comment]
I think we should still keep encryption in the constructor since the data format is supposed to be the API output format. One alternative to simply adding `StringHelper.decrypt` is to cycle through the `responses` instead of the `result` and create each `FeedbackResponseData` one at a time.

**Comment by wkurniawan07** [comment]
That works as well.

**Comment by damithc** [comment]
We need to release this fix soon as students are unable to edit the comments they entered earlier.

**Comment by madanalogy** [comment]
> We need to release this fix soon as students are unable to edit the comments they entered earlier.

Release should be up, apologies for the delay
