### ISSUE TITLE
student accessing an awaiting session: error message not shown

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10823]
A student is trying to access a submission link of a session that no longer exists. She has not joined the course.
The submission page gets stuck at the loading spinner.

![image](https://user-images.githubusercontent.com/1673303/97248696-4aaf3480-183d-11eb-88c8-41989998bdca.png)

Expected: show error message (as a toast message)

EDIT: It looks like this problem applies to cases where a student is trying to access a session that is _awaiting_ (not yet open) e.g., the session open date has been brought forward after the submission link was sent out.

**Comment by wkurniawan07** [comment]
Joining/not is not relevant here.
This is unfortunately not unexpected. The front-end in general has not been optimized for unhappy paths like this.

**Comment by damithc** [comment]
I thought it's supposed to show a 'session deleted' error?

**Comment by wkurniawan07** [comment]
> I thought it's supposed to show a 'session deleted' error?

As a toast message, nothing more.

**Comment by damithc** [comment]
> > I thought it's supposed to show a 'session deleted' error?
> 
> As a toast message, nothing more.

That's good enough. But no toast message is shown in this case.

**Comment by damithc** [comment]
Updated the description. For some reason, the toast message is not showing up as expected.

**Comment by wkurniawan07** [comment]
Actually, someone needs to investigate this. When I said "[it should appear] as a toast message", it's referring to the un-optimized way of handling this. It could already be optimized (e.g. redirect to another page) but not working.

Also, does "no longer exist" mean it never existed in the first place (e.g. a typo) or something that is soft-deleted? The latter might be another thing that is not handled.

**Comment by damithc** [comment]
> Also, does "no longer exist" mean it never existed in the first place (e.g. a typo) or something that is soft-deleted? The latter might be another thing that is not handled.

I checked. Seems it has been soft deleted (still in the recycle bin).

**Comment by damithc** [comment]
> I checked. Seems it has been soft deleted (still in the recycle bin).

Sorry, I was checking the wrong place. The session has been hard deleted (no longer in the recycle bin). I think this is what happened:
1. Instructor created the session
2. The submission link is sent out to students
3. Instructor hard-deleted the session
4. Instructor created another session with the same name in the same course

Not sure if step 4 is what's causing this odd behavior.

**Comment by wkurniawan07** [comment]
1-3 can be considered as non-existent because session is not identified by randomly generated unique key. That means this issue is entirely about session to be open.

**Comment by damithc** [comment]
Actually, there is another possibility.
1. Instructor created the session
2. The submission link is sent out to students
3. Instructor changed the opening date to make it awaiting.

This scenario too is about awaiting sessions, so I guess that's were we need to look.

**Comment by damithc** [comment]
Updated the description. Let's wait for someone to dig into the code to verify if it is indeed a bug affecting _awaiting_ sessions.

**Comment by wkurniawan07** [comment]
Can't really say it's a bug. The session info and questions didn't load exactly because the session is not open for submission, so it's exactly as per what is defined in the business logic. What is right is the user experience should be better.

**Comment by damithc** [comment]
Let's show an appropriate error message for this case. While this situation is not common, when it happens, it can result in a burst of support requests because it looks like the system error from the user POV.

**Comment by lyeyixian** [comment]
Hi, I would like to work on this.
