### ISSUE TITLE
Admin searching for students: also show awaiting sessions

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10824]
Steps:
1. Login as admin
2. Search for a student
3. Expand the panel showing links of the target student

Current: does not show links to awaiting sessions but shows links to open and closed sessions
Expected: show links to all sessions, including awaiting sessions
Reason: it helps identify cases where the student is trying to access a session that has been open before but has changed to awaiting state. otherwise the admin can wrongly deduce that the session has been deleted.

**Comment by gupps17** [comment]
hello, I would like to work on it

**Comment by xyzhang00** [comment]
Hi, I would like to work on this if possible :)
