### ISSUE TITLE
Instructor viewing results: incorrect state shown briefly when expanding the non-submitters panel

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10843]
v7.5.0

When expanding the following panel, an incorrect state 'all have submitted' is shown briefly before the panel is populated.
![image](https://user-images.githubusercontent.com/1673303/99015098-24083200-258f-11eb-8ca7-bf5ef55c260d.png)

**Comment by hhdqirui** [comment]
Hi! I would like to check whether this is still an issue for the current version. I cannot seem to reproduce the bug.
![copy20210729_151459](https://user-images.githubusercontent.com/53338059/127448414-9a5177b2-de8d-46ba-aa80-3671c9aea21a.gif)

**Comment by damithc** [comment]
@hhdqirui I was able to reproduce it once with the latest V8 (beta). Might depend on the number of responses though. In most cases, it didn't happen at all. Try clicking soon after the page loads. Anyway, lowering the severity as the incidence is rare and impact is very low.
