### ISSUE TITLE
Provide a way for instructors to view students' access records

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10859]
Suggested feature: allow instructors to view students' access records of a course. Minimally viewing submission forms and submitting of responses

Reason: Instructors send support requests to check if a certain student has accessed TEAMMATES before the deadline, as they claim to have done. This is currently a labor intensive task for the admin to do.

However, I'm not sure if we have enough data to provide this feature. Probably need to use logs?

**Comment by wkurniawan07** [comment]
Highly not recommended. Logs are not meant for this kind of usage.

**Comment by damithc** [comment]
> Highly not recommended. Logs are not meant for this kind of usage.

Not using logs is fine, but the feature request is still legit (?). 

If not using logs, we need to write more data to the database to keep track of user access, plus periodically purge the data as no point keeping old log data in the database. That's why we used logs for this feature earlier (it was limited to admin users only back then, and the feature got removed in V7).

**Comment by wkurniawan07** [comment]
> the feature request is still legit (?).

I did not object this part.

> That's why we used logs for this feature earlier (it was limited to admin users only back then, and the feature got removed in V7).

- The old feature is for audit/tracing by admin, which is a legitimate usage of all logs. This is an entirely different thing.
- Logs should never be exposed to users (they weren't even exposed to devs).
- Even if we use logs, the source of logging has drastically changed: from page-based to API call-based.

> we need to write more data to the database to keep track of user access, plus periodically purge the data as no point keeping old log data in the database.

Neither of them is an issue.

**Comment by wkurniawan07** [comment]
To be fair, using logs can be a legitimate solution, but it needs to be very targeted and very secured.

**Comment by damithc** [comment]
> To be fair, using logs can be a legitimate solution, but it needs to be very targeted and very secured.

Yup, for example, the log content should not be revealed to the user. Instead, the backend should read the logs, figure out which times the user accessed TEAMMATES, and give only that information to the instructor.
