### ISSUE TITLE
Student submit responses: prompt the student to save a submission confirmation

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10860]
Suggestion: After a student submits responses, prompt the student to save a record of responses locally in some suitable format (rtf, pdf, text?).

Reason: In case the submission is found to be missing in the data base later or the submission doesn't go through for some reason, the student has proof of submission as well as a copy of the responses that can be used in a resubmission.

Some background: 
* There are cases of a student swearing he submitted but there is no trace of a submission in our logs or in the database.
* There are cases where a student says he typed in very long responses and now they have disappeared. Even if the deadline is not over or extended, the user still loses all the work spent typing the responses.
* Although we have confirmation emails, it takes time for the email to come and it's too late when the student realizes the email never came (or don't bother to check for the email anyway), plus the email doesn't contain the responses submitted.

PS:
* If we implement this feature, it should be framed as a 'submission confirmation' so that users don't feel like they are saving a local copy of the submission. It's just that the submission confirmation happen to include a copy of the responses. 
* In fact, we can remove the submission confirmation altogether, saving us about 20% o our email cost.

**Comment by wkurniawan07** [comment]
Resolved by #10861
