### ISSUE TITLE
Student viewing results of team contribution questions: Show the difference between views

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10863]
Current: Here is an example of what a student sees when viewing the results of a 'Team contribution' type question
![image](https://user-images.githubusercontent.com/1673303/101721691-84818500-3ae3-11eb-8efe-4357e8ba8889.png)

Suggested: 
* Add a third row called the `Difference` that gives the difference (i.e., `team_view - my_view`) between the two rows. e.g., -1%, -1%, -1%, +2%
* Give separate tool tips for labels `Team view`, `My view`, `Difference`
* Add the following sentence below the table:
  >Use the table above to compare your view against the team's view of how much each contributed.

**Comment by wkurniawan07** [comment]
> * Add a third row called the `Difference` that gives the difference (i.e., `team_view - my_view`) between the two rows. e.g., -1%, -1%, -1%, +2%

Difference won't make sense for the "others" because those are sorted

**Comment by damithc** [comment]
> Difference won't make sense for the "others" because those are sorted

In V6, the order of `others` was the same in both rows. Did that change in V7?

**Comment by damithc** [comment]
> In V6, the order of `others` was the same in both rows. 

This is IIRC. I could be wrong though.

**Comment by wkurniawan07** [comment]
> In V6, the order of `others` was the same in both rows. Did that change in V7?

No. In both cases both are sorted in descending order.

**Comment by damithc** [comment]
> No. In both cases both are sorted in descending order.

Oh, I see. The first thing is to find is if retaining the order takes a lot of additional effort or it's just a matter of removing the sorting step. Do you happen to know off-hand or will it take some digging up?

**Comment by Syasyazman** [comment]
Hi, I would like to ask if sorting is removed and the order is retained, won't it be easy for students to know which team member received which team view score? Will that compromise the privacy of the contribution feedback?

> > No. In both cases both are sorted in descending order.
> 
> Oh, I see. The first thing is to find is if retaining the order takes a lot of additional effort or it's just a matter of removing the sorting step. Do you happen to know off-hand or will it take some digging up?

Hi, I would like to ask if sorting is removed and the order is retained, won't it be easy for students to know which team member received which team view score? Will that compromise the privacy of the contribution feedback?

**Comment by damithc** [comment]
> Hi, I would like to ask if sorting is removed and the order is retained, won't it be easy for students to know which team member received which team view score? Will that compromise the privacy of the contribution feedback?

Good point. Perhaps we shouldn't do that, given that the change will apply to past sessions as well. Let me close this issue.
