### ISSUE TITLE
Numerical scale question table is not responsive to different browser size

### ISSUE THREAD

**Issue by jianhandev** [TEAMMATES/teammates#10885]
A responsive table will display a horizontal scroll bar if the screen is too small to display the full content. (Example: https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_table_responsive)

The stats table for the numerical question seems to have a fixed width and is not responsive when window is resized, causing issues like the one shown below.

_Notice the table extends beyond the browser width, and to see the whole table content, the user needs to scroll the entire page horizontally instead of just scrolling through the table itself_

![ezgif-7-a2aeae97b203](https://user-images.githubusercontent.com/59337195/102574106-f0d73680-412a-11eb-90b9-a28114075182.gif)

**Steps to reproduce**
1. Login to an instructor's account
2. In the nav bar, go to help > scroll down to 'Questions'
3. Expand 'Numerical Scale Questions' panel
4. Resize the browser window to see the issue highlighted above

Issue was highlighted in #10864

**Comment by Bhaarat-khatri** [comment]
I understand the problem and i want work in this issue.
please tell me what u exactly want a table which is responsive whose size decrease with size brower decrease or something else
please elobrate more..

**Comment by yzia2000** [comment]
> I understand the problem and i want work in this issue.
> please tell me what u exactly want a table which is responsive whose size decrease with brower size decrease or something else
> please elobrate more..

I created a pr addressing this. Its a very simple solution to the issue.

**Comment by Derek-Hardy** [comment]
Here the problem is: 

side-nav has attribute `position: fixed`, which effectively takes the element out of the page flow. Simple margin / padding / set `@media max-width` may not fundamentally help with this issue. 

Instead, we look for ways to allocate column space responsively for `main-body` and `side-nav`. I attempted this issue using bootstrap grid system  #10921.
