### ISSUE TITLE
padding style for ErrorReportComponent

### ISSUE THREAD

**Issue by yhtingg** [TEAMMATES/teammates#10880]
- **Environment**: 

`master` branch at commit `a61aa0da`

**Description of feature/enhancement**

![Screenshot from 2020-12-17 00-07-00](https://user-images.githubusercontent.com/46165274/102374907-d3a44a00-3ffc-11eb-9445-0bec6138d2df.png)

noticed that there is a lack of padding for the `ErrorReportComponent`, perhaps would be good to check if it is intentional, else a suitable padding could be added?

**Comment by damithc** [comment]
> noticed that there is a lack of padding for the `ErrorReportComponent`, perhaps would be good to check if it is intentional, else a suitable padding could be added?

Unlikely it is intentional. Would be good to fix.

**Comment by yhtingg** [comment]
Duplicate of https://github.com/TEAMMATES/teammates/issues/10573
