### ISSUE TITLE
Skip 'closing soon' emails if already submitted

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10901]
Current: TEAMMATES send an automated email to all respondents 24 hours before the session deadline.
Suggested: Skip that email for those who have submitted responses already
Reason: To reduce email cost

**Comment by wkurniawan07** [comment]
Something that I have been wondering for the longest time:

Is "submitted" defined as all the questions that the student/instructor has to answer or answered, or just any non-zero amount of them? e.g. if I have 10 questions to answer but answered only one, does that count as "submitted"?

**Comment by damithc** [comment]
> Is "submitted" defined as all the questions that the student/instructor has to answer or answered, or just any non-zero amount of them? e.g. if I have 10 questions to answer but answered only one, does that count as "submitted"?

As of now, submitting even one question is enough to be considered as submitted.
