### ISSUE TITLE
Resource not found error encountered by user

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10907]
A user reported the following error:
![image](https://user-images.githubusercontent.com/1673303/103532674-a265be00-4ec6-11eb-8761-96147d600b9a.png)

The responses seem to have been saved though.

1. What's the likely cause of this error?
2. Is it possible to improve the error message?

Let me know if you need some info from the logs.

**Comment by wkurniawan07** [comment]
?? That's the submission confirmation that has bern decommissioned. Must be a very badly hit front end cache.

**Comment by damithc** [comment]
> ?? That's the submission confirmation that has bern decommissioned. Must be a very badly hit front end cache.

Indeed. Let's close this then.
