### ISSUE TITLE
Error message while adding instructors. [The server encountered an error when processing your request.]

### ISSUE THREAD

**Issue by srdeotarse** [TEAMMATES/teammates#10919]
Help Request: [Not able to add Instructors , getting Status-FAIL and Message-The server encountered an error when processing your request.]

- **Commit SHA:** Message visible at front dev server
- **Operating System:** Ubuntu 20.04
- **JDK Version:** 11
- **Node.js Version:** v10.19.0
- **Google Cloud SDK Version:** 323.0.0
- **IntelliJ Version (if applicable):**
- **Firefox / Chrome Version (if applicable):** Firefox 84.0.2

**What I was trying to do / What I need help with**

I was trying to add an instructor but received error message [The server encountered an error when processing your request.] as shown below
![image](https://user-images.githubusercontent.com/53873549/104873704-244df080-5977-11eb-9850-dff3f30a4642.png)

**Attempts to resolve the problem**

![image](https://user-images.githubusercontent.com/53873549/104874172-45631100-5978-11eb-8e33-b38e6b082d86.png)

Set the PATH according to above troubleshooting guide.

**Comment by rrtheonlyone** [comment]
Hi there, use JDK 1.8 instead of JDK 11?

**Comment by srdeotarse** [comment]
Thanks @rrtheonlyone I will try with JDK 1.8
