### ISSUE TITLE
Unexpected behaviour when reverting to template feedback path 

### ISSUE THREAD

**Issue by madanalogy** [TEAMMATES/teammates#10917]
**Environment**: Live server at V7.8.0

**Steps to reproduce**

1. Add new essay question to a feedback session
2. Change feedback path to custom feedback path
3. Attempt to revert feedback path to preset template provided

**Expected behaviour**
User interface reverts to template display prior to selecting custom feedback path

**Actual behaviour**
User interface does not change and the visibility options are reset to "deny all"

**Additional info**
![Jan-16-2021 00-04-05](https://user-images.githubusercontent.com/42177597/104752415-97960d80-5791-11eb-9fe5-999fe21ae9f4.gif)

**Comment by t-cheepeng** [comment]
I think this behaviour makes sense? If an instructor changes a feedback path, the visibility should reset itself too as the visibility options don't make sense anymore. 

Unless we want to add a default setting to each feedback path (not sure if that is worth the trouble)

**Comment by madanalogy** [comment]
Anyone addressing this issue then should just focus on the UI component and leave the feedback path portion alone

**Comment by stapletonce** [comment]
Does this bug still need to be worked on?

**Comment by madanalogy** [comment]
Yeap, feel free to give it a shot and let us know if you have any questions or run into any problems
