### ISSUE TITLE
Add a script for the admin to generate a list of active instructors

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10928]
context: We need to inform instructors about the replacement of 'submission confirmation email' with a 'download proof of submission' feature. Otherwise, instructors can end up giving wrong instructions to students.

suggestion: Add a script for the admin to generate a list of emails of instructors who have been active in a certain period in the past.

Example of another admin script `java/teammates/client/scripts/SingleAccountGoogleIdMigrationScript.java`

**Comment by wkurniawan07** [comment]
For me, this is only one form of solution. The real problems are very much still glaring:
- We don't have any means to inform users of updated features
- We don't have any means (from within the system) to communicate to users

**Comment by damithc** [comment]
> For me, this is only one form of solution. The real problems are very much still glaring:
> 
> * We don't have any means to inform users of updated features
> * We don't have any means (from within the system) to communicate to users

Yes, in the long run, we need need such a system. In the interim, this can be used. Plus, this is still needed in case we need to inform users of a 'system down' situation or we need to contact users urgently (without waiting for them to login).

**Comment by madanalogy** [comment]
Could we maybe just make use of a banner like last time? It's the most effective way to communicate with instructors imo, could resolve https://github.com/TEAMMATES/teammates/issues/10782 as well

**Comment by damithc** [comment]
> Could we maybe just make use of a banner like last time? It's the most effective way to communicate with users imo, could resolve #10782 as well

That can work but this is not as time-boxed as the previous case. An instructor might log into TEAMMATES only during just one week in the year. So, we'll have to keep the banner for a long period, which can become an eyesore to those who login frequently.
