### ISSUE TITLE
Adding a new question typo in save button

### ISSUE THREAD

**Issue by madanalogy** [TEAMMATES/teammates#10931]
**Environment**: Live Server at V7.8.0

**Steps to reproduce**
Add a new question to a feedback session, a "new question" box appears.

**Expected behaviour**
Button to save the new question indicates "Save Question".

**Actual behaviour**
Button to save the new question indicates "Save Questions" despite not being able to add any more questions.

**Additional info**
![Jan-24-2021 22-43-06](https://user-images.githubusercontent.com/42177597/105633864-137d0d80-5e96-11eb-91c8-0841ab2c3716.gif)

**Comment by Jellwood** [comment]
I know it seems like this issue was taken, but the linked mention shows a deleted branch and closed pull request? Is this issue still open or should I keep looking for another possible issue? Thank you in advance!

**Comment by madanalogy** [comment]
This issue is still available for first time contributors, feel free to read up on our development guide and send in a PR when you're ready

**Comment by raman-thakur** [comment]
So, here we only need to change the button  "Save Questions" -->> "Save Question" ??

**Comment by samuelshix** [comment]
Hey, I'm new to contributing to open source projects on GitHub. How do I get started to contribute to this issue?
