### ISSUE TITLE
Submission links sent to instructors: Also give join link if not joined yet

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10952]
Scenario:
* A session has questions to be answered by instructors
* Instructors are sent emails containing a link to submit responses
* Unlike links sent to students, instructors need to join the course before they can submit responses

Suggestion:
* If the instructor has not joined yet, the email can also contain the join link with a note that they need to join before they can submit. If not, some might attempt to submit and contact us for tech support saying they receive an 'unauthorized user' error.

**Comment by pPris** [comment]
Hi, may I work on this issue? It seems still applicable to the current version of teammates.
