### ISSUE TITLE
Migrate Objectify 5 to Objectify 6

### ISSUE THREAD

**Issue by Derek-Hardy** [TEAMMATES/teammates#10955]
This issue keeps track of PRs developing features in the title.

**Environment**: 
All PRs for this feature should be made against `objectify-v6-migration` branch **[⚠️ IMPORTANT]**

**Description of feature/enhancement:**
See https://github.com/TEAMMATES/teammates/wiki/Google-App-Engine-Runtime-Upgrade for project details.

**Related past issues:**
#9131

Epic will be resolved after merging of feature branch to master.

**Comment by wkurniawan07** [comment]
I modified the title. Upgrading to GAE 2nd generation runtime entails a lot of things and this is only one of them.

**Comment by Derek-Hardy** [comment]
@wkurniawan07 Yeah.. technically we can just use #9131. Then I will pin the issue and reference existing PRs to that?

**Comment by madanalogy** [comment]
I think we can just stick to using this issue since it's already up, I'll close the older one
