### ISSUE TITLE
Instructor Audit Logs Frontend

### ISSUE THREAD

**Issue by t-cheepeng** [TEAMMATES/teammates#10969]
**Description of feature/enhancement**
Frontend UI for instructor audit logs page

**Preliminaries**
The expected user flow for the logs page is
- Click Logs -> Select date and time to search logs from -> Select date and time to search logs to -> Select the particular course id to search for -> Hit search/filter button and retrieve data. Once data is retrieved, there are two different layout for the presentation of data that we possibly see.

- Option 1
![audit-logs-wireframe-v1](https://user-images.githubusercontent.com/28994607/108170439-256c6c00-7135-11eb-9a03-6867733cd129.png)
- Option 2 (Preferred)
![audit-logs-wireframe-v2](https://user-images.githubusercontent.com/28994607/108170445-269d9900-7135-11eb-90c7-bc9f3709f088.png)

**Justification**
Instructors can now view the access time and submission time of students for feedback submissions without contacting administrator of system

**Comment by t-cheepeng** [comment]
@damithc Updated mockup for audit logs page. If ok, we can proceed with this design

![audit-logs-wireframe-v3](https://user-images.githubusercontent.com/28994607/108582183-7d40e800-736c-11eb-825b-40d50cd8f54c.png)

**Comment by damithc** [comment]
> @damithc Updated mockup for audit logs page. If ok, we can proceed with this design

Student name is going to be a drop down or typing?
Should some columns in the table be sortable? e.g., name
Can provide optional filtering by the session?
The end time can be optional (current time being the default)
'Audit logs' is an internal term. Use a more user-friendly term?
I assume the times are in user's timezone?

Anyway, the above are not fundamental; can do along the way.

**Comment by t-cheepeng** [comment]
@damithc 
As per the previous discussion, all columns in table are sortable and the times are in user's timezone. The default sort when the tabs are expanded is using student's name. 
The search results largely look similar to the wireframe

![image](https://user-images.githubusercontent.com/28994607/111447653-9a3cc100-8748-11eb-8ca9-65aa7a0aefe6.png)

**Comment by damithc** [comment]
> ![image](https://user-images.githubusercontent.com/28994607/111447653-9a3cc100-8748-11eb-8ca9-65aa7a0aefe6.png)

Activity type: the cell value needs to be meaningful to the user e.g., `Access` is not explanatory enough
Should the time be the first column? That's usually the case when you go through a log.
Most likely the activities will be confined to one session. Are we going to show empty tables for other sessions?

**Comment by t-cheepeng** [comment]
@damithc  Swapped time to be first column along with the type and changed wording
![image](https://user-images.githubusercontent.com/28994607/111626926-7c935880-8829-11eb-90d1-c0167557ac76.png)

>
>
>Most likely the activities will be confined to one session. Are we going to show empty tables for other sessions?

Not sure what you mean by this? Is it if we retrieve no logs for a particular feedback session for the given search period? If that's the case, we can either choose to not display the tab or display it but add in a message saying no results found for this particular session

**Comment by damithc** [comment]
`Activity type` -> `Activity`
Can use these:
* viewed the submission page
* submitted responses

How about this order? time, name, activity, email, section, team. This is assuming people read right to left (i.e., put more important info on the left).

If showing sessions without any activities, show them at the bottom of the page (i.e., active sessions should be on top) and greyed out. But this one is purely cosmetic and can be as a separate PR later.

**Comment by t-cheepeng** [comment]
@damithc 
Implemented the changes and it looks like this now
![image](https://user-images.githubusercontent.com/28994607/111744918-e9106500-88c6-11eb-9a45-43f0eb79eba9.png)

**Comment by damithc** [comment]
Some points to consider:
* Activity Time -> Time?
* Should we show the seconds too? A lot can happen within a minute
* For the date picker, show the same date style as elsewhere. I think we want to pick a style that is clear for both US and non-US users.
* Submitted response -> Submitted responses
* Any reason for using green panels here? i.e., was it chosen based on some internal UI guidelines?

**Comment by t-cheepeng** [comment]
@damithc 
![image](https://user-images.githubusercontent.com/28994607/111857968-2f6dce80-8970-11eb-921f-7b529c3e1848.png)

>Activity Time -> Time?
> Should we show the seconds too? A lot can happen within a minute
> For the date picker, show the same date style as elsewhere. I think we want to pick a style that is clear for both US and non-US users.
> Submitted response -> Submitted responses

All above changed

> Any reason for using green panels here? i.e., was it chosen based on some internal UI guidelines?
No, there is no set guideline for choosing the panel colour. The green was choosen to mimic the GRQ/RGQ/etc... views in session results

**Comment by damithc** [comment]
> All above changed

Good. No further UI/UX feedback from me for the moment.

**Comment by madanalogy** [comment]
To take note of https://github.com/TEAMMATES/teammates/pull/11074#discussion_r606931020 when developing frontend for release to end users

**Comment by wkurniawan07** [comment]
Closing for reason similar to #10859: feature has been done, release is another story.
