### ISSUE TITLE
Manager-level instructor cannot view results of a session

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10973]
v7.9.0
Reported by a user
![image](https://user-images.githubusercontent.com/1673303/108614937-02460300-743a-11eb-8223-01fc4f632477.png)

![image](https://user-images.githubusercontent.com/1673303/108614932-ee020600-7439-11eb-9ee1-9abb61bb5417.png)

Let me know if cannot reproduce.

**Comment by madanalogy** [comment]
That's weird, managers should have `CAN_VIEW_SESSION_IN_SECTIONS` permissions, unless there was an API error in retrieving the permissions. Anyone else able to reproduce the error? Can't seem to replicate it on my dev server.

**Comment by wkurniawan07** [comment]
This looks like a bug, but the reproduction scenario is very specific. @damithc was the instructor in question given some kind of custom privilege before, then it was changed to manager?

**Comment by damithc** [comment]
> This looks like a bug, but the reproduction scenario is very specific. @damithc was the instructor in question given some kind of custom privilege before, then it was changed to manager?

Let me check with the user and get back.

**Comment by damithc** [comment]
User says permissions was changed from co-owner to manager in an attempt to resolve this, which means the problem was present even when she had co-owner permissions. Although the user didn't mention it, she may have been given custom permissions earlier without her even knowing about it. She doesn't have the same problem in other courses, which means it is something specific to this course/session. 

We can try to reproduce it by giving custom permissions first and then moving back to co-owner or manager.

**Comment by wkurniawan07** [comment]
@damithc I know the steps I mentioned will reproduce the case. I just need the confirmation that it is what happened here and not anything else.

**Comment by damithc** [comment]
From another user who has been experimenting with custom permissions (might be related to this issue):
>1) I might be missing something but there seems to be a wrong validation that does not allow he instructor use the VIEW option, whether the session has been published or not (image capture attached to this message). 
>
>2) When using the DOWNLOAD RESULT option the instructor can get the file with entries only from his/her section which is perfect.  However,  it only can be done when the results have been published.   It would be great to download them also when results have not been published yet, so the instructor can have a backup of the feedback already entered just in case anything happen.
>![image](https://user-images.githubusercontent.com/1673303/108802372-140ede00-75d3-11eb-970a-0a573334b3c9.png)

**Comment by wkurniawan07** [comment]
Fixes in #11258
