### ISSUE TITLE
Provide a 'today' button in date picker

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10979]
Suggestion: Provide a 'today' button in date pickers so that the user can easily navigate to the calendar of the present time. This is especially useful when an instructor copies an old session and updates the dates to match the current semester (which is a very frequent use case).

![image](https://user-images.githubusercontent.com/1673303/108946690-e50f6f80-7699-11eb-9021-f7a3daee269f.png)

Also, it is nice if the current date is visually identifiable (e.g., a different shade) ~~or the past dates are visually different (e.g., dimmed) from present/future dates~~.

**Comment by syrinemahmoud** [comment]
that sounds a good idea for improvement
