### ISSUE TITLE
Inconsistency in opening contact page

### ISSUE THREAD

**Issue by amarlearning** [TEAMMATES/teammates#10987]
In the footer section of the home page, `Become a sponsor` and `send feedback` both the HTML link redirects to the `contact` page. The only difference is `send feedback` has `target=_blank` while the `Become a sponsor` link doesn't have `target=_blank`.

![imageedit_3_4198622514](https://user-images.githubusercontent.com/9383897/109388083-edcaa480-792a-11eb-98a5-cba11fe79ccc.png)

<span style="color:blue">I am not sure if this is on purpose and it's a bug.</span>

```diff
+ I am not sure if this was on purpose or it's a bug.
```

**Comment by madanalogy** [comment]
@damithc was there any intent to have only one link open in a new tab?

**Comment by damithc** [comment]
> @damithc was there any intent to have only one link open in a new tab?

I don't think so.

**Comment by madanalogy** [comment]
Anyone tackling this issue should fix the behaviour such that both links open in a new tab then

**Comment by amarlearning** [comment]
I believe if the hyperlink is of the same website, then `target=_blank` should not be used. Just like all the hyperlinks in the `Features` page open in the same tab even the contact page link at the end.

**Comment by damithc** [comment]
> I figured since it was in the footer the links are accessible anywhere, and a user might be say filling in a submission halfway when encountering some problems. @damithc any opinion on the behaviour of the links?

@amarlearning's idea is a good baseline but we can deviate if it makes sense. I don't mind opening these in a new tab to avoid the possibility of a user accidentally overwriting a computationally heavy page (e.g., session results) that is currently loaded with one of these. But I'm OK either way.
