### ISSUE TITLE
Instructor setting question options: support generating options from team members

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10981]
Shouldn't there be options `team members` and `team members excluding self` here?
![image](https://user-images.githubusercontent.com/1673303/109038345-9815b280-7706-11eb-930f-09a5ec391f02.png)

**Comment by wkurniawan07** [comment]
There never was. Also, that option only makes sense if the giver is students.

**Comment by damithc** [comment]
> There never was. Also, that option only makes sense if the giver is students.

Yes, it can be only for cases where the giver is a student.
We can add it as the use case is legit. In fact this was reported by a user.
