### ISSUE TITLE
improvement in the contact page ( design ) 

### ISSUE THREAD

**Issue by syrinemahmoud** [TEAMMATES/teammates#10995]
**Issue title: improvement in contact page (Design)

**Description of feature/enhancement
The feature ' Contact Us' , can be improved with 2 methodes : 
it can be either improved and putted in the navbar (as ot is now) , or it can be as a footer at the end of the home page 
Ideally , it should be  in the navbar  , but with some modifications in the design 

**Justification
The contact page is minimalistic , we can bring some modifications in order to attract more users 
It may be more attractive for the platform users and/or visotors . It can also help porfessors and students get in touch with developers and app owners in case they have something to add , or to ask for .
The contact page may contain facebook page or twitter page , in which platform users share their user experiences and give feedbacks .
Components maybe arranged into boxes instead of line ( design improvement)

**Comment by Derek-Hardy** [comment]
> it can be either improved and putted in the navbar (as ot is now)

I am not sure what do you mean here. Which navbar are you referring to?

> it can be as a footnote at the end of the home page

The current footnote already has `Feedback` and `Become a sponsor` redirection to the 'Contact Us' page.

> Components maybe arranged into boxes instead of line

You could probably elaborate a bit more on this (with illustration if possible).

**Comment by Derek-Hardy** [comment]
Nonetheless, the idea of bringing the 'Contact Us' page to the last section of 'Home' is interesting.

**Comment by syrinemahmoud** [comment]
Thank you for your  interaction @Derek-Hardy 

1- Components maybe arranged into boxes instead of line
You could probably elaborate a bit more on this (with illustration if possible).
-> Actually , i'm thinking about something similar to that , just for a design perspective , if we want it to be in the footnote , something similar to this could be a nice idea I think 
![image](https://user-images.githubusercontent.com/56481359/109859521-5a141380-7c5d-11eb-95b0-adae499f7489.png)
Or that 
![image](https://user-images.githubusercontent.com/56481359/109860400-651b7380-7c5e-11eb-9f09-8d24ae3b519e.png)


2- I am not sure what do you mean here. Which navbar are you referring to?
-> This one 
![image](https://user-images.githubusercontent.com/56481359/109859912-cabb3000-7c5d-11eb-98d0-64cef2f08a37.png)







> Nonetheless, the idea of bringing the 'Contact Us' page to the last section of 'Home' is interesting.
> 
> More people might indeed scroll to the bottom than click re-direction in the foot note. Is there a reason for 'Contact Us' to be a separate page in current design? @damithc

yes i think it's easier and more helpful for users @Derek-Hardy

**Comment by wkurniawan07** [comment]
Closing as this is not a priority right now
