### ISSUE TITLE
Submission after deadline: handle proof-of-submission

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10994]
Steps:
1. Student opens the session before the deadline is over (but very near to it)
2. Student clicks the submission button after the deadline is over

Would the student still receive a proof-of-submission file?

A user reported a case where the student says he received a proof file but the file seems to be empty expect the header information at the top. The timestamp at the top of the file indicates the above scenario happened.

**Comment by damithc** [comment]
Can someone take a look at this? I occasionally hear of cases where the proof of submission file is empty except for the header info.
![image](https://user-images.githubusercontent.com/1673303/117911242-06364280-b310-11eb-9c55-44e19fcb8648.png)

In such cases, it is better if we can make it clear that the submission didn't go through.

**Comment by damithc** [comment]
Another case, possibly related (screenshot sent by student)
![image](https://user-images.githubusercontent.com/1673303/120955612-532cfd80-c784-11eb-8e75-95db3807c5dd.png)

This time, the timestamp in the screenshot indicates it was _before_ the deadline.
Is it because the student didn't fill in the answers?

**Comment by wkurniawan07** [comment]
> Is it because the student didn't fill in the answers?

No. Empty answer will still print the question details.
The only scenario for empty proof of submission file is all requests for saving failed. Submission after deadline is a possible cause but not the only cause.
That, or the proof of submission is forged.

**Comment by wkurniawan07** [comment]
Closing as there is no recent occurrence.
