### ISSUE TITLE
V7.11.1

### ISSUE THREAD

**Issue by madanalogy** [TEAMMATES/teammates#11000]
Scheduled for Wednesday, 3 Mar 2021, 4pm SGT .

Release Lead:

- [x] Tagged the latest stable release code with the latest version number
- [x] Released changelogs

PM:

- [x] Deployed the new version
- [x] Released the new version for end users

**Comment by madanalogy** [comment]
[V7.11.1](https://github.com/TEAMMATES/teammates/releases/tag/V7.11.1) has been released by @madanalogy at March 3rd, 2021, 03.06pm SGT.

Code contributions from: @halfwhole, @madanalogy
Review contributions from: @ChooJeremy, @damithc, @madanalogy

Ready for post-release check and deployment by PM (@damithc).

**Comment by damithc** [comment]
Deployed and released. Thanks for the quick fix.
