### ISSUE TITLE
Requesting modifications in  'About' page 

### ISSUE THREAD

**Issue by syrinemahmoud** [TEAMMATES/teammates#11004]
Issue title: [Request modification on 'About 'page] 

**Description of feature/enhancement**
Actually , I'm thiniking of arranging contributors according to their experience, positions and field of activity.
The type or form of contribution can also be a good point to add about past contributors 

**Justification**
This might be helpful for users to contact contributos easily , in case they need them ( for example a cs student can contact a past cs engineer contributor to ask for something )
This can be helpful for new contributors to have an idea about which type of contribution can bring a good added value to the platform

**Comment by wkurniawan07** [comment]
Closing as this is not a priority right now
