### ISSUE TITLE
Optimize frontend result page fetching

### ISSUE THREAD

**Issue by moziliar** [TEAMMATES/teammates#11015]
Part of #11011 

**Description of feature/enhancement**

- [ ] Utilize the updated backend endpoint to achieve loading response by section and question
- [ ] Replace spinner with progress bar

**Justification**

Loading by section and question mitigates the backend server load in large courses.
In the case of long response loading, we would need to show the user there has been progress made.

**Comment by syrinemahmoud** [comment]
i will try to take care of this , that sounds good idea of improovement for frontend

**Comment by moziliar** [comment]
Hi @syrinemahmoud, can you take a look at the existing PR linked to this issue #11017 and see if there's any other areas that could improve this issue otherwise? Would appreciate any suggestion of course.

**Comment by syrinemahmoud** [comment]
@moziliar , thanks for intercation 
Of course , this would be a great pleasure for me , i'll try to suggest something , and i will share with you my proposed solution as soon as I finish it .
