### ISSUE TITLE
Consider combining Responsive and Adaptive Strategies

### ISSUE THREAD

**Issue by dastansultanov** [TEAMMATES/teammates#11026]
**Description of feature/enhancement**
Consider using the adaptive web design approach, which uses static layouts. Or consider combining Responsive and Adaptive Strategies.

**Justification**
I found out that the website has some problems with displaying some elements in comparatively small displays. For instance, the incorrect display of the "Add new Course" button; margin size between elements such as buttons is not appropriate; the border size of the "sort by" element is not appropriate.(checked on Apple Iphone 7 ). It will be enough to consider most common screen widths and make a specific layout for each of them. It could be thought that it is not so important, but, according to the recent studies, number of students using their smartphones for learning is constantly increasing. In addition to that, one of the main aims of the project is "To become the most _flexible_ free peer feedback tool on the web". So, in order to be flexible enough the implementation of the mentioned feature should be considered.

**Comment by Derek-Hardy** [comment]
Hi @dastansultanov Thanks for contributing this great idea!

We have recently migrated our frontend technology and admittedly there are still lots of defects in responsive design here and there that need to be improved.

Adaptive design has its merit indeed as you mentioned. It's common to have six screen size for a single page to provide a smooth UX. We might have to weigh between the site maintenance budget and potential return before proceeding.

**Comment by wkurniawan07** [comment]
Not a priority at the moment.
