### ISSUE TITLE
Modification to "Download Results" button in session table component

### ISSUE THREAD

**Issue by teikjun** [TEAMMATES/teammates#11030]
**Background Information**
In https://github.com/TEAMMATES/teammates/pull/10960, the "Download Results" button in Feedback Session Results page was modified. Instead of fetching all results at once, the results are fetched in batches to avoid API timeout. Also, the user is shown a modal containing download progress. 

**Issue**
The session table component (found on both "Home" and "Sessions" tabs) also contains the "Download Results" button. However, this "Download Results" button was not modified. It still fetches all results at once and may exceed the API time limit.

Unlike the Feedback Session Results page, the Session table component can contain multiple sessions. 

![image](https://user-images.githubusercontent.com/46853051/111032558-cbb34500-8447-11eb-8571-62f0b22003cf.png)

**Possible solutions** 
1. Load all the `feedbackQuestionId` for the relevant session after user hits "Download Results". Then, break down the download in batches (partitioned by `questionId`).
(Rationale: We need `feedbackQuestionId` of the session in order to break down the download to question-level. But, it is not desirable to load `feedbackQuestionId` of all the sessions on the page at the start - the page would load very slowly if there are many sessions. Hence, we load them on demand)
2. Remove the "Download Results" button from session table. Users can download through "View Results" > "Download Results".
3. Leave it as it is - "Download Results" on session table may exceed the time limit for large courses, but it is convenient for small courses. Users with large courses can use "Download Results" on session result page to process the download in batches.

**Remarks**
After https://github.com/TEAMMATES/teammates/pull/11017#issuecomment-797970523 is merged, the results will be partitioned by both `questionId` and `sectionName`. In possible solution no. 1 above, we'll need to fetch all the `sectionName` for the relevant course as well.

**Comment by damithc** [comment]
I think option 3 will be hard to explain to users. I'd rather avoid that.
Why can't the same mechanism (and the code) be used in both places? It's the same functionality, right?

**Comment by moziliar** [comment]
My feel about all these workflow changes are that they can always be automated. If user has to click "View Results" > "Download Results", my take is that it could be automated via solution 1. This should not be a problem if the download now fetches the necessary info (question id, section name) before commencing the same download as the result page.

**Comment by teikjun** [comment]
I agree that option 3's inconsistent behavior will be confusing. I also think that option 1 is the most sensible. 

We can use a similar mechanism in both places. There are two main differences:
- In Feedback Session Page, `feedbackQuestions` are already fetched when the page is first loaded (in order to load the question tabs). In session table component, we'll need incur the additional performance overhead of fetching `feedbackQuestions`.
- Unlike the Feedback Session page, the session table component can contain many sessions. If we apply the same idea, we would be fetching `feedbackQuestions` for all sessions on page load. The performance overhead is expected to be significant when there are many sessions.

To improve the performance, we can fetch `feedbackQuestions` only on demand. When the user clicks "Download Results", we fetch `feedbackQuestions` only for the corresponding session - this is suggested in option 1.

I'll try out both ideas (fetching everything on page load and fetching on demand), and find out which one is actually better!

**Comment by damithc** [comment]
> I'll try out both ideas (fetching everything on page load and fetching on demand), and find out which one is actually better!

I think on demand fetching is the way to go. We shouldn't add unnecessary database read to a page that is as frequently used as the home page.

**Comment by teikjun** [comment]
Agreed, I'll go with the on demand fetching approach
