### ISSUE TITLE
Objectify V6 migration incompatibilities

### ISSUE THREAD

**Issue by jianhandev** [TEAMMATES/teammates#11038]
**Setup**
---
Dev server running Objectify V6, connected to staging server running Objectify V5.

**Submit feedback response**
---
| Staging | Local |
| --- | --- |
| <img width="1280" alt="Screenshot 2021-03-17 at 3 09 58 PM" src="https://user-images.githubusercontent.com/59337195/111432017-71600000-8737-11eb-9953-d1b485ecd91e.png"> | <img width="1280" alt="Screenshot 2021-03-17 at 3 09 48 PM" src="https://user-images.githubusercontent.com/59337195/111432044-7b81fe80-8737-11eb-8943-223926f6871b.png"> |

Result is **NOT** visible.

**Add course**
---
| Staging | Local | 
| --- | --- | 
| <img width="1280" alt="Screenshot 2021-03-17 at 3 46 28 PM" src="https://user-images.githubusercontent.com/59337195/111432943-a1f46980-8738-11eb-9f1a-b607e722736a.png">| <img width="1280" alt="Screenshot 2021-03-17 at 3 47 12 PM" src="https://user-images.githubusercontent.com/59337195/111432921-9d2fb580-8738-11eb-87f2-f23e8a6bc534.png"> |

Result is visible.

**Add instructor**
---
| Local | Datastore | 
| --- | --- | 
| <img width="1279" alt="Screenshot 2021-03-17 at 4 12 30 PM" src="https://user-images.githubusercontent.com/59337195/111436036-796e6e80-873c-11eb-87ec-555887789056.png"> |<img width="936" alt="Screenshot 2021-03-17 at 4 14 03 PM" src="https://user-images.githubusercontent.com/59337195/111435866-47f5a300-873c-11eb-91da-a52749ad7bfc.png">|

However, instructor does not appear in Admin Search (on staging server):

<img width="1280" alt="Screenshot 2021-03-17 at 4 20 36 PM" src="https://user-images.githubusercontent.com/59337195/111436327-ceaa8000-873c-11eb-89d8-6b59af26f059.png">

**Add feedback question**
---
| Staging | Local |
| --- | --- |
| <img width="1280" alt="Screenshot 2021-03-17 at 3 19 38 PM" src="https://user-images.githubusercontent.com/59337195/111431440-c2232900-8736-11eb-99cb-53395ef30c3f.png"> | <img width="1280" alt="Screenshot 2021-03-17 at 3 19 47 PM" src="https://user-images.githubusercontent.com/59337195/111431432-bfc0cf00-8736-11eb-986b-897cbd58d4c9.png"> |

Result is visible.

**Add feedback session**
---
| Staging | Local |
| --- | --- |
| <img width="1279" alt="Screenshot 2021-03-17 at 3 22 33 PM" src="https://user-images.githubusercontent.com/59337195/111430933-11b52500-8736-11eb-9c01-8e86b8aff436.png"> | <img width="1279" alt="Screenshot 2021-03-17 at 3 23 17 PM" src="https://user-images.githubusercontent.com/59337195/111430946-17ab0600-8736-11eb-86d6-a7b2b4fbffb4.png"> |

Result is visible.

**Enroll student**
---
| Staging | Local |
| --- | --- |
| <img width="1280" alt="Screenshot 2021-03-17 at 4 26 46 PM" src="https://user-images.githubusercontent.com/59337195/111437268-db7ba380-873d-11eb-8773-5ceeda941b12.png"> | <img width="1279" alt="Screenshot 2021-03-17 at 4 27 49 PM" src="https://user-images.githubusercontent.com/59337195/111437276-df0f2a80-873d-11eb-997a-e5a3e665b617.png"> |

Result is visible.

**Comment by jianhandev** [comment]
Submitted a feedback response from the local dev server (V6) connected to staging server (V5). Datastore shows that the response is indeed added, but it is not visible on the webpage.

<img width="1012" alt="Screenshot 2021-03-17 at 4 51 00 PM" src="https://user-images.githubusercontent.com/59337195/111440083-f69be280-8740-11eb-9b98-7616d579a18e.png">

**Comment by Derek-Hardy** [comment]
Create/Edit the same `FeedbackResponse` on local v6 and staging v5 servers will save entities to different ID. 

<img width="941" alt="Screenshot 2021-03-18 at 17 31 39" src="https://user-images.githubusercontent.com/32880438/111604323-2f56bd00-8810-11eb-9cdc-9086344a848e.png">

As shown in console above, modifications made on the same response are saved into 2 different entities.

**Comment by wkurniawan07** [comment]
Work is done
