### ISSUE TITLE
providing access to non subscribers to have an ide

### ISSUE THREAD

**Issue by syrinemahmoud** [TEAMMATES/teammates#11040]
Issue title: [providing access to non subscribers]

**Description of feature/enhancement**

providing access to non subscribers to have an idea about different goods provided by the platform .
This may increase the number of subscribers and may be beneficial to the project owner @damithc 

**Justification**
non subscribers cannot use the platform unless , they have a university account , so they cannot see different benefits of the platform 
This could be helpful for people who are seraching for this kind of platforms

**Comment by moziliar** [comment]
Can I clarify what you mean by "the platform"? And what ide is that you are talking about? And who are the subscribers and subscribers to what?

**Comment by damithc** [comment]
Thanks for the suggestion @syrinemahmoud 
TEAMMATES is optimized for education use although we do provide accounts for non-education use if someone asks. But we don't have plans to optimize for non-education use.
