### ISSUE TITLE
Burst of concurrent requests causing high amount of instance uptime

### ISSUE THREAD

**Issue by daongochieu2810** [TEAMMATES/teammates#11071]
**Environment**: Production
 
**Description**
The production server has been hit by high amount of instance uptime in recent days because a course with 50 open sessions is now ongoing. The guilty page is student home page: it will fetch the response status of all sessions in the table in parallel. 50 parallel requests is an almost 100% guarantee to spin up new instance.

**Proposed solutions**:
- Batching: Group individual request into batches of reasonable size and fire the API calls with the batches
- Sequentialization: Make the calls synchronous

**Comment by moziliar** [comment]
A rough scan of the data path at the backend shows that the `/webapi/hasResponses` endpoint can be optimised to consume O(N) space where N is the number of feedback sessions queried. Batching is reasonable as each `hasResponses` call consumes reasonably small amount of compute resources and therefore could be handled at a larger granularity.

The uncertainty that ensues would be whether this indeed prevents GAE from spinning up new instances, as the auto-scaling policy is said to be a multi-factor one without much details revealed; we could only observe the before-after change and determine if such change is sufficient.

Sequentialization affects the existing UX, although the extent might be minimum should the existing latency be already low; it does not require backend update and hence would be cleaner.
