### ISSUE TITLE
Enrolling students: show a progress indicator when enrolling a large class

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11086]
v7.13.0

When a large class is being enrolled in one go, perhaps we should show some progress indicator? Currently, we only show a spinner which can cause the user to think the enrolling is stuck.

**Comment by moziliar** [comment]
@damithc for sure. I believe the progress circle module can be used in this case. @teikjun possible to port it over here too?

**Comment by teikjun** [comment]
sure, no problem!

**Comment by ezhang641** [comment]
Hello, I have added the progress indicator, so can I please get assigned this issue to open a pull request?

**Comment by teikjun** [comment]
@ezhang641 Sure, please feel free to open a pull request
