### ISSUE TITLE
Instructor edit questions: tweak option order for generating answers from teams

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11085]
v7.13.0

![image](https://user-images.githubusercontent.com/1673303/113577387-c666a600-9653-11eb-8971-8badf7519d32.png)

Shouldn't these two be together?

**Comment by tlhuynh** [comment]
Hi, I would like to try this issue.

**Comment by moziliar** [comment]
@tlhuynh sure! Please go ahead.
