### ISSUE TITLE
Enrolling students: clear red background upon submission

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11084]
v7.13.0

Steps:
1. I enrolled students, but with some invalid data
2. Frond end highlighted the problem rows in red
3. I fixed the problems and submitted again
4. Enrolling was successful but those rows remained red

Suggested: clear the error highlighting when the user clicks the 'submit' button. Highlight again only if there are remaining errors.

**Comment by damithc** [comment]
@daongochieu2810 Can we fix this soon? I'd rather wait till this is fixed before releasing this feature to users.

**Comment by daongochieu2810** [comment]
@damithc Yes I will fix this now. Just a note that users can clear error highlighting by clicking on cells
