### ISSUE TITLE
Audit logs: restrict viewing and searching permissions to course owners

### ISSUE THREAD

**Issue by halfwhole** [TEAMMATES/teammates#11099]
**Description of task**

It could be better for only course owners to be allowed to access the audit logs feature, and not all instructors in general.
 
Both the frontend and backend will likely need to be changed, by restricting access to the `/web/instructor/logs` page and the backend logs searching endpoint.

**Comment by damithc** [comment]
@halfwhole What's the current status? All instructors can access it?

**Comment by t-cheepeng** [comment]
@damithc Yes, now all instructors can access the page and search

**Comment by damithc** [comment]
> @damithc Yes, now all instructors can access the page and search

I see. Perhaps leave it be. After all, no confidential info is being released.
Alternatively, we can limit it to owner and manager levels?

**Comment by wkurniawan07** [comment]
> owner and manager levels

Talking about "levels" doesn't really make sense. Instructors operate based on individual permissions.

**Comment by damithc** [comment]
> Talking about "levels" doesn't really make sense. Instructors operate based on individual permissions.

Sorry, to be more specific, I was referring to access levels of individual instructors:
![image](https://user-images.githubusercontent.com/1673303/114352431-70878600-9b9e-11eb-9461-1f93bed15b18.png)

**Comment by wkurniawan07** [comment]
It doesn't change what I said. An access level is just a collection of individual permissions.

**Comment by damithc** [comment]
> It doesn't change what I said. An access level is just a collection of individual permissions.

But we do have a way to identify instructors who have been given these specific roles, yes? From the end-user's POV, that seems to be the case.

**Comment by damithc** [comment]
> But we do have a way to identify instructors who have been given these specific roles, yes? From the end-user's POV, that seems to be the case.

Is it the case that although we can identify roles, the current access control layer cannot actually take action based on roles? In that case, perhaps we'll have to tie this to a specific permission e.g., those who can view students, can also view audit logs (which is almost everyone)

**Comment by wkurniawan07** [comment]
> the current access control layer cannot actually take action based on roles

Not cannot, but our access control checks always make use of the individual permissions ever since those are introduced (2014, I believe). Deviating from that rule will introduce future gotchas.

**Comment by damithc** [comment]
> Not cannot, but our access control checks always make use of the individual permissions ever since those are introduced (2014, I believe). Deviating from that rule will introduce future gotchas.

I don't think this feature is worth a drastic change to access control mechanism. We can go with something that fits the current way i.e., tie this to one (or more) of the current access control flags.

**Comment by t-cheepeng** [comment]
>I see. Perhaps leave it be. After all, no confidential info is being released.

If we are tying it to the access control flags, should we just leave the access control as is per above quote (available to all instructors)?

**Comment by damithc** [comment]
> If we are tying it to the access control flags, it is likely going to be tied to the `view student details` flag.
> should we just leave the access control as is per above quote (available to all instructors)?

It is technically possible for an instructors to exist without 'view students' permissions though, right? Also, it is possible to have instructors who can see students of certain sections only.

![image](https://user-images.githubusercontent.com/1673303/114503434-e4d62e00-9c5f-11eb-93b8-b766b9454d9a.png)

I don't think the above scenario will come into play often but as access of student details are involved, better to be safe than sorry?

An easier solution is to tie this to more prestigious flags (e.g., if the instructor has at least one of the below) so that those with less privileges e.g., tutors are automatically excluded.

![image](https://user-images.githubusercontent.com/1673303/114503633-367eb880-9c60-11eb-9504-cb26db82d43b.png)

**Comment by t-cheepeng** [comment]
> I don't think the above scenario will come into play often but as access of student details are involved, better to be safe than sorry?

👍 

> An easier solution is to tie this to more prestigious flags (e.g., if the instructor has at least one of the below) so that those with less privileges e.g., tutors are automatically excluded.

Would side towards easier solutions. I think we can tie it to the `Enroll/Edit/Delete Students`?

**Comment by damithc** [comment]
> Would side towards easier solutions. I think we can tie it to the `Enroll/Edit/Delete Students`?

Sounds good.

**Comment by madanalogy** [comment]
> Would side towards easier solutions. I think we can tie it to the `Enroll/Edit/Delete Students`?

Wouldn't be that much of a stretch to also add `CAN_MODIFY_SESSION` and `CAN_MODIFY_INSTRUCTOR`. In line with capabilities allowed for owner and manager levels as initially suggested by @damithc 

@AdithyaNarayan fyi for your current open PR. Apologies for getting to this a bit late
