### ISSUE TITLE
Date picker: the 'today' button doesn't update the calendar widget

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11096]
![image](https://user-images.githubusercontent.com/1673303/114264722-29bf5200-9a1f-11eb-8d6e-6079bbcf84b4.png)

Clicking the `Today` button updates the input box but doesn't update the calendar widget.

**Comment by damithc** [comment]
To add, the above behavior was noticed when I was setting the start date of a session. When setting the closing date, it was the opposite: the calendar widget updated but not the input box went blank.

**Comment by madanalogy** [comment]
@daongochieu2810 could you take a look into this when you have the time? Since you added the today button

**Comment by daongochieu2810** [comment]
yes sure
