### ISSUE TITLE
Audit logs: right-align timestamps

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11103]
Perhaps easier on the eye if we right align timestamps, so that hours/mins/seconds line up?
![image](https://user-images.githubusercontent.com/1673303/114353740-f48e3d80-9b9f-11eb-99f1-439feeb5f57a.png)

EDIT: It looks like the time stamp has a fixed width (i.e., the same number of characters) but the hours/seconds don't line up because we are not using a mono-spaced font for the timestamp.
Compare
* Mon, 12 Apr
* Fri, 09 Apr

with
* `Mon, 12 Apr`
* `Fri, 09 Apr`

See how the second one lines up nicely.
Perhaps the better solution is to use a mono-spaced font for the timestamp (rather than right-align)?

**Comment by gharrington1996** [comment]
Could I take this as a good first issue? I would be using this for a class, and a pull request can be expected within one month.

**Comment by t-cheepeng** [comment]
@gharrington1996 Hi, thank you for the interest in contributing. This issue is not available right now. You may want to check out some other issues like https://github.com/TEAMMATES/teammates/issues/11087

**Comment by gharrington1996** [comment]
@t-cheepeng I have no experience with Angular, unfortunately. I am not seeing why this issue is unavailable, could you help me understand?

**Comment by t-cheepeng** [comment]
@gharrington1996 The issue is currently beind handled internally. Apologies for any confusion caused
