### ISSUE TITLE
Audit logs: Show both student name and email

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11102]
![image](https://user-images.githubusercontent.com/1673303/114346161-90ff1280-9b95-11eb-87cc-926737eb8dec.png)

Student name is not unique. Should we also show the email? e.g., `John Doe <john@example.com`

**Comment by halfwhole** [comment]
I agree that showing the email would help in cases where students have the same name. Would the following be better? The dropdown box can also be expanded to accommodate the longer text:

![teammates-audit-logs-8](https://user-images.githubusercontent.com/41856541/115764137-c8f92780-a3d7-11eb-9b97-e5e3f7803317.png)

**Comment by damithc** [comment]
> I agree that showing the email would help in cases where students have the same name. Would the following be better? The dropdown box can also be expanded to accommodate the longer text:
> 
> ![teammates-audit-logs-8](https://user-images.githubusercontent.com/41856541/115764137-c8f92780-a3d7-11eb-9b97-e5e3f7803317.png)

Yes, looks fine.
