### ISSUE TITLE
Instructor checking logs: expand results if empty

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11126]
Scenario: instructor searches for logs using the `/web/instructor/logs` page. 

Current: all results panels are collapsed by default.
Suggested: If there are no results for some sessions, we can expand them automatically so that the user doesn't have to click to find out. 

![image](https://user-images.githubusercontent.com/1673303/117753386-f86ab980-b24a-11eb-9412-621cdb358d2d.png)

We can also consider expanding all results panels by default? Are there any downsides?

**Comment by damithc** [comment]
Audit-logs team, is this one suitable for first-timers?

**Comment by t-cheepeng** [comment]
Yes, it is suitable for first-timers

**Comment by Maezzzzz** [comment]
Is this being handled by anyone currently?

**Comment by moziliar** [comment]
@Maezzzzz as far as we know, no one is at it. You can attempt to submit PR for this issue.

**Comment by hoonti06** [comment]
I am a beginner. I want to work on this.

**Comment by moziliar** [comment]
@hoonti06 thank you for your interest in this issue.

As @Maezzzzz has not confirmed commitment on this issue, @hoonti06 you can try to submit an PR.

**Comment by hoonti06** [comment]
@moziliar Thank you!
