### ISSUE TITLE
Feedback path for new question not inheriting respondent number

### ISSUE THREAD

**Issue by madanalogy** [TEAMMATES/teammates#11127]
Creating a new question does not properly inherit the feedback path when students in this course give feedback to other students in this course.

- **Environment**: Live server as at V7.15.0

**Steps to reproduce**

https://user-images.githubusercontent.com/42177597/117768254-b8b0cb80-b264-11eb-9f33-887519a2eb25.mov

**Expected behaviour**

The "maximum number of students each respondent should give feedback to" should be inherited

**Actual behaviour**

Value reverts to unlimited

**Additional info**

Not sure if this reset is by design. Putting as `s.ToDiscuss` for further feedback from PM @damithc

**Comment by damithc** [comment]
I can't think of a reason not to inherit it. Seems like a bug.

**Comment by lyeyixian** [comment]
I would like to work on this issue.
