### ISSUE TITLE
Audit logs: sort student names alphabetically

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11135]
Page: `/instructor/logs`

This drop-down doesn't seem to be sorted:

![image](https://user-images.githubusercontent.com/1673303/118627635-78ba8d00-b7fe-11eb-97a4-c280e67bc722.png)

I suspect it is using the default order from the database (i.e., the order of enrollment) which may or may not be sorted alphabetically.

**Comment by damithc** [comment]
@t-cheepeng is this suitable for first timers?

**Comment by t-cheepeng** [comment]
Yes, it should be suitable for first timers. Just a simple sorting for data retrieved

**Comment by Gily-H** [comment]
Hi, I would like to work on this issue if it is not taken yet

**Comment by bhupendersinghh** [comment]
Hi, I am a first timer, can I work on this issue if possible?

**Comment by t-cheepeng** [comment]
@Gily-H 
Yes, you can go ahead and work on the issue

@bhupendersinghh 
Thanks for expressing interest! As the previous commenter had commented earlier, priority is given. You can look for other issues with the `good first issue` label

**Comment by Gily-H** [comment]
@t-cheepeng thanks! Would it be appropriate if I were to create a new course and enroll students to view how the drop-down behaves?

**Comment by t-cheepeng** [comment]
@Gily-H Yes, that would be the expected workflow

**Comment by sakibmahmud** [comment]
I would like to work on this issue, please.

**Comment by t-cheepeng** [comment]
Hi @sakibmahmud The issue is currently worked on by someone else. Please find other `good first issue` to work on. Thanks!

**Comment by Gily-H** [comment]
Hi, sorry it's taking a bit I've started summer courses recently. 
I implemented sorting in the `instructor-audit-logs-page.component` for the student drop-down for when `loadData()` retrieves the list of students from the server.

I am checking to see if there is a better way to implement the method using existing resources similar to the sorting methods found in the `tableComparatorService`.

**Comment by rrtheonlyone** [comment]
@Gily-H please submit a PR and we can discuss there
