### ISSUE TITLE
Link recovery: shorten the search window to 3 months

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11144]
![image](https://user-images.githubusercontent.com/1673303/119312435-eeae7080-bca4-11eb-827a-d062a9dc0cf8.png)

![image](https://user-images.githubusercontent.com/1673303/119303032-a5a3ef80-bc97-11eb-927f-f17272b4dff6.png)

current: the above action recovers link for the past 6 months.
suggested: shorten the search window to 3 months (more precisely, 90 days)

additional: in the page, state the duration in days rather than months

See #11143 for context

**Comment by moziliar** [comment]
This will cut down the cost and latency of the submission by half. We probably should think of a better solution that can optimise it further than that.

Refer to the N+1 problem in #11143 which might be of some interest.
