### ISSUE TITLE
Instructor home page: tweak session status tooltips

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11148]
Current:
![image](https://user-images.githubusercontent.com/1673303/119369247-897b6f00-bce6-11eb-8922-f3f40c7eaacc.png)

Suggested: Remove `has been created`. Also, `has ended` -> `is closed for submissions`.

Also applies to the `Open` status.

![image](https://user-images.githubusercontent.com/1673303/119370632-1541cb00-bce8-11eb-94e4-adca1ff4a239.png)

Rephrase as `Students can view responses received, as per the visibility settings of each question`
For 'Not Published': `Students cannot view responses received`

**Comment by jragusin** [comment]
Hi. I would like to take this one.

**Comment by moziliar** [comment]
Hi @jragusin sorry for the delay in response. Feel free to take it up and let me know if you are facing any issue!

**Comment by pPris** [comment]
Hi, first-timer here, can I try this issue?
