### ISSUE TITLE
Students page: tweak text

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11149]
![image](https://user-images.githubusercontent.com/1673303/119374076-b7af7d80-bceb-11eb-9026-7b541c8cb8e2.png)

Some minor cosmetic tweaks:
* Page title `Student List` -> `Students`
* Rephrase the explanation as follows:
  >Expand the panels below to view the details of students in each course. Use the ['Search' page]() if you need to locate the details of a specific student by name or email.

**Comment by cmadhumita5** [comment]
i want to try this. i am a beginner. so please tell me about the branching

**Comment by damithc** [comment]
> i want to try this. i am a beginner. so please tell me about the branching

@cmadhumita5 Did you mean Git branching? Contributing to an OSS project on GitHub requires familiarity with Git. If you are new to Git, we recommend you focus on learning Git basics first. After that, you can come back and attempt to do a PR here.

**Comment by cmadhumita5** [comment]
@damithc I wanted to know which is ur development branch?

**Comment by moziliar** [comment]
@cmadhumita5 for our contribution workflow, we branch directly off master branch, unless we are working on feature branch for individual feature project.

**Comment by BoazWu** [comment]
Hi, I'd like to take this issue
