### ISSUE TITLE
Link recovery is taking a long time

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11143]
![image](https://user-images.githubusercontent.com/1673303/119312435-eeae7080-bca4-11eb-827a-d062a9dc0cf8.png)

![image](https://user-images.githubusercontent.com/1673303/119303032-a5a3ef80-bc97-11eb-927f-f17272b4dff6.png)

After clicking on the `Submit` button, it takes close to a minute (40-50s) for the success message to appear. We need to find ways to reduce that because it is not good for a request to tie up a server instance for that long, particularly given that this action is open to the public.

Some options:
* ~~Reduce the search window. Currently it is 6 months. We can shorten it to 3 months.~~ Done by #11155
* Provide a drop-down to the user to specify the search window. Make it short by default and give a few other options. (2, 4, 6, 8, 12 weeks)
* Look into the code to see if the result can be made faster.
* Use a task queue so that the action can return immediately. In that case (in fact, in all cases), it is better to inform the user that the email will take 5-10 minutes to reach the user.

Other ideas?

**Comment by madanalogy** [comment]
> Use a task queue so that the action can return immediately. In that case (in fact, in all cases), it is better to inform the user that the email will take 5-10 minutes to reach the user.

This might be a bit tricky, what happens if the email isn't found? We could just send a negative email but this might greatly increase costs if the feature is used regularly.

> Look into the code to see if the result can be made faster.

This I think is worth pursuing. Wondering if any of our performance folks want to take a look. No need to code out the solution yourself, good enough to have some preliminary suggestions that others can pick up @daongochieu2810 @teikjun @moziliar

**Comment by moziliar** [comment]
> Look into the code to see if the result can be made faster.

We can first sort out the code logic, followed by profiling, either with no data or with huge amount of data. Will start on this issue shortly.

**Comment by moziliar** [comment]
@damithc @madanalogy 
It seems like we are facing an N+1 problem here:

https://github.com/TEAMMATES/teammates/blob/45e3c0f88ce4f94f4fed28922392136d35ebc6b8/src/main/java/teammates/logic/api/EmailGenerator.java#L276-L280

Testing steps:
1. try invalid email -> get email not found response pretty fast
2. can conclude latency not from scanning of students & sending email
3. try valid email -> 46s
4. vet code logic and discovered that it will first query all sessions within 180 days (involving 3 full scan of all sessions, will verify if session is indexed by start time or end time) -> for each session, query the course and generate the session link from the course info

Can I check how many sessions are there in the datastore within the last 180 days? I think the latency might be linear wrt the # of sessions.

**Comment by moziliar** [comment]
The N+1 problem might not be easy to solve in naive ways; objectify doesn't really have a native OR 
clause for conditional query, and the IN clause is but a syntactic sugar for multiple Datastore queries.

From https://cloud.google.com/datastore/docs/concepts/queries#restrictions_on_queries
> The nature of the index query mechanism imposes certain restrictions on what a query can do. Datastore mode queries do not support substring matches, case-insensitive matches, or so-called full-text search. The NOT, OR, and != operators are not natively supported, but some client libraries may add support on top of Datastore mode.

The use of CompositFilter might be worth exploring to reduce the number of calls to the Datastore in order to mitigate this issue.

**Comment by madanalogy** [comment]
@moziliar thanks for the investigation! Can leave it at that if you're strapped for time and see if any developer wants to pick it up. This shouldn't be that urgent since we have #11144

**Comment by damithc** [comment]
> Can I check how many sessions are there in the datastore within the last 180 days? I think the latency might be linear wrt the # of sessions.

It varies. This should give you some idea (it's for a 14 day window):
![image](https://user-images.githubusercontent.com/1673303/119761472-716e4000-bede-11eb-8fc5-0797b9ec43ad.png)

Keep in mind that a student is unlikely to be in more than a few courses. Hence, it is good to filter by course first(?)

**Comment by moziliar** [comment]
@damithc I think you are right... the logic here is pretty crude which should be subject to refactoring.
The N+1 problem is a non-issue if we query the course the student is in first.
From the data provided, it is reasonable to believe that running through that many sessions incurs the bulk of the latency.
For reference: https://github.com/TEAMMATES/teammates/blob/45e3c0f88ce4f94f4fed28922392136d35ebc6b8/src/main/java/teammates/storage/api/FeedbackSessionsDb.java#L90-L105

@madanalogy I can take it up. The pre-requisite is probably building an LnP test script. Will get on it by also creating an issue for that first.
