### ISSUE TITLE
student viewing responses: show self-response as 'given' AND 'received'

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11146]
Context: When a student is viewing responses of a session, the received responses are shown differently from given responses. 

Here's a case where the student should see only given responses (because the question is configured not to show any received responses to the student):
![image](https://user-images.githubusercontent.com/1673303/119349109-575f1280-bcd0-11eb-95e9-12d994ed502f.png)

Actual: the self response is shown as 'received' and stats are shown based on that single response. 

Suggested: there should be no stats, and the self response should be shown under 'own responses'.
![image](https://user-images.githubusercontent.com/1673303/119350305-c2f5af80-bcd1-11eb-9a6a-1265bc5a49fb.png)

I think when there is a self-response, it should be shown under both given and received (because technically, it is _both_). That way, each can be dealt with independently, based on the visibility settings.

**Comment by samuelfangjw** [comment]
Hi, could I try working on this issue?

**Comment by moziliar** [comment]
Hi @samuelfangjw, please go ahead!
Do ask for help if you are stuck:)

**Comment by samuelfangjw** [comment]
Hi! I have a two questions regarding how I should approach this.

Qns 1) Which approach would work better?

The questions fetched from the api have the following attributes.
```
  feedbackQuestion: FeedbackQuestion;
  questionStatistics: string;
  allResponses: ResponseOutput[];
  responsesToSelf: ResponseOutput[];
  responsesFromSelf: ResponseOutput[];
  otherResponses: ResponseOutput[][];
```
Currently, `responsesFromSelf` is used to generate the responses in the "Your own responses (to others) section".
```html
// Your own responses (to others) section
<div *ngFor="let responseFromSelf of question.responsesFromSelf">
      <tm-student-view-responses ...>
</div>
```
However, the array does not contain self-responses.

I've thought of two ways to get the section to display self responses too, and was wondering if any of them would be preferable in this case. 
1. use the `allResponses` array instead, but filter by givers name (leaning towards this).
2. modify the responsesFromSelf to have self response (by changing the value returned by backend).

Qns 2) Is it possible to get the visibility status of each question? I couldn't find an easy way to check if the responses should be hidden. My current plan is to check if `responsesToSelf` (excluding self response) is empty, but i'm not sure if this might cause unintentional bugs (e.g. if the responses are supposed to be visible but there are no responses from others).

**Comment by rrtheonlyone** [comment]
Hi @samuelfangjw, thanks for looking into this. 

Yes, for question 1, option (2) should be preferred - the `responsesToSelf` field is for students viewing results. Please have a look at `SessionResultsData.java`. 

Reading `SessionResultsData.java` should also hopefully answer question 2 - the backend has some logic for the visibility to students.

**Comment by rrtheonlyone** [comment]
Hi prof @damithc, a clarification on the above issue. 

> I think when there is a self-response, it should be shown under both given and received (because technically, it is both). That way, each can be dealt with independently, based on the visibility settings.

In a scenario such as the above, do you prefer to have the self response be shown under both given/received? (just no stats if the question's responses are not visible to student). 

The alternative is the screenshots by @samuelfangjw in https://github.com/TEAMMATES/teammates/pull/11221: the self-responses will not be shown under given if the question's responses are not visible to student.

**Comment by damithc** [comment]
> The alternative is the screenshots by @samuelfangjw in #11221: the self-responses will not be shown under given if the question's responses are not visible to student.

My gut feeling is that self response should be visible under 'given' no matter what (no reason to hide given response from the giver). But showing self response under 'received' depends on the visibility. If the responses are visible to students, self-response should be shown (together with responses received from others) but otherwise no responses should be shown, not even self response. Does that make sense? @samuelfangjw @rrtheonlyone

**Comment by rrtheonlyone** [comment]
Yes that makes sense to me as well. 

Sorry, incorrectly described the situation earlier. I think @samuelfangjw's screenshots should be correct then. We see that responses received is shown only based on the visibility. I will tag you in the PR for UI review @damithc
