### ISSUE TITLE
Search page: Remove unnecessary panel

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11150]
![image](https://user-images.githubusercontent.com/1673303/119374774-926f3f00-bcec-11eb-876e-065e5e41e7b2.png)

Suggested changes:
* Rephrase as `You can search for students (by name or email) from all your courses here.`
* Give an example at the end `e.g., "John Doe"`
* Remove this outer panel as all results are students anyway.

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by moziliar** [comment]
@RhnSharma thanks for your interest. Please go ahead!

**Comment by sakibmahmud** [comment]
Is the issue still open? I would like to work on this.

**Comment by moziliar** [comment]
@sakibmahmud hi, thank you for your interest in contributing to the project!
The issue is currently handled by another contributor. Maybe you can look for another good-first-issue in the meantime?

**Comment by ipsitagoel** [comment]
Is this issue available to work upon?

**Comment by hhdqirui** [comment]
@ipsitagoel hi, thank you for your interest. This issue is currently available. Feel free to work on this issue.

**Comment by Ronald-patrick** [comment]
I would like to work on this issue. Its already assigned, or else you can assign it to me.

**Comment by hhdqirui** [comment]
@ipsitagoel hi are you currently working on this issue? If not then we will let others who are interested to work on it.

**Comment by rudheer** [comment]
i can work on this issue, pl assign me if no one are currently working on it.

**Comment by Jaswanth19-596** [comment]
I would like to work on this..... Is this issue still open

**Comment by daongochieu2810** [comment]
@Jaswanth19-596 @rudheer it seems like @Moneill22 is still working on this issue

**Comment by Jaswanth19-596** [comment]
Can I work parallely or should I wait till you assaign it to me .

**Comment by moziliar** [comment]
@Jaswanth19-596 there is another contributor working on this issue. Please find another issue to work on in the mean time
