### ISSUE TITLE
Student update profile: profile image does not display correctly when certain formats are used

### ISSUE THREAD

**Issue by jianhandev** [TEAMMATES/teammates#11152]
When a user uploads an image of certain formats e.g. svg/TIFF (Chrome), the system does not display the profile image as expected.

**Steps to reproduce**
1. Login as student
2. Go to **Profile**
3. Click on **Upload/Edit Photo** and upload an svg file

https://user-images.githubusercontent.com/59337195/119604602-eb8cbf00-be21-11eb-99a1-2fc2b188f8d1.mov

**Suggested approach:**
Restrict image formats to the most commonly used and most well-supported MIME types for web content on modern browsers.

We should allow the following MIME types as they have wide support across Chrome, Edge, Firefox, IE, Opera and Safari:
* image/jpeg
* image/png
* image/gif
* image/svg+xml

The following two categories of MIME types either lack browser support or have reasonable support but are rarely used (and thus add little value if we were to include them).

**Do not have wide browser support (should be avoided for web content):**
* image/bmp
* image/x-icon
* image/tiff

**Others (less commonly used):**
* image/apng
* image/avif
* image/webp

**Reference:**
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img 

Suggestion:
* Perform a simple front-end check: Disable formats other than the ones white-listed above.

**Comment by wkurniawan07** [comment]
> two image formats are currently supported (.jpg and .png)

This is wrong. The API layer accepts any `image/*` object, and SVG is one (the official MIME type is `image/svg+xml`).

https://github.com/TEAMMATES/teammates/blob/45e3c0f88ce4f94f4fed28922392136d35ebc6b8/src/main/java/teammates/ui/webapi/PostStudentProfilePictureAction.java#L44-L47

**Comment by jianhandev** [comment]
> The API layer accepts any `image/*` object

You are right... the tooltip here makes me think that only .png and .jpg are accepted. So the image format is correct, and there was no exception raised in the dev server but for some reason the image didn't show up. Tried uploading a TIFF image, the same issue (with the svg) occured.

<img width="302" alt="Screenshot 2021-05-26 at 2 57 59 PM" src="https://user-images.githubusercontent.com/59337195/119617035-f05a6e80-be33-11eb-8577-9dad579c6624.png">

**Comment by damithc** [comment]
> Should we restrict the image formats to png and jpg for the sake of compatibility across different browsers?

This is rarely used non-important feature.
I'm OK to limit to png and jpg only (not much value in supporting rarely used image formats). I'm also OK to do a frontend check only if a user has nothing to gain by bypassing the front-end check, and the bypass does not cause any harm to others or the system integrity. 

Just my initial thoughts. I'm open to other opinions.

**Comment by jianhandev** [comment]
>  I'm also OK to do a frontend check only if a user has nothing to gain by bypassing the front-end check, and the bypass does not cause any harm to others or the system integrity.

I agree with you on this. One concern I have is that certain browser version do not support the `accept` attribute. @rbrishabh has proposed (in his PR) to do an additional check of the file type before sending it over to the backend. Doing so prevents the file from being submitted to the backend if it is not a png/jpg, but there is still a need for some form of error message to be generated (presumably in the backend) and presented to the user.

**Comment by jianhandev** [comment]
> Should we restrict the image formats to png and jpg for the sake of compatibility across different browsers?

My current suggestion to fix this problem is as follows:
1. In the front-end, we disable formats other than jpg/jpeg/png using the `accept` attribute for file input
2. Suppose the front-end is bypassed (e.g. due to incompatibility with certain browsers), in the back-end, we perform another check to ensure the correct format. If an incorrect format is found, send back an error message in `JsonResult`.

@wkurniawan07 do you have other opinions on this? I have thought about it and didn't find any big issues with it.

**Comment by wkurniawan07** [comment]
@jianhandev it's never about "suppose the front-end check is bypassed". Back-end should never trust that the incoming information is accurate, secure, etc. Front-end validation is done if it value-adds to user experience, but it can never replaces back-end validation.

Also, the missing image display could very well be caused by line 32 here:
https://github.com/TEAMMATES/teammates/blob/45e3c0f88ce4f94f4fed28922392136d35ebc6b8/src/main/java/teammates/ui/webapi/ImageResult.java#L30-L34

**Comment by jianhandev** [comment]
Tried manipulating the content type in `ImageResult`, but to no avail. Certain formats, like TIFF, are browser-dependent, which prevents the image from being rendered in `<img>` element. There is also certain quirks associated with SVG images which I have yet to find out why. Limiting it to the commonly used jpg/png formats might not be the best solution but considering that this is a non-important feature, perhaps going with the simpler solution will not lead to major trade-offs. Since it requires modification of both front-end and back-end code, we can put this issue up for contributors who wants a taste of both front-end and back-end development, how does that sound @damithc @wkurniawan07 ?

**Comment by damithc** [comment]
> There is also certain quirks associated with SVG images which I have yet to find out why. Limiting it to the commonly used jpg/png formats might not be the best solution but considering that this is a non-important feature, perhaps going with the simpler solution will not lead to major trade-offs. Since it requires modification of both front-end and back-end code, we can put this issue up for contributors who want a taste of both front-end and back-end development, how does that sound @damithc @wkurniawan07 ?

No objections from me.

**Comment by jianhandev** [comment]
For more flexibility, instead of supporting only jpeg and png, we can support other commonly used formats like image/gif and image/svg+xml which have broad browser support. The problem of svg not rendering properly is being addressed in [PR #11165](https://github.com/TEAMMATES/teammates/pull/11165). 

**Widest browser support:**
image/jpeg
image/png
image/gif
image/svg+xml

**Do not have wide browser support (should be avoided for web content):**
image/bmp
image/x-icon
image/tiff

**Others (less commonly used):**
image/apng
image/avif
image/webp

**Reference:**
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

**Comment by rbrishabh** [comment]
I can work on this!

**Comment by tamrakarsweta220** [comment]
Hi, I am a first time contributor, checking out some good first issues that are still open. I tried to reproduce this bug and it seems like it is working fine now. The profile picture accepts jpg, png, svg, and gif formats. So, I was wondering why this issue is still open? Was it only partially fixed?

**Comment by tamrakarsweta220** [comment]
@jianhandev Hi, can you please provide some insight on the issue?

**Comment by jtsai3** [comment]
Hi, I am a first time contributor and would like to work on this issue. Based on my understanding of previous discussions, we only need to do a frontend check of the file type (gif, jpeg, jpg, png, svg+xml) is that correct? What if when a image type not supported (eg. tif) was uploaded? Will there be any kinds of reminder? Thanks!

**Comment by jianhandev** [comment]
> Hi, I am a first time contributor and would like to work on this issue. Based on my understanding of previous discussions, we only need to do a frontend check of the file type (gif, jpeg, jpg, png, svg+xml) is that correct? 

Yes that is correct.

> What if when a image type not supported (eg. tif) was uploaded? Will there be any kinds of reminder? Thanks!

Yes, I would think a simple warning/reminder to tell the user the appropriate type of image acceptable is sufficient.

**Comment by jtsai3** [comment]
Hi @jianhandev, I have opened a PR at [https://github.com/TEAMMATES/teammates/pull/11495](https://github.com/TEAMMATES/teammates/pull/11495). Could you please give any feedback on this? Thanks!

**Comment by FergusMok** [comment]
Hello, I'll take this issue as the previous PR has been closed due to inactivity.
