### ISSUE TITLE
Student accessing link using wrong Google account: give a more specific error message

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11157]
Context: 
1. A student has joined a course using a Google account earlier.
2. The student is logged into a different Google account.
2. The student clicks on an access link (either to submit or to view results)
3. Current: TEAMMATES gives a generic error `Not authorized to view this page`
   Suggested: Make the error message more explanatory e.g., `You joined TEAMMATES with the Google account johnd... [partial user name] but now trying to access using the account TimKook. Please try again after logging out from other Google accounts and logging into the account jonhd... If the account jonhd... doesn't belong to you, please contact TEAMMATES support.`

**Comment by smanpreet96** [comment]
Hi, I would like to contribute towards resolving this issue.

**Comment by moziliar** [comment]
Hi @smanpreet96 thank you for your interest in contributing to the project.
We recommend first time contributor to try out those labelled with "good first issue" before attempting other not labelled so.
Perhaps you can find another issue and give it a go?

**Comment by smanpreet96** [comment]
Yeah sure I can look for a "good first issue". Let me find one.

**Comment by tjtanjin** [comment]
Hello! May I try working on this?

**Comment by damithc** [comment]
> Hello! May I try working on this?

Sure @tjtanjin 

> Edit: @damithc So I dug around the code a bit and was wondering would it be sufficient to only mention the current account that is being used to access the link? It appears that `RegkeyValidity` only contains 3 boolean attributes and there is no current way to retrieve username from reg key (correct me if I am wrong). There might be quite some modification required to `RegKeyValidity` as well as its associated test cases in order to have it return the username as an attribute as well to include it in the error message. Alternatively perhaps a new class should be created to deal with this? Kindly advice, thank you!

I'm OK to for a solution that is based on the current API for now and create a follow-up issue to investigate a more comprehensive solution. As we are the only users of our API, we _can_ change it if we want. 
@TEAMMATES/active-mentors any inputs?

**Comment by pPris** [comment]
Hi i would like to help with this issue but for testing it out, I'm unsure of how to get a unique feedback submission link and a course join link for the students on the dev server, can I get some help on that?

(Steps taken)
![image](https://user-images.githubusercontent.com/49683462/125194135-9813ea80-e282-11eb-8187-7ffa5e036c25.png)

![image](https://user-images.githubusercontent.com/49683462/125194152-ae21ab00-e282-11eb-921b-2485ad12ab1a.png)


(After enrolling a student in the course from an instructor account, I try to log in as them but when I try to access student pages, it says google account not known to teammates)

**Comment by tjtanjin** [comment]
Just to give a quick update, I have drafted an initial version of the error message in a new PR. The level of details to be included may be further discussed.
