### ISSUE TITLE
Modal cancel loading bug

### ISSUE THREAD

**Issue by ccyccyccy** [TEAMMATES/teammates#11161]
This entire issue might be related to https://github.com/TEAMMATES/teammates/issues/11162

Canceling session permanant delete modal leads to the table being loaded indefinitely.

![Screen Recording 2021-05-29 at 12 34 23 PM](https://user-images.githubusercontent.com/32454748/120058313-8a145c80-c07c-11eb-94a5-aa2cc68ac7f3.gif)

Canceling "Copy from previous feedback sessions" modal leads to form being loaded indefinitely

![Screen Recording 2021-05-29 at 2 19 40 PM](https://user-images.githubusercontent.com/32454748/120060253-4ecc5a80-c089-11eb-925d-fdabcea79076.gif)

**Comment by hhdqirui** [comment]
Hi! I would like to work on this issue.
