### ISSUE TITLE
Student viewing responses: show an empty panel if the student didn't receive responses for a question

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11169]
Context: A student who has logged into TEAMMATES is viewing results of a session. The question is set as visible to the receiving student but the student has not received any responses for that question. The student hasn't given any responses either.

Current: Nothing is shown

![image](https://user-images.githubusercontent.com/1673303/120740187-4fe80680-c525-11eb-89e9-cee031a8b8ef.png)

Suggested: ~~Show an empty panel and mention that there are no responses. Alternatively, we can show a generic `Either not configured to be visible or there are no responses` message.~~ Detect this situation and show an explanatory message `There are no responses to show. i.e., you have not given any responses and the responses you received (if any) are not meant to be visible to you.`

**Comment by lyeyixian** [comment]
Hi, I would like to work on this issue.
