### ISSUE TITLE
Change most mentions of Datastore to database

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#11175]
`Datastore` (specific to Google Cloud Datastore) is a very specific implementation of the database (a general computer system term) we are using. By conflating those terms we create tight coupling, and in the event that we decide to switch our database implementation, the former will stop making sense in most of the places the term is being used.

All mentions of `Datastore` in the code base and documentation should be reworded to `database`, except for the ones that are actually concerned with Datastore.

**Comment by brennanw31** [comment]
I'd like to work on this.
