### ISSUE TITLE
Submission after deadline: show a better error message

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#1117]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on August 06, 2013 17:30:50_

If the submission comes after the deadline (e.g., started editing before the deadline, but submitted after the deadline+grace period), we currently show 'unauthorized access' error page. 
It is better if we can give the real reason for the error.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1118_

**Comment by damithc** [comment]
This is a very old issue. Need to verify if the error message are still the same.

**Comment by sujeet14108** [comment]
@damithc  This is the error message coming now

![screenshot from 2017-04-19 01-05-37](https://cloud.githubusercontent.com/assets/9781422/25154096/cf04f004-24ac-11e7-953f-5efa0abe1b9c.png)

**Comment by damithc** [comment]
Outdated issue. Thanks for investigating it @sujeet14108
