### ISSUE TITLE
Distribute points among recipients: show average excluding self

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11208]
Requested by a user:

Context: an instructor is viewing the results of a 'distribute points among recipients' type question

![image](https://user-images.githubusercontent.com/1673303/122633779-e82ce080-d10c-11eb-93bb-cc580e1c5e72.png)

Suggestion: Also show 'average excluding self' column

**Comment by damithc** [comment]
@ccyccyccy please help to label this as a `good first issue` or a `good second issue`

**Comment by Jellybeano** [comment]
hi could i try working on this?

**Comment by ccyccyccy** [comment]
Go ahead and work on it :)
