### ISSUE TITLE
Checkbox not aligned with text when choosing from template question

### ISSUE THREAD

**Issue by samuelfangjw** [TEAMMATES/teammates#11205]
- **Environment**: `master` branch at commit 476193c

**Steps to reproduce**
From the edit feedback session page, click Add New Question -> Choose from template questions.

**Expected behaviour**
Checkboxes are aligned with the text.

<img width="1023" alt="Screenshot 2021-06-18 at 8 24 03 PM" src="https://user-images.githubusercontent.com/60355570/122561999-1959d200-d075-11eb-9679-572fde55bf4a.png">

**Actual behaviour**
Checkboxes are not aligned with the text.
<img width="1039" alt="Screenshot 2021-06-18 at 8 19 16 PM" src="https://user-images.githubusercontent.com/60355570/122562036-28408480-d075-11eb-8d2f-4a37e22ce47b.png">

**Comment by damithc** [comment]
Thanks for reporting this @samuelfangjw

**Comment by xyzhang00** [comment]
Hi, could I try working on this?

**Comment by halfwhole** [comment]
Sure thing, please go ahead

**Comment by StylPamp** [comment]
I 'm making a PR about this :)

**Comment by madanalogy** [comment]
> I 'm making a PR about this :)

@xyzhang00 had already indicated that they would be working on this. We'll be putting #11213 on hold until #11214 is resolved. @StylPamp
