### ISSUE TITLE
Instructor checking activity logs: start time is not used correctly

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11202]
page: `/web/instructor/logs`

![image](https://user-images.githubusercontent.com/1673303/122528447-ebfa2d80-d04e-11eb-8583-ae9234f87cc6.png)

Looks like 23.59 is interpreted as 'start of the day' when it should be 'end of the day'. 
As this is a 'search' feature, a mistake here has serious consequences because the instructor can be mislead into thinking that a student didn't access the submission page when in fact s/he did.

**Comment by damithc** [comment]
Not urgent to fix as this feature is not yet released to users, but must fix before releasing to users.

**Comment by lyeyixian** [comment]
I can't reproduce this. It seems to be working on my side.

![image](https://user-images.githubusercontent.com/58477697/122794313-af4c6180-d2ee-11eb-8bf5-672cb1c088a1.png)

![image](https://user-images.githubusercontent.com/58477697/122794363-be331400-d2ee-11eb-98d4-cb5ea1a1b002.png)

![image](https://user-images.githubusercontent.com/58477697/122794384-c7bc7c00-d2ee-11eb-919d-a26e500b7f3f.png)

**Comment by damithc** [comment]
Thanks for investigating this @lyeyixian 

A different course: 
![image](https://user-images.githubusercontent.com/1673303/122801738-166e1400-d2f7-11eb-9925-83615a0a2088.png)


There is something wrong with the sort order too.



Not sure what's going on 🤔 
Perhaps it's related to time zone difference not being considered in the logic? 
Perhaps you can look at the logic to see anything is amiss?

**Comment by lyeyixian** [comment]
Yes, I will try to look into it.

**Comment by lyeyixian** [comment]
Hmmm strange, cause this is also working on my side too.
I'm running the server locally, but I think it shouldn't behave differently though.

![image](https://user-images.githubusercontent.com/58477697/122891395-11e94000-d377-11eb-9b9d-3adc702c0b14.png)

**Comment by damithc** [comment]
@AdithyaNarayan @t-cheepeng @halfwhole any thoughts?

BTW, your dev server is running is your local time zone while the production server could be running in a different time zone (UTC?).

**Comment by t-cheepeng** [comment]
I don't believe there is any incorrect logic for the time conversions on frontend side since it is using a service that other pages are also using which takes into account the timezone. Will investigate this on staging

**Comment by damithc** [comment]
> I don't believe there is any incorrect logic for the time conversions on frontend side since it is using a service that other pages are also using which takes into account the timezone. Will investigate this on staging

@t-cheepeng The conversion may be correct but some of the logic might be using unconverted times. Just a guess.

**Comment by rrtheonlyone** [comment]
Hi @AdithyaNarayan are you available to take this one up?

cc: @halfwhole / @t-cheepeng

**Comment by AdithyaNarayan** [comment]
I will take a look into it later this week!

**Comment by damithc** [comment]
@halfwhole @t-cheepeng @AdithyaNarayan Let's fix this one and release this feature to users.

**Comment by halfwhole** [comment]
I haven't confirmed this yet, but it appears possible that different timezones can be used for the searching vs. displaying the log entries. For searching the logs, it guesses the timezone based on web browser's settings:

https://github.com/TEAMMATES/teammates/blob/2a4a02e52671dadc197dd5de74dc9452ee7c32df/src/web/services/timezone.service.ts#L90-L91

For displaying the logs, it makes use of the feedback session's timezone instead:

https://github.com/TEAMMATES/teammates/blob/2a4a02e52671dadc197dd5de74dc9452ee7c32df/src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.ts#L182

**Comment by damithc** [comment]
Thanks for looking into this @halfwhole 

> I haven't confirmed this yet, but it appears possible that different timezones can be used for the searching vs. displaying the log entries. For searching the logs, it guesses the timezone based on web browser's settings:

If this is the case, the severity is low as most likely these two will be the same. The reason I noticed it is because I was masquerading as a different instructor (hence, my browser time zone doesn't match with the session)

> If we had to decide between one or the other, would we prefer using the web browser's timezone, or the feedback session timezone?

I guess it is better to use the session's time zone?


> On a sidenote, it looks like the times are compared lexicographically as strings, which is why `Mon, 21 Jun` comes before `Sun, 20 Jun` in the picture above

Need to fix that too, although that can be a different issue/PR.
