### ISSUE TITLE
Collapse All button visible when feedback session has no questions

### ISSUE THREAD

**Issue by samuelfangjw** [TEAMMATES/teammates#11215]
- **Environment**: `master` branch at commit 744b69a.

**Steps to reproduce**
1. Create a new feedback session.
2. Delete all questions.

**Expected behaviour**
Collapse all button is hidden.

<img width="1552" alt="Screenshot 2021-06-21 at 9 49 04 PM" src="https://user-images.githubusercontent.com/60355570/122773480-f9c3e300-d2da-11eb-90d6-177dcfcc5f6d.png">

**Actual behaviour**
Collapse All button is not hidden. Clicking on the button does not do anything.

<img width="1552" alt="Screenshot 2021-06-21 at 9 47 34 PM" src="https://user-images.githubusercontent.com/60355570/122773616-13652a80-d2db-11eb-9898-16a6283b1f3a.png">

**Comment by damithc** [comment]
Thanks for reporting this @samuelfangjw 
I wonder how much effort it will take to add this feature. If it takes a significant effort (i.e., it adds a significant amount of code), we can leave things be as it doesn't cause any harm anyway.

**Comment by samuelfangjw** [comment]
> Thanks for reporting this @samuelfangjw
> I wonder how much effort it will take to add this feature. If it takes a significant effort (i.e., it adds a significant amount of code), we can leave things be as it doesn't cause any harm anyway.

I believe a one line change similar to the example below should do the trick!

```diff
-  <div *ngIf="!isLoadingFeedbackQuestions" class="offset-md-10 margin-vertical-20px">
+  <div *ngIf="!isLoadingFeedbackQuestions && questionEditFormModels.length" class="offset-md-10 margin-vertical-20px">
    <button class="btn expand-btn btn-light margin-top-30px" (click)="isAllCollapsed ? expandAll() : collapseAll()">
      {{isAllCollapsed ? "Expand" : "Collapse" }} All
    </button>
  </div>
```

**Comment by damithc** [comment]
Thanks for the suggested solution @samuelfangjw 
Let me mark this as a first-timer issue then.

**Comment by moziliar** [comment]
Hi @Shubhojeetban sure! You may proceed!
