### ISSUE TITLE
Autoscrolling doesn't reach the correct question when moderating response

### ISSUE THREAD

**Issue by lyeyixian** [TEAMMATES/teammates#11219]
- **Environment**: `master` branch at commit https://github.com/TEAMMATES/teammates/commit/eb6f5dba9927a7149cf2a52f735199659374781a

**Steps to reproduce**
1. Instructor view a session result.
2. Instructor wants to moderate a response.

**Expected behaviour**

https://user-images.githubusercontent.com/58477697/122939239-0c571e80-d3a6-11eb-90f4-9f6a97b1030c.mp4

**Actual behaviour**
It started to have problem from question 3 onward

https://user-images.githubusercontent.com/58477697/122939609-5b04b880-d3a6-11eb-92b1-396647de6199.mp4

**Comment by damithc** [comment]
@lyeyixian thanks for reporting this. 
🤔  I wasn't aware auto-scrolling even exists for this case. I don't see any auto-scrolling in the the production version. Was the feature added recently? If you can locate the relevant code, you might be able to find when the feature was added.

**Comment by wkurniawan07** [comment]
@damithc #3290

**Comment by damithc** [comment]
> @damithc #3290

Thanks @wkurniawan07 (sorry, that one slipped my mind).

**Comment by tjtanjin** [comment]
Hello! May I try working on this?

**Comment by damithc** [comment]
> Hello! May I try working on this?

Sure @tjtanjin go ahead.
