### ISSUE TITLE
Feedback Rubric Question: Suggestion for Statistics Per Recipient

### ISSUE THREAD

**Issue by rrtheonlyone** [TEAMMATES/teammates#11210]
Right now in latest production branch we have the per recipient statistics feature. This looks like this:

<img width="797" alt="Screenshot 2021-06-20 at 8 43 44 PM" src="https://user-images.githubusercontent.com/10579415/122674542-3a9ef780-d208-11eb-82f9-93c7d606a7af.png">

The **Per Recipient Statistics (Overall)** feature is taking the sum of the average of sub questions divided by the number of sub questions. This opens up some ambiguity as to what value to use when there is no responses for the sub questions. The current implementation takes it as zero and uses that in the average calculations. **An alternative is to ignore sub questions with no responses completely. However, it just feels a little clunky to do it this way.**

I want to propose a slightly different format instead. Like this (for the same example above), in csv notation:

<img width="800" alt="Screenshot 2021-06-20 at 9 56 41 PM" src="https://user-images.githubusercontent.com/10579415/122676866-6e7f1a80-d212-11eb-8d2a-95da5de1784e.png">

The new format uses a similar notation as **Response Summary** and **Per Recipient Statistics (Per Criterion)**. We take the weighted sum and divide by the number of responses. This will give an indication to where a certain recipient lies in the range of weights that currently exist. There also won't be any ambiguity of zero weight vs no responses. We can also remove the assumption that all questions are equally weighted.

For your kind review @damithc.

**Comment by damithc** [comment]
> I want to propose a slightly different format instead. Like this (for the same example above), in csv notation:
> 
> <img alt="Screenshot 2021-06-20 at 9 56 41 PM" width="800" src="https://user-images.githubusercontent.com/10579415/122676866-6e7f1a80-d212-11eb-8d2a-95da5de1784e.png">
> 
> The new format uses a similar notation as **Response Summary** and **Per Recipient Statistics (Per Criterion)**. We take the weighted sum and divide by the number of responses. This will give an indication to where a certain recipient lies in the range of weights that currently exist. There also won't be any ambiguity of zero weight vs no responses. We can also remove the assumption that all questions are equally weighted.

Thanks for bringing this up @rrtheonlyone I'm fine with the proposed approach.

**Comment by u6867511** [comment]
Hi, just checking whether this issue has been fixed already?

**Comment by fsgmhoward** [comment]
@u6867511 I don't think so. You are good to submit a PR for this.

**Comment by u6867511** [comment]
May I please ask, where in the application can this feature be found? I am struggling to find a "Per Recipient Statistics" section. Thank you for your help.

**Comment by u6867511** [comment]
Hello, I was wondering, is it necessary to include the recipient's email in the Per Recipient Statistics (Overall) table? The Per Recipient Statistics (Per Criterion) section does not include the email.

**Comment by damithc** [comment]
> Hello, I was wondering, is it necessary to include the recipient's email in the Per Recipient Statistics (Overall) table? The Per Recipient Statistics (Per Criterion) section does not include the email.

@u6867511 Good to include it, as the email is the only reliable identifier we have (multiple students can have the same name).
