### ISSUE TITLE
Ensure !JDOHelper.isDeleted() check is done for all Datastore read operations

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#1122]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on August 11, 2013 11:04:36_

To be done in *Db classes.
This is to minimize 'trying to read attribute from deleted object' errors.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1123_

**Comment by kanghj** [comment]
This is fixed by #5126
