### ISSUE TITLE
Help Request: 11 tests failing everytime E2E tests ran locally

### ISSUE THREAD

**Issue by pPris** [TEAMMATES/teammates#11220]
- **Commit SHA:**  [latest commit on master](https://github.com/TEAMMATES/teammates/commit/eb6f5dba9927a7149cf2a52f735199659374781a)
- **Operating System:** Windows
- **JDK Version:** "corretto-1.8.0_292"
- **Node.js Version:** v14.17.0
- **Google Cloud SDK Version:** NIL 
- **Firefox / Chrome Version (if applicable):** NIL 

**What I was trying to do / What I need help with**

I've followed the development document closely and I've run the commands to set up the datastore emulator, then the backend, then the frontend, before running the e2e tests. 

About 11 e2e tests fail even on the 5th try, and this number is consistent. I'm not sure how to debug this, and as this is my first time exploring this repo, I'm wondering if there's any step I may have missed that seems obvious to others.

I've attached the stack trace for the 11 failed as it's quite long. Each time I run the tests, the error messages are similar, though for the `org.gradle.internal.serialize.PlaceholderException: Unable to locate element: [name of missing element]`, the name of the missing element may be different each time.

**Attempts to resolve the problem**

* I've checked the setup steps in the development.md. I've also checked troubleshooting document, the errors I received aren't covered there.
* I ran the e2e tests with both firefox and chrome and it's always 11 failing tests. 
* I also set up the e2e tests on my fork on github (to see if there may be anything wrong with my fork), and [the tests still pass](https://github.com/pPris/teammates/pull/1).

[teammates_e2e_stack_trace.txt](https://github.com/TEAMMATES/teammates/files/6696700/teammates_e2e_stack_trace.txt)

**Comment by madanalogy** [comment]
The problem is very likely with the Windows operating system though we don't really know why exactly. The e2e tests in our CI are run on Linux and our developers on iOS don't seem to have any problems with it locally. 

That being said, there shouldn't be any need for e2e test changes relating to issues targeted at new contributors. If the tests fail on a PR just leave a comment and we'll help look into it.

**Comment by pPris** [comment]
Ah I understand, was concerned I set up something wrongly. Thank you for the help!
