### ISSUE TITLE
Instructor home page: show spinner while copying sessions

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11227]
![image](https://user-images.githubusercontent.com/1673303/123449666-7c67dd80-d60e-11eb-9039-2b25a30a9ffe.png)

When this 'copy' button is clicked, a modal opens up. 
![image](https://user-images.githubusercontent.com/1673303/123449888-ab7e4f00-d60e-11eb-8a52-bc578a0cebb9.png)

Suggestion: When the user clicks the 'copy' button in that modal, show a spinner icon in the button until the copy operation is completed. Currently, the modal disappears immediately but the results of the copying doesn't appear for a while.

**Comment by lyeyixian** [comment]
Hi, I would like to work on this.

**Comment by rrtheonlyone** [comment]
@lyeyixian yes please go ahead

**Comment by lyeyixian** [comment]
Currently, the loading spinner is still present (replacing the session table) after closing the modal.

https://user-images.githubusercontent.com/58477697/123778450-af0e2080-d903-11eb-8eb4-0b45e72bc2d0.mp4



This is somewhat related to #11162, but the discussion there is stopped halfway without clear conclusion. So, I not sure if we should change to showing it beside the copy button.
@damithc need input from you prof.

**Comment by damithc** [comment]
> Currently, the loading spinner is still present (replacing the session table) after closing the modal.

@lyeyixian this issue is about the copy button in the instructor's home page, not the sessions page. Spinner-replacing-the-table behavior is not present in that page, right?

**Comment by lyeyixian** [comment]
Oh, yup sorry, I look at the wrong page.

**Comment by lyeyixian** [comment]
@damithc do you think this is ok, cos it's more consistent with the other page this way.

https://user-images.githubusercontent.com/58477697/123836772-a554df00-d93c-11eb-92de-6322b6442987.mp4

**Comment by damithc** [comment]
Hmm... what happens if the user choose multiple destination courses? Which page do we go to in that case? 
Even the UX of the other copy operations that you are trying t follow is not ideal. I feel like the spinner should appear in the button in the modal and the modal should stay until the operation is complete. After that, we can reload the current page (if its contents need updating) or go to a different page, as applicable.  But not sure how hard to accomplish that user flow. @lyeyixian @ccyccyccy what do you guys think?

**Comment by lyeyixian** [comment]
> Hmm... what happens if the user choose multiple destination courses? Which page do we go to in that case?

It will remain on the same page.

**Comment by damithc** [comment]
> > Hmm... what happens if the user choose multiple destination courses? Which page do we go to in that case?
> 
> It will remain on the same page.

OK, that makes sense.  But where do we show the spinner in that case?

Also, I'm not strictly opposed to what @lyeyixian proposed in https://github.com/TEAMMATES/teammates/issues/11227#issuecomment-870756083

At least it is consistent with other pages. Just a bit odd to the eye though.

**Comment by lyeyixian** [comment]
> OK, that makes sense. But where do we show the spinner in that case?

Currently, it's the same as copying to one course, where the table disappears and show a loading spinner. After finished copying, it will show the updated home page

**Comment by lyeyixian** [comment]
Here's the video clip of it.

https://user-images.githubusercontent.com/58477697/123947110-8f91f900-d9d2-11eb-86c2-5cbb689d5171.mp4

**Comment by damithc** [comment]
> Currently, it's the same as copying to one course, where the table disappears and show a loading spinner. After finished copying, it will show the updated home page

You mean in the new version that you implemented, right? 
Does it actually reload the page entirely from the backend (i.e., read all the data from the backend)? Or it's just a visual update of the page done on the frontend?

**Comment by lyeyixian** [comment]
> You mean in the new version that you implemented, right?

Yes

> Does it actually reload the page entirely from the backend (i.e., read all the data from the backend)? Or it's just a visual update of the page done on the frontend?

Nope, it's just a visual update.

**Comment by damithc** [comment]
> > Does it actually reload the page entirely from the backend (i.e., read all the data from the backend)? Or it's just a visual update of the page done on the frontend?
> 
> Nope, it's just a visual update.

Should be fine in that case. Go ahead @lyeyixian

**Comment by lyeyixian** [comment]
OK, I will create a PR now.
