### ISSUE TITLE
[V8] Adding tasks to task queue fails

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11226]
v8.0.0

I tried to send a reminder to a student but encountered the following error:
![image](https://user-images.githubusercontent.com/1673303/123448030-0fa01380-d60d-11eb-8ed0-f946dda379af.png)

The error in the log:
>AbstractMethodError caught by WebApiServlet: java.lang.AbstractMethodError: Receiver class com.google.api.gax.grpc.GrpcCallContext does not define or inherit an implementation of the resolved method 'abstract com.google.api.gax.retrying.RetrySettings getRetrySettings()' of interface com.google.api.gax.retrying.RetryingContext. at com.google.api.gax.retrying.ExponentialRetryAlgorithm.createFirstAttempt(ExponentialRetryAlgorithm.java:90) at com.google.api.gax.retrying.RetryAlgorithm.createFirstAttempt(RetryAlgorithm.java:112) at com.google.api.gax.retrying.BasicRetryingFuture.<init>(BasicRetryingFuture.java:80) at com.google.api.gax.retrying.CallbackChainRetryingFuture.<init>(CallbackChainRetryingFuture.java:63) at com.google.api.gax.retrying.ScheduledRetryingExecutor.createFuture(ScheduledRetryingExecutor.java:102) at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:61) at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:41) at com.google.api.gax.tracing.TracedUnaryCallable.futureCall(TracedUnaryCallable.java:75) at com.google.api.gax.rpc.UnaryCallable$1.futureCall(UnaryCallable.java:126) at com.google.api.gax.rpc.UnaryCallable.futureCall(UnaryCallable.java:87) at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112) at com.google.cloud.tasks.v2.CloudTasksClient.createTask(CloudTasksClient.java:1259) at com.google.cloud.tasks.v2.CloudTasksClient.createTask(CloudTasksClient.java:1242) at teammates.logic.core.GoogleCloudTasksService.addDeferredTask(GoogleCloudTasksService.java:59) at teammates.logic.api.TaskQueuer.addDeferredTask(TaskQueuer.java:47) at teammates.logic.api.TaskQueuer.addTask(TaskQueuer.java:41) at teammates.logic.api.TaskQueuer.scheduleFeedbackSessionRemindersForParticularUsers(TaskQueuer.java:84) at teammates.ui.webapi.RemindFeedbackSessionSubmissionAction.execute(RemindFeedbackSessionSubmissionAction.java:48) at teammates.ui.webapi.RemindFeedbackSessionSubmissionAction.execute(RemindFeedbackSessionSubmissionAction.java:13) at teammates.ui.webapi.WebApiServlet.invokeServlet(WebApiServlet.java:70) at teammates.ui.webapi.WebApiServlet.doPost(WebApiServlet.java:48) at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1452) at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791) at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626) at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at teammates.ui.webapi.OriginCheckFilter.doFilter(OriginCheckFilter.java:111) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at teammates.ui.webapi.RequestTraceFilter.lambda$doFilter$0(RequestTraceFilter.java:109) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by wkurniawan07** [comment]
This is also already known.
