### ISSUE TITLE
[V8] viewing sessions gives error 'failed to log access'

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11225]
version: V8.0.0
steps:
1. instructor views results of a session
2. instructor clicks on a 'moderate responses' button
3. the moderation page loads as expected but the following error message shows up as well
![image](https://user-images.githubusercontent.com/1673303/123445881-e8e0dd80-d60a-11eb-9ee7-a9e538a57d03.png)

I tried the same thing with V7 and there were no such error.

I tried accessing the submission page as a student and the same error showed up. It's possible that logging of session access is not working in V8 for some reason.

**Comment by wkurniawan07** [comment]
This is already known.

On an unrelated note, there is no such version as V8.0.1. V8 is still at pre-release stage for at least a few more weeks.

**Comment by damithc** [comment]
>This is already known.

I see. What's the cause?

> On an unrelated note, there is no such version as V8.0.1. V8 is still at pre-release stage for at least a few more weeks.

Changed it to v8.0.0

**Comment by wkurniawan07** [comment]
> What's the cause?

Conflicting dependency version.

> Changed it to v8.0.0

Still not accurate. The closest thing we have is [V8.0.0-beta.0](https://github.com/TEAMMATES/teammates/releases/tag/V8.0.0-beta.0), and the commit that has the question ID hotfix is untagged. Pre-releases cannot be treated the same as proper releases.

**Comment by damithc** [comment]
> Conflicting dependency version.

I see. What's the way forward?

**Comment by wkurniawan07** [comment]
> What's the way forward?

Updating some dependencies. This is a straightforward code fix of not more than 10 lines of code, no cause of concerns.
