### ISSUE TITLE
Feedback session table doesn't differentiate grace period and open status

### ISSUE THREAD

**Issue by pPris** [TEAMMATES/teammates#11237]
**Steps to reproduce**

I used these settings and to my understanding, this feedback session should be in the GRACE_PERIOD status (it's 5:14 pm at time of screenshot)
![image](https://user-images.githubusercontent.com/49683462/123771603-c518e280-d8fd-11eb-954d-e93cdd1a1798.png)

**Expected behaviour**

The sessions table should indicate to the instructor if a feedback session is in the grace period.

**Actual behaviour**

Seems like the submission in the feedback session table says that the feedback is open and there's no mention of grace period in the table and the tooltips

![image](https://user-images.githubusercontent.com/49683462/123771610-c77b3c80-d8fd-11eb-8f30-bd77073e3fa0.png)

**Additional info**

It's a minor issue but could help clarify the status to instructors.

Fixing this might involve just two files 1) submission-status-name.pipe 2) submission-status-tooltip.pipe

**Comment by damithc** [comment]
Thanks for raising this @pPris 
If it can be done without a lot of extra code, we can show `Open (grace period)` during that period, and change the tooltip accordingly.

**Comment by xyzhang00** [comment]
Hi, may I try working on this issue?

**Comment by damithc** [comment]
> Hi, may I try working on this issue?

@TEAMMATES/active-mentors is this suitable as a first time issue? I'm not sure if this requires any API changes.

**Comment by daongochieu2810** [comment]
> > Hi, may I try working on this issue?
> 
> @TEAMMATES/active-mentors is this suitable as a first time issue? I'm not sure if this requires any API changes.

The front-end seems to have all necessary info, so probably no API changes needed for this issue

**Comment by damithc** [comment]
> The front-end seems to have all necessary info, so probably no API changes needed for this issue

Thanks for checking @daongochieu2810 Go ahead @xyzhang00
