### ISSUE TITLE
Co-owners cannot edit sessions

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11248]
V7

Reported by a user:
![image](https://user-images.githubusercontent.com/1673303/124109373-a2bbcc00-da99-11eb-8535-49e9447bcd3a.png)

This user is a co-owner of the course but the `Edit` button is disabled.

Steps to repro:
1. Add an instructor at `tutor` permission level (user cannot edit sessions, as expected)
2. Upgrade the user to `co-owner`
3. Problem: user still cannot edit sessions

We need a hot-fix, as this is affecting current users.

**Comment by damithc** [comment]
I can't reproduce it elsewhere though. Must be something specific to this specific case. I'll try to find out more from the user.

**Comment by damithc** [comment]
Managed to replicate the problem. Updated the description.

**Comment by wkurniawan07** [comment]
This is the same problem as #10973.

**Comment by damithc** [comment]
> This is the same problem as #10973.

Ah, that's why I felt like I've seen something like this before. Let's fix it this time.

**Comment by wkurniawan07** [comment]
Fixes in #11258
