### ISSUE TITLE
Instructor editing student details: show spinner while saving

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11244]
![image](https://user-images.githubusercontent.com/1673303/123967669-1c47b180-d9e9-11eb-9c7f-43b8f120f1e0.png)

Suggestion: 
1. Add a suitable icon in front of the `Save Changes` label
2. Change the icon to a spinner while the saving is in progress

**Comment by damithc** [comment]
@TEAMMATES/active-mentors is this issue suitable for first-timers?

**Comment by ccyccyccy** [comment]
Looks like it

**Comment by sarojku17** [comment]
Hi @damithc & @ccyccyccy  Can I start looking into it :)

**Comment by damithc** [comment]
@sarojku17 sure, go ahead.

**Comment by tramsy** [comment]
i am new bee can you help how i contribute in it

**Comment by halfwhole** [comment]
Hi @sarojku17, would you be looking into the issue sometime? Otherwise, we might want to let @tramsy have a go at it too (if you're still interested in contributing)!

**Comment by josiahkhoo** [comment]
Hi, can I resolve this issue if no one is working on this at the moment?

**Comment by damithc** [comment]
> Hi, can I resolve this issue if no one is working on this at the moment?

Go ahead @josiahkhoo

**Comment by oryaakov2** [comment]
hey, can i resolve this issue? thats my first time i contribute.

**Comment by sarojku17** [comment]
Yes , please go ahead .
