### ISSUE TITLE
Support running client scripts via Gradle

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11245]
I used to run client scripts  (i.e., those in `src\client\java\teammates\client\scripts`) using Intellij but I would like to be able to run them using Gradle in future. Probably some tweaks to the build.gradle needed for that?

**Comment by damithc** [comment]
For reference, something like this needs to be added (provided by @wkurniawan07 )
```
task execScript(type: JavaExec) {
    classpath = sourceSets.test.runtimeClasspath
    main = "teammates.client.scripts.YourScriptName"
}
```

**Comment by NicolasCwy** [comment]
Ill give this a shot!

**Comment by NicolasCwy** [comment]
Do all scripts contain a main function which takes in no arguments or should we accept command line arguments(if any) to be passed to the script?

**Comment by NicolasCwy** [comment]
Hi Prof would users have to manually change the placeholder your script name or is do we take in the script name from the command line?

**Comment by damithc** [comment]
> Hi Prof would users have to manually change the placeholder your script name or is do we take in the script name from the command line?

@NicolasCwy Latter is preferred but the former is OK too (a bit messy if I have to change the build.gradle locally as it is under version control).
