### ISSUE TITLE
Instructor audit logs: error in 'from' date for first day of the month

### ISSUE THREAD

**Issue by halfwhole** [TEAMMATES/teammates#11246]
On the first day of the month, the instructor audit logs page at `/web/instructor/logs` does not have a proper 'from' date:

<img width="1237" alt="Screenshot 2021-07-01 at 3 24 32 PM" src="https://user-images.githubusercontent.com/41856541/124083514-88292900-da80-11eb-9b32-408c83171acb.png">

Appears to be a boundary error caused by simply subtracting 1 from the day, without wrapping around to the previous month:

https://github.com/TEAMMATES/teammates/blob/9bf9c078ec2488918b9e44d608b186a21333406b/src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.ts#L97

This also caused the recent failure in E2E tests https://github.com/TEAMMATES/teammates/actions/runs/988294367

**Comment by damithc** [comment]
Thanks for reporting this @halfwhole

**Comment by lyeyixian** [comment]
Hi, can I try this out?

**Comment by halfwhole** [comment]
Sure, please go ahead
