### ISSUE TITLE
Copying sessions from the home page results in temporary duplicate sessions being shown

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11242]
Steps that I took:
1. Go to instructor home page
2. Click on the copy button of a session
3. Select to copy to multiple courses (some of which are inside collapsed panels)
4. Finish the copy operation.
5. When I expand the course panel of one of the destination courses, I see an extra duplicate of the copied session.

![image](https://user-images.githubusercontent.com/1673303/123843362-6b87d680-d944-11eb-94ee-b44d1cd2c4a0.png)

The duplicate goes away upon refreshing the page. So I guess this is a front-end glitch.

After refreshing:
![image](https://user-images.githubusercontent.com/1673303/123843862-ec46d280-d944-11eb-9acf-83546561aa1a.png)

**Comment by tjtanjin** [comment]
Hello! May I try working on this issue?
