### ISSUE TITLE
Instructor Feedback Session Results: Session Duration formatting

### ISSUE THREAD

**Issue by Jellybeano** [TEAMMATES/teammates#11254]
- **Environment**:  `master` branch at commit f4924bb3225d25c1e14a499cb563d1106b606949

**Steps to reproduce**
From the Instructor Home page, view the results of any course. (Results -> View Results)

**Expected behaviour**
The Session Duration dates are each on separate lines if there is not enough space.
![image](https://user-images.githubusercontent.com/65604398/124381773-d6dff880-dcf6-11eb-86f0-8a022a9e6fab.png)

**Actual behaviour**
The Session Duration date (usually the second one) is cut off depending on the window size.
![image](https://user-images.githubusercontent.com/65604398/124381845-2292a200-dcf7-11eb-8b52-0d3bef9789e9.png)

**Additional info**

Very small visual bug, might not warrant fixing at all.

Could possibly be solved as seen above in expected outcome by changing regular spaces to non-breaking spaces for dates in instructor-session-result-page.component.ts, and adding minor tweaks in instructor-session-result-page.component.html

**Comment by lyeyixian** [comment]
Hi, I would like to work on this.

**Comment by ericluoliu** [comment]
Working on this

**Comment by ericluoliu** [comment]
When I try to build the front-end developer environment to re-create the formatting issue shown above, I get the message saying authorization to /web/admin/home is denied. I added my Google User ID to the build.properties 'app.admins' property but I still cannot set up the instructor account.

**Comment by damithc** [comment]
> When I try to build the front-end developer environment to re-create the formatting issue shown above, I get the message saying authorization to /web/admin/home is denied. I added my Google User ID to the build.properties 'app.admins' property but I still cannot set up the instructor account.

@TEAMMATES/active-mentors any advice for @ericluoliu ?

**Comment by daongochieu2810** [comment]
@ericluoliu Ensure that the datastore and server are running, and if it still fails, please send us your build.properties

**Comment by ericluoliu** [comment]
Building the servers seem to get stuck at 85% completion.
![image](https://user-images.githubusercontent.com/54130092/125833856-857ddf56-72ca-49a6-9605-45099299d49c.png)

Any ideas?

**Comment by Jellybeano** [comment]
85% completion after running the serverRun command appears to be the norm and not cause an issue when loading the webpage; perhaps could the root problem lie somewhere else? 

(also leaving the link to the [development environment set up guide](https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md) here!)
