### ISSUE TITLE
Instructor viewing students: incorrect message flashed before populating the page

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11260]
Steps:
1. Login as an instructor
2. Click this option
   ![image](https://user-images.githubusercontent.com/1673303/125075588-6a4b6c00-e0f1-11eb-80ff-b63def3ac229.png)

Problem: The next page shows a 'no students in this course' warning momentarily before populating the page, even if the course actually has students. 

Note: Might not be visible when using the dev server as the page will get populated quickly.

**Comment by lyeyixian** [comment]
I would like to work on this.

**Comment by damithc** [comment]
> I would like to work on this.

Go ahead @lyeyixian
