### ISSUE TITLE
Checkboxes aligned via center instead of start when choosing from template questions

### ISSUE THREAD

**Issue by xyzhang00** [TEAMMATES/teammates#11270]
**Environment**: `master` branch at commit 6484257

**Steps to reproduce**
From edit feedback session page, click Add New Question -> Choose from template questions.

**Expected behaviour**
Checkboxes aligned to the first line when there are multiple lines.
<img width="646" alt="Screenshot 2021-07-13 at 9 45 04 PM" src="https://user-images.githubusercontent.com/54242896/125485997-af829738-9767-4e8b-82c8-b11aaebe4439.png">

**Actual behaviour**
Checkboxes are aligned in the center when there are multiple lines.
<img width="646" alt="Screenshot 2021-06-21 at 8 34 59 PM" src="https://user-images.githubusercontent.com/54242896/122763279-ba909480-d2d0-11eb-9b06-d2d2061cd2de.png">

**Additional info**
Modifying files `template-question-modal.component.scss` and `template-question-modal.component.html` should be sufficient to fix this.

**Comment by srijit2002** [comment]
Hey, I am a newbie to open source. So can I take it?

**Comment by srijit2002** [comment]
> **Environment**: `master` branch at commit [6484257](https://github.com/TEAMMATES/teammates/commit/648425746bb9434051647c8266dfab50a8f2d6a3)
> 
> **Steps to reproduce**
> From edit feedback session page, click Add New Question -> Choose from template questions.
> 
> **Expected behaviour**
> Checkboxes aligned to the first line when there are multiple lines.
> <img alt="Screenshot 2021-07-13 at 9 45 04 PM" width="646" src="https://user-images.githubusercontent.com/54242896/125485997-af829738-9767-4e8b-82c8-b11aaebe4439.png">
> 
> **Actual behaviour**
> Checkboxes are aligned in the center when there are multiple lines.
> <img alt="Screenshot 2021-06-21 at 8 34 59 PM" width="646" src="https://user-images.githubusercontent.com/54242896/122763279-ba909480-d2d0-11eb-9b06-d2d2061cd2de.png">
> 
> **Additional info**
> Modifying files `template-question-modal.component.scss` and `template-question-modal.component.html` should be sufficient to fix this.

I am a beginner in open source. Can you please  tell me how can I run this web app?

**Comment by toth2000** [comment]
I would like to work on this issue.

**Comment by halfwhole** [comment]
@toth2000 Please go ahead!

**Comment by A-GHOSH-dev** [comment]
Is this issue solved? Or can I work on it?
