### ISSUE TITLE
Distribute points among options question: negative points allowed on frontend

### ISSUE THREAD

**Issue by halfwhole** [TEAMMATES/teammates#11295]
Very minor issue that's unlikely to be encountered in practice, but the frontend allows for points to be negative without showing any error:

<img width="1106" alt="Screenshot 2021-07-22 at 5 29 46 PM" src="https://user-images.githubusercontent.com/41856541/126619816-4f2a9093-cef9-451d-bf9b-53af25044f55.png">

The question submission will still fail as the backend does not allow for negative points

**Comment by damithc** [comment]
Thanks for catching this @halfwhole 👍 
It brings up the question, "should we support negative points as well?" 
Anyway, as the backend doesn't support it ATM, and the benefits of supporting it is not clear, I think we should block it on the frontend as well.

**Comment by brandonfoong** [comment]
Hi, may I try to resolve this issue?

**Comment by rrtheonlyone** [comment]
@brandonfoong sure please go ahead

**Comment by rhit-namburs** [comment]
Hi may I try and fix this issue!

**Comment by ypinhsuan** [comment]
@rhit-namburs Hi! There is already a PR for this issue, please look for another issue to work on.

**Comment by shubham-singh-748** [comment]
Hey may i contribute

**Comment by daongochieu2810** [comment]
@shubham-singh-748 there is an open PR for this issue, please look for another issue, thanks

**Comment by zhaojj2209** [comment]
Hello! It seems that this issue has not been updated for some time, may I work on it?
