### ISSUE TITLE
Instructor searching: previous results are shown if search encounters an error

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11299]
v8.0.0.rc.0

Problem: The previous results are shown the search encountered an error
![image](https://user-images.githubusercontent.com/1673303/126861349-99a8606c-86d1-4510-9278-87d2a58991a3.png)

**Comment by wkurniawan07** [comment]
Is this really a problem? This simply means there is no new search result to replace the existing one.

**Comment by damithc** [comment]
> Is this really a problem? This simply means there is no new search result to replace the existing one.

There are two issues, although neither is a big problem:

* The keywords and the results don't match anymore, and the matching keywords are no longer visible on the UI.
* The search results disappear first and come back after the error message. So visually, they appear like new results being shown rather than old results not being cleared.

**Comment by jianhandev** [comment]
> * The keywords and the results don't match anymore, and the matching keywords are no longer visible on the UI.

Able to replicate this, I think clearing old results when an error is encountered should be able to solve this problem.

> * The search results disappear first and come back after the error message. So visually, they appear like new results being shown rather than old results not being cleared.

I didn't manage to replicate this however.
