### ISSUE TITLE
Drop downs for further actions in tables expands by adding scrolling to table

### ISSUE THREAD

**Issue by ChooJeremy** [TEAMMATES/teammates#11309]
- **Environment**: master branch at commit 2416bc5807b8400f78cf67d9246256bbc486379d

**Steps to reproduce**
1. Create a new course and a new feedback session for that course.
2. Go to courses page
3. Resize page such that the row of the table spans a height of 2
4. Click results on the lowest row on the table, of the first course  (the 2nd course doesn't have this issue)

**Actual behaviour**
The drop down created through results is blocked and hidden.
<img width="883" alt="Screen Shot 2021-07-26 at 12 20 00 AM" src="https://user-images.githubusercontent.com/4904988/126906185-83c39222-9a7b-4140-913d-16ecb44c52ce.png">
They're actually expanding properly, not being clipped, but the user needs to scroll within the table to select the options.
<img width="875" alt="Screen Shot 2021-07-26 at 12 20 17 AM" src="https://user-images.githubusercontent.com/4904988/126906205-6aae26a6-833b-4d25-a00f-71aaac47066a.png">
(It is not shown in the screenshot, but there's actually a scroll bar on the right, on only the table)

**Expected behaviour**
The drop down should either clip through the bottom
<img width="1222" alt="Screen Shot 2021-07-26 at 12 20 50 AM" src="https://user-images.githubusercontent.com/4904988/126906218-7513e03b-f756-4a0e-a189-e18ff27c3401.png">
Or display towards the top
<img width="872" alt="Screen Shot 2021-07-26 at 12 20 30 AM" src="https://user-images.githubusercontent.com/4904988/126906223-f3cb3dc2-e8fe-498c-806b-8c1fff4d2c5c.png">

**Additional info**

The issue doesn't occur if this is the last course in the list. (In which case, it displays towards the top). 
The issue also doesn't occur if the table row only spans one light (in which case, it clips through the bottom).  
This issue affects other pages too, such as the feedback sessions page.

**Comment by samuelfangjw** [comment]
Hi, I would like to work on this if possible!

**Comment by damithc** [comment]
Go ahead @samuelfangjw
