### ISSUE TITLE
Admin search: increase the search result cap

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11302]
v8.0.0.rc.0 (but applicable to V7 as well)

Current: when admin searches for a user, search results are capped at 20 results only, with no indication of whether there are more results. 

Suggestions:
1. Increase the cap to a higher number e.g., 50
2. If the cap is reached, also display a message to caution the user that there can be more results not shown
3. Check if the same applies to instructor search page, and do the same

**Comment by tjtanjin** [comment]
Hello! May I try working on this?

**Comment by damithc** [comment]
> Hello! May I try working on this?

Sure.
