### ISSUE TITLE
Compare table elements that are expected to be numbers numerically

### ISSUE THREAD

**Issue by xyzhang00** [TEAMMATES/teammates#11327]
- **Environment**: `master` branch at commit 8a97db6

**Steps to reproduce**
Instructor views the result of a session question, like a rank recipients question with more than 10 possible ranks.

**Expected behaviour**
Table elements expected to be numbers are compared numerically and sorted in the correct order.

**Actual behaviour**
<img width="144" alt="Screenshot 2021-07-31 at 10 26 21 PM" src="https://user-images.githubusercontent.com/54242896/127742949-a6284fed-74fe-4f2e-8242-f4c8aceefe5d.png">

**Additional info**
Referring to file[ `table-comparator.service.ts`](https://github.com/TEAMMATES/teammates/blob/master/src/web/services/table-comparator.service.ts). Elements `RANK_RECIPIENTS_SELF_RANK`, `RANK_RECIPIENTS_OVERALL_RANK`, `RANK_RECIPIENTS_TEAM_RANK` etc. faces the above issue. For elements like `RANK_OPTIONS_OVERALL_RANK` and `MCQ_RESPONSE_COUNT`, while they are correctly sorted via natural ordering, it might be more appropriate to sort them numerically as well as they are expected to be numbers.

**Comment by arsatis** [comment]
Hi, may I try to resolve this issue?

**Comment by damithc** [comment]
> Hi, may I try to resolve this issue?

Sure, go ahead.
