### ISSUE TITLE
Update Angular to 12

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#11345]
- Drop browser support for IE 9, 10, and IE mobile
- TypeScript 4.2.3+
- Critical CSS inlining
- Migrate TSLint to ESLint (back to where we started)

**Comment by hoanglan21** [comment]
hi, can I work on this?

**Comment by moziliar** [comment]
Hi @hoanglan21 , it seems that you are new to this project. Perhaps you want to take a look at issues with label "good-first-issue" to get yourself warmed up in the project.
