### ISSUE TITLE
Spacing of contents within Example box can be improved

### ISSUE THREAD

**Issue by xinyee20** [TEAMMATES/teammates#11341]
Page: `/web/front/help/instructor`

Looks relatively squashed

<img src="https://user-images.githubusercontent.com/63994179/128227884-cb1451d1-e00e-4e87-9119-995c53c57d1b.png" width="450">

**Comment by xinyee20** [comment]
Fixed issue in https://github.com/TEAMMATES/teammates/pull/11342

**Comment by ahmedabd1** [comment]
p.VeryLow
