### ISSUE TITLE
Release the results-view-tracking feature to users

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11351]
Currently, the feature that allows instructor to track who viewed session results can only be accessed through the `/instructor/track-result-view` URL.
We should expose this feature to users through the UI.

Add: Need to mark the features as "Beta" as they are known to not scale well. A search for 30 days taking about 3-4 minutes is faster than expected, but letting the user wait that long without any indicator is outright bad UX.

**Comment by wkurniawan07** [comment]
@damithc remind me again, why do we have to split the tracking pages for access + submission and viewing results, when they are doing almost the exact same thing?

**Comment by damithc** [comment]
> @damithc remind me again, why do we have to split the tracking pages for access + submission and viewing results, when they are doing almost the exact same thing?

The use cases are a bit different. For submission/access, it's usually to verify if a student's claim that s/he submitted, or tried to submit. Results viewing is if the instructor is interested to find out who didn't even bothered to look at the results. The UI can provide a common entry point for both but we probably need two different UIs for the two use cases.

**Comment by wkurniawan07** [comment]
> verify if a student's claim that s/he submitted, or tried to submit

> find out who didn't even bothered to look at the results

I can switch the actions in the two sentences and they're still valid use cases.

**Comment by damithc** [comment]
> I can switch the actions in the two sentences and they're still valid use cases.

Valid? yes. Needed? questionable.

* "who didn't bother to submit?" is already catered for by the results page, reminders etc.
* I haven't faced a case where student claimed s/he viewed the results and I had to go and verify it. Even if I had to, it's unlikely I'll be interested in exact timing and how many times -- just yes/no only.

**Comment by wkurniawan07** [comment]
On hold pending #11812.

**Comment by cedricongjh** [comment]
closed in https://github.com/TEAMMATES/teammates/pull/12973, users will be able to access the logs page through the courses page (provided that the course is migrated)
