### ISSUE TITLE
Empty results in instructor audit logs and results view tracking

### ISSUE THREAD

**Issue by halfwhole** [TEAMMATES/teammates#11354]
On the latest `master` branch, the results view tracking and audit logs features don't seem to be working for me on both staging and production, does anyone have the same issue? The results returned are all empty, even when I've viewed/submitted the feedback session.

![Screenshot 2021-08-11 at 2 44 44 PM](https://user-images.githubusercontent.com/41856541/128982939-593a931a-0d57-4a60-a249-e4e7b244b6c6.png)
![Screenshot 2021-08-11 at 2 47 01 PM](https://user-images.githubusercontent.com/41856541/128982945-03f3f0ab-fa73-44d0-8d20-95bc5365f624.png)

**More details**

Upon investigating it further on staging, it seems to be adding `severity>=INFO` to the log filters, e.g.:

```
timestamp>"2021-08-10T15:59:00Z"
timestamp<="2021-08-11T15:59:00Z"
severity>=INFO
labels.courseId="limziwei2.gma-demo6"
logName=("projects/teammates-zw/logs/feedback-session-logs")
```
I'm guessing this is what's leaving out the feedback session logs, which have default severity rather than info severity

**Comment by wkurniawan07** [comment]
Very likely my bad on this. It was me who attempted to streamline all log types after all.
