### ISSUE TITLE
Instructor sample data: defer creation until instructor joins

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#11371]
- **Environment**: V8.0.2, but problem exists since as far back as V6.0.0

**Description of feature/enhancement**

As discussed in https://github.com/TEAMMATES/teammates/issues/11243#issuecomment-898993617.

Only create instructor sample data when the instructor joins.

**Justification**

- If the requesting instructor never uses the system, no sample data is being wasted
- User can supply more information to further customize the sample data, such as timezone (ref: #8787)
- If the account request is persisted in a new entity, this entity can also contain the institute, which means there's no longer a need for institute verification with HMAC value

**Existing similar features and their shortcomings**

Instructor sample data is created when the account is created, which leads to the problems mentioned before.

**Comment by wkurniawan07** [comment]
@samuelfangjw are you interested to work on this? This is a good issue that reaches many different aspects of the system, possibly including a new entity creation as well.

**Comment by samuelfangjw** [comment]
> @samuelfangjw are you interested to work on this? This is a good issue that reaches many different aspects of the system, possibly including a new entity creation as well.

This sounds like fun, I'll give it a shot!
