### ISSUE TITLE
Copying question from another session: optimize fetching of available questions

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#11370]
Current: copying question requires fetching of all questions from all sessions available to a user.

<img width="1000" alt="Screenshot 2021-08-16 at 6 48 14 PM" src="https://user-images.githubusercontent.com/7261051/129552612-0a5d48e9-3a92-4817-923b-0eb697b2a7c5.png">

Problems:
- If the user has large number of sessions, this will introduce a burst of parallel API calls
- If the user knows exactly which question/s s/he want, this is a wasted effort and a major noise in the table
- Even if the user needs to scroll to find out the question/s s/he want, chances are s/he might have found it/them by the time the middle of table is visited; that means the bottom half of the table is wasted

Solutions:
- Fetch only questions from a few sessions at a time
- Add option to "Load more" (similarly, only from the next few sessions) if the user has not found the question/s s/he want
- Allow user to decide which session to populate the question list from

**Comment by damithc** [comment]
Most likely the user will know which session has the question(s) she wants to copy. Another alternative is to load the session names first as collapsed panels and let the user fetch questions by expanding the panel of the target session.

**Comment by moziliar** [comment]
@daongochieu2810 let's take a look?

**Comment by daongochieu2810** [comment]
@moziliar I think prof @damithc 's suggestion works, should we proceed with that?

**Comment by moziliar** [comment]
@daongochieu2810 sounds good, also good from the UX's POV.

**Comment by SimonHasak** [comment]
Hi, I would like to take this task. I have 1,5 year experience as a full stack developer java (spring boot) and angular. I will need more information (for example how many objects will page contains and so on..). Of course if you already decided how to solve this issue. WIll wait for your reply. Thanks.

**Comment by daongochieu2810** [comment]
> Solutions:

> Fetch only questions from a few sessions at a time
> Add option to "Load more" (similarly, only from the next few sessions) if the user has not found the question/s s/he want
> Allow user to decide which session to populate the question list from

> Most likely the user will know which session has the question(s) she wants to copy. Another alternative is to load the session names first as collapsed panels and let the user fetch questions by expanding the panel of the target session.

@SimonHasak I think you can proceed with either suggestion above. The number of objects a page can contain can be 50. Let me know if you have any other questions

**Comment by SimonHasak** [comment]
@daongochieu2810 Just to be sure this solution is needed for every object fetching its questions?. Not only instructor let`s say. As a solution I would like to insert Cursor to the query builder but it is base method for all object containing questions so I would like to clarify this. Thanks.
![image](https://user-images.githubusercontent.com/25928579/145404569-7cd553cc-fb03-4cee-ad00-0f2fde314ac3.png)

**Comment by daongochieu2810** [comment]
@SimonHasak this issue only concerns the copy operation for questions, so modifying code for fetching is not a good idea. I think you can create another method called `getFeedbackQuestionsWithLimit` so it will not affect other operations

**Comment by daongochieu2810** [comment]
@SimonHasak Let us know if you are still working on this issue. Thanks!

**Comment by SimonHasak** [comment]
@daongochieu2810 Hi, yes I am. Will update you with design and implementation till Friday.

**Comment by SimonHasak** [comment]
@daongochieu2810 Sorry but no more working on this issue.

**Comment by zhaojj2209** [comment]
Since this issue is no longer being worked on, I'll try working on it!
