### ISSUE TITLE
Registration keys should be encrypted only before inserted into DB

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#11375]
Current: Student and instructor registration keys are encrypted/decrypted on the go, just before passing to the API/logic layer from the logic/API layer and just before inserting into URLs pasted in emails.

Problem:
- This caused the key used for encryption to be coupled to the users and cannot be changed/rotated without affecting users (see #11374)
- (not necessarily a problem, but worth a mention) This does not provide any additional protection against leakage; if a user leaks his/her registration key, the fact that it is encrypted offers no additional protection.

Solution:
- Encrypt the key immediately before inserting to DB

Data migration status:
- [x] Merged code that work for both the old and new versions of the data schema.
- [x] Released a version containing the above in V8.1.0.
- [x] Created a client script to migrate all data following the old schema to the new schema in PR #11375.
- [x] Ran the script against the live site.
- [ ] Removed the code that is specifically tailored for the old data schema in PR #.

**Comment by damithc** [comment]
> @damithc there are two scripts to be run here: `DataMigrationForUnencryptedKeyForInstructors.java` and `DataMigrationForUnencryptedKeyForStudents.java`.

Both done.
