### ISSUE TITLE
Help Request: Cannot access logged in zone of TEAMMATES

### ISSUE THREAD

**Issue by xinyee20** [TEAMMATES/teammates#11387]
- **Operating System:** Windows 10 64-bit operating system
- **JDK Version:** 11.0.6
- **Node.js Version:** 14.17.4
- **Firefox / Chrome Version (if applicable):** 92.0.4515.159 (Windows)

**What I was trying to do / What I need help with**
I have been trying to access the instructor logged in zone of TEAMMATES through `http://localhost:8080` so that I can understand the issue that I am trying to attempt (#11162 ) better, but have not been able to access the log in page when I went to `http://localhost:8080/web/admin/home`
![image](https://user-images.githubusercontent.com/63994179/130352682-cd2a080c-c48e-4377-985e-1726d450e6e1.png)

**Attempts to resolve the problem**

Steps I have tried: 
(following https://github.com/TEAMMATES/teammates/blob/master/docs/development.md)
1) - run `gradlew.bat generateTypes` --> `npm run start` in terminal 1 --> `gradlew.bat serverRun &` in terminal 2 
2) - run `gradlew.bat generateTypes` --> `npm run start` in terminal 1 --> `gradlew.bat serverRun` in terminal 2
3) - download docker and run `gradlew.bat generateTypes` --> `npm run start` in terminal 1 --> `docker-compose up -d` in terminal 2  --> `gradlew.bat serverRun` in terminal 2 (executing at around 85%)
(managed to successfully create TEAMMATES project in docker but still can't view `http://localhost:8080/web/admin/home`)
![image](https://user-images.githubusercontent.com/63994179/130352887-e18b383b-c2e2-4198-a836-7f095273bd75.png)
![image](https://user-images.githubusercontent.com/63994179/130357179-00af6787-7256-4afa-8075-1d743e06e6d1.png)

Outcome for all 3 ways: can access `http://localhost:4200/web/front/home`, when try to access `http://localhost:8080/web/admin/home` , site just refreshes back to `http://localhost:8080/web/front/home`, rather than being prompted to key in log in credentials

**Comment by xinyee20** [comment]
Managed to resolve this issue:
I tried logging out and logging back in then it prompted me to log in so I could log in as an admin. I click the upper right hand corner to access the add instructor page and I managed to get into the instructor page.

**Comment by moziliar** [comment]
Thanks for the investigation. You can actually see the backend input and see what went wrong.

From what I see in your attempts, you didn't quite start the datastore emulator (can be started natively I believe; but docker-compose is the recommended way), and hence the default admin info cannot be written into it for login use.

**Comment by wkurniawan07** [comment]
@moziliar admin info is not persisted to DB.

What actually happened:
https://github.com/TEAMMATES/teammates/blob/33eaddd39fda83c634136747f5b4dce3f6c1a1c4/src/web/app/pages-admin/admin-page.component.ts#L61-L67
Although that comment (`the /web/admin/* routing is protected`) is no longer true.

**Comment by moziliar** [comment]
Ah I see. @wkurniawan07 My assumption is wrong here. Thanks for the correction.
