### ISSUE TITLE
Remove numOf* fields from question details structure

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#11388]
https://github.com/TEAMMATES/teammates/blob/1ae8c57f005c74b8b596b19c7d8cf164d145d5ee/src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java#L33-L36

https://github.com/TEAMMATES/teammates/blob/1ae8c57f005c74b8b596b19c7d8cf164d145d5ee/src/main/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetails.java#L30-L31

https://github.com/TEAMMATES/teammates/blob/1ae8c57f005c74b8b596b19c7d8cf164d145d5ee/src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java#L35-L36

These question details have `numOf*` fields. They are unnecessary and all places where they are used can be replaced with `.size()` (or `.length`) of the list they are representing without any side effect. In fact, adding `numOf*` adds unnecessary risk of the two numbers getting out of sync.

**Comment by singhsiddharth10** [comment]
I want to take this issue.

**Comment by t-cheepeng** [comment]
@singhsiddharth10 Hi, you are welcome to take up the issue

**Comment by singhsiddharth10** [comment]
@wkurniawan07 Only these 3 files contains numOf* fields or any other files also contain these fields ?

**Comment by singhsiddharth10** [comment]
@t-cheepeng, As my laptop is hardened I won't be able to setup this project locally on my system. So, I won't be able to take up this issue. Sorry for the inconvenience.

**Comment by thefreakingmind** [comment]
Can I take this issue?

**Comment by moziliar** [comment]
@thefreakingmind sure, go ahead!

**Comment by thefreakingmind** [comment]
Solved https://github.com/TEAMMATES/teammates/pull/11397 Changed the Java Files not sure about frontend. Will check it once.

**Comment by darkalok** [comment]
Hello, I want to take this issue. I am new to open source development. So, I want to start with something simple. If this issue is closed , can you assign me another issue for a beginner to start with.

**Comment by moziliar** [comment]
@darkalok Hi, this issue is still being worked on by a developer.

You can look for any issues with the label "good first issue" to start! They are beginner-friendly and our maintainers would be happy to guide you to completion.

**Comment by darkalok** [comment]
Should , I take this issue or some other . Please guide . I will give my
best.

**Comment by moziliar** [comment]
@darkalok you should look for another issue while this issue is being worked on by another developer.

**Comment by darkalok** [comment]
Thanks, I'll check it out.

**Comment by shubham-singh-748** [comment]
Hey can you please refer me these type type of projects?
please....

**Comment by jianhandev** [comment]
@shubham-singh-748 if you are new to the project look for issues tagged with `good first issue` they are usually more beginner-friendly, look forward to your contribution!

<img width="303" alt="Screenshot 2021-09-06 at 11 41 26 PM" src="https://user-images.githubusercontent.com/59337195/132240448-957c6f43-2c63-41f9-9d53-31c753d5b237.png">

**Comment by shubham-singh-748** [comment]
Hey, can i take this issue?

**Comment by hhdqirui** [comment]
@shubham-singh-748 hi, thank you for being interested in this issue. However, this issue is currently being worked by another developer. You can look for another issue to work on. To check whether an issue is being worked on or not, you can check the comment history to see whether there is an open PR that fixes this issue.

**Comment by Novmbrain** [comment]
@moziliar Hello，could I take this issue？

**Comment by moziliar** [comment]
@Novmbrain sure! Go ahead.

**Comment by Shubhojeetban** [comment]
Is this assigned to anyone or can I just take it?

**Comment by jianhandev** [comment]
Hi @Olya-Grygorian this issue is already taken by @Shubhojeetban, you may try other issues tagged with `good first issue`.

**Comment by Emp923** [comment]
Hi Team! If this issue is still available I would like to work on it. Thanks!

**Comment by daongochieu2810** [comment]
@Shubhojeetban let us know if you have time to fix the conflicts in your PR, otherwise we will let others take this issue

**Comment by Shubhojeetban** [comment]
Hi, @daongochieu2810  sorry for the inactivity. Currently, I am busy with some stuff you can reassign.

**Comment by daongochieu2810** [comment]
@Emp923 you can take on the issue, thanks!
