### ISSUE TITLE
Instructor help page, sessions section: use existing components to build example boxes

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#11392]
Current: the following example boxes in the instructor help page (coincidentally or not, all are from Sessions section) are still hard-coding the contents instead of reusing existing components like how other example boxes do.

https://github.com/TEAMMATES/teammates/blob/e9a14de53c18434435280426047e1c51a08f0005/src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html#L156-L169

https://github.com/TEAMMATES/teammates/blob/e9a14de53c18434435280426047e1c51a08f0005/src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html#L193-L218

https://github.com/TEAMMATES/teammates/blob/e9a14de53c18434435280426047e1c51a08f0005/src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html#L233-L255

https://github.com/TEAMMATES/teammates/blob/e9a14de53c18434435280426047e1c51a08f0005/src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html#L298-L362

https://github.com/TEAMMATES/teammates/blob/e9a14de53c18434435280426047e1c51a08f0005/src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html#L389-L409

Problem: It increases the risk of the displayed items being out-of-sync (if not already is).

Solution: Refactor the necessary components to be reusable and use them here.

**Comment by xinyee20** [comment]
Hi, can I try working on this?

**Comment by wkurniawan07** [comment]
@xinyee20 you're very welcome to
