### ISSUE TITLE
Submission status stays as pending for team submissions

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11402]
Reported by a student.
Scenario: All questions in the session are team submissions (i.e., any team member can submit on behalf of the team).
Problem: After a student submit on behalf of the team, the status is still shown as pending, even for the student who submitted.

![image](https://user-images.githubusercontent.com/1673303/131697671-7bc74bab-0e8f-44d6-a5ea-1e3b7397430f.png)

Expected: After one member submits, should show as 'submitted' for all team members

Note: this only applies to registered students as un-registered students can't see the submissions status.

**Comment by damithc** [comment]
This might affect submission reminders too. Other members should not receive reminders if one member has submitted already.

**Comment by shadowezz** [comment]
If there are multiple team questions and a team member only submits part of them, should the status be pending or submitted? If we were to be consistent with the behaviour for individual questions then it should be submitted but then this may cause some questions to be left unanswered.

If there are both team and individual questions, is it true that as long as the student has not answered any of the indiv questions then his/her status should be pending regardless of whether anyone has submitted the team portion?

**Comment by damithc** [comment]
@shadowezz 

>If there are multiple team questions and a team member only submits part of them, should the status be pending or submitted? If we were to be consistent with the behaviour for individual questions then it should be submitted but then this may cause some questions to be left unanswered.

Good point. Let's go with 'team questions are considered pending if none of the team questions are answered', similar to individual questions. Yes, it can leave some questions to go unanswered but that's unavoidable given some questions may be optional to answer anyway.

> If there are both team and individual questions, is it true that as long as the student has not answered any of the indiv questions then his/her status should be pending regardless of whether anyone has submitted the team portion?

Yes, I think so. How about the following?

* individual questions: _pending_ if the student has not answered any questions
* team questions: _pending_ if no team member has answered any of them

If a session has both types, it is considered pending if either type is pending (as per above definition)

**Comment by shadowezz** [comment]
> Yes, I think so. How about the following?
>
>- individual questions: pending if the student has not answered any questions
>
>- team questions: pending if no team member has answered any of them
>
>If a session has both types, it is considered pending if either type is pending (as per above definition) 

So if a session has both types and the user only submits the individual questions, then the status is still pending and the available action is still "Start submission"? Not sure if this will be misleading.

**Comment by damithc** [comment]
> So if a session has both types and the user only submits the individual questions, then the status is still pending and the available action is still "Start submission"? Not sure if this will be misleading.

Good point. I guess we can go with 'session is pending if _both_ types are pending' instead.

**Comment by shadowezz** [comment]
> Good point. I guess we can go with 'session is pending if both types are pending' instead.

Hmm this also runs into the problem where if my teammate submits the team questions then my status will magically change to submitted even though I have not answered the individual questions. Another option we can consider is if a session has both types, then we only look at the individual questions to determine the status.

**Comment by damithc** [comment]
> Hmm this also runs into the problem where if my teammate submits the team questions then my status will magically change to submitted even though I have not answered the individual questions. 

Indeed. What was I thinking ;-p

>Another option we can consider is if a session has both types, then we only look at the individual questions to determine the status.

Yes, that sounds more reasonable.
