### ISSUE TITLE
Help Request: [Dev Server stuck on 85% with 403 error]

### ISSUE THREAD

**Issue by nirikawa** [TEAMMATES/teammates#11404]
- **Commit SHA:** c138e14e197bc3e138811b9634e90a74aac27aa2
- **Operating System:** Windows 10
- **JDK Version:** 11.0.12
- **Node.js Version:** 14.16.1
- **Chrome Version (if applicable):** 93.0.4577.63

**What I was trying to do / What I need help with**
I am trying to get the dev server running so I can run the E2E tests, but I am having trouble.  It stays at 85% EXECUTING forever.
![image](https://user-images.githubusercontent.com/17558539/132073165-1aca270f-648b-49cc-9bb1-7dfadcc4e4be.png)
![image](https://user-images.githubusercontent.com/17558539/132073359-e034a49c-66fe-404e-8065-aecc1d5a7e35.png)

**Attempts to resolve the problem**
I used the normal datastore method which gave the OK when navigating to the port. That resulted in the same thing. Then I tried using the gcloud SDK and got the OK, but still same 85% result.  Then finally I installed Docker for Windows and set that up with an OK for both the datastore and  text search, but I still had the same result of 403 error and 85%.

Any clue on how to get this working? Please and thank you.

**Comment by t-cheepeng** [comment]
@nirikawa If you are running `serverRun`, the dev server should run forever until you stop it. Try to access it using the front end: https://github.com/TEAMMATES/teammates/blob/master/docs/development.md

**Comment by nirikawa** [comment]
> @nirikawa If you are running `serverRun`, the dev server should run forever until you stop it. Try to access it using the front end: https://github.com/TEAMMATES/teammates/blob/master/docs/development.md

Yes the backend does seem to be functional through using the front end, but almost all of the E2E tests fail. I assumed this was due to this problem because in the instructions to set up the back end, it says "To start the server in the background, run the following command and wait until the task exits with a BUILD SUCCESSFUL," so is the stuck at 85% working as intended?

**Comment by RenChauncy** [comment]
Hello, ，mine too.  How did you solve it？

**Comment by RenChauncy** [comment]
> @nirikawa If you are running `serverRun`, the dev server should run forever until you stop it. Try to access it using the front end: https://github.com/TEAMMATES/teammates/blob/master/docs/development.md

Hello, When I access it using the front end, it shows the following:
![微信图片_20211101220237](https://user-images.githubusercontent.com/32806733/139684119-83c10ee4-3a18-4b6a-be74-33cf02cc1189.png)
What should I do? very thankful

**Comment by t-cheepeng** [comment]
@RenChauncy That is intended behaviour. Please see discussion above

**Comment by hanzili** [comment]
> @nirikawa If you are running `serverRun`, the dev server should run forever until you stop it. Try to access it using the front end: https://github.com/TEAMMATES/teammates/blob/master/docs/development.md
Hello, I am having the same issue here, May I ask what it means to access the back end using the front end?
Thank you.
