### ISSUE TITLE
Instructor moderating responses: open in a new tab

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11408]
Scenario:
An instructor is viewing results of a session and clicks on the 'Moderate responses' button. e.g.,
![image](https://user-images.githubusercontent.com/1673303/132117249-6be03e1b-b03c-459e-b00c-d8c5da3d68dd.png)

Current: The submission page opens in the current tab
Suggest: Open it in a new tab (?)
Reason: That page doesn't have a top menu bar. I think it's meant to open as a separate tab. While the user can always go back by pressing the back button, the result page takes time to load and requires multiple clicks to get to the exact view the user desires. It can be annoying if the user loses the results view unintentionally and have to do extra work to get back to where she was before.

**Comment by arsatis** [comment]
I would like to work on this issue!

**Comment by damithc** [comment]
> I would like to work on this issue!

@arsatis Go ahead.
