### ISSUE TITLE
'copy from previous feedback sessions' copy an empty session

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11412]
v8.1.1
Reported by a user.

Steps:
1. Go to instructor home page
2. Go to 'add' sessions option of a course
   ![image](https://user-images.githubusercontent.com/1673303/132285816-10f926f8-beab-4a52-b160-a8983cdfb810.png)

3. Try to copy a session using this button.
   ![image](https://user-images.githubusercontent.com/1673303/132285867-efe27ed8-8d50-4144-a67f-5030210dd603.png)

Problem: The session is copied but there are no questions.
![image](https://user-images.githubusercontent.com/1673303/132285952-b65b2c83-65bd-4990-9fbd-bce2c761cf2a.png)

But the 'copy session' feature in the home page works as expected. We can ask users to copy sessions that way as a workaround for the time being.

![image](https://user-images.githubusercontent.com/1673303/132286073-fffd4045-1c67-411f-a745-e2b4112eb84e.png)

It's good if we can fix this quickly and release a hot patch as this affects current users.

**Comment by xinyee20** [comment]
Hi, I tried reproducing the above using the sessions available in `http://localhost:4200/web/instructor/home` and there are questions generated in all my attempts so I'm slightly confused 
![#11412](https://user-images.githubusercontent.com/63994179/132377209-be8b6fbd-321f-4c0b-b504-4fc7968a5343.gif)

**Comment by wkurniawan07** [comment]
@damithc this problem is not well-defined. Are the sessions copied in the first attempt (from sessions page) and the second attempt (from home page) the same session?

**Comment by damithc** [comment]
> @damithc this problem is not well-defined. Are the sessions copied in the first attempt (from sessions page) and the second attempt (from home page) the same session?

Yes, I tried this for the same session (using my own live data) -- one method of copying works but not the other.

**Comment by damithc** [comment]
Update: The feature in concern (i.e., 'copy from previous feedback sessions') also works if copying a session within the _same_ course, but fails to copy questions when copying over a session from a different course.

**Comment by damithc** [comment]
> Update: The feature in concern (i.e., 'copy from previous feedback sessions') also works if copying a session within the _same_ course, but fails to copy questions when copying over a session from a different course.

@xinyee20 this is probably why you couldn't reproduce the error. Can you try copying a session from a different course?

**Comment by xinyee20** [comment]
ah yes, I manage to face the same issue of the questions missing when I try to copy a session from a different course, let me try and see if I can fix it.

> > Update: The feature in concern (i.e., 'copy from previous feedback sessions') also works if copying a session within the _same_ course, but fails to copy questions when copying over a session from a different course.
> 
> @xinyee20 this is probably why you couldn't reproduce the error. Can you try copying a session from a different course?

**Comment by damithc** [comment]
> ah yes, I manage to face the same issue of the questions missing when I try to copy a session from a different course, let me try and see if I can fix it. (If someone else knows how to fix it fast, feel free to fix it)

Thanks for confirming @xinyee20
