### ISSUE TITLE
Remove student last name field

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#11416]
https://github.com/TEAMMATES/teammates/blob/4054fef43227e005ae673a3e0e43b4aae2fd358a/src/main/java/teammates/storage/entity/CourseStudent.java#L133-L157

The "last name" feature has no visible usage in a long time and is not well-documented. One could even argue that they're not well-designed (in terms of usability).

**Comment by wkurniawan07** [comment]
@damithc do you still want to display the last name in the downloaded CSVs (student list, feedback responses), for whatever reason?

For me I don't see the value add because if the last name is always hard-coded as the last word of the name, it's no longer accurate for all names in the world.

**Comment by damithc** [comment]
@wkurniawan07 we can remove it.
