### ISSUE TITLE
Errors faced when trying to run http://localhost:4200/

### ISSUE THREAD

**Issue by xinyee20** [TEAMMATES/teammates#11419]
Seeking advice on what I should do to get localhost:4200 running again, should I add in Institute to Courses? Am I allowed to alter the types? Is there any other way around? Is anyone else facing the same issue?

**What I was trying to do / What I need help with**
On masters branch, with no edits done, I ran `npm run start` and face the errors shown below:

![image](https://user-images.githubusercontent.com/63994179/133086700-e3b870b8-c426-4197-843f-12306e0d7153.png)

Went into the files to take a look and realise that institute is used in a few Course object but it is not found in Course object in types/api-output.ts as shown by the images below:

<img width="470" src="https://user-images.githubusercontent.com/63994179/133086805-676458f0-8bf1-450f-91a6-76816ce2a364.png">

<img width="300" src="https://user-images.githubusercontent.com/63994179/133086881-0024d55e-6b5a-4a38-933d-e9ae45387ce9.png">

<img width="350" src="https://user-images.githubusercontent.com/63994179/133086933-6a25ec57-5970-4b9d-926d-1c68476b1b3a.png">

**Comment by jianhandev** [comment]
Hi @xinyee20 the `Course` object is recently changed to include the `institute` field, you can find more information here (https://github.com/TEAMMATES/teammates/pull/11363). I believe to fix those errors you should update your local master branch with these latest changes first, and then run `./gradlew generateTypes` once again.

**Comment by xinyee20** [comment]
Ahh I see, thank you very much for the help! :smile:

> Hi @xinyee20 the `Course` object is recently changed to include the `institute` field, you can find more information here (#11363). I believe to fix those errors you should update your local master branch with these latest changes first, and then run `./gradlew generateTypes` once again.
