### ISSUE TITLE
Admin -> manage accounts: HTTP parameter is null

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11432]
v8.2.0 production version

Steps:
1. Login as admin
2. Search for an instructor
3. Click on 'Manage account' in one of the instructors
   ![image](https://user-images.githubusercontent.com/1673303/135020839-cf1b3cd1-150d-48e4-9409-6ba3d1f218ee.png)

Problem:
![image](https://user-images.githubusercontent.com/1673303/135020902-470fcf6b-63eb-4325-b1a3-c954169eafc0.png)

**Comment by jianhandev** [comment]
Seems like this problem occurs when the instructor's google ID is reset.

**Comment by damithc** [comment]
> Seems like this problem occurs when the instructor's google ID is reset.

@jianhandev Oh, you mean if the Google ID was changed using the SingleAccountGoogleIdMigrationScript?

**Comment by wkurniawan07** [comment]
@damithc the instructor is unregistered. Without an existing account, "Manage account" loses its meaning entirely.

**Comment by damithc** [comment]
> @damithc the instructor is unregistered. Without an existing account, "Manage account" loses its meaning entirely.

Ah I see. Makes sense. Can we tweak the feature to let the admin remove the account of an unregistered instructor? This situation arose specifically from such a case: a user wrote back asking us to remove her from TEAMMATES after realizing she needs to use a Google account to login.

**Comment by wkurniawan07** [comment]
> Can we tweak the feature to let the admin remove the account of an unregistered instructor

There is a terminology mismatch here. "Account" is always a Google account. If you're looking for removing unregistered student/instructor (we cannot say "account"), it is a feature that does not exist, but cannot and should not be mixed up with the existing "account management".

**Comment by damithc** [comment]
> There is a terminology mismatch here. "Account" is always a Google account. If you're looking for removing unregistered student/instructor (we cannot say "account"), it is a feature that does not exist, but cannot and should not be mixed up with the existing "account management".

Sure, we can use a different term for that. e.g., a different button to remove such unregistered instructors. Let me create a separate issue for that.
