### ISSUE TITLE
Admin: Give a way to remove unregistered instructors and their data

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11433]
Suggestion: Give a way to remove unregistered instructors.
Reason: Some people can request for a TEAMMATES account and change their mind after receiving the join link. We want to be able to remove such people from the system entirely (i.e., any data entities created for them should be removed).

**Comment by daongochieu2810** [comment]
@damithc Should we give the link sender this feature, or just the admin?

**Comment by damithc** [comment]
> @damithc Should we give the link sender this feature, or just the admin?

I think it's enough to give this feature to the admin, for now.

**Comment by daongochieu2810** [comment]
![Screenshot from 2021-10-05 20-34-59](https://user-images.githubusercontent.com/53283766/136024532-89a1105a-fd1b-4b65-8613-4c405bec82f3.png)
Can we place the UI in the homepage like this

**Comment by damithc** [comment]
@daongochieu2810 this is more for specific cases (if a person requests their data to be deleted). So, no need to list all. Perhaps add a button to search results, given searching for the instructor is likely to be the step that comes just before?

![image](https://user-images.githubusercontent.com/1673303/136028897-464ba644-0416-4e1e-b624-4f9fbaee98d2.png)

**Comment by daongochieu2810** [comment]
@jianhandev I agree with the suggestion

**Comment by damithc** [comment]
> I imagine something like this:
> <img alt="Screenshot 2021-10-05 at 11 13 12 PM" width="1224" src="https://user-images.githubusercontent.com/59337195/136053378-fd3d760c-8a1a-470b-a236-ac8b51966a54.png">
> `Manage this account` button will be hidden since the instructor has yet to register and so the account does not exist yet, and perhaps a confirmation should pop up to confirm the deletion.

Yup that could work. Might need it for the student results too, as we also create a demo student instance using the new instructor's email address (unless we delay the demo course creation until the instructor has registered -- I remember there was some discussion about moving in that direction)

**Comment by daongochieu2810** [comment]
@damithc I think we need to create another issue for removing students, and discuss there

**Comment by damithc** [comment]
> There's something missing here. Is this feature only for unregistered instructors who requested account, or any unregistered instructor?

I think both are possible.
1. X asks for an account, changes mind later, and asks to be removed.
2. Y is added to a course by someone and wants to be removed.

However, we already have two ways to handle the second case:
1. Ask the course owner to remove the instructor
2. Masquerade as the course owner to remove the instructor

So, we can focus on the first case only.

**Comment by samuelfangjw** [comment]
We can continue working on this now that #11396 and #11560 have been merged. 

Fixing this should only involve:
1. Adding a `deleteAccountRequest` function in `account.service.ts`.  This function should call the delete account request endpoint.
2. Adding a button to delete an account request in the admin search page (there is a new account request section), handling any errors that might be thrown.
3. Updating frontend and e2e tests.

@tjtanjin, would you like to continue with this? Else I'll be happy to happy to finish this up.

**Comment by tjtanjin** [comment]
Hey @samuelfangjw, apologies for the slow follow-up. The earliest I can work on this issue would be during the mid-recess week though I noticed you have opened a draft PR. If you're able to spare the time to finish the PR within the next couple of days then please go ahead and I'd greatly appreciate it. Otherwise I'd be happy to finish up the issue during the recess week as well, thanks!
