### ISSUE TITLE
Help Request: E2E test issues

### ISSUE THREAD

**Issue by xinyee20** [TEAMMATES/teammates#11457]
**What I was trying to do / What I need help with**

I refactored some components in PR #11423 to address #11392. Some of the e2e tests failed after the refactoring. I tried downloading the chromedriver to run the e2e test locally on chrome, I realise that the number of test cases that failed does not tally and some that failed is different from the tests that failed in github (e2eTest(Firefox)). Quite a few of the test cases that failed when run locally does not seem related to the code that I have touched to refactor the components within so I am not sure what to touch and whether I should touch the pageObjects relevant to those test classes. Anyone with similar experience dealing with such e2eTests problems after changing some UI files knows how to handle such problems / has any advice? 

Below are some of the test failures from the results of the e2eTesting:

Test class: teammates.e2e.cases.InstructorHomePageE2ETest.baseClassSetUp():
![image](https://user-images.githubusercontent.com/63994179/138603263-02bd9dc3-da73-4971-9ef8-8491dac94be1.png)

testAll
Test class: teammates.e2e.cases.AdminHomePageE2ETest
![image](https://user-images.githubusercontent.com/63994179/138603286-861d8438-3fa2-46e5-99b5-e4a514eb8932.png)

testRgqView
Test class: teammates.e2e.cases.InstructorFeedbackReportPageE2ETest
![image](https://user-images.githubusercontent.com/63994179/138603361-1c753398-e990-4786-b925-46fb2d0a21a7.png)

**Comment by xinyee20** [comment]
Thanks for the advice! I ran the lastest master branch locally it couldn't pass all the e2eTests so i think the problem is partially due to my set up/environment problem so I am referring to the github tests errors to debug. I did tracing and found some component refactoring issues that I manage to fix and reduce the number of test failures. I am left with 4 test failures relating to assertion failures and comparison failures shown below but I can't seem to find the root problem despite attempting to trace the code a few times. Any advice on what could be causing this type of failures/how I can debug these kind of cases? 

![image](https://user-images.githubusercontent.com/63994179/139532949-c486ee5e-5bb6-4964-b392-eeba93fcc354.png)
![image](https://user-images.githubusercontent.com/63994179/139532959-727cd359-8a53-482f-baf5-fe1d634f9af2.png)

**Comment by xinyee20** [comment]
Hi I realise that while updating my code, http://localhost:4200 gets updated but http://localhost:8080 is behaving very weirdly, not really updating properly and localhost:8080 is where the e2e tests are carried out. I am not sure what is going on, any ideas on how to get localhost:8080 to update properly?

**Comment by wkurniawan07** [comment]
The former is Angular dev server, the latter is backend server. If you wish the backend server to serve the built front-end files, you can refer to one of the items in the development guideline.

**Comment by xinyee20** [comment]
Ah yes, running 'npm run build' solves the server update issue, thank you
