### ISSUE TITLE
Unable to upload Profile Pictures on Local Machine

### ISSUE THREAD

**Issue by itishrishikesh** [TEAMMATES/teammates#11456]
- **Commit SHA:** 065c199f74db0de7281f02232df54bc34b417ac9
- **Operating System:** Windows 10
- **JDK Version:**  openjdk 11
- **Node.js Version:** v14.18.0
- **Chrome Version (if applicable):** 95.0.4638.54

**What I was trying to do / What I need help with:**

The student's profile picture could not be uploaded when I tried to reproduce #11147:

![image](https://user-images.githubusercontent.com/24785679/138598211-55546e97-d30f-4f8d-9f1c-d26b3bea3fb2.png)

**Attempts to resolve the problem**
I tried changing the below relative path into an absolute path and was able to upload profile pictures successfully with the LocalFileStorageService.java file found in the main/java/teammates/logic/core directory.:

`private static final String BASE_DIRECTORY = "../../filestorage-dev";`

to

`private static final String BASE_DIRECTORY = System.getProperty("user.dir") + "/filestorage-dev";`

**Comment by itishrishikesh** [comment]
Hi @ypinhsuan, sorry for the late response. I am getting errors while running `npm run lint` which is essential as per [this](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr) guide. Following are the errors:

```
npm run lint

> @ lint C:\Users\user1\IdeaProjects\teammates
> npm-run-all lint:* -c


> @ lint:ts C:\Users\user1\IdeaProjects\teammates
> ng lint --tslint-config static-analysis/teammates-tslint.yml

Linting "teammates"...
All files pass linting.

> @ lint:json C:\Users\user1\IdeaProjects\teammates
> jsonlint-cli ./*.json src/web/**/*.json src/main/resources/*.json src/test/resources/data/*.json


> @ lint:css C:\Users\user1\IdeaProjects\teammates
> stylelint "src/web/**/*.css" "src/web/**/*.scss" "src/web/**/*.html" --config static-analysis/teammates-stylelint.yml


src/web/dist/styles.a63a89b81280caa8c3c1.css
 1:4     ×  Expected single space before "{"                                     block-opening-brace-space-before
 1:5     ×  Expected no more than 1 declaration                                  declaration-block-single-line-max-declarations
 1:6     ×  Expected single space after "{" of a single-line block               block-opening-brace-space-after
 .
 .
 .
 1:3338  ×  Unexpected missing end-of-source newline                             no-missing-end-of-source-newline

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ lint:css: `stylelint "src/web/**/*.css" "src/web/**/*.scss" "src/web/**/*.html" --config static-analysis/teammates-stylelint.yml`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ lint:css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user1\AppData\Roaming\npm-cache\_logs\2021-10-31T08_07_09_612Z-debug.log

> @ lint:spaces C:\Users\user1\IdeaProjects\teammates
> lintspaces -n -t -d spaces -l 1 -. "src/main/**/*.html" "src/web/**/*.html" "src/**/*.xml" "src/**/*.json" "src/**/*.properties" "*.yml" "*.json" "*.gradle" "sta
tic-analysis/*.*ml" ".gitattributes"


File: C:\Users\user1\IdeaProjects\teammates\src\web\dist\ngsw.json
Line: 410 Expected a newline at the end of the file. [warning]

File: C:\Users\user1\IdeaProjects\teammates\angular.json
Line: 122 Expected a newline at the end of the file. [warning]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ lint:spaces: `lintspaces -n -t -d spaces -l 1 -. "src/main/**/*.html" "src/web/**/*.html" "src/**/*.xml" "src/**/*.json" "src/**/*.properties" "*.yml" "
*.json" "*.gradle" "static-analysis/*.*ml" ".gitattributes"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ lint:spaces script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user1\AppData\Roaming\npm-cache\_logs\2021-10-31T08_07_10_884Z-debug.log
ERROR: "lint:spaces" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ lint: `npm-run-all lint:* -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user1\AppData\Roaming\npm-cache\_logs\2021-10-31T08_07_10_917Z-debug.log
```
Do you have any idea why this might be happening?

**Comment by hhdqirui** [comment]
Hi @itishrishikesh , the errors seem to be irrelevant. Are you able to pass the GitHub Action npm lint checks when you submit the PR?

**Comment by itishrishikesh** [comment]
Hi @hhdqirui, I hadn't submitted the PR before, I just did and it seems that first-time contributors like me, need approval before checks are run from maintainers.

**Comment by foueds** [comment]
Hi @itishrishikesh, i'm new in the project and i want to reproduce this issue. thanks

**Comment by itishrishikesh** [comment]
Hi @foueds I'm new here too :)

You just need to upload profile picture from Student Profile page in your local environment, you should be getting the mentioned issue in your console where your server is running.

+ I'm not sure if it is only windows problem, but I was getting this windows.

**Comment by foueds** [comment]
hi @itishrishikesh, i'm working in mac os.
When i try to log as student with this email "test@example.com" i got this
<img width="834" alt="Capture d’écran 2021-11-30 à 14 38 59" src="https://user-images.githubusercontent.com/44832665/144057684-1549d945-b489-41f3-928d-17e19788d79f.png">

**Comment by itishrishikesh** [comment]
@foueds 

First you'll login to admin account, by going to `localhost/web/home/admin`,  you can use `app_admin@gmail.com` (It's default set in build.properties but you can have look in docs)

I think you need to _create_ (Idk if it's correct terminology here) some students by first creating an instructor and then enrolling the students, IG you'll need to look more into docs.

[https://github.com/TEAMMATES/teammates/blob/master/docs/development.md](reference doc I used)
