### ISSUE TITLE
Instructor viewing all records: No past records shown

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11468]
Reported by a user, reproduced myself.
Steps:

1. Login as instructor
2. Search for a student name
3. Click on the 'All records' button of a search result
4. Problem: No past records shown

![image](https://user-images.githubusercontent.com/1673303/141405094-dafe27f0-fe93-44c0-86f8-702a5a642f34.png)

**Comment by wkurniawan07** [comment]
Does this person have sufficient instructor to view responses?

**Comment by damithc** [comment]
> Does this person have sufficient permission to view responses?

Same problem happens for my own courses/students. So, can't be a permission problem.
