### ISSUE TITLE
Allow 'other teams/students in section' as an option in feedback paths

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11463]
Current:
![image](https://user-images.githubusercontent.com/1673303/139794111-236ec2fb-13f3-4cfb-9282-77ea96c794d2.png)

A user suggested that we add the options:
`other students in the same section`
`other teams in the same section`

Reason: if students are supposed to evaluate others in their own section only, it can be quite inconvenient to choose the correct students when the class is large e.g., the user who suggested this has 800+ students and 170 teams in the course.

I think the feature is useful to have but not sure how much effort the implementation will take.

**Comment by madanalogy** [comment]
@tjtanjin it just occurred to me that your PR https://github.com/TEAMMATES/teammates/pull/11469 doesn't have any tests. We recommend including tests for changes or addition of functional code. Could I trouble you to write some tests in a new PR please. You can tag the PR to this issue

**Comment by wkurniawan07** [comment]
Closing as the feature is done. Adding the missing tests can always be done with reference to another issue (or even this issue, even if already closed).
