### ISSUE TITLE
Add a sub-menu for the 'Remind' feature

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11466]
It seems some users are hesitant to click the 'Remind' button because they think it will email everyone.
![image](https://user-images.githubusercontent.com/1673303/141341762-e1d283f5-2de0-42ba-a7fc-8174b9842068.png)

Perhaps we can give two fake options as a drop-down? i.e., `remind all non-submitters`, `select non-submitters to remind`

Both can pop-up the same modal but the first one can auto-select non-submitters.

**Comment by SavidBasnyat** [comment]
Hi, I would like to work on this issue. Could you assign it to me? Thank you.

**Comment by halfwhole** [comment]
Hi @SavidBasnyat, thanks for your interest! We generally don't assign issues in this project, but please feel free to take this issue and submit a PR whenever you're ready too.

**Comment by NicolasCwy** [comment]
@SavidBasnyat are you still working on this issue? Would like to give it a shot

**Comment by SavidBasnyat** [comment]
@NicolasCwy While I have started working on it, I have not been able to make enough progress. So feel free to give it a shot!

**Comment by NicolasCwy** [comment]
@damithc To clarify would the option "remind all non-submitters" select both students and instructors who have not submitted. Also would it be more appropriate to name the second option "select non-submitters to remind" as there could be instructors to remind as well.

**Comment by damithc** [comment]
> @damithc To clarify would the option "remind all non-submitters" select both students and instructors who have not submitted. Also would it be more appropriate to name the second option "select non-submitters to remind" as there could be instructors to remind as well.

@NicolasCwy 
I guess OK to select both students and instructors
Yes, that's a better name for the second option. Good catch.

**Comment by NicolasCwy** [comment]
When "select non-submitters to remind" is clicked, should any of the options in the model be selected? I would think none of the options should be selected, but from the current implementation of the modal, this box will be checked when all instructors have submitted, see picture above. If this is considered a bug, should this be fixed in this issue?
![image](https://user-images.githubusercontent.com/25302138/146664867-b5abba55-9898-4936-86f9-c60980012f46.png)

**Comment by damithc** [comment]
> When "select non-submitters to remind" is clicked, should any of the options in the model be selected? I would think none of the options should be selected, but from the current implementation of the modal, "Select all instructors not yet submitted" will be checked when all instructors have submitted, see picture above. If this is considered a bug, should this be fixed in this issue?

Yes, seems like a bug. Can fix.

**Comment by NicolasCwy** [comment]
When a user clicks on the "select non-submitters to remind" button, should the "Select all students not yet submitted" be selected if there are no students who have not submitted? The current implementation on master is the former. Intuitively I would think that it should remain unselected until the user has performed some action, so there should be some state logic, but would be a little more complicated and purely for cosmetic purposes.

![image](https://user-images.githubusercontent.com/25302138/148948244-75686f5f-5b28-48da-b831-bb659814c8b9.png)
