### ISSUE TITLE
Include a list of non-submitters in the downloaded results

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11478]
When an instructor views results, TEAMMATES shows a list of non-submitters at the bottom of the page.
![image](https://user-images.githubusercontent.com/1673303/143224056-98a94cb7-00c3-487b-b8f0-48fcd696a626.png)

But that list is not included in the csv file, if the instructor downloaded the results.

Suggestion: include the non-submitters list (name, team, email) in the the downloaded spreadsheet as well.

**Comment by Attyuttam** [comment]
Hi, I am new to this repo and this issue seems to be pretty interesting. Can someone please direct me as to which files/folders needs to be looked into to work on this ?

**Comment by t-cheepeng** [comment]
@Attyuttam Hi, thanks for indicating interest. Seems like it is the first time you are contributing to this repository. Try to look for a `good first issue` to work on

**Comment by arsatis** [comment]
May I try to work on this issue?

**Comment by jianhandev** [comment]
@arsatis yes please go ahead :)

**Comment by shadowezz** [comment]
I have made a fix for this issue. Not sure if anyone is currently working on it.

**Comment by moziliar** [comment]
Hi @arsatis, any updates from you?

@shadowezz it seems that there was an interested contributor a while back. Let's wait for a while to see if there's any update?

**Comment by shadowezz** [comment]
Sure, no worries!

**Comment by arsatis** [comment]
Hi @moziliar sorry for the delayed reply, I was working on the issue a while back but had some other matters to attend to so I wasn’t able to complete my commit.

Its fine to merge @shadowezz’s commit, I’ll help out with other issues when I’m available 👌

**Comment by moziliar** [comment]
@arsatis thank's for the update. @shadowezz we will proceed with your PR.
