### ISSUE TITLE
Unexpected behavior when selecting multiple feedback question recipients

### ISSUE THREAD

**Issue by tjtanjin** [TEAMMATES/teammates#11474]
Reproduced on local dev environment on commit `a5fe4b0`

**Steps to reproduce**
1) Go to instructor sessions page
2) Edit a question and change recipient to other students in the course
3) Try to set the maximum number of students feedback should be given to
4) Save the changes and refresh the page - notice changes are not saved

More elaborate examples shown below:

Question 1 is being used for testing here, I tried changing the maximum number of students but even though the value supposedly saves, a refresh shows otherwise.

https://user-images.githubusercontent.com/43908963/141615322-94e251f6-2e69-4a7b-beb3-289ec2a1d533.mp4

Question 2 is being used for testing here, this time, I cannot even modify the maximum number of students. I can however, still save it but refreshing reverts the choice to unlimited again.

https://user-images.githubusercontent.com/43908963/141615403-7be5cd80-477b-4751-9153-b6166bdd433f.mp4

**Additional info**
Strangely, I cannot spot any noticeable difference between the 2 question types. In fact, question 1 was initially having the exact same issue as question 2 and simply suddenly changed its behaviour as I continued testing. I am unable to specifically reproduce the two differing behaviours though they are likely to have the same source of bug.

**Comment by damithc** [comment]
Looks like a serious bug. Would like to fix before the next release, plus this is holding us back from doing a release. Alternatively, we can revert the problematic PR for now, if that can be done cleanly.

**Comment by wkurniawan07** [comment]
@tjtanjin I got a good idea as to why it happened. Can you help to verify that the changes introduced in this branch <https://github.com/TEAMMATES/teammates/tree/11474-feedback-path-event-bubbleup-error> fixed the problem?

**Comment by tjtanjin** [comment]
> @tjtanjin I got a good idea as to why it happened. Can you help to verify that the changes introduced in this branch https://github.com/TEAMMATES/teammates/tree/11474-feedback-path-event-bubbleup-error fixed the problem?

Hello! I have tested and the changes introduced in this branch fixes the problem!
