### ISSUE TITLE
Unable to download results of a session

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11470]
Reported by a user

Class size:
![image](https://user-images.githubusercontent.com/1673303/141756012-0acf3f0b-a4fa-4b42-8d3a-9d0bba9ca85d.png)

The user is unable to download the results for the following question:

![image](https://user-images.githubusercontent.com/1673303/141756320-bd0ec54b-6a5b-46af-97fe-4a1cdc37242b.png)

![image](https://user-images.githubusercontent.com/1673303/141756258-afba8a2a-5123-4ad6-8cae-4fc3fe4fa9f3.png)

I tried, but couldn't download it myself.

The log says `OutOfMemoryError caught by WebApiServlet: Java heap space`

A bit urgent because the user needs a way to access the responses.

**Comment by wkurniawan07** [comment]
The error is unfortunately what it says. Does using an F4 instance help?

**Comment by damithc** [comment]
> The error is unfortunately what it says. Does using an F4 instance help?

I'm trying it now. Will keep you posted.

**Comment by damithc** [comment]
Managed to download with a F4 instance. The file has 138K rows, and is 10MB. In this specific case, most rows are useless as students give responses to only 7 teams but there are 169 teams i.e., 7 rows with data and 162 with 'no response'. Perhaps that's a place to optimize for memory?

**Comment by wkurniawan07** [comment]
We (me and @xpdavid) actually anticipated this kind of problem long ago. It's the reason why this code exists:
https://github.com/TEAMMATES/teammates/blob/a5fe4b04a773da28b6c9cd54eb07625ad2217ecd/src/main/java/teammates/common/datatransfer/questions/FeedbackQuestionDetails.java#L93-L99
Translation: if the recipient type is `STUDENTS`, do not generate missing responses. Looks like we need to do the same for `TEAMS`.

**Comment by damithc** [comment]
> We (me and @xpdavid) actually anticipated this kind of problem long ago. It's the reason why this code exists:

Nice. Should be a quick fix in that case.

**Comment by damithc** [comment]
The results can now be downloaded for the session in question. Thanks @wkurniawan07 and @tjtanjin for the fix.
