### ISSUE TITLE
The Development Guidelines don't explain how to create an account

### ISSUE THREAD

**Issue by Chris-Denby** [TEAMMATES/teammates#11475]
Issue title: Help Request: The Development Guidelines don't explain how to create an account

**What I was trying to do / What I need help with**
Hi, I was following the Development Guidelines document to setup my development environment so I can have a shot at contributing. Everything starts as expected, however after running the interface from http://localhost:4200/web/front/home I am unsure how to create an administrator account to log in. The Development Guidelines detail how to sign in as an administrator, but it assumes an account has already been created.

So, a) this is perhaps something that could be added to the documentation and b), can you please tell me how I setup an account?

**Attempts to resolve the problem**
Checked through documentation for an answer, none found.

Cheers,

**Comment by jianhandev** [comment]
Hi @Chris-Denby thanks for your interest in this project, for logging in you should refer to [this part](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#logging-in-to-a-teammates-instance) of the development docs, also remember to read the comments in the `build.properties` file. Let us know if you have any more questions!

**Comment by simonteozw** [comment]
Hi, I have checked my repository and I do not have my own build.properties file, do I need to create one on my own?

**Comment by jianhandev** [comment]
> Hi, I have checked my repository and I do not have my own build.properties file, do I need to create one on my own?

Hi @simonteozw the answer is in [this part](https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md#step-3-set-up-project-specific-settings-and-dependencies) of the docs :)
