### ISSUE TITLE
Numerical scale questions replacing user ratings with random values 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11487]
Received from a user:

>I've started to notice that when I type in a 5 or whatever number into the questions to rank my teammates that it would actually change the ranking from a 5 or a random number. Most of the time it changes to a 4 but I have found it has changed to a 3 on occasions. I don't believe it has anything to do with the specific computer I am using or any error on my end so I wanted to let you know so you are aware and maybe others have had the same issue.

Although the student says 'ranking' it is actually a numerical scale question.

![image](https://user-images.githubusercontent.com/1673303/144696613-d886644b-af5d-4c47-b19b-b7f215695185.png)

![image](https://user-images.githubusercontent.com/1673303/144696610-2f42ac12-5bd7-4951-b09d-629bdbc7daff.png)

The worrying thing is, another instructor from a different university reported that her students are complaining about this same thing.

The question in concern:
![image](https://user-images.githubusercontent.com/1673303/144696640-5577adc3-5c3c-471b-b8f0-0f423c015acb.png)

In both cases, the session has many similar questions (10-24) but the team size is normal (4-8).

Apparently, they can get TEAMMATES to save the correct values after a few tries.

I couldn't reproduce it at my end though. I'm waiting for more info. Will post here as I receive them.

**Comment by damithc** [comment]
A student said the following:
>when I press a number in the box and then click to the next if I scroll up it often magically changes. I'm using chrome. My keys are working just fine. It has happened in many of the teammate ranting things so it's definitely a recurring issue for me.

From what they describe, one possibility is the action of scrolling (e.g., turning the scroll wheel of the mouse or dragging fingers over the trackpad) is being intercepted by the input box. If the student tries to scroll the page while the focus is in the input box, she might end up scrolling the input box instead (because it is also a wheel of numbers that you can scroll up or down). However, I can't reproduce such a scrolling behavior on my Windows/Chrome set up. Perhaps it affects a certain device/OS only?

**Comment by tjtanjin** [comment]
> A student said the following:
> 
> > when I press a number in the box and then click to the next if I scroll up it often magically changes. I'm using chrome. My keys are working just fine. It has happened in many of the teammate ranting things so it's definitely a recurring issue for me.
> 
> From what they describe, one possibility is the action of scrolling (e.g., turning the scroll wheel of the mouse or dragging fingers over the trackpad) is being intercepted by the input box. If the student tries to scroll the page while the focus is in the input box, she might end up scrolling the input box instead (because it is also a wheel of numbers that you can scroll up or down). However, I can't reproduce such a scrolling behavior on my Windows/Chrome set up. Perhaps it affects a certain device/OS only?

If it helps, I am also unable to reproduce this on my mac os.

**Comment by damithc** [comment]
> If it helps, I am also unable to reproduce this on my mac os.

Thx for checking @tjtanjin There's something going on (given we received reports from two different sessions), but not sure what.

**Comment by jianhandev** [comment]
I tried on safari, chrome and firefox - unable to reproduce this bug too 🤔.

**Comment by fsgmhoward** [comment]
I can reproduce the issue that scrolling event being captured.

Environment: Firefox 91.5.0esr + Windows

How to reproduce: The textbox has to be clicked (so with blue highlighted border) + mouse must be within the input box, then mouse wheel scroll will trigger the change in numbers

So if the student click the textbox and enter the number, then immediately use the mouse to scroll down (without first moving the mouse out of the text box), it will trigger the change.

These steps cannot reproduce it:
- Same Firefox + windows, but with 2-finger scrolling on tracking pad of the laptop
- Edge + windows, mouse wheel scrolls will not change the value

**Comment by moziliar** [comment]
@fsgmhoward It looks plausible a finding. Do you have any suggestions on how it can be fixed?

**Comment by fsgmhoward** [comment]
@moziliar I am unsure whether the mouse wheel scroll is the cause for what these students reported. Disabling the default action for mouse scroll event should fix this. I will try to take a look at it.

**Comment by moziliar** [comment]
@fsgmhoward ok. Thanks for the investigation effort. We can try with this fix and reopen the issue if the issue is still recurring.
