### ISSUE TITLE
Support configuring separate front-end URL for E2E testing

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#11492]
Right now, E2E tests assume a single URL for testing, i.e. the back-end and the front-end hosted concurrently.

While it is a reasonable assumption based on the production system's architecture and should remain that way in CI, it is not convenient for development as a simple front-end change necessitates full rebuilt of the front-end, taking (wasting) a few mins time.

Suggestion: make the front-end URL configurable separately for E2E testing. For CI, the value should be the same as the back-end URL.

**Comment by itishrishikesh** [comment]
Hi @wkurniawan07 :
 
I observed a set of constants are defined in `static class WebPageURIs` in `Const.java` for accessing frontend pages, these constants are referenced in all E2E tests to create/access frontend URL - mostly using `createUrl`.

If we add and read frontend, backend URL separately (from `test.properties`) and change conditions wherever `WebPageURIs` is present in E2E tests to refer to frontend URL - will it be an appropriate solution for the current issue?

Please let me know if this solution makes sense, I will continue on this accordingly.

Thanks!

**Comment by wkurniawan07** [comment]
That's not at all necessary. If you can take some time to understand how the E2E tests work, it should be very clear which operations should use frontend URL and backend URL respectively.
