### ISSUE TITLE
Support custom value for base system URL

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#11490]
Currently, the code assumes that the system is accessible at `https://<project-id>.appspot.com`. We need to modify the code such that the back-end can accept a customizable value for the base system URL.

Note that this is NOT an infrastructure work to map a custom domain name to the App Engine instance. This is just to support using the correct URL in emails and for redirects, and handle CORS if necessary.

**Comment by fsgmhoward** [comment]
I would like to take this issue and try to implement this. Is anyone else currently working on it?
