### ISSUE TITLE
Make 'Download proof of submission' button more prominent

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11494]
Current:
![image](https://user-images.githubusercontent.com/1673303/144964593-0d88b247-cc7f-43c2-9a17-3fc515bd61cb.png)

I suspect most users would click on the OK button without looking at the other button.

We can consider these tweaks:
1. Make the `Download ...` button green and move it to the right (as it is customary for the preferred option to be on the right)
2. Change color of the `OK` button to not green (e.g., use info/secondary colors)
3. Rename buttons as `Don't download proof-of-submission`, `Download proof-of-submission`

Other opinions welcome.

While we are at it, we can also bold (or highlight):
>You are **encouraged to download the proof-of-submission**, which will also contain your latest responses.

**Comment by shadowezz** [comment]
I can have a go at this
