### ISSUE TITLE
Logging into an instance development guidelines clarification 

### ISSUE THREAD

**Issue by egorovak** [TEAMMATES/teammates#11503]
Hi,

I have been working through [developer guidelines](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#logging-in-to-a-teammates-instance) to set up and run teammates' development environment and had some confusion when trying to log into an instance. Specifically, in the section "[Logging in to a TEAMMATES instance](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#as-administrator)" as administrator it says that I will be granted access if the account has admin permission as defined in build.properties. However, to be able to log in as an administrator with my username I had to run the datastore emulator, not just edit build.properties. It took my team of students and me some time to figure that out since it wasn't intuitive to us or explicitly mentioned in the guide.

Therefore, I wanted to suggest two small changes to the developer's guide, to make this a bit more clear to student developers like myself: 
1) Add a sentence about running the datastore emulator in the first bullet point of  "Logging in to a TEAMMATES instance" as administrator. 
2) Switch around sections about[ logging into an instance](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#logging-in-to-a-teammates-instance) and [running the datastore emulator](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#as-administrator) so that they appear in chronological order. 

Please let me know if I misunderstood something and thank you!

**Comment by wkurniawan07** [comment]
The action of logging in, in and of itself, doesn't require datastore/emulator. You probably see the errors/get redirected to home page because after logging in, there needs to be check whether an account is a student/instructor, and this check clearly needs a running DB instance.

**Comment by egorovak** [comment]
@wkurniawan07 Thank you for your response! Do you think it would be reasonable to add a remark about it still in the developer guidelines?
