### ISSUE TITLE
Outdated question in instructor help page

### ISSUE THREAD

**Issue by samuelfangjw** [TEAMMATES/teammates#11547]
This section of instructor help page seems to be outdated.

<img width="522" alt="Screen Shot 2022-01-31 at 11 52 09 PM" src="https://user-images.githubusercontent.com/60355570/151826646-2540a462-4a7f-44bc-a7f5-91f1dd97ec7c.png">

Looking at the students page, there doesn't seem to be a way to filter out students and the "Copy Emails" button doesn't seem to exist anywhere else in the repo.

<img width="1552" alt="Screen Shot 2022-01-31 at 11 56 59 PM" src="https://user-images.githubusercontent.com/60355570/151827534-9589dc5d-9fe8-48ed-9927-51b6e4c2e0c3.png">

**Possible Change**
If single student: 
Use search feature to find student or find student in students page.  

If multiple students:
Under the courses page, click on other actions ->  view. Click download student list, copy emails from there.

**Comment by wkurniawan07** [comment]
This question is really weirdly phrased. It is as if we're providing a built-in email function, which obviously isn't the case. That alone should make the existence of the question highly questionable.
If the question is to be kept, the first thing that should be changed is how the question itself is phrased.

**Comment by fsgmhoward** [comment]
I am not really sure the origin of this question but I guess it is put there because some instructor ask how to do it some times ago? I would say it is a valid concern for some instructors as they may want to use this similar to an LMS. We can still put some instructions for them to extract the email and put an emphasis there saying this feature is not provided by TEAMMATES.

**Comment by hoanglan21** [comment]
<img width="1440" alt="Screen Shot 2022-03-01 at 1 47 28 PM" src="https://user-images.githubusercontent.com/46897782/156230065-ca7bb312-2f92-4dbf-b88b-7af0e250b6f9.png">
my suggestion for this answer is 
1) if the teacher is looking for one specific student, they can go to Student page -> search -> copy the student's email from there
2) if the teacher is looking for a group of students, they can go to Courses -> click the Students button -> Click view/ edit -> Click Download student list and then copy the emails column from the CSV file
Let me know if this is a good answer to the questions and then I can make a PR from this one.

**Comment by fsgmhoward** [comment]
@hoanglan21 Hi, what you said has already been drafted as PR #11555 

The issue now is not how to phrase this answer. Instead, it is whether or not to preserve this question as commented by @wkurniawan07 .

**Comment by damithc** [comment]
I think we can get rid of this question. We used to have such a feature at some point but not any more.

**Comment by fsgmhoward** [comment]
@damithc Noted. I will update the PR accordingly then.

**Comment by wkurniawan07** [comment]
> We used to have such a feature at some point but not any more.

It is true that we used to have the feature described in (1)-(2), but judging by the fact that (3) is the so-called "way" to email the students, the question has been weirdly phrased from the very beginning. Of course, doesn't matter anymore if we're going to delete it.
