### ISSUE TITLE
Make maintainer logs interface scrollable only below the input section

### ISSUE THREAD

**Issue by moziliar** [TEAMMATES/teammates#11540]
**Description of feature/enhancement**
Box up the log output and make them scrollable, separated from the filter inputs.

**Justification**
Use case: maintainer reading the logs needs to scroll up after reading the logs data for some time to recall what are the filter inputs. A better UX can be that the filter input fields can be frozen on top, and let the logs part scrollable.

**Comment by samuelfangjw** [comment]
Hi, I would like to work on this.

**Comment by moziliar** [comment]
Thanks:) appreciate that!

**Comment by samuelfangjw** [comment]
@moziliar, would something like this work? Want to check if something simple would do the trick before I add more complexity.

https://user-images.githubusercontent.com/60355570/150677249-b299b5f8-7c69-4eb4-8a20-14df6da0b695.mov

I think the original idea works too (filter input frozen at top), but need to find some way to reduce the amount of space the filter input selection area takes up, since it currently takes up almost all the space on the page on a laptop sized screen leaving not much space to for the output logs.

**Comment by moziliar** [comment]
It is indeed what I thought of when I used this UI on my larger than normal monitor. It appears to me that the view will not have much benefit for a regular screen. Do you have any better that could make this work?

Here are some of my thoughts:
1. As the page is scrolled down, make it such that the filter input are listed in a horizontal list form (so that the maintainer still can refer to the input)
2. Like 1, except the list is on the left/right of the log entries
3. Slowly reduce the gap between the filter input components (the blue box) as the user scroll down, i.e. slowly compacting it to the top

I feel like it might be asking for too much, as many a time I literally just keyed in my input and I should know what I am looking for; however, after some uses of this UI I figured this might be a good addition when we are just investigating issue across action classes, periods, trace id, etc.

**Comment by samuelfangjw** [comment]
Was thinking maybe clicking the query button will collapse input area and display something similar to this (is this what your 1st bullet point refers to?). Ideally with advanced settings as well, but only if applicable so it doesn't become a mess. Then clicking on edit settings will bring you back to the top and expand the input area so you can issue another query. 

<img width="1552" alt="Screenshot 2022-01-23 at 9 03 31 PM" src="https://user-images.githubusercontent.com/60355570/150679778-d4f1f17b-46a9-44b6-96be-9e3cd15d3f14.png">

**Comment by damithc** [comment]
> Was thinking maybe clicking the query button will collapse input area and display something similar to this (is this what your 1st bullet point refers to?). Ideally with advanced settings as well, but only if applicable so it doesn't become a mess. Then clicking on edit settings will bring you back to the top and expand the input area so you can issue another query.

As maintainers are ourselves, it's OK if the UI/UX is not so refined, as long as it is 'good enough'. We can live with a few inconveniences for the time being :-)

**Comment by moziliar** [comment]
I guess the original change satisfies my use case. I'm good with it.

Perhaps the box can be bigger so that one still can have full screen view of the logs.

**Comment by samuelfangjw** [comment]
> I guess the original change satisfies my use case. I'm good with it.
> 
> Perhaps the box can be bigger so that one still can have full screen view of the logs.

Sorry missed this, will submit a PR shortly.
