### ISSUE TITLE
Infinite loading upon clearing text in a date picker

### ISSUE THREAD

**Issue by ziqing26** [TEAMMATES/teammates#11556]
**Environment**
Live server at `V8.6.0`

**Steps to reproduce**
1. Choose a feedback session to edit (go to Edit Feedback Session Page)
2. Delete the date for any date picker (for example, Submission opening time or Make session visible)
3. Click 'Save Changes" button.
![ezgif-2-a56aae2095](https://user-images.githubusercontent.com/69516975/152679421-9ef34413-1499-4a4e-b778-1ddb995e884c.gif)

**Expected behaviour**
Report an error for invalid date time and stop loading to save data.

**Actual behaviour**
No error is reported and the loading sign is shown to prevent further editing (does not stop trying to save).

**Additional info**
Might need to catch this error before it attempts to save the data in the front end.

**Comment by FergusMok** [comment]
Sounds good, I'll try to fix this issue
