### ISSUE TITLE
Student viewing results: incorrect state shown while loading

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11588]
Steps:
1. Login as a student
2. View results of a session
3. Problem: This message is shown for a brief instance while results are still loading
![image](https://user-images.githubusercontent.com/1673303/155001281-41cb3b63-b02e-4ac0-98d9-296c6098f2a0.png)

Session detail also appear blank but that is less of a problem compared to the above.

**Comment by moziliar** [comment]
@fsgmhoward would you wanna give it a try? Seems like the same issue you solved recently.

**Comment by fsgmhoward** [comment]
@moziliar Sure. I will take a look at it later.
