### ISSUE TITLE
Student home page shows incorrect state while loading

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11587]
![image](https://user-images.githubusercontent.com/1673303/155000333-96882d7f-e7b5-48a9-92e4-30c43324b80e.png)

This appears momentarily before the table is populated with the session data

**Comment by samuelfangjw** [comment]
Possible duplicate of #11551, which should be fixed in the v8.8.0

**Comment by damithc** [comment]
> Possible duplicate of #11551, which should be fixed in the v8.8.0

Thanks for checking @samuelfangjw 
Is this fixed as well? it's similar case but for students viewing results of a session

![image](https://user-images.githubusercontent.com/1673303/155001281-41cb3b63-b02e-4ac0-98d9-296c6098f2a0.png)

**Comment by samuelfangjw** [comment]
> Thanks for checking @samuelfangjw Is this fixed as well? it's similar case but for students viewing results of a session

I don't believe so. Able to replicate on current master branch, and I don't remember seeing an issue or PR for this.

**Comment by damithc** [comment]
> I don't believe so. Able to replicate on current master branch, and I don't remember seeing an issue or PR for this.

Got it. Will create a separate issue.
