### ISSUE TITLE
Wrong argument order in populateFieldsToGenerateInQuestion causes NPE

### ISSUE THREAD

**Issue by leddy231** [TEAMMATES/teammates#11592]
The arguments here
https://github.com/TEAMMATES/teammates/blob/49bea442067302441e41c5416efe6b8333614666/src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java#L626
and here
https://github.com/TEAMMATES/teammates/blob/49bea442067302441e41c5416efe6b8333614666/src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java#L650
are in the wrong order, causeing a NullPointerException one line down
- **Environment**: 
Latest commit as of Feb 23 2022 [49bea44](https://github.com/TEAMMATES/teammates/commit/49bea442067302441e41c5416efe6b8333614666)

**Steps to reproduce**
Try to run populateFieldsToGenerateInQuestion with 
FeedbackParticipantType = STUDENTS_IN_SAME_SECTION or TEAMS_IN_SAME_SECTION 

**Expected behaviour**
Not crashing

**Actual behaviour**
Crashing

**Additional info**
This was discovered while adding new component tests as a school excercise

**Comment by wkurniawan07** [comment]
This is a critical bug and warrants a hot-patch. @leddy231 thanks for catching this!
