### ISSUE TITLE
Compilation error after making a git pull request

### ISSUE THREAD

**Issue by tamrakarsweta220** [TEAMMATES/teammates#11590]
- **Commit SHA: f70ae535d0d0586d48530704227b67f169f49bfb** 
- **Operating System: MacOS**
- **JDK Version: "15.0.2"**
- **Node.js Version: v17.3.0**
- **Firefox / Chrome Version (if applicable):**

**What I was trying to do / What I need help with**
I wanted to create a new branch for an issue I wanted to work on. So, I followed the instructions written on the [development workflow page](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#merging-a-pr) that asked us to pull the code from upstream and then create a new branch. I did that, but when I tried to run the front end of the project from the newly created branch, I got a compilation error. I have attached the screenshot of the error below.

<img width="571" alt="Screen Shot 2022-02-22 at 2 35 41 PM" src="https://user-images.githubusercontent.com/54815489/155205828-73324b51-ebaa-497d-847c-72177f4ee6a1.png">

**Attempts to resolve the problem**
I realized that we have to run the `./gradlew generateTypes` command everytime we pull from the upstream. Previously, I was just doing `npm run build` and that is when the error showed up. However, when I ran the `./gradlew generateTypes` command and then did `npm run build`, the project compiled and I was able to view it on http://localhost:4200/. Is this an expected error? If so, can you explain why it happens and if I resolved it correctly? Also, if it is expected, would it be helpful to add a small note in the [development workflow page](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#merging-a-pr) saying that we have to run both the commands to get rid of the error?

**Comment by samuelfangjw** [comment]
Hi @tamrakarsweta220, yes this is the expected behaviour. `./gradlew generateTypes` is used to generate type definitions required by TypeScript in the frontend from the single source of truth in the backend (e.g. API output formats, Constant, etc...). 

Updating the type definitions is only needed occasionally when new features result in new type definitions being added and is not expected to be a common occurrence.
