### ISSUE TITLE
Can not search for students in instructor search page (difficulties using Apache Solr)

### ISSUE THREAD

**Issue by SavidBasnyat** [TEAMMATES/teammates#11594]
- **Commit SHA:** 
- **Operating System:** MacOS
- **JDK Version:** 14.0.2
- **Node.js Version:** v14.18.0
- **Firefox / Chrome Version (if applicable):**

**What I was trying to do / What I need help with**

I realized that I need to setup Solr in order to work on search features. I followed the steps on [Setting up Solr manually](https://github.com/TEAMMATES/teammates/blob/master/docs/search.md#setting-up-solr-manually) page. After successfully completing step 1 and 2, I was able to start the Solr server. However, I could not complete step 3 as the link provided in that step is not working. How do I connect teammates application with the Solr server running in my computer. I need it to use the search feature in the instructor search page. I am getting the following error when I try to search.
<img width="1432" alt="Screen Shot 2022-02-24 at 3 43 49 PM" src="https://user-images.githubusercontent.com/54815468/155604459-3c7061f3-ee75-4d58-bbf3-3201f95b1fbe.png">
This is the error I am getting in the terminal.

<img width="563" alt="Screen Shot 2022-02-24 at 3 46 48 PM" src="https://user-images.githubusercontent.com/54815468/155605185-4cacee4a-6f86-4c41-bb5e-eba6f38d3299.png">

**Attempts to resolve the problem**

I looked up online for possible solutions but could not find any helpful ones.

**Comment by samuelfangjw** [comment]
> However, I could not complete step 3 as the link provided in that step is not working.

Hi @SavidBasnyat, seems like the link in step 3 needs to be updated. Could you try following step 3 with [this link](https://github.com/TEAMMATES/teammates/blob/master/solr/solr.sh) instead?
