### ISSUE TITLE
Problem with Unicode characters in submissions

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11609]
Reported by a user:

When I enter single quotes, they are decoded to html character codes as shown in the screenshot. Emojis are also affected.

![image](https://user-images.githubusercontent.com/1673303/155938620-21ffb0c4-6b6a-4de7-be26-e77c9839b7d7.png)

How to replicate:
1. Enter feedback containing single quotes. Emojis also work. 
2. Scroll to the bottom of the page and click on the ’Submit Feedback’ button

Expected behaviour: Feedback remains the same.
Actual behaviour: Certain characters are replaced with their html character code counterparts.

**Comment by sivayogasubramanian** [comment]
@damithc I tried to reproduce this but seems like Unicode characters work. Any other way to reproduce this issue?

![image](https://user-images.githubusercontent.com/53614454/173057674-cc98ebe7-a6e9-4b5d-aa4a-41e7c493244d.png)

**Comment by damithc** [comment]
@sivayogasubramanian try these (note the subtle differences in the punctuation symbol used): 
> You’re (rather than You're)
> “Hello” (rather than "Hello")

**Comment by sivayogasubramanian** [comment]
@damithc It seems like it works on my end. 

![image](https://user-images.githubusercontent.com/53614454/173186402-1e2c411b-6054-4be9-8c10-37a13184a83c.png)

**Comment by damithc** [comment]
@sivayogasubramanian based on the initial user report, she is referring to the submission page itself, not the results view.

> How to replicate:
> 
> 1. Enter feedback containing single quotes. Emojis also work.
> 2. Scroll to the bottom of the page and click on the ’Submit Feedback’ button

**Comment by sivayogasubramanian** [comment]
@damithc I tested on the submission page. It works for me. Perhaps can try asking the user for more details like the browser, OS, and specific steps to reproduce.


https://user-images.githubusercontent.com/53614454/175778086-757cf402-1f7a-48da-84f3-95b73a1eb92a.mp4

**Comment by damithc** [comment]
I've asked the user for more info. Will update here if I hear back from him.

**Comment by wkurniawan07** [comment]
Close as there is no recent occurrence
