### ISSUE TITLE
Team contribution question: anomaly in responses shown in the results page

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11615]
A case reported by a user:

Scenario: An instructor is viewing results of a team contribution question.

Results show that a student of a 4-person team has given the following ratings to team members:

![image](https://user-images.githubusercontent.com/1673303/156298278-c8950065-150e-497e-a83a-4cbb3e952be2.png)

However, according to the data in the datastore and the CSV data, the student has given 'Equal Share' to all 4 members. Hence, these 4 should match.

Can someone trace the frontend code to determine which of the following backend value (from `TeamResult.java`) is being used for the `Response` column?

```java
    /** submission values originally from students of the team. */
    public int[][] claimed;
    /** submission values to be shown to instructor (after normalization). */
    public int[][] normalizedClaimed;
    /** average perception of team shown to instructor. Excludes self evaluations */
    public int[] normalizedAveragePerceived;
    /** team perception shown to students. denormalized to match their own claims */
    public int[][] denormalizedAveragePerceived;

    /** the values that were used to calculate normalizedAveragePerceived values. */
    public int[][] normalizedPeerContributionRatio;
```

![image](https://user-images.githubusercontent.com/1673303/156300708-ad41bfec-1003-454f-afce-365a95ac6c45.png)

**Comment by fsgmhoward** [comment]
I cannot reproduce the `4% 4% 4% Eq` value by inputing Eq for all students, although I do find it weird for the values shown in this table - when I input `+10% Eq Eq Eq`, it becomes something like `+7% +3% +3% +2%` in this result table.

**Comment by samuelfangjw** [comment]
Took a quick look, seems like `normalizedPeerContributionRatio` is used, specifically added here.

https://github.com/TEAMMATES/teammates/blob/7c3bda0512557c5cf4accc964a83d28c29af26b2/src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java#L147

**Comment by samuelfangjw** [comment]
To add on to my previous comment, on the frontend, the correct result is initialized at line 47 (see below). However, if statistics object is present, this value is overwritten by the value added in the previous comment.

https://github.com/TEAMMATES/teammates/blob/9cc2e8451096b900b405d8c698291adf0e782e09/src/web/app/components/question-types/question-response/contribution-question-response.component.ts#L47-L55

**Comment by damithc** [comment]
Thanks @samuelfangjw I'll have a look at the Java side of the code and update this thread later.
