### ISSUE TITLE
Sample example questions(Session with different question types) inaccurate when previewing as student

### ISSUE THREAD

**Issue by NicolasCwy** [TEAMMATES/teammates#11612]
- **Environment**: `master` branch at commit de1b10ce29323420014bb7ff1b2c87264fac9f6f, tested on live server as well

**Steps to reproduce**
1. Create a new instructor account
2. Edit sample session named `Session with different question types`
3. Preview as student

**Expected behaviour**
Students will see questions created by sample session (this is the instructor preview)
![image](https://user-images.githubusercontent.com/25302138/156110368-f0a2fecf-796a-4b60-b90a-5caed858af54.png)
![image](https://user-images.githubusercontent.com/25302138/156110390-b901d89a-6d9d-406a-8c80-dbc87d9fd96e.png)

**Actual behaviour**
Student sees questions that are found in other session template
![image](https://user-images.githubusercontent.com/25302138/156110415-47087dd4-0353-4e2c-afa7-75c6340c6220.png)

**Additional info**
- The other example sessions have the correct questions (although both sessions have the questions the same questions as the actual behaviour, this might be a false negative)
- Previewing as instructor shows the correct questions

**Comment by samuelfangjw** [comment]
I don't believe this is a bug. Check the question visibility settings, the first question is for instructors only.

**Comment by NicolasCwy** [comment]
Ah I see, the template got a bit confusing thanks for clarifying
