### ISSUE TITLE
Ng generate: Schematic input does not validate against the Schema

### ISSUE THREAD

**Issue by fsgmhoward** [TEAMMATES/teammates#11622]
There is an issue with the generator schema for `ng generate` at `angular.json` (under root folder). When execute `ng generate component`, this error is thrown:

```
$ ng generate component admin-notifications-page
Schematic input does not validate against the Schema: {"style":"scss","strict":true,"path":"src/web/app/pages-admin/admin-notifications-page","name":"admin-notifications-page","project":"teammates"}
Errors:

  Data path "" must NOT have additional properties(strict).
```

This might be related to the recent update to Angular 12. Under `angular.json`, the key `strict` needs to be removed.
```
"schematics": {
        "@schematics/angular:component": {
          "style": "scss",
          "strict": true
        }
      },
```

Pending investigation on whether similar issues exist for this Angular configuration file.

**Comment by wkurniawan07** [comment]
Looks like I made a mistake during when adding the property. It should be added to a key called `@schematics/angular:application` instead.
```json
"schematics": {
  "@schematics/angular:application": {
    "strict": true
  },
  "@schematics/angular:component": {
    "style": "scss"
  }
},
```

**Comment by samuelfangjw** [comment]
> Pending investigation on whether similar issues exist for this Angular configuration file.

@fsgmhoward  I don't see any other obvious issues with the config file. Should we fix this first? We can always file a new issue if we find any down the line.

**Comment by fsgmhoward** [comment]
@samuelfangjw Sure. Are you going to take it? Just fix it according to the above comment.

**Comment by samuelfangjw** [comment]
> @samuelfangjw Sure. Are you going to take it? Just fix it according to the above comment.

Not really keen on taking credit for this, would you like to finish it up since you found the bug?

**Comment by fsgmhoward** [comment]
@samuelfangjw OK. I will go fix it later.

**Comment by jebarcha** [comment]
Hi, I'm getting this error when trying to create a new interceptor. I already tried the angular.json recommeded above with no luck yet. If this also a knows issue? Thanks

Schematic input does not validate against the Schema: {"name":"core/guards/auth","project":"client","implements":[]}
Errors:

  Data path "/implements" must NOT have fewer than 1 items.

**Comment by leoliscanoa** [comment]
> Hi, I'm getting this error when trying to create a new guard. I already tried the angular.json fix recommeded above with no luck yet. If this also a known issue? Thanks *btw this is in angular 18 cli command: `ng g guard core/guards/auth`
> 
> Schematic input does not validate against the Schema: {"name":"core/guards/auth","project":"client","implements":[]} Errors:
> 
> Data path "/implements" must NOT have fewer than 1 items.

Hey man, you should add this to your angular.json file
`"schematics": {
    "@schematics/angular:guard": {
      "implements": ["CanActivate"]
    }
  },`
Or add the guard type you need

**Comment by jebarcha** [comment]
Hey @leoliscanoa yeah, it did work. 
Many Thanks :)
