### ISSUE TITLE
Refactor date and time methods into utility file

### ISSUE THREAD

**Issue by FergusMok** [TEAMMATES/teammates#11639]
The frontend uses DateFormat/TimeFormat, Moment and epoch timestamps, and even Date.
However, functions to parse and manipulate between the data types are scattered in different files and folders.

Examples that can benefit from refactoring:
- Put methods to convert between the types into one single utility file
E.g getDateTimeAtTimezone (conversion from timestamp to date/time format) implemented only in Session Edit page
- Time-related magic numbers being declared locally repeatedly, or even just used plainly as numbers throughout the repo

**Comment by tau-bar** [comment]
Hello, @FergusMok is it okay if I try working on this?

**Comment by FergusMok** [comment]
@tau-bar Yes please go ahead :)

**Comment by tau-bar** [comment]
@FergusMok Could you help me in reviewing the PR?
