### ISSUE TITLE
Logging in to a TEAMMATES instance

### ISSUE THREAD

**Issue by jgrant12345** [TEAMMATES/teammates#11638]
- **Commit SHA:** 
- **Operating System:**
- macOS
- **JDK Version:**
- 11.0.12
- **Node.js Version:**
- v14.18.1
- **Firefox / Chrome Version (if applicable):**

**What I was trying to do / What I need help with**
I'm new to the project and I was trying to set it up. I ran into a similar issue as this [issue here](https://github.com/TEAMMATES/teammates/issues/11387).  Essentially whenever I try to login as admin for the first time using http://localhost:8080/web/admin/home, I get redirected to http://localhost:8080/web/front/home and I get the error "you are not authorized to view this page".

**Attempts to resolve the problem**
I've tried following the guide as specified here https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#managing-the-dev-server-front-end. I also tried using what was suggested in the issue [here](https://github.com/TEAMMATES/teammates/issues/11387) ```./gradlew generateTypes``` then  ```npm run start``` in terminal 1 --> ```docker-compose up -d in``` terminal 2 --> ```./gradlew serverRun``` in terminal 2 (executing at around 85%) but I essentially am unable to login as an admin.

**Comment by jgrant12345** [comment]
Actually I ended up figuring it out. You can log in with this email: [app_admin@gmail.com](mailto:app_admin@gmail.com). And then enter the url for the admin e.g. http://localhost:8080/web/admin/home. That's what worked for me

**Comment by ypinhsuan** [comment]
Glad to see that you are able to resolve the issue :)
