### ISSUE TITLE
Apply lazy-loading of question responses in session results page

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#11641]
Current: Upon loading the session results page, the responses of all questions are loaded.

Problems:
- Not performant at large number of responses.
  - While it does not introduce burst of parallel API calls, as the burden of fetching all responses falls on one single API call, it is not difficult to see the potential performance issue at large enough scale.
- There is a not-small chance that a user only wants to see the responses of a question somewhere before or until the middle of the page. That means the bottom half of the page is wasted.

Note: While this is in the same spirit as #11640, the root cause is different and more fundamental here.

Solution:
- Upon loading the page, only fetch the list of questions, just like how submission page and feedback report page for instructors work.
- (similar to #11640) Apply lazy loading; only load the responses of the question when the question is in viewport.

**Comment by NicolasCwy** [comment]
Would like to pick this up!

**Comment by tsy24** [comment]
Hi, is this issue still available? If yes, I would like to work on this issue.

**Comment by NicolasCwy** [comment]
@tsy24 Please go ahead!

**Comment by AdwitiyaMishra** [comment]
Hi, I would like to work on this issue. Kindly let me know if it's available

**Comment by ypinhsuan** [comment]
Hi @AdwitiyaMishra, thanks for your interest! There is a PR for this issue already, please find another issue to work on.
