### ISSUE TITLE
Devise a better way to handle duplicate account requests

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#11655]
https://github.com/TEAMMATES/teammates/blob/3824506e4948639b0fba6771aee3dc909c00ec3a/src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java#L29-L36

Line 35 states that if an account request already exists, creating another with same email + institute should result in resending the same registration URL to the account requester.

Problem: the URL will not be usable if the account request is already used to register.

However, this is simply a precursor to a missing feature that we really need.

**Actual problem statement**

We need a more rigorous way to handle duplicate account requests. The discussion goes way back to #11582.

- By mistake or otherwise, an instructor may lost all the courses s/he is in, or at least those s/he is a co-owner of. After #11654, this will preclude him/her from creating new courses, i.e. effectively barring his/her access as "someone who requested an account". This will be a legitimate reason for re-requesting an account, but is not supported.
- Losing access to the account used to login is not a reason to request a new account from system's point of view, but is a legitimate reason from user's point of view. We need to be able to identify such case.
- Sometimes, it is a genuine mistake that someone forgets that s/he is already a registered user, in which case s/he just needs to be reminded.

**Solution**

- Allow resetting of account request's registered at date, much like how an account's google ID can be reset.
- The above operation (create a duplicate account request when an existing one is already registered) should return a 409. But there should be a convenient way to tell admin on the next action to do, which can be either:
  - Resetting the entire account request and resending the system invitation.
  - Resetting just the google account and resending the join link only.
    - Alternatively, running the google ID migration script, if there are many instructors (and students) under the said account.
  - Simply reminding the user.

**Comment by samuelfangjw** [comment]
@wkurniawan07 Can I clarify the expected behaviour when account request is reset? Other than resetting account request registered at date and sending join email, are there any related entities that need to be deleted as well?

**Comment by wkurniawan07** [comment]
I don't think there's any. AccountRequest is very much an independent entity.
