### ISSUE TITLE
Student prompted to login if session is not yet open

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11669]
Scenario:
1. A session opens. Students receive submission links.
2. Instructor changes the session open time to a future time i.e., session no longer open
3. Student tries to submit using the link (the student has not joined the course yet)
4. What is expected: an error message appears stating 'The session is not open'
5. What actually happens: the above error message appears momentarily but the student is taken to the Google login page 1-2 seconds later.

**Comment by damithc** [comment]
More cases of this reported by users ...

**Comment by damithc** [comment]
Increasing the priority, as this issue is generating many support requests ...

**Comment by xyliew25** [comment]
Hi @damithc and all, as assigned by @wkurniawan07, I would like to take up this issue.

I have a few questions regarding the expectations.
1. Suppose that there is no redirection to the login page now, after dismissing/closing the error message, what should be shown or any specific redirection? Now after dismissing/closing the error message, the session submission page looks like this: <img width="960" alt="image" src="https://user-images.githubusercontent.com/75534016/169226259-31350b61-6b36-4995-9259-2460ca5b8111.png"> Note the missing Opening time, Closing time and Instructions fields, and the loading spinner to load the questions.

2. Should a student that joined the course remain to be redirected to the login page, or the same expectation applies? Or should this case be a separate issue?

**Comment by damithc** [comment]
@xyliew25 perhaps a straight-forward solution is to go directly to an error page, rather than show a dialog box? It's straight-forward in the sense it works for all cases; not sure if the implementation will be straight forward though.

**Comment by wkurniawan07** [comment]
@damithc there is no "an error page" other than 404. The concept of an error page has been removed since V7.

@xyliew25 most straightforward way is to redirect (to main front page if user is unregistered, to home page otherwise) after the modal is closed. That answers both your questions.

**Comment by xyliew25** [comment]
@wkurniawan07 I've got it for the case of an unregistered student.

However, for the case of a registered student, at the moment, regardless of whether the feedback session is open or yet to be opened, when the student clicks on the submission link, s/he will first be redirected to the login page before being able to submit his/her feedback or see the 'This feedback session is not yet visible' error message. Do you want this logic to be changed for both cases, or just for the case of yet-to-be-opened sessions?

**Comment by wkurniawan07** [comment]
If we classify the unhappy paths as follows:
- Session-wide unhappy paths, e.g. session not found, not visible, not yet open
- User-specific unhappy paths, e.g. invalid key, wrong registered user

No matter whether the student/instructor is registered or not, if a session-wide unhappy path is hit, there should be no attempt to ask user to log in. Redirect can simply follow whether there is a logged in user or not.

**Comment by xyliew25** [comment]
@wkurniawan07 sorry but I got confused with the last line, i.e. redirect to which page? Do you mean:
* Session-wide unhappy paths:
  * Unregistered student/instructor: main front page after closing the modal
  * Registered student/instructor: 
    * Logged in: student/instructor home page after closing the modal
    * Not logged in: main front page after closing the model
* Happy paths:
  * Unregistered student/instructor: submission page
  * Registered student/instructor: 
    * Logged in: submission page
    * Not logged in: submission page

Also, regarding the user-specific unhappy paths, at the moment, if the key is invalid, the student/instructor will be redirected to the main front page with an error message of 'You are not authorized to view this page.'; if the logged in student/instructor is different from the student/instructor of the submission link, there will be no error thrown (when the session is open). For the latter case, should an error message be shown or have the same behavior as the former?

**Comment by wkurniawan07** [comment]
It is not necessary to differentiate registered/unregistered user:
- Session-wide unhappy paths:
  - Logged in: student/instructor home page after closing the modal
  - Not logged in: main front page after closing the modal
