### ISSUE TITLE
Instructor: add course: Wrong redirection after adding a course

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#1168]
_From [victorph...@gmail.com](https://code.google.com/u/114670200553077300926/) on August 28, 2013 19:58:20_

after adding a course, refreshing the web page display the error "A course by the same ID already exists in the system" instead of actually reloading the add new course page

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1169_

**Comment by mukesh14149** [comment]
I can work on this.
