### ISSUE TITLE
Index error when checking response rate of a session

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11697]
Clicking the 'show' link of some sessions throw an error although some other sessions don't seem to be affected.

![image](https://user-images.githubusercontent.com/1673303/161328341-e3d76d04-ab8e-4b0d-ba1e-bb51dd9a17a9.png)

![image](https://user-images.githubusercontent.com/1673303/161328195-7bc9e89b-77f5-48c6-a032-1fe9cf04af3c.png)

One thing common to the affected sessions is that they have questions meant for instructors.

**Comment by wkurniawan07** [comment]
@moziliar looks like using projection query isn't really a good idea, after all

**Comment by moziliar** [comment]
Agree. Let me remove the projection real quick.
