### ISSUE TITLE
Admin/Maintainer Logs: Two loading spinner

### ISSUE THREAD

**Issue by fsgmhoward** [TEAMMATES/teammates#11694]
- **Environment**: 

Master branch at [7dfda8b](https://github.com/TEAMMATES/teammates/commit/7dfda8ba63070c0924eb397c98bae8008c00b30b).

Currently, the log page shows two spinner while loading (for the table view, histogram view is fine):

![image](https://user-images.githubusercontent.com/10681776/161210393-8f7c0e3c-8fc9-4c7b-a1b9-d686525dd59a.png)

It would be good that only 1 spinner is shown during initial loading of data. This affects both admin logs and maintainer logs page.

**Comment by moziliar** [comment]
I think quite a few pages across TEAMMATES will show more than one spinner, one for each component.
