### ISSUE TITLE
Allow overriding of values in `build.properties` in dev server

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#11706]
Current: `build.properties` is a one-stop configuration file for both production and development instances.

Problem:
While this works, this presents a great inconvenience for developers who have to frequently deploy to production server, as they need to change some values back-and-forth depending on whether they are deploying or running local server. While it is true that the need for developers to use production server has been continuously diminishing, it is still not zero and will never be.

Solution:
- Maintain a dedicated dev server configuration file, e.g. `build-dev.properties`.
- When `Config.java` is initialized, the value of a property is by default read from `build.properties`. However, if the environment is determined to be dev server and the value exists in `build-dev.properties` (which also may not exist), the value will be read from `build-dev.properties` instead.
- Some properties such as `app.localdatastore.port`, `app.taskqueue.active`, and `app.enable.devserver.login` do not make sense in production server. We can optionally introduce another layer of logic here to just use pre-defined values for these properties in production server.
  - So is `app.frontenddev.url`, but this particular property can actually be re-purposed to concurrently solve #11490. May need a rename, though.

This solution draws inspiration from Spring Boot's `application.properties` and `application-*.properties`, for those who are familiar.

**Comment by deepdmistry** [comment]
Can I work on this?

**Comment by NicolasCwy** [comment]
@deepdmistry Yup you can!

**Comment by deepdmistry** [comment]
FYI, I cant do this anytime soon so anyone feel free to pick up. Thanks
