### ISSUE TITLE
Instructor Help Page: Outdated search bar documentation

### ISSUE THREAD

**Issue by FergusMok** [TEAMMATES/teammates#11710]
![image](https://user-images.githubusercontent.com/10182564/161612784-9fe6b53a-8ebd-410a-a3aa-ab06db87abed.png)

Suggested changes: Remove the first instruction, as there is no option for 'Students' in the Instructor's search bar

**Comment by deepdmistry** [comment]
Can i do this ?

**Comment by samuelfangjw** [comment]
@deepdmistry Sure, please go ahead.

**Comment by OIS202** [comment]
Is this still up for me to tackle?

**Comment by deepdmistry** [comment]
Hi @OIS202 I have a PR that fixes this and is approved so I believe it's not up for grabs. Somebody feel free to correct me if that's not the case.

**Comment by FergusMok** [comment]
Hi @OIS202, thank you for the interest, but the issue has been fixed, you can find another issue to work on
