### ISSUE TITLE
student submitting responses: inform that submitting individual responses is optional

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11719]
version: v8.13.1, production

In recent times, we have added a feature for respondents to submit one question at a time. We also have a button at the bottom of the page to submit the whole page, as before.

Some users seem to think that they _have_ to submit each question individually and then submit the whole page one more time at the end.

Suggestion: We can tweak the UI to inform the respondent that submitting individual responses is optional.

**Comment by kantiprasanna** [comment]
I will take up this issue

**Comment by zhengtaoJ** [comment]
Hi may I know is this issue resolved? If not can I work on it?

**Comment by zhaojj2209** [comment]
@zhengtaoJ Feel free to submit a PR for this issue!

**Comment by AdwitiyaMishra** [comment]
Hi, I would like to work on this issue. Kindly let me know if it's available.

**Comment by ypinhsuan** [comment]
Hi @AdwitiyaMishra there is already a PR for this issue as well
