### ISSUE TITLE
Selective Deadline Extension - Error in getting deadline extension entities possibly needing closing email

### ISSUE THREAD

**Issue by halfwhole** [TEAMMATES/teammates#11715]
Issue is observed in the latest `master` branch, on both production and staging. When performing the hourly action to send feedback session closing reminders, there is a `DatastoreException` being thrown. Seems like a simple fix by changing the index file. The error log looks something like this:

<img width="916" alt="Screenshot 2022-04-09 at 11 17 37 PM" src="https://user-images.githubusercontent.com/41856541/162580212-8709323e-8ef9-4a90-9234-5de451bb9ccc.png">

The source location of the error is in line 205:

https://github.com/TEAMMATES/teammates/blob/9aab6bd7b17c246c343a435720bb7fe22c62a26f/src/main/java/teammates/storage/api/DeadlineExtensionsDb.java#L200-L206

The errors can be seen on our maintainer logs every hour as well:

<img width="627" alt="Screenshot 2022-04-09 at 11 24 46 PM" src="https://user-images.githubusercontent.com/41856541/162580520-391039cf-4303-4f47-b4c1-b88741ce8601.png">

**Comment by samuelfangjw** [comment]
https://github.com/TEAMMATES/teammates/blob/9aab6bd7b17c246c343a435720bb7fe22c62a26f/src/main/appengine/index.yaml#L84-L89

That's weird, it's already present though.

**Comment by halfwhole** [comment]
Probably the order of the indexes matters in this case? My understanding is that for datastore, indexes for equality filters should generally be defined before those for inequality/range filters

**Comment by wkurniawan07** [comment]
@halfwhole @samuelfangjw if this is breaking a production system's function (and it looks like it does), it should be released as hot-patch. The fix should aim towards the `release` branch directly and no other fixes already present in `master` should be included.

**Comment by samuelfangjw** [comment]
> @halfwhole @samuelfangjw if this is breaking a production system's function (and it looks like it does), it should be released as hot-patch. The fix should aim towards the `release` branch directly and no other fixes already present in `master` should be included.

Made the changes!

**Comment by samuelfangjw** [comment]
Patch seems to have resolved the issue :)
