### ISSUE TITLE
Broken link in acknowledgements section

### ISSUE THREAD

**Issue by samuelfangjw** [TEAMMATES/teammates#11717]
In the acknowledgements section of the [about](https://teammatesv4.appspot.com/web/front/about) page as well as the [project README](https://github.com/TEAMMATES/teammates#acknowledgements), the link to [Centre for Development of Teaching and Learning (CDTL)](http://www.cdtl.nus.edu.sg/) has been broken for some time.

The correct site should be https://nus.edu.sg/cdtl.

**Comment by DineshKoushik** [comment]
I went ahead to fix this issue without you assigning me. Because I felt that this issue is very minor. Anyway thanks for the opportunity. Looking forward to take up many tasks from your repositories!

**Comment by Kaushik-Iyer** [comment]
Is this issue fixed?

**Comment by ypinhsuan** [comment]
Hi @Kaushik-Iyer, thanks for your interest, but there is a PR that fixes this issue. You can look for other issues to work on :)
