### ISSUE TITLE
Selective deadline extension - NPE when updating feedback session 

### ISSUE THREAD

**Issue by halfwhole** [TEAMMATES/teammates#11722]
Issue is observed on maintainer logs in production, since the release of the selective deadline extension backend.

Occasionally we see a null pointer exception at `FeedbackSessionUpdateRequest` line 19: 

<img width="643" alt="Screenshot 2022-04-11 at 6 54 41 PM" src="https://user-images.githubusercontent.com/41856541/162725744-15ae4725-6e02-4f36-9af8-8f40382025f8.png">

https://github.com/TEAMMATES/teammates/blob/bda123f4d725ef56500012baa25b0cdb0a849a33/src/main/java/teammates/ui/request/FeedbackSessionUpdateRequest.java#L15-L22

**Comment by samuelfangjw** [comment]
@jayasting98, any ideas why an NPE is thrown here? I can't seem to find a path where `studentDeadlines` is null at this point.

**Comment by jayasting98** [comment]
Yea, I was also looking, but not quite sure yet unfortunately.

This should prevent it right? I really don't see how the null pointer exception is happening unless somehow some users have older front-end code.
![image](https://user-images.githubusercontent.com/65202977/162755086-aca0d094-e65f-4537-bcd2-873696f333a5.png)

**Comment by wkurniawan07** [comment]
Looking at a few of those logs, all of them have this in common:
```
"webVersion": "8.12.0"
```
i.e. stale front-end cache, a problem that unfortunately has been plaguing us for far too long.

**Comment by samuelfangjw** [comment]
> Looking at a few of those logs, all of them have this in common:
> 
> ```
> "webVersion": "8.12.0"
> ```
> 
> i.e. stale front-end cache, a problem that unfortunately has been plaguing us for far too long.

Thanks for checking! I couldn't find "webVersion" in the logs just now but I see it now. Ok to close this issue then? I don't think there's much we can do about stale cache.

**Comment by halfwhole** [comment]
Yep agree can probably close this then (#11364 for reference)
