### ISSUE TITLE
Admin page header tabs do not fit header at certain screen sizes

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#11724]
With the addition of the usage statistics and notification tabs to the header bar, the header tabs no longer fit the header for screen/browser widths ranging from 1151px to 992px, as shown below.

<img width="880" alt="Screenshot 2022-04-11 at 21 30 44" src="https://user-images.githubusercontent.com/54243224/162750896-81437bf0-df1a-4661-aa98-196cbc09bd05.png">

Possible solutions include reducing the left/right padding of the header for this size range, or changing the breakpoint for switching to mobile dropdown to 1151px (current breakpoint is 992px).

**Comment by samuelfangjw** [comment]
One thing to note is that the current choice of 992px is unlikely to be arbitrary (this is one of bootstrap's default breakpoints). Might want to consider choosing the next largest default breakpoint here if we do go down that route (if it's not too large).

**Comment by rom-me** [comment]
Can I attempt this?

**Comment by zhaojj2209** [comment]
@rom-me Sure, feel free to submit a PR for this!

**Comment by masoudtabatabaei** [comment]
I think this problem was solved, Is not that so?

**Comment by zhaojj2209** [comment]
> I think this problem was solved, Is not that so?

The issue can still be replicated on my end. To clarify, this only affects admin pages and can therefore only be replicated when logged into accounts with admin privileges; the headers for other pages (student, instructor, maintainer) are unaffected.

**Comment by NehaSantani** [comment]
Hi, I would like to solve this issue!
Is this issue still open?

**Comment by NehaSantani** [comment]
I just Fixed this issue!
Could you please verify!
Thanks
