### ISSUE TITLE
Selective deadline extension - NPE when submitting feedback responses

### ISSUE THREAD

**Issue by halfwhole** [TEAMMATES/teammates#11721]
Issue is observed on maintainer logs in production, since the release of the selective deadline extension backend.

We can occasionally see a null pointer exception from `SubmitFeedbackResponsesAction` line 60: 

<img width="643" alt="Screenshot 2022-04-11 at 6 47 22 PM" src="https://user-images.githubusercontent.com/41856541/162724700-757d360e-0298-4dba-9559-d63e67dbad93.png">

https://github.com/TEAMMATES/teammates/blob/bda123f4d725ef56500012baa25b0cdb0a849a33/src/main/java/teammates/ui/webapi/SubmitFeedbackResponsesAction.java#L55-L63

**Comment by samuelfangjw** [comment]
Looking at the old logic, if `studentAttributes` is null `checkAccessControlForStudentFeedbackSubmission(studentAttributes, feedbackSession); ` will throw UnauthorizedAccessException.

I believe we can check if `studentAttributes` is null and throw the same exception if it is. What do you think?

**Comment by halfwhole** [comment]
Checking for null student attributes sounds good, I'm wondering if we want to throw an `EntityNotFoundException` instead? That would be in line with what's currently in place with e.g. the `CreateFeedbackResponseCommentAction`, which checks for it before going ahead with checking access control for students/instructors

**Comment by samuelfangjw** [comment]
Not too sure about this, but currently it throws this:

https://github.com/TEAMMATES/teammates/blob/bda123f4d725ef56500012baa25b0cdb0a849a33/src/main/java/teammates/ui/webapi/BasicFeedbackSubmissionAction.java#L61-L65

**Comment by damithc** [comment]
@samuelfangjw what's the impact of this? Is it affecting current users?

**Comment by samuelfangjw** [comment]
@damithc, I don't believe it's a critical bug. If I'm not wrong, the recent change in logic just means that Null Pointer Exception is thrown instead of `UnauthorizedAccessException("Trying to access system using a non-existent student entity")` when trying to submit feedback response for a non-existent student/instructor.
