### ISSUE TITLE
Update links to point to the deployed site for developer guide

### ISSUE THREAD

**Issue by tlylt** [TEAMMATES/teammates#11736]
With the recent update and deployment of the developer guide, there are a few cases where references to the dg are still referring to the markdown files instead of the deployed website. For example:
- the readme does not refer to the deployed dev docs (documentation URL, and orientation) . e.g. [here](https://github.com/TEAMMATES/teammates-ops#readme)
  - ![image](https://user-images.githubusercontent.com/41845017/163374835-da20f790-2e0a-4fce-b6cc-566ffc01519e.png)
- pull request template does not refer to the deployed dev docs (PR guideline). e.g [here](https://github.com/TEAMMATES/teammates/blob/master/.github/PULL_REQUEST_TEMPLATE.md)
  - ![image](https://user-images.githubusercontent.com/41845017/163373983-43145883-5a4e-4caf-b3a4-8dc8c7f16ea6.png)
- The issue bot does not refer to the deployed dev docs (contributing guideline) e.g [here](https://github.com/TEAMMATES/teammates/pull/11733#issuecomment-1098774275) 
  -  ![image](https://user-images.githubusercontent.com/41845017/163372814-19e5433e-4ffd-4919-91fc-cb72bce9e0a2.png)
  - Not sure if this part should be raised in the teammates-ops repo

The link to the deployed dev docs is https://teammates.github.io/teammates/

**Comment by SavidBasnyat** [comment]
Could I work on this?

**Comment by damithc** [comment]
This needs to be fixed soon, as our main Dev Docs link is broken.

**Comment by kaixin-hc** [comment]
Since this was a leftover from my PR, I've PRed a fix - thanks @SavidBasnyat for offering.
