### ISSUE TITLE
Broken PUML diagrams in developer guide

### ISSUE THREAD

**Issue by kaixin-hc** [TEAMMATES/teammates#11732]
Raised in https://github.com/TEAMMATES/teammates/pull/11680#issuecomment-1098418311
- **Environment**: 

**Steps to reproduce**
Current developer guide is displaying this behaviour.

However, I can't seem to reproduce this on my own branch. The issue seemed to be there but once I built and deployed it showed no error: See https://kaixin-hc.github.io/teammates/design.html which was built from the master branch which should be currently synced with the teammates master. I've asked the MarkBind team to investigate with me. 

**Expected behaviour**

The PUML diagram should be displayed.

**Actual behaviour**
The following error seems to be displayed in most cases.
<img width="516" alt="Screenshot 2022-04-14 at 12 50 43 PM" src="https://user-images.githubusercontent.com/59471320/163315832-25a8a980-6b33-4004-8cb6-0084916a4ab9.png">

**Additional info**

As the devGuide is actively used by developers, I will push a temporary change to use .png files until we can figure out why this issue is occurring.

**Comment by damithc** [comment]
> However, I can't seem to reproduce this on my own branch. The issue seemed to be there but once I built and deployed it showed no error: See https://kaixin-hc.github.io/teammates/design.html which was built from the master branch which should be currently synced with the teammates master. I've asked the MarkBind team to investigate with me.

@kaixin-hc the difference could be due to manual deployment vs auto-deployment using GitHub actions.

**Comment by wkurniawan07** [comment]
> However, I can't seem to reproduce this on my own branch.

@kaixin-hc What exactly did you do to "reproduce" here? Like Prof said, running and deploying the branch locally (thus having graphviz installed) and letting the branch run as part of CI are not the same reproduction steps.

**Comment by samuelfangjw** [comment]
> I can't seem to reproduce this on my own branch

If I may add on to this convo, I visited `https://kaixin-hc.github.io/teammates/design.html` last night after the issue was brought up. The same issue was present there as well. The deployment workflow ran on your branch [yesterday](https://github.com/kaixin-hc/teammates/runs/6010915615?check_suite_focus=true), so there's a good chance the site I saw was deployed via gh-actions.

**Comment by kaixin-hc** [comment]
Yes, the issue was in the CI which I did not check at the time of creating this issue to push the png fix. At the time of this issue creation thought it would be best to fix the problem before continuing further investigation which I did on the MarkBind issue. Thanks to tlylt who helped to solve the underlying cause!
