### ISSUE TITLE
Instructor editing questions: tweak the confirmation dialog for cancelling an edit

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11759]
v8.14.1, production

Steps:
1. Login as instructor
2. Go to the 'edit' page of a session
3. Add a new question (without saving), change settings of the question
4. Click the 'Cancel' button to cancel the operation. 

Problem: The text in the confirmation dialog (shown below) are not aligned with the operation, which happens to be a 'cancel' operation itself.
![image](https://user-images.githubusercontent.com/1673303/164911284-c90828a6-b75b-47fc-ad00-0282aa2d11e7.png)

How about we tweak the text as follows?
`No, cancel the operation` -> `No, go back to editing`

**Comment by cmess77** [comment]
I believe I have a fix for this. Mind if I take a look?

**Comment by DelphiHide** [comment]
@cmess77 I was just about to open a PR for this

**Comment by cmess77** [comment]
@DelphiHide not a problem, all yours! 👍
