### ISSUE TITLE
'Session closing soon' email: highlight 'No action is required if you have already submitted'

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11755]
v8.14.1, production

Suggestions: When sending the 'Session closing soon' emails for a session
* Tweak `The following feedback session is still open for submissions.` -> `Just a gentle reminder that the following feedback session is still open for submissions, in case you have not submitted yet or wish to update your submission.`
* Highlight the phrase (i.e., `<mark>...</mark>`)  'No action is required if you have already submitted.' and place it to follow the sentence mentioned above.

Reason: To reduce support requests such as these from students:
>I already submitted my feedback so I am not sure why I am still receiving the message below.
>Please advise

**Comment by kvaithin** [comment]
Hi team, I am looking to pick up this work. Thanks.

**Comment by kvaithin** [comment]
Do I need to apply for access to push a branch to this repo? 

Following the docs here. 
https://teammates.github.io/teammates/process.html

Attempting to push my change via the following commands. 

`git push origin 11755-session-closing-soon`

or

`git push -u origin 11755-session-closing-soon`

Getting this error: 

`
ERROR: Permission to TEAMMATES/teammates.git denied to kvaithin.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Issue seems specific to this repo. Able to push to other repos without issue.
Please

**Comment by TomBurrows101** [comment]
I've been working on this for a couple of days, and I keep getting stuck at the testing. I'm honestly not sure why this is happening, but I'm well and truly stuck on it. I can imagine it would be a very simple fix, but as it's my first time contributing, I can't figure it out.


![image](https://user-images.githubusercontent.com/26943188/176271802-6ed29ff7-e4a2-42de-a27c-6bb00931a1d5.png)

**Comment by ziqing26** [comment]
@TomBurrows101 Hi thanks for trying to contribute, the error message is saying that you might want to look into the email content and check if your changes have led to changes in email content which fails `assertEquals` in `testGenerateFeedbackSessionEmails`

**Comment by TomBurrows101** [comment]
@ziqing26 Thanks for responding so quickly. I know that the program is test generating an email to send out (`testGenerateFeedbackSessionEmails`), and then as a part of the test (`EmailChecker.java`) is comparing this email with `src/test/resources/emails/*.html`. What I don't know is, what the differences are between the generated file and the template file. As far as I can tell they are identical, do you know how I'd be able to inspect a file generated by `testGenerateFeedbackSessionEmails`, so I can check for differences?

I hope that all makes sense.

**Comment by ziqing26** [comment]
> @ziqing26 Thanks for responding so quickly. I know that the program is test generating an email to send out (`testGenerateFeedbackSessionEmails`), and then as a part of the test (`EmailChecker.java`) is comparing this email with `src/test/resources/emails/*.html`. What I don't know is, what the differences are between the generated file and the template file. As far as I can tell they are identical, do you know how I'd be able to inspect a file generated by `testGenerateFeedbackSessionEmails`, so I can check for differences?
> 
> I hope that all makes sense.

I have replied you in your merge request, kindly check it if that helps!

**Comment by tenebrius1** [comment]
Hello, could I just check if @TomBurrows101 is still working on it? If not I have a working solution ready for a pull request!

**Comment by TomBurrows101** [comment]
@tenebrius1 Hi, feel free to go ahead and submit your solution, I don't think I'm going to be able to get this working, and I'm really interested to see how you've done it.
