### ISSUE TITLE
submitting responses: differentiate button/dialog for individual question submission from all-questions submission

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11753]
We recently added as a button for respondents to submit one question at time.
![image](https://user-images.githubusercontent.com/1673303/164275736-3456f329-9a07-45c4-bb0a-0080f60cf0db.png)

There was one recent case where a the session had three questions but the last question was optional. Some students filled the first two questions and clicked the submit button at the bottom of the 2nd question, which resulted in submitting only the 2nd question while the student thought the whole form was submitted. The instructor received many complaints "I submitted both questions but question 1 answer is missing!". I suspect this problem is especially applicable when the respondent is using a small screen (e.g., phone) because it is even harder to see if there is some more questions below.

Suggestion: perhaps tweak the button text to make it clear that only the response to one question will be submitted? e.g., `Submit responses to question 2` ? In addition, we can consider differentiating the result dialog for a single question submission from that of the  all-questions submission.

**Comment by hoanglan21** [comment]
Maybe we can make a modal popup when the student clicks the submit button?
