### ISSUE TITLE
Deadline extensions in FeedbackSession entity have unnecessary constraint

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#11751]
- **Environment**: live server at V8.14.0

**Steps to reproduce**

1. Create a session
1. Create a large number of deadline extensions for the session

**Expected behaviour**

Deadline extensions saved successfully.

**Actual behaviour**

```tx
DatastoreException caught by WebApiServlet: The value of property "studentDeadlines" is longer than 1500 bytes.
```
The same can be expected for `instructorDeadlines`.

**Comment by wkurniawan07** [comment]
@damithc [V8.14.1](https://github.com/TEAMMATES/teammates/releases/tag/V8.14.1) which resolves this issue has been released.

**Comment by damithc** [comment]
> @damithc [V8.14.1](https://github.com/TEAMMATES/teammates/releases/tag/V8.14.1) which resolves this issue has been released.

Deployed and released. Thanks for the quick fix @samuelfangjw
