### ISSUE TITLE
Prevent users joining binned courses

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11767]
v8.14.1, production

Current: users can join a course that has been binned (i.e., in the recycle bin, but not permanently deleted) ~~-- this is speculation based on  a support request, to be verified by the dev team~~

Suggestion: instead of letting the user join, perhaps we should inform the user that the course has been deleted? Otherwise they'll send support requests because they can't see the course after joining it.

**Comment by samuelfangjw** [comment]
Tested locally, I can confirm that users can join a course that has been binned.

**Comment by daongochieu2810** [comment]
@samuelfangjw do you have to use the staging server to reproduce the described behaviour?

**Comment by samuelfangjw** [comment]
> @samuelfangjw do you have to use the staging server to reproduce the described behaviour?

@daongochieu2810 No, I reproduced this locally.

**Comment by daongochieu2810** [comment]
@samuelfangjw May I know the steps you took to reproduce this? Thanks

**Comment by samuelfangjw** [comment]
> @samuelfangjw May I know the steps you took to reproduce this? Thanks

Sure, Steps:
1. Enroll student in course
2. Get join course link for enrolled student
3. Move course to recycle bin
4. Join course as student

**Comment by daongochieu2810** [comment]
@samuelfangjw how do I get the join course link for enrolled student?

**Comment by samuelfangjw** [comment]
> @samuelfangjw how do I get the join course link for enrolled student?

@daongochieu2810 you can get it from the admin search page or from the backend console logs (email is sent when you enroll a student).
