### ISSUE TITLE
Deprecation - Upgrade to Codecov Uploader

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [TEAMMATES/teammates#11761]
- **Environment**: 
`master` branch at latest commit.

**Description of feature/enhancement**
The Codecov Bash Uploader as shown below has been [deprecated](https://about.codecov.io/blog/introducing-codecovs-new-uploader/):
https://github.com/TEAMMATES/teammates/blob/115addc70a976d2d0ef6e908c80ca493783f656f/.github/workflows/component.yml#L78-L80
It has since been replaced by a new uploader as seen [here](https://uploader.codecov.io/).

**Justification**

Although the Bash Uploader was supposed to be fully sunset by February 2022, it still worked for RepoSense for a few months and may still be working today. That said, there is a chance that the Bash Uploader may stop working suddenly.

In addition, this may also be a chance to explore switching to the [GitHub Actions version](https://github.com/codecov/codecov-action) of the Codecov Uploader. It's latest version is `v3`.

**Comment by wkurniawan07** [comment]
@yhtMinceraft1010X please be welcome to work on this
