### ISSUE TITLE
Errors after git pull upstream master

### ISSUE THREAD

**Issue by egorovak** [TEAMMATES/teammates#11768]
Issue title: Help Request: Getting java related errors after pulling and setting up the project again

- **Commit SHA:** git pull upstream master
- **Operating System:** Windows 10
- **JDK Version:** 11.0.11 (global and evoroment var)
- **Node.js Version:** v16.15.0
- **Firefox / Chrome Version (if applicable):**

**What I was trying to do / What I need help with**
I tried to update my local by pulling from upstream. I worked through many errors but in the end, I am stuck with many that all seem to be related to java. I am not sure how to proceed. 

**Attempts to resolve the problem**
I did a git pull upstream master instead of git pull and ended up 
with many merge conflicts, that I wasn't sure how to solve. Eventually, I just did the whole [setup](https://teammates.github.io/teammates/setting-up.html) process again because I thought it might be related to some updates there. I have also updated my nodejs, npm and had to install VS. The compilation error disappeared but now I have many errors that seem to be related to java and often package-info.java. I have attached the screenshots to illustrate.

![Screenshot 2022-04-27 180255](https://user-images.githubusercontent.com/46948739/165638726-76b09848-0933-4fa7-b528-c30f7dd8862c.png)

Thank you!

**Comment by wkurniawan07** [comment]
> had to install VS

Although you're free to use VS (or any IDE of your liking), you really don't have to.
This is not a TM-specific problem. Have you tried looking at solutions e.g. in StackOverflow?

**Comment by wkurniawan07** [comment]
Closing as this is not TM-specific issue
