### ISSUE TITLE
Deprecation - Upgrade Node

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [TEAMMATES/teammates#11762]
- **Environment**: 
`master` branch latest

**Description of feature/enhancement**
Although it has been mentioned as a side note under #11729, I feel that given the impending EOL of Node 12, the upgrade of Node (and raising of minimum Node version requirement) should be a separate issue. With regards to Node versions being used by other NUS-OSS projects, the details are as follows:
* RepoSense - [Already Upgraded to Node 14](https://github.com/reposense/RepoSense/pull/1714)
* MarkBind - [Planning to Upgrade to Node 14](https://github.com/MarkBind/markbind/issues/1862)
* CATcher - [Suggested Upgrade to Node 14](https://github.com/CATcher-org/CATcher/issues/941)

**Justification**

Standardising the Node version across all projects may help developers who wish to work on multiple projects since they would only need to install one version of Node. In future, we could also coordinate Node upgrades across all of our projects whenever the Node version in use reaches EOL.

**Comment by wkurniawan07** [comment]
Node versions used in other projects, NUS-OSS or not, cannot and should not affect the Node version used here. That is an unhealthy and unnecessary coupling.

> may help developers who wish to work on multiple projects

I am sorry to say this, but this is a very short-sighted reasoning. What if, for example, the person wants to work on projects outside NUS-OSS that are still tied down to Node 12 (or tied up to Node 16) for whatever reason?
