### ISSUE TITLE
Student homepage: show courses even if there are no sessions in them

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11765]
v8.14.1, production, problem reported by a user

Context: When a student logs in using the Google account, the homepage shows all the courses the student has joined already.

Current: Courses that don't have any sessions are not shown in this homepage

Suggested: Show even those courses (reason: students can join a course even if there are no sessions in it).

**Comment by wkurniawan07** [comment]
> Courses that don't have any sessions are not shown in this homepage

This is incorrect.

**Comment by samuelfangjw** [comment]
I tried replicating this locally, but it seems to work for me.

<img width="1255" alt="Screen Shot 2022-04-27 at 2 09 49 PM" src="https://user-images.githubusercontent.com/60355570/165452630-ca19a860-29d9-4819-b52f-e5833d469bf1.png">

This is after the student has joined the course using the course join link.

Could this be a case where the user is enrolled in a course but has not joined yet?

**Comment by damithc** [comment]
I was surprised by this too, as I don't remember such a behavior in the past. I thought perhaps it's a recent regression.

When I searched for the student, he seems to have joined three courses but only two courses show up in his home page.
![image](https://user-images.githubusercontent.com/1673303/165456761-96afcbb1-d3ba-4f88-925f-e5001e7d17ea.png)

Upon further checking, the problem is that one of these courses is actually in the recycle bin. So, there is no problem with the student homepage. What we need to do is to tweak the admin search page to identify 'binned' courses. I'll open a separate issue for that.
