### ISSUE TITLE
Give an easy way to extend deadline for non-submitters

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11764]
Current: When an instructor views results of a session, TEAMMATES shows a list of non-submitters at the bottom of that page.
![image](https://user-images.githubusercontent.com/1673303/165130488-9d4dee47-5109-4834-b896-d5dcd2fc7a22.png)

Suggestion: provide an easy way to extend deadlines for the non-submitters.

One possible approach is to provide a button similar to the `Remind All` button shown above, which takes the instructor to a page for adding deadline extensions, with the non-submitters pre-selected.

**Comment by danielsimre** [comment]
Is anyone working on this issue? If not, I would like to work on this issue.
