### ISSUE TITLE
viewing logs: instructor might think 'view' is same as 'submission'

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11770]
v8.14.1, production

Context: We have an unreleased feature accessed through `/instructor/logs`, for instructors to view submission activities of students. Here is an example:
![image](https://user-images.githubusercontent.com/1673303/165888427-bf751b4e-1668-4166-bc4b-771b15f27367.png)

There might a slight usability issue here. An instructor not yet familiar with the feature seeing only 'view' actions in the search results might think _view_ is same as _submit_. This happened to a user that used the feature for the first time.

Suggestion: Not sure what's the best way to improve this. Perhaps show an additional info message in the results page? e.g., `What's the difference between 'Viewed ...' and 'Submitted ...'?`

**Comment by hoanglan21** [comment]
Maybe you can rename it to "In progress"? Showing that the student has not submitted the survey at all

**Comment by damithc** [comment]
> Maybe you can rename it to "In progress"? Showing that the student has not submitted the survey at all

Possibly. Another idea is to show an additional message only if the results contain 'view' actions only.

**Comment by jianhandev** [comment]
How about `Viewed but no response` and `Responses recorded`?
* `Viewed but no response` is clear that student has viewed the feedback session but has yet to submit any responses
* `Responses recorded` does not imply to the instructor that the student is done with the submission but rather an indication that responses are recorded. Personally I feel it is clear enough, but if still unclear to anyone, we can add a note e.g. above the table

**Comment by damithc** [comment]
This page is to be redesigned in #11812 Perhaps we discuss over there? I have a feeling that the dropdown that page will have (to select the activity type) will already indicate to the user that _view_ is different from _submit_.

**Comment by jayasting98** [comment]
> This page is to be redesigned in #11812 Perhaps we discuss over there? I have a feeling that the dropdown that page will have (to select the activity type) will already indicate to the user that _view_ is different from _submit_.

@damithc In that case, should we consider putting #11782 on hold?

**Comment by damithc** [comment]
> @damithc In that case, should we consider putting #11782 on hold?

Yes, let's do that.

**Comment by u7305725** [comment]
Can I try this issue?

**Comment by cedricongjh** [comment]
> This page is to be redesigned in #11812 Perhaps we discuss over there? I have a feeling that the dropdown that page will have (to select the activity type) will already indicate to the user that _view_ is different from _submit_.

closed with https://github.com/TEAMMATES/teammates/pull/12973, the user now has a dropdown that indicates that view is different from submit:
![Uploading image.png…]()
