### ISSUE TITLE
team contribution questions: force submissions to be zero-sum

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11772]
Current: A 'team contribution' questions allow respondents to use any scale. e.g., a respondent can give E, E, E or E, E, E+50%

Problem: While this flexibility is expected to increase the sincerity of submissions (the hypothesis is that a respondent will be more willing to say "I did an equal share, but others did more" than to say "I did less than an equal share") it can cause confusion when students compare their ratings with each other or when marks are given based on the absolute values of ratings received.

Suggestion: When creating this type of question, give the instructor an option to force the submission ratings to add up to `team size x E` (similar to point distribution questions) e.g., if the team size is 4, the ratings should add up to `4 x E` such as `E-10, E+10, E, E`. This option can be selected by default. The instructor can be cautioned not to unselect it if marks are intended to be given based on ratings received.

**Comment by xyliew25** [comment]
Hi @damithc and all, when forcing responses to be zero-sum, how are we dealing with the two options of `CONTRIBUTION_POINT_NOT_SUBMITTED` and `CONTRIBUTION_POINT_NOT_SURE` (when `isNotSureAllowed=true`)? Can these two options be removed (when forcing zero-sum) in this case? Though I'm not sure if the initial intention of these options is to increase sincerity in responses.

**Comment by damithc** [comment]
> Hi @damithc and all, when forcing responses to be zero-sum, how are we dealing with the two options of `CONTRIBUTION_POINT_NOT_SUBMITTED` and `CONTRIBUTION_POINT_NOT_SURE` (when `isNotSureAllowed=true`)? Can these two options be removed (when forcing zero-sum) in this case? Though I'm not sure if the initial intention of these options is to increase sincerity in responses.

Good point @xyliew25 .  Yes, I think we'll have to remove those options.
