### ISSUE TITLE
Help pages need some updates

### ISSUE THREAD

**Issue by fans2619** [TEAMMATES/teammates#11794]
Creating this issue to update the instructor help page, since the changes are not targeting issues #2874 and #8769 (those are about adding questions to the instructor help page). There would be a separate PR for those issues. More details of the updates are posted in the Slack channel.

**Comment by samuelfangjw** [comment]
Hi @fans2619, could you kindly update this issue with more details? It's not really clear to me what issue this is addressing and how this PR differs from the others mentioned.

**Comment by fans2619** [comment]
Hi! The two issues mentioned were about adding questions, and this issue would be about some general update. ☺️https://docs.google.com/document/d/1faKfPs6hshJtDMqpLrW66IeC-KRItZ-ZYL73ic21A0Q/edit?usp=sharing

**Comment by damithc** [comment]
@fans2619 share the GoogleDoc link via slack instead, or post the relevant content here.

**Comment by samuelfangjw** [comment]
@fans2619 This seems like the place to bring up a minor cosmetic issue that's been bugging me for some time. You'll notice as you make changes to the instructor help pages that the symbol used for apostrophe is not standardized, with some using apostrophe `'`(U+0027) and some using left/right single quotation mark `‘/’`(U+2018/U+2019). While the difference is hard to spot, it's hard to "un-see" once you notice it.
Would be nice if you could make a conscious effort to use one or the other when you make your changes!

**Comment by fans2619** [comment]
Sure. Thanks for letting me know this! 😃

**Comment by fans2619** [comment]
@samuelfangjw On a side note, I'm actually planning to update the help pages via several small PRs as prof said it's hard to review big PRs for this kind of changes. So I think it will be good to get review for and merge these PRs more quickly, because I guess it's likely to cause quite some conflicts if I continue working without the previous changes being merged. I'm also okay for any alternative ways to do that!
