### ISSUE TITLE
Instructors adding MCQ questions: give option to show as a drop-down

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11791]
Suggestion: When an instructor is adding an MCQ question to a session, give an option to show the question as a drop-down (rather than radio buttons).

Reason: dropdowns are more suitable when there are many options to choose from (it saves UI space)

Perhaps show the option in this empty space? Or below the 'Other' option?

![image](https://user-images.githubusercontent.com/1673303/168462084-663c7eaa-e137-41c8-a846-cb6fd0cbf7d2.png)

Or here?
![image](https://user-images.githubusercontent.com/1673303/171814660-9f516007-0f6b-4247-9c8b-c223e7149724.png)

Complications: Need to handle the 'Other' option properly

**Comment by parthnatu** [comment]
Two questions:
- Is this the appropriate UI change? :
![image](https://user-images.githubusercontent.com/32033882/169626269-f1816699-da54-4774-81ac-a6ca975cdade.png)

- Is the functionality behind this checkbox to be implemented as well? (i.e. is there a way to have the question show up as a dropdown already in the codebase?)

**Comment by damithc** [comment]
> * Is this the appropriate UI change? 
>   ![image](https://user-images.githubusercontent.com/32033882/169626269-f1816699-da54-4774-81ac-a6ca975cdade.png)

Yes, I think it is acceptable

> * Is the functionality behind this checkbox to be implemented as well? 

Yes. 

> * Does this apply to MSQ questions?

How would that work from the user's point of view (i.e., when responding to such a question)?

**Comment by parthnatu** [comment]
> How would that work from the user's point of view (i.e., when responding to such a question)?

Yes, I can see that this won't apply to MSQ. Will work on this :)

**Comment by parthnatu** [comment]
Could I get some help with setting up the debugging environment? I am not sure how to. Also if there is some documentation about the message flow from the UI to the DB that would be great.

Thank you!

**Comment by ypinhsuan** [comment]
Hi @parthnatu, you can refer to this https://teammates.github.io/teammates/development.html to set up the environment.
The high level architecture design is here: https://teammates.github.io/teammates/design.html

**Comment by domlimm** [comment]
Hello! I have taken a look at this issue and the currently opened PR. Not sure if it's still a work in progress. I'd love to work on this issue if that's okay.

**Comment by damithc** [comment]
@domlimm as that PR has not progressed for a while, feel free to takeover and complete the rest but give credit to that PR author if you reuse the code (reuse is recommended as a plenty of work has been put into that PR already).

**Comment by domlimm** [comment]
@damithc thanks prof! I will work from the PR and definitely on the credit 👍🏻
