### ISSUE TITLE
Warn user before deleting last course in institute

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#11825]
- **Environment**: live server at V8.15.0

**Description of feature/enhancement**

- Warn user if s/he is about to delete his/her last course within an institute, as it will cause him/her to lose status as instructor in the said institute.
- (Optional) warn user if s/he is about to delete his/her last course or all of his/her courses, as s/he will lose access to the system as an instructor.

**Justification**

It is a design that an instructor can only add new courses in an institute whereby s/he is already a course co-owner. However, users are not expected to be aware of this detail, and they will expect some form of warning if they are about to lose some form of access.

**Comment by charucjoshi** [comment]
I would like to contribute. This is my first time contributing so can you tell me what I have to do?

**Comment by JOSHI-owo** [comment]
@wkurniawan07 I would like to work on this issue.

**Comment by NicolasCwy** [comment]
@charucjoshi Are you still interested in this issue? A good first place to start is to checkout our [contribution guide](https://teammates.github.io/teammates/contributing-doc.html) and setup the project on your computer,  if you have any issues, feel free to create an issue for someone to assist you. Then you can check out `src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html` and see if you can implement something outlined above

@JOSHI-owo Lets see if the other contributor would still like to work on it, in the meantime you could find another issue or check back in a few days

**Comment by inifnite** [comment]
@NicolasCwy I would like to work on this issue. First time contributing.

**Comment by inifnite** [comment]
@NicolasCwy I have implemented the said functionality on my local machine and its working fine. How do I proceed further?

**Comment by inifnite** [comment]
@NicolasCwy I have gone through the code flow and I think I will be able to resolve the issue. Just need few clarifications regarding the implementation.

**Comment by NicolasCwy** [comment]
@inifnite Feel free to clarify in this thread

**Comment by thikhinab** [comment]
@NicolasCwy Hi! I am interested to work on this issue. May I know if the issue is taken up by someone?

**Comment by inifnite** [comment]
@NicolasCwy  I have actually finished the coding part, just want to know one thing. Are we supposed to show this warning when course is deleted from the bin or soft delete(moving course to bin) also counts?

**Comment by damithc** [comment]
> @NicolasCwy I am doing the coding part, just want to know one thing. Are we supposed to show this warning when course is deleted from the bin or soft delete(moving course to bin) also counts?

Not a direct answer but I guess this depends on which of the two causes the user to lose access?
