### ISSUE TITLE
User documentation: don't use bold to refer to UI text

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11830]
Current: the user documentation uses **bold text** to refer to text in the UI. e.g.,
![image](https://user-images.githubusercontent.com/1673303/170869317-4dbb3a21-273c-4896-a2f0-8cc95e452370.png)

Suggestion: Use a different style to differentiate UI text from the rest e.g., `this style`

Reason: Bold is normally used to make the text stand out by adding more visual weight e.g., to indicate more important parts of the text. By using it for the above purpose, we lose the opportunity to emphasize important parts of the user documentation using bold formatting.

What do others think?

**Comment by tau-bar** [comment]
Hi prof @damithc , I'd like to work on this issue. If we were to change it to use `<code>` tags instead of `<b>`, then it would look like this:

![image](https://user-images.githubusercontent.com/61085398/188300019-5a00f24b-0d3c-41cf-aea5-eaa4793b1a3e.png)

If that's alright then I'll proceed on changing the user documentation.

**Comment by damithc** [comment]
> Hi prof @damithc , I'd like to work on this issue. If we were to change it to use `<code>` tags instead of `<b>`, then it would look like this:
> 
> ![image](https://user-images.githubusercontent.com/61085398/188300019-5a00f24b-0d3c-41cf-aea5-eaa4793b1a3e.png)
> 
> If that's alright then I'll proceed on changing the user documentation.

@tau-bar I'm OK with this formatting. But perhaps we leave this to a first-timer?

**Comment by John-Poulos** [comment]
I would like to work on this, can you assign this to me? Thank you in advance.

**Comment by zhaojj2209** [comment]
@John-Poulos Sure, feel free to make a PR for this issue!

**Comment by John-Poulos** [comment]
> @John-Poulos Sure, feel free to make a PR for this issue!

@zhaojj2209  - Excellent, thank you! 
I had a question about the dev. guidelines at https://teammates.github.io/teammates/development.html; Will I need to pass all the white box tests to work on this particular problem? I pass 1259, fail 191 and have 691 skipped when I ran this last night. I am able to open the project in IntelliJ.
After making changes to the project locally, what is best practice to test these changes? 
Thanks in advance.

**Comment by zhaojj2209** [comment]
@John-Poulos This issue mostly concerns the frontend user documentation; after making the changes, I recommend the following:

- Start the frontend server on your local machine and verify manually that all parts of the documentation that should be changed have been changed
- Ensure frontend linting checks pass (`npm run lint`)
- Ensure frontend tests pass (`npm run test`)

Once you make a PR, there will be automated checks on GitHub to verify that all linting checks/tests are passing as well.

**Comment by John-Poulos** [comment]
@damithc @zhaojj2209  Can I propose to use the <mark> </mark> html tag to give the word a soft background highlight without bolding the word? Is there another method you would prefer?

Using <code> </code> will cause problems with the text in between not being able to be translated when using Google translate, which I assume is important in a project like this.
Thank you again.

**Comment by damithc** [comment]
> @damithc @zhaojj2209 Can I propose to use the html tag to give the word a soft background highlight without bolding the word? Is there another method you would prefer?
> 
> Using ` ` will cause problems with the text in between not being able to be translated when using Google translate, which I assume is important in a project like this. Thank you again.

@John-Poulos Good point. I'm fine with an alternative formatting if using the `<code>` tag gets in the way of accessibility features.

**Comment by John-Poulos** [comment]
Great! I will proceed. Thank you for the quick feedback. Is there a preferred way of doing the many lines of changes or is it simply done one by one?

**Comment by prafullpandey614** [comment]
Can I contribute to this issue still ?
Is it Open yet ?
I am a first timer and I would like to contribute here

**Comment by fsgmhoward** [comment]
@prafullpandey614 Hi thanks for your will to contribute. However, there is already an opened PR (#11954) associated with this issue. It will be entering review phases. You may work on it if the PR gets rejected (although very rarely).

**Comment by u7305725** [comment]
Hi, we are doing a group assignment, can i try on this issue, i may suggest a better one than current pull request by using css
![image](https://user-images.githubusercontent.com/110862712/196304408-72487de2-6ee0-4400-9817-775f67f2e4e4.png)
The "Home" and "Enroll" is my work, the "mark" is what in current pull request

**Comment by u7305725** [comment]
Hi, we are doing a group assignment, can i try on this issue, i may suggest a better one than current pull request by using css
![image](https://user-images.githubusercontent.com/110862712/196304794-b1202c03-4497-4b3c-aa1c-8914df20dadd.png)

The "Home" and "Enroll" is my work, the "mark" is what in current pull request

**Comment by u7305725** [comment]
Hi, we are doing a group assignment, can i try on this issue, i may suggest a better one than current pull request by using css
image

The "Home" and "Enroll" is my work, the "Courses" is what in current pull request

![image](https://user-images.githubusercontent.com/110862712/196305397-170c7227-acc4-4653-8f49-0ea98d621780.png)

**Comment by damithc** [comment]
> Hi, we are doing a group assignment, can i try on this issue, i may suggest a better one than current pull request by using css image
> 
> The "Home" and "Enroll" is my work, the "Courses" is what in current pull request
> 
> ![image](https://user-images.githubusercontent.com/110862712/196305397-170c7227-acc4-4653-8f49-0ea98d621780.png)

@u7305725 we want to differentiate such text but not make them stand out more than the regular text (not too much anyway). So, probably best not to use red for text.

**Comment by u7305725** [comment]
@damithc 
I see, how about this one? i used the css, the background color is #E6E9E9 and text color is #908B8B.
Again, "home" and "Enroll" are my work, "Courses" is in current pull request done by somebody else
![image](https://user-images.githubusercontent.com/110862712/196342376-644957c8-f3b3-4b57-9186-bf18f62935b8.png)

**Comment by damithc** [comment]
> I see, how about this one? i used the css, the background color is #E6E9E9 and text color is #908B8B.
> Again, "home" and "Enroll" are my work, "Courses" is in current pull request done by somebody else
> ![image](https://user-images.githubusercontent.com/110862712/196342376-644957c8-f3b3-4b57-9186-bf18f62935b8.png)

@u7305725 This one is better. Perhaps not use rounded edges as this could give the wrong impression that we are referring to a button.

**Comment by u7305725** [comment]
Sure, i changed it to square border now. If you are satisfied with this style, i will do the change to all css file under instructor-help-page directory
![image](https://user-images.githubusercontent.com/110862712/196345965-db4cb02a-c004-4ca8-96e5-7727affb788a.png)
![image](https://user-images.githubusercontent.com/110862712/196346084-fb120e78-9768-47c6-8c7d-860707980da5.png)
![image](https://user-images.githubusercontent.com/110862712/196346119-c31febdd-86e5-4903-8352-e5ee36c493a0.png)

**Comment by damithc** [comment]
> ![image](https://user-images.githubusercontent.com/110862712/196345965-db4cb02a-c004-4ca8-96e5-7727affb788a.png)

@u7305725 I'm OK with the appearance of this version.

**Comment by u7305725** [comment]
Thanks for approve, I will work on this issue and do a pull request in three days

**Comment by u7305725** [comment]
Hi, i do a [pull request](https://github.com/TEAMMATES/teammates/pull/11975), please take a look at. This may help the project if it is accepted. If not, hope this will help other developers

**Comment by John-Poulos** [comment]
You may want to use a different naming convention for your tag than <b>. Custom html tags include a hypen, so perhaps something like <TM-SlightEmphasis> or something similar. Nice work, you beat me to it :-)

**Comment by u7305725** [comment]
> 

@John-Poulos Sorry, I suppose you want to type tags but these tags are used and hidden by the comments. Maybe something like “b” tag?

**Comment by u7305725** [comment]
> You may want to use a different naming convention for your tag than . Custom html tags include a hypen, so perhaps something like or something similar. Nice work, you beat me to it :-)

Btw thanks for your praise, are you still working on this issue? Can you let me do this? This is first time I do the issue
