### ISSUE TITLE
Add scheduled post-processing step for student activity logs

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#11843]
**Problem statement**

For the student activity logs feature, each usage makes a call to Cloud Logging, which has QPS restriction as well as not-low latency. (a search space of 30 days can take 3-4 mins)

Such implementation is not suitable for a user-facing production feature:
- 3-4 mins latency without any kind of indicator is outright bad UX.
- The QPS restriction is going to haunt us in the future, if not right after the feature is released.
- In addition, Cloud Logging has a (default) bucket lifetime of 30 days.

**Solution**

The general idea is that we need to move the log entities to DB, while at the same time not directly writing to DB as:
- The transaction volume could be high, or at least higher than needed.
- We may not need to record every single activity, i.e. if there is someone who keeps refreshing the submission page, it is a waste to record (and also to display) every single so-called "page visit".

What we need to do is to regularly (e.g. one hour or 30-minute interval) process the logs and inserting the processed data to the DB as needed, similar to how the usage statistics are recorded. Afterwards, users can simply fetch data from the DB, which will be much faster or at least having trackable progress, no QPS restriction, and no expiry date.

**Comment by daongochieu2810** [comment]
@wkurniawan07 how do I run the cron job locally? or is it only possible on the staging server?

**Comment by daongochieu2810** [comment]
@wkurniawan07 @damithc 

Design proposal:
1. Create FeedbackSessionLogEntryAttributes class and transform the current FeedbackSessionLogEntry to a datastore entity
2. Create FeedbackSessionLogEntriesDb and FeedbackSessionLogEntriesLogic. The logic class will expose the method `getFeedbackSessionLogs(courseId, studentEmail, fsName, startTime, endTime)`, studentEmail and fsName can be null and will not be added to the filters if null
3. Create the cron job FeedbackSessionLogUpdateAction that runs every hour. This action will get the logs from gcloud logging service `logsProcessor.getFeedbackSessionLogs(courseId, studentEmail, fsName, startTime, endTime)` with courseId, studentEmail and fsName as null values, startTime as the last log timestamp (retrieved by taking the largest timestamp from logs in the datastore) and the endTime as Instant.MAX. The retrieved logs will be added to the datastore
4. CreateFeedbackSessionLogsAction will still write to a logging service, GetFeedbackSessionLogsAction now get the logs from the datastore instead, with QPS restriction removed
5. To prevent user spam, the minimum time difference between logs from the same user is 2s. Student entity now has a new field `lastLogTimestamp` and this is updated with every log creation event

**Comment by damithc** [comment]
> 5\. To prevent user spam, the minimum time difference between logs from the same user is 2s. Student entity now has a new field `lastLogTimestamp` and this is updated with every log creation event

Should we also factor in the activity itself i.e., differentiate between 'same activity within 2s' vs 'different activities within 2s'

**Comment by wkurniawan07** [comment]
(5) isn't a really good way; we're trading off the so-called spam-filter with increased DB reads/writes. An alternative is to filter out the so-called spams when the logs are ingested/processed.

**Comment by wkurniawan07** [comment]
Also, hourly cron job may be too sparse. Consider 10-min or 15-min interval instead.

**Comment by daongochieu2810** [comment]
> (5) isn't a really good way; we're trading off the so-called spam-filter with increased DB reads/writes. An alternative is to filter out the so-called spams when the logs are ingested/processed.

@wkurniawan07 do you mean that we let all logs go to the logging service, but only filter the logs when they are about to be inserted into the datastore?

**Comment by wkurniawan07** [comment]
> only filter the logs when they are about to be inserted into the datastore?

Yes. It's far simpler that way for the same goal.

Also, on point 3:

> startTime as the last log timestamp (retrieved by taking the largest timestamp from logs in the datastore) and the endTime as Instant.MAX

There's no need to complicate things; for each cron job it should simply the latest 10- or 15- min interval, e.g. if a cron job is run at 10.01pm and the interval setting is 10-min, the logs obtained should be from 9.50-10.00pm.

**Comment by daongochieu2810** [comment]
@wkurniawan07 how do I get the last time that the cron job was run?

**Comment by wkurniawan07** [comment]
`Instant.now()`?

**Comment by daongochieu2810** [comment]
ok thanks :))) another issue about the tests. So currently the logs are available immediately after creation, but its not the case with the new solution. I was thinking of triggering the cron job manually after creating the logs and this works for unit tests, but not sure how that is possible in e2e tests

**Comment by wkurniawan07** [comment]
You can just upload predefined data to the DB. There's no need to have an actual view/submission action as we don't really operate cross-page E2E tests. But if you really want to trigger the cron job manually, you can also do that. Cron job is merely an API endpoint.
