### ISSUE TITLE
README.md and other documentation updates

### ISSUE THREAD

**Issue by VirginiaLink** [TEAMMATES/teammates#11851]
README.md and other documentation updates

**Description of feature/enhancement**
The TEAMMATES readme could benefit from better organization and more links to already existing resources within the repository.

**Justification**
These updates would make it easier for all users (student, teachers, and developers) to navigate the repository.

**Comment by samuelfangjw** [comment]
> These updates would make it easier for all users (student, teachers, and developers)

Students and instructors should access the help pages within the TEAMMATES product website. Developers can access the dev docs at https://teammates.github.io/teammates. Both of these resources are adequately linked from the project README.

Closing this issue as not in scope.
