### ISSUE TITLE
Instructor viewing results: 'Other teams in the same section' path is causing timeout

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11858]
Reported by a user
V8.16.1

A user reported (and I verified) that the results for questions having a certain feedback path is not loading, causing a timeout in the end.

![image](https://user-images.githubusercontent.com/1673303/172996645-4b01aee1-7ea2-4b83-b977-59f7ec71d099.png)

Q1 (rubric) and Q2 (essay) have this path and are not loading. 
![image](https://user-images.githubusercontent.com/1673303/172996525-938203dd-a857-41d0-8978-d84e1411cbdc.png)

Q2 (rubric) has a different path (given below) and is loading.

![image](https://user-images.githubusercontent.com/1673303/172996828-91ba1798-4be5-4329-93ab-2d2d752ae8b1.png)

Perhaps `Other teams in the same section` (a rarely used path) is buggy?

PS: the error message in the log
>Error Message: DeadlineExceededException caught by WebApiServlet
caused by teammates.common.exception.DeadlineExceededException: null
at teammates.common.util.RequestTracer.checkRemainingTime(RequestTracer.java:59)
at teammates.logic.core.FeedbackResponsesLogic.buildResultsBundle(FeedbackResponsesLogic.java:437)
at teammates.logic.core.FeedbackResponsesLogic.getSessionResultsForCourse(FeedbackResponsesLogic.java:479)
at teammates.logic.api.Logic.getSessionResultsForCourse(Logic.java:1262)
at teammates.ui.webapi.GetSessionResultsAction.execute(GetSessionResultsAction.java:76)
at teammates.ui.webapi.GetSessionResultsAction.execute(GetSessionResultsAction.java:15)
at teammates.ui.servlets.WebApiServlet.invokeServlet(WebApiServlet.java:65)
at teammates.ui.servlets.WebApiServlet.doGet(WebApiServlet.java:38)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

**Comment by damithc** [comment]
@xyliew25 can you check if this problem is reproducible?

**Comment by xyliew25** [comment]
@damithc I am unable to reproduce this problem.

For both development and production servers, I created a feedback session where results are published immediately after responses are submitted, and the session contains the above questions with the corresponding feedback path settings. I then submitted responses to the questions, and I am able to view the responses on the session results page.

Were you able to reproduce the problem?

**Comment by damithc** [comment]
The user says she moves some students between sections while the session was ongoing, in case that matters.

**Comment by damithc** [comment]
I couldn't replicate the problem on my own either, although I can verify the user is still facing the problem. It could be that the problem is linked to the user's data. Perhaps we can add some extra log messages for troubleshooting purposes?

Raising severity as we need to fix this problem soon or else the user is unable to access the session results.

**Comment by damithc** [comment]
An update: 
I tried adding a dummy session to the user's course containing one question with this specific feedback path. It still fails. So, the problem is not related to responses already received (as the dummy session didn't have any responses). So, it might be due to the team structure of the course. 
I noticed that some of the teams are unusually large, possibly causing a performance issue.
I've attached an anonymized version of the student list. 
Strangely, I could not replicate the error using this student list but it came close (the results loaded after a very long wait).

[teammates_student_list_anonymized.csv](https://github.com/TEAMMATES/teammates/files/8883471/teammates_student_list_anonymized.csv)

**Comment by damithc** [comment]
The problem goes away if I change the path as follows -- so it is very specific to `Other teams in the same section` option, possibly some inefficiency in the logic that narrows down the responses to the same section

 ![image](https://user-images.githubusercontent.com/1673303/173179105-429625a0-a489-4f90-a109-f8f39f13758c.png)

**Comment by xyliew25** [comment]
@damithc I see, thank you for the extra information! Will look into the possible causes of the inefficiency.

**Comment by xyliew25** [comment]
A small update: I am able to replicate the different loading times between the different feedback paths **with and without the provided student list**. With the small dummy student list that I created, the difference in loading times is, of course, less obvious, but logging the `GET` requests sent from the front end to `ResourceEndpoints.RESULT` makes the difference more noticeable.

**Comment by xyliew25** [comment]
Update: I believe the source of inefficiency is the building of missing responses. Inconsistently, a query to the database is made for the case of `Other teams in the same section`, unlike the case of `Other teams in the course` where the course roster is utilized. Hence, the proposed fix is just to utilize the course roster.

**Comment by xyliew25** [comment]
Alternatively, we can choose not to build missing responses entirely, as per the case of `Other teams in the course`, by adding to the recipient type list in the `shouldGenerateMissingResponses()` method in `FeedbackQuestionDetails.java`. 

However, I think the former fix is more ideal as the business logic is retained.

**Comment by wkurniawan07** [comment]
> we can choose not to build missing responses entirely, as per the case of `Other teams in the course`, by adding to the recipient type list in the `shouldGenerateMissingResponses()` method in `FeedbackQuestionDetails.java`.

Unlike the options that are excluded when building missing responses, "Other teams in the same section" (and also "Other students in the same section") are already upper-bounded by the max. number of students in the section.

**Comment by damithc** [comment]
An update:  The user reported the she was able to view/download the results after deleting some of the students in the course. She deleted students who are not actually taking part in the current session and hence not yet put into proper teams (instead, they were in dummy teams with up to 30 members, resulting in 'unusually' large teams). This increases the chance that this was a performance issue all along.
