### ISSUE TITLE
Submitting responses to team contribution questions

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11868]
v8.17

Context: I noticed that quite a few times respondents chose `Equal share + 100%` option for everyone in the team. This is same as saying everyone did as twice as expected -- most likely the intention was to say everyone did an equal share. Although this does not matter (choosing `Equal share +100%` has the same impact in the final result as choosing `Equal share` for everyone, due to internal normalization done by TEAMMATES), it's better if users are prevented from making this mistake.

Problem: I wonder if the appearance of the dropdown (shown below) is a contributory factor to this user error:
![image](https://user-images.githubusercontent.com/1673303/174469998-b2b77088-044d-4626-a049-7dd5047e792a.png)

Some tweaks we can consider:

1. Repeat `Equal share` at the top of the scale too, as that is the most likely choice.
2. Show `Equal share` in green, and possibly in bold 
3. Remove the `Equal share + 100%` option. If the scale went up to +95 only, users will not be able to make this mistake. However, this change will have backward compatibility implications.
4. Rephrase options as `X% more than an equal share` and `X% less than an equal share`

Other ideas?

**Comment by sivayogasubramanian** [comment]
@damithc Would a slider be better here?

![image](https://user-images.githubusercontent.com/53614454/174847441-8b75f3f1-2c8e-447c-b3a8-5ced24428495.png)

![image](https://user-images.githubusercontent.com/53614454/174847499-1c335e28-dfff-449b-b917-8bc641d9c546.png)

![image](https://user-images.githubusercontent.com/53614454/174847535-2ea0a6e8-19eb-4275-9f11-52e74154ff10.png)

**Comment by damithc** [comment]
> @damithc Would a slider be better here?

hmm... the drop-down is safer (e.g., compatibility with browsers/devices, accessibility benchmarks) and easier (e.g., easier to test) but I will not veto a slider if others think it can do a better job.
