### ISSUE TITLE
Add to instructor help: 'Can I use a different team structure for different sessions?'

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11865]
Suggestion: Add the following to the instructor help page

Question: Can I use a different team structure for different sessions in the same course?
Answer:
Currently it is not possible. If you change the team structure midway, the new team structure will apply to all current/past sessions as well, and will cause any 'incompatible' responses (e.g., responses submitted in relation to a team that no longer exists) to be deleted automatically.
Workarounds (neither is optimal, unfortunately):
Alternative 1: Create a different course for each team structure you want to support.
Alternative 2: Keep changing the team structure as necessary but download the existing responses before changing it -- this works only if it is not important for students to be able to view responses to past sessions.

Probably fits this section:

![image](https://user-images.githubusercontent.com/1673303/173748992-f9fd0a11-493b-4e3f-ab71-124eae934761.png)

**Comment by Richey24** [comment]
if anyone isn't assigned to this, i will like to handle it

**Comment by ypinhsuan** [comment]
Hi @Richey24 please go ahead!

**Comment by Richey24** [comment]
OK, on it
