### ISSUE TITLE
Submitting responses: some users are not sure if the submission went through

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11869]
v8.17

Context: After a user submits responses to a session, we show a success message (with an option to download a proof-of-submission) file. Despite this, based on user queries received, some are still not sure if their submission went through 'properly'. It seems their doubt is because the page stays in edit mode, exactly the same way it was before they clicked the submit button.

![image](https://user-images.githubusercontent.com/1673303/174473580-1410d524-6b2d-41b7-98fc-cd6d0362483b.png)

The reason we stay in the same page in edit mode is because it makes further edits to the submission easier. 

Is there anything we can tweak the UX to eliminate this doubt, without losing the ease of further edits? Ideas welcome.

**Comment by thikhinab** [comment]
@damithc Would having an alert for each of the question be helpful?
![image](https://user-images.githubusercontent.com/59680441/174992841-66f29aa6-06fd-44df-bfc5-548f18a603ce.png)

**Comment by damithc** [comment]
> @damithc Would having an alert for each of the question be helpful?
> ![image](https://user-images.githubusercontent.com/59680441/174992841-66f29aa6-06fd-44df-bfc5-548f18a603ce.png)

Thanks for looking into this @thikhinab Not sure about this will help enough. It's the 'page stays in edit mode'  that seem to confuse some users. They expect to navigate to a different page upon successful submission.

**Comment by damithc** [comment]
> @damithc we need to play devil's advocate here. We can't please every single user. Do we want to prioritize "easier edit after submission" or "go to other page but (hopefully) success is more guaranteed"? They're straight out conflicting requirements.

As of now, we have prioritized ease of editing, which is probably the right thing. So, I'm fine to keep the status quo. But if we _can_ achieve both goals, that would be a bonus. For example, something along this line: Rather than actually navigating to another page, we simply hide the form and replace it with a `All done!` message together with another link/button `Edit answers further`. If the user clicks the button, we hide the message and make the form visible again. To the user it looks like we navigated to a new page, but we are actually in the same page. I'm not sure that kind of client-side acrobatics is feasible and worth the added complexity though. To be weighed against the benefit of avoiding redundant repeated submission attempts (to ensure it went through) and avoiding related support requests.

**Comment by sivayogasubramanian** [comment]
@damithc

Should I try to make the frontend changes and see how it goes?

After the PR is up, we can discuss if we want to merge it.

**Comment by domlimm** [comment]
Hello, may I ask if anyone is attempting to make the frontend changes? If not, I could possibly try it!

**Comment by sivayogasubramanian** [comment]
@domlimm Go ahead. I am not working on this right now.

**Comment by domlimm** [comment]
@sivayogasubramanian Alright, thanks Siva!

Also, updated my reply to clarify on some things. If you could please have a look! 🙇🏻

**Comment by sivayogasubramanian** [comment]
@damithc @domlimm I think the proposed solution by @thikhinab is good in my opinion. We can have two types of messages, "Awaiting your response" and "You previously submitted a response. You can submit again if you wish", or something along those lines.

This keeps the webpage in edit mode and allows the user to see some visual confirmation of the submission status if they are unsure.

> we simply hide the form and replace it with an "All done!" message together with another link/button Edit answers further.

The alternative that is mentioned here is very disruptive for the user.

**Comment by domlimm** [comment]
@sivayogasubramanian I agree with you on @thikhinab's proposed solution. Think it's the cleaner approach for now. I guess we could see how it goes! For a start, i'll attempt with the former one.

**Comment by sivayogasubramanian** [comment]
> For a start, i'll attempt with the former one.

Let's wait for Prof's input as the alternative was suggested by him.

**Comment by domlimm** [comment]
Okay, no problem! Won't start so soon. 👍🏻

**Comment by damithc** [comment]
We already show this to the user 
![image](https://user-images.githubusercontent.com/1673303/184480007-6ba774d5-5a2e-4e6c-98b5-6f99e13708c0.png)

Showing similar messages in each question _might_ help a bit (while adding more verbosity) but the issue here is that the form stays in edit mode which is different from the normal form submission behavior. So, as long as the we retain that behavior, some users will be confused about it. 

Nevertheless, we can try this approach but perhaps in a more subtle way e.g., use green color for questions already saved. What do you think?
![image](https://user-images.githubusercontent.com/1673303/184480381-10118c2a-c23a-4933-8ae6-b61146b6c8b3.png)


> > we simply hide the form and replace it with an "All done!" message together with another link/button Edit answers further.
> 
> The alternative that is mentioned here is very disruptive for the user.

yes, this won't work when saving one question at a time. I was thinking of the full form submission here.

**Comment by domlimm** [comment]
@damithc works for me prof! Agree on a subtle indication to the user that a question's already saved. In my opinion, this is a great way of showing!

As for this below, maybe could see if we need it.
> yes, this won't work when saving one question at a time. I was thinking of the full form submission here.

Will add your suggestion probably tomorrow 👍🏻 and ping back here when it's done.

Thank you both, prof and Siva! 🙂

**Comment by damithc** [comment]
> Hello prof, may I ask if the green background for the header & tick for each question will persistent (i.e. If user comes back another time to edit his/her submission, it will be green) OR it's only temporarily shown (i.e. Once the page refreshes, it's back to blue and the tick is not shown)?

I think it should be persistent. Other suggestions welcome.

**Comment by sivayogasubramanian** [comment]
> I think it should be persistent. Other suggestions welcome.

Same.

**Comment by domlimm** [comment]
Thank you both! Will work on it 👍🏻

**Comment by domlimm** [comment]
Hello, sorry this took awhile.

I would like to confirm on the behaviour regarding the persistency for the proposed suggestion on adding a Success header and a tick when a user submits his/her response for a question.

E.g., There are 3 questions. The user submits responses for Q1 and Q2 but leaves Q3 unsubmitted.

When user returns, Q1 and Q2 should have a Success header and a tick indicating that these questions' responses have been saved and submitted? This would mean creating another field to save into the database i.e., Adding an `isSaved` attribute to each `questionSubmissionFormModel: QuestionSubmissionFormModel`, more info on the line of code [here](https://github.com/TEAMMATES/teammates/blob/master/src/web/app/pages-session/session-submission-page/session-submission-page.component.ts#L689), as we need to persist the state.

Thanks prof and Siva!

**Comment by damithc** [comment]
@domlimm persistent doesn't mean saving it as a separate field in the database. The front end should be able to determine which answers were loaded from the database (and hence, already 'saved'). e.g.,
* Not answered, or edited since the last save: blue
* Loaded the saved answer, or saved after the last edit: green

What do you think?

**Comment by domlimm** [comment]
@damithc Ah! I see prof. Yes this clarifies, thank you so much! Will get it out by this weekend. 👍🏻
