### ISSUE TITLE
Instructor enrolling students: 'scroll down' link broken

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11861]
v8.16.1

Steps:
1.  Login as an instructor
2.  go to the page to enroll students into a course.
3. click on the following link

![image](https://user-images.githubusercontent.com/1673303/173177489-20fd2770-eaae-4af3-803e-252c2b0681de.png)

problem: Nothing happens
expected: Should scroll to the info referred to in the text. 

However, there is no such info in the page. Not sure if the removal of that info was intended in which case the link should (the entire sentence) should be removed. Otherwise the missing info need to be added back.

**Comment by sivayogasubramanian** [comment]
@damithc I investigated this and it works as expected. 

https://user-images.githubusercontent.com/53614454/175062098-fa54367c-158e-4401-a2e7-4f364a7be9ff.mp4

Is this some edge case? And may I know the steps to reproduce this?

**Comment by damithc** [comment]
Yes, it seems to be an edge case. To reproduce, enroll some students first. In the next page load (showing the result of the previous enrolling), the instructions are missing.

![image](https://user-images.githubusercontent.com/1673303/175075408-98c398de-e458-4f2e-be9c-cfa028242400.png)
