### ISSUE TITLE
Account Request Form Upgrade

### ISSUE THREAD

**Issue by fans2619** [TEAMMATES/teammates#11878]
This issue keeps track of PRs relating to the account request form upgrade. More info can be found on the wiki at https://github.com/TEAMMATES/teammates/wiki/Account-Request-Form-Upgrade.

**Comment by fans2619** [comment]
@damithc Good night! I just want to check a few more about the account request form. When you are adding an instructor currently, I guess you only fill in the three fields for every instructor: name, email, institution. So I wonder how you use other information provided: country, home page URL, comments/queries. Are these three for viewing only and won't be edited or stored currently?

**Comment by damithc** [comment]
> @damithc Good night! I just want to check a few more about the account request form. When you are adding an instructor currently, I guess you only fill in the three fields for every instructor: name, email, institution. So I wonder how you use other information provided: country, home page URL, comments/queries. Are these three for viewing only and won't be edited or stored currently?

@fans2619  I use `name | email | institution, country`

url and comments/queries are used to decide if the request from a legit instructor i.e., you need to display those two to me.

**Comment by fans2619** [comment]
> I use `name | email | institution, country`

I see. The `institution, country` seems a little troublesome to deal with. Personally I think you won't need to edit the `country` field in any way but only the `country` part in the `institution`. So I tend to show `country` again in the pop-up (not editable) and the `institution` shown can be `institution, country` (editable). By the way, I just came up with another question: probably we want to keep all the info submitted by a user before it's edited, e.g., original name & edited name.

> url and comments/queries are used to decide if the request from a legit instructor i.e., you need to display those two to me.

So url and comments/queries will definitely be shown in a separate pop-up due to space limitation.

**Comment by fans2619** [comment]
> Need both to be editable, if the data is collected as free text. One obvious reason is to fix typos.

Okay I think of a way. So I'll provide institution and country separately and a non-editable result showing the combination of the two (`institution, country`). The result will be updated automatically after you edit either institution or country, and will be used as the final institution.

> Currently, I don't keep the original data (but perhaps the GSheets does that anyway). I'm not sure if it is worth keeping the original data (I can't think of any use).

Yup I can't think of any use either but it's just my personal habit to keep a copy of everything. I don't think it would take too much space in the database, but I'm very fine with not keeping them also, which apparently is easier to implement.

> That makes my life harder. Figure out a way to show everything without needing further clicks. The current UI can be changed as necessary. It is not very editing-friendly anyway, as you can see below (it's hard to edit when you can see only the first 10 characters of the text): ![image](https://user-images.githubusercontent.com/1673303/176457183-ba04bce9-5704-4bf8-949c-a7d5fd19539c.png)

I can show **each account request** to look like something below, but this will make the home page very long. So to shorten it, it may be possible to collapse requests, if you are okay with?
![image](https://user-images.githubusercontent.com/68739475/176463835-388b8237-bbf3-44f5-bfed-b9853a38d7e6.png)
![image](https://user-images.githubusercontent.com/68739475/176464550-504e32f7-4c22-4359-be63-30ffa852b131.png)

By the way, I just realised something. If we do not use the Google sheet, you probably won't be able to view a past request any more. It doesn't seem to be feasible to fetch and display all the requests every time when the page is loaded. So do you have any way to quickly locate a past request, either through Search or Log, or you seldom search for a past request? Myself is having some trouble with the search function, maybe caused by my setup.

**Comment by fans2619** [comment]
@damithc How does this look like?
![image](https://user-images.githubusercontent.com/68739475/177144394-905a2a0b-2c7d-4546-ad6c-aa9eca31d184.png)

**Comment by damithc** [comment]
> @damithc How does this look like? It's a simple mockup.
> ![image](https://user-images.githubusercontent.com/68739475/177144394-905a2a0b-2c7d-4546-ad6c-aa9eca31d184.png)

Use more realistic data e.g., the actual name/institute is likely a lot longer.

Is this the search results view or account creation page view?

**Comment by fans2619** [comment]
This is the search results.

**Comment by fans2619** [comment]
This mockup was created manually instead of using `html`. I think the focus here should be on whether the `Status` and `Options` are fine.

**Comment by fans2619** [comment]
> What's the purpose of 'Expand/Collapse All' buttons?

An existing feature. I don't think it's useful though.

> What does 'Reset Account Request' mean?

An existing feature again, but let me check it out, because it just came to my mind that instead of providing everything in the search results, probably a "Reset" button is enough to set the status back to "Submitted" so you can process it again on the home page.

> What does 'Registered' mean? Account created? If so, use 'Created' instead, so as not to confuse it with instructor joining TEAMMATES.

The term "Registered" is reused from the current (there is a "Registered At" datetime). And "Registered" means an account (not account request) is created. "Created" is referring to when the account request is created (i.e., when instructor submits the request form). Personally I want to change "Created At" to "Submitted At". However, I think this change can be done last, to reduce the complexity of the data migration. For "Registered", I don't have much opinion on it though.

**Comment by fans2619** [comment]
> 1. We might need 'Resend' button here, in case the email doesn't go through for some reason.

I think having a 'Reset' button will also be able to cover this, right? You can approve it again after reset. By the way, the join link is actually displayed in the panel. It can always be manually copied and sent. (It's called "Account Registration Link" now.)

![image](https://user-images.githubusercontent.com/68739475/177162922-dbdd5d15-2187-4708-94a6-3fa95c99d288.png)


> 2. The Submitted/Rejected/... etc. labels can use different color text (or some other styling) to easily differentiate between them.

Sure. That can be done last.

**Comment by damithc** [comment]
> > 1. We might need 'Resend' button here, in case the email doesn't go through for some reason.
> 
> I think having a 'Reset' button will also be able to cover this, right? You can approve it again after reset. By the way, the join link is actually displayed in the panel. It can always be manually copied and sent. (It's called "Account Registration Link" now.)

Yes, that works.

**Comment by fans2619** [comment]
> Let's keep it as 'Registered'.

Okay!

**Comment by fans2619** [comment]
@damithc You may know that there's no `country` field in the database currently since you always put the country inside `institute`. As a result, if we want to store institute and country separately, the way of **ID generation** for an account request needs to be changed. I have actually kind of achieved this separation already, but the solution is very complicated, and it may cause undesired consequence, although it's unlikely if you have been using `institute, country` all the time before. The solution is complicated as it requires all the places of identifying an account request to use 3 parameters (email, institute, country) instead of the original 2 parameters (email, institute). This also includes that a new field `country` needs to be created to the accountrequest core in the Solr search server. So even though this can be achieved, I would still recommend storing institute and country together directly. This means once users submit the form, the two fields will be combined and stored in the database and later on, you will be editing this "final institute" instead of editing both institute and country. For your referece, we store the institute and country submitted by users as well but there's no need for them to be editable.

**Comment by fans2619** [comment]
But this can be equivalent to that you edit the institute and country, and we have a combined institute with country stored in the database. I think I'll use this instead. So in the end, the combined still should be stored, in order to make the implementation easier.

**Comment by damithc** [comment]
@fans2619 I'm fine as long as I can edit both of them _after_ the user has submitted them, when I'm using the admin UI to accept/reject account requests. They don't even have to be presented to me as two separate fields. It is fine if you want to store them a a single field in the database. Does that clear your doubt?

**Comment by fans2619** [comment]
Yup thanks prof!

**Comment by damithc** [comment]
> @damithc I will store them as a single field and throw away the original data submitted. You'll see only one field and edit it directly. This is to save space in the database. However, some cons are that it may make it hard to read if there are "," in the institute and/or country. There's no perfect solution and it seems that saving space and saving cost is more important for us.

@fans2619 In the case of account requests, the space and cost may not matter much as the number of entities is relatively small. So, you can save as two fields too, if it helps.

**Comment by fans2619** [comment]
Hmm to be honest, what helps me more is to store as a single field. I just hope that won't make admin's life too difficult. Storing as two fields is the hardest to implement, so it's either 1 (combined result only) or 3 (institute, country, instituteWithCountry).

**Comment by damithc** [comment]
> Hmm to be honest, what helps me more is to store as a single field. I just hope that won't make admin's life too difficult. Storing as two fields is the hardest to implement, so it's either 1 (instituteWithCountry only) or 3 (institute, country, instituteWithCountry).

Sure, no objections.

**Comment by fans2619** [comment]
@damithc Previously we discussed about what to do when another **REJECTED** account request exists <ins>when a user submits the account request form</ins>, and we decided to overwrite that account request. However, thinking about it again last night, it may not be a good enough solution because it can cause admin to process the same request again and again. So what if we just ban all submissions if the email%institute conflicts with an existing request, regardless of the status? And we should tell them to contact us if in doubt in this case.

**Comment by damithc** [comment]
> @damithc Previously (long time ago) we discussed about what to do when another **REJECTED** account request exists when a user submits the account request form, and we decided to overwrite that account request. However, thinking about it again last night, it may not be a good enough solution because it can cause admin to process the same request again and again. So what if we just ban all submissions if the email%institute conflicts with an existing request, regardless of the status? And we should tell them a request already exists and contact us if in doubt in this case.

You mentioned earlier that doing so is a minor data leakage as it allows any third party to find out if a certain other person has requested for a TEAMMATES account.

Would adding another status 'Reapplied' help?

**Comment by fans2619** [comment]
Yeah I mentioned before that this can cause a minor data leakage but it's not a big issue as long as we don't disclose the status of the account request. Many existing systems do tell users requesting for an account that the email address/phone number/... already exists.

**Comment by damithc** [comment]
> Yeah I mentioned before that mentioning the request status can cause a minor data leakage but it's not a big issue as long as we don't disclose the status of the account request. Many existing systems do tell users requesting for an account that the email address/phone number/... already exists.

Sure. Inform the user that an account request exists and provide the email address to contact us if further assistance is needed.

**Comment by fans2619** [comment]
@damithc I would like to add a new admin page called "Requests" to display account requests related stuffs. It's a bit message to put everything together since we're going to have show account requests processed recently. Afterwards, I can change the "Requests" page to be the new admin home page for convenience and move the current home page to a new page.

**Comment by damithc** [comment]
> @damithc I would like to add a new admin page called "Requests" to display account requests related stuffs. It's a bit messy to put everything together since we're going to show account requests processed recently. Afterwards, I can change the "Requests" page to be the new admin home page for convenience and move the current home page to a new page.

OK, we can try that and see how it goes.

**Comment by damithc** [comment]
> @damithc I just considered the "internal log" you mentioned. It looks to me the data structure is not simple to build and the log itself will not be used frequently. So unless you think you'll definitely need something like that now, I think we can put it off to a later time to see if the information will be needed? Personally I guess the last processed time and current status are sufficient for some purposes. This is quite similar to we don't need to keep all the information before every edit?

It's a text field. Something like this:

`x.log = x.log + "[Approved on 2022-07-25]"; `

But OK to omit as it's not a must-have feature.

**Comment by fans2619** [comment]
Yup it will be a text field after serialization. However, before serialization, ideally there should be some corresponding classes so that there is a way to deserialize the information later. If everything is a pure string, the implementation is just too rigid, which can be hard to use/maintain/migrate in the future in case we want to extend the log (e.g., to store rejection reasons).

**Comment by fans2619** [comment]
@damithc Hi prof, a question here: Previously we decided that the `lastProcessedAt` timestamp would be updated when you edit and save an account request. My question here is if there's no change made (same account request as before), do you prefer the `lastProcessedAt` timestamp to be updated to the latest or remain? This will unlikely happen but I just want to know your preference.

**Comment by damithc** [comment]
> @damithc Hi prof, a question here: Previously we decided that the `lastProcessedAt` timestamp would be updated when you edit and save an account request. My question here is if there's no change made (same account request as before), do you prefer the `lastProcessedAt` timestamp to be updated to the latest or remain? This will unlikely happen but I just want to know your preference.

I guess you can still update the timestamp if the user does a deliberate write op, even if it is x = x.

**Comment by fans2619** [comment]
Sure.
