### ISSUE TITLE
Enroll students page: improve display of progress bar

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#11876]
**Steps to reproduce**
After clicking "Enroll Students", the button displays weirdly when loading, with the button being unusually unlarged and a whitespace appearing above the text; after the enrolment is successful, the button display returns to normal.
![image](https://user-images.githubusercontent.com/54243224/175329733-8c424b51-79d3-4d32-9058-dbf0c8981c8d.png)

The button should be fixed so that the whitespace is removed.

**Comment by samuelfangjw** [comment]
The "whitespace" is actually a progress bar. Don't think this should be removed at all. At the very least a suitable alternative should be implemented.

**Comment by zhaojj2209** [comment]
Right, that slipped my mind. In my opinion, putting the progress bar display in the enroll button may be a bit jarring, we can consider moving it below the button instead, and possibly also add a percentage completion.

**Comment by damithc** [comment]
I had the same confusion until I enrolled a large number of students and saw the progress increasing. A dirty fix is to start with a fake 1% progress so that it's immediately clear it's a progress bar.

**Comment by samuelfangjw** [comment]
> A dirty fix is to start with a fake 1% progress so that it's immediately clear it's a progress bar.

I've experimented with this idea before. However, the current progress bar we use (ng-bootstrap) doesn't play nicely with small numbers. Here's the progress bar at 1%.

<img width="440" alt="Screen Shot 2022-06-23 at 11 54 16 PM" src="https://user-images.githubusercontent.com/60355570/175342215-4d9550cf-0107-4608-8f81-aa3d224674c0.png">

Might be better than the showing nothing though.

**Comment by damithc** [comment]
I see. 10%?

**Comment by FergusMok** [comment]
Perhaps the default value (e.g 10%) can be built into the component too, so that all the progress bars can benefit

e.g for the edit course progress bar. May be clearer that it's a progress bar with it's title, but still confusing if it stays at 0% for a brief period
![image](https://user-images.githubusercontent.com/10182564/180653081-0f085f45-1254-400e-8ce0-4cd76da8d4e6.png)

**Comment by wangdan87** [comment]
Is this issue still in need of attention? It seems like the solution was to initialize the loading bar to 10%, but I don't see any pull request.

**Comment by zhaojj2209** [comment]
@wangdan87 Feel free to submit a PR for this issue.

**Comment by domlimm** [comment]
May I pick up this issue?

**Comment by domlimm** [comment]
Hey @FergusMok! Aside from the general consensus to set the default value of progress bar component to 10, should we be adding a title too (at least for the copying courses)?
