### ISSUE TITLE
Evaluee/Recipient is being labelled as `Unknown`

### ISSUE THREAD

**Issue by thikhinab** [TEAMMATES/teammates#11888]
- **Environment**: `master` branch at commit 11865

**Steps to reproduce**
-  Create/Edit a question in a session
-  Select `Custom Feedback Path`
    - Case 1:
        -  Select under `Who will give the feedback`: any option
        -  Select under `Who the feedback is about`:  `Other students in the same section`
    - Case 2:
        - Select under `Who will give the feedback`: any option
        - Select under `Who the feedback is about`:  `Other teams in the same section`
    - Case 3:
        - Select under `Who will give the feedback`: `Teams in the course`
        - Select under `Who the feedback is about`:  `Giver's team members and Giver`
-  View the question from the evaluator's perspective

**Expected behaviour**
The evaluee/recipient to be labelled as either `Student`, `Team` or `Instructor`

**Actual behaviour**
The evaluee/recipient to be labelled as either `Unknown`

Case 1:
![image](https://user-images.githubusercontent.com/59680441/176605873-7277b5af-9322-4e41-b49f-da2b31bcc979.png)

Case 2:
![image](https://user-images.githubusercontent.com/59680441/176606047-8e0c8dc0-801b-4ad4-9484-3c078e0af3d3.png)

Case 3:
![image](https://user-images.githubusercontent.com/59680441/176606676-0f19d23c-de52-4170-afc9-c6a500c7f5d3.png)

**Additional Information**
Case 1 and 2 can be solved by be updating `RecipientTypeNamePipe`.
However for case 3, we do not know whether the recipient is an instructor or student.

**Comment by ErnestCuong** [comment]
Hi, I am currently trying to find one issue to solve for my independent work module. If no one is currently resolving this issue, I would like to try and investigate/solve this.

**Comment by damithc** [comment]
> Hi, I have a question, how do you view the session as a student? I could not find the preview session function for instructors.

@ErnestCuong is this what you are looking for?https://teammatesv4.appspot.com/web/front/help/instructor#:~:text=How%20do%20I%20preview%20a%20session%3F

**Comment by ErnestCuong** [comment]
Thank you for pointing it out for me :)

**Comment by ErnestCuong** [comment]
Hi all, I managed to solve case 1 and 2 by adding the 2 missing cases in `recipient-type-name.pipe.ts`. However, as @thikhinab has said, we actually do not know whether the giver or the recipient is an instructor or a student. Does anyone have any suggestion as to what label we should display?

**Comment by fsgmhoward** [comment]
@damithc Hi prof, any comment for his question?

**Comment by damithc** [comment]
> Hi all, I managed to solve case 1 and 2 by adding the 2 missing cases in `recipient-type-name.pipe.ts`. However, as @thikhinab has said, for case 3, we actually do not know whether the giver or the recipient is an instructor or a student. Does anyone have any suggestions as to what label we should display? Do we still want to correctly label people as `Student` and `Instructor`?
> 
> Currently for case 3, `recipientType == OWN_TEAM_MEMBERS_INCLUDING_SELF` while `giverType == TEAMS`.

Only students can be in teams (i.e., instructors cannot be in teams). Does that resolve the issue?

**Comment by ErnestCuong** [comment]
Hi prof @damithc , yes that does resolve and simplify the issue. Thank you.
