### ISSUE TITLE
Add Firebase Authentication

### ISSUE THREAD

**Issue by xyliew25** [TEAMMATES/teammates#11890]
- **Environment**: live server at `V8.17.0`

**Description of feature/enhancement**
An authentication solution that supports any domains on top of Google social accounts.

**Justification**
This feature/enhancement benefits users without Google accounts or users who are not willing to use their (likely personal) Google account from using the system.

**Existing similar features and their shortcomings**
Only Google social account is supported as a form of identity provider.

More info can be found on the wiki at https://github.com/TEAMMATES/teammates/wiki/Authentication-Plus.

**Comment by Abhijeetmishr** [comment]
@xyliew25 Is anyone working on this ?

**Comment by xyliew25** [comment]
@Abhijeetmishr hi, yes, I'm currently working on this issue. PR #11891 includes changes required for the back end as well.

**Comment by Abhijeetmishr** [comment]
> @Abhijeetmishr hi, yes, I'm currently working on this issue. PR #11891 includes changes required for the back end as well.

Ok thank you 
I am new to this project & OpenSource any sugesstion to pickup any issue from backend ?

**Comment by zhaojj2209** [comment]
@Abhijeetmishr We recommend starting from issues with the `good first issue` label on them!
