### ISSUE TITLE
Course Enroll Page highlights the wrong rows

### ISSUE THREAD

**Issue by tau-bar** [TEAMMATES/teammates#11924]
Course Enroll Page highlights the wrong rows: In the event that students are added, but not starting from the first row, the wrong rows are highlighted.

**Environment**: V.8.19.2

**Steps to reproduce**

Insert rows of students (either new, modified or unchanged) not starting from the first row. An example is shown below:

![image](https://user-images.githubusercontent.com/61085398/182779557-5c11676b-df0f-480f-82eb-016d71dff0d9.png)

In this example, the second row represents a student that already exists in the enrollments, and their details have not been modified. The third row is a new student who has not been enrolled yet.

**Expected behaviour**
The second row should be highlighted gray, as the student's details has been unmodified, and the information is in the second row. The third row should be highlighted green, as it is a new student.

**Actual behaviour**
The first row is highlighted gray, and the second row is highlighted green. Refer to the screenshot below:

![image](https://user-images.githubusercontent.com/61085398/182779391-ef7adade-2a3a-4ae7-b79e-0967993966b4.png)

**Additional info**
I know what caused the bug. I will be attempting to fix this issue in my forked repo.

**Comment by domlimm** [comment]
@tau-bar hey Taufiq, i think you've created the PR for this issue in your forked repo instead of the upstream.

**Comment by tau-bar** [comment]
Sorry, it was a PR I did for selection phase. I'll create a new PR to the upstream instead.

**Comment by domlimm** [comment]
Oops sorry.. I think we might be on a different page. I thought you might have mistakenly created it in your forked repo. If it's for other reasons sorry about that! Please revert and ignore what I said 😓

**Comment by tau-bar** [comment]
@domlimm It initially was for the selection phase, but if the bug fix works can it be merged into the main repo? Are there any refinements I should make to the PR?

**Comment by domlimm** [comment]
@tau-bar I see! Sorry not too sure about this selection phase. Could be part of a module. For the rest of your questions, maybe others who are more familiar can answer.. Think we're a little confused
