### ISSUE TITLE
Help Request: E2E Tests

### ISSUE THREAD

**Issue by isabelteo** [TEAMMATES/teammates#11925]
Help Request with E2E Tests

- **Commit SHA:** 3155a78b64ba33ae3ed93a3754db3b9d5b828775 
- **Operating System:** Windows
- **JDK Version:** openjdk version "11.0.11" 2021-04-20
- **Node.js Version:** v17.7.1
- **Chrome Version (if applicable):** 103.0.5060.134
- **Chrome Driver  Version:** 103.0.5060.134

**What I was trying to do / What I need help with**
I was setting up the project and I have passed all the component tests but when I ran the E2E tests, I found that more than 5 were failing. I wanted to double check if it is a local set-up problem or something relating to Windows (like in #11220) because I have not touched the code yet (except to add the link to the chrome driver). Some of the error messages are due to assertion errors relating to a missing dot.

Some examples of the error messages:
![image](https://user-images.githubusercontent.com/83572953/183293959-d1786d24-df4e-48ca-a1ef-79017a48da67.png)

![image](https://user-images.githubusercontent.com/83572953/183294164-96e66518-8059-410e-9bdf-d5130929ebc0.png)

For more detailed output given in terminal : [output_e2e.txt](https://github.com/TEAMMATES/teammates/files/9276930/output_e2e.txt)

To run the tests, I first start the dev server in command prompt: gradlew.bat serverRun & --> set NODE_OPTIONS=--openssl-legacy-provider --> npm run build (as suggested in #11457 )
Then, I run gradlew.bat e2eTests in the terminal of IntelliJ

**Attempts to resolve the problem**
I have looked through a few of the issues relating to E2E tests, such as #11457 , #11220 , #11537 , #11246 
I have checked the troubleshooting guide but the errors like the assertion error or the NoElementFoundException are not inside
The main change I did was to run npm run build based on #11457.

I would appreciate any advice on this matter or to be directed to the relevant closed issue if I have missed it out (so sorry if so) - thank you!

**Comment by samuelfangjw** [comment]
Could you try again with the Firefox driver (geckodriver), I suspect that there may be some issues running e2e tests with chromedriver at the moment.

**Comment by wkurniawan07** [comment]
The first one (`NoSuchElementException`) is one of those intermittent timing issues; this should go away after a few tries. But everything else looks like a weird setting in your locale; either your browser or your Java runtime does these two things: (1) adds the extra dot after the month name and day name and (2) converts AM/PM to lowercase.

**Comment by isabelteo** [comment]
@samuelfangjw @wkurniawan07 thank you for the replies! I tried geckodriver and it has the same assertion errors so I think I will try doing the set up again to figure out what is wrong with my browser or Java runtime!
