### ISSUE TITLE
Instructors with custom permissions cannot reach the session results page

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11929]
v8.19.2, production, reported by a user

Scenario: An instructor has been given permission to view responses of a specific section only. See below for an example:
![image](https://user-images.githubusercontent.com/1673303/183466441-9f9cb32b-255d-4404-b253-5dca0f19d070.png)

Problem: When that instructor tries to view results of the session, the following error shows up:
![image](https://user-images.githubusercontent.com/1673303/183466611-2714cf9e-8bd7-45c5-a082-b4e3325c94c1.png)

I suspect this is because the instructor doesn't have permission to see _all_ results of the session.

**Comment by wkurniawan07** [comment]
Admittedly, the permission-checking code at this page (both versions) is quite a mess. But just to get the record straight, this is the course-wide page?

**Comment by damithc** [comment]
> Admittedly, the permission-checking code at this page (both versions) is quite a mess. But just to get the record straight, this is the course-wide page?

Yes, it is a course-wide results page. The course owner figured out a workaround, by setting the permissions in this way instead:
![image](https://user-images.githubusercontent.com/1673303/183471163-ea9f9d9d-ab1c-4d3a-b540-c62388a9b729.png)

In this case the tutor can see the results, as long as he selects the correct section here:
![image](https://user-images.githubusercontent.com/1673303/183471326-02556824-f67f-440e-a73e-d42b79b7280f.png)

**Comment by damithc** [comment]
Lowering priority as the user found a workaround.

**Comment by tau-bar** [comment]
Is anyone working on this? If not I'd like to try and fix this issue.

**Comment by NicolasCwy** [comment]
@tau-bar Go ahead, but do keep us in the loop as @wkurniawan07 has mentioned that the checks are in this page might be messy

**Comment by tau-bar** [comment]
Alright, will do

**Comment by fans2619** [comment]
@damithc Although I'm not very sure, based on the phrasing in the UI, probably the workaround is actually the correct way to set things. Looking at the page, it says "In general, this instructor can ... but in sections ... this instructor can **only** ...". From my interpretation, the word "only" seems to imply something more restrictive. So it's probably supposed to mean in order for the instructor to have **permission A** for **section B**, he must have **permission A** at both the course level and for **section B**, _provided **section B** permissions are set separately_. With that said, I'm not really sure what's the expected flow when this page was designed previously.

**Comment by damithc** [comment]
@fans2619 You are right in that the the current behavior seems to agree with the UI. For practical purposes though, we need to support both approaches, or switch to the other approach. This is because the more common scenario is a tutor is given access to her own section only. That is, number of inaccessible sections could be a lot more than accessible sections, making the configuration very verbose.  e.g., 15 sections with 15 tutors will require 225 separate access configurations. What do you think?

**Comment by tau-bar** [comment]
@fans2619 @damithc Perhaps a more accurate way to phrase it would be to say "~~But~~ In sections... this instructor can only...", so that the UI would be consistent with the logic? Since as mentioned, the more common scenario is for the tutor to only be given access to their own section. However, I believe issue #11935 needs to be resolved as well before the UI would entirely match the logic of the custom settings.

**Comment by fans2619** [comment]
> we need to support both approaches, or switch to the other approach

I totally agree with this.

**Comment by damithc** [comment]
> @fans2619 @damithc Perhaps a more accurate way to phrase it would be to say "~But~ In sections... this instructor can only...", so that the UI would be consistent with the logic?

Yup. Perhaps remove `only` as well.

**Comment by tau-bar** [comment]
I have updated the UI in the PR.
