### ISSUE TITLE
Instructors with custom permissions cannot view student list

### ISSUE THREAD

**Issue by tau-bar** [TEAMMATES/teammates#11935]
Similar to #11929, if the instructor only has privilege to view student details, they are unable to view the student list.

v8.19.2, development server on master branch.

**Steps to reproduce**
Set the permissions as such:
![image](https://user-images.githubusercontent.com/61085398/184499023-9093a42e-ee56-437b-87bb-14e08d197dc4.png)

**Expected behaviour**
Instructor should be able to see the student list, but only be able to view student details of students in a section to which the instructor has privileges to view student details.

Should look like this:
![image](https://user-images.githubusercontent.com/61085398/184499191-2dc94b92-1ad5-4cdc-b21d-6e8b07430028.png)

**Actual behaviour**
The instructor is unable to view the student list at all.
![image](https://user-images.githubusercontent.com/61085398/184499217-525a7c52-9ebb-42a9-85c8-f69c0845cc86.png)

**Comment by ErnestCuong** [comment]
Hi, I would like to investigate the issue. Is anyone else working on it?

**Comment by fsgmhoward** [comment]
@ErnestCuong I don't think so. Please proceed. Thanks.

**Comment by fans2619** [comment]
@tau-bar How do you know that's a bug instead of an expected behavior?
