### ISSUE TITLE
Question Development

### ISSUE THREAD

**Issue by Broadwc** [TEAMMATES/teammates#11931]
Hi,

I'm one of a number of academics who love TEAMMATES at our institution. What has been developed is amazing and it fills 95% of my needs perfectly. I saw the release allowing zero-sum contribution questions and wondered if there would be a possibility for me to join the community and work on a couple of other questions variations that would be really helpful for my modules. 

This probably isn't the best way to go about asking, so please forgive any mistakes on that front. I'm keen to get involved and hopefully be a positive contributor. 

Christian

**Comment by damithc** [comment]
Christian, glad to hear you found TEAMMATES useful. You are most welcome to contribute code to TEAMMATES. The guide for potential contributors is at https://teammates.github.io/teammates/contributing-doc.html

Please note that changes to features need to be proposed (and approved) first, as we might not want to add features that whose benefit is not enough to justify the future maintenance cost.

**Comment by Broadwc** [comment]
Hi Damith, thanks for the note. I'll start making a suggestion and see how it goes!
