### ISSUE TITLE
Add frontend tests for `course-edit-form`

### ISSUE THREAD

**Issue by thikhinab** [TEAMMATES/teammates#11945]
- **Environment**: `master` branch at commit 39192f4

**Description of feature/enhancement**
Add front-end testing to test course edit form to look out for software regression.

**Justification**
Though the `course-edit-form` within other components, its internal working (such as the behavior of the form for invalid input) is not yet tested.

**Additional info**
There is difficulty in testing the form within `course-edit-form` as the tester cannot access the form before being rendered. Any investigation into this would be helpful.

**Comment by tusharrajpoot** [comment]
@thikhinab can i add tests for that?

**Comment by thikhinab** [comment]
Hey @tusharrajpoot! I working on related issue that may slightly change `course-edit-form`, which might affect this issue. Will try to finish it this week and I will update you on it.

**Comment by u6358194** [comment]
@tusharrajpoot can I work on this issue, that's my first contribution to open source

**Comment by thikhinab** [comment]
@tusharrajpoot I believe #11946 add more tests to this, but there will be room for improvement with the tests introduced by the changes made once #11968  resolved.

**Comment by thikhinab** [comment]
@tusharrajpoot #11946 is merged and #11968 is resolved, you can look into ways to improve the `course-edit-form` tests. Particularly, you can look into tests that checks if the form validation works as intended.

@fsgmhoward Changes that me hold the issues are resolved. Thank you.
