### ISSUE TITLE
Unable to access `web/admin/home` after logging in

### ISSUE THREAD

**Issue by domlimm** [TEAMMATES/teammates#11951]
- **Commit SHA:** 39192f4a67bcf1a5f5439e6181fc062e0973ad90
- **Operating System:** Windows 10
- **JDK Version:** 
```
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```
- **Node.js Version:** v16.17.0
- **Firefox / Chrome Version (if applicable):** Chrome

**What I was trying to do / What I need help with**

Issue: `You are not authorized to view this page` after logging in from `http://localhost:8080/web/admin/home`.

Yesterday, I deleted my containers/images from Docker Desktop, cleared the caches, etc.

Earlier, checked out from the latest `master` and ran `npm ci` followed by doing everything from here on https://teammates.github.io/teammates/development.html#managing-the-dev-server-front-end.

I used Docker for the datastore (https://teammates.github.io/teammates/development.html#running-the-datastore-emulator) too.

However, was not able to create an Instructor account as I can't access any admin page even after logging in.

Appreciate any help please, thank you so much!

**Attempts to resolve the problem**

- Tried setting up the datastore with `gradlew`
- Restarted the entire setup process a few times

**Comment by tenebrius1** [comment]
Hi @domlimm, could I check what value you used to log in to `http://localhost:8080/web/admin/home`? If you did not change any values in the `build.properties` file, the default admin email should just be `app_admin`.

**Comment by damithc** [comment]
Devs, any inputs for this?

**Comment by samuelfangjw** [comment]
@domlimm, could you verify that your backend server is running and the app.admins property in the build.properties file is correctly set?

**Comment by domlimm** [comment]
Hello @samuelfangjw, thanks for your reply!

This is the value for `app.admins` --> `app.admins=app_admin` in the build.properties file.

I ran `./gradlew createConfigs`, `npm ci`, `./gradlew generateTypes`, `npm run build`, `npm run start` for the FE all in sequence.

For the BE, `docker-compose up -d` to run both the database and search service, `./gradlew serverRun` in sequence.

Docker container datastore (leaving solr out. However, the container for it is running too):

![image](https://user-images.githubusercontent.com/46486515/187112582-9377173c-553c-4d41-b9fb-3471dced05e8.png)

And went to `http://localhost:8080/web/admin/home`, logged in with `app_admin@gmail.com` and got:

![image](https://user-images.githubusercontent.com/46486515/187112448-7759e561-97be-44b3-8970-f919bcc7195b.png)

**Comment by tenebrius1** [comment]
I believe the login is just `app_admin` instead of `app_admin@gmail.com`

**Comment by domlimm** [comment]
@tenebrius1 Hello, yup it is!

![image](https://user-images.githubusercontent.com/46486515/187113243-f358afe0-68a9-4657-951b-8bc581ed4554.png)

**Comment by tenebrius1** [comment]
Sorry I realized I was a bit ambiguous, what I meant was could you try logging in as `app_admin` instead of `app_admin@gmail.com`?

**Comment by domlimm** [comment]
@tenebrius1 it worked! Thanks so much Yi Guan!

I don't remember logging in without the domain the first time around haha! 🤨 

![image](https://user-images.githubusercontent.com/46486515/187113532-510561a0-77db-440a-9e08-ce85141923c4.png)

**Comment by domlimm** [comment]
@damithc @samuelfangjw @tenebrius1 Will close this issue now. Thank you so much to all! 🙇🏻
