### ISSUE TITLE
Instructor/Student login, Feedback submission

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11959]
### Discussed in https://github.com/TEAMMATES/teammates/discussions/11958

<div type='discussions-op-text'>

<sup>Originally posted by **akshayavenkat2131** September 20, 2022</sup>
Hi team

I have the Front and Back-end server and the datastore emulator running locally.I would like to try out the submitFeedback feature which I am having problems with.I have tried the following : 
- Tried logging in as a student.I seem to be able to login with my registered email address from what I see, but do not see any "Sessions" tab as mentioned in help pages- 

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/68556957/191066738-fa9bb09a-989b-41dc-bf61-31efd93a9094.png">
- Tried submitting a session-link recovery request for which I don't seem to have received any email.
- Tried logging in as an instructor which I am unable to do as well.
- I also did submit a request for an instructor account earlier which I didn't hear back on.

I seem to have hit a roadblock here.Do I need to have any specific accesses to be able to join courses and submit feedback?Would really appreciate some inputs on how to proceed.

Thanks & Regards
Akshaya.</div>

**Comment by tusharrajpoot** [comment]
@damithc can i work on it?

**Comment by zhaojj2209** [comment]
Closing as query has been answered on #11958.
