### ISSUE TITLE
INFO::main: Logging initialized @14591ms to org.eclipse.jetty.util.log.StdErrLog

### ISSUE THREAD

**Issue by yengah** [TEAMMATES/teammates#11964]
Help Request: INFO::main: Logging initialized @14591ms to org.eclipse.jetty.util.log.StdErrLog

- **Commit SHA:** b47a59b78001caa1124257307c79b4bf569b3716
- **Operating System:** Windows 11
- **JDK Version:** JDK version 18.0.2
- **Node.js Version:** v16.17.1
- **Firefox / Chrome Version (if applicable):** NA

**What I was trying to do / What I need help with**
Running the server backend, as per command: ./gradlew serverRun

The run errors out with:

> Task :serverRun FAILED
2022-10-06 14:50:28.171:INFO::main: Logging initialized @14591ms to org.eclipse.jetty.util.log.StdErrLog
Exception in thread "main" java.lang.ExceptionInInitializerError
        at teammates.main.Application.main(Application.java:38)
Caused by: java.lang.NullPointerException: inStream parameter is null
        at java.base/java.util.Objects.requireNonNull(Objects.java:233)
        at java.base/java.util.Properties.load(Properties.java:408)
        at teammates.common.util.Config.<clinit>(Config.java:116)
        ... 1 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':serverRun'.
> Process 'command 'C:\Program Files\Java\jdk-18.0.2\bin\java.exe'' finished with non-zero exit value 1

**Attempts to resolve the problem**
Changed JDK on IDE from 17 to 18.
And language level to SDK Default.

**Comment by zhaojj2209** [comment]
Do follow the instructions on the TEAMMATES [setting up guide](https://teammates.github.io/teammates/setting-up.html#step-2-install-necessary-tools-and-languages) in order to run the dev server locally. Specifically, TEAMMATES uses JDK 11 while you are using JDK 17/18.

**Comment by yengah** [comment]
Hi,
Switched to JDK 11, but no, I still get the same problem, as follows:

> Task :serverRun
2022-10-07 00:45:13.671:INFO::main: Logging initialized @15463ms to org.eclipse.jetty.util.log.StdErrLog
Exception in thread "main" java.lang.ExceptionInInitializerError
        at teammates.main.Application.main(Application.java:38)
Caused by: java.lang.NullPointerException: inStream parameter is null
        at java.base/java.util.Objects.requireNonNull(Objects.java:246)
        at java.base/java.util.Properties.load(Properties.java:407)
        at teammates.common.util.Config.<clinit>(Config.java:116)
        ... 1 more

> Task :serverRun FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':serverRun'.
> Process 'command 'C:\Program Files\Java\jdk-11.0.10\bin\java.exe'' finished with non-zero exit value 1

**Comment by yengah** [comment]
Yes, all steps done, but still getting the same error.  
Step 3 is done.
build,properties does not exist, however, build.template.properties exist.

**Comment by NicolasCwy** [comment]
@yengah Please create a build.properties by duplicating the build.template.properties and renaming the duplicate

**Comment by yengah** [comment]
@NicolasCwy works!
But now, when trying to connect to the server via my web browser, the following errors

HTTP ERROR 403 Forbidden
URI:	/
STATUS:	403
MESSAGE:	Forbidden
SERVLET:	default
Powered by Jetty:// 9.4.48.v20220622

?

**Comment by samuelfangjw** [comment]
> Yes, all steps done, but still getting the same error.
> Step 3 is done.
> build,properties does not exist, however, build.template.properties exist.

Step 3 should creates these configuration files. There is no need to copy these manually.
```
            "gradle.template.properties",
            "src/main/resources/build.template.properties",
            "src/main/resources/build-dev.template.properties",
            "src/web/environments/config.template.ts",
            "src/test/resources/test.template.properties",
            "src/lnp/resources/test.template.properties",
            "src/e2e/resources/test.template.properties",
            "src/client/resources/client.template.properties",
            "src/main/appengine/app.template.yaml"
```

Seems like there's an issue with this step on your side.

**Comment by yengah** [comment]
Verified all those files present @samuelfangjw.

They are all present.

Seems maybe no issue with this step then?

**Comment by samuelfangjw** [comment]
Should create these files without the template in the name.

**Comment by yengah** [comment]
@samuelfangjw done that.

still does not work.

**Comment by NicolasCwy** [comment]
Could you let us know the order and which steps you have done in [this part of the guide](https://teammates.github.io/teammates/development.html) as well as the URL you are trying to connect to

**Comment by yengah** [comment]
Sure, I'm trying to do the server-backend.

I followed all the steps under "Managing the dev server: back-end".  and am trying to connect to: http://localhost:8080.

**Comment by samuelfangjw** [comment]
> @samuelfangjw done that.
> 
> still does not work.

Yes, this is not related to the current issue, but it does indicate that at least some steps have not been done properly. Please go back and ensure that you have read all the relevant documentation and do not skip any steps. For example, the answer to the current "issue" should be quite clear if you have read the development guidelines.

**Comment by yengah** [comment]
@NicolasCwy any comments?

**Comment by NicolasCwy** [comment]
> Sure, I'm trying to do the server-backend.
> 
> I followed all the steps under "Managing the dev server: back-end". and am trying to connect to: http://localhost:8080.

Would be helpful if you listed out the steps so that I can understand what you have actually done.

I assume that you are trying to access the teammates website using your browser, if so you have to follow the "Managing the dev server: front-end" as well as the "Managing the dev server: back-end" sections. Let me know if this helps and what went  wrong

The order of the commands you should have executed should have thus been
./gradlew generateTypes 
npm run build
./gradlew serverRun
docker-compose up -d

**Comment by yengah** [comment]
@NicolasCwy sure, I'll do this right now.  Please give me 20-25 minutes or so.

**Comment by zhaojj2209** [comment]
http://localhost:8080 is not meant to be accessed directly without specifying a specific endpoint, hence the 403. Either make API calls to specific endpoints, or build/run the frontend and access a specific page.

**Comment by yengah** [comment]
@zhaojj2209 awesome.  Great comment.  
Yes, you are totally correct.
