### ISSUE TITLE
Student submitting responses: omit 'for Question 1' if there is only one question

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11960]
version: v8.19.2. production

Problem: 
When submitting response for a session, the submission button for each question mentions the question number e.g.,
![image](https://user-images.githubusercontent.com/1673303/193080008-1ef0686e-ca5b-4f97-882d-aeb508921eba.png)

But this can be problematic if the session has only one question, as the user might think there are more questions not shown yet.

Suggestion: omit 'for Question 1' if there is only one question in the session.

**Comment by domlimm** [comment]
Hello prof, will this be a `good first issue`? Else, I'd love to work on this!

**Comment by damithc** [comment]
@domlimm on second thoughts, go ahead, as it's best to fix this sooner rather than later.

**Comment by domlimm** [comment]
Will do, thanks prof!
