### ISSUE TITLE
`Auto-detect` Button in `CourseEditForm` is not disabled

### ISSUE THREAD

**Issue by thikhinab** [TEAMMATES/teammates#11968]
- **Environment**: `master` branch at commit 7a1e7d3

**Steps to reproduce**:
1. Visit the following route in the frontend: `/web/instructor/getting-started`
2. Under `Set up a course` section, observe that `Auto-detect` Button of the `form` can be clicked (i.e. it  is not disabled)

**Expected behaviour**
`Auto-detect` button should be disabled as it serves on purpose in the edit mode.

**Actual behaviour**
`Auto-detect` button calls the `detectTimezoneHandler`.

**Additional info**
Since there is check within the `detectTimezoneHandler` for `isDisplayOnly`, no significant computations are carried on.
However, refactoring the boolean that are responsible for disabling buttons within the `CourseEditForm` will make the component less prone to bugs in the future development.

**Comment by zhengtaoJ** [comment]
Hi, can I investigate on this?

**Comment by zhaojj2209** [comment]
@zhengtaoJ Feel free to investigate this issue and PR a fix!
