### ISSUE TITLE
Help Request: explain mcq question details validation

### ISSUE THREAD

**Issue by kulagaIA** [TEAMMATES/teammates#11971]
Hello! It seems to me that mcq question details validation happens only when there are no feedback participants.
In file `FeedbackMcqQuestionDetails.java`
method `validateQuestionDetails()`
does validation only if condition is true: `if (generateOptionsFor == FeedbackParticipantType.NONE)`

Can you please explain, is it a desired behavior? And if yes, why?

**Comment by zhaojj2209** [comment]
@kulagaIA Apologies for the late response.
From my understanding, `generateOptionsFor` is the attribute that indicates whether or not MCQ choices are automatically generated. If the value for `generateOptionsFor` is not `FeedbackParticipantType.NONE`, it means that the MCQ choices are automatically generated and not manually filled in by the user, therefore no validation is needed.

Hope this answers your query.

**Comment by kulagaIA** [comment]
Thank you! This answers my question.
