### ISSUE TITLE
Help when setting up teammates for the first time

### ISSUE THREAD

**Issue by kelvis24** [TEAMMATES/teammates#11979]
Request for help on how to get Teammates running on Windows 11. 

Dear community, 
I have followed the [installation guidelines](https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md) and retried cloning in several directories. 
I just cant seem to get the command: .**/gradlew serverRun** to run and lead to a working http://localhost:8080/ endpoint. 
I have docker, java 11 (java version "11.0.17" 2022-10-18 LTS), node v16.14.2, and latest Chrome version.  I have the local Datastore emulator and Full-test search service up and running as seen bellow.
![image](https://user-images.githubusercontent.com/55446208/197411942-b3e1e439-1982-4c8f-a424-9813235c1329.png)

I have the frontend part running well. When I try logging in, I get this error 
![image](https://user-images.githubusercontent.com/55446208/197412276-e10e6c55-e64f-4f0c-9721-8593c146225c.png)

and when I check my .**/gradlew serverRun** command, I still find it stuck at 85% compilation as seen below.  It gets stuck like this forever. Longest has been almost 2 hrs and I worry it'll never go past this stage. 
I and a team of 5 are working on an open-source development class (college), we chose teammates, and we'd love to figure this out so that we can start working on issues as well. Any help would very very much be appreciated. 

![image](https://user-images.githubusercontent.com/55446208/197411818-c667549f-9350-46d4-9f4c-9802a7916478.png)

**What I was trying to do / What I need help with**
**I'm stuck in the setup level below**. My localhost:8080 isn't working and I'd like it to work. Also my login keeps throwing an Ooops error message. Maybe these problems are connected. I just need this stage to work. Many thanks for your time and consideration. 

![image](https://user-images.githubusercontent.com/55446208/197414383-c1370e50-5ae3-41ff-a513-2dff8576e4b5.png)

**Attempts to resolve the problem**
I renamed my folder directory and removed the spaces in it's previous name. 
Installed java 11 instead and changed the path variable to have 11 instead of java 18. 
I did a lot of reading on slf4j warnings. Couldn't figure out the actual solution to this warning. Then I read that the default to NOP logger implementation was just a warning and It shouldn't affect anything, (I could be wrong, I'm not sure) This is what I read:
![image](https://user-images.githubusercontent.com/55446208/197414317-4cb8d49f-62a7-4e3b-a82e-9b7536d8f848.png)

**Comment by zhaojj2209** [comment]
`./gradlew serverRun` being at 85% is the intended behaviour, the server is already running in the foreground. The errors are being thrown because you are attempting to log in as a student when the account does not yet exist.

Please follow the developer documentation section on [how to log in to TEAMMATES](https://teammates.github.io/teammates/development.html#logging-in-to-a-teammates-instance).

**Comment by u7305725** [comment]
Hi kelvis, this is my personal experience on how to do setting-up after you correctly set up development environment 
[instructions.docx](https://github.com/TEAMMATES/teammates/files/9850358/instructions.docx)

**Comment by kelvis24** [comment]
Thanks guys. I really appreciate all the help! Like you all pointed, I just had to log in the right way.
