### ISSUE TITLE
Cannot run project with npm

### ISSUE THREAD

**Issue by DanhuiChang** [TEAMMATES/teammates#11978]
- **Commit SHA:** 
- **Operating System: mac M1**
- **JDK Version: 11**
- **Node.js Version: 16.8**

**What I was trying to do / What I need help with**

- **Need help to open the project and run in local**

**Attempts to resolve the problem**

- **After I clone the project and followed the instruction, I cannot run the project after "npm run start". The hint said that "cannot find module '../api-output or its corresponding type declarations'"**

**Comment by zhaojj2209** [comment]
Please read the [developer documentation](https://teammates.github.io/teammates/development.html#managing-the-dev-server-front-end). Have you followed the instructions and run the commands that should be run before attempting to start the dev server?
