### ISSUE TITLE
Problem when setting up the project locally

### ISSUE THREAD

**Issue by Alrq** [TEAMMATES/teammates#11994]
- **Commit SHA:**  441e8ba9a98213d346ab09ed83f1172d0ad73507

- **Operating System:** Ubuntu 20.04.5 LTS
- **JDK Version:** 11.0.16
- **Node.js Version:** v19.0.1
- **Firefox / Chrome Version (if applicable):**

**What I was trying to do / What I need help with**

Hi! 
I'm looking to contribute on this project as part of one of my university courses, so i've been following the instruction to set it up locally. I've done every step the way it is said here https://github.com/TEAMMATES/teammates/blob/441e8ba9a98213d346ab09ed83f1172d0ad73507/docs/setting-up.md#:~:text=Blame-,title%3A%20%22Setting%20Up%22,-Setting%20up%20a 
However, when i get to this point: https://github.com/TEAMMATES/teammates/blob/441e8ba9a98213d346ab09ed83f1172d0ad73507/docs/development.md#:~:text=Compiled%20successfully.%3A-,npm%20run%20start,-The%20dev%20server
 I get this message: "This version of CLI is only compatible with Angular versions ^14.0.0, but Angular version 12.2.16 was found instead."  So i'm confused as it was said to use the version 12... 

**Attempts to resolve the problem**

**Comment by zhaojj2209** [comment]
What the error message is saying is that your version of Node (19.0.1) is only compatible with Angular versions 14.0.0 and above. Since TEAMMATES uses Angular 12, you will have to switch to an older version of Node (e.g. Node 12).

**Comment by Alrq** [comment]
Oh! Right ok!  Thank you! 
In the Setting up section, it is said that when we install Node.js we should have version 12.11.1 **minimum** so I thought getting the latest version would be fine.  Wouldn't it be a good idea to mention that version 12 is the recommended version and not the minimum version to use ??
