### ISSUE TITLE
Student submitting fewer responses than allowed: show empty responses at the bottom when reloading the submission page

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11991]
v8.19.2

Background: an MCQ questions is set as follows:
![image](https://user-images.githubusercontent.com/1673303/200155822-b5a0d50b-598a-46e5-8306-4a5474a19d3a.png)

Problem:
If a student give fewer than 10 answers to the above question, the page looks like this the next time the submission page is loaded.
![image](https://user-images.githubusercontent.com/1673303/200155827-4bba57c5-0104-4c44-a6fd-163a89932199.png)

Suggestion:
The empty values should be at the bottom rather than at the top.

**Comment by domlimm** [comment]
Hello prof, will this be for first timers?

**Comment by damithc** [comment]
> Hello prof, will this be for first timers?

@domlimm yes, most likely suitable for first-timers.

**Comment by RohithSurya** [comment]
@damithc This is my first open-source contribution. Can you assign this issue to me?

**Comment by zhaojj2209** [comment]
@RohithSurya Feel free to make a PR for this issue.

**Comment by RohithSurya** [comment]
Hi @zhaojj2209, Can you please check and review my PR 😊 ?
