### ISSUE TITLE
Instructor viewing student activities: distinguish between view and submit

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12011]
Context: the unreleased 'view student activity feature' mentioned in https://github.com/TEAMMATES/teammates/pull/11845

![image](https://user-images.githubusercontent.com/1673303/209202011-6e73a788-b569-4fb5-a4cb-c913ce27fceb.png)

Suggestion: even if the `session access and submission` option is chosen, the results should differentiate between view access and submission. Showing the activity as `viewed OR submitted` is less useful than it can otherwise be.

**Comment by domlimm** [comment]
Hello prof, may I look into this issue?

**Comment by damithc** [comment]
@domlimm go ahead.

**Comment by domlimm** [comment]
Hello again prof, this is what I have found so far.

It seems as though when a student **accessed** a feedback session and **starts submission but did not submit response**, it is logged as the student has viewed and submitted responses. To reproduce this, I made a new feedback session (called `Feedback Test` in the sessions list in image below), clicked on start submission and the logging service captured it as both `session access and submission` when filtered from the Student Activity Logs.

There is another case with the preloaded `Session with different question types` session where student has **only viewed** the course session but **did not submit** a response and it was also captured as `session access and submission` when it should be just under `session access`.

![image](https://user-images.githubusercontent.com/46486515/212259535-cbff149b-be76-45e8-beed-23f9ba3100d0.png)

![image](https://user-images.githubusercontent.com/46486515/212259439-0405015e-f0e3-4224-8a95-08c2fd1c28ca.png)

May I ask how should we go about fixing this issue? Or what should be the end result to display such a log? Not entirely clear yet. Thanks prof!

**Comment by damithc** [comment]
@domlimm In these cases should be displayed as `Viewed the submission page` (leave out the `or ...` part).
The question is if this is a case of recording the event correctly in the database but displaying it in an ambiguous way or if the record in the database is already ambiguous.
@daongochieu2810 any thoughts?

**Comment by daongochieu2810** [comment]
@damithc @domlimm the events are recorded correctly, and this ambiguous display is caused by a logic on the front-end (instructor-student-activity-logs.component.ts line 309). The status is derived from the selected access type from the dropdown instead of the returned log, so this is a bug on my end

**Comment by domlimm** [comment]
@daongochieu2810 hello, thanks for getting back and clarifying! yes, i thought that could be the case too when searching for the bug, but wasn't too sure. would you like to fix it?

**Comment by daongochieu2810** [comment]
@domlimm I'm working on another issue for now, so you can take it if it's possible

**Comment by domlimm** [comment]
@daongochieu2810 alright sure!

could i clarify one more thing?

if we have a bunch of log entries (x5 for this example below) and we select `session access and submission`, we will show all 5, is that correct? and each as a row itself?

thank you!

```json
"feedbackSessionLogEntries": [
    {
      "studentData": {
        ...
      },
      "feedbackSessionLogType": "ACCESS",
      "timestamp": 1673612997999
    },
    {
      "studentData": {
        ...
      },
      "feedbackSessionLogType": "SUBMISSION",
      "timestamp": 1673613014948
    },
    {
      "studentData": {
        ...
      },
      "feedbackSessionLogType": "ACCESS",
      "timestamp": 1673613023436
    },
    {
      "studentData": {
        ...
      },
      "feedbackSessionLogType": "SUBMISSION",
      "timestamp": 1673613029078
    },
    {
      "studentData": {
        ...
      },
      "feedbackSessionLogType": "SUBMISSION",
      "timestamp": 1673613035636
    }
  ]
```

**Comment by daongochieu2810** [comment]
@domlimm yes that's correct

**Comment by domlimm** [comment]
@damithc hello prof, i spoke to hieu about this issue and clarified my doubts. as of now, we have solved the bug on why it shows up as `viewed OR submitted`. however, i'm a little confused as to why the logs are not showing in entirety.

i apologise for the length of this comment.. 😓 

example: i create a new feedback session, i access it (by clicking `Start Submission`) at 00:00. i filter by `ACCESS`/`ACCESS,SUBMISSION` logs and see that it is indeed shown and saved correctly.

now i decide to enter some responses, saved them at 00:01. there should be 2 `ACCESS` (could be more) and 1 `SUBMISSION`.

i filter `ACCESS` and i see only 1 activity log, the latest one. filtering by `SUBMISSION` gives me the correct single submission log. lastly, `ACCESS,SUBMISSION`, gives me only the `ACCESS` log with the latest timestamp _instead of all the logs thus far_.

**all said above are in the JSON below (code snippet) to illustrate the log entries (not entirely correct by the count of each activity type)**

at 00:02, i try to submit again. so let's make the `SUBMISSION` logs count to be 2. i filter `ACCESS,SUBMISSION`, but only see the latest `SUBMISSION` activity log @ 00:02.

is this intended and correct?

thank you prof!

```json
{
    "0": {
        "studentData": {
            "email": "dom@u.nus.edu",
            "courseId": "dom.u.n-demo",
            "name": "Dominic",
            "comments": "This student's name is Dominic",
            "joinState": "JOINED",
            "teamName": "Team 2",
            "sectionName": "Tutorial Group 2"
        },
        "feedbackSessionLogType": "ACCESS",
        "timestamp": 1673704385402
    },
    "1": {
        "studentData": { ...minifying as same as above },
        "feedbackSessionLogType": "ACCESS",
        "timestamp": 1673704524747
    },
    "2": {
        "studentData": { ...minifying as same as above },
        "feedbackSessionLogType": "SUBMISSION",
        "timestamp": 1673704530760
    },
    "3": {
        "studentData": { ...minifying as same as above },
        "feedbackSessionLogType": "ACCESS",
        "timestamp": 1673704534889
    },
    "name": "Feedback Test"
}
```

**Comment by damithc** [comment]
@domlimm I think this question is best directed to @daongochieu2810

**Comment by ellaella12** [comment]
Hi is anyone working on this issue? if not, can i give it a go? @daongochieu2810 @domlimm

**Comment by daongochieu2810** [comment]
@ellaella12 We are in the midst of migrating datastore entities to SQL entities, and we have not migrated feedback session logs yet. So I dont think we should proceed with this issue at the moment

**Comment by ellaella12** [comment]
noted, thank you!

**Comment by cedricongjh** [comment]
closed with https://github.com/TEAMMATES/teammates/pull/12973

Both submissions and submitted responses are now shown separately: 

![image](https://github.com/TEAMMATES/teammates/assets/67156011/5c25a703-7dac-4205-b2df-bdc57d1dcc23)
