### ISSUE TITLE
Remove student profile feature

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#12015]
As discussed in https://github.com/TEAMMATES/teammates/discussions/11785

- [x] Remove the feature
- [ ] Remove the file storage / GCS infra separately, so that it can be reverted easily in the event we need file storage infra again

**Comment by NotJamesB** [comment]
I would love to help out with some of the bugs and issues. Although I can't seem to find how to run the program, I've only worked with web-based applications and would love to know what to do after cloning to my local machine! Hope to hear back!!

**Comment by ypinhsuan** [comment]
Hi @NotJamesB, you can refer to this document to set up the developer environment https://teammates.github.io/teammates/development.html
