### ISSUE TITLE
Update Bootstrap library to 5.x

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#12014]
- Bootstrap 4 will by EOL when 2023 starts.
- As we have adopted Angular 13, we are now capable of upgrading to Bootstrap 5, through the library ng-bootstrap version 12.x.
- This is also a prerequisite to updating Angular to 14, when the time comes. (likely late Q1 2023)

**Comment by Strikker0** [comment]
hi, @wkurniawan07 I wanted to work on this issue can u assign me?

**Comment by wkurniawan07** [comment]
@Strikker0 you're welcome to try, but I will caution you that this is not a simple task to do for new contributors, and especially so for anyone with limited domain knowledge (front-end in general, Bootstrap in particular).

**Comment by Strikker0** [comment]
okey @wkurniawan07
