### ISSUE TITLE
Set generated app.admins field in build.properties to app_admin@gmail.com instead of app_admin

### ISSUE THREAD

**Issue by kevin9foong** [TEAMMATES/teammates#12020]
**Background**: 
When starting the project for the first time, the admin account by default is 'app_admin'. However, when logging in to the platform, the field is labelled 'email'. This may cause confusion for first-time developers of TEAMMATEs. 
![app.admins login](https://user-images.githubusercontent.com/55353265/212457651-895eb3be-e371-4c5f-bf97-c09b50049cdf.png)

**Motivations for fixing**: 
Improve TEAMMATEs onboarding experience for new developers.  

**Environment**: 
Release [V8.20.0](https://github.com/TEAMMATES/teammates/releases/tag/V8.20.0) dev setup 

**Steps to reproduce**
Follow the developer setup guide in the [TEAMMATEs documentation](https://teammates.github.io/teammates/development.html) under the 'As administrator' section. 

**Expected behaviour**
![Expected login info](https://user-images.githubusercontent.com/55353265/212457636-a4be5358-b423-4bde-8b34-1ae92d653e89.png)

**Actual behaviour**
![Actual login info which may cause confusion](https://user-images.githubusercontent.com/55353265/212457643-7c6e006c-c3a8-4fdb-86a3-53679f40d06d.png)

**Additional info**

This issue seems to be linked to Remove trimming of gmail.com for user accounts #11586.

**Comment by zhaojj2209** [comment]
I agree with this suggested change. Now that #11586 is resolved and all of the `@gmail.com`s have been added back to the user google IDs, I think it makes sense for the same to be done to `app_admin`.

**Comment by wkurniawan07** [comment]
You might even want to take it one step further: change the default email value in the local login page (currently `test@example.com`).

**Comment by Strikker0** [comment]
hi, can u assign me this issue?

**Comment by zhaojj2209** [comment]
@Strikker0 Feel free to submit a PR!

**Comment by NaveenJoyGit** [comment]
@kevin9foong  
changed admin email to have '@gmail.com' appended to it. Also added the 'app_admin@gmail.com' as the default email id for admin login as suggested by @wkurniawan07 

As the changes apply for the build.properties file, shall I remove it from the .gitignore and commit my changes??

**Comment by kevin9foong** [comment]
@NaveenJoyGit Hi Naveen, the build.properties file is generated based on build.template.properties in the build.gradlew under the createConfigs task, perhaps the changes should be made in the template instead

**Comment by kevin9foong** [comment]
@NaveenJoyGit 
![image](https://user-images.githubusercontent.com/55353265/216771717-200e031b-e71b-40db-825b-660f5e429582.png)
Heres the screenshot if it helps!

**Comment by NaveenJoyGit** [comment]
@kevin9foong Thanks for pointing this out. I have made the changes and it seems to be building the property file with the updated value.

**Comment by NaveenJoyGit** [comment]
@kevin9foong Raised a PR for this. Please have a review. Thanks
