### ISSUE TITLE
Testing convertSeverity in GoogleCloudLoggingService 

### ISSUE THREAD

**Issue by luishenrrique** [TEAMMATES/teammates#12038]
Multiple condition test

ID | Decision (line) | Condition | Situation for True | Situation for False
-- | -- | -- | -- | --
CD1 | 92 | severity == severity.ERROR | severity is equal to code 500 | severity is different from code 500
CD2 | 95 | severity == severity.WARNING | severity is equal to code 400 | severity is different from code 400
CD3 | 98 | severity == severity.INFO | severity is equal to code 200 | severity is different from code 200
CD4 | 98 | severity == severity.NOTICE | severity is equal to code 300 | severity is different from code 300
CD5 | 101 | severity == severity.CRITICAL | severity is equal to code 600 | severity is different from code 600
CD6 | 101 | severity == severity.ALERT | severity is equal to code 700 | severity is different from code 700
CD7 | 101 | severity == severity.EMERGENCY | severity is equal to code 800 | severity is different from code 800
CD8 | 104 | severity == severity.DEBUG | severity is equal to code 100 | severity is different from code 100

**Comment by wkurniawan07** [comment]
Not all methods require testing. Especially private methods; those are usually tested along with the public/protected methods that call them.
This particular method is not only a private method, but is also what you could describe as "writing test = copying the logic over". A method like that really does not warrant having dedicated tests.
