### ISSUE TITLE
Nav Bar Styling

### ISSUE THREAD

**Issue by shibu-g** [TEAMMATES/teammates#12037]
as a fronend developer i am not finding the nav bar as user friendly as it can be like when this page open in a desktop it shoud be open his all option from menu botton automaticly(inside the nav bar) because it have that much space but when the device width is not as much chage it to back menu button and also make some transition to feel the user we are touching and it responding 

- **Environment**: 

**Description of feature/enhancement**

**Justification**

students,developer,user

**Existing similar features and their shortcomings**

**Comment by zhaojj2209** [comment]
While we do appreciate suggestions that may improve user experience, the issue description is too vague and unreadable to facilitate any meaningful discussion on potential improvements to the navbar.

Feel free to reopen the issue after modifying the description to include more details.
