### ISSUE TITLE
Instructor help page: the page navigation menu items don't look clickable

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12042]
v8.21

Problem: The page navigation menu (see below) items don't appear to be clickable.

![image](https://user-images.githubusercontent.com/1673303/214260894-b9412617-a50c-42fa-aa13-adef5b947668.png)

Suggestion: Change the mouse pointer when hovering over them, or style them as links.

**Comment by ellaella12** [comment]
hi, can i work on this issue?

**Comment by zhaojj2209** [comment]
@ellaella12 Feel free to submit a PR for this issue.

**Comment by ellaella12** [comment]
Hi I have made a pr, may I request for some help reviewing it? Thank you!

**Comment by spiritanand** [comment]
Is this issue open? Can you assign it to me if it is?

**Comment by fsgmhoward** [comment]
@spiritanand Someone has already submitted a PR for this (check the chat history). Please hold until the PR is voided. I would suggest you to look for other issues to work on.
