### ISSUE TITLE
Navigation menu got collapsed 

### ISSUE THREAD

**Issue by Palakkgoyal** [TEAMMATES/teammates#12043]
- **Environment**: The collapsing of navbar occurs at when the width of the screen goes less than 1094px. As the display of that navbar is flex it starts collapsing after a certain point.
**Description of feature/enhancement**
I will give it a certain width so that it do not start collapsing again whenever the screen size reduce

**Justification**

The messing of navigation interrupt the UI. It will benefit the instructor as well as the students.

**Existing similar features and their shortcomings**
There is also a shortcoming in the instructor help section with the page menu. It got to be disappear after 992px
![Screenshot (369)](https://user-images.githubusercontent.com/116902573/214279921-da30b5b5-dce4-4db5-8e61-ffe9ae71db33.png)

**Comment by zhaojj2209** [comment]
Seems like the same bug as that in #11724. Note that the length of the user email needs to be taken into account as well, see below screenshot of the same screen width but with a shorter user email.
![image](https://user-images.githubusercontent.com/54243224/214504728-6c395696-763e-43c3-b00c-5af983eca4c7.png)
One way to fix this would be to set a max width for the email dropdown and use ellipsis to handle text overflow for emails past a certain length.

**Comment by Palakkgoyal** [comment]
Ya, its same. I haven't checked that before. We can also give that navigation menu a width so it won't collapse even if the screen size become small and the email and logo will automatically adjust

**Comment by shreyash184** [comment]
Hi Guys, Sorry I am not able to see the nav-bar in the website, I just checked the website to see the issue, like is the issue to confirm, but looks like the navbar is not there as shown in the screen shot, can anyone help me with this and if anyone is not working on this issue, I would love to pick this up and resolve as early as possible.

**Comment by fsgmhoward** [comment]
@shreyash184 As mentioned by @zhaojj2209 it will not occur when email length is not long enough.

However, I tried to replicate the issue with an email address of 25 chars long, it did not occur for me as well. Need further investigation for this but you could try a very long username at your dev environment to see if it fails.

**Comment by pbnormy** [comment]
Hi Guys, I'm new to open source projects and interested to start contributing so I thought I could start with this as a first issue.
Could anyone guide me in the right direction on how to navigate things in the repository and figure this out? Any help is appreciated.

**Comment by domlimm** [comment]
hello @pbnormy! for a start, you may check out the [developer documentation](https://teammates.github.io/teammates/setting-up.html) on how to get TEAMMATES running on your system.

**Comment by pbnormy** [comment]
hi @domlimm yes I did all of the steps.

**Comment by domlimm** [comment]
@pbnormy you could look at the [design docs](https://teammates.github.io/teammates/design.html). boot up TEAMMATES, navigate around and try out different features. also, you can take a look at TEAMMATES [product website](https://teammatesv4.appspot.com/web/front/home) to get a better feel too!

**Comment by NaveenJoyGit** [comment]
@domlimm @Palakkgoyal @zhaojj2209 Raised a PR for this fix. Please have a review. Thanks.
