### ISSUE TITLE
Back to top issue

### ISSUE THREAD

**Issue by luiza-esteves** [TEAMMATES/teammates#12049]
Issue title: [brief description of feature/enhancement] 

- **Environment**: 
main

**Description of feature/enhancement**
Create a button that allows you to reach the top of the screen more easily

**Justification**
The issue aims to facilitate navigation within the home

**Comment by zhaojj2209** [comment]
Thank you for the suggestion!

While we already have a back to top button for the instructor help page, I believe the addition of a back to top button for the other pages is not of high priority. TEAMMATES uses many components that are collapsible, which help to reduce page height. Depending on browser, there are also keyboard shortcuts that allow for navigating to the top of the page.

**Comment by samuelfangjw** [comment]
I don't believe it is necessary on the home page. The heuristic I'm familiar with is to consider back to top for pages >4 screens long. Think that can be reasonably applied here.

**Comment by hhdqirui** [comment]
I believe session submission page is more applicable, especially when there are many feedback questions. The back to top button can be more useful when [Per Receiver Submission](https://github.com/TEAMMATES/teammates/wiki/Per-Receiver-Submission) project is completed.

**Comment by samuelfangjw** [comment]
Thanks for the issue report. I'm closing as not planned because there is currently no compelling reason to add a back to top button on the home page.
