### ISSUE TITLE
Separate stable and unstable E2E tests for CI run

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#12059]
As mentioned in #12035, E2E tests instability is a perpetual problem that has plagued us.

However, it is noteworthy that only a small number of E2E tests are actually unstable enough to warrant rerunning up to 5 times (and sometimes still failing after that). This means that re-running all E2E tests just to have those few unstable tests passing is often time wasted.

**Proposal**

To have a separate GitHub Actions job (not a separate workflow) for unstable E2E tests.

**Comment by domoberzin** [comment]
Hi, may I work on this issue? Also is there any info on which tests are stable/unstable at the moment?

**Comment by weiquu** [comment]
Hi @wkurniawan07, do you have any examples of unstable issues? I vaguely recall the Instructor Home test being quite unstable

@domoberzin I think you can also check which tests usually have to be ran multiple times by going into a PR and checking E2E test details, then seeing which need multiple runs before passing. Will take a look at this also
