### ISSUE TITLE
Create frontend for Per Receiver Submission

### ISSUE THREAD

**Issue by hhdqirui** [TEAMMATES/teammates#12052]
Create frontend UI/UX for the [Per Receiver Submission](https://github.com/TEAMMATES/teammates/wiki/Per-Receiver-Submission) project.

**Comment by dminkovski** [comment]
Please let me know if you need help or support on this :) Would like to be part of this one 👍

**Comment by singhabhyudita** [comment]
Hi @hhdqirui , can I take up this issue?

**Comment by domlimm** [comment]
Hey @singhabhyudita, it will be good to look at other issues to work on other than this. Sorry for the confusion, have added a `committers` label for clarity.
