### ISSUE TITLE
Instructor viewing rubric question results: add back per criterion averages to the stat table

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12064]
current version: v8.22

In v8.19, the rubric question results were shown like this:

![image](https://user-images.githubusercontent.com/1673303/217835321-62f44545-f087-497f-b250-76536ca6522e.png)

Note how we show a list of averages for each criterion for each student.

In https://github.com/TEAMMATES/teammates/issues/11210 we tweaked the results display format which resulted in this column being removed.

A user wrote to us today to explain that she used this column. Specifically, she would look through these numbers and decide on a score for the student based on how the student scored for each criterion.

Suggestion: Add that column back to the relevant stats table. The values can be copied from the `Per criterion` table. We can name it `Per criterion averages`. In the csv file, each value can be put in a separate cell so that users can easily perform more analysis on them.

**Comment by RohithSurya** [comment]
Hello guys!
Can I take it up and work on it?

**Comment by zhaojj2209** [comment]
@RohithSurya Feel free to submit a PR for this issue!

**Comment by tjex** [comment]
hello. We're also working on this issue for our project assignment. 
We have successfully setup the dev environment and created a new instructor, with which we can login and see the example data.

However, we can't actually find any report view that looks like the screenshot in the OP. How do we navigate to that view, so we can review the results of our code changes?
