### ISSUE TITLE
Inconsistent spacing in headings of rubric question statistics

### ISSUE THREAD

**Issue by samuelfangjw** [TEAMMATES/teammates#12067]
- **Environment**: V8.22.0

<img width="1192" alt="Screenshot 2023-02-10 at 3 09 23 AM" src="https://user-images.githubusercontent.com/60355570/217913774-60d5d5bc-4d77-4ac4-a060-67a490a43a97.png">

There should be a space between the heading "Response Summary (of received responses)" and the info icon.

**Comment by Akashzxr** [comment]
can i work on this issue?

**Comment by samuelfangjw** [comment]
> can i work on this issue?

Sure! Please go ahead.

**Comment by Akashzxr** [comment]
@samuelfangjw iam new to opensource i love to solve this issue.can you help me out on were to find this issue on the site or to recreate this issue.

**Comment by zhaojj2209** [comment]
@Akashzxr This issue concerns the statistics that are shown to the instructor when viewing the course-wide responses to a feedback session that contains a weighted rubric question. To view the page on your local TEAMMATES build, here are the rough steps:

1. Log in as instructor
2. Create a course
3. Create a feedback session containing a weighted rubric question and publish it
4. Submit a response to the feedback session
5. View the course-wide results for the feedback session

You can find the file that contains the code by searching for the specific heading text in the codebase.

**Comment by aryanvarma7272** [comment]
hey @zhaojj2209 , Please assign this issue to me , as per your steps I have requested for instructor account , kindly accept my accept my google forms request. So that I can work on this issue as soon as possible.
Thank You.

**Comment by zhaojj2209** [comment]
@aryanvarma7272 Firstly, "request for an instructor account" is not in the steps I have listed. Instructor accounts are not meant to be used for development. Please read our [development guidelines](https://teammates.github.io/teammates/setting-up.html) and set up a development environment on your local machine instead.

Secondly, there is no need to be assigned the issue before working on it.

Thirdly, @Akashzxr has already expressed interest in working on this issue, please find another issue to work on.

**Comment by aryanvarma7272** [comment]
@zhaojj2209 , So sorry , I overlooked the instructions and in hurry I started to solve the issue.

**Comment by sumit970** [comment]
> 
> 
> - **Environment**: V8.22.0
> 
> <img width="1192" alt="Screenshot 2023-02-10 at 3 09 23 AM" src="https://user-images.githubusercontent.com/60355570/217913774-60d5d5bc-4d77-4ac4-a060-67a490a43a97.png">
> 
> 
> There should be a space between the heading "Response Summary (of received responses)" and the info icon.

Hey please assign this issue to me

**Comment by himanshuSri24** [comment]
@zhaojj2209 hey! Can I work on this issue please? I would love to help @Akashzxr on this since I'm new to open-source as well!
Do let me know if I can work on this and I'll try to fix it asap!

**Comment by zhaojj2209** [comment]
@himanshuSri24 Feel free to submit a PR for this issue!

**Comment by asn001013** [comment]
Hey @himanshuSri24! Are you still working on this? If not I'd like to solve it.

**Comment by himanshuSri24** [comment]
Hey @asn001013 , feel free to take it up. I got a lil caught up
