### ISSUE TITLE
Student viewing rubric results: average doesn't match

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12065]
v8.22
Reported by a user.
Shouldn't this be 10, as the student received 10 from all others?

![image](https://user-images.githubusercontent.com/1673303/217863563-dfdbe07c-2ffe-475a-a480-aa210f588f21.png)

Possibly related to https://github.com/TEAMMATES/teammates/pull/11984

The previous version (v8.19.2) produces 10 as the average, for the same data:

![image](https://user-images.githubusercontent.com/1673303/217864630-23cfcc3d-633a-4f07-ab60-add7ebe8c114.png)

**Comment by damithc** [comment]
Reverting https://github.com/TEAMMATES/teammates/pull/11984 (at least for the time being) is one option, given that it would also take care of #12064

**Comment by samuelfangjw** [comment]
> Reverting #11984 (at least for the time being) is one option, given that it would also take care of #12064

We have a fix for this ready, should be able to hot fix by tomorrow.
