### ISSUE TITLE
Students viewing submission form: Some answered essay questions are not shown in green

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12117]
v8.23.0

When a student is viewing a submission form that was previously submitted, some essay questions that were previously answered show up in blue ...

![image](https://user-images.githubusercontent.com/1673303/220575341-65312294-1065-42e0-b309-770e5d40ea16.png)

... although they should appear green, like this:
![image](https://user-images.githubusercontent.com/1673303/220575798-49cca71b-a34e-4c69-8f67-e6382cdc088b.png)

In fact, the green color shows up that the start briefly before changing to blue. Perhaps due to the delay in loading the text area widget?

I also have a suspicion that only the first few questions in the page are affected as they load first.

**Comment by damithc** [comment]
It would be good to fix this soon, as this can be misleading to users and can result in unnecessary support requests.

**Comment by Khalid6468** [comment]
Hi @damithc, Can I work on this?

**Comment by zhaojj2209** [comment]
@Khalid6468 Feel free to submit a PR for this issue!
