### ISSUE TITLE
Instructor viewing results of rubric questions: missing space after checkbox

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12116]
v8.23.0

![image](https://user-images.githubusercontent.com/1673303/220574090-0c3cf170-e77c-482a-a0ab-8a51aced7b09.png)

There should be a space between the checkbox and the text that follows it?

**Comment by jfish2** [comment]
Hi! As a CS instructor, I'd love to be assigned this issue to get my feet wet with open source

**Comment by Trumerik** [comment]
Hello!
Since nothing has been updated on this for the last couple of days I will also look into this issue.
