### ISSUE TITLE
Instructor viewing results of rubric questions: some students not shown in the stats table

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12115]
v8.23.0 (also present in v8.19.2)
Reported by a user.

Context: an instructor is viewing results of a session that includes  a rubric question.

This team has 5 members.
![image](https://user-images.githubusercontent.com/1673303/220570825-0c53eebe-8804-4a7c-b985-575f29699950.png)

For the rubric question, the stats tables show only 4 members for that team:
![image](https://user-images.githubusercontent.com/1673303/220571075-7e567626-e789-4535-b40f-90cb8d599a94.png)
![image](https://user-images.githubusercontent.com/1673303/220571111-411d77a7-8af8-4957-9030-edb8512e7604.png)

The problem occurs in both stat tables.

But the missing student appears in the table that shows individual responses. The student has given and received responses for the question in concern.

This is the example the user pointed out. Not sure if this is the only case or there are other cases. Not easy to find by eyeballing as the course has 500+ students.

Let me know if you need me to dig for more info.

**Comment by daongochieu2810** [comment]
@damithc can we get the datastore entities related to this issue e.g students, instructors, responses, questions? I checked the logic on both frontend and backend and it looks fine
Files related to this issue:
session-result-csv-service.ts
feedback-responses.service.ts
feedback-rubric-question-details.impl.ts

GetFeedbackResponsesAction
SubmitFeedbackResponsesAction

If the responses can still be seen but not the stats, I suspect that the bug could lie somewhere in `SessionResultCsvService::getQuestionStats` and line 98 of `session-result-csv-service.ts` where there is a TODO comment

**Comment by daongochieu2810** [comment]
In line 181 SubmitFeedbackResponsesAction, `responseDetails` are validated BEFORE `responses` can be saved/submitted, so if the response is visible then details should also be valid

**Comment by daongochieu2810** [comment]
@damithc I'm seeing only 4 responses. Are there supposed to be 5?

**Comment by damithc** [comment]
> I'm seeing only 4 responses. Are there supposed to be 5?

These are the responses received by the student. There are only 4 because the question doesn't include a self-evaluation. So, a member in a 5-person team receives at most 4 responses.
![image](https://user-images.githubusercontent.com/1673303/220643141-5d792e4d-9378-4457-b926-b1f42692befc.png)

**Comment by damithc** [comment]
> @damithc are there any exceptions coming from `src/web/app/components/question-types/question-statistics/question-statistics-calculation/rubric-question-statistics-calculation.ts`?

How to find that?

**Comment by daongochieu2810** [comment]
@damithc is it possible to search the logs with the keyword `calculateStatistics`? I feel like there is a possible exception e.g divide by 0, which causes the stats for that student to be `null`.
The `calculateStatistics` function is in `rubric-question-statistics-calculation.ts`

**Comment by wkurniawan07** [comment]
@daongochieu2810 logging doesn't work that way. You're looking at a front-end function here.

**Comment by samuelfangjw** [comment]
@daongochieu2810, we have not integrated with any error reporting tools for the frontend as far as I'm aware.

**Comment by samuelfangjw** [comment]
I believe the issue could be due to recipients having the same name.

@damithc, possible to confirm this? If my guess is incorrect, the bug is likely to be somewhere else.

**Comment by damithc** [comment]
> I believe the issue could be due to recipients having the same name.
> 
> @damithc, possible to confirm this? If my guess is incorrect, the bug is likely to be somewhere else.

@samuelfangjw yes, there are three students with the exact same name. I didn't even raise that as a possible cause because I didn't think the code is using the name as a primary key (the name is not guaranteed to be unique and should never be used as a primary key).

**Comment by damithc** [comment]
> @damithc, possible to confirm this?

Making the names unique seems to fix the problem. So, that's further confirmation of this hypothesis.

**Comment by zhaojj2209** [comment]
Will make a release for #12123 first. There is another bug related to this where there is no way to differentiate between students with the same name for the per criterion stats table, which will be documented in a separate issue.

**Comment by samuelfangjw** [comment]
@zhaojj2209, good call. Was going to open the issue myself but forgot about it. Thanks!
