### ISSUE TITLE
Instructor help page: page not scrolling to content when anchor links used

### ISSUE THREAD

**Issue by samuelfangjw** [TEAMMATES/teammates#12120]
- **Environment**: `V8.23.0`

**Steps to reproduce**
Visit https://teammatesv4.appspot.com/web/front/help/instructor?section=questions&questionId=essay-questions, or links to any other section in instructor help page.

**Expected behaviour**
Scrolls to section.

**Actual behaviour**

Does not scroll to section.

https://user-images.githubusercontent.com/60355570/220666088-13bbf85c-28ba-4c8b-bae2-b598696ece2d.mov

**Comment by SetsunaS** [comment]
Hello! Can I work on this issue?
