### ISSUE TITLE
Instructor home page: redundant padding

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12132]
In the instructor home page, this padding between the table edge and the panel edge seems redundant.

![image](https://user-images.githubusercontent.com/1673303/221340414-698a4fb6-fabc-4647-a93c-7ba07a739e5e.png)

Also, perhaps the outer border of the panel should be blue? Otherwise there is a visual anomaly at the outer edge at this specific point.
![image](https://user-images.githubusercontent.com/1673303/221340623-41a4dbdf-7f49-415f-962f-f82345d97ff2.png)

Possibly caused by subtle changes in Bootstrap versions. It's' a mere cosmetic issue. Can let it be if hard to fix.

**Comment by zhaojj2209** [comment]
Closing as the issue has been fixed as part of #12081.
