### ISSUE TITLE
Instructor enrolling students: 'Scroll down' link doesn't work

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12130]
v8.23.1 production

When enrolling students in a course, the `Scroll down` link doesn't seem to work. It scrolls the page down by a few pixels only.

![image](https://user-images.githubusercontent.com/1673303/221339711-0fba39fe-f808-4565-a46c-2d57e4326478.png)

**Comment by Bambam320** [comment]
Hi! Can I take this issue on?

**Comment by zhaojj2209** [comment]
@Bambam320 Feel free to submit a PR for this issue.

**Comment by Bambam320** [comment]
Thanks!

**Comment by noreddinelam** [comment]
I submitted a solution for this issue but I don't know why the e2e tests are not working !!

**Comment by noreddinelam** [comment]
@zhaojj2209 thanks for the help
