### ISSUE TITLE
Students answering numeric scale questions: value not shown at narrower window sizes

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12145]
v8.23, production, Chrome browser on Windows 10
Reported by a user:

When the windows is wide enough:
![image](https://user-images.githubusercontent.com/1673303/221767146-7de51a8a-c45a-4a85-9cf7-0e5c4950c40a.png)

When the window is narrow:
![image](https://user-images.githubusercontent.com/1673303/221767287-bd479f73-ba45-44c6-9064-2bdf9d748d33.png)

The workaround is to make the Window wider or to zoom out.

What's bad is that this happens at fairly reasonable window sizes, and the user will not know how to resolve it.

**Comment by weiquu** [comment]
Seems like the issue occurs for width between 769 and 800+, probably due to the `col-md-2` class on the surrounding `div`. I'll make a quick PR to resolve this.
