### ISSUE TITLE
Instructor help page: Preview as Student/Instructor buttons misaligned at small screen sizes

### ISSUE THREAD

**Issue by sumitshinde-84** [TEAMMATES/teammates#12157]
**Expected behaviour**
![Screenshot (83)](https://user-images.githubusercontent.com/110285294/222706375-f42ede34-e4d3-4ca5-af9b-7da87bee8c57.png)

**Actual behaviour**
![Screenshot (84)](https://user-images.githubusercontent.com/110285294/222706401-0c3e16ae-cbd3-4429-bba1-6e24cd98f79e.png)

**Comment by sumitshinde-84** [comment]
hey i have fix this issue check this PR #12158

**Comment by zhaojj2209** [comment]
When submitting an issue, please provide more details so as to aid others in replicating the bug.

To clarify, this is for the instructor help page, where the buttons overflow at small screen sizes.

**Comment by sumitshinde-84** [comment]
@zhaojj2209  Ok can you tell me what changes should i make to fix this issue ,
and sorry because havent provided details of issue

**Comment by sumitshinde-84** [comment]
@zhaojj2209  yes i have maked appropriate changes and i have fixed this issue also check PR https://github.com/TEAMMATES/teammates/pull/12158

**Comment by zhaojj2209** [comment]
Closing as superceded by #12275.
