### ISSUE TITLE
Lintspaces on Linux showing warnings instead of errors

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#12169]
Currently, on GitHub actions, there are cases where linting will pass for Ubuntu but fail on Windows because trailing spaces are identified as warnings instead of errors.

Ubuntu:
<img width="1037" alt="Screenshot 2023-03-06 at 12 39 34" src="https://user-images.githubusercontent.com/54243224/223020835-a62912c2-4a24-475d-82d8-d46bae455282.png">

Windows:
<img width="1029" alt="Screenshot 2023-03-06 at 12 39 14" src="https://user-images.githubusercontent.com/54243224/223020856-ce482eb0-e3a9-44c2-a64a-1de4cb322082.png">

**Comment by sumitshinde-84** [comment]
Can I work on this issue?
