### ISSUE TITLE
The page menu is hidden in the instructors help page

### ISSUE THREAD

**Issue by noreddinelam** [TEAMMATES/teammates#12221]
- **Environment**: 

**Steps to reproduce**

Just log in and navigate to the help page for instructors.

**Expected behaviour**

The expected behavior is to show the page menu somewhere.

**Actual behaviour**

The page menu is not showing at all.

See the images below : 

![image](https://user-images.githubusercontent.com/43784894/226143887-47dcbf04-b37d-4d57-9719-ed0c55535bfd.png)

![image](https://user-images.githubusercontent.com/43784894/226143889-332df0ad-1a81-44ef-ac3e-0e9f0d58d03b.png)

**Additional info**

**Comment by noreddinelam** [comment]
I can work on it too, it the same page as this issue: #12010

**Comment by zhaojj2209** [comment]
Closing as this is a non-issue. What you are seeing is the mobile view, where the page menu is hidden at small screen sizes.
