### ISSUE TITLE
Instructors editing session dates: disable calendar popup if the form is not in edit mode

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12238]
v8.25.0, production

Context: An instructor is in the Session edit page, and without clicking the `edit`  button on top-right, clicks on the calendar icon.
![image](https://user-images.githubusercontent.com/1673303/227146917-4edd422d-ac23-4289-a7f7-8050ab564fcb.png)

Problem: The calendar pops up with all dates disabled. This can make the user thinks the form is broken.

Suggested: Disable the button itself until the `Edit` button is clicked, similar to how the time selection dropdown works.

**Comment by samuelfangjw** [comment]
@zhaojj2209, has this been fixed in the user-friendliness branch?

**Comment by zhaojj2209** [comment]
> @zhaojj2209, has this been fixed in the user-friendliness branch?

This has not yet been fixed, we can leave this issue up.

**Comment by pgfrank1** [comment]
Could I be assigned this issue? I've been looking for an issue to work on for my Enterprise Java course.

**Comment by zhaojj2209** [comment]
> Could I be assigned this issue? I've been looking for an issue to work on for my Enterprise Java course.

@pgfrank1 While TEAMMATES indeed uses Java for the backend, this particular issue is related to the frontend, which uses Angular. Therefore, this may not be a suitable pick for your Enterprise Java course. Feel free to work on the issue regardless, though!

**Comment by sumitshinde-84** [comment]
Is there anyone who is working on it , if not please assign it to me.

**Comment by weiquu** [comment]
Hi @pgfrank1, do let us know if you'll be working on this issue! Else, we'll assign it to @sumitshinde-84 (:

**Comment by pgfrank1** [comment]
@weiquu 

Yes, I have been working on it. Thank you for asking!
