### ISSUE TITLE
Update tzdb version to 2023b or newer

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#12259]
The latest version `2023b` was released a few days ago.

Guide to update: https://github.com/TEAMMATES/teammates-ops/blob/master/maintainer-guide.md#timezone-database-update

**Comment by cpeffer** [comment]
Hey I would like to take this on! Is it alright if I update to the most recent version 2023c?

**Comment by samuelfangjw** [comment]
@cpeffer, sure!

**Comment by aorlandou** [comment]
Hello, is it okay if I take on this issue?

**Comment by kevin9foong** [comment]
> Hello, is it okay if I take on this issue?

@aorlandou sure! looking forward to a PR

**Comment by weiquu** [comment]
I believe this might be causing some issues with the E2E tests - will look into it and probably open a PR later tonight so we can resolve it quickly
