### ISSUE TITLE
Modify minimum page height to factor in footer height

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#12265]
Currently, the minimum page height only factors in the header height and does not factor in the footer height, causing some pages to scroll vertically even though the content fits within the browser window.

https://user-images.githubusercontent.com/54243224/227849609-6b715809-e625-4cc2-bf8d-c6059a1426a2.mov

Suggestion: the footer height should be added in the calculation of the main content's minimum width. Take note that the height of the footer differs for desktop and mobile screen sizes, so that will have to be taken into account as well.

**Comment by destroyer806** [comment]
Hello! I would like to work on this issue

**Comment by domlimm** [comment]
@destroyer806 Feel free to submit a PR for this issue 👍🏻
