### ISSUE TITLE
Instructor edit sessions page: Fix add question button overflow

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#12269]
At screen widths smaller than 379px, the "Add Question" buttons overflow to the next line.
<img width="264" alt="Screenshot 2023-03-27 at 16 14 18" src="https://user-images.githubusercontent.com/54243224/227891449-6910b93d-a046-4966-a642-ec05b4b0d867.png">

The same issue exists for the instructor help page, for widths smaller than 411px.
<img width="255" alt="Screenshot 2023-03-27 at 16 15 15" src="https://user-images.githubusercontent.com/54243224/227895300-25f27709-c48c-48f7-a3e3-4846b8c30826.png">

One way to fix this is to reduce the padding between components at smaller screen sizes.

**Comment by amanx123** [comment]
Assign me so that I can work on this.

**Comment by yenniejunvu** [comment]
Hi! I'm a university student who would like to attempt this, and I am new to open source code.

I believe was able to recreate the issue:
<img width="125" alt="recreate_issue" src="https://user-images.githubusercontent.com/89651035/228066764-7e3fb8bf-d64e-49be-9407-3e6b34979522.png">

**Comment by zhaojj2209** [comment]
@yenniejunvu Feel free to submit a PR for this issue.

@amanx123 You have already expressed interest in another issue, as such we will give the opportunity to someone else. Also, please be nice, we will not assign you the issue just because you demand to be assigned one.

**Comment by singhabhyudita** [comment]
Hi, @yenniejunvu are you working on this one? If not I would like to take up this issue.

**Comment by weiquu** [comment]
Hi @singhabhyudita, please feel free to go ahead and submit a PR for this issue

**Comment by singhabhyudita** [comment]
Sure @weiquu, I'm on it!
