### ISSUE TITLE
Instructor getting started page: Fix scroll to top

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#12267]
Currently, clicking any of the "Back to top" buttons on the getting started page will cause the page to jump directly to the top of the page (see below video).

https://user-images.githubusercontent.com/54243224/227862199-93c2f332-8760-4ea6-a48c-f1c3622a5049.mov

Suggested fix would be to use the `PageScrollService` to handle scrolling.

**Comment by amanx123** [comment]
i would like to work on it , assign me please

**Comment by zhaojj2209** [comment]
@amanx123 Feel free to submit a PR for this issue, we do not assign issues to contributors.

**Comment by alemendoza-v** [comment]
Hello I would like to contribute to this issue, how do I clone that brach? I cant find it in the branch list

**Comment by zhaojj2209** [comment]
@alemendoza-v The issue was reported back when the behaviour was different between the master branch and prod, and the prod version has since been updated. The issue description has been edited accordingly; there is no need for you to clone any separate branches.

Also, note that issues with the `good first issue` label are for first-time contributors only. You have already expressed interest in working on a different issue, so if you are interested in fixing that issue, you should not pick up this one at the same time.

**Comment by itsAfnanAlam** [comment]
Hello! I'm interested in contributing and I noticed that issue #12267 is still open. Is it okay if I work on this issue?

**Comment by EuniceSim142** [comment]
Hi @alemendoza-v, can we check if you plan to work on this issue? If not, we'll give @itsAfnanAlam the go-ahead.

**Comment by alemendoza-v** [comment]
Hello, im sorry ive been working on school projects and have been busy. Go ahead :)
