### ISSUE TITLE
Make instructor getting started page more prominent

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#12268]
Currently, the only way to access the instructor getting started page is via an easy-to-miss link in the instructor help page:
<img width="761" alt="Screenshot 2023-03-27 at 15 12 01" src="https://user-images.githubusercontent.com/54243224/227871207-e79901ca-63ba-4e8d-83b0-945ef231549f.png">

As the getting started guide is useful for instructors using TEAMMATES for the first time, it would be good if access to the page can be made easier. My suggestion would be to change the "Help" tab on the instructor page into a dropdown containing both the getting started page and the instructor help page.

<img width="543" alt="Screenshot 2023-03-27 at 15 33 47" src="https://user-images.githubusercontent.com/54243224/227872003-ae31e0e6-4f61-4f96-bf0f-3f48830f0adb.png">

Other ideas are also welcome.

**Comment by samuelfangjw** [comment]
Could explore maybe showing this message when an instructor joins for the first time as well.

**Comment by zhaojj2209** [comment]
My bad for missing this out, the getting started guide is accessible from the instructor home page as well, and is only shown to new users (do not have any courses other than the demo course).
<img width="1243" alt="Screenshot 2023-03-28 at 14 12 37" src="https://user-images.githubusercontent.com/54243224/228144756-b0452396-9efe-420c-8b01-9ef1149569d5.png">

Nonetheless, it would be good to make the page easier to access for the sake of instructors who may still require guidance even though they already have some courses.

**Comment by singhabhyudita** [comment]
Hi @zhaojj2209 , I like your idea of a dropdown inplace of the Help tab. Can I take up this one?

**Comment by zhaojj2209** [comment]
@singhabhyudita Feel free to submit a PR for this issue.

**Comment by singhabhyudita** [comment]
@zhaojj2209 sure I'm on it!

**Comment by zhaojj2209** [comment]
Perhaps change the "Help" in the dropdown to "Instructor Help"?
