### ISSUE TITLE
Instructor home page: Fix alignment of "Add New Course" button

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#12278]
On smaller screen sizes, the "Add New Course" button becomes misaligned:
![photo_2023-03-28 14 00 27](https://user-images.githubusercontent.com/54243224/228150211-de7f3d51-f5b2-46f2-87c1-0cb7e2f7a67c.jpeg)

Suggested fix: Make the button center-aligned so that it will be level with the "Sort By" button group at any screen size.

**Comment by meet0806** [comment]
Heyy @zhaojj2209 Can I pick up this issue?

**Comment by domlimm** [comment]
@meet0806 Sure go for it!
