### ISSUE TITLE
Instructor home page: Remove links to video tour

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#12277]
Currently, new instructors (no courses other than demo course) are directed to the video tour on the home page even though it has already been removed as part #10481: 
<img width="1243" alt="Screenshot 2023-03-28 at 14 12 37" src="https://user-images.githubusercontent.com/54243224/228147854-253731f6-3031-42d6-85e0-d62ba150d1da.png">
The video tour is also accessible from the getting started guide:
<img width="611" alt="Screenshot 2023-03-28 at 14 27 44" src="https://user-images.githubusercontent.com/54243224/228148017-a0b2b383-3410-45aa-83dc-3c8e55725bce.png">

We should remove both links to the video tour.

**Comment by wkurniawan07** [comment]
@zhaojj2209 the video tour is outdated and should have been removed in #10481

**Comment by zhaojj2209** [comment]
> @zhaojj2209 the video tour is outdated and should have been removed in #10481

Got it, so we should remove these instances altogether. Will update the issue title/description accordingly.

**Comment by ArslanYM** [comment]
Can i work on this?

**Comment by anuth212** [comment]
Hi, I submitted two PR's which should fix this issue

**Comment by samuelfangjw** [comment]
@anuth212, please keep to 1 PR for this issue.

**Comment by anuth212** [comment]
Sorry about that! I'll make one new PR for both issues

**Comment by zhaojj2209** [comment]
> Sorry about that! I'll make one new PR for both issues

That is not what @samuelfangjw meant, please read the comment more closely. Please do not make two PRs. Even though it may seem like there are two parts to it, they are not two separate issues, so please make one and only one PR with fixes for both parts included. 

Please also read our [contribution guidelines](https://teammates.github.io/teammates/process.html#step-4-submit-a-pr) before submitting any PRs. None of your submitted PRs so far have followed them. In particular, please remove the space between [ and # in the title.

Also, while not checked by the bot, please also title your PR such that it is the same as that of this issue.

**Comment by luffingluffy** [comment]
Hello, can I check whether this issue is still open? If so, I can submit a PR for it.

**Comment by weiquu** [comment]
Hi @anuth212, will you still be working on this issue? If not, we'll let @luffingluffy take it

**Comment by anuth212** [comment]
Hi! Yes, i’d still like to work on this issue. I will work on fixing my PR and submitting it soon. @weiquu

**Comment by anuth212** [comment]
I think I have fixed both parts correctly with this new PR, but please let me know if I have done something wrong. Thank you for your help!
