### ISSUE TITLE
Instructor edit sessions page: Fix preview sessions button overflow

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#12275]
At screen widths of less than 378px, the "Preview for Instructor" button overflows to the next line.
<img width="259" alt="Screenshot 2023-03-27 at 16 14 34" src="https://user-images.githubusercontent.com/54243224/228117741-6677b3ce-a95e-4293-9a71-dda0d499c300.png">

The same issue exists on the instructor help page, where the "Preview for Instructor" button overflows at screen widths smaller than 410px, and both buttons overflow at widths smaller than 388px.
<img width="284" alt="Screenshot 2023-03-27 at 16 17 09" src="https://user-images.githubusercontent.com/54243224/228117749-29e3bf59-85d3-42ce-9cf4-f3d83e920254.png">

One way to fix the issue is to align the buttons and dropdowns in column instead of row for small screen sizes.

**Comment by PUJAmangale1221** [comment]
Hey Maintainers, I want to contribute to this issue could you please help me to go forward..!!

**Comment by Oshanik22** [comment]
Hi, first-time contributor here. @PUJAmangale1221 are you working on this? If not i would like to take it up :)

**Comment by itsAfnanAlam** [comment]
@PUJAmangale1221 @Oshanik22 Hey, is anyone of you working on this? If not then can I take it up?

**Comment by zhaojj2209** [comment]
@itsAfnanAlam This issue is for first time contributors only, please take a look at other issues instead.

**Comment by Zxun2** [comment]
Hello! May i ask if this issue has been taken? I'll like to work on this.

**Comment by weiquu** [comment]
Hi @Zxun2, feel free to submit a PR for this issue
