### ISSUE TITLE
Docs: Upgrade to latest MarkBind version

### ISSUE THREAD

**Issue by jovyntls** [TEAMMATES/teammates#12271]
MarkBind is the static-site generator currently used in the TM docs. The docs are on MarkBind v3.1.1; the latest MarkBind version is v4.1.0, with v5 on the horizon.

The new releases of MarkBind have several new feature additions and bug fixes - full release notes can be found [here](https://github.com/MarkBind/markbind/releases).

**Comment by meet0806** [comment]
Heyy @jovyntls @samuelfangjw 
Can I pick up this issue?

**Comment by samuelfangjw** [comment]
> Heyy @jovyntls @samuelfangjw
> Can I pick up this issue?

Sure please go ahead

**Comment by wkurniawan07** [comment]
@meet0806 can I request for you to work on something else? There are plenty of other good issues for first timers.
Reason being this issue is raised by, and is better to be worked on by, people who are actually authors of the MarkBind library itself.

**Comment by samuelfangjw** [comment]
@jovyntls are you actively working on this?

**Comment by jovyntls** [comment]
@samuelfangjw Not currently, the CS3281 batch are looking into it: @yucheng11122017 @EltonGohJH @lhw-1 @itsyme

**Comment by yucheng11122017** [comment]
Hi we will work on it after v5 of Markbind has been released
