### ISSUE TITLE
Instructor edit session page: Fix custom visibility table overflow

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#12276]
At screen widths of smaller than 400px, the custom visibility table overflows, as shown below:
<img width="267" alt="Screenshot 2023-03-27 at 15 58 04" src="https://user-images.githubusercontent.com/54243224/228140993-50e96df8-186b-4b57-85c6-19eebbce2aad.png">

One way to fix this would be to make the table horizontally scrolling, but it would be good to have the entire table fit within the screen width as well.

**Comment by Mrityunjaydeepak** [comment]
Hey, i would like to work on this!

**Comment by weiquu** [comment]
Hi @Mrityunjaydeepak, sure! Feel free to submit a PR for this issue (:

**Comment by Oshanik22** [comment]
Can I work on this? I'm a first-time contributor and having some difficulty finding a good issue to start with, so I'm also open to recommendations for working on any other issue.

**Comment by zhaojj2209** [comment]
@Oshanik22 We recommend any of the issues with the `good first issue` label. Feel free to submit a PR, but if someone else has previously expressed interest in working on the issue, do check with them if they are still working on it first before opening a PR.

Also, as `good first issue`s are for first-time contributors only, note that you can only pick one of them to work on. For subsequent issues, we recommend issues with the `help wanted` label.

**Comment by Oshanik22** [comment]
Hi, @zhaojj2209, thanks for the quick response. @Mrityunjaydeepak are you working on this? If not, I would like to take this up :)

**Comment by Mrityunjaydeepak** [comment]
@Oshanik22  yes, you can take it i am currently working on something else.

**Comment by Oshanik22** [comment]
thanks

**Comment by guivilela7** [comment]
Hi, I'm a first time contributor and would like to work on this issue if possible. @Oshanik22 are you still working on this or could I take it?

**Comment by domlimm** [comment]
@guivilela7 Feel free to submit a PR.

**Comment by nncha96** [comment]
Is this one still open? Can I work on it?

**Comment by jasonqiu212** [comment]
Hi @nncha96, Feel free to submit a PR for this issue!

**Comment by RohithSurya** [comment]
Hey guys!! I would like to submit a PR for this issue
I found how to fix the issue too
