### ISSUE TITLE
Student home page: Make it easier to navigate courses

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#12287]
For students who link multiple courses to the same account, the number of courses on the home page may build up over the years, making it difficult to find a specific course.

Suggestion: provide students with a way to hide a course, or remove a course from their account altogether. After hiding/removing the course, students should still be able to access the session submit form/session results via the links sent to them in session opening/results published emails.

Edit: After discussion, we have decided to go with frontend changes to improve the ease of navigating around the student home page, by making cards collapsible and allowing sorting of courses by creation date.

**Comment by zhaojj2209** [comment]
> @zhaojj2209 do you mean a way for a student to undo a previous 'join' action?

After discussion with @samuelfangjw, we propose two possible approaches:
1. "Hide" the course from view; these hidden courses can be found in a separate table at the bottom of the page. This is similar to archiving courses/soft-deleting sessions on the instructor end.
2. Unlink the student's account from the course altogether (same as the undo approach Prof mentioned). The student would then no longer be able to access the course from their own account, but they should still be able to access the course sessions via the session links.

Both would help to reduce clutter on the student home page, the main difference is that students will still be able to access the course from their account for the first approach.

**Comment by zhaojj2209** [comment]
Thanks for your input! We can definitely make some frontend-only changes such as making course cards collapsible and improving sort logic. Currently the only sort options are course ID and course name, we can perhaps consider adding sort by course creation date as well.

**Comment by gordonscottkolb** [comment]
I'd like to take a shot at this. Would you mind sharing what files I can find the logic and UI code for the course ID and course name sorting?

**Comment by weiquu** [comment]
> I'd like to take a shot at this. Would you mind sharing what files I can find the logic and UI code for the course ID and course name sorting? 

Hi @gordonscottkolb, have you tried finding the files by yourself first? Learning how to navigate a larger code base is a good skill to pick up as an OSS contributor, and one which we would like to cultivate in our contributors. Of course, do let us know if you face any troubles while doing so, and we will be happy to help.

> (Specifically, I would just like to try adding the functionality to sort by course creation date, if possible)

I think it would be a good idea to fix the whole issue together (i.e. both sort and collapsible cards). (@zhaojj2209, let us know if this is okay, or if the issue is still under discussion.)

**Comment by zhaojj2209** [comment]
> I think it would be a good idea to fix the whole issue together (i.e. both sort and collapsible cards). (@zhaojj2209, let us know if this is okay, or if the issue is still under discussion.)

Let's go with both sort by creation date and collapsible cards. Will modify the issue title accordingly.

**Comment by Zxun2** [comment]
Hello! May i check if this issue is available? I'll like to work on this.

**Comment by weiquu** [comment]
Hi @Zxun2, feel free to submit a PR for this issue
