### ISSUE TITLE
Instructor courses page: Improve display of create course card header

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#12280]
Currently, the display of the create course card header doesn't work well on mobile:
![photo_2023-03-28 14 00 05](https://user-images.githubusercontent.com/54243224/228157687-edb7f7ae-863d-4d23-8403-26bc5538607e.jpeg)

Suggestion: switch to column format on mobile screen sizes, similar to the card headers for the instructor edit page (example below).

<img width="346" alt="Screenshot 2023-03-28 at 15 07 46" src="https://user-images.githubusercontent.com/54243224/228158112-ec4f4b6c-d0ab-4bea-8176-b63d7caa34a1.png">

**Comment by ianupam001** [comment]
Hello @zhaojj2209 , I am first time contributor can I make changes regarding this issue ?

**Comment by domlimm** [comment]
@ianupam001 Hi, sure go ahead!

**Comment by Oshanik22** [comment]
Hi @ianupam001, are you working on this? If not then I would like to work on it, please. I am a first-time contributor :)

**Comment by domoberzin** [comment]
Hello, could I work on this issue?

**Comment by domlimm** [comment]
@domoberzin Feel free to submit a PR! 👍🏻
