### ISSUE TITLE
Admin notifications page: Fix notifications table overflow

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#12288]
At small screen widths (<500px), the notifications table overflows:
<img width="308" alt="Screenshot 2023-03-28 at 16 36 04" src="https://user-images.githubusercontent.com/54243224/228181546-bea30451-63e6-4c24-9806-4001feb02dc7.png">

One way to fix this would be to make the table scroll horizontally.

**Comment by yujioshiro** [comment]
Hello,

Are these issues open to anyone? I'm a second-year cs student in the US and have no relationships with TEAMMATES or NUS. I'd like to jump on this issue, but not sure if I'm allowed to contribute.

**Comment by weiquu** [comment]
Hi @yujioshiro, feel free to submit a PR for this issue!

**Comment by yujioshiro** [comment]
Thank you @weiquu! I was actually setting up the environment earlier today and followed the development guidelines, but am stuck on the section "Logging in to a TEAMMATES instance."

When I go to `/web/admin/home`, I get a toast-like notification that reads "You are not authorized to view the page." Following the directions, I believe the build.properties file is the issue. The problem is, I don't have a `build.properties` file and can't find a guide on how to set one up for the teammates repository.

How would I set that up? Or is that not a mandatory step for this specific issue?

**Comment by domlimm** [comment]
Hey @yujioshiro! You should follow the steps starting from [here](https://teammates.github.io/teammates/setting-up.html) and once you reach the bottom of the page, click the link in the line that says `Proceed to the development routine as outlined in this document.`. Let us know if you face any more problems

**Comment by yujioshiro** [comment]
@domlimm I tried to start over from the beginning and set everything up. So I did miss the step about the Datastore emulator and the full-text search service before. I am trying to complete the Datastore emulator setup, but again I am missing the `build.properties`. I'm not sure how to set that up or if that's supposed to be templated with a script.

**Comment by yujioshiro** [comment]
Here are screenshots showing the runDatastoreEmulator command doesn't specify a port

<img width="811" alt="image" src="https://user-images.githubusercontent.com/19900334/231941864-0974c3c6-498f-42db-af3a-e3b82660eef7.png">
<img width="565" alt="image" src="https://user-images.githubusercontent.com/19900334/231941894-074e19ce-7d11-4021-9f41-75ec98c9800b.png">

**Comment by weiquu** [comment]
Hi @yujioshiro, can I check if you're using Docker?

Can you also try to run `./gradlew serverRun` and also `npm run start` and screenshot the webpage that you see?

**Comment by zhaojj2209** [comment]
@yujioshiro Try running `./gradlew createConfigs` again. `build.properties` should be generated automatically.

If that does not work, you can create the `build.properties` and `build-dev.properties` files manually by duplicating the `build.template.properties` and `build-dev.template.properties` files respectively and renaming them. These files can be found in the `src/main/resources` folder.

**Comment by yujioshiro** [comment]
So I tried setting it up again, unfortunately it didn't work.
So then I tried using docker and I am still running into the same issue (seeing the "You are not authorized to view the page." notification). It looks like the `build.properties` file is being templated correctly. Here are some screenshots...

after starting database instance:
<img width="800" alt="image" src="https://user-images.githubusercontent.com/19900334/232177679-28213125-09e6-4c22-976d-f2ccfccd3ec1.png">

after running `npm run start`:
<img width="800" alt="image" src="https://user-images.githubusercontent.com/19900334/232177729-239e41af-b43a-4274-a466-500c5d9c5590.png">

port 8080 after running `./gradlew serverRun`:
<img width="800" alt="image" src="https://user-images.githubusercontent.com/19900334/232177739-47534115-2d4b-445f-9c9f-7ad9555390fd.png">

I'm sure the 404 is the issue, but I can't find anything in the troubleshooting documents about it.

**Comment by domlimm** [comment]
@yujioshiro Hello, this is because there's no such page as `http://localhost:8080/`.

Assuming you have both your frontend and backend started and running, you should try accessing `http://localhost:4200/web/admin/home`. Thereafter, log in with `app_admin`. And you should be good.

**Comment by yujioshiro** [comment]
@domlimm oh 🤦‍♀️ lol

When I go to that url, I still get this:
![admin-error](https://user-images.githubusercontent.com/19900334/232179810-b3ddbe78-7f6b-44de-a019-0b4ad929f616.gif)

And just to confirm, both the frontend and backend are running correctly:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/19900334/232179889-be036a01-1975-49e3-bc84-6434e59ce81e.png">

**Comment by domlimm** [comment]
@yujioshiro That's odd.. When I run `./gradlew createConfigs` it's fine. Does zhaojj's suggestion help?

**Comment by yujioshiro** [comment]
@domlimm 
Here's my terminal after runnning `./gradlew createConfigs`:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/19900334/232180091-57faa316-8690-46fa-89b4-e4c4921b1049.png">

And then confirming the `build.properties` and `build-dev.properties` are properly created:
<img width="260" alt="image" src="https://user-images.githubusercontent.com/19900334/232180130-f280af57-9eee-4413-951d-0c0734d060f0.png">

**Comment by domlimm** [comment]
@yujioshiro Could you please use [github's gist](https://gist.github.com/) and add the contents of your `build-dev.properties` and `build.properties` and share them? Thanks!

**Comment by weiquu** [comment]
> @domlimm oh 🤦‍♀️ lol
> 
> 
> 
> When I go to that url, I still get this:
> 
> ![admin-error](https://user-images.githubusercontent.com/19900334/232179810-b3ddbe78-7f6b-44de-a019-0b4ad929f616.gif)

It appears that you're trying to access the admin page without having logged in... have you tried logging in as app_admin?

**Comment by yujioshiro** [comment]
@domlimm I can just share the link of the gist here? I've never used gist, so not sure if the contents of the .properties files needs to remain secret.

@weiquu I have not. Every time, I click on the top right Login button, the page refreshes and nothing new happens

**Comment by domlimm** [comment]
@yujioshiro I believe it is okay to share it. Anyone is able to generate the contents.

**Comment by yujioshiro** [comment]
@domlimm good point! lol

https://gist.github.com/yujioshiro/0ace9b0346121a2bc81959d1c4485ac0

**Comment by domlimm** [comment]
In build.properties, could you please try changing this to the one below:
```
# This is the list of Google ID of users who have access to admin features of the system.
# This is not necessarily the same as admin roles defined in Google Cloud IAM.
# Separate with commas for multiple values with no leading/trailing spaces.
app.admins=app_admin@gmail.com
```
Try this:
```
# This is the list of Google ID of users who have access to admin features of the system.
# This is not necessarily the same as admin roles defined in Google Cloud IAM.
# Separate with commas for multiple values with no leading/trailing spaces.
app.admins=app_admin
```

**Comment by yujioshiro** [comment]
@domlimm Edited it and then restarted both frontend and backend servers and getting same issue

**Comment by yujioshiro** [comment]
Here's the browser console if it helps:
<img width="518" alt="image" src="https://user-images.githubusercontent.com/19900334/232184385-29e891b4-af2f-4d34-8bd7-767034f87ef3.png">

**Comment by domlimm** [comment]
@yujioshiro Try accessing http://localhost:4200/web/admin/home.

You will be brought to this page, log in with `app_admin`.
![image](https://user-images.githubusercontent.com/46486515/232185271-3b6016b3-3ada-458d-858c-2839fe59671c.png)

You should see this page after you've logged in.
![image](https://user-images.githubusercontent.com/46486515/232185205-c44a965f-077f-47aa-a74b-598ab3d83270.png)

**Comment by yujioshiro** [comment]
@domlimm Sorry, I should have clarified that the error is occurring when I visit that url

![admin-error](https://user-images.githubusercontent.com/19900334/232187426-919af71e-2bd6-4b83-9893-6578ee1689e4.gif)

**Comment by wkurniawan07** [comment]
@yujioshiro please do not pollute the issue thread. Open a help request in the discussion forum and we can take it from there.
