### ISSUE TITLE
Instructor sessions page: Fix deleted feedback sessions table overflow

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#12281]
At small screen sizes (<520px from my own testing), the deleted feedback sessions table overflows:
<img width="314" alt="Screenshot 2023-03-28 at 15 21 58" src="https://user-images.githubusercontent.com/54243224/228159377-33dac13e-5e21-4ac2-9413-780f6fdf3114.png">

The background colour of the cells in the "Actions" column also does not fill the whole cell height.

Suggested fixes:
- Make the table scroll horizontally
- Make the background colour of the cells in the "Actions" column fill the whole cell

**Comment by Sho-Shoo** [comment]
Hi TEAMMATES development team! I am a first-time contributor to the TEAMMATES project and would like to contribute to fixing this issue. Could you please assign this issue to me?

**Comment by domlimm** [comment]
@Sho-Shoo Hello, feel free to submit a PR for this issue 👍🏻 According to our [development workflow](https://teammates.github.io/teammates/process.html#step-1-pick-an-issue-to-fix), we do not assign issues to contributors.
