### ISSUE TITLE
Instructor sessions page: Fix create feedback session card header

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#12282]
The create feedback session card header breaks at small screen widths.

At <800px:
<img width="500" alt="Screenshot 2023-03-28 at 15 32 02" src="https://user-images.githubusercontent.com/54243224/228162486-f35eae6f-838b-46b9-9df2-00bbdf62cf37.png">

At mobile breakpoints (<767px):
<img width="292" alt="Screenshot 2023-03-28 at 15 32 30" src="https://user-images.githubusercontent.com/54243224/228162427-ad214dfb-b3ef-41cc-9241-6f5c67b3717a.png">

There are multiple ways to fix this, including but not limited to:
- Splitting the components into two rows at small screen widths
- Reducing the space between the dropdown and the info button

**Comment by domlimm** [comment]
@vaheaslanyan Hello, sure please go ahead!
