### ISSUE TITLE
Usage statistics and logs page: Improve date/time input on mobile

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#12289]
The display of the admin/maintainer usage statistics/logs pages on mobile are currently as follows:
![photo_2023-03-28 14 00 34](https://user-images.githubusercontent.com/54243224/228182168-0acaf68e-5f60-46f6-a4a5-c822943a59df.jpeg)

![photo_2023-03-28 14 00 37](https://user-images.githubusercontent.com/54243224/228182185-38a1ed54-780f-433c-a820-58774706ad95.jpeg)

The date/time inputs for both pages can be improved to be similar to the admin sessions page (shown below):
<img width="261" alt="Screenshot 2023-03-28 at 15 19 15" src="https://user-images.githubusercontent.com/54243224/228182277-6bda5cf6-f1d9-4d2a-8c11-e3e898ea0f09.png">

**Comment by aorlandou** [comment]
I would like to work on this issue.

**Comment by zhaojj2209** [comment]
@aorlandou Feel free to submit a PR for this issue.
