### ISSUE TITLE
email alerts: omit join link if already joined

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#1229]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on October 08, 2013 09:03:48_

Otherwise, students keep clicking on it. At least we should reword the email to reduce such unnecessary clicking.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1230_

**Comment by RatulGhosh** [comment]
For solving this issue we can keep a field (for checking whether the student has already joined the course or not) for each student enrolled for that course and emails will only be send to those students who have still not joined the course. We can also add a line, saying that ignore if already joined in the email body.

**Comment by damithc** [comment]
I'd rather not add a new field if not absolutely necessary.

**Comment by thyageshm** [comment]
I think the googleid of the student is null or "" if the student is unregistered. Once the student joins, the googleid field will be populated. I think this can be used here

**Comment by YongJieYongJie** [comment]
I'm currently trying to learn about the email system, so I thought I'll contribute what I've gathered by **working up the call hierarchy** from the constants in `EmailTemplates.java`:

We can use `isYetToJoinCourse()` in `Emails.java`, which **already performs the check**:
 `return s.googleId == null || s.googleId.isEmpty();`

Also, `getUnregisteredStudentsForCourse()` in `StudentsDb.java` **duplicates** the null or empty checks and perhaps can be refactored away

**Comment by damithc** [comment]
old issue. closing.
