### ISSUE TITLE
Admin logs page: Fix overflow of "Clear all" button

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#12291]
At screen sizes of <500px, the "Clear all" button overflows:
![photo_2023-03-28 14 00 46](https://user-images.githubusercontent.com/54243224/228185460-b4df5142-7d76-4251-8d81-26e8552487c2.jpeg)

One possible fix is to place the button on a separate row altogether.

**Comment by DeliaBarron** [comment]
Hello! Can i get this issue?

**Comment by domlimm** [comment]
@DeliaBarron Hello! Yes sure please go ahead and work on this issue 👍🏻
