### ISSUE TITLE
Instructor view session results (course-wide): Improve display of no-response card header

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#12290]
The current display of the no-response card header doesn't work well on mobile:
![photo_2023-03-28 14 00 24](https://user-images.githubusercontent.com/54243224/228184114-8d2260e5-5394-4deb-851e-285d200d7467.jpeg)

Suggestion: switch to column format on mobile screen sizes, similar to the card headers for the instructor edit page (example below).
<img width="346" alt="Screenshot 2023-03-28 at 15 07 46" src="https://user-images.githubusercontent.com/54243224/228184558-b1135519-70e9-495b-924f-30e8a6448f83.png">

The card header should also be changed to be a button semantically so that it can be picked up by screen readers. For the approach, do refer to the card headers in the instructor edit sessions page.

**Comment by rhyses-pieces** [comment]
@zhaojj2209 Hiya, I'm setting up my local dev environment for this project and I'm interested in working on this issue.

**Comment by zhaojj2209** [comment]
@rhyses-pieces Feel free to submit a PR for this issue.
