### ISSUE TITLE
Submit feedback page: Long names lead to cutoff

### ISSUE THREAD

**Issue by ong6** [TEAMMATES/teammates#12305]
- **Environment**: 
Teammates v8.25
Macos 13.1 - Arc Browser

**Steps to reproduce**
1. Navigate to submit feedback page
2. Select a long name:
<img width="390" alt="image" src="https://user-images.githubusercontent.com/19247856/228780052-a6c604f7-a298-49ec-a1ab-971ae169c4e5.png">

It overflows into the dropdown icon.

**Expected behaviour**

It should wrap or get cut off.

**Actual behaviour**
n/a

**Additional info**

**Comment by zhaojj2209** [comment]
Thanks for catching the issue!

We have merged PR #12179 to fix this as part of our ongoing user-friendliness project; we will close this issue once the fix has been released.

**Comment by zhaojj2209** [comment]
Closing as issue has been fixed and deployed.
