### ISSUE TITLE
Modified session timing modal does not use updated session name

### ISSUE THREAD

**Issue by samuelfangjw** [TEAMMATES/teammates#12307]
- **Environment**: V8.25.0

**Steps to reproduce**

Copy a feedback session and rename it. In this case, "Project Presentation Week 10" has been renamed to "Project Presentation Week 11". Ensure the opening date of the session is sometime in the past (> 2hrs).

<img width="509" alt="Screenshot 2023-03-30 at 8 28 04 PM" src="https://user-images.githubusercontent.com/60355570/228835838-62e3b3d7-5194-4f64-bd0c-ffb05fb7e3ec.png">

**Expected behaviour**

Session name is the updated session name.

**Actual behaviour**

<img width="1279" alt="Screenshot 2023-03-30 at 8 22 18 PM" src="https://user-images.githubusercontent.com/60355570/228834402-c72fa373-51d9-416b-9414-1db7ca74619a.png">

Session name is the old session name. This makes it seem as if the older session was modified and not the newer one.

**Comment by meet0806** [comment]
Hey @samuelfangjw can I look into this issue?
