### ISSUE TITLE
Popover appears in front of modal blocking buttons

### ISSUE THREAD

**Issue by samuelfangjw** [TEAMMATES/teammates#12314]
- **Environment**: 

V8.25.0

- **Issue**

![telegram-cloud-photo-size-5-6138667426573826030-y](https://user-images.githubusercontent.com/60355570/229011379-4b0019e1-0f89-4255-a185-75f3a5720d37.jpg)

**Comment by aniatt** [comment]
I'm a first time contributor and would like to address this bug.

**Comment by zhaojj2209** [comment]
@aniatt Feel free to submit a PR for this issue.

**Comment by mud1tx** [comment]
@samuelfangjw How can I generate this issue?

**Comment by Mex7180** [comment]
Hi, is anyone working on this issue? If not I'd like to give it a try. :D

**Comment by jasonqiu212** [comment]
Hi @Mex7180, Feel free to submit a PR for this issue :)
