### ISSUE TITLE
Instructor sending submission reminders: missing space between checkbox and label

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12313]
v8.15, production

![image](https://user-images.githubusercontent.com/1673303/229006712-54d85e73-40d7-40a3-ae4a-22453232385e.png)

Perhaps already fixed in the current master. Posting here just in case.

**Comment by zhaojj2209** [comment]
Not yet fixed, let's leave this up.

**Comment by rick711c** [comment]
@damithc, Hii.. I want to work on this issue. can you please assign this to me. Thank you.

**Comment by quantavoid11** [comment]
@zhaojj2209 Can I work on this issue?

**Comment by weiquu** [comment]
Hi @rick711c, we do not assign issues to contributors, but feel free to submit a PR for this issue 

@quantavoid11, since @rick711c has expressed interest first, let's give them the chance to work on it. In the meantime, do look through the other open issues and see if there are any you wish to work on.

**Comment by quantavoid11** [comment]
Sure, I will look for other issues.

**Comment by Surya-Bhai007** [comment]
Hey, I want to work on this issue. @rick711c , are you working on this issue?

**Comment by yuridam** [comment]
Hi, is this still actively being worked on? if no, I want to work on this.

**Comment by domlimm** [comment]
@yuridam Hello, feel free to submit a PR for this issue.

**Comment by Venkateeshh** [comment]
Is anyone working on this issue still??

**Comment by weiquu** [comment]
Nope, @Venkateeshh feel free to submit a PR for this issue

**Comment by sgadkar2** [comment]
Hi, Is this issue still open? Can I work on it ?

**Comment by jasonqiu212** [comment]
Hi @sgadkar2, Feel free to submit a PR for this issue!
