### ISSUE TITLE
Instruction to install old version while setting up the project locally

### ISSUE THREAD

**Issue by ArslanYM** [TEAMMATES/teammates#12320]
In [this](https://teammates.github.io/teammates/setting-up.html) documentation the step asks to run the `npm ci` command for working on front-end but it gives and error as it is and older command 

**Steps to reproduce**
change the code in the instruction to the newer one 

![this](https://user-images.githubusercontent.com/104521101/229176282-f0a3dba8-5fd7-4cf8-ac26-bbd8b552dbe6.png)

**Comment by wkurniawan07** [comment]
This is not an issue. Those are warnings instead of errors, and they are not uncommon if deprecated NPM packages are used either directly by us or by our dependencies transitively (in this case it is the latter).
