### ISSUE TITLE
Instructor courses page: fix copy instructors from other courses modal checkbox 

### ISSUE THREAD

**Issue by weiquu** [TEAMMATES/teammates#12334]
Path: Instructor pages -> Courses tab -> Edit course details -> Copy instructors from other courses

The modal that appears has a checkbox to select instructors to copy over. However, there's no indication that it has been checked:
<img width="913" alt="copy instructors modal" src="https://user-images.githubusercontent.com/48304907/229415211-de94ccd3-a183-4b48-9038-32a0c2a5d96e.png">

**Comment by judith-n** [comment]
Hello, I created a PR for this issue. This is my first time with open source, so let me know if anything is not ok :)
