### ISSUE TITLE
StudentsLogic.java: Refactor program to remove code smells and enhance maintainability

### ISSUE THREAD

**Issue by sagarshah97** [TEAMMATES/teammates#12336]
While reviewing the code for `StudentsLogic.java` Implementation level code smells were identified:
- Add meaningful name to the variable (e.g.: `int studentsCount`)
- Overlooking Single Responsibility Principle (e.g.: `getSectionInvalidityInfo()` method)
- Complex conditional statements (e.g.: `getTeamInvalidityInfo()` method) 

These smells can be easily removed by refactoring the code which would not break any existing functionality.

**Comment by zhaojj2209** [comment]
Thank you for the issue! Issues related to refactoring are evaluated on a case-by-case basis.

Making refactoring changes when the code is fully functional may only serve to introduce regressions that break existing functionality. The `getXXXInvalidityInfo()` methods are self-explanatory enough that refactoring provides minimal benefit.

Furthermore, work is currently underway to migrate our database, during which the code in `StudentsLogic.java` will undergo an overhaul. We may take your suggestions into account when writing code for the new logic components, but any code refactoring done to the current codebase will be overridden down the line anyway, which would then render the changes useless.

For the above reasons, we will not be accepting this issue.
