### ISSUE TITLE
Instructor sessions page: fix copy questions modal checkbox

### ISSUE THREAD

**Issue by weiquu** [TEAMMATES/teammates#12335]
Path: Instructor pages -> Sessions tab -> Edit feedback session -> Copy question

The modal that appears has a checkbox to select questions to copy over. However, there's no indication that it has been checked (e.g. in the screenshot below, rows 2 and 4 have been checked):
<img width="914" alt="Screenshot 2023-04-03 at 1 07 23 PM" src="https://user-images.githubusercontent.com/48304907/229416718-7eb624eb-7199-4e9f-938a-94407c11551f.png">

**Comment by Khalid6468** [comment]
Can I work on this?

**Comment by domlimm** [comment]
@Khalid6468 Hello, as you have previously worked on an issue, please leave issues tagged with `good first issue` to new contributors. Feel free to look for other issues to work on!

**Comment by puhung** [comment]
Hi, I am a new contributor. Can I work on this?

**Comment by quantavoid11** [comment]
I am new to open source and can fix this issue. Please let me work on this.

**Comment by domlimm** [comment]
@quantavoid11 Sure, please go ahead and open up a PR!

**Comment by PeeyushDas** [comment]
I would like to work on this issue. Can someone please guide me to where I can view the source code and append it?

**Comment by domlimm** [comment]
@PeeyushDas Hello, thanks for your interest! As @quantavoid11 has indicated that he will be working on it, I'd suggest you look for another issue tagged with `good first issue` to work on. You may look at [TEAMMATES documentation](https://teammates.github.io/teammates/index.html) to get started.

**Comment by weiquu** [comment]
Hi @quantavoid11, I think it looks fine. Do create a PR so that we can take a look at the changes in the code itself!
