### ISSUE TITLE
Instructor courses page: fix margin of copy instructors from other courses modal on mobile

### ISSUE THREAD

**Issue by weiquu** [TEAMMATES/teammates#12344]
Path: Instructor pages -> Courses tab -> Edit course details -> Copy instructors from other courses

The modal that appears has a large margin on the right, which is different from the behaviour of other modals on mobile:
![copy instructors modal closed](https://user-images.githubusercontent.com/48304907/230135274-9698225c-67ae-45df-b060-33959b31693a.PNG)

This makes it difficult to read the text in the table:
![copy instructors modal open](https://user-images.githubusercontent.com/48304907/230134967-a7153c09-d0a1-4c06-b167-1678f8e3f281.PNG)

**Comment by weiquu** [comment]
Hi @vishalsingh2972, we don't assign issues to contributors, but feel free to submit a PR for this issue.

> P.S Also new here so could you please also attach the exact folder in the repository so that I can try looking at the problem directly without getting overwhelmed by the huge code base.

I suggest that you first follow the steps [here](https://teammates.github.io/teammates/setting-up.html) to set up the development environment, and then take a look at the [development workflow](https://teammates.github.io/teammates/development.html). After you've done that, you can navigate to the path highlighted in the issue and find the relevant component/file by inspecting the page's elements (or any other means).

Being able to individually navigate through a larger, unfamiliar codebase is a good skill for an open-source contributor (or any software developer) to have. I hope you'll take this chance to get some experience and learn how to do so (: That being said, do reach out if you face any issues along the way

**Comment by b-walton** [comment]
Is it ok If I take on this issue? Unless you are still working on it @vishalsingh2972

**Comment by vishalsingh2972** [comment]
> Is it ok If I take on this issue? Unless you are still working on it @vishalsingh2972 

Very kind of you to ask @b-walton , sure please go ahead 👍
