### ISSUE TITLE
Link recovery is case sensitive

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12362]
v8.26, production

As per a report from a user, this feature seems to be case sensitive:
![image](https://user-images.githubusercontent.com/1673303/230925048-92ea0438-3a5f-46f6-af84-af8b4588018e.png)

i.e., entering `abc@example.com` and `ABC@EXAMPLE.COM` give different results.

**Comment by wkurniawan07** [comment]
This is not limited to just link recovery. Email address fields in the system are generally used in a case-sensitive manner.

There is no easy way out here due to the data already in the DB.

**Comment by damithc** [comment]
I see. Should we consider lower-casing all email addresses before storing them from now on?

**Comment by luffingluffy** [comment]
Hello, I would love to take this issue if it gets the go ahead.

**Comment by wkurniawan07** [comment]
@damithc it is not safe; there is no rule that says that email addresses are case-insensitive. Although this has been a long topic of debate for many years, there is still no such rule, and it depends on email providers whether to treat emails as case-sensitive or not. The only guaranteed case-insensitive part of email addresses is the domain (e.g. `@example.com`).

**Comment by wkurniawan07** [comment]
Close as this is by design
