### ISSUE TITLE
Incorrect Developer Website link in Contact page

### ISSUE THREAD

**Issue by domlimm** [TEAMMATES/teammates#12375]
**Environment**: 
V8.26.0

**Steps to reproduce**

https://teammatesv4.appspot.com/web/front/contact

![image](https://user-images.githubusercontent.com/46486515/231967619-6e409df9-19dc-416e-973c-ae4a9d12a3b2.png)

**Expected behaviour**

Should link to https://teammates.github.io/teammates/index.html.

**Actual behaviour**

Links to back to [TEAMMATES repository](https://github.com/TEAMMATES/teammates).

**Comment by domlimm** [comment]
Oh I see.. Initial thought was that clicking on the link will bring me to the developer documentation.

How about `TEAMMATES GitHub`? Consistent with the Blog part as `TEAMMATES Blog`.

Except I'm assuming developers will know GitHub. But the current Developer Website means that if anyone who is interested to join TEAMMATES, it will be someone who is looking to develop TEAMMATES?

**Comment by anuth212** [comment]
I would like to make a PR to help fix this issue. I'll make the change to the link name so it is more clear.
