### ISSUE TITLE
Instructor editing feedback path of a question: unnecessary scrollbars

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12399]
v8.27, production, Windows, Chrome

Context: an instructor is editing questions of an existing session

![image](https://user-images.githubusercontent.com/1673303/233297810-77b14ec6-b1ac-440e-8192-5150af818ef9.png)

![image](https://user-images.githubusercontent.com/1673303/233298086-fc460937-0a88-4a7a-8e9b-3df7981c01e0.png)

Let me know if more info needed to reproduce

**Comment by athakaras** [comment]
Hello. I am interested in trying this issue. Can you please provide more info on how to find the feedback path both on site and on files? Thanks a lot!

**Comment by zhaojj2209** [comment]
@athakaras The components in question can be found on the instructor edit sessions page. We recommend following our [development guidelines](https://teammates.github.io/teammates/development.html) to set up the project on your local device, then exploring the site/codebase to find the relevant components/files on your own.

**Comment by athakaras** [comment]
@zhaojj2209 thankyou! I have set up the project locally. In order to gain a better understanding, the problem is that the scrollbars should be removed completely ?

**Comment by athakaras** [comment]
Hello! I raised a PR that fixes the issue. Please review :)
