### ISSUE TITLE
Sort icons in info table headings are hard to see

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12407]
Since Bootstrap changes the color for the 'info' style, the grey sort icons don't seem to have enough contrast with 'info' background to be able to see them easily e.g.,
![image](https://user-images.githubusercontent.com/1673303/233819626-130ae762-87bd-47de-8051-362ad2dc9c48.png)

Should we use white instead of grey for them?

**Comment by HenniLenni** [comment]
I'll work on this issue, will make a pr soon
