### ISSUE TITLE
Instructor editing questions: warning about visibility is removed if the edit is cancelled.

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12400]
v8.27, production, Windows, Chrome

Context: An instructor is editing questions of a session that already has some responses. For each question with responses, a warning like this appears:
![image](https://user-images.githubusercontent.com/1673303/233301346-69913e59-9df3-4b92-9004-60af8ad4a38c.png)

Problem: If the instructor go to the edit mode of a question and then cancels the edit, the warning disappears. Refreshing the page will bring it back.

Not a big issue but just a glitch/inconsistency.

**Comment by alemendoza-v** [comment]
Hello, Im interested in solving this issue, could someone tell me where to look at please?

**Comment by zhaojj2209** [comment]
@alemendoza-v This issue can be found on the instructor edit sessions page. We recommend following our [development guidelines](https://teammates.github.io/teammates/development.html) to set up the project on your local device, then exploring the site/codebase to find the relevant components/files on your own.

**Comment by alemendoza-v** [comment]
@zhaojj2209 Thanks! I'll do that and try to solve this issue, do I have to be assigned?

**Comment by zhaojj2209** [comment]
@alemendoza-v Feel free to submit a PR, we do not assign issues to contributors.

**Comment by itsAfnanAlam** [comment]
@alemendoza-v Hello! are you still working on this? If not can I take it up?

**Comment by Zxun2** [comment]
Hello! May i check if there is anyone working on this currently? I would like to work on it.

**Comment by weiquu** [comment]
Hi @Zxun2, feel free to submit a PR for this issue
