### ISSUE TITLE
Comments for Responses for Essay Question

### ISSUE THREAD

**Issue by ellaella12** [TEAMMATES/teammates#12421]
I am interested to work on this project: https://github.com/TEAMMATES/teammates/wiki/Comments-for-Responses. May I check if this issue is available? 

Currently, students can add comments to their responses when they answer MCQ or MSQ questions. it would be good to add a similar ability to the essay question type.

**Comment by jasonqiu212** [comment]
@ellaella12 Thanks for indicating interest to contributing to this project! Yes, please proceed with submitting a PR for this issue

**Comment by singhabhyudita** [comment]
Hi @ellaella12 are you still working on this issue? If not I would like to take this one up!

**Comment by ellaella12** [comment]
Hi sorry I am still working on it, was trying to fix a bug in the pr. I have fixed the bug and will be fixing the e2e tests. I will try to complete it quickly, thank you!

**Comment by khushboo-9876** [comment]
Is this issue Available, I want to work on it ?

**Comment by ellaella12** [comment]
Hi sorry I am currently working on the issue, I will try to complete it soon, thank you!
