### ISSUE TITLE
Include student email in 'distribute points' type question summary table CSV

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12430]
v8.27, production
Feature requested by a user. 

When an instructor downloads results of a session as a csv file, the summary table of 'distribute points' type questions do not specify the email address of the student in concern. Here is an example:

![image](https://github.com/TEAMMATES/teammates/assets/1673303/c61867df-0fcf-4071-beee-4103707b8429)

This is the problem because email address is the unique identifier, not the name.

Suggestion: add the email as a separate column to the summary table. Based on a quick eyeballing, other questions types seem to include the email in the summary data table but it may be worth doing an exhaustive check to see if we missed it in any other question type.

P.S: The email is shown in the Web view as follows:
![image](https://github.com/TEAMMATES/teammates/assets/1673303/8726dab6-efef-4f34-a78c-3ed9090fec0d)
In the CSV file, it should be a separate column (for easier processing), and it might be good to do the same in the Web view, for consistency.

**Comment by riotgage** [comment]
I am a first-time contributor to this project. 
Adding email to generated csv will require updating getQuestionCsvStats(...). Can I take this issue ?
