### ISSUE TITLE
Bug when registering multiple instructors

### ISSUE THREAD

**Issue by Leonardo0o0** [TEAMMATES/teammates#12448]
- **DEV Enviroment V8.27.0**: 
if i try to register an instructor by adding multiple instructors "Add Instructor Details in the format: Name | Email | Institution" and when i try to go to another by using a "," or "|" it get mixed with the institution and make only one request.

**Steps to reproduce**
in the Adding Multiple Instructors field put:
Name | Email | Institution | Name | Email | Institution | Name | Email | Institution
or 
Name | Email | Institution , Name | Email | Institution ...

**Expected behaviour**
appear 3 or 2 new instructors like in the examples given

**Actual behaviour**
the institution gets mixed with the name ex: oxford , nathan

**Comment by wkurniawan07** [comment]
This is incorrect use of the feature. Adding multiple instructors are done with different rows, not duplicating columns, the latter of which are highly prone to confusion if not errors.

Close as not planned.
