### ISSUE TITLE
[Search Students]: Massive string is not correctly treated

### ISSUE THREAD

**Issue by MauricioMachadoFF** [TEAMMATES/teammates#12442]
- **Environment**: 
- Dev server
- Master at commit `4b2333d36f76e172bb9e15fd18b70d02e4587d9a`

**Steps to reproduce**

- Log in as a `instructor`
- Access the Search feature via the menu bar
- Make a search with a massive String ( more than 6000 characters, counting the whitespaces)

**Expected behaviour**
If we have a limit accepted on the backend we should have one of two in our frontend: 
- Define this limit at the frontend and don't send this request to the backend
- Send this request to the backend. Backend spit out an error. Frontend treat the spitted error.

### The expected behaviour would be:

- Error message shown to user before sending a search with more characters than the limit.

**SUGGESTED BEHAVIOR**

- Addition of a char counter at the search field
- When char counter reaches its limit block anymore typing
- Enhance error treatment at search student methods

**Actual behaviour**
-  User can type as much as it wants
- The More the user types the slower the navigator gets due to memory allocation
- After sending the request, a red banner without any message pops up

**Additional info**

## Photos

The photos have been cutted out only for the relevant information. My monitor specs are: 1920x1080

![SCR-20230522-o8q](https://github.com/TEAMMATES/teammates/assets/62910920/43063a1a-7837-4478-84b8-ab63e25cd736)
![SCR-20230522-o8u](https://github.com/TEAMMATES/teammates/assets/62910920/074de8eb-0fdd-4d66-94d5-c5d58bdd14a1)

**Comment by weiquu** [comment]
Thanks @MauricioMachadoFF for pointing this out! Not a big issue since I don't think searches will be >6000 characters long, but an error message should definitely be shown.

Worth noting that this issue also exists for the admin search page.

**Comment by LarsGielen** [comment]
I managed to reproduce this problem and would like to try to solve it. It is my first time contributing to this project though, is this a problem that can be solved by someone with little knowledge about the project?

**Comment by weiquu** [comment]
Hi @LarsGielen, I think this issue is fine for a first-time contributor. Please feel free to submit a PR when you're ready

**Comment by LarsGielen** [comment]
Hi @weiquu, I think I solved the problem by setting the maxlength property of the search bar and showing a warning when the user has reached the limit. 

Right now I have hard coded the limit. Is there any way of not having to hard code the limit? or is it not a problem?

**Comment by RahulkumarRV** [comment]
hey, I want to work on this issue, as it is my first contribution 
can I work on this issue?

**Comment by weiquu** [comment]
Hi @RahulkumarRV, this issue is already being worked on by another contributor. Do take a look at other issues tagged as "good first issue"
