### ISSUE TITLE
Improvement in search bar UI of admin and instructor search page

### ISSUE THREAD

**Issue by riotgage** [TEAMMATES/teammates#12452]
When search bar is hovered or is in focus the border of search bar is too thick and spills over search button.
![Screenshot 2023-05-24 202120](https://github.com/TEAMMATES/teammates/assets/48171184/f4daa210-d9f0-4221-a273-32999b0f8e82)

For better UI, we should make it little thin

**Comment by weiquu** [comment]
Quick correction: there is no shadow on hover, only when it's focused. 

Not sure if this issue needs to be fixed, since it comes at the expense of treating this input field differently from other input fields throughout the site. @ others, pls weigh in (:

**Comment by damithc** [comment]
@riotgage thanks for reporting this visual anomaly, and thanks @weiquu for the follow up.
As an actual admin user of TEAMMATES, I don't feel we need to fix this. It doesn't affect my usage at all.

**Comment by cedricongjh** [comment]
hi @riotgage, thank you for surfacing this. However, as the fix requires treating the input field differently from all the other input fields on the site, and it does not affect the usage of admins at all, we've decided not to accept this issue.
