### ISSUE TITLE
Set character limit on feedback configuration

### ISSUE THREAD

**Issue by CaduRoriz** [TEAMMATES/teammates#12459]
Inside feedback editing functionality, in the test setup description it doesn't have a character limit what could causes a lot of problems 
![image](https://github.com/TEAMMATES/teammates/assets/77363222/b4809bfe-7b70-4f15-b291-83ddfe1cf07e)

**Comment by samuelfangjw** [comment]
@CaduRoriz Could you elaborate on this, what problems exactly?

**Comment by wkurniawan07** [comment]
Duplicate of #12455
