### ISSUE TITLE
Add steps on how to enter masquerade mode in developer guide

### ISSUE THREAD

**Issue by NicolasCwy** [TEAMMATES/teammates#12473]
As an extension to #12466, we can add steps in the [developer guide](https://teammates.github.io/teammates/development.html#logging-in-to-a-teammates-instance) to make it clearer on how we can enter masquerade mode. This discussion #12433 outlines the steps and would be helpful.

This can be a new subsection under `Logging in to a TEAMMATES instance`, after `Logging in without UI`
<img width="1249" alt="image" src="https://github.com/TEAMMATES/teammates/assets/25302138/a354fd06-d41b-40b7-9a56-dd8a92c300c2">

**Comment by sahilkamate03** [comment]
Hello @NicolasCwy ,
Can I work on the issue.
Thank you for your time and consideration!

**Comment by domlimm** [comment]
Hey @sahilkamate03! Please feel free to submit a PR for this.
