### ISSUE TITLE
Add a trigger for good first issues

### ISSUE THREAD

**Issue by athakaras** [TEAMMATES/teammates#12480]
Add a trigger for good first issues

- **Environment**: The master branch of the repo

**Description of feature/enhancement**
This proposal suggests implementing a trigger by using github actions that automatically adds a comment to issues that are labeled as a "Good First Issue." The comment will provide helpful guidelines and resources for first-time contributors, useful links, and they will inform the contributor that the project does not assign issues but rather the users express their interest, by explaining the process of contribution.

**Justification**
Currently, when an issue is labeled as a "good first issue", there is no automated system in place to guide first-time contributors. As a result, these individuals may face difficulties understanding the project's guidelines and best practices. This lack of initial guidance can lead to delays and frustration, potentially discouraging new contributors from engaging with the project. As far as I am concerned, I also had some trouble in my first contribution and this feature would have helped me a lot. I also noticed some very popular projects doing so, that's why I think it would be a very good addition to the project's documentation.

**Existing similar features and their shortcomings**
The contribution documentation page of the project can be considered as exisiting similar feature, however, I think that this feature provides a **faster** and **easier** way to get the information a user needs altogether. 

Please tell me if this is something that you would like to see in the project, so that I can raise the respective PR:)

**Comment by weiquu** [comment]
Thanks @athakaras for the suggestion! I think this idea makes sense (: While we wait for other contributors to weigh in, could you provide some examples of guidelines, resources, and links the comment would contain? I assume it would have links to the contribution / workflow page, but I'm not sure what else

**Comment by athakaras** [comment]
@zhaojj2209 i am raising a PR! Please let me know if it is okay:)
