### ISSUE TITLE
Flickering questions when loading sessions results

### ISSUE THREAD

**Issue by Zxun2** [TEAMMATES/teammates#12499]
- **Environment**: master

**Steps to reproduce**

- Go to instructor home page
- Select the first session of the demo course
- Select "View results (from/to me)"

![image](https://github.com/TEAMMATES/teammates/assets/63457492/f7fe8485-7475-4237-9eea-863328bdb2a3)

**Expected behaviour**
 
- There should be no flickering 

**Actual behaviour**

https://github.com/Zxun2/teammates/assets/63457492/1e5b68cc-5bec-4f07-aa57-e3837ec1847b

**Additional info**

- The questions defaults to `hasResponse: true` which causes the bug

**Comment by tushargupta123** [comment]
Hey can i correct the issue ?

**Comment by domlimm** [comment]
@tushargupta123 Hello, feel free to submit a PR for this.

**Comment by rajatmohan22** [comment]
@domlimm Hi, is this issue already assigned to someone? because if not i'll definitely contribute a PR within the next 2-3 days

**Comment by jasonqiu212** [comment]
Hi @rajatmohan22, feel free to submit a PR for this issue!

**Comment by OpherM** [comment]
Hey Please is this issue still open?

**Comment by jasonqiu212** [comment]
Hi @OpherM, Someone else has indicated interest in fixing this issue. Could you look into another issue instead? Thanks!

**Comment by HarshSingh21** [comment]
Hi,
 Can I get assigned to this role? I would love to contribute.

**Comment by jasonqiu212** [comment]
Hi @HarshSingh21, Please feel free to submit a PR for this issue!

**Comment by blejkowski** [comment]
Hi @jasonqiu212, is this issue still available? I believe I have figured it out and got a working solution, will send a PR for this issue if allowed to do so. Thanks

**Comment by Sourav-Kumar-Panda** [comment]
Hii,
Can I get assigned to this role? =

**Comment by jasonqiu212** [comment]
Hi @Sourav-Kumar-Panda, Thank you for your interest in working on TEAMMATES! Someone is already working on this issue in #12570. I would recommend to find another issue to work on! :)

**Comment by Sourav-Kumar-Panda** [comment]
Ok, No problem.
