### ISSUE TITLE
Allow instructors to use start/end dates up to 12 months in future

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12494]
Current: Instructors cannot choose start/end dates further than 3 months into the future

Suggested: Increase this limit to either 9 or 12 months

Reason: Some instructors set up their courses in advance (e.g., some will set up their fall courses during summer)

Requested by a user.

**Comment by damithc** [comment]
@wkurniawan07 any cost (or other) downsides if we allow 9 or 12 months for start/end dates?

**Comment by wkurniawan07** [comment]
Not really. In essence the only reason for the limit is abuse prevention, so as long as the limit is sensible it can always be changed.

**Comment by damithc** [comment]
> Not really. In essence the only reason for the limit is abuse prevention, so as long as the limit is sensible it can always be changed.

Thanks for the confirmation @wkurniawan07 

Let's set it to 12 months then, as 9 feels a bit random.

**Comment by Zxun2** [comment]
Hello! May I work on this issue?

**Comment by sawilkhan** [comment]
Is the issue still open?
