### ISSUE TITLE
Instructor home page loads forever if attempt to copy a feedback sessions fail

### ISSUE THREAD

**Issue by Zxun2** [TEAMMATES/teammates#12507]
- **Environment**: master

**Steps to reproduce**
- Go to Instructor Home Page
- Add a new course, `New Course`
- Copy any existing session from `Sample Course 101` over to `New Course`
<p align="center">
<img src="https://github.com/TEAMMATES/teammates/assets/63457492/3d94f53e-b663-481e-b7d7-a67cd85abe1c" width="400"/>
</p>

- Under `New Course`, copy the session again into the `Sample Course 101`
<p align="center">
<img src="https://github.com/TEAMMATES/teammates/assets/63457492/1c43fb7f-e1c3-46d6-ae5f-2ce5f05e14a6" width="400"/>
</p>

- Error toast pops up, and page loads forever.

![image](https://github.com/TEAMMATES/teammates/assets/63457492/af16afeb-b524-466b-a945-fb8bda3afa5a)

- Clicking on the `Home` button on the navbar yields no results. Will only resolve by either hard refreshing or navigating to another page, and back

**Expected behaviour**

Returns back to the home page.

**Actual behaviour**

Page loads forever.

**Additional info**

NIL

**Comment by rexong** [comment]
I would like to try this issue.
