### ISSUE TITLE
Email's validation

### ISSUE THREAD

**Issue by lucasfs1007** [TEAMMATES/teammates#12502]
My goal with this issue is to create more efficient abstractions for email validation.
I will create tests using TDD, in which I will create methods to validate emails without the need to manually authorize forms. These abstractions are more related to my individual studies within my testing discipline than something completely new. I will fork these modifications into my own repository, but everyone is welcome to collaborate with me. link to my repository: https://github.com/lucasfs1007/teammates_testes

**Comment by weiquu** [comment]
Hi @lucasfs1007, can you give more examples of what you seek to implement? It seems that you're just testing email validation, and not "[creating] more efficient abstractions". I'm also not sure what you mean by manually authorising forms.

If you could also provide details about what problems have arisen/might arise due to our current email validation, that would be great as well.

**Comment by lucasfs1007** [comment]
Hi @weiquu, My main goal here is really to do some tests to practice TDD practices a little deeper, abstracting a little more from what we already have for study purposes.
With the question of forms, I noticed that when logging in for the first time, instead of receiving confirmation via email, I received the following forms to respond to. My feeling that after the completion of the same, my registration was taking place manually.

**Comment by lucasfs1007** [comment]
![image](https://github.com/TEAMMATES/teammates/assets/88278278/0fd8a1e9-9169-40df-a341-47bae80a9124)

**Comment by zhaojj2209** [comment]
@lucasfs1007 It seems that you are proposing for us to do away with the account request form and replace it with email validation. However, there is a fundamental misconception on the use of the account request form. The purpose of the account request form is not solely to check if the email is valid, but rather to verify the identity of the user before we provide them with an account.

Do also refer to https://github.com/TEAMMATES/teammates/issues/12451#issuecomment-1560526064 for our stance on email validation.

Closing as not planned.
