### ISSUE TITLE
Instructors creating sessions: response visible time should be 'not now' by default

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12517]
When an instructors is creating a new session, 

Current:

![image](https://github.com/TEAMMATES/teammates/assets/1673303/877ffd12-0628-4dd0-8177-4b7e5b26d49b)

The default `Make response visible` time is empty.

Expected:

Should be set to `Not now`.

Otherwise, there will be an error message upon saving.

Seems like a regression caused by V8.28

**Comment by damithc** [comment]
Possibly caused by #12498
@Zxun2 can have a look?

**Comment by Zxun2** [comment]
I have submitted a PR for this. Apologies for the inconvenience 🥲

**Comment by damithc** [comment]
> Apologies, I have submitted a PR for this!

No worries @Zxun2 . It's a rite of passage 😀 
Thanks for the quick response.
