### ISSUE TITLE
V8.28.1

### ISSUE THREAD

**Issue by samuelfangjw** [TEAMMATES/teammates#12520]
Scheduled for Saturday, Jul 15, 2023, ~10.00pm~ 10.00am SGT.

Release Lead:

- [x] Tagged the latest stable release code with the latest version number
- [x] Released changelogs

PM:

- [x] Deployed the new version
- [x] Released the new version for end users

**Comment by samuelfangjw** [comment]
[V8.28.1](https://github.com/TEAMMATES/teammates/releases/tag/V8.28.1) has been released by @samuelfangjw at July 15th, 2023, 09.01am SGT.

Code contributions from: @Zxun2
Review contributions from: @domlimm, @weiquu

Ready for post-release check and deployment by PM (@damithc).

**Comment by damithc** [comment]
Deployed and released. Thanks again for the quick patch release. 💯
