### ISSUE TITLE
Instructor sessions page: Empty deleted sessions table is not displayed

### ISSUE THREAD

**Issue by jasonqiu212** [TEAMMATES/teammates#12538]
**Current Behavior**

The instructor sessions page does not display an empty table of deleted feedback sessions, if there are no deleted sessions.

With deleted sessions:
![Screen Shot 2023-07-31 at 4 32 35 PM](https://github.com/TEAMMATES/teammates/assets/25262042/0abd7f5b-8c2c-4fcb-a979-72a1f9d7e1a6)

No deleted sessions:
![Screen Shot 2023-07-31 at 4 32 52 PM](https://github.com/TEAMMATES/teammates/assets/25262042/ff0b3d87-0f7e-4451-ab3a-20e5478b1b35)

**Expected Behavior**

With reference to #10508:

> I think empty tables should be shown even if there are no deleted/archived items. That's more consistent with our policy that even disabled items are shown to let users know where things are.

**Suggestion**

- Add an alert for Deleted Sessions table when there are no deleted courses (Similar to #12521)

**Comment by damithc** [comment]
@jasonqiu212 is this suitable for first timers?

**Comment by jasonqiu212** [comment]
@damithc Yes professor. Given that contributors can reference from #12521, I believe this is suitable for first-time contributors.

**Comment by mariemllr** [comment]
Hi, can I contribute to this issue? :)

**Comment by jasonqiu212** [comment]
Hi @mariemllr, Sure thing! Feel free to submit a PR for this issue
