### ISSUE TITLE
Instructor Search Page: sorting affects sort icons for all tables

### ISSUE THREAD

**Issue by weiquu** [TEAMMATES/teammates#12536]
Sorting a table affects the sort icons for all tables. Note that only the sort icon is affected - the actual rows of the other tables aren't sorted.

https://github.com/TEAMMATES/teammates/assets/48304907/59dd4d7f-8cf3-4d30-8234-c14632af2f2e

**Comment by damithc** [comment]
Good catch @weiquu 
Let's raise the priority, as this is user-facing and makes the user view 'incorrect'
