### ISSUE TITLE
Instructor Session Page: Failed copy feedback session causes page to load forever. 

### ISSUE THREAD

**Issue by rexong** [TEAMMATES/teammates#12551]
- **Environment**: 
`master` branch at commit `8633d4e`

**Problem**
The issue is similar/identical to the issue #12507. 
When we try to copy the feedback session, if it fails, it will lead to the page loading forever. The only way to stop it is through hard refresh or navigating to another page. 

**Steps to reproduce**
1. Go to instructor session page. 
2. Click on `Copy` for any available session.
3. Select the same course as the selected session.
![image](https://github.com/TEAMMATES/teammates/assets/66376253/537996d6-6471-4d53-8245-8d5effcc5cb9)
4. Click `Copy`.

**Expected behaviour**
- Error toast to be shown
- Session table should be generated.

**Actual behaviour**
Page goes into a loading state forever. 

<ins>Video Demo of Actual Behaviour</ins>
https://github.com/TEAMMATES/teammates/assets/66376253/74e424cd-ef1c-4d02-9aef-7d0d9199277c

**Additional info**

As mentioned, this issue is similar to issue #12507. 
To resolve this issue, look at PR #12550

**Comment by Trjindal** [comment]
i would like to work on it

**Comment by domlimm** [comment]
@Trjindal Feel free to submit a PR for this issue.

**Comment by PKS-formido** [comment]
Can I try to resolve it?

**Comment by jasonqiu212** [comment]
Hi @PKS-formido, Feel free to submit a PR for this issue :)

**Comment by mambalde** [comment]
is anyone working on this?

**Comment by PKS-formido** [comment]
@mambalde I am just trying. You can also try to solve the issue. No need to hold up because of me

**Comment by Petros1020** [comment]
Hi really nice project i am happy that i found it!
I made a PR about this issue. https://github.com/TEAMMATES/teammates/pull/12572

Thanks
