### ISSUE TITLE
`@` sign is shown as `&#64;` when viewing essay question submission page

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12578]
V8.29.0, production

Steps:
1. A respondent uses an `@` in a response
2. The same respondent views the submission page again e.g., to edit responses
3. Problem: The `@` sign appears as `&#64;` (but it appears correctly when the instructor views/downloads responses)

![image](https://github.com/TEAMMATES/teammates/assets/1673303/9b46fe1d-72d9-4d2b-be6f-4414147c7337)

EDIT: Happens only for plain-text mode text fields, not for rich text fields

EDIT: Happens for apostrophe  as well, as noted in https://github.com/TEAMMATES/teammates/issues/12864

**Comment by RohithSurya** [comment]
I will check on the issue

**Comment by cedricongjh** [comment]
Unfortunately, I've been unable to replicate the issue locally (tried on chrome, safari, firefox), if anyone else is able to do let me know!

**Comment by RohithSurya** [comment]
> Unfortunately, I've been unable to replicate the issue locally (tried on chrome, safari, firefox), if anyone else is able to do let me know!

I have been able to replicate it. The text box should be a normal one... not rich text editor

**Comment by damithc** [comment]
> I have been able to replicate it. The text box should be a normal one... not rich text editor

Good catch @RohithSurya I didn't notice it myself.

**Comment by cedricongjh** [comment]
> Looking now on how to fix the issue

Awesome! Thanks @RohithSurya

**Comment by RohithSurya** [comment]
HI guys!
I raised a PR for the issue

**Comment by itstrueitstrueitsrealitsreal** [comment]
Hi, can I work on this issue?
