### ISSUE TITLE
Cannot add more individual deadline extensions while some are ongoing

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12594]
Received from a user, and can be reproduced:

>I have a session that recently closed, and I need to extend the deadline for some students.  I already extended it for a few students and it worked perfectly. However, now when I try to extend it for any student (except the ones who already have an extension), it gives me an error message that says "There are students who do not exist in the course" and will not extend it.  It doesn't matter who I try to extend it for, I get the same message.

**Comment by damithc** [comment]
Perhaps we can start by looking at what condition causes the message `There are students who do not exist in the course` to appear, as it seems like an unusual error message. I've never seen that before myself.

**Comment by cedricongjh** [comment]
I will look into this!

**Comment by cedricongjh** [comment]
i've tried to replicate the issue on my end and unfortunately am unable to:


https://github.com/TEAMMATES/teammates/assets/67156011/a6125493-2683-48bf-a3d2-aa233a1ae13c

As for the error message: `There are students who do not exist in the course`, it triggers when a student's deadline is to be extended but that student cannot be found in the course for which the session is under. This does seem like very strange behaviour as it does not seem like it's possible for the user to select a student not in the course from the UI. A possibility I can think of is that the student was deleted in between the 2 deadline extensions API requests but that does sound very unlikely to me

**Comment by damithc** [comment]
Thanks for looking into this @cedricongjh I get the same error when I try to extend the deadline for that specific student the user reported. I've emailed the user to ask if she edit student details in between. Waiting for reply.

**Comment by cedricongjh** [comment]
The logic works as follows:

1. Frontend sends PUT request with `courseId` and `feedbackSessionName` as params
2. Backend searches for the feedback session in the db using the `courseId` and `feedbackSessionName`
3. If there are new students who have individual deadlines, check if all the students sent in the PUT request to update their deadlines are in the course
4. Load student emails in the course from the db using `courseId` as a filter, as the set of student emails in the course
5. Check if the emails in the update request are in set of student emails in the course

Given that the feedbacksession stores the student deadlines as a map of studentEmail to deadline, could it be the case where an existing student that has an individual deadline has their email address changed, and thus every request we make to update the deadline throws an error as that email is no longer in the course? (in sending a PUT request, the ones with existing deadlines are sent to the backend as well)

**Comment by cedricongjh** [comment]
If my hypothesis is correct, there is a quick fix:

![image](https://github.com/TEAMMATES/teammates/assets/67156011/2a10e8ab-ee15-45ea-99e9-f2ced9998ff5)

Delete all the current individual deadlines (this would result in student deadlines being an empty set, and hence the check for `verifyAllStudentsExistInCourse` would be true), then add them all back (adds in the correct updated email, thus the check is valid and the update operation goes through)

The long term fix would probably be not to use emails for this but instead the generated id of the student

**Comment by damithc** [comment]
On the positive side, I found a way to replicate the problem. Steps:

1. Give some extensions
2. Edit the email address of one of the students who was given an extension
3. Try to give an extension to another student --> which causes this error to happen

I thought deleting the relevant rows from the DeadlineExtensions table would solve the problem but I encountered an odd situation:

Even after deleting the rows from the table (using database interface), the extensions still appear in the Web UI, and the problem persists. For example, the following database query does not return any results, but the deadline extensions continue to appear in the table. 

![image](https://github.com/TEAMMATES/teammates/assets/1673303/2cf9f8df-90cc-4555-8c6f-16abc6dd6eb7)

![image](https://github.com/TEAMMATES/teammates/assets/1673303/328566b1-4a0b-4dab-9e80-00b71a2f6b06)

Is this because of caching, or are the extensions also recorded in some other place? 

In addition, the update to the email seem to be propagated to the DeadlineExtensions table correctly, so it is puzzling how it breaks the functionlity.

**Comment by damithc** [comment]
Another experiment:

1. Give some extensions
1. Edit the email address of one of the students who was given an extension
1. Try to give an extension to another student --> error
2. delete the previous extension using Web UI (not through database UI)
3. Try to give an extension to another student --> works

Unfortunately, 4 can be done only if you stay in the same page. The moment you refresh the page, the extension disappears from the view, which means it can't be deleted using the Web UI anymore.

**Comment by damithc** [comment]
@samuelfangjw anything you remember about this feature that can explain this behavior?

**Comment by cedricongjh** [comment]
> Is this because of caching, or are the extensions also recorded in some other place?

Deadlines extensions are also recorded under `FeedbackSession`:

![image](https://github.com/TEAMMATES/teammates/assets/67156011/e5cbe2f5-ebb9-4a51-a1b2-59683198632e)

This might explain the reason for the bug, as the student email recorded here is likely not updated

**Comment by damithc** [comment]
> Deadlines extensions are also recorded under `FeedbackSession`:

Oh no! this can't even be updated via the database UI, as it is not stored as a human-readable value  :-(

**Comment by damithc** [comment]
> > Deadlines extensions are also recorded under `FeedbackSession`:
> 
> Oh no! this can't even be updated via the database UI, as it is not stored as a human-readable value :-(

To add, I wasn't able to read or edit that field (it is in BLOB format) but I was able to delete it entirely (i.e., delete all extensions) which solved the problem. I was able to add more extensions (but lost all the previous ones).

**Comment by cedricongjh** [comment]
Perhaps this would fix it: https://github.com/TEAMMATES/teammates/issues/12594#issuecomment-1742674441

Basically we set the map to empty (since it contains an invalid student email), and then give out the extensions again, this would be a temporary fix for the user. 

The long-term fix now would be to ensure that we update the deadline extensions map in `feedbackSession` when we update a student's email, which i can work on

**Comment by damithc** [comment]
> The long-term fix now would be to ensure that we update the deadline extensions map in `feedbackSession` when we update a student's email, which i can work on

Let's work towards this. The user in concern has no further need to give extensions in the affected session, which means we can  take a few more days to do a proper fix.

**Comment by anjum-edge** [comment]
The Long term fix can be important because it effects in the long term performance and fix extension bugs to see long term effects

**Comment by damithc** [comment]
@anjum-edge please refrain from spam posting
