### ISSUE TITLE
Student viewing results of a contribution question: (i) icon doesn't look clickable

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12607]
Context: a student is viewing the result of a contribution question.

![image](https://github.com/TEAMMATES/teammates/assets/1673303/dd90dcfb-e243-42c9-a4cd-278bd8aca858)

Suggestions:
1. Make the hover over mouse icon indicate that it is a clickable item
2. Put a dotted line below it (similar to `My View` in the screenshot) to show that there is additional content behind the `(i)` icon.

**Comment by nikkixiong** [comment]
Hi, I am interested in this issue, can I be assigned to this issue?

**Comment by cedricongjh** [comment]
hey @nikkixiong, feel free to submit a PR for this!

**Comment by anjum-edge** [comment]
why not take all the issues.

**Comment by Jiaqi093** [comment]
Hi, may I be assigned to this issue?

**Comment by Zhouheng98** [comment]
Hi, I am a student, can I try to solve this problem?

**Comment by cedricongjh** [comment]
hi @Jiaqi093 and @Zhouheng98, let's give @nikkixiong time to submit a PR

@nikkixiong do let us know if you're still working on this, thank you!

**Comment by Jiaqi093** [comment]
Hi, I have solved this issue and submit a PR, is that ok for review?

**Comment by Jiaqi093** [comment]
Hi, I just submit a PR, could you please review it?

**Comment by saurabhje** [comment]
If its still not fixed let me know.

**Comment by cedricongjh** [comment]
hi @saurabhje there's already an open PR for this issue, you're welcome to find other issues to contribute to
