### ISSUE TITLE
gradle build failing at the test task

### ISSUE THREAD

**Issue by aditya4196** [TEAMMATES/teammates#12625]
Im trying to setup the teammates project on my local, I ran the ./gradlew build, and it is failing in the test task with below error for all the tests

teammates.common.datatransfer.questions.FeedbackRubricQuestionDetailsTest > initializationError FAILED
    org.junit.runners.model.InvalidTestClassError at ParentRunner.java:525

Can anyone help me?

**Comment by cedricongjh** [comment]
hi @aditya4196 the command for running the project is ./gradlew serverRun, do try that out and let us know if you run into any issues

**Comment by aditya4196** [comment]
Thanks @cedricongjh 
I was able to start the application
I would like to contribute to this project. Im gonna go through some issues but incase there is anything to do, please assign it to me.

**Comment by cedricongjh** [comment]
> Thanks @cedricongjh I was able to start the application I would like to contribute to this project. Im gonna go through some issues but incase there is anything to do, please assign it to me.

great to hear! we'll proceed to close this issue
