### ISSUE TITLE
When adding a comment while submitting responses, show visibility of the comment as well

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12649]
Context: A respondent (e.g., a student) submitting responses chooses to add an optional comment together with a response.

Problem: Some respondents (based on the comments submitted) seem to think that the comment will be seen by the instructors of the course only. However, the current behavior is that comment has the same visibility as the response itself.

Suggestion: When the comment box is expanded, show the visibility description for the comment as well i.e., simply repeat the visibility description  of the response (seen at the first arrow in the screenshot below) above the comment box as well (i.e., at the second arrow).

![image](https://github.com/TEAMMATES/teammates/assets/1673303/6e6acecc-8d6c-4f7a-835e-3da8ec50680d)

**Comment by kashyapshukla** [comment]
.Hello,
I am new to contribution. I need help in setting up the back end locally.

**Comment by weiquu** [comment]
Hi @kashyapshukla, please open a new help request under the Discussions tab - let's keep comments here to be about the above issue. Please also detail what you've tried and the error you're facing

**Comment by ArunErram** [comment]
can i work on these isuue ?

**Comment by cedricongjh** [comment]
hi @ArunErram, there's already an open pull request that will close this issue, we would like to encourage you to look out for other issues to contribute to instead, thank you!
