### ISSUE TITLE
Instructor Home Page: Students dropdown buttons of the wrong colour

### ISSUE THREAD

**Issue by weiquu** [TEAMMATES/teammates#12657]
The buttons in the Students dropdown of a course in the instructor home page are the wrong colour:

![Screenshot 2023-12-12 at 8 36 41 PM](https://github.com/TEAMMATES/teammates/assets/48304907/7c01e3d6-f6c0-4e32-8034-9169ad873d47)

This seems to be an unintentional change cause by #12591, in particular the following addition to `styles.scss`:
```
  .btn-info {
    background-color: darken(#0DCAF0, 3%); // 3% darker than info
  }
```

The background colour is being used by another button in another page; moreover, it's unclear why the buttons in the students dropdown is of class `.btn-info` when no other dropdown button has that class (they have `.button-light` instead, but even that class seems to be redudant).

My suggestion is to simply remove that class from the affected buttons, as well as to ensure that no other buttons are affected. I've taken a quick look and this seems to be the only case, though I might have missed something.

**Comment by Mehakpreet9911** [comment]
Hello! I am first time contributor and would like to work on this issue.

**Comment by Mehakpreet9911** [comment]
okay, so I wanted to checkout the website first. But its not opening(the index.html file). Can you please guide.

**Comment by cedricongjh** [comment]
hi @Mehakpreet9911, do follow the guide here:  https://teammates.github.io/teammates/setting-up.html to setup your local development environment.

If you are running into any further issues, do create a post in discussion

**Comment by SArora12** [comment]
Hi , Can I take up this issue . I am a beginner and want to contribute

**Comment by Immortal-codes** [comment]
hey, can i contribute in this issue.

**Comment by clanang** [comment]
Hi. I would also like to work on this issue. I have a local up-and-running. Thank you!

**Comment by clanang** [comment]
Hi! I would like to work on this issue. Thank you!

**Comment by domlimm** [comment]
@SArora12 You may proceed to submit a PR for this issue.

@Immortal-codes Please allow @SArora12 to have a go first. Feel free to look at other issues tagged `good first issue` in the meantime!

**Comment by SArora12** [comment]
Ok

**Comment by SArora12** [comment]
@domlimm hey, i am facing some issue in running the project successfully . Can you help me with the set up part?

**Comment by Immortal-codes** [comment]
okay, no issue @SArora12
