### ISSUE TITLE
Student Home Page: Indicate default sort

### ISSUE THREAD

**Issue by weiquu** [TEAMMATES/teammates#12656]
The default sort for the courses on student home page seems to be by course ID; however, there's no indication of this via the sort by buttons:

![Screenshot 2023-12-12 at 7 36 06 PM](https://github.com/TEAMMATES/teammates/assets/48304907/b6e020f1-3999-4f3a-a75b-0894462a150b)

In contrast, the default sort (by creation date) is indicated in the instructor home page:

![Screenshot 2023-12-12 at 7 36 47 PM](https://github.com/TEAMMATES/teammates/assets/48304907/848800bf-baac-46a4-bfca-987f5258e5fd)

My suggestion would be to:
- Have the default sort on the student home page be by creation date as well - this seems to be more meaningful than course ID
- Indicate the default sort on the student home page

**Comment by averheecke-scottlogic** [comment]
Hi, I would like to pick this up as my first issue :)

**Comment by domlimm** [comment]
Hi @averheecke-scottlogic, feel free to submit a PR for this!
