### ISSUE TITLE
Instructor Home Page: Dropdown buttons on mobile

### ISSUE THREAD

**Issue by weiquu** [TEAMMATES/teammates#12658]
The dropdown buttons on mobile overflow / are clipped at the edge of the screen.

Example of overflow (note that it extends beyond the full-width footer):
![overflow 1](https://github.com/TEAMMATES/teammates/assets/48304907/afe7e827-68f2-4d39-a65a-27556720ac9c)

Example of clipping by the side:
![overflow 2](https://github.com/TEAMMATES/teammates/assets/48304907/feb72022-f25d-4ed6-8062-7db5124a9ea7)

(I'm using width 467)

The dropdown should be within the screen width itself.

**Comment by Tejasker** [comment]
hey , I think I can take up the issue & raise PR once confirmed

**Comment by weiquu** [comment]
Hi @Tejasker, sure please go ahead!

**Comment by Tejasker** [comment]
hey @weiquu , 
I too need help in creating a TEAMMATES instance, I have gone through the documentation & followed as instructed but I am not able to create an account TEAMMATES instance  and posted this same request in the discussion section too.

**Comment by Tejasker** [comment]
Thanks @weiquu 
This is my 1st open-source project which I started Contributing to.
Thanks for helping me out when required, glad I successfully made my first contribution, raised PR for it #12662  and hoping it will Merge in the coming future.

Thanks
Tejasker
