### ISSUE TITLE
Instructor's Student Records Page: Misleading name for canceling of comment edit

### ISSUE THREAD

**Issue by weiquu** [TEAMMATES/teammates#12665]
When editing a comment, the button for cancelation of editing is named "Discard", which is quite misleading - my instinct would be to assume that this deletes the comment entirely, rather than "discarding" the edit:
![discard and save buttons](https://github.com/TEAMMATES/teammates/assets/48304907/25cf317c-531a-4f98-90f5-a579542f6dfd)

Possibly a better wording would be Cancel, as is common in other website (e.g. Github):
![Screenshot 2023-12-16 at 5 03 08 PM](https://github.com/TEAMMATES/teammates/assets/48304907/69c12ada-37e3-44ec-a4c5-24933ee4d4f5)

In a similar vein, pressing "Save" even when no edits have been made to a comment causes the comment to show up as edited - I'm not sure if this behaviour is intended or intuitive. Open to discussion.

The delete icon on the comment might also be better in red?

**Comment by abdqudus** [comment]
Can I take this issue

**Comment by cedricongjh** [comment]
hi @abdqudus feel free to submit a PR

**Comment by abdqudus** [comment]
Should I just use "discard changes"? The button text is a ternary operator that either reads "Discard" or "Cancel"  . I think making the button text "Cancel" wouldn't be that good?

**Comment by cedricongjh** [comment]
hi @abdqudus I think we that should stick to "Cancel" as suggested by @weiquu, as is common in most websites

**Comment by abdqudus** [comment]
Oh,Ok
