### ISSUE TITLE
Instructor's Student Records Page: Accessibility issue for comment buttons

### ISSUE THREAD

**Issue by weiquu** [TEAMMATES/teammates#12664]
When using a screen reader, the comment buttons are simply read as "button", with no other information on what the button does. Here are the 2 comment buttons (edit and delete):
![comment buttons](https://github.com/TEAMMATES/teammates/assets/48304907/ac54af08-80d1-49b4-be38-20672949098a)

Let's add a description that the screen reader can pick up.

In addition, the buttons when adding/editing a comment are picked up in the wrong order by the screen reader. Here is the buttons (discard and save) for editing a comment; the same issue exists for adding a comment (cancel and save):
![discard and save buttons](https://github.com/TEAMMATES/teammates/assets/48304907/03a378ca-3f4d-4770-9c8d-43938cf086e7)

The screen reader first goes to Save and then Discard. Let's change the ordering so that the screen reader goes to Discard and then Save, to follow the visual order on the page

**Comment by rahulpro2001** [comment]
hii I would like to work on this one and want to ask when we go to the Comment section the button for comment also has no description can I work on this one
![ff](https://github.com/TEAMMATES/teammates/assets/72226387/fb95f193-149a-4c0f-918e-36ef5ea86f91)

**Comment by weiquu** [comment]
Hi @rahulpro2001, if I'm not wrong, the comment button is being picked up by the screen reader correctly. You can enable your own screen reader to check. I'm on mac, so [here](https://www.apple.com/voiceover/info/guide/_1121.html#:~:text=VoiceOver%20is%20a%20built%2Din,VoiceOver%2C%20press%20Command%2DF5.) are the commands I use - if you're using a different OS, I'm sure you can find the instructions of how to enable their screen reader online.

Regardless, do ensure that all buttons are being correctly read by the screen reader and in the right order when you eventually submit a PR (i.e. please resolve this issue fully).

**Comment by rahulpro2001** [comment]
okk @weiquu

**Comment by rahulpro2001** [comment]
@weiquu can we change the order of buttons or not?

**Comment by weiquu** [comment]
> @weiquu can we change the order of buttons or not?

Hi @rahulpro2001, please change the order the _screen reader_ picks up the buttons, but do not change the visual order of the buttons.

**Comment by rahulpro2001** [comment]
okk will update you shortly

**Comment by willzoo** [comment]
@weiquu Hi! I'm a first timer and would like to contribute to this issue if possible.

**Comment by weiquu** [comment]
Hi @willzoo, sure please feel free to submit a PR for this issue

**Comment by Manon-ds** [comment]
Hi, can I work on this issue?

**Comment by MinalDubey24** [comment]
Hi,  is the issue still open? Can I work on it?

**Comment by weiquu** [comment]
Sure, please feel free to submit a PR

**Comment by WesleyJammer** [comment]
Hey, i am a student and i am curious if this issue is still open? i like to work on this if it is possible.
