### ISSUE TITLE
More guidance for updating of snapshot tests

### ISSUE THREAD

**Issue by weiquu** [TEAMMATES/teammates#12669]
Fairly often I've found myself (and seen others) commenting the following text (or something similar) on PRs:

> You can update the snapshots by running `npm run test` and pressing `a` to run all test cases. After that, check through the snapshots to make sure the changes are as expected, then press `u` to update them. You can find more details on snapshot testing [here](https://teammates.github.io/teammates/snapshot-testing.html).

The frequency of this issue's occurrence points to it being a problem with our documentation (or possibly something workflow related) rather than with individual contributors.

I've gone through the dev docs, and the sections relevant to snapshot tests are:
- Development -> Testing -> [Running the tests](https://teammates.github.io/teammates/development.html#testing), which doesn't really mention how to update tests. It's also worth mentioning that if `npm run test` is ran after changes are made (which I find is often the case in my own development), sometimes no tests are ran at all, giving the impression that there are no changes needed to tests
- [Snapshot Testing](https://teammates.github.io/teammates/snapshot-testing.html), which mentions the default verification mode and how the auto-update mode is activated by pressing `u`

Unfortunately, the link between the 2 pages is not made explicit - the first doesn't mention snapshot testing, and the second doesn't mention the `npm run test` command.

My suggestion is to amend the docs such that this process is made clearer. For example, we could amend the Development page to link the snapshot tests to the command (and options), as well as add in a point to the Process page, which the generated PR description points to. Even just a paragraph mentioning the text (see above) would be useful, so that we could give contributors the link to it.

Possibly a checklist of test commands to run in the PR description would also be helpful, though I seem to remember some reservations about making the PR description too long.

**Comment by damithc** [comment]
It's good that you brought this up, @weiquu 👍 
If there is a gap in the documentation, this is a good time to fix it.
