### ISSUE TITLE
Instructor's Student Records Page: Moderate response button (on panel)

### ISSUE THREAD

**Issue by weiquu** [TEAMMATES/teammates#12666]
Clicking on the "Moderate response" button when the panel is open closes the panel instead of bringing the user to the moderate response page.

![Screenshot 2023-12-16 at 4 47 07 PM](https://github.com/TEAMMATES/teammates/assets/48304907/35a4e829-dad8-443e-a8c1-b26f65905cfa)

In addition, the "Moderate response" button is not clickable via screen reader controls. It just shows up as plain text (seems to be encompassed within the expand panel button):

![Screenshot 2023-12-16 at 4 47 43 PM](https://github.com/TEAMMATES/teammates/assets/48304907/3b96e716-30cf-4a5b-a073-b98b747a8c54)

**Comment by Ragul84** [comment]
I would like to work on this issue. Can i go ahead?

**Comment by domlimm** [comment]
Hello @Ragul84, feel free to submit a PR for this!

**Comment by thisismedg** [comment]
Can I contribute to this issue? I'm a first timer.

**Comment by cschetan77** [comment]
Hi @weiquu , I'm a first timer, I went through the TEAMMATES application and really liked it. 
Wanted to contribute.  Already went though the contribution guidelines and have the application up and running in my local. 

But was not able to reproduce the issue. However was able to create feedback sessions and get responses on those. Also getting Moderate option but not like what is shown in the image. Gone through help pages, but no luck.

Could you please let me know, what exact steps needs to be performed so I can reproduce it.

**Comment by weiquu** [comment]
Hi @cschetan77, I assume that you have found the student records page; if not, please log in as an instructor, find a student, and click on All Records (that URL will look something like http://localhost:4200/web/instructor/students/records?courseid=instructor.gma-demo&studentemail=alice.b.tmms@gmail.tmt).

After that, scroll down to any panel that has a Moderate response button. When the panel is open, clicking the button closes the panel instead of bringing the user to the moderate response page:


https://github.com/TEAMMATES/teammates/assets/48304907/940fc135-7b20-4b09-94f7-2f367e439e61



The second issue to resolve has to do with the screen reader. You should find out how to enable the screen reader on your computer, and navigate to the button using the screen reader controls.

**Comment by cschetan77** [comment]
Thanks @weiquu for prompt response and helping out. Was able to reproduce the issue. Started looking into it.
![image](https://github.com/TEAMMATES/teammates/assets/29810067/c8ddf1fc-09e6-4a92-af83-ccef4f679260)

**Comment by BusMihail** [comment]
Hi! I took an interest to this project and since I've seen no PRs on this issue I've solved the first problem myself. Unfortunately i can't figure out how to get the screen reader controls going to start working on the 2nd. Any tips? I am on Windows 11.

**Comment by cschetan77** [comment]
@cedricongjh sorry got involved somewhere else. Yes I'm looking into it. I was able to solve the button click issue, currently looking into the screen reader one. Will try to post the approach here to proceed. Thanks

**Comment by rapiddeveloper22** [comment]
Can I work on this issue

**Comment by cedricongjh** [comment]
hi @eraysozer20, feel free to submit a PR
