### ISSUE TITLE
Remove redundant newline in Development section of Docs

### ISSUE THREAD

**Issue by domlimm** [TEAMMATES/teammates#12671]
**Steps to reproduce**

Production/Live
1. Visit https://teammates.github.io/teammates/development.html#pre-requisites.

Locally
1. Change directory into the `docs` folder in project root i.e., `cd docs`.
2. Run `npm run serve`.
3. Visit http://127.0.0.1:8080/teammates/development.html#managing-the-dev-server-back-end.

**Expected behaviour**

Line 2 should be removed. Not sure why the line numbers are not showing locally, please disregard that.

![image](https://github.com/TEAMMATES/teammates/assets/46486515/46186698-4960-4370-b44c-add161a7ab09)

**Actual behaviour**

![image](https://github.com/TEAMMATES/teammates/assets/46486515/301d3d2f-6677-4674-ac97-95f832c6d4c0)

**Comment by pushkarkohli1** [comment]
planning to work on #12671
