### ISSUE TITLE
Course Joining Mail not recieved to Student

### ISSUE THREAD

**Issue by Ravinkumar2264** [TEAMMATES/teammates#12681]
- **Environment**: Production

**Steps to reproduce**
**1.** To send an email to the student joining the course.

**Expected behaviour**
 **1.** The student should recieve mail to join the course. 

**Actual behaviour**
![image](https://github.com/TEAMMATES/teammates/assets/153491308/c473227d-b67d-42be-aabe-0d417ec6fe5e)
1. The student does not recieve any notification and a mail. 
**Additional info**

**1.** The student will recieve the mail when the course feedback session is going to expire.

**Comment by weiquu** [comment]
Hi @Ravinkumar2264, as far as I'm aware, we don't send emails to students to join the course. See the below message (Instructor -> Students -> Send Invite):

> Usually, there is no need to use this feature because TEAMMATES sends an automatic invite to students at the opening time of each session. Send a join request to [email] anyway? 

The instructor has the option to trigger the invitation to join the course manually, either for all students or for individual students.

As you've pointed out, the student will receive an email for when the feedback session is about the expire, as well as right before it opens and when it opens (these details are in the create feedback session page).

I've done some checks and the emails send out accordingly.

Let me know if I've understood you correctly, and whether you've pointing out an issue or suggesting a possible enhancement. In the future, please also provide exact steps to reproduce the issue.

**Comment by damithc** [comment]
@Ravinkumar2264 In addition to what @weiquu said, the `Student notifications` page in your screenshot is not related to email notifications. Instead, it shows the system-wide notices (e.g., upcoming system down times)

**Comment by Ravinkumar2264** [comment]
>The instructor has the option to trigger the invitation to join the course manually, either for all students or for individual students.
My instructor has sent an invitation, but as I am a student, I don't receive any notification or the course joining invitation.

**Comment by weiquu** [comment]
Hi @Ravinkumar2264, I'm afraid I can't reproduce the issue. Can you give the exact steps you followed, as requested previously? Here are mine:
1. Log in as instructor
2. Go to the enrol students page of a course
3. Enrol a student
4. Go to the course details page and click on send invite for that particular student
5. Click on Yes in the popup
6. The email should have been sent to the student's email

You might also want to check your spam folder.

**Comment by Ravinkumar2264** [comment]
Yes, my instructor has followed all the steps you mentioned, but I haven't
received any emails. I have been waiting for more than 3 days, so I raised
an issue.

**Comment by Ravinkumar2264** [comment]
I forgot to follow step 2. Sorry for the confusion. Thank you for your feedback.
