### ISSUE TITLE
Excess padding on edit course details component 

### ISSUE THREAD

**Issue by domoberzin** [TEAMMATES/teammates#12693]
- **Environment**: 

**Steps to reproduce**
1) Go to home page as instructor
2) Click Instructors tab on a particular course -> Click on View/Edit

**Expected behaviour**
No excess padding at the bottom of the course details.

**Actual behaviour**
Excess padding observed at the bottom of the edit course details component.

**Additional info**

<img width="1248" alt="image" src="https://github.com/TEAMMATES/teammates/assets/74132255/0a58800c-e178-4b93-a5c3-02dea894c424">

**Comment by ananyasista** [comment]
Hi! I've never contributed to an open-source project before, but would I be able to take up this issue? If the issue can be corrected through HTML/CSS I should be able to give it a go

**Comment by weiquu** [comment]
Hi @ananyasista, yes the fix should be achievable with just HTML/CSS; feel free to submit a PR for this issue

**Comment by saloni0419** [comment]
Is anyone working on this #12693  issue @weiquu @domoberzin

**Comment by cedricongjh** [comment]
hi @saloni0419, let's let @ananyasista submit a PR for this (do let us know if you're not working on it any longer), in the meantime feel free to look into other issues that you're interested in

**Comment by pranay911** [comment]
@domlimm  Can you please assign this to me?

**Comment by domlimm** [comment]
@pranay911 Hi, we do not assign issues. As @ananyasista is working on it, please look for other issues tagged with `good first issue` for now 😄

**Comment by ArunErram** [comment]
can i work on these if it's not done by anyone ?

**Comment by cedricongjh** [comment]
hi @ArunErram, currently @ananyasista is still working on this issue

@ananyasista do let us know within 3 days if you're still working on this issue, else we'll assign it to the next person in the queue

**Comment by ananyasista** [comment]
Hi yes, I'm still working on this issue!

**Comment by abdullahsohailcs** [comment]
If this doesn't get solved do let me know. I would love to help

**Comment by pranay911** [comment]
@ananyasista @domlimm can you please assign this issue to me?

**Comment by weiquu** [comment]
Hi @pranay911, we do not assign issues. Since there are others who are waiting / currently working on the issue, I suggest you take a look at some other issue if you still wish to contribute.

@ananyasista do let us know if you need any help - we can take a look at your current implementation if you open a draft PR. Since it has been quite a while, do get back to us within the next 1-2 days, else we'll let @abdullahsohailcs have a shot at it.

**Comment by ananyasista** [comment]
Hi! Yes, I'll try to get a PR draft by tonight or tomorrow

**Comment by ananyasista** [comment]
@weiquu Actually, I don't think I have the time to complete this issue at the moment. Feel free to pass it on to the next person in line!

**Comment by frankgomezdev** [comment]
Looking to make my first (real) contribution to an open-source project. Would I be able to take up this issue?
