### ISSUE TITLE
Autosave and restore progress if user navigates away

### ISSUE THREAD

**Issue by ckcherry23** [TEAMMATES/teammates#12749]
### Autosave and restore progress if the user navigates away from the feedback form

**Environment**: Production

**Description of feature/enhancement**
* Autosave progress periodically (potentially in local storage) and give users who navigated away but did not submit responses an option to restore their progress, especially for text editors. 
* Maybe restore progress by default if users never submitted any responses.

**Justification**
* If we look at features in other apps, for example, creating GitHub issues itself, one simple navigation back and forward does not lead to any data loss. 
* The issue occurred pretty frequently with me as I ended up navigating away by mistake (going back by swiping on the touchpad) multiple times and lost progress.

**Comment by cliu585** [comment]
Hello! Would it be possible for me to work on this issue with @azhang49, @SongEmily, and @p0nk0?

**Comment by Respirayson** [comment]
Hi, I would like to work on this issue!
