### ISSUE TITLE
Student submitting responses: apostrophe turns into `&#39;`

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12864]
v8.30, production

Reported by a user:

>Anytime I submit a question response that involves an apostrophe it gets replaced with the following characters: `&#39;` I am on a MacBook Pro, 2021 and I’ve never seen that issue on any other platform.

I checked the submission of that user and found evidence of the problem:
![image](https://github.com/TEAMMATES/teammates/assets/1673303/7f0dc960-b88d-4385-85c6-a3a4900323db)

But I couldn't reproduce it myself.

I remember encountering a similar issue before, but I couldn't locate the corresponding issue. So, posting here so that we don't lose this user's bug report.

**Comment by cedricongjh** [comment]
i think the similar issue can be found here: https://github.com/TEAMMATES/teammates/issues/12578

**Comment by damithc** [comment]
Thanks for finding that, @cedricongjh 
Closing in favor if #https://github.com/TEAMMATES/teammates/issues/12578
