### ISSUE TITLE
Some feedback sessions duplicated in student home page

### ISSUE THREAD

**Issue by xenosf** [TEAMMATES/teammates#12875]
**Some feedback sessions duplicated in student home page**

- **Environment:** Live server at `V8.29.0`

**Steps to reproduce**
* Log into TEAMMATES as student with Google
    * Account has courses linked previously
* Go to student home page

**Expected behaviour**
* Each session is listed once

**Actual behaviour**
* Some sessions are listed twice

**Additional info**
Screenshot showing 2 courses with duplicated sessions:
<img width="1384" alt="" src="https://github.com/TEAMMATES/teammates/assets/40383042/582212be-dbdc-493c-99e6-8e296322e2ed">
Screenshot showing 1 course with duplicated sessions, 1 course with no duplicated sessions:
<img width="1234" alt="" src="https://github.com/TEAMMATES/teammates/assets/40383042/3cdbb46c-4d70-41b3-9dce-e378571a041b">

**Comment by cedricongjh** [comment]
seems like a FE bug, the API is being called twice

**Comment by drustanyjt** [comment]
Wanted to add another data point for this bug. I've also experienced this duplicate feedback session issue.

I'm currently taking the two courses shown (HSH1000, CS2103T) in AY2324 S2. I've also:
1. Authenticated using my Google account
2. Using Google Chrome as my browser
3. Website seems to say I'm using version `V9-0-0-b4`

![image](https://github.com/TEAMMATES/teammates/assets/110999129/7456cbf8-3624-4a8b-ba84-ecfcc01074f1)

**Comment by Respirayson** [comment]
Hi, would it be possible for me to work on this issue?

**Comment by cedricongjh** [comment]
hi @Respirayson, feel free to submit a PR
