### ISSUE TITLE
Caution instructors not to share the 'instructor copy' of the submission email with students

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12872]
Currently, when TEAMMATES sends a copy of a submission email to instructors, we included the following preamble:

![image](https://github.com/TEAMMATES/teammates/assets/1673303/651eb734-c7c3-4b80-9805-1894a546fed3)

Suggestions: 

1. Perhaps we can also mention something like the below, to prevent instructors from sharing this email with students (because if they do, students end up clicking on the dummy link in the email)

> Please do not share this email with students, as it does not contain the link students need to click (which is unique to each student).

2. It might also help if we don't hyperlink the dummy link placeholder?

3. Somewhat unrelated: Should we also add to the preamble something like  the below?

> We recommend that you make the following announcement (edit content as you see fit) using an alternative means (e.g., your course announcements) to  alert students:
>
> --------
> The TEAMMATES session ... in course ... is now open.
> If you did not receive the unique access link via email, and you can't find it in your spam box either, go to ... (info about link recovery page)
>
> --------

**Comment by cliu585** [comment]
Hello! Would it be possible for me to work on this issue with @azhang49, @SongEmily, and @p0nk0?

**Comment by cedricongjh** [comment]
hi @cliu585, feel free to submit a PR
