### ISSUE TITLE
Per-recipient stats are calculated based on student name, not email

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12894]
Reported by a user. V8.30

Example question:
![image](https://github.com/TEAMMATES/teammates/assets/1673303/3dacd437-352f-4da6-a4a5-d561bf3ed00b)

Problem:
Per-recipient stats are calculated based on student name. When there are multiple students with the same name, their scores are added up. It should be based on student email instead, which is the only field guaranteed to be unique. 

A similar problem might be affecting other places too, but this is the one reported by the user. As a temporary workaround, I've asked the used to disambiguate names so that no students have the same name.

**Comment by jckras** [comment]
Hi, can I work on this?

**Comment by cedricongjh** [comment]
hello @jckras feel free to submit a PR!

**Comment by jckras** [comment]
> Reported by a user. V8.30
> 
> Example question: ![image](https://private-user-images.githubusercontent.com/1673303/312165683-3dacd437-352f-4da6-a4a5-d561bf3ed00b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NTY3MzAsIm5iZiI6MTcxMDk1NjQzMCwicGF0aCI6Ii8xNjczMzAzLzMxMjE2NTY4My0zZGFjZDQzNy0zNTJmLTRkYTYtYTRhNS1kNTYxYmYzZWQwMGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMTc0MDMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2QwYzU4ZWJiM2Q3YTM0YmQxMjk3M2I2OGI4NzE5YTI4OWE4NTM2MWYyMzI3ZTljNDZlZTUzYzBjOTEwOTEyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DZGIBj-A8Fq-_q4-6Qz7udCX3NqZA9H7Z0tKQ4OfqZ0)
> 
> Problem: Per-recipient stats are calculated based on student name. When there are multiple students with the same name, their scores are added up. It should be based on student email instead, which is the only field guaranteed to be unique.
> 
> A similar problem might be affecting other places too, but this is the one reported by the user. As a temporary workaround, I've asked the used to disambiguate names so that no students have the same name.

Hi @damithc the image that was included with this example does not seem to be a visualization of the problem occurring. Can you please provide clearer details on how to reproduce this issue? Thank you.

**Comment by damithc** [comment]
@jckras steps required to reproduce the problem:
1. Create a course that has multiple students with the same name
2. Simulate a session that has a question such as the one given in the screenshot
3. View the results (as an instructor) of that session and examine per-recipient stats of students with the same name

**Comment by jckras** [comment]
@damithc Thank you! Can you explain what you mean by "Simulate a session"? I have created a session with a similar question such as the one in the screenshot, but how do I "simulate" it in order to get responses from students?

**Comment by jckras** [comment]
H @damithc, my partner @Hkovin and I have been working on this issue. We looked at somewhat similar issues for guidance such as [https://github.com/TEAMMATES/teammates/issues/12125](url) Do you have any idea what files might be causing this issue? Java or typescript?

**Comment by damithc** [comment]
@jckras Thanks for taking an interest in this issue. 

> What are your thoughts on this?

We can wait to see if other devs have some idea about this specific issue, but normally, it the the PR author's job to find the problem and propose a solution. So, try to come up with a solution that works, and the dev team members can give feedback on your solution.

**Comment by jckras** [comment]
@[damithc](https://github.com/damithc) Hi, I have a proposed solution for this bug! In the `msq-question-statistics.component.ts` file the perRecipientColumnsData object has the header descriptions shown below.
<img width="689" alt="Screen Shot 2024-03-27 at 1 06 39 PM" src="https://github.com/TEAMMATES/teammates/assets/99275379/00ab466c-7888-431a-b925-0e85f2f36d68">
In order to separate responses based on student email, I think I should add another component of the perRecipientColumnsData object that includes the recipient email. After this change, the  perRecipientColumnsData object implementation would look like the updated code shown below.
<img width="691" alt="Screen Shot 2024-03-27 at 1 06 54 PM" src="https://github.com/TEAMMATES/teammates/assets/99275379/9eacc754-d545-4b00-b738-45a74a2540ae">

**Comment by jckras** [comment]
Hi @damithc and @cedricongjh - found the issue, doing testing and submitting a PR this week. Wanted to follow up. Thank you!
