### ISSUE TITLE
Check if the search service is active in account request search test

### ISSUE THREAD

**Issue by jayasting98** [TEAMMATES/teammates#12901]
Currently, `AccountRequestsDbIT::testSqlInjectionSearchAccountRequestsInWholeSystem` does not check if the search service is active.

https://github.com/TEAMMATES/teammates/blob/234218979f55d3eb5689186ad737dcbdd22b3df8/src/it/java/teammates/it/storage/sqlapi/AccountRequestsDbIT.java#L196-L209

This leads to the following failing test if you try to test locally without the search service.

![image](https://github.com/TEAMMATES/teammates/assets/65202977/591ed384-6a70-4291-880c-40896a367c68)

To fix this, we can check if the search service is active, before running the rest of the test, like in the following.

https://github.com/TEAMMATES/teammates/blob/234218979f55d3eb5689186ad737dcbdd22b3df8/src/it/java/teammates/it/storage/sqlsearch/AccountRequestSearchIT.java#L117-L123

**Comment by jayasting98** [comment]
We may also want to move the test method into `AccountRequestSearchIT`.

**Comment by techMedMau** [comment]
Hi, may I work on this issue?
Besides, it seems like this issue only needs to add a check condition to ensure the search service is on and move it to the right file.
Am I understanding it correctly?

Thank you

**Comment by traitsisgiorgos** [comment]
can I take the issue?

**Comment by domlimm** [comment]
@techMedMau Hey Maureen, as you've previously contributed before. Let's leave this for a new contributor.

@traitsisgiorgos Feel free to submit a PR for this.

**Comment by traitsisgiorgos** [comment]
thanks!!

**Comment by AggarwalNeelesh** [comment]
Hey , I am a beginner in open source having experience in java.
I want to solve this issue

**Comment by jayasting98** [comment]
@AggarwalNeelesh Hi, thank you for your interest. Let's give @traitsisgiorgos some time to try to do this. If they decide not to continue with this, you may try to tackle this issue.

**Comment by traitsisgiorgos** [comment]
Can I ask you a question ?

**Comment by traitsisgiorgos** [comment]
@jayasting98

**Comment by traitsisgiorgos** [comment]
We also want to move the method to the correct file?

**Comment by simranfarrukh** [comment]
Hello, may I work on this issue?

**Comment by jayasting98** [comment]
> We also want to move the method to the correct file?

Hi @traitsisgiorgos, yes, we may want to move it over to `AccountRequestSearchIT`.

**Comment by jayasting98** [comment]
Hey, @simranfarrukh, thank you for your interest. @traitsisgiorgos is working on this right now. If you want, you can consider handling a different issue.

**Comment by EmilyMSong** [comment]
Is this issue still available to be worked on? I would like to work on it with my team for a class project!

**Comment by jayasting98** [comment]
Hello, @EmilyMSong. @traitsisgiorgos is currently working on this right now. Nevertheless, if you would still like to contribute, there are other issues that you can consider working on.

**Comment by itstrueitstrueitsrealitsreal** [comment]
Hi, @jayasting98. I am looking to work on this project and I am trying to get `AccountRequestsDbIT::testSqlInjectionSearchAccountsRequestsInWholeSystem` to pass.

I have made the changes locally, and it seems that #13101 also remedies this issue, but has not been merged in. 

Would it be possible to work on this issue? Thanks!

**Comment by traitsisgiorgos** [comment]
you can work on it
