### ISSUE TITLE
Dev docs (E2E testing): Chromedriver link broken

### ISSUE THREAD

**Issue by xenosf** [TEAMMATES/teammates#12909]
Link to Chromedriver download broken in e2e testing dev docs

- **Environment**: https://teammates.github.io/teammates/e2e-testing.html#using-chrome

Link to chromedriver download in the docs is `https://sites.google.com/a/chromium.org/chromedriver/downloads`, which leads to a "not found" page:
<img width="927" alt="image" src="https://github.com/TEAMMATES/teammates/assets/40383042/bacf0cfc-d608-4e59-8d09-f7a3e82e1869">

Link should be `https://chromedriver.chromium.org/downloads`

**Comment by nadasuhailAyesh12** [comment]
I am a new contributor.I want a merged PR for my open source university assignment can I proceed one .

**Comment by NicolasCwy** [comment]
@nadasuhailAyesh12 Hi please go ahead!

**Comment by dhrax21** [comment]
Hey I want to work on this issue:)

**Comment by NicolasCwy** [comment]
@dhrax21 Lets give @nadasuhailAyesh12 3 days to respond else you can work on this
