### ISSUE TITLE
Gradle task componentTests should not stop entirely when only one task fails

### ISSUE THREAD

**Issue by jayasting98** [TEAMMATES/teammates#12900]
The Gradle task `componentTests` now depends on the two Gradle tasks `unitTests`, and `integrationTests` since #12056. These can be independent from each other, so if one fails, we should continue to execute the other (except when it fails due to the failure of a common dependency, like compilation). However, when either of them fails due to a failing test, the other one is not completed because the execution of the whole `componentTests` task is aborted.

To prevent this, we can run `componentTests` with the option `--continue`, just like the Gradle task `lint`. This probably needs to be changed in the GitHub workflows and in the documentation.

**Comment by Hkovin** [comment]
Hi, me and my classmate @jckras want to contribute to our first open-source project. Can we resolve this issue?

**Comment by weiquu** [comment]
Sure @Hkovin, feel free to open a PR for this issue

**Comment by Hkovin** [comment]
> Sure @Hkovin, feel free to open a PR for this issue

Hi, my partner and I need to work on an issue with different requirements so we can no longer work on this one. Thank you though!

**Comment by emrekenar** [comment]
Hello, can I work on this issue?

**Comment by jayasting98** [comment]
@emrekenar Hi! Thank you for your interest in the project. Since there is nobody currently working on this, you are free to submit a PR for this.
