### ISSUE TITLE
Existing Test data json has to be manually migrated to SQL format

### ISSUE THREAD

**Issue by NicolasCwy** [TEAMMATES/teammates#12920]
**Description of feature/enhancement**
Existing JSON test data used for tests is in the format for the current noSQL database. Migrating each JSON file by hand can be tedious due to the foreign key relationships enforced by SQL and any other attribute changes. This can be solved by using a user script to migrate these files instead

**Proposed Usage**
1. Specify JSON file to migrate, and create migrated file in same directory as JSON file
2. Create a folder to place JSON files to migrate and migrate all JSON files

Comments on what would be easier to use to use is welcome

**Comment by NicolasCwy** [comment]
@cedricongjh Do let me know which is better!

**Comment by cedricongjh** [comment]
i think 1. is better, as that is how we will be using this script when migrating e2e tests, we will only be creating one new file per e2e test
