### ISSUE TITLE
CreateAccountAction seems to have redundant code

### ISSUE THREAD

**Issue by jayasting98** [TEAMMATES/teammates#12954]
The following code seems to be redundant.

https://github.com/TEAMMATES/teammates/blob/a9423daf0778ca72d0bd71e67ca1ab73e76edb7f/src/main/java/teammates/ui/webapi/CreateAccountAction.java#L114-L115

## Explanation

We obtain the account request from the database, so whatever data it has is already in the database.

https://github.com/TEAMMATES/teammates/blob/a9423daf0778ca72d0bd71e67ca1ab73e76edb7f/src/main/java/teammates/ui/webapi/CreateAccountAction.java#L55

Specifically, the email address, and the institute we get here should be the one already in the database.

https://github.com/TEAMMATES/teammates/blob/a9423daf0778ca72d0bd71e67ca1ab73e76edb7f/src/main/java/teammates/ui/webapi/CreateAccountAction.java#L66-L68

We call this method without having done any changes yet to the account request, the email address, and the institute.

https://github.com/TEAMMATES/teammates/blob/a9423daf0778ca72d0bd71e67ca1ab73e76edb7f/src/main/java/teammates/ui/webapi/CreateAccountAction.java#L95

So it should not be necessary to set the email address, and the institute here. Firstly, the account request already has those values. Secondly, those values are also already in the database.

https://github.com/TEAMMATES/teammates/blob/a9423daf0778ca72d0bd71e67ca1ab73e76edb7f/src/main/java/teammates/ui/webapi/CreateAccountAction.java#L106-L120

**Comment by eraldprifti03** [comment]
Hello, i would like to work on this issue, if possible.
