### ISSUE TITLE
Translation of Code of Conduct into Spanish

### ISSUE THREAD

**Issue by skylar-mo** [TEAMMATES/teammates#12952]
Since this project is working towards helping people all over the world, my suggestion is to translate the Code of Conduct into Spanish. This will encourage more programmers to get involved and will also demonstrate an inclusive environment. A classmate of mine has also suggested to translate the README.

**Comment by wkurniawan07** [comment]
[The code of conduct is based on Contributor Covenant and is already available in many languages, including Spanish.](https://www.contributor-covenant.org/translations/)
