### ISSUE TITLE
Release V9.0.0-beta.5

### ISSUE THREAD

**Issue by ziqing26** [TEAMMATES/teammates#13060]
Scheduled for Sunday, 21 Apr, 2024

Release Lead: @ziqing26 @cedricongjh 

- [x] Tagged the latest stable release code with the latest version number
- [x] Released changelogs

PM:

- [x] Deployed the new version
- [x] Released the new version for end users

**Comment by damithc** [comment]
Deployed and released. Thanks to all who pitched in 💯
