### ISSUE TITLE
Use AccountRequestUpdateRequest as parameter

### ISSUE THREAD

**Issue by ziqing26** [TEAMMATES/teammates#13064]
**Environment**: `master`

**Description of feature/enhancement**

Currently the AccountRequestUpdate parameters are passed in as separate parameters (see this [link](https://github.com/TEAMMATES/teammates/blob/4682dffb71e4566ed72a9e8a7b2b814e8d16f869/src/web/services/account.service.ts#L121-L136)).

We want to change it to take in one type as the parameter, instead of passing every parameters in separately. An example of how a type is passed in to represent all parameters: [link](https://github.com/TEAMMATES/teammates/blob/4682dffb71e4566ed72a9e8a7b2b814e8d16f869/src/web/services/course.service.ts#L139-L142)

**Justification**

This refactors the code in a more maintainable way, as developers do not need to update the function parameters every time there is a change. Instead, they can just edit the typescript type.

**Comment by SaquibKhanANU** [comment]
Hello, i am interested in attempting this issue

**Comment by ziqing26** [comment]
Hi @SaquibKhanANU sure feel free to submit a PR:)

**Comment by Akshay1018** [comment]
Hi @ziqing26 if this issue is not assigned to anyone, you can assign it to me. I can take this up. Thanks

**Comment by ziqing26** [comment]
Hi @SaquibKhanANU and @Akshay1018 , thank you for your interest. Currently there is an open PR by @Stain19 . If that is not merged but closed in the future, feel free to submit PR but for now you might want to look for another good first issue in TEAMMATES. Thank you:)
