### ISSUE TITLE
Release V9.0.0-beta.6

### ISSUE THREAD

**Issue by ziqing26** [TEAMMATES/teammates#13084]
Scheduled for Tuesday, 23 Apr

Release Lead: @ziqing26 

- [x] Tagged the latest stable release code with the latest version number
- [x] Released changelogs

PM:

- [x] Deployed the new version
- [x] Released the new version for end users

**Comment by ziqing26** [comment]
[V9.0.0-beta.6](https://github.com/TEAMMATES/teammates/releases/tag/V9.0.0-beta.6) has been released by @ziqing26 at April 23rd, 2024, 02.09pm SGT.

Code contributions from: @cedricongjh, @domoberzin, @xenosf
Review contributions from: @jayasting98, @weiquu, @ziqing26 

Ready for post-release check and deployment by PM (@damithc).

**Comment by damithc** [comment]
Deployed and released. Thanks for the quick patch everyone! 💯
