### ISSUE TITLE
Admin managing account requests: use spinners to indicate actions in progress

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#13105]
V9-0-0-b6, production

Current: When the admin is dealing with account requests (e.g., approving/rejecting/deleting etc.), there is no UI change during the time between clicking a button and result message showing up

Suggested: Use spinners to show some action is in progress, similar to how we use spinners elsewhere in TEAMMATES

**Comment by Ceaseless04** [comment]
Hi, can I be allowed to work on this feature? I would like to implement the UI change that consists of a spinner to show that the task is in progress. 

If possible can you also provide a GIF of how the spinner is used in TEAMMATES?

**Comment by Andy-W-Developer** [comment]
Hey Ceaseless04,

Here is a spinner example on the Edit Course Details page for instructors.

https://github.com/TEAMMATES/teammates/assets/128531452/3a10b4f5-5341-460b-94c4-f61f4727d15a

**Comment by Andy-W-Developer** [comment]
@Ceaseless04 any updates on this issue?

**Comment by damithc** [comment]
> Here is a spinner example on the Edit Course Details page for instructors.
> https://github.com/TEAMMATES/teammates/assets/128531452/3a10b4f5-5341-460b-94c4-f61f4727d15a

@Andy-W-Developer Thanks for providing this example.
@Ceaseless04 to add, here's where the spinner appears:
![image](https://github.com/TEAMMATES/teammates/assets/1673303/fb269730-103d-4c72-b9b5-9c81f74472c7)
