### ISSUE TITLE
Account request form: No need to CC the email 'Acknowledgement of Instructor Account Request'

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#13103]
When a user submits an account request, s/he is sent an ACK email with the subject `Acknowledgement of Instructor Account Request`.

Current: This email is CC'ed to the admin
Suggested: There is no need to CC  this to the admin, as there is another email sent to admin to alert him about the new account request

**Comment by Ashwinn11** [comment]
I would like to work on this. Can i get assigned?

**Comment by jayasting98** [comment]
Hi, @Ashwinn11. Thank you for your interest. Feel free to create a pull request for this issue.
