### ISSUE TITLE
Join course: email user after joining a course for the first time

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#1368]
This email can serve as a record of which Google ID was used to access TEAMMATES. Furthermore, it can help detect accidental joining using other people's accounts

**Comment by HirdayGupta** [comment]
@damithc Just to be clear, you mean a confirmation email after the student registers himself by signing in with a google ID after clicking the link sent in the course-join invitation email? What all information would this email contain?

**Comment by damithc** [comment]
> @damithc Just to be clear, you mean a confirmation email after the student registers himself by signing in with a google ID after clicking the link sent in the course-join invitation email? What all information would this email contain?

Yes.
Info: Course code/name, google ID used to join, what to do if the joining was a mistake (email us).

**Comment by HirdayGupta** [comment]
@damithc Should I also send the email to the instructors who register their googleids (the ones who are invited to join by other instructors)? The arguments in favour of sending the email to students (ie record for Google ID used and accidental joining using other people's accounts) also apply to instructors.

**Comment by damithc** [comment]
> @damithc Should I also send the email to the instructors who register their googleids (the ones who are invited to join by other instructors)?

Yes, that can be useful too. It can be a separate issue if it can be cleanly separated. We prefer smaller PRs whenever possible.

**Comment by HirdayGupta** [comment]
@damithc It can be quite cleanly separated, but then the second PR would just be concerned with how to move the email sending method from the specific student verifation action class to the general action class so that it can be reused in the instructor verification action. Because everything else is the same. I think even the email template looks the same for both instructors and students.

**Comment by damithc** [comment]
> forgot to ask, keeping this in mind, should I still do this in separate PRs or the same PR only?

I'll leave you to decide. I'm OK with both.
