### ISSUE TITLE
Add Action level tests for deletion of response when MCQ and MSQ question is edited

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#1419]
Ensure that existing responses are modified appropriately when an MCQ or MSQ question is edited.

**Comment by damithc** [comment]
@LowWeiLin this should be a Action level test? Don't we need similar tests for other types such as numeric scale? e.g. the scale is changed while in a way that existing responses don't match the new scale.

**Comment by rcyq** [comment]
Yes, the deletion of existing responses when a question (MCQ/MSQ/NumScale) got edited is tested in the Action level test (InstructorFeedbackQuestionEditActionTest).

**Comment by damithc** [comment]
@rcyq is there a corresponding UI test that checks for the warning dialog?
