### ISSUE TITLE
instructorStudentComment: add to mashup.jsp

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#1499]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on January 13, 2014 18:36:33_

We want to see how comments are shown in the UI

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1500_

**Comment by zulrich91** [comment]
Please i need some clarifications about this issue ?. I dont understand what one is suppose to do here .

**Comment by BillyZafack** [comment]
I like to have this as my 1st issue. But I will need more precisions on the problem

**Comment by nsaiisasidhar** [comment]
Hi, can you please let me know if there is any criteria on how to specify a particular parameter value, needs to be appended to parameter keys in **ActionURIs** in mashup.jsp

**Comment by nsaiisasidhar** [comment]
Hi, can you please let me know if there is any criteria on how to specify a particular parameter value, needs to be appended to parameter keys in ActionURIs in mashup.jsp. For example, **fsname** = _First+feedback+session_ and **_courseid_** = _CS2104_.

**Comment by nsaiisasidhar** [comment]
Hi, I submitted a pull request with required code changes to mashup.jsp

I request other aspiring contributors, not to submit any pull requests for this issue, as I want to have this as my first issue.

In case any corrections are to be made (such as in the key-value pairs appended to URI's), please let me know, I'll make them promptly.

**Comment by wkurniawan07** [comment]
Outdated; instructor comments page and student comments page have both served to display how comments are shown in the UI.
