### ISSUE TITLE
NUMSCALE question: Strengthen step validation for question creation/submission

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#1562]
_From [arnold.k...@gmail.com](https://code.google.com/u/105779801956403207546/) on January 27, 2014 16:48:59_

Currently, the create/submit forms does not enforce that:
1) The range is divisible by the step (warning is shown but not enforced)
2) The submitted value is one of the possible values according to the step

This is because of difficulties in reliably checking whether or not the input is in accordance to the two rules above. The difficulty is caused by float precision problems in javascript. 

A workaround needs to be found and the validation rules enforced.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1563_

**Comment by samsontmr** [comment]
There doesn't appear to be a check in `FeedbackNumericalScaleResponseDetails`. I'm guessing that is where the check should be happening?
