### ISSUE TITLE
Welcome stranger message can be improved in student home

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#1563]
_From [wulifu20...@gmail.com](https://code.google.com/u/107379343006199273595/) on January 27, 2014 23:37:05_

What can be improved on the system? What can be added to the system? 1. The welcome stranger message doesn't attract the attention of the users very well. It doesn't make me feel that something is going wrong and I better take a look at it
2. the welcome message in the student home page can be improved to be more readable (a lot of information, no highlight) Please specify: 1) Exact page to implement/improve feature after student login (student home) 2) The details of the feature a) show the "welcome stranger" msg in a way that attracts people's attention. eg. show a big notice such as "oops, you are not a registered student"
b) highlight the important sentence (eg. make it bold or use another color)

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1564_

**Comment by damithc** [comment]
This message was drafted before we started allowing unregistered access to students. The message can be reworded to mention the possibility of unregistered access.

**Comment by sujeet14108** [comment]
@damithc  Hi i have solved this issue as shown below. Should anything more is required or i send a pull request?
![screenshot from 2016-03-01 17 31 12](https://cloud.githubusercontent.com/assets/9781422/13426478/9b8bc35c-dfd3-11e5-8038-6f1b65973f40.png)

**Comment by damithc** [comment]
Suggested new message:

{in red, bold, normal size letters} **Oops! Your Google account is not known to TEAMMATES.**

{normal letters}
To access a course on TEAMMATES, first you need to wait till an instructor adds you to that course and TEAMMATES sends you instructions on how to access that particular course in TEAMMATES.

If you 'joined' the course in TEAMMATES using a Google account before, but cannot login anymore, these are the possible reasons:
{the rest can be as before, but no need for highlighting}

**Comment by sujeet14108** [comment]
@damithc Is this ok?
![screenshot from 2016-03-05 11 20 12](https://cloud.githubusercontent.com/assets/9781422/13545978/477416ea-e2c4-11e5-8f52-0a72299b468b.png)
