### ISSUE TITLE
adminAccountAdd: make the demo course session more recent

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#1571]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on February 01, 2014 08:55:54_

Currently, one of the sessions in the demo course is given a very old date. As a result, its stats don't show up in the home page. May be we can set it to a current date when creating the demo course?

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1572_

**Comment by mukesh14149** [comment]
@damithc  Sir Which Stats are you talking about?
![t1](https://cloud.githubusercontent.com/assets/10887629/24792550/1fc6fb14-1b9c-11e7-931a-4a1c436b5060.png)
All sessions correctly showing their responses.

**Comment by damithc** [comment]
The stats its referring to are no longer in the home page. Closing.
