### ISSUE TITLE
Add gmail testing for InstructorFeedbackRemind

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#1590]
_From [arnold.k...@gmail.com](https://code.google.com/u/105779801956403207546/) on February 06, 2014 13:00:01_

Like for evaluation, feedback remind action should be tested on whether or not an email is received by the student by retrieving emails from the gmail account and verifying the reminder email is received.

Should be done when tests are run on live/staging server.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1591_

**Comment by wkurniawan07** [comment]
Pretty sure `InstructorCourseDetailsPageUiTest` has already included this.
