### ISSUE TITLE
instructorStudentList: add a 'mailto' link under the list of emails

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#1682]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on March 06, 2014 15:59:51_

Such a link makes it easier to email the students shown in the list.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1684_

**Comment by xpdavid** [comment]
@damithc Is this acceptable?
![sequence 01](https://cloud.githubusercontent.com/assets/13977235/22626424/f7c1b174-ebe7-11e6-9c80-4f1f4b2dda49.gif)

**Comment by damithc** [comment]
@xpdavid yes, that can work. Does `Ctrl+C` is understood by Mac users too?

**Comment by xpdavid** [comment]
![screen shot 2017-02-05 at 9 59 34 pm](https://cloud.githubusercontent.com/assets/13977235/22626686/85cb5884-ebee-11e6-9c9d-4dd01240e436.png)
There are some places in Teammates also using "... `Ctrl + C` to copy ...".
I think user can always use right click to copy it. Maybe change it to
> Email is now selected, you may copy it (`Ctrl + C`) and paste it (`Ctrl + V`) to your email client.

**Comment by damithc** [comment]
Yes, I guess Mac users will know what to do. Should be `Emails`.
