### ISSUE TITLE
Show date in a universally understood format

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#1701]
Users from US may not be used to the current format we show the date and mix up month and date. We should use a format that is universally understood and not confusing to any user. 

The format used in the home page is fine but not so in other places. In particular, 'instructor edit session details' page.

![image](https://cloud.githubusercontent.com/assets/1673303/25770003/f2cba46c-325b-11e7-920d-16ac8c5ae884.png)

**Comment by HirdayGupta** [comment]
Beginning work on this issue. Question: Would you want to change the way dates are stored across this page?

**Comment by nidhi98gupta** [comment]
@damithc I would like to work on this issue.

**Comment by damithc** [comment]
> @damithc I would like to work on this issue.

@nidhi98gupta sure.

**Comment by nidhi98gupta** [comment]
@damithc Sir, I have a question.
I changed the date format to Mon, 21 Mar 2011 in instructorFeedbackEdit.js which shows right date format when any date is selected from datepicker. 
![date](https://user-images.githubusercontent.com/24381442/35053510-456f716a-fbd0-11e7-813b-7c54e475b992.png)
 But on selecting that feedback session again from Session page doesn't show new date format i.e it shows old format only. Also dates of feedback session doesn't get updated. 
I tried changing date format in timeHelper.java but it didn't help. Please guide me.

**Comment by damithc** [comment]
> I tried changing date format in timeHelper.java but it didn't help. Please guide me.

@nidhi98gupta I don't know how to fix this issue myself. :-p hopefully some other dev who has some expertise in this part of the code can weigh in. If not, we have to wait till another contributor who can figure it out comes along.
