### ISSUE TITLE
Refreshing instructorCourses.jsp refill textboxes and staus message

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#1774]
_From [malinda...@gmail.com](https://code.google.com/u/115975016700225696121/) on April 08, 2014 11:06:28_

instructorCourses.jsp
1. add a new course using above page.
2. after succeeded, refresh the page.
3. textboxes are filled with past values and status is shown as course is already exist.

reason for this issue is also same as issue 1722 . 
but we can avoid filling textboxes again.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1777_

**Comment by bamboo3250** [comment]
The reason for this issue to happen is not because of refreshing instructorCourses.jsp but redoing the InstructorCourseAddAction, which adds the course again. This is expected behaviour so I'm not sure we should fix this.

**Comment by damithc** [comment]
See if there is a better approach to handle this situation. May be redirect to instructorCoursesPage instead of the instructorCourseAdd page? Anyway, this is not urgent because the problem doesn't cause any damage to the data.

**Comment by damithc** [comment]
Duplicate
