### ISSUE TITLE
Validation for MCQ/MSQ responses

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/teammates#1805]
Validation should be done on MCQ/MSQ responses to ensure they match the options available.

Manipulating the DOM from the browser can allow students to submit options other than those given.
![untitled](https://cloud.githubusercontent.com/assets/3910365/2898872/975990e2-d5a9-11e3-890b-017008b8875d.png)

**Comment by samsontmr** [comment]
Has this issue been solved?

**Comment by damithc** [comment]
> Has this issue been solved?

@samsontmr this is an old issue (as you can guess from the screenshot). You may have to verify yourself if ti still exists.
