### ISSUE TITLE
Student: submit responses: show a 'closing soon' warning

### ISSUE THREAD

**Issue by thyageshm** [TEAMMATES/teammates#1872]
A provision for a warning that will inform the student/instructor submission giver when there is little time left (maybe 15 mins). 

A message like: "Please take note that only x minutes are left for this submission to close and be informed that you would have to submit the COMPLETED form before the feedback session closes."

**Comment by Neurrone** [comment]
I'd like to work on this.

In src/main/java/teammates/common/datatransfer/FeedbackSessionAttributes.java, why is the additional check being done in the isClosingWithinTimeLimit method (line 343)?

Looks like it would cause method to return true only if the number of hours left is 1 less than the time limit being checked for. Is this to stop multiple closing reminders from being emailed, based on the comment above?

**Comment by AnaghHegde** [comment]
@Neurrone Shall i work on this?.

**Comment by Neurrone** [comment]
@AnaghHegde sure.

**Comment by AnaghHegde** [comment]
@Neurrone I assume you have done some work on this earlier based on what you have commented above.  I didn't get what you were trying to say in the above comment. Can you brief me a little about it?.

**Comment by Neurrone** [comment]
@AnaghHegde afraid not. Tried working on this as my first contribution to teammates, which was some time ago, so I don't remember much about it. Didn't write any code for this, since I needed to understand the current code first.

**Comment by AnaghHegde** [comment]
@Neurrone @damithc @thyageshm Should i need to consider the grace time also?.

**Comment by damithc** [comment]
> Should i need to consider the grace time also?.

No. Students are unaware of the grace period.

> also it should be sent to only to those students who have not submitted yet right ?

No, it can be for anybody who loads the page.

BTW, there is no need for a countdown. Just show a one-time warning at page load if there is less than 15 minutes left.

**Comment by AnaghHegde** [comment]
@damithc I am confused. Are we gonna send them email or it will be just displayed in the feedback session page?.

**Comment by damithc** [comment]
> Are we gonna send them email or it will be just displayed in the feedback session page?.

2nd one.

**Comment by AnaghHegde** [comment]
@damithc Is it ok if i use just `Window.alert()` or something else (beautify it using some libraries) ?.

**Comment by damithc** [comment]
> Is it ok if i use just Window.alert() or something else( which is used in the teammates earlier i couldn't find any so) ?.

Follow the approach we use in other similar situations, e.g. we show an alert when a student loads a submission page that is already past the deadline

**Comment by AnaghHegde** [comment]
@damithc is this fine ?
![screenshot 128](https://cloud.githubusercontent.com/assets/12005551/25188532/04214d2c-2544-11e7-8a2c-881e42513ed6.png)

**Comment by damithc** [comment]
Yes, a message like that will do. You can use this text `Warning: you have only x minutes before the submission deadline expires!`

**Comment by HirdayGupta** [comment]
May I take this issue if @AnaghHegde is not going to finish his PR? I have an idea for a slightly different implementation.

**Comment by AnaghHegde** [comment]
@HirdayGupta Please give me 3-4 days. I am busy with internship. I am not able to find time. I will do it over the weekends. Ok?

**Comment by HirdayGupta** [comment]
Sure @AnaghHegde 😃

**Comment by chowyb** [comment]
@HirdayGupta you may take up this issue if you're still interested in it.
