### ISSUE TITLE
Instructor: send submission reminders: check if session is open before sending

### ISSUE THREAD

**Issue by thyageshm** [TEAMMATES/teammates#1883]
In InstructorFeedbackRemindAction, currently we do not check if the session is open before sending the reminders for the feedback givers who are (expected) to give feedback.

**Comment by HirdayGupta** [comment]
Dropping a note that the UI is probably incorrectly left enabled due to #7943

**Comment by HirdayGupta** [comment]
> Dropping a note that the UI is probably incorrectly left enabled due to #7943

Apologies for the above comment. I just tested it out again and the UI does get correctly disabled.

However as @damithc sir said: 
> In any case, it is better to check in the backend as well

I will be pushing a PR for this issue soon.
