### ISSUE TITLE
Add test Cases for helper functions in datepicker.js

### ISSUE THREAD

**Issue by thyageshm** [TEAMMATES/teammates#1939]
4 new functions have been added to the datepicker.js file and need JS test cases.

All are very simple to be tested.

**Comment by AnaghHegde** [comment]
@thyageshm is this still open?can i work on this?.I have recently completed the d.FirstTimers .

**Comment by thyageshm** [comment]
Hi, welcome to the team! I believe it is still open. Please go ahead and give it a try.

**Comment by AnaghHegde** [comment]
@thyageshm Can you please be a little specific about the functions?. Like what are the new functions that were added? or can you guide me a little. So that i will get a clear picture about the issue.

**Comment by thyageshm** [comment]
Please take a look at src/test/javascript folder. There are 4 isolated functions defined at the bottom of the page. Follow the examples of other jsTests and test those 4.

**Comment by AnaghHegde** [comment]
@thyageshm Can you please tell exactly or be more specific. I am confused here.

**Comment by damithc** [comment]
@AnaghHegde let's try to finish your other PR first. Also, try to pick issues that you have a reasonable idea how to do.

**Comment by VamsiSangam** [comment]
Can I work on this issue?

**Comment by VamsiSangam** [comment]
And just to update the issue, there are currently 3 helper functions in [datepicker.js](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/js/datepicker.js) -

``` javascript
/**
 * Adds an event handler on all passed in divs to open datepicker on 'click'.
 * @assumption: all passed in divs are valid datepicker divs
 */
function triggerDatepickerOnClick(datepickerDivs) {
    $.each(datepickerDivs, function(i, datepickerDiv) {
        datepickerDiv.on('click', function() {
            if (!datepickerDiv.prop('disabled')) {
                datepickerDiv.datepicker('show');
            }
        });
    });
}

/**
 * @assumption: startDate has a valid value
 * @returns {Date} publishDate if it is valid and smaller than startDate, else startDate
 */
function getMaxDateForVisibleDate(startDate, publishDate) {
    var minDate = 0;

    if (publishDate === null || publishDate === undefined) {
        minDate = startDate;
    } else if (startDate > publishDate) {
        minDate = publishDate;
    } else {
        minDate = startDate;
    }

    return minDate;
}

/**
 * @assumption: visibleDate has a valid value
 * @returns {Date} visibleDate
 */
function getMinDateForPublishDate(visibleDate) {
    return visibleDate;
}
```

**Comment by thyageshm** [comment]
@VamsiSangam, sure take a shot at it :-)
