### ISSUE TITLE
BackDoorLogic: optimize persistDataBundle method

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2258]
Optimize this method so that it uses *Db methods directly instead of going through Logic layer. Furthermore, we can use `persistAll` instead of persisting one entity at a time.

**Comment by whipermr5** [comment]
After an initial look through the code, `persistDataBundle` does use the `*Db` methods; however it seems there currently are multiple calls to persist the data throughout the `*Db` `create*` methods. If we can keep everything in memory before one final call to persist everything, we should get a significant speed up. Perhaps the `create*` methods can be modified to take in one more parameter, a boolean specifying whether or not to persist the data?

**Comment by damithc** [comment]
> Perhaps the create* methods can be modified to take in one more parameter, a boolean specifying whether or not to persist the data?

Can give it a try. Before deciding, we need to see the additional complications it brings in and the performance gain it provides.

**Comment by whipermr5** [comment]
Note to self: use [Objectify deferred operations](https://github.com/objectify/objectify/wiki/BasicOperations#deferring-operations) for `persistDataBundle`.
