### ISSUE TITLE
Add specific error messages to error pages such as error.jsp

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#229]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on June 29, 2012 16:29:45_

It is better to show specific error message in the error page.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=230_

**Comment by thyageshm** [comment]
@damithc sir, what exactly are the requirements for this issue? We have some "custom" error pages in teammates right now. I guess in 2012 we only had one error page?

**Comment by damithc** [comment]
Even the custom error pages have fixed content. We should be able to add a more specific message. For example, for 'entity not found' some hint about which entity was not found.

**Comment by damithc** [comment]
old issue. closing.
