### ISSUE TITLE
Fix question visibility options striped table in instructorFeedbackEditPage

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/teammates#2296]
The stripes do not alternate properly when some rows are hidden.

**Comment by visithamanujaya** [comment]
hi 
can i try this
i have already completed the orientation task
here is my link for my status
https://groups.google.com/forum/m/#!topic/teammates-contributors/gcRNXx4ei98

**Comment by damithc** [comment]
No longer relevant
