### ISSUE TITLE
Student: view team: allow viewing team members' profiles

### ISSUE THREAD

**Issue by thyageshm** [TEAMMATES/teammates#2297]
Currently students cant view other students' profiles.

A list of team members is available in studentCourseDetailsPage and can be used as links to the profile page. 

Access Control needs to be amended and IMPT: the link to the image has to use encrypted studentemail and course instead of the blob-key when the viewer is another student.

**Comment by damithc** [comment]
Currently students can view the profile pic of team members, but not other details.
