### ISSUE TITLE
instructorFeedbackSessionAdd form: Give an edit links to both sentences

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2305]
Currently, the edit link is given to the 2nd sentence only. Some users might think the session visibility (first sentence) cannot be changed.
By the way, 'change' may be better than 'edit'? 'change' is the intent, 'edit' is the mechanism.

**Comment by mikelimantara** [comment]
Hi, can I start on this issue?

**Comment by xpdavid** [comment]
Is this acceptable? @damithc 
<img width="1148" alt="screen shot 2017-01-14 at 3 31 04 pm" src="https://cloud.githubusercontent.com/assets/13977235/21954884/3e0d1e6c-da99-11e6-9bcf-af3d3a97bb49.png">
One link for a submission form.
<img width="1131" alt="screen shot 2017-01-14 at 3 31 11 pm" src="https://cloud.githubusercontent.com/assets/13977235/21954885/3f78bd4c-da99-11e6-932d-2829be667f6c.png">
One link for a submission form.
<img width="1128" alt="screen shot 2017-01-14 at 3 34 01 pm" src="https://cloud.githubusercontent.com/assets/13977235/21954887/4106250a-da99-11e6-9baf-efbac03976d5.png">
Can open both
![screen shot 2017-01-14 at 8 38 34 pm](https://cloud.githubusercontent.com/assets/13977235/21954895/801f324a-da99-11e6-8947-784bf9baa9a8.png)

**Comment by damithc** [comment]
UI looks fine to me @xpdavid
