### ISSUE TITLE
Show loading gif picture while the profile picture is being loaded

### ISSUE THREAD

**Issue by thyageshm** [TEAMMATES/teammates#2312]
instructor.js is to be edited for both hover-triggered and click-triggered ViewPhoto events.

**Comment by Maroooon** [comment]
Hey Thyagesh ,
Can I be assigned this issue...

**Comment by damithc** [comment]
There's no need to assign. You can submit a pull request to any open issue
Shubham.

**Comment by xpdavid** [comment]
If we want to load the image asynchronously, we need to create a JavaScript Object "Image" to do this in the background (just like send a ajax request). Cannot simply change `src` to "ajax-loading.gif" and change back as this is not asynchronous. An example is [here](http://blog.teamtreehouse.com/using-jquery-asynchronously-loading-image) @wkurniawan07 @damithc Any suggestions?

**Comment by damithc** [comment]
@xpdavid 

> Cannot simply change src to "ajax-loading.gif" and change back as this is not asynchronous.

This doesn't work at all, or doesn't have a good user experience at times? Until now I thought out 'loading...' gif is working correctly (based on my usage of TEAMMATES).

**Comment by xpdavid** [comment]
@damithc It works, but it is not asynchronously. Basically, if we do this, we just tell the browser **first** load `ajax-loading.gif` **then** load `profile-image.gif`. The task is executed sequentially.

**Comment by damithc** [comment]
> It works, but it is not asynchronous. Basically, if we do this, we just tell the browser first load ajax-loading.gif then load profile-image.png. The tasks are executed sequentially.

So, not a big problem (although not ideal) in the context of 'loading...' spinner gif right? The gif is small and the user is not surprised to see it first.

**Comment by xpdavid** [comment]
That's true.
But if there network connection is not fast enough, the server is 'busy' to response, or the profile image is large, they may experience something like "loading the image progressively" (below)
![progressive](https://cloud.githubusercontent.com/assets/13977235/21952150/e12dbef2-da4f-11e6-8e47-ec99e1fe50bc.gif)
If we use asynchronous loading, we could show 'loading...' spinner gif until the actual profile image finishes downloading. :P

**Comment by damithc** [comment]
@xpdavid i see. I'm ok to make it async. @wkurniawan07 what do you think?

**Comment by xpdavid** [comment]
@damithc @wkurniawan07 I manage to do it without using a new `Image` object and still achieve that show 'loading...' spinner gif until the actual profile image finishes downloading. Is it acceptable? Should I send PR?
![demo](https://cloud.githubusercontent.com/assets/13977235/22008488/97385ea6-dcb6-11e6-88b9-2fe74e9afed2.gif)

**Comment by damithc** [comment]
> Should I send PR?

Yes please :-) Nice work @xpdavid
