### ISSUE TITLE
Add const sum and contribution question views to mashup

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/teammates#2340]
As per title

**Comment by nsaiisasidhar** [comment]
Hi, can you please let me know if you mean studentFeedbackResultsCONSTSUM.html and studentFeedbackResultsCONTRIB.html pages.

**Comment by damithc** [comment]
@nsaiisasidhar are you able to load the mashup page from your dev server?

**Comment by Yogitha6** [comment]
@damithc 
Prof,
I am able to see the mashup page on my dev server and I understand that this issue requires changes to the mashup.jsp page. Also with my research I am guessing the issue refers to adding [contribution question](https://teammatesv4.appspot.com/instructorHelp.jsp#fbContrib) to mashup.
Is this correct?
Also, I have no clue on the Const sum. Could you please give me any hints on this?

**Comment by damithc** [comment]
@Yogitha6 
This is an old issue, so check if it is already fixed fully or partially.
`Const sum` refers to 'distribute points among participants/options' type questions.
