### ISSUE TITLE
Take student to CourseJoinPage if he is already logged in clicks on an unreg student's link

### ISSUE THREAD

**Issue by thyageshm** [TEAMMATES/teammates#2342]
Currently, the student is logged out and taken to the page as an unregistered and not logged in student. But we could be more pro-active and redirect to the course join page for the student to immediately confirm.

**Comment by nsaiisasidhar** [comment]
Hi, can you please let me know if the unreg student's link is to unregister from course and the file where link is located.

**Comment by damithc** [comment]
`unreg student's link` refers to unique links emailed to students by TEAMMATES.

**Comment by nsaiisasidhar** [comment]
Thank you @damithc

**Comment by sujeet14108** [comment]
![screenshot from 2017-04-07 04-00-45](https://cloud.githubusercontent.com/assets/9781422/24778255/418addf6-1b47-11e7-8f93-7e5281d84ecf.png)

So what we want in this is after click on the link like on above image inspite of going to below image user should go to last image ?

![screenshot from 2017-04-07 04-01-23](https://cloud.githubusercontent.com/assets/9781422/24778268/4e5b38b4-1b47-11e7-9e9e-80f5bde8f40a.png)

![screenshot from 2017-04-07 04-01-31](https://cloud.githubusercontent.com/assets/9781422/24778267/4e5347e4-1b47-11e7-85fd-fb4a12a543a1.png)

**Comment by damithc** [comment]
@sujeet14108 we still have to confirm with the student that he wants to join using the currently logged in Google account. This is a very old issue; Looks like the current behavior is as desired. When I tried the scenario, I'm taken to this page, which is what we want. 

![image](https://cloud.githubusercontent.com/assets/1673303/24783619/ff962494-1b7f-11e7-99f3-09c6728603ac.png)

I'm closing the issue. Thanks for investigating it.
