### ISSUE TITLE
Student: edit profile: allow deleting profile pic 

### ISSUE THREAD

**Issue by franklingu** [TEAMMATES/teammates#2351]
as per title

**Comment by thyageshm** [comment]
![page_delete_location](https://cloud.githubusercontent.com/assets/5160137/5836430/a71dd78a-a1b0-11e4-98a6-7d00590d6e0f.jpg)

**Comment by thyageshm** [comment]
All the code at logic level and below have already been written (refer to deleteStudentProfilePicture in Logic.java). We need a StudentProfilePictureDeleteAction and appropriate UI changes to the studentProfilePage.jsp.

**Comment by thyageshm** [comment]
shall I handle this one?

**Comment by damithc** [comment]
sure

**Comment by nidhi98gupta** [comment]
@damithc Can I work on this?

**Comment by damithc** [comment]
> @damithc Can I work on this?

@nidhi98gupta  sure.
