### ISSUE TITLE
The Exception messages need to be delimited  by line breaks (<br>) and not Const.EOL

### ISSUE THREAD

**Issue by franklingu** [TEAMMATES/teammates#2352]
Invalidity Info in statuses are now delimited by Const.EOL which is not rendered on a browser resulting in a huge paragraph of text. Either we can change EOL to a <br> or change statusMessage.jsp to replace all Const.EOL to '<br>'

**Comment by thyageshm** [comment]
@JosephineKwa reminder about this issue

**Comment by wkurniawan07** [comment]
Fixes in #5085.
