### ISSUE TITLE
Give more information about sections in instructorHelp page

### ISSUE THREAD

**Issue by franklingu** [TEAMMATES/teammates#2354]

**Comment by damithc** [comment]
@ovshake This issue is not about a .java file. It's about the help page meant for instructors.

**Comment by ovshake** [comment]
@damithc oh! sorry, I didn't notice that space between 'instructorHelp' and 'Page'.

**Comment by ZhaoDingfan** [comment]
I'm trying to work on this issue but I cannot understand the meaning of ''sections'' in the help page of instructors. Could you please explain more about that to me?

**Comment by damithc** [comment]
> I'm trying to work on this issue but I cannot understand the meaning of ''sections'' in the help page of instructors. Could anyone explain more about that to me?

`Sections` here refers to sections of a course. i.e. a course can be divided into sections.

**Comment by ZhaoDingfan** [comment]
@damithc Thanks for clarifying.

**Comment by damithc** [comment]
Merging into #2335
