### ISSUE TITLE
mashup.jsp: Student Feedback Question Submit Page is broken

### ISSUE THREAD

**Issue by franklingu** [TEAMMATES/teammates#2355]
Shows only the session details. No form to submit.

**Comment by chowyb** [comment]
Seems to be fixed.

![mashup](https://cloud.githubusercontent.com/assets/7546744/15110075/6d702624-1611-11e6-9d12-40e04faf3795.png)

**Comment by damithc** [comment]
Very old issue. Probably got fixed along the way.
