### ISSUE TITLE
change instructorSampleData comment time to be different

### ISSUE THREAD

**Issue by franklingu** [TEAMMATES/teammates#2402]
right now the time for 2 studentComments is the same, which will cause sorting problem. in fact, here is another potential problem for comments sorting as it only considers creation time, which is always a problem for testing.

**Comment by visithamanujaya** [comment]
can i work on this

**Comment by Mynk96** [comment]
I couldn't find any 2 comments with same comment time in instructorSampleData.json.Is this issue already resolved?

**Comment by damithc** [comment]
@Mynk96 this is an old issue that might got fixed along the way without anybody noticing. If you can confirm the problem does not exist anymore, we can close this issue.

**Comment by Mynk96** [comment]
@damithc we can close this issue as, there are no two comments with same time

**Comment by damithc** [comment]
Thanks for the investigation @Mynk96
