### ISSUE TITLE
Comment's visibility option values should be generated with the same format

### ISSUE THREAD

**Issue by kai33** [TEAMMATES/teammates#2421]
now after edit a comment's visibility options,
its option values (generated by javascript) have no space in between.

but after refresh,
the values (generated by front-end java codes) will have spaces in between like "GIVER, STUDENTS, INSTRUCTORS".

This different behaviours will fail the test, see commit c7b7ae8

**Comment by visithamanujaya** [comment]
can i work on this

**Comment by kai33** [comment]
Hi, you'd better try those issues with label forFirstTimers first
