### ISSUE TITLE
Show shortname with the photo.

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2431]
When giving comments to students, it is useful to know the preferred name of a student.

**Comment by damithc** [comment]
@thyageshm can you try this one?

**Comment by thyageshm** [comment]
sure sir

**Comment by thyageshm** [comment]
@damithc sir just to confirm, this is only in feedbackResultsPage right?

**Comment by damithc** [comment]
Yes. In fact, the only time I need it is when I'm entering a comment.
Perhaps we can auto load the photo and short name when the instructor
starts adding a comment?

**Comment by thyageshm** [comment]
ok
