### ISSUE TITLE
feedbackQuestionContributionResultsStatsFragment.html has <%=idx%>

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/teammates#2487]
It probably should not be there. Need to check what it is used for, and fix/remove accordingly.

**Comment by wkurniawan07** [comment]
Yep, doesn't look like it's used. In fact, the whole id (not just the `<%=idx%>`) looks redundant.

**Comment by damithc** [comment]
@wkurniawan07 what happened to this one?

**Comment by wkurniawan07** [comment]
Oops forgot about this one. Anyway like I mentioned this is as easy as removing the entire `id="..."` part and fixing the test case. Any one of the current contributors is more than capable of fixing this.
