### ISSUE TITLE
Handling "Back" botton when adding a course

### ISSUE THREAD

**Issue by ihenria** [TEAMMATES/teammates#2489]
When having successfully added a course from https://teammates-xxx.appspot.com/page/instructorCoursesPage?user=xxx, clicking a botton from the table ("View", for example) followed by the "back" botton from the browser toolbar will incur the error:

A course by the same ID already exists in the system, possibly created by another user. Please choose a different course ID.

**Comment by damithc** [comment]
Old issue. closing.
