### ISSUE TITLE
Instructor: edit instructors: ensure at least one instructor is visible to students

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/teammates#2515]
This is related to #2512

**Comment by nikiforosbotis** [comment]
@LowWeiLin Can I take over that?

**Comment by LowWeiLin** [comment]
Sure =)

**Comment by nikiforosbotis** [comment]
Thank you! 
In order to better understand the issue, is this the problem we are looking to solve?
![a](https://cloud.githubusercontent.com/assets/9116253/24241064/ec68ec44-0fb3-11e7-9880-d6889487241d.png)
How can I see which instructor is visible to a student or not?

Thanks @LowWeiLin

**Comment by damithc** [comment]
@nikiforosbotis 

![image](https://cloud.githubusercontent.com/assets/1673303/24242226/1f1f4546-0ff2-11e7-9b47-2f86721d6b10.png)

We want to ensure at least one instructor in the course has this option ticked.

**Comment by mukesh14149** [comment]
I am working on this issue.

**Comment by nikiforosbotis** [comment]
@mukesh14149 I'm sorry to say that but I have already started working on this issue, as it is proved by the images I had uploaded earlier. In order to follow the "best practice" as proposed by the "Teammates" team, I would propose you to let me some time to finish this issue and if I do not manage to produce the required result you can work on that. I hope you understand my point.

**Comment by mukesh14149** [comment]
You hadn't updated on this issue since 16 days. So, I thought may be you were not working on it. I started working on it yesterday, and close to completion now. But,  if you too had completed the issue, go ahead.

**Comment by nikiforosbotis** [comment]
@mukesh14149 You're right, the thing is that I was working and I was planning to work on that issue during this week. However, in case you have completed your contribution please go ahead and submit a PR. If you have just started familiarizing yourself with the corresponding code, please give me some time and I will do it.

**Comment by amarlearning** [comment]
Working on this

**Comment by bjrodrig** [comment]
working on this

**Comment by RonakLakhotia** [comment]
Is this issue still valid?

**Comment by damithc** [comment]
> Is this issue still valid?

I believe so. You can test on your dev server to confirm the problem still exists.

**Comment by RonakLakhotia** [comment]
I would like to take up this issue.
