### ISSUE TITLE
Revise content of the instructor help page

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2532]
Daryl has come up with some revisions to the instructor Help page. Someone needs to transfer those changes to the actual html page.

**Comment by github-tn** [comment]
Can I take this? Where is the revised content?

**Comment by damithc** [comment]
Take a different one :-) The revised content may be outdated and might
require further revision.

**Comment by yasirunilan** [comment]
Is this open yet? Is the revised content ready to be added?

**Comment by damithc** [comment]
Stale issue. closing.
