### ISSUE TITLE
Student: submit responses: implement back-end integrity check for responses

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#2542]
User can edit the DOM to set the recipient to be the same recipient as a previous response in the same question. This problem is detected when updating responses, but is not checked when the response is new. Related to #2350. 

This is in particular a problem with the distribute points question (ConstantSumQuestion), since the user can assign 2 set of points to the same person, which causes the total sum of points assigned to be wrong, as only one set of points is saved into the database.

**Comment by damithc** [comment]
Might have to do as multiple PRs, one PR per question type

**Comment by arjunsuri** [comment]
I want to take this issue...Could you please tell what exactly I have to do in this issue...as I am not able to figure out from the explanation?

**Comment by vandy56** [comment]
@damithc @kanghj I'll take a stab at this one.

**Comment by vandy56** [comment]
Hey @damithc and @kanghj would I be correct to start at FeedbackResponsesLogic.java in teammates.logic.core and fixing the addNewResponses method to check for an existing response?

If I'm reading this right (and I'm still pretty new so not sure I am), the existing checks in the method check to be sure the response is not the same ID as a previous response, but does not check individual items.

Thanks for your help.

**Comment by damithc** [comment]
@chowyb can help with @vandy56's query?

**Comment by vandy56** [comment]
@chowyb update: I have discovered the ConstantSumQuestion and response files mentioned in the initial issue. Now I'm looking for the test implemented on the updating of responses (as I feel it might give me a clue into this problem.

Will update when I find more. Please advise as you see fit.

**Comment by vandy56** [comment]
Coming back to this one @chowyb and @damithc. I can't actually replicate the issue. Can you please advise on how to do so? 

I couldn't figure out how to edit the recipient to be the same as a previous response when logged in as a student.

**Comment by sukanta-27** [comment]
Checked. The issue is still relevent. Changing the email address in the `select` options for the a particular recipient in the DOM will result this. 

Will like to work on this issue.
