### ISSUE TITLE
custom instructor cannot view responses for which receiverSection is None

### ISSUE THREAD

**Issue by franklingu** [TEAMMATES/teammates#2562]

**Comment by franklingu** [comment]
@damithc , being able to see all was happening at this time? I remember that things were okay at that time.

**Comment by damithc** [comment]
I didn't check at that time. 

When submitting: 
if tutor permission was set only once: can submit for all students 
if tutor permission was updated later: can submit only for his sections 

When viewing results:
tutor can see results of the whole course although has permission for some sections only.
