### ISSUE TITLE
Prevent status message contamination between concurrent requests from the same user

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2620]
It seems if two tabs loaded two different pages at the same time, the status message from one page can appear in the other.

**Comment by thyageshm** [comment]
Sir I am having trouble reproducing this bug. Could you please give a little more details on how to reproduce this bug?

**Comment by damithc** [comment]
I don't remember how I produced this exactly. If you have multiple tabs submitting things in parallel, there is chance that the status message meant for one page being stolen by another page. I suspect it is because we use the session object to store the status message but the session object is shared by all TEAMMATES pages in the the browser (is that the case?)

**Comment by damithc** [comment]
Another case of this, noticed in a screenshot sent by a student (for an unrelated issue):
![image](https://user-images.githubusercontent.com/1673303/33463201-08d42648-d677-11e7-96e0-fef1945149d0.png)

**Comment by LiHaoTan** [comment]
A similar bug can be produced with the edge case:
![image](https://user-images.githubusercontent.com/13617389/37241361-c442f832-2492-11e8-98e0-d0427b713e15.png)

**Comment by LiHaoTan** [comment]
Here's a demo of how to replicate a case commonly happening in Appveyor (albeit rudimentary).

[![FeedbackNumScaleQuestionUiTest](https://img.youtube.com/vi/1plMdEaDvN4/0.jpg)](https://www.youtube.com/watch?v=1plMdEaDvN4)

**Comment by wkurniawan07** [comment]
Resolved in V7 (session is no longer used to contain any data).
