### ISSUE TITLE
Instructor enroll students: delete responses of 'constant sum' type questions of affected teams

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2669]
When a student is deleted/added to a team after others have submitted responses to a 'constant sum' type question (i.e. divide points among team members), the existing values are no longer correct. 
We can delete the responses automatically but should warn the instructor first.

**Comment by damithc** [comment]
I believe in some cases the values can be adjusted automatically (i.e. prorated).

**Comment by wkurniawan07** [comment]
Superseded by #7249
