### ISSUE TITLE
Student: view results: do not show anonymous results if there is only response per team

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2719]
If only one student submitted responses and there are anonymous and non-anonymous questions, the recipient can guess the sole responder via the non-anonymous questions.

Suggested: If a session has both anonymous and non-anonymous questions, hide responses to an anonymous question if there is only one response for that question.

**Comment by hppranaav** [comment]
Hi @madanalogy, I would like to take a crack at this issue if its ok?

**Comment by lyeyixian** [comment]
Hi, I would like to work on this. Is this still relevant?

**Comment by wkurniawan07** [comment]
@damithc after further examination, I'm not sure if this is worth doing. This feature (if it can even be called that) is far too situational to be useful.
- This necessitates all responses for a student to need to be fetched in one go. While we haven't hit a scale where that can hit performance issues, it is not to say that it would happen, and addition of this feature will make any kind of fetching-by-batch difficult if not impossible.
- The situations whereby this can happen in real life are easily solvable through other means:
  - Before deadline: if the instructor really requires partial responses to be hidden from students, an option to specify when results will be visible is always there
  - After deadline: if a team (of > 2 people) has that kind of low response rate, that is a tell-tale sign of another problem, and not one that is our job to solve
- And what if a team has only 2 people, in a course that can have teams of e.g. 2, 3, 4 people? This feature will needlessly hide the responses of the other team member.

**Comment by damithc** [comment]
Thanks for looking into this @wkurniawan07 
Let's drop this one then.
