### ISSUE TITLE
Instructor: add comments on responses: do not allow comments on responses of Contribution questions

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#2732]
~~When #2717 is done, students will be unable to see the raw values of responses and any instructor comments on studentFeedbackResults. However, they can still see both the comments and the raw value of the response on studentCommentsPage. This will be inconsistent and confusing for the student. 
Preventing instructors from commenting on responses in contribution questions can be done on the UI side.~~ 

Updated description (by @damithc):

Students don't get to see individual values they receive for contribution questions. So, there is no way for us to show the student comments instructors add to individual responses. Preventing instructors from commenting on responses in contribution questions is a quick fix, which can be done on the UI side.

**Comment by arvind-kalyan** [comment]
Hi, shall I start this?

**Comment by arvind-kalyan** [comment]
Thanks @LowWeiLin !

**Comment by arvind-kalyan** [comment]
Hi, 
Here, we have to disable the option for instructor to comment for contribution question, correct? This applies only for the question where we have to rate the team members' contribution (where Equal Share, +5% etc. are involved), right?

**Comment by LowWeiLin** [comment]
Yes

**Comment by arvind-kalyan** [comment]
Here, we could either 'disable' the comment button, or remove the button as such right? Am I missing something?

**Comment by damithc** [comment]
Because that button is not to be enabled at any time, might as well remove
it.

**Comment by arvind-kalyan** [comment]
Sir, I have disabled the button when the question is a contribution question. The button is there, but won't be clickable. This same comment button will be clickable in other question types.

**Comment by damithc** [comment]
Can you add a tool tip "Commenting is not available for Contribution
Questions" to the disabled icon?

**Comment by arvind-kalyan** [comment]
Sure. Will do.

**Comment by arvind-kalyan** [comment]
It seems that adding a tooltip to a disabled button is a bit tricky. We have to use another outer element, live <div> or <span> and put the tool-tip on that. Also, with this, it doesn't work if the display style of that outer element is not "inline-block" (which makes the comment button go far to the left from it's original position) So much complications. I've done something simpler. :) I added style="display:none", so that button is not visible for contribution questions.

**Comment by wkurniawan07** [comment]
> However, they can still see both the comments and the raw value of the response on studentCommentsPage. This will be inconsistent and confusing for the student.

@damithc student comments page no longer exists. Does this mean the issue is no longer relevant now?

**Comment by damithc** [comment]
> student comments page no longer exists. Does this mean the issue is no longer relevant now?

Looks like it's still relevant. The problem is students don't get to see individual values they receive for contribution questions. So, there is no way for us to show the student comments instructors add to individual responses.

**Comment by wkurniawan07** [comment]
Checked and confirmed that it is the case, although instead of the comments being "inconsistent and confusing for the student", they will just be simply not shown to them.

**Comment by damithc** [comment]
> Checked and confirmed that it is the case, although instead of the comments being "inconsistent and confusing for the student", they will just be simply not shown to them.

yup. Description updated.
