### ISSUE TITLE
instructorViewStudentRecord: format 'no comments' differently

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2772]
Currently, the 'You don't have any comments on this student.' phrase is formatted in the same way we show comments. That could be confusing. Let's format it differently.

**Comment by ARSPRodrigo** [comment]
@damithc 
Hi sir,

Can you assign me this issue. Because I'm interested in UI part.

**Comment by ARSPRodrigo** [comment]
@LowWeiLin <https://github.com/LowWeiLin> I Sent the pull request #3099
