### ISSUE TITLE
Instructor: view session results: give a 'remind' button in the 'did not submit' panel

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2775]
When the instructor is viewing the list of students who did not submit yet, he/she may want to send them a reminder. We can also have a link in each row, to send individual reminders.

![image](https://cloud.githubusercontent.com/assets/1673303/25771236/723d1740-327e-11e7-80c4-dc111279c49a.png)

**Comment by damithc** [comment]
For this feature, we should consider reusing the same modal window used in the 'remind' button on the instructor home page.

**Comment by shubham49** [comment]
Do we have to add 'remind' group button or just remind button that opens a pop up and sends email on 'OK'.

**Comment by damithc** [comment]
> Do we have to add 'remind' group button or just remind button that opens a pop up and sends email on 'OK'.

It's better to have a confirmation dialog.

**Comment by HirdayGupta** [comment]
Working on this. Trying to link this button with the same action as the Remind button on the instructor home page. However, when I copy the `href` parameter from the home page's remind button link to this new one, I get an `Invalid Origin Error`. I'm assuming this has something to do with the `token` URL paramater that gets passed in the URL. Any ideas on how I can avoid the `Invalid Origin Error`?

**Comment by shubham49** [comment]
@HirdayGupta actually i had started working on this. I have just completed it. If you are in mid way then you can help me by reviewing my PR. If you have completed it go ahead.

**Comment by HirdayGupta** [comment]
@shubham49 I see. In that case go ahead as I was only just beginning. Have given it significant thought though, so would be happy to assist the Devs in reviewing your PR.

**Comment by shubham49** [comment]
Thanks @HirdayGupta
