### ISSUE TITLE
Instructor: moderate feedback: give message "Some questions may be hidden..." as a status message 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2818]

**Comment by PSNAppz** [comment]
@damithc I would like to work on this issue.But where exactly should I add the message?There is already a message showing in this page.
![typo](https://cloud.githubusercontent.com/assets/4481429/15627309/96e171b6-24fd-11e6-95c7-ed50e1cd4385.png)

**Comment by kanghj** [comment]
@PSNAppz, If I'm not wrong, this issue is about displaying that message as a status message instead, to be consistent with the usual status messages a user sees when he/she reaches the submission page.

**Comment by xpdavid** [comment]
@damithc 
I manage to do this, but there is one question.

![screen shot 2017-01-13 at 11 32 33 am](https://cloud.githubusercontent.com/assets/13977235/21917609/02e390e8-d984-11e6-9a08-e7b03345bb53.png)

I think we should show the message as `warning` message. But the `/js/feedbackSubmissionsEdit.js` included in the page would detect if there are warning message box (typically `.alert-warning.statusMessage`), then we use bootstrap modal to pop it. Therefore, this will result in

![screen shot 2017-01-13 at 11 29 07 am](https://cloud.githubusercontent.com/assets/13977235/21917601/ecdd1b66-d983-11e6-9efb-d36f88ef8a4e.png)

**My suggested solution** is to use JS to detected whether we have "Moderating Responses" box on the top of the page and decide whether to pop it as modal or not.
![75a448a0-1830-467a-9058-c789d3bc377a](https://cloud.githubusercontent.com/assets/13977235/21917641/46d5c14a-d984-11e6-9575-00067d354d94.png)

**Comment by damithc** [comment]
> I manage to do this, but there is one question.

Sorry @xpdavid I missed your question earlier. 

I've forgotten details about this issue (my bad, I should have specified them in the issue).

1. Is the message shown (a) every time an instructor is moderating, or (b) only if some questions are actually hidden?  

2. Is the message also shown to students when they submit responses, or just for the moderator?

**Comment by xpdavid** [comment]
@damithc 
1. Currently the message shown every time an instructor is moderating, but can make it shown when there are actually hidden questions.
2. Student won't see the status message when they submit feedback. The message is only for moderator.

**Comment by damithc** [comment]
OK, now I remember what the issue was about: change formatting of the message that already exists.

@xpdavid what's the possibility of showing the message in the top bar, just below the line `Moderating ...` so that the rest of the page remains as close to the student submission page as possible? e.g. 

---

**You are moderating responses for (or submitting on behalf of) `abc@mail.com`**

* The page below resembles the submission page as seen by the respondent `abc@mail.com`. You can use it to moderate responses submitted by the respondent or submit responses on behalf of the respondent.
* Note that questions not visible to the respondent (based on visibility settings of the question) are not shown in the page below.

---

**Comment by xpdavid** [comment]
@damithc I agree. Sounds better if we do that.
![screen shot 2017-01-15 at 1 43 51 pm](https://cloud.githubusercontent.com/assets/13977235/21960485/adbb5d84-db28-11e6-81b0-eb6f5935f1ce.png)
Of course questions are not visible to student will not be shown. But moreover, questions that are not supposed to show responses, giver's name, recipient's name **to instructor** will also not be shown. So I rephrase the second sentence. Not sure whether it is appropriate.

**Comment by damithc** [comment]
@xpdavid looks good. Go ahead.
`to instructors (i.e. you)` --> `to you` ?

**Comment by damithc** [comment]
Another thing: may we should use `respondent` instead of `student`? I don't remember if we support moderating responses of instructors, and even if don't, in future we might.
Even better if we can choose Student/Instructor based on the actual type of respondent, but that can be a separate PR.

**Comment by xpdavid** [comment]
@damithc 
> Another thing: may we should use respondent instead of student? I don't remember if we support moderating responses of instructors, and even if don't, in future we might.
Even better if we can choose Student/Instructor based on the actual type of respondent, but that can be a separate PR.

The detection is already implemented in the `.tag`
```
${isInstructor ? "Instructor" : "Student"}
```
But the actual logic is not there. I think this is for future implementation of moderating responses of instructors.

> to instructors (i.e. you) --> to you ?

I am not sure whether the users are aware of their roles as instructors. I am writing "instructor" explicitly here to remind users that there are options related visibility to instructors in question visibility setting.

**Comment by damithc** [comment]
> I am not sure whether the users are aware of their roles as instructors. I am writing "instructor" explicitly here to remind users that there are options related visibility to instructors in question visibility setting.

I was trying to avoid two consecutive brackets.  Go ahead with a current version. We can get someone else's input during review stage.
