### ISSUE TITLE
Email reminders: Include recipient list in the copy of email sent to instructor

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2820]
The copy of reminder sent to instructors says 'students'. It sounds like the reminder was sent to the whole course even when it was sent to one student.

**Comment by damithc** [comment]
@ackoroa any thoughts?

**Comment by ackoroa** [comment]
For this I reused the function that generates the normal reminder so it'll be true if in the whole course there's only one student who hasn't responded and the instructor clicked "remind all" also. 

Maybe we can put that part as a variable in the template and change it depending on which method (remind particular or remind all) calls it?

**Comment by damithc** [comment]
Yes let's do that.
