### ISSUE TITLE
instructors: can use a student ID field to identify students uniquely

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2855]
Some instructors would like to have an ID column where student name/emails appear in tables (e.g. in the csv file). These are the folks who use an ID such as matric number to uniquely identify students, instead of emails/names.

**Comment by thyageshm** [comment]
Just bouncing some thoughts here. Should we edit the Student Entity to have a String attribute to provide this feature? By default it will be null and if it is not null we can use the unique ID given by instructor in all our displays (as necessary)

**Comment by damithc** [comment]
Yes, that is a reasonable approach. Note that we have to ensure that the ID
is not null for *all* students in the course :-p
