### ISSUE TITLE
Instructor: view results: show correct heading when user is both a student and instructor

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#2857]
When a user is both an instructor and student, and when the question is about instructors, the incorrect heading is shown. The user will be grouped under his team as a student, although it should show "Instructor".

**Comment by yj-soh** [comment]
Is this bug still present?
I've set up a session with questions about instructors, but instructorFeedbackResultsPage appears the same regardless of whether as a user that is both a student and instructor (in that session) or as a user that is only an instructor.

**Comment by kanghj** [comment]
Yes, it is still present. You need to have questions about students too. 

In Recipient > Question > Giver, the heading for the instructor's team as a student appears twice.
![appearstwice](https://cloud.githubusercontent.com/assets/2216119/6886368/f0e7bae2-d66d-11e4-8b27-207792919001.PNG)

I've also just noticed that this has an additional effect where the response for the question about instructors cannot be seen in that view, which is more important than the incorrect heading name, although it can be seen in the Giver >* >* view.

**Comment by yj-soh** [comment]
Right, I've traced down the source of the bug.

A list of responses for that session are sorted and parsed into a mapping of `recipient - responsesForRecipient` in `getResponsesSortedByRecipientQuestionGiver`.
The sorting separates the responses for a user if the user is both an instructor and student, making something like the following list possible:

1. Instructor
0. InstructorStudent (as an instructor)
0. Student
0. InstructorStudent (as a student)

The parsing creates a new list of responses for the recipient on the current iteration at each change of recipient, so the above list will create 4 lists and the 4th will end up overwriting the 2nd (as there is no checking if the recipient already exists in the map). This causes the "cannot be seen in that view" problem.

Next, the list is parsed (stably) into a mapping like so:

1. Instructor - Response 1
0. InstructorStudent - Response 4, Response 2 (R2 only if the problem above remains.)
0. Student - Response 3

The heading of each team is created based on the recipient team in the first response (of that user) it sees, so the above mapping will create a heading of InstructorStudent's team as a student if R4 is read first or remains in the instructor team if R2 is read first (then creates InstructorStudent's team as a student right after). This causes the duplication in headings assuming InstructorStudent's team is not the same as the next student's.

Solving the hidden response to instructor is easy enough by adding a check before putting into the map. The double heading, on the other hand, will need quite a bit of changing as the current code appears to assume a user will not exist in two teams at a time.

**Comment by kanghj** [comment]
I think that ideally, InstructorStudent's responses as an instructor and student should not be displayed together. Responses to *InstructorStudent as an instructor* should appear under InstructorStudent in the team "Instructors", and responses to *InstructorStudent as a student* should appear under InstructorStudent in the student's team. Just appending the 4th list to the 2nd list may not be a good solution. 

The assumption that a user will not exist in two teams is a correct one, "Instructors" is not really a team and can be dealt with separately. 

If you want to submit an adhoc fix, maybe make a new issue since the "cannot be seen in that view" problem is a little different from this original issue?

**Comment by wkurniawan07** [comment]
Fixed in V7.
