### ISSUE TITLE
Instructor: question edit: Use different color for inner panel titles

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2868]
Using a different color set them apart from other bold text in the panel. Use the darker tone of the panel background color?

![image](https://cloud.githubusercontent.com/assets/1673303/5698545/f4bcc950-9a4a-11e4-9e48-2b5ed32dfca6.png)

**Comment by NisalaNiroshana** [comment]
Hi,
I am willing to work with this issue.
Thanks
