### ISSUE TITLE
Instructor help page: mention the 'moderation' feature

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2874]
also mention sending reminders individually

**Comment by vamshi-s** [comment]
@damithc  you meant to add the explanation about individually  sending invites to students to join course functionality usage in instructorHelp.html page 
![sendinvite](https://cloud.githubusercontent.com/assets/11355301/6600291/c95bad2c-c834-11e4-9863-928b7439bc0d.png)
?

**Comment by vamshi-s** [comment]
@damithc  You meant Adding few questions & Adding Explanation about how to use this feature in instructorHelp.html page. ?
![mode](https://cloud.githubusercontent.com/assets/11355301/6600588/85ba3834-c836-11e4-933f-1a706d0c6198.png)

**Comment by nodermatt** [comment]
Is this still relevant? I would be willing to take the time to extend the instructor help page to display the moderate and remind feature.

I was thinking of adding a screenshot for both features as they include multiple steps that would be cumbersome to mock compared to the question examples.

**Comment by damithc** [comment]
>Is this still relevant? I would be willing to take the time to extend the instructor help page to display the moderate and remind feature.

Need to check the current state of the help page to see if these two things are mentioned there.

> I was thinking of adding a screenshot for both features as they include multiple steps that would be cumbersome to mock compared to the question examples.

We try to avoid screenshots as they get outdated quickly. In lieu of a screenshot, perhaps we can just mock the relevant button so that it is easy for the reader to locate the said button by eyeballing the page? e.g.,

> You can click on the `[moderate]` button in each row ...

**Comment by nodermatt** [comment]
@damithc Thanks for the quick response! As far as I can tell (on the master branch), there is no mentioning of the said features on the instructor help page. If it is still intended to add mentioning of the features there I will work on it.

Good point, screenshots do out-date and cause confusion instead of help. I will draft somethings based on your suggestion.

**Comment by damithc** [comment]
> @damithc Thanks for the quick response! As far as I can tell (on the master branch), there is no mentioning of the said features on the instructor help page. If it is still intended to add mentioning of the features there I will work on it.

@nodermatt If it is not mentioned in the help pages (check thoroughly), you can go ahead with adding it.

**Comment by wkurniawan07** [comment]
Issue has been resolved.
