### ISSUE TITLE
Instructor: can add multiple instructors on a course in one step

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2890]
Requested by a user. Adding one at a time is troublesome.
Perhaps allow copying multiple instructors from existing courses?

**Comment by thyageshm** [comment]
something like these?
![page_with_button](https://cloud.githubusercontent.com/assets/5160137/5836315/f0eda130-a1ae-11e4-9372-d0138058b5fe.jpg)
![page_with_modal](https://cloud.githubusercontent.com/assets/5160137/5836316/f20147d4-a1ae-11e4-97ae-ccf078f7f8dd.jpg)

**Comment by damithc** [comment]
Yes, something like that. :-)

**Comment by Siddhant085** [comment]
Can I be assigned this issue?
