### ISSUE TITLE
Refactor *SearchResultBundle to always filter out CourseId etc (except for admin)

### ISSUE THREAD

**Issue by kai33** [TEAMMATES/teammates#2917]
In the old design, *SearchDocuments are filtered/searched by specifying CourseId in the *SearchQuery. But it turns out that it's not completely filtered and not safe for some time, as GAE's full-text search engine splits the CourseId by some characters, which then results in wrong cases. E.g. search for 'CourseId', but returns results for 'CourseId' and 'CourseId.Wrong' (it's splitted into 'CourseId' and 'Wrong', that's why it can be searched).

To prevent this, so when we get the search result, we need to manually filter out the CourseId by current user's CourseIds. So that in some special cases, other courses' data cannot be seen by current user (or sometimes it will cause null ptr exception).

But if in the future we're to implement the new searchable documents, and forgot to filter out CourseId (and maybe email) manually, this issue will happen again issue #2913. So what to do for this issue is, maybe using proxy patten to wrap the APIs, to ensure that filter for the CourseId (or email maybe) is a must-have for the corresponding *SearchResultBundle.

**Comment by damithc** [comment]
Any way to prevent Google from splitting those keywords?

**Comment by kai33** [comment]
no api provided for that

**Comment by damithc** [comment]
What if we add double quotes around the search string (like in normal
Google search)? Does that help?

**Comment by kai33** [comment]
no, not working. still match

**Comment by xpdavid** [comment]
Filtering `courseId` in memory with all the search result is not ideal and not scalable. I think one need to take a look at the search API documentation to find way to filter out them by using query while getting rid of the above problem. We then end up with #4345 though.
