### ISSUE TITLE
student: can add a comment to an answer

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2933]
e.g. to explain why a certain option in the MCQ question was chosen

**Comment by arvind-kalyan** [comment]
Sir, Can I try this?

**Comment by damithc** [comment]
This is too big to do in the middle of the semester. May be during the summer? :-)

**Comment by damithc** [comment]
@LowWeiLin anything we can give to @arvind-kalyan ?

**Comment by LowWeiLin** [comment]
@arvind-kalyan you can try #2894, or if you want something even more challenging, #2732.

**Comment by arvind-kalyan** [comment]
@damithc sir, Yes, Absolutely. :-)

**Comment by damithc** [comment]
This probably needs to be done one question type at a time.
