### ISSUE TITLE
Error while adjusting feedback session responses

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2943]
I added some details to students of the course. Mostly, moving to teams and sections. After that, I got 19 of these errors. Note that existing submissions don't have anything to do with teams. They are all 'no specific recipient' type submissions. Some of these caused the server to crash.

Error Message: teammates.logic.automated.FeedbackSubmissionAdjustmentAction execute: Error encountered while adjusting feedback session responses of L1 wrap up in course : CS2103-Jan2015 : API call has not completed yet.

**Comment by LowWeiLin** [comment]
Are there any stack traces for this?

**Comment by damithc** [comment]
Here's the full trace. It's not very detailed because this type of errors are internal. This could be an out of memory error, or iterating through a result set that is too big.

500 599548ms 0kb AppEngine-Google; (+http://code.google.com/appengine) module=default version=5-34
0.1.0.2 - - [28/Jan/2015:10:33:18 -0800] "POST /feedbackSubmissionAdjustmentWorker HTTP/1.1" 500 0 "https://teammatesv4.appspot.com/page/instructorCourseEnrollSave?courseid=CS2103-Jan2015&user=damith" "AppEngine-Google; (+http://code.google.com/appengine)" "teammatesv4.appspot.com" ms=599548 cpu_ms=345005 queue_name=feedback-submission-adjust-queue task_name=11154708043812789441 exit_code=202 app_engine_release=1.9.17 instance=00c61b117c1183bdb74cc462e07c19ef1531d520
I 2015-01-29 02:23:19.169
teammates.logic.automated.FeedbackSubmissionAdjustmentAction execute: Adjusting submissions for feedback session :Welcome surveyin course : CS2103-Jan2015
W 2015-01-29 02:23:20.957
com.google.appengine.api.datastore.BaseQueryResultsSource logChunkSizeWarning: This query does not have a chunk size set in FetchOptions and has returned over 1000 results.  If result sets of this size are common for this query, consider setting a chunk size to improve performance.
  To disable this warning set the following system property in appengine-web.xml (the value of the property doesn't matter): 'appengine.datastore.disableChunkSizeWarning'
E 2015-01-29 02:33:18.559
teammates.logic.automated.FeedbackSubmissionAdjustmentAction execute: Error encountered while adjusting feedback session responses of Welcome survey in course : CS2103-Jan2015 : API call has not completed yet.
E 2015-01-29 02:33:18.626
A problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. (Error code 202)

**Comment by LowWeiLin** [comment]
I can't reproduce the exception, but the error is caught at FeedbackSubmissionAdjustmentAction line 84.
The exception is caught and a severe log is made, but the stack trace is not logged. Should I modify it to log the stack trace as well, so that its easier to identify the problem?

**Comment by damithc** [comment]
Yes, let's do that.

**Comment by damithc** [comment]
Actually, I don't think it's going to help much. The stack trace I gave you
is from the app engine log. App engine logs stack trace automatically.  So
we are unlikely to get more details than that.

**Comment by LowWeiLin** [comment]
Will there be a stack trace logged even if we explicitly catch the exception?

try {
    stLogic.adjustFeedbackResponseForEnrollments(enrollmentList, response);
} catch (Exception e) {
    log.severe(String.format(errorString, sessionName, courseId, e.getMessage()));
    return false;
}

**Comment by damithc** [comment]
You are right; this code may be swallowing the stack trace. Let's log the
stack trace and see if it gives us more details.

**Comment by damithc** [comment]
Old issue. closing.
