### ISSUE TITLE
Rapid 'response save' requests from a single student

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2946]
Any idea what's causing this behavior pattern? It's the same student. I've seen this pattern a few times before.
![image](https://cloud.githubusercontent.com/assets/1673303/5956840/0df4c5f8-a7ed-11e4-9034-755de85cd593.png)

**Comment by damithc** [comment]
I have another case of this. Almost like a DoS attack :-p

**Comment by damithc** [comment]
Apparently, this could happen for the submission edit page if the URL is incomplete. e.g. copy pasted only part of the link sent it email. May be the browser tries to load the page repeatedly? @thyageshm is there anything we can do to prevent it?
![image](https://cloud.githubusercontent.com/assets/1673303/6101737/2e0dfb78-b064-11e4-9580-ea85f72ea8b2.png)

**Comment by thyageshm** [comment]
looking into it now sir

**Comment by thyageshm** [comment]
Sir I found the bug in the edit page that causes multiple requests being sent in succession. I will send in a fix by tomorrow. As for the EditSave, I am yet to find the cause and believe will find it soon

**Comment by thyageshm** [comment]
@damithc sir, the issue is with the fact that for registered students, if the feedback session name is invalid, we redirect them to the home page with the error message that the feedback session they are looking for is not there. But in the case of an unregistered student, we cannot redirect her to the home page as it requires them to be logged-in to access the student home page. how shall I proceed? 

My suggestions: would be either to just give them a Unauthorised Access Page (not recommended but easy to implement) or update the code in the student Submit Page to handle this situation with an appropriate error message instead of redirecting students.

**Comment by thyageshm** [comment]
Another way is to add a new "error page" which asks the user "Feedback Session that you are looking for either does not exist or has been removed by your instructor. If you came to this page by copying the link from your email, please check that you have copied the entire url properly."

**Comment by damithc** [comment]
I like the idea of a separate error page.

**Comment by thyageshm** [comment]
ok sir, will work on that. Moving forward, that page can be used in situations where a courseId, feedbackSessionName or any other parameter is not valid

**Comment by damithc** [comment]
How's this coming along? Another student reported a case like this. BTW, how do students end up clicking on an 'incorrect' link? Presumably, they are clicking on the link sent by TEAMMATES.

**Comment by thyageshm** [comment]
Hi sir, I am still working on this one. will be creating a new error page as requested. This issue happens whenever we cannot find the specified feedback session in the given course. Eg: when the session is deleted, name not found (when link is not copied properly)

**Comment by damithc** [comment]
In the most recent case, the link in the email is indeed pointing to the
wrong session. Either the session was deleted or we have a bug that causes
wrong link to be included in the email occasionally.

**Comment by thyageshm** [comment]
Sir do we have a log to cross check whether it was the former or the later? I have come to notice that we have a "entityNotFound.jsp" error page. Shall I reuse it in this case? This is what is shown in that page:

 We could not locate what you were trying to access.<br><br>
Make sure that the URL is correct, and you are a registered user of TEAMMATES. [Logout]

**Comment by damithc** [comment]
1. The logs are buried too deep in the logs now. Irrespective of how the
wrong link got to the student, clicking a wrong link should be handled the
same way right?
2. Yes, reusing that seems appropriate.

**Comment by thyageshm** [comment]
Ok! will send in a fix for EditPage soon. As for EditSave, has there been another case, as I have not been able to isolate why that would happen..

**Comment by thyageshm** [comment]
shall I open a separate one for editpage and send in the bug fix?

**Comment by damithc** [comment]
Yes, let's fix the edit as a separate issue. That's the more frequent one
for now.

**Comment by damithc** [comment]
I think the error message in the 'entity not found' is not entirely
appropriate. Students need not be registered. Change as follows?

TEAMMATES could not locate what you were trying to access. Possible reasons:
* You clicked on a link received in email, but the link was mangled by the
email software. Try copy-pasting the entire link into the Browser address
bar.
* The entity (e.g. course, session) you were trying to access was deleted
by an instructor after the link was sent to you by TEAMMATES.

If the problem persists, contact TEAMMATES support at
teammates@comp.nus.edu.sg (if the problematic link was received via email,
remember to copy-paste that email content when contacting TEAMMATES
support).

**Comment by thyageshm** [comment]
Ok! I have just added this bit:

If you are a registered user you can go back to the <a> home page</a>

**Comment by damithc** [comment]
Good.

**Comment by damithc** [comment]
Is this fixed? I'm still getting a similar behavior.
![image](https://cloud.githubusercontent.com/assets/1673303/6520408/405df1de-c400-11e4-91a3-9878216c091d.png)

**Comment by thyageshm** [comment]
The repeated calls to EditPage has been fixed, I will look harder to figure out what is going wrong with the EditSave page

**Comment by thyageshm** [comment]
I am still not able to figure out why the save page would have such a behaviour. Are there any more information regarding these instances?

**Comment by damithc** [comment]
I'll collect more info next time I catch it happening.

>
>

**Comment by thyageshm** [comment]
@damithc sir, is this one still happening?

**Comment by damithc** [comment]
I wasn't looking out for it in the recent times. But we did notice some users sending multiples of requests rapidly (when we were investigating another issue). I'll report if I encounter this again. Meantime, we'll keep it open.

**Comment by damithc** [comment]
Old issue. closing.
