### ISSUE TITLE
instructor: can create a profile page 

### ISSUE THREAD

**Issue by JosephineKwa** [TEAMMATES/teammates#2965]
Currently only students have profile pages. I feel it would be helpful if instructors had profile pages that students could view through the links in studentCourseDetailsPage. With the photos in the instructors' profile page, students would be able to recognize their instructors more easily and perhaps get to know their instructors a little better too.

**Comment by thyageshm** [comment]
This one might require porting of legacy data if we decide to add another field in the account object.
