### ISSUE TITLE
Include session instructions in the email alerts

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2977]
It could be useful to include session instructions in the email alerts

**Comment by halfdreamer** [comment]
can i work on this ?

**Comment by kanghj** [comment]
@halfdreamer, by this point, you are at task 6 of the [Instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true). You can still work on this issue and when you are done, make a pull request, but we don't promise to review your pull requests during the application period.

**Comment by halfdreamer** [comment]
@kanghj no problem...

**Comment by damithc** [comment]
Done in a different issue.
