### ISSUE TITLE
instructor: can send an invite to other instructors

### ISSUE THREAD

**Issue by dg711** [TEAMMATES/teammates#2978]
We can add an "Invite" button for the user Instructors to enable them to invite their colleagues and fellow faculties through the mail directly from the homepage . We can add template messages to enhance accessibilities . It would be a fairly good enhancement.

**Comment by damithc** [comment]
Currently, adding an instructor to a course will generate an invite. But there is no way for instructors to invite other instructors without adding them to a course first.
