### ISSUE TITLE
FeedbackQuestionsLogic: Optimize getRecipientsForQuestion

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/teammates#2994]
This function is usually called for all questions in a feedback session, and the recipients for these questions could be the same. DB calls can be saved by caching the recipients.

**Comment by kai33** [comment]
Then it would be better to have a thread-safe CacheUtil (based on memcache or ehcache). Other parts may also need it

**Comment by damithc** [comment]
Will be considered in future backend optimizations.
