### ISSUE TITLE
admin search: Some instructors don't show up in the search

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#3001]
For example, I have an instructor named Sellou who shows up as a student but not as an instructor

**Comment by arvind-kalyan** [comment]
Sir, Can I try this?

**Comment by damithc** [comment]
@arvind-kalyan This one may be related to a data migration we did sometime back. It's best handled by someone who was involved in that data migration.

**Comment by damithc** [comment]
Old issue. closing.
