### ISSUE TITLE
Remove Unused branch in Action.java

### ISSUE THREAD

**Issue by thyageshm** [TEAMMATES/teammates#3011]
In Action.java, under the method getRegkeyFromRequest(), we have a branch that checks for the legacy regkey parameter name in the url. since we no longer support it, we can remove that check.

**Comment by vamshi-s** [comment]
protected String getRegkeyFromRequest() {
        String regkey = getRequestParamValue(Const.ParamsNames.REGKEY);
        if (regkey == null) {
            //TODO: remove this branch on October 15th 2014.
            return getRequestParamValue(Const.ParamsNames.REGKEY_LEGACY);
        } else {
            return regkey;
        }
    }

I Think it has been handled, Please let me know , If not.

**Comment by thyageshm** [comment]
What do you mean? I still see the check being done in that code...

**Comment by vamshi-s** [comment]
@thyageshm  Iam sorry, i got it wrong. This needs to be removed.
f (regkey == null) {
//TODO: remove this branch on October 15th 2014.
return getRequestParamValue(Const.ParamsNames.REGKEY_LEGACY);
} else {

**Comment by thyageshm** [comment]
yup. do you want to try out this issue?

**Comment by karan173** [comment]
@thyageshm Can I be assigned this issue?

**Comment by vamshi-s** [comment]
@thyageshm  yes.Please do..Thank you :)

**Comment by vamshi-s** [comment]
@thyageshm  yes.Please do..Thank you :)

**Comment by vamshi-s** [comment]
starting issue.

**Comment by thyageshm** [comment]
Thanks @weilin

**Comment by thyageshm** [comment]
@damithc sir, has there been any severe log? or to be safe should we just leave the check there for a while longer?

**Comment by damithc** [comment]
None yet. Let's wait till the semester is over.

**Comment by thyageshm** [comment]
ok

**Comment by sujeet14108** [comment]
Can i solve this issue?
