### ISSUE TITLE
InstructorFeedbacksPage sometimes loads without the form for creating a new session

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#3020]
![noform](https://cloud.githubusercontent.com/assets/2216119/6342441/fba7d1a2-bc13-11e4-8084-2c1b0cd447bb.PNG)

The form for creating a new session is missing in the above screenshot.

**Comment by damithc** [comment]
I noticed that too. In fact the form appears at first and then disappears
after a few seconds. Is it something specific to testing or the web driver?
I didn't notice it in the live site or dev site.

**Comment by kanghj** [comment]
I've encountered this outside of testing before, when using the dev server. We have a form that submits, using ajax, to the same page to load the sessions table, but sometimes it submits the form without using ajax, taking the browser to the page that is supposed to be loaded by ajax.

**Comment by damithc** [comment]
Probably fixed now. No reports from users.
