### ISSUE TITLE
build an AccessControlUtil

### ISSUE THREAD

**Issue by kai33** [TEAMMATES/teammates#3046]
It would be nice to have an AccessControlUtil (similar to GateKeeper) for action level and page data level: call the api, pass the required params, then can get the filtered results or whether to disable/hide the web elements.

benefits:
0, re-use the codes in actions & jsp pages, avoid copy-paste & not sync problem
1, look cleaner
2, easy for the newcomers to apply
3, easy to manage the code base for access control

**Comment by chowyb** [comment]
@damithc As discussed, I'll begin trying out this issue to see which approach works best.

@JosephineKwa this is the issue I was referring to, hopefully it won't conflict too much with your feature ><
