### ISSUE TITLE
Student: view results of anonymous questions: hide/clarify misleading stats

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#3063]
In anonymous questions (only recipient can see responses anonymously), stats for other students is simply based on the viewers own responses, but that fact may not be clear to the viewer. We have to state that the table is based on the values shown below only. Furthermore, it is better if we can omit such misleading stats.

**Comment by jacoblipech** [comment]
@damithc To clarify sir, which question type does this statistics apply to? As a student, when I clicked on view responses, I only can find statistics such as the one shown below for distributing points question type. Is this what you are referring to?
<img width="919" alt="screen shot 2018-05-25 at 5 44 06 pm" src="https://user-images.githubusercontent.com/28522090/40538176-85a7699a-6043-11e8-9619-1de5fe1ae8f0.png">

**Comment by damithc** [comment]
Try a few other question types. Perhaps this issue no longer exists. Sometime back we used to show to students the summary stats for the whole class; we may have removed that feature at some time. If that feature doesn't exist anymore, this issue doesn't exist either.

**Comment by jacoblipech** [comment]
I have tried all the following question types and statistics do not appear for any of these questions:
- Team Contribution Question
- Essay Question
- MCQ (Single & Multiple) Question
- Numerical Scale (among options) Question
- Numerical Scale (among recipients) Question
- Distribute Points (among recipients) Question
- Distribute Points (among options) Question
- Rubric Question
- Rank Question (student)
- Rank Question (question format)

The only statistics that appear is for the numerical scale question as I have shown above but I think the statistics looks clear enough that it is only from the respondent himself.
I think we can safely close this issue.

**Comment by damithc** [comment]
Thanks for checking @jacoblipech
