### ISSUE TITLE
Table rows outside Modal window in instructorFeedbackResultsPage

### ISSUE THREAD

**Issue by arvind-kalyan** [TEAMMATES/teammates#3070]
Steps to reproduce the issue:
1. Log in as SHomeUiT.instr
2. Add New Feedback Session
3. Click "View Results", after creating the session. 
4. Click on "click here" link shown in the image attached.

![initial](https://cloud.githubusercontent.com/assets/5078299/6556678/1abfc9ec-c695-11e4-9cde-9f6b90b1ea9a.JPG)
![outside modal window](https://cloud.githubusercontent.com/assets/5078299/6556712/513966c2-c695-11e4-8e05-82d8f7f78982.png)

**Comment by arvind-kalyan** [comment]
When we open the modal window, the table is selected by default, even before "Select Table" is clicked. Was it meant to be like that?

**Comment by damithc** [comment]
The content is simply meant to be copy pasted to another document, not read
manually. That is why the content is already selected. That is also why
beautifying the display is a low priority.
