### ISSUE TITLE
Instructor home page: show feedback start/end times in a timeline

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#3074]
so that instructors can do a visual double-check of whether the start/open times were set correctly.

**Comment by vamshi-s** [comment]
@damithc 
I need to modify this page ryt ?
Please read the Instructions dialog in the Image.
Please can you provide me some more information, if i interprrted the issue wrongly.

![feedback submission](https://cloud.githubusercontent.com/assets/11355301/6599918/716f2c30-c832-11e4-94fe-3ebb02237a49.png)
