### ISSUE TITLE
Instructor: search students: add a confirmation dialog for the "delete" button

### ISSUE THREAD

**Issue by ryancyq** [TEAMMATES/teammates#3091]
Currently, there isn't any test checking for the confirmation dialog of "delete" button.

**Comment by arvind-kalyan** [comment]
Can I try this?

**Comment by damithc** [comment]
In fact, there is no confirmation for the delete button. :-p

![image](https://cloud.githubusercontent.com/assets/1673303/25886631/0f510dc4-3591-11e7-8147-11cbcdb27b6b.png)

**Comment by amarlearning** [comment]
@damithc Is think this issue should be closed because I just checked there is a confirmation modal for the delete button. _[screenshot]_
![screenshot from 2017-05-24 03-49-27](https://cloud.githubusercontent.com/assets/9383897/26378925/38910a10-4034-11e7-9245-f05787d3580f.png)

**Comment by damithc** [comment]
> Is think this issue should be closed because I just checked there is a confirmation modal for the delete button.

@amarleraning
Yes, there seems to be a confirmation dialog (my bad), but this issue is about adding tests for it. Check if your UI tests cover the said modal dialog.

**Comment by amarlearning** [comment]
@damithc I think then the title of this issue should be changed :smile:

**Comment by damithc** [comment]
> @damithc I think then the title of this issue should be changed

You are right. Done. 👍

**Comment by amarlearning** [comment]
> Check if your UI tests cover the said modal dialog.

@damithc Yes, we do have a [test](https://github.com/TEAMMATES/teammates/blob/master/src/test/java/teammates/test/cases/browsertests/InstructorStudentListPageUiTest.java#L242) for the `delete` button.

Both [`viewPage.clickDeleteAndCancel(courseId, studentName)`](https://github.com/TEAMMATES/teammates/blob/master/src/test/java/teammates/test/cases/browsertests/InstructorStudentListPageUiTest.java#L258) and [`viewPage.clickDeleteAndConfirm(courseId, studentName)`](https://github.com/TEAMMATES/teammates/blob/master/src/test/java/teammates/test/cases/browsertests/InstructorStudentListPageUiTest.java#L262) are covered. :+1:

**Comment by amarlearning** [comment]
The issue still open? :sweat_smile:

**Comment by whipermr5** [comment]
@amarlearning The instructor search page delete does not have a confirmation modal. You were looking at the instructor student list page.

**Comment by amarlearning** [comment]
Taking this one

**Comment by joanneong** [comment]
I will try working on this issue.
