### ISSUE TITLE
beautifying the instructorCourseEdit page customizing sections part

### ISSUE THREAD

**Issue by franklingu** [TEAMMATES/teammates#3145]
currently it is just a groups a checkboxes, but it does not look good.
a suggested solution is [multiselect](http://davidstutz.github.io/bootstrap-multiselect/)
another one that looks really good [chosen](http://harvesthq.github.io/chosen/)

**Comment by sujeet14108** [comment]
Can i solve this by using multiselect?

**Comment by damithc** [comment]
@sujeet14108 as you are a new contributor, look for a `d.FirstTimers` or `d.Contributors` issue first.

**Comment by sujeet14108** [comment]
@damithc  i have solved one of the d.FirstTimers issue. Do i have to solve more d.FirstTimers issue?

**Comment by damithc** [comment]
No. In fact you should not do more than one first timer issue. Now you can move to `d.Contributors` issues.
