### ISSUE TITLE
Display constant sum statistics sorted by recipient name or option

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#3147]
For both the statistics on the website and in the csv file downloadable by instructors, the statistics table can be displayed in a sorted order

Edit (18 December 2016):
Screenshot (of the table to change sorting for ): 
![constantsumstats](https://cloud.githubusercontent.com/assets/2216119/21293745/fbe2f0fc-c567-11e6-9e20-d731782fb221.PNG)

**Comment by Siddhant085** [comment]
can I solve this one?

**Comment by kanghj** [comment]
There is no longer a need to be assigned the issue, you can work on it and make a pull request for it when you are done.

**Comment by swxsw** [comment]
Just to clarify, what is meant by statistics on the website and where do I download the csv file? Is the statistics referring to when an instructor views the feedback results page of a set of questions that was given?

**Comment by damithc** [comment]
@swxsw both refer to session results as seen/downloaded by instructors.

**Comment by swxsw** [comment]
@damithc Correct me if I am wrong, but isn't the session results already displayed in a sorted order when the user/instructor clicks on the respective header? Is this issue referring to the need to sort by more than one column or things like reverse sorting?
![capture](https://cloud.githubusercontent.com/assets/19543997/21283771/b0e47ece-c443-11e6-89d1-5cd8bd203d2a.JPG)
Genuinely confused, sorry

**Comment by damithc** [comment]
'sortable' is not the same as 'sorted' :-) Anyway, may be @kanghj who posted the issue can say more.

**Comment by swxsw** [comment]
Oh, i see :) @kanghj, is there any preferred sorting order when the results are first displayed?

**Comment by damithc** [comment]
Sort by `recipient` (or `option`)?

**Comment by swxsw** [comment]
@damithc Got it:) Sorry for asking, didn't realize
