### ISSUE TITLE
Mass editing the email addresses of already enrolled students

### ISSUE THREAD

**Issue by BillyZafack** [TEAMMATES/teammates#3186]
An instructor cannot mass edit email addresses of students he has already enrolled. This is because, the email address column is used as reference(to identify a student) in the mass editing. We could nevertheless let the instructor choose this reference column(reasonable ones of course), thus permitting the mass editing of email addresses.

**Comment by damithc** [comment]
Internally, email is used as the primary key for students in a course. So it is a bit hard to allow mass editing emails. KIV for now.

**Comment by damithc** [comment]
Will be considered in the upcoming student data ui update
