### ISSUE TITLE
Change "Received Responses Statistics" to "Statistics for Received Responses"

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#3245]
In the instructor's results page, on the views where the statistics are shown, the text shown is "Received Responses Statistics". "Statistics for Received Responses" sounds better.

**Comment by Doomdev** [comment]
Fixes - https://github.com/TEAMMATES/repo/pull/3248 . :+1:

**Comment by weaveranoop** [comment]
@kanghj While going through this issue, I also found a jsp file (also a linked HTML file inside src\test\resources\pages folder) containing the heading "Given Responses Statistics" which should also be converted to "Statistics for Given Responses". Should I go forward and do the needful? What do you suggest?

**Comment by kanghj** [comment]
Yes. If you really wish to, you can go ahead and make a pull request if you have fixed the issue, although they will not be reviewed for now.
