### ISSUE TITLE
Bind HTML to input boxes so that we can test the functionality of clearing the text boxes

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3263]
Related to #3235.

![screen shot 2015-04-05 at 1 06 17 am](https://cloud.githubusercontent.com/assets/6291947/6993846/f82545ce-db34-11e4-8a9d-7e8fbf687acf.png)
![screen shot 2015-04-05 at 1 06 01 am](https://cloud.githubusercontent.com/assets/6291947/6993847/f827e612-db34-11e4-9258-6836fa0d614e.png)

Currently, when changing the text boxes for Rubric options, MCQ and MSQ options, the HTML remains as the default initialized values and do not change - thus rendering us unable to test for the functionality of clearing text boxes.

**Comment by wkurniawan07** [comment]
This kind of direct DOM manipulation is no longer employed in V7.
