### ISSUE TITLE
Set up a Continuous Integration system for all pull-requests

### ISSUE THREAD

**Issue by kai33** [TEAMMATES/teammates#3295]
1. It's time-consuming (~30min) for reviewers to run all test cases to ensure dev green before merge a pull-request.
2. Instead, it's professional to use Continuous Integration (CI, eg Jenkins) to monitor our PR list. If there's new PR, it will pull the PR, build, run all tests and run failed test against the master branch for some times.
3. It can even do more, eg to build using Maven with Cobertura plugin to ensure that test coverage % is always above certain stat, with PMD to find common programming flaws, verify coding & naming styles etc.
4. When the test is dev green, CI can post a status (green or not) and result link back to the PR. Thus, the reviewers only need to focus on those green ones and if codes are fine, we can directly merge it.

It's feasible, super productive, and I think @thyageshm has done half of the work already.

**Comment by damithc** [comment]
I believe Eric @wgx731 also did some work on trying to apply CI to TEAMMATES.

**Comment by thyageshm** [comment]
I totally agree with this proposal (also considering my comp isnt able to handle the entire test suite easily.. :-P). But one thing I have realised is that an impediment to this idea are the dependencies of the project. Since developers are allowed to use new libraries in the code, we have to update the CI system so that the build doesnt break.

**Comment by thyageshm** [comment]
@ashrayjain we can take the CI forward with this issue

**Comment by ashrayjain** [comment]
Sure, I would like to formally specify the requirements first though. What are our requirements here?
To start off, we probably build and test every new PR when it is created? After that, whenever the PR is updated, we run it again to update CI status for that PR?
What about a build on master after merging a PR? If this build fails, what should be done?

**Comment by thyageshm** [comment]
Lets try to setup a manual run on the master on Travis. Based on how long it takes, we can decide on when to run the test suite (eg: every update to PR vs when `s.ToReview` is added to the PR [?])

**Comment by thyageshm** [comment]
@damithc sir, does it make sense for us to call this issue a `c.Epic` and create multiple `c.Story` for fixing existing issues, documentation, etc related to this?

**Comment by kai33** [comment]
wrt dependency, r u guys going to try [maven-dependency-plugin](https://maven.apache.org/plugins/maven-dependency-plugin/)?
it will help copy the dependency jar files to the target folder when build.

The new PR with new lib should include the new dependency in pom.xml, and then maven will download and copy it to the right place. So no need to worry about this.
> But one thing I have realised is that an impediment to this idea is the number of dependencies of the project. Since developers are allowed to use new libraries in the code, we have to update the CI system so that the build doesnt break.

**Comment by damithc** [comment]
This is not a user-facing feature, so technically not a story or an epic. But do feel free to break into smaller tasks.

If you are getting maven involved, see if gradle can be used instead. 1. We used maven before, and it was a pain to use at the time. 2. Hubturbo is using gradle, so I don't want to add another new tool unless we have to.

**Comment by ashrayjain** [comment]
@damithc @thyageshm for the issue of multiple builds being triggered in quick succession for the same PR, we can use this project. https://github.com/grosser/travis_dedup
I tested this with a test project and it works well. We can use the first option where we simply add a webhook to our repo from the github dashboard.

This seems to be the recommended way to go. More discussion on this here. https://github.com/travis-ci/travis-ci/issues/964

**Comment by damithc** [comment]
Sure, we can try that.
