### ISSUE TITLE
Instructor: make session buttons more clickable / tappable

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3324]
Refer to screenshot below, if more buttons are added / even without more buttons being added and on smaller screen sizes (on screenshot 13 inch), the buttons can go to the next line and have no padding between each other -> tapping / clicking on some buttons might be harder.

![button](https://cloud.githubusercontent.com/assets/6291947/7195857/acaecfe2-e4f9-11e4-9f13-638a602cd171.png)

**Comment by damithc** [comment]
We'll improve the space utilization later as a separate issue. e.g. we can
replace common buttons like edit/delete/copy with icons.

**Comment by amarlearning** [comment]
@junhaoyap Looks like this issue is resolved by now.
[screenshot]
![screenshot from 2017-05-24 03-27-26](https://cloud.githubusercontent.com/assets/9383897/26378206/22d4bb0c-4031-11e7-827f-5dcd260772bd.png)

**Comment by damithc** [comment]
Yes, can be closed.
