### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#3342]
This happens when trying to view results for a course of 150 student, team size 5, and 8 peer evaluation questions. i.e. about 150_8_5= 6000 responses. As far as I can see, the user does not see any error message, but the server instance dies while trying to load the results page.

**Comment by LowWeiLin** [comment]
IS there a stack trace for this?

**Comment by damithc** [comment]
Here it is:


javax.servlet.ServletException: java.lang.OutOfMemoryError: Java heap space
    at
org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:862)
    at
org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:791)
    at
org.apache.jsp.jsp.instructorFeedbackResultsByRecipientGiverQuestion_jsp._jspService(instructorFeedbackResultsByRecipientGiverQuestion_jsp.java:1209)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:97)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at
org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at
org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
    at
org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at
org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at
org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:327)
    at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:126)
    at teammates.ui.controller.ShowPageResult.send(ShowPageResult.java:57)
    at
teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:59)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at
org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at
teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
    at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at
com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:142)
    at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at
com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
    at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at
com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)
    at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at
com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
    at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at
com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
    at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at
org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at
org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at
org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at
org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at
com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:254)
    at
org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at
org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at
org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at
com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at
com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
    at
com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:527)
    at
com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
    at
com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
    at
com.google.tracing.CurrentContext.runInContext(CurrentContext.java:220)
    at
com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
    at
com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
    at
com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
    at
com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:251)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:2271)
    at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
    at
java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
    at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
    at java.io.OutputStream.write(OutputStream.java:75)
    at
com.google.apphosting.runtime.jetty.RpcResponseGenerator.addContent(RpcResponseGenerator.java:65)
    at
org.mortbay.jetty.AbstractGenerator$Output.write(AbstractGenerator.java:644)
    at
org.mortbay.jetty.AbstractGenerator$Output.write(AbstractGenerator.java:579)
    at java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:167)
    at
org.mortbay.jetty.AbstractGenerator$OutputWriter.write(AbstractGenerator.java:927)
    at java.io.PrintWriter.write(PrintWriter.java:426)
    at
org.apache.jasper.runtime.JspWriterImpl.flushBuffer(JspWriterImpl.java:119)
    at org.apache.jasper.runtime.JspWriterImpl.write(JspWriterImpl.java:326)
    at org.apache.jasper.runtime.JspWriterImpl.write(JspWriterImpl.java:342)
    at
org.apache.jsp.jsp.instructorFeedbackResultsByRecipientGiverQuestion_jsp._jspService(instructorFeedbackResultsByRecipientGiverQuestion_jsp.java:970)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:97)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at
org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at
org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
    at
org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at
org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at
org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:327)
    at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:126)
    at teammates.ui.controller.ShowPageResult.send(ShowPageResult.java:57)
    at
teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:59)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at
org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at
org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at
teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)

**Comment by kai33** [comment]
The reason may be that, this page with 6K response UI elements is quite heavy already. When users view it for some times and GC is not working on time, it can easily exceed the memory limit in GAE (only up to 1GB, too small)

Possible solutions:
the core idea is not to load all the response UI elements at one time
1. Paginate the results by question/section/team etc
2. Only load 25~100 responses at the beginning, and provide a 'load more' option to do async loading for the next 25~100 responses

similar to what InstructorCommentsPage did (pagination + ajax loading).

**Comment by damithc** [comment]
Old issue. closing.
