### ISSUE TITLE
Instructor: view results: table width may exceed panel's

### ISSUE THREAD

**Issue by kai33** [TEAMMATES/teammates#3348]
as per title, for view type: Group By Question & Group By RQG
![screen shot 2015-04-23 at 1 42 02 am](https://cloud.githubusercontent.com/assets/3591355/7281188/80fdb646-e95a-11e4-98d8-77a8d35f4217.png)

**Comment by HirdayGupta** [comment]
I'm unable to replicate this issue in the Instructor view results page. Is this still an issue?

**Comment by damithc** [comment]
Try including a very long word (e.g. a long URL) in one of the responses.

**Comment by HirdayGupta** [comment]
@damithc Still unable to reproduce. Could you give me the specifics of how you reproduced the error?

**Comment by damithc** [comment]
Seems to be fixed now. Closing. Thanks for investigating @HirdayGupta
