### ISSUE TITLE
adminSearchResults: Give a way to resend a specific link 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#3355]
This is for cases where a student emails me saying they did not receive a link.

**Comment by thyageshm** [comment]
@JosephineKwa could we try and complete this by this release?

**Comment by damithc** [comment]
Lowered priority. Can manage without this feature for some more time.

**Comment by thyageshm** [comment]
@JosephineKwa reminder about this issue. please consider unassigning some issues if your feel the workload is high at this time. You can reassign yourself when things settle down :-)

**Comment by thyageshm** [comment]
Unassigning issue due to inacitivity

**Comment by damithc** [comment]
Superseded by another issue
