### ISSUE TITLE
instructorFeedbackEdit.js multiple hiding of same element

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3373]
Within function toggleVisibilityMessage and getVisibilityMessage, the selected form's 'visibilityOptions' is hidden multiple times.

If toggle already hides it, do we need to hide it again in getVisibilityMessage, upon success and also if previousFormData === formData and one more time in getVisibilityMessageIfPreviewIsActive as it calls getVisibilityMessage?

**Comment by damithc** [comment]
Old issue. closing.
