### ISSUE TITLE
Highlight keywords in search results

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#3392]
This can be useful in searching by student name etc., for both for instructor/admin users

**Comment by damithc** [comment]
example:
![image](https://cloud.githubusercontent.com/assets/1673303/7580564/f21aaf1a-f8a9-11e4-8eb6-cc9d8dd8be06.png)

**Comment by bamboo3250** [comment]
I think this issue has been addressed via PRs of #4513 and #4798.

**Comment by damithc** [comment]
Yes, that's right. Closing.
