### ISSUE TITLE
Responses to teams are not correctly updated when a team is renamed

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#3404]
When updating teams and sections in the enrollment page, and the entire team is moved to a different section, FeedbackResponseLogic fails to correctly update the response's section where the team is the recipient.

**Comment by damithc** [comment]
I think we should provide a proper 'rename team' feature. Otherwise it is hard to detect when a team is being renamed.

**Comment by damithc** [comment]
Will be considered in the upcoming student data UI update.
