### ISSUE TITLE
Instructor: view results: Do not show 'Missing Response' rows for sections that instructors do not have permissions for

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#3431]
It is correct that the responses are not visible to an instructor who does not have sufficient permissions to view all responses in the class. However, the 'No Response' rows are appearing for these sections that the instructor does not have permissions to view responses for. 

The code for determining whether to show the 'No Response' rows should be smart enough to account for the instructors' permissions level.

**Comment by rclakmal** [comment]
@kanghj @damithc Would like to try this out. What exactly is the current logic. As per the code it looks like if either recipient section or giver section is restricted, instructor is not allowed to see the feedback. Right ?

`boolean isNotAllowedForInstructor = isGiverSectionRestricted || isRecipientSectionRestricted;`

**Comment by MaddyThakker** [comment]
@kanghj can I take this up?

**Comment by arjunsuri** [comment]
what exactly do we need to do in this issue?

**Comment by kanghj** [comment]
On the feedback results page for instructors, "Missing response" rows are shown for students who have not submitted a response yet. However, if an instructors does not have permission to view responses for some students, "missing response" rows are displayed for these students currently. Things could be improved by not displaying any row for these students.

**Comment by arjunsuri** [comment]
great I am taking it

**Comment by arjunsuri** [comment]
I looked into the issue....there are around 100 errors in InstructorFeedbackResultsPageData.java when I run this program in my local machine...Do I need to resolve the bugs

**Comment by dabbler011** [comment]
working on this.

**Comment by Haozhe321** [comment]
@dabbler011 are you still working on this?

**Comment by FergusMok** [comment]
I've tried replicating the problem, but I believe the problem has already been solved (3 years ago)

This is the "Feedback Session Results" view of an instructor that is unable to view responses (There is a submitted response).

![image](https://user-images.githubusercontent.com/10182564/155729775-af32ea15-f233-40c2-93fc-1d926ed88000.png)

**Comment by wkurniawan07** [comment]
Closing as issue has been resolved
