### ISSUE TITLE
Instructor: 'all records' page: contribution questions: show 'perceived contribution' even if the student has not submitted responses

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#3432]
Scenario:
* There is a session with a 'team contribution' question. e.g., the `First team feedback session` in the sample course of a new instructor
* There is a student who has not submitted the session. To simulate this, you can edit the submission of a student in the session mentioned above to remove his/her submission for the question in concern.
* Instructor is looking at the 'All records' page of that student.

Currently, the _Perceived Contribution (PC)_ value is shown within the student's self response. Here is the page for a student who has submitted the session.

![image](https://user-images.githubusercontent.com/1673303/36832534-d2469750-1d66-11e8-8add-3dc834158542.png)

If the student has not submitted anything for that session, the PC value is not shown at all. Here is an example (compare with the screenshot above)

![image](https://user-images.githubusercontent.com/1673303/36832844-3d1594f4-1d68-11e8-9d34-d4ea9339b569.png)

This is also applicable to when the instructor is viewing results, grouped by recipient. e.g.,
![image](https://user-images.githubusercontent.com/1673303/36833091-37e819ba-1d69-11e8-8588-14645297085a.png)

I suspect both problems can be solved by one fix (if both views are generated by the same code). If not, create another issue for the second one after fixing the first one.

**Comment by VamsiSangam** [comment]
Working on this.

**Comment by architkansal** [comment]
I would like to work on it. Could you elaborate a bit more on this and where should I start looking?

**Comment by damithc** [comment]
> I would like to work on it. Could you elaborate a bit more on this and where should I start looking?

Updated the description with more details.

**Comment by architkansal** [comment]
I tried reproducing the scenario:
I created a course - cs101 and a session in it - Feedback for PPT-1
I added some students and submitted session for one student ( from student's account ).
Why is the **PC:  N/A** in Instructor's View ? and there is **no data** corresponding to other students (who have not submitted session ) about themselves.
I might be lacking some context here. Cloud you explain a bit more about the PC value and how to reproduce the problem in a new session, to help me understand better.
Here are some screenshots from my session:
**Instructor View:**
![screenshot from 2018-03-01 15 05 20](https://user-images.githubusercontent.com/15241672/36838100-3b04f438-1d64-11e8-9f8d-841a51121c35.png)
![screenshot from 2018-03-01 15 05 31](https://user-images.githubusercontent.com/15241672/36838106-3fa371cc-1d64-11e8-8e51-ed1c32729954.png)
**Student View:**
![screenshot from 2018-03-01 15 09 22](https://user-images.githubusercontent.com/15241672/36838107-42fe6e94-1d64-11e8-9dbb-6581c8c07e8a.png)

**Comment by damithc** [comment]
> Why is the PC: N/A in Instructor's View ?

PC is calculated based on how others rated the student. If no one else has rated the student, PC is not available.

**Comment by architkansal** [comment]
so PC is only applicable for `Team Contribution` Question right ?
and in 2nd Image above, `To Jean Wong - From Anshul Goyal ` the PC value should have been there as Anshul has given feedback for Jean Wong. But Jean Wong has not submiited the session yet. And that is the issue here exactly right ?

**Comment by damithc** [comment]
> so PC is only applicable for Team Contribution Question right ?
> and in 2nd Image above, To Jean Wong - From Anshul Goyal the PC value should have been there as Anshul has given feedback for Jean Wong. But Jean Wong has not submiited the session yet. And that is the issue here exactly right ?

Yes, for both questions.

**Comment by architkansal** [comment]
Thanks a lot for the clarification. Could you point me to the files to look at for this ?

**Comment by architkansal** [comment]
Is there some way to persistently store the data from localhost somewhere so that when server is restarted the data including courses, students etc is not lost ?
or incrementally build the server so that changes in backend reflect without restarting the server again to avoid losing data ?

**Comment by damithc** [comment]
> Is there some way to persistently store the data from localhost somewhere so that when server is restarted the data including courses, students etc is not lost ?

@LiHaoTan for your comments please

**Comment by wkurniawan07** [comment]
> Is there some way to persistently store the data from localhost somewhere so that when server is restarted the data including courses, students etc is not lost ?

@architkansal is that not the case right now? Are you developing with Eclipse, IntelliJ, or command line?

**Comment by architkansal** [comment]
Right now, when I restarted the server with some changes in UI controller, all my data got erased.
I am developing with Eclipse. Though I ran the server from terminal using `./gradlew appengineRun`.

**Comment by wkurniawan07** [comment]
> Though I ran the server from terminal using `./gradlew appengineRun`.

Thanks for reporting. Apparently the `run` command is modified when the Gradle plugin upgrades from `1.3.3` to `1.3.4`. Will create an issue and submit a quick fix.

Meanwhile, if you want to bypass this limitation for now, change the value of `1.3.4` here to `1.3.3`:
https://github.com/TEAMMATES/teammates/blob/7390503e29083bc487c7d0b689177ea8bc71e897/build.gradle#L27

**Comment by architkansal** [comment]
Thanks, will switch to 1.3.3 for now.

**Comment by architkansal** [comment]
what are the best ways to log the outputs in the project temporarily for the sake of investigation ?
can we hit the endpoints explicitly and get the data e.g. using postman, for a session ?
What practices do we generally follow here ?

**Comment by wkurniawan07** [comment]
@architkansal have you read the [development guidelines](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md)? You can find the answers to all your questions there.

> Can we hit the endpoints explicitly and get the data e.g. using postman, for a session ?

No; we don't use a RESTful architecture. There is a limited subset of function that adopt RESTful architecture but this is for the testing infrastructure rather than production usage.

**Comment by architkansal** [comment]
Why are there two different values ? ( 'All Records' Page )
from Anshul Goyal to Anshul Goyal: ( Shows the value actually filled by Anshul Goyal )
![screenshot from 2018-03-02 16 22 49](https://user-images.githubusercontent.com/15241672/36895789-335c84d0-1e36-11e8-80c1-32420923e473.png)

to Anshul Goyal from Anshul Goyal: ( How is this calculated? )
![screenshot from 2018-03-02 16 22 37](https://user-images.githubusercontent.com/15241672/36895815-4e50670c-1e36-11e8-82bd-5cfe32b101ad.png)

**Comment by nidhi98gupta** [comment]
@architkansal For understanding how contributions are calculated, you can view this file.
[https://github.com/TEAMMATES/teammates/blob/898c5c994bab4258957404762303dce24bca9282/src/main/webapp/partials/technicalInformationCalculatePointsContribution.jsp](url)

**Comment by damithc** [comment]
> Why are there two different values ?

This happens when a student a student gives ratings that don't add up to the correct total. e.g., if there are 4 members but the students ratings add up to 4E+10% instead of the correct value 4E.

The `To Student` view shows values after correcting for this error while `From student` view shows before.  Yes, this is confusing to the reader, but that's a battle for another day.

**Comment by architkansal** [comment]
I am not sure where the PC value is calculated / sent to the browser. I have been trying to track it all the way but unable to:
Below is the image showing one of the `CONTRIB` Question Response. 
![image](https://user-images.githubusercontent.com/15241672/36922885-6db278ac-1e8f-11e8-88eb-1e59e5378590.png)
 and Corresponding Question:
![image](https://user-images.githubusercontent.com/15241672/36923036-f8c01c24-1e8f-11e8-988e-03dc8ad72f93.png)

Based on my understanding of the code, a set of these `relevantQuestions` and `responses` are what sent in response to the ajax call.
I could not find a response with values of PC and yet I can see the PC value for user "Anshul Goyal" ( image in previous comment ) I could not find that logic in front-end either.
Could you help me figure it ?
Thank you for prompt replies. its taking me some time to on-board, this architectural style is somewhat new to me and I have not used JSP before. Once through, I could contribute faster.

**Comment by architkansal** [comment]
Got it! Below is an example for student who has not submitted session but now his PC value is shown in all records Page:

![image](https://user-images.githubusercontent.com/15241672/36945225-edfb3aac-1fd0-11e8-9627-598ed9b9d21a.png)

I have shown the student's own response as `NOT AVAILABLE` and displayed the PC value next to it.
Is that okay from UI side or do we want to display it in some other manner ?
Also this does not fix the view when the instructor is viewing results, grouped by recipient as you has suspected @damithc so I shall take care of that separately when this one is done.

**Comment by damithc** [comment]
> Is that okay from UI side or do we want to display it in some other manner ?

In other places we show absence of a response like the following. May be we can do the same here?
![image](https://user-images.githubusercontent.com/1673303/36946289-a8e5afea-1ff5-11e8-8b07-1cb008c76a39.png)

**Comment by architkansal** [comment]
@damithc  sure, will replace the text "NOT AVAILABLE" with "No Response".

**Comment by architkansal** [comment]
@damithc is there some command / tool to format the code according to the required code style in order to pass the static analysis ?
should I run in God mode also, to update the expected html files ?

**Comment by damithc** [comment]
> @damithc is there some command / tool to format the code according to the required code style in order to pass the static analysis ?
> should I run in God mode also, to update the expected html files ?

You can run linters to ensure the code style is correct. Our dev docs explain how to setup/run linters.
Yes, you'll need God mode for this.

**Comment by architkansal** [comment]
I think there is one small issue in [Development Guidelines-Using Chrome](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#using-chrome).
We need to mention :
change `test.selenium.browser=firefox` to `test.selenium.browser=chrome`.
let me know if that is correct. I will create one small issue and submit the solution.

**Comment by damithc** [comment]
> let me know if that is correct. I will create one small issue and submit the solution.

Go ahead @architkansal

**Comment by wkurniawan07** [comment]
@architkansal refer to existing issue #8254.
However, I am also currently working on general documentation update under the flag of #8565 which will also include that, so you need not work on it.

**Comment by jacoblipech** [comment]
closed via #8874
