### ISSUE TITLE
Remove isArchived attribute from courses

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#3511]
Since the archive status is now on the Instructor entities instead of Courses, we should remove it on the course so that the attribute does not cause confusion

**Comment by damithc** [comment]
Yes, we should. I wonder what would happen if we try to load a legacy
object that has the attribute using the new class that doesn't have the
attribute.

**Comment by kai33** [comment]
https://github.com/TEAMMATES/repo/blob/master/src/main/java/teammates/logic/core/CoursesLogic.java#L720

may need to migrate first?

**Comment by kanghj** [comment]
We have a migration script which adds the isArchived attribute to instructors for this already : DataMigrationForIsArchivedAttribute.java

If the migration is already done, then it should be safe to remove the attribute from the entity. We can write another migration script to remove the attribute entirely, as mentioned on https://cloud.google.com/appengine/articles/update_schema. But the [TEAMMATES technical report on legacy data](https://docs.google.com/document/d/1syHy4BPrM7TkCP7PJYvYZmt7rkRROWqYvBh8w_ZJt1w/pub?embedded=true) suggests that the attribute will be deleted in future when modifications to the course are made. As for loading the legacy data, the additional attribute will be ignored.

**Comment by kai33** [comment]
then it should be fine.

one thing to note: https://github.com/TEAMMATES/repo/blob/master/src/main/java/teammates/common/datatransfer/InstructorAttributes.java#L129
a default value 'false' may be required
