### ISSUE TITLE
InstructorFeedbackResultsPage, FeedbackSessionResultsBundle: refactor

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#3512]
Refactor InstructorFeedbackResultsPage and the functions in the logic layer that it uses, as well as FeedbackSessionResultsBundle.

**Comment by tshradheya** [comment]
In #8233 I refactored `FeedbackSessionResultsBundle.java` while changing comparators to lambdas so it looks like that file is pretty much refactored.

And for `InstructorFeedbackResultsPage.java` can I ask as to what exactly needs to be refactored?

**Comment by wkurniawan07** [comment]
This issue looks not well-defined. Usually the case when someone wants to refactor something but lost interest in it subsequently. Will be closing this; can open a new one on a necessity basis.
