### ISSUE TITLE
StudentProfilePageUiTest fails frequently on line 177

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3527]
getProfilePicturePage(instructorId, email, courseId).verifyHasPicture();

expected puzzled.png but got entityNotFound.png, only started encountering this recently but > 50% of the time when I run entire test suites I get this weird failure which never happened before.

**Comment by MrFool** [comment]
Managed to pin point the error but I'm not very sure how to fix this ->

![screen shot 2015-05-27 at 3 29 25 pm](https://cloud.githubusercontent.com/assets/6291947/7831027/35eeb506-0485-11e5-9ee2-84af564471be.png)
![screen shot 2015-05-27 at 3 28 54 pm](https://cloud.githubusercontent.com/assets/6291947/7831026/35edfa08-0485-11e5-9405-9443c7448de6.png)
![screen shot 2015-05-27 at 3 28 39 pm](https://cloud.githubusercontent.com/assets/6291947/7831028/35efd256-0485-11e5-80f5-b721a3a861dd.png)
![screen shot 2015-05-27 at 3 30 16 pm](https://cloud.githubusercontent.com/assets/6291947/7831037/4d5bc094-0485-11e5-849e-95d6936c67e8.png)


Note the test tries to log in admin as masquerade but instead gets entityNotFound, so the problem doesn't lie in the assertion but actually the login process, could it be that there is another test we should run sequentially as they might be interfering with each other again?

**Comment by LowWeiLin** [comment]
@thyageshm I'm getting this as well. Any ideas?

**Comment by LowWeiLin** [comment]
@thyageshm This is still happening

**Comment by thyageshm** [comment]
let me look into this

**Comment by thyageshm** [comment]
will start work on this after my FYP report is submitted

**Comment by wkurniawan07** [comment]
Looks like this got solved by modifying the thread count in Travis (although it introduced new failures), so closing.
