### ISSUE TITLE
Instructor: view results: add comprehensive tests for the different visibility options

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#3530]
To complete #3512, our tests should cover the different visibility options comprehensively. 

Edit: In particular, the test to add should cover the different visibility settings on the results page, for both students and instructors with different permissions, and cover the different question types (to test the statistics computed under various access control and visibility settings) and different feedback paths.

**Comment by MrFool** [comment]
Does this deal with InstructorFeedbackQuestionVisibilityMessageAction testing?

**Comment by kanghj** [comment]
Related, but not what I was thinking about when I made this issue. Will update the issue description to be more specific

**Comment by MrFool** [comment]
Ok, I'll look into the one I was talking about in my slice refinement then, it's currently 0% tested

**Comment by xpdavid** [comment]
Specifically in V7, the result logic has been simplified and visibility checking is just several places:
- Add tests for `FeedbackSessionsLogic::isResponseVisibleForUser` (We might want to move it to response logic as this is the task related response logic)
- Add tests for `FeedbackResponsesLogic::isNameVisibleToUser`
- Add tests for `FeedbackResponseCommentsLogic::isResponseCommentVisibleForUser`
- Add tests for `FeedbackResponseCommentsLogic::isNameVisibleToUser`
