### ISSUE TITLE
FeedbackRubricQuestionUiTest, FeedbackRankQuestionUiTest: simplify

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#3554]
Unnecessarily complicated compared to its comrades (Feedback...QuestionUiTest). Or is it for a reason?

**Comment by wkurniawan07** [comment]
I realized this issue is because Rubric questions came into the playing ground late. There are two possible solutions to this, both of which are somewhat equally time-consuming:
1. Make other question tests like Rubric (but still simplify Rubric where possible).
2. Make Rubric like other question tests, migrate the extra tests to more relevant pages (e.g test(Instructor/Student)(Submit/Results)Page to (Instructor/Student)Feedback(Submit/Results)PageUiTest.

**Comment by damithc** [comment]
@LowWeiLin any comments?

**Comment by LowWeiLin** [comment]
Which part is more complicated? Simplifying the tests but maintaining coverage is welcome.

The reason the rubric tests was separated into a test by itself was due to the UI tests taking way too long to complete. Separating it out allows us to run them in parallel, and not stop and have to run everything again if there is a failure.

**Comment by wkurniawan07** [comment]
If you compare it to other `Feedback*QuestionUiTest`, it's quite obvious this one stands out in terms of complexity and length. Oh, and the recent newcomer `FeedbackRankQuestionUiTest` too, so I'll rename the issue.
The issue is not about why rubric tests is tested by itself. It's about why there is a need to test anything more than adding/editing/customizing/deleting/validating new question frame (like all other `Feedback*QuestionUiTest`). The other actions tested (submit page and results page) are quite clearly coverable by their own UI tests simply by adding the desired question type to the data bundle used. (I'm gearing more towards option 2 I mentioned before as I hardly see the advantage of option 1)

**Comment by LowWeiLin** [comment]
There is a need to test how the question type is displayed on the different pages, such as submission form, results, statistics. (both student and instructor side)
Yes, it could be done for all question types in one location by using one data bundle (if that is what you mean?), but typical data bundle is already too messy/large, and there is no test currently that is meant to do just that.

**Comment by wkurniawan07** [comment]
Yes I understand the need for testing them, however can't they be done on `(Instructor/Student)Feedback(Submit/Results)PageUiTest`? Those tests are not using typical data bundle (in fact, _no_ UI tests are using typical data bundle), they have their own data bundles which can be added with all the stuffs we need.

**Comment by damithc** [comment]
Now that we have examples of both approaches, we can decide which way is better. We may add more question types in future and existing questions types will be made more customizable. So trying to test all question types for a particular action can result in increasingly big json/html files. That's why we wanted to try slicing tests by question types rather than action. When we have everything related to a particular question type separated out (not sure if it can be done though), it can be used as a boilerplate for adding more question types.

**Comment by wkurniawan07** [comment]
I'll add some historical context to this issue. In particular, on why `Feedback*QuestionUiTest`s appear.

It started out that `InstructorFeedbackEditPageUiTest` tests adding/deleting/customizing/validating for ALL question types in one go (along with all other tests in that page), and that resulted in a very long test (~4 mins in dev server). It was worsened by the fact that at that time this test had a quite high failure rate and each failure means the test has to be run again from scratch.

I'd like to believe that is the reason why when rubric question was introduced, `FeedbackRubricQuestionUiTest` stood on its own. It's a very reasonable approach.

Then I did #3282 (almost one year ago), which migrated a large bulk of that ~5 mins test to separate tests. This was where all the `Feedback*QuestionUiTest`s appeared, and also what made `FeedbackRubricQuestionUiTest` looks unnecessarily long compared to the others.

Why was the same not done for the submit/results page? It's all about testing efficiency.

1. In adding/deleting/customizing/validating question frame, the total time of all the actions can reach 15-20 secs per question (regardless of type, but each type has to be tested with one question). These actions can't be grouped as currently adding/editing/customizing/validating more than one question at a time is not supported.
2. In submitting, one extra question needs only 1-2 seconds of extra treatment (programmatically enter and submit the response), and the action can be grouped (i.e the new question can be treated immediately as long as it's in the same session). Moving it to `Feedback*QuestionUiTest` adds the hassle of needing to navigate to the submit page.
3. In viewing results, there's no extra operation from the user's part: the questions/responses in the bundle will be retrieved in the same amount of database query (although the data queried will be larger in size). Moving it to `Feedback*QuestionUiTest` adds the hassle of needing to navigate to the results page. To make it worse, results page have 5 types of view and testing it for _each_ question type is quite ridiculous (at 10 question types we'll easily have 5 * 10 = 50 test files).

And really this is why I'm inclined to option 2.

If this causes `Feedback*QuestionUiTest`s to "not do what they advertise", we can combine them all to make `InstructorFeedbackEditQuestionFrameUiTest`, separating each question type by `@Test`. It will work and still has the same benefit.

**Comment by damithc** [comment]
Well, i'm fine with whichever approach that gives us simpler code, can run tests in parallel, and faster (my priority is in that order). I'm not familiar with the code so not sure which approach fits that bill.

**Comment by thyageshm** [comment]
@wkurniawan07 could we put this one to V5.74?

**Comment by wkurniawan07** [comment]
As V7 radically simplifies (at least aims to) the E2E tests, this is no longer an issue.
