### ISSUE TITLE
Change name of css classes with '-for-test'

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#3601]
![fortestnaming](https://cloud.githubusercontent.com/assets/2216119/7951455/00b093c8-09da-11e5-865b-fb7d06be9d01.PNG)

Throughout various jsp files, such as in InstructorHome.jsp, instructorFeedbackResultsPage and instructorStudentList, there are css classes suffixed with 'for-test', as seen in the screenshot above. They should be renamed.

**Comment by junhaoyap** [comment]
Some elements do actually have it for a good reason, but perhaps we should rename them and not let them be '*-for-test'? Refer to attached screenshot.

Within the remind modal ->

![screen shot 2015-06-29 at 3 37 52 pm](https://cloud.githubusercontent.com/assets/6291947/8403194/d7f23798-1e74-11e5-83c7-883984be7bfb.png)

there is no other "handle" for Selenium to look for, or perhaps not classes but IDs?

**Comment by damithc** [comment]
Yes, renaming should improve it a bit.

**Comment by amarlearning** [comment]
@damithc would like to take this one.
Just want little more input on this issue :sweat_smile:

**Comment by damithc** [comment]
> Just want little more input on this issue

I'm not familiar with the issue myself. So, have to see if anyone else can give some input :-p

**Comment by kanghj** [comment]
If I recall correctly, the issue is that we had css classes that were there just to make it easy to locate some elements with Selenium. In many cases, there should be better alternatives to specify these elements.

**Comment by amarlearning** [comment]
@kanghj I think we should use `ID's` instead of `class` because they are the safest and fastest when it comes to locating element using selenium. 

Let me know your thoughts on this and I will start working on this PR.

**Comment by wkurniawan07** [comment]
I can't make a generalizing statement, but what @kanghj is true for at least some elements. Some classes might be used for styling, some for dynamic interaction with jquery, etc.
In any case, `-for-test` suffix is not a good name so regardless of the usage, any `*-for-test` should be renamed, at least to remove the `-for-test` suffix.

**Comment by amarlearning** [comment]
@wkurniawan07 should I change the `*-for-test` classes to Id's or simply just remove the `-for-test` from the classes?

**Comment by wkurniawan07** [comment]
@amarlearning the spirit of the issue itself is just changing the `*-for-test` class names to `*`.

**Comment by wkurniawan07** [comment]
V7 has no such selectors anymore.
