### ISSUE TITLE
Instructor: view results: sanitize csv data in html 

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#3622]
This allows the student to execute javascript on the instructor's results page if the instructor uses the modal. 

EDIT (by damith):
To replicate: Just submit a response with html content? You can load the csv data as a html modal on the instructor results page by clicking on "Non-English characters not displayed properly in the downloaded file? click here"

**Comment by bamboo3250** [comment]
it seems that the function csvToHtmlTable() in StringHelper.java doesn't apply sanitizeForHtml() for its data.

**Comment by bamboo3250** [comment]
@kanghj Could you tell me how to replicate this bug again?

**Comment by kanghj** [comment]
Just submit a response with html content?

**Comment by wkurniawan07** [comment]
Closing as the modal to show table has been deprecated.
