### ISSUE TITLE
student feedback submit: show 'to team members' question even when there are no team members

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#3661]
It may be more intuitive to show the question to the student if the recipient is 'team members' but the student does not have team members. However, student should not be able to submit responses and it should be clear to the student that the reason is because he/she does not have team members.

**Comment by tarun14110** [comment]
@damithc We also want to do like this for other recipients also ? Like, Feedback about `Other teams in the course` and there is only 1 Team. Feedback for  `Other students in the course` and there is only single student (may be this won't happen) ?

**Comment by damithc** [comment]
Yes, that would be good. Can do in the same PR or as separate PRs.
