### ISSUE TITLE
instructor feedback copy: should highlight copied sessions

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#3690]
When an instructor copy a session (by clicking the copy button in the home page), the resulting page should highlight the copied sessions.

**Comment by nidhi98gupta** [comment]
@damithc Sir, is this issue still open? Because on clicking the copy button, new dialog opens up.
![dialogbox](https://user-images.githubusercontent.com/24381442/36147324-ce932b54-10dd-11e8-8cb1-92951ab8fc0b.png)
If yes, then can you please point out what needs to be highlighted.

**Comment by damithc** [comment]
Issue no longer applicable.
