### ISSUE TITLE
Add feedback session button is not disabled for instructors without permissions for any course

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#3712]
If the course Id select is empty as a result of an instructor who has a course, but does not not permissions to add sessions to the course, the "Create feedback session" button is not disabled for the instructor, and this allows the instructor to be able to submit the form.

**Comment by damithc** [comment]
Meaning the user can create a session even if he doesn't have permission? or is it blocked by the backend?

**Comment by kanghj** [comment]
The backend will fail on an assumption, so the user can't create a session.
