### ISSUE TITLE
Move JavaScript events into the respective JavaScript files

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3770]
When they are separated from their HTML, it is much easier to look for them and know where they are, saves time debugging when things happen.

Additionally, maybe we can also consider removing HTML generation from JavaScript, has the same purpose as above, to separate them properly so we know where to look for what and not spend time looking for them only to notice that HTML is hidden in JavaScript and JavaScript is hidden in HTML.

**Comment by wkurniawan07** [comment]
This is essentially #6961.
