### ISSUE TITLE
Upgrade jQuery from v1.11.3 to v3.x

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3806]
To be done after #3799 in the future when IE8's market share has plunged even further, this will reduce the loading time of all of our pages since we use jQuery extensively.

To look at this issue again early 2016 and mid 2016.

**Comment by MrFool** [comment]
A side effect of this is we can also remove ->




once this is done.

**Comment by chowyb** [comment]
@damithc @wkurniawan07 might be worth looking at this issue again? Current market share for IE8 and below as of now, as taken from various sources:

From [netmarketshare](https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0), desktops, for June 2016:
IE8: 5.21%
IE7: 1.15%
Total: **6.36%**

From [W3Counter](https://www.w3counter.com/trends), desktops, for June 2016:
IE8: 0.5%
IE7: 0.4%
Total: **0.9%**

From [Clicky](https://clicky.com/marketshare/global/web-browsers/internet-explorer/), desktops, for 28 July 2016:
IE8: 0.31%
IE7: 0% (assumed to be included in "Others")
Total: **0.31%**

From [StatCounter](http://gs.statcounter.com/#desktop-browser_version-ww-monthly-201506-201606), **all platforms**, for June 2016 (via .csv file):
IE8: 2.02%
IE7: 0.08%
IE6: 0.09%
IE4: 0.01%
IE0(?): 0.06%
Total: **2.26%**

**Comment by damithc** [comment]
Do we have an 'unspported browser' check?

**Comment by damithc** [comment]
@chowyb yes we can take a look at this again now.

**Comment by wkurniawan07** [comment]
If anyone's looking at this issue, the current state-of-the-art jQuery is version 3.x (earliest release in June 2016, a good one year after this issue was opened).

**Comment by wkurniawan07** [comment]
No longer applicable in V7 (no more jQuery)
