### ISSUE TITLE
Create a new 'under maintenance' version

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#3810]
The purpose of this version is to block access for a short period in case we need to do a major maintenance. e.g. recover from a data corruption
It can be just a static webpage that we serve if any page of the webapp is requested. 

Most likely we need a `web.xml` that reroutes all requests to a `under-maintenance.html` page.

**Comment by MrFool** [comment]
Related to #3805, can look at it after JSTL is done

**Comment by MrFool** [comment]
Also, for this, we can do one with bootstrap stuff, one step forward in making non logged in and logged in both look similar.
