### ISSUE TITLE
Remove double disabled from InstructorFeedbacks Page elements

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3812]
Refer to #3807 for more details

We should also find a consistent way to do it so that in JavaScript we can be sure which way is the correct way to disable or enable elements correctly (i.e. whether .prop() or .addClass() / .removeClass()) should be used.

**Comment by MrFool** [comment]
Also, disabled="disabled" is for XHTML, we might want to use the HTML syntax of disabled if we so decide to use that.

**Comment by wkurniawan07** [comment]
Resolved in #4959. For details, we are consistently (at the point this is written) using `.prop()` for toggling boolean attributes.
