### ISSUE TITLE
Improve InstructorFeedbacks HTML Rendering

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3829]
![screen shot 2015-06-25 at 9 49 05 pm](https://cloud.githubusercontent.com/assets/6291947/8355812/0fc1121e-1b84-11e5-8a6a-0942ea7e4296.png)
![screen shot 2015-06-25 at 9 48 49 pm](https://cloud.githubusercontent.com/assets/6291947/8355813/0fed5658-1b84-11e5-9ec6-702d656c43bb.png)

Right now, this certain portion feels like it could be improved as it is possible that it is neither hasPublish or hasUnpublish and that might turn out to be really confusing as can be seen from the way the HTML is being generated.

Perhaps another variable can be introduced to make this more understandable, it might make it more verbose but it can help readability and maintanability.

**Comment by MrFool** [comment]
Perhaps a sort of boolean that signifies whether the session is still waiting to be open can be added to help with clarity? Any other ideas would help too.

**Comment by wkurniawan07** [comment]
Resolved in #4959.
