### ISSUE TITLE
Instructor: remind students: disable 'Remind' button if no student is selected

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3854]
![screen shot 2015-06-29 at 5 20 25 pm](https://cloud.githubusercontent.com/assets/6291947/8404898/42a8ec68-1e83-11e5-83a2-53b6a89f864f.png)

This is quite confusing for a new instructor, under sample course 201, I clicked on Remind Particular Students under Second Feedback Session, note that response rate is 0 / 0 and it showed me an empty modal but still allows me to click on "Remind".

Perhaps there is a better way to deal with when there is no one to remind?

It doesn't actually error out because if nothing is selected a status message pops up saying that no one has been selected but a new instructor would find this confusing and we should minimize such confusing encounters.

**Comment by damithc** [comment]
Yes, it is confusing and should be improved. How come demo course got 0/0?

**Comment by junhaoyap** [comment]
I'm not sure, perhaps it's got to do with me testing the copying of sessions here and there and not cleaning it up? We can look more into this issue when we're done with the JSTL :D

**Comment by damithc** [comment]
Suggestions: Disable the `Remind` button is no student is selected. Related #7065

**Comment by amarlearning** [comment]
I think this issue is resolved now. I cannot reproduce this.

**Comment by damithc** [comment]
Thanks for checking @amarlearning
