### ISSUE TITLE
Remove unnecessary line breaks at the bottom of mainContent div

### ISSUE THREAD

**Issue by yj-soh** [TEAMMATES/teammates#3866]
In most pages, the content within mainContent ends with anything from 0 to 3 or 4 `<br>`s.
This creates a gap of whitespace between the main content and the footer.
However, regardless of whether this is expected behaviour or not, it should be better to remove all of those and adjust that spacing accordingly using a `padding-bottom` or `margin-bottom` CSS attribute common to all pages.

Eventually, we should probably do likewise for the main text title present on most pages, and other like common tags, but those will be significantly easier after templating.

**Comment by junhaoyap** [comment]
Will help to standardize templating as well, never a good idea to use brs to introduce spacing in the long term.

**Comment by wkurniawan07** [comment]
Resolved in V7.
