### ISSUE TITLE
A wild 21 in the middle of feedbackResponseComments.js

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3875]
![screen shot 2015-07-03 at 5 21 47 pm](https://cloud.githubusercontent.com/assets/6291947/8496480/041de0d4-21a8-11e5-9d0f-ac0ec30bc2ba.png)

Thanks to @kanghj for pointing it out.

**Comment by wkurniawan07** [comment]
That's the length of the string 'responseCommentTable-' if I'm not mistaken.

**Comment by damithc** [comment]
Still, a magic string :-)

**Comment by wkurniawan07** [comment]
Magic string/number indeed, but replacing 21 with `"responseCommentTable-".length` isn't that much of an improvement either.
`responseCommentTable-` comes from some div id, btw.

**Comment by damithc** [comment]
It is still better than 21. At least it shows how 21 was computed.

**Comment by sujeet14108** [comment]
Do we just have to  replacing 21 with "responseCommentTable-".length to solve this or something more is needed?

**Comment by damithc** [comment]
I think that should be enough @sujeet14108. Any comments @wkurniawan07 ?

**Comment by yj-soh** [comment]
As JavaScript isn't compiled, I would recommend putting it as a comment instead.

Alternatively and hopefully, alter the markup and find a way to identify those elements properly.
If that code is still unchanged from that screenshot, honestly, using `parent()` 17 times in that segment alone isn't very helpful for anyone reading it.

**Comment by junhaoyap** [comment]
I just had a random thought, if substring always returns the same value ```responseCommentTable``` as a string, wouldn't using a string be much more obvious than selecting it from somewhere and doing a ```.substring(x)```?
