### ISSUE TITLE
Document's ready event handler should be near the top for feedbackResponseComments.js

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3879]
It's better to have all document ready event to be at the top or near the top for all our JavaScript files. 

Currently, for e.g. in feedbackResponseComments.js the document's ready event handler is hidden in the middle. 

Because of that, there are some JavaScript files where we have multiple document ready event handler attached, that can be confusing. It would be much more maintainable and be less error prone if we have all of them at the top of each JavaScript file and we instantly know where to look for them instead of accidentally defining a new one.

On some files even, we have $(document).ready inside window.onload and also sometimes body.onload. The ready event fires before the onload event so that can be confusing and also unnecessary.

**Comment by wkurniawan07** [comment]
Achieved in #6137.
