### ISSUE TITLE
Merge all 4 instructor pages search components into one

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3889]
Also display the differences based on the page we are currently in instead of needlessly repeating ourselves.

**Comment by wkurniawan07** [comment]
Finally, you get why I'm taking all the trouble to standardize comments and stuffs :+1::+1:

**Comment by thyageshm** [comment]
@wkurniawan07 any updates?

**Comment by wkurniawan07** [comment]
I've had my hands full for 5.73, so putting this to the next milestone.

**Comment by wkurniawan07** [comment]
There are only 2 search bars for very different purposes now; not warrant the abstraction anymore
