### ISSUE TITLE
Unused parameters in toggleSendRegistrationKey() for instructorCourseDetails

### ISSUE THREAD

**Issue by yj-soh** [TEAMMATES/teammates#3895]
```
function toggleSendRegistrationKey(courseID, email) {
    return confirm("Usually, there is no need to use this feature because TEAMMATES " 
                   + "sends an automatic invite to students at the opening time of each" 
                   + " session. Send a join request anyway?");
}
```
Is it supposed to use the course id and email somehow?
Or should the parameters be removed?
At the moment, it is being called without passing any parameters in.

![sendinvite](https://cloud.githubusercontent.com/assets/8586080/8540666/6a38a47a-24ba-11e5-8bbe-31afa4a77c3a.png)
It corresponds to the "Send Invite" button on the course details page.

**Comment by bamboo3250** [comment]
Maybe add forFirstTimers tag for this issue?

**Comment by samatdav** [comment]
I decided to fix this old issue as a FirstTimer. Hope I followed the PR procedure correctly :-)
