### ISSUE TITLE
InstructorFeedbacks: tooltip for private sessions should explain what a private session is

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#3899]
Or provide a link to the help page on private sessions. It can be confusing to new users especially since clicking on the option for private session causes many of the other options to abruptly vanish.

**Comment by junhaoyap** [comment]
@ngzhian Might want to take a look at this, can help to learn the code base.

**Comment by ngzhian** [comment]
Here's what the tooltip says right now:
```
Select this option if you want the feedback session to never be visible. Use this option if you want to use this as a private feedback session.
```
I propose we tweak the wording of the tooltip slightly, and also beside the text "Never (this is a private session)", add a link to the a page with more details on the sessions.

Suggested tweak:
Remove "(this is a private session)" from the label, and change the tooltip to
```
Select this option if you want the feedback session to be private. A private session is never visible to anyone.
```

Also: I cannot find any page with details explaining what a private session is, just `instructorHelp.html#fbSetupSession`, is that okay? Should we write down more details about private sessions in that document?

**Comment by damithc** [comment]
Yes we should add more details about private sessions to the help page.

**Comment by PSNAppz** [comment]
@kanghj I would like to work on this issue.
Should I change the tooltip shown on every page to the above suggested one? or is there anything else to do?

**Comment by kanghj** [comment]
Yes, we can go with what was suggested and discuss further when you make a pull request. You can add more details to the help page too.

**Comment by sznicci** [comment]
Hi,
I have been working on this issue and I have a fix, but for the test cases I should rewrite about 180 .html files. I was thinking doing this with a python script.
My question is, do you have any usual way of doing this or is it fine with a python script?

**Comment by wkurniawan07** [comment]
@sznicci [this](https://github.com/TEAMMATES/teammates/blob/master/docs/godmode.md) should answer your question.

**Comment by sznicci** [comment]
Thank you @wkurniawan07 the link!
I read the documentation and I could solve the problem. I am going to make a PR soon.
