### ISSUE TITLE
Instructor: edit rubric question: allow moving columns

### ISSUE THREAD

**Issue by taniach** [TEAMMATES/teammates#3910]
An instructor should be able to add a column and place it in between existing columns by dragging and dropping the column in the correct place. The new blank column is added to the right. Currently, the instructor has to cut and paste existing column contents to shift them to the right.

<img width="1158" alt="screen shot 2015-07-08 at 2 39 20 pm" src="https://cloud.githubusercontent.com/assets/7547452/8564487/2cf58c66-257f-11e5-9965-c89e79e7346a.png">

**Comment by VamsiSangam** [comment]
Working on this.

**Comment by VamsiSangam** [comment]
Can I assume that the first column (one with option description) is not supposed to be draggable?

**Comment by chowyb** [comment]
@damithc can probably weigh in on this better, but from what I understand, the first column should not be draggable, and only the columns with headers ("Strongly Agree", "Agree" etc. in the screenshot) should be draggable.

**Comment by damithc** [comment]
> @damithc can probably weigh in on this better, but from what I understand, the first column should not be draggable, and only the columns with headers ("Strongly Agree", "Agree" etc. in the screenshot) should be draggable.

Yes, that's right. In fact, may be easier (especially when writing test cases) to provide `move left` and `move right` buttons of each columns rather than dragging?

**Comment by VamsiSangam** [comment]
> provide move left and move right buttons of each columns rather than dragging?

I was looking at various dragging libraries till now :stuck_out_tongue_closed_eyes: . If you don't even want to drag the columns and have buttons instead, then I can forget about those libraries and write my own JS to swap the contents on columns (or something similar to that) on button clicks. That way is much simpler for me to do things and write tests as well. :v:  Should I proceed with this approach?

**Comment by damithc** [comment]
> Should I proceed with this approach?

Yes @VamsiSangam, go ahead.
