### ISSUE TITLE
Missing space in confirmation message for archiving courses

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#3914]
![archivemsg](https://cloud.githubusercontent.com/assets/2216119/8564967/b60c7b50-2583-11e5-8805-4083b18222bb.PNG)

"revertedby" -> "reverted by"

**Comment by srajat** [comment]
@damithc Thanks for pointing me in the right direction sir. Can i solve this issue then?

**Comment by damithc** [comment]
Go ahead and submit a PR.
