### ISSUE TITLE
Instructor: search: Allow searching feedback responses, questions

### ISSUE THREAD

**Issue by taniach** [TEAMMATES/teammates#3918]
Currently, it allows searching for feedback response comments but not feedback responses.

**Comment by eei34** [comment]
@damithc @LiHaoTan  Currently the instructor search page allows for searching of responses, questions, and comments. When selecting the "Comments for responses" checkbox, the results include keywords of responses, questions, and comments. Should the checkbox be renamed to "Feedback" with a tooltip explaining the results or should search results be implemented to include specifically responses, comments, or questions?

**Comment by damithc** [comment]
> When selecting the "Comments for responses" checkbox, the results include keywords of responses, questions, and comments.

I wasn't aware of this behavior. Is that correct? I thought it searches comments on responses only, not the responses themselves.

**Comment by damithc** [comment]
Closing this. Will create a new issue for renaming the tick box.

**Comment by nidhi98gupta** [comment]
@damithc This issue is still valid. Currently search feature only allows searching for feedback response comments.

>  When selecting the "Comments for responses" checkbox, the results include keywords of responses, questions, and comments

That's because comment docs have these fields.

Although search checkbox has been renamed but if a question/response has no comment on it then it is not searchable.

**Comment by damithc** [comment]
> Although search checkbox has been renamed but if a question/response has no comment on it then it is not searchable.

I see. reopening.

**Comment by Rishabh-Bajpai-Hub** [comment]
Can you confirm this is still an issue?.
