### ISSUE TITLE
Panel not intuitively 'clickable' in Instructor Comments Page

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3921]
The panels do not have an arrow on the right or anything to indicate that it is clickable for it to expand and load the comments, we could add something to indicate so that users (especially new ones) will know that it can be clicked.

**Comment by chowyb** [comment]
Hi, just checking if this is still an issue, as the panels "Comments for students" and "Comments in session: ..." seem to have arrows already.

**Comment by damithc** [comment]
Yes, seems to be fixed now.
