### ISSUE TITLE
The function isBlank in multiple JavaScript files can be simplified

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3922]
![screen shot 2015-07-08 at 4 47 14 pm](https://cloud.githubusercontent.com/assets/6291947/8566489/03ed68ae-2591-11e5-8247-e450010a8336.png)

Regex can be slow, not everyone understands regex (I don't, yet) and the check can be as simple as

str.trim() === "", we don't need to add an extra layer of function to do that particular check

**Comment by wkurniawan07** [comment]
I did a search on the workspace, apparently this method is stolen from `typeahead.bundle.min.js`. :stuck_out_tongue:

**Comment by damithc** [comment]
Any benefit of regex check over the simpler comparison?

**Comment by wkurniawan07** [comment]
Referring to [this doc](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/trim), this is how `trim` is defined:
```
return this.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g, '');
```
So `trim` itself is using regex, but the implementation is hidden from us (which can be a good or a bad thing).
`str.trim() === ""` does look simpler, though.

**Comment by damithc** [comment]
OK then, we'll go for the simpler one.

**Comment by wkurniawan07** [comment]
I just tried something. The regex method can handle things like:
```
isBlank(0) // true
isBlank(123) // false
isBlank(true) // false
```
Whereas the trim method will throw errors on the above three cases.
Proper usage of the method won't require us to handle those cases, but in JS where variables are untyped, we may need some sort of protection against such misuses. Should we keep the regex method?

**Comment by Gisonrg** [comment]
Do you think it's a good idea that we also test if the given input is a String? If it is not a string then the method will return false. In that way we could prevent misuses, and the trim() method could be used as well :P

**Comment by wkurniawan07** [comment]
Oops sorry I somehow missed this! @Gisonrg yeah sure, that's one way to deal with it. You wanna work on it? Btw, if you haven't done one `d.FirstTimers` issue before, you should do one of those first.

**Comment by Gisonrg** [comment]
@wkurniawan07 Yea sure I can work on this one.
I will do one `d.FirstTimers` on weekend. Quite busy this week :smile:

**Comment by wkurniawan07** [comment]
Suit yourself bro :+1: Just submit PRs when you're done. Remember to follow the workflow as specified [here](https://github.com/TEAMMATES/teammates/blob/master/devdocs/process.md).
