### ISSUE TITLE
Change Instructor Comments pagination display

### ISSUE THREAD

**Issue by taniach** [TEAMMATES/teammates#3929]
<img width="1184" alt="screen shot 2015-07-09 at 12 43 02 pm" src="https://cloud.githubusercontent.com/assets/7547452/8588098/2ce95a90-2638-11e5-93cc-b51e5b533608.png">

The alignment looks a bit off if there are many courses. One way to improve would be to show at most a specific number of courses at a time and show more if the user clicks. 

<< (First) < (Previous) 1 2 3 4 5  > (Next) >> (Last)

When the instructor clicks next,

<< (First) < (Previous) 2 3 4 5 6  > (Next) >> (Last)

**Comment by JosephineKwa** [comment]
I will work on the pagination standardization between student comments and instructor comments here too

**Comment by JosephineKwa** [comment]
Would a dropdown menu be more suitable? In cases where instructors have 100+ courses, they might have to keep clicking next in order to go the the page they want

**Comment by taniach** [comment]
A dropdown will be good.

**Comment by thyageshm** [comment]
@JosephineKwa reminder about this issue
