### ISSUE TITLE
Separate JavaScript constants into a Const object

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3975]
var const = {
    // so on and so forth
}
1. Reduces the pollution of the global namespace
2. Faster too because there will be less scope resolutions
3. More maintainable, we should have a const.js file instead of dumping them into common.js, common.js contains too much things at the moment

**Comment by junhaoyap** [comment]
We could also use self-invoking functions and pass the window in, like suggested in #3978 to allow strict mode as well.

**Comment by RatulGhosh** [comment]
Should I create a new js file containing all the constants or should I move those constants to the respective js files that uses them.

**Comment by junhaoyap** [comment]
In view of preparation for migration to ES6, cc @li-kai, we can consider using constants instead of our current I_AM_A_CONSTANT convention and it guarantees immutability

**Comment by wkurniawan07** [comment]
No longer relevant in V7
