### ISSUE TITLE
Move utility functions in common.js into a util object

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3978]
We can do it like below:

(function(window) {
'use strict';
var util = {
add: function(a, b) {
return a + b;
}
}

window.util = util;
})(window));

Reduces global namespace pollution and allows for enabling strict mode.

**Comment by AnaghHegde** [comment]
@junhaoyap Just to confirm when you meant like JSON obj right  ?

```
var util = {

       functionname : function(){

        } ,
       functionname : function(){

        }
}
```
 and later use it in this way  `util.functionname()` .

**Comment by AnaghHegde** [comment]
@junhaoyap just to be clear you are talking about self invoking functions inside `util object` right ?.

**Comment by wkurniawan07** [comment]
Something even better has been done: broken up into modules.
