### ISSUE TITLE
property files created via copying templates aren't updated

### ISSUE THREAD

**Issue by ngzhian** [TEAMMATES/teammates#3980]
For example, when `test.template.properties` is updated, `test.properties` will not have those values.
Found this while running test cases and discovering some errors because I didn't have `test.timeout` in my `test.properties`.
Wondering if there's a way to do this using 2 levels of properties, e.g. a default `test.properties` that is checked into source, and a per-developer `test.local.properties` that can can specify values that overrides those in `test.properties`.

**Comment by damithc** [comment]
Good point. Splitting into two files don't solve the problem entirely though. besides, I think most of our properties need changing, if not for dev testing, for staging testing. Another approach is to detect missing properties (e.g. when loading properties) and inform the developer to add the missing properties.

**Comment by ngzhian** [comment]
What I mean is that: we have 2 files `test.properties` (checked into source) and `test.local.properties` (not checked in). Any new property is added to `test.properties`.
When we read in properties we will read in `test.properties` first, then `test.local.properties` (if available). Any property defined in `test.local.properties` will override the one in `test.properties`.
E.g.
```
// in test.properties
test.timeout=15
test.timeout_long=20
```
```
// in test.local.properties
test.timeout=30
```
`test.timeout_long=20` is a new property and since it was checked into source control, all developers get it. When running tests that references `test.timeout_long`, in the suggested way of loading, what a user will get is
```
test.timeout=30 // test.local.properties overrides test.properties
test.timeout_long=20 // from test.properties
```
instead of currently where you will get errors running the test cases because `test.timeout_long` isn't defined.

The other solution can be done as well. We can probably check for a missing property in the constructor for `TestProperties`? But how do we tell if a property can be `null` or not? Are all properties supposed to be non-null? For this I defer to the core team.

**Comment by wkurniawan07** [comment]
If you want to try the other solution, we have `TestPropertiesTest`, which hasn't been touched since forever. You can use this opportunity to get that test back up to date!

**Comment by damithc** [comment]
The suggested approach of overriding defaults with locally defined values
does not require two properties files. We can define the default in the
code itself and override the default if it is in the properties file.
However, we are back to square one when we add a new property that *must*
be overridden. In those cases we have to inform developers to update the
properties file, just like how we do now. Still, such properties may be
rare, so the suggestion is worth considering.
