### ISSUE TITLE
Instructor search displays more results than it should

### ISSUE THREAD

**Issue by taniach** [TEAMMATES/teammates#3985]
<img width="1158" alt="screen shot 2015-07-15 at 5 57 29 pm" src="https://cloud.githubusercontent.com/assets/7547452/8695942/1614b188-2b1b-11e5-89f5-95883c2c7e86.png">

Searching for one student's email should not display the other students.

**Comment by kai33** [comment]
because dot and @ are treated as space, so it becomes an OR search for keywords "alice b tmms gmail tmt".
Then the other students are also shown

**Comment by damithc** [comment]
Any workaround?

**Comment by rclakmal** [comment]
@damithc @taniach What if we skip the `sanitizeForSearch` after checking whether the search text is **only an email**  & nothing else ?
