### ISSUE TITLE
The method joinParticipantTypes belongs to a util class

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3994]
`InstructorFeedbackResponseCommentAddAction.java`
private String joinParticipantTypes(List<FeedbackParticipantType> participants, String joiner) {
// so on and so forth
}

It can be and will be used in different places.

**Comment by junhaoyap** [comment]
It should also be named "delimiter" and not "joiner"

**Comment by chen-zhuo** [comment]
Where should we move this method to? I am thinking of moving it to `Utils.java`. Is it okay? If yes, I will proceed to create a PR.

**Comment by junhaoyap** [comment]
Sounds good - I saw the pull request it looks ok too, thanks!
