### ISSUE TITLE
Input element's checked attribute does not follow HTML standards

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3997]
As per http://www.w3schools.com/tags/att_input_checked.asp, it should be simply checked and not checked="checked" unless we are following XHTML standards.

**Comment by kanghj** [comment]
We might need to update the html style guide. https://docs.google.com/document/d/12PJYbQoqjK-0LzaUuguQ4kGE--eikCcHfwzZDGwFOJ0/pub?embedded=true

See the section under attributes

**Comment by junhaoyap** [comment]
Not sure if attr="attr" was done on purpose for some compatibility issue? Maybe we can ask whoever wrote the google docs, perhaps it was done with a purpose and if so we can close the issue and know why at the same time.

**Comment by damithc** [comment]
I think this was written by Chun Teck long ago. We should add references to that doc so that we know where these guidelines came from. Anyway, anything you can find about that specific guideline based on other html guidelines out there?

**Comment by junhaoyap** [comment]
After looking around, it seems that there is no "one way to rule them all", the best practise is to adhere to what we need and want to do.

If we are intending to adhere to XHTML (I'm not sure if we do, do we?) then we MUST use checked="checked" as that is the only way for it to be a valid XHTML document. However, if we do not need / want to adhere to XHTML, in HTML just checked is good enough.

I guess it ultimately depends on that, whether we want to adhere to XHTML. However, I'm not quite sure what the benefits / downsides are for adhering to XHTML or not.

**Comment by damithc** [comment]
We need to research pros/cons, decide which one to follow, and document it so that next time we don't have to go through this again :-)

**Comment by wkurniawan07** [comment]
Let's do this. Since our stand in "not using XHTML" is clear, we should be consistent, i.e no checked="checked".
That aside, the HTML style guide is severely outdated. And poorly enforced as well (how many variations of naming conventions are there in the wild?).

**Comment by thyageshm** [comment]
@wkurniawan07 reminder about this issue
