### ISSUE TITLE
Use delegated events for jQuery events

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3998]
Currently we are attaching direct event handlers and also using AJAX to dynamically add elements, it gets harder and harder to maintain if we constantly need to attach event handlers every time we dynamically add elements.

Some stuff that are could happen / already are happening:
1. Certain elements have too many of the same event handlers (but different function objects) being attached.
2. Elements may miss having some event handlers attached because we are attaching direct event handlers to them via helper functions (what if we forget to run one helper function and the Selenium test does not cover those content for example?)

If we use delegated events, all existing elements and dynamically loaded elements will all have the said event. This reduces the possibility of faults and also increases performance since up to x number of elements can all reference to one function object rather than having one function object for every element.

**Comment by wkurniawan07** [comment]
No longer applicable in V7 (no more jQuery).
