### ISSUE TITLE
Sorting of private sessions may cause an error

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#4001]
When creating a new private feedback session, if the start time input field was cleared before making the feedback session private, the feedback session is created with start time == null. This causes an error during sorting of feedback sessions due to the lines:

<code>Assumption.assertNotNull(session1.getSessionStartTime());</code>

and 

<code>Assumption.assertNotNull(session2.getSessionStartTime());</code>

This affects InstructorStudentRecords and StudentComments

[Edit] the comparators are in <code>SessionAttributes.java</code>

**Comment by damithc** [comment]
Not relevant anymore as we are hoping to remove support for private sessions.
