### ISSUE TITLE
Instructor: enroll students: prevent double enrolling caused by eventual persistence

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4024]
If the instructor enrols twice quickly, it can result in double enrolment.

**Comment by xpdavid** [comment]
Google is going to migrate Datastore to "FireStore" which will remove the "eventual-consistency" thing:
https://cloud.google.com/datastore/docs/upgrade-to-firestore (Happened in 2021)

**Comment by wkurniawan07** [comment]
Close as Datastore or rather Firestore in Datastore mode is no longer eventually consistent.
