### ISSUE TITLE
Instructor: add instructor: 'display to students as' textbox should be enabled only if the checkbox is checked

### ISSUE THREAD

**Issue by taniach** [TEAMMATES/teammates#4043]
<img width="1164" alt="screen shot 2015-07-30 at 5 16 49 pm" src="https://cloud.githubusercontent.com/assets/7547452/8979796/cc51f5b8-36de-11e5-91e4-890cbb31f27f.png">

If the checkbox is not checked, the textbox should be disabled. Currently, it is always enabled.

The default value after adding a new instructor is 'Instructor' if the checkbox is checked and the textbox is empty. Suggestion: Load the page with the checkbox unchecked and a disabled textbox containing the value 'Instructor'. The examples (e.g co-lecturer, teaching assistant) can be given in the tooltip.

**Comment by damithc** [comment]
The more common case is to display to user. Hidden instructors are rare. So default should cater for the common case.

**Comment by taniach** [comment]
Then we can have a textbox with the value 'Instructor' inside since it is the default. Blank textbox changing to 'Instructor' on submit seems misleading.

**Comment by HirdayGupta** [comment]
Hi @amarlearning! Didn't know you were working on this! 😅 

I had some code ready to go that takes a different approach to this issue (taking into consideration the follow up comments made by@damithc and @taniach). Submitting the PR to see what devs have to say! 😃
