### ISSUE TITLE
"For measuring failure rate: user tried to copy session to multiple courses" spotted

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4059]
This was inserted into the code to measure failure rate. It happened a few times, for a use who has 100 over courses. Anything we need to do?

**Comment by kanghj** [comment]
Perhaps we can add some simple javascript validation to check if the user copied the feedback session with the same name to the original course? 

Or we can make the form submission by ajax instead, so after the user receives the error message without his form fields resetting.

**Comment by damithc** [comment]
So this happens if the user tries to copy the session to the same course?
It happened a few times since the original post.

**Comment by kanghj** [comment]
Yes, it happens if the feedback session is copied to a course that already has a feedback session with the same name.

**Comment by damithc** [comment]
The javascript validation seems easier, as long as we can cover it adequately in tests.

**Comment by damithc** [comment]
Happened a few more times today.

**Comment by damithc** [comment]
Happening more.

**Comment by damithc** [comment]
Happening quite regularly, about once a day.

**Comment by damithc** [comment]
Still happening.

**Comment by kanghj** [comment]
I'll submit a pull request for this in the next milestone
