### ISSUE TITLE
Remove unused jsp files

### ISSUE THREAD

**Issue by taniach** [TEAMMATES/teammates#4106]
Not being used anymore because they were converted to tags:
* adminHeader.jsp
* instructorHeader.jsp
* statusMessage.jsp
* statusMessageWithoutFocusingToStatus.jsp
* studentHeader.jsp

**Comment by SambitAcharya** [comment]
@taniach please assign this to me.

**Comment by taniach** [comment]
Hi Sambit. You can start working on the issue and submit a pull request when you finish.

**Comment by thyageshm** [comment]
@SambitAcharya please make sure that you only work on ONE `d.FirstTimers` issue

**Comment by SambitAcharya** [comment]
@thyageshm ok. I will work on this one.

**Comment by SambitAcharya** [comment]
@taniach please review https://github.com/TEAMMATES/teammates/pull/4786

**Comment by thyageshm** [comment]
@SambitAcharya please open another pr since the last one was closed since it did not conform to our process. Please refer to our [process document](/TEAMMATES/teammates/blob/master/devdocs/process.md) regarding naming PRs as well as the first comment.

**Comment by mt10589** [comment]
@taniach I would like to work on this.
