### ISSUE TITLE
Text overflow in statusMessage panel in adminHomePage

### ISSUE THREAD

**Issue by chen-zhuo** [TEAMMATES/teammates#4112]
![text overflow](https://cloud.githubusercontent.com/assets/10667091/9120300/12a704f2-3cae-11e5-87f3-d03422cbde0a.png)

As shown above, there is text overflow in statusMessage panel showing the join link in adminHomePage, when trying to add a new instructor.

**Comment by damithc** [comment]
Low priority because only the admin sees this page and it's purely cosmetic. But thanks for reporting :-)

**Comment by damithc** [comment]
Closing in favor of #6900
