### ISSUE TITLE
FeedbackResponsesDb: inconsistent behaviour between getFeedbackResponseEntitiesForSessionInSection and getFeedbackResponseEntitiesForQuestionInSection

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#4125]
It is unclear what "In Section" should mean. <code>getFeedbackResponseEntitiesForQuestionInSection</code> only includes responses within the section (from and to the specified section), but <code>getFeedbackResponseEntitiesForSessionInSection</code> includes responses given from the specified section to other sections, and from other sections to the specified section.

**Comment by wkurniawan07** [comment]
The behaviour is consistent in V7.
