### ISSUE TITLE
Rename instructorFeedbackResultsAjaxResponseRate.js

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/teammates#4127]
No longer only used for response rate, after #4122 is done.
Rename the classes .ajax_response_rate_submit and .ajax_response_rate_auto as well.

**Comment by mt10589** [comment]
@LowWeiLin as they are no longer used, does this mean to remove these files?

**Comment by LowWeiLin** [comment]
No, they are still used, but have to be renamed.

**Comment by damithc** [comment]
@LowWeiLin can this be at `d.Contributors` level?

**Comment by LowWeiLin** [comment]
It requires looking through the code, but contributors should be able to do it.

**Comment by nsaiisasidhar** [comment]
Hi, can you please let me know what the target names should be for the JS file and the two CSS classes above.
