### ISSUE TITLE
Instructor: add courses/sessions: give more specific error messages when a field is empty

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4129]
For example, instead of giving this as the error message,
"" is not acceptable to TEAMMATES as feedback session name because it is empty. The value of feedback session name should be no longer than 38 characters. It should not be empty

We can be direct and say the field cannot be empty.

**Comment by Siddhant085** [comment]
Can I work on this one?

**Comment by kanghj** [comment]
Sure, go ahead. Submit a pull request when you are done.

**Comment by Siddhant085** [comment]
The current error message is coming from a InvalidParametersException in the InstructorFeedbackAddAction.java file. A solution to give a simple status message is to make a javascript function and do client side verification of the session name and time.

**Comment by Siddhant085** [comment]
The status message is coming from an InvalidParameterException. I think using java script to do user side verification and showing appropriate message would be a better way of solving the issue.

**Comment by damithc** [comment]
We prefer server-side validation to avoid duplication.

**Comment by Siddhant085** [comment]
Is the change fine?
![screenshot](https://cloud.githubusercontent.com/assets/11002537/9392246/3b572e40-4799-11e5-847c-668792360261.jpg)

**Comment by junhaoyap** [comment]
The first letter should be capitalized if possible.

**Comment by Siddhant085** [comment]
It is a field name so wouldn't prefer changing it, see if this one is fine.
![screenshot](https://cloud.githubusercontent.com/assets/11002537/9392484/ad16ae74-479a-11e5-834f-80d42fdd9f74.jpg)

**Comment by junhaoyap** [comment]
I'll let @damithc confirm it, but it should be "... cannot be empty" without the "is".

**Comment by damithc** [comment]
In addition to removing 'is', may be show the field name in a different
way? e.g. italized or bold
We should use the same name used in the form. i.e. session name

**Comment by Siddhant085** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/11002537/9410241/c9ca11d0-483c-11e5-907a-5cd1a3ae3614.jpg)

**Comment by damithc** [comment]
Can you tweak a bit more, as follows?
 'The field session name cannot be empty. It cannot be longer than 38
characters'.

**Comment by Siddhant085** [comment]
Sir the value is empty is contained within a variable REASON_EMPTY this variable is also used in error messages for other empty fields like course name. Therefore changing the value of REASON_EMPTY from "is empty" to "empty" will require me to change the error messages for all the other fields also.

**Comment by damithc** [comment]
I see. In that case, keep it as it is and submit a PR. The code reviewer will be able advise further.

**Comment by Siddhant085** [comment]
In class FieldValidator most of the field name variables have an article with them in the field name, can we get the article removed from the variable and get them added to the error message.
![1](https://cloud.githubusercontent.com/assets/11002537/9423366/b11d0e7e-48de-11e5-9784-23d601203d19.jpg)
![2](https://cloud.githubusercontent.com/assets/11002537/9423368/be5179cc-48de-11e5-9aff-f5ebf343f3a1.jpg)

**Comment by kanghj** [comment]
Is there a reason why that will be better? If it's not related to this issue, you can make an issue for that for further discussion. For this issue, it might be better if you make a pull request with the changes that you have made, so any discussion can be made with reference to your code.

**Comment by amarlearning** [comment]
Taking this one
