### ISSUE TITLE
Create separate panels for multiple status messages of different colours

### ISSUE THREAD

**Issue by taniach** [TEAMMATES/teammates#4147]
Pass status message objects separately to statusMessage.tag instead of using requestScope
Solves the problem of precedence (e.g. one message for success and one message for warning on the same page)

**Comment by thyageshm** [comment]
@taniach if it is possible, could you give some updates on this? If you won't have time to work on this, we shall look into assigning it to someone else as this has been open for a very long time now.

**Comment by taniach** [comment]
This issue involves a significant number of changes. I may not be able to finish it sometime soon so we can let someone else work on it now.
