### ISSUE TITLE
Attach sources and javadocs to external libraries used by the project

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#419]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on December 11, 2012 20:20:11_

These are needed for Eclipse to show information about the APIs we use from those libraries.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=420_

**Comment by wkurniawan07** [comment]
Achieved via Gradle.
