### ISSUE TITLE
When editing a fresh 'custom' instructor, first section is automatically selected

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4192]
No section should be ticked by default, but it seems the first section is ticked automatically.
![image](https://cloud.githubusercontent.com/assets/1673303/9560509/14e3c400-4e4a-11e5-93d8-211134877f94.png)

**Comment by srajat** [comment]
Please assign me this task and point out from where this page is generated. Thanks.

**Comment by damithc** [comment]
@srajat if you are a new contributor looking for an issue to fix, I suggest you start with an issue labelled d.FirstTimers. Please refer to the 'Contributor Orientation Guide (link given in our [project home page](https://github.com/TEAMMATES/teammates)) for more guidance on how to get started.

**Comment by chowyb** [comment]
Upon further analysis, the boxes appear to be checked in a manner such that the first group has the first section automatically selected, and the second group has the second section automatically selected. This pattern continues until there are n groups, where n is the number of sections in the course, upon which no further groups can be created. An example of this is shown below:

![section](https://cloud.githubusercontent.com/assets/7546744/15103822/c06850f6-15e2-11e6-98fd-728fcbf04815.png)

This may be of use if an instructor wishes to customize section permissions one by one, although admittedly this may not be the most common use case for this feature. As such, I would like to confirm if this issue still needs to be resolved.

**Comment by damithc** [comment]
Yes, I prefer not to auto-select any sections. The current behavior does not fit my usage of custom permissions.
