### ISSUE TITLE
Error: Bad request

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4219]
This seem to happen to some users now and then, and usually goes away after a while.

![image](https://cloud.githubusercontent.com/assets/1673303/9619687/2288be28-5145-11e5-8803-b62372cc9867.png)

**Comment by damithc** [comment]
Getting more of these. raising pirority.

**Comment by kanghj** [comment]
Does this only happen on login, or is there any particular page the users are trying to access?

**Comment by damithc** [comment]
Seems to be related to the unique links we send. Users encounter this when
they click on that link.

**Comment by thyageshm** [comment]
sir could we have one of the links that resulted in this error?

**Comment by damithc** [comment]
Here's one, but slightly modified to protect the user data
http://teammatesv4.appspot.com/page/studentFeedbackResultsPage?courseid=MGT4001W1-Fall2015&fsname=Practice+Peer+Evaluation&key=321CEDDB2E31655D8616C352B81A1C7D322F6D73156D620837CE1C625AFA0CAAEEE05956F1005A95A75D1F9CE707EF0FAAF8C8D3733A50182BA805335714C19B&studentemail=abcd%40gmail.com

**Comment by thyageshm** [comment]
question: is the problem a persistent one or a transient one? That is, does it get solved over time or did we have to generate another link for them?

Another question: If we generated another link, was the email address different or the same the second time around?

**Comment by kai33** [comment]
FYI,
this issue is very similar to this one:
https://code.google.com/p/googleappengine/issues/detail?id=11681

1. direct cause: the re-direct URL (controlled by GAE, that /_ah/conflogin?state=...) is too long (> max 2048 chars), so GAE responds with a bad request.
2. possible root causes: the user may login with multiple accounts, which will result in a longer re-direct URL. I saw a post that said if login with only one account, it can pass (shortened the re-direct URL). I'm also afraid that maybe the key is too long (not sure for this one though)?

**Comment by damithc** [comment]
Can anybody confirm that this is caused by multiple account logins?

**Comment by kanghj** [comment]
@yj-soh tried logging in with 5 or 6 accounts and it works

**Comment by damithc** [comment]
There is a steady stream of support requests because of this (e.g. 1-2 requests per week). It might not happen to everyone who has multiple requests, but when it does happen, it seems to be due to multiple requests.

**Comment by LowWeiLin** [comment]
Do you mean multiple accounts?
Doe it work when they log out of some accounts, or use incognito mode to log in?

**Comment by damithc** [comment]
Yes, multiple accounts. My advice to those users was to 'logout of all Google accounts except one or use a different browser' and none of them got back to me (so I assume it worked).

**Comment by wkurniawan07** [comment]
Does this still happen?

**Comment by damithc** [comment]
Yes, I do get emails about this error now and then, but not very frequent.

**Comment by damithc** [comment]
No recurrence in the past few months. Closing.
