### ISSUE TITLE
Incorrect highlighting for question panels with empty responses in sessions with many responses

### ISSUE THREAD

**Issue by ashrayjain** [TEAMMATES/teammates#4251]
Related to #4145 
I ran across this issue in one of the existing test cases, namely testViewPhotoAndAjaxForLargeScaledSession

The issue here is that all the responses are loaded via AJAX, but on demand rather than automatically on page load. On page load, all the questions have empty responses. These are filled up when the user clicks on the respective question.

The code that fixes #4145 needs the response content before it can determine that the response is empty, and change the panel to grey.

Right now, the panel is only turned grey when the user clicks on an empty question, which defeats the purpose.

**Comment by damithc** [comment]
No longer relevant.
