### ISSUE TITLE
Allow moderating values on behalf of instructors

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4274]
Sometimes, we need to modify values entered by tutors.

**Comment by damithc** [comment]
This feature needs to be added soon.

**Comment by thyageshm** [comment]
@kennho any updates on this one?

**Comment by kanghj** [comment]
@kennho, how is your progress on this? If you find that this is too difficult for you now, we can reassign this to someone else.

**Comment by kennho** [comment]
I have managed to make the moderate button appear. Still trying to make the edit form appear after the instructor click on the moderate button. Progress may be slow for this week as I have an assignment deadline on Wednesday. Sorry.

**Comment by thyageshm** [comment]
@kennho this issue has slipped one too many milestones. Please set a milestone for V5.71 or 72 and complete it by then. If this issue is expected to take more time, please post here.

**Comment by thyageshm** [comment]
@kennho reminder to complete this by this release
