### ISSUE TITLE
Student: view responses for rubric questions: include the criteria as well

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4283]
The current format makes it hard to understand the result (see screenshot) because the description of each criteria is missing.

Results view:
![image](https://cloud.githubusercontent.com/assets/1673303/9846869/cd0ae6ca-5b07-11e5-8dd6-b32d04163018.png)

Question:
![image](https://cloud.githubusercontent.com/assets/1673303/9846891/efc50132-5b07-11e5-80e0-d8362c6b4892.png)

**Comment by JosephineKwa** [comment]
Prof @damithc I realised that the criteria can be displayed by clicking the [more] link beside the question. Or perhaps you were looking for something else?

**Comment by damithc** [comment]
It is easier to read when the criterion is displayed side-by-side with the value, but it is no longer a high priority.

**Comment by JosephineKwa** [comment]
Removing this from V5.54 milestone

**Comment by thyageshm** [comment]
@JosephineKwa reminder about this issue
