### ISSUE TITLE
admin search: The link for student name should go to the course owners page

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4291]
This link should go to the 'student record' page under the course owner's account. Currently, it seems to go to the account of a randomly selected instructor.
![image](https://cloud.githubusercontent.com/assets/1673303/9867331/d09330d0-5b9e-11e5-9785-93d1ba35d9f6.png)

**Comment by unyoungwax** [comment]
Is the course owner a registered instructor with the privilege to modify instructors?
