### ISSUE TITLE
questionWithResponses.tag: change "moderated-question" HTML class to an id

### ISSUE THREAD

**Issue by yj-soh** [TEAMMATES/teammates#4296]
The possible `moderated-question` class in `questionWithResponses.tag` should be an id instead to reflect how there can only be one moderated question on page load.
This is currently used only for scrolling to that question, so it makes more sense that the scrolling is done according to one element (i.e. an id) than multiple (i.e. class).

**Comment by amarlearning** [comment]
@damithc taking this one

**Comment by amarlearning** [comment]
@damithc Not able to find any CSS property defined over that class `moderated-question`.
That means this `moderated-question` class is just used for scrolling purpose?

**Comment by damithc** [comment]
No idea myself. Ask in slack?

**Comment by wkurniawan07** [comment]
@amarlearning looks like it; doing what is described by the issue should not affect correctness.

**Comment by amarlearning** [comment]
@wkurniawan07 noted
