### ISSUE TITLE
Update godmode test to test default values of encryption key

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#4313]
To prevent the same hashes from getting generated in the html files. To prevent situations where the raw key is used in the html file

**Comment by wkurniawan07** [comment]
Looking at the date, this should've been posted when I was inactive for a short period. What's the reason for testing raw key?

**Comment by kanghj** [comment]
This is not relevant anymore now that godmode is part of the standard workflow. During that period,  there were times when we manually updated html tests, but left the profile picture key in the html. Because everyone used the same encryption key, the profile picture's url was the same for everyone, and therefore the test only failed when testing on the live server.
