### ISSUE TITLE
Add a test for whether the scrolling functions are working

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#4317]
From #4171 and #4293, use JavaScript executor to run the function, return a boolean and assert it through Java side.

**Comment by tshradheya** [comment]
@LiHaoTan Can you help me in understanding how this can be done?

Here is what I have in my mind:

```
Have a UI Test which would load an HTML page and then call the appropriate `scrollTo` function from scrollTo.js file. I am not sure what and how should I assert to check if the scrollTo function works properly.
```

**Comment by LiHaoTan** [comment]
@tshradheya I suppose maybe we can test it like so:
- scrollToPosition
  - Just check the final scroll position via window.scrollY
- scrollToElement
  - assert element is not visible first
  - scroll to element
  - assert element is visible
