### ISSUE TITLE
Cannot edit email of student if the section has exactly 100 students

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4346]
Seems like a boundary case. A easy workaround is to allow 101 students internally, but keep the published limit as 100.

**Comment by damithc** [comment]
Another user encountered this problem.

**Comment by rclakmal** [comment]
@damithc Had a look on this. Could think of two approaches. 
1. Skip the `validateSections` unless section or the team hasn't been changed from the original values. In `validateSections` it only checks whether there has been any violation of section rules or team rules. Doesn't make sense to do this check if only the email is changed. 

2. Second approach, we can delete the old record as soon as we copy the old record data to current record.

**Comment by rclakmal** [comment]
@damithc Created a PR for above approach.
