### ISSUE TITLE
admin create instructor page: Add some explanations about the forms

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4357]
Can add some explanations about why there are two forms, the format used for first form, etc.
This extra info will be useful for devs who are accessing TEAMMATES dev/staging server as admin.

![image](https://cloud.githubusercontent.com/assets/1673303/10039071/165d43f4-6201-11e5-9bfe-555ee59cfea4.png)

**Comment by suhasdarsi** [comment]
I would like to work on this

**Comment by kanghj** [comment]
@suhasdarsi, just submit a pull request when you are ready, or if you want further discussion.

**Comment by Pulasthih** [comment]
Added a PR
