### ISSUE TITLE
Remove all regex comparison in HtmlHelper (that is all calls to AssertHelper.isContainsRegex) to make html comparison faster

### ISSUE THREAD

**Issue by thyageshm** [TEAMMATES/teammates#4383]
Substitute them with normal String compare. @LowWeiLin @kanghj @wkurniawan07 will need your ideas and help to get this one rolled out!

Here are some challenges that we might face (please feel free to add on):
1. Admin pages do not have a mechanical way of adding wildcards ({*}) and so godmode wont be able to do a string-wise compare
2. The popups that have a height dependent on screen size. Things like "height: 423 px" in some of the html pages.
3. Might limit options for creating test cases, since they have to stay within context of godmode's capability.
4. Rules in GodMode might keep increasing and we might have to find an efficient way of doing the substitutions.

**Comment by wkurniawan07** [comment]
This can be done with relative ease for now if we want it to. I have no strong opinion on whether we should or should not, though.

**Comment by thyageshm** [comment]
The main benefit of this would be an increase in quality of test cases. Devs will now be forced to make sure that the "variables" in their test cases are known and predictable.

**Comment by wkurniawan07** [comment]
@thyageshm guess what, I tried it (regex comparison -> string equals) and it worked without any problem.

**Comment by thyageshm** [comment]
:+1: Awesome!

**Comment by thyageshm** [comment]
shall we try and change it?

**Comment by wkurniawan07** [comment]
I'm un-assigning myself and reducing this to `d.Contributors` because the issue's difficulty has been reduced to that level.
