### ISSUE TITLE
admin activity log: user shown as 'unknown' for failed enroll action

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4436]
Only registered instructors can enroll, so I'm not sure why this is shown as 'Unknown'
![image](https://cloud.githubusercontent.com/assets/1673303/10303720/4a2c2f46-6c48-11e5-950b-e1a7fadfa073.png)

**Comment by xpdavid** [comment]
@damithc As indicated in the screenshot, seems that the parsing of log message fails, therefore everything is shown as `Unknown`.
From the log message (part of) `TEAMMATESLOG|||InstructorCourseEnrollSave|||instructorCourseEnrollSave|||true|||Intstructor|||...` seems that the action (InstructorCourseEnrollSave) is done by a registered instructors. It will be helpful if you post the full log message.

**Comment by damithc** [comment]
@xpdavid it's an old issue. I don't have the full log message. I tried to reproduce the problem by supplying invalid data to an enroll operation, but it did not reproduce the problem. Let's close this for now. I'll reopen if it happens again.
