### ISSUE TITLE
instructor remind particular students: Make the student list sortable

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4449]
The student list shown can include section, team, and made sortable?

**Comment by sundychenD** [comment]
Hi Professor Damith, is this issue ongoing or closed? as the student list under each course already shows "section, team" and became sortable.
<img width="1140" alt="screen shot 2015-12-29 at 11 26 57 pm" src="https://cloud.githubusercontent.com/assets/7552874/12036729/b415d7c2-ae83-11e5-8140-0bdfba92ad95.png">

**Comment by wkurniawan07** [comment]
@sundychenD this issue is about this particular modal window:
![image](https://cloud.githubusercontent.com/assets/7261051/12044988/e2473756-aed5-11e5-92a3-28395fcc5193.png)
i.e when you click `Remind -> Remind particular students` for any session on the instructor home page or instructor feedback sessions page.

**Comment by sundychenD** [comment]
I see, thanks a lot, I'd like to work on this issue. 
Just another question. Is the expected UI be the one shown below?

![](https://cloud.githubusercontent.com/assets/7552874/12036729/b415d7c2-ae83-11e5-8140-0bdfba92ad95.png)

**Comment by damithc** [comment]
Regarding the UI, we need a column with check boxes.
No need for the columns Photo and Actions.
No need for the enroll button either.

**Comment by sundychenD** [comment]
After a pull the most recent code from upstream (https://github.com/TEAMMATES/repo.git). 
I have some problem creating the feedback session. After I click the "Create Feedback Session" I get an server error.
<img width="1279" alt="screen shot 2016-01-09 at 9 51 19 pm" src="https://cloud.githubusercontent.com/assets/7552874/12216412/4a8ea2e8-b71b-11e5-9e65-4700ff496660.png">
However the session seems to be created but the response rate is 0/0 and the remind student list is empty. (The dummy course CS3241 has 4 students enrolled and joined).
The exception I have is generated by "teammates.common.datatransfer.FeedbackQuestionType", the source code also shows several errors.
<img width="863" alt="screen shot 2016-01-09 at 9 55 18 pm" src="https://cloud.githubusercontent.com/assets/7552874/12216428/b6a5a2d8-b71b-11e5-8164-5a02dd05fe57.png">

**Comment by damithc** [comment]
Try doing a 'clean project' in eclipse.

**Comment by kanghj** [comment]
Can you try refreshing and cleaning the project?

**Comment by sundychenD** [comment]
Great, the errors are gone after I refresh the project. @kanghj so what kind of cache problem caused this error? Why restarting eclipse doesn't work at the first place?

**Comment by damithc** [comment]
It could be an Eclipse bug that makes it think the class files are up-to-date (and hence, no need to recompile) when in fact the class files are outdated.

**Comment by belyabl9** [comment]
Hello,

I've started to work on this enhancement and got such result:
![image](https://cloud.githubusercontent.com/assets/6876210/13581777/37e51ab4-e4b1-11e5-8035-7321fc5c2705.png)

I need your approve about the following:
1. Is provided UI suitable from the UX point of view ? I mean table representation, column order.
2. Sorting. Do I understand correctly that you use sorting based only on one column for already existing tables ? May I make this column in such way of sorting ? Please, correct me if I am wrong.

I am waiting for your response before creating pull request.

Thanks in advance.

**Comment by damithc** [comment]
1. You can also consider adding the email address column.
2. Yes, sorting by one column is ok.
