### ISSUE TITLE
Show receiver type in the feedback submission form

### ISSUE THREAD

**Issue by ashrayjain** [TEAMMATES/teammates#4451]
It says "To:14" here. Not sure what it should be... Came across this while giving feedback for one of my modules.

<img width="1243" alt="screen shot 2015-10-09 at 2 55 15 am" src="https://cloud.githubusercontent.com/assets/3591327/10376603/4d09d52a-6e31-11e5-802c-ded458277c65.png">

on OS X 10.10.5, Chrome 45.

**Comment by damithc** [comment]
You are in team 14 :-)
Perhaps it can say 'To Team: 14' to make it clearer?

**Comment by ashrayjain** [comment]
Oh! Right. I guess adding Team might make sense?

**Comment by tarun14110** [comment]
I am not able to reproduce. Is that issue with some specific session or question type ?
![screenshot from 2016-07-04 00 03 33](https://cloud.githubusercontent.com/assets/12219700/16547097/6d7bd430-417f-11e6-9a18-06174c3281be.png)

**Comment by damithc** [comment]
You are reproducing in. In your screenshot, the expected text is **`To Team: Team 2`**

**Comment by tarun14110** [comment]
@damithc got that. what exactly is expected from below points?
1. Display every receiver type. like` Self, Students, Instructors, Teams, Own team, Own team members, own team members including self, ...`
2. Grouping all receiver types into just 3 -` Instructor, Student, Team`.
3. Just displaying receiver type `Team`.

**Comment by damithc** [comment]
Option 2? @kanghj what do you think?

**Comment by kanghj** [comment]
Option 2 sounds good for teams and instructors, but I am not sure if displaying `Student` is necessary, since that's the most common and the default recipient type that a response giver would expect.

**Comment by damithc** [comment]
Yes, that's true. may be go with option 3? Person names are long and we don't want to add more text to it.
