### ISSUE TITLE
'Not in a section' appears wrongly in feedback results 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4456]
All the students are in sections, and yet I get this, in the middle of the report too.
![image](https://cloud.githubusercontent.com/assets/1673303/10408711/f459920a-6f37-11e5-81b3-809ea6bf50ea.png)

**Comment by kanghj** [comment]
Can I get more details on this? 
What is the recipient type of Question 3, and are all responses for that question wrongly grouped under "Not in a section"?

**Comment by kanghj** [comment]
If the recipient type is General, then the behaviour is as expected. Responses for general feedback are grouped under "Not in a section" and "-" even if every student in the course has a section. Should that be changed?

**Comment by damithc** [comment]
The session has 5 questions. 3 have 'nobody specific' as the recipient. Those three appear in 'Not in a section' panel. I didn't count but seems all students are listed there.
I guess the current behavior is not wrong. May be rename the panel 'No specific recipient' or something like that?

**Comment by pandilladivya** [comment]
Should I have to rename the panel from 'Not in a section' to 'No specific recipient' ?
I dint find any issues in the current behavior.

Kindly review @damithc 
Thank you

**Comment by damithc** [comment]
Sure. let's do that.
