### ISSUE TITLE
Create Action specificially for testing ajax failures

### ISSUE THREAD

**Issue by yj-soh** [TEAMMATES/teammates#4475]
The current methodology for testing ajax failures is by modifying the form to be submitted to include some invalid value.
Instead, as suggested by @kanghj, we should have a specific URL or action that will call the server and return an error to specifically trigger ajax errors.

**Comment by damithc** [comment]
We still have to modify the form to submit to the new URL?

**Comment by wkurniawan07** [comment]
Not relevant anymore. V7 makes it much easier to simulate AJAX request failure.
