### ISSUE TITLE
Remove unused HTML files

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#4478]
`maintenance.html`: the comparison is removed in 377569f
`instructorFeedbackDoneEditing.html`: the comparison and the file are both removed in 62d8965 but somehow the file survived, should be some merge conflict along the way
`instructorFeedbackResultsSortSecondSessionQuestionSearch.html`: added in b36deab but never used
`studentFeedbackSubmitPageRankSuccess.html`: added in b7b7df4 but never used

**Comment by yashmehrotra** [comment]
@wkurniawan07 Hi Wilson, I would like to work on this. Apart from removing `src/test/resources/pages/instructorFeedbackDoneEditing.html` and `instructorFeedbackResultsSortSecondSessionQuestionSearch.html` are there any other files to be removed ?

**Comment by wkurniawan07** [comment]
`maintenance.html`, as written. Of course, feel free to submit a pull request for this issue, just remember to follow our development process as lined out [here](https://github.com/TEAMMATES/repo/blob/master/devdocs/process.md).
