### ISSUE TITLE
Cannot find recipient errors

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4482]
I'm getting quite a few of these
Error Message: teammates.common.datatransfer.FeedbackContributionResponseDetails getContributionQuestionResponseAnswerHtml: getContributionQuestionResponseAnswerHtml - recipientIndex is -1 Cannot find recipient

**Comment by LowWeiLin** [comment]
It comes with other information right? Is it possible to check for that response, that the recipient exists in the course?

**Comment by damithc** [comment]
1. Error Type: ERROR
Error Message: teammates.common.datatransfer.FeedbackContributionResponseDetails getContributionQuestionResponseAnswerHtml: getContributionQuestionResponseAnswerHtml - recipientIndex is -1 Cannot find recipient: abc@stonybrook.edu CourseId: EST-194 Session Name: Feedback for Assignment 2 Response Id: abczfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgLLFiIMLDA%efg@stonybrook.edu%abc@stonybrook.edu

That's all the information we have (it's just a severe log message, not an exception).
Seems the student exists. I checked a few other cases, and the student does exist.

**Comment by kanghj** [comment]
Is this problem happening for different courses, or for the same course? Were the students' teams changed at any point?

**Comment by LowWeiLin** [comment]
1. Can we check the visibility options for that question?
2. Does this happen all the time? - whenever the results page is accessed
3. Can the response be seen on the results page?

**Comment by damithc** [comment]
@LowWeiLin 
1. The log doesn't tell me which question it is. The session has one contribution question. Here are the questions.
![image](https://cloud.githubusercontent.com/assets/1673303/10557466/83f2fdd6-74e0-11e5-9a4f-a5d35207c74c.png)
![image](https://cloud.githubusercontent.com/assets/1673303/10557465/7b3db96a-74e0-11e5-93c3-53df2bea0fe7.png)

2. Yes, every time that session is accessed.
3. Hard to verify.

**Comment by damithc** [comment]
@kanghj 
Same course.
The instructor has not changed teams recently, but could have done earlier.

**Comment by damithc** [comment]
When I go to the 'moderate' page of one of the affected students, the problematic response is shown whithout a name.
![image](https://cloud.githubusercontent.com/assets/1673303/10557499/07fbbb6c-74e2-11e5-9ac8-6df5978f265b.png)

**Comment by damithc** [comment]
Closing because I did not get similar errors for the past few months.
