### ISSUE TITLE
Ensure responses are valid before showing them

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/teammates#4486]
In results, submit pages.
Related to #4482

**Comment by Sumei1009** [comment]
I do not quite understand this issue. What do you mean "responses are valid"? No duplicated responses?

**Comment by LowWeiLin** [comment]
Take a look at the linked issue?

**Comment by Sumei1009** [comment]
The linked issue is that we should avoid duplicated responses edited by students from the same team? 
So if we want to make sure the responses are valid, does it mean this is the latest edited and the single version of the responses?

**Comment by LowWeiLin** [comment]
Yes, but we do not have the means to find the latest response right now, untill we add timestamps to responses. 
Other validations that should be done are to ensure the giver and recipient are valid (exists and are valid for the question settings) and also check that the response is valid (can be done through a validation function in response/question atrributes)

**Comment by Sumei1009** [comment]
Well, I will try to work on it. Thanks for the clarification.

**Comment by AnaghHegde** [comment]
@LowWeiLin I think its still open?.

**Comment by xpdavid** [comment]
In V7, frontend will always trust data from the backend. If we want to add the check, the correct place to add is the backend.

**Comment by damithc** [comment]
Issue too old. Haven't seen the specific error in concern recently. Closing.
