### ISSUE TITLE
Display comment time in the session's time zone

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/teammates#4488]
Currently, comment timestamp is in the format: Mon, 13 Jul 2015, 08:47:18 UTC
We need to do this using the session time zone.

**Comment by wkurniawan07** [comment]
I don't think it's realistic for this to be done by the next milestone. This needs to wait for timezone values to be appended to relevant `*Attributes`, in particular courses.
Taking this off the milestone, indefinitely.

**Comment by wkurniawan07** [comment]
Not realistic to put this on any milestone as of now; this has to wait until what I mentioned up there.

**Comment by thyageshm** [comment]
@wkurniawan07 @jkt001 could we create the necessary issues needed to unblock this issue?

**Comment by wkurniawan07** [comment]
I believe it's already there: #4812.

**Comment by Mynk96** [comment]
I have solved the issue, but this requires changes in `FeedbackResponseCommentRow.java` which will create lots of merge conflicts with PR #7551.So, will create PR for this after #7551 is merged.
