### ISSUE TITLE
admin activity log search: trailing spaces are not trimmed

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4512]
Both `info:abc` and `info:abc[space]` should return the same results (irrespective of trailing spaces), but they don't.

**Comment by ruchirsharma1993** [comment]
Hello Sir,
Can i work on this issue ?

**Comment by damithc** [comment]
Yes, go ahead. There are no other open PR for this issue. If this is your first issue, I suggest you start with a `d.FirstTimers` issue.
