### ISSUE TITLE
admin search: highlight search terms in results

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4513]
e.g. When searching for `Jean Adams`, it is easier to scan search results if the search terms are highlighted in the results.

**Comment by tarun14110** [comment]
@damithc  
![screenshot from 2016-01-30 02 58 19](https://cloud.githubusercontent.com/assets/12219700/12688632/79e495f6-c6fd-11e5-8b71-56472d0401c0.png)

I am able to highlight the discontinuous keywords of search String in the result. But the way I am doing don't seem efficient to me. If you could guide me with this , I can make this more efficient.

I am splitting searchString in array. Then for every index of array I am traversing the data and replacing that keyword with highlighted one.

eg. I am replacing `<td>${instructor.name}</td>` with
```

<c:set var="arrayOfSearchKey" value="${fn:split(searchKey,' ')}" />
	<c:set var="instructor_name" value="${instructor.name}" />

	<c:forEach var="i" begin="0" end="${fn:length(arrayOfSearchKey)-1}">
		<c:set var="highlightedSearchKeyElement"
			value=" <label style='background-color:yellow'>${arrayOfSearchKey[i]}</label> " />
		<c:set var="instructor_name" value="${fn:replace(instructor_name,arrayOfSearchKey[i],highlightedSearchKeyElement)}" />
	</c:forEach>

	<td>${instructor_name}</td>

```

Should I send a pull request or efficient this code first ?

**Comment by damithc** [comment]
@bamboo3250 what do you think?
@tarun14110 also look at third party solutions e.g http://www.sitepoint.com/10-jquery-text-highlighter-plugins/

**Comment by tarun14110** [comment]
@damithc  I had implemented a third party solution from the above given link. It works like a charm.
Had to code very less, and no need to pass searchKey to lower jsp pages. In the above case I had to pass the searchKey till the lowest level. 

implements
1) case insensitive search
2) discontinuous words matching.
3) highlighting even parts of keywords.
![screenshot from 2016-01-30 14 03 52](https://cloud.githubusercontent.com/assets/12219700/12694674/62c31b50-c75b-11e5-9c1e-e4c8438bb2ac.png)

**Comment by damithc** [comment]
When using third party solutions, need to make sure the library is mature, reputable, stable, well supported, etc. Create a PR when ready.

**Comment by bamboo3250** [comment]
This task is not trivial at all so I also prefer using 3rd party solution here.

**Comment by damithc** [comment]
Yes, I prefer a 3rd party solution too. Just want to make sure we picked the best 3rd party solution though.

**Comment by tarun14110** [comment]
Using https://github.com/bartaz/sandbox.js/blob/master/jquery.highlight.js jquery plugin. Is it fine.

**Comment by thyageshm** [comment]
@tarun14110, when choosing a 3rd party solution try to justify WHY you chose this one over the other available choices. In general try to consider many different options and then filter down to one or two. Some metrics you can use to do this filtering are:
1. Relevance (does it have the features we need)
2. Reliability (are other using this? are there enough contributors? are there live releases happening?)
3. Maturity (How many versions have been released?)
4. Ease of usage
5. Size

There are many others which are not mentioned here. But this should help. 

If the above filtering does not result in just one option, then post the remaining options here for other's opinions.

**Comment by tarun14110** [comment]
I am not able to find a such 3rd party solution that can pass all these filters. There were not much options available.https://github.com/bartaz/sandbox.js/blob/master/jquery.highlight.js and https://github.com/julmot/jmHighlight#4-usage-examples are the best , I had looked. The first one is not updated since 2010. The later one is updated continuously , and had additional features. I prefer 2nd. 
@thyageshm  should I go with this or I have to search for another option available.

**Comment by damithc** [comment]
May be @zeulb can offer some advice as he dealt with highlighting text in another project.

**Comment by zeulb** [comment]
I have used https://github.com/bartaz/sandbox.js/blob/master/jquery.highlight.js to implement text highlighting before. I think it is mature and reputable based on the number of forks and starts. It is also easy to use.

I didn't know about [jmHighlight](https://github.com/julmot/jmHighlight#4-usage-examples) before, but it also seems to be a good option. It has more features than the first one and some of them seems to be useful. Plus it still being updated continuously. But I think it is quite new and not many people know about this yet. So I am afraid it might not have matured enough. So unless the extra features will be useful for the website, I prefer the first one.

**Comment by thyageshm** [comment]
#4722 fixes this one
