### ISSUE TITLE
Feedback question visibility: Hide "Recipient's team members" for recipient type = "Giver's team member and giver"

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#4514]
For recipient type = "Giver's team member", these are the available visibility options:
![teammember](https://cloud.githubusercontent.com/assets/2216119/10660912/0785b206-78dd-11e5-8fb0-cb88e1b1d8c8.PNG)

For recipient type = "Giver's team member and Giver", these are the available visibility options:
![teammemberandgiver](https://cloud.githubusercontent.com/assets/2216119/10660916/0d867a14-78dd-11e5-83e0-c81e10defdc3.PNG)

Recipient's team members should be hidden for the 2nd case, where recipient type is Giver's team member and Giver

**Comment by thyageshm** [comment]
@kanghj any updates on this one?

**Comment by thyageshm** [comment]
@Sumei1009 thank you for taking up this issue :-)
