### ISSUE TITLE
Instructor: home page: show response published status separate from submission status

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4536]
These two things are independent. A session could be both open and published.

**Comment by HirdayGupta** [comment]
@damithc As I understand it, you are recommending the creation of a new column in the table called "Published Status" and renaming the existing column to "Submission Status".

The possible values for the former are "Published/Not Published" and that for the latter are "Open/Closed". Let me know if this understanding is correct.

Also, would just like to clarify, what should be displayed in "Published Status" when "Submission Status" is "Awaiting" or "Private"? Would "NA for Private Session" or "NA for net yet open session" work?

**Comment by damithc** [comment]
The two things are independent. A session can be published but awaiting. e.g. instructor intend to reopen the session after collecting responses once.

`Published? : Yes, No`
`Submissions: Awaiting, Open, Closed`

This issue probably has too many things to do (there are many things that depend on the session status) -- unlikely you can finish it before the GSoC deadline.

**Comment by HirdayGupta** [comment]
> This issue probably has too many things to do (there are many things that depend on the session status) 

@damithc sir could you please give an example of one of these things that depend on the session status? I'm not too sure what you mean by this.

Also, regarding not being able to complete by GSoC deadline, I actually already have a PR-ready branch for this issue. Was just awaiting your input to figure out exactly what content I would need to put in the table (ie: published/not published etc). I had just missed that a session can be both awaiting and published, didn't think of that. If the info you gave above is complete, that is, the info to be displayed in `Published?` and `Submissions:`, then I can push the PR even now. Would just like to confirm that I have not missed something which you think might cause the delay?

**Comment by damithc** [comment]
For one thing, this needs to change everywhere a session status is mentioned, not just in the instructor home page. The whole app needs to be consistent on what is meant by 'session status'.

**Comment by HirdayGupta** [comment]
@damithc Sir I have already implemented this. Instructor Home Page, Instructor Sessions Page and Student Home Page tables have both columns in my branch.

**Comment by HirdayGupta** [comment]
- Instructor Home Page
<img width="1264" alt="screen shot 2017-08-19 at 10 44 40 am" src="https://user-images.githubusercontent.com/18088721/29483731-9061c032-84cb-11e7-90ca-882fbf40e3ff.png">
- Instructor Sessions Page
<img width="836" alt="screen shot 2017-08-19 at 10 45 14 am" src="https://user-images.githubusercontent.com/18088721/29483732-918df7f0-84cb-11e7-97a1-9bf354b818e2.png">
- Student Home Page
<img width="832" alt="screen shot 2017-08-19 at 10 45 33 am" src="https://user-images.githubusercontent.com/18088721/29483733-91dd42a6-84cb-11e7-863b-d093562f43ba.png">

Will now change the table headings to `Submissions:` and `Published?` as you recommended above and change the content displayed in the tables with the content you suggested. (Ie: Yes/no for published? and Awaiting/Open/Closed for submissions)

**Comment by HirdayGupta** [comment]
Note: forgot to clarify that for students: the Submissions column can have: submitted/pending/awaiting/closed.

**Comment by HirdayGupta** [comment]
@damithc sir you can see the current state of my branch [here](https://github.com/TEAMMATES/teammates/compare/master...HirdayGupta:4536-show-response-published-status-seperately). May I go ahead with the PR?

**Comment by damithc** [comment]
> Will now change the table headings to Submissions: and Published? as you recommended above and change the content displayed in the tables with the content you suggested. (Ie: Yes/no for published? and Awaiting/Open/Closed for submissions)

Just `Submissions` (no `:`)

>@damithc sir you can see the current state of my branch here. May I go ahead with the PR?

Sure
