### ISSUE TITLE
Multiple problems in MashupPageUiTest

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#4538]
Some serious ones:
- A few pages (`instructorCourseStudentDetailsPage`, `instructorCourseStudentEditPage`, `instructorStudentRecordsPage`, `instructorFeedbackPreviewAsStudentPage`, `instructorFeedbackPreviewAsInstructorPage`, `studentCourseJoinConfirmationPage`) doesn't load correctly because the student email is wrong (ends with `.com` instead of `.tmt`).
- ~~`studentCourseJoinConfirmationPageNew` won't load except the `app.url` defined in `build.properties` matches `test.app.url` defined in `test.properties`.~~ No longer an issue.
- The error pages (`deadlineExceededErrorPage`, `entityNotFoundPage`, `errorPage`) now won't load because of their error 500 status.
- Many missing pages.

Some not-so-serious ones:
- The jquery script is taken from CDN. That means this page cannot be tested offline (on an unrelated note, `logout.jsp` and `instructorHelp.html` are also guilty of this).
- The `instructorHelp` iframe is not resized due to typo in line 459 (`instructorHelpt`).
- No red line boundaries (`<br><hr class="hr-bold"><br>`) between the static pages, making it harder for viewers to separate them.

And one that I'm not so sure:
We only load `teammatesCommon.css` and `mashup.css` on top of bootstrap. Does this mean some of the views are not 100% accurate?

**Comment by damithc** [comment]
This page is supposed to stay loaded after a test run (i.e. browser used for loading this page should not be reused for subsequent tests). I don't think it happens now.

**Comment by wkurniawan07** [comment]
I can confirm that it still is, so that one's not a problem.

**Comment by Gisonrg** [comment]
@wkurniawan07 
Are you already working on this one now? I just found the same problems and was trying to fix them, then I saw the issue already being raised :stuck_out_tongue:

**Comment by wkurniawan07** [comment]
@Gisonrg I haven't started yet. Feel free to work on it if you wish.

**Comment by Gisonrg** [comment]
@wkurniawan07 
Sure bro, I will tackle this one :)
