### ISSUE TITLE
Make instructor feedback edit page and submission pages resilient to duplicate question numbers

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#4541]
When questions have the same question number, we can order them by their questionid, so that the order is deterministic.

**Comment by Sumei1009** [comment]
May I take this issue? Anyone working on it?

**Comment by kanghj** [comment]
@Sumei1009, yes go ahead and assign yourself and a milestone

**Comment by kanghj** [comment]
@Sumei1009, actually, this is non-trivial, so you should consider doing easier things first until you get more experience.

**Comment by xpdavid** [comment]
Of course duplicate question numbers might indicates bugs in question order adjustments. However, I do believe same question number will still result in successful submission/edit in V7.

- We don't use HTTP param to convey the question number but use the Request body in JSON format.
- API layer use `quesitionId` as resource identifier.
