### ISSUE TITLE
Increase course ID, course name, and session name max length

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4552]
See if we can increase the max length. But we have to be mindful of the impact of longer names/IDs on display formats.

**Comment by amarlearning** [comment]
@damithc Is this issue still open?

**Comment by damithc** [comment]
Yes. Note that this requires changes in both front end and backend.

**Comment by ahmedEl-Lithy** [comment]
Is this issue still open?

**Comment by samuelfangjw** [comment]
Is this issues still relevant? I would like to work on this if possible.

**Comment by damithc** [comment]
> Is this issue still relevant? I would like to work on this if possible.

Go ahead @samuelfangjw
