### ISSUE TITLE
instructor editing questions: Make the 'responses will be deleted' message harder to miss

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4566]
Currently, it looks like a regular message and users might click 'OK' without reading it.

**Comment by leonardhml** [comment]
Hello, I would like to work on this issue. May I ask what are some of the possible files that I can look into to fix this issue?

**Comment by damithc** [comment]
Start with a `d.FirstTimers` issue first. Those are easier to figure out by yourself.

**Comment by leonardhml** [comment]
Hi Prof, I have already done one `d.FirstTimers` task. The instructions were that I should only do one of those.

**Comment by tungnk1993** [comment]
Since html tag can't be used in default modal dialog, I think it's better to use prompt dialog to get a confirm message from user. Also, the dialog can be shortened a bit.

Here's what I implemented:
![promptdialog](https://cloud.githubusercontent.com/assets/3363879/14041565/158cb152-f2ad-11e5-82c7-26138ea9c19a.PNG)

Javascript code:

Before
```
if (!confirm('Editing these fields will result in all existing responses for' +
                       ' this question to be deleted. Are you sure you want to continue?')) {
    event.stopImmediatePropagation();
    return false;
}
```
After

```
var promptAnswer = prompt('Editing these fields will delete all existing responses for' +
                                    ' this question.\nType \'DELETE\' to confirm.')

if (promptAnswer != 'DELETE') {
    event.stopImmediatePropagation();
    return false;
}
```

May I know if this approach is acceptable?

**Comment by damithc** [comment]
I don't think we want users to type anything.

**Comment by tungnk1993** [comment]
For a richer dialog box, I would suggest using external library for nice UI and easy customization. [https://nakupanda.github.io/bootstrap3-dialog/](https://nakupanda.github.io/bootstrap3-dialog/). However, this also requires changes to multiple js files to ensure consistency.

**Comment by damithc** [comment]
Before adding another external library,  I want to make sure the existing libraries don't provide a reasonable alternative, even if not the best.

**Comment by Sumei1009** [comment]
Could we use jQuery dialog and css styling for the customisation?

**Comment by xeia** [comment]
Would implementing a bootstrap modal such as:
![bs modal](https://cloud.githubusercontent.com/assets/12380232/15355613/5a4bc082-1d26-11e6-9ecf-c6065c58cd35.png)
in place of the confirmation box, be viable? 
Additional styling and formatting can be applied via css also, such as for the title area background

**Comment by damithc** [comment]
Yes, that might work. @LowWeiLin @kanghj what do you think?

**Comment by LowWeiLin** [comment]
Looks fine to me. We could also show the number of affected responses in the modal too, in another issue.

**Comment by damithc** [comment]
And if we are going to use modal windows for dialog boxes extensively and system-wide, we should probably extract out common stuff to somewhere. Again, can be a separate issue. I think @YongJieYongJie used a modal window recently for a similar purpose.

**Comment by wkurniawan07** [comment]
On a related note, [this ESLint rule](http://eslint.org/docs/rules/no-alert) might be of interest. It's one of the rules that Google enforced that we (currently) don't.

**Comment by xeia** [comment]
I refactored it out as a shared tag for a confirmation modal, the difference with #5290 would be having a yes/no button to get the user's choice instead of being like a message prompt?

**Comment by YongJieYongJie** [comment]
@xeia For reference, my PR is at #5290
 - I noticed in your screenshot the top corners are not rounded;
 - I actually added css styles to round off the top corners of the modal because after applying bootstrap colors, the border radius was overwritten

**Comment by xeia** [comment]
@YongJieYongJie Thanks for the heads up, the screenshot was done before your PR was merged in hence the styles you added were not reflected. Attached below is the screenshot I just took, of the current modal dialog:
![image](https://cloud.githubusercontent.com/assets/12380232/15413952/2cd55940-1e68-11e6-834d-c662697351f4.png)
