### ISSUE TITLE
Instructor: support previewing results as a student

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4570]
First, we have to make sure all responses are visible to the instructor

**Comment by fans2619** [comment]
Hi prof @damithc , regarding this function, where is the best place to put it? Currently my plan is to _add_ a box similar to the **preview session box** _to_ the **view course-wide session result page**. (put the green box in image 2 at the green box in image 1)

![image1](https://user-images.githubusercontent.com/68739475/172130864-8a6b76ab-0186-47e2-92eb-42478179171e.png)

---

![image2](https://user-images.githubusercontent.com/68739475/172130895-12729a9a-f588-4498-9337-90bc80981e27.png)

**Comment by damithc** [comment]
Sounds good. Shouldn't we put it at the bottom of the page though, for consistency? There is no good reason for it to be at the top in one page and at the bottom in the other.

**Comment by fans2619** [comment]
Hmm the reason is because currently the section below seems to be controlled by the **View** settings. So I want to put above it.

**Comment by fans2619** [comment]
Hmm okay I think as long as it's okay to be in this page, I can start implementing it first. We can always adjust later.

**Comment by fans2619** [comment]
Putting at bottom may also be a good idea.

**Comment by fans2619** [comment]
Open for discussion: What should be displayed to instructor B if a question's results is set to be visible to person A (whose results are being previewed as) but not visible to instructor B (who is previewing the results)? Note that this also includes more complicated cases, e.g., a question's answer is visible to both A and B but the giver's/recipient's name is only visible to A.
The simplest approach is to follow what "moderation" feature is doing currently, i.e., the entire question is displayed to B only if all the 3 items ("answer", "giver's name", "recipient's name") are set to be visible to B. Plus, we can show a note to tell B that "this question is visible to A but not himself/herself". However, this simplest approach may not be the best one considering the usability of this "preview results" feature. For example, given the above case, a more lenient implementation may be showing the giver's/recipient's as _Anonymous_ to B and provide a note to tell B that "A will actually see the giver's/recipient's name".

**Comment by damithc** [comment]
> The simplest approach is to follow what "moderation" feature is doing currently, i.e., the entire question is displayed to B only if all the 3 items ("answer", "giver's name", "recipient's name") are set to be visible to B. Plus, we can show a note to tell B that "this question's result is actually visible to A but not himself/herself". However, this simplest approach may not be the best one considering the usability of this "preview results" feature. For example, given the above case, a more lenient implementation may be showing the giver's/recipient's as _Anonymous_ to B and provide a note to tell B that "A will actually see the giver's/recipient's name".
> @damithc

@fans2619 I'm OK to go with the simpler solution. I expect most questions are set to be fully visible to instructors.
