### ISSUE TITLE
Data Migration: Migrate responses with giver type team to use new responseid format

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#4584]
Data migration initiated by changes in [#4576]

- [x] Merged code that work for both the old and new versions of the data schema.
- [x] Released a version containing the above in [VERY OLD VERSION].
- [x] Created a client script to migrate all data following the old schema to the new schema in PR #11344.
- [x] Ran the script against the live site.
- [ ] Removed the code that is specifically tailored for the old data schema in PR #11344.
    - [x] #7283

**Comment by damithc** [comment]
@JosephineKwa is this related to the issues you posted recently? If so, may be link them up?

**Comment by JosephineKwa** [comment]
Yup they're somewhat related. The issues I created arose as the relevant methods were not updated after the changing of response giver from student email to team name.

**Comment by xpdavid** [comment]
Bad news:
- It is hard to write the script as it is involve multiple retrieval of entities. 

Good news:
- Only need to do it for entities created before (around) 2015
- We will remove a lot of code in the backend and our code will become much simpler
    - e.g. Cascade deletion logic will be simplified
