### ISSUE TITLE
Remove HTML sanitization in EntityAttributes classes

### ISSUE THREAD

**Issue by bamboo3250** [TEAMMATES/teammates#4588]
Since we are using JDO to store and retrieve data from the database, by right, SQL injection should never happen and there is no need to sanitize before saving data. So we can safely remove sanitizeForSaving() function from all classes extended from `EntityAttributes`.

Those classes are:
AccountAttributes
AdminEmailAttributes
CommentAttributes
CourseAttributes
FeedbackQuestionAttributes
FeedbackResponseAttributes
FeedbackResponseCommentAttributes
FeedbackSessionAttributes
InstructorAttributes **(Ongoing)**
:white_check_mark: StudentAttributes
StudentProfileAttributes

While removing sanitizeForSaving(), we also have to apply sanitization in the frontend (JSP/JSTL), where the attribute is used, as well. From now, I will create small issues to work on those classes one by one.

**Comment by leeyimin** [comment]
Remaining classes to sanitize include :

- [ ] AccountAttributes
- [ ] CourseAttributes
- [ ] InstructorAttributes

**Comment by madanalogy** [comment]
> Remaining classes to remove HTML sanitization include :
> 
> * [x]  AccountAttributes #8774
> * [ ]  CourseAttributes #7260
> * [ ]  InstructorAttributes #4699

Might be worthwhile to add #9247 to this list for completeness?

**Comment by wkurniawan07** [comment]
Closing as:
- HTML sanitization in the back-end has been removed since long ago (around 2016-7)
- HTML sanitization in the front-end is automatic as long as `{{ thisFormat }}` is used
- Only old data with HTML characters will be weirdly displayed. The benefit of fixing is marginal.
