### ISSUE TITLE
Give an option for stronger anonymity in feedback results

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4597]
Currently, we use a random id to denote an anonymous respondent and we use the same id in all questions. This weakens the anonymity of the results because it makes it easier to guess the actual identity of the respondent.
e.g. From one essay question response the user can guess the identity of anonymous1234 as John (may be based on John's writing style or because the John revealed the identity in the answer) and use that information to identify all other responses from John.
Perhaps we should give an option to further randomize how we show responses from anonymous respondents?

**Comment by wkurniawan07** [comment]
I'd say this is not an option, but something that really needs fixing. Back then when I was taking CS2103 myself, it was very easy for me to guess who's who in the standard peer evaluation session.

Also, to anyone who wants to take the trouble to look at the source code, the anonymity is non-existent. The algorithm is readily replicable in any Java-running machine and there's no randomness in it. Proof: take a look at the HTML tests; we can hard-code so many instances of "Anonymous student 12345678" and the tests pass at all times, for all users.

**Comment by damithc** [comment]
The anonymous id generated should be really random and should not be reversible or predictable. If it is not, that needs fixing. However, using a different random ID for each question is a separate issue, as there is a benefit for using the same random ID for one person. Sometimes you want to know all answers given by person X without knowing who X is. e.g. random person 123 rated me low in Q1, and I want to know the reason for it, which is given in Q2.

**Comment by wkurniawan07** [comment]
The anonymous ID is not reversible, but very easy to reverse-engineer. Like I said, "non-existent" for anyone who looks at the correct part of the source code.

**Comment by kanghj** [comment]
Yes, it's just the hash of the student's name. Should be fixed in a different issue, I guess.

**Comment by wkurniawan07** [comment]
Superseded by #6092.
