### ISSUE TITLE
Slash is html encoded in csv file

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4622]
Received this bug report from a user:
My student name has D/O in her name but displayed as D&amp;#x2f;O  in the csv file.

**Comment by yash14123** [comment]
How do we fix this? ANy hints?

**Comment by damithc** [comment]
@yash14123 Let's wait until you have successfully merged your first issue before we move to more. When choosing issues, try the ones you think you know how to fix before moving to more challenging ones.

**Comment by belyabl9** [comment]
Hello @damithc,

Could you please clarify steps to reproduce this issue ? I've tried to add new student and edit existing with slash in name. After that I clicked 'Download Students List' on 'Course Details' page, but .csv file has correct symbols. Issue is not new, so probably it is not actual anymore or I missed something.

Thanks in advance.

**Comment by damithc** [comment]
Steps:
1. Enroll a student who has a `/` in the name
2. Download the results of a session in that course
