### ISSUE TITLE
Wrong explanation for persistence.xml in settingUp.md

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#4628]
In [`settingUp.md`](../blob/master/devdocs/settingUp.md) it is mentioned that `persistence.xml` is auto-generated. This is **wrong**: `persistence.xml` is used [to specify the JPA configuration](https://cloud.google.com/appengine/docs/java/datastore/jpa/overview).
On top of the correcting the explanation, JPA also needs to be added to the list of tools used in implementation. The description can be taken from the same page. The version used is v1.0, which comes with DataNucleus v1.x.

**Comment by srajat** [comment]
Corrected explanation for persistence.xml

#4860
