### ISSUE TITLE
Change the variable names in InstructorCourseDetailsPageUiTest

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#4643]
Currently it might not be that obvious that Alice is student one and Charlie is student two.
Also, consider making the variables global as they are used in multiple test segments.

**Comment by ajay-sai** [comment]
Respected sir ,Iam M.Ajay sai of SRM University(Kattankulathur),India. Iam
interested in participating in this year gsoc ,I have finished setting up
the environment ,I am going through the issues I can fix ,can you help me
with some issues I can fix .I am interested in comments+ project.

I am past gsoc '15 participant and links to github :

https <https://github.com/ajay-sai/app-web-server>://
<https://github.com/ajay-sai/app-web-server>github.com
<https://github.com/ajay-sai/app-web-server>/
<https://github.com/ajay-sai/app-web-server>ajay-sai
<https://github.com/ajay-sai/app-web-server>/
<https://github.com/ajay-sai/app-web-server>app-web-server
<https://github.com/ajay-sai/app-web-server>

https <https://github.com/ajay-sai/crowdmap>://
<https://github.com/ajay-sai/crowdmap>github.com
<https://github.com/ajay-sai/crowdmap>/
<https://github.com/ajay-sai/crowdmap>ajay-sai
<https://github.com/ajay-sai/crowdmap>/
<https://github.com/ajay-sai/crowdmap>crowdmap
<https://github.com/ajay-sai/crowdmap>

Iam well versed in languages like html ,JavaScript ,java,c,c++,python,css.
Iam leaning bit of Testng  now.

I have done a internship in wed development under Centre for Good
Governance ,Telengana,India.
Report : please find the attachment

<https://docs.google.com/document/d/1OGhgTdcdUSNYzfzWL_Aa0iHuhnEZMwyuABKxNEZGMIc/edit?usp=drivesdk>

<https://docs.google.com/document/d/1OGhgTdcdUSNYzfzWL_Aa0iHuhnEZMwyuABKxNEZGMIc/edit?usp=drivesdk>
internshipreport
<https://docs.google.com/document/d/1OGhgTdcdUSNYzfzWL_Aa0iHuhnEZMwyuABKxNEZGMIc/edit?usp=drivesdk>
_
<https://docs.google.com/document/d/1OGhgTdcdUSNYzfzWL_Aa0iHuhnEZMwyuABKxNEZGMIc/edit?usp=drivesdk>
ajaysai
<https://docs.google.com/document/d/1OGhgTdcdUSNYzfzWL_Aa0iHuhnEZMwyuABKxNEZGMIc/edit?usp=drivesdk>
_
<https://docs.google.com/document/d/1OGhgTdcdUSNYzfzWL_Aa0iHuhnEZMwyuABKxNEZGMIc/edit?usp=drivesdk>
m.docx
<https://docs.google.com/document/d/1OGhgTdcdUSNYzfzWL_Aa0iHuhnEZMwyuABKxNEZGMIc/edit?usp=drivesdk>

Thanks :)

**Comment by damithc** [comment]
@ajay-sai welcome to TEAMMATES. Please follow our 'Instructions to GSoC applicants' document.
