### ISSUE TITLE
Entities not removed after testing in StudentsDbTest

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/teammates#4646]
Individual tests in StudentsDbTest do not clean up after creating entities, and would fail if they were not running in alphabetical order. The order they are run should be explicitly defined and any entities created should be removed after testing.

We should also look into which other tests do the same thing...

**Comment by damithc** [comment]
I think our policy is to delete potentially conflicting entities *before* the test is run, but not delete them after the test. Leaving the entities is useful for debugging. i.e. we can examine the created data after the test is over.

**Comment by damithc** [comment]
@LowWeiLin Should they be deleted (see my comment above)? If not, close this issue.

**Comment by LowWeiLin** [comment]
The entities are not deleted before the test either. Will rename the issue.
