### ISSUE TITLE
Many methods are duplicated across BaseComponentTestCase and BackDoorTest

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/teammates#4656]
There also seems to be very similar functions in both files, should check if they are actually duplicates.

**Comment by wkurniawan07** [comment]
Worked on this and ready to make a PR after #6227 is merged. Sneak preview: indeed they are, and there are tons of other methods that are duplications: `verify(Absent|Present)InDatastore` in all of its variants, `putDocuments`, `removeAndRestoreData`, `equalizeIrrelevantData` (for posterity sake).

One thing, though, putting `d.Easy` label before was inaccurate :p
