### ISSUE TITLE
Conflicting messages when a session is closed

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4666]
Received this from a student
![image](https://cloud.githubusercontent.com/assets/1673303/12599815/e89eca0a-c4cf-11e5-873a-eebb9fd5a08e.png)

**Comment by YongJieYongJie** [comment]
Did some preliminary tracing:

1st message
* defined at `UNREGISTERED_STUDENT` 
* shown when the **user is not logged in via Google**
* There is a similar message called `UNREGISTERED_STUDENT_RESULTS`.

2nd message
* defined at `FEEDBACK_SUBMISSIONS_NOT_OPEN`
* shown when the **feedback session is closed**.  
  
  
The **relevant request path** is as follows:
* `FeedbackSubmisisonEditPageAction.java` (**2nd msg added**)
  *  calls init() on `FeedbackSubmissionEditPageData.java` (**1st msg added**)  
...
* `studentFeedbackSubmissionEdit.jsp` (**1st msg shown**)
  * uses tag: `feedbackSubmissionForm.tag`
    * includes jsp: `feedbackSubmissionEdit.jsp` (**2nd msg shown**)

**Comment by Sumei1009** [comment]
Can we change to only when the feedback session is open, then the first message is showed? Otherwise we only display the second message? Or should I change the first message as "You are accessing TEAMMATES without logging in" instead of "You are submitting feedback..."

**Comment by YongJieYongJie** [comment]
I think the first message should always be shown whenever the user is not logged in to TEAMMATES because it serves as a call-to-action for users to actually log in.

So maybe a rephrasing will do. Something like "...you may submit feedback for sessions that are currently open"

**Comment by damithc** [comment]
Yes, rephrasing as suggested by @YongJieYongJie sounds like a workable solution.

**Comment by YongJieYongJie** [comment]
@Sumei1009 will you be working on this? If not, I can make a pull request for this.
