### ISSUE TITLE
Give students a proof of submission

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4676]
When a student submit a session, we can give the log entry ID to student to keep as the 'proof of submission'. If there is any dispute later, we can use that ID to search for the entry in the log.

**Comment by jkt001** [comment]
I am looking into this issue, and I will see how this can be done.

**Comment by jkt001** [comment]
Once I have finished working with #4752 and #4819 (i.e. they are merged / mergeApproved), I will work on this. Sorry for delaying this for so long.

**Comment by thyageshm** [comment]
@jkt001 please add the `s.OnHold` label if this issue is dependent on the other two in order to be completed

**Comment by thyageshm** [comment]
@jkt001 reminder for this issue

**Comment by damithc** [comment]
Closing. There is a duplicate for this issue.
