### ISSUE TITLE
Instructor: view results: edit comment: update 'last edited timestamp' via AJAX

### ISSUE THREAD

**Issue by jkt001** [TEAMMATES/teammates#4697]
This is the state of the unedited comment:
<img width="885" alt="screen shot 2016-01-31 at 16 17 20" src="https://cloud.githubusercontent.com/assets/8586215/12701039/34457c10-c836-11e5-8ff6-c505a38b5291.png">

And this is the state of the (previously unedited) comment after edit:
<img width="886" alt="screen shot 2016-01-31 at 16 17 28" src="https://cloud.githubusercontent.com/assets/8586215/12701040/34491884-c836-11e5-8789-71a50d3c247e.png">

Notice that, after it is edited, the "last edited..." time-stamp is not displayed.

**Comment by manishvishnoi2** [comment]
hello sir,
I logged in as a instructor and edited a comment.Its working fine on my machine.
![result](https://cloud.githubusercontent.com/assets/8419629/13433368/92ec5c4c-dff7-11e5-89d9-315958273bf0.png)

**Comment by jkt001** [comment]
@manishvishnoi2 you are in the wrong page. This is in InstructorFeedbackResultsPage, not the Comments section

**Comment by Mynk96** [comment]
I think this is not exactly an issue. How this works is, on refreshing the page 'last-edited-timestamp` is available. @damithc In this issue, Do we want 'last-edited-timestamp' after the ajax action is completed?

**Comment by damithc** [comment]
> I think this is not exactly an issue. How this works is, on refreshing the page(after adding a new comment) 'last-edited-timestamp` is available. @damithc In this, Do we want 'last-edited-timestamp' after the ajax action is completed?

Ideally, the time stamp should update after the ajax submission is complete, but as you say, this is not a big issue. Also note that the page in concern (i.e. the `Comments` page) no longer exists but the problem might exist in other places.

**Comment by Mynk96** [comment]
@damithc For now, the problem persists in `InstructorFeedbackResultsPage` and `InstructorStudentsRecordPage`.
I'll create a PR to solve it.
