### ISSUE TITLE
Data Migration: Remove HTML sanitization in InstructorAttributes

### ISSUE THREAD

**Issue by bamboo3250** [TEAMMATES/teammates#4699]
Data migration initiated by Issue #4588.

- [x] Merged code that work for both the old and new versions of the data schema (Pending #7787).
- [x] Released a version containing the above in V.
- [ ] Created a client script to migrate all data following the old schema to the new schema in PR #.
- [ ] Ran the script against the live site.
- [ ] Removed the code that is specifically tailored for the old data schema in PR #.

Script to Run: `DataMigrationForSanitizedDataInInstructorAttributes.java`

**Comment by damithc** [comment]
@leeyimin do you plan to do this one later?

**Comment by leeyimin** [comment]
@damithc I plan to do this as well, but might be done later than the other Attributes since the changes required for this is likely to be large.

**Comment by leeyimin** [comment]
Continuing this issue, tasks include

- [ ] Removing html sanitization before saving for name
- [ ] Removing html sanitization before saving for role, displayedName
- [ ] Add data migration script for legacy data
- [ ] Run data migration on datastore
- [ ] Remove code added to provide compatibility with legacy format

**Comment by madanalogy** [comment]
@damithc just checking whether the data migration script has been run? Would like to take this to the next step

**Comment by damithc** [comment]
This was a long time ago :-p
Which script exactly? I can try to run it again. But run it yourself first to confirm the script is safe to run.

**Comment by madanalogy** [comment]
> This was a long time ago :-p
> Which script exactly? I can try to run it again. But run it yourself first to confirm the script is safe to run.

It's the [`DataMigrationForSanitizedDataInInstructorAttributes.java`](https://github.com/TEAMMATES/teammates/blob/master/src/client/java/teammates/client/scripts/DataMigrationForSanitizedDataInInstructorAttributes.java) script file. I've tried executing it on my local dev environment and it executes successfully with a config warning logged I'm assuming is related to the fact that I'm running it in a dev environment.

**Comment by damithc** [comment]
> It's the [`DataMigrationForSanitizedDataInInstructorAttributes.java`](https://github.com/TEAMMATES/teammates/blob/master/src/client/java/teammates/client/scripts/DataMigrationForSanitizedDataInInstructorAttributes.java) script file. I've tried executing it on my local dev environment and it executes successfully with a config warning logged I'm assuming is related to the fact that I'm running it in a dev environment.

Thanks @madanalogy 

I get the following when I run the script in preview mode:
```
Total number of entities: 36192
Number of affected entities: 22
```
@xpdavid should I run the script in live mode?

**Comment by xpdavid** [comment]
Unfortunately, I just find out this is why the script is not scheduled to be run: The code is merged in V7 not V6.

**Comment by damithc** [comment]
> Unfortunately, I just find out this is why the script is not scheduled to be run: The code is merged in V7 not V6.

oops. I'm glad I asked before running it :-p

**Comment by madanalogy** [comment]
I take it then that we won't be moving on this issue until v7 goes live?

**Comment by xpdavid** [comment]
Yup. We need release v7 and then we can run the migration script.

**Comment by wkurniawan07** [comment]
Closing (see #4588 for reasons)
