### ISSUE TITLE
Review the future dates used in test cases

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#4707]
Continuation of #4701.
Need to review which future dates can be set to the past (so that things like #4701 can be prevented for good), and which ones need to be in the future (there is at least one such case in `typicalDataBundle`).
Similar bug to #4701 will haunt us in approximately 1-2 months from now if this is not fixed for good.

**Comment by tarun14110** [comment]
@wkurniawan07 I am looking into this issue. Should I use date utility functions for these ?
Are there more cases (other than you have updated in 4701), I need to find ?

**Comment by wkurniawan07** [comment]
Oops sorry @tarun14110 I missed this! I'm not exactly sure because I haven't checked everything myself, but I suspect there's more. In fact, the fix I've done in #4706 will only last until next month.
We could either move the date to so far in the future (10 years from now? xP) or use utility functions to set the date during testing. Either one seems reasonable.

**Comment by tarun14110** [comment]
@wkurniawan07 ok. Could you please assign this issue to me ?

**Comment by wkurniawan07** [comment]
You don't really need to be assigned to work on it, but sure.

**Comment by thyageshm** [comment]
@wkurniawan07 @tarun14110, please fix this asap as we are already being affected by this. We are unable to get dev green because of hard coded dates in March
