### ISSUE TITLE
Add create, last update timestamp to FeedbackQuestion entity

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/teammates#4715]

**Comment by jkt001** [comment]
Is this supposed to be similar to the one in Student (for the createdAt and updatedAt timestamp)? (i.e. the difference is now that the attributes must be added to the entity instead of just returning the default timestamp). I can work on this (and the other one as well) if possible.

**Comment by LowWeiLin** [comment]
This is for adding the timestamps to the **FeedbackQuestion** entity. Includes returning a default timestamp.

**Comment by jkt001** [comment]
Ok I shall try to do this. Should I do #4716 as well since it is similar?

**Comment by LowWeiLin** [comment]
Sure
