### ISSUE TITLE
Allow questions to be marked as 'compulsory'

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4727]
The submission should be blocked until all compulsory questions have been answered.

**Comment by mukesh14149** [comment]
I would like to work on this.

**Comment by thyageshm** [comment]
Hi @mukesh14149, I believe this would be your first issue. Please fix an issue marked with the label `d.FirstTimers` before trying any other issue. When fixing issues and creating PRs, please follow the workflow specified [here](/TEAMMATES/repo/blob/master/devdocs/process.md).
