### ISSUE TITLE
Convert contributor orientation guide to markdown

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4744]
The current one is here https://docs.google.com/document/d/1cY9pmEmw4dC6Z4LjN1WUTsynJ0jVPgbWsFhdyBy_wCU/pub?embedded=true

**Comment by yash14123** [comment]
Where do you want to add this , in which folder?

**Comment by yvsssantosh** [comment]
Hello,

I have some experience with markdown
Is it okay if I work on this issue?
Kindly Review
@damithc 

Thank You

**Comment by yvsssantosh** [comment]
I've completed this issue :)

Do I have to make changes to the CONTRIBUTING.md file ?
Kindly review

Thank You

**Comment by damithc** [comment]
@yvsssantosh You can submit a PR when the issue is done. Remember to follow our process.

**Comment by yvsssantosh** [comment]
Hi,

I just wanted to make sure that I'll be making the PR to the right file
Is the file to be changed is in the root directory CONTRIBUTING.md or should I be creating a new file in devdocs

Kindly Review
Thank You

**Comment by kanghj** [comment]
@yvsssantosh, it's not the CONTRIBUTING.md file.
