### ISSUE TITLE
Allow user to assign value to rubric choices

### ISSUE THREAD

**Issue by Sumei1009** [TEAMMATES/teammates#4746]
Refer to [issue #4603](https://github.com/TEAMMATES/repo/issues/4603)
Can someone help to figure out a better way for user to assign value to rubric choices?

**Comment by damithc** [comment]
@manishvishnoi2 if you are a new contributor looking for an issue to fix, I suggest you start with an issue labelled `d.FirstTimers`. Please refer to the 'Contributor Orientation Guide (link given in our [project home page](https://github.com/TEAMMATES/teammates)) for more guidance on how to get started.

**Comment by kanghj** [comment]
@unyoungwax, do you want to do this?

**Comment by unyoungwax** [comment]
Sure. I will follow the suggestion given in the previous comment.

**Comment by thyageshm** [comment]
@unyoungwax please add a milestone to this issue

**Comment by unyoungwax** [comment]
The UI for the rubric question and the statistics:
![question](https://cloud.githubusercontent.com/assets/10228385/14060404/96330f3a-f39e-11e5-98c7-75b516eecd37.jpg)
 
![stats](https://cloud.githubusercontent.com/assets/10228385/14060405/9ab3bb90-f39e-11e5-870a-1cc2762cf1ef.jpg)

The weight for each rubric choice is indicated in the parenthesis. The average is rounded to 2 decimal places.

Is this okay?

**Comment by kanghj** [comment]
There was another issue where the average for rubrics was already partially implemented, you can refer to that and keep most of the details the same. For the UI, @damithc can decide.

**Comment by damithc** [comment]
This should be an optional thing that users can add, but not present by default. Can the UI reflect that in some way? May be a toggle button?

**Comment by unyoungwax** [comment]
I have changed the UI for the question.
![question](https://cloud.githubusercontent.com/assets/10228385/14065450/681d3fa8-f45c-11e5-9920-6a0b437bdefa.jpg)
The "assign weights" button toggles the visibility of the textboxes for assigning weights.

**Comment by damithc** [comment]
Perhaps add a right arrow and put it in the empty cell on the top left corner? e.g. `[assign weights -->]`

**Comment by kanghj** [comment]
@unyoungwax, how is this issue coming along?

**Comment by unyoungwax** [comment]
I am writing the tests for this issue. The progress is slow because many things need to change. I will submit a pull request tonight.

**Comment by damithc** [comment]
Yes, this is a non-trivial issue. Thanks for taking it up.
