### ISSUE TITLE
Document the use of google cloud storage for profiles

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#4748]
For the staging server, the use of student profile pictures require setting up google cloud storage that is not documented in the setting up guide.

**Comment by damithc** [comment]
@thyageshm I remember this is documented somewhere. It should be included in the set up guide.

**Comment by thyageshm** [comment]
Yes, the setting up of GCS is provided in the [technical report made for profiles](https://docs.google.com/document/d/1TGVkdu6JlOFX_2dJoeZu1avkiKj8ZqFcpBREJhKK78c/pub?embedded=true). The link is also available in README.md under technical reports (the last one)

**Comment by damithc** [comment]
I think we need to move the relevant part to the main dev docs, as it is (an optional) part of the setting up process.

**Comment by yash14123** [comment]
I would like to work on this. :)

**Comment by thyageshm** [comment]
I think this one should be done by one of the core team as we have to confirm whether the process is still valid (it was written a year and a half ago). We also need billing enabled to check this.

**Comment by wkurniawan07** [comment]
Closing as this is platform/ops-specific and does not belong in this repo anymore.
