### ISSUE TITLE
Update client API to OAuth

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4753]
The current scripts will stop working soon
https://cloud.google.com/appengine/docs/deprecations/clientlogin

**Comment by yash14123** [comment]
Link to the client API file?

**Comment by damithc** [comment]
We need to address this quickly.

**Comment by damithc** [comment]
@bamboo3250 this falls in your area.

**Comment by bamboo3250** [comment]
Yes, I'm going to do it after finishing all pending PRs.
