### ISSUE TITLE
Admin severe log alert: No line breaks in stack trace

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4759]
Stack traces in the periodic severe log alert emails look like this. Seems the line breaks in the stack trace have been lost.
![image](https://cloud.githubusercontent.com/assets/1673303/12997500/c5e33486-d174-11e5-8416-f9638ea37698.png)

**Comment by thyageshm** [comment]
I think this is because our email header is `content-type: text/html` and so we must use `<br>` instead of the `\r\n`

**Comment by wkurniawan07** [comment]
Just curious, is this the first time this gets noticed? The function `logSevereForErrorInSendingItem` that I recently added is not the first one that uses `TeammatesException.toStringWithStackTrace` for severe logging.

**Comment by damithc** [comment]
Yes, previously we didn't have the stacktrace for some cases and the stacktrace had line breaks for other cases. See screenshot.
![image](https://cloud.githubusercontent.com/assets/1673303/13038868/93b2842e-d3d3-11e5-9847-588f3e7a254a.png)

**Comment by damithc** [comment]
In fact, it doesn't happen to all log alerts. Just now received an email that had the proper linebreaks.
![image](https://cloud.githubusercontent.com/assets/1673303/13039454/135abe20-d3da-11e5-8f52-00ac5292b8e3.png)

**Comment by damithc** [comment]
I'm guessing the the linebreaks problem is specific to stacktraces missing previously and added by @wkurniawan07 in his recent fix.

**Comment by wkurniawan07** [comment]
Did a quick check and those pages that correctly display the line breaks are indeed using `<br>` (and all other HTML tags to style the display). Strange thing is, there are numerous other instances of `TeammatesException.toStringWithStackTrace` used in `log.severe`. That means those kind of severe logs never come. Just our luck, again.
