### ISSUE TITLE
InstructorFeedbackResultsPageUiTest failures: wrong tooltip attribute position

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#4770]
Related to the changes in #4732. Causes failure on the other related tests too.

![failure](https://cloud.githubusercontent.com/assets/2216119/13039693/5e19da06-d3dd-11e5-94d2-8b115e99e14e.PNG)

Expected result on the left, actual is on the right.

**Comment by damithc** [comment]
@ashrayjain you merged without dev green?

**Comment by ashrayjain** [comment]
No, it was dev green for me after I ran God mode. I will verify asap.

**Comment by wkurniawan07** [comment]
Do you run the test again _after_ regenerating with God mode, this time _without God mode_?

**Comment by ashrayjain** [comment]
Yup, I distinctly remember running it multiple times, first with god mode and then without.
