### ISSUE TITLE
Outdated links in the about page

### ISSUE THREAD

**Issue by jkt001** [TEAMMATES/teammates#4771]
In the about page (again),

there are links tied to contributors when TEAMMATES was hosted in Google code.

<img width="881" alt="screen shot 2016-02-15 at 12 26 44" src="https://cloud.githubusercontent.com/assets/8586215/13039889/2331048e-d3e0-11e5-9718-940f9feb1a0a.png">

However, all links to their contributions now leads to this same <a href = "https://code.google.com/archive/p/teammatespes/"> page</a>.

<img width="1295" alt="screen shot 2016-02-15 at 12 27 04" src="https://cloud.githubusercontent.com/assets/8586215/13039882/fba13e02-d3df-11e5-9f64-84bb32e05dae.png">

Is it better to list their names only since the links does not provide any additional information?

**Comment by wkurniawan07** [comment]
I'd think it is since linking to that page has no value add, but let's wait for more inputs.

**Comment by damithc** [comment]
Yes, we can remove outdated links.

**Comment by yash14123** [comment]
can I get a link to the exact file with the about page?

**Comment by kanghj** [comment]
@yash14123, src/main/webapp/about.html

**Comment by yash14123** [comment]
Please assign me this . Thanks , :)

**Comment by yash14123** [comment]
PR added.

**Comment by pankajd94** [comment]
I want to work on this issue,please assign me .

**Comment by wkurniawan07** [comment]
@pankajd94 you do not need to be assigned to work on an issue, just submit a pull request when it's done and ready for review. Remember to follow the workflow specified [here](https://github.com/TEAMMATES/teammates/blob/master/devdocs/process.md).

**Comment by YongJieYongJie** [comment]
@pankajd94 you made a pull request against your own fork and not this main repo,
perhaps you want to consult the [TEAMMATES Development Process][dev]

[dev]: https://github.com/TEAMMATES/teammates/blob/master/devdocs/process.md

**Comment by yasirunilan** [comment]
Can I work on this issue?

**Comment by yvsssantosh** [comment]
Can I please work on this issue?

**Comment by damithc** [comment]
No need to ask. Just submit a PR :-)

**Comment by yvsssantosh** [comment]
Hi,
Since github links are not outdated, I will be keeping them and removing the links hosted on google Code.

Is this what we are expected to do?

Kindly review.
Thank you :)

**Comment by yvsssantosh** [comment]
![capture](https://cloud.githubusercontent.com/assets/11535830/13871741/999036ca-ed0a-11e5-8106-3b474f0f7984.PNG)

Is this how it's expected?
Shall I send a PR

Kindly Review

Thank You
