### ISSUE TITLE
Create LogHelper class to query log

### ISSUE THREAD

**Issue by bamboo3250** [TEAMMATES/teammates#4773]
At the moment, the functions to retrieve logs from GAE are duplicated in `AdminActivityLogAction` and `AdminEmailLogAction`. Following DRY principle, we should have a class to help us do that task.

**Comment by wkurniawan07** [comment]
Glad you think the same bro, I had this very thought myself when I opened the previous issue :+1:

**Comment by bamboo3250** [comment]
I have to maintain them so it's bugging me a lot :joy:

**Comment by bamboo3250** [comment]
Closing this issue because it will be solved together with #4417 in #4766.
