### ISSUE TITLE
'Deploy' icon missing from settingUp.md

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4780]
![image](https://cloud.githubusercontent.com/assets/1673303/13051793/21dc772a-d436-11e5-9792-002cfb0ef8dc.png)

**Comment by SambitAcharya** [comment]
@damithc please assign me this task.

**Comment by Gourav2906** [comment]
@damithc hey i am a newbie here please help me solve this

**Comment by Gourav2906** [comment]
@damithc created a pull request to solve this.
