### ISSUE TITLE
Document responsiveness guidelines

### ISSUE THREAD

**Issue by ashrayjain** [TEAMMATES/teammates#4783]
This doc will be in the form of a technical report and will outline the best practices and guidelines to be followed when designing pages for Teammates that need to be responsive, i.e. mobile / tablet friendly.

**Comment by thyageshm** [comment]
@ashrayjain reminder for this issue

**Comment by thyageshm** [comment]
@ashrayjain please work on this issue...

**Comment by amarlearning** [comment]
Working on this and will open a PR in some days!
