### ISSUE TITLE
Investigate integration with SlackIn for public channel

### ISSUE THREAD

**Issue by ashrayjain** [TEAMMATES/teammates#4785]
SlackIn - http://rauchg.com/slackin/

**Comment by damithc** [comment]
Rauch Guillermo is the project mentor for FBOA Socket.IO team. He was here during the code sprint. :-p

**Comment by ashrayjain** [comment]
Oh! Nice :)

**Comment by ashrayjain** [comment]
@damithc So, as you had mentioned, looks like single channel guest accounts is a paid feature :(
Moreover, they have a limit on number of such accounts (max = 5 * number of paying accounts).

One alternative is to create a separate free organisation only for contributors, etc. but this might not be ideal.

**Comment by damithc** [comment]
I don't think slack is a very good medium for contributors because we don't have fulltime people always monitoring the channel. We need a more async medium such as email. GitHub works because it has email notifications.

**Comment by ashrayjain** [comment]
Ok. So I guess we can close this issue?
