### ISSUE TITLE
AdminHomePageUiTest failing on line 227

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#4790]
Some elements are missing some stuff like - class="margin-bottom-7px" which is causing some unexpected failures

**Comment by damithc** [comment]
@ashrayjain is this related to your recent PR?

**Comment by ashrayjain** [comment]
Hmm. Thats strange. Its passing me for me on master.
<img width="404" alt="screen shot 2016-02-18 at 12 12 16 pm" src="https://cloud.githubusercontent.com/assets/3591327/13133706/e9cc7dd0-d638-11e5-9afb-23138ea0b440.png">

**Comment by wkurniawan07** [comment]
Reporting that this is passing, tested just now.

**Comment by junhaoyap** [comment]
Indeed, after cleaning and re-running as @kanghj mentioned it's passing now, not sure what went wrong, I'll be closing both! Thanks all for the help and responses :)
