### ISSUE TITLE
FeedbackRubricQuestionUiTest failing on line 219

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#4791]
Same thing, some elements expected class="margin-bottom-7px" but do not have it

**Comment by ashrayjain** [comment]
Same here. Passing for me on master.

**Comment by kanghj** [comment]
yes I believe it passed for me yesterday too. @junhaoyap, try cleaning your project and restarting teammates.

**Comment by junhaoyap** [comment]
Odd, ok I will try to clean and rebuild and get back to this thread

**Comment by wkurniawan07** [comment]
Ditto here, also passing.

**Comment by junhaoyap** [comment]
Ditto as per the other! Thanks all!
