### ISSUE TITLE
Add Issue and PR templates

### ISSUE THREAD

**Issue by ashrayjain** [TEAMMATES/teammates#4792]
Github recently added support for templates that project administrators can specify for issues and PRs. Might be something interesting for us to look into?

https://help.github.com/articles/helping-people-contribute-to-your-project/

**Comment by YongJieYongJie** [comment]
@damithc 
To ensure that the naming convention is followed, perhaps we set up the PR template as follows:
Fixes #
\

For the issue template, we can have a simple reminder:
\

(I've tested the comment syntax on another repo and it works: i.e., user can see it when editing the description, but it will not be shown in the markdown-ed version.)

**Comment by wkurniawan07** [comment]
@YongJieYongJie want to do this? Your suggestion sounds good to me.
