### ISSUE TITLE
Properly sanitize student name, team name and comments related to StudentAttributes in the front end

### ISSUE THREAD

**Issue by bamboo3250** [TEAMMATES/teammates#4806]
I will look through all JSON files that have `students` and append some special HTML characters to  `name`, `lastName`, `comments` and `team`fields to make sure that nowhere else is left out.
Any recommendation is appreciated.

**Comment by damithc** [comment]
Try to do the conversion in a central place so that it will not be left out even by mistake.

**Comment by thyageshm** [comment]
@bamboo3250 reminder to finish this up soon as another issue is also onHold on this.
