### ISSUE TITLE
Release V5.70

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4820]
Due on: March 1st, 2016.

**Comment by damithc** [comment]
@JosephineKwa @yj-soh @jkt001 @unyoungwax @Sumei1009 @kennho please assign issues you plan to contribute to this release.

**Comment by damithc** [comment]
@JosephineKwa @yj-soh @jkt001 @unyoungwax @Sumei1009 @kennho please be reminded that you need to assign issues for the next milestone. The deadline was yesterday.

**Comment by thyageshm** [comment]
Release 207
Code Contributions from: @damithc, @bamboo3250, @shiv12095, @sujeet14108, @Sumei1009, @tarun14110, @wkurniawan07, @unyoungwax, @paradite 
Review Contributions from: @junhaoyap, @kanghj, @bamboo3250, @LowWeiLin, @thyageshm, @wkurniawan07

Sprint Velocity: 36hrs (code) + 24hrs (review) = 60hrs (total)

**Comment by thyageshm** [comment]
@damithc assigning task to you until deployment

**Comment by damithc** [comment]
Deployed.
