### ISSUE TITLE
Eliminate the usage of Selenium's built-in waitForPageToLoad

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#4825]
To be done after #4824 so that Selenium RC can be eliminated for good.
If things go well, this would get rid of all `TimeoutException` thrown by Selenium while doing the mentioned process.

**Comment by wkurniawan07** [comment]
Pushing this to 5.72. I'll try to get it done quick but this issue is not trivial at all (in particular, requires a hell lot of testing) so I might need more time.

**Comment by wkurniawan07** [comment]
As the result this is affected, too.

**Comment by thyageshm** [comment]
@wkurniawan07 please update the effort based on your research effort
