### ISSUE TITLE
Instructor: edit student details: Fix 'Error encountered while adjusting feedback session responses'

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4834]
Error Message: teammates.logic.automated.FeedbackSubmissionAdjustmentAction execute: Error encountered while adjusting feedback session responses of Week 2 Group Learning Activity in course : BMGT365_2016SP : null TEAMMATESLOG|||feedbackSubmissionAdjustmentWorker|||Servlet Action Failure|||true|||Unknown|||Unknown|||Unknown|||Unknown|||Servlet Action failure in feedbackSubmissionAdjustmentWorker
class java.lang.NullPointerException: java.lang.NullPointerException at teammates.logic.core.FeedbackResponsesLogic.updateFeedbackResponseForChangingSection(FeedbackResponsesLogic.java:600) at teammates.logic.core.StudentsLogic.adjustFeedbackResponseForEnrollments(StudentsLogic.java:645) at teammates.logic.automated.FeedbackSubmissionAdjustmentAction.execute(FeedbackSubmissionAdjustmentAction.java:83) at teammates.logic.automated.FeedbackSubmissionAdjustmentWorkerServlet.doGet(FeedbackSubmissionAdjustmentWorkerServlet.java:12) at teammates.logic.automated.WorkerServlet.doPost(WorkerServlet.java:31) at javax.servlet.http.HttpServlet.service(HttpServlet.java:637) at javax.servlet.http.HttpServlet.service(HttpServlet.java:717) at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166) at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388) at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216) at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182) at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765) at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418) at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260) at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) at org.mortbay.jetty.Server.handle(Server.java:326) at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923) at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78) at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:148) at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:468) at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437) at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444) at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:256) at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308) at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300) at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441) at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235) at java.lang.Thread.run(Thread.java:745)

**Comment by wkurniawan07** [comment]
This is a carbon copy of #4769 (even down to the session name and course name). I suspect something's off with that particular session/course. Like, something's not right in the `feedbackSubmissionAdjustmentWorker` but that particular session/course is the one that brings it to the surface.

**Comment by damithc** [comment]
Happening a few times every month, for different courses. Here's a recent one.
```
0. Error Type: ERROR

Error Message: teammates.common.util.Logger severe: Error encountered while adjusting feedback session responses of Round #1 in course Bus102_Peer_Evaluation_Round1_S1_2017: null
TEAMMATESLOG|||worker|||Servlet Action Failure|||true|||Unknown|||Unknown|||Unknown|||Unknown|||Servlet Action failure in worker
class java.lang.NullPointerException: 
java.lang.NullPointerException
at teammates.logic.core.FeedbackResponsesLogic.updateFeedbackResponseForChangingSection(FeedbackResponsesLogic.java:626)
at teammates.logic.core.StudentsLogic.adjustFeedbackResponseForEnrollments(StudentsLogic.java:528)
at teammates.logic.api.Logic.adjustFeedbackResponseForEnrollments(Logic.java:2397)
at teammates.ui.automated.FeedbackResponseAdjustmentWorkerAction.execute(FeedbackResponseAdjustmentWorkerAction.java:66)
at teammates.ui.automated.AutomatedServlet.doPost(AutomatedServlet.java:41)

{enrollmentdetails::[
{
"updateStatus": "MODIFIED",
"course": "Bus102_Peer_Evaluation_Round1_S1_2017",
"email": "aaa@aucklanduni.ac.nz",
"oldTeam": "Stream 2 Team 8",
"newTeam": "Stream 5",
"oldSection": "Stream 2",
"newSection": "None"
},
{
"updateStatus": "MODIFIED",
"course": "Bus102_Peer_Evaluation_Round1_S1_2017",
"email": "bbb@aucklanduni.ac.nz",
"oldTeam": "Stream 4 Team 15",
"newTeam": "Stream 3",
"oldSection": "Stream 4",
"newSection": "None"
},
{
"updateStatus": "MODIFIED",
"course": "Bus102_Peer_Evaluation_Round1_S1_2017",
"email": "ccc@aucklanduni.ac.nz",
"oldTeam": "Stream 5 Team 12",
"newTeam": "Stream 5",
"oldSection": "Stream 5",
"newSection": "None"
}
], courseid::Bus102_Peer_Evaluation_Round1_S1_2017, fsname::Round #1}|||/worker/feedbackResponseAdjustment|||Unknown%20170404173231230
```

**Comment by damithc** [comment]
No recurrences in the recent months. Closing.
