### ISSUE TITLE
ActivityLogEntry: Remove redundant code in getMessageInfo

### ISSUE THREAD

**Issue by thngkaiyuan** [TEAMMATES/teammates#4850]
`Sanitizer.sanitizeForHtml(message);` in the getMessageInfo() method is redundant as it does not change the state of the program in any way. It should not be replaced with `message = Sanitizer.sanitizeForHtml(message);` either as that will break legitimate HTML code within variable `message`. Therefore, that line of code should be removed.

**Comment by suhasdarsi** [comment]
Hey I would like to work on this if possible

**Comment by kanghj** [comment]
@suhasdarsi, you don't have to be assigned to this to work on it, just submit a pull request when you are ready, or if you want further discussion.
