### ISSUE TITLE
Update QUnit framework from v1.10.0 to v1.22.0

### ISSUE THREAD

**Issue by Gisonrg** [TEAMMATES/teammates#4858]
The current QUnit framework we are using is v1.10.0, which is a version around 4 years ago. 
According to QUnit, they are removing many globals that we are widely using in our JavaScript test files  (such as `module()` and `test()`) in their upcoming v2.x release. New APIs of QUnit 2.0 are already usable in their latest release last week (v1.22.0). [Upgrade guide](http://qunitjs.com/upgrade-guide-2.x/)
In order to migrate smoothly in the future and reduce the pollution of global scope, I suggest we upgrade our current QUnit framework, as well as all the JavaScript test cases to use the updated API for better compatibility and performance.

**Comment by wkurniawan07** [comment]
As long as the disruption to other developers can be kept at a minimum level, go ahead and give it a shot :ok_hand:
