### ISSUE TITLE
Update about.html with new contributors until V5.70

### ISSUE THREAD

**Issue by thyageshm** [TEAMMATES/teammates#4869]

**Comment by thyageshm** [comment]
@damithc sir, should we link the contributors to the closed pull requests list? Currently there are some that point to issues, some that point to open PRs. 
Or maybe we can open another issue?

**Comment by thyageshm** [comment]
@damithc or we can use the "involves" search. Sample link searching my [name](https://github.com/TEAMMATES/teammates/issues?q=involves%3Athyageshm). This shows all issues/PRs where the person has been author/assignee/mentions/commenter

**Comment by damithc** [comment]
Yes, we can link to an "involves" search.

**Comment by thyageshm** [comment]
ok
