### ISSUE TITLE
InstructorCommentsPageUiTest failing on dev server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4887]
line 201 `commentsPage.verifyHtmlMainContent("/instructorCommentsPageAddFrc.html");`

![image](https://cloud.githubusercontent.com/assets/1673303/13518057/c371e7ec-e204-11e5-8643-80e651b3da5b.png)

**Comment by wkurniawan07** [comment]
This should've been fixed in latest master...

**Comment by damithc** [comment]
Yes that's what I thought too, but looks like it slipped through? I even cleaned the project and ran it again to make sure.

**Comment by wkurniawan07** [comment]
If I'm not mistaken this is not part of 5.70. That might be the reason.

**Comment by damithc** [comment]
yup, that must be the reason. I was testing V5.70
