### ISSUE TITLE
InstructorFeedbackResultsPageUiTest failing on dev server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4888]
Looks like the same problem as #4817
![image](https://cloud.githubusercontent.com/assets/1673303/13518116/76b8b07e-e205-11e5-9ca4-65b7ee2fafcb.png)

line 469 `resultsPage.verifyHtmlMainContent("/instructorFeedbackResultsFilteredBySectionB.html");`

**Comment by damithc** [comment]
@wkurniawan07 this must be fixed as well, right? Close if so.

**Comment by wkurniawan07** [comment]
#4880 will fix it so it's safe to close as well.
