### ISSUE TITLE
instructor/admin search: results are not highlighted if the search words are in double quotes

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4889]
e.g searching for `"Jane Doe"` will not highlight neither `Jane` nor `Doe` in the results

**Comment by junhaoyap** [comment]
We should extend this to single quotes ```'John Doe'``` too, perhaps?

**Comment by damithc** [comment]
Yes, it should cover all symbols that can be used in search.

**Comment by tarun14110** [comment]
The search string be like `Tarun "yadav" ` . So in this case, `tarun` is highlighted whether it exists as substring or full string anywhere on search result. Do `yadav` should work the same way, Or only highlight wherever its exists as full word. 
![screenshot from 2016-03-05 22 11 03](https://cloud.githubusercontent.com/assets/12219700/13548861/d16bdfc6-e31f-11e5-85ee-0074e5f08008.png)

Here `tarun` is highlighted everywhere. But if someone search `"tarun" `, do I highlight all the same strings as before Or I should don't higlight tarun14110@iiitd.ac.in and tarun14110.iii-demo.

**Comment by damithc** [comment]
I supposed we can highlight even partial words.
