### ISSUE TITLE
instructor/admin search: better matches can be missing from results

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4890]
Let's say I search for `John Doe`. The result contains hits for `John` (e.g. `John Harvey`) and `Doe` (e.g. `Jean Doe`), but the intended target `John Doe` could be missing from the results even if that person exists in the database.

**Comment by rclakmal** [comment]
@damithc Tried reproducing this by adding students with exact 3 names. Searched for `John Doe` and I could see all 3 results.
![snip20160305_1](https://cloud.githubusercontent.com/assets/794011/13550291/d233da9e-e31a-11e5-8ee0-21def710c069.png)

**Comment by damithc** [comment]
I think this depends on the number of hits. I suspect the current one gives the first n results, not the best n results. If there are enough hits for the single words, hits for multiple words could get left out.

**Comment by rclakmal** [comment]
@damithc 
Sent a pull request introducing a sort option to avoid this situation.
