### ISSUE TITLE
Query Regarding Google Summer of Code

### ISSUE THREAD

**Issue by aayushchandna** [TEAMMATES/teammates#4894]
Hey, this is my first attempt at Gsoc. I have a fair experience in coding and i think i can contribute to TEAMMATES. 
If i want to know more about the project of my choice and gain further insight as to what are the expectations from the same, whom should i reach out to? Can someone please help.
Thanking in anticipation.

**Comment by junhaoyap** [comment]
Hello, thank you for your interest in contributing to Teammates - you can find out more about contributing to Teammates as part of the GSoC here at https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true

If there are any more questions feel free to reach out again here and we will respond promptly!

**Comment by RatulGhosh** [comment]
sir, I am looking to apply for GSoC.
I had successfully set up the developer environment and started with #4512 , #1563 and #4106 
I want to discuss about some of the listed projects and where should I write the  project proposal.

**Comment by aayushchandna** [comment]
Hi sir,
Thanks for responding. I am interested in the project Email Customizer. Before i start drafting the proposal i want to know further about the expectations from the project, apart from those mentioned already. Should i contact the mentor directly ?  Also please guide as to how can i contact the mentor?

**Comment by damithc** [comment]
@aayushchandna Our **Instructions for GSoC Applicants** has info on how to contact us regarding specific project ideas.

**Comment by junhaoyap** [comment]
@RatulGhosh you should be opening your own issue page and I see you have done that so good job!

@aayushchandna As above, the document that I have linked you a few days ago should have all the info an applicant needs to apply for GSoC to Teammates
