### ISSUE TITLE
No line breaks in severe log alerts

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4896]
This problem doesn't seem to be fixed yet (this is from V5.70):
![image](https://cloud.githubusercontent.com/assets/1673303/13545614/8c3fe080-e2cc-11e5-8913-e19c2c3eb21d.png)

**Comment by wkurniawan07** [comment]
As I expected, this case was missed before. This needs only a one-liner fix. Are there other stack traces without line breaks that start with something different (i.e not "Crash report failed to send. Detailed stack trace:")?

**Comment by damithc** [comment]
Forwarded three alert emails to you and @thyageshm.

**Comment by wkurniawan07** [comment]
Received, they're exactly where I expected it to occur.
