### ISSUE TITLE
Failed AdminHomePageUiTest due to strict timeout

### ISSUE THREAD

**Issue by chen-zhuo** [TEAMMATES/teammates#4904]
This test case fails due to timeout at `waitForAjaxLoaderGifToDisappear()` in `AppPage.java`. If I increase the value of `test.timeout` in `test.properties` file from 15 to 35, the test case can pass.

I remember running all tests in January this year and I could pass all tests within a few tries. Probably the new version is inefficient? Or should we simply increase the value of `test.timeout`?

FYI, I am using MacBook Pro running on Mac OS X El Capitan (version 10.11.3) with 3GHz Intel Core i7 CPU and 8GB RAM.

**Comment by damithc** [comment]
I too had to increase the test timeout to pass tests at V5.70 which was never an issue before. Not sure what's going on.

**Comment by wkurniawan07** [comment]
There's a test case for adding multiple instructors added pretty recently. One instructor is enough to eat up the entire 15 secs, with more it's expected to need more time than that.

**Comment by damithc** [comment]
I see, mystery solved :-)

**Comment by kanghj** [comment]
Actually, we can take this chance to do a minor optimisation in <code>persistDataBundle</code> to update respondents for each session only once.

**Comment by damithc** [comment]
Actually, account creation taking more than 15s on dev server is some cause for concern. Can it be optimized?

**Comment by kanghj** [comment]
The updating of respondents can certainly be optimised. We can also consider shifting creation of the demo course to the task queue instead.

**Comment by kanghj** [comment]
Reopening this issue since it ought to be resolved in some way

**Comment by bamboo3250** [comment]
Closing this issue since it has been addressed via #4924
