### ISSUE TITLE
Libraries are missing

### ISSUE THREAD

**Issue by arshdkhn1** [TEAMMATES/teammates#4908]
Lib folder is missing, have you done this intentionally or its really missing ?  I would suggest  move to maven

**Comment by yj-soh** [comment]
Hello @arshdkhn1, are you setting up the development environment?
Have you taken a look at [how to set it up](https://github.com/TEAMMATES/teammates/blob/master/devdocs/settingUp.md)?

**Comment by arshdkhn1** [comment]
Yes I am setting dev environment , but getting build path error as Lib folder is missing 
![error](https://cloud.githubusercontent.com/assets/16819670/13550999/b84291e4-e350-11e5-97ad-0b441c7a582b.png)

**Comment by yj-soh** [comment]
If you have set up the development environment, you should have the lib folder available.
Please follow the steps in the link above without skipping any.
