### ISSUE TITLE
Interest in contributing to GSOC project

### ISSUE THREAD

**Issue by wkk91193** [TEAMMATES/teammates#4912]
Hi!
I'm a second year student of Informatics Institute of Technology Sri Lanka, and I hereby express my willingness to contribute to projects "Team profile" ,"Feedback resume", "Tag and search students"

My fields of expertise are version controlling, Object Oriented programming&designing, design patterns,java web applications,javascript,angularjs, Object Relational Mapping(ORM),handling apache tomcat servers.

I would be pleased, receive to further details on the mentioned projects plus warm up tasks in order to further my understandings.

Thank you,
Kumaranath Fernando

**Comment by damithc** [comment]
**Welcome to the TEAMMATES contributor community Kumaranath** :-) 
Please refer to our  'Instructions for Google Summer of Code Applicants' (link given in our [project home page](https://github.com/TEAMMATES/teammates)) for guidance.

**Comment by junhaoyap** [comment]
Welcome to the TEAMMATES contributor community @wkk91193, as mentioned, it would be great if you would look through the document and see how you can move forward into contributing to TEAMMATES for GSoC -

Do also look at the Contributor Orientation Guide on our project home page for orienting yourself into contributing to TEAMMATES :)
