### ISSUE TITLE
New contributor [Serhii Beliablia]

### ISSUE THREAD

**Issue by belyabl9** [TEAMMATES/teammates#4916]
Hello, TEAMMATES community,

Link to app: [https://teammates-belyabl9.appspot.com/](https://teammates-belyabl9.appspot.com/)
Link to fork: [https://github.com/belyabl9/teammates](https://github.com/belyabl9/teammates)
UI changes (border separator between columns):
![image](https://cloud.githubusercontent.com/assets/6876210/13555171/cb2d674a-e3c1-11e5-8c01-780a59566c69.png)
Name: Serhii Beliablia
Self-intro: I am a master’s degree student at Chernihiv National University of Technology, Ukraine.
I tried participation in GSOC/14 for TEAMMATES, but without a success. I am going to do my best this year.

**Comment by damithc** [comment]
**Welcome to the TEAMMATES contributor community Serhii** :-) 
Please refer to our  'Instructions for Google Summer of Code Applicants' (link given in our [project home page](https://github.com/TEAMMATES/teammates)) for guidance.
