### ISSUE TITLE
New contributor self intro Pulasthi Harasgama

### ISSUE THREAD

**Issue by Pulasthih** [TEAMMATES/teammates#4918]
Hi, I was following the "Contributor Orientation Guide" and having completed phases A-C, I am creating an issue here as suggested in phase D. 

Link to my App: https://teammates-pulasthih.appspot.com/
Link to my Fork: https://github.com/Pulasthih/teammates
Screenshot of the change:
![changedui](https://cloud.githubusercontent.com/assets/8380805/13555098/b522b204-e3dd-11e5-99a5-ed21b36c05ff.JPG)

The page that adds new instructors has two options to add either multiple instructors or a single instructor. I noticed that this could be confusing to a new user since a proper description has not been provided. So I changed the headings and also added an information point on how to add multiple instructors.

Name: Pulasthi Harasgama
Intro: I am a third year undergraduate of Computer Science and Engineering of the University of Moratuwa, Sri Lanka. I was fascinated by the system and I plan on contributing to it in future and if possible, as my GSOC project. I have experience with open source development and with webapp development. More information about some of my work can be found in my [blog](http://pulasthiharasgama.wordpress.com). Looking forward to working with everyone.

**Comment by junhaoyap** [comment]
Welcome to the TEAMMATES contributor community @Pulasthih, good work on moving into Phase D and following the instructions!

Please refer to our 'Instructions for Google Summer of Code Applicants' for guidance on how you can move forward in applying to contribute to TEAMMATES under GSoC :)
