### ISSUE TITLE
New contributor self intro [Ratul Ghosh]

### ISSUE THREAD

**Issue by RatulGhosh** [TEAMMATES/teammates#4919]
As suggested by the  "Contributor Orientation Guide" ,I am creating an issue here as suggested in phase D.
Link to my App: https://teammates-ratul.appspot.com
Link to my Fork: https://github.com/RatulGhosh/teammates
Screenshot of the change:
![capture](https://cloud.githubusercontent.com/assets/8985903/13555912/efcd9bb6-e3f2-11e5-8cf9-ba86b75e309f.PNG)
Name: Ratul Ghosh
Short Intro: My name is Ratul Ghosh. I am originally from Kolkata where I received my initial schooling.Presently I am pursuing electronics and communication engineering from [IIIT Allahabad](http://iiita.ac.in/) .
I am fascinated by the system and will try my best to improve it even further. I have experience with  J2EE with Struts and Hibernate, nodejs , python etc. More information about my work can be found [here](http://ratulghosh.tk). Looking forward to collaborate with TEAMMATES.

**Comment by junhaoyap** [comment]
Welcome to the TEAMMATES contributor community @RatulGhosh, good work on moving into Phase D and following the instructions!

Please refer to our 'Instructions for Google Summer of Code Applicants' for guidance on how you can move forward in applying to contribute to TEAMMATES under GSoC :)

**Comment by junhaoyap** [comment]
Apologies @RatulGhosh I jumped to conclusion that you're looking forward to applying to contribute to TEAMMATES under GSoC without first asking you - is that the plan or are you just looking to contribute to TEAMMATES as a form of open source contribution?

**Comment by damithc** [comment]
Yes, he is hoping to apply for GSoC :-)

**Comment by RatulGhosh** [comment]
I have submitted by proposal via the GSoC system can I please get any review for my proposal.

**Comment by RatulGhosh** [comment]
@damithc I have submitted by proposal via the GSoC system 4 days ago can I please get early review for my proposal.
