### ISSUE TITLE
Instructor: edit session: add a test to cover start time not being given a default value at 11pm

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#4921]
Related to #4909 - add a test to prevent regression

**Comment by rclakmal** [comment]
@junhaoyap @damithc IMO, the test case doesn't need to be specific for 11PM. We should check whether a given a time we run the test case, does it show the relevant option in the drop down ? Or a test like this already exist ?

**Comment by damithc** [comment]
I believe it is already tested for typical cases, but not for this corner case.

**Comment by wkurniawan07** [comment]
No longer relevant
