### ISSUE TITLE
Ability to preview emails before sending

### ISSUE THREAD

**Issue by RatulGhosh** [TEAMMATES/teammates#4928]
I want to discuss  about some of the features in the Email Customizer project like how to preview emails before sending.Should I send a MimeMessage to the default email client , using the Desktop API with the URI constructor ( In Java 1.6 we have a standard way to open the default mailer) so I can preview it before sending in JavaMail or are there any better ways.

**Comment by damithc** [comment]
@RatulGhosh Try to write the proposal based on the details given in the ideas page. It’s OK if your proposal is slightly different from what we had in mind. If your initial proposal is good enough to interest us, we’ll contact you during the application evaluation period (after the submission deadline) to hammer out further details before doing the final selection. If our project idea is not clear on some aspect, use your judgement to make the choice you think is the best. That will help us judge the quality of the applicant. :-)

**Comment by RatulGhosh** [comment]
Sir I made a simple template using javascript for previewing emails before sending them.I have also  defined variables in the mail body. Can you please tell whether I am going in the right direction.


![capture3](https://cloud.githubusercontent.com/assets/8985903/13641480/901b44fe-e63e-11e5-8f90-ba7ec557deef.PNG)

**Comment by damithc** [comment]
To understand what Email Customizer feature is about, have a look at the 'mail merge' feature available in other software e.g. Microsoft Office

**Comment by RatulGhosh** [comment]
can we use google sheets instead of excel. If we use google sheets we could use Google Apps Script to do stuffs like sending emails from a Spreadsheet very easily.

**Comment by damithc** [comment]
It is up to you to propose what you think is the best :-)
In general we don't want to add more third party libraries/frameworks unless the benefit justifies the cost.

**Comment by RatulGhosh** [comment]
can I send my project proposal for review to my mentor.

**Comment by damithc** [comment]
We can give feedback for proposals submitted early. Submit via GSoC system and let us know.

**Comment by RatulGhosh** [comment]
okay sir , thank you very much

**Comment by RatulGhosh** [comment]
Sir I have submitted my proposal via the GSoC system.
