### ISSUE TITLE
Query Regarding Gsoc 2016.

### ISSUE THREAD

**Issue by Devmassnk** [TEAMMATES/teammates#4934]
Hello
I have doubt regarding Gsoc. Do TeamMates select student for gsoc, other then NUS university. I looked over past selected students, they all were from NUS. It will be great if somebody can confirm .

**Comment by damithc** [comment]
No, we don't limit slots to NUS students only. In fact, last year we had 2 non-NUS students in our request for slots, but they got cut-off because we got fewer slots. Having said that, the project is based in NUS, so we get lot of strong applications from NUS students.
