### ISSUE TITLE
Email alerts sent out for private sessions

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4939]
Looks like a student received an email submission alert for a session that is marked 'private'. Not sure it was marked private after the email was sent out.

**Comment by tarun14110** [comment]
@damithc I have looked over the code. We are clearly only taking non-private sessions for sending emails. It can happen only at the time of sending email the session is non-private.

**Comment by damithc** [comment]
Thanks for checking @tarun14110 . Do we have a test to ensure private sessions do not send emails?

**Comment by tarun14110** [comment]
Not for all emails. We have test for `private sessions` only for `closing reminder` email. We have to add tests for opening and publishing emails also. Should I do that ?

**Comment by damithc** [comment]
@wkurniawan07 what do you think? Is it worth the effort?

**Comment by wkurniawan07** [comment]
I believe this issue can be closed. The said tests are already present in `EmailGeneratorTest`, starting from line 160:
```java
______TS("no email alerts sent for sessions not answerable/viewable for students");

FeedbackSessionAttributes privateSession =
        fsLogic.getFeedbackSession("Private feedback session", "idOfTypicalCourse2");

emails = new EmailGenerator().generateFeedbackSessionOpeningEmails(privateSession);
assertTrue(emails.isEmpty());

emails = new EmailGenerator().generateFeedbackSessionClosingEmails(privateSession);
assertTrue(emails.isEmpty());

emails = new EmailGenerator().generateFeedbackSessionPublishedEmails(privateSession);
assertTrue(emails.isEmpty());
```
