### ISSUE TITLE
Delete possibly-conflicting entities in Db tests before test is run

### ISSUE THREAD

**Issue by jkt001** [TEAMMATES/teammates#4955]
For all Db Tests, entities are removed from the database after the test is run. This will be done after #4752, #4819, and #4954 is merged and all changes to the test-cases affected (and other tests in Db test) will be made in the same PR.

**Comment by thyageshm** [comment]
@jkt001 reminder to work on this pr :-)

**Comment by jkt001** [comment]
@thyageshm ok, working on it...

**Comment by jkt001** [comment]
After working on this issue, I realize that this might be of higher priority than I previously thought.

The testDeleteStudent test in StudentsDb.java will <b>always fail</b> on the first run (or if all tests are run in that file) because of not removing such entity.
