### ISSUE TITLE
New contributor self intro [Alexandr Kolymago]

### ISSUE THREAD

**Issue by justtimki** [TEAMMATES/teammates#4966]
link to fork: https://github.com/justtimki/teammates/tree/tinker
Was
![was1](https://cloud.githubusercontent.com/assets/15367601/13706168/f73c67a4-e7b4-11e5-9e34-62a74fdea962.png)
Become
![new1](https://cloud.githubusercontent.com/assets/15367601/13706173/0170169e-e7b5-11e5-9dc0-e115f0a748b5.png)

My name is Alexandr Kolymago, was born in Belarus, Gomel and now i'm living and studying here. I'm second year student and specialize in IT. I'm familiar with JavaSE, JavaEE(JSP, Servlets, jstl), JDBC. Have some experience in HTML, CSS, JS. On my github profile you can find some projects, which "close" to teammate :)

**Comment by taniach** [comment]
Welcome to the TEAMMATES contributor community @justtimki and good work on moving into Phase D and following the instructions. You can pick some issues and start contributing.
