### ISSUE TITLE
EmailTemplates contains ${joinFragment} placeholders that are unused

### ISSUE THREAD

**Issue by YongJieYongJie** [TEAMMATES/teammates#4967]
There might be some **redundancy** in the email templates in `EmailTemplates.java` because the `${joinFragment}` placeholder seems to be always replaced with empty string for the following:
* `USER_FEEDBACK_SESSION_PUBLISHED`
* `USER_FEEDBACK_SESSION_CLOSING`
* `USER_FEEDBACK_SESSION`

I checked this by:
1. tracing the call hierarchy for each of the email template constants in `EmailTemplates.java`, then
2. from every assignment of the constant, I follow through to see how the placeholders are replaced

**Comment by damithc** [comment]
@taniach have a look to see if this is really the case.

**Comment by taniach** [comment]
Yes it is, because for the above templates `${joinFragment}` is replaced in `generateFeedbackSessionEmailBaseForStudents()`, `generateFeedbackSessionEmailBaseForInstructors()` and `generateFeedbackSessionEmailBaseForInstructorReminders()` which do not require a join fragment.

**Comment by YongJieYongJie** [comment]
I just looked at the commit history, the `${joinFragment}` **in this three templates** were unused since when automated email was [first implemented][commit]. In other templates, the placeholder is used.

Perhaps we remove the placeholder in these three templates?

[commit]: https://github.com/TEAMMATES/teammates/commit/03b03180b135aaef9357e2648150c3e8e80d42c6#diff-485a91b80865353e0a523b57aec60fce

**Comment by taniach** [comment]
Yes we can do that
