### ISSUE TITLE
Clarification about email support

### ISSUE THREAD

**Issue by belyabl9** [TEAMMATES/teammates#4968]
Hello,

I have some questions related to sending emails. I would be grateful if you clarify it a little.
I have been reading "Help for Instructors" and found such point:

> Any time
> You can use the ‘Students’ page any time to do these things:
> Email a group of students ...

But all I see on 'Students' page is:
![image](https://cloud.githubusercontent.com/assets/6876210/13715087/5f46a38e-e7db-11e5-942c-9f05dfb54e62.png)
![image](https://cloud.githubusercontent.com/assets/6876210/13715108/78f6f9d2-e7db-11e5-8e09-b5ba11b3b2f8.png)

How one or multiple destination email sending can be achieved ?
Doesn't it mean that system provides only email addresses and further sending is on our own ?
Is it possible to send custom emails like from Administrator's realm ?

Next question: when we look at student's teammates from Student realm, their names are represented as mailto links. I think it is really convenient and may be done as an enhancement for Instructor realm.
Please, share your thoughts.

Thanks in advance

**Comment by damithc** [comment]
Yes, we provide a way to get the list of emails. The user is expected to copy paste the list to any email client. At the moment we don't allow users to use TEAMMATES as a email sending client.

From what I remember, there was no way to support such links for multiple emails at the same time. The mailto links works for one email address only.

**Comment by belyabl9** [comment]
@damithc, thanks for clarification. What about email sending client for instructors, is such functionality needed for TEAMMATES ? Should it be considered while preparing design for 'Email Customizer' GSOC project idea ?

**Comment by damithc** [comment]
Yes @belyabl9, support for sending ad hoc emails to selected users can be added under the 'Email customizer' project idea.

**Comment by belyabl9** [comment]
I see, thanks.
You may close this issue
