### ISSUE TITLE
New Contributor : Self Intro [Aayush Chandna]

### ISSUE THREAD

**Issue by aayushchandna** [TEAMMATES/teammates#4969]
Link to fork : https://github.com/aayushchandna/teammates/tree/tinker

Was: 
![was](https://cloud.githubusercontent.com/assets/17591326/13721788/819550d0-e857-11e5-9227-e4a38018546d.png)

Became:
![is](https://cloud.githubusercontent.com/assets/17591326/13721790/967ed584-e857-11e5-9b4f-eb4aa52b8eb4.png)

The contact details for the site are now being displayed  at the bottom of the home page itself instead of a new page being loaded for the same.

My name is Aayush Chandna. I was born and brought up in India and now I am studying in Thapar University here.I am a third year student, pursuing B.E in Computer Science.I have good experience with Java(JSP,Servlets,jstl), JDBC, javaScript, HTML and CSS. I want to contribute to Teammates. I am interested in a few projects, primarily "Email Customizer".

**Comment by junhaoyap** [comment]
Welcome to the TEAMMATES contributor community @aayushchandna, good work on moving into Phase D and following the instructions!

Please refer to our 'Instructions for Google Summer of Code Applicants' for guidance on how you can move forward in applying to contribute to TEAMMATES under GSoC :)

It'll also be great if you can pick some issues and start contributing!
