### ISSUE TITLE
New contributor self intro [Onkar Shedge]

### ISSUE THREAD

**Issue by onkarshedge** [TEAMMATES/teammates#4971]
Link to my app:[http://4-18-dot-teammates-onkar.appspot.com/](http://4-18-dot-teammates-onkar.appspot.com/)
Link to my fork: [https://github.com/onkarshedge/teammates.git](https://github.com/onkarshedge/teammates.git)
screenshot of UI change: Changed the about.html page added the flip view.
![screenshot from 2016-03-12 16 44 49](https://cloud.githubusercontent.com/assets/10570922/13722673/66037e5c-e873-11e5-8275-27b63ad39f30.png)

Self Introduction:
Hello, I am Onkar Shedge from [PICT](http://pict.edu/), India. I am pursuing Computer Engineering and I am in final year. I am interested in contributing to teammates as GSoC student.I liked the idea of comment threads and report visualization. Right now the statistics are displayed with respect to equal share and also avg,agg depending on question. With visualization it will be easy to get brief result and compare.I have some knowledge of JSP, JSTL ,Java .

**Comment by taniach** [comment]
Welcome to the TEAMMATES contributor community @onkarshedge , good work on moving into Phase D and following the instructions!

Please refer to our 'Instructions for Google Summer of Code Applicants' for guidance on how you can move forward in applying to contribute to TEAMMATES under GSoC :)

It'll also be great if you can pick some issues and start contributing!
