### ISSUE TITLE
settingUp.md: an extra character before the repo url

### ISSUE THREAD

**Issue by Gisonrg** [TEAMMATES/teammates#4975]
In [settingUp.md](https://github.com/TEAMMATES/teammates/blob/master/devdocs/settingUp.md#setting-up-the-dev-server), section `Setting up the dev server`, step 1, there is an extra character \` (backtick) before the repo url 

![screen shot 2016-03-13 at 01 19 07](https://cloud.githubusercontent.com/assets/4332224/13724219/ababa088-e8b9-11e5-9fe7-26e3fc608a86.png)

Good for FirstTimer :stuck_out_tongue:

**Comment by yasirunilan** [comment]
Can I work on this firsttimers issue?

**Comment by damithc** [comment]
As described in our process, contributors are free to submit a PR. No need to get the issue assigned first.

**Comment by yasirunilan** [comment]
Thank you .I'll do it.

**Comment by VIthulan** [comment]
I've sent a PR.
Thanks.
