### ISSUE TITLE
Salutations

### ISSUE THREAD

**Issue by patricksanang** [TEAMMATES/teammates#4981]
Hello,
I'm really happy if I'll work with the teammates during the GSoC.

**Comment by YongJieYongJie** [comment]
Hi @patricksanang!

I'm one of the aspiring GSoC'er too,
TEAMMATES has a lot of wonderful resources, you might want to read through [Instructions for Google Summer of Code applicants][GSoC] and [Contributor's Orientation Guide][COG].

[GSoC]: https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true 
[COG]: https://docs.google.com/document/d/1cY9pmEmw4dC6Z4LjN1WUTsynJ0jVPgbWsFhdyBy_wCU/pub?embedded=true

**Comment by taniach** [comment]
Welcome to the TEAMMATES contributor community @patricksanang 

Please refer to our 'Instructions for Google Summer of Code Applicants' for guidance on how you can move forward in applying to contribute to TEAMMATES under GSoC :)
