### ISSUE TITLE
Setting up the Development Environment

### ISSUE THREAD

**Issue by yasirunilan** [TEAMMATES/teammates#4985]
I followed the instructions on how to set up the development environment.But every time I run the test cases,I get about 50 test cases failing.Could any one of you help me to solve this.

By the way I'm Yasiru Nilan, 3rd year undergraduate of department of computer science and engineering of University of Moratuwa.

**Comment by YongJieYongJie** [comment]
Are you using Firefox v38.0.5?
I recall having some failing tests previously but was fixed by using the exact version.

Perhaps you can post a screenshot of the failed tests too.

**Comment by junhaoyap** [comment]
@yasirunilan in order for us to render you some help, can you post some screenshots regarding the failure cases and more information about which phase of the setting up process you are at so we have a better understanding of what is going on?

**Comment by yasirunilan** [comment]
Thanks @YongJieYongJie ,I have some other version of firefox.Now I'm getting only 4 failing test cases.Am I ok to move forward.

**Comment by yasirunilan** [comment]
@junhaoyap thanks for helping.Errors got reduced upto 4.

**Comment by yasirunilan** [comment]
I'm going to move forward.I'll contact you if I encounter any other problems.

**Comment by yj-soh** [comment]
Which test are those and why are they failing?
Is it consistent?

**Comment by yasirunilan** [comment]
yeah they are consistent.
![1](https://cloud.githubusercontent.com/assets/9814784/13730262/9a7d0e70-e970-11e5-88bd-e14c184aa06c.PNG)

**Comment by wkurniawan07** [comment]
Hi @yasirunilan, the one that you showed above should be gone eventually after a few runs. How about the other three, can you post them here as well?

**Comment by yasirunilan** [comment]
Yeah I'll post the screen shots in here.I"m always getting those 4 errors
even after few runs.

Yasiru Nilan

BSc. Eng(Hons) Undergraduate |Batch Representative CSE'13 Batch
Department of Computer Science and Engineering |University of Moratuwa |
Sri Lanka

Asst. Secretory | Leo Club of University of Moratuwa | Leo District 306A2

**Comment by yasirunilan** [comment]
![img_20160314_173900](https://cloud.githubusercontent.com/assets/9814784/13754304/7ae1dc86-ea3c-11e5-9333-28d4e778815a.jpg)
When I today run the test cases.I get only one failing case.screen shot is below.This is failing again and again even I run this test case several times.
I moved forward to staging server part.Is it okay???

**Comment by damithc** [comment]
Yes, you can proceed to next steps while you try to resolve this problem in parallel.

**Comment by yasirunilan** [comment]
https://github.com/TEAMMATES/teammates/issues/5027
