### ISSUE TITLE
New contributor self intro [Leonard Hio]

### ISSUE THREAD

**Issue by leonardhml** [TEAMMATES/teammates#4996]
My fork: https://github.com/leonardhml/teammates/tree/tinker
My app: http://teammates-leonardhml.appspot.com/index.html

<h2>My change:</h2>

The list of team members shown in the about.html page looks a little too disorganised and cluttered. I made a small change to the way it looks by using bootstrap to wrap the list of team members in a table:

<h3>Before:</h3>

![before](https://cloud.githubusercontent.com/assets/12406055/13743584/a28029ec-ea1d-11e5-8ab7-4351b4e53531.PNG)

<h3>After:</h3>

![after](https://cloud.githubusercontent.com/assets/12406055/13743585/a2820b0e-ea1d-11e5-9c47-2154d663dc3c.PNG)

I feel that this change brings about some degree of formality and style that will make a good impression on the viewer.

<h2>About Me:</h2>
Hello everyone! I am Leonard Hio, and I am currently an undergraduate in my second year, studying Computer Science at NUS. My interests in CS include algorithms and Artificial Intelligence.

I am very excited for the opportunity to contribute in one way or another to this project. As someone who is still relatively new to the world of software development, I am eager to learn as much as I can from this experience, and in order to do so, I am prepared to dedicate the time and effort necessary to improve on my skills as well as make a difference to this project. I am also hoping to get a place for GSoC, so that I can have an even more fruitful learning journey ahead.

My programming experience only started two years ago when I first entered NUS. However, in those two years, I was able to direct my own learning beyond the syllabus, learning web and Android development in my spare time. For Orbital 2015, I created an Android application based on the Google Maps API to help students navigate around NUS, and I also created a travel web application with a Node.js backend for SIA App Challenge in 2015. Right now, I have a good foundation in Java, HTML, CSS, Javascript, and Node.js. As this will be my first time working in a large group on a project,  I look forward to learning a lot from all of you, and I also hope to contribute in some significant way to this project :)

**Comment by wkurniawan07** [comment]
Hi @leonardhml, nice to see you again :p
Good job on setting up the dev environment! Now you can find issues to work on, starting from one labelled `d.FirstTimers` and then `d.Contributors`. If you want to apply for GSoC, you can find out more about it in [this document](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true).
