### ISSUE TITLE
New Contributor Self Intro [Venkatesan Harish]

### ISSUE THREAD

**Issue by harishv7** [TEAMMATES/teammates#5000]
## URLs to my fork and app:
My fork: https://github.com/harishv7/teammates/tree/tinker
My app: http://teammates-harish.appspot.com/

## Changes made:
I edited the default fonts to "Raleway" which is provided under the SIL OPEN FONT LICENSE.
Also I have added CSS transitions for hover actions on the navbar with linear color change transition.

## Before:
![Before](http://i.imgur.com/vG2K74j.png)

## After
![After](http://i.imgur.com/0LyZGgq.png)
![After2](http://i.imgur.com/0pPXUys.png)

## More about me:

Hello! I am Venkatesan **Harish**. Currently, I am an second-year Computer Engineering undergraduate at NUS. I have always found TEAMMATES a great platform that helps professors and students to communicate about their various projects. My programming experience is primary in frontend web development. I have built my foundation in HTML, CSS, JS, Java, C and Python since my JC days. More recently, I have been involved in both web and iOS development with ReactJS and React Native. Currently, I am pursuing iOS development with Swift. With my experience, I am sure I can contribute well to the further development of TEAMMATES. Also, I am excited to learn some great software engineering skills from all the current contributors. I am looking forward to extend this internship opportunity to GSoC 2016 if possible.

Thank you!

**Comment by wkurniawan07** [comment]
Hi @harishv7, welcome to the TEAMMATES community!
Good job on setting up the dev environment! Now you can find issues to work on, starting from one labelled `d.FirstTimers` and then `d.Contributors`. If you want to apply for GSoC, you can find out more about it in [this document](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true).
