### ISSUE TITLE
Add country markers to the user map

### ISSUE THREAD

**Issue by paradite** [TEAMMATES/teammates#5001]
This is a follow up of #4872 and #4970 
By adding zoom and pan, we will be able to zoom into areas to see smaller countries like Singapore.

**Comment by yvsssantosh** [comment]
Hi,
@paradite 
I'm currently working on this...

Thank you

**Comment by paradite** [comment]
@yvsssantosh are you aware of how to implement this? there is a very simple way to do it.

**Comment by yvsssantosh** [comment]
Hi,
Since we are using containers i presume we can use ImageViewer API
Kindly share your thoughts

Thank You

**Comment by paradite** [comment]
@yvsssantosh ImageViewer API? This is on web, using JavaScript and HTML, not Java.

**Comment by yvsssantosh** [comment]
Hi,

I have an example running on my web server
And yes it uses Javascript and html

Is it okay if I link you to that?

**Comment by paradite** [comment]
sure please

**Comment by yvsssantosh** [comment]
I'm sorry it took me a while\

Here is the link

http://49.206.198.14:5678/ImageViewer/demo/container-mode.html

**Comment by paradite** [comment]
@yvsssantosh can you try using this on the actual map? It is on svg and contains a lot of logic in it. Not sure if your API would work on it.
If it works then you can send PR?

**Comment by yvsssantosh** [comment]
I think maps would be easier but i need to change a lot of code.
I will give it a shot with this and if it doesn't work then I'll do with maps

I hope my approach is alright
Kindly review
Thank You

**Comment by damithc** [comment]
Actually, I'm not sure if zooming is the best solution here. Perhaps we should show an indicator icon (e.g. map pin) for each country so that small countries are not overlooked/hidden.

**Comment by yvsssantosh** [comment]
@damithc 

Hi,
I think if zoom feature is not enabled then for countries which are too small and close together...the pin might overlap thus showing less number of countries

I believe that zooming is necessary then too.....

Kindly review

Thank You

**Comment by damithc** [comment]
Seeing the country is not important, but realizing a country exists is important. Users will not use zoom if they don't realize there is a country that is too small to see. So, I still prefer the marker idea. Overlapping markers is not a big problem because in the rare case of two small countries existing near each other, the markers can be displaced a bit to avoid an overlap. Accuracy of the marker placement is not a big concern.

**Comment by belyabl9** [comment]
@damithc, I've achieved the following result on my dev environment:
![image](https://cloud.githubusercontent.com/assets/6876210/13863475/ba01e8a8-eca2-11e5-866a-6c677a5a928a.png)
Is it what you expect ? Should I proceed with it ?

**Comment by paradite** [comment]
@belyabl9 that looks very nice. @damithc I think that's what you wanted?

**Comment by damithc** [comment]
Some suggestions:
1. The markers should appear for countries that are using TEAMMATES only, not for all countries
2. The institute count should pop up when the mouse pointer is on the country or the marker
3. When possible, the marker should be contained within the country (but can go out of the country for small countries)

**Comment by belyabl9** [comment]
Marker positions are based on the information about longitude and latitude for every country. I've found it after some surfing the Web, so currently I can't be sure that this database is accurate enough for every country. The good point is that we can modify these coordinates in easy way as we want e.g. for overlapped markers

**Comment by damithc** [comment]
Good. Looking forward to your PR @belyabl9
