### ISSUE TITLE
New contributor self intro [Wei Hu]

### ISSUE THREAD

**Issue by weihu816** [TEAMMATES/teammates#5005]
### a) My App 
http://teammates-weihu.appspot.com
### b) My Fork
https://github.com/weihu816/teammates/tree/tinker
### c) Changes Made

1. Before the YouTube video is opened in a new window. Now it's a popup window.
2. A feature browsing index is added at the top of the features page.

<img width="500" alt="screen shot 2016-03-15 at 00 02 58" src="https://cloud.githubusercontent.com/assets/7198709/13767701/e69c8f78-ea43-11e5-8b71-c4ff2e4301da.png">

<img width="500" alt="screen shot 2016-03-15 at 00 02 23" src="https://cloud.githubusercontent.com/assets/7198709/13767669/7b8f8424-ea43-11e5-8b60-2306190afe8f.png">

### d) Self-Intro
Hello! My name is Wei Hu. I'm a first-year master student at UPenn, United States. I come from China.

I hope to participate in GSoC 2016 during this summer. It's exciting to see the impact of technological change in education. And I'm very excited about the opportunities of working together with this great community to improve this interesting project during this summer with full-commitment.

I'm proficient in Java and hope to work as a backend developer. I've taken undergrad/graduate level database courses and been exposed to a wide variety of web technologies, such as Java GWT, Node.js, J2EE. I have good knowledge of software engineering. During the process of exploring web technologies, I've done projects like implementing an HTTP web server and servlet container, building a web crawler and search engine. I believe I'll make positive contributions to this project and let's work together to make this software better and better.

**Comment by junhaoyap** [comment]
Welcome to the TEAMMATES contributor community @weihu816, good work on moving into Phase D and following the instructions!

Please refer to our 'Instructions for Google Summer of Code Applicants' for guidance on how you can move forward in applying to contribute to TEAMMATES under GSoC :)

It'll also be great if you can pick some issues and start contributing!
