### ISSUE TITLE
New contributor self intro [Yasiru Nilan]

### ISSUE THREAD

**Issue by yasirunilan** [TEAMMATES/teammates#5006]
(a) **Link to my app** : http://teammates-yasiru.appspot.com/
(b) **Link to my Fork** : https://github.com/yasirunilan/teammates/tree/tinker

(c)
 Earlier it was like this 

- First four of the core team was listed one by one like in a column.

- I changed it to get first four of the developers to one Row so that core developers get highlighted.

![earlier](https://cloud.githubusercontent.com/assets/9814784/13769951/94105148-eaa9-11e5-842b-d165203fae2a.PNG)

Now it's like this

![now](https://cloud.githubusercontent.com/assets/9814784/13769996/fd9ccda8-eaa9-11e5-9385-ce32e98edd02.PNG)

(d)
I'm Yasiru Nilan and I'm an 3rd year undergraduate of department of Computer Science and Engineering ,University of Moratuwa,Sri Lanka.I went through all the project ideas by TEAMMATES and all of them took my mind.So I would like to work with TEAMMATES along with GSoC 2016.Also I would like to contribute to TEAMMATES as a contributor not only for GSoC but also in other times.I'm now working on fixing some issues on this project and willing to contribute.

Also I have technical skills on JAVA,JSP,HTML,CSS,Bootstrap,MySQL,PHP,Javascript etc.My recently finished project was done using Java,JSP,HTML,CSS.So I have the technical capabilities to contribute to this project.
So I think I'm capable of doing a project for GSoC 2016 with TEAMMATES.

**Comment by taniach** [comment]
Welcome to the TEAMMATES contributor community @yasirunilan , good work on moving into Phase D and following the instructions!

Please refer to our 'Instructions for Google Summer of Code Applicants' for guidance on how you can move forward in applying to contribute to TEAMMATES under GSoC :)

**Comment by yasirunilan** [comment]
Can I get an early feedback if I submit my proposal for GSoC 2016 days before the deadline??

**Comment by taniach** [comment]
@damithc Is it possible to provide early feedback?

**Comment by damithc** [comment]
Yes @yasirunilan submit through the system and let us know.

**Comment by yasirunilan** [comment]
I submitted a draft proposal through the system.Could you please review that and give a feedback.
Thanks in advance.

**Comment by damithc** [comment]
Will do tonight.

**Comment by yasirunilan** [comment]
ok .thanks

**Comment by damithc** [comment]
Please email us the proposal. I can't find yours in the GSoC system.

**Comment by yasirunilan** [comment]
shall I give the link to proposal(google doc)

**Comment by yasirunilan** [comment]
Or if I need to email it,what's the email that I should send it?

**Comment by yasirunilan** [comment]
![capture](https://cloud.githubusercontent.com/assets/9814784/13955305/1d5b4ba4-f06a-11e5-8914-8e76e5a7270e.PNG)

**Comment by damithc** [comment]
Found it. Comment added.

**Comment by yasirunilan** [comment]
Yeah.Thanks for the feedback

**Comment by yasirunilan** [comment]
I have concerned only about one project in there.But there are several projects that I can work on.If so do I need to implement UI prototypes for all the projects.Please clarify.

**Comment by damithc** [comment]
You can give a full proposal for one project and include less detailed proposals for other projects you can do.

**Comment by yasirunilan** [comment]
![createteam](https://cloud.githubusercontent.com/assets/9814784/13994265/0fce25fc-f14a-11e5-8b0b-e3416ff549df.png)

**Comment by yasirunilan** [comment]
any comments??

**Comment by damithc** [comment]
No comments at this point. Go ahead and include it in your proposal.

**Comment by yasirunilan** [comment]
Thanks
