### ISSUE TITLE
New contributor self intro [Dhanuka]

### ISSUE THREAD

**Issue by sudosparrowhawk** [TEAMMATES/teammates#5008]
d) Hello! everyone. I'm Dhanuka from Sri Lanka. I'm a first year Natural Science student at Open University of Sri Lanka. And really love to code! I started my coding journey with Java. I learned almost everything from Stackoverflow and Java API. Now I'm really good with Java SE, HTML, CSS, SQL, Bootstrap and JavaScript.

I work on Arch Linux system. I use Eclipse as my main IDE, and also use Geany for quickly find answers for Stackoverflow questions. And also I use Gnome, VLC, firefox, gedit, libreoffice, GIMP and list goes on.. As you can see I'm all Open Source. Ever since I started using open source software I always wanted to contribute to the open source community. Thanks to Google I got my chance.

I went through all the Organizations and their project ideas and I found TEAMMATES.
I'd like to contribute to Project: Team profiles. So, I read all of the instructions and Contributor Orientation Guide. When I'm following Phase instructions, today I learned how to use github and also configured Eclipse with Google pulgin and TestNG. But I couldn't complete the Phase D's 9th one. Because I'm not very familiar with Java EE yet. And This a great opportunity for me to learn all the required technologies including Java EE. So, I'm ready!

Stackoverflow profile - http://stackoverflow.com/users/4533771/sudosparrowhawk?tab=profile

Thanks.

**Comment by samatdav** [comment]
Hello, Dhanuka! Nice to meet you! I also apply to Teammates this year. To better prepare for the application process you may find it useful to go through [Instructions for GSoC Applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true) and [Contributor Orientation Guide](https://docs.google.com/document/d/1cY9pmEmw4dC6Z4LjN1WUTsynJ0jVPgbWsFhdyBy_wCU/pub?embedded=true).
I hope it helps :-)

**Comment by sudosparrowhawk** [comment]
Thank you very much Samat. Nice to meet you too @samatdav

**Comment by sudosparrowhawk** [comment]
When setting up the development environment in Eclipse, First I downloaded the teammates-master.zip file. And then according to the Developer Troubleshooting Guide (https://docs.google.com/document/d/1_p7WOGryOStPfTGA_ZifE1kVlskb1zfd3HZwc4lE4QQ/pub?embedded=true#h.9yiw9q5jm2c) I installed the Google plugin for Eclipse and TestNG too.
After importing the project into Eclipse I've few errors, Can anyone guide me to solve these errors.

![screenshot from 2016-03-15 18-54-47](https://cloud.githubusercontent.com/assets/17715090/13779267/24657c88-eae0-11e5-8134-bce1052f1be8.png)
Google App Engine Problem
```
Description	Resource	Path	Location	Type
The project 'teammates-master' does not have any App Engine SDKs on its build path	teammates-master		Unknown	Google App Engine Problem
```
JSP Problem
```
Description	Resource	Path	Location	Type
Can not find the tag library descriptor for "http://java.sun.com/jsp/jstl/core"	accountTable.tag	/teammates-master/src/main/webapp/WEB-INF/tags/admin/accounts	line 3	JSP Problem
```
Java Build Path Problems 
```
Description	Resource	Path	Location	Type
Project 'teammates-master' is missing required library: 'src/main/webapp/WEB-INF/lib/google-api-client-appengine-1.18.0-rc.jar'	teammates-master		Build path	Build Path Problem

```
Java Problems 
```
Description	Resource	Path	Location	Type
The project cannot be built until build path errors are resolved	teammates-master		Unknown	Java Problem
```

**Comment by samatdav** [comment]
@sudosparrowhawk Did you follow [Setting Up the Developer Environment](https://github.com/TEAMMATES/teammates/blob/master/devdocs/settingUp.md) guide? There are some prerequisites you have to do before downloading and installing the zip.

**Comment by junhaoyap** [comment]
Welcome to the TEAMMATES contributor community @sudosparrowhawk, good work on moving into Phase D and following the instructions!

Please refer to our 'Instructions for Google Summer of Code Applicants' for guidance on how you can move forward in applying to contribute to TEAMMATES under GSoC :)

It'll also be great if you can pick some issues and start contributing!

Also, thank you @samatdav for chipping in! :+1:

**Comment by sudosparrowhawk** [comment]
Thanks again @samatdav :) I still got some errors. 

![screenshot from 2016-03-16 00-32-51](https://cloud.githubusercontent.com/assets/17715090/13790484/a3a50f6c-eb0e-11e5-9a00-e4dd9b3e5ecf.png)


I got this errors after creating `com.google.gdt.eclipse.core.prefs` file. 

```
eclipse.preferences.version=1
jarsExcludedFromWebInfLib=/home/dhanuka/Documents/workspace/TEAMMATES/src/test/resources/lib/appengine/appengine-api-labs.jar
warSrcDir=src/main/webapp
warSrcDirIsOutput=true
```

**Comment by sudosparrowhawk** [comment]
Hi
