### ISSUE TITLE
Rubrics: don't show numerical values of options in students' view

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#5015]
The numerical values for computing the average can be hidden for the student's submit page for now, until we allow instructors to specify the numerical value for each option in #4746.

Edit: need to hide in student results page too

**Comment by damithc** [comment]
They are not shown in student result page right? If they are, need to be hidden there as well.

**Comment by kanghj** [comment]
Updated the issue description

**Comment by damithc** [comment]
A user is waiting on this. Need to release as a hot fix.
