### ISSUE TITLE
Not explicit creation of main config files in settingUp devdoc.

### ISSUE THREAD

**Issue by samatdav** [TEAMMATES/teammates#5018]
In [settingUp devdoc here](https://github.com/TEAMMATES/teammates/blob/master/devdocs/settingUp.md#setting-up-the-dev-server), the third point (creation of main config files), does not mention explicitly enough the process of creating files without ".template" in the names.

**Comment by wkurniawan07** [comment]
@samatdav the templates aren't meant to be removed; you'd have seen that the above doc specifies `copy → paste → rename`.

**Comment by samatdav** [comment]
@wkurniawan07 changed the issue.

**Comment by wkurniawan07** [comment]
Quoting the same doc:
```
src/main/resources/build.properties
Use build.template.properties (in the same folder) as the template (i.e. copy → paste → rename)...
```
I believe that it's explicit enough. Do you have any suggestion to make it clearer? Also bear in mind that we prefer not to spoon-feed new contributors with every slightest detail.

**Comment by samatdav** [comment]
@wkurniawan07 I would suggest adding a sentence about the renaming process in the main description of the step, rather than in a specific sub step. I proposed a PR.

**Comment by junhaoyap** [comment]
@damithc can you please take a look?

**Comment by damithc** [comment]
I think the current one is good enough, but if someone proposes a better description, we can always upgrade.
