### ISSUE TITLE
Rephrase the link to user map in index.html

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5020]
![image](https://cloud.githubusercontent.com/assets/1673303/13811188/194f240a-ebaf-11e5-8185-e09739513c77.png)

Rephrase as:
~~See who is using TEAMMATES in our [user map]()~~
[See who is using TEAMMATES ...]()

**Comment by pandilladivya** [comment]
Hello @damithc I am working on this issue .

Thankyou :)

**Comment by pandilladivya** [comment]
Kindly check PR #5028

**Comment by pandilladivya** [comment]
Hi,

New PR create #5039 

Kindly review
Thank You
