### ISSUE TITLE
New contributor self intro [Shahin Alam] 

### ISSUE THREAD

**Issue by sopnopriyo** [TEAMMATES/teammates#5022]
(a) Link to my app : http://teammates-shahin.appspot.com/
(b) Link to my Fork : https://github.com/sopnopriyo/teammates/tree/tinker
(c) I have modified the about page , the four core team members image and their information is now in one row.
**Before**
![screenshot from 2016-03-16 21 47 43](https://cloud.githubusercontent.com/assets/7261420/13814432/31041f62-ebc1-11e5-8db4-36a16710d79d.png)

**After**
![screenshot from 2016-03-16 21 25 56](https://cloud.githubusercontent.com/assets/7261420/13814471/64be9ac6-ebc1-11e5-8447-71111d2dc4de.png)
now

(d)
My name is Shahin Alam and I am 2nd year student , studying bachelor of Computer Science in University of Malaya.I was looking for some interesting open source projects and found TEAMMATES  to be interesting.I have knowledge on HTML5,CSS3,Javascript, PHP, Java , JSP Servlet , Oracle 10g and MySQL .So I would like to put these knowledge into practice with TEAMMATES.

**Comment by junhaoyap** [comment]
Welcome to the TEAMMATES contributor community @sopnopriyo, good work on moving into Phase D and following the instructions!

It'll also be great if you can pick some issues and start contributing!

One question - are you an aspiring GSoC applicant?

**Comment by sopnopriyo** [comment]
Thank you @junhaoyap . I will start by picking some small issues.
Yes, I want to participate for GSoC.

**Comment by junhaoyap** [comment]
Awesome @sopnopriyo - I've added the GSoC tag to this so we can keep track of all the people who wants to participate in GSoC with TEAMMATES, I look forward to your first contribution!
