### ISSUE TITLE
Issues in Setting up Developer Environment

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#5023]
Hi, my name is Yuan Bin, a Year 3 Computing Science student from the National University of Singapore.

I am having issues with getting the UI tests to pass on my system, as the connection appears to be refused. Firefox states that it is unable to establish a connection to localhost:8888, and a screenshot of the errors after re-running the failed tests (via "Run failed tests") is as follows:
![teammates001](https://cloud.githubusercontent.com/assets/7546744/13816482/87a2eb02-ebc9-11e5-968e-6bfa65cff995.png)

I have already followed the steps as given in `https://github.com/TEAMMATES/teammates/blob/master/devdocs/settingUp.md` up to Step 3 of "Running the test suite", as well as setting the Firefox path to a 38.0.5 version, as I am using the latest version of Firefox (45.0) as my main browser.

I note that running the development server works normally, and I am able to access localhost:8888 when not running tests.

**Comment by jkt001** [comment]
Hi Yuan Bin,

Are you sure that you are running the test <b> while </b> the dev server is running?

Once you opened up Eclipse, run the dev server and then run the tests without turning off the dev server.

Hope this helps!

**Comment by chowyb** [comment]
Hi,

Thanks for the help! I realised I misinterpreted the instructions, and explicitly turned off the dev server before running tests (also because another school project I'm on has that workflow)

Thanks again!

**Comment by junhaoyap** [comment]
@wkurniawan07 assigning you to help out if any more is needed, @jkt001 thanks for chipping in!
