### ISSUE TITLE
New contributor self intro [Yasiru Nilan]

### ISSUE THREAD

**Issue by yasirunilan** [TEAMMATES/teammates#5027]
(a) Link to my app : http://teammates-yasiru.appspot.com/
(b) Link to my Fork : https://github.com/yasirunilan/teammates/tree/tinker

(c)
Earlier it was like this

![earlier](https://cloud.githubusercontent.com/assets/9814784/13823532/ef401a22-ebcf-11e5-854b-bc2034c9d31a.PNG)

- First four of the core team was listed one by one like in a column.

- I changed it to get first four of the developers to one Row so that core developers get highlighted.

Now it's like this
![now](https://cloud.githubusercontent.com/assets/9814784/13823598/53ab2d26-ebd0-11e5-9a1b-714672f71d4d.PNG)

(d)
I'm Yasiru Nilan and I'm an 3rd year undergraduate of department of Computer Science and Engineering ,University of Moratuwa,Sri Lanka.I went through all the project ideas by TEAMMATES and all of them took my mind.So I would like to work with TEAMMATES along with GSoC 2016.Also I would like to contribute to TEAMMATES as a contributor not only for GSoC but also in other times.I'm now working on fixing some issues on this project and willing to contribute.

Also I have technical skills on JAVA,JSP,HTML,CSS,Bootstrap,MySQL,PHP,Javascript etc.My recently finished project was done using Java,JSP,HTML,CSS.So I have the technical capabilities to contribute to this project.
So I think I'm capable of doing a project for GSoC 2016 with TEAMMATES.

**Comment by junhaoyap** [comment]
Welcome to the TEAMMATES contributor community @yasirunilan, good work on moving into Phase D and following the instructions!

Please refer to our 'Instructions for Google Summer of Code Applicants' for guidance on how you can move forward in applying to contribute to TEAMMATES under GSoC :)

I see you have already started working on fixing some issues and that's great!

**Comment by yasirunilan** [comment]
Can I get an early feedback if I submit my proposal for GSoC 2016 days before the deadline??

**Comment by junhaoyap** [comment]
@yasirunilan I'll have to defer this to @damithc - please advise

**Comment by yasirunilan** [comment]
Thanks.I got the a feedback however @junhaoyap
