### ISSUE TITLE
Testing time

### ISSUE THREAD

**Issue by belyabl9** [TEAMMATES/teammates#5029]
Hello, TEAMMATES community,

I have a question, it should not take a lot of your precious time :-)
What is the approximate time of running full test suite for your machine ?

It is really important for me, because it takes my laptop about 20-30 minutes. Especially, it hurts me when I am doing some minor fix. I understand that e.g. some minor JS changes don't  require running full test suite, but responsible people do it to be sure that you won't damage some project version after merge.

I only want to find out if it's a problem with my environment or slow hardware.
I would be grateful if some of you write amount of testing time for your machine in comments including information about hardware and OS.

Thanks in advance.

**Comment by YongJieYongJie** [comment]
My tests take about 20 minutes (but usually need to rerun some failed tests to get them to pass), here a dump of my system information:
![image](https://cloud.githubusercontent.com/assets/14101781/13833120/9621a962-ec1d-11e5-9ea6-9efd2a5a6e45.png)

**Comment by damithc** [comment]
Yes, 20 minutes is not abnormal. On a related note, @ashrayjain is working on moving the testing to Travis CI server. Once that is done, we can dispense of running tests on our local machines.

**Comment by belyabl9** [comment]
Oh, in such case I should not worry about it. Thanks for your answers. "Moving the testing to Travis CI server" sounds great.
I've got enough information, so we may close this one.
