### ISSUE TITLE
Add code coverage for JavaScript tests

### ISSUE THREAD

**Issue by Gisonrg** [TEAMMATES/teammates#5040]
Since we are already using QUnit to run JavaScript tests, it's good to also provide information for code coverage, so we would know where can be improved in our code, or add missing test cases if needed.
[Blanket.js](http://blanketjs.org/) seems like a good choice as it is lightweight, works well, and supports QUnit by default. It's also very easy to configure to the current system as well.

**Comment by wkurniawan07** [comment]
You can consider [JSCover](http://tntim96.github.io/JSCover/) as well. Either way, it's good if we can have coverage tool for JS :+1:
