### ISSUE TITLE
Help | Unable to Download http://www.comp.nus.edu.sg/~seer/teammates-libs/libsV5.60.zip file

### ISSUE THREAD

**Issue by rajivjhaimin** [TEAMMATES/teammates#5043]
Greetings, 
I am Rajiv Jha,an open source developer from New Delhi, India.
I am trying to set up the dev server on my localhost, But i ran into this problem. I am unable to download the http://www.comp.nus.edu.sg/~seer/teammates-libs/libsV5.60.zip file. I have tried it over different networks too. 
Downloading starts but after few minutes it ceases, leading to abrupt ending of zip file downloaded.
I am trying this from yestreen. 
Kindly Help
Thanks

**Comment by YongJieYongJie** [comment]
@rajivjhaimin 
I'm not sure what's the problem, perhaps you can try getting zip file from my [Dropbox][db].
[db]: https://www.dropbox.com/s/li9vmv07ntw6yc6/libsV5.60.zip?dl=1

**Comment by rajivjhaimin** [comment]
@YongJieYongJie 
Thanks. It worked.

**Comment by damithc** [comment]
Thanks for the help @YongJieYongJie :+1:
