### ISSUE TITLE
SanitizerTest not fully implemented

### ISSUE THREAD

**Issue by YongJieYongJie** [TEAMMATES/teammates#5048]
Several tests in [SanitizerTest][link] are not implemented since the file was created.

[link]: https://github.com/TEAMMATES/teammates/blob/master/src/test/java/teammates/test/cases/common/SanitizerTest.java#L46

**Comment by Fenn-CS** [comment]
Pls Assign me the task

**Comment by YongJieYongJie** [comment]
@Fenn-CS actually I've already submitted a Pull Request and is pending review

**Comment by Fenn-CS** [comment]
@YongJieYongJie  Ok,:)
