### ISSUE TITLE
New contributor self into [Chao Song]

### ISSUE THREAD

**Issue by songchoa** [TEAMMATES/teammates#5053]
(a) link to the app: teammates-chaosong.appspot.com

(b) link to my fork: https://github.com/songchoa/teammates

(c) original: 
<img width="1026" alt="screen shot 2016-03-18 at 5 17 35 pm" src="https://cloud.githubusercontent.com/assets/17481346/13893685/b36c5e2e-ed2e-11e5-8923-fdde8e4212a4.png">
 modified:
picture 1:
 <img width="1106" alt="screen shot 2016-03-18 at 5 13 00 pm" src="https://cloud.githubusercontent.com/assets/17481346/13893714/dc050cc8-ed2e-11e5-94b1-efc086e17c3c.png">
picture 2:
<img width="975" alt="screen shot 2016-03-18 at 5 13 22 pm" src="https://cloud.githubusercontent.com/assets/17481346/13893717/e1efa92c-ed2e-11e5-9d13-e9690ce69abc.png">

(d)self into:

Hey guys! I'm Chao Song from Iowa State University (Ames, IA, USA). My major is Software Engineering, and this is my Junior year. I feel pretty comfortable about programming using Java, JavaScript, and HTML. I hope i can make a contribution to this awesome project. Thanks!

**Comment by songchoa** [comment]
Hi, i have shared my first proposal draft with you. Thanks!

**Comment by junhaoyap** [comment]
Welcome to the TEAMMATES contributor community @songchoa, good work on moving into Phase D and following the instructions!

Please refer to our 'Instructions for Google Summer of Code Applicants' for guidance on how you can move forward in applying to contribute to TEAMMATES under GSoC apart from sharing your draft with us :)

It'll be great if you can pick a few first timer issues and start contributing!
