### ISSUE TITLE
New contributor self intro [Yuan Bin]

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#5059]
a) no link to app (no GAE account)
b) Link to fork: https://github.com/chowyb/teammates
c)
Edited the Acknowledgements section so that the section title stands out better as compared to the text in the section. Previously, the first line in the section stood out more than the title itself (due to larger font size)
Before:
![old](https://cloud.githubusercontent.com/assets/7546744/13903919/ef61b9e2-eec8-11e5-83f3-6dbb980c2334.png)

After:
![new](https://cloud.githubusercontent.com/assets/7546744/13903920/f461f6be-eec8-11e5-81b0-0064bf19fa04.png)

d)
Hi! My name is Yuan Bin, a 3rd year Computer Science undergraduate from the National University of Singapore (NUS), and taking a focus area in Interactive Media.

I have experience in using HTML, CSS, JS and Java, and while I presently do not have experience with JSP, I hope to bridge this learning gap quickly so I am able to contribute to this project as soon as I am able to.

Thank you!

**Comment by junhaoyap** [comment]
Welcome to the TEAMMATES contributor community @chowyb, good work on moving into Phase D and following the instructions!

I see that you have already opened an issue which is great! It'll be even better if you can start picking some first timer issues and start contributing :)

One question - are you an aspiring GSoC applicant?

**Comment by chowyb** [comment]
Hi @junhaoyap,

Nope, I will not be applying for GSoC.

**Comment by junhaoyap** [comment]
@chowyb got it - do let us know if you run into any problems when contributing and we'll be glad to help!
