### ISSUE TITLE
Duplicate bold class in teammates.css

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#5060]
Two instances of the .bold class have been defined in teammates.css as shown in the two screenshots below:

![bold1](https://cloud.githubusercontent.com/assets/7546744/13904014/e13036e2-eecc-11e5-91de-eec9c1f68fbf.png)

![bold2](https://cloud.githubusercontent.com/assets/7546744/13904015/e6d2f1ac-eecc-11e5-84b5-09ad1d3e48c6.png)

While this presently does not seem to cause any issues, it would probably be better to only have one such declaration for the class.

**Comment by priyamm** [comment]
@chowyb  kindly check PR https://github.com/priyamm/teammates/pull/1

**Comment by chowyb** [comment]
@priyamm I am not a core member of the TEAMMATES development team, and as such I do not have the authority to review your PR.

However, I note that your PR is on your own fork (the contributor repo) instead of the main TEAMMATES repo (the committer repo). You might want to put up a PR on this repo instead, using the `compare across forks` option when putting up the PR.

**Comment by priyamm** [comment]
Hi, 
Oh, I figured that out that I didn't compare it. Actually, I am new to Git.
It seems somebody else fixed it.
Thanks
