### ISSUE TITLE
Broken link in Contributor Orientation Guide

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#5061]
In the [**Contributor Orientation Guide**](https://docs.google.com/document/d/1cY9pmEmw4dC6Z4LjN1WUTsynJ0jVPgbWsFhdyBy_wCU/pub?embedded=true), there is a link for `project vision, challenges, and principles`, however this refers to a page on the TEAMMATES server that likely does not exist anymore.

![overview](https://cloud.githubusercontent.com/assets/7546744/13904035/643f6a58-eecd-11e5-80af-dc0df9fd3397.png)

This link should probably point to https://github.com/TEAMMATES/teammates/blob/master/devdocs/overview.md instead.

**Comment by damithc** [comment]
Fixed. Thanks for the bug report @chowyb
