### ISSUE TITLE
New contributor self intro [Rajiv Jha]

### ISSUE THREAD

**Issue by rajivjhaimin** [TEAMMATES/teammates#5068]
Greetings,

(a) link to the app: http://teammates-rajivjha.appspot.com/

(b) link to my fork: https://github.com/rajivjhaimin/teammates

Updations : I have added  http://teammates-rajivjha.appspot.com/features.jsp and also made the menu and footer common  in include folder to ease the management.
My online projects : **www.junksquare.com** & **www.xampaperz.com**
My open source contribution : **Reperesentator, Spoken-tutorial, MOOC - IIT-Bombay by MHRD, Govt. of India. **
I am Rajiv Jha, pursuing B.tech (II Year) from University School of Information and Communication Technology, New Delhi, India.
I have Knowledge of **HTML5, CSS, Java Script, Bootstrap, PHP, Python, App Engine, Git, JSP, Mysql, Mysqli** and Java. I am interested to contribute into teammates project namely **Data upload and Email Customizer**. **It would be amazing if i can contributes to teammates** in GSOC 2016 session and further after.
Thanks and Regards
Rajiv jha

**Comment by taniach** [comment]
@rajivjhaimin We appreciate and thank you for your interest in TEAMMATES. To begin with, you can check our Contributor Orientation Guide. It will help you get started.

**Comment by rajivjhaimin** [comment]
@taniach 
Greetings,
I have made the whole website responsive.
Kindly have a look at http://4-18.teammates-rajivjha.appspot.com/index.html 
I have also transferred the html file to jsp file and use include feature of jsp to ease the management of common parts of website, for eg. Header, Footer.

![image](https://cloud.githubusercontent.com/assets/14246533/13942839/9c92ba9a-f01c-11e5-98a1-b544d91eb04f.png)
![image](https://cloud.githubusercontent.com/assets/14246533/13942863/1751237a-f01d-11e5-8715-388787660e6a.png)
![image](https://cloud.githubusercontent.com/assets/14246533/13942866/1cb0990e-f01d-11e5-94ba-6f8cad0b5661.png)
![image](https://cloud.githubusercontent.com/assets/14246533/13942878/4ab93dd8-f01d-11e5-9fdd-ec2fb55060cd.png)
Thanks

**Comment by damithc** [comment]
Good effort Rajiv :-)

**Comment by rajivjhaimin** [comment]
@damithc  Thanks Sir .

**Comment by rajivjhaimin** [comment]
@damithc  @LowWeiLin 
Greetings Team,
I have submitted my proposal for review.
Kindly guide me with the feedbacks.
 
Thanks

**Comment by damithc** [comment]
Comments added to the proposal draft.
