### ISSUE TITLE
New contributor:self intro[Harshvardhan Singh]

### ISSUE THREAD

**Issue by Harshvardhan58** [TEAMMATES/teammates#5076]
[New contributor.docx](https://github.com/TEAMMATES/teammates/files/181663/New.contributor.docx)

**Comment by junhaoyap** [comment]
Welcome to the TEAMMATES contributor community @Harshvardhan58, could you extract what you have in the document in here so we can all see it without having to download a file?

By the way - are you an aspiring GSoC applicant?

**Comment by Harshvardhan58** [comment]
Thank you for notifying me. I will post in issue by tonight.

And yes I am interested to participate in Gsoc. Can you please guide me
that what I should do increase my chance to get selected.

Thank you
Harshvardhan Singh
