### ISSUE TITLE
Instructor roles do not match their privileges in test data

### ISSUE THREAD

**Issue by unyoungwax** [TEAMMATES/teammates#5079]
For example, in `InstructorCommentsPageUiTest.json`, the instructor with the "Manager" role has the permission to modify course. There is also a "Helper" role that has different privileges in different tests, it should be renamed to "Custom".

Other .json files that have the similar problem include `InstructorCourseEditPageUiTest.json`, `InstructorSearchPageUiTest.json`, etc.

**Comment by damithc** [comment]
@unyoungwax do take this issue when you have time.
