### ISSUE TITLE
Couldn't access the admin/adminHomePage

### ISSUE THREAD

**Issue by shreyamahapatra** [TEAMMATES/teammates#5080]
Steps followed-
1.cloned the repository
2.src/main/resources/build.properties

#-----------------------------------------------------------------------------
# This file contains some confuguration values required using building
#   and running of the app.
# It should be placed in src\test\resources 
# Use'\' to escape ':' e.g., http\://google.com
#-----------------------------------------------------------------------------

# This is the app url used in emails sent out by app.
# For dev server, any URL would do. 
# For staging server, use the url of the app on remote server.
# e.g. app.url=http\://teammates-john.appspot.com
app.url=http\://teammates-john.appspot.com

# This is the Google Cloud Storage bucket name used by the app
# For dev server, any name would do
# For staging server, use the url of the app on remote server (without https\://)
# e.g. app.gcs.bucketname = teammates-michelle.appspot.com
app.gcs.bucketname=teammates-john.appspot.com

# This is the key used by test driver to access backdoor. 
# It can be any random string you choose, 
#   as long as it matches with test.backdoor.key in test.properties. 
# e.g. app.backdoor.key=lsfdieafoereojfe

app.backdoor.key=samplekey

# This is the encryption key used for encryption
# It should be a base 16 string and a multiple of 16 bytes (at least 32 chars)
#e.g."1234567890abc123456789abc1234567"

app.encryption.key=5360b12f6a07af7be93437d215f72fca

# This is the maximum time the app waits for a datastore operation to persist.
# We use such a delay because of 'eventual consistency' nature of the datastore.
# Increase the number if test cases fail due to persistency delays.
# Value is in milliseconds 
app.persistence.checkduration=4000

# This is the email address to report runtime error not handled
#   by the system, i.e. AssertionFailure and other unchecked exceptions.
# This should be an email you check. e.g., email of the app admin.  
app.crashreport.email = app_admin@gmail.com

# This is the url to display as a message of the day to a student.
# Use test-student-motd.html to test this feature.
# e.g. app.student.motd.url = test-student-motd.html
app.student.motd.url = 

# Sendgrid username for sending emails
# If this is blank, GAE JavaMail be used for sending emails instead of Sendgrid.
app.sendgrid.username = 

# Sendgrid password for sending emails
app.sendgrid.password = 

3.src/test/resources/test.properties

#-----------------------------------------------------------------------------
# This file contains some configuration values used during testing.
# It should be placed in src\test\resources 
# Use'\' to escape ':' e.g., http\://google.com
#-----------------------------------------------------------------------------

# This is the url of the app we are testing against.
# e.g. test.app.url=http\://localhost\:8888
# e.g. test.app.url=https\://4-30-dot-teammates-john.appspot.com
# Note: the '.' in the url has been replaced by -dot- to support https connection for the staging server.
test.app.url=http\://localhost\:8888

# This is the key test suite use to access app backdoor.
# It should match app.backdoor.key in build.properties
# e.g. test.backdoor.key=fjdlsafdkfdk
test.backdoor.key=samplekey

# These are parameters for Selenium  
# allowed values for browser: firefox, chrome
test.selenium.browser=firefox

# Optional field to change firefox path.
# This will enable user to use non default binary.
# To use default firefox setting, leave the field as is,
# to use custom path, e.g. 
#test.firefox.path=C:\\Program Files (x86)\\Mozilla Firefox 12\\firefox.exe
test.firefox.path=

###############################################################################
# This is the timeout value, in seconds, for the waitings done in browsers
# e.g waiting for element (non-)presence/(in)visibility, for page to load
# This value can be adjusted depending on your CPU power/memory availability.
# Note that the value entered must be a positive integer.
test.timeout=15

###############################################################################
# Given below are the test accounts/passwords used for testing. 
# The values given below will work for the dev server(except one test case GodModTest).
# To pass GodModTest, change ALL the accounts(except test.admin.account) by appending to the back of it.
# e.g. alice.tmms -> alice.tmms.asd
# If you plan to run the test suite against a staging server, 
# you need to create four Google accounts (to use as test accounts) 
# and give their details below.

# The Google account of a user that has 'admin access' to the application
# For testing against staging server, you should use your own google account here.
# Omit '@gmail.com'
test.admin.account=yourGoogleId
test.admin.password=adminpassword

# This Google account will be given 'instructor access' to the application.
# For testing against a production server, replace it with details of a real GMail account.
test.instructor.account=teammates.coord
test.instructor.password=anypassword

# These two Google accounts will be given 'student access' to the application.
test.student1.account=alice.tmms.shreya
test.student1.password=anypassword
test.student2.account=charlie.tmms
test.student2.password=anypassword

# A Google account will not be given access to the application.
test.unreg.account=teammates.unreg
test.unreg.password=anypassword

4.src/main/webapp/WEB-INF/appengine-web.xml

<?xml version="1.0" encoding="utf-8"?>
<appengine-web-app xmlns="http://appengine.google.com/ns/1.0">

  <threadsafe>true</threadsafe>
    
    
    
    
    <application>teammates-john</application>
    
    
    
    <version>4-18</version>
    
    
    <system-properties>
        <property name="java.util.logging.config.file" value="WEB-INF/logging.properties"/>
    </system-properties>

    
    <sessions-enabled>true</sessions-enabled>
    
</appengine-web-app>

5..settings/com.google.gdt.eclipse.core.prefs

eclipse.preferences.version=1
lastWarOutDir=C:/Users/HP/Desktop/teammates

jarsExcludedFromWebInfLib=C:/Users/HP/Desktop/teammates/src/test/resources/lib/appengine/appengine-api-labs.jar|C:/Users/HP/Desktop/teammates/src/test/resources/lib/appengine/appengine-api-stubs.jar|C:/Users/HP/Desktop/teammates/src/test/resources/lib/appengine/appengine-api.jar|C:/Users/HP/Desktop/teammates/src/test/resources/lib/appengine/appengine-remote-api.jar|C:/Users/HP/Desktop/teammates/src/test/resources/lib/appengine/appengine-testing.jar|C:/Users/HP/Desktop/teammates/src/test/resources/lib/httpunit/httpunit.jar|C:/Users/HP/Desktop/teammates/src/test/resources/lib/javamail/mail.jar|C:/Users/HP/Desktop/teammates/src/test/resources/lib/selenium/selenium-server-standalone-2.46.0.jar
warSrcDir=C:/Users/HP/Desktop/src/main/webapp
warSrcDirIsOutput=true

included the libraries in the project folder

Still couldn't access

**Comment by shreyamahapatra** [comment]
![image](https://cloud.githubusercontent.com/assets/12638368/13917812/1cb42716-ef89-11e5-9533-e612acc94535.png)

**Comment by damithc** [comment]
Try to follow every step carefully. This setup instructions are tried-and-tested, so the chances are you missed out a step. Give it one more try from the top and ask here if you are not sure how to follow any of the steps.

**Comment by shreyamahapatra** [comment]
i have used eclipse mars. That would create a issue?

**Comment by shreyamahapatra** [comment]
My server is running absolutely fine but the said page dont open it up

**Comment by damithc** [comment]
Do refer out [troubleshooting guide](https://docs.google.com/document/d/1_p7WOGryOStPfTGA_ZifE1kVlskb1zfd3HZwc4lE4QQ/pub?embedded=true)
If still doesn't work, post the output of the dev server console.

**Comment by shreyamahapatra** [comment]
i am getting errors in the jsp files

**Comment by shreyamahapatra** [comment]
********************************************************
There is a new version of the SDK available.
-----------
Latest SDK:
Release: 1.9.34
Timestamp: Fri Feb 12 01:06:15 IST 2016
API versions: [1.0]

-----------
Your SDK:
Release: 1.9.27
Timestamp: Thu Sep 03 01:59:33 IST 2015
API versions: [1.0]

-----------
Please visit https://developers.google.com/appengine/downloads for the latest SDK.
********************************************************
Mar 21, 2016 7:22:29 PM com.google.appengine.tools.development.SystemPropertiesManager setSystemProperties
INFO: Overwriting system property key 'java.util.logging.config.file', value 'C:\Users\HP\Desktop\appengine-java-sdk-1.9.27\appengine-java-sdk-1.9.27\config\sdk\logging.properties' with value 'WEB-INF/logging.properties' from 'C:\Users\HP\Desktop\teammates\src\main\webapp\WEB-INF\appengine-web.xml'
Mar 21, 2016 7:22:30 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: Logging to JettyLogger(null) via com.google.apphosting.utils.jetty.JettyLogger
Mar 21, 2016 1:52:38 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: jetty-6.1.x
Mar 21, 2016 1:52:43 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: Started SelectChannelConnector@127.0.0.1:8888
Mar 21, 2016 1:52:43 PM com.google.appengine.tools.development.AbstractModule startup
INFO: Module instance default is running at http://localhost:8888/
Mar 21, 2016 1:52:43 PM com.google.appengine.tools.development.AbstractModule startup
INFO: The admin console is running at http://localhost:8888/_ah/admin
Mar 21, 2016 1:52:43 PM com.google.appengine.tools.development.DevAppServerImpl doStart
INFO: Dev App Server is now running

**Comment by damithc** [comment]
Try to load adminHomePage on the browser and post the dev server console output again.

**Comment by damithc** [comment]
Seems this problem was solved. closing.
