### ISSUE TITLE
Create enum for instructor permissions

### ISSUE THREAD

**Issue by unyoungwax** [TEAMMATES/teammates#5084]
Currently the instructor permissions (e.g. modify course) are represented as constants (`INSTRUCTOR_PERMISSION_MODIFY_COURSE`) in `Const`. It might be a good idea to create an enum for the instructor permissions to simplify some methods and also avoid passing invalid parameters to methods that require instructor permission name as a parameter.

**Comment by xpdavid** [comment]
@damithc @wkurniawan07 
This actually requires a lot of works. So I want to share some basic ideas before doing it.
It can be done by just changing to a `enum` type `InstructorPermission`
``` java
        public enum InstructorPermission {
            MODIFY_COURSE("canmodifycourse"),
            MODIFY_INSTRUCTOR("canmodifyinstructor"),
            MODIFY_SESSION("canmodifysession"),
            MODIFY_STUDENT("canmodifystudent"),
            
            VIEW_STUDENT_IN_SECTIONS("canviewstudentinsection"),
            VIEW_COMMENT_IN_SECTIONS("canviewcommentinsection"),
            GIVE_COMMENT_IN_SECTIONS("cangivecommentinsection"),
            MODIFY_COMMENT_IN_SECTIONS("canmodifycommentinsection"),
            
            VIEW_SESSION_IN_SECTIONS("canviewsessioninsection"),
            SUBMIT_SESSION_IN_SECTIONS("cansubmitsessioninsection"),
            MODIFY_SESSION_COMMENT_IN_SECTIONS("canmodifysessioncommentinsection");
            
            private final String info;
            
            InstructorPermission(String theInfo) {
                info = theInfo;
            }
            
            @Override
            public String toString() {
                return info;
            }
        }
```
I have examined the `InstructorPrivileges` and there are method like `isPrivilegeNameValidForSectionLevel` to check whether it is `section` or `course` level privileges. Since we are going to use `enum`, my suggestions would be removing those methods and divide the `InstructorPermission` into three part `CourseLevel` `SectionLevel` and `SessionLevel`
``` java
public class InstructorPermission {
    public enum CourseLevel {
        ...
    }
    public enum SectionLevel {
        ...
    }
    public enum SessionLevel {
        ...
    }
}
```
Is this acceptable?

**Comment by damithc** [comment]
Perhaps @chowyb can weigh in as he was involved in access control aspect recently. 
@xpdavid this issue's existence doesn't necessarily mean it's something we want to do. You can actually evaluate if it is a good thing to do and propose an alternative. The current access control code is our first attempt at it, so it might even need a full scale upgrade. As it requires some extra analysis, it's also suitable for CS2103R.

**Comment by chowyb** [comment]
Breaking it down into `CourseLevel`, `SectionLevel` and `SessionLevel` seems fine from what I remember, as the permissions are indeed classified into those levels (and checking the more broader permission levels ie. session -> section (more broad) -> course (even more broad) if the section or session is not marked as special). However, I do remember some things that you may need to take note of (or perhaps you already know xD):

1. You will need to create a script to migrate the stored data, as currently the strings used to represent these privileges are stored in the database as well.
An alternative method would be to add additional code to migrate the data when it is loaded (eg. checking if the privileges are still strings in the code, and changing them to enums if they are), although this method is not advised for this particular case.
2. The constant strings at this moment likely cannot be removed, as they are used as `name` attributes in certain `input` elements in the resulting HTML file for editing instructor privileges, and the backend code uses these same strings to check for the parameters from form submission.

Additional: if you are interested in overhauling the current access control code, you might find #3046 interesting

**Comment by xpdavid** [comment]
@chowyb Thanks for explanation. I'll look at it.

**Comment by damithc** [comment]
> You will need to create a script to migrate the stored data, as currently the strings used to represent these privileges are stored in the database as well.
> An alternative method would be to add additional code to migrate the data when it is loaded (eg. checking if the privileges are still strings in the code, and changing them to enums if they are), although this method is not advised for this particular case.

We need both. First we need to deploy a version that works with current legacy data as well as new data. Then, we run the script to migrate existing data. Third, we deploy a new version that is no longer aware of past data. 

Given the workload involved, I'm wondering if we should delay this PR for a more suitable time such as summer vacation.

**Comment by wkurniawan07** [comment]
Closing as this is not a priority right now
