### ISSUE TITLE
New Contributor Self Intro [Divya Pandilla]

### ISSUE THREAD

**Issue by pandilladivya** [TEAMMATES/teammates#5086]
**URLs to my fork and teammates app:**

**My fork**: https://github.com/pandilladivya/teammates/tree/tinker
**My app**: http://v4-dot-teammates-divya.appspot.com/

**Changes made:**

Added contents to features.html

![change](https://cloud.githubusercontent.com/assets/16818129/13925878/118e699c-efb0-11e5-82f0-4a39b69fa596.PNG)

**About Me**

I am Divya Pandilla, currently pursuing my undergrads in IT department from KMIT(www.kmit.in) ,Hyderabad.Apart from academia I am also working as an intern in Teleparadigm Networks Lmt (www.teleparadigm.com) in eLearning Domain. 

I have created a module for bulk upload of courses and students. At the time of uploading the students, we can even enroll them into predefined courses. Bulk upload can be done by users with certain privileges. The bulk upload takes various formats like xml ,csv ,excel as well as json format. This module was further extended to pull data from various sources like db, excel, csv , xml in various formats from different LMS's and convert it into our format and then upload it. I followed adapter desgin pattern for it.

I was also involved in implementing a forum for the LMS where the users(teachers,students,teaching assistant) can create a topic and keep posting their comments into it. The users can reply for the comments based on their privileges. These topics can be sorted based on the latest , oldest , nested reply format. I have also varied interest in developing android apps which are on the way to google store. During my course of internship I have learnt j2ee, xml , json, jquery, hibernate.

I am getting familiar with your code base and i have also worked with issues  #5020 #5065 and #5070 and am willing to solve more issues. 

Looking forward to work this summer with you.
Thank You

**Comment by taniach** [comment]
Welcome to the TEAMMATES contributor community @pandilladivya , good work on moving into Phase D and following the instructions. Great to know you started working on issues. 

One question - are you an aspiring GSoC applicant?

**Comment by pandilladivya** [comment]
@taniach 
Thank you for the review 
Yes,I want to apply for Teammates for this year of Google Summer of Code

**Comment by pandilladivya** [comment]
kindly review my proposal :)
Thank you!

**Comment by damithc** [comment]
Comment added.

**Comment by pandilladivya** [comment]
@damithc 
please review the other proposal 

Thank you!

**Comment by pandilladivya** [comment]
I have made changes to the draft.
Kindly review @damithc 

Thank you :)
