### ISSUE TITLE
Gsoc 2016(comments)

### ISSUE THREAD

**Issue by ajay-sai** [TEAMMATES/teammates#5092]
Iam M .Ajay Sai of 3rd year SRM . I finished the setting up and running test cases ,I am finished with the stages .Can you help me with a bug I can fix ,and  to contact Josephine madam would be great thanks :)

**Comment by wkurniawan07** [comment]
@JosephineKwa here you go madam :joy::joy::joy:

**Comment by damithc** [comment]
@ajay-sai you can select an issue with `d.firstTimers` label
