### ISSUE TITLE
Remove unused imports

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#5100]
There are a few warnings in eclipse showing unused imports. 
Such as in InstructorCoursesPageUiTest.java, org.openqa.selenium.By is never used.

**Comment by yasirunilan** [comment]
PR added .

**Comment by yasirunilan** [comment]
Another PR added.Kindly review

**Comment by wkurniawan07** [comment]
This got fixed when we added the static analysis tools.
