### ISSUE TITLE
Remove unused items in PageData.java

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#5101]
At present:
- ~~Global constant `DISABLED`~~
- Methods `getPointsInEqualShareFormatAsHtml`, `getP2pFeedbackAsHtml`, `getGracePeriodOptionsAsHtml`, `getTimeOptionsAsHtml`
- Methods `isResponseCommentVisibleTo` and `isResponseCommentGiverNameVisibleTo` which take in 3 parameters.

More to be added if found.

**Comment by ManrajGrover** [comment]
@kanghj I'll take this one up. Please assign this issue to me.

**Comment by kanghj** [comment]
@ManrajGrover, thanks for your interest in this. There's no need to get assigned to work on an issue. Just make a pull request following our [development process](https://github.com/TEAMMATES/teammates/blob/master/devdocs/process.md) when you are ready.
