### ISSUE TITLE
studentPageCustom.tag and instructorPageCustom.tag are unnecessary

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#5102]
Both are outright duplications of their non-custom counterparts.

**Comment by yj-soh** [comment]
They are?

**Comment by wkurniawan07** [comment]
As much as how `statusMessage.tag` and `statusMessageWithoutFocusingToStatus.tag` were. #4070

**Comment by yj-soh** [comment]
I believe this was mainly for performance, though it may have been premature optimisation.
If we go solely with the custom version, it would require an additional if check on every load of any of the student / instructor pages (though I'm not sure if it's just the initial load or consequent ones too).

**Comment by wkurniawan07** [comment]
Very premature. Two conditionals, and both are one liners, are not worth it if you trade it with almost-outright duplication of codes.
