### ISSUE TITLE
New contributor:self intro [Viet Thang]

### ISSUE THREAD

**Issue by vietthang207** [TEAMMATES/teammates#5110]
Hi, my name is Dinh Viet Thang, a year 2 student from National University of Singapore.
I apply to become PowerPointsLabs contributor. However, I have no prior experience in C# so Prof. Damith tells me to work on Teammates first before he can accept me to PowerPointsLabs team.

So right now I am having issue with Teammates Dev server. The server start normally, but when I key in some email, the server throw exception.
![image](https://cloud.githubusercontent.com/assets/16717647/13963118/169f9a4c-f09f-11e5-9ab6-a85d3b15e97c.png)

**Comment by damithc** [comment]
@wkurniawan07 is this mentioned in our troubleshooting guide? If not, I think it is common enough to be mentioned there.

**Comment by wkurniawan07** [comment]
It actually is already in the troubleshooting guide.
@vietthang207 to save you some time, for that particular error, check that you have created (copy/paste the template then rename) `build.properties` and `appengine-web.xml`.

**Comment by vietthang207** [comment]
Thanks you so much, I miss the build.property.

**Comment by vietthang207** [comment]
This is the link to my app:
http://4-18-dot-teammates-vietthang207.appspot.com/index.html
Link to my fork:
https://github.com/vietthang207/teammates
Change made: 
       + change the current pointer in the navigation bar
       + navigation bar is now moving as you scroll down
       + change the background a little bit
Original:
![image](https://cloud.githubusercontent.com/assets/16717647/14015427/d41bbcea-f1f3-11e5-894c-e8bf36ea4e92.png)
New one:
![image](https://cloud.githubusercontent.com/assets/16717647/14015438/e766ffb2-f1f3-11e5-8432-2638f7172ead.png)

My name is Dinh Viet Thang, a year 2 student from National University of Singapore. Although I apply for GSoC under PowerPointLabs, I was requested to work something on Teammates. It is a nice and big project, and I would love to contributing to it.
