### ISSUE TITLE
New contributor self intro [Khac Tung] + Attempt to fix #5012

### ISSUE THREAD

**Issue by tungnk1993** [TEAMMATES/teammates#5111]
a) link to app: [https://teammates-nkt.appspot.com/index.html](https://teammates-nkt.appspot.com/index.html)
b) link to fork: [https://github.com/tungnk1993/teammates](https://github.com/tungnk1993/teammates)

c) My latest commit attempts to fix #5012 (To see the change on staging server, it requires instructor access so I don't know how to let dev check on my app)

![after_fix](https://cloud.githubusercontent.com/assets/3363879/13968742/569a2076-f0b9-11e5-9c02-a2f20cd4f4f7.PNG)

d) 
Real name: Nguyen Khac Tung. NUS CS Year 3, Focus Area: Information Retrieval. Interested in full-stack development. Have worked on small projects before, hopes to learn more from contributing to this large project

**Comment by junhaoyap** [comment]
Welcome to the TEAMMATES contributor community @tungnk1993, good work on moving into Phase D and following the instructions!

I see you have already tried to tackle an issue - which is great! However that issue that you're working on is already being worked on by @YongJieYongJie - perhaps you can pick a first timer issue to help yourself get into the flow of things and be familiarized with the system and process?

Also, are you an aspiring GSoC applicant?

**Comment by tungnk1993** [comment]
Tks @junhaoyap for the reply. Sorry for the duplication as I didn't see his reference commit at the time. I picked #5105 as a first-timer issue ([link to branch](https://github.com/tungnk1993/teammates/tree/5105-update-qunit-ver-1.22) to familiarize with the process.

Not really that aspiring, just another applicant i guess :)

**Comment by junhaoyap** [comment]
@tungnk1993 no worries as long as you're applying, you're aspiring ;) When you have a issue fixed, you can open a pull request and we'll take a look at it, don't leave it on a branch or the work might never be seen!
