### ISSUE TITLE
Add a 'Table of Content' to the settingUp.md

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5112]
Add a hyperlinked table of content at the top of `/devdocs/settingUp.md`

**Comment by krishnilak** [comment]
https://github.com/krishnilak/teammates/tree/tinker

**Comment by damithc** [comment]
@krishnilak if you would like to fix this issue, please submit a PR. Remember to follow the development process we have specified in our project documentation.

**Comment by krishnilak** [comment]
https://github.com/TEAMMATES/teammates/pull/5130

**Comment by krishnilak** [comment]
Add a 'Table of Content' to the settingUp.md #5112
https://github.com/TEAMMATES/teammates/pull/5130

**Comment by krishnilak** [comment]
Add a 'Table of Content' to the settingUp.md #5112
https://github.com/TEAMMATES/teammates/pull/5130

**Comment by dustinlapierre** [comment]
By hyperlinks do you mean anchors to the different sections of the settingUp.md document?
