### ISSUE TITLE
New contributor:self intro[Harshvardhan Singh]

### ISSUE THREAD

**Issue by Harshvardhan58** [TEAMMATES/teammates#5121]
(a) Link to the App: http://4-18-dot-teammates-master.appspot.com
(b) Link to my fork: https://github.com/Harshvardhan58/teammates.git
(c) 
   **original:**
![image](https://cloud.githubusercontent.com/assets/13389806/13987034/a86d7d0e-f12b-11e5-8fcf-ef24ba4f022c.png)
   **modified:**
![image](https://cloud.githubusercontent.com/assets/13389806/13987085/ec777f0e-f12b-11e5-8bdd-a73a7a1de5c5.png)

   When hover:
      **Picture 1:**
![image](https://cloud.githubusercontent.com/assets/13389806/13987146/2830a430-f12c-11e5-9a28-8f6b0893b8b3.png)
      **Picture 2:**
![image](https://cloud.githubusercontent.com/assets/13389806/13987189/5c57ef52-f12c-11e5-99f3-0aab6605e629.png)

(d) **self intro:**
   Hey! I'm Harshvardhan Singh from Techno India NJR college (Udaipur, RAJ, INDIA). I am pursuing B.TECH in Computer Science, 2nd year. Programming is my passion. I love to do programming using **Java**, **JavaScript**, **HTML** and **CSS**.I will give my 100% to this awesome project. Thanks!

**Comment by junhaoyap** [comment]
@Harshvardhan58 You don't have to create a new issue when changing - you could have just edited the first post but that's ok cause I got you :)

Please refer to our 'Instructions for Google Summer of Code Applicants' for guidance on how you can move forward in applying to contribute to TEAMMATES under GSoC :)
