### ISSUE TITLE
New contributor:self intro[Krishni Andradi]

### ISSUE THREAD

**Issue by krishnilak** [TEAMMATES/teammates#5123]
a)Link to the app 
_**http://teammatesv4.appspot.com/**_
b) Link to my fork
_**https://github.com/krishnilak/teammates**_
c) The change done (i attached some .gif files, it contains animation)
**original:**
**_https://drive.google.com/file/d/0B7Y2NSLI2MwyN2I0TjE5VkdRT2s/view?usp=sharing_**
**after changing**:
_**https://drive.google.com/file/d/0B7Y2NSLI2MwyTHh5VUJjZG5pUnM/view?usp=sharing**_
d) Real name and a short self-intro
I'm Krishni Andradi.
Computer Engineering Undergraduate University of Peradeniya, Sri Lanka.
I'll do my best for this project if i got a chance

**Comment by taniach** [comment]
Welcome to the TEAMMATES contributor community @krishnilak , good work on moving into Phase D and following the instructions!

Please refer to our 'Instructions for Google Summer of Code Applicants' for guidance on how you can move forward in applying to contribute to TEAMMATES under GSoC apart from sharing your draft with us :)

It'll be great if you can pick a few first timer issues and start contributing!

**Comment by krishnilak** [comment]
Ok taniach
Thank You
