### ISSUE TITLE
Same email id has been allowed to access Instructor and Student account

### ISSUE THREAD

**Issue by rajivjhaimin** [TEAMMATES/teammates#5124]
Greetings, 
I registered myself as student and instructor with same email address and have access to both accounts.
Steps i did:
		1.Registered myself as instructor (rajivjha1996@gmail.com)
		2.Then added my email address as student also in one of the course.(That is allowed)
                3. Go to a different browser and opened my student's portal with the same email address.
		
I did it on my localhost and live app too.
According to me this addition shouldn't be allowed and there must be a check on each email address that whether it is being used by an instructor or not.
Teacher won't do this intentionally, but it will create transactional issue at the database level.

![image](https://cloud.githubusercontent.com/assets/14246533/14016315/6c101212-f1e5-11e5-9842-91b8c34c2a93.png)

**Comment by damithc** [comment]
Thanks for the bug report. Yes, it appears odd at first, but this is an intended behavior. Instructors (especially, new users) can add themselves as a student to experience the system from a student point of view. 
Let us know if you discovered a concrete problem with the intended behavior.
