### ISSUE TITLE
New Contributor Self Intro [yvsssantosh]

### ISSUE THREAD

**Issue by yvsssantosh** [TEAMMATES/teammates#5125]
Hello,

I've successfully set up the developer environment with the instructions given

**Link to my app** - v4-dot-teammates-santosh.appspot.com
**Link to my fork** - https://github.com/yvsssantosh/teammates

**About Me**

My name is **Y V S S Santosh** and I'm from Keshav Memorial Institute Of Technology, Hyderabad , India currently pursuing my CS year III.
I've already worked on e-Learning Management System and I was one of the contributors for Telescope (www.teleuniv.net). 

I have developed a grading and evaluation tool for my college.This tool provides platform for lot of languages like java,c,pascal,hadoop,R,Python,c++,MySql etc., where the student can practice his lab sessions.These exercises have test cases based on which the student is graded and reports were generated.I have build this plugin on moodle.These exercises are based on only programming languages.The web version has become stable and am currently creating an android native app for it.

My focus on Telescope was to work on sending emails to students, providing the students Intelli-Sense so that the effort to write chunks of code is reduced and students have a greater time developing the logic and understanding the problem at hand, and finally the reports module which evaluates the student based on the performance in the course. To analyze performance of the student exams are conducted with a time limit and responses submitted are validated against many test-cases

I'd like to contribute to Teammates and am hoping to work with you guys for GSoC 2016

Links to the issues I'm solving/solved 

https://github.com/TEAMMATES/teammates/issues/4744

https://github.com/TEAMMATES/teammates/issues/4771

I am getting familiar with your platform and the code.I am also working on other issues.

Thank You

**Comment by junhaoyap** [comment]
Welcome to the TEAMMATES contributor community @yvsssantosh, good work on moving into Phase D and following the instructions!

Please refer to our 'Instructions for Google Summer of Code Applicants' for guidance on how you can move forward in applying to contribute to TEAMMATES under GSoC :)

It seems you have already started contributing so awesome job there! Looking forward to more of your contributions :+1:

**Comment by yvsssantosh** [comment]
I've sent 3 proposals for teammates via the official GSoC portal

Kindly review
@damithc

**Comment by yvsssantosh** [comment]
I've raised an issue and solved it too

#5197 

Looking forward to work with more issues :)
