### ISSUE TITLE
SettingUp.md: recommend Source Tree instead of GitHub for Windows

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5131]
The current SettingUp.md says `Install GitHub for Windows/Mac (recommended), or at least, Git`

Should be changed as `Install Source Tree or other similar Git Client, or at least Git`.

**Comment by manparvesh** [comment]
updated, please check

**Comment by yash2o1o** [comment]
Hi i am a first timer and wanted to contribute. Is this issue still relevant?

**Comment by samsontmr** [comment]
@yash2o1o yes it is, please go ahead!

**Comment by amarlearning** [comment]
@samsontmr I think this issue should be closed by now.

**Comment by samsontmr** [comment]
@amarlearning Yes, I just checked and the issue is still valid.

**Comment by amarlearning** [comment]
@samsontmr Yes, you are right. 
It's the first step of [Install necessary tools and languages](https://github.com/TEAMMATES/teammates/blob/master/docs/settingUp.md#step-1-install-necessary-tools-and-languages)
As, I am already done with my `d.FirstTimers`, so i will leave this for someone else :smile:
