### ISSUE TITLE
New Contributor Self Intro [Sachithra Sewwandi]

### ISSUE THREAD

**Issue by SachithraSewwandi** [TEAMMATES/teammates#5132]
I have successfully setup developer environment on my laptop 
Link to my fork: https://github.com/SachithraSewwandi/teammates

I have made a UI change in the index page

Previous image : https://drive.google.com/drive/folders/0B6Kh3x0Z7lv4VGI4ajBZMGRoNnM
After UI change : https://drive.google.com/drive/folders/0B6Kh3x0Z7lv4VGI4ajBZMGRoNnM

I am Sachithra Sewwandi from Faculty of Engineering University of Peradeniya and I am specializing Computer Engineering, I would like to contribute to teammates on GSCO 2016

Thank You
sachithra

**Comment by junhaoyap** [comment]
Welcome to the TEAMMATES contributor community @SachithraSewwandi, good work on moving into Phase D and following the instructions!

Please refer to our 'Instructions for Google Summer of Code Applicants' for guidance on how you can move forward in applying to contribute to TEAMMATES under GSoC :)

It'll be great if you can start looking at some first timer issues and start getting into the hang of contributing!
