### ISSUE TITLE
New Contributor intro [Nikhil]

### ISSUE THREAD

**Issue by m-nikhil** [TEAMMATES/teammates#5137]
Hi, 
    I am Nikhil, from Amrita University (Coimbatore,India). Doing B.Tech in Computer Science.
I feel comfortable at programming cpp,python,html,css,js,php. And also a knowledgeable in java,ajax,mysql. I have applied for Data Upload and Rich-text support for this GSoc,2016. 

link to my github :  https://github.com/m-nikhil/teammates.git

After adding changes to the UI: 
**Made the navbar responsive. THESE ARE THE SNAPS OF MOBILE VIEW**
![screenshot 56](https://cloud.githubusercontent.com/assets/11210096/14053195/9eddadf6-f2f5-11e5-9943-9d7dc73b2d4e.png)

![screenshot 57](https://cloud.githubusercontent.com/assets/11210096/14053221/bb4df72a-f2f5-11e5-9a1d-3e4f55d1eeef.png)

Looking forward to contribute :)  Can anyone say where can I start contributing?  
-------------------
Nikhil.
m_nikhil@outlook.com

**Comment by rajivjhaimin** [comment]
Hi Nikhil ! 
https://docs.google.com/document/d/1cY9pmEmw4dC6Z4LjN1WUTsynJ0jVPgbWsFhdyBy_wCU/pub?embedded=true  - Contributor Orientation Guide
https://github.com/TEAMMATES/teammates/blob/master/CONTRIBUTING.md - to start contributing
https://github.com/TEAMMATES/teammates/blob/master/devdocs/process.md - process to contribute, it's a must read document as it contains the details about branching and pull requests.
Hope it help, 
Cheers :)

**Comment by junhaoyap** [comment]
Welcome to the TEAMMATES contributor community @m-nikhil, good work on moving into Phase D and following the instructions!

Please refer to our 'Instructions for Google Summer of Code Applicants' for guidance on how you can move forward in applying to contribute to TEAMMATES under GSoC :)

Thank you @rajivjhaimin for chipping in but he's absolutely right - I look forward to some of your contributions @m-nikhil :+1:
