### ISSUE TITLE
Godmode should sanitize Text nodes when converting into standard HTML

### ISSUE THREAD

**Issue by bamboo3250** [TEAMMATES/teammates#5142]
When converting page source into DOM Document and Node, the content of Text nodes are always unsanitized by default. There will be a problem if we use and convert the HTML output with unsanitized content one more time into standard HTML to compare with the actual page source. If there are mismatches, the standard HTML of `expected` seems broken.

**Comment by thyageshm** [comment]
@bamboo3250 I do not understand the problem you are trying to solve here. Could explain further as to what the issue is? Also, an example would help :-)

**Comment by bamboo3250** [comment]
@thyageshm In our test case, there is a team named `Team 1</td></div>'"`. Before showing on web page, it is sanitized to `Team 1&lt;&#x2f;td&gt;&lt;&#x2f;div&gt;&#39;&quot;`. However, when Godmode creates Document, those strings are unsanitized back to `Team 1</td></div>'"` and writes them into output files. The next time Godmode reads those output file, it cannot produce the same output because of those `</td></div>` are treated as HTML elements while they should be just texts.

![image](https://cloud.githubusercontent.com/assets/8078323/14064340/0ce84116-f432-11e5-90a5-87451a0d944a.png)

**Comment by thyageshm** [comment]
Got it, nice :+1:
