### ISSUE TITLE
Implement dynamic zooming and panning for user map

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#5145]
What #5001 originally was about. It still will be a good addition for the user map.

**Comment by damithc** [comment]
Given the purpose of the map, I'm not sure we need to go as far as zooming/panning. I'll put as low priority for now.

**Comment by AnaghHegde** [comment]
@damithc i am recently done with my FirstTimers issue. Can i work on this?. Is it still open ?.

**Comment by damithc** [comment]
@AnaghHegde I would say this is a VERY low priority issue, but you can take it up if other `d.Contributors` issues are not to your liking.

**Comment by AnaghHegde** [comment]
@damithc can you suggest some the issues so that i can know which are important ( priority ) because many issues are very old ( 2 years ) .

**Comment by damithc** [comment]
@AnaghHegde it's ok to pick old issues.

**Comment by AnaghHegde** [comment]
@damithc @wkurniawan07  In dynamic zooming as the zooming increases we need the only the institution name to be shown right ?.

**Comment by AnaghHegde** [comment]
@wkurniawan07 @damithc Can you please confirm if my approach is right?. So that i can start working on this.

**Comment by damithc** [comment]
> In dynamic zooming as the zooming increases we need the only the institution name to be shown right ?.

No I don't think so. Just make the map bigger (without making pins bigger) so that easier to see smaller countries? @wkurniawan07 is that what you had in mind? @paradite any input?

**Comment by AnaghHegde** [comment]
@damithc 
>
No I don't think so. Just make the map bigger (without making pins bigger) so that easier to see smaller countries?

If the institutions increases then we still have the same problem. Isn't it ?

**Comment by damithc** [comment]
> If the institutions increases then we still have the same problem. Isn't it ?

What do you mean?. The map shows one pin per country, not one pin per institution.

**Comment by wkurniawan07** [comment]
> Just make the map bigger (without making pins bigger) so that easier to see smaller countries?

My concerns exactly, because we currently have a clutter of pins especially in the Eastern Europe region:

![screen shot 2017-01-24 at 9 55 05 pm](https://cloud.githubusercontent.com/assets/7261051/22249945/08d39372-e280-11e6-98f4-1c3ccd185994.png)

**Comment by damithc** [comment]
@AnaghHegde is the problem clear? If so, we'll leave you to figure out a suitable solution and propose it to us.

**Comment by AnaghHegde** [comment]
@damithc 

>You meant to increase the map size?

Am i right or wrong ?

If yes we can just increase the width and the scaling of the pins will be same.

**Comment by paradite** [comment]
hi @AnaghHegde @damithc, I think a complete solution would involve:
- **zooming** of the map, which is done through scaling, I believe the original library that I was using for the map already has this function, you just to make it adjustable for the user
- **panning** of the map, which allows part of the map to be enlarged and pan around the map while maintaining the overall size (width and height) of the map constant. This means we **should not** make the whole map bigger, but rather, keep the **viewport size constant** and zoom into a part or pan to other parts. This can be done by adjusting the limits of the map in terms of the coordinates.

**Comment by paradite** [comment]
However, I do also think this is a minor issue which may take up a lot of time in designing the UI, so maybe not the most suitable issue to work on unless you have a lot of free time.

**Comment by AnaghHegde** [comment]
@paradite Its like google map (where the view size will be same for a user) but when you zoom in you can see the things more clearly. 
  
I will work on this whenever i have a free time.

**Comment by paradite** [comment]
Yes. And I believe if we change to Google Maps API directly instead of d3 and TopoJSON, we can implement these features trivially:

https://developers.google.com/maps/documentation/javascript/

The downside of that approach is the dependency on Google Maps service at run time, since the Google Maps library cannot be loaded offline.

**Comment by AnaghHegde** [comment]
@paradite wouldn't it affect a lot (changes to be done) if we switch from d3 and TopoJSON to Google Maps API ?.If that's okay i can look into it.

**Comment by paradite** [comment]
Yes. It would affect a lot of code, but zooming and panning will come as built-in features. So I leave it to @damithc and @wkurniawan07 to decide if that's a good approach should you work on this issue.

**Comment by AnaghHegde** [comment]
@wkurniawan07 @damithc 

> And I believe if we change to Google Maps API directly instead of d3 and TopoJSON, we can implement these features trivially:

https://developers.google.com/maps/documentation/javascript/

The downside of that approach is the dependency on Google Maps service at run time, since the Google Maps library cannot be loaded offline.

What is your opinion on this?. Is this ok?.

**Comment by AnaghHegde** [comment]
@wkurniawan07 @damithc Is this a good idea to use Google Maps API like @paradite suggested. If this ok i will start work on this. Or should i need to come up with a different idea.

**Comment by damithc** [comment]
I think we'll leave this alone for now. Not a high priority at the moment.
