### ISSUE TITLE
Better styles for numbers in the user map

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5146]
![image](https://cloud.githubusercontent.com/assets/1673303/14075772/9e8bc78c-f50e-11e5-862d-ced9ae193fe9.png)
The institute and country count can be shown in bigger orange letters (similar to how entry count is shown in home page).
The last updated time can be shown in gray letters at the bottom right hand corner of the map.

**Comment by Harshvardhan58** [comment]
#

**Comment by Harshvardhan58** [comment]
I want to work on this issue.

**Comment by damithc** [comment]
Go ahead @Harshvardhan58. Please remember to follow the process as giving in our documentation.

**Comment by Harshvardhan58** [comment]
I am not able to find the page where I need to make changes. Can you please help me

**Comment by Harshvardhan58** [comment]
I have got the issue and I will do it by tomorrow.


Thank you

**Comment by yasirunilan** [comment]
PR added please review.
