### ISSUE TITLE
admin create account page: data format can be misleading

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5162]
These brackets can be misleading (the actual format does not require brackets)
![image](https://cloud.githubusercontent.com/assets/1673303/14148235/3ec8187c-f6d1-11e5-8c19-dfd9bc3662be.png)

**Comment by yasirunilan** [comment]
actual format doesn't require brackets,but it requires the vertical bar right??

**Comment by damithc** [comment]
Yes

**Comment by yasirunilan** [comment]
So giving an example line below will do the thing.Is that OK?

**Comment by yasirunilan** [comment]
Or either can add a sentence that says enter without the brackets.

**Comment by damithc** [comment]
The previous PR had a suitable fix, but it was in the wrong place. You can refer that one.

**Comment by yasirunilan** [comment]
Yeah sure.I'll refer that.

**Comment by yasirunilan** [comment]
Added a fix,please review.
