### ISSUE TITLE
Add TEAMMATES to https://github.com/MunGell/awesome-for-beginners

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5194]

**Comment by songchoa** [comment]
I submitted a PR for adding TEAMMATES to "awesome-for-beginners". I'll let you know when the PR gets accepted.

**Comment by damithc** [comment]
Thanks @songchoa. Keep us posted.

**Comment by songchoa** [comment]
@damithc TEAMMATES is there.

**Comment by damithc** [comment]
Great. Thanks @songchoa
