### ISSUE TITLE
Convert Developer Troubleshooting Guide to markdown

### ISSUE THREAD

**Issue by yvsssantosh** [TEAMMATES/teammates#5195]
Currently the developer troubleshooting guide is on the link below

https://docs.google.com/document/d/1_p7WOGryOStPfTGA_ZifE1kVlskb1zfd3HZwc4lE4QQ/pub?embedded=true

This would be good to have a markdown file for this

**Comment by yvsssantosh** [comment]
I've put a PR
Kindly review

@damithc

**Comment by wkurniawan07** [comment]
Fixed in #5197.
