### ISSUE TITLE
CSV file missing reponses if the session name has extra space

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5249]
Can publish but cannot download results.

**Comment by damithc** [comment]
@bamboo3250 @kanghj @wkurniawan07

**Comment by kanghj** [comment]
I am not able to replicate this issue. Do we have more information about this?

**Comment by damithc** [comment]
Actually, the file can be downloaded but the 'feedback' column says 'No response' for every row. Only one team has '#' in the team name.
![image](https://cloud.githubusercontent.com/assets/1673303/14942262/d4c16604-0fe9-11e6-86df-afab6cfa7643.png)

**Comment by damithc** [comment]
BTW, the course has another session that was done previously (seems to be the same questions), but the downloaded data for that session seems fine.

**Comment by damithc** [comment]
And the responses can be viewed on the web page. So it is specific to CSV generation.

**Comment by kanghj** [comment]
Most likely, it has nothing to do with the team name. It looks like a similar problem to #5122, where an extra space in the session name is removed, causing the logic using the session name to become incorrect.

**Comment by bamboo3250** [comment]
So we have `FeedbackQuestionAttributes`, `FeedbackResponseAttributes`, FeedbackResponseAttributes` and `FeedbackSessionAttributes` that have `feedbackSessionName`. Is there anything else?

**Comment by kanghj** [comment]
@bamboo3250, That should be all. But I think we might not need to migrate the feedback session name if all the entities saved the field in a consistent manner. We just need to pass the unmodified feedback session name to the form on the results page to download the results.

**Comment by bamboo3250** [comment]
There is still one thing I wonder. Why does it only affect CSV but not the web page?

**Comment by kanghj** [comment]
Actually the web page is affected too. The status message that says that there are no responses yet is actually triggered. It only succeeds in loading the responses when we try to load responses by the question.

**Comment by kanghj** [comment]
@bamboo3250, I think we have to write a script to migrate the responses. FeedbackResponseAttributes <code>sanitizeForSaving</code> should not modify the feedback session name.

**Comment by damithc** [comment]
We need a quick fix as the user needs this data to calculate final grades which she needs to release soon.

**Comment by damithc** [comment]
I went to the database and removed the extra space from the Session object and Question objects. Now the results can be downloaded (although the link sent to students for viewing results will not work anymore)

**Comment by damithc** [comment]
Any fix for this?

**Comment by kanghj** [comment]
@bamboo3250, will you be fixing this?
