### ISSUE TITLE
Extra "the" and comma in design.md

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#5251]
An extra "the" and comma can be found in design.md, under `UI -> Request flow -> Things to note`

![design](https://cloud.githubusercontent.com/assets/7546744/14951879/9ef4cebc-108e-11e6-8e73-39c7ef1bde4d.png)

**Comment by chowyb** [comment]
@damithc I found another error in the document, should I add on to this issue or make a new one?

**Comment by damithc** [comment]
As we are short of firstTimers issues, you can add it as a separate issue.

**Comment by AakanxuShah** [comment]
@chowyb : I am interested in this one too ! Should I go ahead and fork the project ?
