### ISSUE TITLE
Typo in design.md: mechanims

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#5252]
Under the `Logic` section, just before the diagram, there is a typo in the word "mechanism".

![design2](https://cloud.githubusercontent.com/assets/7546744/14954317/04f4f830-10a4-11e6-8467-984c4f8ac0ad.png)

**Comment by damithc** [comment]
Updated the issue title to be more specific.

**Comment by shr7** [comment]
Hi, @chowyb  since @AakanxuShah  has decided to work instead on #5603 can I take up this one?
I am new to open source contributions.
