### ISSUE TITLE
Accounts of admin, instructor and student for testing purpose. 

### ISSUE THREAD

**Issue by tarun14110** [TEAMMATES/teammates#5254]
Could someone please tell me the accounts of admin, instructor and student for testing purpose. 
test@example.com is not working for me anymore.
For instructor login , CFResultsUiT.instr is working fine.
![screenshot from 2016-05-03 19 55 12](https://cloud.githubusercontent.com/assets/12219700/14986325/fbc95948-1168-11e6-8b03-e05550518f90.png)

**Comment by damithc** [comment]
You need to create instructor accounts yourself. There are no built-in accounts. Some accounts created during testing remains after testing though e.g. CFResultsUiT.instr

**Comment by tarun14110** [comment]
whats the admin Id Sir ?

**Comment by wkurniawan07** [comment]
Hi @tarun14110, as mentioned, there are no built-in accounts. For dev server, any ID will be granted admin access as long as you tick `Sign in as Administrator`. This would work even if the ID is not a registered instructor/student.

**Comment by tarun14110** [comment]
@wkurniawan07  I am not able to login through the Instructor Id, which I added through admin. 

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/12219700/14993755/f8e29200-1189-11e6-9fef-bd8309f2ba49.gif)

**Comment by damithc** [comment]
The new instructor needs to join TEAMMATES. I think this procedure is described in settingUp.md

**Comment by tarun14110** [comment]
oh, I missed that. sorry for trouble . You can close this issue sir.
