### ISSUE TITLE
Participants who have not responded panel: html tag incorrectly displayed as text

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#5266]
![wronginstructors](https://cloud.githubusercontent.com/assets/2216119/15079408/e92a29fa-13ea-11e6-868b-e3bd816a92af.PNG)

A bug introduced in #5058,

**Comment by damithc** [comment]
How bad is this? Should not occur under typical circumstances right?

**Comment by kanghj** [comment]
It happens when instructors need to give feedback in a feedback session, but not all instructors have responded.
