### ISSUE TITLE
Standardize use of frontend validation

### ISSUE THREAD

**Issue by YongJieYongJie** [TEAMMATES/teammates#5274]
Currently frontend validation is used when adding course:
![image](https://cloud.githubusercontent.com/assets/14101781/15107997/f0bbc328-1605-11e6-8f86-d3c38bbfd677.png)

But the other validations are all backend; e.g.:
![image](https://cloud.githubusercontent.com/assets/14101781/15108030/26828cbc-1606-11e6-81ba-2bbcac1bc4d4.png)

Perhaps we can implement frontend validation across the board, because frontend validation is much faster, and since user can be alerted before even clicking the submit button, there is no breaking of flow.

E.g., of backend validation breaking flow: when adding instructor to course, if input is invalid, the whole page will be refreshed, the scroll position will be lost, and the user needs to click button to add new instructor again.

**Comment by damithc** [comment]
Let's use backend validation here as well. Adding front-end validation is to be discussed separately.

**Comment by YongJieYongJie** [comment]
There is already some backend validation for when adding a new course, but the error message is misleading:
![image](https://cloud.githubusercontent.com/assets/14101781/15131862/525bb676-1686-11e6-8356-a956fb336a45.png)

Specifically, it does not inform user of invalidity in course name. I will check where to add the missing error message.

**Comment by damithc** [comment]
Can close if this issue is no longer valid or superseded by other issues.
