### ISSUE TITLE
Misleading error messages from backend validation when adding course

### ISSUE THREAD

**Issue by YongJieYongJie** [TEAMMATES/teammates#5277]
The error message is misleading:
![image](https://cloud.githubusercontent.com/assets/14101781/15131862/525bb676-1686-11e6-8356-a956fb336a45.png)

Specifically, it assumes any problem will be with the course ID, and does not inform user of invalidity in course name.

**Comment by wkurniawan07** [comment]
I could think of one sure way to solve this and #5274: refactor (or even rewrite) `FieldValidator`. That class is quite messy right now :p

**Comment by YongJieYongJie** [comment]
@wkurniawan07 
Yup yup, I had some fun exploring and working on `FieldValidator` few weeks ago, but the PR got too big. Shall churn out smaller issues regarding `FieldValidator` and start working on them.
