### ISSUE TITLE
Refactor instructorFeedbackResults<...>.js

### ISSUE THREAD

**Issue by belyabl9** [TEAMMATES/teammates#5329]
The content of these source files is almost identical. Only 'question' sort type has significant differences, but there are also common parts.
I propose to extract such common logic into one or some functions in instructorFeedbackResults.js

**Comment by johnsv** [comment]
Hi! Me and four other CS students at KTH are doing a project where we would like to work on this issue. Is this ok for you and are you interested in solving this issue?

**Comment by belyabl9** [comment]
Hello @johnsv,
Sure, if it's still actual. I've started working full-time after finishing GSOC program, so don't have time for this project at the moment

**Comment by matteushast** [comment]
To reduce complexity we decided not to extract the logic from the Question type.
