### ISSUE TITLE
Preferable way of checking if string is empty

### ISSUE THREAD

**Issue by belyabl9** [TEAMMATES/teammates#5331]
Looking through the code, I've found that we use two approaches to determine if string is empty
1. String.isEmpty    // 485 occurrences
2. String.equals("") // 73 occurrences

I think it'd be great to use the only variant for such common logic.
As for me, 1st variant (isEmpty) is more preferable because it's more semantic and faster based on open sources (just length check)

**Comment by wkurniawan07** [comment]
Not something that we can enforce, but I personally prefer `isEmpty()` as well.

**Comment by damithc** [comment]
I prefer `isEmpty()` too

**Comment by kanghj** [comment]
PMD has a rule for this that I can add next

**Comment by damithc** [comment]
@belyabl9 go ahead and create a PR
