### ISSUE TITLE
Should we use Hashmap, instead array of Strings for populateTemplate in common.util.FeedbackQuestionFormTemplates

### ISSUE THREAD

**Issue by tarun14110** [TEAMMATES/teammates#5342]
In common.util.FeedbackQuestionFormTemplates, populateTemplate method uses array of string for key value pair for replacing strings.
Shouldn't we use Hashmap, instead array of Strings ?

using HashMap will
1. avoid multiple substitutions at the same index position. Let template_string => "abcd" and sub-string array of values =["a","b","c","d"] .It means replace 'a' with 'b' and 'b' with 'c'. replace in a first step "a" to "b" and in a second step "b" to "c" which would lead into an unexpected effective replacement of "a" to "c".
2. iterate only once over template String.
3. don't create for each replacement pair a new String object, as it would have been here populatedTemplate = populatedTemplate.replace(values[i], values[i+1]);

```

String template = "abcd";
StringBuilder populatedTemplate = new StringBuilder();
HashMap<Character, Character> map = new HashMap<>();
map.put('a', 'b');
map.put('b', 'c');
for (int i = 0; i < template.length(); i++) {
    populatedTemplate.append(
            map.getOrDefault(template.charAt(i), template.charAt(i)));
}
System.out.println(populatedTemplate);

```

**Comment by damithc** [comment]
@tarun, may be create a PR so that we can compare the difference? The PR need not be complete; do just enough for us to evaluate your approach against the original.

**Comment by tarun14110** [comment]
The way I was thinking is not working here.
1) We are also replacing variables in the templates with some other variable (or some other template code that contains other variable.) . So replacing an index of template only once will not work here, it need to replaced again and again till all all variables are replaced. So, limiting to single replacement will not work here.
2) Previous code is clean and easy to understand.

So I think we should close this issue.

**Comment by damithc** [comment]
Noted. closing.
