### ISSUE TITLE
New contributor self intro Saumya Tiwari

### ISSUE THREAD

**Issue by ilovejava1988** [TEAMMATES/teammates#5347]
a) [http://4-18-dot-teammates-saumya.appspot.com/](url)
b) [https://github.com/ilovejava1988/teammates.git](url)
c) 
[teammates-saumya.zip](https://github.com/TEAMMATES/teammates/files/264078/teammates-saumya.zip)

d) Hi i am saumya tiwari. I am a software developer. Aspire to learn new technologies and strengthen existing ones through contribution to open source.

**Comment by damithc** [comment]
Welcome to TEAMMATES dev community @ilovejava1988 
Good job on deploying to the staging server. You can proceed to the next step in the contributor orientation guide.
