### ISSUE TITLE
Special character spotted in student name

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5348]
![image](https://cloud.githubusercontent.com/assets/1673303/15265945/cf7b2e1e-19c6-11e6-98de-311bc4802b46.png)

**Comment by damithc** [comment]
It's like this even in the database. It should be `/`
The course was created about 2 months ago.

**Comment by damithc** [comment]
@bamboo3250 any comments?

**Comment by bamboo3250** [comment]
Could you run the script `DataMigrationForSanitizedDataInStudentAttributes.java` in preview mode then post the result here?

**Comment by damithc** [comment]
Is it scalable to run on 100K students?

**Comment by kanghj** [comment]
This issue must mean that `DataMigrationForSanitizedDataInStudentAttributes` wasn't run on the old data in non-preview mode then. Let's restrict it to run only on courses in the last year and run it again.

**Comment by damithc** [comment]
Old issue. closing.
