### ISSUE TITLE
New contributor self intro Neeti Raghunath

### ISSUE THREAD

**Issue by nraghun** [TEAMMATES/teammates#5353]
1) http://4-18-dot-teammates-neeti.appspot.com/
2) https://github.com/nraghun/teammates.git
3) 
![changeincolor](https://cloud.githubusercontent.com/assets/11624269/15273383/cef995b2-1a4c-11e6-8a14-a184397bb384.JPG)
4) Hi, I am Neeti Raghunath. I am a software developer, looking to expand my programming skills by contributing to open source projects.

**Comment by PSNAppz** [comment]
Is that an issue?

**Comment by damithc** [comment]
Welcome to the TEAMMATES developer community @nraghun . You may proceed to the next step in the contributor orientation guide.
@PSNAppz Yes, Neeti is doing the right thing by posting her intro here.

**Comment by PSNAppz** [comment]
@damithc 😀 Ok.
