### ISSUE TITLE
Exception messages in FeedBackSessionsLogic class could be extracted to Constants

### ISSUE THREAD

**Issue by rclakmal** [TEAMMATES/teammates#5357]
There are several EntityDoesNotExistException and InvalidParametersException messages used multiple times in the class. They could all be extracted to Constants.

**Comment by YongJieYongJie** [comment]
I think whenever either of the two exceptions is raised, similar magic string messages of the form `"Trying to [do some illegal operation]"` are used.

Searching for `"Trying to` returns quite a few `.java` files

**Comment by xeia** [comment]
Just to clarify, should the log message strings/assumption strings be extracted to constants as well?

**Comment by damithc** [comment]
@rclakmal are you working on this already?

**Comment by rclakmal** [comment]
@damithc I didn't start yet on this one. If there is a new contributor interested pls go ahead. Unless I will fix by  tomorrow.

**Comment by rclakmal** [comment]
@xeia Would you like to take this issue up ?

**Comment by xeia** [comment]
@rclakmal sure thing, but i would like to check if it is required to extract the log and assumption message strings?

**Comment by rclakmal** [comment]
@xeia I would personally extract all strings which are being used multiple times. For an example, `Trying to update a feedback session that does not exist` is used 10 times in the code. But let's wait for input from a project member :-) @damithc @YongJieYongJie

**Comment by damithc** [comment]
@xeia go ahead and do what you think is the best. We can discuss further when the PR is in.
