### ISSUE TITLE
New contributor self intro [Xue Si]

### ISSUE THREAD

**Issue by xeia** [TEAMMATES/teammates#5370]
a) Link to the app: https://teammates-xstan.appspot.com/
b) Link to the fork: https://github.com/xeia/teammates
c) 
![modified](https://cloud.githubusercontent.com/assets/12380232/15284164/523011f0-1b82-11e6-87d2-c146cf4b6293.png)
added a stickiness to the navbar, underlining and coloring of text upon hover on the loginHolder (sorry the mouse cursor isn't shown, it is pointing at 'Student Login')
d) Hi, I am Tan Xue Si, a year 2 CS student at NUS and hoping to help contribute!

Also, after adding the underlining I think there is a (stray?) whitespace before the word 'Instructor Login' on the button value, or is it intended?

**Comment by wkurniawan07** [comment]
Hi @xeia, welcome to the TEAMMATES developer community!
Good job in setting up the dev environment! I see that you also have made a PR on a first-timer issue, so you can move on to more challenging issues, starting from the ones labeled `d.Contributors`. Looking forward to more of your contributions!
