### ISSUE TITLE
Misleading file extension of course enroll sample spreadsheet

### ISSUE THREAD

**Issue by YongJieYongJie** [TEAMMATES/teammates#5385]
On the course enrollment page, the sample spreadsheet will be downloaded as `Course Enroll Sample Spreadsheet.csv`, even though the enrolment page does not accept comma separated values.

Users actually need to use Excel (and perhaps other similar softwares) for the copy and paste to work. Text editors will not work.

Maybe we can save the file as `.xls` or `.ods` (openDocument spreadsheet) to avoid confusion.

**Comment by damithc** [comment]
`.xls` sounds more user friendly. I guess even those without Office can open `xls` files using their office alternatives?

**Comment by YongJieYongJie** [comment]
Actually Google Sheets and Microsoft Excel Online work too.
Using these will be more convenient as  users can just follow a link to open the sample spreadsheet to copy and paste.

[Google Sheets](https://docs.google.com/spreadsheets/d/18IdKzFFOM20384wxS-E4Ok5ixdH0MzRaqKX6AsN5xYA/edit?usp=sharing)
[Excel Online](https://onedrive.live.com/redir?resid=DD25068C10583299!1167&authkey=!AAr1xIAI_iJdhX4&ithint=file%2cxlsx)

**Comment by damithc** [comment]
Yes, we can use GoogleSheets.
