### ISSUE TITLE
Load responses by ajax by default on non-question views of instructor results

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#5417]
The questions view of the instructors results page automatically load responses incrementally by ajax. This solved some problems with a slow initial load of the results page. Currently for the non-question views, we try to render all responses at once unless there are a large number of responses. We can make the non-question views, such as recipient > giver > question, do the same and use ajax loading by default. This will help in making the code more understandable on the results page too, as there will be less possible ways that the results page can loaded.

**Comment by belyabl9** [comment]
I'd like to try that after some exploring of current implementation. As I see, it's already partially implemented

**Comment by kanghj** [comment]
@belyabl9, for the non-question views, let's first go with the existing separation on those pages, request per section.
