### ISSUE TITLE
unable to set up the dev server

### ISSUE THREAD

**Issue by pragin** [TEAMMATES/teammates#5421]
Hi, I was trying to setup the developer environment for TeamMates. I followed every letter from this document [](https://github.com/TEAMMATES/teammates/blob/master/devdocs/settingUp.md). When I ran the command ./gradlew setUp it executed some commands and finally gave an error saying build failed. Please find the error message below. Can someone please help me to sort this out. Thanks
* Where:
Build file '/Volumes/Untitled/teammates/build.gradle' line: 78

* What went wrong:
Execution failed for task ':updateLibs'.
> Could not expand ZIP '/Volumes/Untitled/teammates/libs/libsV5.60.zip'.

**Comment by wkurniawan07** [comment]
@pragin, that could be caused by insufficient permission. Can you try re-running the setup command again with administrator privilege?

**Comment by pragin** [comment]
@damithc I am using a Mac. I tried `Sudo ./gradle setUp`. Still it gave me the same error.

**Comment by damithc** [comment]
@wkurniawan07 may be @pragin can perform the steps manually?

**Comment by pragin** [comment]
@wkurniawan07  @damithc  how do I do that? Can you please help me? I also tried the steps on my windows 7 laptop and failed with the same error.

**Comment by wkurniawan07** [comment]
@pragin I just downloaded the zip folder and it's working fine. I uploaded it in my Dropbox, see if you can download it from there instead: https://www.dropbox.com/s/ji1hrhuw3li4osx/libsV5.60.zip?dl=0

**Comment by pragin** [comment]
@wkurniawan07 great it worked perfectly. you are a legend

**Comment by damithc** [comment]
@wkurniawan07 what seems to be the actual problem? The file corrupted or the download failed?

**Comment by wkurniawan07** [comment]
@pragin any more difficulties in setting up?
