### ISSUE TITLE
Update TEAMMATES Java style guide

### ISSUE THREAD

**Issue by JosephineKwa** [TEAMMATES/teammates#5423]
Specifically, the modifier order should be changed to follow this order
1.public
2. protected
3.private
4.abstract
5.static
6.final
7.transient
8.volatile
9.synchronized
10.native
11.strictfp

Edit: Also link the current java style guide to the one given below, instead of the Google doc

**Comment by damithc** [comment]
Can we switch to this one? https://github.com/nus-cs2103/website/blob/master/contents/coding-standards-java.md
It's same as the GoogleDoc one but to be used by CS2103 and our other projects.

**Comment by wkurniawan07** [comment]
Resolved in 1b2db7a.
