### ISSUE TITLE
Action.executeAndPostProcess() throwing EntityDoesNotExistException is out of place

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#5430]
- `EntityDoesNotExistException` is a checked exception, and all other checked exceptions (`InvalidParametersException`, `EntityAlreadyExistsException`, `JoinCourseException` to name a few) are properly handled in the body of the `execute()` method of all `*Action` classes.
- This Exception is propagated to `Action.executeAndPostProcess()` and later on `ControllerServlet.doPost`, the latter method is catching this Exception (or more like forced to), but all other caught Exceptions in that method are unchecked. It looks logical: `ControllerServlet.doPost` catches all possible unchecked Exceptions as a safety net, but then a wild checked Exception is included.

It stands to reason that this behaviour is out of place, intended or not. Is there a specific reason for `EntityDoesNotExistException` for having this special treatment? I'm thinking of writing the unchecked version for that to standardize the behavior, something along the line of:
```java
try {
    doSomethingThatMightThrowEdnee();
} catch (EntityDoesNotExistException ednee) {
    throw new EntityNotFoundException(ednee);
    // EntityNotFoundException is a subclass of RuntimeException
}
```
Of course if there are better ways to handle it then the better ways take place, the above is just a boilerplate method that can be applied everywhere.

**Comment by wkurniawan07** [comment]
@damithc @kanghj @LowWeiLin will need all your opinions on this.

**Comment by damithc** [comment]
The reason it is handled at the highest level is because we treat it the same way no matter where it is thrown. So it is a coincidence that it can be handled at the same level runtime exceptions are handled. There is room for improvement though -- it can be caught earlier (at lower levels) and handled in more specific ways based on where it originated from, for example, we can say 'the session has been deleted' instead of the general 'entity not found'.

**Comment by wkurniawan07** [comment]
Yes, I'm thinking the same, that's what I meant by "if there are better ways to handle it then the better ways take place".
What I am not content about is the fact that a checked Exception is let through when everything past `Action.execute()` should already be RuntimeExceptions.

**Comment by wkurniawan07** [comment]
We'll go down one level at a time, so changing the issue title.
