### ISSUE TITLE
CoursesLogicTest: fix occasional test failure due to wrong ordering

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/teammates#5439]
In testGetCoursesForStudentAccount(),

```
// For some reason, index 0 is Course2 and index 1 is Course1
// Anyway in DataStore which follows a HashMap structure,
// there is no guarantee on the order of Entities' storage
```

Test should not assume the order of values in a hashmap.

**Comment by sujeet14108** [comment]
@LowWeiLin  
Are we talking about this ?

         CourseAttributes course1 = dataBundle.courses.get("typicalCourse1");
        assertEquals(course1.getId(), courseList.get(0).getId());
        assertEquals(course1.getName(), courseList.get(0).getName());

        CourseAttributes course2 = dataBundle.courses.get("typicalCourse2");
        assertEquals(course2.getId(), courseList.get(1).getId());
        assertEquals(course2.getName(), courseList.get(1).getName());`

In this to verify instead of checking for fixed index we can iterate on courseList to check if both courses exits or not ?

**Comment by wkurniawan07** [comment]
@sujeet14108 you are exactly right.
