### ISSUE TITLE
MCQ question: right align 'generate' option

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5460]
Right aligning the test to be near the dropdown can make the option easier to understand
![image](https://cloud.githubusercontent.com/assets/1673303/15533162/ec7c1f82-2295-11e6-888e-b9c10a2b150a.png)

**Comment by damithc** [comment]
Or we can split this into two question types

**Comment by thyageshm** [comment]
Can I try this one?

**Comment by damithc** [comment]
Go ahead.

**Comment by thyageshm** [comment]
is this ok?
![image](https://cloud.githubusercontent.com/assets/5160137/18828408/5c820640-840a-11e6-81b2-df0d380ddb5f.png)

Reducing that space alone results in responsiveness issues (at some screen widths the words break to two lines while the select tag remains in the first line. OR right aligning it causes issues in small devices)

**Comment by thyageshm** [comment]
Here's the result I can get with more code change:
![image](https://cloud.githubusercontent.com/assets/5160137/18829144/9257a498-840d-11e6-9ff8-c28dfc423afe.png)
![image](https://cloud.githubusercontent.com/assets/5160137/18829159/a137f670-840d-11e6-898d-9240354a5e69.png)
![image](https://cloud.githubusercontent.com/assets/5160137/18829175/b31c46b6-840d-11e6-8f06-a1738e420240.png)
![image](https://cloud.githubusercontent.com/assets/5160137/18829191/c33c0b44-840d-11e6-9903-cd876c3ed69d.png)
![image](https://cloud.githubusercontent.com/assets/5160137/18829203/d423a296-840d-11e6-939f-16f9348fc291.png)

**Comment by damithc** [comment]
It can be misleading when the two check boxes appear together one below the other. Can we prevent that, or at least show a separator between the two?
