### ISSUE TITLE
Typo in the specification document (Google Docs)

### ISSUE THREAD

**Issue by PSNAppz** [TEAMMATES/teammates#5466]
**Change Strarted to Started.**

[Specifications](https://docs.google.com/document/d/1hjQQHYM3YId0EUSrGnJWG5AeFpDD_G7xg_d--7jg3vU/pub?embedded=true)

![typo](https://cloud.githubusercontent.com/assets/4481429/15538022/35c5bada-2297-11e6-94e6-15f89a5e5e28.png)

**Comment by damithc** [comment]
Fixed. Thanks for the bug report @PSNAppz
