### ISSUE TITLE
Remove checkstyle suppressions on Config and TestProperties

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#5478]
Currently, `MemberName|StaticVariableName` is suppressed for `TestProperties` and `Config` in `teammates-checkstyle-suppressions.xml`. We should remove the suppressions and fix the violations on Config and TestProperties.

**Comment by wkurniawan07** [comment]
@kanghj you can split this to two issues (one class each) and assign me one. Of course, feel free to do both if you want 😛
