### ISSUE TITLE
Rename 'Instructors' in courseEditAddInstructorPanel.tag to 'Instructor'

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#5496]
In courseEditAddInstructorPanel.tag, the `div` with class `panel-heading`, `Instructors` should be changed to `Instructor`.

This is to make it consistent with the headings of the Edit Instructor panels, which are in courseEditInstructorListPanelHeading.tag.

**Comment by PSNAppz** [comment]
It has to be d.firstTimers issue.

**Comment by ablyx** [comment]
Hi, can I have a go at this?

**Comment by damithc** [comment]
Sure @ablyx
