### ISSUE TITLE
Use Transactions when adjusting Feedback Questions question numbers

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#5505]
#5208 tackled a symptom of the underlying problem, that the way we handle feedback questions is very vulnerable to eventual consistency. Currently, most of the code assumes that question numbers in the feedback session will be consistent. In this issue, we should explore the use of transactions while adjusting question numbers instead.

First step is to use a one-to-many owned relationship between session and questions. This will make them part of the same entity group.

**Comment by kanghj** [comment]
@damithc, if we want to put questions in the same entity group as the session, the cleanest way seems to be introduce a new entity type and then migrate all existing questions to the new entity type. We cannot add a new parent to an existing entity.

**Comment by damithc** [comment]
OK to use a new class for the purpose of migration. If we cannot find a suitable name, we can also use a convention like `QuestionV2`

**Comment by kanghj** [comment]
Actually, if we do a migration now, the feedbackQuestionIds we have been using which are getting used in FeedbackResponses will have to be cascaded to, making the migration script extremely expensive. Any new responses made during the migration may not be correctly handled too. In addition, the old links generated by `Get Link` on the edit page will break too, so currently I will look at trying to add the relationship only on the Session instead of a bidirectional relationship.

**Comment by damithc** [comment]
To be relooked at later.
