### ISSUE TITLE
Filtering improvements for feedback session results

### ISSUE THREAD

**Issue by belyabl9** [TEAMMATES/teammates#5525]
Filtering of feedback session results seems to be implemented partially for non-question view types.
1. Initially, I started with filtering by section name and after some investigation I found that it can handle only lower-case. As we allow to create sections ( "Test Section", "test Section", "Test section", "test section") as different ones, now we can't filter the only section. And even more worse situation is when we type filtering text preserving case = we got nothing for sections with upper-case letters. There are two ways to solve it: 1) convert to lower case filtering text too 2) moving to case-sensitive filtering
I know that we have separate input for section filtering, but based on filtering placeholder sections are supported there too.
By the way, do we have any possibility to pass more than one filtering object ? I mean smth. like "section1|section2".
2. Probably, I don't know some requirements, but I can't achieve filtering by something other (team/student name, etc.) than sections for non-question views

Could you explain mentioned points and describe the nearest plans about this functionality

Thanks in advance

**Comment by kanghj** [comment]
For 2, this is a bug caused in a recent pull request. I also realised our test cases for this filtering is quite  lacking, so the bug got through somehow. I will make a new issue for it, sorry for the confusion.

**Comment by kanghj** [comment]
For 1, I think we should convert the filtering/search text to lower case too.

@damithc, I think the other questions need your attention: 
* By the way, do we have any possibility to pass more than one filtering object ? e.g. "section1|section2"
* describe the nearest plans about this functionality

**Comment by damithc** [comment]
Good questions @belyabl9 
This feature needs some thinking. I think @rclakmal will take it on in due course (he is doing the reports+ project). Most likely we'll have to introduce a richer UI for more sophisticated filtering, somewhat similar to the one we have in the 'students' page.
![image](https://cloud.githubusercontent.com/assets/1673303/15797436/ba4b1970-2a4a-11e6-81a8-598aee2de530.png)

**Comment by belyabl9** [comment]
@damithc, thanks for clarification. Then I think this issue may be closed
