### ISSUE TITLE
Fix regression which broke filtering in instructor results page

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#5528]
As discussed in #5525 point 2, the filtering of results on InstructorFeedbackResultsPage might be broken. We should fix it and introduce a stronger test case. In [src/main/webapp/js/instructorFeedbackResults.js#115](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/js/instructorFeedbackResults.js#L115), `hide` should be `show`.

**Comment by wkurniawan07** [comment]
Apologies, I'm definitely the one who caused this >.<
