### ISSUE TITLE
Standardize use of Assumption.assertNotNull()

### ISSUE THREAD

**Issue by YongJieYongJie** [TEAMMATES/teammates#5532]
Currently, `Assumption.assertNotNull()` is called using different constant strings like `ERROR_NULL_PARAMETER`, `DBLEVEL_NULL_INPUT` or magic strings like `"Non-null value expected"`.

All these strings are equally uninformative and are just variations of `"Null parameter supplied\n"`.

Related issue:
Enhance null check for post parameters to cater for cache expiry #2972

**Comment by AnaghHegde** [comment]
@damithc So what exactly has to be standardized in this issue?. 

>All these strings are equally uninformative and are just variations of "Null parameter supplied\n".

Does this mean's the output of the AssertNotNull() method has to be standardised to something common?.

**Comment by damithc** [comment]
Looks like the issue is not clearly defined. Closing.
