### ISSUE TITLE
CONTRIBUTING.md links to the old contributor orientation guide

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#5539]
The one used now is in the `devdocs/` folder.

**Comment by damithc** [comment]
Let's fix this soon. Removing `firstTimers` label because this is not a low priority issue.

**Comment by damithc** [comment]
@wkurniawan07 this should be closed, right?

**Comment by chowyb** [comment]
@damithc the merged PR referencing this issue is on the contributor's own fork, and not on our repository. The issue is still not fixed yet.

**Comment by damithc** [comment]
I see. It's a high priority issue. Can submit a quick fix?
