### ISSUE TITLE
Write tests to cover the new functionality of avoiding "missing/empty" responses.

### ISSUE THREAD

**Issue by rclakmal** [TEAMMATES/teammates#5558]
#5548 introduces a new checkbox which can be used to avoid empty responses in both panel views and csv download. Tests should be included to cover these functionalities.

**Comment by damithc** [comment]
We prefer the functional code and test code came in the same PR :-)

**Comment by rclakmal** [comment]
I see. :) Will close the current PR and open it once tests are also added..

**Comment by kanghj** [comment]
Closing this since this should be done together in the same PR as #5548
