### ISSUE TITLE
Combine pages for "Course Details" and "Edit Course Details"

### ISSUE THREAD

**Issue by YongJieYongJie** [TEAMMATES/teammates#5561]
Currently, clicking the `[view]` button leads to "Course Details" page with students-related options (remind student to join etc.), whereas clicking `[edit]` button leads to "Edit Course Details" page with course name/id and instructors-related options (add instructor, change permissions etc.).

Perhaps we can combine the two into one "Course Details" page, and use Bootstrap tabs or pills to switch between control for instructors and for students (something like what we are doing on the comments page for switching between courses).

The result will be a more streamlined navigation for courses because there'll only be two pages: course listings (linked from the main nav bar) and course details (linked wherever the course name/id is shown).

(Perhaps there are access control considerations preventing this?)

**Comment by damithc** [comment]
The current design wasn't a conscious decision. Yes, we can consider combining them.

**Comment by chowyb** [comment]
Access control likely won't be much of a problem when addressing this issue, as both pages are viewable even to an instructor with no privileges. All related actions that can be performed from those pages (eg add/edit instructors) should remain about the same non-UI wise, with the exception of redirect results.

**Comment by nsaiisasidhar** [comment]
Hi, I like to contribute to this issue. Can you please let me know if its studentsComments.jsp or instructorComments.jsp to refer to get an idea on how it's implemented.

**Comment by damithc** [comment]
No longer relevant
