### ISSUE TITLE
FeedbackResponseAttributes: rename giverEmail to giver and recipientEmail to recipient

### ISSUE THREAD

**Issue by YongJieYongJie** [TEAMMATES/teammates#5571]
Extension of issue:
Rename misleading instance variable names in FeedbackResponseAttributes #5456

**Comment by damithc** [comment]
Some have been fixed, but some still to be fixed.
![image](https://cloud.githubusercontent.com/assets/1673303/26245346/41eb8804-3cc6-11e7-8ba0-3cb5dab45f5c.png)

**Comment by sujeet14108** [comment]
taking this one

**Comment by sujeet14108** [comment]
@YongJieYongJie  @damithc  Do we need to rename `giverEmail` to `giver` everywhere including json files ?

**Comment by damithc** [comment]
@whipermr5 can help?

**Comment by whipermr5** [comment]
After checking, it looks like the json files have already been updated to `giver` for `FeedbackResponseAttributes`. The remaining instances of `giverEmail` in json files belong to `FeedbackResponseCommentAttributes`, which is outside the scope of this issue. The only two remaining issues here are with the param name in the constructor and the `toString` method. Changing the former is safe; I'll leave you to investigate the effects of changing the latter.
