### ISSUE TITLE
instructor edit student email: Give an option to resend emails when editing student email

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5577]
When editing student email, it can be helpful to give an option to resend the pending emails that were sent to the wrong address before.

**Comment by tarun14110** [comment]
Which emails we want to resend to new email ? 
I think resending `FeedbackSessionOpeningEmail`, if session is opened and `FeedbackSessionPublishedEmail` if session is published are enough ?

**Comment by damithc** [comment]
Yes, in fact can we sent one email with a list of all relevant links from the course?

**Comment by tarun14110** [comment]
@damithc I thought that, it will help customize the email. But we have only atmost 2 relevent links for the course i.e SessionSubmissionLink and viewPublishedSessionLink , correct me if I am wrong ? Is it worth creating a new email for this ? We can  add some fragments to the existing email if we want to add some info? Or adding new Email is also a good idea if we need to add some additional content ?

**Comment by damithc** [comment]
It may be more than two links. For example, a student found out he missed all previous sessions because emails have been going to the wrong email address. Another example is when a student loses an email account (e.g. due to hacking) and wants to access past sessions. I think it is ok to create a separate email template for this. When all emails look the same, users tend to ignore them thinking they are duplicates.

**Comment by tarun14110** [comment]
yeah, got that. It will be good to have different email.
