### ISSUE TITLE
Disable submit buttons after form submission on instructorFeedbackEdit page

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#5582]
In general, we should disable the submit button once the form is submitted. When the site is slow, users may get impatient and click the button multiple times, possibly resulting in incorrect behavior. For example, currently on the feedback edit page, after adding a question, an instructor can press submit multiple times. This actually results in multiple of the same question getting added. When we allow instructors to send reminders, this may also result in multiple emails getting sent. We should see if we can specify this behavior in common.js, otherwise make multiple issues for the different forms.

**Comment by damithc** [comment]
Even better if can add the 'spinner gif' to the button at the same time (to show something is happening).
