### ISSUE TITLE
PSA: renew your .classpath file and local copy of dependencies

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#5591]
Hi all TEAMMATES contributors/developers,

Effective immediately, we will be using Gradle to manage the server-side dependencies to external libraries and not relying on zipped library file anymore. As such, you need to update your local configuration to agree to this routine. Here is what you need to do:

1. For each of the branch that you are actively working on (this includes your `master` branch), sync with the most current `master` branch.
2. When all are done, run the command `./gradlew resetEclipseDeps` or `gradlew.bat resetEclipseDeps`, whichever one applies.

For those interested in technicalities, this command will:

1. Flush the Eclipse `.classpath` file and the `WEB-INF/lib` folder
2. Downloads all the dependencies to your local Gradle cache if not yet present
3. Copy the necessary jar files to the `WEB-INF/lib` folder for the purpose of deployment, and configure Eclipse `.classpath` to use the jar files from the local cache.

The settings (e.g which libs to download/copy) are all configured from `build.gradle` file.

**Comment by wkurniawan07** [comment]
Tagging active devs: @damithc @kanghj @JosephineKwa @YongJieYongJie @chowyb @rclakmal @belyabl9 @tarun14110

**Comment by chowyb** [comment]
@wkurniawan07 I think we might need to refresh again after the recent Sendgrid commit

**Comment by wkurniawan07** [comment]
@chowyb and again after I added Mailgun/Mailjet, and again after I upgraded Selenium (soon), ... it's not practical to keep announcing for every single dependency change. Also, I'm not the only one who can change the dependencies.
Besides, you don't need to do step 1 anymore.
