### ISSUE TITLE
Instructor: view student record: allow opening of multiple comment panels

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#5600]
In `instructorStudentRecordsPage`, the panels behave such that only one edit panel may be open at any time, however in `instructorFeedbackResultsPage`, multiple panels may be open at once. This should be changed so that all these pages allow for multiple panels to be open at once.

[Above description was edited by Damith]

**Comment by Mynk96** [comment]
I think this has been resolved after #7418 merged.
![testtt](https://user-images.githubusercontent.com/17481466/27486194-551024a2-581f-11e7-99cb-487e1e2bfe48.PNG)

**Comment by damithc** [comment]
@chowyb can confirm?

**Comment by chowyb** [comment]
@damithc @Mynk96 confirmed fixed on latest version of master, closing this issue.
