### ISSUE TITLE
Improve Feedback path UI

### ISSUE THREAD

**Issue by tarun14110** [TEAMMATES/teammates#5604]
For Feedback path give a dropdown with some common feedback paths (e.g. ‘Students give feedback to their team members’) and an ‘other ...’ option. If the user chooses the ‘other ...’ option, it will show the UI we are using now.

**Comment by damithc** [comment]
@tarun14110 put this on hold for a bit. A few other devs ( @YongJieYongJie @JosephineKwa ) are also working on some UI changes related to this area, so we want to give them a few more days to settle their proposed UI first.
