### ISSUE TITLE
Rename privileges names

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#5607]
Currently in the code, the privileges are named like "canmodifysessioncommentinsection", we should change the names to be more readable.

**Comment by samsontmr** [comment]
@kanghj Do you mean by using camel case, or changing the name entirely?

**Comment by kanghj** [comment]
I was thinking about using camel case, but renaming it completely is fine too. I missed this out in the original post, but this issue must also involve writing a migration for the existing data with the old names to use the new names.

**Comment by wkurniawan07** [comment]
Closing as this is not a priority right now
