### ISSUE TITLE
Parts missing from results page

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5612]
The config options and summary table missing.
![image](https://cloud.githubusercontent.com/assets/1673303/16031713/f090d1a8-3230-11e6-9da2-ec44baeec784.png)

**Comment by damithc** [comment]
@kanghj any ideas?

**Comment by damithc** [comment]
And the csv file comes without the file extension and the has only 'no response' rows. Something to do with sanitization?

**Comment by kanghj** [comment]
Looks like a repeat of #5249. Can we verify if the csv file has the same problem?

**Comment by damithc** [comment]
Yes, csv file has the same problem.

**Comment by damithc** [comment]
In addition, it is missing the `.csv` part in the file name

**Comment by kanghj** [comment]
Just to confirm, is the filename of the csv `instructorFeedbackResultsDownload` or is it correctly named with the course and feedback session name?

**Comment by kanghj** [comment]
I would like to be able to confirm if the missing data is due to the same problem in #5249, I can update the script @bamboo3250 wrote in #5273 to only run on a single course so that we can verify that. Alternatively, we can check that from the google app engine datastore viewer itself.

**Comment by damithc** [comment]
Yes it is `instructorFeedbackResultsDownload`
Yes, there is an extra space. I've removed it in the database (from session and questions) and the instructor can see the missing parts on the webpage now. The csv file not contains the missing data, but the file name is still wrong.
