### ISSUE TITLE
Highlight that more information is available about feedback status

### ISSUE THREAD

**Issue by YongJieYongJie** [TEAMMATES/teammates#5614]
Although more information about the feedback session status is available on mouse over, there is no visual indication of such; perhaps we can add a dashed underline to the words `Published`, `Open` etc..

![image](https://cloud.githubusercontent.com/assets/14101781/16031451/e608a754-322d-11e6-8065-2a7908b97957.png)

**Comment by damithc** [comment]
What visual indicator should we use for items that has tool tips? It should be subtle. A thin dotted underline?

**Comment by YongJieYongJie** [comment]
Yup, I think a dotted (and perhaps faded) underline will look fine, maybe something like the third line in this picture:
![image](https://cloud.githubusercontent.com/assets/14101781/16061447/92ffa03e-32bf-11e6-87d2-ff14200e8552.png)

**Comment by damithc** [comment]
yes, we can try a faded dotted line. I've seen something similar being used elsewhere.

**Comment by damithc** [comment]
Apparently, we have something similar in other places:
![image](https://cloud.githubusercontent.com/assets/1673303/16105220/0131426e-33bb-11e6-8b41-8e3e65b33d17.png)

**Comment by rclakmal** [comment]
@YongJieYongJie We can close this issue with the fix in #5696
