### ISSUE TITLE
Buildpath error after running resetEclipseDeps gradle task

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5615]
I have both Java 8 and Java 7 on my machine, which is likely the cause of this problem. 

![image](https://cloud.githubusercontent.com/assets/1673303/16032679/04fb78ce-323a-11e6-9bfd-898d32833ed0.png)

We may need to find a workaround and document it as Java 8 is likely to be the default jdk in future developers.

**Comment by wkurniawan07** [comment]
If I understand the issue correctly, @kanghj and I encountered this before. It's settled with `gradle.properties`.

**Comment by damithc** [comment]
In the set up doc, need to mention that `resetEclipseDeps` should be run after editing `gradle.properties` right?

**Comment by wkurniawan07** [comment]
`resetEclipseDeps` is not part of setting up task. But I see where an issue might come about, I'll fix that right away.
