### ISSUE TITLE
Instructor help page: add side navigation

### ISSUE THREAD

**Issue by YongJieYongJie** [TEAMMATES/teammates#5616]
Currently, we are using the "back to top" method for users to navigate back to the contents listing, this can get quite tedious after a while.

Having a side navigation (something like the [bootstrap components page](http://getbootstrap.com/components/)) would make the help page more helpful.

**Comment by YongJieYongJie** [comment]
Here's what I have so far:

With a collapsible side navigation, we can present a lot more help topics without cluttering the UI. 

Additionally, if the side navigation does make the help page more easily navigable, we can more readily redirect users to the help page when necessary (before we implement methods to bring help content to the location where help is needed).

![2016-07-04-165731_1280x800_scrot](https://cloud.githubusercontent.com/assets/14101781/16555689/7dfa17f2-4208-11e6-83b5-e5756a86e1dd.png)
![2016-07-04-170700_1280x800_scrot](https://cloud.githubusercontent.com/assets/14101781/16555934/c58bdb18-4209-11e6-94e1-19b6618456e3.png)

**Comment by damithc** [comment]
On which side should we have it? Is there a UIX reasoning behind one side vs the other?

**Comment by YongJieYongJie** [comment]
@damithc I chose to put it on the right because side navigation on the left tend to be full length (i.e., taking up the full vertical space). Also, since the highlighted portion scrolls with the page, it looks nicer beside the scrollbar.

**Comment by YongJieYongJie** [comment]
The html structure of various sections of the help page is inconsistent and should be fixed before progressing further on this issue.

Current progress:

![2016-07-05-164155_1280x800_scrot](https://cloud.githubusercontent.com/assets/14101781/16578889/8fa206be-42cf-11e6-94da-10700b06a4f1.png)
