### ISSUE TITLE
CSV download of the feedback responses should take the 'Section' filter in to consideration

### ISSUE THREAD

**Issue by rclakmal** [TEAMMATES/teammates#5628]
![section](https://cloud.githubusercontent.com/assets/794011/16062246/2ac6e310-3292-11e6-8a6c-5a9fda6ffa5f.png)

**Comment by rclakmal** [comment]
This is already in place. Nothing to implement

**Comment by damithc** [comment]
Not sure when it broke, but this feature is not working anymore :-p
