### ISSUE TITLE
InstructorFeedbackResults: search should work for uppercase letters

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#5637]
As described in #5525, a search for "Alice" does not match "Alice Betsy", but "alice" does. This behavior is unexpected. Both "Alice" and "alice" should match.

**Comment by YongJieYongJie** [comment]
Related to this `TODO` in FieldValidator?
```
/*
     * =======================================================================
     * Field: Student name [Refer generic field: person name]                                                                              
     * May not be unique, even within a course.
     * TODO: make case insensitive
     */
```

**Comment by kanghj** [comment]
Nope, the search on the results page is entirely in javascript. I have no idea what that TODO in FieldValidator actually means.
