### ISSUE TITLE
Instructor: view results: edit and add comment: revert visibility checkboxes and comment text when canceling edits

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#5653]
When cancelling an edit being made to a comment, or when adding a new comment, the visibility checkboxes and text are not reverted. Therefore, it is possible to cancel an edit on a comment, and edit the comment again, resulting in the form being filled in with data that has already been modified.

**Comment by Mynk96** [comment]
@chowyb Do we have any feature to cancel an edited comment?

**Comment by chowyb** [comment]
@Mynk96 yes, it is possible to click "cancel" at the bottom of the form instead of clicking "save". However, looking at the behaviour now, it appears that the text for the comment is not reverted either. We should probably revert the text input/visibility checkboxes when "cancel" is clicked, just to be consistent with the current behaviour (such as that for when edits made to a feedback question are cancelled, for instance)

**Comment by Mynk96** [comment]
@chowyb Got it!

**Comment by Mynk96** [comment]
The PR created for this issue reverts visibility checkboxes after user cancels editing or adding a comment.
In addition, it also reverts the comment text. So, I think we should rename this to 
`Instructor: view results: edit and add comment: revert visibility checkboxes and comment text when canceling edits`

**Comment by chowyb** [comment]
@Mynk96 updated issue title and description.
