### ISSUE TITLE
Remove submission page for single question 

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#5670]

**Comment by kanghj** [comment]
@tarun14110, are you interested in working on this? I haven't actually started work on this so you can take over this issue if you are interested.

**Comment by tarun14110** [comment]
@kanghj ok, I will do. please explain a little bit. Do we need to remove the `Get link` feature completely ? or something else ?

**Comment by kanghj** [comment]
Yes, let's remove this `Get link` feature completely, including any actions, page data classes, tests, jsp that are used only by this feature.
