### ISSUE TITLE
Remove redundant tooltip

### ISSUE THREAD

**Issue by YongJieYongJie** [TEAMMATES/teammates#5684]
![redundant_tooltip](https://cloud.githubusercontent.com/assets/14101781/16215661/a93d365a-3796-11e6-9a8e-390858f2f1be.png)

**Comment by belyabl9** [comment]
@YongJieYongJie , should 'Edit this question', 'Discard your changes' be removed as well ?

**Comment by YongJieYongJie** [comment]
@belyabl9 Yup, I think we can remove them since edit is intuitive and discard changes actually has a confirmation prompt

**Comment by belyabl9** [comment]
@YongJieYongJie , ok, just wanted to confirm in order not to do it via 3 different issues ;)
