### ISSUE TITLE
Remove unnecessary HTML in test .json files

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#5686]
Quite a number of .json files (eg. `instructorStudentRecordsPageUiTest.json`) have unnecessary HTML (eg. `Teammates Test</option></td></div>'\"`) in their content. This should be removed where possible as it adds no value to the tests.

**Comment by wkurniawan07** [comment]
Errrr no, it's to test sanitization.

**Comment by chowyb** [comment]
Oh okay, didn't know that.

Closing this issue.
