### ISSUE TITLE
InstructorFeedbackResultsPageAction: split into multiple classes for different result views

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#5687]
Instead of having various parameters (sort type, whether it is grouped by team, filter by section, load by ajax) determining behavior in many methods in `InstructorFeedbackResultsPageAction` and `InstructorFeedbackResultsPageData`, we should be able to use inheritance where appropriate and have multiple classes. Currently, both InstructorFeedbackResultsPageAction and InstructorFeedbackResultsPageData are doing way too many things.

**Comment by Neurrone** [comment]
Would like to try working on this. @kanghj what did you have in mind? How would inheritance help here, since multiple options can be active at once.

**Comment by kanghj** [comment]
For a start, we can split it based on the sort type (question, recipient > giver > question, giver > question > recipient, etc). There's also a setting for loading the CSV results as a table in the page, which could also be moved to its own action.

**Comment by Neurrone** [comment]
Hm, do you mean this? 

* having an action class for each sort type (question, recipient > giver > question, etc
* move the CSV loading to its own action class

Then in the refactored execute method:

1. If loading of a CSV is requested, construct a Csv action object and execute it
2. Parse setIndex param's value if it exists as an integer, and set it in InstructorFeedbackResultsPageData
3. If sort type is not specified in the request, set defaults

Based on the request parameters, construct an instance of the appropriate action class. Call some method on it to do the following:

4. Set the bundle to be returned.
5. Add status messages to warn if there are too many responses
6. return PageResult

**Comment by wkurniawan07** [comment]
V7 takes this to an entirely new level: there is only one Action class to get session results, which is independent of how the front-end displays it.
