### ISSUE TITLE
Allow smaller increments for session start and end time

### ISSUE THREAD

**Issue by YongJieYongJie** [TEAMMATES/teammates#5695]
From `// TODO: allow smaller increments` in FieldValidator

**Comment by rclakmal** [comment]
@YongJieYongJie is this` //TODO `still open ? Couldn't find it in the task view. 
What would be the expected size of increment (30 mins of 15mins) and thinking differently, would it make sense to include a time picker ? @damithc

**Comment by damithc** [comment]
Let's not do this right now as there are some changes being done to times handling on another front (i.e. daylight saving time). This feature is low priority anyway.

**Comment by Tikam02** [comment]
This works for me - I set the ct as a global var and only store the end time once

Please change setInterval("calculate_time()",100); to setInterval(calculate_time,100);

You can create your own namespace if you do not want to pollute the global scope
var ct, end_time = <?php echo $_SESSION['start_time']; ?>; // Get end time from session variable (total time in seconds). 

window.onload=function() { // make sure the output field exists
  ct = setInterval(calculate_time,100); // Start clock.
}
function calculate_time() {
  var dt = new Date(); // Create date object.
  var time_stamp = dt.getTime()/1000; // Get current minutes (converted to seconds).
  var total_time = end_time - Math.round(time_stamp); // Subtract current seconds from total seconds to get seconds remaining.
  var mins = Math.floor(total_time / 60); // Extract minutes from seconds remaining.
  var secs = total_time - (mins * 60); // Extract remainder seconds if any.
  if(secs < 10){secs = "0" + secs;} // Check if seconds are less than 10 and add a 0 in front.
  document.getElementById("txt").value = mins + ":" + secs; // Display remaining minutes and seconds.
// Check for end of time, stop clock and display message.
  if(mins <= 0) {
    if(secs <= 0 || mins < 0)  {
     clearInterval(ct);
     document.getElementById("txt").value = "0:00";
     var form = document.createElement("form");
     form.action = "http://www.example.org/q/conflinux/expire_me.php";
     form.method = "post"
     document.body.appendChild(form);
     form.submit();
   }
  }
 }
