### ISSUE TITLE
Standardize 'you' vs 'I' in UI

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5704]
Sometimes we should use 'I/my' etc and sometimes we should use 'You/your' etc.

See http://ux.stackexchange.com/questions/4348/your-vs-my-in-user-interfaces

**Comment by YongJieYongJie** [comment]
One main source of inconsistency is in the "Team peer evaluation session" where the questions are phrased in first person whereas the visibility hint is worded in second person:

![you and i - question](https://cloud.githubusercontent.com/assets/14101781/16550597/e9d0bf32-41de-11e6-9337-6ca3c0c2911b.png)

We can rephrase the questions to be in second person (as questions usually are) as follow:

`My estimate of how much each team member contributed.` --> `How much contribution did each team member made?`

`Comments about my contribution(shown to other teammates)` --> `Please elaborate on the contributions you made (response will be shown to your teammates)`

`Comments about team dynamics(confidential and only shown to instructor)` --> `Please describe the team dynamics (response is confidential and shown only to the instructor)`

@damithc What do you think?

**Comment by damithc** [comment]
yes, I agree that rephrasing to second person will be better. The exact rephrasing need to be worked out though. i.e. refine your suggested questions further.

**Comment by YongJieYongJie** [comment]
@damithc I have refined the phrasing further.

Currently, the approach is more direct, starting with "Who What When Where How Why" as much as possible.

(The previous rephrasing is less direct, and uses language like "please elaborate", "please provide feedback" etc.)

__The rephrased questions are as follow:__

1. _My estimate of how much each team member contributed._
 ➔ How much work did each member of the team contribute?
OR 
 ➔ How much effort did each member of the team put in?
 - the first phrasing is ability-blind: i.e., weaker student is disadvantaged by this phrasing;
 - the second phrasing is ability-aware: i.e., a weaker student who tries his best will nonetheless be rated highly

2. _Comments about my contribution(shown to other teammates)_
 ➔ What contributions did you make to the team?
(response will be shown to your teammates)
OR
 ➔ How have you contributed to the team?
(response will be shown to your teammates)

3. _My comments about this teammate(confidential and only shown to instructor)_
 ➔ What comments do you have regarding each of your teammates?
(response is confidential and will only be shown to the instructor)

4. _Comments about team dynamics(confidential and only shown to instructor)_
 ➔ How is the team dynamics thus far?
(response is confidential and will only be to the instructor)

5. _My feedback to this teammate(shown anonymously to the teammate)_
 ➔ What feedback do you have for each of your teammates?
(response will be shown anonymously to each teammate)

**Comment by damithc** [comment]
1. first one is fine. 'member of the team' --> team member? Add visibility info (other 4 questions have it).
2. first one is fine.
3-5. fine. teammate --> team member?

Note that Serhii is adding a rich text description to questions. So may be wait till that is merged?

**Comment by jimmyshephard** [comment]
I would like to take up this issue guys. Looks like it's been pending for a while.

**Comment by Vaggelis-Malandrakis** [comment]
@jimmyshephard Are you still working on this? If not, I would like to solve it

**Comment by Vaggelis-Malandrakis** [comment]
@damithc Do you know if this issue is open?

**Comment by damithc** [comment]
> @damithc Do you know if this issue is open?

@Vaggelis-Malandrakis Yes, it is open.

**Comment by jimmyshephard** [comment]
Anyone interested can go ahead, won't be able to look at this for a while

**Comment by xpdavid** [comment]
The position of the session template file is in now in frontend (https://github.com/TEAMMATES/teammates/pull/9345) (Subject to the review :P)

**Comment by Ayush517** [comment]
@damithc Is this still open? I would like to work on this.

**Comment by damithc** [comment]
> @damithc Is this still open? I would like to work on this.

The issue is still open. @wkurniawan07 is this a good time to start working on this issue?

**Comment by Ayush517** [comment]
@wkurniawan07 any updates?

**Comment by wkurniawan07** [comment]
@Ayush517 you can proceed.
