### ISSUE TITLE
Auto-switch to a different email service if the current one is unusable

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5705]
If the current email service is not working or has reached a hard quota limit, the system should auto-switch to another service.

**Comment by wkurniawan07** [comment]
This one have some implications:
- I'm not aware of any API that can tell whether a mail service is working or not or telling the quota limit. If there are, when should they be called? Making an API call for every mail send is a cost on its own.
- How would the auto-switch policy be implemented? Let's say service A fails, which service should it use as a fallback (we have 4 choices, or 3 if we want to discard the default)? Also, what would happen if the fallback service is misconfigured?

**Comment by damithc** [comment]
Yes, it will not be easy if there are no suitable APIs. Confirm none of the three services has a way to get the quota info. It may be in the account/admin api rather than the mail api.
If there is really no api, then we may have to rely on exceptions thrown by the service.
As for the order, we can go by the order specified in the build.properties. If it says `...=serviceA, serviceB`, then we use serviceA first and fallback on serviceB when serviceA doesn't work anymore.

**Comment by damithc** [comment]
Something like this doesn't help? https://sendgrid.com/docs/API_Reference/Web_API/Customer_Subuser_API/account_limits.html
