### ISSUE TITLE
Indicate which emails did not reach the intended recipients

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5706]
It may be useful if the instructor can know which email addresses are not reachable.

**Comment by Sivhaun** [comment]
Where in the code do I find this?

**Comment by damithc** [comment]
@Sivhaun this may be a bit difficult to do. Have you done an issue labelled for `firstTimers`?

**Comment by Sivhaun** [comment]
yes but someone submitted a pull request and it was accepted before I finished it, so when I went to submit it the issue was closed.

**Comment by damithc** [comment]
I see. Try another `firstTimer` one?

**Comment by damithc** [comment]
I see. Try another `firstTimer` one?
