### ISSUE TITLE
Add confirmation dialog/modal for deletion of Feedback Response Comments

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#5711]
Currently, there is no confirmation dialog or modal that shows up when deleting a feedback response comment, which may lead to accidental deletions.

**Comment by belyabl9** [comment]
I'll work on it

**Comment by belyabl9** [comment]
Is 'Are you sure you want to remove this comment ?' enough for the confirmation message ?

**Comment by damithc** [comment]
Yes, something like that should be enough.
