### ISSUE TITLE
Email sent to respondent after submission: include answers submitted

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5721]
The current email does not include the responses submitted.
To be done after #5675

**Comment by damithc** [comment]
This will require adding code for each question respnse type to generate a user readable string representation of the answer.

**Comment by tshradheya** [comment]
I have some doubts regarding the including answers submitted in the email.

Won't this just include lots of details for the student in the email? I was thinking of someway by which we include just a summary of details rather than all the details of answers. What are your thoughts on this?

**Comment by damithc** [comment]
> Won't this just include lots of details for the student in the email? I was thinking of someway by which we include just a summary of details rather than all the details of answers. What are your thoughts on this?

Yes, that is a lot of details but it can be useful as a record of what was actually submitted (in case the responses got deleted later due to some mishap). Just a summary of questions is not that useful?

**Comment by wkurniawan07** [comment]
Resolved by #10861
