### ISSUE TITLE
Instructor: edit question: remove irrelevant form elements from form

### ISSUE THREAD

**Issue by YongJieYongJie** [TEAMMATES/teammates#5728]
The current approach is that form elements of all possible question types are in the new question form, but only those for chosen question type is shown.

As a result, upon form submission (or AJAX request for visibility message), many redundant request parameters are sent.

**Comment by muskanbararia** [comment]
Can I work on it?

**Comment by sukanta-27** [comment]
@Crphang I guess this issue is similar (or points out to the same problem) as #8688?

**Comment by Crphang** [comment]
@sukanta-27 Yes. I'll close this issue and mention it in the more #8688 since the discussion there is more elaborate.
