### ISSUE TITLE
Email failures not causing test failures on live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5738]

**Comment by damithc** [comment]
All tests passed (except the usual failures) even when the email service is not working at all.

**Comment by wkurniawan07** [comment]
That is expected. Email sending is not tested (it never was), otherwise it's easily eating up quota + spamming the test accounts.

**Comment by damithc** [comment]
On a related note, may be failures to send emails should be emailed to admin using GAE email service? 100/day should be enough for that purpose.

**Comment by wkurniawan07** [comment]
Non-200 responses are already severe logged under the current code.

The thing is, failures to send email don't always translate to such. A "200" code may only mean that the request to perform email sending is received and queued (see this [Mailgun example](https://cloud.google.com/appengine/docs/java/mail/mailgun#learning_more)), but nothing else after that is known. Only via the email service's admin console then the email status will be known.
Which is why #5705 is infeasible, if not impossible.

**Comment by damithc** [comment]
Severe logs are supposed to send me an email, but that doesn't happen if the email service is broken. may be use GAE mail for emailing severe logs -- or send by both?

**Comment by wkurniawan07** [comment]
Force-sending via GAE mail is possible, but that means the current rate of sending every 5 mins cannot be sustained because 24 x (60 / 5) = 288 >> 100. The max. rate we can get here is sending every 15 mins, amounting to at most 96 severe log emails per day, and the GAE mail cannot be used for anything else.

**Comment by damithc** [comment]
At the moment, there are about 10-20 severe log emails per day (checking every 5 minutes doesn't mean sending every 5 minutes). It's fine we don't use GAE quota for anything else. Again, we can duplicate the those emails using a slightly different subject line and send the duplicate via the normal email service. That way, the risk of something going wrong in the live server but not receiving any notification of it is minimum. The current situation is bad: None of the emails were sent out during testing and I didn't get any indication of it. Tests passed (they should not have) and there were no severe log emails either.

**Comment by wkurniawan07** [comment]
If it just happens today when switching to Mailgun, it might be an issue of misconfiguration. Mailgun requires the email sender's domain to be registered with the appropriate SPF/DKIM records, and they need about 24-48 hours to verify these records.

**Comment by damithc** [comment]
I've done that already, a few days ago. Based on mailgun dashboard, my domain is already active. Can you email me the relevant build.properties values. I'll try using yours.

**Comment by damithc** [comment]
While using GAE to send admin emails is good, that does not address this main cause of this issue, which I suspect to be an inadvertent weakening of tests. 

1. I used to get a bunch of emails during live server testing (because I set my own email as a student account used for testing). However, I don't get those emails anymore since the recent switch to other email service. 

2. If the email service is not working, some tests should fail during live server testing (those tests actually access the recipient email box to verify the email was sent). These specific email tests used to be ignored during dev server testing, so you might not notice the difference but I do. Have those tests been altered in some way?.

**Comment by wkurniawan07** [comment]
I need more information before troubleshooting this. What tests are involved in (1)? The only one I'm aware of is `AutomatedSessionRemindersTest` (in fact this is what I've been using when trying the different email services), and this is not automated (i.e a manual check needs to be done to make sure that the emails are sent).
As for (2), I'm well aware of that (in fact I already specifically mentioned `InstructorCourseDetailsPageUiTest`) and I have tested it prior to deploying the alternative email services. There is no alteration, no failure from this test before/after the alternative email services are deployed.

**Comment by damithc** [comment]
I did get some of the emails during V5.83 testing.

**Comment by damithc** [comment]
Getting the emails now.
