### ISSUE TITLE
Instructor home page: Show year as a tooltip of start/end time

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5742]
As the year is not shown at all, it's hard to see when the course was held.
I thought we had this feature already (may be we had it and lost it due to a regression?)
![image](https://cloud.githubusercontent.com/assets/1673303/16383642/864f1650-3cb8-11e6-92a6-ff853195c4bf.png)

Or perhaps we can show the duration `[earliest start time - latest end time]` on the panel header center?

**Comment by YongJieYongJie** [comment]
I think we can put the missing information in tooltips (just realized this is what GitHub is doing).
Actually, much of the visual clutter is also caused by the time (e.g., `11:59 PM`), if we are putting information in tooltips, we can consider hiding the time too.

**Comment by damithc** [comment]
Time is a VERY important information. Should not be hidden. :-) In fact we should find a more visual way to show the date/time info so that mistakes in times can be spotted easily. e.g. setting AM time when meaning to set a PM time, confusing month with date etc.
The more information we can show, the better (as opposed to 'more we can hide, the better'). Showing more info without overwhelming the user is the challenge. We can't show everything, so we need to decide which ones are ok to hide. It's fine to hide the year because most users won't need to see it to know it, as long as it's clear to the user that the year can be viewed by hovering (show dotted underline?). However, as an instructor accumulates many courses over the years (many of them are repeats), the year becomes a little bit more important.

**Comment by wkurniawan07** [comment]
For reference, the start/end date is added here #4426 and removing the year is actually a conscious decision (look at the issue thread).

**Comment by damithc** [comment]
Year is not so important (although I found it useful as admin when trying to troubleshoot through other user's homepages) but the day (Sun, Mon, etc.) can be useful to all users. If they can't be shown directly, there should be an easy way to access them. So I'm OK with the functionality of this PR.
