### ISSUE TITLE
instructor: view session results: fix bug that says 'no responses' when there are responses

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#5765]
In certain circumstances, the page will incorrectly state that no responses exist for the session, even though responses exist. This issue will be updated once I trace the cause of the bug.

![results](https://cloud.githubusercontent.com/assets/7546744/16475169/f31fca3e-3eae-11e6-9c71-01309bc711d7.png)

**Comment by chowyb** [comment]
The cause of the bug has been determined:

To figure out whether there are responses for a feedback session, the code gets the first 2 responses (if any) as a sample from the database, and then checks if they are visible to the instructor, removing them from the returned list if they are not visible. As such, if the instructor is unable to view the sampled responses, the application reports that there are no responses in the session. The method in question is `FeedbackSessionsLogic.getFeedbackSessionResultsForUserWithParams()`, but there appears to be no easy fix to this issue without compromising performance.

A separate bug has been discovered however, and can be found in #5770.

**Comment by damithc** [comment]
Perhaps that method should distinguish between having responses and having responses but invisible to the user. In the first case, it is safe to say there are no responses. in the 2nd case (rare), we may have to do further probes -- in spite of the performance hit -- before deciding there are no responses.

**Comment by chowyb** [comment]
The method seems to be used significantly by other session-related actions as well, and it will be difficult to customise it wihout affecting the other actions. I would also not recommend creating a copy of the method to cater specifically for this case (it's 300 lines long).

It is possible however to simply increase the sample size (an easy change), but this trades in performance in the common case (case 1) for the less common case (case 2), although increasing it to a relatively small number (10?) may not affect performance too much.

**Comment by damithc** [comment]
Is the problem random or repeatable?
Increasing the sample size doesn't fix the problem fully, right?

**Comment by chowyb** [comment]
The problem isn't exactly random, I'm not sure in what order responses get retrieved from the datastore, but assuming no one modifies the responses (making new submissions etc.) the same responses will be taken out every time, and yes increasing the sample size doesn't fix the problem, only reduces the chances of it happening.

Not knowing in what order responses get retrieved from the datastore is also the reason why I can't provide a method to replicate this bug, as the steps I use will work on one sample course, but not on another. I'll check if it's possible to replicate it on a new non-sample course though.

**Comment by kanghj** [comment]
I think we can fix this by deciding whether or not to display the message only after the page loads the rest of responses by ajax?

**Comment by wkurniawan07** [comment]
Fixed in V7
