### ISSUE TITLE
email alerts sent to respondents: include session instructions

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5768]
We can include session instructions in the email.

**Comment by HirdayGupta** [comment]
@damithc May I be assigned this issue?

**Comment by damithc** [comment]
@HirdayGupta go ahead and submit a PR. No need to be assigned.

**Comment by HirdayGupta** [comment]
@damithc Apologies for the delayed response. Now that I am done working on #7046, I would like to ask what session instructions are you referring to?

**Comment by damithc** [comment]
@HirdayGupta 

> I would like to ask what session instructions are you referring to?

When creating a session, the instructor can specify additional instructions on how to answer the questions.

**Comment by HirdayGupta** [comment]
@damithc `session.getInstructionsString()` returns an HTML formatted string that is enclosed in `<p></p>` paragraph tags. This is quite inconvenient for email formatting as the email ends up looking like this: 

<img width="1280" alt="screen shot 2017-04-08 at 4 35 28 pm" src="https://cloud.githubusercontent.com/assets/18088721/24828405/06f68a44-1c7a-11e7-800c-350ade935a71.png">

If I include a method that parses this string and returns it in the desired format, (say, without the p tag) then in which class in the util package should I place it? SanitizationHelper or StringHelper or something else? 

Or, alternatively, would you recommend working around this and formatting the session instructions differently in the email? For example:

<img width="1280" alt="screen shot 2017-04-08 at 4 48 24 pm" src="https://cloud.githubusercontent.com/assets/18088721/24828466/38ff5150-1c7b-11e7-85fb-2cdb353b6824.png">


Also, I can only test this on my local server as, for some reason, my Staging Server has run out of quota. Is there any way around this so I can view this email in an actual browser? I am currently copying the email HTML from the logs of the local server.

**Comment by damithc** [comment]
@HirdayGupta Can we put the session instructions inside a box (so that it doesn't get mixed up with the instructions in the email)?
