### ISSUE TITLE
Rich text support: make the formatting toolbar appear on demand

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5775]
The toolbar covering parts of the form look a bit untidy.
![image](https://cloud.githubusercontent.com/assets/1673303/16488344/a6029e30-3f02-11e6-9b2b-d71d8fe80439.png)

Should we show a small icon clicking of which inserts the toolbar at the top of the text box (without covering the other things)?

**Comment by belyabl9** [comment]
@damithc : this is how inline mode works. The alternative may be an icon that causes re-initialization of editor and switches between inline and form modes. If I haven't got you correctly, please, provide a simple prototype

**Comment by damithc** [comment]
Ok, have a look at the documentation and tell us what are the possible alternatives. I guess we should use one of the available options rather than implement our own custom mode.
The current mode is not that bad. If there are no better alternatives, we can stick with it.

**Comment by belyabl9** [comment]
I think 'fixed_toolbar_container' fits for our needs. Look:
![image](https://cloud.githubusercontent.com/assets/6876210/16496373/45470d36-3efa-11e6-9f74-0506eb4e070c.png)

![image](https://cloud.githubusercontent.com/assets/6876210/16496352/2f3e24b6-3efa-11e6-9cbe-5c77c9ff6cb5.png)

**Comment by wkurniawan07** [comment]
Will the toolbar always be present, or does it appear on demand like this issue states?

**Comment by belyabl9** [comment]
@wkurniawan07 : Toolbar will be present only if textarea is selected. These changes avoid overlapping the nearest fields by toolbar
