### ISSUE TITLE
User should be able to print(export) groupBy views in the feedback session responses.

### ISSUE THREAD

**Issue by rclakmal** [TEAMMATES/teammates#5779]
![snip20160701_3](https://cloud.githubusercontent.com/assets/794011/16507566/05a9a5f4-3f2b-11e6-8a12-51a28406a2ee.png)

As discussed on #5630, including groupBy views in csv download does not make much sense. But still there should be a way to export these different groupBy views. 

We can utilize [jQuery PrintElement](http://projects.erikzaadi.com/jQueryPlugins/jQuery.printElement/Sample/) plugin, which allows to open printer view focusing on a given element. Currently panels are not grouped in to one main `div`.  We should group them to a single div to use printElement on top of it.

@damithc What would be the action element for this task ? Do we need to show a separate button once an advanced groupBy view is selected ?

**Comment by damithc** [comment]
Rather, we should have a 'print' button in this page all the time for all views. It should give a printer friendly view of the whole page (i.e. excluding non-print-worthy items such as buttons).
