### ISSUE TITLE
Refactor FeedbackSessionsLogic.java

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#5780]
With the upcoming feature for custom feedback paths, there will likely be significant changes to these logic components as well. It would be good to refactor these in advance to allow easier extension of functionalities later.

**Comment by chowyb** [comment]
Retroactively changing the issue to focus only on `FeedbackSessionsLogic`. Other Feedback*Logic files will be covered under their own issues (eg. #6403)

**Comment by wkurniawan07** [comment]
Closed by #6374.
