### ISSUE TITLE
Standardize copy session button to use tooltip

### ISSUE THREAD

**Issue by YongJieYongJie** [TEAMMATES/teammates#5791]
The copy button uses the title attribute whereas other buttons uses tooltip, we should standardize to use tooltips because that is more common.

We can also elaborate more on the purpose of copying. Perhaps something like `Copy the feedback session to another course for reuse`

(the reason for inconsistency may be that the data-toggle attribute for the copy button is used to trigger the copy modal, but we should be able to use javascript to trigger the modal, and use the data-toggle for tooltips)

using title attribute:
![copy title](https://cloud.githubusercontent.com/assets/14101781/16550763/9252d120-41e1-11e6-886b-b9a00ad8c08e.png)

using tooltip:
![delete tooltip](https://cloud.githubusercontent.com/assets/14101781/16550764/93230b7e-41e1-11e6-8516-c1fb5cea6479.png)

**Comment by wkurniawan07** [comment]
@YongJieYongJie you may find #3865 interesting.
