### ISSUE TITLE
Instructor remind particular student: triggering two emails instead of one

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5797]
I tried sending a reminder to a particular student through the home page, and ended up sending two emails.
![image](https://cloud.githubusercontent.com/assets/1673303/16575457/e64fc448-42ba-11e6-803e-0120454ec5dd.png)

**Comment by damithc** [comment]
Is it because I'm both a student and an instructor in that course?

**Comment by kanghj** [comment]
Yes, it's because the email of that student is associated with both a student and instructor.

**Comment by damithc** [comment]
I see, so it is not going to be a frequent occurrence. The content of the two emails look different though. Is that intended.?

**Comment by chowyb** [comment]
Just reached the section of code that touches sending of reminder emails (as part of refactoring), and confirmed that the code will send two separate emails if the email is associated with both a student and instructor.

The two emails in the screenshot look about the same however, excluding for the link. Gmail uses a purple colour to mark text which it thinks was quoted from a previous email from what I remember.

**Comment by damithc** [comment]
The difference: one email contains the key while the other doesn't. But I think that's because instructors are using Google accounts and don't need the key to access the session.

**Comment by kanghj** [comment]
Yes, the key is to allow unregistered students to submit responses

**Comment by damithc** [comment]
i suppose sending two emails is the correct behavior (as the two submission links are different) as long as the instructor has questions to respond to.
