### ISSUE TITLE
Visibility preview not shown immediately after a new question is added

### ISSUE THREAD

**Issue by JosephineKwa** [TEAMMATES/teammates#5821]
This is what the visibility preview looks like immediately after a new question is added:
![vp](https://cloud.githubusercontent.com/assets/9999077/16725008/efad2626-4787-11e6-94a7-48b9a2ee57cc.PNG)
It only gets updated if the "Preview Visibility" button is clicked.

**Comment by damithc** [comment]
Is this a recent bug already in production (i.e. V5.82 or before?)

**Comment by kanghj** [comment]
It's already in production in V5.81. @YongJieYongJie

**Comment by damithc** [comment]
Oops.  Better fix it fast. We can do a release as soon as it's fixed. As
always, add a failing test first.
>
>

-- 
Sent from a mobile device.

**Comment by wkurniawan07** [comment]
Our good old friend #5671 is the cause once again. @YongJieYongJie
