### ISSUE TITLE
Typo in enableJS.jsp: conformation

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#5832]
In `src/main/webapp/enableJS.jsp`, there is the following line under the section to enable JavaScript in Internet Explorer:

`<li>Answer yes to the following conformation box.</li>`

"conformation" should be "confirmation" instead.

**Comment by Naruto8** [comment]
This is my first time, so sorry if I make a mistake. I have fixed the typo and sent a pull request. So, let me know whether what I did was right. This would be great motivation for me. Thanks!!

**Comment by chowyb** [comment]
Hi @Naruto8,

I have commented on your previous pull request. You will need to open a new one with the correct naming (branch and pull request) to continue, everything else looks fine though :)
