### ISSUE TITLE
getFeedbackSessionEntity should use lookup by key 

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#5837]
If `feedbackSessionId` always used the same format `feedbackSessionName%courseId`, we should be able to lookup the FeedbackSession by key instead of using a query.  This has the added benefit of not retrieving an older version of the entity, important for #5505 to make it easier to debug in future.

**Comment by damithc** [comment]
Closing because the linked issue is closed.

**Comment by whipermr5** [comment]
Just realised this was fixed in #8235 ([relevant line](https://github.com/TEAMMATES/teammates/pull/8235/files#diff-a6fa1d3cb3ad7c706264ec6ed43a4701R468)).
