### ISSUE TITLE
Rubrics questions: change suffix to be consistent with other questions

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#5847]
For rubrics questions, the usual suffix is in the form `{question number}-{row}-{column}`, which is inconsistent with other question types (eg. `{row}-{question number}` for MCQs, MSQs, constSum). This should be changed to a form that is more consistent with other question types, such as the form `{row}-{column}-{question number}`.

**Comment by ParmaarK** [comment]
@chowyb InstructorFeedbackEditPage class needs to be changed right?

**Comment by sukanta-27** [comment]
@damithc @xpdavid IMO, rubric questions have a better suffix than MCQ/MSQ. I think it is better to go from high level to low level in the id, like in rubric question `{question number}-{row}-{column}` than to go from low to high (or inner to outer parts of the DOM whatever that is called :P ) like  `{row}-{question number}`. 

I think it makes selecting elements and manipulating them easier. Would like some thoughts on this.

**Comment by sukanta-27** [comment]
@damithc @xpdavid @bqnguyen94 Will like your thoughts on https://github.com/TEAMMATES/teammates/issues/5847#issuecomment-403195768

**Comment by xpdavid** [comment]
Let's ask the author @chowyb for inputs?

Regarding
> I think it makes selecting elements and manipulating them easier.

I think we have [`CSS [attribute$=value] Selector`](https://www.w3schools.com/cssref/sel_attr_end.asp)?

**Comment by wkurniawan07** [comment]
V7 does not employ this kind of direct DOM manipulation anymore.
