### ISSUE TITLE
Make tool tip text decoration more subtle

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5860]
The current one is black dashes. May be gray dots will be more subtle? Not sure if it is possible though.

**Comment by chowyb** [comment]
Would this work? The colour of the dots below is the same as the current dashes.
![dotted](https://cloud.githubusercontent.com/assets/7546744/16907981/7adf4fc2-4cfa-11e6-860d-619c438f270b.png)

It could be made lighter as well:
![dotted2](https://cloud.githubusercontent.com/assets/7546744/16908021/bdfd0326-4cfa-11e6-8faf-c1d8837d9e42.png)

**Comment by damithc** [comment]
Yes, that looks more subtle. And yes, color can remain the same.
