### ISSUE TITLE
Instructor: clarify access control for moderating responses is same as permission for modifying comments 

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#5861]
The permission for an instructor to modify a student's response is currently the permission for modifying comments. Since this may not be very intuitive, we can either add a new permission for it, or document it  in instructorHelp or provide an explanation in `instructorCourseEditPage` .

**Comment by damithc** [comment]
The UI gives it as `Sessions: Edit/Delete Responses/Comments by Others` which is probably clear enough. Will close for now.
