### ISSUE TITLE
Some emails still carrying the old link description

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5862]
Here's an example:
![image](https://cloud.githubusercontent.com/assets/1673303/16908369/7eb88746-4cfd-11e6-9f4b-fa67dd294d78.png)
It should be like this instead.
![image](https://cloud.githubusercontent.com/assets/1673303/16908380/9316d724-4cfd-11e6-8807-9531b670a355.png)

**Comment by damithc** [comment]
Whoever did the recent related issue can take this one too?

**Comment by tarun14110** [comment]
@damithc can you please recheck, that those emails are not from previous version ? I had checked, seems it can't happen. We even don't have any string `The student's unique submission url appears here`.

**Comment by damithc** [comment]
Yes it is possible that emails were triggered by the previous version while I was testing the new version. We'll KIV this until we find more evidence of this.

**Comment by wkurniawan07** [comment]
This is impossible to happen now, as @tarun14110 has mentioned.
