### ISSUE TITLE
Make 'question description' text box taller and add a placeholder text

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5871]
It's better if the 'description' text box is resizeable just like the text box above it.
![image](https://cloud.githubusercontent.com/assets/1673303/16912437/b4885e96-4d16-11e6-935a-61556fc1c245.png)

**Comment by damithc** [comment]
@belyabl9 can have a go at this one?
While you are at it, we can make the height of the first text box about 2 lines and the height of the description text box about 4 lines (a visual hint that the question should be short and the description can be longer). 
We can also add placeholder text to both text boxes.
Question: `A concise version of the question e.g. "How well did the team member communicate?"`
Description: `More details about the question e.g. What criteria to consider when answering the question`

**Comment by belyabl9** [comment]
@damithc , ok, I'll do these changes

**Comment by damithc** [comment]
Just realizes the text box auto-resizes based on content size, so there is no need to make it specifically resizeable. But you can still do the other enhancements suggested.

**Comment by belyabl9** [comment]
@damithc , may these proposed placeholder text variants be used without changes ? Let's choose them before the PR in order not to regenerate static tests some times.
Q: "A concise version of the question e.g. "How well did the team member communicate?"
D: "More details about the question e.g. "What criteria to consider when answering the question""

The issue is delayed, because TinyMCE does not have a built-in support for placeholders in inline mode, so I'm working on a unified solution that may be used throughout the web-interface

**Comment by damithc** [comment]
@YongJieYongJie any input on the phrasing of placeholder text?

**Comment by YongJieYongJie** [comment]
The placeholder text reads fine, except that the example for the description is not really an example. Perhaps we can use something like "More details about the question e.g. `What criteria to consider when answering the question e.g. "In answering the question, do consider communications made informally within the team, and formal communications with the instructors and tutors.`

**Comment by belyabl9** [comment]
@damithc , @YongJieYongJie , please, have a look on a result:
![image](https://cloud.githubusercontent.com/assets/6876210/17193260/ee7a71ca-545a-11e6-8fbf-f720995d8dce.png)

**Comment by damithc** [comment]
Looks fine @belyabl9

**Comment by YongJieYongJie** [comment]
@belyabl9 Is there a relatively easy way to standardize the padding within the text boxes? Currently, the top padding of the description box is visibly larger.

**Comment by belyabl9** [comment]
@YongJieYongJie , I'll make padding-top:5px within the PR for this issue
![image](https://cloud.githubusercontent.com/assets/6876210/17204586/ee123ba6-54ae-11e6-9ffe-c3aa7ec14d8a.png)

**Comment by YongJieYongJie** [comment]
@belyabl9 If you're fixing the padding-top, let's fix the padding-left right bottom etc. too

**Comment by belyabl9** [comment]
@YongJieYongJie , 5px is ok, yes ?

**Comment by YongJieYongJie** [comment]
@belyabl9 5px 10px looks fine. Perhaps you can post a screenshot so everyone who's interested can see.

**Comment by belyabl9** [comment]
@YongJieYongJie , here it is:
![image](https://cloud.githubusercontent.com/assets/6876210/17271673/8b339308-568a-11e6-9e7e-d041043c5c01.png)
