### ISSUE TITLE
Instructor: home page: stay in home page after sending reminder emails

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#588]
Current: when an instructor sends a reminder using the home page, the entire home page loads again.

![image](https://cloud.githubusercontent.com/assets/1673303/25749340/ba715c2c-31e0-11e7-98ad-c5133c3a1e13.png)

Suggested: we can perform the action using an ajax request, avoiding the page reload.

**Comment by nikiforosbotis** [comment]
@damithc I would like to work on that.

**Comment by nikiforosbotis** [comment]
@damithc I checked out the problem that is described on this issue and I am pretty confident that the desired behavior is already implemented (I pushed the button to send reminding emails and then it showed me this image:)
![a](https://cloud.githubusercontent.com/assets/9116253/24375865/9c3ef884-1342-11e7-8063-f60003a45642.png)

Have I misunderstood anything or am I correct?

**Comment by damithc** [comment]
@nikiforosbotis In some sense, yes it stays in the same page. However, it loads the entire page again instead of keeping the previous page; the latter is more desirable. But then again, I'm not sure it's too difficult to implement for a new contributor.

**Comment by nikiforosbotis** [comment]
@damithc Yes I agree, it is not something I am very familiarized with. I prefer to work on the other issues I have commented on so this is available for anyone else who wants to contribute on that.
