### ISSUE TITLE
New Contributor Self Intro [Hashma Shahid]

### ISSUE THREAD

**Issue by hshahid** [TEAMMATES/teammates#5889]
**URLs to my fork and teammates app:**

**My fork:** https://github.com/hshahid/teammates
**My app:** http://v4-dot-teammates-divya.appspot.com/

**Changes:**
I added a form to the 'Contact Us' page to make it easier and smoother for a user to send an email to the Teammates team. 
**Before:**
<img width="887" alt="screen shot 2016-07-20 at 7 23 05 pm" src="https://cloud.githubusercontent.com/assets/8768780/16989919/723b0828-4eaf-11e6-835c-de93f741902b.png">

**After:**
<img width="920" alt="screen shot 2016-07-20 at 7 29 50 pm" src="https://cloud.githubusercontent.com/assets/8768780/16991727/0052dc98-4eb6-11e6-892d-aaa8a80fdb45.png">

**About me:**
Hi, my name is Hashma Shahid and I am currently double majoring in Computer Science and International Relations at Mount Holyoke College. I have wanted to be a part of the opensource community for a long, long time but felt there wasn't enough instruction on how to start. I'm hoping this project will give me the experience needed to start giving back to the coding community! I also want to improve my coding skills to excel as a software engineer. 

I made changes to the Contact Us form to so users can directly send an email through the website and it's easier for them to report issues/concerns. 

Thanks,
Hashma

**Comment by wkurniawan07** [comment]
Welcome to the TEAMMATES contributors community, @hshahid!
Good job on setting up the project and deploying to a staging server! Your forked app's "contact us" page does not seem to reflect what is seen on the screenshot above, though.
You can start contributing by working for issues marked `d.FirstTimers` (but do not do more than one of these), continuing with issues marked `d.Contributors`. Looking forward to your contributions!
