### ISSUE TITLE
Unable to add new questions on Chrome

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#5894]
On submitting the form for creating a new question, the button displays 'Saving' and gets disabled, but the form is not submitted.

Edit: Chrome 51.0.2704.103 m (64-bit)

**Comment by damithc** [comment]
This bug is not in production, right?

**Comment by kanghj** [comment]
Not yet, the cause of this should be a recent PR (#5858). @rclakmal, can you take look at this issue?

**Comment by chowyb** [comment]
Early question, but how do we write a test for this issue? Our standard way of using Firefox won't work here.

**Comment by kanghj** [comment]
Maybe we can't write a test in this issue, I guess. @wkurniawan07, with the latest selenium upgrade, are we able to enable testing using Chrome again?

**Comment by rclakmal** [comment]
I am looking in to this.

**Comment by rclakmal** [comment]
Found the [cause](http://stackoverflow.com/questions/20157321/disabling-a-submit-button-when-clicking-on-it-will-prevent-the-form-from-being). Will look for a suitable solution

**Comment by wkurniawan07** [comment]
@kanghj I'm positive it can because the major issue is the `element.click()` which is fixed. There might be more fixes needed, I'll be looking into it.
