### ISSUE TITLE
BACKDOOR STATUS FAILURE when running local tests.

### ISSUE THREAD

**Issue by g2mark** [TEAMMATES/teammates#5907]
Getting this message upon running Local tests after starting dev server:

> java.lang.AssertionError: expected:<[BACKDOOR_STATUS_SUCCESS]> but was:<[BACKDOOR_STATUS_FAILURE] Assertion error Non-null value expected>

localhost:8888/backdoor gives:
> Server failed to respond within a reasonable time.
> This may be due to an unusually high load at this time.

**Comment by damithc** [comment]
Are you able to access dev server using a browser?

**Comment by g2mark** [comment]
Yes localhost:8888 does give me the page

**Comment by wkurniawan07** [comment]
Hi @g2mark, accessing `localhost:8888/backdoor` on its own without passing any parameters is expected to give that server error message (although I have to admit the error message is misleading). Can you identify which test gives that assertion error?

**Comment by g2mark** [comment]
<img width="1038" alt="screen shot 2016-07-24 at 8 54 04 pm" src="https://cloud.githubusercontent.com/assets/4411302/17087871/f2811976-51e0-11e6-8df7-e0ff8f93b658.png">

**Comment by chowyb** [comment]
@g2mark the error above is likely from an older version, as this problem has been fixed in #5852. Pulling the latest version, and running `gradlew.bat resetEclipseDeps` from the command line should resolve the issue.

**Comment by g2mark** [comment]
Thank you!
