### ISSUE TITLE
Travis tests not passing even on multiple retries

### ISSUE THREAD

**Issue by g2mark** [TEAMMATES/teammates#5910]
I followed the instructions to retry the Travis tests if they aren't working due to timing issues, but after 4-5 times i still get these 17 failures.  Should i keep trying?

<img width="1041" alt="screen shot 2016-07-24 at 9 50 43 pm" src="https://cloud.githubusercontent.com/assets/4411302/17088437/e768d8d2-51e8-11e6-8d7a-514d1781aea2.png">

**Comment by chowyb** [comment]
@g2mark is it possible to show a screenshot of what the difference between expected and actual output is? You can double click on the "AssertionError" on the right to bring up the comparison window.

**Comment by g2mark** [comment]
<img width="1407" alt="screen shot 2016-07-24 at 11 23 35 pm" src="https://cloud.githubusercontent.com/assets/4411302/17089530/b1b84d50-51f5-11e6-9563-622488782259.png">

**Comment by chowyb** [comment]
@g2mark this may be a strange question to ask, but are you using JDK 7?

**Comment by g2mark** [comment]
@chowyb Ah after investigating I see what happened.  I did set Eclipse to use 7 but the project still had 8 in its build path for some reason and was using it.  I changed it and every test passed except this one:

<img width="1400" alt="screen shot 2016-07-25 at 12 25 45 am" src="https://cloud.githubusercontent.com/assets/4411302/17090445/829cc862-51fe-11e6-9859-0797e04509c1.png">

**Comment by chowyb** [comment]
@g2mark it might have to do with your mouse hovering over the browser while the test is running, causing buttons to appear where they normally wouldn't (since they appear on hover). You might have to move the mouse to a location where it won't be in the browser window (maybe at the top of the screen?)

**Comment by damithc** [comment]
@chowyb thanks for helping @g2mark to troubleshoot the setup :+1:

**Comment by g2mark** [comment]
Yes all good!  Thanks @chowyb
