### ISSUE TITLE
instructorFeedbackResultsPage: "Collapse students" button does not work correctly when not grouped by question

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#5911]
On a non-question view like 'Giver > Recipient > Question', and when the students are not grouped by teams, the "Collapse Students" button does not work correctly on participants who have not responded (the grey panels). The cause of this is code duplication in `instructorFeedbackResults.js` and the js files for ajax loading.

**Comment by belyabl9** [comment]
I'll fix it
