### ISSUE TITLE
Instructor Home Page: Sorting by date does not take year into account

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#5922]
On the instructor home page, when sorting session by "Start Date" and "End Date", the year is not taken into account, and as such, "01 Mar 2016" is taken to be an earlier date than "01 Apr 2012" (as an example).

**Comment by rclakmal** [comment]
@chowyb Could the results be confusing to the user since we are not showing the year? (year is only visible in the tool tip)

**Comment by damithc** [comment]
I don't think so. The user is expected to know the year even if it is not shown. :-)

**Comment by rclakmal** [comment]
@damithc @chowyb I will look in to this issue
