### ISSUE TITLE
Missing space between question description and feedback path

### ISSUE THREAD

**Issue by YongJieYongJie** [TEAMMATES/teammates#5925]
@damithc May I check if this UI change was intended, i.e., removing the gap between question itself and the feedback path?

It was introduced in ab7f961aed951054c382782abb3393e3802bc951 #5784

![2016-07-27-113554_1280x800_scrot](https://cloud.githubusercontent.com/assets/14101781/17163094/528fe162-53ee-11e6-9f4c-c421e5770b11.png)

**Comment by damithc** [comment]
No it wasn't.

**Comment by YongJieYongJie** [comment]
@belyabl9 would you be able to handle this since you are more familiar with the concerns around the rich text description text box?

**Comment by belyabl9** [comment]
@YongJieYongJie , I'll have a look
