### ISSUE TITLE
Deleted students trying to join: handle the NPE

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5931]
If a student was deleted from a course, when the student tries to join using the join link, we throw a NullPointerException.

**Comment by nsaiisasidhar** [comment]
Hi, I want to contribute to this issue. Could you please let me know if the exception needs to propagate any error message to UI, and the associated class files to be checked for making code changes.

**Comment by damithc** [comment]
@nsaiisasidhar have you done a `forFirstTimers` issue already?
