### ISSUE TITLE
Moderating responses/previewing sessions heading does not properly escape HTML characters

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#5932]
When moderating a student's responses, the heading of the page does not properly escape HTML, resulting in HTML elements possibly being introduced into the heading.
![sani](https://cloud.githubusercontent.com/assets/7546744/17198033/87fc4244-54a4-11e6-853e-c750f226d419.png)

Edit: This also applies to previewing sessions.

**Comment by kanghj** [comment]
The fix for this is in #4700
