### ISSUE TITLE
InstructorSearchPageUiTest: variable actual result

### ISSUE THREAD

**Issue by belyabl9** [TEAMMATES/teammates#5936]
Two independent PRs are failing due to variable results of this test.
Was this functionality modified in the recent time ?

**Comment by wkurniawan07** [comment]
I've left a comment in one of those PRs. I'll take a look at the other one shortly.

**Comment by belyabl9** [comment]
@wkurniawan07 , I think the reason was quite obvious - the wrong cursor place while running the test.
Please, close this issue

**Comment by wkurniawan07** [comment]
Wrong cursor place should not cause an element to be hidden. But sure, this can be reopened whenever needed.
