### ISSUE TITLE
student view team: Show team member profile photo

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5943]

**Comment by damithc** [comment]
@chowyb can you give this one a try? I need it for CS2103. Photos can be loaded on demand.

**Comment by tarun14110** [comment]
@damithc Can I work on this ?

**Comment by damithc** [comment]
Sure @tarun14110 
Thanks for volunteering :+1: .

**Comment by tarun14110** [comment]
Which one is better ?

![screenshot from 2016-07-31 20 00 09](https://cloud.githubusercontent.com/assets/12219700/17277192/53a4fed8-575a-11e6-8055-bc7a42a9b878.png)


![screenshot from 2016-07-31 20 06 37](https://cloud.githubusercontent.com/assets/12219700/17277193/540f0a9e-575a-11e6-86ad-97bca4d67106.png)

**Comment by damithc** [comment]
Use a vertical format instead. That way, it can scale up to any team size.
[photo][details]
[photo][details]
...

**Comment by tarun14110** [comment]
The above format take cares of big team sizes, next team member comes in next row. Doing vertical way we will waste a lot of space, lot of scrolling will be required to see all faces ? Vertical format will be better if we need to display more info about each team member other than name ?

**Comment by damithc** [comment]
I prefer vertical because we can show more information in the  2nd column. As of now, it may by just the name and the email, but in future we can add more details there. e.g. more details from the profile page.

**Comment by wkurniawan07** [comment]
To get the best of both worlds, try vertical but stack where possible?
[photo][details][photo][details]
[photo][details][photo][details]
...

**Comment by tarun14110** [comment]
sure. Sending PR in few minutes.
