### ISSUE TITLE
teammates dev server will start but having issues using it.

### ISSUE THREAD

**Issue by MiniOtacon** [TEAMMATES/teammates#5949]
**Specifications**
Mac OSX
EclipseIDE for Java Developers: 4.5.2
JDK: 1.7.0_79
Google App Engine: 1.9.40

**Issue**
I made it to step 8 of [setting up the dev server](https://github.com/TEAMMATES/teammates/blob/master/devdocs/settingUp.md#setting-up-the-dev-server), but when I tried accessing "http://localhost:8888/admin/adminHomePage" it redirected me to "http://localhost:8888/errorPage.jsp" and printed a stacktrace to the console (which I've provided a log file of the console, [console.txt](https://github.com/TEAMMATES/teammates/files/392742/console.txt)).
![dev server started](https://cloud.githubusercontent.com/assets/14066723/17280479/a90421b6-5745-11e6-87dd-01faecc4f3c7.png)

I'm not really sure why the admin console "http://localhost:8888/_ah/admin" will work but not the adminHomePage location that caused those errors. Any suggestions?

**Comment by damithc** [comment]
JSP is compiled on demand, so compile errors can emerge even after starting the server. Check in eclipse to see if it shows any jsp errors.
![image](https://cloud.githubusercontent.com/assets/1673303/17282878/128134ac-57dd-11e6-863f-b9bc9dd5aad2.png)

**Comment by MiniOtacon** [comment]
It looks like Google App Engine (GAE) is giving errors and JSP lists a couple dozen warnings. I've tried reinstalling GAE (and even tried version 1.9.34 instead of 1.9.4) and rebuilding with gradle but I still have GAE errors
![errors2](https://cloud.githubusercontent.com/assets/14066723/17283983/34fe320e-576b-11e6-8b05-b125270c26b2.png)

And since you can't see the full error description, here is the copied text of the mentioned errors:

* The App Engine SDK JAR appengine-api-1.0-sdk-1.9.40.jar is missing in the WEB-INF/lib directory	lib	/teammates/src/main/webapp/WEB-INF	Unknown	Google App Engine Problem
* The App Engine SDK JAR appengine-jsr107cache-1.9.40.jar is missing in the WEB-INF/lib directory	lib	/teammates/src/main/webapp/WEB-INF	Unknown	Google App Engine Problem
* The file src/main/webapp/WEB-INF/lib/appengine-api-labs.jar has a different size than App Engine SDK library appengine-api-labs.jar; perhaps it is a different version?	appengine-api-labs.jar	/teammates/src/main/webapp/WEB-INF/lib	Unknown	Google App Engine Problem
* The file src/main/webapp/WEB-INF/lib/appengine-endpoints-deps.jar has a different size than App Engine SDK library appengine-endpoints-deps.jar; perhaps it is a different version?	appengine-endpoints-deps.jar	/teammates/src/main/webapp/WEB-INF/lib	Unknown	Google App Engine Problem
* The file src/main/webapp/WEB-INF/lib/appengine-endpoints.jar has a different size than App Engine SDK library appengine-endpoints.jar; perhaps it is a different version?	appengine-endpoints.jar	/teammates/src/main/webapp/WEB-INF/lib	Unknown	Google App Engine Problem

**Comment by wkurniawan07** [comment]
@MiniOtacon based on the console outputs these are the problems that you may need to rectify:
- Use SDK 1.9.27 instead of any other versions.
- Configure Eclipse to use JDK 1.7 (not JRE, not Java 8).

The existing JSP warnings are fine to be ignored.

**Comment by MiniOtacon** [comment]
@wkurniawan07, it was the Google App Engine version that was causing those errors, the server runs as expected now. Thanks so much for the help, this issue can be closed.

**Comment by wkurniawan07** [comment]
@MiniOtacon the accounts in `test.properties` are not useful other than when you are running test. If you want to go to the admin pages in dev server, all you need to do is ticking "Log in as administrator" when entering login credentials (any ID will do).
