### ISSUE TITLE
New contributor self intro [Pratyoush Srivastava]

### ISSUE THREAD

**Issue by pratyoushs** [TEAMMATES/teammates#5952]
1. **Link to my app**: http://4-18-dot-teammates-pratyoushs.appspot.com/index.jsp

2. **Link to my fork:** https://github.com/pratyoushs/teammates

3. **Changes**: Fixed the top navigation bar to make it easier to navigate to different pages without scrolling to top.
![teammatescapture1](https://cloud.githubusercontent.com/assets/15091305/17308290/31e078d8-5807-11e6-866c-5d75279a6a01.JPG)
![teammatescapture2](https://cloud.githubusercontent.com/assets/15091305/17308292/31e46448-5807-11e6-9754-b5695fe727d8.JPG)
![teammatescapture3](https://cloud.githubusercontent.com/assets/15091305/17308291/31e2dbd2-5807-11e6-8006-71a675ab56e5.JPG)

4. **Self Intro**: My name is Pratyoush Kumar Srivastava. I am graduate student studing in University of Florida majoring in Computer Science. I have always wanted to be part of the opensource community but always feared making contributions. Through your project I not only want to learn and gain valuable experience but also want to give back to the opensource community. I hope I will be able to make some valuable contributions to Teammates!
Thanks,
Pratyoush.

**Comment by wkurniawan07** [comment]
Hi @pratyoushs, welcome to the TEAMMATES community!
Good job on setting up as well as deploying your own fork to the staging server! You can start contributing by fixing an issue labeled `d.FirstTimers` (do just one of this), then moving on to issues labeled `d.Contributors` (recommended). Looking forward to your contributions!
