### ISSUE TITLE
Instructor copy session: check for empty session name before submitting

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5955]
Prevent submitting this form (and point out the problem) if the session name is empty.
![image](https://cloud.githubusercontent.com/assets/1673303/17361882/3ff68b0c-59a5-11e6-83c4-5a0b9b2a012f.png)

The current one not only submits the form with the empty value, but also sends the user to a course different from the one he was using before.

**Comment by rclakmal** [comment]
@damithc Shall I take this up ?

**Comment by damithc** [comment]
Sure. Thanks @rclakmal
