### ISSUE TITLE
Instructor help page: make 'create new session' responsive

### ISSUE THREAD

**Issue by YongJieYongJie** [TEAMMATES/teammates#5965]
To have a side bar in the help page (as per #5616), the form for creating new feedback session needs to be responsive:

![responsive](https://cloud.githubusercontent.com/assets/14101781/17463847/fcd1fe36-5d02-11e6-8850-dbc25dbd7f7a.png)

**Comment by amarlearning** [comment]
@YongJieYongJie @damithc  @wkurniawan07 Can i take this one ?

**Comment by damithc** [comment]
@amarlearning go ahead.

**Comment by amarlearning** [comment]
@damithc I found some useless code in the `instructorHelp.jsp`, what should I do with it?
This code is used in this page repeatedly. ([lines](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/instructorHelp.jsp#L8834-L8835), [lines](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/instructorHelp.jsp#L8821-L8822) and [lines](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/instructorHelp.jsp#L8824-L8832) )

Please let me know if I am missing out something!

![screenshot from 2017-04-09 15-00-39](https://cloud.githubusercontent.com/assets/9383897/24836287/d16a3dc8-1d35-11e7-828d-e2d2b8befa49.png)

**Comment by amarlearning** [comment]
@damithc As YongJieYongJie said in this [comment](https://github.com/TEAMMATES/teammates/issues/5616#issuecomment-230420900), The HTML structure of various sections of the help page is inconsistent and should be fixed before progressing further on this issue.

so this might take some time!

**Comment by damithc** [comment]
I'm ok with cleaning up the code first. Just create issues for them and proceed with submitting PRs for them.

**Comment by amarlearning** [comment]
@wkurniawan07 I have to write some Js code in order to resolve this issue. As there is no JavaScript file for the `instructorHelp.jsp`. 

Should I make a new Js file for this page, or in which file should I write please let me know?

**Comment by wkurniawan07** [comment]
No longer relevant as components in help page in V7 are directly created from the original component.
