### ISSUE TITLE
Copying session fails due to new question type

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#5966]
In certain conditions, copying a session now fails due to a FatalNucleusUserException.

**Comment by damithc** [comment]
Sounds bad. Under what conditions?

**Comment by kanghj** [comment]
I'm not very certain of the cause since it doesn't happen consistently, but it does seem like larger sessions are more vulnerable to this

**Comment by kanghj** [comment]
@damithc, @wkurniawan07, let's revert #5842 for this milestone?

**Comment by damithc** [comment]
Sure. It it because larger sessions break the limitation of how many edits can be done to an entity group in a short time?

**Comment by kanghj** [comment]
The error is that there were too many entity groups getting edited in a single transaction, so there's code where questions are getting related to the session but not getting created in the same entity group.

**Comment by wkurniawan07** [comment]
This shouldn't be that high a priority anymore since the new question entity is scrapped. @kanghj perhaps you can make a fix against the new question entity branch?
