### ISSUE TITLE
Instructor: edit question visibility: warn that existing responses will be deleted when visibility is changed

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5980]
Perhaps we can warn the instructors that changing the visibility after collecting responses is not recommended. 
However, we should have a way to limit the number of such warnings, as we don't want to annoy the user by showing the same warning too many times.

**Comment by damithc** [comment]
I would like to do this soon, because more and more instructors run into this problem after the submissions are collected.

**Comment by rclakmal** [comment]
@damithc What about indicating this as a tool tip in the edit visibility button ?

**Comment by damithc** [comment]
That's not good enough. We can't expect people to read tool tips. Note that the user might not even edit the visibility.

**Comment by rclakmal** [comment]
Yeah agreed! 
How about a warning text indicating the same placed within the visibility section ? What ideas do you have in mind ?

**Comment by junhaoyap** [comment]
We can add a warning that pops if and only if the visibility change is being submitted when there are already responses? @damithc

**Comment by damithc** [comment]
That's too late. We already do something like that.

**Comment by HirdayGupta** [comment]
@damithc How about this: **If** an instructor attempts to edit a question that already has responses, the visibility section colour changes to red and displays a warning?

Something like this:
![screen shot 2017-06-02 at 2 05 03 pm](https://cloud.githubusercontent.com/assets/18088721/26717868/95e1d702-479c-11e7-8daf-3836776bb9de.png)

(Screenshot for demo purposes only. Will work on a nicer looking design for the warning box).

**Comment by damithc** [comment]
That works too, but a confirmation dialog is easier to implement/test and harder for the user to ignore? I'm ok with the current suggestion too.

**Comment by HirdayGupta** [comment]
> A confirmation dialog harder for the user to ignore

As mentioned by you earlier sir, we are already giving a popup if the instructor submits any changes to the visibility. And also, as rightly pointed out by you, too many popups might annoy the user. Hence I proposed this solution.

**Comment by damithc** [comment]
You have a point. Go ahead.
