### ISSUE TITLE
Instructor home page: reorganize buttons on the course panel

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5983]
The current `edit` and `view` are a bit misleading.

![image](https://cloud.githubusercontent.com/assets/1673303/17641735/207c3c6a-615f-11e6-9099-2383841d2c19.png)

We can use drop down buttons instead:
```
Students
    Enroll
    View/Edit

Instructors
    View/Edit

Sessions
    Add

Course
    Archive
    Delete
```

**Comment by belyabl9** [comment]
@damithc , I'd like to do this task. I've prepared sample implementation, please, have a look if it is what you expect
![image](https://cloud.githubusercontent.com/assets/6876210/17649346/e8a0fce4-623b-11e6-93c7-2099dda72c2e.png)

![image](https://cloud.githubusercontent.com/assets/6876210/17649348/f5fe5e22-623b-11e6-9820-00ddd86e7fd3.png)

![image](https://cloud.githubusercontent.com/assets/6876210/17649349/0113d990-623c-11e6-9fe5-6b9905ac7180.png)

![image](https://cloud.githubusercontent.com/assets/6876210/17649350/0b23bb94-623c-11e6-9035-b474c08b2c91.png)

![image](https://cloud.githubusercontent.com/assets/6876210/17649351/1617a560-623c-11e6-939e-1c7a62698f8e.png)

By the way, as I see from the sources we have one more button there - for pending comments. What location is expected for it ?

**Comment by damithc** [comment]
The sub-menu looks like buttons instead of menu items. Compare that with how the `Remind` sub menu looks. Can we get a similar 'flat' look?
Can you add a screenshot with the existing comments button (to see how it looks with the new buttons)?

**Comment by belyabl9** [comment]
@damithc , please, have a look at this one
![image](https://cloud.githubusercontent.com/assets/6876210/17660227/a8c7689c-62e0-11e6-99f2-bf7dfaa211d7.png)

**Comment by damithc** [comment]
We can keep the comments button as it is.
Why does the drop down menu doesn't look as nice as the `Remind` button.? The `Remind` drop-down looks like a built in bootstrap control while the `Students` one looks like we hand-coded it.

**Comment by belyabl9** [comment]
I've used bootstrap classes for these dropdown buttons. Could you, please, clarify what exactly you don't like ?

**Comment by damithc** [comment]
In that case, it should be fine. I was wondering why this divider is missing.
![image](https://cloud.githubusercontent.com/assets/1673303/17663014/12dc4988-631c-11e6-9fa5-4df74ba2bf33.png)
In addition, is it possible to style the drop down to match the button? i.e. font size and colors

**Comment by belyabl9** [comment]
Ok, I'll try to make them as similar as possible
