### ISSUE TITLE
Instructor copy session: 'copy' button doesn't show any activity after clicking

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5986]
The copy button takes some time to show some activity. Users can think the click didn't go through and click again.

**Comment by damithc** [comment]
@rclakmal you did a similar thing somewhere else, am I right? Can you point to that PR here so that the person doing this issue can follow the same?

**Comment by rclakmal** [comment]
This was with #5858

**Comment by rclakmal** [comment]
@damithc I would take this up myself. Could you put a screen on which copy button you are talking about ?

**Comment by damithc** [comment]
`Copy session` opens a modal dialog. I'm referring to the button in that modal dialog.
