### ISSUE TITLE
Instructor add essay question: Typo in tooltip

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5995]
![image](https://cloud.githubusercontent.com/assets/1673303/17731144/991a34a0-649e-11e6-9fcd-8b3f1d0a6aa9.png)

Should be `... shown to the ...`

**Comment by damithc** [comment]
@tarun14110 can you fix this one?

**Comment by dp80** [comment]
Can i fix this if it is not in progress already?

**Comment by damithc** [comment]
@dp80 sure go ahead.
