### ISSUE TITLE
Instructor: edit question: show spinner while loading visibility preview

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5996]
It's best if we show the spinner while loading the updated visibility preview.

**Comment by xpdavid** [comment]
This one is relatively easy to do. I recommend mark it as `d.FirstTimer` issue. Refer to #6375

**Comment by hardik124** [comment]
Hey , I am a first timer and I want to contribute.

**Comment by SmokinClove** [comment]
This is for the instructor feedback edit page right?
Thanks.
Van

**Comment by damithc** [comment]
> This is for the instructor feedback edit page right?

Yes, here:
![image](https://cloud.githubusercontent.com/assets/1673303/23821709/254ed5f6-0676-11e7-9f2c-1209bcb136df.png)

**Comment by SmokinClove** [comment]
Got it, thanks Prof. Will create a PR after testing.
Van

**Comment by HirdayGupta** [comment]
Working on this
