### ISSUE TITLE
Travis ./gradlew createConfigs testClasses" failed

### ISSUE THREAD

**Issue by sharvinbala** [TEAMMATES/teammates#6006]
Hi everyone. I'm new to github and I've been trying to build the latest code using travis but it's returning with "The command "./gradlew createConfigs testClasses" failed and exited with 126 during ." Not sure what I'm missing though. Your guidance is much appreciated. Thank you in advance

**Comment by wkurniawan07** [comment]
@sharvinbala exit code 126 is permission issue. Should be rectifiable with `chmod +x gradlew`, however this should not happen even in forked branches. What were you attempting to do?

**Comment by sharvinbala** [comment]
thanks @wkurniawan07  that worked. I was trying to use travis for the automated builds. Still a newbie though

**Comment by wkurniawan07** [comment]
@sharvinbala my concern is that the permission should not change even if Travis pulls from forked branches. Can I see the repo/Travis build log where this occurred?
