### ISSUE TITLE
Send join reminder: timeout in big courses

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6011]
This feature times out for big courses (100+ students). Possibly calls to sendgrid is taking longer than it used to take? Need to switch to task queues ASAP.

**Comment by damithc** [comment]
@wkurniawan07 this needs fixing soon

**Comment by JosephineKwa** [comment]
I will try working on this too

**Comment by JosephineKwa** [comment]
@damithc just to clarify the timeout happens when sending join reminders to the entire course? Or also when attempting to send to a specific student?

**Comment by damithc** [comment]
To the entire course.

**Comment by wkurniawan07** [comment]
Fixed in #6013
