### ISSUE TITLE
Error code 104 in instructor feedback results

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#6014]
The error code 104 appears frequently in instructor feedback results, likely due to exceeding the memory limit.

**Comment by chowyb** [comment]
Currently planning to handle this via the interim measure (prevent autoloading if number of respondents > 30). Correctly fixing this will require additional discussion, since I suspect measures that are currently in place to avoid retrieving too many responses are not working as intended. Below is a summary of my findings:

1. Student feedback results are not expected to be the main cause of failure here, since only relevant responses are retrieved from the database. Therefore, there is little memory space wasted on storing responses that may not be displayed to the user.
2. No measures are in place to avoid retrieving too many responses for the Question view (which so happens to be the default view); the questions will be automatically loaded, with all their responses, even if the number of responses/respondents exceed the amounts as set in the code (2,500 responses, and 150 (or 30 after changing) respondents), and even if "All Sections" is selected.
3. Measures are in place to avoid retrieving too many responses in the other views (GRQ, RGQ, GQR, RQG), but they do not work too well since:
 1. For the case of retrieving responses from all sections, the system first attempts to retrieve up to the set number of responses, and reports that the number of responses is too large if the number of responses > set number of responses. Otherwise, it displays the page properly, and retrieves the responses (again) via ajax.
 2. For the case of retrieving responses from a single section, the system attempts to retrieve up to the set number of responses for the section. If there are more responses in the database that have not been retrieved yet, those responses are simply discarded, and not displayed to the user.
4. Some comments features will retrieve the entire set of responses without taking any limits into consideration. While this does not seem to pose any problems currently (unless noted otherwise), this should still be fixed if possible.

**Comment by kanghj** [comment]
@chowyb, I think your observations for (3) is irrelevant to this issue. I am not to replicate what you are observing for (2), changing the value of `RESPONDENTS_LIMIT_FOR_AUTOLOADING` correctly only retrieves 1/2 responses on the first load (unless I'm missing something?).

**Comment by kanghj** [comment]
@damithc, currently the results page has many parameters which results in different behavior (first load vs ajax, questions vs non-question views, etc...), do we know which page is causing the errors? Are the error 104s are coming on the first load of the results page, or when the responses is getting loaded by ajax, or on the non-question views of the page?

**Comment by damithc** [comment]
Here is an example:
```
page/instructorFeedbackResultsPage?courseid=S11617-0356-DEEE2A14-PSeow&fsname=CPF+(Report)+Self+and+Peer+Evaluation&user=abc%40yahoo.com&frgroupbyteam=on&frsorttype=question&frshowstats=on&frindicatemissingresponses=true&questionid=ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgKWHy40LDA&frgroupbysection=
```
This one has only 5x5 students, but 7 team questions. It doesn't crash all the time. I guess if the server memory is already taken up by a few other requests, a request like this one can send it over the limit?.

Another one that crashed was 16x5 students, 2 team questions. So these are not really big sessions. Are we loading big results sets even when the session is small?

**Comment by damithc** [comment]
![image](https://cloud.githubusercontent.com/assets/1673303/17835187/004613ba-6792-11e6-90ac-87d1e2ee3884.png)
From the timestamps you can see groups of parallel requests going down together. There is still a possibility that the failure was caused by a different request executing at the same time.

**Comment by damithc** [comment]
@chowyb how do we detect the result set exceeds the size? Do we use cursors or something like that?

**Comment by kanghj** [comment]
At the moment, I am still not able to notice any mistake in the number of responses retrieved for each ajax request for the responses for each question, so the inefficient code may not be related to the retrieval of responses. Anyway, apart from reducing that respondent limit, I guess another possible quick fix is to limit the number of ajax requests at a single time (load questions 1 and 2 first, followed by 3 and 4, ...).

**Comment by chowyb** [comment]
@damithc the current implementation is as follows:

1. Given a range of size `n` (which is 2,500 in the default case), attempt to retrieve up to `n + 1` responses from the database.
2. If the number of responses returned is less than or equals to `n`, then we say that the result set does not exceed the size, otherwise we say it does.

@kanghj yep just tested the number of respondents issue for the question view, and it seems to be working fine (probably used a wrong value yesterday). I can look into the number of responses issue again (which seems to occur upon the initial loading when not in question view, and viewing a single section), but that can probably wait for now. I had initially brought it up more to argue against reducing the number of responses that are retrieved, as it might cause a bug to surface (but only if what I had mentioned earlier in `3ii` is confirmed)

**Comment by damithc** [comment]
May be 2500 is a bit too high? 5 such requests in parallel is already 25000 responses. That may be ok in normal cases, but can crash if the server is already near memory limit.
Yes, it's better if we can limit the number of parallel ajax requests but I thought that's controlled by the browser.

**Comment by damithc** [comment]
Perhaps auto-load the first 2 questions only? Or not auto-load at all?

**Comment by chowyb** [comment]
Just tested out not auto-loading at all, and it does not work too well on the other views as the topmost panel for "No specific recipients" will disappear when clicked on if there are no responses for that panel, which would not leave a good impression on the user. Other panels where no responses are present will still display properly. As such, I would recommend auto-loading at least the first question/panel only.

No change was observed for student feedback results.

One possible side effect is that this will have a significant impact on our testing however, as quite a number of pages rely on the auto-loading effect to test for HTML content.

**Comment by damithc** [comment]
1. Yes, we can auto-load just the first one, and do that only in question view.
2. We can have an additional parameter `autoload=true` that uses the current behavior. Then, we can use that parameter during testing

**Comment by damithc** [comment]
I can reproduce this error by loading the results page of a session. 5x5 students, 10 team questions. The total number of responses is not that high, yet it causes a server crash. Only 2 questions loaded. The other 8 went down with the server. Sounds odd right?

**Comment by damithc** [comment]
I tried loading 3 questions (by manually clicking on the panels) in parallel, and it worked. 4 questions worked too. So our solution of auto-loading only one might bring a respite but it's still odd.
