### ISSUE TITLE
feedbackSubmissionAdjustmentWorker failing 100%

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6017]
Failing with error 204. `A problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. (Error code 204)`
May be this one too is accessing 'all sessions'?

**Comment by JosephineKwa** [comment]
It doesn't access all sessions but it does try to retrieve all the responses for a session

**Comment by damithc** [comment]
That may be too much memory for bigger sessions. Need to figure out a way to do it in a cheaper way. Perhaps do it for one modified student at a time and retrieve only responses related to that student?

**Comment by damithc** [comment]
fails at v5.95

**Comment by wkurniawan07** [comment]
Does this still happen?

**Comment by damithc** [comment]
Not in recent times. closing.
