### ISSUE TITLE
instructorFeedbackResultsDownload crashes for big courses

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6019]
Usually causes error 104, sometimes timeout.
Probably we should detect sessions with big result sets and ask the user to download by section/question.

**Comment by JosephineKwa** [comment]
This check is already in place for when the user attempts to download the entire set of results. However the limit for the response size is 10000. Perhaps we could reduce it to 1000 (or even less)?

**Comment by damithc** [comment]
Let's reduce it to 2k and see how it goes.

**Comment by wkurniawan07** [comment]
Fixed in #6022
