### ISSUE TITLE
Instructor result download: xlsx file taking longer than csv file

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6030]
I have a case where csv file is downloaded almost immediately but the xlsx file time out.

**Comment by damithc** [comment]
@rclakmal any reason xlsx takes significantly longer than the csv file?

**Comment by rclakmal** [comment]
@damithc  any more information on this specific case ? 

There are some extra checks to apply different formatting for questions. Other than that, it is just distributing the file content to xlsx rows.

**Comment by damithc** [comment]
Here are some data. The 2nd of each pair is the csv file. As you can see, xlsx files takes way longer.
The top pair is for a session with 1 question and 20+ students.
The other two pairs are for a session with 80+ students and 8 questions.
![image](https://cloud.githubusercontent.com/assets/1673303/17927519/a9570174-6a28-11e6-8d4a-5f41fad49dd8.png)

**Comment by rclakmal** [comment]
Thanks @damithc ...Just to be clear, is this happening constantly for all sessions with high number of students. 

I will have a look at the code to see on how we can improve slicing the rows.

**Comment by damithc** [comment]
20+ students is actually a small class. The difference in performance is applicable to both small and large classes. In large classes it can exceed 60 seconds and then a timeout.

**Comment by rclakmal** [comment]
For large files, Apache POI recommends a [streaming](http://poi.apache.org/spreadsheet/how-to.html#sxssf) API with regard to performance and memory. I'm trying out this to see whether there are any performance improvement.

**Comment by damithc** [comment]
Are the file sizes of two types different? Does the difference match the
difference in latency observed?

-- 
Sent from a mobile device.

**Comment by damithc** [comment]
If anything, the xslx file is smaller, so the file size is not the problem.
![image](https://cloud.githubusercontent.com/assets/1673303/17954173/ac238fc0-6aab-11e6-8e83-6efc0483e405.png)
We may have to remove xlsx feature until we figure this out. Most people will choose the xslx option and it fails for mid size courses and large courses.

**Comment by damithc** [comment]
The two options using two different methods to retrieve data? Or are they using the same code at database level?

**Comment by rclakmal** [comment]
@damithc It's the same retrieval underneath. In xslx, we do a split of csv records to fill out the of the cell contents of excel file. This is also needed to have the cell level control for formatting. This split could be expensive for large number of rows. 

Shall I remove the option from the UI then ?

**Comment by damithc** [comment]
Yes, let's remove it from UI until we find a faster way to build the xlsx file. I suspect use of regex could be the culprit. regex can take long to match.

**Comment by kanghj** [comment]
![xls1](https://cloud.githubusercontent.com/assets/2216119/17974698/a7484eaa-6b19-11e6-903c-c9c35605f517.png)

@damithc, @rclakmal, I guess some of our regexes are responsible here, but some Apache POI's methods seems a bit slow too.

**Comment by damithc** [comment]
Thx hong Jin. This shows performance bottlenecks can come from unlikely
places. :-p

-- 
Sent from a mobile device.

**Comment by rclakmal** [comment]
Thanks @kanghj ...the split with regex seems to be the main culprit though
