### ISSUE TITLE
Lines of code (LOC) count in README is not accurate

### ISSUE THREAD

**Issue by paradite** [TEAMMATES/teammates#6034]
The current README shows this:
![screen shot 2016-08-28 at 2 55 47 am](https://cloud.githubusercontent.com/assets/1209810/18029471/4ed52d48-6ccb-11e6-98cb-3d50c15119a3.png)

Which differs significantly from what I gathered from `cloc` on latest master branch:
```
[~/workspace/teammates/src (master)]
$ cloc .
    1680 text files.
    1591 unique files.                                          
     286 files ignored.

github.com/AlDanial/cloc v 1.70  T=14.25 s (98.4 files/s, 38279.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                           384            886             18         346680
Java                           746          27965          11054         103411
JSON                            60            581              0          25532
JavaScript                     122           2606           2057          13256
CSS                             19            314             92           7559
JSP                             59            244             32           2399
XML                             11             65             56            666
Markdown                         1              1              0              2
-------------------------------------------------------------------------------
SUM:                          1402          32662          13309         499505
-------------------------------------------------------------------------------
```

Based on the issue #336,  I also looked at the analysis from this website:
https://www.openhub.net/p/teammates/analyses/latest/languages_summary
The data is from 4 months ago, but the distribution is similar to what I got from `cloc`, HTML being more than Java.

**Comment by damithc** [comment]
We don't count most of the HTML files as they are generated by test scripts.
We do count comments because they are written by developers.
The correct openhub URL to check is https://www.openhub.net/p/teammates-on-github/analyses/latest/languages_summary
The one you checked points to an old repo.

**Comment by wkurniawan07** [comment]
@paradite the issue still stands though; although not as bad as how you thought it was, the LoC count is still inaccurate. In addition, the third-party JS files are not counted because we don't own them.

@damithc I thought this is the one, as used in our README? https://www.openhub.net/p/teammatesonline

**Comment by damithc** [comment]
Yes, https://www.openhub.net/p/teammatesonline is the more accurate one. It omits the test resources folder.

**Comment by damithc** [comment]
As long as the numbers are not grossly unrepresentative, it's ok to be off by a few KLoC.
