### ISSUE TITLE
New contributor self intro [Dhiren]

### ISSUE THREAD

**Issue by dp80** [TEAMMATES/teammates#6060]
1. my teammates app: **https://teammates-dhiren.appspot.com**
2. my github fork: **https://github.com/dp80/teammates**
3. For my first commit i addressed issue #5995.
4. As reported, it look like this now:
![991a34a0-649e-11e6-9fcd-8b3f1d0a6aa9](https://cloud.githubusercontent.com/assets/619498/18488227/2eac907e-79be-11e6-9e38-491bfe1bb387.png)

After the fix:
![9-13-2016 2-04-28 pm](https://cloud.githubusercontent.com/assets/619498/18488261/45722eea-79be-11e6-8000-4bfb60377f30.png)

Self-intro: My name is Dhiren.  I reside in Austin, TX.  I am looking to contribute to the open source project to enhance my coding skills thru the community feedback process while also getting the satisfaction of having contributed to open source project.

**Comment by damithc** [comment]
Welcome to TEAMMATES @dp80

**Comment by junhaoyap** [comment]
Hi @dp80, welcome to the TEAMMATES community!

Good job on setting up as well as deploying your own fork to the staging server! I see you have already started contributing by having an ongoing fix of an issue labeled d.FirstTimers (do just one of this), afterwards you can move on to issues labeled d.Contributors (recommended). Looking forward to more of your contributions!
