### ISSUE TITLE
New contributor self intro Steve Simpson

### ISSUE THREAD

**Issue by stevesimpson4375** [TEAMMATES/teammates#6073]
a. A link to my app: https://4-18-dot-teammates-stevesimpson.appspot.com/
b. A link to my fork: https://github.com/stevesimpson4375/teammates
c. I added additional text to the search tips box. There is now a third tip that identifies the wildcard character
![image](https://cloud.githubusercontent.com/assets/8096950/18817665/4485686a-8334-11e6-9b1f-44944e54de73.png)
![image](https://cloud.githubusercontent.com/assets/8096950/18817706/4ad0e8ec-8335-11e6-9732-ab1bcfb04697.png)

d. My name is Steve Simpson and I recently earned a degree in software development. I have used github and just about all the languages this project uses, but classes are much different than the real world. I am looking to gain experience working on a real project.

**Comment by damithc** [comment]
Welcome to TEAMMATES @stevesimpson4375 :-) 
Kudos on completing this step. Looking forward to your first PR.
