### ISSUE TITLE
'Instructor only' visibility is buggy

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6078]
![image](https://cloud.githubusercontent.com/assets/1673303/18938029/0dccf0c6-8628-11e6-81b1-d79b43f6908c.png)

**Comment by damithc** [comment]
@YongJieYongJie need a fix urgently

**Comment by YongJieYongJie** [comment]
@damithc May I check what is the feedback path? I tried all the various combinations of the feedback giver and recipient but could not reproduce the error.

**Comment by damithc** [comment]
Students --> own team
In this case 'receiver's team members' is same as 'givers team members'. The former is not shown but seem to default to 'ticked'

**Comment by damithc** [comment]
![image](https://cloud.githubusercontent.com/assets/1673303/18956164/ff4cd646-868c-11e6-9e0a-3259bb51d57e.png)

**Comment by damithc** [comment]
Actually, I can't reproduce in the essay question (above screenshot) but can reproduce it in this one:
![image](https://cloud.githubusercontent.com/assets/1673303/18956252/5cb8d1d6-868d-11e6-9679-403d939f4529.png)

**Comment by wkurniawan07** [comment]
Fixed via #6079
