### ISSUE TITLE
IRC / communications

### ISSUE THREAD

**Issue by DanielPBak** [TEAMMATES/teammates#6083]
Hi, I'm a potential contributor. I was wondering if there's an IRC channel or some other communication channel for this project. The docs say that most communication happens on the Issues tracker, but I find it hard to believe that a project of this scale and survive without some sort of chat room. Am I wrong?

Dan

**Comment by damithc** [comment]
Hi @DanielPBak 
Our issue tracker doubles as a discussion board. If you have a question, just post an issue in the issue tracker, like you did just now. :-)

**Comment by junhaoyap** [comment]
Hi @DanielPBak, welcome to the TEAMMATES community!

As mentioned by @damithc, our issue tracker doubles as a discussion board! Looking forward to your first contribution and more 👍
