### ISSUE TITLE
Move scripts to the page bottom instead of top

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6088]
It is a common practice for boosting web performance because putting scripts on top blocks parallel downloads (and thus make the webpage load slower, especially so when the scripts are large).

**Comment by damithc** [comment]
Is there any downside?

**Comment by wkurniawan07** [comment]
All sorts of literature, stackoverflow posts, etc. recommends putting scripts just before the closing `</body>` tag as well, unless they are absolutely necessary on top or somewhere in the body.

I can attest to that: pages do load faster, or at least we get the "illusion" that they are because the script is loaded after the DOM, thus we don't see empty white page for an extended period of time (the script loading being deferred to the end).

**Comment by damithc** [comment]
I think we have some pages with 'onLoad' event wired to a JS function. Will they still work if the script is at the bottom?

**Comment by wkurniawan07** [comment]
```html
<body onload="someFunction()">
    <script src="script.js"></script> <!-- someFunction() defined here -->
</body>
```
`onload` is triggered only when the body is completely loaded, and that includes the script inside, so there is no effect on correctness.
(although we don't have any body onload, this should serve as a good enough example)

**Comment by junhaoyap** [comment]
The trade-off (whether it is a downside or not depends on perspective) when we do this ->

Users will get to see the HTML generated BEFORE the JavaScript is loaded, aka if some UI depends on JavaScript to be shown or depends on JavaScript to be styled, it might look awkward until JavaScript is loaded (this is not noticeable by users with good data connectivity)
