### ISSUE TITLE
Cannot initialise Google App Engine sdk

### ISSUE THREAD

**Issue by DanielPBak** [TEAMMATES/teammates#6091]
I am at the "Setting up the Dev Server" stage of setting up the development environment.

daniel@beepboop:~/teammates$ ./gradlew printUserHomeDir
:printUserHomeDir
Your Gradle user directory is: /home/daniel/.gradle

BUILD SUCCESSFUL

Total time: 5.017 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.12/userguide/gradle_daemon.html

However, when I try to add an App Engine SDK, (/home/daniel/.gradle/appengine-sdk or /home/daniel/.gradle/), Eclipse says "Failed to initialize App Engine SDK at /home/daniel/.gradle/".

I am using Ubuntu 16.04 LTS.

**Comment by wkurniawan07** [comment]
Hi @DanielPBak, Eclipse requires the directory of the precise version of the SDK, not the Gradle user home. Likely for your case is `/home/daniel/.gradle/appengine-sdk/appengine-java-sdk-1.9.27`.
