### ISSUE TITLE
Sessions: student view results: stop showing a random identifier for anonymous responses

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6092]
Currently, all answers by the same student will have the same anonymous identifier e.g., `Anonymous Student 2322423`. That is good to have in some contexts, but some instructors don't want such traceability between responses from the same anonymous respondent. ~~An option to turn it on/off would be nice to have.~~ 
~~EDIT: we can go back to fully randomized anonymous identifiers. Making it an option may be an unnecessary complication.~~
EDIT: we can remove the identifier completely. It's enough to say `Anonymous Student`

**Comment by wkurniawan07** [comment]
Duplicate of #4597?

**Comment by damithc** [comment]
Yes.

**Comment by wkurniawan07** [comment]
Re-opening this and closing the other one instead to make it more updated.

**Comment by kanghj** [comment]
For the UI, where should this option be shown to the instructor?

**Comment by damithc** [comment]
Good question.  It applies across questions, so I guess we have to put it among the main session settings. Perhaps we fully randomize by default and not give an option? I think more users prefer it to be fully randomized.

**Comment by damithc** [comment]
Increasing priority as I would like to fix this soon.

**Comment by tshradheya** [comment]
I can work on this
