### ISSUE TITLE
Instructor: edit visibility/path: warn if user click on first level options

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6095]
Some instructors click on these and complain nothing happens
![image](https://cloud.githubusercontent.com/assets/1673303/19209203/24557e28-8d38-11e6-8772-c175a323cfda.png)

**Comment by VamsiSangam** [comment]
@damithc sir, I'd like to work on this. But I'm not sure what to do here. There are 2 options, I could try to -

1. Make the menu not disappear on clicking a first level option.
2. Display a modal saying instructor is supposed to click on a second level option and some descriptive info about it.
3. 1 and 2

Which option should I implement?

**Comment by damithc** [comment]
Let's try 1 and see how it goes.
