### ISSUE TITLE
Response deletion warning message sometimes not shown when question edited

### ISSUE THREAD

**Issue by YongJieYongJie** [TEAMMATES/teammates#6097]
Related to #6070

**Comment by nsaiisasidhar** [comment]
Hi, I like to work on this issue. Can you please let me know if **trigger.('change')** is the event that needs to be fired for showing the response deletion warning message. Also as I am new to this project, I am having a difficult time to find the associated JS file, which needs to be edited, so can you please tell me which is JS file that handles events of question edit.

**Comment by damithc** [comment]
@nsaiisasidhar perhaps take an easier issue [labelled for `contributors`](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors) instead?

**Comment by wkurniawan07** [comment]
Invalidated by #6124.
