### ISSUE TITLE
Email copy sent to instructor at session close: mention it is a copy

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6106]
The email should say 'The following email has been sent to students' at the beginning.

**Comment by wkurniawan07** [comment]
I don't think it's meant to be a "copy" in the first place ([reference](https://github.com/TEAMMATES/teammates/pull/5739#r70785607)). Then again, our policy is very vague: when to send only to students and instructors get a copy, and when to send also to instructors?

**Comment by sznicci** [comment]
Hi, I was thinking about fixing this. I have read the conversation @wkurniawan07 linked, but I am still a little bit confused.

What is the intended behavior? Is there anything to be done here?

**Comment by damithc** [comment]
It is worded to address respondents. In most cases instructors are not respondents. So a copy makes more sense in most situation. However, this is not that important. I'm lowering the priority.

**Comment by damithc** [comment]
Looks like this is fixed. Closing.
