### ISSUE TITLE
New contributor self intro [fairbet]

### ISSUE THREAD

**Issue by fairbet** [TEAMMATES/teammates#6113]
a) the link to your app: https://teammates-fairbet.appspot.com/

b) link to your fork: https://github.com/fairbet/teammates

c) a screenshot of the change you did (as seen on the UI) : 
![new_navbar](https://cloud.githubusercontent.com/assets/21210268/19632475/d9622d28-9974-11e6-924c-2d9a6fd6227b.PNG) 
I added the teammates logo to navigation bars across the site!

d) your real name and a short self-intro
I'm Fred Xu, a CS undergrad at Duke University. Excited to join the TEAMMATES community!

**Comment by Gisonrg** [comment]
Welcome to TEAMMATES! ;) @fairbet

**Comment by wkurniawan07** [comment]
Hi @fairbet, welcome to the TEAMMATES community!
Good job on setting up and deploying to your own staging server! You can contribute first to issues labelled `d.firstTimers` (do just one of this), then `d.Contributors`. Looking forward to your contributions!
