### ISSUE TITLE
New contributor self intro [sznicci]

### ISSUE THREAD

**Issue by sznicci** [TEAMMATES/teammates#6123]
a) the link to your app : http://teammates-sznicci.appspot.com/

b) link to your fork : https://github.com/sznicci/teammates/tree/tinker

c) a screenshot of the change you did (as seen on the UI) :

I added an icon with different colours to the instructor and student navigation bars next to the logout like the admin has it.

![student](https://cloud.githubusercontent.com/assets/8382849/19781841/3d5e5688-9c83-11e6-9609-46172a663d79.png)
![instructor](https://cloud.githubusercontent.com/assets/8382849/19781840/3d55a72c-9c83-11e6-9746-887448d10e84.png)

d) your real name and a short self-intro :

I am Nikoletta Szedljak, I live in Cambridge, UK. I am very enthusiastic about Java programming and would love to contribute to the TEAMMATES project.

**Comment by junhaoyap** [comment]
Hi @sznicci, welcome to the TEAMMATES community!

Great job on setting up as well as deploying your own fork to the staging server! You can contribute first to issues labelled d.firstTimers (do just one of this), then d.Contributors. Looking forward to your contributions!
