### ISSUE TITLE
Reduce the size of profile_pic_too_large.jpg

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6132]
The said image is in `src/test/resources/images/` folder.
It is ~10.5 Mb in size however it is testing a function branch that will execute at the lower limit of 5 Mb, thus the remaining ~5.5 Mb is a waste of space.
It should be replaced with another image with size just slightly above 5 Mb.

**Comment by ManrajGrover** [comment]
I can take this one up.
