### ISSUE TITLE
Consider developing a self-hosting version via AppScale

### ISSUE THREAD

**Issue by CalebBell** [TEAMMATES/teammates#6135]
Good afternoon,

The University of New Brunswick, Canada, has been searching for a peer evaluation tool for some time. TEAMMATES is very well featured, elegant, maintained, and open source. However, we are bound by local privacy regulations which prevent confidential student data from being stored on third party servers (except companies we are paying and have data sharing agreements with). Because of this, using the GAE instance is not an option for us. An increasing number of universities in Canada are bound by these requirements. 

Deploying our own instance to Google App Engine is unfeasible for the same reason - while they would happily take our money to host it, it would cost them too much money to go through our data sharing agreement process. This appears to preclude TEAMMATES from ever being used by our university. The only option would be if we could host TEAMMATES on our premises. I recently learned about [AppScale](https://github.com/AppScale/appscale), which aims to allow on-premises deployment of GAE applications. It appears to support most of the APIs available on GAE. Would this be something the TEAMMATES project would be interested in supporting?

Sincerely,
Caleb

**Comment by damithc** [comment]
@CalebBell we might develop a self hosting version although not in the near term.
W.r.t. the restriction on putting confidential data on third party servers, many universities (even our own) have this restriction. However, they continue to use TEAMMATES by arguing that the data put on TEAMMATES is not really 'confidential' in the spirit of what the restriction seek to protect.

**Comment by damithc** [comment]
Closing temporarily to focus on higher priority issues. Will be reopened later.
