### ISSUE TITLE
Add external reviews to the website

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6136]
We can list 3rd party reviews somewhere in the website, once we have enough.
Here are some:
https://cit.duke.edu/blog/2016/01/teammates/
https://telic.wordpress.com/2015/11/13/teammates-peer-feedback-system-review/
http://www.cabvroanoke.org/presentations/CABV486.pdf

**Comment by nsaiisasidhar** [comment]
Hi, I like to work on this issue. Please let me know where they need to be displayed, is it on Home page ? Also assign this issue to me.

**Comment by wkurniawan07** [comment]
@nsaiisasidhar this issue might need to be delayed until we get more reviews. Work on something else first?
