### ISSUE TITLE
New contributor self intro damarray

### ISSUE THREAD

**Issue by damarray** [TEAMMATES/teammates#6149]
Hi,
As we forgot at the first time, here is some information about us.
We are two students, Dorian Bourcet and Dris Amarray from Collège de Rosemont (QC, Canada). We are glad to contribute to the Teammates project.

**Link to our fork** : https://github.com/damarray/teammates

The changes we did are about HTML external links on pages index.jsp, about.jsp, contact.jsp.
We corrected some invalid links on index.jsp and added an "external link" icon to identify those opening in new tab.

**index.jsp**
![home](https://cloud.githubusercontent.com/assets/23157689/20105842/221bb1a0-a5a1-11e6-8307-b0acd90506d4.png)

**about.jsp**
![about](https://cloud.githubusercontent.com/assets/23157689/20105844/22280856-a5a1-11e6-8c09-fd5a26a4e694.png)

**contact.jsp**
![contact](https://cloud.githubusercontent.com/assets/23157689/20105843/22270c58-a5a1-11e6-9f6a-e9083f1927b9.png)

**Comment by wkurniawan07** [comment]
@damarray good job on setting up the dev environment! :+1: The orientation guide also specifies deploying to staging server, so it'd be good if you do that and report back here as well.
Anyway, I recognise that there are invalid (more like outdated though) in many of our static pages. Feel free to open an issue and work on it!
