### ISSUE TITLE
Recipient and giver sensitive information might leak through logging operations

### ISSUE THREAD

**Issue by rcaa** [TEAMMATES/teammates#6155]
FeedbackResponseAttributes {giver,recipient} might contain sensitive information such as their email. It might leak in source code points like FeedbackContributionResponseDetails:99 and FeedbackContributionResponseDetails:106. Should we avoid printing this information in log files?

@wkurniawan07 
https://github.com/TEAMMATES/teammates/commit/0ba6fd115131b499946d9cc0f517a0eb01d285ba#diff-2635fd1eb988f676ba650224a41f23c1R105

**Comment by damithc** [comment]
@rcaa Log files are secure and can only be accessed by TEAMMATES admin.

**Comment by wkurniawan07** [comment]
@rcaa thanks for your concern. As @damithc has said, the log files from the actual site are accessible only by the admins (not even the most senior of the developers can see them), and the information contained are at times needed to assist debugging/troubleshooting.
