### ISSUE TITLE
Infinite redirect loop on an invalid route

### ISSUE THREAD

**Issue by louietyj** [TEAMMATES/teammates#6159]
Accessing an invalid route such as https://teammatesv4.appspot.com/yo redirects to something like https://teammatesv4.appspot.com/yo/index.jsp/index.jsp/index.jsp/index.jsp/index.jsp/index.jsp/index.jsp/index.jsp/index.jsp/index.jsp/index.jsp/index.jsp/index.jsp/index.jsp/index.jsp/index.jsp/index.jsp/index.jsp/index.jsp/index.jsp/

Chrome gives an ERR_TOO_MANY_REDIRECTS error.

**Comment by mohamed-moanis** [comment]
On a dev server I can't reproduce such behavior, but interestingly  the 404 page that is declared in web.xml doesn't show up for such a request.
On a live version of teammates, the bug is present, but I can't access server logs to check how the request was handled/redirected?

**Comment by damithc** [comment]
@mohamed-moanis you should be able to see the logs of your staging server.

**Comment by mohamed-moanis** [comment]
Can you show me where the logs are in the app engine dashboard?

**Comment by damithc** [comment]
![image](https://cloud.githubusercontent.com/assets/1673303/21085389/736c7240-c04c-11e6-92b7-b9ea45ac9e83.png)
