### ISSUE TITLE
Test failures due to line endings in HTML attribute value

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6174]
A whole bunch of tests failing on live server with a diff like this. e.g. `InstructorFeedbackPageUiTest::testCopyActions()`

![image](https://cloud.githubusercontent.com/assets/1673303/20705920/e37a358c-b65f-11e6-80b3-2cd5f992a087.png)

**Comment by damithc** [comment]
@wkurniawan07 any idea? Check PRs merged between 5.90 and 5.91

**Comment by wkurniawan07** [comment]
This looks like line ending issue, although it's weird that it happens in the first place. The only possible explanation is #6152. Are the failures caused strictly by this kind of occurrence (i.e. line ending inside an attribute value)?

**Comment by damithc** [comment]
Yes, all cases failing with a similar diff.

**Comment by damithc** [comment]
Without a fix for this, I can't deploy the next version :-p

**Comment by wkurniawan07** [comment]
This happens in dev also, on environments where the line ending is not LR.
