### ISSUE TITLE
Potential bug between AJAX call and waitForElementVisibility in test cases

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#6179]
Hello, I am a new contributor and I currently keep failing the test case 'teammates.test.cases.ui.browsertests.InstructorFeedbackEditPageUiTest' for 'staging test' against my server 'https://teammates-xiaopu.appspot.com/'.
<img width="960" alt="screen shot 2016-11-30 at 2 21 35 am" src="https://cloud.githubusercontent.com/assets/13977235/20723008/c89c4f4a-b6a3-11e6-9e0f-9c51a544efa4.png">
I find a possible reason for this.
In `teammates.test.cases.ui.browsertests.InstructorFeedbackEditPageUiTest`, the test case clicks the visibility option by using `feedbackEditPage.enableOtherVisibilityOptions(2);` and checks whether the visibility message is updated or not. When the option is clicked, AJAX request is sent to the server. The test case tries to use `waitForElementVisibility` to wait  the AJAX call, but it doesn't actually wait (reason below) and `visibilityMessage2.getText()` gets empty message (or message not updated by AJAX) thus the test cases fail.
``` java
feedbackEditPage.enableOtherVisibilityOptions(2);
// ...
WebElement visibilityMessage2 = browser.driver.findElement(By.id("visibilityMessage-2"));
feedbackEditPage.waitForElementVisibility(visibilityMessage2);

assertTrue("Expected the receiving student to be able to see response, but was "
                   + visibilityMessage2.getText(), visibilityMessage2.getText()
                   .contains("The receiving student can see your response, and your name."));
// ...
```
I think `feedbackEditPage.waitForElementVisibility(visibilityMessage2);` will always return true **when the page is loaded, visibility option is clicked after the loading**. The server renders the `div` element when page is loaded.
``` html
// `src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/questionVisibilityOptions.tag`
// ...
    <!-- Fix for collapsing margin problem. Reference: http://stackoverflow.com/questions/6204670 -->
    <div class="col-sm-12 visibilityMessage overflow-hidden" id="visibilityMessage-${fqForm.questionIndex}"> // here
        This is the visibility hint as seen by the feedback giver:
        <ul class="text-muted background-color-warning">
        <c:forEach items="${fqForm.visibilitySettings.visibilityMessages}" var="msg">
            <li>${msg}</li>
        </c:forEach>
        </ul>
    </div>
// ...
```
When doing AJAX request, the script **finds the div** to update the message.
``` javascript
// `src/main/webapp/js/instructorFeedbackEdit.js`
/**
 * Updates the visibility message div according to configurations in the
 * visibility checkboxes div (using AJAX)
 * @param $containingForm
 */
function updateVisibilityMessageDiv($containingForm) {
    // ...
    var formData = $containingForm.serialize();
    var $visibilityMessageDiv = $containingForm.find('.visibilityMessage'); // here
    // ...    
    $.ajax({
        // ...
    });
}
```
Thus, no matter the AJAX call complete or not, the `feedbackEditPage.waitForElementVisibility(visibilityMessage2);` will always return true.

Whether the test case fails or not actually depends on the speed of the server. If the server gives quick response to AJAX request, then `visibilityMessage2.getText()` would get correct data.

But I would like to point out this is a existing potential "bug" for test case, and I believe this may not be the only test case that has this issue. So I think for better testing, a mechanism need to be provided to wait for AJAX request in test cases.

**Comment by xpdavid** [comment]
When I try to log the content of `visibilityMessage2.getText()`
![screen shot 2016-11-30 at 2 56 08 am](https://cloud.githubusercontent.com/assets/13977235/20724324/b9672b9e-b6a8-11e6-8dfb-479ee80dd8a9.png)

**Comment by damithc** [comment]
We do have a few test cases that fail against a remote server due to deficiencies in how the test is written.  This could be one of them. Were you able to pass all tests against the dev server?.

**Comment by wkurniawan07** [comment]
Hi @xpdavid, thanks for the report!
Indeed this is one of the test failures that have been existing for quite some time, for the very reason that you have fabulously explained. Staging server test failures, however, is not a high priority for fixing because we rarely run the entire test suite (or even _any_ test) on the staging server.
For this particular failure, there is actually a routine that has been written to handle such case, only that it has not been applied here. Feel free to contribute a fix if you wish.

**Comment by xpdavid** [comment]
@damithc Yes, I can pass all the test cases against the `dev server`, so I guess it depends on the speed of response of the server.

**Comment by damithc** [comment]
@wkurniawan07 is this issue already in our issue list? If yes, we can close this and link from that issue to this one.
