### ISSUE TITLE
Typo in Const.java NO_SPECIFIC_RECEIPIENT

### ISSUE THREAD

**Issue by JosephineKwa** [TEAMMATES/teammates#6183]
Should be `NO_SPECIFIC_RECIPIENT`

**Comment by okornoe** [comment]
Hello guys am Kelvin a first timer and I want to contribute on the project, how do I proceed from here.
Help me out, and I will be very glad

**Comment by damithc** [comment]
Welcome to TEAMMATES @okornoe 
Please refer to our 'Contributor Orientation Guide' (link given in our [project home page](/teammates/teammates))

**Comment by shreab373** [comment]
hi, this is my first ever contribution, can i take this?

**Comment by damithc** [comment]
@shreab373 sure. No need to ask :-)

**Comment by okornoe** [comment]
hello guys and damithc, I have started setting up my environment for the project and I have this difficulty.
I do not know where/the specific directory to run this command './gradlew appengineDownloadSdk'
I tried it in my terminal and I had this error
![opensourceteammatesproject](https://cloud.githubusercontent.com/assets/12277906/21422838/b08b803e-c831-11e6-80d7-6a03ffedd664.PNG)

**Comment by sznicci** [comment]
Hi @okornoe,

Have you tried to run this command in the teammates project directory?

**Comment by shreab373** [comment]
hi, this may be a rather stupid question but to fixing the bug the guidelines mention we need to create our own branch with the issue name and a few keywords, when i do that and then created a PR, it is getting created in my forked version of the rep, what am i missing?

sorry but i'm only starting to get used to git

**Comment by damithc** [comment]
@shreab373 you need to correct our repo (not your own repo) as the destination repo. https://help.github.com/articles/creating-a-pull-request/

**Comment by AnaghHegde** [comment]
@damithc is the issue still open ?

**Comment by damithc** [comment]
@AnaghHegde yes still open. There is an open PR for it but it doesn't seem to be active (#6252). You can submit a PR if you wish.

**Comment by AnaghHegde** [comment]
@damithc but its assigned to wkurniawan07.

**Comment by damithc** [comment]
@AnaghHegde 

> but its assigned to wkurniawan07

He is the reviewer, not the author, of the PR.

**Comment by damithc** [comment]
@AnaghHegde PRs are assigned to the reviewer.
