### ISSUE TITLE
New contributor self intro Mohamed Moanis

### ISSUE THREAD

**Issue by mohamed-moanis** [TEAMMATES/teammates#6185]
Hello teammates community, I would like to introduce myself so I prepared a tinker fork and made some house keeping for the external links to remove dead ones.

So this is my app istance:
http://teammates-mmoanis.appspot.com/

This is my tinker branch on my fork:
https://github.com/mohamed-moanis/teammates/tree/tinker

The changes were replacing 3 dead links I found on the live app - I guess there should be an automated scan before deployment to keep it updated. These aren't much, but I am not really a UI guy.

- YourKit LLC
![capture](https://cloud.githubusercontent.com/assets/7101613/20858408/2d02ea7e-b94d-11e6-861a-0218af93807e.JPG)

-  International Conference on Software Engineering Education and Training (CSEET)
- International Conference on Teaching and Learning in Higher Education (TLHE)
![capture2](https://cloud.githubusercontent.com/assets/7101613/20858409/32ad7cc8-b94d-11e6-820b-b466854912b8.JPG)

And finally for a small intro, I am Mohamed Moanis from Egypt. I graduated this summer with a BSc in electronics and computer engineering - with a major in computer engineering - from Cairo university, Egypt. I am currently a software engineer in an EDA company in the Cairo office - which I don't represent and my presence here isn't related to my work. I hope my contribution will be helpful to Teammates!

**Comment by damithc** [comment]
Welcome to TEAMMATES @mohamed-moanis :-)
Perhaps you can submit this fix as a proper issue + PR?

**Comment by junhaoyap** [comment]
Hi @mohamed-moanis, welcome to the TEAMMATES community!

Great job on setting up as well as deploying your own fork to the staging server! In your case, since you have found a bug, your best bet will be to open an issue on our issue tracker and perhaps submit it as a first time fix? We will greatly appreciate that!
