### ISSUE TITLE
FeedbackSession#isSentClosingEmail returning wrong member

### ISSUE THREAD

**Issue by leelunn** [TEAMMATES/teammates#6208]
In FeedBackSession.java, the isSentClosingEmail appears to be returning the wrong member.

`return sentClosedEmail;` should be `return sentClosingEmail;`

**Comment by damithc** [comment]
@wkurniawan07 for your investigation please.

**Comment by wkurniawan07** [comment]
Indeed it is, however this mistake never actually translates into bug because `sentClosedEmail` is always updated after `sentClosingEmail`. Nevertheless, it needs to be fixed.

@leelunn you're welcome to fix it, that one line is all that needs to be changed.

**Comment by leelunn** [comment]
@wkurniawan07 I have a branch prepared for this already that includes some TODO housecleaning in FeedbackSession, it is acceptable to include those changes at the same time for this issue?

**Comment by wkurniawan07** [comment]
@leelunn I know the TODOs in that class, they are non-trivial and require large-scale database migration so it's best to keep them for later.
