### ISSUE TITLE
Remove additionalQuestionInfo.js import in instructorComments.jsp

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6212]
Accidentally re-added in #6187 after removed in #6137.

**Comment by aravindputrevu** [comment]
is the issue still open ? If so can i work on it ?

**Comment by wkurniawan07** [comment]
@aravindputrevu it is still open, feel free to work on it.

**Comment by aravindputrevu** [comment]
Thank you . I will

**Comment by yasirunilan** [comment]
This is still open right?

**Comment by damithc** [comment]
@yasirunilan 
>This is still open right?

Yes, but there are two open PRs for this ahead of yours.

**Comment by yasirunilan** [comment]
okay thanks :) I'll look into some of the other issues

**Comment by aravindputrevu** [comment]
I raised a pull request yesterday. Awaiting review completion.
