### ISSUE TITLE
Some objects are not assigned at the same time they are defined

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6218]
There are some instances of:
```java
Object obj;
obj = ...; // do the assignment immediately afterwards
```
which can be shortened to:
```java
Object obj = ...; // do the assignment at the same time it is defined
```

- `DataGenerator`: line 82
- `FeedbackQuestionsLogicTest`: line 640
- `InstructorFeedbackQuestionEditAction`: line 203
- `StudentAttributesTest`: line 411
- `StudentFeedbackSubmitPageUiTest`: line 127
- `StudentProfilePictureEditActionTest`: line 177

**Comment by AnaghHegde** [comment]
Hi, I am very interested in this.I am very new to opensource.Can you please tell me what i have to do.Thanks.

**Comment by damithc** [comment]
@AnaghHegde our project has a 'Contributor Orientation Guide' that you can refer to.
