### ISSUE TITLE
New contributor self intro [Zafer Khourdaji]

### ISSUE THREAD

**Issue by zkhourdaji** [TEAMMATES/teammates#6236]
**a) the link to your app:** https://test-zafer-136-136.appspot.com/

**b) link to your fork:**  https://github.com/zkhourdaji/teammates

**c) a screenshot of the change you did (as seen on the UI):** I simply switched the student login button with the instructor login button (revolutionary I know)
![teammates](https://cloud.githubusercontent.com/assets/14949184/21289350/6def2efe-c469-11e6-9110-fce94a14e436.png)

**d) your real name and a short self-intro:**  Hello everyone! My name is Zafer. I am 20 years old. I am from Michigan, USA. I am in my second year of college working toward getting my CS bachelor degree. Currently, I am going to a small community college but will transfer all my credits to a state school when I get my associate in Java programming. I am really passionate about programming and truly enjoy it, this is the first time I get into OSS so I am super excited!

P.S. Thanks for everyone for having very well written documentation, Especially the orientation guide!
After couple of days of working on setting my environment I was able to get everything working. ( well almost everything; I couldn't download most of the static analysis tools).

**Comment by damithc** [comment]
Welcome to TEAMMATES @zkhourdaji :-) Looking forward to your first PR.
