### ISSUE TITLE
Set up codacy for automated code review

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6237]
Codacy can detect and comment on some code quality issues (based on checkstyle, PMD, etc.) in PRs

**Comment by damithc** [comment]
Example:
![image](https://cloud.githubusercontent.com/assets/1673303/21291870/3fabbbea-c52a-11e6-9499-1c5a124f236e.png)

**Comment by hackosinn** [comment]
Hi, my name is Anand. please tell me how can i contribute to this project. i am new on github and i have no experience of contributing to open source projects. i will be grateful if anyone can help me

**Comment by damithc** [comment]
@hackosinn welcome to TEAMMATES. Please refer to our 'Contributor Orientation Guide' (link given in our README)

**Comment by aravindputrevu** [comment]
@damithc  I am interested in doing this. I have good idea on static analysis tools.
Let me know how can i integrate with the build process.

**Comment by damithc** [comment]
@aravindputrevu codacy integration does not require any changes to the build process. It's something that needs to be configured by someone with admin access to the repo, so let's leave it to a senior developer.

**Comment by aravindputrevu** [comment]
Okay ! 👍

**Comment by wkurniawan07** [comment]
The reason I'm quite reluctant of implementing this is because our own build has already supported CheckStyle, PMD, ESLint, Stylelint, etc. which essentially is what Codacy uses.
If we really need a quality badge, [SonarQube](https://www.sonarqube.org/) is the industry leader by far.

**Comment by samsontmr** [comment]
@wkurniawan07 Should I reference this issue or create a new one since this one says codacy?

**Comment by wkurniawan07** [comment]
@samsontmr create a new one. For all we know, some future developer might still want to set this up, and having more than one quality badge never kills 😛

**Comment by damithc** [comment]
codacy recently imposed a limit on PRs/day even for opensource projects. Closing.
