### ISSUE TITLE
Set up AppVeyor to run tests on Windows

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6238]
Travis can be our primary CI because the live server is a Unix box.
However, many of our devs are using Windows and running CI on AppVeyor (in parallel to Travis) can help detect Windows specific test failures.

**Comment by wkurniawan07** [comment]
The thing about AppVeyor is it doesn't allow parallel builds (Travis allows 5, as comparison). When our development rate increases (e.g during GSoC period) this will be a significant bottleneck.

**Comment by damithc** [comment]
That's true. For merging purposes, we can assume AppVeyor will pass and go ahead with the merge before AppVeyor result. If the AppVeyor subsequently failed, we can go back and do something about it (unmerge?). 
This AV CI is a low value thing for us given that we already have Travis. We can give it a try if the set up cost is low. We can always disable it if it doesn't seem to help.

**Comment by wkurniawan07** [comment]
One solution would be for the AV CI to not build pull requests, i.e. only build the stable `master` branch after each merge.

**Comment by damithc** [comment]
Yes, that works too.

**Comment by wkurniawan07** [comment]
I've managed to set this up with all tests passing except for one.
@damithc can you add the project in AppVeyor? I can do it but it would be weird if the repo URL carries my username :p

**Comment by damithc** [comment]
@wkurniawan07 

> can you add the project in AppVeyor?

Done.

**Comment by wkurniawan07** [comment]
It seems like I can't access the settings page right now :S Unlike Travis, AppVeyor's access control mechanism seems to be different.
If there is no way to enable me (or any other repo admins) to modify the settings, can the following be applied (all in `General` tab):
- Check `Skip branches without appveyor.yml`
- Check `Rolling builds`
- Git clone depth: 50 (following Travis)
- Branches to build: as per discussion above, only `master` (and possibly `release`), but this is up to your discretion.

I will also need the URL to the badge, which can be found in the `Badges `tab, the one marked as "Sample markdown code".

**Comment by wkurniawan07** [comment]
Might want to consider [this](https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization) as well.

**Comment by damithc** [comment]
Done, except the 'Branches to build' setting. I left it to 'all branches' just to see how it goes. If it turns out to be damper on our workflow, we can set it to 'master' only.
If you find out how to add more admins to a project, let me know.
Badge: [![Build status](https://ci.appveyor.com/api/projects/status/dvr6t33lqg6hsmxw?svg=true)](https://ci.appveyor.com/project/damithc/teammates)

`[![Build status](https://ci.appveyor.com/api/projects/status/dvr6t33lqg6hsmxw?svg=true)](https://ci.appveyor.com/project/damithc/teammates)`

**Comment by wkurniawan07** [comment]
@damithc it seems like building PRs are enabled via webhook (configured via GitHub) and not via the specified "Branches to build", and the latter will cause all branches pushed to this repo (not including forks), regardless of being part of a PR or not, to be built. Perhaps limit it to `master` and `release` first and see if it is indeed the case?
Confusing indeed but we don't have a say on how the want to run their stuffs :p

**Comment by damithc** [comment]
Done. 👍
