### ISSUE TITLE
Not able to start the dev server while setting up the environment.

### ISSUE THREAD

**Issue by nikhilmudholkar** [TEAMMATES/teammates#6245]
I followed the steps given in this page https://github.com/TEAMMATES/teammates/blob/master/docs/settingUp.md

when i import the teammates project in setup 6, the eclipse builds it and it shows a lot of errors. Nearly 434 errors. Also it flasses the a message. 
."Errors occurred during the build.
Errors running builder 'Google App Engine Project Validator' on project 'teammates'.
Unable to locate the JVM for project teammates. Please verify that you have a project-level JVM installed by inspecting your project's build path.
Unable to locate the JVM for project teammates. Please verify that you have a project-level JVM installed by inspecting your project's build path."
 Can anyone please help me resolve this issue. I am stuck from quiet a long time.
@AnaghHadge ...i think you faced a similar problem. How was it solved?
![issue1](https://cloud.githubusercontent.com/assets/20753893/21361969/567a7292-c70c-11e6-8dd3-c2ce3b6de72f.png)
![issue2](https://cloud.githubusercontent.com/assets/20753893/21361973/5b7c8852-c70c-11e6-9577-83c05ba19b67.png)
![issue3](https://cloud.githubusercontent.com/assets/20753893/21361977/60915778-c70c-11e6-84b3-e9f382b3a3af.png)

**Comment by leelunn** [comment]
@nikhilmudholkar Can you post a screen shot after opening the window resulting from doing the steps below:

1. Project | Properties
2. Click on Java Build Path
3. Click on Libraries tab
4. Scroll to the bottom of the list
5. Select JRE System Library
6. Click Edit

**Comment by nikhilmudholkar** [comment]
![issue4](https://cloud.githubusercontent.com/assets/20753893/21383737/48267980-c78d-11e6-85d3-b3ac9395d8cd.png)

**Comment by leelunn** [comment]
@nikhilmudholkar It looks like you have partially missed a step in the set up guide.  You must use a version of java 1.7 JDK.  Take a look at [common troubleshooting](https://github.com/TEAMMATES/teammates/blob/master/docs/troubleshooting-guide.md#common-setup-errors-and-solutions ) and particularly item 2 and 6.

**Comment by nikhilmudholkar** [comment]
There are a lot of jdk1.7 librraries. Which one to choose?
![issue5](https://cloud.githubusercontent.com/assets/20753893/21384272/d7a1d738-c78f-11e6-8e41-ad242be01746.png)

**Comment by wkurniawan07** [comment]
@leelunn thanks very much for chipping in! 👏
@nikhilmudholkar my setup is using JavaSE-1.7, although I am not sure how choosing the others would be different. Wrong Java version aside, the problem actually comes because the value chosen has no compatible execution environment in the system. Have a look at [this SO answer](http://stackoverflow.com/questions/15374697/unbound-javsse-1-7-libraries-in-java-eclipse-project).

**Comment by nikhilmudholkar** [comment]
@wkurniawan07  ...i followed the answer. Earlier 254 errors were there but now they are reduced to 152. But i am still not able to remove all of them. Can you please help me out. Should i remove all the versions of java and reinstall it? Will it work?

**Comment by nikhilmudholkar** [comment]
I did everything from the beginning. Surprisingly all the java error vanished now and now it shows google app engine problem. I am enclosing a screenshot. I tried everything. The same problem was mentioned in the troubleshooting guide. I tried the steps mentioned there but with no luck. Please help me out.
![issue6](https://cloud.githubusercontent.com/assets/20753893/21430289/871ba2ae-c888-11e6-8967-b4cde889c024.png)

**Comment by nikhilmudholkar** [comment]
issue solved. Thanks a lot @wkurniawan07 , @leelunn

**Comment by wkurniawan07** [comment]
@nikhilmudholkar noted with thanks. Closing this issue.
