### ISSUE TITLE
New contributor self intro SK

### ISSUE THREAD

**Issue by kilarusravankumar** [TEAMMATES/teammates#6247]
- link to my fork: https://github.com/kilarusravankumar/teammates

- Screenshot :
![2016-12-20](https://cloud.githubusercontent.com/assets/13055113/21372965/e1384090-c6e8-11e6-9347-3fd0926cf761.png)

Hi my name is Sravan Kumar kilaru.

**Comment by damithc** [comment]
Welcome to TEAMMATES @kilarusravankumar . Looking forward to your next PR :-)
