### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by hackosinn** [TEAMMATES/teammates#6254]
Run the command ./gradlew appengineDownloadSdk to obtain the Google App Engine SDK (version specified in build.gradle)...i don't understand this line. where should i run this line? i have installed gradle but this line isn't executing in command prompt.

**Comment by nikhilmudholkar** [comment]
hi @hackosinn , i just set up my environment. You need to run this line in the command prompt and not the git bash. I faced a similar confusion. This line might not be executing in cmd because you need to first go to the teammates directory in command prompt. Type cd and the folder name one by one to enter the teammates directory. Then run the gradlew command. It will run.

**Comment by damithc** [comment]
@hackosinn the command should be run from the root of the folder you cloned.

**Comment by hackosinn** [comment]
when i ran the command it says that "task gradlew.bat is not found in root
project teammates"

**Comment by hackosinn** [comment]
i don't know how to use gradle.i searched about it but got nothing good.can
u specify how can i set up gradle for teammates

**Comment by damithc** [comment]
@hackosinn can you give a screenshot after running the command?

**Comment by nikhilmudholkar** [comment]
@hackosinn .see, there is a gradlew file in teammates repo. 
![issue7](https://cloud.githubusercontent.com/assets/20753893/21467168/8fe1133c-ca0a-11e6-85c4-ebb035f62c80.png)
You need to go to teammates directory and then run the command. Like if I need to run this command, I would go to c/users/pc/documents/github/teammates.
Hope this helps.

**Comment by wkurniawan07** [comment]
@hackosinn while the answer given by @nikhilmudholkar is/should be correct, another thing to note is that you do not need to "set up" Gradle for this project. We use [Gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html) which allows Gradle tasks to be run without the need for Gradle explicitly set up in any machine.

**Comment by yasirunilan** [comment]
I see this issue has been raised by developers several times.isn't it good to add that the command should be ran in project root directory in project orientation guide.

**Comment by AnaghHegde** [comment]
@yasirunilan i think it makes sense because it is confusing.Even i also had the same issue

**Comment by wkurniawan07** [comment]
The instruction is now present after #6257, so closing the issue.
