### ISSUE TITLE
Dev guide: describe how to verify each step is done correctly

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6256]
In the steps given for setting up the dev server, we can describe how the new dev can verify if the step was done correctly. Otherwise they could perform a step incorrectly without realising it.

**Comment by nikhilmudholkar** [comment]
In a separate troubleshooting guide, we can post the screenshots of each and every step. Like if we need to change the name of a certain file, we can post the screenshots before and after the naming. This would be of immense help to new users. Also we can enable a comments section on that guide. So users can discuss amongst themselves the procedure. I feel that most of the doubts will be cleared via discussion or reading the past comments.

**Comment by yasirunilan** [comment]
Yes I also thinks this is a good thing to have. I personally have experienced this and I'm sure many other developers too have experienced it.better to have some supportive documents related to that case

**Comment by AnaghHegde** [comment]
@damithc I am interested in this.Can you guide me how should i have to proceed?

**Comment by aravindputrevu** [comment]
@AnaghHegde  Probably you should refer the settingUp.md and do the setup yourself thereby you will get first hand understanding how things work and where it is failing !

**Comment by AnaghHegde** [comment]
@aravindputrevu You didn't get my point and without doing the setup by them selves no one is contributng here i guess.

**Comment by damithc** [comment]
> Can you guide me how should i have to proceed?

Submit a PR to rectify the issue mentioned :-)

**Comment by aravindputrevu** [comment]
@AnaghHegde I am really sorry, i thought that you haven't setup. Don't make me wrong ! PEACE

**Comment by AnaghHegde** [comment]
@aravindputrevu No problem.PEACE .

@damithc I m thought something like this : After every step some of the files will be changed/added in the root directory (like when you run some commands) so i will mention what all the files have changed after every step till **Step : 4** and for the eclipse part (including tests,plugins and java libraries) we can post a screen shot. Is that ok ? any suggestions ?

**Comment by damithc** [comment]
@wkurniawan07 your input?

**Comment by wkurniawan07** [comment]
I'm against creating any script for the following reason:
- It's a maintenance burden for the project maintainers, particularly if our setting up steps change and the script has to adapt.
- Manually checking the presence of required files is not a hard task for developers, e.g. saying things like (the files abc and def should now be present).

Screenshots are fine, but do not make it too detailed. Our setting up guide are brief by intention; devs should be able to figure out many things by themselves.

**Comment by damithc** [comment]
> I'm against creating any script

I'm OK with manual verification too. 

Prefer textual description over screenshots when possible. In some cases we might need screenshots, and in those cases, just capture the relevant parts only. The more details the screenshot shows, the faster it will get outdated (and will bloat the repo size too).

The good good thing about having verification instructions for each step is we can ask the help-seeker to post screenshot after each step confirming the step was done correctly.

**Comment by AnaghHegde** [comment]
@damithc You are saying only manual verification of files is enough ?. Posting the screen shots will make it too easy?

>The good good thing about having verification instructions for each step is we can ask the help-seeker to post screenshot after each step confirming the step was done correctly.

What difference it makes?Because at present situation if someone faces issue and post it in issue tracker we will ask them to post screenshots.

**Comment by damithc** [comment]
> Posting the screen shots will make it too easy?

That's not the reason for preferring text over screenshots. Screenshots take up a lot of space in the repo and get outdated quickly (also, they sometimes differ based on OS version). Therefore, if something can be explained in text clearly enough, no need for screenshots. But some things are harder to explain clearly in text; use screenshots for those cases.

**Comment by AnaghHegde** [comment]
@damithc ok thank you for explaining that.

**Comment by ovshake** [comment]
@damithc Can I also try this? I recently have set up my development environment and it took me 18 tries. I think I might know all the places where one could go wrong. (Speaking for Windows 10)

**Comment by AnaghHegde** [comment]
@ovshake i m currently working on this.I have submitted a PR. Its almost done. Fixing some small errors.I m sorry.

**Comment by ovshake** [comment]
@AnaghHegde No problem. :)

**Comment by damithc** [comment]
@ovshake feel free to give comments on the ongoing PR by @AnaghHegde

**Comment by AnaghHegde** [comment]
@damithc @ovshake  Yeah its good idea . It helps a lot since you have tried this lot of times.
