### ISSUE TITLE
Regarding gradle-2.12-bin.zip

### ISSUE THREAD

**Issue by Mynk96** [TEAMMATES/teammates#6261]
Where to put the zip gradle-2.12-bin ? I am not able to download using command ./gradlew appEngineDownloadSdk in the terminal? I have downloaded externally

**Comment by wkurniawan07** [comment]
Hi @Mynk96, you need to run the said command from the folder where you clone your TEAMMATES fork. On a side note, you do not need to set up Gradle manually on your computer as [Gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html) allows you to perform all the Gradle tasks without actually setting it up.
If you have downloaded the App Engine SDK manually, you are more than welcome to use it for the project.

**Comment by Mynk96** [comment]
Done Thank you
