### ISSUE TITLE
Does Teammates project build on Eclipse Neon ?

### ISSUE THREAD

**Issue by aravindputrevu** [TEAMMATES/teammates#6265]
I want to contribute to the Teammates, so trying to setup the Dev environment. 
I would like to know whether Teammates project supports Eclipse Neon.

Thanks and regards
Aravind Putrevu

**Comment by damithc** [comment]
@aravindputrevu if you are game enough, you can give it a try. Usually newer versions of Eclipse don't break the set up process. You can be the guinea pig to test it out if you wish :-p

**Comment by aravindputrevu** [comment]
Okay then. I will try it and update this thread. @damithc

**Comment by aravindputrevu** [comment]
I have successfully built and deployed teammates on the dev server using Eclipse Neon. Can we add the same to settingup.md
