### ISSUE TITLE
Change URLs to use new repository name

### ISSUE THREAD

**Issue by JosephineKwa** [TEAMMATES/teammates#6282]
There are a few instances in the docs where the old repository name is used in URLs i.e. https://github.com/TEAMMATES/repo instead of https://github.com/TEAMMATES/teammates.
While this does not cause any problems as the old name still redirects to the correct page, it would still be better to use the actual URL to avoid confusion.

Files involved:
`docs/glossary.md`
~~`docs/process.md`~~
~~`docs/settingUp.md`~~
~~`README.md`~~

**Comment by rishikksh20** [comment]
I am interested in working on the issue.

**Comment by wkurniawan07** [comment]
The last two files are not needed as they will be fixed in #6257. I will update the issue description accordingly.
@rishikksh20 you're welcome to.

**Comment by rishikksh20** [comment]
@wkurniawan07  I submitted pull request after change in first two files.

**Comment by AnaghHegde** [comment]
@JosephineKwa is this still open?I am interested in working on this.

**Comment by JosephineKwa** [comment]
Hi @AnaghHegde , currently someone else is working on this issue and there is a PR open for it. Perhaps you could select another [first timer issue from this list](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers), maybe try #4021?
