### ISSUE TITLE
Explore using mentionbot to identify potential reviewers

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6283]
Seems easy to set up and could be useful
https://github.com/facebook/mention-bot

**Comment by AnaghHegde** [comment]
@damithc Can you be little more specific about potential reviewers part ?.

**Comment by damithc** [comment]
> @damithc Can you be little more specific about potential reviewers part ?.

@AnaghHegde let's leave this alone for now. One of the senior devs who has a better view of the workflow can take a look at this.

**Comment by wkurniawan07** [comment]
GitHub has already supported similar feature so...
