### ISSUE TITLE
Student: view session results: do not show self responses

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6290]
Current:
When students view session results, they can see responses they gave to others. 

Suggestion:
Don't show responses the user gave to others. Instead, give a link to show the corresponding submission page. 

Justification:
Self-responses clutter the page. Some students get confused by self-responses.

**Comment by hackosinn** [comment]
@damithc -  do we have to stop the import of self response or only remove the section which shows the self respons?

**Comment by damithc** [comment]
@hackosinn 

> do we have to stop the import of self response or only remove the section which shows the self respons?

What did you mean by 'import'?

**Comment by hackosinn** [comment]
@damithc -sir i mean that user don't need to submit response about himself.

**Comment by damithc** [comment]
@hackosinn 

Stop showing the self-responses only. We should continue to collect self-responses.

**Comment by hackosinn** [comment]
@damithc -ok

**Comment by xpdavid** [comment]
![image](https://cloud.githubusercontent.com/assets/13977235/21951464/cbf4d786-da41-11e6-9a23-4fabc3af62c9.png)
@damithc Currently, the self-response is shown in different colour (maybe that is clear enough). So what I am thinking is to add a phrase like "self-response" instead of removing it.

**Comment by damithc** [comment]
> Currently, the self-response is shown in different colour (maybe that is clear enough). So what I am thinking is to add a phrase like "self-response" instead of removing it

Yes, we can try that. Use 'Your own response' instead? Perhaps use grey color for panels, to tone them down further? Another idea is to collapse them by default, but that can be a different PR.
