### ISSUE TITLE
Wrong Status Message in AdminAccountDeletePageActionTest

### ISSUE THREAD

**Issue by AnaghHegde** [TEAMMATES/teammates#6296]
When deleting a Admin Account in AdminAccountDeletePageActionTest.java  , Const.StatusMessages.INSTRUCTOR_REMOVED_FROM_COURSE is used. And there is no status message defined for this action in StatusMessages class in Const.java.

**Comment by wkurniawan07** [comment]
@AnaghHegde you have to fix the test failure in the PR itself, not in another issue. We do not allow a failing build (❌) to be merged without good reason.

**Comment by AnaghHegde** [comment]
@wkurniawan07  i m not talking about the test failure.The issue #4021 is different( it is with respect to AdminAccountDetailsPage where When deleting a student in Admin Account Details, Const.StatusMessages.INSTRUCTOR_REMOVED_FROM_COURSE is used instead of Const.StatusMessages.STUDENT_DELETED), what i have posted here is about the AdminAccountDeletePageActionTest . I think these two are different. So when i ran the test in my local environment i got the error.So i thought it might be a bug.So i posted it in the issue tracker.

**Comment by wkurniawan07** [comment]
@AnaghHedge, do go through the said test once again. The account that it is removed is an instructor account, not an admin account, thus the status message is correct.

A general, high-level comment: when something does not work right in the application, it is often not meaningful to talk about the tests. The latter are meaningful only when the tests themselves are not right. There is a difference between "The test shows that the application does not work correctly" (the bug exists in the application) and "The test is unstable", "The test does not test the correct items" (the bug exists in the test).

**Comment by AnaghHegde** [comment]
@wkurniawan07 Thanks for information related to test and bugs.
