### ISSUE TITLE
Upgrading AppEngine SDK to latest version ?

### ISSUE THREAD

**Issue by aravindputrevu** [TEAMMATES/teammates#6298]
I would like to know why the older version of AppEngine SDK is used. Why can't we upgrade it by resolving issues ?

**Comment by wkurniawan07** [comment]
Thanks for your query, @aravindputrevu! There are two reasons for this:
- Prior to a few months ago, this project did not use an automated dependency management. This makes updating dependency difficult (if not impossible), thus it is not a regular thing to do (if something to do at all) for the project maintainers.
- Even after that, keeping all dependencies up-to-date at all times is not practical. While some updates are as easy as modifying the build configurations (`build.gradle` and/or `package.json`), problems like dependency hell (you can Google this term to find out!) occur from time to time (although this project has yet to encounter one). Also, some dependency updates require some (non-trivial) tasks to be done by all developers; App Engine SDK falls into this latter category.

Having said that, the SDK was last upgraded more than one year ago (#4500) and indeed it has been a while, so it may be good to finally upgrade again. I will take a look at it some time soon.

**Comment by aravindputrevu** [comment]
Okay ! Please let me know if i can help in anyway.
