### ISSUE TITLE
Refactor TimeHelper and most time-related usages

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6300]
Working on timezone/DST/time-related functions is not really comfortable now because the API of `TimeHelper` is undocumented (in many parts), untested (many functions), under-utilized (many functions still hard-code `Calendar.getInstance`, `Calendar.set`, etc.) and contains many unnecessary functions. To put it in one word: under-maintained.

**Comment by whipermr5** [comment]
Raising priority as this is the root cause of many recent issues (e.g. #7669, #7789, #7808).

**Comment by whipermr5** [comment]
Subsumed under #8362.
