### ISSUE TITLE
New contributor self intro [anand singh]

### ISSUE THREAD

**Issue by hackosinn** [TEAMMATES/teammates#6310]
a) link to your app- http://localhost:8888/page/studentHomePage?user=anandsmart55

b) link to your fork-https://github.com/hackosinn/teammates 
 
c)  a screenshot of the change you did (as seen on the UI). i changed the title in view team page to Team Details. removed the import of the course id next to Team Deatils as we are already showing the course id along with other details.
       
Before

![screenshot 242](https://cloud.githubusercontent.com/assets/19956681/21728222/194c0086-d46b-11e6-9a98-84e3b7092f29.png)

After
![screenshot 241](https://cloud.githubusercontent.com/assets/19956681/21728247/3165cb66-d46b-11e6-943b-1f843f429b0a.png)

d) My name is Anand Singh. i'm a b.tech 3rd year student. for the first time i'm contributing to an oss. i'm looking forward to contributing to teammate and learn many new things.

**Comment by wkurniawan07** [comment]
Welcome to TEAMMATES, @hackosinn!
The "link to your app" posted is incorrect, though, it should be something like `https://teammates-hackosinn.appspot.com/page/studentHomePage?user=anandsmart55` (I pick the app name randomly, but you get the idea). Have you managed to deploy your own app to a staging server?
Nevertheless, you are welcome to contribute to some issues. Most, especially the easier ones, don't require testing on staging server.

**Comment by hackosinn** [comment]
i created the server in my laptop and host the app on it. link works only when my laptop is on.
@wkurniawan07  if it is necessary then i can host it on google cloud platform.

**Comment by junhaoyap** [comment]
@hackosinn, Welcome to TEAMMATES!

It is better if you will be able to do so because there will be certain issues whereby being able to stage your own server will be required, like @wkurniawan07 mentioned, it might not be necessary for beginner issues so you can start by working on one first timer issue before revisiting this, what is the problem you're having in hosting it on google cloud platform by the way?

**Comment by hackosinn** [comment]
@junhaoyap - i'm unable to register for free trial of google cloud platform.they are asking for debit card(though they will not charge) but they are not accepting my card.

**Comment by hackosinn** [comment]
@junhaoyap - i am posting the screenshot of the error (it says use jdk not jre)
![screenshot 253](https://cloud.githubusercontent.com/assets/19956681/21765803/1226f608-d691-11e6-885e-4d990dc13460.png)

i'm using jdk not jre.
![screenshot 254](https://cloud.githubusercontent.com/assets/19956681/21765858/5069e9a2-d691-11e6-9a38-4c101409de2a.png)

**Comment by wkurniawan07** [comment]
@hackosinn I'm referring to your second screenshot: it shows all the installed JREs to be used by Eclipse, not necessarily to be used by any particular project. The one that you should be paying attention to is `Project -> Properties -> Java Build Path -> Libraries -> JRE System Library`. Does it correctly use a JDK 1.7?

**Comment by hackosinn** [comment]
@wkurniawan07 - Sir, what did u mean by "Does it correctly use a JDK 1.7

**Comment by wkurniawan07** [comment]
@hackosinn does the problem still persist?
