### ISSUE TITLE
Unsupported major minor issue 52

### ISSUE THREAD

**Issue by nikhilmudholkar** [TEAMMATES/teammates#6311]
I got the error mentioned in the title. I looked up the net and people suggested me to uncheck the box mentioned in the image below and select 1.7 in compilation level.

![issue 1](https://cloud.githubusercontent.com/assets/20753893/21731760/03a8c30c-d47c-11e6-991d-89e3d5489599.png)

But when i do it and then apply settings. The settings don't get applied. The checkbox returns to it's orignal state.

![issue2](https://cloud.githubusercontent.com/assets/20753893/21731819/52c658e6-d47c-11e6-8b6a-3e0db74e949b.png)

@damithc @wkurniawan07 ...can you help me figure out the problem. I am stuck in starting the dev server since a long time.

**Comment by nikhilmudholkar** [comment]
I tried doing what was told to do in troubleshooting guide about the "unsupported major minor issue 52". But that dosen't seem to be working. I am still getting the same error. Even the problem mentioned above was solved and i tried setting compilation level to 1.7 . Still the same error.

**Comment by AnaghHegde** [comment]
@nikhilmudholkar do you have java 8 installed in your machine? .Which os are you using windows 10?

**Comment by junhaoyap** [comment]
@wkurniawan07 can you assign someone on the Windows platform to this?

**Comment by nikhilmudholkar** [comment]
I am using windows 8.1. I had java 8 installed on my machine. But when this error showed, internet suggested me to uninstall it. But even after uninstalling, the problem continues.

**Comment by AnaghHegde** [comment]
@nikhilmudholkar did you set the JAVA_HOME for jdk 7?. Check if java.exe , javac.exe , javaws.exe is there in  C:\Windows\System32 if they are present delete those files and set the JAVA_HOME. I m not sure it will work , but it worked for me (i  also had a similar problem). In windows 10 you can't have both java 7 and 8 , i don't know if its true for 8.1 also .

**Comment by nikhilmudholkar** [comment]
I am completely confused now. I completely deleted java8 from my PC. I even followed the tutorial guideline to the problem. Still i am getting the same issue. Is it related to the version of eclipse I am using?? I am using eclipse luna.
@wkurniawan07  what might be the issue and how can i solve it?
