### ISSUE TITLE
User map: move 'last updated date' to userMapData.json

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6317]
Currently the last updated date of the user map is in `src/main/webapp/usermap.jsp` while the user data is actually updated in `src/main/webapp/js/userMapData.json`.

Explore the possibility of moving the date into the json file so that only one file needs to be updated.

**Comment by AnaghHegde** [comment]
@damithc  i am interested in this. can i work on this ?

**Comment by damithc** [comment]
@AnaghHegde sure

**Comment by AnaghHegde** [comment]
@damithc can you guide me a little about the issue. I didn't get the issue .

**Comment by damithc** [comment]
@AnaghHegde Have a look at #5792 That should help you understand what this issue is about.

**Comment by AnaghHegde** [comment]
@damithc one more thing just to confirm its with respect to only user map right?

**Comment by damithc** [comment]
> one more thing just to confirm its with respect to only user map right?

Yes.

**Comment by AnaghHegde** [comment]
@damithc Correct me if i am wrong ok but in the issue #5792 the date is updated no?. So i just have to again update it for latest user map right ?.

**Comment by damithc** [comment]
> but in the issue #5792 the date is updated no?. So i just have to again update it for latest user map right?

No, you misunderstood the issue entirely. Give it another go (i.e read the issue description again and give it some more thoughts). :-p

**Comment by AnaghHegde** [comment]
@damithc ok. So i have to move (add in json file ) the last updated date to userMapData.json and make it display in the webpage right? and remove the last updated date in usermap.jsp file ?

**Comment by damithc** [comment]
> So i have to move (add in json file ) the last updated date to userMapData.json and make it display in the webpage right? and remove the last updated date in usermap.jsp file ?

Yes, that's right.

**Comment by paradite** [comment]
I think this is actually quite hard to do. The approach I can think of is to:
- fetch the data from json using javascript
- render it within the jsp using javascript

**Comment by AnaghHegde** [comment]
@paradite Thanks for the input.

**Comment by AnaghHegde** [comment]
@damithc can you please help me in #6322 .Its failing in code formats even though i did the source format.

**Comment by paradite** [comment]
https://github.com/TEAMMATES/teammates/issues/6317#issuecomment-271586376

testing.

**Comment by AnaghHegde** [comment]
@paradite I didn't get you.

**Comment by paradite** [comment]
@AnaghHegde Ah sorry. I was just testing out something It is not related to you or the issue, you can ignore it.

**Comment by AnaghHegde** [comment]
@damithc Can you please tell me what does this error says :   Unexpected negated condition  no-negated-condition . I got this in build log.

**Comment by damithc** [comment]
> Can you please tell me what does this error says : Unexpected negated condition no-negated-condition . I got this in build log.

Let's see what happens after redoing your PR from scratch after a fresh setup.

**Comment by AnaghHegde** [comment]
I did from the scratch and this is the only error i am getting.So i am
asking this.
