### ISSUE TITLE
New contributor self intro [Samson]

### ISSUE THREAD

**Issue by samsontmr** [TEAMMATES/teammates#6326]
a) [teammates-samson.appspot.com](http://teammates-samson.appspot.com)
b) [https://github.com/samsontmr/teammates](https://github.com/samsontmr/teammates)
c) a screenshot of the change you did (as seen on the UI)
*Before*
![before](https://cloud.githubusercontent.com/assets/15007950/21845910/8716fb94-d82f-11e6-92f5-53eaa9de9488.png)
*After (improved text readability)*
![after (improved text readability)](https://cloud.githubusercontent.com/assets/15007950/21845909/86d0cafc-d82f-11e6-9f89-3b3dead0219d.png)
d) I'm Samson and I'll be contributing to TEAMMATES as part of CS3281/2. I'm also contributing to matplotlib and scikit-learn!

**Comment by junhaoyap** [comment]
@samsontmr, welcome to TEAMMATES and good job on finishing the orientation tasks! 👍 Your first link is incorrect as it links to something github, removing the github prepended url works so there's not big issue here!

I see that you'll be contributing as part of CS3281/2 so I hope you can start by looking at some first timer issues, seeing as you have already contributed to other open source projects before, it should be easy to get your feet wet!

**Comment by samsontmr** [comment]
Strange, must have been the http://. I've created PRs on some issues!
