### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6327]
**What is the proposed new/enhanced feature?**

Templates for creating issues in our issue tracker.

Templates are quite commonly used in other open source projects to streamline the process of issue reporting. For example:
- Bug reports: "Which environment the bug comes from" (dev/staging/live at some version), "What is done", "What is the expected behaviour", "What is the actual behaviour", etc.
- Feature/enhancement requests: "What is the proposed new/enhanced feature", "Are there existing similar features, and in what way are they lacking", "What problems/use cases does it solve", etc.
- New contributor self-intro: As per defined in our contributor's orientation guide.
- Help requests: As per defined in our troubleshooting guide.

We could even enforce an issue title based on this, e.g it has to be prefixed with one of those categories.

**Are there existing similar features, and in what ways are they lacking?**

The best that we have is CONTRIBUTING.md, but the contents are far too generic ("clear title, description, and as much relevant information as possible").

**What problems/use cases does it solve?**

Makes it easier for the core team to triage issues, less time needed to clarify stuffs from the issue reporter, etc.

**Comment by shrut1996** [comment]
@wkurniawan07  Has this issue been resolved?

**Comment by damithc** [comment]
> Has this issue been resolved?

@shrut1996 You can visit the ongoing PR for this issue (link given in the issue timeline, just above your comment) to see the current status of it.
