### ISSUE TITLE
Implement InstructorFeedbackRemind(ParticularStudents)ActionTest

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6329]
It was left empty before with the following reason:
```java
@Test
public void testExecuteAndPostProcess() {
    // This test case was omitted as the action is executed in the background task queue
    // so we cannot determine its result.

    // The logic under the action is covered with test case to ensure the action works.
}
```
The reason is no longer valid because the architecture of the task queue has been enhanced to allow for testing (refer to #6223).

**Comment by AnaghHegde** [comment]
@wkurniawan07 I am interested in this. Can i work on this ?.

**Comment by xpdavid** [comment]
@AnaghHegde I have done with it. PR on the way. Sorry

**Comment by AnaghHegde** [comment]
@xpdavid ok sure.No problem i will find other.
