### ISSUE TITLE
Invalid link and no image for University Count in README.md file

### ISSUE THREAD

**Issue by AnaghHegde** [TEAMMATES/teammates#6330]
![screenshot 40](https://cloud.githubusercontent.com/assets/12005551/21849827/cf2a4a00-d82d-11e6-8605-315e7de56e26.png)

Both the image and link are not working properly.

![screenshot 41](https://cloud.githubusercontent.com/assets/12005551/21849836/da68c572-d82d-11e6-8ba0-254772c39492.png)

**Comment by wkurniawan07** [comment]
This happens intermittently and is not a consistent failure.
