### ISSUE TITLE
New contributor self intro [Xiao Pu]

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#6336]
a) [https://teammates-xiaopu.appspot.com/](https://teammates-xiaopu.appspot.com/)
b) [https://github.com/xpdavid/teammates](https://github.com/xpdavid/teammates)
c) a screenshot of the change you did (as seen on the UI) Related to issue #3328
_Before_:
![screen shot 2017-01-11 at 8 31 31 pm](https://cloud.githubusercontent.com/assets/13977235/21878751/444df2ae-d8cf-11e6-9967-8512822626a9.png)
_After:_
![screen shot 2017-01-11 at 8 32 15 pm](https://cloud.githubusercontent.com/assets/13977235/21878784/6d634450-d8cf-11e6-9732-f6f7e11bfabd.png)
d) I'm Xiao Pu and I'll be contributing to TEAMMATES as part of CS3281/2.

**Comment by junhaoyap** [comment]
@xpdavid, welcome to TEAMMATES and good job on finishing the orientation tasks without mistakes! 👍 

I see that you'll be contributing as part of CS3281/2 so I hope you can start by looking at some first timer issues, it will be a good chance for you to start getting your feet wet!

**Comment by xpdavid** [comment]
@junhaoyap I have completed one first beginner issue #6213 and a issue for contributor #6324.
I will continue to work on this project :)

**Comment by junhaoyap** [comment]
@xpdavid great! Doing very well :)
