### ISSUE TITLE
Use package.json and CDN to entirely manage front-end dependencies regardless of environment

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6346]
It will be a contradiction to #3923, but I have experienced that having to sync the copies (particularly during updates) adds a non-trivial maintenance burden. I therefore propose to reverse the decision made in that issue and opt for using CDN fully for external files, dev environment or not.

Cons:
- Internet connection is required. One of the original intention of that issue was to severe the need for Internet, but hey everyone's on Internet these days.
- If the CDN is down, so is the dev environment, but it will also affect the live environment so the dev environment getting affected is a secondary problem. 😛
- May slow down (or even speed up?) the tests. I can't provide any quantitative evidence of this, though.

Pros:
- Adding/updating/deleting libraries are as simple as adding/updating/deleting entries to/in/from `package.json` (of course, discounting other stuffs such as dependency hell).
- It severs the need to host the local copies of the libraries anymore; reduces repo size and maintenance burden significantly. This burden comes from having to know which files of the library need to be hosted, and affects all three processes of add/update/delete.

The pros far outweigh the cons for me, but that's just one person's (biased) opinion.
@damithc @junhaoyap will need your inputs on this!

**Comment by damithc** [comment]
We can try it out.

**Comment by junhaoyap** [comment]
@wkurniawan07 @damithc I am for it as well, back in the "dark ages" we did not have CI and running tests locally is really a huge burden, especially since network connectivity in certain parts of school or time (cough cough) may be "not as good".. now that we have automatic tests running on production ready servers handled by Jenkins, these problems should be less relevant and this is a good move

**Comment by wkurniawan07** [comment]
@junhaoyap my concerns as well. Unrelated, but just one correction before you potentially mislead other devs: we're using Travis, not Jenkins :p

**Comment by paradite** [comment]
Just curious why not use a js bundler or builder to automate the process of managing front-end libraries? I am talking about webpack or Rollup. 

In this way, you can keep everything in `package.json` while not relying the CDN. Instead npm and the builder will grab the libraries and serve them together with the other local codebase.

**Comment by wkurniawan07** [comment]
> Just curious why not use a js bundler or builder to automate the process of managing front-end libraries? I am talking about webpack or Rollup.

Under my radar (although not in the near future), but let's take it one step at a time. Introducing JS automated tool is a non-trivial devops task.
