### ISSUE TITLE
Difficulty downloading app engine SDK while setting up dev server

### ISSUE THREAD

**Issue by hackosinn** [TEAMMATES/teammates#6347]
command to download app engine  is not downloading any app engine. i'm running the command in root directory. it says build successful but there is no app engine  folder in root directory.

Screenshot:
![screenshot 271](https://cloud.githubusercontent.com/assets/19956681/21945022/1158d7f2-d9ff-11e6-81a9-2ac4045e41e9.png)

**Comment by wkurniawan07** [comment]
It is never intended to be downloaded in the project's root directory in the first place. Gradle does not work that way.

**Comment by xpdavid** [comment]
The task `appengineDownloadSdk` is provided by google app engine plugin for Gradle.

**Comment by hackosinn** [comment]
i tried to apply plugin but got error-"Task apply is not found in root  project teammates".

**Comment by hackosinn** [comment]
@xpdavid  - can u elaborate the steps u did to download and install app engine.

**Comment by wkurniawan07** [comment]
> i tried to apply plugin but got error-"Task apply is not found in root project teammates".

What did you mean by "apply plugin"?

Also, I recall that you have successfully run a dev server instance on your computer before. That should mean you have followed the setting up instructions correctly before. Have you done similarly this time?

**Comment by hackosinn** [comment]
@wkurniawan07 - u r right. i followed the same steps as before but i don't know why am i facing problems this time. i downloaded the app engine from google and place it in root directory of teammates and in Eclipse → Preferences → Google → App Engine,  add app engine. it is not working.

**Comment by xpdavid** [comment]
@wkurniawan07 BTW It is necessary to create issue template.
@hackosinn Make sure you use correct java version and app engine version. Can you put the details of your errors? Like what eclipse tells you?

**Comment by hackosinn** [comment]
@xpdavid - how did u download app engine. please write down the steps

**Comment by wkurniawan07** [comment]
@hackosinn could you please explain what you have tried and what did not work? Giving out straightaway answers to "please write down the steps" is a form of spoonfeeding (Google this term if you do not know), and does not help in honing your developing/troubleshooting skills. Figuring generic things out like this is a necessary skill for developers working on open source projects.

**Comment by hackosinn** [comment]
@wkurniawan07 - apologies for that.i ran the command given in contribution guide to download app engine in root directory of teammates and output was build successful. but what should i select in Eclipse → Preferences → Google → App Engine as there is no app engine. the command to download the app engine didn't download the app engine.

**Comment by wkurniawan07** [comment]
@hackosinn have you followed step 4 of the setting up guide, i.e. the same document?

**Comment by hackosinn** [comment]
@wkurniawan07  i followed every instruction of step 4. only problem i am getting is to select app engine in eclipse as there is no app engine to select. the command to download the app engine didn't download it.  screenshot of the command
![screenshot 273](https://cloud.githubusercontent.com/assets/19956681/21957189/3c49906a-dab7-11e6-9864-0c9f63f27f1f.png)

**Comment by hackosinn** [comment]
@wkurniawan07  according to guide command should download the required app engine, but it only says build successful

**Comment by xpdavid** [comment]
@hackosinn The app engine sdk won't be put in the `teamates` repo directory. Instead it will be put in the dir like `/Users/XP/.gradle` (in mac OS). Try run `./gradlew printUserHomeDir` to get the install dir.

**Comment by wkurniawan07** [comment]
@hackosinn, please follow the step 4 carefully, word by word. There was at least one thing that you have correctly done before that you missed out now.

>according to guide command should download the required app engine, but it only says build successful

This one I can tell you: because you have downloaded it before. That is how dependency management tools work.

> i'm using gradle 3.2.1

You don't really need to install your own Gradle.
