### ISSUE TITLE
"magic" string in "InstructorFeedbackRemindParticularStudentsAction"

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#6353]
There is a "magic" string in "InstructorFeedbackRemindParticularStudentsAction"
``` java
String[] usersToRemind = getRequestParamValues("usersToRemind");
```
For good code quality, should use `Const.ParamsNames.SUBMISSION_REMIND_USERLIST` instead.
``` java
// Should use
String[] usersToRemind = getRequestParamValues(Const.ParamsNames.SUBMISSION_REMIND_USERLIST); 
```

**Comment by yash2o1o** [comment]
hi, i am a first timer, if possible i would like to take this up.

**Comment by xpdavid** [comment]
@yash2o1o There is a PR on the way #6362. You may need to choose another issue to work on.
