### ISSUE TITLE
Separate common.datatransfer package into sub-packages

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6355]
`teammates.common.datatransfer` is presently too cluttered and could be tidied up by breaking into sub-packages based on these categories:
- `.attributes`: the entity attributes, essentially those which can connect to the persistable entities.
- `.questiontypes`: the classes related to feedback questions and responses for different question
- `.bundles`: everything else (for the lack of more fine-tuned categories). Hopefully, everything in this sub-package is pure data structures: just classes containing public class variables without any methods (and thus naturally exempted from testing).

Other plausible categorisations are acceptable for consideration.

**Comment by damithc** [comment]
Keep in mind that packaging should be done based on coupling rather than category. i.e. a bunch of classes that work together should be in the same package.

**Comment by samsontmr** [comment]
How about `.comment` , `.course`, `.student`, `.instructor`?

**Comment by samsontmr** [comment]
@damithc @wkurniawan07 Shall I go ahead and refactor the package according to the sub-packages I've proposed?

**Comment by damithc** [comment]
> Shall I go ahead and refactor the package according to the sub-packages I've proposed?

@wkurniawan07 's call as he has a better overall view of restructuring that is going on.

**Comment by wkurniawan07** [comment]
@samsontmr that would be unnecessarily fragmented, and would cause even more coupling if we have cases where some course DTO interacts with some student DTO (which is very possible).
At the very least, the `.attributes` sub-package must be there because it essentially limits the dependency to `storage.entity` package to that sub-package only. Everything else (`.bundle`, `.questiontypes`, or other kinds of grouping) are experimentable. The idea is to try to minimize the coupling needed between one sub-package to another.

**Comment by samsontmr** [comment]
@wkurniawan07 alright shall we stick to the original 3 you suggested then?

**Comment by wkurniawan07** [comment]
@samsontmr follow at least `.attributes`. Everything else, you can experiment.
