### ISSUE TITLE
Reorganize parts of the test package

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6360]
In particular:
- `teammates.test.cases.ui`: the package contains action tests, the subpackage `browsertests` contains UI tests, and the subpackage `pagedata` contains page data tests. Bundling them is incorrect because these three types of test are entirely different: `pagedata` is a data transfer structure with no knowledge of the application components, `action` is the application component that is next-to-next-to-most directly visible to the end user, and `browsertests` is a black-box UI testing with no knowledge of the application components.
- `teammates.test.cases.common`: should be separated between the utility classes and DTO classes.
- `teammates.test.util`: no clear difference from `teammates.test.driver`, and it is not present in the architecture diagram anyway.

**Comment by samsontmr** [comment]
Do you need help with this? The second one seems easy enough

**Comment by wkurniawan07** [comment]
@samsontmr thanks but no thanks, I'm actually done with this :p
