### ISSUE TITLE
Dec app server not running as expected.

### ISSUE THREAD

**Issue by nikhilmudholkar** [TEAMMATES/teammates#6361]
I have compiled my project properly. It is giving no errors initially. But when i go to http://localhost:8888/admin/adminHomePage  , it shows error in console as unsupported major minor issue 52. The login page is loading but after that this error comes. Please help. I am a bit new and facing lot of problems.

**Comment by wkurniawan07** [comment]
@nikhilmudholkar, I appreciate you trying to say that you have completely deleted Java 8 from your PC, but the evidence "unsupported major minor issue 52" has spoken that you still used Java 8. Can you provide evidence to support that you no longer use Java 8? Some places to find out from:
- The result of running `java -version` command
- The Eclipse configurations:
  - `Window -> Preferences -> Java -> Compiler`
  - `Window -> Preferences -> Java -> Installed JREs`
  - `Project -> Properties -> Java Compiler`
  - `Project -> Properties -> Java Build Path -> Libraries -> JRE System Library (an entry on the list)`

Eclipse version has nothing to do with it as Eclipse does not come bundled with any Java, and Luna is one of the supported versions.

**Comment by nikhilmudholkar** [comment]
![issue1](https://cloud.githubusercontent.com/assets/20753893/21965257/37717514-db82-11e6-883a-2106a2d1c5a3.png)


![issue2](https://cloud.githubusercontent.com/assets/20753893/21965264/3ecbfafa-db82-11e6-989c-181e3dac3775.png)

![issue3](https://cloud.githubusercontent.com/assets/20753893/21965266/473068de-db82-11e6-8430-be21e9d82158.png)

![issue4](https://cloud.githubusercontent.com/assets/20753893/21965267/4e47b9c4-db82-11e6-8e0b-428ac64a45ee.png)

![issue5](https://cloud.githubusercontent.com/assets/20753893/21965269/54b5d7d2-db82-11e6-8a0b-eafcc7547d57.png)

@wkurniawan07  these are the images that u asked fr. I am stuck in this issue for a long time. Please suggest me an answer, i am quite interested to work in teammates.

**Comment by kanghj** [comment]
@nikhilmudholkar, does http://localhost:8888 load fine for you? Anyway, although this usually only happens during deployment, you could try the second point under Common Problems in our [troubleshooting guide](https://github.com/TEAMMATES/teammates/blob/master/docs/troubleshooting-guide.md#common-setup-errors-and-solutions) and see if doing [this](http://stackoverflow.com/questions/13913019/changing-jdk-in-eclipse) helps.

**Comment by nikhilmudholkar** [comment]
![issue6](https://cloud.githubusercontent.com/assets/20753893/21972759/c0038746-dbe1-11e6-95d6-19ffd3eb9c5a.png)

as you can see localhost:8888 is working perfectly.

![issue7](https://cloud.githubusercontent.com/assets/20753893/21972770/e43ecd1e-dbe1-11e6-8016-a0b00a95d1fe.png)
even this login page is loading. But when i click login as checking the administrator box i get the error.

![issue8](https://cloud.githubusercontent.com/assets/20753893/21972774/fd9c78ec-dbe1-11e6-91a0-4ab59b7cbb27.png)

**Comment by wkurniawan07** [comment]
@nikhilmudholkar can you try running `gradlew.bat resetEclipseDeps` and then refreshing the project?

**Comment by nikhilmudholkar** [comment]
@wkurniawan07 ....i tried. But the problem persists.What should i do??

**Comment by wkurniawan07** [comment]
@nikhilmudholkar does this problem still persist?
