### ISSUE TITLE
Error while deploying to app engine

### ISSUE THREAD

**Issue by 95adityajain** [TEAMMATES/teammates#6363]
`Error :` Unable to update app: Error posting to URL: https://appengine.google.com/api/queue/update?app_id=teammates-aditya&version=4-18&
400 Bad Request
**Invalid queue configuration**. Must be fewer than or equal to **_10 non-default entries_**

Above error occurs, when task queues are being deployed on app engine(As there are `11` task queues defined in `src/main/webapp/WEB-INF/queue.xml`).

> What I did:

Commented one queue tag in `queue.xml` (now total number of queues are `10` ), and then project is deployed successfully.

How can i deploy without removing one of the task queue?
Thanks

**Comment by wkurniawan07** [comment]
Hmmmm it looks like the limit is imposed for apps with no billing enabled. Can you enable billing and try again? If you don't want to be charged, just set your spending limit to 0.

**Comment by 95adityajain** [comment]
Thanks. It worked.

**Comment by ovshake** [comment]
@wkurniawan07 
My Dev Server is running on local host but when I am trying to host it on the GAE, it is showing me this error.
![error message](https://cloud.githubusercontent.com/assets/22028532/21982890/6d0adfa2-dc14-11e6-97a8-22946db69437.png)

I ensured that I have JDK installed (1.7..0_80).
![installed jre](https://cloud.githubusercontent.com/assets/22028532/21982940/a2717ee4-dc14-11e6-8b13-e607d396ba42.png)

And I also checked the project level of JDK.

![compilation level](https://cloud.githubusercontent.com/assets/22028532/21982956/bcb984b8-dc14-11e6-89be-d8a2b7e0c602.png)

The error log showed this


![error log](https://cloud.githubusercontent.com/assets/22028532/21983203/1b8517e0-dc16-11e6-95a7-ba58571ef26f.png)


After looking at some online forums, I modified the eclipse.ini file as by adding the vm argument but then it is showing me a Fatal Error. 
I have also checked the org.gradle.java.home variable. It is pointed to the jdk directory as shown in the comments.
 
Thanks

**Comment by damithc** [comment]
> After looking at some online forums, I modified the eclipse.ini file as by adding the vm argument but then it is showing me a Fatal Error.

Once I faced the same error, and updating the eclipse.ini file solved it. Perhaps you can post how you modified the ini file and what is the fatal error you get?

**Comment by ovshake** [comment]
![fatal error](https://cloud.githubusercontent.com/assets/22028532/21986468/9479ecca-dc25-11e6-87c2-7efe4aa31017.png)

This is the dialog box i get after I click OK for the fatal error message. 
I have added the vm argument before the vmargs argument.

**Comment by ovshake** [comment]
This is the fatal error dialog box

![fatal error2](https://cloud.githubusercontent.com/assets/22028532/21986668/594d53ca-dc26-11e6-92dc-5e78965850a2.png)

and this the ini file on notepad

![notepad file](https://cloud.githubusercontent.com/assets/22028532/21986683/66258ae0-dc26-11e6-90c2-bb0e7d951fc6.png)

**Comment by damithc** [comment]
I wonder if it's something to do with the space in the middle of `Program Files` in you -vm argument. Try using `PROGRA~1` in place of `Program Files` (they are equivalent). I'm just shooting in the dark here.

**Comment by 95adityajain** [comment]
@ovshake 
![untitled](https://cloud.githubusercontent.com/assets/22568835/21987409/63688d04-dc29-11e6-9aa8-58ae41d70f43.png)

Try moving `--launcher.appendVmargs` just above `-vmargs` (below `-vm`)

**Comment by ovshake** [comment]
@damithc @95adityajain 
This is how my ini file looks right now.
![image](https://cloud.githubusercontent.com/assets/22028532/21990407/b41d0224-dc34-11e6-817f-3b382c6562bf.png)

I didn't get a fatal error now, but eclipse still didn't open up. Now it told me some to check the log files as 'some' error has occurred. The log file was unreadable but this thing caught my eye. I have erased all traces of Java 1.8 as far as eclipse is concerned. I even removed it from my Path variable. Then how come this thing showed up?

![image](https://cloud.githubusercontent.com/assets/22028532/21990368/8c029286-dc34-11e6-92e6-2cc825224e25.png)

**Comment by damithc** [comment]
@ovshake 
Perhaps you can try with a fresh copy of eclipse, in case it cached some Java8-related settings when it was run when Java 8 was available on your computer?

**Comment by damithc** [comment]
BTW, here's my eclipse.ini (I'm using Eclipse Mars)
```txt
-startup
plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.300.v20150602-1417
-product
org.eclipse.epp.package.jee.product
--launcher.defaultAction
openFile
--launcher.XXMaxPermSize
256M
-showsplash
org.eclipse.platform
--launcher.XXMaxPermSize
256m
--launcher.defaultAction
openFile
--launcher.appendVmargs
-vm
C:/Program Files/Java/jdk1.7.0_45/bin
-vmargs
-Dosgi.requiredJavaVersion=1.7
-Xms256m
-Xmx1024m
```

**Comment by nikhilmudholkar** [comment]
@damithc ....will working with a fresh copy of eclipse solve my problem as well? I have mentioned my problem in the fresh issue that i created.
Can eclipse cache java related settings??

**Comment by damithc** [comment]
@nikhilmudholkar

> will working with a fresh copy of eclipse solve my problem as well

Can give it a try. The fact is, we know the set up procedure works (because so many others have set up successfully) and we can only suggest solutions for problems that we have encountered before. For new problems that crop up for whatever reason, we can only hope that the respective dev will figure out the solution using Internet resources and share the solution so that others can benefit.

**Comment by hackosinn** [comment]
@ovshake -  http://stackoverflow.com/questions/3333553/how-can-i-change-the-java-runtime-version-on-windows-7.  type regedit in run. then go to HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\jre  edit this and change 1.8 to 1.7 .  hope this helps

**Comment by ovshake** [comment]
@hackosinn    I did that too....I ended up messing up both my 1.7 and 1.8 and I needed 1.8 for my college purposes. I will try tonight again from scratch installing both of them. (My 15th attempt :P)
