### ISSUE TITLE
New contributor self intro [Li Kai]

### ISSUE THREAD

**Issue by li-kai** [TEAMMATES/teammates#6365]
a) https://teammates-divided.appspot.com/
b) https://github.com/li-kai/teammates
c) Enlarged the click area for log in links, so no more aiming with your mouse!
<img width="276" alt="untitled" src="https://cloud.githubusercontent.com/assets/14850387/21976734/2d5d4d32-dc0e-11e6-95cd-5bee5b7b59c7.png">
<img width="238" alt="untitled1" src="https://cloud.githubusercontent.com/assets/14850387/21976735/2d5d4594-dc0e-11e6-9ca7-ece253cf4fc9.png">
d) I'm Li Kai and I'll be contributing to TEAMMATES as part of CS3281/2. I'll be looking forward to improving the experience of using TEAMMATES.

**Comment by junhaoyap** [comment]
@li-kai, welcome to TEAMMATES and good job on finishing the orientation tasks as mentioned in the documents and TEAMMATES are not divided :(

I see that you will be contributing as part of CS3281/2 so if you have already completed a firstTimer task, we look forward to seeing your contributions to the higher level tasks, if not it will be great if you can get your feet wet via one firstTimer issue!
