### ISSUE TITLE
Homepage links open to same new tab

### ISSUE THREAD

**Issue by li-kai** [TEAMMATES/teammates#6366]
Steps to reproduce: 
1) Click on any of the links under `Well Received by the Academic Community` section of the [homepage](https://teammatesv4.appspot.com/), which opens a new tab. 
2) Again, go back to the homepage and click on another link.

You will notice that the link opens to the same tab in step 1. The reason is that instead of `target="_blank"`, it is `target="blank"`.

**Comment by aravindputrevu** [comment]
Can i take up this ? @damithc

**Comment by damithc** [comment]
@aravindputrevu you can submit a PR for a `d.FirstTimer` issue without asking first. Note that you should not do more than one `d.FirstTimer` issues.

**Comment by wkurniawan07** [comment]
@aravindputrevu you have done a `d.FirstTimers` issue before, please do other types of issues. Particularly those labelled `d.Contributors` are suitable.

**Comment by aravindputrevu** [comment]
@wkurniawan07  @damithc Thank you ! Will search issues labelled with that label.
