### ISSUE TITLE
New contributor self intro [Aditya]

### ISSUE THREAD

**Issue by 95adityajain** [TEAMMATES/teammates#6369]
a) http://4-18-dot-teammates-aditya.appspot.com/
b) https://github.com/95adityajain/teammates
c)  Login button UI changed.
![change](https://cloud.githubusercontent.com/assets/22568835/21980329/e894a04c-dc08-11e6-9032-b21683c7b990.jpg)

d) I'm Aditya Jain, 4th year B.tech student, looking forward to learning exciting things by contributing to TEAMMATES.

**Comment by yasirunilan** [comment]
Good start Adithya and well done. (Y)
 Now it's time to go ahead and work on a a first timer labeled issue.

**Comment by junhaoyap** [comment]
Thank you @yasirunilan for welcoming @95adityajain!

@95adityajain, welcome to TEAMMATES and good job on finishing the orientation tasks as described!

If you have already completed a firstTimer task, we look forward to seeing your contributions to the higher level tasks, if not it will be great if you can get your feet wet via one firstTimer issues (not more than that as we want to share those with the other new contributors)!
