### ISSUE TITLE
Distribute points (among options) question should not allow duplicate options

### ISSUE THREAD

**Issue by JosephineKwa** [TEAMMATES/teammates#6371]

**Comment by damithc** [comment]
@JosephineKwa did you mean disallow duplicate options?

**Comment by JosephineKwa** [comment]
@damithc yup that's what I meant

**Comment by thenaesh** [comment]
Can I confirm that this is what you want to disallow?

![duplicate_options](https://cloud.githubusercontent.com/assets/9165895/22049527/bd4788fc-dd6e-11e6-9b22-d23d97b40e60.png)

**Comment by JosephineKwa** [comment]
:+1 @thenaesh yup thats what I want to disallow
