### ISSUE TITLE
Submit feedback: distribute points (among recipients) question: give a way to distinguish between recipients with the same name

### ISSUE THREAD

**Issue by JosephineKwa** [TEAMMATES/teammates#6372]
In the feedback submission page, there is no way (except by inspecting the html) to distinguish between students with the same name. This affects the results page as well, where the user is only able to distinguish between students with the same name through their photograph.

**Comment by damithc** [comment]
Most instructors don't force students to upload a photo. So, we need something else. Show email as tooltip?

**Comment by samsontmr** [comment]
what about Matric/Admin ID?

**Comment by yasirunilan** [comment]
Showing email as the tool tip would be good. But can't we display the email as another field without showing it as a tool tip.I feel like that better than a tool tip.
Any idea??

**Comment by damithc** [comment]
> But can't we display the email as another field without showing it as a tool tip.I feel like that better than a tool tip.

In 99.9% of the cases, the email address is not needed because the name is enough to distinguish. So showing it all the time adds unnecessary noise to the page. 


Another (better?) approach is to disallow same name in the same course and ask the user to add some additional info to the name if they are the same.

**Comment by yasirunilan** [comment]
If so I think showing the tool tip is better as my opinion.

**Comment by AnaghHegde** [comment]
What if we show email id to only those students who have same name along with name. So it avoids the unnecessary noise and it will be easy to identify.

> In 99.9% of the cases, the email address is not needed because the name is enough to distinguish. So showing it all the time adds unnecessary noise to the page.

**Comment by damithc** [comment]
> What if we show email id to only those students who have same name not for all students. It avoids the unnecessary noise and it will be easy to identify.

That works too.

**Comment by AnaghHegde** [comment]
@damithc can i work on this ?

**Comment by damithc** [comment]
> can i work on this ?

Yes, if you have some idea on how to proceed and you have already completed a `d.FirstTimer` issue.

**Comment by yasirunilan** [comment]
@AnaghHegde  are you working on this one?

**Comment by AnaghHegde** [comment]
@yasirunilan yes i am working on this.PR on its way.

**Comment by AnaghHegde** [comment]
@yasirunilan I m not working on this sorry . Its not listed as a `d.contributor`. So i will find something else to work on. I didn't notice the tag.

**Comment by junhaoyap** [comment]
cc @wkurniawan07 could you add tags to this issue, re: ^

**Comment by damithc** [comment]
Giving low priority because there is a workaround for this rare problem (i.e. just ask the instructor to modify the names so that they are distinguishable).

**Comment by whipermr5** [comment]
Following https://github.com/TEAMMATES/teammates/pull/8036#issuecomment-330864397, I guess this issue should be closed?

**Comment by damithc** [comment]
> Following #8036 (comment), I guess this issue should be closed?

Yes, but need to spawn a new issue for the new approach suggested.

**Comment by whipermr5** [comment]
> Yes, but need to spawn a new issue for the new approach suggested.

Done: #8041
