### ISSUE TITLE
Remove unused methods in CoursesLogic

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6378]
The following two methods:
- `getTotalEnrolledInCourse(String)`
- `getTotalUnregisteredInCourse(String)`

Newly added:
- `getSectionForCourse(String, String)`
- `getNumberOfSections(String)`
- `getNumberOfTeams(String)`
- `getCoursesDetailsListForInstructor(String, boolean)`
- `getArchivedCoursesForInstructor(String)`
- `getCourseIdToSectionNamesMap(List<CourseAttributes>)`

are not used other than in their unit tests (and sometimes in `Logic`, but not subsequently called by any action), which can be removed as well. This is what I'd like to term as "false coverage".

**Comment by boxin-yang** [comment]
functions such as

1. getCourseIdToSectionNamesMap(List<CourseAttributes>)
2. getCoursesDetailsListForInstructor(String, boolean)
3. getArchivedCoursesForInstructor (String)
4. getSectionForCourse(String, String)

Are used in Logic.java use well and I deleted their corresponding methods. I ran local test and it passes so I guess it is not a problem right
