### ISSUE TITLE
New contributor self intro [Thenaesh Elango]

### ISSUE THREAD

**Issue by thenaesh** [TEAMMATES/teammates#6381]
a) [teammates-thenaesh.appspot.com](https://teammates-thenaesh.appspot.com)
b) [github.com/thenaesh/teammates](https://github.com/thenaesh/teammates)
c) Changed two buttons on the index page to use bootstrap instead of images:
**new**
![teammates](https://cloud.githubusercontent.com/assets/9165895/22039017/7dda8c7c-dd38-11e6-8e7f-5ad119b72324.png)
**old**
![teammates_old](https://cloud.githubusercontent.com/assets/9165895/22039022/80767388-dd38-11e6-9f31-74e0ee8ad3fa.png)

d) Hi, I'm Thenaesh and I'll be contributing to TEAMMATES as part of CS3281/2!

**Comment by junhaoyap** [comment]
@thenaesh, welcome to TEAMMATES and good job on finishing the orientation tasks and having a very obvious UI change!

I see that you will be contributing as part of CS3281/2, if you have already completed a firstTimer task, we look forward to seeing your contributions to the higher level tasks, if not it will be great if you can get your feet wet via the firstTimer issues!
