### ISSUE TITLE
New contributor self intro [Lee Yi Min]

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#6387]
a) App: http://teammates-yimin.appspot.com/index.jsp
b) Fork: https://github.com/leeyimin/teammates
c) Logo in navbar was changed to png for the non-static pages.
![tinker](https://cloud.githubusercontent.com/assets/6365864/22062327/19e504dc-ddb4-11e6-8a69-fb7e1231b036.png)
d) 
Hi, I am Yi Min.
Writing self-intro is hard,
Made haiku instead.

**Comment by junhaoyap** [comment]
@leeyimin, welcome to TEAMMATES and good job on finishing the orientation tasks!

I see that you'll be contributing as part of CS3281/2 and already have some PRs open so there isn't much else! Looking forward to more of your contributions and great job on the haiku! 👍
