### ISSUE TITLE
New contributor self intro [Shrut]

### ISSUE THREAD

**Issue by shrut1996** [TEAMMATES/teammates#6390]
a) App: http://teammates-156013.appspot.com/index.jsp
b) Fork: https://github.com/shrut1996/teammates
c) A slight change in the fonts and layout of the 'About Us' Page.

Before:
  
![screenshot from 2017-01-18 22-26-45](https://cloud.githubusercontent.com/assets/20799404/22074633/fe8f4ea2-ddce-11e6-8442-1333f567f4f9.png)

After:

![screenshot from 2017-01-18 22-27-40](https://cloud.githubusercontent.com/assets/20799404/22074663/27a27ada-ddcf-11e6-9384-9c26d2b35237.png)

d)
Hey there ! My name is Shrut Patel, I'm a 2nd year Computer Science Student.
I have found happiness in contributing to OSS and I'm looking forward to contribute to TEAMMATES.

**Comment by junhaoyap** [comment]
@shrut1996, welcome to TEAMMATES and good job on finishing the orientation tasks!

I love your spirit and I hope to see you tackle a firstTimer issue so that you can get your feet wet into contributing to TEAMMATES!

**Comment by shrut1996** [comment]
Thanks a lot! I have a small problem. I hosted my local server at "localhost:8889" and i entered the admin page but I cant go further meaning the web page isn't responding ( a blank page shows up) am I missing some specific URL?

**Comment by chowyb** [comment]
@shrut1996 are there any error messages that show up in Eclipse's console?

**Comment by shrut1996** [comment]
These are the errors shown when I use the URL- http://localhost:8888/admin/adminHomePage

![screenshot from 2017-01-19 15-24-29](https://cloud.githubusercontent.com/assets/20799404/22110928/870f3846-de83-11e6-99ff-8115a0538864.png)
![screenshot from 2017-01-19 20-10-44](https://cloud.githubusercontent.com/assets/20799404/22110930/8862f8d6-de83-11e6-8d8e-329e7d5d1b3b.png)
![screenshot from 2017-01-19 20-10-55](https://cloud.githubusercontent.com/assets/20799404/22110933/8963541a-de83-11e6-9560-ed0e417992b1.png)
![screenshot from 2017-01-19 20-11-03](https://cloud.githubusercontent.com/assets/20799404/22110934/8a5f432e-de83-11e6-860a-e1bcecdcc94d.png)
![screenshot from 2017-01-19 20-11-15](https://cloud.githubusercontent.com/assets/20799404/22110935/8be50b8e-de83-11e6-93c1-2088154b60a7.png)

**Comment by ovshake** [comment]
@shrut1996 Please check your build path for which Java Version you are using. I think you are using 1.8. This project requires 1.7

**Comment by AnaghHegde** [comment]
@shrut1996 post it on the issue tracker page so that everyone can see and someone will help you with your problem.

**Comment by ovshake** [comment]
@shrut1996 Did you create the app.yaml file manually for the project for deploying?

**Comment by shrut1996** [comment]
@ovshake No I didn't create any file. I later realised that even though I had changed my Java compiler compliance to 1.7, I needed to change the eclipse.ini file.
Thanks!
