### ISSUE TITLE
Local Server is set up but unable to access the pages

### ISSUE THREAD

**Issue by shrut1996** [TEAMMATES/teammates#6395]
I'm able to start the server.
![screenshot from 2017-01-19 22-21-59](https://cloud.githubusercontent.com/assets/20799404/22116187/bea74fe8-de95-11e6-9e1c-ba48170c1e18.png)

But once I enter the URL -  "localhost:8888/admin/adminHomePage" or any other nothing shows up but instead I am getting these errors in the eclipse console.
![screenshot from 2017-01-19 15-24-29](https://cloud.githubusercontent.com/assets/20799404/22116090/6b413ff8-de95-11e6-90ed-3271286c7079.png)
![screenshot from 2017-01-19 20-10-44](https://cloud.githubusercontent.com/assets/20799404/22116094/6e4adbe6-de95-11e6-87ef-064cccb51aa4.png)
![screenshot from 2017-01-19 20-10-55](https://cloud.githubusercontent.com/assets/20799404/22116096/6f6fb6b8-de95-11e6-8f1c-10ddb4f0cf8d.png)
![screenshot from 2017-01-19 20-11-03](https://cloud.githubusercontent.com/assets/20799404/22116108/75b0ecfe-de95-11e6-8e4f-59559acc27cd.png)
![screenshot from 2017-01-19 20-11-15](https://cloud.githubusercontent.com/assets/20799404/22116110/76c83124-de95-11e6-8f5f-a257607a5895.png)
 
I have even changed the java compiler compliance to 1.7.

![screenshot from 2017-01-19 22-24-38](https://cloud.githubusercontent.com/assets/20799404/22116312/1a1f2486-de96-11e6-957e-204381d1e449.png)

Thanks!

**Comment by xpdavid** [comment]
![39f8096e-7d86-4144-ab5c-91181230d338](https://cloud.githubusercontent.com/assets/13977235/22117124/c0e16254-dead-11e6-9897-1f3228a23697.png)
You may need to check your JVM version. Currently the image shows it is 1.8.

**Comment by shrut1996** [comment]
I've Changed it but still the same problem.

![screenshot from 2017-01-19 23-05-21](https://cloud.githubusercontent.com/assets/20799404/22117969/f27873fa-de9b-11e6-9e93-11910a64c859.png)
![screenshot from 2017-01-19 23-05-37](https://cloud.githubusercontent.com/assets/20799404/22117970/f31cd21a-de9b-11e6-8cf9-2a1b941c71f5.png)

This is the page I get "localhost:8888/errorPage.jsp" with any page I search for.
![screenshot from 2017-01-19 23-05-54](https://cloud.githubusercontent.com/assets/20799404/22117973/f41ed78a-de9b-11e6-91a0-c8a2dce6dd77.png)

Thanks!!

**Comment by shrut1996** [comment]
@xpdavid Thanks a lot. It is working now because I had added the JRE file instead of the JDK file.

**Comment by damithc** [comment]
Thanks for the help @xpdavid
