### ISSUE TITLE
Failed Travis Tests

### ISSUE THREAD

**Issue by shrut1996** [TEAMMATES/teammates#6401]
I ran the Travis tests and I've been getting failures in these tests specifically:
1) Sequential UI tests
2) Occasional tests  
3) Parallel UI tests 
4) Rare tests

I had Firefox 50.1 which I uninstalled and then I downloaded Firefox 45.0 but still I got the same error in fact it couldn't even connect to Firefox then. 
I also tried by re-installing TestNG.
Is there any alternative?
Thanks !

**Comment by chowyb** [comment]
Hi @shrut1996,

What errors are shown in the Eclipse console?

**Comment by shrut1996** [comment]
Hey there, I ran the failed tests and I'm getting connection refused

![screenshot from 2017-01-20 16-34-47](https://cloud.githubusercontent.com/assets/20799404/22147400/6c753494-df2e-11e6-9c0c-6256eabd7429.png)

Now I also tried using Chrome and even changed the test.properties files by changing the chromedriver path but still the same error.

![screenshot from 2017-01-20 16-38-22](https://cloud.githubusercontent.com/assets/20799404/22147509/e3d14c80-df2e-11e6-93ed-ff0a0ada1160.png)

**Comment by chowyb** [comment]
@shrut1996 was the dev server running at the time you were running the tests?

**Comment by shrut1996** [comment]
No @chowyb it wasn't.

**Comment by chowyb** [comment]
@shrut1996 for the tests to work, the dev server should be running at the same time. The tests will use Firefox/Chrome (whichever was chosen) to connect to the dev server (which should be running already) and perform automated input and HTML comparisons on the browser to simulate user input and expected results.

**Comment by shrut1996** [comment]
@chowyb Brilliant ! Almost all tests pass now. Thanks for the help :)

**Comment by chowyb** [comment]
@shrut1996 👍, although I am concerned as to why "almost all" tests pass now instead of "all".

**Comment by shrut1996** [comment]
@chowyb I'm getting failed tests for the "AdminHomePageUITest" and "InstructorFeebackResultsPageUITests"

![screenshot from 2017-01-21 16-14-38](https://cloud.githubusercontent.com/assets/20799404/22173863/c25f8f14-dff4-11e6-9025-0fcaeabf92ed.png)

I'm having a look at it though. Thanks!

**Comment by shrut1996** [comment]
@chowyb Is it fine if my AllJsTests.java passes but these two mentioned don't?

**Comment by chowyb** [comment]
@shrut1996 no, all tests should pass locally.

@wkurniawan07 would you happen to know the issue here? The screenshot seems to suggest an error when attempting to access some local service (perhaps emails, going by the `MailService` and `TaskQueue`).

**Comment by shrut1996** [comment]
@chowyb  @wkurniawan07 It turned out that I had a couple of corrupted files so I cloned this repo again and no longer got the "AdminHomePageUITest" failure but still have the "InstructorFeebackResultsPageUITests" failed test.

![screenshot from 2017-01-22 17-54-57](https://cloud.githubusercontent.com/assets/20799404/22182491/f333761e-e0cb-11e6-8027-166d3dcef57a.png)

**Comment by wkurniawan07** [comment]
@shrut1996 -- can you post the full stack trace of the failure? The one shown on the bottom right of the screen; "org.openqa.selenium...Driver info: org.openqa.selenium.chrome.ChromeDriver".

**Comment by shrut1996** [comment]
@wkurniawan07 

![screenshot from 2017-01-22 22-04-59](https://cloud.githubusercontent.com/assets/20799404/22183925/ed9c1d78-e0ee-11e6-846f-ab80c8a4bfcb.png)

**Comment by junhaoyap** [comment]
@shrut1996 could you also zero in on the specific test that is failing and locate which line is causing the failure? We know that it is a Selenium error, specifically it being unable to find a certain element and knowing which line is throwing the error might give us more information and hints

**Comment by shrut1996** [comment]
![screenshot from 2017-01-24 14-28-54](https://cloud.githubusercontent.com/assets/20799404/22240490/76e4faac-e241-11e6-9dfe-ccee3f4691c2.png)

Is this is what you're looking for?

**Comment by junhaoyap** [comment]
Somewhere deeper down the trace, exactly which method and which line

**Comment by shrut1996** [comment]
It is the testDownloadAction method can't find the line

![screenshot from 2017-01-24 15-34-09](https://cloud.githubusercontent.com/assets/20799404/22242766/a3e0280c-e24a-11e6-9e7d-e5b628bd1377.png)

**Comment by shrut1996** [comment]
All these methods (lines 720-790) are throwing the errors.


![screenshot from 2017-01-24 15-43-23](https://cloud.githubusercontent.com/assets/20799404/22243116/f4b52be6-e24b-11e6-95b7-b2206b24bec8.png)

![screenshot from 2017-01-24 15-43-27](https://cloud.githubusercontent.com/assets/20799404/22243119/fdfba98c-e24b-11e6-928f-57ca47ae4877.png)

**Comment by junhaoyap** [comment]
It says that there is an assertion error in one of the screenshots, try to investigate what is different

**Comment by shrut1996** [comment]
Apart from "<actual>" and "<expected" the only difference is : 


![screenshot from 2017-01-24 16-11-12](https://cloud.githubusercontent.com/assets/20799404/22243998/cf6d8384-e24f-11e6-9f6d-5da5dcc2d32f.png)

**Comment by yash2o1o** [comment]
@junhaoyap @wkurniawan07 @chowyb  hey, i am also getting failed travis test in the following when ran on travis.ci.org:

![fail1](https://cloud.githubusercontent.com/assets/19612017/22285895/68c27f80-e313-11e6-89ed-953a0791257b.png)
![fail2](https://cloud.githubusercontent.com/assets/19612017/22285893/68beb3e6-e313-11e6-85c5-91d0997b660b.png)
![fail3](https://cloud.githubusercontent.com/assets/19612017/22285894/68c15218-e313-11e6-8991-3af5b607660b.png)

and also in InstructorFeedbackResultsPageUiTest in eclipse but not on travis.ci.org.

**Comment by junhaoyap** [comment]
@shrut1996 in cases like that, we would usually do a search for the difference to narrow down on the culprit, it is entirely possible you have found a test that isn't stable - find the entity generating that fragment and see if you can find the one responsible for adding the empty when it should not and why

**Comment by junhaoyap** [comment]
@yash2o1o it seems you have a different set of failing tests from @shrut1996, is that part of a pull request? If you ran it on your own machine, what is the result?

**Comment by shrut1996** [comment]
@junhaoyap But this test class is passing in the travis.ci.org

**Comment by junhaoyap** [comment]
@shrut1996 I am not sure why I don't see the newest comment, maybe you deleted it by accident as I see it on my email

The thing about CI versus local machines is that there could be configuration differences and they could be causing differing experiences and such so if there is indeed such a configuration difference we want to find it

**Comment by shrut1996** [comment]
@junhaoyap Yes I thought so. There must definitely be a configuration difference . Do you reckon I might find this difference in the test where I'm getting the assertion error?

**Comment by junhaoyap** [comment]
@shrut1996 I'm not so sure, this is the first time we're seeing such an error as a team :s @wkurniawan07 any help here?

**Comment by wkurniawan07** [comment]
Apologies, this missed my radar.

Those failures actually look familiar. They occur from time to time on the _first_ test run, but always gets resolved in subsequent runs (which consists only the failing tests of the previous run). @shrut1996 Do the failures persist to the point that it marks the build as failure?

**Comment by shrut1996** [comment]
@wkurniawan07 This test fails even in the subsequent runs of the failing tests but there is NO problem with the build, the project is built successfully. However as I mentioned above this test passes when ran on the Travis CI.
Thanks (Y)
