### ISSUE TITLE
New contributor self intro [Yash]

### ISSUE THREAD

**Issue by yash2o1o** [TEAMMATES/teammates#6404]
1. App:  https://teammates-yash.appspot.com/
2. Fork: https://github.com/yash2o1o/teammates
3. 
![team](https://cloud.githubusercontent.com/assets/19612017/22148765/0ccd12c0-df36-11e6-8ccb-b791ee269f39.png)

I changed color of the text (student peer ....) using bootstrap.

My name is Yash Patel. I am excited to contribute to open source.

**Comment by junhaoyap** [comment]
@yash2o1o, Welcome to TEAMMATES! Good job on going through with the introductory steps!

I see that you are excited to contribute to open source, what is your motivation for that? In the mean time, I will recommend that you start with a first timer issue that you can find to get your feet wet!

**Comment by yash2o1o** [comment]
@junhaoyap, Thank you.
I was really interested in how real world projects actually work and i must say i am really fascinated by the sheer amount of work that goes behind it. And i also wish to take part in GSOC.

**Comment by junhaoyap** [comment]
@yash2o1o the scale will be massively different from that of schools or pet projects for sure!
