### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by allevy3** [TEAMMATES/teammates#6415]
I am attempting to set up the development environment on my computer.

I have run ./gradlew appengineDownloadSdk and ./gradlew setup

Results for ./gradlew setup

:createConfigs
:createLaunches
:eclipseProject
:setup
BUILD SUCCESSFUL
Total time: 5.82 secs

However after downloading the google tools for eclipse I get the following error when attempting to point it at the android SDK.

"Could not find folder 'tools' ...SDK 'C:\Users\Alex\.gradle\'."

**Comment by chowyb** [comment]
@allevy3 you will need to point it at the appengine folder itself, so the last folder in your path should be `appengine-java-sdk-1.9.27`.

Also, the path in your issue `C:\Users\Alex.gradle` appears to be a little off, it should probably look like `C:\Users\Alex\.gradle` instead.

**Comment by allevy3** [comment]
Thank you. Your information was useful to solving the problem.
