### ISSUE TITLE
Need Help on failing test 

### ISSUE THREAD

**Issue by DIL8654** [TEAMMATES/teammates#6429]
Hi All,

Thanks for your comments related to #6323  and tried all those and finally only 2 test cases are fails now.

1. I am not sure why google drive always showing in my local language when opens google doc.
even I make remember by google login, but when test runs, it is not using my google account to open the shared document.

2. I am not sure why failing test for TaskQueuesLogicTest.java:66 in attached screenshot.

Herewith I have attached screenshot. your suggestions are appreciate.

Sorry for the inactivity, it was because of I had to move to new place. :)

Regards,
Dilanka

<img width="1425" alt="test_fails" src="https://cloud.githubusercontent.com/assets/10825139/22184227/9a0779e6-e0f3-11e6-97f0-5d0d0b88e136.png">

**Comment by chowyb** [comment]
@DIL8654 this seems to be an issue with the test itself, as it assumes the language in your region is English. This is brought up in a previous issue (#6049), but it has not been fixed yet.

**Comment by DIL8654** [comment]
@chowyb thanks for the comment, I will ignore that test for now.

**Comment by junhaoyap** [comment]
@DIL8654 closing this for now, if this issue keeps cropping up we will see if we need to up the priority of the issue that has already been reported, cc @damithc

**Comment by damithc** [comment]
@junhaoyap upped the priority of the said issue #6049.
