### ISSUE TITLE
Edit responses: sort by recipient name

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6433]
When editing responses where there are multiple recipients (e.g. recipients are students of the course), the responses should be sorted by name. The current one doesn't seem to be sorted (see screenshot).

![image](https://cloud.githubusercontent.com/assets/1673303/22238767/2b60c40a-e24e-11e6-8aab-cbd4afe598e8.png)

**Comment by Mynk96** [comment]
@damithc I am not able to reproduce unsorted responses, everytime I am getting sorted result. Can you please elaborate more on this issue?

**Comment by damithc** [comment]
Seem to be fixed. Closing.
