### ISSUE TITLE
Remove unused parameter in StudentProfilePage.java

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6439]
In `teammates.test.pageobjects.StudentProfilePage#editProfileThroughUi`, the first parameter `fileName` is not used and thus can be removed.

**Comment by PratyushTalreja** [comment]
I am done making changes to the required file.

**Comment by wkurniawan07** [comment]
@PratyushTalreja welcome and thanks for your interest in contributing to TEAMMATES!
It's great that you have solved this issue! The next step is to open a PR, the details can be found out in our [workflow document](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md).
I also observed that you have expressed interest in a number of other issues. Unfortunately, all of them are labelled `d.FirstTimers` and any contributor is limited to one such issue.

**Comment by PratyushTalreja** [comment]
@wkurniawan07 Thank you for the warm welcome. I have made a pull request for this issue. For the other d.FirstTimers, I got your point and I will check for other issues. Thank you once again.
