### ISSUE TITLE
Remove unused parameter in FeedbackQuestionsLogic.java

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6440]
In `teammates.logic.core.FeedbackQuestionsLogic#copyFeedbackQuestion`, the first two parameters `oldCourseId` and `oldFeedbackSessionName` are not used and thus can be removed.

**Comment by ablyx** [comment]
I'll fix this in #6436

**Comment by damithc** [comment]
> I'll fix this in #6436

Don't fix multiple issues in one PR unless there is a strong justification.

**Comment by ablyx** [comment]
Ok, but this issue can be part of #6435 which #6436 fixes. What's the best way to do this?

**Comment by damithc** [comment]
> Ok, but this issue can be part of #6435 which #6436 fixes. What's the best way to do this?

@ablyx If you _cannot_ do #6436 without fixing this issue, then it's fine to do both in the same PR. Otherwise leave this one alone because we are running out of firstTimer issues anyway.

**Comment by ablyx** [comment]
Alright then, I'll leave this untouched!
