### ISSUE TITLE
ActivityLogEntry should not have dependency to GateKeeper

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6442]
`ActivityLogEntry` is a utility class which should not have any business with `GateKeeper`, an API logic class.

**Comment by AnaghHegde** [comment]
@wkurniawan07 I am interested on this. Can i work on this ?. 
Correct me if i am wrong. You want to move this to utility class from API lgoic class?.

**Comment by xpdavid** [comment]
@AnaghHegde Note really. 
`ActivityLogEntry` has import `import teammates.logic.api.GateKeeper;` and use it in
```
UserType userType = new GateKeeper().getCurrentUser();
googleId = userType == null ? "Unknown" : userType.id;
```
`ActivityLogEntry` is a utility class and should not depends on the `GateKeeper` which relate to the logic part in the App.

**Comment by AnaghHegde** [comment]
@xpdavid 
>ActivityLogEntry has import import teammates.logic.api.GateKeeper; and use it in

What do you mean by use it in ?.I m still having the confusion.

**Comment by xpdavid** [comment]
check this line in `ActivityLogEntry`
``` java
UserType userType = new GateKeeper().getCurrentUser();
```
This is the usage of `GateKeeper`

**Comment by AnaghHegde** [comment]
@xpdavid I got that. I m still confused about the issue only. Do i need to remove that dependency and make it work ?.
