### ISSUE TITLE
Minor error under "No signup required for students" writeup in features.jsp

### ISSUE THREAD

**Issue by JosephineKwa** [TEAMMATES/teammates#6456]
At `...unique links TEAMMATES email them...`, `email` should be changed to `emails`

**Comment by PratyushTalreja** [comment]
I am interested in this.

**Comment by nikiforosbotis** [comment]
@JosephineKwa Can I take over that? Or is it done?

**Comment by JosephineKwa** [comment]
@nikiforosbotis yes it is still available, go ahead and fix it.
