### ISSUE TITLE
Minor error under "Bug reports and feature requests" in contact.jsp

### ISSUE THREAD

**Issue by JosephineKwa** [TEAMMATES/teammates#6458]
Change `...submitted to above email address.` to `...submitted to the above email address.`

**Comment by shivanshsoni** [comment]
I solved this issue already.. you can see my commit above

**Comment by JosephineKwa** [comment]
Hi @shivanshsoni, go ahead and create a PR for your fix. Remember to refer to the [guidelines](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md) on the conventions to follow.
