### ISSUE TITLE
Unable to see some of the files in eclipse after importing project into workspace

### ISSUE THREAD

**Issue by AnaghHegde** [TEAMMATES/teammates#6468]
Today i was having some os problem , so again from the scratch i setup my local environment. Everything is working fine(even the test) except that some of the files were not visible in the eclipse.I have attached screenshot below 

![screenshot from 2017-01-26 22-40-10](https://cloud.githubusercontent.com/assets/12005551/22342598/ed43de4a-e41a-11e6-88ab-e2ce633465d7.png)

Take a look at the image the, directory **java** and **main** is not visible in eclipse but they are present in the project root directory.
I am using Ubuntu 16.04.

**Comment by junhaoyap** [comment]
@AnaghHegde on the left, we see a folder with ```src/main/java```, when you expand that, is it empty?

**Comment by AnaghHegde** [comment]
@junhaoyap No. It contains all the necessary files. Only the bottom one doesn't show the files.I tried googling about the error but no luck.

**Comment by wkurniawan07** [comment]
I don't use Linux, but my guess is that _is_ the default behaviour in Linux.
Anyway, as long as the necessary files are accessible, all should be well. Closing the issue.
