### ISSUE TITLE
Instructor: edit student: delete outdated responses when moving student to another section

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6470]
Moving a student from a team in one section to a team in another section is supposed to delete responses given to, and received from, members of the previous team. However, there are cases where this did not happen in the live server.

**Comment by junhaoyap** [comment]
Just to be sure, it happens only on certain cases and not all cases?

**Comment by xpdavid** [comment]
The API for update of student has been rewritten. Need to investigate whether it is still the case.

**Comment by wkurniawan07** [comment]
No longer happening
