### ISSUE TITLE
New contributor self intro Anirudh

### ISSUE THREAD

**Issue by sponde25** [TEAMMATES/teammates#6479]
App: http://4-18-dot-teammates-sponde25.appspot.com/index.jsp
Fork: https://github.com/sponde25/teammates/tree/tinker
I underlined the important lines in terms of use page. Not much, but baby steps.
Before:
![screenshot 21](https://cloud.githubusercontent.com/assets/9167391/22369090/00fe1d8e-e4b0-11e6-8f8a-8a9723a359f5.png)
After:
![screenshot 23](https://cloud.githubusercontent.com/assets/9167391/22369101/0d916222-e4b0-11e6-9c5e-0868bf81db83.png)
Hi, I am Anirudh Jain from IIT(ISM), Dhanbad. I have trying to get into Open Source development and finally decided to take the leap.

**Comment by junhaoyap** [comment]
@sponde25, Welcome to TEAMMATES! Great job on what seems to be like your first try into OSS development!

I will recommend that you start with a first timer issue that you can find to get your feet wet, we do have quite a lot opened recently and they do get snagged up pretty quickly so I advise you to start as soon as possible :)
