### ISSUE TITLE
Make frontpage responsive

### ISSUE THREAD

**Issue by li-kai** [TEAMMATES/teammates#6487]
With almost half of google's search traffic coming from mobiles, it's time to make the front page responsive.

**Comment by yash2o1o** [comment]
@li-kai do we have to do it using bootstarp? If yes, then I would like to give it a try.

**Comment by wkurniawan07** [comment]
@yash2o1o this issue is already being worked on. Perhaps you can try working on something else?

**Comment by yash2o1o** [comment]
@wkurniawan07  great. I will try some other issue.
