### ISSUE TITLE
Refactor getParticipantListFromParams(String) method in *action classes

### ISSUE THREAD

**Issue by AnaghHegde** [TEAMMATES/teammates#6490]
InstructorFeedbackQuestionAddAction and InstructorFeedbackQuestionVisibilityMessageAction and InstructorFeedbackQuestionEditAction  have implementations of `getParticipantListFromParams(String)` which are almost completely identical.

**Comment by damithc** [comment]
`Refractor` -> `Refactor`

**Comment by AnaghHegde** [comment]
Can some one add the labels to the issue please.

**Comment by damithc** [comment]
@wkurniawan07 please have a look when you have time and validate/prioritize as necessary.

@AnaghHegde OSS projects are often manned by volunteers who have other day jobs. Sometimes things take some time to progress.

**Comment by AnaghHegde** [comment]
@damithc I am sorry.I didn't mean it. Since i have already submitted a PR i just wanted to confirm if it comes under `d.Contributors` issue.

**Comment by damithc** [comment]
> Since i have already submitted a PR i just wanted to confirm if it comes under d.Contributors issue.

@AnaghHegde it's fine.

**Comment by AnaghHegde** [comment]
@wkurniawan07 I have found some other methods which comes under refactoring only. Shall i open a new issue or i just need to add them to this issue only ?
