### ISSUE TITLE
HTML not sanitized in the admin home page

### ISSUE THREAD

**Issue by thenaesh** [TEAMMATES/teammates#6492]
There are some parts of `adminHome.js` and the associated AJAX handler `AdminInstructorAccountAddAction.java` that construct HTML strings for insertion into the DOM, and concatenate user input into it without sanitizing.

The result is things like this occurring:
![teammates_script_injection_bold_attempt_and_success](https://cloud.githubusercontent.com/assets/9165895/22418125/88df4f7a-e712-11e6-94a2-87224d41e521.png)
![teammates_script_injection_alert_success](https://cloud.githubusercontent.com/assets/9165895/22418130/8d131572-e712-11e6-9b7e-9c8f540c8bff.png)

This seems more like a cosmetic issue than an actual security issue, though, since the admin using this page is assumed to be trusted.

**Comment by boxin-yang** [comment]
Wonder if this is necessary as this page is only viewed by the admin
