### ISSUE TITLE
Wrong usage of Inheritance in *action classes

### ISSUE THREAD

**Issue by AnaghHegde** [TEAMMATES/teammates#6498]
The following 4 classes extends `FeedbackSubmissionEditPageAction`

1.InstructorFeedbackSubmissionEditPageAction 

2.InstructorFeedbackSubmissionEditSaveAction 

3.StudentFeedbackSubmissionEditSaveAction  

4.StudentFeedbackSubmissionEditPageAction 

And InstructorFeedbackRemindAction extends `InstructorFeedbacksPageAction`.

 This is wrong usage of inheritance. As only Action and *AbstractAction can be extended.

**Comment by wkurniawan07** [comment]
- The first four are incorrect. Notice that `FeedbackSubmissionEditPageAction` and `FeedbackSubmissionEditSaveAction` are `abstract` classes. You're welcome to rename those classes to mention `*AbstractAction`, but not required, as the fact that the class names are not prefixed with `Instructor-` or `Student-` is already a certificate of their `abstract`-ness.
- The one on `InstructorFeedbackRemindAction` is correct.
- There are two other violations of this so-called "rule". See if you can figure them out.

**Comment by AnaghHegde** [comment]
@wkurniawan07 `InstructorFeedbackRemindAction` class even-though extends `InstructorFeedbacksPageAction` its not using any of the features of `InstructorFeedbacksPageAction` class.

**Comment by AnaghHegde** [comment]
@wkurniawan07 what else i am missing?. I m not able to find anything else other than above mentioned.

**Comment by wkurniawan07** [comment]
@AnaghHegde In case of communication barrier, when I say "... are correct", I meant that your claim is correct, i.e. the classes that you mentioned use inheritance wrongly.
The other two classes are `InstructorCourseDeleteAction` and `InstructorCourseStudentDeleteAction`. You should be able to figure out why easily.

**Comment by AnaghHegde** [comment]
@wkurniawan07 
>There are two other violations of this so-called "rule". See if you can figure them out.

I was thinking it has to something to do with the `InstructorFeedbackRemindAction`.My mistake.

>The other two classes are `InstructorCourseDeleteAction` and `InstructorCourseStudentDeleteAction`.

Again these extend `InstructorCoursesPageAction` which is similar to `InstructorFeedbacksPageAction` .
