### ISSUE TITLE
PSA: regenerate some of your launch files

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6500]
Greetings to all active developers/contributors,

If you have been using the provided launch configurations for running tests in Eclipse, there are some changes that you need to do due to #6321. This is to be done when you sync with the latest `master` branch, commit dccb667 onwards. Follow these steps:
1. Delete the files `All tests (GodMode).launch`, `All tests.launch`, `Staging tests.launch`, and `Travis tests.launch`, all in `.launches` folder. Alternatively you can delete the entire `.launches` folder and restore the source-controlled files with `git reset --hard` afterwards.
2. Run the command `./gradlew createLaunches` or `gradlew.bat createLaunches` to obtain the new launch files.

Also, from this point onwards, we will refer the tests run in Travis CI as "CI tests" instead of "Travis tests", and analogously "CI green" instead of "Travis green".

**Comment by damithc** [comment]
I wonder if there is a better way to convey this info to relevant devs. For example, have a file that has a running list of these announcements (with dates) and mention in the troubleshooting guide to check that file if their setup breaks inexplicably.

**Comment by junhaoyap** [comment]
cc @TEAMMATES/contributors

**Comment by wkurniawan07** [comment]
@junhaoyap I don't think that's a good idea. That group was used back then when external contributors are invited to the project, which we don't do anymore, so what you just did was notifying people who haven't been involved for ~2 years 🤔
