### ISSUE TITLE
Review the need for some documentation files

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6506]
- Specs
- Resources bin
- Decision analysis
- All best practices document
- All technical reports

Based on my observations, the above documentations are either (1) very outdated, (2) not read, (3) disorganized, or (4) combination of them. Any documentation in the repo, not just the abovementioned, is a maintenance burden. Knowing that some of the mentioned traits apply, I believe not all of them are worthy of being kept.

I do not wish to undermine the efforts of the people who made those documentations, but we really need to triage these documents, find out which ones we still need, and figure out how best to present them in the repo (Google docs is very likely not the best way). Otherwise they will just be distractions (for the lack of better word): "Hey this document exists, let's read it" -> "Wait this document has not been updated since 2014, why is it still here? Are the information inside still relevant?", and this does not really speak well of the project's documentation value.

**Comment by damithc** [comment]
Most of the content in those documents are outdated. However, they contain bits of information that are not documented elsewhere and might be needed for very specific purposes if not for general consumption. I suggest we move all of them into a separate page called 'Archived docs (no longer maintained)' to avoid those questions you mentioned.

**Comment by wkurniawan07** [comment]
Marking them as outdated is one thing.

My other concern is that we actually do need some sort of documentation on our policies and decisions on most aspects of the project (sanitisation, logs, testing, devops, etc.), otherwise they will be lost in time (which is what is happening now!). While code comments and header comments help to explain some things, bigger pictures such as why things are done in certain way in the entire project (as opposed in a certain class) cannot be contained in a class-level documentation.

I have to concede that I am really guilty of making many policies without properly documenting them somewhere. Take this as my attempt to absolve some of these guilt.

Concrete plan: make a `policies/` sub-directory in the `docs` folder`, populate it, and maintain it. We'll start with existing documents such as `dependencies.md`, `emails.md`, `staticAnalysis.md`.

**Comment by damithc** [comment]
Yes, go ahead and document those policies worth documenting. If anything from the outdated docs are relevant, just copy paste into new docs. If the documented policies are general enough, they can be moved to oss-generics later.
