### ISSUE TITLE
Use enum instead of string for status message colors

### ISSUE THREAD

**Issue by Neurrone** [TEAMMATES/teammates#6512]
StatusMessage's constructor currently takes in an enum for the color, but stores and exposes it as a string instead.

**Comment by PratyushTalreja** [comment]
Can you please elaborate a bit on this bug? I am interested.

**Comment by Neurrone** [comment]
I think it would be better if the enum was used consistently. I listed this mainly for completeness, as it would be tedious to change.

**Comment by PratyushTalreja** [comment]
@Neurrone I think manipulating enum value dynamically is not possible.

**Comment by Neurrone** [comment]
@PratyushTalreja what do you mean dynamically manipulate?
