### ISSUE TITLE
InstructorCourseRemindAction: extractUserName may not return username correctly

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#6513]
The current implementation extracts the username from the email content and cuts off at the first comma, possibly returning the names of students incorrectly. If sanization is applied to the username in the email, eg. in #6454, desanitization would be required, which is additional work.

**Comment by damithc** [comment]
@leeyimin what is the impact of this issue? Some emails containing only part of the receiver name? or some emails not going out at all?

**Comment by leeyimin** [comment]
@damithc I think it is a minor issue that just affects the Action log message.
