### ISSUE TITLE
Templates: refactor populateTemplate()

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#6515]
In Templates utility class, populateTemplate accepts varargs of alternating key and value strings to do population of the fields in templates. A more defensive way is to use Map to replace the varargs, as suggested by @ablyx. 
I also propose to have a new method populateTemplateWithSanization to sanitize the values before populating the fields with them. The use of sanitization is usually embedded within the method call of populateTemplate and it can be difficult to know which fields are sanitized in a quick glance. The need for it might be diminished though if using a Map is sufficiently clear.

**Comment by wkurniawan07** [comment]
Someone has unsuccessfully tried it before: #5342. Of course, it might be faults in his attempts rather than this being inherently not doable.

**Comment by Labirinto** [comment]
I've refactored the code. Could you please review it?

**Comment by xpdavid** [comment]
Actually, after V7, there are only limited places where the method is used. It would easier to do the refactor. In addition, we could employee more robust template engine to do the job.

**Comment by wkurniawan07** [comment]
Closing as this is not a priority right now
