### ISSUE TITLE
Refactor StringHelper and Sanitizer class

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#6518]
Certain methods in Sanitizer are more suitable in StringHelper. (eg. removeNonAscii, trimIfNotNull, etc)

New Desanitization class:
There exists two methods in StringHelper which recovers string from sanitized html and another method in Sanitizer to desanitize url for NEXT_URL. It may not be clear to users wishing to use such functions where exactly to find them.

**Comment by wkurniawan07** [comment]
If I may suggest, rename the `Sanitizer` to `SanitizationUtils` or `SanitizationHelper` instead, and make it such that the sanitizing and desanitizing methods of the same topic appear back to back.
```java
public class SanitizationUtils {
    
    public static String sanitizeForHtml(String htmlUnsanitizedString) {
        ...
    }
    
    public static String desanitizeFromHtmlSanitized(String htmlSanitizedString) {
        ...
    }
    
    // all other sanitization methods organized similarly
    
}
```
This way you are more sure that when you implement a sanitizing method, you also implement its desanitizing counterpart, and it becomes easier to compare those two side-by-side.
