### ISSUE TITLE
Refactor magic number in InstructorCourseEnrollSaveActionTest

### ISSUE THREAD

**Issue by ablyx** [TEAMMATES/teammates#6530]
In `teammates.test.cases.action.InstructorCourseEnrollSaveActionTest#testExecuteAndPostProcess`
the variable `sizeLimitBoundary` uses the same number as `SIZE_LIMIT_PER_ENROLLMENT` in `teammates.logic.core.StudentsLogic`. 

To prevent the use of such magic numbers, `SIZE_LIMIT_PER_ENROLLMENT` should be placed in `teammates.common.util.Const` and `sizeLimitBoundary` should be called from `teammates.common.util.Const`.

**Comment by ablyx** [comment]
This is a really simple problem, should this be labeled as first timers?

**Comment by damithc** [comment]
@ablyx can be a bit more detailed in issue description and more specific in issue title? Especially if it is meant for first timers.

**Comment by ablyx** [comment]
@damithc sorry about that. This should be much clearer now.
