### ISSUE TITLE
Set up SonarQube for code quality check

### ISSUE THREAD

**Issue by samsontmr** [TEAMMATES/teammates#6535]
Continuing from the discussion in #6237, we will be using the SonarQube code quality badge.

**Comment by samsontmr** [comment]
@wkurniawan07 will we be moving to Java 8 soon? It appears that the latest version of SonarQube (which should be what web service uses) doesn't support Java 7...
Unless we want to set up our own SonarQube server to run an older version.

**Comment by damithc** [comment]
> will we be moving to Java 8 soon?

Not sure. We have to wait till App Engine supports it.

> SonarQube (which should be what web service uses) doesn't support Java 7...

That's a bit strange. Isn't Java 8 backward compatible?

**Comment by samsontmr** [comment]
> That's a bit strange. Isn't Java 8 backward compatible?

Yeah that's what I thought, but it seems like [it's not the case here](https://blog.sonarsource.com/sonar-ecosystem-upgrades-to-java-8/). I'm getting an [Unsupported major.minor version 52.0](http://stackoverflow.com/questions/37686144/java-lang-unsupportedclassversionerror-org-sonar-batch-bootstrapper-environment) error in the build when sonarqube tries to run.

**Comment by wkurniawan07** [comment]
> That's a bit strange. Isn't Java 8 backward compatible?

This is not the issue. SonarQube _itself_ requires Java 8 runtime to run, but the VM we use for Travis CI is configured with Java 7.
If TEAMMATES is to use any Java 8 library, we would expect the same error.

**Comment by damithc** [comment]
> This is not the issue. SonarQube itself requires Java 8 runtime to run, but the VM we use for Travis CI is configured with Java 7.

I see. TEAMMATES cannot use Java 8 VM? If cannot, we have to put SonarCube on hold until GAE gains Java 8 compatibility.

**Comment by damithc** [comment]
These guys claim to offer a free hosted SonarCube for OSS projects. https://www.sonarsource.com

**Comment by wkurniawan07** [comment]
No longer on hold since Java 8 migration is done.

**Comment by wkurniawan07** [comment]
@tshradheya you can try first and see where it goes.
