### ISSUE TITLE
New contributor self intro iamhunter

### ISSUE THREAD

**Issue by iamhunter** [TEAMMATES/teammates#6539]
My App: http://teammates-iamhunter.appspot.com/
My Fork: https://github.com/iamhunter/teammates

My Changes: I changed the font of the main caption, replaced the "/" with "and", and I linked "more..." to the features page.
<img width="1680" alt="screen shot 2017-02-03 at 1 29 15 pm" src="https://cloud.githubusercontent.com/assets/12401866/22603308/d6fb8bf6-ea14-11e6-85b4-c17209fc54f6.png">

<img width="1680" alt="screen shot 2017-02-03 at 1 29 29 pm" src="https://cloud.githubusercontent.com/assets/12401866/22603309/d7073c26-ea14-11e6-877f-4ef3f452fd1d.png">

Intro: My name is Andrew Hunter and I am a Computer Information Systems major at Clemson University in South Carolina.  I am very excited to start working on teammates and open-source in general because it will introduce me to a much larger scale of projects than I am used to with my school projects.

**Comment by junhaoyap** [comment]
@iamhunter, Welcome to TEAMMATES! Great job!

I will recommend that you start with a first timer issue that you can find to get your feet wet to get started and I am looking forward to seeing your contributions to open source and TEAMMATES!
