### ISSUE TITLE
Doubt in the Contribution oriented guide

### ISSUE THREAD

**Issue by kishankhakhar** [TEAMMATES/teammates#6541]
What is to be done in the 2nd step in Set up Locally?
The line is as follows:

Get Travis green / Local CI green and dev green. It is OK to proceed to the next phase if you have fewer than 5 failing test cases.

Help asap

**Comment by AnaghHegde** [comment]
@kishankhakhar I presume that you have successfully completed all the previous steps.

>Get Travis green / Local CI green and dev green. It is OK to proceed to the next phase if you have fewer than 5 failing test cases.

May be thsi[](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md) will help you.
