### ISSUE TITLE
Feature Request: Remove white-space on right side of top banner

### ISSUE THREAD

**Issue by iamhunter** [TEAMMATES/teammates#6542]
Proposed Feature / Enhancement
Force the header to a min-width of 1000px.

I have a working example of it here: http://teammates-iamhunter.appspot.com/

I will create a PR if this gets approved

Problem it solves
On mobile, there is some white space on the right of the top banner
On the web, when the width of the window gets smaller than 1000px, background of the banner continues to decrease with size, but the page stays at 1000px, resulting in white space when someone scrolls to the right to reach the login buttons

<img width="877" alt="screen shot 2017-02-04 at 5 48 48 pm" src="https://cloud.githubusercontent.com/assets/12401866/22622212/995daaf6-eb02-11e6-8ec4-7d0ba1680645.png">
<img width="636" alt="screen shot 2017-02-04 at 5 49 18 pm" src="https://cloud.githubusercontent.com/assets/12401866/22622213/996006a2-eb02-11e6-8b82-b35d3ef14f72.png">

**Comment by damithc** [comment]
@li-kai any relation to #6488?

**Comment by li-kai** [comment]
@damithc Yep, the responsive version will avoid this problem.

**Comment by damithc** [comment]
@iamhunter thanks for the issue. 👍 It is a valid issue but currently being covered in another ongoing PR.
