### ISSUE TITLE
Refactor FeedbackSessionsLogic

### ISSUE THREAD

**Issue by samsontmr** [TEAMMATES/teammates#6545]
Some methods, like `getFeedbackSessionResultsForUserWithParams` (236 lines!!!) are extremely long and could be broken up to be more readable.

**Comment by damithc** [comment]
Need to ensure it has near 100% code coverage before refactoring. If it doesn't, may have to increase coverage first as a separate issue.

**Comment by samsontmr** [comment]
Speaking of coverage, didn't we have a coverage bot some time ago?

**Comment by wkurniawan07** [comment]
I made a special issue for that method: #6576. Can use this issue for smaller but nevertheless need-to-refactor methods.

**Comment by sujeet14108** [comment]
How to check if it has 100% code coverage ?

**Comment by chowyb** [comment]
@sujeet14108 from a comment on another issue [here](https://github.com/TEAMMATES/teammates/issues/6563#issuecomment-278284773), you can use EclEmma to check for code coverage.

**Comment by sujeet14108** [comment]
![screenshot from 2017-06-03 00-52-28](https://cloud.githubusercontent.com/assets/9781422/26741556/705a8e56-47f7-11e7-9e43-05bb123410bb.png)

**Comment by damithc** [comment]
> Here is EclEmma output

If you are refactoring methods not covered by tests, you may want to add tests first (as a separate issue). Not applicable to cosmetic and minor refactorings such as changing comments or renaming.

**Comment by emilppp** [comment]
We're a group at KTH (https://www.kth.se/en) and want to look into this

**Comment by wkurniawan07** [comment]
@emilppp sure, if it qualifies for your school assignment. What exactly is required?

**Comment by emilppp** [comment]
@wkurniawan07 We might not be able to do every function in FeedbackSessionsLogic.java but we will try to tackle the longest ones. Would it be fine to break it up into new files, seeing as it is very long (above 2000 lines), or do you want to keep the file structure as it is?

**Comment by emilppp** [comment]
@wkurniawan07 Our assignment is basically to refactor something within an open-source project

**Comment by wkurniawan07** [comment]
@emilppp breaking it up into some classes may be a possible solution, but if you do it, it should be a well-thought design and not just because there are > 2000 lines (otherwise you'll run into [poltergeist anti-pattern](https://sourcemaking.com/antipatterns/poltergeists)).

**Comment by wkurniawan07** [comment]
Closing due to lack of scope.
