### ISSUE TITLE
Add FeedbackResponseCommentSearchTest to test searching for feedback response comments

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6550]
The test cases' design can follow `StudentSearchTest`.

**Comment by wkk91193** [comment]
@wkurniawan07 Using feedbackResponseCommentsDb.search() returned results that were not relevant. I had to comment out assertSameContentIgnoreOrder() checks in order for tests to pass. Is the feedbackResponseCommentsDb.search() implemented correctly?

**Comment by wkurniawan07** [comment]
@wkk91193 I will not dismiss that possibility. What test cases were you using, what did you expect and what did you get instead?

**Comment by wkk91193** [comment]
@wkurniawan07. 
I committed my changes as referenced above! 

expected:<[FeedbackResponseCommentAttributes [feedbackResponseCommentId = null, courseId = idOfTypicalCourse1, feedbackSessionName = First feedback session, feedbackQuestionId = 2, giverEmail = instructor1@course1.tmt, feedbackResponseId = 2%student2InCourse1@gmail.tmt%student1InCourse1@gmail.tmt, commentText = Instructor 1 comment to student 1 self feedback Question 2, createdAt = Sun Feb 01 23:59:00 UTC 2026, lastEditorEmail = null, lastEditedAt = null]]>

but was:<[[FeedbackResponseCommentAttributes [feedbackResponseCommentId = 17, courseId = idOfTypicalCourse1, feedbackSessionName = First feedback session, feedbackQuestionId = agR0ZXN0chYLEhBGZWVkYmFja1F1ZXN0aW9uGAEM, giverEmail = instructor1@course1.tmt, feedbackResponseId = agR0ZXN0chYLEhBGZWVkYmFja1F1ZXN0aW9uGAEM%student1InCourse1@gmail.tmt%student1InCourse1@gmail.tmt, commentText = Instructor 1 comment to student 1 self feedback, createdAt = Sun Mar 01 23:59:00 UTC 2026, lastEditorEmail = instructor1@course1.tmt, lastEditedAt = Mon Apr 02 23:59:00 UTC 2012]], [FeedbackResponseCommentAttributes [feedbackResponseCommentId = 18, courseId = idOfTypicalCourse1, feedbackSessionName = First feedback session, feedbackQuestionId = agR0ZXN0chYLEhBGZWVkYmFja1F1ZXN0aW9uGAIM, giverEmail = instructor1@course1.tmt, feedbackResponseId = agR0ZXN0chYLEhBGZWVkYmFja1F1ZXN0aW9uGAIM%student2InCourse1@gmail.tmt%student1InCourse1@gmail.tmt, commentText = Instructor 1 comment to student 1 self feedback Question 2, createdAt = Sun Feb 01 23:59:00 UTC 2026, lastEditorEmail = instructor1@course1.tmt, lastEditedAt = Sun Feb 01 23:59:00 UTC 2026]]]>

**Comment by Neurrone** [comment]
@wkk91193 please use your open PR for discussion, as its confusing to have the discussion split across 2 places.
