### ISSUE TITLE
Images used in the project are not optimized

### ISSUE THREAD

**Issue by li-kai** [TEAMMATES/teammates#6552]
All the images in [this page](https://teammatesv4.appspot.com/about.jsp) are not optimized, resulting in the user downloading nearly 3.5mb of images when visiting the page.

**Comment by wkurniawan07** [comment]
As the matter of fact, _none_ of the images used in this project are optimized 😛

But you're right that the about page has the biggest impact by far.

**Comment by li-kai** [comment]
> none of the images

I did a compression on `/images/` folder but I didn't see any good results. Some are already as optimized as they can be.

**Comment by wkurniawan07** [comment]
> Some are already as optimized as they can be.

I just [kraked](https://kraken.io/web-interface) all the images in the folder, and all but one image are optimize-able.

**Comment by li-kai** [comment]
You were right. Guess something was wrong with my settings on first parse. I'll optimize the rest.

**Comment by wkurniawan07** [comment]
Renamed the issue and PR for accuracy.
