### ISSUE TITLE
Feature Request for the Student Profile Page

### ISSUE THREAD

**Issue by shrut1996** [TEAMMATES/teammates#6556]
When a student opens his/her profile page, they get the edit mode. However I suggest we could make the profile page as it is from the Instructors' perspective and give edit options besides the fields as it is in websites like Facebook. Or else we could give a link on the page stating "View as Instructor" so that the student can see how the Instructor can see his/her profile.

**Comment by damithc** [comment]
Thanks for the suggestion @shrut1996 👍 
Although we are not likely to do this anytime soon as the profiles feature is not used a lot and the suggested enhancement is not a big improvement although nice to have.
