### ISSUE TITLE
Refactor StudentLogic::enrollStudents(String, String, boolean)

### ISSUE THREAD

**Issue by boxin-yang** [TEAMMATES/teammates#6557]
In Student Logic class, part of enrollStudents(String, String, boolean) is done repeatedly and could be optimized. 

line 304:         List<String> invalidityInfo = getInvalidityInfoInEnrollLines(enrollLines, courseId);

in calling getInvalidityInfoInEnrollLines, each line is scanned and StudentAttributesFactory makes new StudentAttributes for each line. However, the returned result is only used to check for invalid results. Once no invalid result is found, the method proceeds to use StudentAttributesFactory to makes new StudentAttributes instances, which is already done in getInvalidityInfoInEnrollLines.

I am thinking of saving the result of getInvalidityInfoInEnrollLines and if no error is found, enrollStudents method should reuse the StudentAttributes instances created in getInvalidityInfoInEnrollLines.

**Comment by damithc** [comment]
I'm not sure if it can improve the performance significantly though. i.e. whether it is worth the additional complication to the code

**Comment by boxin-yang** [comment]
Erm, I think I will discuss with you or @wkurniawan07  tmr with regards to this. Also, there are some SLAP issues within this function that might be refactored. But I will leave this for now and discuss this tmr during class :)
