### ISSUE TITLE
Suppress repetitions of getInvalidityInfo in *Attributes

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6560]
This following routine:
```java
error = validator.getInvalidityInfoFor*(*);
if (!error.isEmpty()) {
    errors.add(error);
}
```
is repeated infinitely many times in all `*Attributes` class.

**Comment by LimeTheCoder** [comment]
I think to get rid of that routine, we need a little bit change methods api in FieldValidator class. I propose to replace old api of this methods, for example
`String getInvalidityInfoForCourseId(String courseId) `
 to following
`  boolean validateCourseId(String courseId, List<String> errors)...`
and update errors list in that particular methods if needed.
After that replacement, *Attributes will look like this.

        FieldValidator validator = new FieldValidator();
        List<String> errors = new ArrayList<String>();
        
        validator.validateCourseId(getId(), errors);
        validator.validateCourseName(getName(), errors);
        validator.validateCourseTimeZone(getTimeZone(), errors);

        return errors;

**Comment by wkurniawan07** [comment]
The method you proposed does not seem intuitive: why would a validation method accept a List of error strings as a parameter?
Also, `getInvalidityInfoFor*` is used many times beyond this purpose so it might not be wise to overhaul the API just like that.

**Comment by Malkone** [comment]
Please check the solution via link above for one class for the moment (StudentProfileAttributes). If such change is acceptable, I will make similar to other *Attributes classes.
