### ISSUE TITLE
Refactor StudentLogic.java

### ISSUE THREAD

**Issue by boxin-yang** [TEAMMATES/teammates#6563]
some method comments(such as validateTeams((List<StudentAttributes>, String)) do not follow java coding standard

**Comment by damithc** [comment]
Ensure the code is well covered by tests before refactoring. You can use EclEmma to find test coverage of the class.

**Comment by sujeet14108** [comment]
I don't see much problem in the class except for some Javadocs comment voilation like 
In `validateTeams` method 
    
    /**
     * Validates teams for any team name violations.
     */
That can be changed to 

    /**
     * Validates teams for any team name violations.
     *
     * @param studentList
     * @param courseId
     * @throws EnrollException
     */`
Except from these cosmetic changes at few places i don't see any other changes needed.

So is it doable ?

**Comment by damithc** [comment]
@boxin-yang any inputs?

**Comment by wkurniawan07** [comment]
Will not comment at issue at hand, but @sujeet14108 your suggested change is actually redundant and will be flagged as violations by CheckStyle because merely adding the parameter names and exception types do not add any new value to the documentation.

This is what will add value:
```java
/**
 * Validates teams for any team name violations.
 *
 * @param studentList the list of students ...
 * @param courseId the course ID of ...
 * @throws EnrollException if ... happens
 */
```

**Comment by sujeet14108** [comment]
@damithc Here is EclEmma output
![screenshot from 2017-06-03 00-52-28](https://cloud.githubusercontent.com/assets/9781422/26756637/d5a248a8-48c4-11e7-95d5-d4dbd2ba4dd1.png)

**Comment by damithc** [comment]
Closing due to lack of more specific info.
