### ISSUE TITLE
Admin scripts: StatisticsPerInstitute.java: improve scalability 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6566]
teammates/client/scripts/StatisticsPerInstitute.java is used to generate student number stats. This script is run monthly to generate monthly stats. However, it is not scalable (it tries to read all student entities at once) and cannot be run anymore since we went past 100K students. 
The script needs to be updated to read smaller chunks of data at a time so that it can run over large sets of data.

**Comment by whipermr5** [comment]
May need to make use of sharding counters? https://cloud.google.com/appengine/articles/sharding_counters

**Comment by damithc** [comment]
> May need to make use of sharding counters? https://cloud.google.com/appengine/articles/sharding_counters

Unlikely. The processing happens in the local Computer (we connect to the datastore remotely). The current algorithm is:
1. Read all student objects from remote datastore to local computer memory
2. Process all student objects in local memory

The above is not scalable to large student numbers. Instead, we can read 1000 students at a time.

**Comment by samsontmr** [comment]
Similar to pagination?

**Comment by damithc** [comment]
More likely the solution is Query Cursors https://cloud.google.com/appengine/docs/java/datastore/query-cursors

**Comment by samsontmr** [comment]
Hmm this sounds interesting, I'll work on this.

**Comment by AnaghHegde** [comment]
@samsontmr Shall i work on this?.

**Comment by samsontmr** [comment]
@AnaghHegde I recommend that you complete your existing PRs before opening a new one.

**Comment by whipermr5** [comment]
If we are just doing counts, [projection queries](https://cloud.google.com/appengine/docs/standard/java/datastore/projectionqueries) will give much better performance.
