### ISSUE TITLE
ControllerServlet: do not sent email to admin upon error

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6587]
Currently, an email alert is sent to the admin if a request is terminated due to an exception. This code is in the ControllerServlet. However, sending an email can delay the termination of the request which can anger GAE into shutting down the entire instance. Simply logging the error is enough because errors logged at SEVERE level generate email alerts anyway.

![image](https://cloud.githubusercontent.com/assets/1673303/22779822/3f524b5e-eef7-11e6-9df2-a92cc9a43f61.png)

**Comment by LiHaoTan** [comment]
Hi, can I suggest that instead of just the changes above that I make the changes as follows:
```Java
EmailWrapper errorReport =
                    new EmailGenerator().generateSystemErrorEmail(requestMethod, requestUserAgent, requestPath,
                                                                  requestUrl, requestParams, userType, t);
            /*
             * Error report is not sent immediately as it can delay termination of request which may result in GAE shutting down the instance.
             * The error report will be sent by email in the cron job /auto/compileLogs later
             */
            if (errorReport != null) {
                log.severe(ActivityLogEntry.generateSystemErrorReportLogMessage(req, errorReport, userType));
            }
```
