### ISSUE TITLE
AboutUs page: make the list numbering continuous

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6588]
See screenshot below. Instead of restarting the numbering from 1, make it continue from the previous list.

![image](https://cloud.githubusercontent.com/assets/1673303/22780295/31af7af6-eef9-11e6-9e12-107b28cf87dd.png)

**Comment by wkurniawan07** [comment]
Those are different sections for different titles (past team members, past committers, contributors). I don't think it's right to make the numbering continuous.

**Comment by damithc** [comment]
> Those are different sections for different titles (past team members, past committers, contributors). I don't think it's right to make the numbering continuous.

That's true. However, I'm more interested in showing the total size of our dev community rather than how many in each section.

**Comment by wkurniawan07** [comment]
> I'm more interested in showing the total size of our dev community

Then wouldn't a small script to count that number be the solution?

**Comment by damithc** [comment]
> Then wouldn't a small script to count that number be the solution?

Yes, that's even better.

**Comment by wkurniawan07** [comment]
Which way to go then? The two alternatives have nothing in common.

**Comment by damithc** [comment]
> Which way to go then?

I'm not sure how complicated the implementation of each solution is, so cannot decide myself. I suggested continuous numbering because I thought it is a trivial change (although the result is not perfect), but I could be wrong. If the required script is not that complicated either, we can leave the list numbering as they are and use the script to report the total dev community size in a separate place of the page.  What do you think?

**Comment by wkurniawan07** [comment]
Haven't tried myself, but a script to calculate the number of certain items in a static page cannot be any longer than 15 lines.

**Comment by li-kai** [comment]
I have an alternative solution, it is more complicated but would make things more maintainable. We could simply put the data in JSON format, then have the javascript just display them. Alternatively we could put that data in an ArrayList in Java, and pump them through JSTL loops.

Pros:

1) Data is now decoupled from view, meaning changes can be easily seen and maintained through line changes.
2) Adding new members is trivially easy.
3) Counting members is trivially easy.

Cons:

1) No longer a static page.

**Comment by wkurniawan07** [comment]
I'm all for the JSON solution. We're living in the age where most "static" pages are auto-generated anyway. 🤖

**Comment by damithc** [comment]
I'm ok for a non-static solution. Do we merge the current solution and upgrade to the non-static solution in a later PR?

**Comment by wkurniawan07** [comment]
The thing is, if we merge the current solution, it will get undone anyway. Of course if we still want to welcome external contribution, it is always doable.

**Comment by damithc** [comment]
> Of course if we still want to welcome external contribution, it is always doable.

OK, can close the current PR without merging but count it as a contribution. Close this issue (and reopen a new one) as the name and most of the discussion does not reflect the new direction?

**Comment by wkurniawan07** [comment]
Closing as agreed.
