### ISSUE TITLE
New contributor self intro [LimeTheCoder]

### ISSUE THREAD

**Issue by LimeTheCoder** [TEAMMATES/teammates#6595]
a) App: https://teammates-limethecoder.appspot.com/
b) Fork: https://github.com/LimeTheCoder/teammates
c) I created a list of conferences in index.jsp, instead of enumeration them in the sentence.
Before
![image](https://cloud.githubusercontent.com/assets/8873908/22842958/0bd140ac-efe0-11e6-8a98-b853e01a94df.png)

After
![image](https://cloud.githubusercontent.com/assets/8873908/22842970/1945e4fe-efe0-11e6-8c38-4e4645e6e8c6.png)

d) Hi! My name is Taras. I'm 3-rd year Software Engineer student with minor in Applied mathematics in Kyiv Polytechnic Institute, Ukraine. I suppose, your team will be included as a mentor organisation in GSoC17. I want to take part in it, so I decided to start early to better know your project and team.

**Comment by wkurniawan07** [comment]
@LimeTheCoder welcome to the TEAMMATES community!
Good job on setting up your very own dev environment and deploying to staging server! You can contribute to some of the open issues in the project, particularly those labelled `d.FirstTimers` (do just one of this) and `d.Contributors`.

As for GSoC, the program committee has yet to announce this year's mentor orgs, so there is no certainty yet that we will be one this year even though we were for the past three GSoCs.
