### ISSUE TITLE
"New contributor self intro Br35Ba56"

### ISSUE THREAD

**Issue by Br35Ba56** [TEAMMATES/teammates#6596]
Link to my appspot:  http://teammates-tony.appspot.com
Link to my Fork: https://github.com/Br35Ba56/teammates

Screen Shot to my change on my Tinker branch, changed 1000 to 1200 
![tinkerscreenshot](https://cloud.githubusercontent.com/assets/21034740/22843215/bef56198-efd8-11e6-8d8d-34bcd1673f8e.png)

Hello everyone,
My name is Anthony Schneider and I am studying Computer Science at the University of Maryland University College.  So far all of my course work has been in Java and I am looking forward to learn more by contributing to this project.  Just getting the development environment and staging server set up was a lot of firsts for me.  Looking forward to working with everyone!

**Comment by wkurniawan07** [comment]
@Br35Ba56 welcome to the TEAMMATES community!
Good job on setting up your very own dev environment and deploying to staging server! You can contribute to some of the open issues in the project, particularly those labelled `d.FirstTimers` (do just one of this) and `d.Contributors`.
