### ISSUE TITLE
Improve StudentAttributes.java doc comments

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#6606]
In gist, the doc comments of two methods, `isSectionChanged` and `isTeamChanged`, are aware of an "edit form" even though this low level class should not be.

Refer to comments [here](https://github.com/TEAMMATES/teammates/pull/6581#discussion_r100711782), [here](https://github.com/TEAMMATES/teammates/pull/6581#discussion_r100711809) and [here](https://github.com/TEAMMATES/teammates/pull/6581#discussion_r100711867).

**Comment by damithc** [comment]
To be done after #6581 is merged. 
Change the header comment of `isSectionChanged` and `isTeamChanged` to follow that of `isEmailChanged`

**Comment by amirhmd** [comment]
Hey guys, sorry, is there any body who could help me getting started with contributing tto this project? i am very looking forward to contribute in this project but I am new and i am not very high in experience.

**Comment by whipermr5** [comment]
Hey Amir! Check [this](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#fixing-issues) out :)

**Comment by saitj99** [comment]
@whipermr5 @damithc  could you confirm if this issue is fixed and close it. I see that the comments are fixed on _master_.  Issue addressed in PR #6583.

**Comment by whipermr5** [comment]
@saitj99 You're right!
