### ISSUE TITLE
New contributor self intro MikeBruns

### ISSUE THREAD

**Issue by MikeBruns** [TEAMMATES/teammates#6613]
https://teammates-michaelbruns.appspot.com/
https://github.com/MikeBruns/teammates/tree/tinker

I changed the testimonial cycle animation. It now cycles by fading instead of a straight change. Picture is showing the testimonial fading out. See my app engine to witness the fading :)
![intropic](https://cloud.githubusercontent.com/assets/7191840/22960699/e7d5e0dc-f30d-11e6-9865-1fa9a81d93f7.png)

My name is Michael Bruns and I am a recent computer science graduate from Bowling Green State University looking to become more familiar with open source projects and Java.  I have some experience and can work on web development, but am very interested in taking on front end and some back end work in this project.

Thanks

**Comment by junhaoyap** [comment]
@MikeBruns welcome to the TEAMMATES community!

Great job on setting up your very own dev environment and deploying to staging server with a nice change!

You can start to get your feet wet by contributing to some of the open issues in the project, particularly those labelled d.FirstTimers (do just one of this) and d.Contributors which will help you to become more familiar with open source projects and Java!

Looking forward :)
