### ISSUE TITLE
Bug report: User map does not load

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6621]
**Environment (dev/staging/live, version)**

Live server at V5.96

**Steps to Reproduce**

Open `/usermap.jsp` and wait for the user map to load.

**Expected Behaviour**

The user map loads.

**Actual Behaviour**

The user map does not load:

![image](https://cloud.githubusercontent.com/assets/1673303/23006780/e6b3dfd8-f43e-11e6-9121-f0b6dec3c3ea.png)

**Comment by damithc** [comment]
I have rolled back to v5.95. This needs to be fixed in the next version.

**Comment by wkurniawan07** [comment]
I found the problem. Will push as a hot patch.

**Comment by wkurniawan07** [comment]
Meanwhile I'll edit the issue description and title to fit the template.

**Comment by wkurniawan07** [comment]
Fixed in #6624.

**Comment by whipermr5** [comment]
This has [happened before](https://github.com/TEAMMATES/teammates/issues/6341), just that it was [broken](https://github.com/TEAMMATES/teammates/pull/6315) and [fixed](https://github.com/TEAMMATES/teammates/pull/6342) within the same milestone [(V5.93)](https://github.com/TEAMMATES/teammates/milestone/232) so it went unnoticed.
