### ISSUE TITLE
Refactor updateStudent in StudentsDb

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#6623]
This method has become too long after the email update issue was fixed in #6581 (refer to [comment](https://github.com/TEAMMATES/teammates/pull/6581#discussion_r100712141)).

**Comment by AnaghHegde** [comment]
@whipermr5 How about having 2 methods which handles the `if` and `else` conditions.

**Comment by wkurniawan07** [comment]
@AnaghHegde you can give it a try.
