### ISSUE TITLE
Self intro Shivansh Soni

### ISSUE THREAD

**Issue by shivanshsoni** [TEAMMATES/teammates#6635]
Hello sir, 
I am Shivansh Soni and I am contributing to this from a month. I have solved many issues as you can check my commits. I want to be a part of GSOC this year and want to work for your organisation.

**Comment by junhaoyap** [comment]
@shivanshsoni welcome to the TEAMMATES community!

Nice to have you around, have you introduced yourself before with the template that we have?

In any case, I don't think we are sure of whether we are in GSOC this year yet, cc @damithc @wkurniawan07 for confirmation regarding GSOC
