### ISSUE TITLE
Remove unused parameter in InstructorHomeAjaxCoursePageData.java

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6638]
In `teammates.ui.pagedata.InstructorHomeAjaxCoursePageData#init`, the last parameter `sectionNames` is not used and thus can be removed.

**Comment by onealml** [comment]
I have just made a pull request for this issue. (please ignore the duplicate commits, the correct one is the last pull request I made!).
Also I assumed that there was a typo in this issue name: it says InstructorHome**AjaxCourse**PageData.java but the actual file I found and edited was InstructorHome**CourseAjax**PageData.java
