### ISSUE TITLE
Remove unnecessary classes in common.datatransfer package

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6640]
- `FeedbackQuestionBundle`: not used at all.
- `SessionResultsBundle`: an empty interface with only one implementing class. Removing it has no side effect.
- `FeedbackSessionState`: only used in `AdminSearchPageData`; can be moved there as a private enum instead.

**Comment by jamesrowlands85** [comment]
I will pick this up and submit a pull request.

**Comment by jamesrowlands85** [comment]
My only thought is that is it not best to leave the interface SessionResultBundle as a marker interface?
