### ISSUE TITLE
Misplaced null check in FeedbackSessionResultsBundle.java

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6641]
In `teammates.common.datatransfer.FeedbackSessionResultsBundle`, these two methods `getPossibleGivers(FeedbackQuestionAttributes, String)` and `getPossibleRecipients(FeedbackQuestionAttributes, String)` are guilty of an identical mistake:
```java
boolean variable = parameter.someMethod();

if (parameter == null || variable) {
    return new ArrayList<String>();
}
```
If `parameter` is really null, NPE will occur and thus the null check is futile.

**Comment by nmjacob** [comment]
Hi, I am new to working on public GitHub repos, so I am going to take this issue as my first if that is ok. I will follow all the guidelines in the project documentation.

**Comment by wkurniawan07** [comment]
Hi @nmjacob, welcome to TEAMMATES!
As it turns out, this issue has been solved in #6652 (and it was me who solved it, apologies!) and so is not valid anymore. Sorry about this!
Nevertheless, there are many other issues labelled `d.FirstTimers` that are equally beginner-friendly as this one and you're welcome to work on any one of them! However, you should do only one of such issue.

**Comment by nmjacob** [comment]
@Wkurniawan07 just so I know for future notice, am I supposed to write a comment I want to work on something? Or just do it? Trying to learn the GitHub customs haha :)

**Comment by wkurniawan07** [comment]
@nmjacob that varies from project to project. Here it is not required, but appreciated.
