### ISSUE TITLE
FeedbackNumericalScaleQuestionDetails: refactor long methods

### ISSUE THREAD

**Issue by AnaghHegde** [TEAMMATES/teammates#6657]
Some methods of this class have 130 lines of code. I think following methods need refactoring.

1. `getStudentQuestionResultsStatisticsHtml()`  

2. `getQuestionResultStatisticsCsv()`
 
3. `populateSummaryStatisticsFromResponses()`

**Comment by yalapeno** [comment]
We, 5 people, are looking for an issue to work on as a part of a school project. It has to be about refactoring a part of a relatively big project(>10000 lines of code). This issue got our attention while searching. What is the state of this issue? do you need refactoring in any other project or in this one? We can not take zulip project, it's already taken by other students..

**Comment by OLGKAD** [comment]
@yalapeno 
Hi! If you're doing this as a part of your Software Engineering Fundamentals assignment #3, in KTH, then I'm afraid that our team has secured this issue first.

**Comment by yalapeno** [comment]
@OLGKAD 
hey, yes we realized that later and we now got another project :)
