### ISSUE TITLE
New contributor self intro - Vamsi Sangam

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#6658]
a) [Link to my app](http://4-18-dot-teammates-vamsi.appspot.com/)
b) [Link to my fork](https://github.com/VamsiSangam/teammates)
c) Screenshot of the UI change -
![capture](https://cloud.githubusercontent.com/assets/11662001/23205954/e21459d0-f911-11e6-8702-62e4bc7d4b04.JPG)
d) Intro -

My name is Vamsi Sangam. I am an undergraduate student at Indian Institute of Information Technology Allahabad (IIITA). I like web development. You can check out my [website](https://vamsisangam.github.io/) which used to be an ASP.NET MVC app hosted in Microsoft Azure. But then things got costly and I decided to make it a static site in GitHub :stuck_out_tongue_closed_eyes: . I am mostly a Java guy but I am fluent with C, C# and trying to get fluent with Python.

I am kind of new to open source development. My second ever PR to be accepted was in Teammates. I just added a space somewhere :smile: . Back then I was just trying to understand GitHub and the various projects. I googled "github java projects for beginners" and the [first link](https://github.com/MunGell/awesome-for-beginners) is what lead me to the Teammates project. :smile:

With Teammates, I hope to learn how to build production quality software, the processes behind it and also how to maintain them. And as I am still a rookie to GitHub I hope to learn more about it and why it is used so extensively for software development. :smile:

**Comment by wkurniawan07** [comment]
Welcome to TEAMMATES, @VamsiSangam!

Good job on setting up your own developer environment and staging server! I also recognize that you have contributed a fix to TEAMMATES before, but you're of course welcome to contribute more fixes! Do take note that you're no longer allowed to work on issues labelled `d.FirstTimers`, but there are still plenty of other issues for you to pick and fix. In particular, issues labelled `d.Contributors` are suitable for non-first-timer newcomers like yourself.

Looking forward to more of your contributions!

**Comment by VamsiSangam** [comment]
Thank you @wkurniawan07 . Will get started with ```d.Contributors``` issues :smile:

**Comment by paradite** [comment]
Nice personal website. Good job!

**Comment by VamsiSangam** [comment]
Thank you @paradite ! Your website looks great and informative too! :smile:

**Comment by junhaoyap** [comment]
@VamsiSangam welcome to the TEAMMATES community! Fantastic job so far!

May I know if you are you aiming to be part of GSOC?

**Comment by VamsiSangam** [comment]
Yes sir I will be a part of GSoC 2017.

**Comment by wkurniawan07** [comment]
@VamsiSangam if you'd like to apply for GSoC, you may want to consider which one(s) of our [project ideas](https://docs.google.com/document/d/1fAvYvQr0E93OsZgyneaXGX0jaMA-zptTIxqLn83xwN0/pub?embedded=true) you'd like to undertake (you're not required but welcome to discuss here). Other than that, you've been doing the right thing; do continue contributing fixes so we know what you're capable of! 💻

**Comment by VamsiSangam** [comment]
Sure @wkurniawan07 ! Will go through them for sure. Thank you! :smile:

**Comment by junhaoyap** [comment]
@VamsiSangam thanks for confirming with us, do read through the document that @wkurniawan07 has provided, it will help!

**Comment by VamsiSangam** [comment]
@wkurniawan07 and @junhaoyap , just letting you know that I'm interested to work with the Questions+ project. I'll need a little more time before I can submit the proposal. :smile:
