### ISSUE TITLE
New contributor self intro Aman Dhaliwal

### ISSUE THREAD

**Issue by a-dhaliwal** [TEAMMATES/teammates#6661]
**A:** [Link to my app](http://4-18-dot-teammates-adhaliwal.appspot.com/)

**B:** [Link to my fork](https://github.com/a-dhaliwal/teammates/)

**C:** For my UI change, I simply edited the student and instructor login buttons. Instead of them staying green, they are white, but change green when a mouse is hovered over them. Like so:

**Before:**

![before](https://cloud.githubusercontent.com/assets/25941140/23239207/d4789f6c-f933-11e6-98b8-0f1c790e5673.PNG)

**After:**
![after](https://cloud.githubusercontent.com/assets/25941140/23239275/50136490-f934-11e6-98d8-c8d8444eb0cb.PNG)

**D:** Hey there everyone, my name is Aman Dhaliwal. I graduated with a diploma in an IT support program(think managing servers, setting up computers, handling help desk operations, stuff of that nature). While looking for work in that field I was given a much better opportunity to switch into a career in programming, that is what brings me here. While I have programmed as a hobby and for school for many years, becoming semi-fluent to fluent in languages like Python, C and C#, Java. I have never really been involved in programming professionally nor in anything related to open source. I feel by working on this project, I can get accustomed to working on big projects and working on open source projects as well as get familiar with git and work on my Java skills. Hopefully that wasn't too long of an intro, haha.

Another thing I want to mention is for my staged app, I wasn't able to deploy my app until I commented out 2 queue tasks in queue.xml, I was getting errors related around restrictions imposed on free google app engine accounts. I could have fixed it by signing up for billing, that requires a credit card, I don't have one so I had to find a band aid solution around that in removing two queue tasks so that it would deploy successfully. It wasn't the only issue I had however, took me a fair bit of googling and tinkering to get it all working, got quite annoying at times but I'm glad I managed to get it all up and running and look forward to contributing to this project.

**Comment by wkurniawan07** [comment]
Welcome to TEAMMATES, @a-dhaliwal!

Good job on setting up your own developer environment and staging server! I have read the introduction and I can assure that you are coming to the right place to learn all those. For starters, you can contribute by fixing an issue labelled `d.FirstTimers` (which you are already in the process of doing -- good job!), and then to other issues (particularly those labelled `d.Contributors`).

As for the staging server needing credit card registration, it was indeed a limitation that we have missed in documenting, so apologies for that. Removing some items from `queue.xml` is the only way to circumvent this problem. You may want to add a portion in our documentation (particularly in troubleshooting guide) to mention about this problem; we'll gladly welcome your contribution on this!

Looking forward to your contributions!
