### ISSUE TITLE
New contributor self intro Tainan

### ISSUE THREAD

**Issue by tainansv** [TEAMMATES/teammates#6680]
**a)** [link](https://teammates-tainan.appspot.com/) to my app

**b)** [link](https://github.com/tainansv/teammates) to my fork

**c)** My change on UI. I added a hover effect in the background of the links on navbar.
(the mouse does not appear in screenshot, sorry)
![capturar](https://cloud.githubusercontent.com/assets/12564380/23364519/254c71f4-fcde-11e6-961c-44eec290a1e0.PNG)

**d)**  Hi, my name is Tainan Valentim. I'm from Brazil, graduated in Computer Networks. While in college I became interested in programming, learning more on my own. I know Java, a bit of C# and Python, and web development stuff like HTML, CSS, JavaScript, etc.
I don't have experience as a developer, and this is my first participation in a project. I expect gain experience, knowledge and the most important, be helpful 😄 

P.S. my english is not so good, sorry for something

**Comment by wkurniawan07** [comment]
@tainansv welcome to TEAMMATES community!
Good job on setting up your dev environment and deploying to staging server! You can contribute by fixing issues listed in our issue tracker; I advise to start with one labelled `d.FirstTimers` (but do not do more than one of these), and then `d.Contributors`. Looking forward to your contributions! 👍

There's nothing to worry about the language barrier; so long as we can understand each other's messages, all is cool 👌

**Comment by junhaoyap** [comment]
@tainansv  welcome to the TEAMMATES community! Good job so far!

May I know if you are you aiming to be part of GSOC? The process differs a little so it would be great if we can know if you are aiming for it!

Your English is good enough, just like what @wkurniawan07 said, we understand and that's what matters, no need to be apologetic when you speak /type in English

**Comment by tainansv** [comment]
@junhaoyap for what I know, to be part of GSOC it's necessary be a student, right? I am already graduated.
Besides that, I'm not yet confident enough in my skills to be part of such big event. Maybe in the future.

**Comment by junhaoyap** [comment]
@tainansv I am not sure if it is necessary to be a student, I would refer to @damithc regarding that as he knows most about GSoC!

Learning / Contributing to open source is one way to improve your skills 👍  Great job on starting on the open source path here!
