### ISSUE TITLE
New contributor self-intro Zhao Dingfan

### ISSUE THREAD

**Issue by ZhaoDingfan** [TEAMMATES/teammates#6683]
A: [Link](https://teammates-dingfan.appspot.com/) to my app

B: [Link](https://github.com/ZhaoDingfan/teammates) to my fork

C: For my UI change, actually I implemented it successfully on the localhost. However, it does not work on GAE, so it remains the same for UI. Once I find the problem with GAE deployment, I will change my UI immediately. 

![alt text](https://github.com/ZhaoDingfan/teammates/blob/master/src/main/webapp/images/UI_Screenshot.png?raw=true)

D: Hello everybody, my name is Zhao Dingfan. Currently I am a student of National University of Singapore. I major in Computer Engineering and this is my first time to contribute to such a huge scale project, hope I can have chance to be enrolled in this project in the future. 

P.S. I have a small question about the deployment of GAE, is there any difference about the final effect between deploying code from IDE and upload the code to GAE itself?

**Comment by wkurniawan07** [comment]
@ZhaoDingfan welcome to TEAMMATES community!
Good job on setting up your development environment and deploying to staging server! You can contribute by fixing issues listed in our issue tracker. For starters, you can fix one labelled `d.FirstTimers` (do just one of these), and then `d.Contributors`. Looking forward to your contributions! 👍

As for your question -- I presume by "uploading the code to GAE itself" you mean using shell command or Gradle command to deploy? I have not verified it myself, but I have done them before some time back and did not find any noticeable difference.

**Comment by junhaoyap** [comment]
@ZhaoDingfan welcome to the TEAMMATES community! Good job!

May I know if you are you aiming to be part of GSOC? The process might differ a little so we would like to differentiate between those who are and those who aren't!

**Comment by ZhaoDingfan** [comment]
Thank you for your kind greeting!
Actually I am a CEG student in NUS and I applied for this internship through SIP portal. Maybe in the future I will also apply for TEAMMATES through GSOC.
