### ISSUE TITLE
GSOC'17

### ISSUE THREAD

**Issue by ntbandara3** [TEAMMATES/teammates#6685]
Hello guys, 

I am a 3rd year Software Engineering undergraduate at Sri Lanka Institute of Information Technology. I am interested in the GSOC'17 program and have experience with HTML, CSS, JavaScript, Java languages and Git.

Hope to hear from you guys soon 
Cheers. :grin:
<<Nandun>>

**Comment by wkurniawan07** [comment]
@ntbandara3 thanks for your interest in contributing to TEAMMATES under GSoC! Do read [our instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true) for more relevant information.

**Comment by junhaoyap** [comment]
@ntbandara3 welcome to the TEAMMATES community! @wkurniawan07 gave some good advice :)
