### ISSUE TITLE
gsoc 17

### ISSUE THREAD

**Issue by YaroslavTER** [TEAMMATES/teammates#6687]
Hi, I'm interesting in your organization which is participating in Google Summer Of Code and I want to be accepted. I'm study in National Aviation University (Ukraine) on Software Engineering 3 year. I have some experience in implementation of own small games in JavaScript that is hosted on my GitHub account. Also have some experience with languages Java, C#, have entry level of HTML, CSS and use version control system Git. Hope on answer.

**Comment by damithc** [comment]
@YaroslavTER Good to hear your interest in contributing to TEAMMATES under GSoC. Please read to [our instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true).
