### ISSUE TITLE
New contributor self intro [Wu Xiao Xiao]

### ISSUE THREAD

**Issue by a0129998** [TEAMMATES/teammates#6688]
1. I can't deploy because I don't have a method of payment.
2. <a href="https://github.com/a0129998/teammates.git">link to fork</a>
3. 
![image](https://cloud.githubusercontent.com/assets/12403982/23443689/82a266d6-fe6b-11e6-8d4c-eb9606641abc.png)
4. My name is Wu XiaoXiao, I mainly program in Java and C++, I'm also farmiliar with html and CSS. ;D

**Comment by wkurniawan07** [comment]
@a0129998 welcome to TEAMMATES community!
Good job on setting up your development environment! You can contribute by fixing issues listed in our issue tracker. For starters, you can fix one labelled `d.FirstTimers` (do just one of these), and then `d.Contributors`. Looking forward to your contributions! 👍

As for why you cannot deploy; does Google App Engine itself require payment method even for a task as simple as hosting code, or something else?

**Comment by junhaoyap** [comment]
@a0129998 welcome to the TEAMMATES community! Good job!

Are you also looking to be part of GSOC?

**Comment by boxin-yang** [comment]
@a0129998  Hi Xiaoxiao!!! Looking forward to work with you hahaha

**Comment by a0129998** [comment]
@wkurniawan07 google cloud platform requires me to provide payment details to register with them. According to them it's to make sure that I am not a robot.

@junhaoyap yep.

@boxin-yang Hi boxin.

**Comment by junhaoyap** [comment]
@a0129998 thanks! in that case Do read [our instructions for GSoC applicants](https://docs.google.com/document/u/1/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true) for more relevant information!
