### ISSUE TITLE
Dev docs: deploying to staging server: explain how to handle task queue count restriction

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6691]
With more than 10 items in the task queue (and unlikely to go down), deploying is not possible without billing enabled. We need to add an entry on this to the troubleshooting guide.

**Comment by damithc** [comment]
> We need to add an entry on this to the troubleshooting guide.

As _everyone_ is going to encounter this, better to explain this where we cover how to deploy to staging server?

**Comment by wkurniawan07** [comment]
@damithc according to https://github.com/TEAMMATES/teammates/issues/6688#issuecomment-283620352, a card is needed even for registering. That already overshadows the problem described by this issue because once a card is available, one only needs to activate billing with quota of zero to stay at free tier.
I think @chowyb can verify that also?

**Comment by chowyb** [comment]
Yep can confirm, I'm unable to start the free trial due to this part of the form:
![regis](https://cloud.githubusercontent.com/assets/7546744/23513583/7af9f360-ff9f-11e6-94fb-362d5cdd514d.png)

**Comment by samsontmr** [comment]
Can confirm this too.

**Comment by wkurniawan07** [comment]
Closing this issue on account of:
1. Deploying to staging server is no longer a requirement for a new contributor
1. A card is needed even for activating staging server; it overshadows the problem described here
1. There is a way to deploy an application without the task queue configuration (albeit this means the staging server's task queues will not work)
1. GAE's stance on this keeps changing; better to consult their official documentation when the need arises
