### ISSUE TITLE
Self Intro - Monish Godhia

### ISSUE THREAD

**Issue by share-with-me** [TEAMMATES/teammates#6692]
Hi Teammates Community, 
I would like to work for the project - Reports+ as part of my GSoC '17. I have worked on similar projects before and have ample exposure to charting libraries such as d3.js, dc.js and crossfilter.js and other web technologies. 
How should I start this project? Is there a qualification task? Thanks!

**Comment by wkurniawan07** [comment]
@share-with-me thanks for your interest in contributing to TEAMMATES under GSoC! Do read [our instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true) for more relevant information.

**Comment by junhaoyap** [comment]
Hi @share-with-me, welcome to the TEAMMATES community!

**Comment by paradite** [comment]
Hi @share-with-me interesting experience with d3.js. Just curious if your recent repos [InteractiveDashboard](https://github.com/share-with-me/InteractiveDashboard) and [d3-warmup-dashboard](https://github.com/share-with-me/d3-warmup-dashboard) are written by yourself?

I also do quite a bit of d3.js in the past so I am excited to see someone with similar interest.

**Comment by share-with-me** [comment]
Hey @junhaoyap , thanks much! Pretty excited!

**Comment by share-with-me** [comment]
Hey @paradite , yes - the warmup as the name suggests was just to get warm up again with the d3.js (I love it!) and I wrote it completely by myself. The interactive dashboard (first time) was something I came across a few weeks back ( using d3.js, dc.js and crossfilter.js) and I referred some blogs to make that! I do feel confident in now although it its usage! What projects have you done using d3.js? (If new, I ll suggest please look into dc.js and crossfilter.js too!)

**Comment by paradite** [comment]
you can take a look at https://github.com/paradite/gitviz and https://github.com/paradite/Graphpedia which I did a few years back with d3.js mainly.

**Comment by share-with-me** [comment]
They are cool (both of them) - I loved Graphpedia! By the way, these are too old!  What are you working with currently?

**Comment by paradite** [comment]
Now I am not working on any open-source projects since I am graduating soon. But I will definitely want to work on cooler project when I get a chance.

**Comment by junhaoyap** [comment]
@share-with-me, remember to look into the link that @wkurniawan07 has provided for you!
