### ISSUE TITLE
Remove unused methods in datepicker.js

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#6693]
The methods `getMinDateForEndDate` and `getMaxDateForStartDate` are not used in the project. There is no reason to leave them there.

**Comment by sayedafif** [comment]
Can I work on this?

**Comment by xpdavid** [comment]
@sayedafif There is already a PR for this issue. Maybe you want to try other `d.firstTimers` issues? :)

**Comment by sam25malik** [comment]
Hi i want to contribute as i would like to increase my chances of selection for gsoc can u suggest me  some issue?

**Comment by xpdavid** [comment]
@sam25malik Welcome to Teammates. You can start to contribute by fixing `d.firstTimers` issue :)
