### ISSUE TITLE
CI tests skipped after branch merge

### ISSUE THREAD

**Issue by AnaghHegde** [TEAMMATES/teammates#6696]
I am not sure this is the same case as #6509. But take a look at the screen shot. 
![capture](https://cloud.githubusercontent.com/assets/12005551/23467725/d1bbf17a-fec4-11e6-9c45-b7338240e63f.PNG)

But looks like it is.

**Comment by AnaghHegde** [comment]
I will try to reproduce the same thing as happened in #6509.

**Comment by wkurniawan07** [comment]
I just checked the PR in question, and nothing was skipped. Do be patient and wait for the yellow dot to turn green; sometimes the CI builds do not finish in sequence.
