### ISSUE TITLE
New Contributor Self-Intro Boban Trajanovski

### ISSUE THREAD

**Issue by btrajanovski** [TEAMMATES/teammates#6697]
<a href="https://github.com/btrajanovski/teammates"> Fork</a>

Hi, my name is Boban Trajanovski. I’m originally from Macedonia but currently live and work in the United States. I’m perusing undergraduate degree in Computer Science concentration Network Security in Northeastern Illinois University in Chicago. I have knowledge in couple programming languages such as: Java, basic Python, HTML, CSS, JavaScript, jQuery, Bash shell. The most experience I have is couple of school project but other than that this is my first time participation in a big project. 
I’m hoping I can be of some help.

**Comment by wkurniawan07** [comment]
@btrajanovski welcome to TEAMMATES community!
Good job on setting up your development environment! You can contribute by fixing issues listed in our issue tracker. For starters, you can fix one labelled `d.FirstTimers` (do just one of these), and then `d.Contributors`. Looking forward to your contributions! 👍

One question: are you planning to apply for GSoC?

**Comment by junhaoyap** [comment]
@btrajanovski welcome to the TEAMMATES community! Great job!

I was about to ask if you are planning to apply for GSoC and noticed that @wkurniawan07 has already asked so welcome once again!

**Comment by btrajano** [comment]
Hi guys! 
No, I'm not going to apply for the GSoC 2017. 

Looking forward to work woth you guys!
