### ISSUE TITLE
Unused @returns documentation tags in datepicker.js

### ISSUE THREAD

**Issue by samsontmr** [TEAMMATES/teammates#6700]
A number of header comments in datepicker.js have unused `@returns` tags. 

**Task:**
Either use them to describe what the respective methods return, or remove them entirely.

**Comment by a0129998** [comment]
I'm interested in this task.

**Comment by samsontmr** [comment]
@a0129998 Just go ahead and open a pull request :)

**Comment by a0129998** [comment]
Hi, I have created a pull request, but I forgot to add labels, but it's ready to be reviewed.
