### ISSUE TITLE
Dev docs: tweaks Intellij instructions

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6702]
Some minor things I noticed while dogfooding: [to be updated as I dogfood more]

> `Configure → Project Defaults → Project Structure.`

Windows version of Intellij doesn't seem to have this menu path

> Click `Import existing project` and select the local repository folder

This menu path is not present in the main UI

![image](https://cloud.githubusercontent.com/assets/1673303/23511549/5e9aa766-ff98-11e6-8e56-9ceb056c3870.png)

Initially I thought I should use `...` button, but it didn't work (I was able to choose the project folder but the OK button remained disabled). Then I tried using the button with the folder icon and itworked.

> Go to Run → Play
Use `Run...` instead of `Play`?

> Click + → .... Select the App Engine SDK you downloaded in Step 3 of the Setting up a development 
> environment guide.

If the user chose the `appengine-sdk` folder instead of the sub-folder inside it (note that `appengine-sdk` is the folder mentioned in _Step 3_) it will result in this error at a later stage:
`Error running Dev Server: 'C:/Users/damithch/.gradle/appengine-sdk' isn't valid App Engine SDK installation: 'C:\Users\damithch\.gradle\appengine-sdk\lib\appengine-tools-api.jar' not found`

**Comment by samsontmr** [comment]
> Windows version of Intellij doesn't seem to have this menu path

It's in the bottom right corner of the welcome screen (the screen IntelliJ shows you if you close the project/haven't imported any projects).

**Comment by damithc** [comment]
> It's in the bottom right corner of the welcome screen (the screen IntelliJ shows you if you close the project/haven't imported any projects).

We cannot assume the IDE is a fresh install, which means the welcome screen may not be present.  In my case, I already had some other projects configured for Intellij which means IDE opens with the most recent project (not the welcome screen). Also note that some of the other projects might be using Java 8, which means we cannot simply set the entire IDE to use Java 7.

**Comment by samsontmr** [comment]
Perhaps we can have separate sets of intructions for fresh installs and those with existing projects?

Mine was a fresh install, so I had to add a JDK before IntelliJ allowed me to import the project (otherwise I got stuck at the screen where you need to select a JDK).

**Comment by damithc** [comment]
You can write the main description for fresh installs and include variations (may be as block quotes) where an existing install differs.
