### ISSUE TITLE
GSOC 2017

### ISSUE THREAD

**Issue by hackosinn** [TEAMMATES/teammates#6704]
Hi, 
     I'm a 3rd year computer science student. i'm interested in projects comments+ and usability hero as part of Gsoc 2017. i'm familiar with teammates community and code structure as i have contributed to it. Due to college project i couldn't contribute to teammates recently. i have experience with java,jsp,html,css and javascript. 

Thanks!

**Comment by samsontmr** [comment]
Hi @hackosinn, if you have already read [our instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true), you can continue to contribute whenever you have time :)

**Comment by junhaoyap** [comment]
Hello @hackosinn, you are indeed familiar and if you're interested in GSoC, do read the link that @samsontmr has provided!

**Comment by AnamikaD** [comment]
Hi, 
Is this project still available? #6913
