### ISSUE TITLE
Clarify App Engine SDK selection instructions in Development Guidelines

### ISSUE THREAD

**Issue by samsontmr** [TEAMMATES/teammates#6709]
Line 48 (shown below) of `development.md` is unclear as to which `appengine-sdk` folder the user is supposed to select (`appengine-sdk` or `appengine-java-sdk-<version>`).  This needs to be clarified.
> **Line 48**
> `Click + → .... Select the App Engine SDK you downloaded in Step 3 of the Setting up a development environment guide.`

From @damithc:
> If the user chose the appengine-sdk folder instead of the sub-folder inside it (note that `appengine-sdk` is the folder mentioned in Step 3) it will result in this error at a later stage:
`Error running Dev Server: 'C:/Users/damithch/.gradle/appengine-sdk' isn't valid App Engine SDK installation: 'C:\Users\damithch\.gradle\appengine-sdk\lib\appengine-tools-api.jar' not found`

**Possible Solution:**
Give an example of the folder name to be selected in parentheses after `App Engine SDK` like so: 
> App Engine SDK (`appengine-java-sdk-<version>`)

Other suggestions are welcome (you can post your suggestion as a comment here first).

**Comment by Skchoudhary** [comment]
@samsontmr 

Specifying like this might also not clear to user which folder to choose, so we can simply specifies like this
`Click + → .... Select the appengine-java-sdk-<version>(sub-folder of App Engine SDK  you downloaded in Step 3 of the Setting up a development environment guide)`

**Comment by samsontmr** [comment]
@Skchoudhary 
`Select the App Engine SDK (appengine-java-sdk-<version> sub-folder) you downloaded in Step 3 of the Setting up a development environment guide.` should be sufficient.

**Comment by Skchoudhary** [comment]
@samsontmr 

So, should I go ahead do that modification.

**Comment by samsontmr** [comment]
Yes you can.

**Comment by Skchoudhary** [comment]
@samsontmr 

ok
