### ISSUE TITLE
Bind loop variable using closure rather than external variable

### ISSUE THREAD

**Issue by li-kai** [TEAMMATES/teammates#6712]
As mentioned in #6608, in `instructorFeedbackResults.js`, we should bind `idx` to the setTimeout instead of using another variable `i`.

Reading material: http://ignaciothayer.com/post/a-dangerous-example-of-javascript-hoisting/

**Comment by junhaoyap** [comment]
Just leaving another material here for when the time comes

ES6 arrow functions (some effects on binding): https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions

ES6 block scope variable declaration (let - works closer to how most people expects variable declarations to work in most modern languages):
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/let

**Comment by amarlearning** [comment]
@li-kai As I am already done with my `d.FirstTimers`, I would like to take this one :smile:

**Comment by li-kai** [comment]
@amarlearning Go ahead, and ask questions if you're not clear. Pls work on the `dev-es6` branch!

**Comment by amarlearning** [comment]
@li-kai Not able to find this file `instructorFeedbackResults.js` in `dev-es6` branch.
here is the [link](https://github.com/teammates/teammates/blob/dev-es6/src/main/webapp/js/instructorFeedbackResults.js), this says page not found.

**Comment by li-kai** [comment]
@amarlearning It's `.es6` cause we're in process of migration. [https://github.com/teammates/teammates/blob/dev-es6/src/main/webapp/js/instructorFeedbackResults.es6](https://github.com/teammates/teammates/blob/dev-es6/src/main/webapp/js/instructorFeedbackResults.es6)
