### ISSUE TITLE
instructor.js: add more tests

### ISSUE THREAD

**Issue by Neurrone** [TEAMMATES/teammates#6713]
Only 3 functions in instructor.js are being tested currently.

**Comment by Neurrone** [comment]
After investigating, the functions in instructor.js are mostly about registering event handlers. 

The handlers open a bootbox modal, and redirects the browser to a url when the user chooses ok. 

Since there doesn't seem to be a way of simulating clicks on the ok button for testing, the remaining things are whether the callback is called, and if the window.location is set appropriately. Is testing these required?

**Comment by damithc** [comment]
@wkurniawan07 @li-kai @thenaesh your input?

**Comment by thenaesh** [comment]
I think one thing that might work is to extract out all the parts in a function (e.g. in `bindPublishButtons`) that occur before the Bootbox call.

For instance,
```js
function bindPublishButtons() {
    $('body').on('click', '.session-publish-for-test', function(event) {
        event.preventDefault();

        var $button = $(this);
        var feedbackSessionName = $button.data('fsname');
        var messageText = 'Are you sure you want to publish the responses for the session "' + feedbackSessionName + '"?';

        var isSendingPublishedEmail = $button.data('sending-published-email');
        if (isSendingPublishedEmail) {
            messageText += ' An email will be sent to students to inform them that the responses are ready for viewing.';
        }

        var okCallback = function() {
            window.location = $button.attr('href');
        };

        BootboxWrapper.showModalConfirmation('Confirm publishing responses', messageText, okCallback, null,
                BootboxWrapper.DEFAULT_OK_TEXT, BootboxWrapper.DEFAULT_CANCEL_TEXT, StatusType.WARNING);
    });
```
can be extracted into something like
```js
function handleBindPublishButtonsEvent(event) {
    var $button = $(this);
    var feedbackSessionName = $button.data('fsname');
    var messageText = 'Are you sure you want to publish the responses for the session "' + feedbackSessionName + '"?';

    var isSendingPublishedEmail = $button.data('sending-published-email');
    if (isSendingPublishedEmail) {
        messageText += ' An email will be sent to students to inform them that the responses are ready for viewing.';
    }

    var okCallback = function() {
        window.location = $button.attr('href');
    };
    
    return {messageText: messageText, okCallback: okCallback};
}

function bindPublishButtons() {
    $('body').on('click', '.session-publish-for-test', function(event) {
        event.preventDefault();
        
        var result = handleBindPublishButtonsEvent.call(this, event);

        BootboxWrapper.showModalConfirmation('Confirm publishing responses', result.messageText, result.okCallback, null,
                BootboxWrapper.DEFAULT_OK_TEXT, BootboxWrapper.DEFAULT_CANCEL_TEXT, StatusType.WARNING);
    });
}
```

Then those parts can be tested (in particular, to make sure that the callback link is correct) by manually firing the events. Then we can just trust Bootbox to do the right thing. xD

**Comment by Neurrone** [comment]
@thenaesh good idea

**Comment by wkurniawan07** [comment]
@Neurrone I am actually already trying to do it in #6615, if you don't mind waiting. I'll try to get it merged in 2-3 days.

**Comment by Neurrone** [comment]
@wkurniawan07 sure. Was also going to wait for https://github.com/TEAMMATES/teammates/pull/6714 in case it modifies the file.

**Comment by li-kai** [comment]
I am also facing this issue in other js files. I personally don't feel that is a lot of advantage of writing tests for these.
