### ISSUE TITLE
Add TEAMMATES to up-for-grabs list

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6715]
We can add TEAMMATES to the lit of beginner friendly OSS projects maintained at http://up-for-grabs.net

**Comment by domdomegg** [comment]
Done - see:
https://github.com/up-for-grabs/up-for-grabs.net/pull/566

**Comment by domdomegg** [comment]
Merged; this issue can be closed

**Comment by samsontmr** [comment]
Thanks @domdomegg!
