### ISSUE TITLE
Hi , I am new and I would like to contribute can someone please help me to get started?

### ISSUE THREAD

**Issue by suhaibk9** [TEAMMATES/teammates#6719]
I can code in JAVA . I would be highly obliged if someone will guide me on how to start contributing.

**Comment by rclakmal** [comment]
@suhaibk9 Pls refer to [https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md](Contributor Guide).

**Comment by samsontmr** [comment]
Hi @suhaibk9, welcome to TEAMMATES! You can start by reading the [Contributor Guide](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md), setting up your development environment and fixing a [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue. Don't forget to [introduce yourself](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md#phase-d-introduce-yourself-to-the-community) as well!

Are you planning to apply for GSoC? If you are, please read [our instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true).

**Comment by junhaoyap** [comment]
@suhaibk9, welcome to the TEAMMATES community, as mentioned by @rclakmal and @samsontmr, we have a contributor's guide that should have more than sufficient information to get anyone with some background and effort started, do get your feet wet and if you need more specific help, you can always post here again!
