### ISSUE TITLE
Use vector images (SVG) in webapp and docs

### ISSUE THREAD

**Issue by domdomegg** [TEAMMATES/teammates#6720]
**Use vector images in webapp and docs**

Images in [`webapp/images`](https://github.com/TEAMMATES/teammates/tree/master/src/main/webapp/images) and [`docs/images`](https://github.com/TEAMMATES/teammates/tree/master/docs/images) should use vector image files, probably SVG.

In `webapp/images` there are many `.pptx` versions of the illustrations which could easily be converted to SVG, however no such copies exist in webapp.

Hopefully the creators of the images can find original source files otherwise they will have to be recreated.

**Justification**
- All those using the site will benefit from faster load times.
- Vector formats are easily editable and allow editors to work together on files better to improve them
- Vector is scalable and so looks much better on high-DPI displays e.g. 4K, mobile
- SVG is supported and has been supported on all major browsers for years.

**Comment by damithc** [comment]
@domdomegg 
How easy is it to convert from pptx to svg?
How much of a size saving do we get for the images we have?

**Comment by domdomegg** [comment]
Here's IssueLifecycle as svg:
![IssueLifecycle](http://svgur.com/i/tf.svg)

It's less than half the size of the previous image, and now can be easily translated by someone simply opening the file and editing the text, and looks sharp on high-dpi 4k and mobile screens.

To convert it from the pptx to svg I simply opened it up in LibreOffice and clicked `File > Export`, and saved as svg. SVGs can be further compressed using a tool called SVGO, of which there is an easy to use [online GUI](https://jakearchibald.github.io/svgomg/), literally just drag and drop which can shave even more off the size.

**Comment by domdomegg** [comment]
Also SVG images can be embedded directly into the webpage so reduce the number of requests to the server, reducing server strain and further decreasing load time, especially on high latency connections.

**Comment by samsontmr** [comment]
> Also SVG images can be embedded directly into the webpage so reduce the number of requests to the server, reducing server strain and further decreasing load time, especially on high latency connections.

Sounds like it's worth converting and is even simple enough to be a first timer / contributors issue.

**Comment by domdomegg** [comment]
Yea - the pptx to svg ones in docs certainly could be marked for d.FirstTimers. Might be worth creating a batch job in LibreOffice (not sure how, but think it should be possible).

I'm not sure it includes all of them but certainly worth having a look in [`webapp/mockups`](https://github.com/TEAMMATES/teammates/tree/master/src/main/webapp/mockups) as it seems to include a lot of the sources for the files in `webapp/images`. Others might need to be recreated from scratch.

**Comment by samsontmr** [comment]
The ones in `webapp` should be made a higher priority though, since they directly impact TEAMMATES' performance.

**Comment by damithc** [comment]
I have no objections to svg. However, it seems there's no easy way to convert from Microsoft PowerPoint to svg (is there?). I think most of our devs (and me, who deal with the diagrams the most) use Microsoft PowerPoint to draw the diagrams :-p

**Comment by domdomegg** [comment]
I don't have Microsoft PowerPoint so don't know whether there is a similar option in it for sure, but [LibreOffice](http://help.theatremanager.com/book/export/html/3914) (free office suite program) can simply save slides as SVGs, so it seems likely that Microsoft must have that feature tucked away somewhere.

Alternatively there seem to be online sites that convert `pptx` files to `svg` files - although with varying degrees of success.

**Comment by damithc** [comment]
Let's wait to see if there's an easy way to convert diagrams in pptx files to svg. In PowerPoint, user can simply select the part of the diagram that needs to be converted and choose 'save as picture'. However, that feature does not support svg format.
I don't think we can ask users who already has MS Office to install Libre Office (although free).

**Comment by damithc** [comment]
Closing to focus on higher priority issues. Will be reopened later.
