### ISSUE TITLE
Reorder syntax validation instructions in setup guide

### ISSUE THREAD

**Issue by thenaesh** [TEAMMATES/teammates#6722]
In the [setup guide](https://github.com/TEAMMATES/teammates/blob/master/docs/settingUp.md), under the Eclipse section, of Step 4: Set up an IDE, there are instructions to configure indentation and to turn off syntax validation for HTML/JSP.

The instructions for syntax validation require going to `Project → Properties → ...`, which cannot be done until the project has been imported. The indentation configuration instructions (or at least the syntax validation disabling instructions) should therefore come after instructions for importing the project.

**Comment by anu0012** [comment]
Hey, @thenaesh Can I take this issue?

**Comment by thenaesh** [comment]
@anu0012 Sure, no need to ask!
