### ISSUE TITLE
Setup guide: mention the Java path should use '/'

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6723]
**Description of feature/enhancement**
The `settingUp.md` has the following sentence:

> * gradle.properties
If you want to use a JDK other than the one specified in your PATH variable, add the value to the variable org.gradle.java.home. This value must be a valid JDK 1.7 directory.

We may want to mention that Windows users should be careful to use `/` instead of the Windows default `\` (`\` is used if the user copy-pasted the path from Windows explorer to the `gradle.properties`)

**Justification**

Using `\` will cause the Intellij project import to fail.

**Comment by Neurrone** [comment]
Should this be a first timers issue?
