### ISSUE TITLE
Setup guide: Change `Import existing project` to `Import project`

### ISSUE THREAD

**Issue by samsontmr** [TEAMMATES/teammates#6724]
The first bullet point of Step 3 of the [instructions for setting up IntelliJ](https://github.com/TEAMMATES/teammates/blob/master/docs/settingUp.md#intellij-idea) should read:
> Click `Import project` and select the local repository folder.

**Comment by iamsk9** [comment]
@samsontmr I understood the issue. I would like to contribute to this. :100:

**Comment by samsontmr** [comment]
@iamsk9 go ahead and open a pull request :)
