### ISSUE TITLE
New contributor Self-Intro A Sai Krishna

### ISSUE THREAD

**Issue by iamsk9** [TEAMMATES/teammates#6725]
Hello **teammates community**. My name is **Sai Krishna**. I am from India, currently pursuing undergraduate degree in Computer Science Engineering. I have the knowledge and experience working on web applications and mobile apps. During my full semester internship in a startup I worked on developing some LAMP and MEAN applications and hybrid mobile apps. I also contributed some open source projects. I am excited to join this team and looking forward to contribute for this project missions.

a. I couldn't deploy my app on GAE because a problem with my debit card
b. [Link ](https://github.com/iamsk9/teammates)to my fork
c. ![screenshot 16](https://cloud.githubusercontent.com/assets/10477029/23584822/b28afabe-0192-11e7-8b12-d5cfb42072a8.png)

**Comment by samsontmr** [comment]
Hi @iamsk9, welcome to TEAMMATES! You can start by fixing a [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue, then those labelled `d.Contributors`.

Are you planning to apply for GSoC? If you are, please read [our instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true).

**Comment by junhaoyap** [comment]
@iamsk9, welcome to the TEAMMATES community, @samsontmr has kindly given you the information necessary to go further!
