### ISSUE TITLE
Change `File` to `Configure` in Step 2 of instructions for setting up IntelliJ

### ISSUE THREAD

**Issue by samsontmr** [TEAMMATES/teammates#6726]
Change all occurrences of `File` to `Configure` in Step 2 of the [instructions for setting up IntelliJ](https://github.com/TEAMMATES/teammates/blob/master/docs/settingUp.md#intellij-idea).
Example: 
> `File → Settings → Editor → Code Style` should be changed to `Configure → Settings → Editor → Code Style`

**Comment by shubhamnishad97** [comment]
@samsontmr can I fix this issue.

**Comment by samsontmr** [comment]
Sure, just go ahead and open a PR when you've fixed it!

**Comment by Neurrone** [comment]
@shubhamnishad97 if you're already fixing the typo in #6735, remember to only do one first timers issue.

**Comment by shubhamnishad97** [comment]
ok, sorry got confused. I will be focussing on #6375.

**Comment by kumar1005** [comment]
hii.. i am new on github.
can i fix this??

**Comment by vibhorgupta96** [comment]
Seeing that this issue has not been fixed yet, i would like to fix it.
