### ISSUE TITLE
common.js: break into smaller helper scripts

### ISSUE THREAD

**Issue by thenaesh** [TEAMMATES/teammates#6729]
The common.js file is currently a place where all sorts of definitions go, causing immense coupling in the JavaScript front-end. It would be good to modularize everything there and break the file up into smaller pieces.

Some preliminary ideas:
* Check all the reverse-dependencies of every function(/variable) defined in common.js, to find out where each function is mostly used.
* Group the functions into clusters (represented by objects), and export the objects in the style of timezone.js. Example clusters would be `UiModifiers` (all the functions that modify the DOM), `Validation` (the validation/sanitization functions), `TeammatesConstants` (that giant bunch of constants defined at the top (possibly can split this up even more)), etc.
* Ensure that every file explicitly imports the clusters they want to use, instead of relying on the global script inclusion (this will require a bit of bundling to be introduced, though, so may be best left for later).

This will probably be a Herculean refactoring effort, with lots of name qualification that needs to added all over the place. But it would be a good start to improving the modularity of the code, and we can later add explicit imports and bundling when we're moving to ES6.

I'm open to any suggestions or more efficient ways of doing this. @li-kai @Neurrone @whipermr5 @wkurniawan07 @junhaoyap

**Comment by wkurniawan07** [comment]
At the very least we can break it up according to functionality. Imports, requires, and bundles can come later. Constants are actually suggested in #3975, and I'm on the way of introducing the prototype of it in #6615.

`common.js` is indeed a fine specimen of [a God class](https://sourcemaking.com/antipatterns/the-blob).

**Comment by junhaoyap** [comment]
All for it, can't think of any more efficient ways of doing this, it is going to take ```a Herculean effort``` no matter which way we choose :)

The downside of bundling too many generic functions into common.js is that many files require it now without ever using it, some of the things we can think about is whether something really needs to be abstracted, some abstractions really don't add much value and instead adds bloat
