### ISSUE TITLE
Email sent after instructor editing student email: Include submission links for closed sessions

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6730]
**Description of feature/enhancement**

The email that can be sent by instructor after editing student's email should also contain the submission link for *closed* sessions, not just open sessions, but not for sessions awaiting-to-open.

**Justification**

The reasons why students need the link to closed sessions are:

1. to check if submission was saved
1. to be able to email intended responses to instructor (to submit on behalf of the student)

Refer to #5930.

**Comment by AnaghHegde** [comment]
@wkurniawan07 Can i work on this ?.

**Comment by wkurniawan07** [comment]
@AnaghHegde go ahead and submit a fix if you wish, but I'd suggest you to work on your current PRs first.

**Comment by AnaghHegde** [comment]
@wkurniawan07 sure. Since those PRs are in review stage i will be working on this whenever i have time.But i ll open a PR only when the older ones get merged.
