### ISSUE TITLE
Fix typo in AdminHomeJsTest.js

### ISSUE THREAD

**Issue by Neurrone** [TEAMMATES/teammates#6735]
On line 1, we have "QUnit.module('common.js');" - it should be "AdminHome.js" instead.

**Comment by shubhamnishad97** [comment]
Hi @Neurrone im new to this community and Github. Can i solve this issue

**Comment by Neurrone** [comment]
@shubhamnishad97 please go ahead and open a PR :).

Btw, sorry if I was unclear, but the correct string should be "QUnit.module('AdminHome.js');"
