### ISSUE TITLE
Problems with setting up

### ISSUE THREAD

**Issue by AToleuov** [TEAMMATES/teammates#6737]
Hi everybody, I have completed the set-up of the environment. Eclipse shows no errors on compiling, however when I try to access localhost:8888, it doesn't work and the following is printed in the console:
SEVERE: Compilation error
org.eclipse.jdt.internal.compiler.classfmt.ClassFormatException
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:342)
	at org.apache.jasper.compiler.JDTCompiler$1.findType(JDTCompiler.java:206)
	at org.apache.jasper.compiler.JDTCompiler$1.findType(JDTCompiler.java:163)
        .........

**And this:** 
Mar 06, 2017 1:06:08 AM com.google.apphosting.utils.jetty.JettyLogger warn
WARNING: /
org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: 1 in the generated java file
The type java.io.ObjectInputStream cannot be resolved. It is indirectly referenced from required .class files

Stacktrace:
	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:92)
	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:330)
	
**And this:**
Mar 06, 2017 1:06:09 AM org.apache.jasper.compiler.JDTCompiler$1 findType
SEVERE: Compilation error
org.eclipse.jdt.internal.compiler.classfmt.ClassFormatException
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:342)
	at org.apache.jasper.compiler.JDTCompiler$1.findType(JDTCompiler.java:206)
	....
**And this:**
Mar 06, 2017 1:06:09 AM com.google.apphosting.utils.jetty.JettyLogger warn
WARNING: EXCEPTION 
org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: 1 in the generated java file
The type java.io.ObjectInputStream cannot be resolved. It is indirectly referenced from required .class files

Stacktrace:
	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:92)
	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:330)
	....

Actually, I have no idea what is going on here. I have gone over the troubleshooting page, but there was no related problem. I would appreciate any help. Please suggest me where I am doing wrong.

Thank you!

**Comment by samsontmr** [comment]
Hi @AToleuov, perhaps you could provide us with the details specified [here](https://github.com/TEAMMATES/teammates/blob/master/.github/template-helpRequest.md)?

**Comment by junhaoyap** [comment]
@AToleuov we have a page for common troubleshooting, please look for it under our documentation and make sure it is not one that we have detailed there and request for more help in the style that the link @samsontmr has provided

**Comment by AToleuov** [comment]
Hi TEAMMATES community again,
Thank you for your responses @samsontmr and @junhaoyap ! So sorry that I missed the style for help request!

- **Operating System:** macOS Sierra v10.12.3
- **JDK Version:** 1.8.0_101
- **Eclipse Version:** eclipse neon.2 release (4.6.2)
- **Firefox / Chrome Version (where applicable):** Version 56.0.2924.87 (64-bit)

**What I was trying to do / What I need help with**
I was trying to set up the project on my machine. I have gone through all the steps of the guide. No problems occurred in the meantime. Finally I could compile the project and run the web server. But when I tried to access localhost:8888 on a web browser, it just failed. In the console I got the following messages (please see the attached console.txt which contains the full console output): 
[console.txt](https://github.com/TEAMMATES/teammates/files/820711/console.txt)

**Attempts to resolve the problem**
I tried to go over the steps again to double check any missing installations. I tried to change the IDE and do the same process with IntelliJ IDE instead of Eclipse, but the issues remained same.

**Comment by samsontmr** [comment]
@AToleuov TEAMMATES uses Java 7...

**Comment by AToleuov** [comment]
@samsontmr but doesn't it have backward compatibility?

**Comment by samsontmr** [comment]
Unfortunately no, you'll have to install JDK 1.7.x for it to work.

**Comment by AToleuov** [comment]
Will try to change the jdk. Thank you for your help and time!

**Comment by AToleuov** [comment]
@samsontmr Just finished with rebuilding the project with jdk7. Works fine! Please close the issue as solved. Thank you!

**Comment by junhaoyap** [comment]
@AToleuov @samsontmr thanks for clearing it up!
