### ISSUE TITLE
New Contributor Self-Intro Tiffany White

### ISSUE THREAD

**Issue by twhite96** [TEAMMATES/teammates#6738]
- **Link to my app:** e.g. No app currently
- **Link to my fork:** e.g. https://github.com/twhite96/teammates

**Screenshot of changes made (as seen on the UI)**

![Changes](http://d.pr/i/DfL2+)

**Short self-introduction**
My name is Tiffany White and I have a couple years of CS training at the University of Pittsburgh as well as some self-study. I am currently studying Java, JavaScript, Go, and C.

I want to contribute to Teammates as a first timer in OSS. I want to get involved in the community and showcase what I know. It helps future prospective employers, and it is just generally fun.

I'm currently working on learning more JavaScript at Udemy so that I can build a few libraries to Open Source.

**Comment by samsontmr** [comment]
Hi @twhite96, welcome to TEAMMATES! You can start by fixing a [`d.FirstTimers`](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue, then those labelled `d.Contributors`.

Are you planning to apply for GSoC? If you are, please read [our instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true).

**Comment by twhite96** [comment]
Hi @samsontmr. I have a small fix to a `d.FirstTimers` issue but I am trying to get everything set up in my dev environment.

**Comment by junhaoyap** [comment]
Welcome to the TEAMMATES community, @twhite96
