### ISSUE TITLE
Video tour doesn't open on Chrome

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6741]
'Video tour' button doesn't work as expected on Chrome, but seems to work on Firefox.

**Steps to reproduce**

Click on the 'video tour' button in the home page using Chrome 

**Expected behaviour**

Play YouTube video in full screen mode

**Actual behaviour**

Tries to download a file.

**Comment by junhaoyap** [comment]
What Chrome version and OS was tested for this?

I tested this on production, Mac OS Sierra (10.12) and Google Chrome Version 56.0.2924.87 (64-bit) and it works for me ->

<img width="1280" alt="screen shot 2017-03-06 at 3 24 01 pm" src="https://cloud.githubusercontent.com/assets/6291947/23600303/f6b5f542-0280-11e7-9ec9-b10dbf2db311.png">
<img width="1280" alt="screen shot 2017-03-06 at 3 23 50 pm" src="https://cloud.githubusercontent.com/assets/6291947/23600304/f6b62d8c-0280-11e7-8235-d9af9f89c70a.png">

**Comment by damithc** [comment]
I'm using Chrome 56 Windows version. Happened on both my computers and also reported by a user.

**Comment by whipermr5** [comment]
I'm using the same OS and browser as @junhaoyap and I get the video download. I think we should link to https://www.youtube.com/embed/mDtfmNmRwBM?autoplay=1 instead, which is in [official YouTube docs](https://developers.google.com/youtube/player_parameters).

**Comment by AnaghHegde** [comment]
@damithc  I am also using Chrome windows(10 ) version 56.0.2924.87 (64-bit). Its working for me no issues.  I am not able to reproduce the errror.

![temp](https://cloud.githubusercontent.com/assets/12005551/23620239/3105a810-02bc-11e7-8529-74a2f7eab96f.PNG)

![capture](https://cloud.githubusercontent.com/assets/12005551/23620244/3ab70322-02bc-11e7-8390-d551df74af91.PNG)

**Comment by Mynk96** [comment]
@damithc actually the problem comes when Adobe Flash player plugin in chrome is not always allowed to run ,then it downloads a .swf file.
If it is allowed, then it runs as expected.
![capture](https://cloud.githubusercontent.com/assets/17481466/23638059/581a7540-0305-11e7-9726-137be033a11f.PNG)

**Comment by damithc** [comment]
Thanks for investigating this issue @junhaoyap @whipermr5 @AnaghHegde 
Looks like it doesn't affect most users. Still, may be safe to use the normal YouTube link?

**Comment by Mynk96** [comment]
@damithc can we just embed the youtube video ,something like this
![capture2](https://cloud.githubusercontent.com/assets/17481466/23640506/374e401c-0314-11e7-9b80-f862824e70b4.PNG)
user can change to fullscreen if he wants to

**Comment by damithc** [comment]
Sorry, forgot to thank @Mynk96 
Um, not sure I want to embed the video in the page just yet, unless we redesign the page to fit it in.

**Comment by AnaghHegde** [comment]
@damithc how about just uploading the video in YouTube and giving link. It solves the plugin problem as well as redesigning of the page .

**Comment by damithc** [comment]
> how about just uploading the video in YouTube and giving link.

It's already on Youtube. Just need to give the link.

**Comment by AnaghHegde** [comment]
ok . So its fine right rather than using api or changing the page design ?

**Comment by AbhishekChd** [comment]
@damithc The youtube flash has been [deprecated](https://developers.google.com/youtube/flash_api_reference). Although it is supported in most cases, for all users we must embed the video and rather make the frame size large if possible and the user can make it full screen if he/she wishes to.

**Comment by shivanshsoni** [comment]
@damithc  I think if his (Always allowed to run) is not checked we can redirect him to chrome://plugins/ to check it So he can never get any problem . We can give  a popup message to check (Always allowed to run).

**Comment by whipermr5** [comment]
Changing the link to https://www.youtube.com/embed/mDtfmNmRwBM?autoplay=1 will address the flash issue. It looks like the best solution right now.
