### ISSUE TITLE
Instructor edit feedback path: clicking on first level options makes the menu disappear

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6744]
**Problem:**
This is how the user is supposed to use the feature:
![image](https://cloud.githubusercontent.com/assets/1673303/23613757/b82be490-02bb-11e7-8a4d-645802fc646f.png)

However, if the user clicks on the first level option instead of hovering, the menu disappears. Some users are confused by this and claims 'cannot change the feedback path'.

**Suggested solution:**

To be discussed

**Comment by damithc** [comment]
Categorizing it as a `c.Bug` because I can't phrase it as an enhancement until we know the solution. It's a UIX bug in some sense.

**Comment by amarlearning** [comment]
@damithc Not able to recreate that error. working fine in my case.

**Comment by damithc** [comment]
> Not able to recreate that error. working fine in my case.
> Which browser are you using ?

I updated the issue description. The original could have been misleading. Try again. It's not an error, just a UX quirk that confuses some users.

**Comment by amarlearning** [comment]
@damithc I think that behavior is totally fine because as soon as the user hovers on the first level option, the second level option appears. 

As you said in the issue description
> However, if the user clicks on the first level option instead of hovering, the menu disappears. Some users are confused by this and claims 'cannot change the feedback path'.

I don't think anybody can click on the first level option without hovering it, and if they hovers they get to see the second level option. I think no change is required in this case.

Let me know your views on that

**Comment by damithc** [comment]
That's what I thought too, but some users got confused by it (perhaps they think clicking is compulsory, as was the case in older menu systems). No harm fixing it if it can be done without a lot of effort.

**Comment by amarlearning** [comment]
@damithc If you have any idea on "How to fix that". Let me know, I will do that! :smile:

**Comment by damithc** [comment]
How to fix In the code? I have no idea.
In terms of UX, we can just ignore clicks on the first level menu.

**Comment by damithc** [comment]
Closing in favor of #6095
