### ISSUE TITLE
Make feedback submission page to use AJAX

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#6745]
As suggested by @damithc, sometimes the form post for feedback submission may get errors (Maybe due to high traffic in TEAMMATES and thus the process time exceed 60s). In this case, student will be redirected to an error page and the feedback will not be stored successfully. It is not a good user experience as users lost their submission.

A solution to this would be to replace the form post to AJAX. Even if a error happens in the server, students won't lost their data and they can just resubmit the feedback again.

**Comment by xpdavid** [comment]
I have try some experiments. Here are some observations and I want to discuss with @damithc @wkurniawan07 and @li-kai 

The most intuitive solution would be to make the redirect URL into JSON format. AJAX get the data and use `window.location.href` to redirect it. However, this is not possible in current design in TEAMMATES (correct me if I am wrong). The final url will be determined at the very last step in `executeAndPostProcess()` in `Action`. Therefore, there is no way for pageDate to access the final url during `execute()` in `Action` (`execute()` method is in `executeAndPostProcess()` method).

I have came out two solutions.
1. We use the AJAX to pass the status messages and we use JS to put the status messages to indicate whether the submission of feedback is success or not at the same page. (If we do this, we lost the ability to redirect users to different pages after submission, currently student will be redirect to student home page after submission of feedback)

2. This is more like tricky solution. As indicated in [here](http://stackoverflow.com/questions/9177252/detecting-a-redirect-in-jquery-ajax), it's impossible for AJAX to catch the redirection. So how about we just follow the redirection and replace everything in current page with the content.

**Comment by li-kai** [comment]
I don't think the AJAX solution is the best. It does not prevent cases where the user may accidentally press back or close the tab/window.

There already [libraries](http://garlicjs.org/) in js that can do what we want. Underneath it just persists data to [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Storage/LocalStorage). It's somewhat easier compared to solutions suggested earlier too 😄

**Comment by xpdavid** [comment]
@li-kai I am talking about the case where the response time exceed 60 seconds and the request get killed (and the instance in GAE also get killed, which may affect all the users who uses this instance). Users may lost all their submission data in this case.

Of course, if you have better solution. I will leave it to you to decide :)

**Comment by li-kai** [comment]
I see. In that case, that is much trickier. I'm afraid I'm not so familiar with the inner workings of GAE yet. Let's discuss this on thurs?

**Comment by wkurniawan07** [comment]
Resolved in V7.
