### ISSUE TITLE
TEAMMATES logo displaced

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#6746]
This is the current view on the live server when logged in:

<img width="457" alt="screen shot 2017-03-07 at 12 13 14 am" src="https://cloud.githubusercontent.com/assets/6811428/23618500/73360568-02cb-11e7-9516-137564015f5a.png">

**Comment by Dartteon** [comment]
I'm not too sure if this is the solution -

I found that the navBar classes in the various pages' `.tag` files are inconsistent. The landing page's one, `staticPage.tag` correctly references the TEAMMATES image, while the rest (admin, instructor, student) do not - they simply have the string TEAMMATES inside the <a>tag.

The fix I'm suggesting would be to standardize all the `.tag` pages to correctly reference the TEAMMATES image like in `staticPage.tag`.

p.s I'm not really familiar with .tag files, as I haven't worked with them before. Are they generated via something like gulp/webpack, or do they function just like normal js files?

**Comment by whipermr5** [comment]
@Dartteon Nice work investigating the problem! Yup that is indeed the solution I was envisioning. You can go ahead and update the `.tag` files in a PR. To my knowledge they aren't generated, but function like `.jsp` files.

**Comment by wkurniawan07** [comment]
@Dartteon `.tag` is not a JS template; it's an extension of [JSP](https://www.tutorialspoint.com/jsp/).

**Comment by amarlearning** [comment]
@wkurniawan07 @whipermr5 I would like to take this one. Let me know if anyone else is not working.

**Comment by Dartteon** [comment]
@amarlearning I'm fixing this in https://github.com/TEAMMATES/teammates/pull/6836
