### ISSUE TITLE
Change `Play` to `Run...` in development.md

### ISSUE THREAD

**Issue by samsontmr** [TEAMMATES/teammates#6752]
The word `Play` under `Starting the dev server` (line 60 of `development.md`) should be changed to `Run...`.

**Comment by JessDF** [comment]
Hello, I'm knew to open source projects/ bug errors and I was wondering a few things:

- What does c.DevOps and p.Low stand for?

I am interested in fixing this bug if no one else has fixed it.

**Comment by wkurniawan07** [comment]
@JessDF go ahead and submit a PR :slightly_smiling_face:

As for those labels, [this will answer your question](https://github.com/TEAMMATES/teammates/blob/master/docs/issues.md#issue-labels). Different projects use labels differently.

**Comment by JessDF** [comment]
@wkurniawan07 , Do you know if there are any other run->play's that need to be changed to run->run?
