### ISSUE TITLE
AdminActivityLogPageAction: remove inline javascript

### ISSUE THREAD

**Issue by Neurrone** [TEAMMATES/teammates#6754]
The HTML being returned uses inline javascript in some places. E.g

```java

// the "Search More" button to continue searching from the previous fromDate
        status.append("<button class=\"btn-link\" id=\"button_older\" onclick=\"submitFormAjax("
                      + nextEndTimeToSearch
                      + ");\">Search More</button>...
```

Binding to the DOM should be done in `AdminActivityLog.js` instead, and required parameters supplied by data-* attributes. 

Will work on this after https://github.com/TEAMMATES/teammates/pull/6733 and https://github.com/TEAMMATES/teammates/pull/6524 are done.

**Comment by xpdavid** [comment]
@Neurrone Should be after #6524 rather than #6531.

**Comment by Neurrone** [comment]
Thanks @xpdavid.

**Comment by wkurniawan07** [comment]
Done some time while doing #6961.
