### ISSUE TITLE
Help Request: Don't know how to update code from Eclipse to GAE

### ISSUE THREAD

**Issue by ZhaoDingfan** [TEAMMATES/teammates#6756]
- **Operating System: macOS Sierra 10.12.3**
- **JDK Version: Java 1.8.0**
- **Eclipse Version: Eclipse Neon**
- **Firefox / Chrome Version (where applicable): Chrome latest version**

**What I was trying to do / What I need help with**
I was trying to deploy my code from Eclipse to GAE. According to the instruction to new contributors, there should be a deploy button at the end. However, I didn't see that button. Also I don't know how GAE works so that I cannot understand the link between a project of GAE and my source code in Eclipse.

**Attempts to resolve the problem**
Instead, I just ran it on my localhost and it works. Thus, I upload the file that contains source code to GAE directly. Surprisingly, it works. The problem is that I don't see any place for me to update my code in GAE. 

P.S. Can anyone introduce the working mechanism of GAE? Thanks a lot!

**Comment by AnaghHegde** [comment]
@ZhaoDingfan 
>**JDK Version: Java 1.8.0**

You should use JDK 1.7 i assume by mistake you typed 1.8.

![capture](https://cloud.githubusercontent.com/assets/12005551/23686329/02779c92-03cf-11e7-9d37-5f95ceb8ebbb.PNG)
 
Can you see the icon at the top with `g` that is deployment button.

**Comment by wkurniawan07** [comment]
@ZhaoDingfan I hope I answer the correct part of "working mechanism" for you.

PaaS like Google App Engine, Heroku, and AWS Elastic Beanstalk provides virtual machines for your code to run on. They do their work by setting up the necessary environment, server, database, and what nots, you do your work by supplying the code. They are not code editors or IDEs (or at least, not yet, but I don't see they ever will be) so you cannot modify your code in-place; instead you update the code by the method of deployment.

**Comment by ZhaoDingfan** [comment]
Thanks for your replies!
@wkurniawan07 Do you mean that once I wanna update my code I just deploy my code to GAE again?

**Comment by tarun14110** [comment]
@ZhaoDingfan yes, you need to deploy the code again to see the updated changes.
