### ISSUE TITLE
New contributor self intro- Van

### ISSUE THREAD

**Issue by SmokinClove** [TEAMMATES/teammates#6774]
a) Link to my app: https://teammates-van.appspot.com
b) Link to my fork: https://github.com/SmokinClove/teammates
c) A screenshot of the change you did (as seen on the UI)
I adjust the padding of the word TEAMMATES such that it will align better with the rest of the header items (changed padding:0 to padding-left:0)
Before
![teammates1](https://cloud.githubusercontent.com/assets/12591759/23786515/79f5b6e8-05a8-11e7-99b0-2a5cb066c7e5.PNG)

After
![teammates2](https://cloud.githubusercontent.com/assets/12591759/23786608/fc15fc00-05a8-11e7-89a0-b42b45cc3337.PNG)

d) Real name and a short self-intro
Hello World,
I am Nguyen Tuong Van, a year 3 CS student. I love (not in any specific order) cats, coffee, programming and anything to do with music.
Thanks!

**Comment by samsontmr** [comment]
Hey Van! Welcome to TEAMMATES XD You can start by fixing a [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue, then those labelled `d.Contributors`.

Are you planning to apply for GSoC? If you are, please read [our instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true).
