### ISSUE TITLE
Random test fail in *LogicTest.java recently

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#6777]
There are test failures on Travis or Appveyor for `*Logic` recently. This may be caused by #6655, which use `dependsOnGroup` to control the order of test cases.

**Comment by shivanshsoni** [comment]
Can I work on this issue?
@xpdavid

**Comment by xpdavid** [comment]
@shivanshsoni This issue got PR already. You may want to find [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors) Issues to work on.

**Comment by shivanshsoni** [comment]
OKK
