### ISSUE TITLE
New contributor self intro Brandon Wayne Odiuwuor

### ISSUE THREAD

**Issue by BrandonOdiwuor** [TEAMMATES/teammates#6782]
- **Link to app**: https://teammates-brandon.appspot.com

- **Link to fork:** https://github.com/BrandonOdiwuor/teammates.git

- **Screenshot of changes made (as seen on the UI)**
![teammates-tinker](https://cloud.githubusercontent.com/assets/15610188/23796202/a4ea8f16-0591-11e7-9fdb-b204aa78f645.png)

- **Real name and a short self-intro**
Hello teammates,
My name is Brandon Wayne Odiwuor a junior majoring in Computer Science at Ashesi University College. I am so much pleased with the vision of teammates to become a training ground for software engineering students like me who have the theorotical understanding of software engineering principles but have not had the opportunity to see their practical application. I am looking forward to working with you people over my summer vacation to solidify my understanding of Web application development with Google App Engine which I am currently studying at Udacity.

**Comment by Neurrone** [comment]
Hi @BrandonOdiwuor 

welcome to TEAMMATES! You can start by fixing a [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue, then those labelled [d.Contributors](https://github.com/TEAMMATES/teammates/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20label%3Ad.Contributors%20).

Are you planning to apply for GSoC? If you are, please read [our instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true).
