### ISSUE TITLE
Changing logic for function in datepicker.js.

### ISSUE THREAD

**Issue by Mynk96** [TEAMMATES/teammates#6783]
`function getMaxDateForVisibleDate(startDate, publishDate) {
    var minDate = 0;

    if (publishDate === null || publishDate === undefined) {
        minDate = startDate;
    } else if (startDate > publishDate) {
        minDate = publishDate;
    } else {
        minDate = startDate;
    }

    return minDate;
}`
Comparing startDate and publishDate and return minimum between them seems vague as publishdate always has to be >= startDate.

**Comment by Mynk96** [comment]
maxVisibleDate should be <= startDate

**Comment by anu0012** [comment]
Hey, @Mynk96 I am a beginner so can I start with this issue?

**Comment by xpdavid** [comment]
> Hey, @Mynk96 I am a beginner so can I start with this issue?
@anu0012 Please find d.firstTimer issue to start your first PR :)

> Comparing startDate and publishDate and return minimum between them seems vague as publishdate always has to be >= startDate.
@Mynk96 So are you going to make it more general? Like a function to return the minimum date?

**Comment by Mynk96** [comment]
Actually what i think there are two problems 
1) 
![capture-3](https://cloud.githubusercontent.com/assets/17481466/23822491/71466508-0673-11e7-87fb-e11e27a25034.PNG)

The instructor in the above case should not be allowed to select 10 as response visible date as before startDate,no response will be there to view. 

2)
Due to above i.e. (publishDate can be less than startDate),the getMaxVisibleDate compares startDate and publishDate to get minimum of the two and the assigns to maxVisibleDate which can be selected in the datepicker.

So instead of using the function we could fix visibleDate as always <= startDate and publishDate always >= startDate...
after changes it looks like this:
![capture-4](https://cloud.githubusercontent.com/assets/17481466/23822655/3010a694-0677-11e7-9d94-a2d3c3dcd650.PNG)

**Comment by xpdavid** [comment]
@Mynk96 Good catch. Currently the system allow this situation.
______________________________________________________________________________
^Visible from              ^Response visible from(publish)       ^Opening time

**Comment by Mynk96** [comment]
@xpdavid So can I create a pr request to solve this issue?

**Comment by xpdavid** [comment]
Let's wait how @damithc talk about this.

**Comment by Mynk96** [comment]
@xpdavid okay

**Comment by damithc** [comment]
@Mynk96 It is possible to have responses even if the start date has not reached yet. That is because the start date can be changed after a session is open. So it is possible to have a session with responses published (visible to students) yet the start date is in the future.

**Comment by Mynk96** [comment]
@damithc I got it,but sholdn't max visible date be always <= startDate?

**Comment by damithc** [comment]
@Mynk96 

> @damithc I got it,but shouldn't max visible date be always <= startDate?

Not necessarily. Consider a scenario where an instructor has a session that periodically lets student update responses (e.g. he opens it every week Fri-Sat) but allows student to view current responses all the time. That mean on Wednesday the start time is in future but responses collected in the previous week are visible.

Note that normally we don't want to complicate software just to accommodate very rare use cases. But TEAMMATES' main strength is supposed to be flexibility, so I don't want to impose the suggested restrictions unless allowing it creates far too much complexity for us.
