### ISSUE TITLE
New contributor self intro Tan Li Hao

### ISSUE THREAD

**Issue by LiHaoTan** [TEAMMATES/teammates#6792]
a) [Link to my app](https://teammates-lihaotan.appspot.com/)
b) [Link to my fork](https://github.com/LiHaoTan/teammates)
c) **UI Change: Make request form fullscreen**
![request form change](https://cloud.githubusercontent.com/assets/13617389/23824151/5b6765d2-06ac-11e7-9b00-ab59daea1865.png)

d) **Self-Intro**
Hi, I am Li Hao, a year 2 Computer Science student from NUS. I am not the strongest student around but I hope to contribute something useful to open source projects. I have benefitted a lot from open source projects from learning from the code to using the free tools and I think OSS are really great. It is still too idealistic for everything in the world to be free, but I look forward to a future where there is no need to have a price tag on anything. At the moment, I am hoping AI can head in the right direction to free people from many things they do not want to do.

I am new to contributing to open source projects and am currently exploring TEAMMATES.

**Comment by thenaesh** [comment]
Hi @LiHaoTan, welcome to TEAMMATES! Nice and useful change you have there! :)

You can start by fixing some [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issues, and then move on to [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors).

If you're planning to apply for GSoC, do check out our [instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true).
