### ISSUE TITLE
Emails sent to students: include contact details of the course owners

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6805]
**Suggestion** :
When emailing students (e.g submission opening email), we can include contact details of the course owners so that students can contact the course owner if they have questions about the session, to confirm the email is legit, or report errors in student data (e.g. assigned to the wrong team).

**Justification** :
This will ease the admin workload because currently students write to TEAMMATES admin when they have questions/problems regarding a session.

**Comment by mshehrozsajjad** [comment]
I would like to work on this.

**Comment by damithc** [comment]
@mshehrozsajjad go ahead

**Comment by HirdayGupta** [comment]
@damithc would you like these contact details to be included across all Feedback Session-related emails? Or do you have some specific ones in mind?

**Comment by damithc** [comment]
> @damithc would you like these contact details to be included across all Feedback Session-related emails? Or do you have some specific ones in mind?

All of them.

**Comment by HirdayGupta** [comment]
Okay. And would you like the contact details of all course co-owners to be included?

**Comment by damithc** [comment]
Good question. yes, all co-owners.

**Comment by HirdayGupta** [comment]
@damithc while checking which instructors' emails to include, does it need to be verified if they've joined or not?

**Comment by damithc** [comment]
> @damithc while checking which instructors' emails to include, does it need to be verified if they've joined or not?

Good question. I guess no need.
