### ISSUE TITLE
Explicitly specify mode and padding scheme when using Ciphers

### ISSUE THREAD

**Issue by Neurrone** [TEAMMATES/teammates#6806]
In StringHelper when using AES, only "AES" is specified when requesting a cipher with Cipher.getInstance(). Parameters such as the mode and padding scheme are unspecified, so the JDK implementation's defaults are used.

According to [this page,](https://stackoverflow.com/questions/6258047/java-default-crypto-aes-behavior) Oracle's JDK7 uses "AES/ECB/PKCS5Padding"; it would be better if we specified this explicitly, after ensuring that this are the parameters being used now. 

Applies to other places too where encryption might be used, if any.

**Comment by tainansv** [comment]
[This page](http://download.java.net/jdk7u8/docs/technotes/guides/security/crypto/CryptoSpec.html) says that the standard parameter is really this you said "AES/ECB/PKCS5Padding".

**Comment by Neurrone** [comment]
@tainansv is really what? The page is very long, could you mention the specific section? 

Yup, hence why I said that the defaults being used needs to be checked just to be sure.

**Comment by tainansv** [comment]
In the section 'generating a pair of keys', subsection 'creating a cipher' says:
'The standard algorithm name for AES is "AES", the standard name for the Electronic Codebook mode is "ECB", and the standard name for PKCS5-style padding is "PKCS5Padding".'

**Comment by Neurrone** [comment]
@tainansv Yes, but look at the next paragraph. Copying this example from the page,

```java
    Cipher aesCipher;
    
    // Create the cipher
    aesCipher = Cipher.getInstance("AES/ECB/PKCS5Padding");
```

What we have is
```
    aesCipher = Cipher.getInstance("AES");
```

Notice the mode of operation and padding scheme is not specified, so the defaults for the implementation are used; would be better to specify explicitly.

**Comment by tainansv** [comment]
So we use explicitly "AES/ECB/PKCS5Padding", since it is the default, right?

**Comment by Neurrone** [comment]
Almost. We still need to check if this setting is really being used now by teammates (just to be sure). Then if so, specify it explicitly, yeah.

**Comment by sujeet14108** [comment]
@Neurrone Is this issue still open to solve ?

**Comment by Neurrone** [comment]
@sujeet14108 yup

**Comment by sujeet14108** [comment]
@Neurrone  Ok on it.

**Comment by sujeet14108** [comment]
@Neurrone Do we just need to change "AES" to "AES/ECB/PKCS5Padding" ?

**Comment by Neurrone** [comment]
Not quite. There's a way of printing out the default cipher parameters being used; if its confirmed it uses the default of "AES/ECB/PKCS5Padding", then yes.

**Comment by Neurrone** [comment]
Actually, best to write tests too to verify that when explicitly specifying these parameters, its doing the same thing as just saying AES. Google uses its [own custom java runtime](https://cloud.google.com/appengine/docs/java/). Unlikely that its defaults are different, but better safe than sorry.
