### ISSUE TITLE
New contributor self intro [Sandeep Choudhary]

### ISSUE THREAD

**Issue by Skchoudhary** [TEAMMATES/teammates#6808]
a)[link to my app](https://teammates-skchoudhary.appspot.com/)
b)[link to my fork](https://github.com/Skchoudhary/teammates)
c) **UI Change: Solve Table overflow in adminHomePage**
Before:
![teammatebug](https://cloud.githubusercontent.com/assets/15611967/23873526/5eebb2be-0858-11e7-8cdf-d7cc0ee9727e.jpg)
After:
![teammatefull](https://cloud.githubusercontent.com/assets/15611967/23873547/69d2dec8-0858-11e7-8579-d530f823937c.jpg)

d)**Self-Intro**
Hola TEAMMATES,
My name is Sandeep Choudhary and I am final year Computer Science student from India.I am a Developer|Hacker|Explore .I have little bit experience of open source world and great admire of FOSS culture.So now I am on my way to be part of such cool community and contribute to FOSS.To start that GSOC is great place and TEAMMATES is great project because to _for student and by student_.

Hoping to be part of great team and learning some new things out which help me to increase my code quality.

Cheers!

**Comment by Neurrone** [comment]
Hi @Skchoudhary, welcome to TEAMMATES!

You can start by fixing some [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issues, and then move on to [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors).

Sounds like you're planning to apply for GSoC. If so, do check out our [instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true).

**Comment by Skchoudhary** [comment]
Hi @Neurrone 
I have already fix my d.FirstTimers issues and looking forward to d.contributors.

**Comment by junhaoyap** [comment]
@Skchoudhary welcome to the TEAMMATES community!

Great job on your first timer issue, do remember to look at the GSoC instructions as soon as you can to familiarize with the process as you seem to interested in GSoC!
