### ISSUE TITLE
Project setup: eliminate the need to modify config file manually after `./gradlew setup`

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#6812]
Currently, there are some manually steps after running `./gradlew setup`

> `src/test/resources/test.properties`
> Append a same unique id (e.g your name) to each of the default accounts found at the bottom of this file, e.g change test.student1.account=alice.tmms to test.student1.account=alice.tmms.KevinChan.

It's redundant to ask developers to append the unique id. So maybe we just use `alice.tmms.JohnDoe` for everyone.

In addition, as reported in #6810, GodMod may fail if `app.student.motd.url` is not set properly.

How about we just make `app.student.motd.url` set to `test-student-motd.html` in `./gradlew setup`

**Comment by damithc** [comment]
From what I remember, the requirement to add a unique suffix to test accounts is from pre-travis era when reviewer was supposed to run tests for the new code. This requirement ensures that both dev and reviewer do not use the same test account credentials (if they do, hard coded test account credentials in test html files will go unnoticed). Not sure if the same reasoning is still applicable.

**Comment by xpdavid** [comment]
@wkurniawan07 What do you think?

Account credentials now are not hard coded into test html files anymore. Every time when html comparison is needed, HtmlHelper will inject test properties to the test html.

**Comment by damithc** [comment]
> Every time when html comparison is needed, HtmlHelper will inject test properties to the test html.

Don't forget the situation where a dev adds a new test html file which contains a hard coded test account instead of a placeholder variable. We need way to detect that situation.

**Comment by xpdavid** [comment]
That's true.
1. If the guy uses GodMod to generate test html, placeholder will be inserted and everything will be fine.
1. If the guy just does this by himself, write hard-coded html, since everyone use the same `alice.tmms.JohnDoe`, he will pass the test cases. The only way to find this problem is to run test cases against staging sever (as we use real google id instead).

**Comment by damithc** [comment]
Probably @wkurniawan07 needs to weigh in as he is the expert on GodMode. One option is to force CI to use different test accounts from others devs, then it can catch any hard-coding problems.
