### ISSUE TITLE
New contributor self intro Nikiforos Botis

### ISSUE THREAD

**Issue by nikiforosbotis** [TEAMMATES/teammates#6815]
1)[Link to my app](http://teammates-nikiforos.appspot.com/index.jsp)
2)[Link to my fork](https://github.com/nikiforosbotis/teammates)
3)UI change: enhance the appearance of the "Terms of Use" page by adding emphasis and bullets:
![termsofuse](https://cloud.githubusercontent.com/assets/9116253/23892809/d2686c5e-08a4-11e7-9d54-a41087654947.png)

4)**Self Intro**
Dear All,
My name is Nikiforos Botis and I am an undergraduate student at the [Department of Management Science and Technology](http://aueb.gr/index_en.php) at [AUEB](http://aueb.gr/index_en.php). I am also an alumnus of [UCL](http://www.ucl.ac.uk/) in which I studied Management Science and Innovation for a semetster. I have recently started to be involved in programming and I consider contributing to such an Open Source project as an ideal way of acquiring experience and adding valuable things at the community.

I really hope I will make an impact on TEAMMATES project since it is a very good idea for CS students.

Thank you!

**Comment by xpdavid** [comment]
Hi @LiHaoTan, welcome to TEAMMATES! Nice and useful change you have there! :)

You can start by fixing some [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issues, and then move on to [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors).

If you're planning to apply for GSoC, do check out our [instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true).

**Comment by nikiforosbotis** [comment]
Dear @xpdavid . 
Is the referenced name that is welcomed (LiHaoTan) misplaced or should I do anything else in order to be welcomed?
Thank you,
Nikiforos

**Comment by xpdavid** [comment]
@nikiforosbotis Wrong name. Sorry. Are you planning to apply for GSoC?

**Comment by nikiforosbotis** [comment]
@xpdavid thank you for your reply. Yes, I do plan to apply for GSoC but I feel it's better to first do some additions to this project in order to familiarize with TEAMMATES and then to apply. What do you think?

**Comment by junhaoyap** [comment]
@nikiforosbotis welcome to the TEAMMATES community!

That is indeed true, we recommend you look through the process when you have time to familiarize yourself with the timeline so you do not miss the application deadlines etc!

**Comment by nikiforosbotis** [comment]
@junhaoyap Thank you for your interest! I have already in mind that there is a deadline in the GSoC applications.
