### ISSUE TITLE
Navbar showing contents behind it

### ISSUE THREAD

**Issue by yash2o1o** [TEAMMATES/teammates#6823]
**Environment**
LocalHost
http://localhost:8888/admin/adminEmailComposePage
Master branch is up-to-date with upstream.

**Steps to reproduce**
Clicking on the collapsed navbar button on /admin/adminEmailComposePage .

**Expected behaviour**
![bug1](https://cloud.githubusercontent.com/assets/19612017/23945819/00409030-099e-11e7-98ee-362da251629d.png)

**Actual behaviour**
![bug](https://cloud.githubusercontent.com/assets/19612017/23945830/058d89ee-099e-11e7-82da-a69b41bbb696.png)

**Comment by wkurniawan07** [comment]
Confirmed at ce0e1d3.

**Comment by xpdavid** [comment]
@yash2o1o If I am not wrong, delete the line in https://github.com/TEAMMATES/teammates/blob/9fe3aa5710c3ab7caaebc37a4c8e19d2f25ee124/src/main/webapp/js/adminEmail.js#L10 and everything should be fine.

This code is magically introduced in #3075 according to `git blame`
```
$('.navbar-fixed-top').css('zIndex', 0);
```

Feel free to submit PR for this :)

**Comment by yash2o1o** [comment]
@xpdavid great. I will submit the PR. I have completed one first timer issue so would that be fine?

**Comment by xpdavid** [comment]
Please don't, as we want to leave enough first-timers issues for new developers.

**Comment by yash2o1o** [comment]
@xpdavid okay :)
