### ISSUE TITLE
DataNucleus Enhancer error upon opening project

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#6835]
This error shows up as soon as eclipse is opened -

![data-nucleus-enhancer-error](https://cloud.githubusercontent.com/assets/11662001/23996563/d9f5063c-0a73-11e7-84e6-af71b4a3e614.JPG)

**Comment by VamsiSangam** [comment]
This shows up on the UI when trying to login as admin..

![3](https://cloud.githubusercontent.com/assets/11662001/24079359/48c2fc38-0cac-11e7-876d-4f79aedd686c.JPG)

The console shows these error messages -

![1](https://cloud.githubusercontent.com/assets/11662001/24079363/54087fb4-0cac-11e7-89a4-723ce5d20b93.JPG)
![2](https://cloud.githubusercontent.com/assets/11662001/24079364/5a8025ea-0cac-11e7-9924-2ecc75d804e8.JPG)

**Comment by samsontmr** [comment]
For the second error, try running the `clean` Gradle task. I remember this happening to me before.

**Comment by VamsiSangam** [comment]
I had my project specific settings related to ORM enhancement incomplete. Following instructions from [ide-usage.md](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-usage.md) solved the issue.
