### ISSUE TITLE
Different types of styles/fonts used in staticAnalysis.md

### ISSUE THREAD

**Issue by AnaghHegde** [TEAMMATES/teammates#6843]
Take a look the image below.

![imageedit_5_5777107652](https://cloud.githubusercontent.com/assets/12005551/24031947/506fe524-0b0b-11e7-8785-5171acde2b19.gif)

This is not the only one. It's also repeated. I think its better to use only one format, may be the 2nd one is better instead of using `#` . It's happening because of the missing space.

**Comment by xpdavid** [comment]
Confirm in 9168d13, It turns out there should be a space between `#####` and title name.
e.g.

######Configuring Checkstyle Eclipse plugin (wrong way)

###### Configuring Checkstyle Eclipse plugin (Correct way)

**Comment by AnaghHegde** [comment]
@xpdavid I think it was there earlier also i guess. In the commit  8db7d17 where IntelliJ support was added. In that case also it was present.

**Comment by samsontmr** [comment]
@xpdavid This can be a first timer issue once it's defined more clearly.

**Comment by AnaghHegde** [comment]
Yeah, as only spaces has to be removed.

**Comment by xpdavid** [comment]
> Yeah, as only spaces has to be **added**.
@AnaghHegde Maybe you want to provide more details so that other developers can work on it?

**Comment by AnaghHegde** [comment]
In the `[staticAnalysis.md](https://github.com/TEAMMATES/teammates/blob/master/docs/staticAnalysis.md#tool-stack)` page the space missing in some of the sub headings. They are as follows 

- #####Configuring Checkstyle Eclipse plugin

- #####Suppressing Checkstyle warnings

For example  : 
actual    #####Configuring Checkstyle Eclipse plugin
expected  ##### Configuring Checkstyle Eclipse plugin 

To correct this add a space between `####` and next word.

**Comment by AnaghHegde** [comment]
@xpdavid In the same page

```#####Suppressing PMD warnings To introduce code that violates PMD rules, use @SuppressWarnings("PMD.RuleName")
```

It should be like this 

##### Suppressing PMD warnings

To introduce code that violates PMD rules, use @SuppressWarnings("PMD.RuleName")

Shall i open a new issue or will track this one also in the same issue ?.

**Comment by damithc** [comment]
> Shall i open a new issue or will track this one also in the same issue ?

Given that we are short of d.FirstTimer issues, it's fine to have one issue per file (but not one issue per each typo). If the typos are in the same file, one issue can cover all of them.

**Comment by sravi4701** [comment]
I want to work on this issue. How should I get started?

**Comment by AnaghHegde** [comment]
Hi @sravi4701 . Before you work on the issue, please follow our [Contributor Orientation Guidelines](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md).
