### ISSUE TITLE
Review the client scripts

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6845]
A large number of client scripts, particularly data migration ones, are now irrelevant because they were already run (although admittedly I do not know which ones). Maintaining them is the same as maintaining dead code and is [a non-trivial maintenance burden](http://stackoverflow.com/questions/15699995/why-unused-code-should-be-deleted).

If the purpose is to show devs how to create scripts, it has not served its purpose well because variations are everywhere.

For scripts still used: need proper documentation.

**Comment by samsontmr** [comment]
> For scripts still used: need proper documentation.

Second this.

**Comment by wkurniawan07** [comment]
@damithc may I know which ones of the scripts are still regularly run, or at least still used within the past year?

**Comment by damithc** [comment]
> may I know which ones of the scripts are still regularly run, or at least still used within the past year?

Will do.

**Comment by damithc** [comment]
Confirmed can be deleted:
```
AddSectionsToLargeCourses
DataMigrationAppendInstitutionForAccounts
DataMigrationForInstructorsCourseArchiving
DataMigrationForIsArchivedAttribute
DataMigrationForResponseRate
DataMigrationForSearchableInstructors
DataMigrationForSearchableStudents
DataRepairForCorruptedResponses
InstructorStudentInstitueMigrator
ModifyInstituteOfStudentsInCourse
RepairFeedbackSessionNameWithExtraWhiteSpace
RepairFeedbackSessionResponseRate
RepairStudentsWithDuplicateEmail
```

The rest need further examination.
