### ISSUE TITLE
New contributor self intro Sai Teja

### ISSUE THREAD

**Issue by saitj99** [TEAMMATES/teammates#6850]
a) link to your app - https://teammates-sai.appspot.com/
b) link to your fork - https://github.com/saitj99/teammates
c) a screenshot of the change you did (as seen on the UI)
**BEFORE**
<img width="701" alt="screen shot 2017-03-17 at 7 01 39 pm" src="https://cloud.githubusercontent.com/assets/20525497/24066958/e4741b08-0b44-11e7-8599-1dbfada915a9.png">

**AFTER**
<img width="748" alt="screen shot 2017-03-17 at 7 02 14 pm" src="https://cloud.githubusercontent.com/assets/20525497/24066919/83f0634a-0b44-11e7-885f-d7d5dbfaaee6.png">

Edited 'errorPage.tag' to make pageNotFound.jsp consistent with rest of the app.
d) your real name and a short self-intro
My name is Sai Teja and I'm revisiting web programming after a couple of years. Kudos to everyone for a great job with the orientation and induction documentation, it took me less than a day to learn and start working.

**Comment by Neurrone** [comment]
Hi @saitj99, welcome to TEAMMATES!

Happy to hear you found the documentation helpful :)

You can start by fixing some [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issues, and then move on to [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors).

If you're planning to apply for GSoC, do check out our [instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true).

**Comment by junhaoyap** [comment]
@saitj99 welcome to the TEAMMATES community!

Do make sure to check out the GSoC process if you're going for it!
