### ISSUE TITLE
Remove useless replacement of text in AdminActivityLogPageActionTest

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#6857]
We should remove this line in `AdminActivityLogPageActionTest`.

https://github.com/TEAMMATES/teammates/blob/06e464953e3e7ab33e806701f9547240354b159f/src/test/java/teammates/test/cases/action/AdminActivityLogPageActionTest.java#L453

```
actualMsg = actualMsg.replace("<mark>", "").replace("</mark>", "");
```

This is because in #6524, the highlight in log message is moved to JS (front-end) part.

**Comment by amarlearning** [comment]
@xpdavid can i take this one ?
