### ISSUE TITLE
Update V4.m to reflect new website as at V4.49+

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#686]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on March 10, 2013 12:20:04_

V4.m (the version we used when we take the app offline for maintenance) still shows older home page design. It needs to reflect the website as at 4.49.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=687_

**Comment by wkurniawan07** [comment]
No longer relevant?

**Comment by damithc** [comment]
Still relevant. We haven't taken the app offline in a long time but that is not to say we never will.

**Comment by damithc** [comment]
Old issue. closing.
