### ISSUE TITLE
Issue Title: Help Request: Run Local Tests - IntelliJ

### ISSUE THREAD

**Issue by jimmyshephard** [TEAMMATES/teammates#6860]
- **Operating System: Ubunti 16.04 LTS
- **JDK Version: 1.7.0_80
- **IntelliJ Version: 2016.2.5

**Need to be able to run local tests, can run CI tests on command prompt**
Setup the project and gotten to use the application, register instructor, a couple of students, works fine. 
It's clear how to get CI tests running on the command line, there's a task ciTests but can't figure out how to run just local tests, docs say
Run tests using the configurations under Run --> Play but don't see anything relevant there

Here's a screen shot of my run options

![screenshot from 2017-03-18 16-58-54](https://cloud.githubusercontent.com/assets/18121985/24076369/873ae9e0-0bfc-11e7-8527-9ecb7a28d594.png)

**Comment by jimmyshephard** [comment]
Decided to go with Eclipse. Can run CI as well as local tests without a problem there.

**Comment by samsontmr** [comment]
There's currently an issue where IntelliJ wipes out the .idea folder (where the run configs are stored) when you import the project. You'll need to restore them from git after importing the project
