### ISSUE TITLE
Teammates logo not aligned properly

### ISSUE THREAD

**Issue by amarlearning** [TEAMMATES/teammates#6861]
Teammates logo on [this](https://teammatesv4.appspot.com/page/studentHomePage) page is not aligned properly, as seen in this image.

![screenshot from 2017-03-19 04-33-56](https://cloud.githubusercontent.com/assets/9383897/24077074/05ff6426-0c67-11e7-90b5-6287ee37a7b6.png)

Let me know if I can take this up :smile:

**Comment by xpdavid** [comment]
Is this the same as #6746, @amarlearning Remember to search before post issue :P

**Comment by amarlearning** [comment]
Closing this issue, because of this #6746
