### ISSUE TITLE
New contributor self intro "Amar Prakash Pandey"

### ISSUE THREAD

**Issue by amarlearning** [TEAMMATES/teammates#6862]
**Link to my app:** Not deployed my app, because I don't have an international credit card. :disappointed: 
**Link to my fork:** [Link](https://github.com/amarlearning/teammates)

**Screenshot:**
![screenshot from 2017-03-19 06-30-10](https://cloud.githubusercontent.com/assets/9383897/24077305/e0cfb11c-0c6e-11e7-9fa8-0707a4fbcd01.png)

**Introduction:**
Hello,
My name is Amar Prakash Pandey, a senior year undergraduate student pursuing the bachelor of technology degree in Computer Science and Engineering. I am an Open Source Community Member at DuckDuckHack, the open source community of DuckDuckGo.

_I would like to contribute to the Teammates organization through the project "Student Data UI upgrade". It would be great if someone can guide me further. :smile:_
 
Website: http://www.amarpandey.me

**Comment by samsontmr** [comment]
Hi @amarlearning , welcome to TEAMMATES! You can start by fixing a [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue, then those labelled `d.Contributors`.

Are you planning to apply for GSoC? If you are, please let us know and read [our instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true).

**Comment by junhaoyap** [comment]
@amarlearning welcome to the TEAMMATES community!

@samsontmr I think ```I would like to contribute to the Teammates organization through the project "Student Data UI upgrade"``` is a GSoC project, @amarlearning please go through the instructions as per the link that @samsontmr has provided!
