### ISSUE TITLE
In MobileView, text inside the menu is aligned on right side.

### ISSUE THREAD

**Issue by amarlearning** [TEAMMATES/teammates#6864]
Text inside the menu in mobile view is aligned to `right side`. Not sure whether it's a feature or a bug?

![screenshot from 2017-03-19 07-19-40](https://cloud.githubusercontent.com/assets/9383897/24077493/ea2841d8-0c74-11e7-8c9a-c0e624c9e121.png)

**Comment by wkurniawan07** [comment]
@li-kai for your clarification, whether this is this a conscious decision or not.

**Comment by li-kai** [comment]
@wkurniawan07 Yep it is. The button is on the right so I'd expect the text to be on the right as well.

**Comment by amarlearning** [comment]
@wkurniawan07 @li-kai I think it will look better if they were aligned to the left side. Just a suggestion.
Let me know what you think.

**Comment by li-kai** [comment]
@wkurniawan07 Right now I think this is an issue on mobile because the inner and outer navigations are not consistent. Any opinions?

**Comment by wkurniawan07** [comment]
@li-kai I have no strong opinion on this. You can have your say.

**Comment by li-kai** [comment]
@amarlearning Go ahead and make them left aligned. :D
