### ISSUE TITLE
New Contributor Self-Intro: [James Murithi]

### ISSUE THREAD

**Issue by jimmyshephard** [TEAMMATES/teammates#6866]
- **Link to my app:** https://teammates-jamesmurithi.appspot.com
- **Link to my fork:** https://github.com/jimmyshephard/teammates

**Screenshot of changes made (as seen on the UI)**

![fixed-col-overflow](https://cloud.githubusercontent.com/assets/18121985/24078072/83e8da70-0c30-11e7-8aea-9a9ee32e0b44.png)

**Short self-introduction**
Hi, I'm James and I found team mates to be a project whose domain I could easily identify with and comprehend. My background is Computer Science, would like to be part of a team that's working on a project that's making a difference in education as well as training in Software Development. This is my first succesful attempt in setting up for an open source project, thanks to the awesome docs, hope to eventually introduce others to this

**Comment by Neurrone** [comment]
Hi @jimmyshephard, welcome to TEAMMATES!

Happy to hear you found the documentation helpful :)

You can start by fixing some [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issues, and then move on to [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors).

If you're planning to apply for GSoC, please let us know, and check out our [instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true).

**Comment by junhaoyap** [comment]
@jimmyshephard, welcome to the TEAMMATES community!

@Neurrone has given a very good rundown on what the next possible steps could be!

Looking forward to seeing your contribution, James!

**Comment by jimmyshephard** [comment]
Thank you @Neurrone and @junhaoyap
