### ISSUE TITLE
Development Workflow: Explicitly state that contributors should not create multiple PRs for a single issue

### ISSUE THREAD

**Issue by samsontmr** [TEAMMATES/teammates#6867]
Contributors should not be opening multiple PRs for the same issue (e.g. Closing a PR and creating a new one). Doing this makes it difficult to keep track of past reviews/comments on the PR. We should consider stating this explicitly in our development workflow document.

**Comment by samsontmr** [comment]
As an aside, we can also consider including an obvious list of do's and dont's for PRs to help us manage the recent influx of new contributors better ([checkstyle's](https://github.com/checkstyle/checkstyle/wiki/PR-rules) is a good example).

**Comment by wkurniawan07** [comment]
I just read the process document again and guess what, [it actually is there](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#updating-the-pr).

> If you are tasked to update your PR either by Travis CI or by your reviewer, there is no need to close the PR and open a new one. You will simply make and push the updates to the same branch used in the PR, essentially repeating step 3.

I wouldn't mind making it more obvious in any way, though.

**Comment by samsontmr** [comment]
Appropriate FirstTimers issue? :P
