### ISSUE TITLE
Forbid 'use strict' directive in ES6 code

### ISSUE THREAD

**Issue by thenaesh** [TEAMMATES/teammates#6870]
Since ES6 module code is strict by default, there is no need for strict mode directives. Forbidding it in the ESLint rules can help catch accidental `'use strict;'`s lying around, so it's one less thing for reviewers to worry about.

**Comment by junhaoyap** [comment]
👍 @thenaesh I suppose we can close this issue?

**Comment by thenaesh** [comment]
Yep, can close.
