### ISSUE TITLE
Need some more details related to "Student Data UI upgrade" project

### ISSUE THREAD

**Issue by amarlearning** [TEAMMATES/teammates#6878]
Hello,

My name is Amar Prakash Pandey, a senior year undergraduate student pursuing the bachelor of technology degree in Computer Science and Engineering. I am an Open Source Community Member at DuckDuckHack, the open source community of DuckDuckGo.

I would like to contribute to the Teammates organization through the project _"Student Data UI upgrade"_. I need some more information related to **"**Student Data UI upgrade**"** project. It would be great if someone can guide me further.

Website: http://www.amarpandey.me

Kind regards. :smile:

cc: @wkurniawan07

**Comment by damithc** [comment]
@amarlearning what specific questions do you have about the project idea? Do you have an idea about the current state of the 'Student enrollment' feature?

**Comment by amarlearning** [comment]
@damithc I saw the `video tour` in which it shows how students are being enrolled. The instructor has the copy the data from the excel sheet and then he/she has to paste that data into the textbox.
Please let me know if I am missing out on anything?

I have two question related to this project:

1. Features to consider
2. Any specific language or framework for this project? 

Kind Regards.

**Comment by damithc** [comment]
@amarlearning 

> I saw the video tour in which it shows how students are being enrolled. The instructor has the copy the data from the excel sheet and then he/she has to paste that data into the textbox.

Yes, that's right. You can try it yourself after setting up a local copy of TEAMMATES.
 
> I have two question related to this project:
> Features to consider
> Any specific language or framework for this project?

Actually, we expect you to 'propose' answers to these questions in your proposal. :-)

**Comment by amarlearning** [comment]
@damithc Submitted my draft proposal on the GSoC site. Please review it.

**Comment by damithc** [comment]
@amarlearning Comments added to the proposal.

**Comment by amarlearning** [comment]
@damithc Thank you for the response  :smile:
I am not getting free time due to my exams so I am not sure about my another proposal. But I'll try to submit proposal for `Coverage Hero (JavaScript)`

Kind Regards

**Comment by junhaoyap** [comment]
Was informed that GSoC proposal deadline is over, if you need any help with any of the development procedures, please open a new issue on GitHub!
