### ISSUE TITLE
GSoC 2017 New Contributor Introduction

### ISSUE THREAD

**Issue by vineetkumarr260** [TEAMMATES/teammates#6881]
Hello TEAMMATES Team,
I am Vineet Kumar, a second-year student enrolled in Mechanical Engineering at Delhi Technological University, Delhi, India.
I am really looking forward to contribute to TEAMMATES project through or beyond GSoC'17.
Java is my most preferred language and I have experience in Java and Android development. I have also some experience with front-end web development technologies (HTML, CSS, Javascipt). Thus, I want to be a part of the project. Kindly guide me on how to get started with the project.
I hope this counts a valid proposal and humbly request the concerned mentor to guide me, so that I could quickly get started with making useful contributions to the TEAMMATES Open Source Development Community.

**Comment by thenaesh** [comment]
Hi Vineet, please read our developer guides, starting [here](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md). That will get you started with making a new contributor self-introduction. Follow the links within that page wherever necessary, and most importantly, follow all instructions to the letter (especially regarding tooling versions).

After that, you may proceed to solve an issue labelled `d.FirstTimers` (don't solve more than one of these) and `d.Contributors`. Avoid those marked `d.Committers`, as those typically require in-depth knowledge of the codebase and already have a development plan.

As for GSoC, check out our [instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true).
