### ISSUE TITLE
Moving non-production reusable code to test.driver package

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#6886]
There are methods in utility classes of `common.util` package which are only used by test classes and not in production code. These methods can be moved to appropriate/new classes in `test.driver` package instead to avoid mixing production and non-production code. 
Helper classes and methods in `teammates.client.scripts.util` can also be moved to test.driver package to put non-production reusable code all in a single package.

**Comment by VamsiSangam** [comment]
Can I work on this issue?

**Comment by sujeet14108** [comment]
@VamsiSangam  Actually i am working on this issue and would make a pull request by tonight.

**Comment by VamsiSangam** [comment]
Ok cool. Will move to another issue then. Good luck :smile:
