### ISSUE TITLE
Rubric questions: show summary excluding self-evaluation

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6887]
**Feature**: Instructor/student viewing results of a rubric question

**Current state**: stats shown in summary table includes self ratings
Example (from instructor side):
![image](https://cloud.githubusercontent.com/assets/1673303/24099061/85d1de58-0da8-11e7-8a59-9aca83a46e2d.png)

**Suggestion**: provide a way to view stats excluding self ratings as well

**Justification**: some users have requested for this feature.

**Comment by tshradheya** [comment]
Working on this

**Comment by tshradheya** [comment]
Prof @damithc I have a query regarding this, when the instructor is viewing results and then goes into `excluding self` mode, are all responses given by 
- student A to A hidden?
or
- by the instructor hidden?

**Comment by damithc** [comment]
> Is it just all responses given by A to A?

Yes, that's correct.
