### ISSUE TITLE
Fix infinite redirects when serving unknown URLs

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#6889]
**Environment**

Live server at `V5.98`

**Steps to reproduce**

Visit http://teammatesv4.appspot.com/abc

**Expected behaviour**

Fail gracefully with a 404 status code and error page

**Actual behaviour**

![screen shot 2017-03-20 at 10 42 45 pm](https://cloud.githubusercontent.com/assets/6811428/24105147/fbc1d49a-0dbe-11e7-855d-1391e79a1496.png)

**Comment by Dartteon** [comment]
Is this bug able to be replicated on localhost? Somehow, I just get redirected to Error 404 page upon invalid URLs. (I'm on latest master)

**Comment by whipermr5** [comment]
Need staging server to replicate; it seems like an issue with GAE's default handler servlet.

**Comment by HirdayGupta** [comment]
Found some threads facing a similar issue:
- A (temporary?) workaround is suggested in an answer at StackOverflow [here](I will verify if this works after sorting out a billing problem on my staging server)(http://stackoverflow.com/questions/12293934/google-app-engine-endless-redirect-with-a-filter-mapped-to). 
- A possible (but vaguely worded) solution is on the comment by "gk" [here](https://groups.google.com/forum/#!topic/google-appengine-java/eU4OmLWjX10).

@whipermr5 take a look at them and see if you find any of them viable. Will get started working on it once you revert.

**Comment by whipermr5** [comment]
@HirdayGupta The first one looks viable :)
