### ISSUE TITLE
Footer text "Hosted on Google App Engine" cut off

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#6890]
When viewing full width in Chrome on my 13" Macbook Pro, `Engine` is hidden as it wraps to the next line:
![screen shot 2017-03-20 at 10 48 27 pm copy](https://cloud.githubusercontent.com/assets/6811428/24105556/33edb2ac-0dc0-11e7-995b-2fd0fc6c6ed9.png)

When resized slightly smaller, only `Google` shows:
![screen shot 2017-03-21 at 12 02 49 am copy](https://cloud.githubusercontent.com/assets/6811428/24109015/5f6ebb9c-0dca-11e7-9ae4-bbf1cfd21cb5.png)

Smaller than that activates the mobile layout, where everything shows fine.

**Comment by amarlearning** [comment]
@whipermr5 I would like to work on this

**Comment by damithc** [comment]
@whipermr5 can this be a d.FirstTimer issue?

**Comment by whipermr5** [comment]
@damithc I'm okay, but that would mean @amarlearning cannot work on it. @amarlearning can let others work on this?

**Comment by amarlearning** [comment]
@whipermr5 @damithc yeah, sure! 😊

**Comment by mshehrozsajjad** [comment]
@whipermr5  Can I work on this?
