### ISSUE TITLE
Google Summer of Code Question

### ISSUE THREAD

**Issue by sanket0354** [TEAMMATES/teammates#6893]
***** INFORMATION ON GOOGLE SUMMER OF CODE PROJECT IDEAS *****
I want to have a free account, as i am planning to submit a proposal as part of Google Summer of Code, so just going through the Web application in understanding its basic features and get an idea of what features if added will be useful for the application to grow. I have already submitted a free account request.

**Comment by samsontmr** [comment]
@sanket0354 you can actually set up the dev server locally and explore to your heart's content :)

**Comment by sanket0354** [comment]
Thanks for the quick reply. Can you help me locate a doc or something towards dev-env setup. I am really looking forward towards this project :)

**Comment by damithc** [comment]
@sanket0354 either of these links in our README should lead you to documentation on how to set up TEAMMATES locally.

![image](https://cloud.githubusercontent.com/assets/1673303/24131213/2fab5d26-0e28-11e7-9ab0-10846453e8ff.png)

**Comment by sanket0354** [comment]
Thanks. I appreciate you quick reply! :) I will let you know once i set it up and if i have any questions or problems concerning the set up.

**Comment by sanket0354** [comment]
That was easy to setup. Clean Documentation and setup :)
Now I have the app up and running. 

So one question, i am trying to login as instructor,

I have this in test.properties, 
**test.instructor.account=teammates.coord
test.instructor.password=anypassword**

i tried using the account name as email but it says user not found, will the username be something else ?

**Comment by AnaghHegde** [comment]
I think [this](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#logging-in-to-a-teammates-instance) will help you.

**Comment by sanket0354** [comment]
Everything is working fine :)
Can you please help me getting started through a small issue that i can solve before submitting the proposal that will help me increase my chance in getting the proposal accepted?

**Comment by AnaghHegde** [comment]
For GSOC please follow our [Instructions for GSoC Applicants
](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true) page. For contribution first do the [`d.FirstTimers`](https://github.com/TEAMMATES/teammates/labels/d.FirstTimers) but only one then go with the [`d.contributor`](https://github.com/TEAMMATES/teammates/labels/d.Contributors).
