### ISSUE TITLE
New contributor self intro: Muhammad Shehroz Sajjad

### ISSUE THREAD

**Issue by mshehrozsajjad** [TEAMMATES/teammates#6899]
a. **Link to my app :**   https://teammates-mshehroz.appspot.com
b. **Link to my fork :**   https://github.com/mshehrozsajjad/teammates

c. **Screenshot of the change Idid (as seen on the UI) :**

> Fixed Overflow Issue when adding new instructor on Admin Page.

![teammates](https://cloud.githubusercontent.com/assets/19376792/24124362/2e2263c0-0de5-11e7-8625-c81d4cac1563.JPG)

d.**Short Introduction :**
     Name: Muhammad Shehroz Sajjad
     Intro: Hi, I am currently studying BS Computer Science from National University of Science & Technology, Islamabad. I have done web development and designing for over a year in php,.net and java. I have recently started contributing to open source projects to improve my skills. I want to contribute to Teammates. I would like to improve the GUI of Teammates in future. You can see my portfolio <a href="http://mshehrozsajjad.me/">here</a>.

**Comment by Neurrone** [comment]
Hi @mshehrozsajjad, welcome to TEAMMATES!

You can start by fixing some [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issues, and then move on to [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors).

If you're planning to apply for GSoC, let us know, and check out our [instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true).

**Comment by mshehrozsajjad** [comment]
Yes, I am planning to apply for  GSoC.
