### ISSUE TITLE
Admin: home page: fix data row overflow

### ISSUE THREAD

**Issue by mshehrozsajjad** [TEAMMATES/teammates#6900]
**Environment**
Local Dev Server

**Steps to reproduce**
When we add details of a new instructor and get response row is overflowed.
![teammates](https://cloud.githubusercontent.com/assets/19376792/24125516/e396807e-0dea-11e7-89bd-2789bbb863e3.JPG)

**Expected behaviour**
It should be inside the table.

**Actual behaviour**
Data is overflowing out of table.

I want to work on this issue.

**Comment by amarlearning** [comment]
@leeyimin Is anyone working on this issue?

**Comment by rclakmal** [comment]
Discussion [here ](#4845) would help anyone who takes up that issue

**Comment by amarlearning** [comment]
@rclakmal Thanks for this!

**Comment by DaemonWill** [comment]
Currently under review : 

![image](https://cloud.githubusercontent.com/assets/28215667/25990180/cc841a80-36cc-11e7-9cfb-ffe8ff5a1f49.png)

I included a link for the join url as mentioned in #4112

**Comment by kyleaolson** [comment]
No work on this in a while so I thought I'd take a stab at it. As stated in the PR, I was able to get the URL to wrap with this:
```html
<td style="word-wrap: break-word;min-width: 160px;max-width: 160px;">long long comments</td>
```
from here: https://stackoverflow.com/questions/21587813/bootstrap-responsive-table-content-wrapping

But since it's difficult to break URLs without it looking really choppy, I went with the cleaner approach (IMO) of just adding a name for the link.

**Comment by bjrodrig** [comment]
Can I work on this issue? 

I followed the discussion on issue #4845 and created the same modification that mukesh14149 created. 
<img width="623" alt="admin add instructor overflow - join link" src="https://user-images.githubusercontent.com/29617046/33800583-ce6de840-dd10-11e7-872c-001f1da571e0.PNG">

I noted that there was a request to add a test to check that the actual link matched the expected url.
I added this code to AdminHomePage.java:
`public String getJoinLink(String messageText) {
        WebElement link = browser.driver.findElement(By.linkText("[Join Link]"));
        return link.getAttribute("href");
    }`
I added this test to AdminHomePageUiTest.java
`assertEquals(expectedjoinUrl, homePage.getJoinLink(homePage.getMessageFromResultTable(2)));`
I also modified the original tests with the new message in the results table and got that to work.
`assertEquals("Instructor AHPUiT Instrúctör WithPlusInEmail has been successfully created [Join Link]",
                homePage.getMessageFromResultTable(2));`

All the CI Tests were working when I ran them this afternoon. I haven't done static analysis yet.

**Comment by LiHaoTan** [comment]
@bjrodrig sure, please go ahead. We don't require that you ask so if you want to let others know you are working on an issue, you can leave a note.

Also, I suggest not updating your progress on the issue tracker unless you need or want to promote discussion. It would save everyone's time by presenting just the final solution :).
