### ISSUE TITLE
New Feature: Video should be played on the same page

### ISSUE THREAD

**Issue by amarlearning** [TEAMMATES/teammates#6901]
Instead of pointing the URL to youtube, we can design an interface via javascript through which video can be played on the same page. Everything at the back goes dull and video comes up, something like this:

![screenshot from 2017-03-21 05-58-46](https://cloud.githubusercontent.com/assets/9383897/24127557/8d34b4d8-0dfb-11e7-9b2e-bf56decb219c.png)

Let me know your thoughts on this ?

**Comment by nikiforosbotis** [comment]
@amarlearning I agree with that. I had noticed it as well but I did not open an issue. Do you want me to have a try?

**Comment by damithc** [comment]
Hmmm, it can be nice but not sure if there is a big benefit to doing so. Perhaps our efforts are better spent on improving higher-impact areas, such as user documentation?

**Comment by nikiforosbotis** [comment]
@damithc This is the results I take when I press "Video Tour":
![a](https://cloud.githubusercontent.com/assets/9116253/24242139/259c23d4-0fb7-11e7-8cb9-4b2564366b51.png)

**Comment by damithc** [comment]
Closing to focus on higher priority issues. Will be reopened later.
