### ISSUE TITLE
Checking response rate of an empty course gives an error

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6903]
v5.99

Steps:
* Go to instructor home page
* Click 'Show' of a session that doesn't have any students

Actual: 
Error message shown (see example)
![image](https://cloud.githubusercontent.com/assets/1673303/24130805/9fc24f82-0e25-11e7-904d-cee10270c90d.png)

Expected:
Show `0/0` ?

**Comment by nikiforosbotis** [comment]
@damithc Can I take over that issue? I have already made an issue labeled d.FirstTimers with success and I want to move on to the next level.

**Comment by damithc** [comment]
Sure, go ahead @nikiforosbotis

**Comment by nikiforosbotis** [comment]
Dear @damithc 
I tried to see the problem that you refer to in my dev server but (when followed the instructions) the result I got was this:
![a](https://cloud.githubusercontent.com/assets/9116253/24200203/a5806534-0f0c-11e7-95a2-9ec2a92e4b94.png)

which is the correct state. Does this problem appear only on the web application and when running locally does not exist? Or has it stopped being happening now?

**Comment by damithc** [comment]
I noticed this behavior in a course of an actual user.  But I can't reproduce this by myself. The user has added students to the course since then, so I cannot reproduce it using that course either. 
Let's close this for now. I'll reopen if it crops up again.

**Comment by damithc** [comment]
@nikiforosbotis Thanks for investigating by the way. 👍

**Comment by nikiforosbotis** [comment]
@damithc I would just like to find the bug and correct it. It is not a problem. If you notice that error again, please let me know in order to fix it.
