### ISSUE TITLE
Reorganize dev docs

### ISSUE THREAD

**Issue by samsontmr** [TEAMMATES/teammates#6906]
As brought up by @li-kai and a few of us during our last discussion, the files in the `docs` folder (in fact, possibly even the sections within the files themselves) need to be reorganised for better navigability. We will need do this soon so we can better manage the influx of potential GSoC applicants. 

On a somewhat related note, we should probably also explicitly lay down standards for commit messages that contributors should adhere to. This is so that reviewers waste less time trying to decipher the commits, and can instead spend their time more fruitfully.

**Possible solutions** (not mutually exclusive, and up for discussion)
* Table of Contents needs to be reorganised
  * Each section/file as a list item instead of sentences with embedded links
  * I really like how [matplotlib's developer guide](http://matplotlib.org/devel/) is organised.
* Files can be reorganised into a tree structure instead of the current flat one.

**Comment by AbhayGoyal** [comment]
Hey I am a first timer. May i know what is the issue that needs to be addressed.

**Comment by whipermr5** [comment]
@AbhayGoyal You may want to start with a `d.FirstTimers` issue :)

**Comment by wkurniawan07** [comment]
Closing as there is a lack of direction for this issue.
