### ISSUE TITLE
Extract checking of page result destination in action tests as a method

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#6909]
Many action tests does checks for page result destination to see if it matches the expected ViewUri,  expected user and error parameters.
For example in InstructorCourseDetailsPageActionTest, lines 36 and 37.
```
assertEquals(Const.ViewURIs.INSTRUCTOR_COURSE_DETAILS + "?error=false&user=idOfInstructor1OfCourse1",
                     pageResult.getDestinationWithParams());
```
This can be extracted as a util method in BaseActionTest so that each assertion do not have to construct the entire expected destination string themselves. All action tests should be refactored to use the extracted method.

**Comment by sujeet14108** [comment]
In a single action class sometimes 3 (Uri, error, userId) and sometimes 4(Uri, error, userId, courseInfo) parameters are used. So to solve this we should implement abstract method of variable parameters in each action class?

**Comment by leeyimin** [comment]
@sujeet14108 I believe there might be no need to implement a separate method for each action class. The needed string usually follows a certain format of `viewUri + "?error=" + error + "&user=" + userId `. We can implement this method in BaseActionTest and make all the tests use this method from BaseActionTest. For the four variable case, we can overload the same method.

**Comment by sujeet14108** [comment]
@leeyimin  Okay on it.
