### ISSUE TITLE
New Contributor Self-Intro: Kumaranath Fernando

### ISSUE THREAD

**Issue by wkk91193** [TEAMMATES/teammates#6912]
Hi!

I'm a third-year student of Informatics Institute of Technology Sri Lanka.I went through the list of ideas for the year and  is interested in  contributing to the  project 'Performance Hero'.

I browsed through [Contributor Orientation Guide ](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md), forked and cloned the repository.  I was wondering  as  to  where I could find code implementation on the JDO backend?

Any help on this is appreciated!

Regards,
Kumaranath Fernando

**Comment by Neurrone** [comment]
Hi @wkk91193, welcome to TEAMMATES!

The [storage section of the design document](https://github.com/TEAMMATES/teammates/blob/master/docs/design.md#storage-component) might be useful.

You can start by fixing some [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issues, and then move on to [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors).
