### ISSUE TITLE
GSoC 2017: Usability Hero 

### ISSUE THREAD

**Issue by AnamikaD** [TEAMMATES/teammates#6913]
Is this project still available? If yes,  how may I contribute to it? Who are the mentors?

**Comment by damithc** [comment]
> Is this project still available? 

All projects available until they are assigned to a student, which happens during GSoC selection period.

> If yes, how may I contribute to it? 

You can submit a proposal for it.

> Who are the mentors?

If you have questions about the project, you can ask here.

**Comment by AnamikaD** [comment]
@damithc Thank you!
