### ISSUE TITLE
Running data migration script for sanitized data in AdminEmailAttributes

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#6917]
In fixing #6625, html sanitization of data in AdminEmailAttributes before saving is removed and data is sanitized when displayed. Current data of AdminEmailAttributes in database needs to be desanitized so that it will be displayed and sent out correctly, which can be done by running DataMigrationForSanitizedDataInAdminEmailAttributes.java.

**Comment by whipermr5** [comment]
@damithc I'm guessing the script has been run and this issue can be closed?

**Comment by damithc** [comment]
Not yet. will do soon. We usually delay the the data migration for at least one more version in case we have to roll back the current version due to some problem.

**Comment by damithc** [comment]
done
