### ISSUE TITLE
Numbering issue in troubleshooting-guide.md 

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#6920]
![image](https://cloud.githubusercontent.com/assets/6365864/24209157/7968d928-0f60-11e7-925e-da57830517c8.png)
Sections [Common setup errors and solutions](https://github.com/TEAMMATES/teammates/blob/master/docs/troubleshooting-guide.md#common-setup-errors-and-solutions) and [Common test errors and solutions](https://github.com/TEAMMATES/teammates/blob/master/docs/troubleshooting-guide.md#common-test-errors-and-solutions) in troubleshooting-guide.md have formatting issues which results in repeated numbering.

**Comment by wkurniawan07** [comment]
@leeyimin, you may want to investigate and escalate the issue to some other documentation files as well. This is a result of a tinker from GitHub's side: https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown.

**Comment by saching97** [comment]
@leeyimin @wkurniawan07  As far as I can see, this problem also exists in Steps 2 and 3 of Setting Up ([https://github.com/TEAMMATES/teammates/blob/master/docs/settingUp.md](url)), while the other documents remain unaffected. I would like to take this issue up as a "FirstTimer".
