### ISSUE TITLE
InstructorFeedbackResultsDownloadActionTest have unnecessary duplications

### ISSUE THREAD

**Issue by ablyx** [TEAMMATES/teammates#6924]
There seems to have unnecessary duplication among the `verifyFileContent` methods that can be refactored to make it clearer.

**Comment by s0lidarity** [comment]
Hey, I'm new as an open source contributor, but I'd like to work on this issue. How do I go about helping?

**Comment by ablyx** [comment]
You can look at the file `InstructorFeedbackResultsDownloadActionTest.java` and see if you can do any refactoring for the `verifyFileContent` methods.

**Comment by wkurniawan07** [comment]
Closing as the issue scope is not clear.
