### ISSUE TITLE
Benchmarking mechanism for the JDO backend

### ISSUE THREAD

**Issue by wkk91193** [TEAMMATES/teammates#6931]
I'm keen to know if there 's a benchmarking mechanism already in place for the JDO backend? since this could help me in planning the proposal for "Performance hero" project. 

Thanks in advance

**Comment by damithc** [comment]
Do don't have any performance/scalability benchmarks for the backend at the moment. 
On a related note, pay attention to given priority values in the project ideas list. Higher priority project ideas are more likely to be chosen compare to lower priority ones, all other things being equal.
