### ISSUE TITLE
Error while enrolling student: The team ID should be unique 

### ISSUE THREAD

**Issue by AnaghHegde** [TEAMMATES/teammates#6932]
I was trying something and i noticed this. I used the data given in the xl sheet.
![screenshot 89](https://cloud.githubusercontent.com/assets/12005551/24259430/dba9ce88-1016-11e7-8a10-1ee345e7dd8b.png)

And when i change the Team id then 
![screenshot 90](https://cloud.githubusercontent.com/assets/12005551/24259610/644c3596-1017-11e7-8e38-ea685f4d6ccc.png)

Later i used a different data and i got this 
![screenshot 86](https://cloud.githubusercontent.com/assets/12005551/24259631/79d96dd4-1017-11e7-9782-091c1ed613c3.png)

**Comment by wkurniawan07** [comment]
- First and second screenshots: Teams named "Team 1", "Team 2", "Team 3" might have already existed in some other section in that course. Take note that the error message has specified it clearly: that the team ID should be **unique across the entire course** and **a team name cannot be spread across multiple sections**.
- Third screenshot: Take a look at your first column. Very likely you're missing the `Section |` divider.

**Comment by AnaghHegde** [comment]
>the team ID should be unique across the entire course and a team name cannot be spread across multiple sections.

I will look into it.

>Third screenshot: Take a look at your first column. Very likely you're missing the Section | divider.

I know that but i am talking about the error message. It should give message saying that `Section` header is missing. I also tried with other headers and i am getting proper error messages.

**Comment by AnaghHegde** [comment]
Missing Team
![captureteam](https://cloud.githubusercontent.com/assets/12005551/24275646/0828d234-1057-11e7-87cb-3f830818e8e5.PNG)

Missing Email
![captureemail](https://cloud.githubusercontent.com/assets/12005551/24275656/17b72b2e-1057-11e7-930f-0b3f529529e1.PNG)

Missing Name 
![capture1](https://cloud.githubusercontent.com/assets/12005551/24275661/1e874b14-1057-11e7-8509-5fcbae0a7dc5.PNG)

**Comment by wkurniawan07** [comment]
There is no requirement that the first column must be "Section". Things like `Team | Email | Section`, `Email | Comments | Section | Team`, and all sorts of variations are acceptable.
However, the missing column cases for "team", "email", and "name" are different because they are required fields for enrolling students. A missing section is acceptable; enrolling a team without section will simply result in enrollment to a section named "None".
