### ISSUE TITLE
AllJsTests failing on the live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6935]
v5.100
21 cases fail

![image](https://cloud.githubusercontent.com/assets/1673303/24281144/3eee5b56-1091-11e7-8d55-a13bc94c99b3.png)

**Comment by damithc** [comment]
@thenaesh @li-kai @wkurniawan07

**Comment by wkurniawan07** [comment]
Does this persist after a few runs?

**Comment by damithc** [comment]
Yes, tried many times using eclipse and intellij. I'm using FF38, if that has any relevance.

**Comment by damithc** [comment]
Passes on dev server using the same FF38.

**Comment by wkurniawan07** [comment]
Can the same test be attempted at V5.99? I managed to reproduce it even as far back as V5.98.

It seems like something was changed in the live server that the coverage library is not allowed to read the production files anymore.

**Comment by damithc** [comment]
Yes, fails at v5.99 too.

**Comment by wkurniawan07** [comment]
Can try at V5.95 or anything that's further back? I'm pretty sure the problem exists but need to verify.

**Comment by damithc** [comment]
Passes at v5.95

**Comment by wkurniawan07** [comment]
As it turns out in V5.95 all JS tests are done via local file. So the earliest trace of this strange failure should be from V5.96 which I also have confirmed.
This should not be a great concern (at most one can just remove the Blanket library).

**Comment by damithc** [comment]
OK, i'll ignore this failure for the purpose of deploying v5.100
