### ISSUE TITLE
New Contributor Self-Intro: Sachin Gopal

### ISSUE THREAD

**Issue by saching97** [TEAMMATES/teammates#6936]
- **Link to my app:** http://teammates-sachin.appspot.com/
- **Link to my fork:** https://github.com/saching97/teammates/tree/tinker

**Screenshot of changes made (as seen on the UI)**
![screenshot](https://cloud.githubusercontent.com/assets/24409931/24291364/9e3fd7ac-10ae-11e7-9c0f-305482fe7661.JPG)
I have tried to make the layout more easy on the eye and more streamlined. Comments are highly welcome!

**Short self-introduction**
Hello everyone! My name is Sachin Gopal and I'm a Computer Science undergrad studying in Vellore Institute of Technology, Chennai. I have a keen interest in designing and building user-friendly websites. This is my first experience with working on Open Source software and it has been amazing so far, thanks to the easy to follow and well designed documentation. I am really looking forward to joining this awesome community and contributing to TEAMMATES.
Cheers :)

**Comment by Neurrone** [comment]
Hi @saching97, welcome to TEAMMATES!

You can start by fixing a [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue to become familiar with our workflow, and then move on to [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors).

If you're planning to apply for GSoC, let us know, and check out our [instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true).

**Comment by saching97** [comment]
Thanks a lot @Neurrone ! I will be moving to those soon and yes, I am planning to apply for GSoC
