### ISSUE TITLE
Message : Feedback for GSoC propsal draft

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#6939]
This is to notify that I have shared my GSoC proposal draft with the organization. Please give feedback as soon as possible. Please let me know if you have any issues in viewing the draft.

**Comment by damithc** [comment]
@VamsiSangam Comments added to the proposal.

**Comment by LimeTheCoder** [comment]
@damithc Hey, could you also check my proposal too;)

**Comment by damithc** [comment]
@LimeTheCoder some comments added to your proposal.

**Comment by mshehrozsajjad** [comment]
@damithc  Sir, can you check my proposal too?

**Comment by damithc** [comment]
> @damithc Sir, can you check my proposal too?

@mshehrozsajjad please allow commenting in your Google doc for me to add comments.

**Comment by mshehrozsajjad** [comment]
@damithc done.

**Comment by damithc** [comment]
@mshehrozsajjad comments added to the proposal

**Comment by VamsiSangam** [comment]
@damithc updated my draft. Please review.

**Comment by damithc** [comment]
@VamsiSangam reviewed.

**Comment by junhaoyap** [comment]
If any of you have not yet done your introductions or I have missed it, @VamsiSangam @mshehrozsajjad @LimeTheCoder - welcome to the TEAMMATES community, please also refer to our Google Summer of Code guidelines, the guidelines there will help you make your draft / proposals better!

**Comment by junhaoyap** [comment]
Was informed that GSoC proposal deadline is over, if you need any help with any of the development procedures, please open a new issue on GitHub!
