### ISSUE TITLE
Related to GSOC idea "Coverage hero (Java)"

### ISSUE THREAD

**Issue by wkk91193** [TEAMMATES/teammates#6942]
Hi!
Are there existing tools used in development for measuring test coverage,static code analysis and test profiling so forth..
This is in order to get rough idea of the current context.

Regards,
Kumaranath

**Comment by damithc** [comment]
:-)
![image](https://cloud.githubusercontent.com/assets/1673303/24320734/f78ae0e6-1175-11e7-9e08-dcc743336602.png)
