### ISSUE TITLE
Clarification: TeamMates contribution before deadline

### ISSUE THREAD

**Issue by wkk91193** [TEAMMATES/teammates#6943]
Hi!
I've read through the contributor orientation guide, Just to clarify, is it mandatory to fix issues before GSOC application submission deadline?

Regards,
Kumaranath Fernando

**Comment by damithc** [comment]
> is it mandatory to fix issues before GSOC application submission deadline?

@wkk91193 it's optional, as given [here](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true)

**Comment by rclakmal** [comment]
@wkk91193 However, it will increase your chances of getting accepted in great deal :-)

**Comment by junhaoyap** [comment]
Welcome @wkk91193 to the TEAMMATES community! It is optional indeed and as @rclakmal pointed out, it becomes a good, solid and real indication of the kind of contribution that one can produce, we can all see why that would increase someone's chances of getting into the program to any organization, not just for TEAMMATES! :)

**Comment by junhaoyap** [comment]
Was informed that GSoC proposal deadline is over, if you need any help with any of the development procedures, please open a new issue on GitHub!
