### ISSUE TITLE
New contributor self intro : Cho Joo Yeong

### ISSUE THREAD

**Issue by jujojujoju** [TEAMMATES/teammates#6944]
a) link to your app :
b) link to your fork : https://github.com/jujojujoju/teammates/tree/tinker

c) a screenshot of the change you did (as seen on the UI)

Before :

![image](https://cloud.githubusercontent.com/assets/23520179/24322181/ab00ebfe-11a1-11e7-9977-d7ae7ba97cbb.png)

In ipad

![image](https://cloud.githubusercontent.com/assets/23520179/24322194/fc14cace-11a1-11e7-876a-03f1db11e474.png)

After : 

![image](https://cloud.githubusercontent.com/assets/23520179/24322122/c1f6df22-11a0-11e7-9a88-1f02fbb2ddff.png)

In ipad

![image](https://cloud.githubusercontent.com/assets/23520179/24322219/65bcc224-11a2-11e7-88ae-f9e2e4cdb11c.png)

I minimized the burden of scrolling on the 'about us' page and unified several different profile sizes of core teams. And I just unified the profile size in a smaller display.

However, I could not attach a link to my application because I could not solve the problem of not receiving the new instructor's join link....
(I'm guessing carefully that the js file has been changed to es6, so it will still be read as a js file from 'admin HomePage.html') That's why I took just screenshot from my local.

d) your real name and a short self-intro
Dear All,
My name is Cho JooYeong and I am majoring in Computer Science at Kyunghee University in Korea for 3 years.
I have some experience with Android application development and web development experience covering front and backend using node.js and php.
Also, I recently added a solution to solve problem Troubleshooting.md in teammates's doc.

I am looking forward to be a part of TEAMMATES and participating in the project with the best mentors also I will support this GSOC'17.

Thank you.

**Comment by leeyimin** [comment]
Hi @jujojujoju! Welcome to TEAMMATES.
Do take a look at the [instructions for GSoC applications](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true) and the [project ideas](https://docs.google.com/document/d/1fAvYvQr0E93OsZgyneaXGX0jaMA-zptTIxqLn83xwN0/pub?embedded=true)! 
You may also want to look at [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors) issues when finding the next issue to fix :)

**Comment by jujojujoju** [comment]
Thank you!

**Comment by wkurniawan07** [comment]
> However, I could not attach a link to my application because I could not solve the problem of not receiving the new instructor's join link....
> (I'm guessing carefully that the js file has been changed to es6, so it will still be read as a js file from 'admin HomePage.html') That's why I took just screenshot from my local.

Hi @jujojujoju! Your guess happens to be correct. I apologize for this; this was caused by the very recent migration to ES6 done. To resolve this problem, you need to run `npm run build` from the project root folder which will regenerate the required JS files, and deploy the updated version.

**Comment by junhaoyap** [comment]
Welcome @jujojujoju to the TEAMMATES community! Nice! Looking forward to your contributions 👍

**Comment by jujojujoju** [comment]
Thank you. I look forward to it !

**Comment by damithc** [comment]
@jujojujoju did you apply to TEAMMATES under GSoC 2017?

**Comment by junhaoyap** [comment]
Was informed that GSoC proposal deadline is over, if you need any help with any of the development procedures, please open a new issue on GitHub!

@damithc I think @jujojujoju did, GSoC was mentioned at the end of the introduction.

**Comment by jujojujoju** [comment]
Yes, I did !
I am looking forward to GSOC results and are constantly trying to resolve issues.
