### ISSUE TITLE
Documentation for existing testing process

### ISSUE THREAD

**Issue by wkk91193** [TEAMMATES/teammates#6945]
Hi!
As of now, I've browsed through the [design doc ](https://github.com/TEAMMATES/teammates/blob/master/docs/design.md),  [Documentation For Developers ](https://github.com/TEAMMATES/teammates/tree/master/docs). However, I could not find detailed information on Test driver Component. Is there any existing documentation on regard?

Any help would be highly appreciated!!. Thanks!

Regards,
Kumaranath Fernando

**Comment by wkk91193** [comment]
Perhaps, even details on TestNG framework/Test suite would very much helpful

**Comment by damithc** [comment]
@wkk91193 
We have a little bit more info in [this doc](https://docs.google.com/document/d/1aK-1ubIA59fbNsEujwvWKqx7itwLPTD6mzFo4F_oEoI/pub?embedded=true)
But our docs on testing are sparse and could be slightly outdated.

**Comment by wkk91193** [comment]
Thanks alot @damithc for the response.. Yes. I did have a look at it earlier on.

**Comment by wkurniawan07** [comment]
@wkk91193, the design doc you linked earlier already has explanation for test driver component on it.

Details for TestNG framework (or any external framework we use) can be found online as provided by their own maintainers. We do not provide them here because it is unnecessary and will only be duplicate work.

**Comment by junhaoyap** [comment]
Was informed that GSoC proposal deadline is over, if you need any help with any of the development procedures, please open a new issue on GitHub!
