### ISSUE TITLE
New Contributor Self-Intro: Chandu Herath

### ISSUE THREAD

**Issue by chanduherath** [TEAMMATES/teammates#6946]
- **Link to my app:**  https://teammates-chandu.appspot.com
- **Link to my fork:**  https://github.com/chanduherath/teammates

**Screenshot of changes made (as seen on the UI)**

![teammatesadiminhomepage](https://cloud.githubusercontent.com/assets/12373517/24328148/7f338294-11ff-11e7-9249-723dc7d57b82.png)

**Short self-introduction**

I am an Chandu Herath, an undergraduate from Department of Computer Science and Engineering University of Moratuwa in Sri Lanka. I would like to contribute to the TEAMMATES project and I am planning to apply for GSOC 2017 also. Its a new experience for me to involve with the OSS and I am willing to contribute to the community.

**Comment by samsontmr** [comment]
Hi @chanduherath , welcome to TEAMMATES! If you have already read [our instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true), you can start [here](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md).

**Comment by junhaoyap** [comment]
Welcome @nashmia-riaz to the TEAMMATES community! @samsontmr has already given you a good rundown of what follows from here, thanks @samsontmr!
