### ISSUE TITLE
Documentation for existing testing process

### ISSUE THREAD

**Issue by wkk91193** [TEAMMATES/teammates#6947]
Hi!
As of now, I've browsed through the design doc , Documentation For Developers . However, I could not find detailed information on Test driver Component or on TestNG framework/Test suite. Is there any existing documentation on regard?

Any help would be highly appreciated!!. Thanks!

Regards,
Kumaranath Fernando

**Comment by samsontmr** [comment]
Please refrain from creating duplicate issues.
