### ISSUE TITLE
query regarding the performance hero project

### ISSUE THREAD

**Issue by shilpi0527** [TEAMMATES/teammates#6949]
Performance hero is dealing mainly with the sql query optimization.Using jsp/servlet we can build a small project and can use optimized sql queries
So how this would proceed since sql queries would be at the backend

**Comment by damithc** [comment]
Not sure what your question is. 
Strictly speaking, TEAMMATES doesn't use SQL.

**Comment by junhaoyap** [comment]
Welcome @shilpi0527 to the TEAMMATES community! Treat it more like generally "backend optimization", SQL query optimization isn't the only wait to improve performance :) Not sure if I have seen your introductions before so if you haven't, please find time to refer to our Google Summer of Code guidelines and also our introductions guideline!

**Comment by junhaoyap** [comment]
Was informed that GSoC proposal deadline is over, if you need any help with any of the development procedures, please open a new issue on GitHub!
