### ISSUE TITLE
New Contributor Self-Intro: Liheng Ding

### ISSUE THREAD

**Issue by dingliheng** [TEAMMATES/teammates#6950]
a) Link to my app: http://www.connexus-141219.appspot.com/
b) Link to my fork: https://github.com/dingliheng/teammates/tree/tinker

c) Screenshot of changes made (as seen on the UI):
**I have modified the login buttons for the navigation bar using bootstrap button styles.**
Before:
<img width="1228" alt="screen shot 2017-03-26 at 9 06 48 pm" src="https://cloud.githubusercontent.com/assets/14024451/24338089/4bf8beb2-1268-11e7-8346-6b3a24066d66.png">

After:
<img width="1228" alt="screen shot 2017-03-26 at 9 07 03 pm" src="https://cloud.githubusercontent.com/assets/14024451/24338120/8a7c50f4-1268-11e7-8119-a07b116dd927.png">

d)Self Intro
Hi everyone,
My name is **Liheng Ding**. I'm a master student majoring software engineering at UT Austin for 2 years.

I have already developed a few web applications by myself based on google app engine(If you like, you can see the link above to one of my GAE applications). Through these applications, I have learned necessary knowledge about building a web application like handing requests, managing datastore(like blobstore) and UI design. Besides, I also have some experience in developing mobile applications and I think it's time to design a mobile version for Teammates which can be an efficient way to popularize our project.

I take a great interest in Teammates where I can not only learn a lot and improve my skills, but also enjoy a happy time with such a group of talented "teammates". I'm looking forward to seeing you guys in this summer!

Best,
Liheng Ding

**Comment by rclakmal** [comment]
Hey @dingliheng Welcome to TEAMMATES!!

I presume you are planning to apply for GSoC17. If that is the case, have a a look at the [instructions for applicants ](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true). You can start by fixing a [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue to become familiar with development workflow, and then move on to [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors) issues. 

Good luck!

**Comment by junhaoyap** [comment]
Welcome @nashmia-riaz to the TEAMMATES community! @rclakmal has kindly given a good rundown on what can be done from here on, thanks @rclakmal!

**Comment by junhaoyap** [comment]
Was informed that GSoC proposal deadline is over, if you need any help with any of the development procedures, please open a new issue on GitHub!
