### ISSUE TITLE
Gsoc 2017 : Coverage Hero Projects

### ISSUE THREAD

**Issue by yash2o1o** [TEAMMATES/teammates#6952]
Hi TeamMates Community,
My name is Yash Patel. I am a freshman year student majoring in Computer Science. I would like to part in Gsoc by contributing to the Coverage Hero projects. I have contributed to teammates before and i am familiar with the teammates workflow. I am new to software testing and finding it a bit challenging. I have gone through the design doc and tried to understand the project structure. Are there any resources to go through for the coverage hero projects. It would help greatly. 
Thanks :)

**Comment by damithc** [comment]
@yash2o1o perhaps you can try to look through the existing code and try to figure out which parts are not covered by tests. You can use EclEmma for measuring coverage of Java code. [This (slightly outdated) page](https://docs.google.com/document/pub?id=1LymZ6oeEA6TZRzgW7X2FUxA2MPbZTjUrzIx6si_5ThI&embedded=true#h.gt69u6cffz72) has some resources about testing.

**Comment by yash2o1o** [comment]
Thanks.
