### ISSUE TITLE
Acknowledgment on submission of draft on the idea "Coverage Hero(java)"

### ISSUE THREAD

**Issue by wkk91193** [TEAMMATES/teammates#6959]
Hi!

I'm Kumaranath Fernando. This is to notify that did mail a link to a draft of my initial proposal on "Coverage Hero(java)" via teammates@comp.nus.edu.sg. I did also submit a link on summerofcode.withgoogle.com page.

I would love to hear your feedback and thus adjust and make improvements if necessary.

Thank you,
Regards

**Comment by damithc** [comment]
@wkk91193 added comments to the proposal.
