### ISSUE TITLE
Remove inline javascript onclicks

### ISSUE THREAD

**Issue by Neurrone** [TEAMMATES/teammates#6961]
Many pages use inline scripting such as `onclick=...`.

**Comment by amarlearning** [comment]
@Neurrone I would like to take this one :smile:

**Comment by amarlearning** [comment]
@wkurniawan07 Thanks. 
Considering your advice. I would make a single change and submit for review. if everything goes in the right direction. I will continue to do this else i will stop.

Should I ? :sweat_smile:

**Comment by wkurniawan07** [comment]
Re-opening as some pages still has `onclick`.

**Comment by thenaesh** [comment]
We are not done. xD

**Comment by wkurniawan07** [comment]
The last of the `on*`s are located in the question-related HTML files in `src/main/resources` and a small amount of question-related JS (`question*.es6`).

**Comment by wkurniawan07** [comment]
@thenaesh let's just close this one and include this in V5.107? We can always open a new issue for the ones left behind in `src/main/resources`.

**Comment by whipermr5** [comment]
@wkurniawan07 You mean V5.108? Scheduled for release tonight.
@thenaesh Okay if I close this?

**Comment by wkurniawan07** [comment]
@whipermr5 no, V5.107, most/all the works related to this issue had been done by then.
