### ISSUE TITLE
New Contributor Self-Intro: Liu, Yun-Chun

### ISSUE THREAD

**Issue by yunchun-liu** [TEAMMATES/teammates#6962]
Hi Team,
I'm Liu, Yun-Chun. I study at National Taiwan University and it currently exchanging at NUS. My background may be a bit different as I major life science, but I minor CS and really enjoy programming!
Kindly review my proposal as I submitted it through GSoC websites.

Ps. I'm getting "Unexpected Token" error in every import/export in .js files in Eclipse. I tried googling around but there's not specific solution for solving this error in IDE. It would be good to have some advice over for this issue if it's a common one. Will try to contribute as soon as I fix it.

Cheers,
Yun-Chun

**Comment by Neurrone** [comment]
Hi @yunchun-liu, welcome to TEAMMATES!

Can you paste the exact error message?

**Comment by junhaoyap** [comment]
Welcome @yunchun-liu to the TEAMMATES community! Please remember to refer to our Google Summer of Code guidelines if you haven't already :)

Regarding the error, it will help if you looked at our help request guidelines, it will help us in order to help you :)

**Comment by yunchun-liu** [comment]
@Neurrone  @junhaoyap  thank you for your kind reminder! I'll check them out.

**Comment by junhaoyap** [comment]
Was informed that GSoC proposal deadline is over, if you need any help with any of the development procedures, please open a new issue on GitHub!
