### ISSUE TITLE
Typos in FeedbackSessionsLogic, EntitiesDb and FeedbackSession

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#6985]
Detail CheckStyle Report:
https://htmlpreview.github.io/?https://github.com/xpdavid/CS2103R-Report/blob/master/codingStandard/spelling/main.html

FeedbackSessionsLogic.java
instuctor is not a word according to provided dictionary
``` java
            List<FeedbackQuestionAttributes> instuctorQuestions =
                    fqLogic.getFeedbackQuestionsForInstructor(fsa.getFeedbackSessionName(),
                                                              fsa.getCourseId(),
                                                              fsa.getCreatorEmail());
```

EntitiesDb.java
INTRUCTOR is not a word according to provided dictionary
``` java
    public static final String ERROR_UPDATE_TO_EXISTENT_INTRUCTOR_PERMISSION =
            "Trying to update to existent IntructorPermission: ";
```

FeedbackSession.java
Respoding is not a word according to provided dictionary
``` java
    public void setRespodingStudentList(Set<String> studentList) {
        this.respondingStudentList = studentList;
    }
```

**Comment by Jvsierra** [comment]
I solved the issue and referenced it in this pull: https://github.com/TEAMMATES/teammates/pull/7137
