### ISSUE TITLE
Admin*Action.java: fix typos

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#6986]
Detail CheckStyle Report:
https://htmlpreview.github.io/?https://github.com/xpdavid/CS2103R-Report/blob/master/codingStandard/spelling/main.html

AdminActivityLogPageAction.java
courese is not a word according to provided dictionary
``` java
        if (logRole.contains("Unregistered") && !logRole.contentEquals("Unregistered")) {
            String coureseId = logRole.split(":")[1];
            return getLocalTimeZoneForUnregisteredUserRequest(coureseId);
        }
```

AdminEmailComposeSendAction.java
fanalised is not a word according to provided dictionary
``` java
        AdminEmailAttributes fanalisedEmail = new AdminEmailAttributes(subject,
                                            addressReceiver,
                                            groupReceiver,
                                            new Text(content),
                                            new Date());
```

AdminSearchPageAction.java
Insititute is not a word according to provided dictionary
``` java
data = putStudentInsitituteIntoMap(data.studentResultBundle.studentList, data);
```
Seesion is not a word according to provided dictionary
``` java
processedData = extractDataFromFeedbackSeesion(fsa, processedData, student);
```

**Comment by Anirudh257** [comment]
I would love to work on this.

**Comment by praveshjain** [comment]
Seeing as the previous commenter did not raise a pull request, I have worked on this and raise a PR.
