### ISSUE TITLE
Typos in StudentProfilePictureEditAction, AdminSearchPageData

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#6988]
Detail CheckStyle Report:
https://htmlpreview.github.io/?https://github.com/xpdavid/CS2103R-Report/blob/master/codingStandard/spelling/main.html

StudentProfilePictureEditAction.java
``` java
readAllPostParamterValuesToFields();
```

AdminSearchPageData.java
Seesion is not a word according to provided dictionary
``` java
public HashMap<String, String> feedbackSeesionLinkToNameMap = new HashMap<String, String>();
```

AdminSearchPageData.java
Homa is not a word according to provided dictionary
``` java
public HashMap<String, String> instructorHomaPageLinkMap = new HashMap<String, String>();
```

**Comment by dtwilliams10** [comment]
I can work this issue!

**Comment by manisha-chouhan** [comment]
i can handle this

**Comment by theitrain** [comment]
#7426 

I submitted a pull request for this.
