### ISSUE TITLE
Typos in AdminSessionsPageData and InstructorFeedbackResponseCommentAjaxPageData

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#6989]
Detail CheckStyle Report:
https://htmlpreview.github.io/?https://github.com/xpdavid/CS2103R-Report/blob/master/codingStandard/spelling/main.html

AdminSessionsPageData.java
gettotal is not a word according to provided dictionary, should be getTotal
``` java
    public int gettotalInstitutes() {
        return totalInstitutes;
    }
```

InstructorFeedbackResponseCommentAjaxPageData.java
Visiblities is not a word according to provided dictionary
``` java
        Map<FeedbackParticipantType, Boolean> responseVisiblities = new HashMap<>();
```

**Comment by sdweber422** [comment]
Currently fixing this. Will have a PR in a few minutes.
