### ISSUE TITLE
New contributor self intro Muhammad Mohsin Ajmal

### ISSUE THREAD

**Issue by mohsin2596** [TEAMMATES/teammates#6996]
a) link to my app: (Unable to deploy because of JDK issue)
b) link to my fork: https://github.com/mohsin2596/teammates

c) a screenshot of the change I did 
![change_1](https://cloud.githubusercontent.com/assets/26625526/24515739/efe776fe-1591-11e7-96f4-91bdc0f3167e.JPG)

![change_2](https://cloud.githubusercontent.com/assets/26625526/24515761/feb4bd5e-1591-11e7-8019-b6507bd40897.JPG)

Changed the admin home page to use tabbed navigation to add a new instructor. Having both option in the same place may create ambiguity for the user. 

d) My real name and a short self-intro
Hey Everyone!
My name is Muhammad Mohsin Ajmal and I am an under graduate student of Computer Science from Pakistan studying in National University of Computer and Emerging Sciences. I started learning how to code at the age of 12 and want to be a part of the open source community.

I have also applied for Google Summer of Code and would like to request the moderators to please give me feedback on my proposal draft. 

Regarding the jdk issue to deploy app: I have an ongoing project and hence have not messed around a lot with fixing the jdk issue yet, for some odd reason eclipse fails to get the jdk even though I have defined the path for it in JAVA_HOME and have also updated the jdk used in eclipse as per instructions.

**Comment by damithc** [comment]
Welcome to TEAMMATES @mohsin2596. :-)
Some comments added to your proposal

**Comment by junhaoyap** [comment]
Welcome @mohsin2596 to the TEAMMATES community! Please remember to refer to our Google Summer of Code guidelines if you haven't already :) It will help fill in the gaps if the comments did not already!

**Comment by mohsin2596** [comment]
Thank you @junhaoyap and @damithc. I revised my proposal before uploading the final version. Looking forward to GSoC and good luck to everyone who applied :)

**Comment by junhaoyap** [comment]
Was informed that GSoC proposal deadline is over, if you need any help with any of the development procedures, please open a new issue on GitHub!
