### ISSUE TITLE
New contributor self intro: Nashmia Riaz

### ISSUE THREAD

**Issue by nashmia-riaz** [TEAMMATES/teammates#6997]
**About me:**
Hello, all. :)
My name is Nashmia Riaz and I'm a third year student of Software Engineering at National University of Science and Technology (NUST) in Islamabad, Pakistan. I love web development and programming, and like to make video games and websites during my free time. I am also a graphic designer, so I have an eye for detail and feel that presentation is key towards developing any piece of software.  You can checkout my resume [here](https://nashmia-riaz.github.io/), which includes some of my recent projects. I plan on applying to TEAMMATES for GSoC 2017 and will be submitting my proposal very soon.

**Link to app:**
http://teammates-nashmia.appspot.com/

**Link to fork:**
https://github.com/nashmia-riaz/teammates

**Screenshot of the change I made:**
![untitled](https://cloud.githubusercontent.com/assets/13387692/24522159/1aa1a638-15a8-11e7-8ae1-c9c3d467d472.png)

**First Contribution**
I recently made one of my first contributions to the TEAMMATES code. You can see it referenced in the issue here: https://github.com/TEAMMATES/teammates/issues/6818#issuecomment-290233143

**Comment by Neurrone** [comment]
Hi nashmia-riaz, welcome to TEAMMATES!

Next, you could  try [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors).

**Comment by junhaoyap** [comment]
Welcome @nashmia-riaz to the TEAMMATES community! Please remember to refer to our Google Summer of Code guidelines if you haven't already :)

**Comment by junhaoyap** [comment]
Was informed that GSoC proposal deadline is over, if you need any help with any of the development procedures, please open a new issue on GitHub!

**Comment by nashmia-riaz** [comment]
Thank you so much @jungaoyap and @Neurrone for your help! :)
