### ISSUE TITLE
Response summary is shown after the first question 

### ISSUE THREAD

**Issue by AnaghHegde** [TEAMMATES/teammates#6999]
This should come after the first question right( like for the other questions ) ?
![screenshot 96](https://cloud.githubusercontent.com/assets/12005551/24539376/e9145502-160b-11e7-81c2-a60ddad6141c.png)

But the entire response summary is shown. It should be shown at the top right ( which makes more sense )  and the response for the first question is shown after this. 
![screenshot 95](https://cloud.githubusercontent.com/assets/12005551/24539373/df3dcf36-160b-11e7-8a42-646937aefa24.png)

**Comment by wkurniawan07** [comment]
@AnaghHegde I do not seem to understand this. Is this a bug or something that works correctly but needs improvement?

**Comment by AnaghHegde** [comment]
@wkurniawan07 It's not a bug. It would be better if the summary at the top instead of having summary as well as all the responses one after the other.

**Comment by damithc** [comment]
Closing to focus on higher priority issues. May be reopened later.
