### ISSUE TITLE
User map not loading

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7000]
**Environment**

- Live server at V5.100 (seems to work at v5.99)
- `master` branch since 06e4649

**Steps to Reproduce**

Go to `/usermap.jsp`.

**Expected Behavior**

Usermap loads.

**Actual Behavior**

![image](https://cloud.githubusercontent.com/assets/1673303/24548026/8917d19e-1645-11e7-9603-ac58af53e8e1.png)

**Reason**

Addition of an institution from "Palestine". Nothing sounds off, but "Palestine" surprisingly is not in the list of countries in `countryCodes.es6` -- what is present there is "Palestinian Territory, Occupied".

**Step to Fix**

Add `'Palestine': 'PSE'` to the country codes list.

**Comment by AnaghHegde** [comment]
Yes. Its working in v5.99 and not in v5.100. I am working on this.

**Comment by AnaghHegde** [comment]
The console says : **`TypeError: coordinates is undefined`**. Take a look at this. 

![screenshot 99](https://cloud.githubusercontent.com/assets/12005551/24552819/9eeb8b1e-1645-11e7-8664-a510543bbf0e.png)

But when i printedd those values, even the array `pins` it contains proper values. I don't understand why console gives this error.

![screenshot 98](https://cloud.githubusercontent.com/assets/12005551/24552764/5f195566-1645-11e7-8a54-28eb7cef59ab.png)

**Comment by wkurniawan07** [comment]
@damithc is this urgent? If not, it is actually convertible to a `d.FirstTimers` issue.

**Comment by damithc** [comment]
> @damithc is this urgent? If not, it is actually convertible to a d.FirstTimers issue.

Not very urgent. As long as it gets fixed in the next couple of releases.

**Comment by AnaghHegde** [comment]
@damithc 
>Not very urgent. As long as it gets fixed in the next couple of releases.

It's working fine in master. So doesn't that count ?.

**Comment by wkurniawan07** [comment]
> It's working fine in master.

@AnaghHegde I can assure you that it is not. Which version of `master` are you using?

**Comment by wkurniawan07** [comment]
@damithc I'll add the reason and way to fix in the issue description itself.

**Comment by AnaghHegde** [comment]
@wkurniawan07 The latest commit is 22dd83d.
