### ISSUE TITLE
New contributor self intro: Griffin Hines

### ISSUE THREAD

**Issue by GriffinHines** [TEAMMATES/teammates#7007]
**About me:**
Hey guys, I'm a first year Computer Science student at the University of Georgia. My experience writing code spans about 3 months right now, but I'm excited to learn more, and Teammates seems like a great place to do that. As you can see below, my tinker to Teammates UI reformatted some of the text at the bottom of the 'about us' page.

**Link to app:** http://teammates-griffinqh.appspot.com/

**Link to fork:** https://github.com/GriffinHines/teammates

**Screenshot of change:**

**Before:**
![before](https://cloud.githubusercontent.com/assets/26612528/24559160/b3e3eab4-160b-11e7-8435-ce56cf7dff5d.png)

**After:** 
![after](https://cloud.githubusercontent.com/assets/26612528/24559173/bd95db44-160b-11e7-928b-68ff55697fe5.png)

**First timers issue:** [User Map not Loading #7000](https://github.com/TEAMMATES/teammates/pull/7008)

I'm looking forward to making more contributions!

**Comment by junhaoyap** [comment]
Welcome @GriffinHines to the TEAMMATES community! I see that your first timer issue is about to be merged so that's great! Looking forward to seeing your work with contributor issues and I am sure you will learn a lot!
