### ISSUE TITLE
Trivial formatting error in design.md

### ISSUE THREAD

**Issue by HirdayGupta** [TEAMMATES/teammates#7009]
Just a trivial error I noticed while going through documentation in the [design.md ](https://github.com/TEAMMATES/teammates/blob/06528da44c16af94681355c42b0fc10f05fdad5e/docs/design.md)file. The heading **policies** under Storage API and Logic API was not being highlighted by git due to erroneous markdown syntax. The file reads: `###Policies` whereas it should instead read `### Policies`

@damithc (or any other core team member) possible `d.FirstTimers` issue? Or should I go ahead and submit a PR fixing it?

Other possible labels: `a-Docs` , `a-CodeQuality`

**Comment by damithc** [comment]
@HirdayGupta thanks for the bug report. Also, remember that we don't allow more than one `d.FirstTimers` issue per person.

**Comment by HirdayGupta** [comment]
@damithc I am aware of that. Hence I pointed it out here instead of fixing it. Thanks! :)

**Comment by GregHib** [comment]
Never made a PR before might as well start with an easy one like this
