### ISSUE TITLE
gsoc proposal writing

### ISSUE THREAD

**Issue by bikashthakur** [TEAMMATES/teammates#7011]
Hello Sir/Ma'm,
I'm Bikash Thakur, final year computer science student, registered to GSOC 2017. After got registered to gsoc, i was looking for organisation for the project to work on, and then I found your organisation, and things that attracted me is that I'm also working on the similar project for my college. So thought it would be a good oppertunity for me to work on this project if get selected. I've almost completed my college project, I would be happy to share that with you.  I'm willing to work on Reports+ project, I know I'm too much late in this process, so I need your guidance for the proposal writing as early as possible. Thank You.

**Comment by junhaoyap** [comment]
Welcome @bikashthakur to the TEAMMATES community, please refer to our Google Summer of Code guidelines, there are pointers there that will definitely help you, afterwards if you need more comments please refer to @damithc

**Comment by junhaoyap** [comment]
Was informed that GSoC proposal deadline is over, if you need any help with any of the development procedures, please open a new issue on GitHub!
