### ISSUE TITLE
Query regarding GSOC Proposal

### ISSUE THREAD

**Issue by HirdayGupta** [TEAMMATES/teammates#7012]
Hello. As I am working on my proposal, I had a couple of questions.

1. Is it recommended to include code and to show how we'd implement some of the changes we are proposing? Or will a textual description suffice?

2. Is it recommended to include screenshots with any UI changes being proposed? Are mockups/rough diagrams permissible?

Thank you!

**Comment by damithc** [comment]
> Is it recommended to include code and to show how we'd implement some of the changes we are proposing? Or will a textual description suffice?

Code not normally expected, but it can help your case if you include code snippets.

> Is it recommended to include screenshots with any UI changes being proposed? Are mockups/rough diagrams permissible?

At least mock ups are recommended, anything more is a bonus.

**Comment by HirdayGupta** [comment]
Noted, thanks!

Also, in the Usablity Hero project, the features to consider say

> Reduce brittleness of documentation

Could you please explain what you mean by this?

**Comment by damithc** [comment]
`brittleness of documentation` means the tendency for the documentation to get outdated quickly.

**Comment by junhaoyap** [comment]
Was informed that GSoC proposal deadline is over, if you need any help with any of the development procedures, please open a new issue on GitHub!
