### ISSUE TITLE
Regarding Gsoc Proposal

### ISSUE THREAD

**Issue by Mynk96** [TEAMMATES/teammates#7013]
I have shared the Gsoc proposal draft.Please review and give feedback. If there is any problem regarding draft or something which is not clear please let me know.

**Comment by damithc** [comment]
@Mynk96 please set the permission of your proposal to 'comment only' so that I can add comments. Currently it is 'view only'

**Comment by Mynk96** [comment]
@damithc changed permission to 'comment only', also made lots of changes kindly go through it.

**Comment by junhaoyap** [comment]
If this is your first time posting, welcome to the TEAMMATES community @Mynk96, please look through our Google Summer of Code guidelines, there should be some guidelines to help you with your first draft even before comments are given :)

**Comment by junhaoyap** [comment]
Was informed that GSoC proposal deadline is over, if you need any help with any of the development procedures, please open a new issue on GitHub!
