### ISSUE TITLE
New contributor self intro [Jay Dalal]

### ISSUE THREAD

**Issue by jaydalal12** [TEAMMATES/teammates#7014]
a) link to app
http://jaydalal-teammates.appspot.com/
b) link to fork
https://github.com/jaydalal12/teammates
c) a screenshot of the change I did (Added buttons for Instructor & Student Login)
![image](https://cloud.githubusercontent.com/assets/21137132/24579110/7f0165e0-170c-11e7-8edc-2552de07ecc7.png)

d) Hi, my name is Jay Dalal. I am working as Software Engineer. I am here to contribute in Teammates community and enhance my skills and learn new skill.

**Comment by samsontmr** [comment]
Hi @jaydalal12, welcome to TEAMMATES! You can start by fixing a [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue, then those labelled `d.Contributors`.

**Comment by junhaoyap** [comment]
Welcome @jaydalal12 to the TEAMMATES community!
