### ISSUE TITLE
New contributor self intro [Abdul Basit]

### ISSUE THREAD

**Issue by basitsattar** [TEAMMATES/teammates#7015]
My App Link 
http://teammates-abdulbasit.appspot.com/

Repository Link
https://github.com/basitsattar/teammates/tree/tinker 

I have improved the layout of the About Us page. 

<img width="1440" alt="screen shot 2017-04-01 at 6 26 49 pm" src="https://cloud.githubusercontent.com/assets/8505943/24579156/2bab2474-1709-11e7-805c-6edfe92cfeb2.png">
<img width="1440" alt="screen shot 2017-04-01 at 6 27 04 pm" src="https://cloud.githubusercontent.com/assets/8505943/24579159/2bafe91e-1709-11e7-9cad-f9592a15dd88.png">
<img width="1440" alt="screen shot 2017-04-01 at 6 27 13 pm" src="https://cloud.githubusercontent.com/assets/8505943/24579158/2bae4c1c-1709-11e7-8281-6ba50bd70e46.png">
<img width="1440" alt="screen shot 2017-04-01 at 6 27 19 pm" src="https://cloud.githubusercontent.com/assets/8505943/24579157/2bad0672-1709-11e7-95be-9d4ff921f327.png">

I am Abdul Basit, a software engineering student from NUST University Islamabad. I am also a member of Pak-US Alumni  Network and have studied a semester in University of Wisconsin, Eau claire sponsored by U.S Department of states. I have been doing web development for more than three years now and have made a lot of websites during this time. I am experienced in both front end and backend technologies.I am also going to submit my proposal to TeamMates for Google Summer of code. Check this link to get more information about me (www.abdulbasit.info).

**Comment by samsontmr** [comment]
Hi @basitsattar, welcome to TEAMMATES! Nice change to the UI, I like it!

You can start by fixing a [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue, then those labelled `d.Contributors`.

**Comment by junhaoyap** [comment]
Welcome @basitsattar to the TEAMMATES community! Please refer to our Google Summer of Code Guidelines if you haven't already :)

**Comment by junhaoyap** [comment]
Was informed that GSoC proposal deadline is over, if you need any help with any of the development procedures, please open a new issue on GitHub!

**Comment by basitsattar** [comment]
@junhaoyap  
Thanks a lot. I'll ask for help when needed.

**Comment by VamsiSangam** [comment]
Awesome website @basitsattar ! :astonished:

**Comment by basitsattar** [comment]
Thanks a lot :)
