### ISSUE TITLE
New Contributors self intro [Angelos Tsalapatis, Haris Panidis]

### ISSUE THREAD

**Issue by Fade1** [TEAMMATES/teammates#7018]
A) No international card 
B) https://github.com/Fade1/teammates
C) 
![image](https://cloud.githubusercontent.com/assets/15677505/24579542/618bc304-1700-11e7-9e7b-81486af061a8.png)
 Since we are two people, we decided to change two different things regarding the Home page of the project. Firstly we added a new dropdown menu that includes the two links that redirect students and instructors to their respective pages.In the second change we decided to contain the whole information panel of the home page into a single carousel, in order to add some visual aesthetics.
D) Hello friends,
We are both students at the Athens University of Economics and Business in the Department of Managment and Technology.We were asked to contribute to an open source project on github for the sake of a class we are currently attending. We decided that this specific project fits perfectly our web development background from previous semesters and therefore we will be able to contribute effectively.We are already thinking of making some UI changes and resolving some issues , in order to start to get involved. Thanks in advance :))

Sencirely, 
Angelos & Haris

**Comment by angelosdmg** [comment]
Hello Angelos,
Welcome to our project :P

**Comment by xpdavid** [comment]
@Fade1 Welcome to TEAMMATES. You can start to work on `d.FirstTimer` issue and submit your first PR. :)

**Comment by Fade1** [comment]
Nice to meet you all :)

**Comment by junhaoyap** [comment]
@Fade1, welcome to the TEAMMATES community, I am not sure what is Haris's handle so I can't welcome him / her, it would be the best to start with a firstTimer issue as @xpdavid suggested, afterwards the both of you can start on contributor issues and that will be sure to improve on your web development skill!
