### ISSUE TITLE
Clarification : Submission of PR after gsoc application deadline

### ISSUE THREAD

**Issue by wkk91193** [TEAMMATES/teammates#7040]
Hi!
After preparing the GSOC application, I did not have much time on submitting a PR on an issue labeled Contributor, although I submitted a PR on an issue labeled FirstTimer, this is to clarify if PR submissions after GSoC application deadline still are considered to improve chances of selection as a GSOC student.

Regards
Kumaranath Fernando

**Comment by damithc** [comment]
Yes they are considered @wkk91193
