### ISSUE TITLE
Instructor view results, grouped by recipient: show spinner while loading panels

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7043]
v5.100

In the case such as below, clicking the panel causes it to load, which can take a significant time. During this time we should show the spinner gif to indicate that things are happening in the background. Otherwise the user might think it's stuck/broken.

![image](https://cloud.githubusercontent.com/assets/1673303/24736377/4fb20a04-1aba-11e7-9c65-13eba74ff10c.png)

**Comment by mshehrozsajjad** [comment]
@damithc Is this assigned to someone?

**Comment by damithc** [comment]
@mshehrozsajjad as you can see in the thread above, there is an open PR for this. Take a look at that PR and if you have a better solution, you can submit another PR. We don't mind multiple PRs for the same issue as long as they are not duplicate solutions.
