### ISSUE TITLE
Instructor: view results, group by recipient: fix 'No specific recipient' showing questions with specific recipients

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7044]
v5.100

These questions have specific recipients but are shown as `No Specific Recipient`

![image](https://cloud.githubusercontent.com/assets/1673303/24736476/d5e0c462-1aba-11e7-8818-329239f07a44.png)

**Comment by VamsiSangam** [comment]
Can I work on this?

**Comment by VamsiSangam** [comment]
I think I found the source of error. `teammates.ui.pagedata.InstructorFeedbackResultsPageData.java` has the method `buildSectionPanelsForForAjaxLoading` which builds those panels. Here's the code -

``` java
private void buildSectionPanelsForForAjaxLoading(List<String> sections) {
    sectionPanels = new LinkedHashMap<String, InstructorFeedbackResultsSectionPanel>();

    InstructorFeedbackResultsSectionPanel sectionPanel = new InstructorFeedbackResultsSectionPanel(
            Const.DEFAULT_SECTION, Const.NO_SPECIFIC_RECIPIENT, true);
    sectionPanels.put(Const.DEFAULT_SECTION, sectionPanel);

    for (String section : sections) {
        sectionPanel = new InstructorFeedbackResultsSectionPanel(section, section, true);
        sectionPanels.put(section, sectionPanel);
    }
}
```

The line in between - `sectionPanels.put(Const.DEFAULT_SECTION, sectionPanel);` causes the "No specific recipient" panel to show up. Removing that line solves the issue. But what was the purpose of writing that line? Was it meant for something else?

**Comment by VamsiSangam** [comment]
@damithc could you please clarify my above question as to why the `sectionPanels.put(Const.DEFAULT_SECTION, sectionPanel);` was written?

**Comment by damithc** [comment]
> @damithc could you please clarify my above question as to why the sectionPanels.put(Const.DEFAULT_SECTION, sectionPanel); was written?

@VamsiSangam Not sure myself. Have to wait till someone else offer some input on this.

**Comment by VamsiSangam** [comment]
Sure!

**Comment by VamsiSangam** [comment]
> But what was the purpose of writing that line? Was it meant for something else?

@whipermr5 , could you please clarify my above question, or tag someone who could?

**Comment by whipermr5** [comment]
Viewing the `blame`, that line was first introduced in July 2015 via 3271068faccb50cf55cbb7f01778d091533c4d1c by @kanghj.

**Comment by kanghj** [comment]
That line was intentionally added back then, since that section was for containing responses for "Nobody specific (For general class feedback)".

**Comment by VamsiSangam** [comment]
So @damithc sir, that panel is meant for responses for question where the recipient is `Nobody specific (For general class feedback)` as said by @kanghj.

The current behavior is that when the user selects `Group by - Recipient > Question > Giver`, then `N + 1` drop down options show up, where `N` is the number of sections and the extra one which is meant for `Nobody specific (For general class feedback)`.

If that particular feedback session has questions with recipient as `Nobody specific (For general class feedback)`, then clicking on the `No specific recipient` panel reveals the responses. If there are no such questions for that particular feedback session, then clicking on `No specific recipient` panel makes it disappear.

Everything seems to be OK. I don't understand the issue now :sweat_smile

**Comment by damithc** [comment]
> Everything seems to be OK. I don't understand the issue now :sweat_smile

The thing is, my questions have recipients. See below
![image](https://cloud.githubusercontent.com/assets/1673303/25837489/beeddc48-34c0-11e7-9b75-984255de34b3.png)

**Comment by damithc** [comment]
The feature seems to be working in some cases but not in others. If it helps, the problematic case is a session where all the questions have this type of feedback path i.e. from `Students in this course`, to `Other students in this course`

![image](https://cloud.githubusercontent.com/assets/1673303/26024175/319fcd3c-37ff-11e7-9eca-4399cbb9be1d.png)

**Comment by LimeTheCoder** [comment]
Hi, @damithc. Could you please check teammates.test.cases.browsertests.FeedbackRubricQuestionUiTest#allTests. During testInstructorResultsPage, response for rubric question appears under 'No specific recipient panel' but there is specific recipient exists.
![image](https://user-images.githubusercontent.com/8873908/29051117-1124abf8-7be9-11e7-9072-72ba2a8aaf0a.png)
Is it a bug? If so it's still confusing that it behaviour covered by tests.

**Comment by damithc** [comment]
@LimeTheCoder it is possible that current tests cover (and pass) the buggy behavior.  Those tests need to be fixed as well.

**Comment by LimeTheCoder** [comment]
Hello, @damithc. After an investigation, it seems that this panel contains responses with givers or recipients which section is 'None'. So currently this section can contain responses with specific recipients if they section is 'None'. Should we rename this panel to 'No specific section' or try to change behaviour to contain only responses without recipients? Since other panels are exactly sections in the course so it seems that we should choose the first way and rename that panel to 'No specific section' which will contain data that wasn't included in other panels in that view.

**Comment by damithc** [comment]
See if renaming it to 'Recipient not in a specific section' makes sense in all situations. If it does, we can go with it.
