### ISSUE TITLE
about.jsp: Add photos for current committers

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7046]
Processed photos are given below. To be added to https://teammatesv4.appspot.com/about.jsp (names are already in that page)
Might need resizing the photos before adding to the repo.

![image](https://cloud.githubusercontent.com/assets/1673303/24753806/59cb6372-1b06-11e7-8a28-6e3e03ef8823.png)
Samson

![image](https://cloud.githubusercontent.com/assets/1673303/24753827/73b35fd8-1b06-11e7-9a5e-b9e7e4ba9f1b.png)
Xiao Pu

![image](https://cloud.githubusercontent.com/assets/1673303/24753732/02d25efe-1b06-11e7-87d8-94dd05b23039.png)
Boxin

![image](https://cloud.githubusercontent.com/assets/1673303/24753736/0c9160ac-1b06-11e7-9efb-36e5cbbcb4e0.png)
John

![image](https://cloud.githubusercontent.com/assets/1673303/24753740/1242f22c-1b06-11e7-9884-e26d5a283d04.png)
Dickson

![image](https://cloud.githubusercontent.com/assets/1673303/24753748/1990e782-1b06-11e7-8e0c-bc95a2f5f049.png)
Theanesh

![image](https://cloud.githubusercontent.com/assets/1673303/24753758/25d50a78-1b06-11e7-9234-e214d2b6ec87.png)
Li Kai

![image](https://cloud.githubusercontent.com/assets/1673303/24753775/369aa8f4-1b06-11e7-950c-6f66f419c9ce.png)
Ming Shin

![image](https://cloud.githubusercontent.com/assets/1673303/24753782/41034012-1b06-11e7-9378-d8df857e6422.png)
Yi Min

**Comment by mshehrozsajjad** [comment]
Can I work on this? Also If I can improve previous outlook of page?

**Comment by HirdayGupta** [comment]
I would also like to work on this and improve the design of the overall page as well as include these pictures.

**Comment by HirdayGupta** [comment]
@mshehrozsajjad why don't we each pick one from the about.jsp issue and the email issue?

**Comment by mshehrozsajjad** [comment]
Sure! I would like to work on email issue are you okay with it?

**Comment by HirdayGupta** [comment]
@mshehrozsajjad Sure! Just to clarify you'll be working on Issue#6805 and I'll work on this.

**Comment by mshehrozsajjad** [comment]
Okay!

**Comment by HirdayGupta** [comment]
@damithc check out http://teammates-hirday.appspot.com/about.jsp

I have uploaded these pictures and have also revamped the design of the page.

Would you like me to submit a PR with these changes for this issue and then discuss any design changes on the page? Or would you rather discuss design changes here? Or if you would like me to simply upload the images in the existing page design and submit a PR with just that I can also do that.

**Comment by chowyb** [comment]
@HirdayGupta a PR that fixes this issue should ideally upload the images in the existing page design, without changing the overall design if possible. An issue to change the design of about.jsp has already been opened (#7017), but is presently on hold so it's not a priority for now.
