### ISSUE TITLE
Git Help Required: Accidentally Merged Remote Tracking Branch

### ISSUE THREAD

**Issue by HirdayGupta** [TEAMMATES/teammates#7052]
Hi,

I seem to have accidentally merged a remote tracking branch into my fork's master. I think it is because of this that any of the new branches I create cannot be seen when I try to create a new pull request (using the compare across forks option). Requesting assistance on how to proceed. I have completed the changes required from Issue #7046 but am unable to open the pull request.

Thanks.

**Comment by mshehrozsajjad** [comment]
Have you followed the guidelines [here ](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md) about submitting a PR?

**Comment by HirdayGupta** [comment]
Yes,  I have. I am just unable to see the branch I have made the changes in here:
<img width="1145" alt="screen shot 2017-04-07 at 2 29 23 pm" src="https://cloud.githubusercontent.com/assets/18088721/24793181/b336820a-1b9e-11e7-9f89-849d1fc55ff3.png">

I think I am unable to see it because of the issue I mentioned earlier. Requesting any possible assistance into the matter. Thanks.

**Comment by rclakmal** [comment]
@HirdayGupta Merging remote master to your fork master shouldn't create any problem. In fact this is what you call "Syncing the fork" and its good to sync your fork once in a while. 

What exactly is the problem you are facing? which branch you can't see ?

**Comment by rclakmal** [comment]
If you can't see a branch in the PR tool, it is very well possible that you haven't push your branch yet and only exists locally.

**Comment by basitsattar** [comment]
have you pushed the new branch to your remote? If not check out that branch and run this command

git push origin <name-of-your-branch> 

to push the branch to remote origin.

**Comment by HirdayGupta** [comment]
@rclakmal thanks, I think that fixed the issue! Apologies for the oversight on my part.
