### ISSUE TITLE
Show alerts in flat (not 3D) style

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7059]
To avoid alerts looking like expandable panels, we can use a flat (not 3D style) for alerts.

The current style:
![image](https://cloud.githubusercontent.com/assets/1673303/24825032/06c8162c-1c49-11e7-9377-5704249341ca.png)

Flat style:
![image](https://cloud.githubusercontent.com/assets/1673303/24825036/1b22a33a-1c49-11e7-83c6-8336bdfa9813.png)
![image](https://cloud.githubusercontent.com/assets/1673303/24825047/6371943e-1c49-11e7-938a-c67fe0df2cbf.png)

**Comment by saching97** [comment]
@damithc I'm working on this, will update the teammatesCommon.css
