### ISSUE TITLE
admin search: show open/close dates for sessions in search results

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7060]
See screenshot below. It will be useful if the opening and closing dates are shown for each session, as it can help determine which sessions are current sessions. This is useful when a student emails us about not receiving a link without specifying which session he/she is referring to.

![image](https://cloud.githubusercontent.com/assets/1673303/24825266/f3b9712a-1c4d-11e7-8b36-47070e7add1d.png)

Steps:
1. Go to admin search page.
2. Search for a student name
3. Click on one of the search results to expand details

**Comment by mukesh14149** [comment]
I can work on this.

**Comment by shreyag12** [comment]
Hi, when I search Derrick, I get no results found.
![screenshot from 2017-07-09 20 32 10](https://user-images.githubusercontent.com/6481566/27995069-c708ea8a-64e5-11e7-80a7-1cf7b295269e.png)

**Comment by arjunsuri** [comment]
@shreyag12 how did you reach at admin search page?I mean did you sign up as a professor, as there is no student sign up page.
