### ISSUE TITLE
admin search: provide a mailto link with pre-filled values

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7061]
Current situation:

When a student emails admin requesting to resend a link, the admin users the 'admin search' page to locate the student and his/her links (see screenshot below), copy paste the link to a new email message, and send it manually to the student using a different email account (in case the one used by TEAMMATES is blocked on the student's side).

![image](https://cloud.githubusercontent.com/assets/1673303/24825340/8f4cc87a-1c4f-11e7-94df-f2869e2d9995.png)

Suggestion:

In the above page, we can provide a `mailto` link that opens the admin's email application with pre-filled values (subject, body, receiver).

Benefit:
Less manual work for the admin.

**Comment by mukesh14149** [comment]
@damithc  Sir, Can't this #7071 solve this issue, as instructor can directly remind this particular student from home page.
but If student wants link after the session is over then its a problem for instructor to remind from homepage.
If this is the situation i would like to solve this issue.

**Comment by damithc** [comment]
> Can't this #7071 solve this issue, as instructor can directly remind this particular student from home page.

No, this is for the case when a student write to the TEAMMATES admin (i.e. me) requesting the link instead of writing to the instructor. We allow both options.

**Comment by mukesh14149** [comment]
Ok i can work on this.

**Comment by amarlearning** [comment]
working on this :)

**Comment by amarlearning** [comment]
> opens the admin's email application

@damithc By that, you mean the default application installed on your system `(Like Thunderbird Mail)`?

**Comment by damithc** [comment]
> @damithc By that, you mean the default application installed on your system (Like Thunderbird Mail)?

yes.
