### ISSUE TITLE
Rich text boxes: make the toolbar appear over existing content

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7063]
Currently, when the user clicks on a rich text form field, the formatting toolbar is inserted above the form field, shifting all elements below it. When the user clicks outside the form field after editing it, the toolbar disappears and elements below it shifts again. This jumping of page content gets in the way of a smooth user user experience. It can also result in 'mishit clicks' i.e. user tries to click a button but ends up clicking something else because content moves with the click.

Options:
1. make the toolbar stay fixed all the time
2. make the toolbar appear on top of the existing content above the form field (I believe this is the default mode but we changed it to the current behavior in a misguided attempt to improve user experience -- my bad 😢  )

Before clicking:
![image](https://cloud.githubusercontent.com/assets/1673303/24825575/803366d8-1c53-11e7-878e-c8ca05c8023a.png)

After clicking:
![image](https://cloud.githubusercontent.com/assets/1673303/24825570/5977f220-1c53-11e7-9951-5958dbd31e88.png)

**Comment by HirdayGupta** [comment]
@damithc Github isn't tracking changes in `src/main/webapp/js/instructorFeedbackEdit.js`. 
When I tried to add using `git add` it says the file is part of `.gitignore`. Why is this so? And should I use the `git add -f` command to override this?

**Comment by wkurniawan07** [comment]
@HirdayGupta you need to override the `.es6` file.

**Comment by amarlearning** [comment]
@damithc can I work on this issue?

**Comment by damithc** [comment]
@HirdayGupta are you working on this?

**Comment by HirdayGupta** [comment]
@damithc yes I am. I'm working on the method 1 (make the toolbar fixed all the time).

**Comment by damithc** [comment]
> @damithc yes I am. I'm working on the method 1 (make the toolbar fixed all the time).

@amarlearning in that case you can try to other alternative if you want. We can compare the two approaches and choose the better one.

**Comment by amarlearning** [comment]
> @damithc make the toolbar appear on top of the existing content above the form field (I believe this is the default mode but we changed it to the current behavior in a misguided attempt to improve user experience -- my bad :cry: )

Not able to understand, can you be please a little more descriptive.

**Comment by damithc** [comment]
> Not able to understand, can you please a little more descriptive.

Like this:
![image](https://cloud.githubusercontent.com/assets/1673303/24919462/5ec91ca2-1f16-11e7-8425-773642ff46e3.png)

**Comment by HirdayGupta** [comment]
@damithc referring to the screenshot you posted above, is it a mock-up? or did you code it up? If it is the latter, would you be able to share your approach with me? I ask as I am finding it tricky to implement the second functionality correctly.

My current approach is to use JavaScript to override the CSS Position property for the div that contains the editor. However, I am unable to figure out the correct combination of position properties that would make this possible.

**Comment by damithc** [comment]
@HirdayGupta It is a mockup, but it's also how the code worked when rich text support was introduced (by @belyabl9 last summer). So you should be able to find the code if you look through the git history of a relevant file or dig up the original PR by @belyabl9 I believe the library already has support for this mode without you having to write a lot of extra code yourself.

**Comment by damithc** [comment]
See https://github.com/TEAMMATES/teammates/issues/5775
That is the change I'm trying to reverse now :-p

**Comment by HirdayGupta** [comment]
@damithc Thanks! simply removing `fixed_toolbar_container` implements the desired behaviour! 😆 

Will submit a PR with the fix soon.
