### ISSUE TITLE
Instructor: remind particular students: show students who have submitted in gray color

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7065]
Current situation:

When the instructor choose 'Remind -> Remind particular students' option from the home page (see below), only those who have not submitted are shown in the list.
![image](https://cloud.githubusercontent.com/assets/1673303/24826806/c780cdb0-1c70-11e7-8162-5ea1a4820e20.png)

Suggestion:
Also show those who have submitted (possibly in gray color).

Justification:
In some cases a student who have submitted earlier might need to receive the link again e.g. student wants to edit the submission but cannot find the email containing the link.

**Comment by mukesh14149** [comment]
I am working on this.
