### ISSUE TITLE
Instructor: view student list: add a 'delete all students' button 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7066]
Suggestion:
In the course details page, we can have a 'delete all students' button. Alternatively, we can have check boxes in each row with a 'Delete selected students' button.

![image](https://cloud.githubusercontent.com/assets/1673303/24826864/15afc74c-1c72-11e7-8046-781c10d604b4.png)

![image](https://cloud.githubusercontent.com/assets/1673303/24826859/ed7f0c38-1c71-11e7-8c46-07dcf1c72a5c.png)

Justification:
Sometimes instructors need to delete many students at once, for example, when students were enrolled with wrong details.

**Comment by AnaghHegde** [comment]
@damithc Look's interesting i will work on this. PR on the way.

**Comment by AnaghHegde** [comment]
@damithc One clarification, should i need to give option to delete students who are yet too join also?.

**Comment by damithc** [comment]
> One clarification, should i need to give option to delete students who are yet too join also?.

Yes. Join status is totally irrelevant to this feature.

**Comment by AnaghHegde** [comment]
Ok. Lets say a invitation is sent to student but immediately after that he is deleted using the delete button. But what if he joins using the link ?.

**Comment by damithc** [comment]
> Ok. Lets say a invitation is sent to student but immediately after that he is deleted using the delete button. But what if he joins using the link ?.

The link is useless if the student is deleted. Trying to use that link will result in an error.

**Comment by Yogitha6** [comment]
@AnaghHegde Are you still working on this? If not I could pick up this issue.

**Comment by AnaghHegde** [comment]
@Yogitha6  Sorry i am working on this. I ll be opening a PR in 2 days.

**Comment by AnaghHegde** [comment]
@damithc I have some questions regarding design constraints.
- Should i need to add a button at the top like Remind and Download 
- Any other suggestion ?.
![screenshot 129](https://cloud.githubusercontent.com/assets/12005551/25383659/aee4710e-29da-11e7-974b-f5d3e2c9ea7f.png)

**Comment by damithc** [comment]
> Should i need to add a button at the top like Remind and Download

yes. make it red too.

**Comment by AnaghHegde** [comment]
@damithc Also when the instructor clicks on the button a new window will be opened with something like this. I guess that is ok?

![screenshot 131](https://cloud.githubusercontent.com/assets/12005551/25456527/c1a81aa4-2af0-11e7-8027-30a7c069f7b0.png)

**Comment by damithc** [comment]
@AnaghHegde To limit the size of this PR within reasonable limits, lets start by adding a 'delete all' button that deletes all students in the course. There is no need for a modal window as shown in your screenshot because there is no need to select which students to delete. Just a confirmation dialog is enough (similar to the delete button given in each row).

**Comment by amarlearning** [comment]
@damithc I think @AnaghHegde is not working on this issue. I would like to take this one.

**Comment by damithc** [comment]
> @damithc I think @AnaghHegde is not working on this issue. I would like to take this one.

@amarlearning yes you can take it up and there is no active PR.

**Comment by shubham49** [comment]
@amarlearning if you are not working on this, should I take this?

**Comment by amarlearning** [comment]
Busy with other PRs, so can't take this one right now. Go ahead 👍
