### ISSUE TITLE
No styles/fonts are used in godmode.md

### ISSUE THREAD

**Issue by AnaghHegde** [TEAMMATES/teammates#7069]
It's similar to #6843.

![imageedit_11_7388678390](https://cloud.githubusercontent.com/assets/12005551/24830358/3cd98ac6-1ca2-11e7-8287-ea4523dbda29.jpg)

It's repeated in the page at many places. Add a missing space in between the # and the heading.

**Comment by chowyb** [comment]
Duplicate of #7049, closing this issue.

**Comment by AnaghHegde** [comment]
Oops. Didn't see that. My bad.
