### ISSUE TITLE
instructor remind students: allow even if the session is closed

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7073]
Current situation:
The `remind` button in instructor home page is disabled if the session is closed.
![image](https://cloud.githubusercontent.com/assets/1673303/24833880/3089dc38-1d08-11e7-9034-46e9c21966b6.png)

Suggestion: 
Enable it even if the session is closed, but not if it is awaiting.

Justification: 
In rare cases, a student might want to have a copy of the link even after the session is closed e.g. to check his/her submission

**Comment by sujeet14108** [comment]
Working on it.

**Comment by sujeet14108** [comment]
@damithc Is this what we want ?
![screenshot from 2017-04-09 19-34-24](https://cloud.githubusercontent.com/assets/9781422/24837889/9efd9512-1d5b-11e7-87da-04ad9861330f.png)

**Comment by damithc** [comment]
Yes. Note that the functionality should work in the backend too.

**Comment by sujeet14108** [comment]
This is working just by changing 
 `this.allowedToRemind =
                session.isOpened()
                && instructor.isAllowedForPrivilege(Const.ParamsNames.INSTRUCTOR_PERMISSION_MODIFY_SESSION);`

to 

`this.allowedToRemind =
                (session.isOpened()||session.isClosed())
                && instructor.isAllowedForPrivilege(Const.ParamsNames.INSTRUCTOR_PERMISSION_MODIFY_SESSION);`

On backened too

**Comment by sujeet14108** [comment]
@damithc  Is this correct way of doing it ?

**Comment by damithc** [comment]
> Is this correct way of doing it ?

Can go ahead. When the PR is in, the reviewer can take a deeper look.
