### ISSUE TITLE
Enforce LooseCoupling Rule in PMD for production code.

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#7084]
> One of the principles in designing API is hiding of the internal implementation to users. In other words, we should avoid using implementation types and use the interface instead. There is a `PMD` rule for this: `LooseCoupling`. This rule can be applied to TEAMMATES production code.
> 
> ---- From Technical Report: Static Analysis (Java) in TEAMMATES in https://xpdavid.github.io/CS2103R-Report/

![image](https://cloud.githubusercontent.com/assets/13977235/24856552/b584c316-1e17-11e7-9a0a-f1254f1c4e24.png)
For example, we should expose `Map` instead of the implementation `HashMap` here.

Two tasks here:
1. Add `<rule ref="rulesets/java/typeresolution.xml/LooseCoupling"/>` to `teammates-pmdMain.xml`
2. Fix violations reported by PMD.

**Comment by sdweber422** [comment]
I can work on this.
