### ISSUE TITLE
Replace raw exception throws in production code

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#7085]
> There is a rule in `PMD` named `AvoidThrowingRawExceptionTypes` and it indicates that throwing raw exception types is not a practice in software engineering. We may want to use `Assumption.assert*` rather than throwing raw exceptions in the production code. Therefore, we should change all RuntimeException to make use of `Assumption` class for production code.

![image](https://cloud.githubusercontent.com/assets/13977235/24856706/41895e62-1e18-11e7-9712-2e89b85affa8.png)
For example, we should use `Assumption.assert*` here.

Three Tasks here.
1. Add `<rule ref="rulesets/java/strictexception.xml/AvoidThrowingRawExceptionTypes"/>` to `teammates-pmdMain.xml`
2. Fix violations reported by PMD (Make use of `Assumption.assert` instead)
3. Remove `TODO` if it is necessary (Like the example above)

**Comment by AnaghHegde** [comment]
@xpdavid Look's interesting i will work on this.

**Comment by AnaghHegde** [comment]
@xpdavid I have some questions How should i have to handle the `catch` block exception in `Assumption.assert*` methods as there is no proper one to handle exception. Shall i write a new method ?.

**Comment by damithc** [comment]
Probably need to throw a more specific exception class (i.e. a subclass of RunttimeException) to avoid the PMD violation.

**Comment by AnaghHegde** [comment]
I don't know if it's the best way but, in AssertionError class if we change it to public we can manage using 
`Assumption.assert*()`. I still don't whats the point of having it as private.
```
private AssertionError(String detailMessage) {
        super(detailMessage);
    }
```

**Comment by xpdavid** [comment]
@AnaghHegde Note that AssetionError is come with `jdk1.7`. It is not the class defined by us. Also, there are difference between checked and unchecked exception in Java, which is the reason why we need to write dummy `return` if we use `Assumption.assert*` or `Assumption.fail()`
