### ISSUE TITLE
Change the repackaged import in some classes

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#7089]
~~Original:~~

~~`TypeToken` in `AdminEmailLogPageActionTest` should be imported from `com.google.gson.reflect.TypeToken` rather than `com.google.appengine.repackaged.com.google.gson.reflect.TypeToken`~~

Modified:

Some classes have imports from `com.google.appengine.repackaged.*` which was not recommended. They are:
- `com.google.appengine.repackaged.org.joda.time.DateTime` from `AdminEmailListGenerator`
- `com.google.appengine.repackaged.com.google.gson.reflect.TypeToken` from `AdminEmailLogPageActionTest`
- `com.google.appengine.labs.repackaged.com.google.common.base.Joiner` from `AssertHelper`

The import should be just from the package name after the `com.google.appengine.repackaged` prefix.

**Comment by aashutoshrathi** [comment]
@xpdavid assign this issue to me

**Comment by wkurniawan07** [comment]
I'll escalate the issue a bit.

@aashutoshrathi feel free to, there is no need to be assigned.

**Comment by aashutoshrathi** [comment]
Should I just open a PR ?

**Comment by wkurniawan07** [comment]
@aashutoshrathi that's right. Do take note that I just added some more works to be done for this issue.

**Comment by aashutoshrathi** [comment]
Ok done thanks @wkurniawan07
