### ISSUE TITLE
Instructor: view results: correct the initial direction of chevrons in question panels

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7092]
v5.101

steps:
login as an instructor and navigate to the results of a session.

actual:
![image](https://cloud.githubusercontent.com/assets/1673303/24893828/a533b822-1eb8-11e7-89ca-e4c2c8379056.png)

expected:
These should be pointing downwards

**Comment by sujeet14108** [comment]
On it

**Comment by AnaghHegde** [comment]
@damithc Is this what you are asking ?.
![screenshot 112](https://cloud.githubusercontent.com/assets/12005551/24914997/9555eae8-1ef3-11e7-922e-a9137929b459.png)

**Comment by boxin-yang** [comment]
The initial value for panel.panelHeading.display-icon pull-right. glyphicon-chevron-up should be changed to glyphicon-chevron-down in this case.

**Comment by AnaghHegde** [comment]
@boxin-yang Yes. Indeed i followed the same. I changed ` glyphicon-chevron-up` to ` glyphicon-chevron-down`.
