### ISSUE TITLE
Typos in Instructor Help

### ISSUE THREAD

**Issue by sujeet14108** [TEAMMATES/teammates#7105]
![screenshot from 2017-04-12 20-09-51](https://cloud.githubusercontent.com/assets/9781422/24963478/54076778-1fbc-11e7-9501-a48c2efd6423.png)

![screenshot from 2017-04-12 20-09-16](https://cloud.githubusercontent.com/assets/9781422/24963479/5408c8e8-1fbc-11e7-86f3-efc083b6e66b.png)

![screenshot from 2017-04-12 20-06-26](https://cloud.githubusercontent.com/assets/9781422/24963535/7ce11342-1fbc-11e7-991c-b774d7a96a67.png)

**Comment by khrisdaniels** [comment]
I would like to work on this.
