### ISSUE TITLE
Eclipse compilation errors after commit c74ff60

### ISSUE THREAD

**Issue by HirdayGupta** [TEAMMATES/teammates#7108]
After merging from the 'TEAMMATES/master' now(13 April) to a test branch (no other commits except a merge from 'TEAMMATES/master' 9 days ago), I was given multiple compile errors by eclipse. After refreshing and cleaning the project, only one error remained.

The error is in **src/test/java/teammates/test/pageobjects/AppPage.java** on the following lines:

``` java
public static LoginPage createCorrectLoginPageType(Browser browser) {
        return getNewPageInstance(browser, TestProperties.isDevServer() ? DevServerLoginPage.class
                                                                        : GoogleLoginPage.class);
    }
```

**Error description by Eclipse:**
> Multiple markers at this line
> 	- Type mismatch: cannot convert from Class \<DevServerLoginPage\> to Class \<T\>
> 	- The method getNewPageInstance(Browser, Class<T>) in the type AppPage is not applicable for the arguments (Browser, 
> 	 (TestProperties.isDevServer() ? DevServerLoginPage.class : GoogleLoginPage.class))

When I force it to proceed with the build to deploy to local server, it gives lots of errors **before** saying _"Dev App Server is now running"_: The entire console output before the success message is [here](https://gist.github.com/HirdayGupta/956fcc4026e1d2c8e4926f372a4d931d).

On visiting `localhost:8888' (because dev server was running) I get an **HTTP ERROR 503** which says:

> Problem accessing /. Reason:
>     SERVICE_UNAVAILABLE

**Pull requests for #7063 and #6805 are on hold for this**

**Comment by Neurrone** [comment]
@HirdayGupta I've found that sometimes you need to do it a few times before it recognizes the updates to all the files.

**Comment by whipermr5** [comment]
@HirdayGupta This is due to c74ff60 which changes some of the IDE settings which breaks existing projects but should be fine for freshly setup ones. To fix, go to project properties -> Java Compiler and set the JDK Compliance level to 1.7. You may also need to follow step 4 subsection `Google App Engine` of [this document](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-usage.md#eclipse-ide).

**Comment by HirdayGupta** [comment]
@Neurrone @whipermr5 Thanks! Changing the compiler compliance level worked.

**Comment by HirdayGupta** [comment]
@whipermr5 @Neurrone Eclipse is giving new problems. I made no preference changes after the previous issue was fixed and somehow managed to get some XML errors out of nowhere. I currently have the following four errors. All of them are only on XML Files.

1. **Error Message:** *cvc-complex-type.2.4.a: Invalid content was found starting with element 'exclude-pattern'. One of '{"http://pmd.sourceforge.net/ruleset/2.0.0":rule}' is expected.*
    - **File:** static-analysis/teammates-pmdMain.xml
    - **Line in Code:** `<exclude-pattern>.*/test/java/.*</exclude-pattern>`

2. **Error Message:** *Referenced file contains errors (http://java.sun.com/xml/ns/jdo/jdoconfig).*
    - **File:** static-analysis/teammates-pmdMain.xml
    - **Line in Code(indicated by eclipse):** `<?xml version="1.0" encoding="utf-8"?>`

3. **Error Message:** *cvc-elt.1: Cannot find the declaration of element 'jdoconfig'.*
    - **File:** src/main/resources/META-INF/doconfig.xml
    - **Line in Code:**  `<jdoconfig xmlns="http://java.sun.com/xml/ns/jdo/jdoconfig"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://java.sun.com/xml/ns/jdo/jdoconfig">`

2. **Error Message:** *cvc-identity-constraint.4.1: Duplicate unique value [appstats] declared for identity constraint "web-app-filter-name-uniqueness" of element "web-app".*
    - **File:** /teammates/src/main/webapp/WEB-INF/web.xml
    - **Line in Code:** `<filter-name>appstats</filter-name>`

**Comment by whipermr5** [comment]
@HirdayGupta Make sure XML validation is [disabled](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-usage.md#eclipse-ide):
```
Validation: We do not validate HTML, JSP, and XML.
Validation → uncheck the Build option for HTML Syntax Validator, JSP Content Validator, JSP Syntax Validator, and XML Validator.
```

After that, redo the steps listed [above](https://github.com/TEAMMATES/teammates/issues/7108#issuecomment-293750635). Note that the settings are lost and you'll need to do those steps again every time you switch to an older branch (even after switching back to the newer branch), so try to update all your branches.

**Comment by HirdayGupta** [comment]
@whipermr5 Thank you so much for the assistance. That seems to have solved the issue.
