### ISSUE TITLE
ide-usage.md: Eclipse section assumes JDK 1.7 default

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#7110]
Even though there is a note that states this is not required, the project fails to build when following the steps exactly if JDK 1.7 is not the default. To fix, an additional step is required:

`Project properties -> Java Compiler -> Tick "Use compliance from execution environment 'JavaSE-1.7' on the 'Java Build Path'"`

Add this additional step with an accompanying screenshot (~~preferably macOS for consistency with the other screenshots~~ use the below screenshot) to `ide-usage.md`.

**Comment by wkurniawan07** [comment]
Actually this is what you need to do:
![screen shot 2017-04-13 at 3 45 16 pm](https://cloud.githubusercontent.com/assets/7261051/24995145/479b06e4-2060-11e7-93f2-7d095e5ee109.png)

Using Java 8 with 1.7 compliance will compile, but it will result in incompatible JSP if I'm not mistaken.

**Comment by whipermr5** [comment]
Even with the correct 1.7 library in the build path, the compliance level can still be wrongly set to 1.8 (and is indeed set to 1.8 if that is the default JDK in Eclipse). This results in the errors shown in #7108.

**Comment by VamsiSangam** [comment]
Can I work on this?

**Comment by whipermr5** [comment]
@VamsiSangam Sure!
