### ISSUE TITLE
ide-usage.md: eclipse setup: correct menu path for project-specific settings

### ISSUE THREAD

**Issue by AnaghHegde** [TEAMMATES/teammates#7136]
In the ide-usage.md in [Step 4](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-usage.md#eclipse-ide) it says 

Configure the following project-specific settings (all can be found in `Project → Properties → ...`):

```
HTML: Web → HTML Files → Editor → Indent using spaces.
CSS: Web → CSS Files → Editor → Indent using spaces.
XML: XML → XML Files → Editor → Indent using spaces.
```

but in both windows and Linux these option is there in  `Window`→ `Preference`

![screenshot from 2017-04-16 03-38-01](https://cloud.githubusercontent.com/assets/12005551/25067103/17e4c694-2257-11e7-9b91-99d96fa86529.png)

**Comment by HirdayGupta** [comment]
Even on the Mac on Eclipse Mars(4.5.0) these settings are in `Eclipse` -> `Preferences`

**Comment by ihsraham** [comment]
Hello! I am new here. I would like to work on this issue.

**Comment by AnaghHegde** [comment]
Hi @ihsraham welcome to teammates. If you are done with the project setup please go ahead and submit a PR. If you are not please setup the project environment locally and then start working on. Thank you.

**Comment by ihsraham** [comment]
I have setup the project environment locally. I wanted know if I should mention separate steps for Eclipse on Mac i.e. Eclipse -> Preferences while for Windows and Linux its Window -> Preferences?
