### ISSUE TITLE
New Contributor Self-Intro: Assan Toleuov

### ISSUE THREAD

**Issue by AToleuov** [TEAMMATES/teammates#7139]
- **Link to my app:** https://teammates-assan.appspot.com
- **Link to my fork:** https://github.com/atoleuov/teammates

**Screenshot of changes made**
As seen on the UI, I modified the main page by structuring the information into table grid and putting the dynamic content (user testimonials) at the top for better user experience.

<img width="1280" alt="screen shot 2017-04-16 at 06 33 15" src="https://cloud.githubusercontent.com/assets/13019554/25067726/a502246a-226e-11e7-9772-3def1a8aaa38.png">

**Short self-introduction**
My name is Assan Toleuov. I am a 4-year student at Nazarbayev University, Astana, Kazakhstan. I am here, because of two reasons. First, I want to get more experience in real-world software development by working on big projects. And second, this is part of my Open Source Software class which I am taking right now. TEAMMATES seems to be very interesting and pretty welcoming for newly joining developers. I hope that my work would be productive while I am here with the community.

**Comment by Neurrone** [comment]
Hi @AToleuov, welcome to TEAMMATES!

You can start by fixing a [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue to become familiar with our workflow, and then move on to [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors).
