### ISSUE TITLE
Admin emails: Add tests for sending email using groupmode

### ISSUE THREAD

**Issue by Mynk96** [TEAMMATES/teammates#7140]
Test cases present only to check addressmode of AdminEmailPage.

**Comment by Mynk96** [comment]
working on it!

**Comment by Mynk96** [comment]
@xpdavid thinking of using javascriptexecutor for uploading files as the input is hidden!
Can you suggest me any better appraoch?

**Comment by Mynk96** [comment]
@xpdavid can you please suggest me how to verify the encoded key that comes in, after uploading group receiver's list?

**Comment by xpdavid** [comment]
Sorry for the late reply. I am doing my exams revision this days. I suggest you to write an action test first before writing UI test. Take a look at `StudentProfilePictureEditActionTest` to get a rough idea.

**Comment by Mynk96** [comment]
@xpdavid Okay, I'll proceed that way.
