### ISSUE TITLE
USA and references to the United States of America should come first.

### ISSUE THREAD

**Issue by TheRealDonaldJTrump** [TEAMMATES/teammates#7143]
**Description of feature/enhancement**

`USA` and `American` should appear before the entries of other countries and nationalities, in any occurrences within lists, both ordered and unordered, and dropdown menus.

**Justification**

From this day forward, a new vision will govern our land. From this day forward, it’s going to be only America First. 

**Existing similar features and their shortcomings**

America isn't first.

# **MAKE AMERICA GREAT AGAIN**

**Comment by damithc** [comment]
Issue not suitable for public discussion. To be discussed internally.
