### ISSUE TITLE
New contributor self intro Nassim Bou Ghannam

### ISSUE THREAD

**Issue by nassimbg** [TEAMMATES/teammates#7146]
- My App: [https://teammates-nassim.appspot.com/](url)

- Fork: [https://github.com/nassimbg/teammatesBG](url)

![image](https://cloud.githubusercontent.com/assets/27228405/25072625/31faa578-22dc-11e7-96d5-0f49728ee821.png)
![image](https://cloud.githubusercontent.com/assets/27228405/25072627/4284f38a-22dc-11e7-8cc2-00616211536e.png)
![image](https://cloud.githubusercontent.com/assets/27228405/25072628/4b459efc-22dc-11e7-9b32-a856ba44b8e8.png)

- Hello,
My name is Nassim Bou Ghannam, I have majored in Software Engineering at the American University of Beirut.
I have been working as a java back-end developer, and I have experience with several other languages such as Python, C++, PHP, JS... I'm here to contribute to open source projects with the hope of learning some new technologies.

**Comment by Neurrone** [comment]
Hi @nassimbg, welcome to TEAMMATES!

You can start by fixing a [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue to become familiar with our workflow, and then move on to [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors).

**Comment by nassimbg** [comment]
Hey @Neurrone,

Thank you
