### ISSUE TITLE
New contributor selfintro Quentin Lassalle

### ISSUE THREAD

**Issue by qlassalle** [TEAMMATES/teammates#7152]
- Link to my app : http://teammates-qlassalle.appspot.com

- Link to my fork : https://github.com/qlassalle/teammates

- The changes I've done to the UI :

![capture d ecran 2017-04-17 a 13 27 48](https://cloud.githubusercontent.com/assets/9036994/25087801/e54de8ca-2371-11e7-8e5a-530d1733f51d.jpg)

![capture d ecran 2017-04-17 a 13 29 52](https://cloud.githubusercontent.com/assets/9036994/25087806/fa47b134-2371-11e7-86b5-27e70715adf8.jpg)

![capture d ecran 2017-04-17 a 13 30 14](https://cloud.githubusercontent.com/assets/9036994/25087813/0299b922-2372-11e7-95f3-d3a6e8c19494.jpg)

As you can see I added a table to the contributors part in the "About us" page and did a small change to the "Join us" sentence.

I'm Quentin Lassalle, a CS student in France, near Paris. I used to work at Thales for 1 year and a half doing Web development (with the CakePHP framework). I hope I'll learn a lot of things contributing to this project !

**Comment by wkurniawan07** [comment]
@qlassalle welcome to TEAMMATES community!
Good job on setting up your own development environment and deploying to your own staging server! You can start contributing by fixing a `d.FirstTimers`-labelled issue (do just one of this), followed by `d.Contributors`-labelled issues. Looking forward to your contributions!

**Comment by qlassalle** [comment]
@wkurniawan07 Thanks a lot ! I'm going to look for some `d.FirstTimers`-labelled issues to get started !
