### ISSUE TITLE
Uncaught typo in FeedbackResponseCommentRow.java 

### ISSUE THREAD

**Issue by sdweber422** [TEAMMATES/teammates#7155]
Typo caught in issue #6989 also found in src/main/java/teammates/ui/template/FeedbackResponseCommentRow.java

Typo did not show up in CheckStyle Audit: 
https://htmlpreview.github.io/?https://github.com/xpdavid/CS2103R-Report/blob/master/codingStandard/spelling/main.html#f-/Users/XP/Documents/teammates-git/src/main/java/teammates/ui/template/FeedbackResponseCommentRow.java

responseVisiblities is not a word according to provided dictionary. Multiple occurences beginning with: 
```
Map<FeedbackParticipantType, Boolean> responseVisiblities)
```

**Comment by wkurniawan07** [comment]
@xpdavid I guess you have not run the analysis on method parameters yet, right?

**Comment by xpdavid** [comment]
Haven't run the analysis on methods' name and parameters' name :P

**Comment by thejosharcher** [comment]
I can correct this!
