### ISSUE TITLE
Help Request: "Unexpected token" errors in .js files in the node_modules folder 

### ISSUE THREAD

**Issue by rchliu** [TEAMMATES/teammates#7156]
- **Operating System:** Windows 10
- **JDK Version:** 1.7
- **Eclipse / IntelliJ Version (if applicable):** Neon 4.6.3 - JEE
- **Firefox / Chrome Version (where applicable):**

My current installation of Node is 6.10.2, with npm 3.10.10. 

**What I was trying to do / What I need help with**
I'm in the process of setting up the dev environment with Eclipse. After cleaning the project, I'm receiving many syntax errors with the .js files in the `node_modules` folder that was created from npm install. 

These primarily seem to be caused by the import/export statements present in some of the modules, as well as with the shebang lines at the beginning of js files:

![screenshot](https://cloud.githubusercontent.com/assets/8629449/25112469/687afd8a-23bf-11e7-8994-09827cc3454d.png)

A Google search tells me that Node currently doesn't support ES6's import/export. I noticed that #6962 faced a similar issue, but I'm not sure what came of that. 

**Attempts to resolve the problem**
I have:
- deleted and reinstalled the `node_modules` folder
- reinstalled Node and npm (still using latest stable version)
- installed a fresh copy of Eclipse with only the project-relevant plugins
- done this using an unmodified clone of the project

**Comment by whipermr5** [comment]
The contents of the libraries in `node_modules` are out of the scope of our project, and shouldn't be validated.

To disable validation for this folder:
`Preferences` -> `Validation` -> `JavaScript Validation | Settings (...)` -> `Add Exclude Group...` -> select newly added `Exclude Group` -> `Add Rule...` -> select `Folder or file name`; click `Next >` -> `Browse Folder...` -> navigate to `node_modules` -> `Finish`

**Comment by rchliu** [comment]
Okay, that makes sense. Thanks!

**Comment by sud1989** [comment]
Hi,
I am facing similar issues with the project setup. 
They don't go away even after excluding folder node_modules from JS validation
