### ISSUE TITLE
Intellij setup: Add back the Staging tests config file

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7157]
The Intellij config file for staging tests was added in #6824 but has gone missing again.

**Comment by wkurniawan07** [comment]
This is my doing in #6980. What is the purpose of staging tests?

**Comment by damithc** [comment]
Those are the tests run against the live server before deployment.

**Comment by damithc** [comment]
@LiHaoTan can take a shot at this one? Otherwise I have to patching this in after every release.

**Comment by LiHaoTan** [comment]
@damithc sorry for the delay but I haven't got around to finish the things I wanted in the PR since I upgraded the scope. Do you still need this? I can resolve this issue independently (albeit it may not be ideal) and do a follow-up.

**Comment by damithc** [comment]
I guess no need. I can run the full test suite against the live server.
