### ISSUE TITLE
ide-usage.md: Add steps to disable JavaScript validation for node_modules folder in Eclipse

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#7159]
The `node_modules` folder contains external JavaScript libraries and do not need to be validated. Skipping validation will save a lot of CPU resources and avoid issues like #7156.

The steps are:
`Preferences` → `Validation` → click `...` settings button for `JavaScript Validation` → click `Add Exclude Group...` if `Exclude Group` is not already in the list → `Exclude Group` → `Add Rule...`  `Folder or file name` → `Next >` → `Browse Folder...` → navigate to `node_modules` → `Finish`

**Comment by wkurniawan07** [comment]
Apologies for this, I missed this because my Eclipse has been configured to skip such validation since long ago 😅

**Comment by HirdayGupta** [comment]
@whipermr5 are you sure this would be a `d.Contributors` issue and not a `d.FirstTimers` one? Will work on it if it is definitely the former.

**Comment by whipermr5** [comment]
@HirdayGupta You're right; I guess it should be a `d.FirstTimers`.

**Comment by Yogitha6** [comment]
I am working on this. (I am a first timer contributing to open source projects)
