### ISSUE TITLE
ide-usage.md: Wrong order of running gradle task setupIntellij for IntelliJ setup

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#7160]
The doc states that `./gradlew setupIntellij` should be run before importing the project. However, during project import, IntelliJ asks if it can overwrite the existing `.idea` folder, which contains the launch configurations generated by `./gradlew setupIntellij`. The command then has to be run again to get the launch configurations.

The command `./gradlew setupIntellij` should be moved to the last step.

**Comment by saching97** [comment]
@whipermr5 I'll be working on this
