### ISSUE TITLE
InstructorRequestAccount: Move from Google Forms to a "Proper Request System"

### ISSUE THREAD

**Issue by nikiforosbotis** [TEAMMATES/teammates#7161]
Dear All,

I have chosen to work (and I have already started to doing so) with the creation of a "proper request system" instead of the Google Form in the "request.jsp" page, as proposed in [that](https://docs.google.com/document/d/1hjQQHYM3YId0EUSrGnJWG5AeFpDD_G7xg_d--7jg3vU/pub?embedded=true) page. 

First of all, I would like to ask you where the data obtained from the form should be stored. I guess I should not immediately create a new instructor based on this data since a first approval should be given by the administrator, right? Or we can automate this process by saying, for example, if this instructor belongs to one of the following universities, we will accept him and we will provide him with details for creating his account? Based on that question, I was wondering if I should work with the same way as you have been worked in other forms that I found (e.g. form action="${data.instructorCourseEnrollSaveLink}) or whether I should follow another path in order to store the obtained data and make them available to the admin.

I have created a small prototype of how the form will look like in order to get your feedback:
![instructorrequest](https://cloud.githubusercontent.com/assets/9116253/25121731/556e3ed4-242b-11e7-97f3-7ffee185d340.png)

Thank you in advance for your time.

**Comment by nikiforosbotis** [comment]
@damithc I see what you mean but I consider it as a very good way in order to familiarize myself with the project and contribute to it. Is it impossible to get some help on that? I have already done some work and I really believe that I can produce a nice result.

**Comment by damithc** [comment]
You are right, it will force you to touch most aspects of TEAMMTES. However, this feature is bigger than it appears at first because it also need to cover approval by admin and account creation. It will also require adding test cases which is not trivial. We prefer 'work with existing feature to learn' over 'adding new features to learn'.
For the next couple of weeks we are going to be very low on 'dev help' because it's the exam period for most of our core developers. That's one more reason not to start this feature at this time.

**Comment by nikiforosbotis** [comment]
@damithc ok, I understand your point. Can you propose me something to do in which I will be provided with support when needed, and it will be suitable for someone who tries to do his first contribution to an OS project?

**Comment by damithc** [comment]
@nikiforosbotis you can pick one of the `d.Contributors` issues.
