### ISSUE TITLE
Not able to create feedback session in dev server

### ISSUE THREAD

**Issue by AnaghHegde** [TEAMMATES/teammates#7162]
I tried in both chrome as well as firefox but it's not giving the option to create session. I also tried with 
` /admin/adminHomePage` and then creating an instructor from there but still the same issue.

![screenshot 126](https://cloud.githubusercontent.com/assets/12005551/25127522/c813910a-2453-11e7-9bb0-34175f0be022.png)

**Comment by damithc** [comment]
Why is there an `isusingAjax=on` at the end of the url?

**Comment by AnaghHegde** [comment]
Honestly i don't know.

**Comment by damithc** [comment]
it's for the same reason (the extra parameter). Start by loading localhost:8888 and navigate from there to try to figure out at what point the extra parameter gets added to the URL.

**Comment by AnaghHegde** [comment]
>navigate from there to try to figure out at what point the extra parameter gets added to the URL.

You mean to instructor home page ?. I already tried that.

**Comment by damithc** [comment]
Start from `localhost:8888/page/instructorHomePage` and see at what point the extra parameter gets added to the url. Also, do you observe the problem at v5.102? I tried that version today and there was no such problem.

**Comment by AnaghHegde** [comment]
> Also, do you observe the problem at v5.102

Yes. The latest commit in local env is ca4ff7f . I have added the screen recording [here](https://app.hyfy.io/v/ab3883BJkoU/). Take a look at it.

**Comment by damithc** [comment]
Let's wait to see if anybody else faces the same problem. I deployed v5.102 today and it did not have this problem.

**Comment by wkurniawan07** [comment]
It looks like you're using outdated JavaScript files. Try running `npm run build` and see if it persists.

**Comment by AnaghHegde** [comment]
@wkurniawan07 I am sure that, it's not the case. I already tried that.

**Comment by wkurniawan07** [comment]
You may need to clear your browser cache for the changes to take effect.

**Comment by AnaghHegde** [comment]
I have disabled the firefox browser cache as mentioned the dev step.

**Comment by wkurniawan07** [comment]
Can you tell me the contents of `instructorFeedbacksSpecific.js` that is loaded by that page?

**Comment by AnaghHegde** [comment]
What do you mean by contents of `instructorFeedbacksSpecific.js`. What exactly are you expecting.

**Comment by wkurniawan07** [comment]
Exactly that. If you have run `npm run build`, there should be some JS files on top of ES6 files. I want to know the contents of that one specific JS file. Actually, just the first 5-10 lines will do.

**Comment by AnaghHegde** [comment]
Yeah its there. 
```
"use strict";

/* global readyFeedbackPage:false */

$(document).ready(function () {
    readyFeedbackPage();
});
```

**Comment by wkurniawan07** [comment]
My suspicion is confirmed: you're not using the latest JS files. Please do not claim as such if you are not sure.
Running `npm run build` would solve the problem.

**Comment by AnaghHegde** [comment]
I did run the `npm run build` after the case #7118.

**Comment by wkurniawan07** [comment]
You'd notice how different your `instructorFeedbackSpecific.js` file is when compared to [its latest ES6 counterpart](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/js/instructorFeedbacksSpecific.es6). When you ran the `npm run build` before, which commit was your branch at? Was it c74ff60 or before?

**Comment by AnaghHegde** [comment]
After the commit c74ff60 only i opened the issue #7118. So i don't remember exactly which commit i was at. Moreover a strange thing i observed is only some were working(js files) and some of them not. This is the case in my issue. Only 2 pages weren't working as expected(may be more) .

**Comment by AnaghHegde** [comment]
![screenshot from 2017-04-18 23-51-27](https://cloud.githubusercontent.com/assets/12005551/25146618/248d39ac-2492-11e7-9344-4450a91e0b8f.png)
Also any idea why the eclipse might not be showing .js file after transpiling ?

**Comment by HirdayGupta** [comment]
@AnaghHegde try refreshing eclipse to see if it displays the js files. And also ensure you are on the same branch as you were when you did run the `npm run build` command.

**Comment by AnaghHegde** [comment]
@HirdayGupta Its working. It was just a one time thing.
