### ISSUE TITLE
Instructor: download results: include only the selected section

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7164]
Current:
An instructor can choose to show results of a specific section.
![section](https://cloud.githubusercontent.com/assets/794011/16062246/2ac6e310-3292-11e6-8a6c-5a9fda6ffa5f.png)
However, when the instructor downloads the results using the `Download Results` button, all responses of that session are in the downloaded csv file.

Suggestions:
Only responses for the selected section should be in the downloaded csv file.

Justification: 
This allows downloading responses one section at a time, which is useful when the course is big.

Other notes: This was supposed to be implemented long time ago ( #5628 ) but somehow doesn't seem to be working now.

**Comment by sdweber422** [comment]
I would like to work on this.

**Comment by damithc** [comment]
Looks like only the 'response summary' part honors the selected section. The individual responses for the whole cohort is included irrespective of what section is selected.

**Comment by damithc** [comment]
@sdweber422 we are not sure how difficult this one is as we don't know the cause of the problem. You are welcome to try but recommended to choose a `d.Contributor` issue first.

**Comment by AnaghHegde** [comment]
@damithc Shall i try to investigate this ?.
