### ISSUE TITLE
InstructorHomePageUiTest: remove redundant reloading of previous page

### ISSUE THREAD

**Issue by sujeet14108** [TEAMMATES/teammates#7165]
Non Needed redirection in UInstructorHomePageUiTest 

 No need of redirection ( `homePage.goToPreviousPage(InstructorHomePage.class);` ) while testing remind button as the browser remains in the home page after sending a reminder

**Comment by sujeet14108** [comment]
working on it

**Comment by damithc** [comment]
@sujeet14108 can make the issue description a bit more informative? Also, I suggest we leave this for first timers as it simply requires deleting some lines.

**Comment by sumit-nsit** [comment]
Hey, I am a first timer and would love to solve it. I understand the line you want to have removed, can I commit change?

**Comment by sujeet14108** [comment]
So there are multiple test case in the class where there is this type of redirection.
You have to remove all those.

**Comment by sumit-nsit** [comment]
I found two. you think there would be more?

**Comment by sujeet14108** [comment]
@sumit-nsit I don't know the exact number. You should go for it and submit a PR.

**Comment by btrajanovski** [comment]
Hi guy, I was able to fix the problem ad submitted it for review.

**Comment by stellargo** [comment]
@damithc could you provide a little more details as to from which parts is this redirection need to be removed, like everywhere in InstructorHomePageUiTest.java?

**Comment by ncbaihly** [comment]
Is @stellargo still working on this or could I pick it up for a first time PR?

**Comment by orinn248** [comment]
I committed a fix in reference to this issue.  I see it listed above but I'm still unsure whether I'm supposed to issue a pull request on it. Any help would be appreciated.
