### ISSUE TITLE
New contributor self intro Josh Archer

### ISSUE THREAD

**Issue by thejosharcher** [TEAMMATES/teammates#7172]
- Link to my app: https://teammates-josharcher.appspot.com

- Link to my fork: https://github.com/thejosharcher/teammates

<img width="1667" alt="screen shot 2017-04-19 at 12 21 30 am" src="https://cloud.githubusercontent.com/assets/5824152/25163460/9176f476-2498-11e7-9e17-dcf0c82db9e7.png">

My GUI change was in the about.jsp. I dropped the "Would you like to join the TEAMMATES team as a contributor? Contact Us." down with an hr tag above it and centered the p tag containing the sentence. 

My name is Josh Archer. I am a graduating student from Georgia Southern University. I am starting as an Associate Software Engineer for Greenway Health in May.

**Comment by whipermr5** [comment]
Hi Josh, welcome to TEAMMATES! Good job setting everything up correctly :)

I see that you've already started on a [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue; that's great! You can feel free to move on to [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors) issues too while waiting for that to be reviewed/merged.
