### ISSUE TITLE
Help Request: Missing library org.kohsuke

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7174]
- **Operating System:** Windows 10
- **JDK Version:** 1.7
- **Eclipse Version (if applicable):** Kepler Service Release 2

**What I was trying to do / What I need help with**
Upon `Project -> Clean` these errors show up.

![error](https://cloud.githubusercontent.com/assets/11662001/25166700/41976168-24fa-11e7-89ec-56ae41166ea0.JPG)

How can I add the missing library?

**Comment by whipermr5** [comment]
[Troubleshooting guide](https://github.com/TEAMMATES/teammates/blob/master/docs/troubleshooting-guide.md)

Solution:
`./gradlew resetEclipseDeps`

**Comment by VamsiSangam** [comment]
Thanks! That solved my issue :tada:
