### ISSUE TITLE
Help Required: New Eclipse build issues after merging latest commits involving the scalability tests

### ISSUE THREAD

**Issue by HirdayGupta** [TEAMMATES/teammates#7178]
Eclipse is giving the following compile time errors after merging the latest commits into my branch:

<img width="1208" alt="screen shot 2017-04-19 at 10 45 57 pm" src="https://cloud.githubusercontent.com/assets/18088721/25201505/96206dea-256f-11e7-99d8-e03d08b0e7a2.png">

My JDK compliance is at 1.7, and I am pretty sure I've followed each step in the setup guides.

**Comment by AnaghHegde** [comment]
@HirdayGupta Try cleaning the project and rebuild it. Also check the Data Nuclues version and  ORM as well. In my case it got changed to something else.

**Comment by whipermr5** [comment]
Dependencies have been updated; you need to run `./gradlew resetEclipseDeps` to get the new libraries.

**Comment by HirdayGupta** [comment]
@whipermr5 thanks! `./gradlew resetEclipseDeps` solved it. Thoughts on adding a documentation file for current developers which should be updated every time a commit requires steps like this?

**Comment by whipermr5** [comment]
The step is already documented in [dependencies.md](https://github.com/TEAMMATES/teammates/blob/master/docs/dependencies.md). The [troubleshooting.md](https://github.com/TEAMMATES/teammates/blob/master/docs/troubleshooting-guide.md#common-test-errors-and-solutions) doc also links to it under `Common test errors and solutions`.

**Comment by HirdayGupta** [comment]
@whipermr5 Thanks for the links! I didn't just mean about `./gradlew resetEclipseDeps` though. What I meant was a document that is **required** to be updated each time someone adds a commit that will require similar steps (eg: updating dependencies, changing a setting,etc). Essentially something for **existing** devs to refer to each time a new commit breaks the project. (Something like: <Commit Number>: <Additional Step>).

**Comment by damithc** [comment]
Yes it would be nice to have some way to inform developers when they need to do some additional steps. We haven't figured out a good way to do that yet though.
