### ISSUE TITLE
InstructorFeedbacksPageAction.java: change Feedbacks -> FeedbackSessions

### ISSUE THREAD

**Issue by thejosharcher** [TEAMMATES/teammates#7185]
Typo caught in the class /src/main/java/teammates/ui/controller/InstructorFeedbacksPageAction.java. InstructorFeedbacksPageAction is not a word according to the provided dictionary. The 's' should be removed from Feedback, and the updated name should change across the project. 

CheckStyle did not catch. I believe it is the same as in #7155.

**Comment by damithc** [comment]
This could be a case of using `Feedbacks` as a shorter form of `FeedbackSessions`. I don't mind changing to the longer form though as long as its done everywhere.

**Comment by Yogitha6** [comment]
I am working on this. I am a first timer in open source development.

**Comment by damsehgal** [comment]
@thejosharcher @damithc Can I be assigned to fix this issue as my first "d.FirstTimers" commit?

**Comment by Yogitha6** [comment]
@damsehgal There is no assigning. You can comment saying you are working on this issue and start working on it if no one else is working on it.

**Comment by damsehgal** [comment]
@thejosharcher @damithc @Yogitha6 I am working on tihs issue.

**Comment by VamsiSangam** [comment]
Hi @damsehgal ! I guess this is your first issue in TEAMMATES, in which case, welcome to TEAMMATES! :smile: Please have a look at the [Orientation guide](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md), this is a must-do for first timers so that they can setup the project locally without any hassles and can contribute smoothly! Looking forward for your contributions!!

**Comment by Yogitha6** [comment]
@damsehgal @VamsiSangam , Yes I guess he didn't do the New Contributor Issue posting yet. My bad, I didn't check that before replying to him. Vamsi is totally right. You need to follow the Orientation guide before making your first contribution.

**Comment by SELVAKUMAR-S** [comment]
hi team, i would like to work on this issue as my first task and i have done my orientation task under #7558

**Comment by VamsiSangam** [comment]
Sure @SELVAKUMAR-S , feel free to work on this issue and submit a PR when ready :smile:

**Comment by SELVAKUMAR-S** [comment]
thanks, working on this !!!

**Comment by damithc** [comment]
I'm not sure how extensive this change is going to be. May be first we should find out how many places need changing.

**Comment by SELVAKUMAR-S** [comment]
Sure @damithc , will work on this based on the suggestions from PR #7581
