### ISSUE TITLE
New contributor self intro Richard Liu 

### ISSUE THREAD

**Issue by rchliu** [TEAMMATES/teammates#7189]
**Link to my app:** 
https://teammates-rchliu.appspot.com/

**Link to my fork:** 
https://github.com/rchliu/teammates

**Screenshot of changes made (as seen on the UI)**
![fork](https://cloud.githubusercontent.com/assets/8629449/25308906/6aac4a92-278d-11e7-8a51-e15c13a4c95a.png)

I added a drop down menu to the About section on the navbar with links to the user map and the TEAMMATES blog. 

**Short self-introduction**
Hey, everyone! My name's Richard and I'm a first year (soon to be second year) computer science student at the University of Waterloo, in snowy Canada. I've been programming for a few years now but have never dipped my toes into open source software before, so I'm excited to start contributing to this project and learn more about development along the way.

**Comment by whipermr5** [comment]
Hi Richard, welcome to TEAMMATES! Good job setting everything up correctly and running the tests :) You can get your feet wet by working on a [`d.FirstTimers`](https://github.com/TEAMMATES/teammates/issues?q=is%3Aissue+is%3Aopen+label%3Ad.FirstTimers) issue.
