### ISSUE TITLE
Use builder instead of telescoping constructor antipattern in Attributes classes

### ISSUE THREAD

**Issue by LimeTheCoder** [TEAMMATES/teammates#7190]
Builder pattern is used for constructing objects with a lot of parameters, especially if many of these parameters are null and when many of them share the same data type.With builder pattern client code benefits greatly in terms of usability and readability. The parameters to the constructor are reduced and are provided in highly readable method calls.

**Comment by BrianCoveney** [comment]
Hi, I've started working on AccountAttributes. Hope that's ok @LimeTheCoder and @whipermr5

**Comment by whipermr5** [comment]
Effort tracker, to be updated as each PR is merged:

| PR | Effort |
| - | - |
| #7191 | 4 |

**Comment by craaaa** [comment]
I'll take a stab at `CourseAttributes`!

**Comment by xpdavid** [comment]
This issue will be solved along with #9466, which will add builder for feedback response.
