### ISSUE TITLE
New contributor self intro Yogitha Mahadasu

### ISSUE THREAD

**Issue by Yogitha6** [TEAMMATES/teammates#7194]
**Link to my app:**
https://teammates-yogitha.appspot.com/

**Link to my fork:**
https://github.com/Yogitha6/teammates

**Screenshot of changes made (as seen on the UI)**
![changeinui](https://cloud.githubusercontent.com/assets/13936975/25319096/053110f6-2857-11e7-89e3-a844421b8d97.JPG)

I changed the lay out of the core team. It seemed a little too much of scrolling. I thought we can have better usage of space by utilizing bootstrap grid layout.

**Short self-introduction:**
Hello everyone! I am Yogitha Renu Mahadasu, a master's student in Computer Science department at University of Colorado, Boulder. I worked as a Java Developer for CA Technologies for 2years and I have web development experience of over 4 years. I am starting as a Senior Systems Engineer at Visa Inc in June. This is my first attempt to contribute to an open source project. The documentation of this project is great and I was able to get started without running into major issues. My contribution here is for one of my course projects at CU - Open Source Development. Course Content: https://github.com/nmcclain/CSCI4830-009

**Comment by Neurrone** [comment]
Hi @Yogitha6, welcome to TEAMMATES!

You can start by fixing a [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue to become familiar with our workflow, and then move on to [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors).
