### ISSUE TITLE
Change alert type from success to info in Admin Activity Log and Email Log 

### ISSUE THREAD

**Issue by Mynk96** [TEAMMATES/teammates#7197]
![finalchange](https://cloud.githubusercontent.com/assets/17481466/25338209/07f75744-291c-11e7-8731-5b62d5829aea.PNG)

**Comment by VamsiSangam** [comment]
@Mynk96 are you working on this or can take p this issue?

**Comment by Mynk96** [comment]
@VamsiSangam working on it.
