### ISSUE TITLE
Unclear "p" in the Admin Email Compose Page

### ISSUE THREAD

**Issue by sujeet14108** [TEAMMATES/teammates#7201]
Is the below "p" is doing something or has any meaning ?
It seems to be a button but use is not clear.

![imageedit_2_7058302007](https://cloud.githubusercontent.com/assets/9781422/25363084/db4a75dc-2975-11e7-841b-e7829dfe7a6f.gif)

**Comment by VamsiSangam** [comment]
Hi @sujeet14108 ! That `p` is not a button. It is related to the HTML which is rendered from the message you type. The normal text you type is put into HTML `<p>` tags, which is what that `p` stands for. If you were typing an un-ordered list item, then it would show `ul > li` as such -

![capture](https://cloud.githubusercontent.com/assets/11662001/25363523/c8f37278-2978-11e7-9296-df76edf8e59e.JPG)

So, the text there shows in which level of nesting of HTML tags are you typing currently. You can click `Tools` -> `Source Code` to check out the HTML which is generated from the message you typed. For example -

![capture](https://cloud.githubusercontent.com/assets/11662001/25363609/7dfca91e-2979-11e7-9bf1-5c15196131bb.JPG)

So as per this HTML, if my cursor in the text box is near 'Lorem Ipsum', then I am actually typing a `<p>` tag which is what it shows. And if my cursor was near 'Hello', then I am actually typing an `<li>` tag inside a `<ul>` tag which is what gets displayed. I hope this clarifies the issue. Feel free to ask again if you have anymore confusion. :smile:

**Comment by sujeet14108** [comment]
@VamsiSangam What is need of this from user perspective ?

**Comment by VamsiSangam** [comment]
It serves a similar purpose as HTML breadcrumbs in your IDE. 

![b7923006-29bd-11e7-888c-ac4fa0e79f99](https://cloud.githubusercontent.com/assets/11662001/25375359/13a09298-29be-11e7-8d71-8d9385452573.JPG)

When we write very very long paragraphs nested deep inside we are often confused at which level we are. Looking at the text at the left bottom helps us to keep a track of where we are. In IDEs this confusion is less as we have opening and closing tags. But where as the text box in `adminEmailComposePage` where we don't even have opening and closing tags, we are bound to loose a track of where we are very easily.

![capture](https://cloud.githubusercontent.com/assets/11662001/25375287/d9deac84-29bd-11e7-801a-2ab2bbbebbe9.JPG)

The picture above has very little text, but imagine if you were writing around 200+ words at each level, it could be hard for you to keep track of where you are. You might end up scrolling up and down to check at which level you are. The text at the bottom right corner simplifies that.

Additionally, that text in `adminEmailComposePage` performs an another functionality. Clicking on a tag highlights the text which belongs to a particular tag. As such -

![capture](https://cloud.githubusercontent.com/assets/11662001/25375747/615e2080-29bf-11e7-8908-ca503337f294.JPG)

In the above pic I clicked on the last `ul`, couldn't capture the cursor.

**Comment by sujeet14108** [comment]
Thanks understood :)
