### ISSUE TITLE
Give an alternative link to the account request form

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7202]
Some users have mentioned that they cannot see the account request form (possibly a problem with embedding googledoc form). 
![image](https://cloud.githubusercontent.com/assets/1673303/25419088/ee0c6320-2a82-11e7-9f18-84533ced528a.png)

Suggestion:
Just below the page title, include a `Cannot see the form? click here` with a direct link to the form.

**Comment by damithc** [comment]
Another user reported this. I experienced the problem myself when I tried. The embedded form did not load but the direct link worked

**Comment by Yogitha6** [comment]
I can work on this as it is not a FirstTimers issue anymore.

**Comment by Yogitha6** [comment]
Issue is fixed, build is successful, PR #7214 is ready for review

**Comment by damithc** [comment]
I've deployed a temporary fix for now.
