### ISSUE TITLE
studentList.tag: prevent 'Add Comment' button causing a 'page not found' error

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7203]
**Description of feature/enhancement**

In `instructorStudentListPage` and `instructorCourseDetailsPage` (both of which rely on `studentList.tag`), the "Add Comment" button click leads to `pageNotFound.jsp`. We could instead trigger the dropdown to display upon clicking the "Add Comment" button or the down caret button beside it.

**Justification**

"Add Comment" which is mainly used to display the tooltip is still clickable nonetheless and redirects user to `pageNotFound.jsp`. User might not like to see a **Page not found** warning all of a sudden when the tooltip nicely said "Give a comment to student...".

This issue is to eliminate the exposed possibility of user getting a warning. My suggestion is to trigger the dropdown on any of the buttons. Other suggestions are most welcome.

**Comment by damithc** [comment]
@VamsiSangam did you mean the button shown below? I tried the current version (v5.102) and it does not lead to a 'page not found'.  Did I misunderstand the issue?
![image](https://cloud.githubusercontent.com/assets/1673303/25432981/4e5ffa08-2ab9-11e7-87ca-d16555125cc4.png)

**Comment by VamsiSangam** [comment]
No sir, I meant these in `instructorStudentListPage` -

![1](https://cloud.githubusercontent.com/assets/11662001/25433233/4993b8b6-2aa5-11e7-807f-e455c0ae09dc.JPG)

and similar buttons in `instructorCourseDetailsPage` -

![2](https://cloud.githubusercontent.com/assets/11662001/25433260/5cf31e2e-2aa5-11e7-9796-7f8813105a14.JPG)

both of which are generated from `studentList.tag` file.

**Comment by damithc** [comment]
@VamsiSangam good catch. 👍

**Comment by VamsiSangam** [comment]
Can I take up this issue?

**Comment by damithc** [comment]
> Can I take up this issue?

Sure @VamsiSangam
