### ISSUE TITLE
 New Contributor Self-Intro Dhruv Sehgal

### ISSUE THREAD

**Issue by damsehgal** [TEAMMATES/teammates#7207]
- **https://teammates-damsehgal.appspot.com**
- **https://github.com/damsehgal/teammates**

**![Screenshot](http://oi68.tinypic.com/adhnnm.jpg)**
I don't know much about HTML, CSS or front - end developement. So, I just changed the color of login buttons on top right corner to #00FFFF.

**My name is Dhruv Sehgal. I am final year undergrad student at Thapar University. I am a competitive programmer and have experience with C++ and Java. I am here to contribute to open source project and to learn how large projects actually work.**

**Comment by damithc** [comment]
Welcome to TEAMMATES @damsehgal
