### ISSUE TITLE
Instructor: view results: rubric questions: give stats per recipient per sub-question

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7208]
Suggestion:
When instructors view/download results of a rubric question, we can also give per-recipient stats (total, average, etc.) for each sub-question, if there are weights attached to each response.
![image](https://cloud.githubusercontent.com/assets/1673303/25556539/fa7704b6-2d30-11e7-8543-c7e488f1c66c.png)

**Comment by Yogitha6** [comment]
Can I work on this?

**Comment by AnaghHegde** [comment]
@Yogitha6 Sure, go ahead.

**Comment by Yogitha6** [comment]
@AnaghHegde , Thank you. I am working on this.

**Comment by Yogitha6** [comment]
@damithc 
Prof,
Could you confirm if the following information is what we are looking for when an Instructor downloads results for rubric questions?

![rubricquestionperrecipientstats](https://cloud.githubusercontent.com/assets/13936975/25567196/b2e9a386-2da5-11e7-9f21-75aafe794908.JPG)

Am I missing some information that needs to be displayed as part of this issue?

**Comment by damithc** [comment]
Yes. You can also show total (e.g. `10`) and values received e.g. (`5,5`).

**Comment by Yogitha6** [comment]
Ok, so do I add new columns before average to show the **total** and **values received** as per your suggestion?
Or just Team, Name, Email, Sub Question, Total, Values received would be good enough ?

**Comment by damithc** [comment]
> Ok, so do I add new columns before average to show the total and values received as per your suggestion? Or just Team, Name, Email, Sub Question, Total, Values received would be good enough ?

@Yogitha6 `Average` is the important one. The other two are nice to have.

**Comment by Yogitha6** [comment]
Ok Professor.
I started working on making changes to the code. I should make a PR in a day or so.

**Comment by Yogitha6** [comment]
Couldn't make great progress though I figured out what files to modify and started working on it,  because of my exams and project demos this week. Will it be ok if I make a PR for this issue next week?

**Comment by VamsiSangam** [comment]
Working on this.

**Comment by VamsiSangam** [comment]
Sir, the this is what currently an instructor gets when he/she downloads results for rubric question -

![capture](https://user-images.githubusercontent.com/11662001/27818934-908d7126-60b5-11e7-93bb-01f338fdc705.JPG)

I am planning to add a new table in between like this -

![2](https://user-images.githubusercontent.com/11662001/27818948-a3456940-60b5-11e7-8d91-05d5cf9765d8.JPG)

This new table would have requested data. Is this approach acceptable?

**Comment by damithc** [comment]
`Responses Received` column can be split like this:

...| Disagree (Weight: -1) | Agree (weight: 1) | ...
---|---|---|---
...| 2 | 4 | ...

Not sure if it complicates things too much. What do you think?

**Comment by VamsiSangam** [comment]
> Not sure if it complicates things too much. What do you think?

I felt it was doable sir, so it doesn't complicate things IMO. I wrote enough code to get the features running. Here are the screenshots -

- Downloaded CSV

![1](https://user-images.githubusercontent.com/11662001/27833597-2bf46ec2-60f1-11e7-8746-0c1170261e90.JPG)

- Instructor results page

![2](https://user-images.githubusercontent.com/11662001/27833612-37c57fd4-60f1-11e7-93df-172aff50a382.JPG)

- Instructor results page - rubric question without weights (just to show that it is unaffected)

![3](https://user-images.githubusercontent.com/11662001/27833643-4e02a15a-60f1-11e7-8a33-ec06cedc0912.JPG)

Is this UI acceptable to you sir?

**Comment by damithc** [comment]
Looks good @vamshi-s Good work so far 👍 
This will make rubric questions a lot more useful to instructors.

**Comment by VamsiSangam** [comment]
Ok sir, will proceed with the PR.

BTW sir, you tagged someone else :stuck_out_tongue_closed_eyes:

**Comment by damithc** [comment]
> BTW sir, you tagged someone else 😝

corrected. :-p
