### ISSUE TITLE
Reduce number of profile pic requests

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7216]
v5.102

![image](https://cloud.githubusercontent.com/assets/1673303/25625169/654f725a-2f8e-11e7-807c-dbaedbdca651.png)

It appears there is a high number of `page/ProfilePic` requests, which outnumber all other type of requests. This is unexpected because more students don't even have profile pics. Any request to load a pic should be initiated by the user clicking on a 'show picture' link manually. We need to find the origin of these requests and rewrite the code to minimize unnecessary requests.

**Comment by whipermr5** [comment]
The request `referer` header contains the URL of the requesting page. Are the headers captured in the logs?

**Comment by damithc** [comment]
No it is not captured by logs. hard to see a pattern in the logs.

![image](https://cloud.githubusercontent.com/assets/1673303/26537218/0398de42-4470-11e7-83bb-8311e3d1f20b.png)

**Comment by whipermr5** [comment]
Maybe can try filtering by IP and user agent to narrow the logs down to a single user session? Expand `protoPayload`, click on `ip` and select `Show matching entries`; do the same for `userAgent`:
![screen shot 2017-05-29 at 5 29 09 pm](https://cloud.githubusercontent.com/assets/6811428/26544560/d1894868-4494-11e7-8fbe-dd3b3ad64fb4.png)

**Comment by damithc** [comment]
I checked 3 cases. All seem to result from `studentCourseDetails` page (i.e. student viewing team details). However, I'm not sure if the number of requests is correct. For example, this guys has only 5 members in his team but there are about 50 profile pic requests from one page request to view team.
![image](https://cloud.githubusercontent.com/assets/1673303/26546213/70e61ee4-449b-11e7-9bed-ba367807f079.png)

**Comment by whipermr5** [comment]
Only a few of the URLs are unique. I believe the culprit here is the browser's mechanism for quicker loading of page elements - when it doesn't receive a response within a certain amount of time, it opens another (or several other) connection(s) in parallel to request the same URL, then uses whichever response is fastest. It might have been caused by (i) our profile picture action responding slower than before, and/or (ii) a recent browser update decreasing the threshold value before parallel requests are fired off.

**Comment by damithc** [comment]
I see. Perhaps we can modify the page to show 'show picture' link instead? The picture can be loaded only if the link is clicked. A better approach is to not show the picture (or the link) if the student has no profile picture but not sure how much work that takes.

**Comment by whipermr5** [comment]
Are there still a lot of profile pic requests? Wondering if #7477 affects this in any way.

**Comment by damithc** [comment]
Seems to be fixed now. No high number of profile pic requests in the last 24 hours.

**Comment by whipermr5** [comment]
Should this be closed, then?
