### ISSUE TITLE
New contributor self intro Kathy Guo

### ISSUE THREAD

**Issue by kguo901** [TEAMMATES/teammates#7217]
a) Link to app: [http://teammates-kathy.appspot.com/](http://teammates-kathy.appspot.com/)
b) Link to fork: [https://github.com/kguo901/teammates](https://github.com/kguo901/teammates)
c) I titled the bottom section of the home page "Why choose TEAMMATES?" and reorganized the product highlights.
![teammates ui](https://cloud.githubusercontent.com/assets/15681154/25640914/8e50552c-2f5f-11e7-8e2f-dd75727d2169.png)
d) My name is Kathy Guo. I am a second-year student studying Computer Science and Engineering at the Ohio State University. Although I have done personal projects in the past, this is my first time contributing to open source. I have experience working with Java, HTML, CSS, and basic JavaScript, and I look forward to participating in this project!

**Comment by Yogitha6** [comment]
Hi @kguo901 , welcome to TEAMMATES!

Good work 👍! Looks like you finished the orientation successfully. 

One suggestion:
You were supposed to make visible changes to the UI in the tinker branch of your fork. I see that you made changes to your master branch. Your master branch should always be in sync with the teammates master branch. Please revert the change in your master branch.

You can start by fixing any d.FirstTimers issue (like #7215 - which you requested) to become familiar with the workflow, and then move on to d.Contributors issues. Please refer to the [process document](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md) to understand the workflow.

**Comment by kguo901** [comment]
@Yogitha6  Thank you for letting me know! I will revert the changes in my master branch.

**Comment by damithc** [comment]
Welcome to TEAMMATES @kguo901 :-)
