### ISSUE TITLE
Update entry count in home page

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7222]
Update this number to reflect 6.5 million as at May 4th 2017

![image](https://cloud.githubusercontent.com/assets/1673303/25701053/2bac1a6a-30fd-11e7-9200-08f4b1bd7b75.png)

**Comment by harispan** [comment]
hello, i would like to work on this issue, where are these feedback entries located ? are they a static number or a dynamic one? Thanks

**Comment by damithc** [comment]
> i would like to work on this issue, where are these feedback entries located ? are they a static number or a dynamic one?

@harispan good questions. We prefer if you can find the answers yourself 😛

**Comment by damithc** [comment]
@harispan 
BTW, new contributors are recommended to read our 'Contributor Orientation Guide' (link given in our [project home page](/teammates/teammates))

**Comment by shubham49** [comment]
If anyone is not working on this issue, may I do this?

**Comment by VamsiSangam** [comment]
Hi @harispan ! Are you working on this issue currently??
