### ISSUE TITLE
Email sent to instructors at session closing: Add a preamble 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7226]
Current:
TEAMMATES sends students an email notification at the point when a session is closed.
A copy of that email is sent to the instructors as well.

Suggestion:
Add a preamble to the email copy sent to the instructor. e.g.
```
The email below has been sent to students of course: CS2103-Jan2017.

=== Email message as seen by the students ===
{content of the email}
```
Justification:
It makes it clear that the email content (written to address students) is just a copy. Otherwise the instructor might be confused by the instructions given in the email.

**Comment by nikiforosbotis** [comment]
@damithc I would like to work on this.
