### ISSUE TITLE
Message: Requesting GSoC students and mentors to join Gitter

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7230]
There's a [Gitter chat room](https://gitter.im/TEAMMATES/GSoC2017) already created by @damithc sir for GSoC 2017. But I guess nobody is aware of it yet. It would be really cool if all the GSoC students and mentors join Gitter. I don't know if TEAMMATES generally uses Gitter, but it is a great place to talk about tech, non-tech stuff and also to get to know each other. Gitter also has a mobile app, so it makes conversations very easy. Looking forward :smile:

**Comment by damithc** [comment]
We are using slack at the moment. Haven't decided to switch to Gitter as of yet. I created the chat room for testing only. Will let you know early next week whether we switch to Gitter or stay with slack. In the latter case, we'll be inviting you to slack.

**Comment by VamsiSangam** [comment]
Ok sir, then keeping this issue open might lead everyone to the wrong destination. Closing issue now.
