### ISSUE TITLE
Pull Request Template: Fix typo 'abovementioned'

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7234]
A minor typo in [PULL_REQUEST_TEMPLATE.md](https://github.com/TEAMMATES/teammates/blob/master/.github/PULL_REQUEST_TEMPLATE.md). Change -

> Titled the PR as specified in the abovementioned document

to 

> Titled the PR as specified in the above-mentioned document

**Comment by whipermr5** [comment]
Even though it is not commonly used nowadays, `abovementioned` is an acceptable word:
https://www.merriam-webster.com/dictionary/abovementioned
http://www.dictionary.com/browse/abovementioned
