### ISSUE TITLE
instructorHomePage: Add spacing to send notification button

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7235]
In `instructorHomePage`, the course panel's button which sends a reminder to recipients of pending comments is a little too clumsy -

![1](https://cloud.githubusercontent.com/assets/11662001/25769686/c0a517f2-323d-11e7-81ed-1c81431d24eb.JPG)

We can add a little space, as such -

![2](https://cloud.githubusercontent.com/assets/11662001/25769670/9da03336-323d-11e7-971e-99fed08e8495.JPG)

to make it more readable.

**Comment by kguo901** [comment]
I will work on this.
