### ISSUE TITLE
Student: submit responses: contribution question: Give more info on 'Equal share' scale

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7236]
Suggestion:
In the submission form, we can have more info on the scale used

![image](https://cloud.githubusercontent.com/assets/1673303/25769746/656ea882-3254-11e7-8bf1-a9da4ef93066.png)

Add a `More info about the 'Equal share' scale` link that opens a modal window?

Justification:
Some students don't understand the meaning of `Equal share`

**Comment by HirdayGupta** [comment]
Working on this.

**Comment by HirdayGupta** [comment]
@damithc should this link be adjacent to each option? (refer screenshot below) or just the first option?

<img width="1180" alt="screen shot 2017-05-08 at 10 38 29 am" src="https://cloud.githubusercontent.com/assets/18088721/25790943/855d11ce-33da-11e7-977b-4797618e374e.png">

**Comment by damithc** [comment]
Once is enough. May be we can name it `More info about the 'Equal share' scale`?
