### ISSUE TITLE
Student: submit responses: allow student to add a comment for each response

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7239]
When students submit responses, it is useful if the system allows student to add an explanatory comment. It also avoid the need to add questions such as 'explain your response to the previous question' to collect justifications.

This might have to be done as multiple PRs, one per question type. We can start with MCQ questions.

**Comment by Mynk96** [comment]
Just a doubt, should I create a new entity for example FeedbackResponseExplanation got each explanation from students or just add a new responseExplanation attribute for each of their responses?

**Comment by Mynk96** [comment]
@damithc  your input?

**Comment by damithc** [comment]
@Mynk96 my initial impression is that we should reuse FeedbackResponseComment for this. i.e. just like instructors can add comments to responses, we should allow students to add comments to responses too.

**Comment by Mynk96** [comment]
@damithc Yes, We can also do it that way.
