### ISSUE TITLE
Instructor: FeedbackEditPage: fix update message

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#7252]
On instructorFeedbackEditPage, after editing a feedback question, the following message is shown to the user:

The changes to the question has been updated.

This should be changed to "The changes to the question have been updated.". Alternatively, it might be possible to rephrase this message to be clearer instead.

**Comment by narendravardi** [comment]
Hi @chowyb,

I am new and want to contribute. Can I work on this?

**Comment by chowyb** [comment]
Hi @narendravardi,

Sure, feel free to work on this issue. You may wish to have a look at our [contributor orientation guide](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md) before proceeding.

**Comment by adityavhegde** [comment]
Hi,

Has anyone already taken/resolved this issue ? I am a new contributor (completed the UI change task). 
If not, I'd like to take this up.

**Comment by chowyb** [comment]
Hi @adityavhegde,

Sorry for missing this! No one has resolved this issue yet, so you may feel free to try it out. 👍

**Comment by adityavhegde** [comment]
Hi @chowyb ,

As analysed and tested, I was able to modify the FEEDBACK_QUESTION_EDITED field in Const.java and the text seems to be updating.  As suggested by you, above, the new text is "The changes to the question have been updated."

Do you recommend, going with this change, or we should change the text to something else.

**Comment by chowyb** [comment]
Hi @adityavhegde,

Yes, that should be fine. Please feel free to open a PR with your change 👍 any further changes (if needed) can be discussed there.

**Comment by adityavhegde** [comment]
Hi @chowyb ,

My master was a few commits behind Teammates, so I synced my master with Teammates. Now when I re-launch the application, the edit button is not working (running on the dev server)

**Comment by VamsiSangam** [comment]
Hi @adityavhegde ! The edit button has 2 parts right, I mean the pencil icon and the "edit" text. Click exactly on the pencil icon, 

![1](https://user-images.githubusercontent.com/11662001/27005114-4a08878c-4e35-11e7-9887-090a7af42d83.JPG)

if that doesn't work click exactly on the "Edit" text,

![2](https://user-images.githubusercontent.com/11662001/27005119-58c8a20c-4e35-11e7-9f03-f055ad841937.JPG)

If only one of them works let me know which one worked. If both don't then do mention that here too. I am facing something similar to this, so that's why I'm asking :sweat_smile:

**Comment by adityavhegde** [comment]
Hi @VamsiSangam , 

I did try it. It was working fine before I synced my repo.

**Comment by VamsiSangam** [comment]
So currently no matter where you click on "Edit" button, the question isn't going to edit mode?

**Comment by adityavhegde** [comment]
That is correct. Possibly something wrong, going on my end?

**Comment by VamsiSangam** [comment]
Well, submit a PR with the changes made so far. Then we can have clear look if anything is wrong. :smile:

**Comment by adityavhegde** [comment]
Alright. I'll create the PR. Thanks.

**Comment by damithc** [comment]
@chowyb @VamsiSangam Can this be a case of failing to run `npm run build` too?

**Comment by VamsiSangam** [comment]
Yes sir @adityavhegde just needed to run `npm run build`. Once he ran it everything was fine (I confirmed with him). Recently the inline JS was shifted to .es6 files, so the inline JS of the edit button's `onclick` is now in the .es6 files. Once the command is run, everything will work as expected.
