### ISSUE TITLE
Adding new Pages

### ISSUE THREAD

**Issue by angelosdmg** [TEAMMATES/teammates#7254]
Hello everyone,
I have some questions regarding new pages and what steps one should follow in order to create one. 
Which are the files that should be changed and what should I add? 
Is it the same process for servlets?

Thank you in advance

**Comment by wkurniawan07** [comment]
Hi @angelosdmg, what were you trying to achieve? The answer to your question would depend on that.

**Comment by angelosdmg** [comment]
Hello @wkurniawan07 . I'm trying to understand the project in depth because I'm interested. 
Let's say that I want to add a new page where the admin is being shown just a html page.

**Comment by wkurniawan07** [comment]
> add a new page where the admin is being shown just a html page.

To clarify: are you trying to add an HTML page (static) that can only be accessed by admins?

**Comment by angelosdmg** [comment]
@wkurniawan07 yes
(but my general goal is to understand how the application works (adding static pages at first, servlets etc)

**Comment by wkurniawan07** [comment]
I assume this is resolved in #7410.
