### ISSUE TITLE
Admin: home page: fix typo

### ISSUE THREAD

**Issue by malayaleecoder** [TEAMMATES/teammates#7257]
Change from `Add Instructor` to `Add Instructors` is required as the details are expected from multiple Instructors.
<img width="1067" alt="screen shot 2017-05-09 at 11 43 15 am" src="https://cloud.githubusercontent.com/assets/16613630/25834917/a705e606-34ad-11e7-84fd-55b50296427c.png">

**Comment by angelosdmg** [comment]
Hello, I'd like to fix this issue

**Comment by malayaleecoder** [comment]
@angelosdmg Sure, go ahead. Feel free to comment here in case of queries

**Comment by DorianDevelops** [comment]
Has this issue been fixed? If not may help?

**Comment by angelosdmg** [comment]
@DorianDevelops I'm working on it

**Comment by whipermr5** [comment]
@DorianDevelops As [updated](https://github.com/TEAMMATES/teammates/pull/7302#issuecomment-308581969) by @angelosdmg, you may take the issue now if you're still interested to work on it.

**Comment by stanislous** [comment]
@whipermr5 fixed this issue. But All checks have failed. Can you explain me why?

**Comment by whipermr5** [comment]
@stanislous I've replied you in https://github.com/TEAMMATES/teammates/pull/7624#pullrequestreview-46732038. You can comment directly on your PR :)
