### ISSUE TITLE
Add a GodMode section to the Troubleshooting docs

### ISSUE THREAD

**Issue by thenaesh** [TEAMMATES/teammates#7259]
Alternatively, this could be added directly to the GodMode docs.

Document some things to watch out for and some common errors and their workarounds. 
Known issues as of now:

- [ ] Stuff to change in build.properties, requirement to _clean_ project after that
- [ ] ...

**Comment by thenaesh** [comment]
Anyone else with issues with GodMode, just add them here.

**Comment by wkurniawan07** [comment]
I don't think there's any more work to be done here, now that things have been simplified by a lot.
