### ISSUE TITLE
instructorHelp: Update UI based examples

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7264]
The UI based examples are outdated. Update them according to the latest UI. Eg. this is the example given in `instructorHelp.jsp`, for `Sessions -> Setting up questions`.

![1](https://cloud.githubusercontent.com/assets/11662001/25847750/02ef19a2-34d5-11e7-9cad-3cfd7f5dbf80.JPG)

This is the actual UI the instructor sees when creating a new essay question -

![2](https://cloud.githubusercontent.com/assets/11662001/25847784/327b31c4-34d5-11e7-8eda-951c52b6d36e.JPG)

Make such updates wherever necessary.

**Comment by kguo901** [comment]
I can work on this.

**Comment by damithc** [comment]
@VamsiSangam are you going to work on this?

**Comment by VamsiSangam** [comment]
No sir I am not. @kguo901 feel free to take up this issue 👍

**Comment by damithc** [comment]
@kguo901 I suggest you do just one example and get it reviewed first.

**Comment by kguo901** [comment]
@damith Sounds good, sir.
