### ISSUE TITLE
Minor typo in the comments at InstructorDB.java file

### ISSUE THREAD

**Issue by nikiforosbotis** [TEAMMATES/teammates#7265]
A minor typo exists in the InstructorDB.java, line 91 in the comments:

`* visibility according to the logged-in user's google ID. This is used by amdin to`

As you can see, the used word is "amdin" instead of "admin".

I do consider it as a proper issue for FirstTimers and this is why I openned it.

**Comment by chowyb** [comment]
@nikiforosbotis thanks for the report 👍
