### ISSUE TITLE
Assistance on phase C of the orientation task list please

### ISSUE THREAD

**Issue by cmorris2** [TEAMMATES/teammates#7267]
Hi, I am new to the project and I would like to become a contributor so I am trying to finish the orientation task list. I have gotten to phase C #2, but I'm stuck and would like assistance on making a change to the UI. My main issue is just locating the appropriate files to make the changes to the UI. I apologize if this is already posted somewhere. Thank you for your time.

**Comment by VamsiSangam** [comment]
Hi @cmorris2 ! Thanks for your interest in TEAMMATES! 😄 

As you are a first time contributor, you should try modifying the UI of the straight forward pages, such as

- [Home page](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/index.jsp)
- [Features page](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/features.jsp)
- [About Us page](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/about.jsp)
- [Contact page](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/contact.jsp)
- [Terms of use page](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/terms.jsp)

or at-least this is the list of popular pages the first timers usually try to modify. You can modify the other pages as well, you will find the UI part of the application in `/src/main/webapp/`. And obviously we don't expect any fancy UI changes from you just yet. Any small change will do. You can comment here if you need help with anything. 😄
