### ISSUE TITLE
New contributor self intro Daimen

### ISSUE THREAD

**Issue by DaemonWill** [TEAMMATES/teammates#7269]
a)     https://teammates-daimen.appspot.com/
b)     https://github.com/DaemonWill/teammates
c)     When creating a new instructor from adminHome page, table content spills over large screens, did 
        a quick fix
 
        before: 
![image](https://cloud.githubusercontent.com/assets/28215667/25887556/9e64cea8-3530-11e7-8161-7f919735afbb.png)
          
        after: 
![image](https://cloud.githubusercontent.com/assets/28215667/25887599/c30939ce-3530-11e7-8978-18a99521b68e.png)

d)    Hey there! My name is Daimen Williams, I graduated undergrad in 2016 with a degree in physics and since then  I've been working as a Full-Stack JEE Contractor; although I'm probably much stronger working with the Frontend haha. This is also my first open-source project, really wanted to get my feet wet with this first before diving into any other projects XD . Also I just made this profile! I never really bothered with github before and used to use gitLab for my personal repos. 

( ^_^)／

**Comment by leeyimin** [comment]
Hi @DaemonWill, welcome to TEAMMATES! 😄 Great job on completing the orientation tasks! You may want to submit what you have done on your tinker for #6900 or proceed to work on a firstTimers issue.

**Comment by DaemonWill** [comment]
Thanks for including the link to the issue. I saw that for #4112 they tried to include a link instead (which seems like a better option) so I included that as well and made a pull request.
