### ISSUE TITLE
Remove support for commenting on students/courses/teams

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7271]
Currently we support commenting on feedback responses as well as students/teams/courses. 

As our user base and code base grows, we need to get rid of features that are not within our main focus. This particular feature is not within our main focus and based on usage data, rarely used. I proposed to get remove support for comments on students/courses/teams (but we continue to support and strengthen support for comments on feedback responses). In the rare case a user wants to comment on students, he can do so by creating a session for it.

This means there is no need to keep two types of entities Comment and FeedbackResponseComment and we can also remove the 'Comments' tab entirely from the UI.

**Comment by wkurniawan07** [comment]
+1 this, for the reason that this feature is not very well-engineered (especially the front-end part) to begin with.

**Comment by wkurniawan07** [comment]
Question: can the "clear pending comments" feature be removed as well?
(to be frank: is it even used?)

**Comment by damithc** [comment]
> Question: can the "clear pending comments" feature be removed as well?
> (to be frank: is it even used?)

Yes, it can be removed. The only downside is if a comment was added after a session is published, the instructor has no direct way to inform the recipients about the new comment.
