### ISSUE TITLE
Instructor: download results: include feedback response comments

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7272]
The csv file can include feedback response comments too. However, we should take care not to degrade the performance too much.

**Comment by Mynk96** [comment]
working on it!

**Comment by Mynk96** [comment]
Suppose instructor adds two comments for a particular response, so we will show two comments on two different cell or in a single cell separated with something, for example 'comma'. ?

**Comment by damithc** [comment]
Good question. Note that the different comments can be from different instructors. Perhaps we can do something like this?
`instructor 1 | comment from instructor 1 | instructor 2 | comment from instructor 2`
i.e. number of columns depends on the number of comments.

**Comment by Mynk96** [comment]
@xpdavid Do we have any method to just extract values from html tags?

![capture](https://cloud.githubusercontent.com/assets/17481466/26522399/65cfb062-431d-11e7-875c-f8b70127cd16.PNG)

**Comment by Mynk96** [comment]
@damithc what if the same instructor gives more than one comments, then should we show all his/her comments in a single cell?

**Comment by damithc** [comment]
I think it is better to show each comment in a separate cell. i.e. show them in the other order they were given and ignore the fact that it is from the same instructor.

**Comment by Mynk96** [comment]
@damithc got it🙂

**Comment by Mynk96** [comment]
@damithc Here is the sample `CSV` [file](https://drive.google.com/file/d/0B4LHGBsmr3q0YmdNY1EzVjJhUzA/view?usp=sharing) after including Instructor `comments`. Need your input for the same.

**Comment by damithc** [comment]
What I had in mind initially was something like this:
![image](https://user-images.githubusercontent.com/1673303/27160780-3c4aabee-51a9-11e7-97d0-5bf9d7d71209.png)
What do you think?

**Comment by Mynk96** [comment]
@damithc Yes, the above layout will be much easier for the instructor to interpret instead of scrolling sideways to see the comment and the scrolling back to see the response. Considering the above inputs, I have made [changes.](https://drive.google.com/file/d/0B4LHGBsmr3q0YmdNY1EzVjJhUzA/view?usp=sharing)
Also, I have kept the headers only vertically as I think that will make content more readable (even when the comments are very long). 
![excel](https://user-images.githubusercontent.com/17481466/27169798-ef814baa-519a-11e7-9dbe-ba810cfc3892.PNG)

**Comment by damithc** [comment]
Sorry I did not explain clearly. Your previous location is correct (it should be in the same row as the response -- to preserve sortability). My suggestion was only about what to put in what cell.

![image](https://user-images.githubusercontent.com/1673303/27172144-beeab714-51e6-11e7-94f2-4fd7fa375d0d.png)
