### ISSUE TITLE
Troubleshooting guide: Add help link to change encoding scheme

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7274]
Quite a few people have been facing issues trying to get the encoding scheme right, despite having all the project specific properties as per our `ide-usage.md`. 

[This link](https://z0ltan.wordpress.com/2011/12/25/changing-the-encoding-in-eclipse-to-utf-8-howto/) seems to have solved their issues successfully. Add this to the `troubleshooting-guide.md` under `Common setup errors and solutions`

**Comment by RaghavBatra** [comment]
I forked the repository and made the changes! How do I sync the fork back with the main branch?

**Comment by RaghavBatra** [comment]
Oops I think they appeared on their own!

Also, sorry for 2 commits: the second is there to align my messages with those of the group!

**Comment by whipermr5** [comment]
@RaghavBatra You need to submit a PR.

**Comment by RaghavBatra** [comment]
@whipermr5 sorry since I am new to this, but how would I submit a PR?

**Comment by VamsiSangam** [comment]
Follow these steps -

- Fork [teammates](https://github.com/TEAMMATES/teammates) repo.
- Create a new branch named `7274-add-help-link-in-docs`. Why is the name `7274-add-help-link-in-docs`? We have some conventions, [you can read them here](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-2-start-clean-from-a-new-branch).
- Checkout to this branch using `git checkout 7274-add-help-link-in-docs`. Now you are in your new branch.
- Make changes in this branch.
- Then execute these commands to save and push your local changes to github -
```
git add .
git commit -m "Added help link to docs"
git push
```
- Now head to your fork in github and navigate to your new branch `7274-add-help-link-in-docs`.
- Click `New pull request` button.
- Then fill the PR title and description according to our conventions mentioned in the same link I mentioned above.
- Then click `Create pull request` button.

Some resources to help you out. [Pull request](https://help.github.com/articles/about-pull-requests/), [Tutorials](https://www.atlassian.com/git/tutorials).

You can comment here if you have any difficulty :smile:

**Comment by RaghavBatra** [comment]
Done! Thanks! Can you review the changes now?
