### ISSUE TITLE
Question type - rank: results: show 'average excluding self rating'

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7277]
Current:
![image](https://cloud.githubusercontent.com/assets/1673303/25942025/1e394440-366e-11e7-9237-9ecfd7a058dd.png)

The average shown includes self rating. 

Suggestion:
Add a column showing 'Average excluding self rating'.
Should be added to the downloaded results too.

**Comment by shubham49** [comment]
Working on it.
