### ISSUE TITLE
Instructor: view results: 'rank' questions: indicate self rating

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7278]
Current:
![image](https://cloud.githubusercontent.com/assets/1673303/25942352/34f6ae2e-366f-11e7-9372-ace56d9b3ba4.png)

Suggested:
We can indicate the self rating e.g. `1, 2, [3], 3`
Alternatively, we can give the self rank as a separate column

**Comment by VamsiSangam** [comment]
Working on this.
