### ISSUE TITLE
FeedbackQuestionsLogic: remove unused method isQuestionFullyAnsweredByTeam

### ISSUE THREAD

**Issue by JosephineKwa** [TEAMMATES/teammates#7279]

**Comment by MentalMittal** [comment]
Hey, this is my first time contributing. How can I contribute?

**Comment by JosephineKwa** [comment]
Hey there, welcome to TEAMMATES @MentalMittal! To start contributing, do follow the orientation task list in our [contributor orientation guide](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md). I look forward to your contributions!

**Comment by MentalMittal** [comment]
Thank you @JosephineKwa Will try my best to contribute.

**Comment by AbhayGoyal** [comment]
I guess the issue if fixed right?

**Comment by whipermr5** [comment]
@AbhayGoyal The issue is still open.

**Comment by desponda** [comment]
Will try to pick up this one as a first timer
