### ISSUE TITLE
Multiple-choice (multiple answers) questions: support weights for options

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7281]
Suggestion:
For 'Multiple-choice (multiple answers)' type questions, we can support allocating weights for each option. 

Justification:
These weights can be used to calculate a score.

**Comment by VamsiSangam** [comment]
Sir, isn't this issue same as #2776 ? If not how is this different?

**Comment by damithc** [comment]
> Sir, isn't this issue same as #2776 ? If not how is this different

@VamsiSangam Edited #2776 title to show the difference. They are similarly named, but two different types of questions.
