### ISSUE TITLE
JSON test data: use team name as giver in team responses

### ISSUE THREAD

**Issue by JosephineKwa** [TEAMMATES/teammates#7283]
For team responses, the response giver should be the team name rather than the email of the student that gave the response. E.g. `response1ForQ1S2C1` in `typicalDataBundle.json`. I've only checked `typicalDataBundle.json` but it's probably the case in other `json` files too.

**Comment by amarlearning** [comment]
working on this

**Comment by amarlearning** [comment]
Update: this might take some time :sweat_smile:

**Comment by shaharyar-shamshi** [comment]
@JosephineKwa  sir I am working on it

**Comment by xpdavid** [comment]
Need to be done as the last step of #4584
