### ISSUE TITLE
FeedbackSessionsLogic: stop updateRespondentsForSession from adding team names to responding student list

### ISSUE THREAD

**Issue by JosephineKwa** [TEAMMATES/teammates#7284]
The responding student list is generated by iterating through all the responses of the session and adding the response giver. As response givers can be team names, this would result in the responding student list containing team names. This arose after the team response giver was changed from student email to team name to fix #4576.

Only student emails should be added to the list. However members of a team giver are not included in the responding student list. We need to determine how to take into consideration responses submitted by a single student on behalf of a team (related to issue #7285).

This method is currently only being used when restoring a data bundle to the datastore, so it's not that big of a problem.

**Comment by wkurniawan07** [comment]
Closed after #10678
