### ISSUE TITLE
Form not avilable to create a course

### ISSUE THREAD

**Issue by amarlearning** [TEAMMATES/teammates#7286]
Trying to create a new course, but there is no form available to do so.
[screenshot]
***
![screenshot from 2017-05-11 19-11-40](https://cloud.githubusercontent.com/assets/9383897/25952341/108b4c70-367e-11e7-934f-e726d551b79f.png)
***
And no sample courses are there on my Instructor account
[screenshot]
***
![screenshot from 2017-05-11 20-13-35](https://cloud.githubusercontent.com/assets/9383897/25955292/7523fe68-3686-11e7-93b2-416f318e07d1.png)
***

**Comment by damithc** [comment]
I remember someone else reported an issue like this. Was it @AnaghHegde ?
Usually, there is no `isUsingAjax=on` at the end of the URL but in your case you seem to have that extra bit at the end of the URL. 
![image](https://cloud.githubusercontent.com/assets/1673303/25956174/9460ad00-369d-11e7-87bc-c3ec5ef0794f.png)

**Comment by amarlearning** [comment]
@damithc Do you have any idea of why is this happening or how to resolve this?

**Comment by AnaghHegde** [comment]
@damithc Yes. It was me. @amarlearning Try running `npm install` and then `npm run build`. Beccause in my case it was due to problem with transpilation of `es6` to `js` files. So try running these two commands.
`

**Comment by amarlearning** [comment]
@AnaghHegde Thanks that worked for me as well, I got my form.
@damithc But still no sample courses are there on my Instructor account, is there any way to get them back or I have to create some courses manually?

**Comment by damithc** [comment]
> But still no sample courses are there on my Instructor account, is there any way to get them back or I have to create some courses manually?

Try creating another instructor account and see if a sample course is created for it.

**Comment by AnaghHegde** [comment]
@damithc i think we can add this error to trouble shooting guide may be. As there are good chances that people might get this error.

**Comment by damithc** [comment]
> i think we can add this error to trouble shooting guide may be. As there are good chances that people might get this error.

Good suggestion @AnaghHegde Feel free to create an issue for it.

**Comment by amarlearning** [comment]
> Try creating another instructor account and see if a sample course is created for it.

@damithc Thanks, that worked.
