### ISSUE TITLE
Change teammates-eslint.yml and teammates-eslint-es6.yml

### ISSUE THREAD

**Issue by LiHaoTan** [TEAMMATES/teammates#7287]
There are no longer anymore ES5 Javascript files.

~~Can the es6 rules be migrated from `teammates-eslint-es6.yml` to `teammates-eslint.yml` or will it cause conflicts with the `json` plugin? (I took a look at how the plugin works and it should not cause any conflicts)~~

~~If the rules cannot be migrated over, can the rules from `teammates-eslint.yml` be removed and then renamed to `teammates-eslint-json.yml` so it better represents its new purpose. Likewise, can `teammates-eslint-es6.yml` be renamed to `teammates-eslint.yml` to make it more concise?~~

See https://github.com/TEAMMATES/teammates/issues/7287#issuecomment-301062674

**Additional Dependencies**
The documentation for setting up the ESlint plugin for IntelliJ is inaccurate as it uses the old ES5 rules.

**Comment by LiHaoTan** [comment]
I think the following should be done instead.

1. Rename `teammates-eslint.yml` to `teammates-eslint-json.yml`.
2. Rename `teammates-eslint-es6.yml` to teammates-eslint.yml`.

If possible, can we use [JSONLint](https://github.com/zaach/jsonlint) instead? It provides more comprehensive messages and is more suited for JSON linting. whipermr5 did not want to introduce additional dependencies but I think this is better than using the ESLint JSON plugin.

@wkurniawan07 can we do this?

**Comment by wkurniawan07** [comment]
@LiHaoTan shouldn't be a problem. The existence of the two different configs are due to the migration done some time back, but this part is not yet cleaned up. For (1), why not just do (2) and add the JSON plugin in it?

As for JSONLint, I'm not against adding any new linter, but is it considerably better than ESLint JSON plugin (i.e. does it justify its inclusion)? Also, does it support failing the build and printing the error message to the console when encountering violations? You'd notice that all the linters we use support those two features.

**Comment by LiHaoTan** [comment]
I was thinking that JSON linting and Javascript linting should be kept separate since they are not the same and are commonly separated in many places. For example in IntelliJ only javascript linting is required. Not sure if there is a plugin for ESLint in Eclipse but if it exists it is similar.

For JSONLint I think maybe that should be pushed back to the future as a separate issue to evaluate because neither the ESLint JSON plugin and JSONLint are ideal. 

[Example issue with ESLint JSON Plugin](https://github.com/azeemba/eslint-plugin-json/issues/7)
[Example issue with JSONLint](https://github.com/zaach/jsonlint/issues/85)

The ironic thing about the ESLint JSON Plugin is that uses another linter (JSHint) to validate JSON files and the version of JSHint used by the plugin had some issues, not sure if JSHint actually resolved them though.

JSONLint is also not very ideal, the different wrappers around it doesn't solve all the problems.

**Comment by wkurniawan07** [comment]
@LiHaoTan where would you draw the line of "ideal" here? The current JSON linting provided by ESLint can catch syntax errors, and since JSON is a data notation rather than programming language, it should be sufficient. Better linters are always welcome, but don't let it steal your attention from more important items to be worked on.

**Comment by LiHaoTan** [comment]
@wkurniawan07 I agree that the issue about the plugin not being so ideal is not so important, which is why I think it should be addressed as a  separate issue or not at all, sorry for not being clear.

So the issue here is more of the redundant rules.

In any case, if I look at the surface `JSONLint` seems to be worse off since it can't catch duplicate keys. And while `eslint-plugin-json` catches them, the errors shown might not reflect the right errors.

Perhaps for JSON some less important issues not addressed would also be trailing whitespaces and no `newline` at end of file. I'm guessing there might be better linters around or maybe we can just use [git to check](https://coderwall.com/p/h988xa/cause-travis-to-fail-on-trailing-whitespace).

**Comment by wkurniawan07** [comment]
@LiHaoTan if what you want is trailing whitespaces, no EOL at the end of file, and perhaps presence of tab characters, [this](https://github.com/evanshortiss/lintspaces-cli) is your friend.

**Comment by LiHaoTan** [comment]
@wkurniawan07 thanks that look interesting though I think ESLint already offer those options. For non `.js` files I was thinking that maybe a git pre-commit hook check for all files would be better as it is more agnostic and doesn't introduce any additional dependencies. Maybe there's some better option.
