### ISSUE TITLE
Add stylelint support to IntelliJ

### ISSUE THREAD

**Issue by LiHaoTan** [TEAMMATES/teammates#7288]
Stylelint support is built into IntelliJ, instructions can be updated to show how to setup.

In addition, gradle task(s) can be created to automatically setup static analysis tools such as stylelint.

**Comment by wkurniawan07** [comment]
> gradle task(s) can be created to automatically setup static analysis tools such as stylelint.

Is this IntelliJ-specific?

**Comment by LiHaoTan** [comment]
Theoretically no but Eclipse have no stylelint plugins.

The idea is that `teammates-stylelint.yml` be copied to `.stylelintrc.yml`. By default stylelint reads from that file and the IntelliJ stylelint similarly reads from that location. If there is to be a plugin for Eclipse, it should be able to read from the default location as well.

Though this would not enable stylelint in IntelliJ so a `workspace.xml` can be generated using the gradle plugin and then the stylelint configuration can be enabled.
