### ISSUE TITLE
New contributor self intro Colby Morris

### ISSUE THREAD

**Issue by cmorris2** [TEAMMATES/teammates#7290]
a) Link to my app: https://colby-teammates.appspot.com
b) Link to my fork:  https://github.com/cmorris2/teammates/tree/tinker
c) Changed font color in UI: teammates/src/main/webapp/index.jsp  
![uichange](https://cloud.githubusercontent.com/assets/16637219/25968307/9f0ec814-3656-11e7-8406-5c5bfa23a9c3.PNG)
I am just beginning to learn HTML/CSS so it is a minor change, but nevertheless I think it looks alright. :]
d) Hey everyone!
My name is Colby Morris and I'm a Computer science student from Alabama, U.S. I wanted to get involved in open source and thought this was a great opportunity to begin contributing. 

I look forward to contributing!

**Comment by wkurniawan07** [comment]
Hi @cmorris2, welcome to TEAMMATES community!
Good job in setting up your dev environment and deploying to staging server! You can start contributing by fixing issues listed in our issue tracker, in particular those labelled `d.FirstTimers` (do just one of these) and `d.Contributors`. Looking forward to your contributions! 👍

**Comment by nijoey** [comment]
Hey Colby, Amazing work. See I am also trying to do the same thing, but I am stuck in after setting up the dev environment stage. I am able to run the website on my localhost and it run fine. 
What I am not getting is how were you able to deploy it on your staging server ? (https://colby-teammates.appspot.com) . How were you able to create it ? 

Can you please guide me on that one ?

thanks 
nijoey

**Comment by cmorris2** [comment]
Hi @nijoey ,
Did you ever figure this out? I have been busy and hadn't gotten a chance to respond.
