### ISSUE TITLE
Instructor: home page: combine 'view results' and 'publish results' buttons

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7294]
Current:
![image](https://cloud.githubusercontent.com/assets/1673303/26024006/2d2f729c-37fb-11e7-809b-aeb82e638e17.png)

Suggested:
Combine the two buttons like this (similar to the `Remind` button):
`Results`
  -`View`
  -`Publish`
Furthermore, clicking the `Results` button directly can be considered as `View Results`

Justification:
Saves space (especially because we might add more results-related buttons in future such as 'resend results link').

**Comment by amarlearning** [comment]
@damithc I would like to take this one
