### ISSUE TITLE
Instructor: view results: remove 'filter results' feature

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7295]
Current:
![image](https://cloud.githubusercontent.com/assets/1673303/26024192/79323716-37ff-11e7-8620-c4bf2092fa74.png)

Suggestion:
Remove the filter box

Justification:
It simply filters the question text, so not that useful. We can remove this superficial 'filter' feature until we have a 'filter' feature with more substance

**Comment by LimeTheCoder** [comment]
Work on it.
