### ISSUE TITLE
Instructor: view results: move 'expand ...' button outside the box

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7296]
Current:
![image](https://cloud.githubusercontent.com/assets/1673303/26024214/fb677958-37ff-11e7-8a43-93d986ffc2b4.png)

Suggestion: 
Move the button outside the box, like this:
![image](https://cloud.githubusercontent.com/assets/1673303/26024222/24c8ad44-3800-11e7-8aa1-b6edd08e6cfd.png)
While we are at it, we can rename it to `Expand all questions` etc. (i.e. insert `all`)

Justification:
The button works on panels, so it is more intuitive if it appears near the panels.

**Comment by LimeTheCoder** [comment]
Work on it.
