### ISSUE TITLE
Instructor: view results: give a 'Edit view' button

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7297]
Current:
The page is reloaded whenever a setting of the view is changed:
![image](https://cloud.githubusercontent.com/assets/1673303/26024273/e3f2a3a0-3800-11e7-906f-b09fd5376734.png)

Suggested:
Make the settings un-editable.  Provide an `Edit view` button that shows the settings in a modal window.
![image](https://cloud.githubusercontent.com/assets/1673303/26024270/cefbbad6-3800-11e7-8677-bd067a66cb08.png)

Justification:
Reloading page for each settings change is a waste of resources (and can be irritating to the user) because the user might want to change multiple settings.

**Comment by LimeTheCoder** [comment]
Work on it too.

**Comment by HirdayGupta** [comment]
@LimeTheCoder may I work on this?

**Comment by LimeTheCoder** [comment]
@HirdayGupta yes, you can take it.
