### ISSUE TITLE
Remove code related to private sessions

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7305]
Sometime back we used to have a feature called 'private sessions' (i.e. an instructor can create a session that is not visible for anyone else -- e.g. to record your own observations about students). The UI does not have this feature anymore, but there may be some code related to private sessions still in the code base. We should remove those.

**Comment by wkurniawan07** [comment]
It can still be created: a session with visible date set to "never".

**Comment by damithc** [comment]
> It can still be created: a session with visible date set to "never".

I see. I was wondering where it went :-p
