### ISSUE TITLE
sequential and parallel ui test are failing

### ISSUE THREAD

**Issue by amarlearning** [TEAMMATES/teammates#7309]
Operating System: Ubuntu 16.04
JDK Version: 1.7
Eclipse: Luna

In this [PR](https://github.com/TEAMMATES/teammates/pull/7299) of mine, I got my Travis CI build failing so as suggested by @thenaesh tried to run godmode on failing the test and still, some test is failing.

Steps that I followed to run godmode:
1. Changed `isGodModeEnabled` to `true` in `BaseUiTestCase.java`
2. then `./gradlew ciTests` in CLI

But still, sequential-ui-test and parallel-ui-test are failing.
[screenshot added]
![screenshot from 2017-05-16 17-28-44](https://cloud.githubusercontent.com/assets/9383897/26106151/a268fec0-3a62-11e7-950d-6d3592c959f5.png)

**Comment by whipermr5** [comment]
This issue has been resolved. For future reference for the benefit of those facing similar issues, @amarlearning solved it by cleaning and building the project after editing `build.properties` and `test.properties`, restarting the dev server, and re-running the tests.
