### ISSUE TITLE
test.json is causing error ?

### ISSUE THREAD

**Issue by nkshschdv** [TEAMMATES/teammates#7310]
- **Operating System: Ubuntu 16.04 x64**
- **JDK Version: 1.7**
- **Eclipse / IntelliJ Version (if applicable): Eclipse Java EE IDE for Web Developers. Neon.3 Release (4.6.3)**

**What I was trying to do / What I need help with**
So, I m getting **ONE** error in validation in teammates > node_modules > jsonfilter > test.json as shown in the screen shot below.
![testjson](https://cloud.githubusercontent.com/assets/15321028/26118744/9a08dbd0-3a88-11e7-8715-20c228d7cea1.png)

**Attempts to resolve the problem**

Well , I re-read the documents, applied the settings in project properties and Eclipse preferences again just to confirm  then restarted and cleaned the project but of no use.

**Comment by VamsiSangam** [comment]
Hi @nkshschdv ! Can you post a screenshot of the window which opens after you select `Project` > `Properties` > `Validation` > Click `...` button beside `Javascript Validation` ? And please expand that window so that all the entries are visible.

**Comment by nkshschdv** [comment]
Of course! Although, I didn't understood the meaning of "click ... " but here is the screenshot below.
![you](https://cloud.githubusercontent.com/assets/15321028/26119960/ce85bd52-3a8c-11e7-9f31-d0aad87c58d4.png)

**Comment by VamsiSangam** [comment]
Actually, by `...` I was referring to these buttons -

![capture](https://cloud.githubusercontent.com/assets/11662001/26120087/2fad1490-3a8d-11e7-87b0-058616acd405.JPG)

This is what shows up in my `Validation` window. When I click on `...` beside `Client-side Javascript`, I get something like this -

![1](https://cloud.githubusercontent.com/assets/11662001/26120122/4e1126ec-3a8d-11e7-98bc-3a5293f49f2b.JPG)

This is where we add the exclusion rule for `node_modules` folder. I don't know how things go in Ubuntu. Try clicking on `Client side JavaScript` or `JavaScript Validation` in your window, see if you can get something similar to my 2nd image.

**Comment by nkshschdv** [comment]
Here is the JavaScript Validation Settings... Entries screenshot
![Uploading javascript validation.png…]()

**Comment by nkshschdv** [comment]
Here is the JavaScript Validation Settings... Entries screenshot
![javascript validation](https://cloud.githubusercontent.com/assets/15321028/26120334/f17c87ae-3a8d-11e7-93c3-595d9cd09075.png)

**Comment by VamsiSangam** [comment]
Looks good! What about `Client side JavaScript`? Can you do similar setting changes to its options too?

**Comment by nkshschdv** [comment]
Uh! I don't know where that option exist in Eclipse IDE.

**Comment by VamsiSangam** [comment]
I meant this option -

![ce85bd52-3a8c-11e7-9f31-d0aad87c58d4](https://cloud.githubusercontent.com/assets/11662001/26120587/dab77bb8-3a8e-11e7-9ce8-6c4a8f43b108.png)

Are you able to change any settings for that option?

**Comment by nkshschdv** [comment]
Done ! I'm curious what is the difference between two?
And its build and Manual option is not checked like others. 
![client side](https://cloud.githubusercontent.com/assets/15321028/26120825/afcb4f0a-3a8f-11e7-9c9e-cc7a4040f41a.png)

**Comment by VamsiSangam** [comment]
Honestly it confuses me too. Some versions of eclipse have 2 options as such.

Now do a `Project` > `Clean`. Your errors should get resolved. 😄

**Comment by nkshschdv** [comment]
It still shows the same error. Screenshot below
![not resolved](https://cloud.githubusercontent.com/assets/15321028/26121065/a6277608-3a90-11e7-9bf8-085086f8f0e8.png)

**Comment by VamsiSangam** [comment]
In your `Problems` tab which is showing you the error, can you tell me what `Type` it is? You should see the error type if you scroll that window to the right.

![capture](https://cloud.githubusercontent.com/assets/11662001/26121426/c8d0e7ce-3a91-11e7-9318-01332e24119b.JPG)

**Comment by nkshschdv** [comment]
its JSON type and it says "unexpected character at 2:0" in test.json . Screenshot below.
![problelm type](https://cloud.githubusercontent.com/assets/15321028/26121592/6e695568-3a92-11e7-8f1e-92b61bafb526.png)

**Comment by VamsiSangam** [comment]
It is a JSON problem, which means your JavaScript validation settings are fine.

We don't validate JSON files in TEAMMATES. I noticed you have a `JSON Syntax` option in validation. Can you enable project specific settings for that and turn off the validation?

![ce85bd52-3a8c-11e7-9f31-d0aad87c58d4 1](https://cloud.githubusercontent.com/assets/11662001/26121742/e24d7a7c-3a92-11e7-8feb-bd2d657d8a51.png)

**Comment by nkshschdv** [comment]
It didn't solved the problem . However, Under Validation , I unchecked the "JSON Validator" build option and after cleaning the error is removed.I don't know , Is it done ?
![json validator build unchecked](https://cloud.githubusercontent.com/assets/15321028/26122060/d8e6a976-3a93-11e7-99b4-79ae5843d497.png)

**Comment by VamsiSangam** [comment]
Well yeah which ever way it is to disable JSON validation, I didn't know how to do it so I thought it would work.

So after unchecking `Build` for `JSON Validator` in `Validation`, did your error go away on `Clean`?

**Comment by nkshschdv** [comment]
yeah , You can see in the previous comment screenshot that Problem tab view shows zero error. But However , the error is shown if we manually go to file and open it. So, we effectively suppressed the error.

**Comment by VamsiSangam** [comment]
We needn't concern ourselves with errors from `node_modules` folder as they come from third party libraries. Which reminds me can you add an exclusion rule for JSON validation only for `node_modules` folder, instead of the whole application. The steps would be similar to that of what you followed to disable JavaScript validation for `node_modules`. 

This is important because, we have plenty of JSON files used by the application, so disabling validation only for `node_modules` is a more accurate course of action. Let me know if you are able to do this.

**Comment by nkshschdv** [comment]
Done ! Yeah! You are right! I added the Exclude Group entry as node_modules . And consequently, no error shown after clean .

**Comment by nkshschdv** [comment]
So, I think i should move to next step of Setting up local Green CI. Well, There are no instructions in the documents regarding that ?

**Comment by VamsiSangam** [comment]
Cool! I'm really sorry we don't have this in our docs. We will update our docs accordingly. 👍 

@whipermr5 I think we can add steps for excluding JSON validation to the `node_modules` folder in the docs. And interestingly my Kepler version of Eclipse doesn't even have any provision for JSON validation. So I guess this error can only pop in the recent versions.

@nkshschdv [Local CI Green](https://github.com/TEAMMATES/teammates/blob/master/docs/glossary.md) means you must execute the Travis CI tests in your Eclipse and have all of them passed (a few, < 5,  failing cases are OK). You can execute the tests by clicking on the green play button on the top right side of your IDE and then select `CI Tests`. And don't forget to start your Dev server before running the tests.

**Comment by whipermr5** [comment]
@VamsiSangam Oh yea I missed it out when reporting #7159 😅 Could you open a first timer issue for it?

**Comment by nkshschdv** [comment]
@VamsiSangam  The installation of Green-CI is very tricky and complex. I literally installed things in hurry in temptation. The official documents are not helpful for me to install the server.

**Comment by VamsiSangam** [comment]
"Installation"? Oh no :stuck_out_tongue_closed_eyes: You don't have to install any thing. `Local CI Green` is only a "term" we use, it does not refer to a library or server or anything which were supposed to download.

For running tests, start your Dev server, and then click on the button I mentioned in the above image.

[I've created a short video](https://www.youtube.com/watch?v=QbjSGDT3q1I) which demonstrates how to run tests. In the video, I stopped the tests after a short while, but you have to let it go until it is done :stuck_out_tongue_closed_eyes:
