### ISSUE TITLE
Instructor: Home page: add a chevron button to collapse a course

### ISSUE THREAD

**Issue by malayaleecoder** [TEAMMATES/teammates#7316]
Right now the behaviour is as follows,

`Before clicking the chevron down button`

<img width="1280" alt="before" src="https://cloud.githubusercontent.com/assets/16613630/26137560/8cc0c092-3af5-11e7-9273-8f3941aa94db.png">

`After clicking the chevron down button`

<img width="1276" alt="after" src="https://cloud.githubusercontent.com/assets/16613630/26137613/e3f40a18-3af5-11e7-8fbf-5cfdfcf848b2.png">

A chevron up button to roll back the list which would bring it back to the earlier state is desirable.

**Comment by shubham49** [comment]
I can work on this issue.

**Comment by shubham49** [comment]
I have one query:
If a user expanded the list then collapsed it, again expanded it. While 2nd time expansion, would there be ajax request again?

**Comment by damithc** [comment]
> If a user expanded the list then collapsed it, again expanded it. While 2nd time expansion, would there be ajax request again?

No, it should not.

**Comment by shubham49** [comment]
Thanks @damithc  
One more question, should whole row be clickable to collapse like this
![clickable_row](https://cloud.githubusercontent.com/assets/10528953/26142537/937fe5da-3afe-11e7-92e9-b50b3db72a35.gif)
or just chevron up button.

**Comment by damithc** [comment]
> One more question, should whole row be clickable to collapse like this

Yes, it's better if the whole header is clickable, similar to how we do it in other places.
