### ISSUE TITLE
Instructor: view results: update CSV file results for constant sum feedback questions

### ISSUE THREAD

**Issue by rchliu** [TEAMMATES/teammates#7321]
The CSV reports that are generated for instructors should be updated to match the changes in #7244 for const sum feedback questions. 

![result2](https://cloud.githubusercontent.com/assets/8629449/26183032/19590af6-3b4a-11e7-8257-90296b9666b4.png)

In the above image, a "total points" column should be added.

**Comment by nikiforosbotis** [comment]
I'd like to work on this
