### ISSUE TITLE
Fix sanitization of query string in SearchQuery

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#7325]
According to https://cloud.google.com/appengine/docs/standard/java/search/#Java_Special_treatment_of_string_and_date_fields, special characters such as '&', '\\'', '#' can be part of the tokens. However, they are replaced by spaces by `sanitizeForSearch`, which can result in unexpected results when searching.

For example, a student named Jean O'Kelly and searching " \\"Jean O'Kelly\\"" (with quotes) would not return the desired student due to the replacement of the apostrophe with space. While users can still find the student by search without quotes ("Jean O'Kelly"), the search is much less exact and can return other users with the name Jean or Kelly.

`sanitizeForSearch` may be unnecessary for quotes-enclosed strings in the query string as the query string which is sanitized is later processed and enclosed with "\\"" so there is (probably) no chance of code injection.

Another issue with SearchQuery is that it is unable to accurately search for fields which have been sanitized for html before saving. An instructor with name "John O'Connor" will not appear with search "\\"John O'Connor\\"" in Admin Search Page while "\\"John O 39 Connor\\"" will work. 

Before all fields of all attributes are migrated to its unsanitized form, it may be necessary to search the html sanitized and html unsanitized version of the given search string.

**Comment by damithc** [comment]
> Before all fields of all attributes are migrated to its unsanitized form, it may be necessary to search the html sanitized and html unsanitized version of the given search string.

Let's expedite the migration. Search is not a critical feature, so it can be 'slightly broken' until the migration is complete.

**Comment by leeyimin** [comment]
It seems like updating attributes of related attributes do not trigger the updates of the documents. 
Eg. Updating course name will not update all the search documents which includes its name in the searchableText
This means that the search will remain broken for currently existing documents even after migration unless all documents are updated.
