### ISSUE TITLE
ide-usage.md: add steps to disable JSON validation for node_modules folder in Eclipse

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7326]
JSON validation is present in newer versions of Eclipse which is validating JSON files in `node_modules` folder. Some files have been reported to cause errors #7310 . We must disable JSON validation for `node_modules` folder so that these errors are suppressed. 

Add steps for disabling JSON validation in `ide-usage.md`, under `Validation`.

**Comment by AmrishJhaveri** [comment]
This is completed, right?

**Comment by VamsiSangam** [comment]
Hi @AmrishJhaveri ! Apologies for the late reply. The docs only mentions how to disable JavaScript validation for `node_modules` folder, not JSON validation. Although both are very similar we still need to mention in the docs to disabled JSON validation for `node_modules` to prevent unnecessary trouble.

**Comment by dreyskiy** [comment]
I ran into this problem a few moments ago.  I can fix this and do a pull request if thats ok with you.  Its a very simple change.

**Comment by VamsiSangam** [comment]
Sure @dreyskiy ! Go ahead :smile:
