### ISSUE TITLE
Bug in Godmode that adds strange segment to HTML when run

### ISSUE THREAD

**Issue by thenaesh** [TEAMMATES/teammates#7327]
Recently, Godmode has been adding
```
  <div id="student-motd-wrapper">
    <input id="motd-url" type="hidden" value="test-student-motd.html">
    <script defer="" src="/js/studentMotd.js" type="text/javascript">
    </script>
    ${studentmotd.container}
  </div>
```
to HTML files when run.

**Comment by VamsiSangam** [comment]
Can refer to #7311 for example.

**Comment by thenaesh** [comment]
This appears to be the suspect in line 57 of `feedbackSubmissionEdit.tag`:
```
            <c:if test="${not data.headerHidden}">
                <ts:studentMessageOfTheDay />
            </c:if>
```

**Comment by VamsiSangam** [comment]
Cause of the issue - https://github.com/TEAMMATES/teammates/pull/7311#discussion_r117207467

**Comment by thenaesh** [comment]
So the issue is that the segment is actually supposed to be there, but was accidentally removed previously. So it should be added back.
