### ISSUE TITLE
Running data migration script for sanitized data in StudentProfileAttributes

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#7328]
After the release of V5.104, DataMigrationForSanitizedDataInStudentProfileAttributes script should be run to desanitize existing sanitized data in StudentProfileAttribute.

**Comment by damithc** [comment]
I've reassigned it to the subsequent milestone. That allows some time to lapse between deploying new code and migrating data, to confirm the new code is stable.

**Comment by damithc** [comment]
Done.
