### ISSUE TITLE
Respondent: edit submission: give a submit button for each question

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7341]
Current:
The respondent needs to submit the entire submission form.

Suggested:
Give a 'submit' button for each question (and a 'submit all' button at the bottom)
The button should use ajax to submit, instead of loading the entire page.

**Comment by shubham49** [comment]
Only `instructorEditStudentFeedbackPage` and `studentFeedbackSubmissionEditPage` are involved in this or any other page is also there?

**Comment by HirdayGupta** [comment]
@shubham49 I am actually working on this issue. If you could give me some time to finish up my code and PR, that would be nice. But to answer your question, in the solution that I am working on, I am only considering the two you mentioned.

**Comment by shubham49** [comment]
I didn't find any activity on this issue, that's why I commented. Well if you are working on it then you can proceed.

**Comment by HirdayGupta** [comment]
Yes, my apologies, forgot to comment. Thanks @shubham49 😃

**Comment by HirdayGupta** [comment]
> The button should use ajax to submit, instead of loading the entire page.

Would this be only for the individual submit buttons? Or also for the submit all button?

**Comment by damithc** [comment]
> Would this be only for the individual submit buttons? Or also for the submit all button?

@HirdayGupta Just the individual submit buttons. How far have you gone into implementing this? I wonder if the implementation complications and possible UI complications (from the usability POV) is worth the benefit.

**Comment by HirdayGupta** [comment]
> I wonder if the implementation complications and possible UI complications (from the usability POV) is worth the benefit.

@damithc Are you talking about the AJAX for the buttons or the entire feature itself?

**Comment by damithc** [comment]
> @damithc Are you talking about the AJAX for the buttons or the entire feature itself?

Entire feature.

**Comment by HirdayGupta** [comment]
@damithc Apologies for the delayed response. Slipped my mind. I haven't gotten too far, can stop if you feel this wouldn't add value. Would you recommend doing so?

**Comment by damithc** [comment]
> I haven't gotten too far, can stop if you feel this wouldn't add value. Would you recommend doing so?

Yes, let's put this on hold for now. I have no clear idea how the UI should be.

**Comment by damithc** [comment]
@HirdayGupta btw, if you have done any work on this, you can create a PR for it (which will be closed without merging) for future reference and for you to take GSoC credit for it.

**Comment by HirdayGupta** [comment]
@damithc Didn't write enough merge quality code to claim credit. Most of the work I had done was trial and error, trying to see how the feature would work.

**Comment by damithc** [comment]
Let's close this one. Doesn't feel like it's worth the effort.
