### ISSUE TITLE
Regarding being the new contributor

### ISSUE THREAD

**Issue by shaharyar-shamshi** [TEAMMATES/teammates#7346]
Warm greeting to all Teammates developer. 
Myself shaharyar shamshi I want to be active contributor of this organisation as I have keen interest in open source and In this project especially.
can anyone guide me how to start so that I can contribute for enhancement of this project.
I will be very thankfull to you

**Comment by chowyb** [comment]
Hi @shaharyar-shamshi, welcome to TEAMMATES! You may begin by reading up on our [Contributor Orientation Guide](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md). Looking forward to your contributions!
