### ISSUE TITLE
FieldValidator: fix error in message

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#7349]
The characters banned in `NON_HTML_FIELD_ERROR_MESSAGE` are `< > " / ' &` while backslash is allowed, so the backslash `\\` should be replaced with a double quote `\"` in the message.

**Comment by alwaysreadytolearn** [comment]
I would like to work on this issue but it seems like oabhi23 has already worked on it but didn't create any pull request. Is it fine If I take up this task, this is my first time on open source contribution and would like to take up something simple.

**Comment by damithc** [comment]
@alwaysreadytolearn you can ask in #7355 is @sneachta96 plans to continue that PR.
