### ISSUE TITLE
Instructor: comments page: properly display filtered data on ajax call

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#7351]
In instructorCommentsPage, when filtering the comments being displayed (via "Show comments from" under the "Show More Options" checkbox), if a checkbox is disabled, the associated comment can still show up when doing an ajax call (which occurs when the panel is expanded for the first time).

An example of this would be using the default course that is created when an admin adds a new instructor: using the instructor's account, uncheck "You" under "Show comments from", then expand the "Comments in session: Session with different question types" panel. A comment from the instructor will be displayed in the panel, even though the filter should prevent this comment from being seen.
![filter1](https://cloud.githubusercontent.com/assets/7546744/26299738/81d735cc-3f0e-11e7-8ebc-e16e5da782a7.png)
![filter2](https://cloud.githubusercontent.com/assets/7546744/26299867/eaa13224-3f0e-11e7-9a20-1d122ec5203e.png)

**Comment by Mynk96** [comment]
Working on it!

**Comment by wkurniawan07** [comment]
@chowyb I'm going to remove that page though... #7334

**Comment by chowyb** [comment]
@wkurniawan07 oh right, forgot about it for a moment, somehow I thought the feedback response comments would stay at least.

Putting this on hold for now then, I'll close this once that PR gets merged. @Mynk96 you might want to work on something else

**Comment by Mynk96** [comment]
@chowyb fine no problem...😄
