### ISSUE TITLE
Combining the Login buttons into a single dropdown login button

### ISSUE THREAD

**Issue by amarlearning** [TEAMMATES/teammates#7357]
I think the login buttons (Student and Instructor Login) in the index page should be combined to a single login dropdown button which has two options `Student` and `Instructor`. This will surely save space and would look good in terms of UI/UX.

![screenshot from 2017-05-23 23-40-26](https://cloud.githubusercontent.com/assets/9383897/26369170/7f020e5e-4011-11e7-85d6-8066a65cce68.png)

**Comment by leeyimin** [comment]
Wouldn't this mean additional button clicks to login?

**Comment by damithc** [comment]
Yes, it adds one more click. Given the space in the menu bar is not a big problem at the moment, let's put this in hold for now.
