### ISSUE TITLE
Instructor: StudentList: make buttons more clickable / tappable

### ISSUE THREAD

**Issue by amarlearning** [TEAMMATES/teammates#7370]
> Refer to screenshot below, if more buttons are added / even without more buttons being added and on smaller screen sizes (on screenshot 13 inches), the buttons can go to the next line and have no padding between each other -> tapping/clicking on some buttons might be harder.

Same as this issue #3324 _[screenshot]_
![screenshot from 2017-05-25 01-26-33](https://cloud.githubusercontent.com/assets/9383897/26423162/222913a6-40ea-11e7-8de7-a88bc865e99d.png)

**Comment by chowyb** [comment]
Note the "Add Comment" button will be removed soon, but this may still be an issue that requires fixing.
