### ISSUE TITLE
instructorCourseStudentDetailsEdit and rubric question: Remove spaces inside textarea

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7382]
The `instructorCourseStudentDetailsEdit` has a `textarea` tag which is used for editing general comment on the student. The input box shows leading and trailing white-spaces inside it as such -

![capture](https://cloud.githubusercontent.com/assets/11662001/26460909/daf65570-4198-11e7-94bb-8a0dbbeca453.JPG)

These spaces are not a part of the actual comment text. This is a common issue with the `textarea` tag. The false spacing occurs when `textarea` is used with a new line, as such -

``` html
<textarea>
    lorem ipsum
</textarea>
```

It is removed when `textarea` is used in a single line, as such -

``` html
<textarea>lorem ipsum</textarea>
```

So, the following lines in `studentInformationTable.tag` must be written in a single line -

``` jsp
<textarea class="form-control" rows="6" name="<%=Const.ParamsNames.COMMENTS%>" 
                              id="<%=Const.ParamsNames.COMMENTS%>">
    <c:out value="${studentInfoTable.comments}"/>
</textarea>
```

If the line exceeds the TEAMMATES convention of maximum 125 characters in a single line, the line break can be given anywhere between the `textarea` tag attributes but should not be given inside the tag itself.

This is a good `d.FirstTimers` issue.

**Comment by lonewolf9277** [comment]
Hi may I do this? I am new to open source

**Comment by VamsiSangam** [comment]
Sure @lonewolf9277 :smile: ! Please go through our [contributor orientation guide](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md) before you do. It will help you set up the project smoothly so that you can issues without hassles.

**Comment by lonewolf9277** [comment]
Thanks. Will do this today.

**Comment by VamsiSangam** [comment]
**Adding this to scope of issue** - In ` teammates/src/main/webapp/js/instructorFeedbackEdit/questionRubric.es6`, in `addRubricRow()`, the `textarea` tag is added with a new line, which causes the same issue -

``` js
const rubricRowFragment =
    `<td class="align-center rubricCol-${questionNum}-${cols}">
        <textarea class="form-control" rows="3" id="rubricDesc-${questionNum}-${newRowNumber - 1}-${cols}"
                name="rubricDesc-${newRowNumber - 1}-${cols}">
        </textarea>
    </td>`;
```

This should be changed to something like this -

``` js
const rubricRowFragment =
    `<td class="align-center rubricCol-${questionNum}-${cols}">
        <textarea class="form-control" rows="3" id="rubricDesc-${questionNum}-${newRowNumber - 1}-${cols}"
                name="rubricDesc-${newRowNumber - 1}-${cols}"></textarea>
    </td>`;
```

Also similar issue in the `addRubricCol()` method -

``` js
const rubricRowFragment =
    `<td class="align-center rubricCol-${questionNum}-${newColNumber - 1}">
        <textarea class="form-control" rows="3" id="rubricDesc-${questionNum}-${rows}-${newColNumber - 1}"
                name="rubricDesc-${rows}-${newColNumber - 1}">
        </textarea>
    </td>`;
```

this needs to be changed to something like this -

``` js
const rubricRowFragment =
    `<td class="align-center rubricCol-${questionNum}-${newColNumber - 1}">
        <textarea class="form-control" rows="3" id="rubricDesc-${questionNum}-${rows}-${newColNumber - 1}"
                name="rubricDesc-${rows}-${newColNumber - 1}"></textarea>
    </td>`;
```

@lonewolf9277 if you are working on this, please note :smile:

**Comment by damithc** [comment]
Upgrading the difficulty level because this might require changes to test cases (and God mode)

**Comment by VamsiSangam** [comment]
@lonewolf9277 , the scope of this PR has been increased, and it involves some complex actions for which you may not be ready for. Please move to another [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aissue+is%3Aopen+label%3Ad.FirstTimers) issue of your choice. Sorry for the inconvenience. :sweat_smile:

**Comment by lonewolf9277** [comment]
Ok no problem

**Comment by VamsiSangam** [comment]
Working on this.
