### ISSUE TITLE
Change links to index.jsp to point to application root

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#7405]
Example: the TEAMMATES logo links to the application root `/`, whereas the Home menu item links to `/index.jsp`. For consistency, all links to `/index.jsp` should be changed to point to `/`. Requires updating of test HTML files using GodMode.

Add: such links can be found at:
- `Const.java`
- `LogoutServlet.java`
- `bodyFooter.tag`
- `helpPage.tag`
- `staticPage.tag`

**Comment by nikiforosbotis** [comment]
@whipermr5 I would like to work on that
