### ISSUE TITLE
Understanding of servlets

### ISSUE THREAD

**Issue by angelosdmg** [TEAMMATES/teammates#7410]
Hello, can you please explain me how does the logout servlet work? Where does the mapping happen?

**Comment by VamsiSangam** [comment]
The logout servlet is `teammates.ui.controller.LogoutServlet`, it is a generic servlet to log out any user I guess. As for the mapping, it happens in `teammates.ui.controller.ActionFactory`, a URL is mapped to a subclass of `Action` class.

**Comment by Mynk96** [comment]
`<servlet>
        <servlet-name>LogoutServlet</servlet-name>
        <servlet-class>teammates.ui.controller.LogoutServlet</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>LogoutServlet</servlet-name>
        <url-pattern>/logout</url-pattern>
    </servlet-mapping>`
From the above code you can clearly see how logout servlet works.
As soon as you press logout button, it takes you to url http://localhost/logout which is mapped to LogoutServlet in teammates.ui.controller.

**Comment by wkurniawan07** [comment]
@angelosdmg `web.xml` is where the mapping between URL patterns and servlets happen.

**Comment by angelosdmg** [comment]
Thanks guys. Problem solved
