### ISSUE TITLE
Token validation: handle requests with old sessions

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7411]
One example from the log (all requests from the same IP)
![image](https://cloud.githubusercontent.com/assets/1673303/26611195/35c8222c-45df-11e7-908e-7bbcf21b0370.png)

Does it look right?

**Comment by damithc** [comment]
The above screenshot is not very useful because it cuts off logs that happened _before_ the error. Here are some that don't. In all three cases there is a significant time lapse between loading the edit page and saving it. However, from user's point of view it can be annoying to get an error message even if the page was loaded long ago, especially if the user ends up losing all he typed.

![image](https://cloud.githubusercontent.com/assets/1673303/26752699/d0f7b6b2-4888-11e7-862c-0e545316c469.png)

![image](https://cloud.githubusercontent.com/assets/1673303/26752766/fac1f934-4889-11e7-9c39-8f4190499756.png)

![image](https://cloud.githubusercontent.com/assets/1673303/26752799/9a698b50-488a-11e7-91d9-1facb452884c.png)

**Comment by whipermr5** [comment]
@damithc The time lapse shouldn't be a problem at all as our token only depends on the session, so as long as the user remains logged in, it's valid. Can you expand the log item to see which of the four cases it is: missing/invalid referrer/token? If it's a missing referrer, it's up to the user to re-enable it in the browser.

**Comment by damithc** [comment]
I checked one. It says `teammates.common.exception.InvalidOriginException: Invalid session token`


![image](https://cloud.githubusercontent.com/assets/1673303/26771527/7f0c260c-49f1-11e7-89c5-20c0b8bfb137.png)
