### ISSUE TITLE
LMS Integration

### ISSUE THREAD

**Issue by DanielSEvans** [TEAMMATES/teammates#7420]
Our school uses teammates in some courses -bravo for the great application !
We are users of D2L. I saw that there is an LMS Integration project planned.
Is there any advancementi in this area

**Comment by damithc** [comment]
@DanielSEvans we have just started looking into it. So things are moving in that direction but it might take at least a few months before some LMS integration is available for users. In the meantime, you'll have to copy paste the student data from D2L (or any other source) to TEAMMATES.

**Comment by wkurniawan07** [comment]
Closing as this is not a priority right now
