### ISSUE TITLE
Set up Webpack to enable modular JS development

### ISSUE THREAD

**Issue by thenaesh** [TEAMMATES/teammates#7428]
Every JSP file should include one minified JS file, which imports what it needs and no more. To start this off, we first do this for the page-specific files (e.g. `adminEmail.es6`).

For each JS file `x.es6` containing the main functionality of `X.jsp`, the rough strategy is as follows:

1. Track down the sources `y1.es6`, ..., `yn.es6` of all external functions used in `x.es6`. This should be easy given that the external functions are already documented in the ESLint configuration in `x.es6`.
1. For each `yk.es6`, `1 <= k <= n`, add the functions defined in `yk.es6` and used in `x.es6` to the `module.exports` of `yk.es6`.
1. Import `y1.es6`, ..., `yn.es6` into `x.es6` using the ES6 `import` statement.
1. Remove `y1.es6`, ... `yn.es6` from the `<script>` declarations of `X.jsp`.
1. Update any necessary Webpack configuration.

We can initially ignore things like `common.es6` (which, among other things, contains stuff like `toggleSort`), if this is possible. We can also avoid recursively tracking down the dependencies of each `yk.es6`, if this helps manage complexity initially.

**Comment by thenaesh** [comment]
@wkurniawan07 @li-kai For your comment. There are probably places where this plan will blow up that I'm not aware of.

**Comment by wkurniawan07** [comment]
That is in fact the migration plan from the very beginning. It very well explains why I [proposed the creation of one main script per page](https://github.com/TEAMMATES/teammates/pull/7004).

When we're ready to involve bundlers in the game (likely but not necessarily Webpack), then your idea should be feasible. I can't pinpoint any place where pitfalls can occur just yet.
