### ISSUE TITLE
Add new instructor in adminHomePage not working

### ISSUE THREAD

**Issue by Mynk96** [TEAMMATES/teammates#7432]
![fail](https://cloud.githubusercontent.com/assets/17481466/26723254/3d912a34-47b1-11e7-96a8-c510cd628edb.PNG)

Log details:-
Servlet Action failure in adminInstructorAccountAdd
class teammates.common.exception.InvalidOriginException: teammates.common.exception.InvalidOriginException: Missing session token at teammates.ui.controller.Action.validateOriginIfRequired(Action.java:147) at teammates.ui.controller.Action.init(Action.java:94) at teammates.ui.controller.ActionFactory.getAction(ActionFactory.java:143) at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:66) at javax.servlet.http.HttpServlet.service(HttpServlet.java:637) at javax.servlet.http.HttpServlet.service(HttpServlet.java:717) at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166) at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:128) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:125) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366) at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349) at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388) at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216) at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182) at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765) at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418) at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98) at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:509) at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) at org.mortbay.jetty.Server.handle(Server.java:326) at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923) at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547) at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212) at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409) at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582) 
{ "instructoremail": [ "aa@gmail.com" ], "instructorinstitution": [ "asdfsf" ], "instructorshortname": [ "a" ], "instructorname": [ "asd" ] }

**Comment by damithc** [comment]
Recently there was a similar case like this and the solution was to run `npm run build` (which needs to be run whenever there is a change to javascript code).

**Comment by Mynk96** [comment]
Well I tried running `npm run build` before creating this issue it didn't work, but now after your suggestion, I again did `npm run build ` and surprisingly it worked. Closing

**Comment by shreyag12** [comment]
Add Instructor is not working for me too. Could you please tell how did you solve the problem. I tried npm run build as well. But it didn't work.

**Comment by damithc** [comment]
> Add Instructor is not working for me too. Could you please tell how did you solve the problem. I tried npm run build as well. But it didn't work.

It might help if you give more details. What did you observe when you tried it? any error message? A screenshot might help too.

**Comment by shreyag12** [comment]
![screenshot from 2017-06-12 21 41 32](https://user-images.githubusercontent.com/6481566/27043574-35d7a840-4fb8-11e7-8e22-8f23c49e1b6f.png)
No error comes when i press this Add Instructor button.

**Comment by damithc** [comment]
@shreyag12 can you try the other form displayed at the top of the same page?
@TEAMMATES/activedevs can someone confirm this behavior reported by @shreyag12 above?

**Comment by whipermr5** [comment]
Mine's working fine on a clean setup from `master`. @shreyag12 what happens when you do `npm run build`?

**Comment by Mynk96** [comment]
@shreyag12 this problem looks like javascript not properly included in the page. Can you please clean your cache in your web browser, clean your project in eclipse, do `npm run build` and restart your dev server (sequentially). I hope that would resolve your problem.

**Comment by shreyag12** [comment]
![screenshot from 2017-06-17 10 20 35](https://user-images.githubusercontent.com/6481566/27250251-709c60a0-5347-11e7-85af-f2786bc56413.png)
![screenshot from 2017-06-17 10 19 43](https://user-images.githubusercontent.com/6481566/27250255-882bb414-5347-11e7-96a4-1176a6e7065c.png)
This is what happens when I run npm run build. Could you please tell what i am doing wrong?

**Comment by whipermr5** [comment]
From a quick Google search: `ln -s /usr/bin/nodejs /usr/bin/node`

**Comment by shreyag12** [comment]
![screenshot from 2017-06-17 14 26 28](https://user-images.githubusercontent.com/6481566/27251656-fc679dea-5368-11e7-9cd3-d8aa9d7e59b4.png)
@whipermr5  I did as you said but now this error has come and i installed electron-to-chromium also npm install --save electron-to-chromium
but this problem still persists.

**Comment by whipermr5** [comment]
`npm install`

**Comment by shreyag12** [comment]
![screenshot from 2017-06-24 10 54 17](https://user-images.githubusercontent.com/6481566/27505973-8c87514c-58cb-11e7-9a9c-b0404f4e8dce.png)
Hi, I searched about this issue but could not resolve it. Do you have any idea about it? 
@whipermr5 @Mynk96

**Comment by whipermr5** [comment]
`npm install`

**Comment by shreyag12** [comment]
![screenshot from 2017-06-24 11 38 15](https://user-images.githubusercontent.com/6481566/27506220-a2cc44fc-58d1-11e7-8a05-ab5c4badc8e5.png)
@whipermr5 did npm install as well.

**Comment by whipermr5** [comment]
Which one did you do: `sudo apt-get install nodejs-legacy` or `ln -s /usr/bin/nodejs /usr/bin/node`?

**Comment by whipermr5** [comment]
The `apt` command in your screenshot doesn't look like it installed `nodejs-legacy` but `nodejs` (which didn't do anything as it was already installed).

**Comment by shreyag12** [comment]
![screenshot from 2017-06-24 11 51 05](https://user-images.githubusercontent.com/6481566/27506358-91651660-58d3-11e7-9d5b-6c23e91d1342.png)

@whipermr5 see it says nodejs-legacy is already installed

**Comment by whipermr5** [comment]
I see 😅 What version of nodejs?

**Comment by shreyag12** [comment]
v0.10.25

**Comment by whipermr5** [comment]
I see. Can you install Node.js v8? https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
