### ISSUE TITLE
Document how to use masquerade mode

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7447]
When developers are manually testing against the dev server, they can use the _masquerade mode_  to impersonate different users. Just need to add the `user=username` to the URL e.g. `http://localhost:8888/page/studentHomePage?user=johnKent`
Note: masquerade mode works only if the logged in user has admin access

We can add the above info to our dev guides as some developers may not be aware of it.

**Comment by davel37** [comment]
Is there anybody working on this issue? I would like to take it if it's free.
