### ISSUE TITLE
New contributor self intro Aditya Hegde

### ISSUE THREAD

**Issue by adityavhegde** [TEAMMATES/teammates#7451]
Hi all,
Here is a small change to the index page. I made the video open on the same page, replacing the image, which is just below the header. Pressing the escape key, closes the video -- thereby replacing it with the original image.
The opened video is responsive in nature (adjusting to browser sizes)

**my fork**: https://github.com/adityavhegde/teammates/tree/tinker

![video_changes](https://cloud.githubusercontent.com/assets/10449636/26785592/d91b830c-4a20-11e7-9773-dfdf7abe81e6.JPG)

I am a Master's Computer Science student. Having had experiences with smaller projects in Java, alongside my interests in OSS, I want to delve deeper into  best practices in Software Engineering -- which brings me here.

**Comment by thenaesh** [comment]
Welcome to TEAMMATES! You may start with solving `d.FirstTimers` issues (please don't do more than one of these) and then proceed to solving `d.Contributors` issues.

**Comment by adityavhegde** [comment]
Hi @thenaesh,
Appreciate your response. Is there a slack channel where communication takes place ?

**Comment by damithc** [comment]
> Is there a slack channel where communication takes place ?

@adityavhegde we don't have a public access chat channel at the moment. You can use the issue tracker to ask questions or request for help.

**Comment by adityavhegde** [comment]
@damithc thank you :)
