### ISSUE TITLE
InstructorFeedbackResponseCommentDeleteActionTest is not stable

### ISSUE THREAD

**Issue by HirdayGupta** [TEAMMATES/teammates#7454]
The `InstructorFeedbackResponseCommentDeleteActionTest` is failing.

- Travis error message: Java.lang.NullPointerException at InstructorFeedbackResponseCommentDeleteActionTest.java:52. 
- local machine error message: java.lang.AssertionError: response comment not found at InstructorFeedbackResponseCommentDeleteActionTest.java:124 

This was happening across all my open PRs before #7452 was merged by @whipermr5, but is now happening only on #7416 and #7453. Requesting assistance in dealing with this issue.

**Note:** the error persists even after multiple test tries in Travis.

**Comment by wkurniawan07** [comment]
I've been observing for the past few days. Seems like this failure has non-trivial potential to halt an otherwise-passing build, so this should be remedied as soon as we can.

The linked PR is not the cause; the actual cause is #7332. @sujeet14108 can you spend some time to troubleshoot?

**Comment by HirdayGupta** [comment]
@wkurniawan07 I've noticed across several other PRs with failing tests that this error goes away over multiple Travis test tries.However, in the ones linked above, it remains even after all test tries. How is it that the tests behave in an inconsistent manner?

**Comment by whipermr5** [comment]
Related to #7455?

**Comment by wkurniawan07** [comment]
Could very well be. I haven't troubleshot and perhaps will not.

**Comment by whipermr5** [comment]
Subsuming under #7455.
