### ISSUE TITLE
InstructorFeedbackSubmissionEditSaveActionTest and InstructorFeedbackResponseCommentDeleteActionTest: load required data bundles

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#7455]
#7332 introduced mandatory `testAccessControl` for every action test. One such test, `InstructorFeedbackSubmissionEditSaveActionTest`, overrides `prepareTestData` and does not load the typical data bundle. However, the typical data bundle is actually needed for the access control test.

The access control test calls `verifyUnaccessibleWithoutSubmitSessionInSectionsPrivilege`, which calls `gaeSimulation.loginAsInstructor(helperOfCourse1.googleId)`, which asserts that `gateKeeper.getCurrentUser().isInstructor` is true. `gateKeeper.getCurrentUser()` calls `accountsLogic.isAccountAnInstructor`, which retrieves the account from the datastore and returns false if it doesn't exist. Since `helperOfCourse1` isn't in the datastore, the assertion fails.

The only reason why the CI currently passes is because the JDO API is very slow, and the typical data bundle, loaded from previous test runs, is still accessible even though it is actually being removed. For Objectify, which uses caching, the test fails because the typical data bundle is (rightfully) removed before the test runs. This is the reason why #7338 started failing after #7332 was merged in.

EDIT: Widening the scope to include #7454 as the cause of that is also missing data required for the test.

**Comment by damithc** [comment]
Good job diagnosing the problem 👍

**Comment by sujeet14108** [comment]
Looking at it. :sweat_smile:
