### ISSUE TITLE
Assistance requested: Test is failing on Travis but passing on local machine

### ISSUE THREAD

**Issue by HirdayGupta** [TEAMMATES/teammates#7456]
Refer to the content under the heading Test 3 on [this comment](https://github.com/TEAMMATES/teammates/pull/7416#issuecomment-306313173). The test `InstructorCourseStudentDetailsEditPageUiTest` is failing with `NoSuchElementException at InstructorCourseStudentDetailsEditPageUiTest.java:74` on Travis but is passing on my local machine. The PR does not affect any aspect of the contents being tested in this file.

Requesting assistance in dealing with the same.

**Comment by wkurniawan07** [comment]
Your latest build is a green though...

**Comment by HirdayGupta** [comment]
@wkurniawan07 Yes, it is. Was an issue before the latest commits. Closing.
