### ISSUE TITLE
Instructor: enroll students: trim leading/trailing spaces

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7457]
A user reported this error.
`" Humaira Ken" is not acceptable to TEAMMATES as a/an person name because it starts with a non-alphanumeric character. All person name must start with an alphanumeric character, and cannot contain any vertical bar (|) or percent sign (%).`

Sounds like our code is not trimming leading spaces.

**Comment by wkurniawan07** [comment]
I don't think it comes from "enroll students": [here's proof](https://github.com/TEAMMATES/teammates/blob/master/src/test/java/teammates/test/cases/logic/StudentsLogicTest.java#L617).

**Comment by damithc** [comment]
Yes, I thought we handled this sometime back. From the admin log:
```
Problem in line : 1	1	 abc Tuly	abctuly@icloud.com 
• " abc Tuly" is not acceptable to TEAMMATES as a/an person name because it starts with a non-alphanumeric character. All person name must start with an alphanumeric character, and cannot contain any vertical bar (|) or percent sign (%).


Problem in line : 1	1	 def Cribbs	 defcribbs@aol.com
• " defcribbs@aol.com" is not acceptable to TEAMMATES as a/an email because it is not in the correct format. An email address contains some text followed by one '@' sign followed by some more text. It cannot be longer than 254 characters, cannot be empty and cannot contain spaces.
• " def Cribbs" is not acceptable to TEAMMATES as a/an person name because it starts with a non-alphanumeric character. All person name must start with an alphanumeric character, and cannot contain any vertical bar (|) or percent sign (%).


Enrollment string entered by user:
Section	Team	Name	Email 
1	1	 abc Tuly	abctuly@icloud.com 
1	1	 def Cribbs	 defcribbs@aol.com 
```
I asked the user to remove the extra spaces and she says it worked after that.

**Comment by wkurniawan07** [comment]
I tried the enrollment string provided there and did not encounter the said problem in the latest `master`.

**Comment by damithc** [comment]
> I tried the enrollment string provided there and did not encounter the said problem in the latest master.

I can't reproduce it either. :-p Strange.
