### ISSUE TITLE
Dev Help Required: enabling GodMode in test.properties

### ISSUE THREAD

**Issue by HirdayGupta** [TEAMMATES/teammates#7464]
@whipermr5 I changed the `test.godmode.enabled` to `true` in the `test.template.properties` file. (This option is, for some reason, not visible to me in the `test.properties` file. Don't know if this is an error in the [new God Mode documentation](https://github.com/TEAMMATES/teammates/blob/master/docs/godmode.md) or the cause of this Issue)

I then refreshed, cleaned and ran the project as a web application on localhost:8888

However, on running `InstructorFeedbackEditPageUiTest`, I still get a java.lang.AssertionError because the expected HTML and Actual HTML files are different.

**Note:** God mode seemed to be working fine before #7379.

**Comment by whipermr5** [comment]
Hey @HirdayGupta, the option should be copied into `test.properties`, as that is the file that is read :)

**Comment by HirdayGupta** [comment]
@whipermr5 thanks! It's working now. 😃

**Comment by HirdayGupta** [comment]
@whipermr5 Permission to close? (issue is sorted) Also, would you like to add a line in god mode doc that says `For existing developers, copy the test.godmode.enabled property from test.template.properties to test.properties`. If so can open a new `d.FirstTimers` issue.

**Comment by whipermr5** [comment]
I'd prefer to just let the existing devs read it through this issue; will keep it open for a few more days :)
