### ISSUE TITLE
New contributor self intro Brian Coveney

### ISSUE THREAD

**Issue by BrianCoveney** [TEAMMATES/teammates#7465]
app:
https://1-0-dot-teammates-brian.appspot.com/index.jsp

fork:
https://github.com/BrianCoveney/teammates/tree/tinker

screenshot of the change:

![contact_us](https://user-images.githubusercontent.com/8080260/26900162-3ff36cbc-4bc9-11e7-8684-e95f81178136.png)

self-intro:

Hi all, my name is Brian Coveney. I am a 3rd year computing student, and mainly work on small Java applications for college and fun. I'd like to getting started contributing to OOS, and your project looks interesting.

**Comment by whipermr5** [comment]
Hey Brian, welcome to TEAMMATES! Good job setting everything up correctly! You can get your feet wet by working on a `d.FirstTimers` issue, then move on to `d.Contributors` issues :)

**Comment by BrianCoveney** [comment]
Thanks for the welcome @whipermr5. I'll have a look at the ```d.FirstTimers``` issues to start with.

**Comment by davel37** [comment]
Hi Brian,
Quick question as we are both based in europe. Did you have to sign up for the business version of GAE thus incurring monthly charges, as the individual (free) option is not available in europe?

**Comment by BrianCoveney** [comment]
Hi Dave,

I had already set up a business version of GAE for a previous college project. As you said, there is no free option in Europe, but there is a [free trial](https://cloud.google.com/free/docs/frequently-asked-questions) of a year / $300 in credit.  I will close my a/c within this period for obvious reasons. 

You've probably seen this (take from link above):

![billing](https://user-images.githubusercontent.com/8080260/27804697-43da4f94-6028-11e7-95c6-342914099607.png)
