### ISSUE TITLE
InstructorHelp: Remove horizontal scroll for mobile devices

### ISSUE THREAD

**Issue by amarlearning** [TEAMMATES/teammates#7467]
Facing a horizontal scroll in Instructor Help page for mobile devices. _[screenshot]_
![screenshot from 2017-06-08 05-20-51](https://user-images.githubusercontent.com/9383897/26906401-a1b49598-4c0a-11e7-8c2d-bc3a760d829a.png)

**Comment by amarlearning** [comment]
Can anyone please confirm that if there is a horizontal scroll in `instructorHelp.jsp` page on a small screen.

**Comment by chowyb** [comment]
Seems to still be present; the main cause appears to be visibility settings when editing a question, where the button stretches the screen (especially if the text is long).

**Comment by amarlearning** [comment]
@chowyb yes, you are right that button stretches the screen if the text is too long. I think the footer is also totally unresponsive.

**Comment by wkurniawan07** [comment]
No longer reproducible.
