### ISSUE TITLE
Fix lintspaces on Windows

### ISSUE THREAD

**Issue by shubham49** [TEAMMATES/teammates#7469]
I have added unnecessary spaces in some .html file, and ran `npm run lint:spaces`.
![image](https://user-images.githubusercontent.com/10528953/26914201-7ed2816a-4c3d-11e7-921b-9b5635bf009b.png)
As you can see I get no errors.

If I modify `lint:spaces` script in package.json file, I get errors.
![image](https://user-images.githubusercontent.com/10528953/26914291-12bef67e-4c3e-11e7-96e7-511cdd4712f7.png)

I have removed ' character from the script, I guess that doesn't work for windows.

**Comment by whipermr5** [comment]
Thanks for the report!
