### ISSUE TITLE
AdminHomePageUiTest: enhance to cover content of the sample course

### ISSUE THREAD

**Issue by sujeet14108** [TEAMMATES/teammates#7479]
As discussed in #7441

**Comment by sujeet14108** [comment]
@damithc In `AdminHomePageUiTest` i guess the the required test is already present.

        //verify sample course is accessible for newly joined instructor as an instructor

        ______TS("new instructor can see sample course in homepage");
        InstructorHomePage instructorHomePage = AppPage.getNewPageInstance(browser, InstructorHomePage.class);
        instructorHomePage.verifyHtmlMainContent("/newlyJoinedInstructorHomePage.html");

        ______TS("new instructor can access sample coure enroll page");
        InstructorCourseEnrollPage enrollPage = instructorHomePage.clickCourseEnrollLink(demoCourseId);
        enrollPage.verifyHtmlMainContent("/newlyJoinedInstructorCourseEnrollPage.html");

        ______TS("new instructor can access sample coure details page");
        instructorHomePage = enrollPage.goToPreviousPage(InstructorHomePage.class);
        InstructorCourseDetailsPage detailsPage = instructorHomePage.clickCourseViewLink(demoCourseId);
        detailsPage.verifyHtmlMainContent("/newlyJoinedInstructorCourseDetailsPage.html");

        ______TS("new instructor can access sample coure edit page");
        instructorHomePage = detailsPage.goToPreviousPage(InstructorHomePage.class);
        InstructorCourseEditPage editPage = instructorHomePage.clickCourseEditLink(demoCourseId);
        editPage.verifyHtmlMainContent("/newlyJoinedInstructorCourseEditPage.html");

        ______TS("new instructor can access sample coure feedback session adding page");
        instructorHomePage = editPage.goToPreviousPage(InstructorHomePage.class);
        InstructorFeedbacksPage feedbacksPage = instructorHomePage.clickCourseAddEvaluationLink(demoCourseId);
        feedbacksPage.verifyHtmlMainContent("/newlyJoinedInstructorFeedbacksPage.html");

        ______TS("new instructor can archive sample course");
        instructorHomePage = feedbacksPage.goToPreviousPage(InstructorHomePage.class);
        instructorHomePage.clickArchiveCourseLinkAndConfirm(demoCourseId);
        instructorHomePage.verifyHtmlMainContent("/newlyJoinedInstructorHomePageSampleCourseArchived.html");

        ______TS("new instructor can unarchive sample course");
        AppUrl url = createUrl(Const.ActionURIs.INSTRUCTOR_COURSES_PAGE)
                                        .withUserId(TestProperties.TEST_INSTRUCTOR_ACCOUNT);
        InstructorCoursesPage coursesPage = AppPage.getNewPageInstance(browser, url, InstructorCoursesPage.class);
        coursesPage.waitForAjaxLoadCoursesSuccess();
        coursesPage.unarchiveCourse(demoCourseId);
        coursesPage.verifyHtmlMainContent("/newlyJoinedInstructorCoursesPageSampleCourseUnarhived.html");

        ______TS("new instructor can access sample course students page");
        coursesPage.loadStudentsTab().verifyHtmlMainContent("/newlyJoinedInstructorStudentListPage.html");

        ______TS("new instructor can view feedbackSession result of sample course");
        coursesPage.loadInstructorHomeTab();
        instructorHomePage = AppPage.getNewPageInstance(browser, InstructorHomePage.class);
        instructorHomePage.clickFeedbackSessionViewResultsLink(demoCourseId, "Second team feedback session");
        instructorHomePage.verifyHtmlMainContent("/newlyJoinedInstructorFeedbackResultsPage.html");
`

**Comment by damithc** [comment]
If it is already covered by tests, then some of the tests should have failed when you added new comments :-)

**Comment by sujeet14108** [comment]
There are three session in sample course but current test only tests for one feedback session. Would write the test for other and update it :)
