### ISSUE TITLE
Admin: create instructor: fix bug that shows failure even when the operation succeeds

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7481]
v5.106, manual testing against dev server

![image](https://user-images.githubusercontent.com/1673303/26962417-94cf5b38-4d18-11e7-9fdd-53ff52c04b91.png)

Operation seems to succeed (the join link works and the sample course is in the datastore) but shown in red and the data is reinserted to the text box (should only happen when the operation fails)

**Comment by whipermr5** [comment]
Note to self: scan through the changes in #7132 to see if any other page data has been affected but as yet undetected. 😅
