### ISSUE TITLE
Dev docs: explain how to run dev server in CLI with console output visible

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7482]
Current:
`gradlew appEngineRun` starts the dev server in CLI mode.

Problem: 
In this mode, dev is unable to see the console output of the dev server. It is better if the dev can see the console output e.g. for debugging

Suggested:
Find out and document how to run the dev serve in CLI mode with the console output visible.

Edit:
Simply add the command `./gradlew appengineRun -Pdisable_daemon` to [`development.md#managing-the-dev-server`](https://github.com/TEAMMATES/teammates/blob/7e0250de262e883ad81bd50bc7b943a73582e156/docs/development.md#managing-the-dev-server).

**Comment by LiHaoTan** [comment]
Just adding some info here. This can be done with `./gradlew appengineRun -Pdisable_daemon`

**Comment by damithc** [comment]
> Just adding some info here. This can be done with ./gradlew appengineRun -Pdisable_daemon

Looks like leaving `org.gradle.daemon=false` in the `gradle.properties` doesn't have the same effect. So we have to enable it and then disable it :-p

**Comment by LiHaoTan** [comment]
@damithc oh they don't refer to the same daemon, this property refers to the app engine specific daemon, not the Gradle daemon.

**Comment by whipermr5** [comment]
Seems like `disable_daemon` is actually our own custom property, used to pass the `daemon` option to the `appengineRun` closure ([link](https://github.com/TEAMMATES/teammates/blob/7e0250de262e883ad81bd50bc7b943a73582e156/build.gradle#L539)).

**Comment by huai99** [comment]
I can work on this problem
