### ISSUE TITLE
Instructor: view results: separate 'expand' button from status message

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7485]
v5.106
![image](https://user-images.githubusercontent.com/1673303/26964952-53abd1d2-4d26-11e7-8078-607008633e78.png)

Can use `InstructorFeedbackResultsPageUiTest#testViewPhotoAndAjaxForLargeScaledSession()` to observe this problem

**Comment by shreyag12** [comment]
Hello,
I would like to work on this.

**Comment by adityavhegde** [comment]
Hi, is anyone still working on this. If not, I'd like to take this up.

**Comment by adityavhegde** [comment]
Hi @LimeTheCoder, I am still working on this. Quite a confusing state of affairs.

**Comment by LimeTheCoder** [comment]
Hi, @adityavhegde. Okay, you can continue, sorry. I'll close my open pull request.

**Comment by adityavhegde** [comment]
Thank you @LimeTheCoder :)

**Comment by adityavhegde** [comment]
@whipermr5  , is there a data or way, I can use to replicate this.
I run the test file, but the tests are fast, which makes it difficult to observe how my changes are affecting.
I tried logging in, with the test user id, but this particular test case is not visible.

**Comment by whipermr5** [comment]
@adityavhegde Add a line `assertTrue(false);` to make the test fail at the desired place.

**Comment by arjunsuri** [comment]
Is it still open?

**Comment by adityavhegde** [comment]
@arjunsuri I expect it to close sooner. There is an active pull request.
