### ISSUE TITLE
Intellij instructions: give more details about deploying

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7489]
Current instructions in `/docs/development.md` point to [this link](https://www.jetbrains.com/help/idea/2016.3/getting-started-with-google-app-engine.html#deploy_googleapp_via_runConfig) but step 4 might need more guidance on what the required `Google App Engine Deployment settings` are.

**Comment by wkurniawan07** [comment]
Issue is outdated as the docs now point to official instructions from Cloud Tools for IntelliJ.
