### ISSUE TITLE
instructorFeedbackEdit: add class margin-bottom-7px to JS added MCQ and MSQ options

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7507]
The options for MSQ and MCQ question types have a class `margin-bottom-7px` which adds a small gap between them.

![1](https://user-images.githubusercontent.com/11662001/27046520-6038b818-4fc2-11e7-9fe5-0bdd0ead31db.JPG)

But the options which are generated through JS, by clicking `+ add more options` button don't have this class which makes subsequently added options cramped.

![2](https://user-images.githubusercontent.com/11662001/27046581-a5a0a208-4fc2-11e7-8809-e6d8e8587b21.JPG)

**Solution**

In `addMsqOption()` method of `questionMsq.es6`, change this line -

``` js
<div id="msqOptionRow-${curNumberOfChoiceCreated}-${questionNum}">
        <div class="input-group">
```

to

``` js
<div id="msqOptionRow-${curNumberOfChoiceCreated}-${questionNum}" class="margin-bottom-7px">
        <div class="input-group">
```

Similar change must be done in `addMcqOption()` method of `questionMcq.es6` also.

**Comment by chowyb** [comment]
Setting to `d.Contributors` as this might require use of GodMode, even though the change is relatively straightforward.
