### ISSUE TITLE
Instructor: edit question: receiver is instructors: support specifying a max number of recipients

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7512]
Current:
![image](https://user-images.githubusercontent.com/1673303/27067744-0fc824b8-503f-11e7-818d-72a330da8159.png)

Support something like this (screenshot from the case where recipient is 'other students in the course')
![image](https://user-images.githubusercontent.com/1673303/27067819-639c0aa0-503f-11e7-8bf7-6432bf2cc405.png)

Justification:
Requested by a user. His course has 30 tutors and each student gives feedback to one instructor only.

**Comment by LuLechuan** [comment]
Can I work on this issue since nobody took it?
