### ISSUE TITLE
Add datastore-indexes.xml for easier deployment

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#7513]
Currently, we do not have a [datastore-indexes.xml](https://cloud.google.com/appengine/docs/standard/java/config/indexconfig) file in `src/main/webapp/WEB-INF/`, but instead rely on the autogenerated `src/main/webapp/WEB-INF/appengine-generated/datastore-indexes-auto.xml` which only gets updated index by index whenever the dev server performs an action that queries the datastore.

For the file to be fully populated, the entire test suite must first be run locally. This is required before deploying to a staging server, as the live Datastore requires indexes to be generated first before queries can succeed. If a deployment is attempted without this step, the resultant staging server is not fully functional - it will throw an exception whenever the user invokes an action that runs a query requiring an index that has not yet been generated.

By explicitly specifying all required indexes in `datastore-indexes.xml`, the testing step can be skipped and the project can be deployed from a fresh setup much more quickly.

**Comment by damithc** [comment]
:+1:
In fact. some indexes don't get created even if the entire test suite is run. e.g. those related to automated reminders.

**Comment by whipermr5** [comment]
I do get all 6 indexes by running the full test suite, unless I'm missing some more?
<img width="644" alt="screen shot 2017-06-19 at 8 06 22 am" src="https://user-images.githubusercontent.com/6811428/27265341-60e47e38-54c6-11e7-86fb-bd4c59bf7daa.png">

**Comment by damithc** [comment]
> I do get all 6 indexes by running the full test suite, unless I'm missing some more?

There were times when some indexes were not added by the test suite. Perhaps test cases have been added to cover all 6 indexes since then.
