### ISSUE TITLE
New contributor self intro Steven Israel

### ISSUE THREAD

**Issue by malenchite** [TEAMMATES/teammates#7515]
App:
http://teammates-malenchite.appspot.com/

Tinker Fork:
https://github.com/malenchite/teammates/tree/tinker

UI Change:
 My simple change was to alternate the graphics on the main index rather than have them in a single column.

![image](https://user-images.githubusercontent.com/1165054/27082626-8afda4fe-5013-11e7-93ea-d45480eb14e7.png)

Intro:
My name is Steven Israel. I have been working in robotics for over a decade but I am trying to transition to a more purely software-driven role. I have no experience in Java or OSS, so this seemed like a great place to get my feet wet.

**Comment by whipermr5** [comment]
Hey Steven, welcome to TEAMMATES! Good job setting everything up correctly! You can get your feet wet by working on a `d.FirstTimers` issue, then move on to `d.Contributors` issues :)
