### ISSUE TITLE
Instructor: publish session: fix bug where emails go out but the session remains unpublished

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7516]
Received from a user:
`I went to Home, then on the course list, selected “View Results” of the session. Then selected Publish Results. I did get emails from students saying they could not view the results.  So I went back in and clicked “Publish Results” from the Home page. I then got the email that the session results were published.`

Two sessions faced similar issues today. The session was published by the instructor and students received emails but the links didn't work and the session status remained closed.

Need to investigate if something broke in the recent release (v5.106) or it's a temporary glitch? May be caused by cached JS files?

**Comment by wkurniawan07** [comment]
Likely cached JS files. I cannot reproduce this on the latest `master`.

**Comment by damithc** [comment]
> Likely cached JS files. I cannot reproduce this on the latest master.

Given that we do weekly releases, cached JS files could be a frequent problem? Any solutions?

**Comment by rclakmal** [comment]
Normally you could append the file get requests with a time stamp. But this way, user would be forced to download the file over and over within the same release, which is useless. Appending the release number would be a better way to go I guess ?

**Comment by wkurniawan07** [comment]
Actually it is very unlikely because our deployment descriptor (`appengine-web.xml`) does not specify caching, which means static files (JS included) should only be cached for 10 minutes max (something that should be improved for front-end performance). Likely it is a corner case where the user used the site "just nice" after the newest version went live.

**Comment by damithc** [comment]
Closing because no recent recurrences.
