### ISSUE TITLE
Release 5.107

### ISSUE THREAD

**Issue by thenaesh** [TEAMMATES/teammates#7526]
Scheduled for June 16, 2017, 11.59pm SGT.

**Comment by whipermr5** [comment]
The recent change to `appengine-web.template.xml` requires updating the local copy of `appengine-web.xml` before deploying.

**Comment by thenaesh** [comment]
Release 258

Code Contributions from: @adityavhegde, @amarlearning, @HirdayGupta, @whipermr5, @LiHaoTan, @li-kai, @Mynk96, @nikiforosbotis, @shubham49, @malenchite, @sujeet14108, @LimeTheCoder, @thenaesh, @VamsiSangam, @wkurniawan07
Review Contributions from: @damithc, @whipermr5, @LiHaoTan, @sujeet14108, @samsontmr, @thenaesh, @wkurniawan07, @chowyb

Sprint Period: June 9, 2017 - June 20, 2017
Sprint Velocity: 184 points (code) + 64 points (review) = 248 points (total)

**Comment by damithc** [comment]
deployed
