### ISSUE TITLE
Clean up the AJAX calls

### ISSUE THREAD

**Issue by thenaesh** [TEAMMATES/teammates#7528]
It's an unholy, filthy mess right now, with AJAX calls in several files requesting HTML snippets and just chucking them into the DOM in a sloppy, error-prone and unmaintainable way.

Ideally, AJAX calls should request for JSON snippets, and we should have a standardised, easy-to-understand way to insert them into the page. Now that we have ES6, we can make full use of its features to build proper AJAX infrastructure.

(Perhaps we can explore the use of something like Vue.js, but maybe we shouldn't go that far. :stuck_out_tongue: @whipermr5 )

**Comment by wkurniawan07** [comment]
Not trying to discourage or anything because it is a legitimate issue, but I hope you understand the magnitude of what this issue entails...

**Comment by thenaesh** [comment]
@wkurniawan07 I'm painfully aware. :laughing:

**Comment by HirdayGupta** [comment]
@thenaesh As someone who is writing new AJAX functions, what should I keep in mind while implementing that would be in keeping with the AJAX standards expected of this PR. Given that the infrastructure to systematically place JSON responses into the DOM doesn't yet exist, should I still be avoiding chucking HTML into the DOM?

**Comment by thenaesh** [comment]
@HirdayGupta Ideally, try to keep the AJAX handling code modular, such that the parts doing the actual insertion into the DOM are kept separate from the other parts and easily replaceable.

**Comment by wkurniawan07** [comment]
This is V7's biggest achievement, by far.
