### ISSUE TITLE
Upgrade AppEngine SDK to 1.9.54

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#7529]
The current version we're using, 1.9.27, is nearly two years old - it's time for an upgrade.

**Reasons for Upgrading**

- Appstats cost calculation seems to have changed, as discovered in https://github.com/TEAMMATES/teammates/pull/6848#issuecomment-295121466. Before moving on to write more performance profiling tests that include cost calculation, we need to use the latest libraries for accurate results that mirror how Google currently calculates cost.
- As discovered by @LiHaoTan, using the latest library is a fix for #7483. However, he will continue work on #7498 to fix the root issue (we were including two conflicting libraries in our codebase).
- As discovered by @wkurniawan07, the latest library works fully with JDK 8. This will enable migration to JDK 8 and avoid issues like #7548. See https://github.com/TEAMMATES/teammates/issues/7548#issuecomment-309794006 and https://github.com/TEAMMATES/teammates/pull/7553#issue-237309548.

**Caveats**

- There is an issue of incompatibility between the latest GCS client library and Appstats https://github.com/GoogleCloudPlatform/appengine-gcs-client/issues/52
  - This can be fixed using a nice workaround developed by @wkurniawan07 https://github.com/wkurniawan07/repo/commit/e55390de34743fcbad958a89d5502bed93fad676#diff-00c25927bba9dfac02bcc8073a86939c

**Comment by wkurniawan07** [comment]
For reference, the reason I did not do any upgrade before was because I was waiting for [Java 8 support](https://cloudplatform.googleblog.com/2017/03/your-favorite-languages-now-on-Google-App-Engine.html). Clearly it did not make the cut before, but it might in the next 3-4 months so I leave it up to you if you want to upgrade now or wait a little longer.

P.S. if you want to upgrade now, it looks like 1.9.54 has been released.

**Comment by whipermr5** [comment]
@wkurniawan07 👍 It doesn't seem to be on maven central though (at least not the website).

**Comment by LiHaoTan** [comment]
@whipermr5 Hey it actually shows up.
https://search.maven.org/#artifactdetails%7Ccom.google.appengine%7Cappengine-api-1.0-sdk%7C1.9.54%7Cjar

Though the `gradle-appengine-plugin` is still on 1.9.53, I wonder if it's compatible.

https://github.com/GoogleCloudPlatform/gradle-appengine-plugin

**Comment by wkurniawan07** [comment]
If it's anything like [their previous 5 releases](https://github.com/GoogleCloudPlatform/gradle-appengine-plugin/blob/master/RELEASE_NOTES.md), there shouldn't be any problem.

On another note, that plugin is set for deprecation in favour of [this one](https://github.com/GoogleCloudPlatform/app-gradle-plugin).

**Comment by whipermr5** [comment]
Oh cool! I see it now. Maybe we should take this opportunity to migrate to the latest cloud tools library.

**Comment by whipermr5** [comment]
Hmm 1.9.53 seems to be incompatible with IntelliJ (I cannot add the application server - nothing happens after selecting the 1.9.53 SDK folder). 1.9.52 is fine though. @LiHaoTan can confirm this?

**Comment by LiHaoTan** [comment]
Hmm I can add it just fine?

**Comment by whipermr5** [comment]
> Though the gradle-appengine-plugin is still on 1.9.53, I wonder if it's compatible.

They just released 1.9.54 four days ago :D
