### ISSUE TITLE
Instructor: edit instructors: reflect changes to not-yet-joined instructor's visibility elsewhere in the system

### ISSUE THREAD

**Issue by HirdayGupta** [TEAMMATES/teammates#7537]
Noticed this while working on #4043 

In the Instructor Course Edit Page, any changes made to the visibility of an existing instructor are not reflected across the system.

**Environment:**
Most recently updated `master` branch

**Steps to reproduce:**
- Go to the edit course view (Courses -> Edit Course)
- Click edit instructor for any instructor in the course
- uncheck/check the `Display to students as` checkbox
- click save changes

Current Behaviour: A success message is displayed but the changes made to this instructor are not reflected anywhere in the app. The Instructor Course Edit UI still displays the old visibility selection and even in the student UI, on clicking `view team`, it is evident that the old visibility settings have remained unchanged.

Expected behaviour: Change the visibility of instructors as per the user's edit.

**Comment by wkurniawan07** [comment]
I cannot reproduce this. Could this be because of cached old JS code?

**Comment by HirdayGupta** [comment]
@wkurniawan07 Nope, I don't think its because of cached JS code. Running it with Chrome Console open and Disable Cache enabled. Ensured that I ran NPM run build after switching to master before running the dev server too. Am I missing anything to rule out cached code?

**Comment by HirdayGupta** [comment]
@wkurniawan07 UPDATE: just discovered that the described error occurs only if the instructor is yet to join the course. This being the case, should the expected behaviour change? Or is this still a bug that needs fixing?

**Comment by wkurniawan07** [comment]
Managed to reproduce. It is a bug.
@HirdayGupta I'll give you the challenge to find out the cause and fix it. (I've already known why)
