### ISSUE TITLE
Got problem while using checkstyle

### ISSUE THREAD

**Issue by dyugoaykol** [TEAMMATES/teammates#7540]
- **Operating System:Ubuntu 16.06**
- **JDK Version: 1.8.0_131**
- **Eclipse / IntelliJ Version (if applicable):Eclipse Java EE IDE  Neon.3 Release (4.6.3).**
- **Firefox / Chrome Version (where applicable):**

**What I was trying to do / What I need help with**
I'm setting up the static tool analysis. There were no problems when we clean the project. But upon following the guide at https://github.com/TEAMMATES/teammates/blob/master/docs/staticAnalysis.md#tool-stack, I m encouraged to run the Checkstyle and this is where I have been shown the following two errors. 

![problem with checkstyle](https://user-images.githubusercontent.com/16326855/27258431-c81e8224-5417-11e7-82b2-89a3ba750445.png)

**Attempts to resolve the problem**
I m unable to attempt anything . I'm relatively new to code standards and project itself. 

Note: I started the forking of project and related setup on May 15 and was able to setup IDE using this page ->https://github.com/TEAMMATES/teammates/blob/master/docs/ide-usage.md . I mentioned this because code may have been changed.

**Comment by whipermr5** [comment]
Have you pointed it to use our config file `teammates-checkstyle.xml`?

**Comment by HirdayGupta** [comment]
@whipermr5 I got the same thing on installing the check style plugin for Eclipse. I had pointed it to use the `teammates-checkstyle.xml`. As a temporary fix (since I rarely/never work with `/src/client`, I just changed the plugin settings to  only check files

**Comment by dyugoaykol** [comment]
Yes, I pointed it using the instructions mentioned at https://github.com/TEAMMATES/teammates/blob/master/docs/staticAnalysis.md#tool-stack; Following is the screenshots.
1. Adding the file to checkstyle.
![coding standard](https://user-images.githubusercontent.com/16326855/27258811-10ae0898-5422-11e7-882d-3b057d938675.png)
2. Enabling the standard.
![standart enabled](https://user-images.githubusercontent.com/16326855/27258824-5e9e5d1e-5422-11e7-9045-67d0c0aadb77.png)

**Comment by whipermr5** [comment]
@HirdayGupta @dyugoaykol Which version of the checkstyle plugin was installed?

**Comment by HirdayGupta** [comment]
@whipermr5 Mine is Eclipse Checkstyle Plugin 7.6.0.201703111252. Downloaded from the link in the help docs.

**Comment by whipermr5** [comment]
@dyugoaykol Can you press edit on the file set and screenshot the resulting dialog?

**Comment by whipermr5** [comment]
@HirdayGupta

From [the doc](https://github.com/TEAMMATES/teammates/blob/master/docs/staticAnalysis.md#version-numbers):

> The version number of all the tool stacks are declared in build.gradle or package.json.
>
> When downloading the plugin for Eclipse, find the plugin version that uses the correct version of the tool, e.g if CheckStyle 6.19 is used find an Eclipse plugin that uses CheckStyle 6.19 as well. If the exact version of the plugin cannot be found, using the latest version is allowed, however there is no guarantee that there will be no backward-incompatible changes.
>
> Conversely, when updating any tool, ensure that the tool version is supported by the Eclipse plugin, e.g when upgrading CheckStyle to 6.19 ensure that there is an Eclipse plugin which supports that version as well.

**Comment by dyugoaykol** [comment]
Sure , I was lazy. @whipermr5 . Here is the version.
![version](https://user-images.githubusercontent.com/16326855/27258887-a60f3604-5423-11e7-833f-786cc50ed4f1.PNG)

**Comment by whipermr5** [comment]
Do use version 6.19 as declared in [`build.gradle`](https://github.com/TEAMMATES/teammates/blob/81bc6820c5c22503ee6dd60ea081cb89968fc265/build.gradle#L19).

**Comment by dyugoaykol** [comment]
Great ! That resolved the problem. I also learned how to install the old version using manual methods. Thanks and Cheers !
