### ISSUE TITLE
CI Test error ?

### ISSUE THREAD

**Issue by nkshschdv** [TEAMMATES/teammates#7542]
- **Operating System: ubuntu 16.06**
- **JDK Version:1.8 **
- **Eclipse / IntelliJ Version (if applicable):**
- **Firefox / Chrome Version (where applicable):**

**What I was trying to do / What I need help with**
The CI Test fails and ended with the following error notifications as shown screen shot:
![ci error](https://user-images.githubusercontent.com/15321028/27264960-f97b9032-54a8-11e7-8d9f-864dfb9aae98.png)

what could be wrong with the CI Tests?

**Comment by whipermr5** [comment]
There's a problem with your setup, as shown by how the datanucleus class was not found. Run through `settingUp.md` and `ide-usage.md` again - you might have missed a step.

**Comment by HirdayGupta** [comment]
@nkshschdv I was getting a similar error in #7534. The solution for me was to run `./gradlew resetEclipseDeps`.

**Comment by nkshschdv** [comment]
What exactly does this command to the Eclipse ? I want to understand the cause .@HirdayGupta

**Comment by whipermr5** [comment]
You can find the exact steps [here](https://github.com/TEAMMATES/teammates/blob/81bc6820c5c22503ee6dd60ea081cb89968fc265/build.gradle#L498-L506).

**Comment by nkshschdv** [comment]
It did solved .However, the problem still persists. But it shows now similar but more errors. It tries to use my Firefox for selenium testing but of no use, nothing appeared on the browser.
The errors were enormous , Following i have attached screenshots as they appeared in sequence :
1. 
![1](https://user-images.githubusercontent.com/15321028/27273920-cf02d89c-54ee-11e7-943b-4106012ff8f8.png)
2.
![2](https://user-images.githubusercontent.com/15321028/27273949-e76a5f5e-54ee-11e7-8c78-6913df06d7bb.png)
3.
![3](https://user-images.githubusercontent.com/15321028/27273954-ede4f196-54ee-11e7-85c6-724eaf030668.png)
4.
![4](https://user-images.githubusercontent.com/15321028/27273962-f4d7688a-54ee-11e7-88fb-cf0bec89d129.png)

**Comment by whipermr5** [comment]
See #7437

**Comment by nkshschdv** [comment]
I'm following the steps for installation again .
I found out that , I have multiple JDK or JRE  Installed.as shown in screenshot below.
![jdk multiple name](https://user-images.githubusercontent.com/15321028/27316583-778e40d2-559e-11e7-8842-985cd5102151.png)
but i had set up JRE as java-oracle7 in eclipse. Is there any way to know that it is problem or not.Screen shot below
![hre in eclipse](https://user-images.githubusercontent.com/15321028/27316649-e08af8f0-559e-11e7-9dd4-ccb563fe34db.png)

**Comment by nkshschdv** [comment]
Well, adding the 1.7 openJDK in installled JRE section solved the problem Solved the problem.Belpw is the screen shot of current jdk, 
![solved tests](https://user-images.githubusercontent.com/15321028/27318670-5f9a5ba2-55ab-11e7-963c-4b017610dc18.png)
Now, CI Test is working. and only 5 and sometimes 6 test fails but the document says its okay. 
Thank You @whipermr5 @HirdayGupta .
cheers !
