### ISSUE TITLE
.travis.yml: downgrade to Precise image

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#7548]
Travis' upcoming update to their Trusty 14.04 images on Wednesday, 21 June 2017, 14:30 UTC will lead to an error in our build ([example](https://travis-ci.org/whipermr5/teammates/builds/244780974#L491)):
```
ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-7-oracle
```

This is due to https://github.com/travis-ci/travis-ci/issues/7884, with the root cause being that Oracle has stopped providing the binaries for JDK 7: http://www.webupd8.org/2017/06/why-oracle-java-7-and-6-installers-no.html

Solution considered: switch to OpenJDK 7. But the provided OpenJDK 7 has a bug that causes the gradle download to fail due to an SSL exception ([example](https://travis-ci.org/whipermr5/teammates/builds/244784881#L491)).

Solution considered: switch to Oracle JDK 8 and set source compatibility to 1.7. But the build consistently dies halfway through, with no output for 10 minutes ([example](https://travis-ci.org/whipermr5/teammates/builds/244870546#L2179)).

Seems like the only solution is to downgrade to Precise images instead of Trusty, which works fine ([example](https://travis-ci.org/whipermr5/teammates/builds/244853870)).

**Comment by wkurniawan07** [comment]
> Solution considered: switch to Oracle JDK 8 and set source compatibility to 1.7. But the build consistently dies halfway through, with no output for 10 minutes (example).

I can tell for sure that this is fixed in SDK 1.9.52, if it is going to affect your decision in any way. However this would necessitate all devs to use JDK 8 -- not that it is a bad idea.
