### ISSUE TITLE
InstructorFeedbacksPage: rename boolean methods 

### ISSUE THREAD

**Issue by sujeet14108** [TEAMMATES/teammates#7552]
`InstructorFeedbacksPage.java`:
Boolean methods `verifyHidden`, `verifyEnabled`, `verifyDisabled` and `verifyVisible` should be ranamed to `isHidden` , `isEnabled`, `isDisabled` and `isVisible` repectively as discussed in #7549

**Comment by narendravardi** [comment]
@damithc can i pick this up?

**Comment by leeyimin** [comment]
@narendravardi Please go ahead!

**Comment by MaddyThakker** [comment]
@damithc can I work on this issue? I have set up a local environment for the same. Thanks.

**Comment by mr2much** [comment]
I'm trying to work with this, but I'm having problem setting up the environment on IntelliJ IDEA, I cloned the repository and everything, but Graddle is giving me problems, it says that the 					https://repo1.maven.org/maven2 is not indexed, how do I solve this?
