### ISSUE TITLE
Student: submit responses: tweak info about Equal Share scale

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7557]
Current:
![image](https://user-images.githubusercontent.com/1673303/27373262-3437cba8-569a-11e7-8300-b1d3c81e3f89.png)

Suggested: 
More info about the 'Equal share' scale
OR 
More info about the _Equal share_ scale
OR 
More info about the `Equal share` scale

---

Current:
![image](https://user-images.githubusercontent.com/1673303/27373320-70f535d0-569a-11e7-8d7a-a3ff5b6e4afe.png)

Suggested:
>`Equal share` is a relative measure of individual contribution to a team task.
For example, in a 3-person team, 'equal share' means a third of the work done.
`Equal share + 10%` means the person did about 10% _more_ than an equal share, `Equal share - 10%` means about 10% _less_ than an equal share, and so on.

**Comment by adityavhegde** [comment]
Hi @damithc , I would like to work on this one. Re-confirming, the requirement, is something like below expected 
![image](https://user-images.githubusercontent.com/10449636/27383710-cd8d311c-56a9-11e7-888d-c47f86329b66.png)

**Comment by damithc** [comment]
> Re-confirming, the requirement, is something like below expected

@adityavhegde yes, that matches the first part of the requirement.

**Comment by adityavhegde** [comment]
@damithc Do have a look at these changes : 
![image](https://user-images.githubusercontent.com/10449636/27385004-b32d9fc8-56ae-11e7-82b2-9e2c46c509e6.png)

Should I go ahead with these texts, or do you suggest any alternatives ?

**Comment by damithc** [comment]
@adityavhegde Have a closer look at your text and the suggested text; there are small differences.

**Comment by adityavhegde** [comment]
@damithc thank you for pointing out. I guess I missed the word **task** on the first line and **a hyphen** between 3 and person. 
I also see you have used blocks around Equal Share. Do you suggest them being present, or did you just mean to stress it. 
I also introduced a new line between Equal share +10 and -10%, so that they have a better look and feel.  Am I still missing something ?

**Comment by damithc** [comment]
> I guess I missed the word task on the first line and a hyphen  between 3 and person.

Also, my version has only three sentences. Yours has four.

> I also see you have used blocks around Equal Share. Do you suggest them being present, or did you just mean to stress it.

Minimally, you should put single quotes around them to make them stand out. They need to stand out. Single quotes is the easiest way to set them apart from the rest. There are other ways, for example, using italics or `code formatting`. Whichever it is, use is consistently in both places (link as well as modal)

**Comment by adityavhegde** [comment]
@damithc how about using bold letters to highlight ? I believe, they stand out better. However, we would not want to have too many of them. 
What are your thoughts on this. Does this look like a lot of highlighting ?

![image](https://user-images.githubusercontent.com/10449636/27402074-0836cfa6-56e3-11e7-8c75-8b2edc7a10d4.png)

**Comment by damithc** [comment]
Out of these two options, I prefer italics. Our purpose is to make that part look different, not more important.
See if the [`<code>` tag](http://getbootstrap.com/css/#code) works.

**Comment by adityavhegde** [comment]
Using the code tag: 

![image](https://user-images.githubusercontent.com/10449636/27416891-eee571ec-572d-11e7-8fc6-eefadcff03c6.png)

**Comment by adityavhegde** [comment]
@damithc Should I open a PR with any of the above changes ?

**Comment by damithc** [comment]
> @damithc Should I open a PR with any of the above changes ?

@adityavhegde yes, go ahead. 

---

> @damithc Using the code tag. Is it semantically correct, to use the code tag ?

I guess it is ok. We often use the code tag to refer to text in the UI

**Comment by adityavhegde** [comment]
@damithc re-confirming, we go ahead with the code tag ?

**Comment by damithc** [comment]
> @damithc re-confirming, we go ahead with the code tag ?

Yes.
