### ISSUE TITLE
New contributor self intro Selvakumar Selvaraj

### ISSUE THREAD

**Issue by SELVAKUMAR-S** [TEAMMATES/teammates#7558]
App:
http://4-18-dot-teammates-selva.appspot.com/

Tinker Fork:
https://github.com/SELVAKUMAR-S/teammates/tree/tinker

UI Change:
Below screenshot shows my change, just switched the image (placed towards right)and corresponding text(placed towards left) positions in index.jsp
![teammates](https://user-images.githubusercontent.com/3601667/27373649-c2f95b22-5686-11e7-90df-2b6166b01d8b.png)

Self intro:
I am Selva, a Computer Science Undergraduate currently working as a software developer at athenahealth inc and my current projects doesn't deal with java and i want to be involved in java project and i have understanding of java through my college degree

Excited to work in teammates project !!!

**Comment by whipermr5** [comment]
Hey Selva, welcome to TEAMMATES! Good job setting everything up correctly! I see you've already submitted a PR for a `d.FirstTimers` issue; that's good! While waiting for it to be reviewed, feel free to take a look at `d.Contributors` issues if you're bored :)

**Comment by SELVAKUMAR-S** [comment]
Sure John, thanks!!!
