### ISSUE TITLE
New contributor self intro Shehan Erange

### ISSUE THREAD

**Issue by stanislous** [TEAMMATES/teammates#7562]
Hi.. I'm Shehan. I currently follow the Computer Engineering degree at the University of Peradeniya. I really interested in this open source project and follow the basic configuration settings. But while build in IntelliJ Idea, I got some errors.

Error:(5, 37) java: package teammates.common.datatransfer does not exist
Error:(13, 15) java: cannot find symbol
  symbol:   class DataBundle
  location: class teammates.test.cases.search.BaseSearchTest
/home/shehan/Documents/OSS Project/teammates/src/test/java/teammates/test/cases/BaseComponentTestCase.java
Error:(5, 30) java: package org.testng.annotations does not exist
Error:(6, 30) java: package org.testng.annotations does not exist
Error:(10, 37) java: package teammates.common.datatransfer does not exist
Error:(11, 48) java: package teammates.common.datatransfer.attributes does not exist
Error:(12, 48) java: package teammates.common.datatransfer.attributes does not exist
Error:(13, 48) java: package teammates.common.datatransfer.attributes does not exist
Error:(14, 48) java: package teammates.common.datatransfer.attributes does not exist
Error:(15, 48) java: package teammates.common.datatransfer.attributes does not exist
Error:(16, 48) java: package teammates.common.datatransfer.attributes does not exist
Error:(17, 48) java: package teammates.common.datatransfer.attributes does not exist
Error:(18, 48) java: package teammates.common.datatransfer.attributes does not exist
Error:(19, 34) java: package teammates.common.exception does not exist
Error:(20, 29) java: package teammates.common.util does not exist
Error:(21, 29) java: package teammates.common.util does not exist
Error:(22, 32) java: package teammates.logic.backdoor does not exist

So how do I fix it? Thank you in advance.

**Comment by whipermr5** [comment]
Hello Shehan, welcome to TEAMMATES! After fixing your setup, you can get started by fixing a `d.FirstTimers` issue, then move on to `d.Contributors` issues.

As for your setup, did you follow all the steps in [`settingUp.md`](https://github.com/TEAMMATES/teammates/blob/master/docs/settingUp.md) and [`ide-usage.md`](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-usage.md#intellij-idea) exactly?

**Comment by stanislous** [comment]
Hi whipermr, I followed all steps. But it did not work on Ubuntu. But it successfully worked on Windows. Therefore I will try my best to fix issues.

**Comment by whipermr5** [comment]
Did you do the automated set up or the manual set up?
