### ISSUE TITLE
Remove unused email html template for cleared pending comments

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#7564]
The email template `userEmailTemplate-pendingCommentsCleared.html` is no longer used in TEAMMATES so the file and its corresponding constant `Templates.EmailTemplates.USER_PENDING_COMMENTS_CLEARED` can be removed.

**Comment by wkurniawan07** [comment]
I knew I left something behind when doing #7334 😅

**Comment by SELVAKUMAR-S** [comment]
@leeyimin @wkurniawan07  shall i work on this as my first time task ? i have created self intro issue already

**Comment by leeyimin** [comment]
@SELVAKUMAR-S Go ahead 😄

**Comment by mr2much** [comment]
How can I contribute to this project?

**Comment by SELVAKUMAR-S** [comment]
Is that a practice that one person should work only on one d.FirstTimers issue? I have already created a PR for another d.FirstTimers issue. So I will leave this to other first time contributors if that is required

**Comment by HirdayGupta** [comment]
>Is that a practice that one person should work only on one d.FirstTimers issue?

@SELVAKUMAR-S yes, that is a practice we follow here at TEAMMATES, so if you have already created a PR for a `d.FirstTimers` issue then leave this one for other new contributors.

@mr2much please read our [orientation guide](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md#orientation-task-list) to find out how you can get started contributing to TEAMMATES! If you need any assistance, search the issue tracker to check if your question has already been answered or create a  new issue and someone will help you out 😄
