### ISSUE TITLE
Use diamond constructor for Lists and Maps

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#7593]
```java
// Variant 1
List<String> list = new ArrayList<String>();

// Variant 2
List<String> list = new ArrayList<>();
```
Both variants resolve to the same runtime behavior but variant 2 is more concise and does not necessitate duplication of parameter type.

**Comment by sujeet14108** [comment]
Can i take this?

**Comment by LimeTheCoder** [comment]
hi, @sujeet14108, I want to take it too. In Intellij Idea need just 2 clicks to fix this issue.
