### ISSUE TITLE
issues.md: update labels list

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#7595]
The following labels were decommissioned:
- `c.Enhancement`, `c.Story`, `c.Task`

The following labels were added:
- `a-Storage`: database schema, GAE datastore
- `f-Questions`: features related to specific question types
- `f-Sessions`: feedback session creation, editing
- `f-Website`: front page, product website
- `t-Java`: Java-related technologies, e.g. language syntaxes

The following labels need to adapt in lieu of the added labels:
- `a-Persistence`: eventual consistency, CRUD operations
- `f-Submissions`: feedback submissions
- No `t-*` label: usually documentation update, or mixture of many languages

**Comment by ihsavru** [comment]
Hello! I am new here. I would like to work on this issue. What description do I provide of these labels?

**Comment by Surya-06** [comment]
How can I get started with contributing to the issue mentioned above ?

**Comment by wkurniawan07** [comment]
I have updated the issue description with the suggested descriptions.

**Comment by Surya-06** [comment]
@wkurniawan07 Have updated the issues.md with the details given . Hope I helped :-)

**Comment by wkurniawan07** [comment]
@Surya-06 you need to submit a pull request if you want your works to be considered.

**Comment by Surya-06** [comment]
@wkurniawan07  I have created a pull request of the fork which I have modified with the details given by you. I have also posted the details of the stuff which I changed along with the pull request just a few minutes before the previous message . Will it be considered ?
