### ISSUE TITLE
Use enum instead of string for gender field in StudentProfileAttributes and related classes

### ISSUE THREAD

**Issue by LimeTheCoder** [TEAMMATES/teammates#7603]
Replace 'gender' field with corresponding enum for StudentProfileAttributes and related classes.
Currently gender field is String that only accepts "male", "female" or "other" values, so It's better to use enum over String value in that case.

**Comment by ParmaarK** [comment]
can I take this?

**Comment by shivakrishna9** [comment]
@whipermr5 I will do this :)

**Comment by Surya-06** [comment]
@shivakrishna9  Are you taking this issue ?? else would you let me do it ..

**Comment by arjunsuri** [comment]
<%@ tag description="studentProfile - Edit profile div" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ tag import="teammates.common.util.Const" %>
<%@ attribute name="profile" type="teammates.ui.template.StudentProfileEditBox" required="true" %>
<%@ attribute name="sessionToken" required="true" %>
<c:set var="MALE" value="<%= Const.GenderTypes.MALE %>" />
<c:set var="FEMALE" value="<%= Const.GenderTypes.FEMALE %>" />
<c:set var="OTHER" value="<%= Const.GenderTypes.OTHER %>" />
<div id="editProfileDiv" class="well well-plain well-narrow well-sm-wide">
    <h3 id="studentName">

where is the declaration of var in studentProfileDiv.java? I hope I am checking the correct java file. In this issue, it is said that var is of String datatype but I am not able to figure out where is var declared String?

**Comment by LimeTheCoder** [comment]
teammates.ui.controller.StudentProfileEditSaveAction#extractProfileData
55 line

**Comment by rajujha373** [comment]
i dont know weather have i done correctly,,, please help

**Comment by whipermr5** [comment]
@rajujha373 You can submit a PR for us to take a look :)

**Comment by gaurav122197** [comment]
@LimeTheCoder @whipermr5, Is this issue still open?

**Comment by LiHaoTan** [comment]
@gaurav122197 someone else is currently working on this in #8208, I suggest you pick another issue :).
