### ISSUE TITLE
InstructorHelp: Lot of useless code should be deleted

### ISSUE THREAD

**Issue by amarlearning** [TEAMMATES/teammates#7604]
In the instructor's help page, If you just search for `display: none;` the count will be around 17. I checked manually and found out that all of them remain hidden throughout so it's better to remove that.

Such as line [this](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/partials/instructorHelpSessions.jsp#L969), [this](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/partials/instructorHelpSessions.jsp#L994), [this](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/partials/instructorHelpSessions.jsp#L1273), [this](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/partials/instructorHelpSessions.jsp#L3052) and many more.

**Comment by whipermr5** [comment]
I'm not sure this is an issue as the instructor help page should mirror the actual UI elements exactly, including hidden elements. I feel it's not worth the effort to manually go through the HTML and remove the hidden elements.

Besides, we need to explore a more maintainable solution where we extract the UI elements out into `.tag` files to be included inside the instructor help page and populated with dummy data. That way, we won't have to keep updating the instructor help page when the UI elements change.

**Comment by amarlearning** [comment]
> I'm not sure this is an issue as the instructor help page should mirror the actual UI elements exactly, including hidden elements.

@whipermr5 I think all the hidden elements showed be removed since we don't have any kind of JS enabled in the InstructorHelp page. so there is no point in adding code line that would just increase the file size and do nothing and there will be no visible changes seen in the UI element of InstructorHelp page which would make them differ from the UI elements present in different pages.

**Comment by whipermr5** [comment]
@amarlearning It's the additional effort required that I'm against, as it's quite unnecessary. I feel the decrease in file size isn't substantial and does not justify the effort. Also, it's a temporary problem that'll go away when we use `.tag`s, so it's not worth it to fix it now.

**Comment by wkurniawan07** [comment]
No longer relevant as components in help page in V7 are directly created from the original component.
