### ISSUE TITLE
New contributor self intro Tanya Pascal aka josephine

### ISSUE THREAD

**Issue by josephinex** [TEAMMATES/teammates#7617]
1. Link to my fork  https://github.com/josephinex/teammates
2. ![screenshot at 2017-06-27 12-10-18](https://user-images.githubusercontent.com/6609602/27580037-2b57a71e-5b32-11e7-8cc5-5982df4e0d33.png)
3. So, my name is Tanya Pascal and I'm an IT student and entry level Java developer. I have very little experience in programming and this is the first time I'm going to contribute to a project on github. In the past though I worked as a front end web developer, but now I want to focus on backend in Java. I chose teammates because it's student friendly and there are issues for beginners to fix and I think it's a good project to learn from. Two personal things I want to accomplish while contributing : to develop attention to details and to write good code. I will try to do my best and not to provoke any hard feelings :)
Thanks!

**Comment by whipermr5** [comment]
Hey Tanya, welcome to TEAMMATES! Good job setting up the dev server correctly. You can get started by working on a `d.FirstTimers` issue, then move on to `d.Contributors` issues :)

A question: should you submit a PR that gets merged, would you like to be credited in our [about page](http://teammatesv4.appspot.com/about.jsp) as `Tanya Pascal` or `Tatiana Pascal` as per your GitHub profile?

**Comment by josephinex** [comment]
Hi, as Tatiana Pascal, I think. Thanks!
