### ISSUE TITLE
instructorFeedbackEdit.es6: Remove unwanted space

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7621]
Near [line 122](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/dev/js/main/instructorFeedbackEdit.es6#L122) of `instructorFeedbackEdit.es6`, a line begins with a space -

``` js
 } from '../common/visibilityOptions.es6';
```

Change this to -

``` js
} from '../common/visibilityOptions.es6';
```

(Remove space in the beginning)

**Comment by MiHawkStackOverFlow** [comment]
is this still open ?

**Comment by VamsiSangam** [comment]
@MiHawkStackOverFlow , someone else is working on this issue, feel free to work on other [a.FirstTimers](https://github.com/TEAMMATES/teammates/labels/d.FirstTimers) issue. :smile:

**Comment by davel37** [comment]
It looks like all the d.FirstTimers issues are tied up at the moment. I guess we'll wait till new issues arise.:smile:

**Comment by damithc** [comment]
> It looks like all the d.FirstTimers issues are tied up at the moment. I guess we'll wait till new issues arise.😄

@davel37 here's a new `firsttimers` issue #7696

**Comment by arjunsuri** [comment]
hey I also want a new d.FirstTimers issue....Please suggest me one as well.

**Comment by VamsiSangam** [comment]
Hi @arjunsuri ! You can take up #7706 . Although it doesn't have a `d.FirstTimers` label assigned yet, I'm pretty confident that it has the same level of difficulty as that of a `d.FirstTimers` issue. :smile:

**Comment by arjunsuri** [comment]
I will surely look into that
