### ISSUE TITLE
Instructor: view student list: add icons to buttons

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7628]
Suggestion:
Add suitable icons to these three buttons. In addition, we can style the `Delete All` button in red.

![image](https://user-images.githubusercontent.com/1673303/27632864-9de5010c-5c2f-11e7-9eac-6e45003d2aa0.png)

**Comment by adityavhegde** [comment]
Taking this one.

**Comment by stanislous** [comment]
@damithc, For the time being, I have changed the particular file and it worked successfully. But it didn't pass the checks. Therefore do I need to change the particular test files too?

![screenshot 388](https://user-images.githubusercontent.com/20964806/27762395-f62eae92-5e8e-11e7-95b5-827fc7aad62a.png)

**Comment by damithc** [comment]
> Therefore do I need to change the particular test files too?

Yes

**Comment by damithc** [comment]
Another thing: for the 'remind' button, may be use the envelope icon?

**Comment by arjunsuri** [comment]
Is this still open?
