### ISSUE TITLE
Remove unused comments-related constants and classes

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#7643]
The constants `Tooltips.COURSE_EMAIL_PENDING_COMMENTS`, `StatusMessage.COMMENT_CLEARED`, `StatusMessage.COMMENT_CLEARED_UNSUCCESSFULLY`, and `ActionURIs.INSTRUCTOR_STUDENT_COMMENT_CLEAR_PENDING` in the `Const` class are no longer used in TEAMMATES, so they can be removed.

Doing the above necessitates the removal of `getInstructorStudentCommentClearPendingLink()` in the `PageData` class as well - this method is not used anywhere else.

**Comment by wkurniawan07** [comment]
I did a backtrack and found out quite a lot of leftovers that I missed in #7334 (much more than what the issue description describes). I'll take responsibility here; we're not currently lacking in `d.FirstTimers` issue anyway.
