### ISSUE TITLE
Migrate development tools to Google Cloud SDK

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#7648]
The development tool stack currently used by us (App Engine SDK, Gradle App Engine Plugin, Google Plugin for Eclipse, Datanucleus for enhancement) is deprecated by Google in favour of Google Cloud SDK and Objectify. One of them has been fixed (kudos @whipermr5!), so the rest should follow suit soon. ~~This will also ease the migration to Java 8 by a significant margin.~~ Edit: I have determined that the SDK and Java 8 are independent.

- [x] [CLI/Gradle](https://cloud.google.com/appengine/docs/standard/java/tools/migrate-gradle)
- [x] [Eclipse](https://cloud.google.com/eclipse/docs/)
- [x] [IntelliJ](https://cloud.google.com/tools/intellij/docs/migrate)

**Comment by wkurniawan07** [comment]
Just to update progress, this is currently blocked by <https://issuetracker.google.com/issues/63732823>.

**Comment by lzzhaha** [comment]
Please update the IDE information page concerning the plugin  downloading issue

**Comment by whipermr5** [comment]
@lzzhaha What issue are you referring to? Anyway, the work for this has been done in the [`teammatesv6` branch](https://github.com/TEAMMATES/teammates/tree/teammatesv6) (do check if your issue has been resolved there). We have yet to release it as we're waiting to see how [this issue](https://issuetracker.google.com/issues/68206731) develops, so you won't see the changes on the `master` branch yet.

**Comment by lzzhaha** [comment]
I mean in that orientation page we are advised to install Google plugin which is deprecated. So I wonder whether I should keep installing that or install Google Cloud SDK instead. Thanks!

**Comment by whipermr5** [comment]
I believe it has already been fixed ([link](https://github.com/TEAMMATES/teammates/blob/teammatesv6/docs/ide-usage.md)).

**Comment by lzzhaha** [comment]
Thank you very much! I have been looking at a wrong page.

**Comment by wkurniawan07** [comment]
@lzzhaha to clarify, if you wish to set up now, you still need to download the older Google plugins for Eclipse/IntelliJ. If you want to wait for a week or so (hopefully I can release the change by this weekend), then you can follow the new setup instructions.
Alternatively (not advised), you can set up under the `teammatesv6` branch and use the more updated plugins for Eclipse/IntelliJ without having to wait.
