### ISSUE TITLE
FeedbackRankRecipientsQuestionDetails: show all columns regardless of recipient type

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#7652]
Currently, self-rank excluded statistics is used when the recipient type of the question is NONE or SELF, but ranking recipient questions for NONE or SELF are unlikely to be used. Thus, `shouldSelfBeExcludedFromRankings` should be removed and all columns should be shown regardless of recipient type.

**Comment by damithc** [comment]
@leeyimin I wonder if showing that column in all cases is an easier route. Would that make the code simpler? It doesn't affect the accuracy of the statistics, right?

**Comment by leeyimin** [comment]
@damithc It does make the code simpler and the accuracy should not be affected. Should I change the issue to show all columns instead?

**Comment by damithc** [comment]
> Should I change the issue to show all columns instead?

Yes, I guess that will make our life easier. Sometimes the lazy route is the better one :-p
