### ISSUE TITLE
New contributor self intro Sie Huai

### ISSUE THREAD

**Issue by huai99** [TEAMMATES/teammates#7661]
App: 
https://teammates-siehuai.appspot.com/

Fork:
https://github.com/huai99/teammates

Screenshot on UI changes
![image](https://user-images.githubusercontent.com/26456025/27762452-1130bf8a-5ea5-11e7-8379-3b6bf7d976f9.png)

What I have done to the UI is just implementing the hover behavior for the login button, it will change the background to white and the color of the wording to dark green when the user hovers over the button.

Self-intro:
Hi guys, my name is Sie Huai and I am an electrical and electronic engineering student studying in Singapore. I have develop an interest in programming and eagerly looking for places to brush up my skill and contribute. Teammates seems to be an interesting project with strict and good software practices being enforced, I hope to learn from you guys ! Happy coding :)

**Comment by whipermr5** [comment]
Hey Sie Huai, welcome to TEAMMATES! Good job setting everything up correctly! You can get your feet wet by working on a `d.FirstTimers` issue, then move on to `d.Contributors` issues :)
