### ISSUE TITLE
instructorFeedbackResults.es6: fix typo

### ISSUE THREAD

**Issue by HirdayGupta** [TEAMMATES/teammates#7664]
In the file [`teammates/src/main/webapp/dev/js/common/instructorFeedbackResults.es6`](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/dev/js/common/instructorFeedbackResults.es6), on lines 153 and 154, `isButtonInExpandMode` is mistakenly written as `isButtonInExapandMode`.

**Comment by damithc** [comment]
@HirdayGupta what's the impact? Just a typo or affects behavior?

**Comment by HirdayGupta** [comment]
@damithc just a typo as far as I can tell. I thought it would make a good d.FirstTimers issue.
