### ISSUE TITLE
New contributor self intro Ladislav Jaroscak

### ISSUE THREAD

**Issue by enaru** [TEAMMATES/teammates#7666]
My fork:
https://github.com/enaru/teammates

Screenshot of UI change:
![screenshot_teammates](https://user-images.githubusercontent.com/29780186/27770532-9413b8a8-5f40-11e7-96fd-29d77c8fc393.png)

For UI change I changed border for the login buttons.

Hello, my name is Ladislav Jaroscak. I'm student of computer science in Slovakia. I have always enjoyed programming, writing algorithms, solving computably difficult problems. I haven't got much experience in actual software projects though. Teammates looks like a good place to learn new set of skills. I'd be happy if I could be of any help one day.

**Comment by whipermr5** [comment]
Hey Ladislav, welcome to TEAMMATES! Good job setting up the dev server correctly. You can get started by working on a `d.FirstTimers` issue, then move on to `d.Contributors` issues :)
