### ISSUE TITLE
Include src/test/resources/**/*.html in lintspaces config

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#7670]
When these files are edited manually instead of using GodMode, whitespace violations such as missing newline at the end of the file can be introduced without being caught by CI, leading to future unrelated changes when the same files are updated using GodMode (see https://github.com/TEAMMATES/teammates/pull/7634#discussion_r125002435).

A separate lintspaces config might be needed for these files as the current one also enforces a maximum of one newline between blocks, no trailing spaces and no tab characters. Need to investigate whether it is feasible to enforce these checks on the test HTML files.

**Comment by wkurniawan07** [comment]
No longer relevant as V7 removes all HTML comparisons in E2E tests.
