### ISSUE TITLE
New contributor self intro David Laffey

### ISSUE THREAD

**Issue by davel37** [TEAMMATES/teammates#7693]
a)Based in Spain and therefore not entitled to an individual GAE account (only entitled to the business account)

b)https://github.com/davel37/teammates/tree/tinker

c)
![screenshot 172](https://user-images.githubusercontent.com/18369575/27902741-08d61192-6237-11e7-8714-4c57e92543ab.png)

Just some small changes made to the terms of use page using Bootstrap Jumbotron.

My name is David Laffey, originally from Ireland but based in Valencia, Spain. I studied Maths and Computers in NUI Galway, and last year completed a Postgraduate in Software Engineering from the same University. Looking to get involved in some Open Source Projects and Teammates looks like a perfect place to start!.

**Comment by whipermr5** [comment]
Hey David, welcome to TEAMMATES! The changes look good 👍 You can get your feet wet by working on a `d.FirstTimers` issue, then move on to `d.Contributors` issues :)
