### ISSUE TITLE
Update user map for June 2017

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7696]
Follow #7215 and similar.
New data to consider:

Country|Institute
-- | --
Australia | Carey Baptist College
Australia | Monash University
Australia | University of Canberra
Australia | University of South Australia
Australia | University of Western Australia
Belgium | KU Leuven
Brazil | AEDB
Brazil | The State University of Londrina
Brazil | UNESP
Brazil | Universidade Católica de Brasília
Brazil | Universidade de São Paulo
Canada | College de Bois-de-Boulogne
Canada | St. Barbara Catholic Elementary School
Colombia | Universidad del Norte
Colombia | Universidad del Norte
Costa Rica | Colegio Calasanz Hispanocostarricense
Estonia | Oneself Limited
Estonia | Tartu University Pärnu college
France | EMLYON Business School
France | IESEG School of Management
Germany | TU Munich
India | IIIT, Allahabad
India | Payilagam
Malaysia | International University of Malaya-Wales
Malaysia | Universiti Putra Malaysia
Mexico | CETYS Universidad
Mexico | Lemon Three
Mexico | UDLAP
Nederlands | Hogeschool van Amsterdam
Netherlands | Eindhoven University of Technology
Netherlands | University of Twente
New Zealand | Eastern Institute of Technology
New Zealand | Massey University
New Zealand | Massey University
New Zealand | Queen's High School
New Zealand | The University of Auckland
Philippines | Oneself Limited
Portugal | School of education Porto
Russia | Higher School of Economics
Singapore | MCI Group
Singapore | SHATEC Institutes
Singapore | Singapore Institute of Technology
Singapore | Singapore Polytechnic
Singapore | St. Joseph's Institution
South Korea | SUNY Korea
Spain | Cooke e-learning
Spain | Universidad de Barcelona
Spain | University of Barcelona
Switzerland | Pädagogische Hochschule St. Gallen
Taiwan | Chung-Yuan Christian University
Turkey | Kredi Akademi
UK | Brunel University
UK | Hult International Business School
UK | University College London
USA | Arizona State University
USA | Carnegie Mellon University
USA | College America
USA | Colorado State University
USA | Delaware Technical Community College
USA | Flagship Computing
USA | Grand Valley State University
USA | Hult Business School
USA | Illinois State University
USA | Johns Hopkins University
USA | Kennesaw State University
USA | Medical College of Wisconsin
USA | Medical College of Wisconsin
USA | Morgan County Charter School System
USA | Morgan County Middle School
USA | NC State University
USA | NC State University
USA | Nichols College
USA | Noncommsioned Officer Academy at the USAJFKSWCS
USA | Northeastern University
USA | NYU Stern
USA | Phillip & Sala Burton Academic High School
USA | Portland State University
USA | Regis University
USA | Regis University
USA | Southern Illinois University Edwardsville
USA | UNC - Chapel Hill
USA | University at Albany, SUNY
USA | University of California, Irvine
USA | University of Dallas
USA | University of Georgia
USA | University of New Hampshire

**Comment by davel37** [comment]
Hello!. I would like to take this issue.

**Comment by chowyb** [comment]
@davel37 sure! Feel free to submit a pull request for this issue :)

**Comment by davel37** [comment]
Perfect! I'm out of the flat and away from computers (work related) all day. When I get back to the flat tonight I'll create the pull request.

**Comment by arjunsuri** [comment]
hey! I would also like to take this issue.
