### ISSUE TITLE
Fix browser tests that fail on Chrome

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#7699]
Even though we [support Chrome](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#using-chrome), 3 browser tests are failing, namely:
```
AdminEmailPageUiTest
InstructorFeedbackEditPageUiTest
InstructorFeedbackResultsPageUiTest
```

**Comment by damithc** [comment]
After fixing these, perhaps we can set appveyor to use chrome instead of firefox? :-p
