### ISSUE TITLE
New contributor self intro Bicheng Xu

### ISSUE THREAD

**Issue by uxxSam** [TEAMMATES/teammates#7704]
Link to my app:
https://teammates-samxu.appspot.com/

Link to my fork:
https://github.com/uxxSam/teammates

Screenshot of change on the UI:
![uichange](https://user-images.githubusercontent.com/27687790/27983047-1b6f5ccc-63e6-11e7-9a61-d0329b347f4d.jpeg)
I added hover effects on the login buttons. 

Intro:
Hi guys, my name is Bicheng Xu. I am a student of Computer Science at Northeastern University in the U.S. I enjoy writing web applications and solving problems. I have worked on a few smaller projects by myself and would like to learn more from open-source and complicated projects like Teammates. I wish my contribution will help make this project even better.

**Comment by whipermr5** [comment]
Hey Bicheng, welcome to TEAMMATES! Good job setting everything up correctly! You can get your feet wet by working on a `d.FirstTimers` issue, then move on to `d.Contributors` issues :)
