### ISSUE TITLE
Instructor: download results: multiple repetition of header bug

### ISSUE THREAD

**Issue by LimeTheCoder** [TEAMMATES/teammates#7707]
In CSV results file, header repeats before each row with response instead of appearing only once at the beginning.

![image](https://user-images.githubusercontent.com/8873908/27988998-0f5eb372-6438-11e7-8152-beee4577d6cf.png)

**Comment by LimeTheCoder** [comment]
Probably, side-effect of changes introduced in #7555

**Comment by damithc** [comment]
@Mynk96 can confirm the bug?

**Comment by damithc** [comment]
If the bug is confirmed, need to be fixed before next release. Also, how come it is not caught by existing tests?

**Comment by Mynk96** [comment]
@damithc @LimeTheCoder Well, the idea was to check each response for comments from the instructor's and add a header correspondingly.
The other approach was to get the maximum number of comments for response and then add a header, but as the screenshot in PR #7711 shows that would have left unnecessary blank cells or a text as "No comment" if there were no comments for responses.

**Comment by damithc** [comment]
> The other approach was to get the maximum number of comments for response and then add a header, but as the screenshot in PR #7711 shows that would have left unnecessary blank cells or a text as "No comment" if there were no comments for a particular response.

Empty cells is WAY more acceptable than repeating header rows :-p

This behavior is already visible in [one of your comments](https://github.com/TEAMMATES/teammates/pull/7555#issuecomment-311430741). I should have detected it back then. Sorry about that. Anyway, need to fix before next release.

**Comment by LimeTheCoder** [comment]
@Mynk96 @damithc So It's was intended behaviour? Duplicate header before each row of responses is redundant, not obvious for users, time and space consuming and finally makes overall information hardly-readable. I think in that case better to use the second approach with only one header generated according to a maximum number of comments per response. See #7711. I don't think, that rows with blank cells are important in that case. In our results CSV file there many examples of blank cells.

**Comment by whipermr5** [comment]
@thenaesh This needs to be fixed before V5.109 can be released.
