### ISSUE TITLE
Instructor: remove unnecessary unboxing of Boolean value

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#7716]
In the `return` statement of `isDisplayedToStudents` in Instructor.java, the `Boolean` variable `isDisplayedToStudents` can be returned directly without unboxing it.

**Comment by Surya-06** [comment]
@leeyimin  Hi ! Can i take up this issue ??

**Comment by leeyimin** [comment]
@Surya-06 Sure, go ahead 😄

**Comment by Surya-06** [comment]
@leeyimin By unboxing you meant that it can be returned directly without calling the booleanValue function right??

**Comment by leeyimin** [comment]
Yes 😄

**Comment by Surya-06** [comment]
@leeyimin  i have changed it , could u please have a look at it...

**Comment by leeyimin** [comment]
@Surya-06 Sorry, I did not notice earlier that you have already completed a first timer issue. Please take a look at d.Contributors issues instead!

**Comment by Surya-06** [comment]
@leeyimin  Oh , all right i will take a look .

**Comment by suleymantekin** [comment]
Hi, can I do this change, please?

**Comment by rajujha373** [comment]
I have submitted the pull request. don't know weather i have done right... any help will be appreciated :)
