### ISSUE TITLE
Instructor: response comments: fix misalignment of edit/delete buttons

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#7719]
For comments on InstructorFeedbackResultsPage and InstructorStudentRecordsPage, the edit and delete buttons can be out of line if the comment details are long enough.

![push](https://user-images.githubusercontent.com/7546744/28008608-d7068dac-658a-11e7-8794-f158103497c6.png)

**Comment by stanislous** [comment]
Can I take this issue?

**Comment by HirdayGupta** [comment]
Working on this
