### ISSUE TITLE
AdminLogQueryTest: Fix numeric overflow in expression

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#7722]
`22 * 365 * 24 * 60 * 60 * 1000` causes an overflow as int-32 multiplication is used (See https://stackoverflow.com/questions/1494862/multiplying-long-values). This can be fixed by using [Calendar](https://docs.oracle.com/javase/7/docs/api/java/util/Calendar.html#add(int,%20int)) method.

**Comment by josephinex** [comment]
If you don't mind, I can work on this issue. Thanks!

**Comment by josephinex** [comment]
Seems like it has been done by someone else?

**Comment by leeyimin** [comment]
#7738 is closed and has not fixed the issue 😄

**Comment by josephinex** [comment]
@leeyimin so, shall I take another issue then?

**Comment by chowyb** [comment]
@josephinex there's no need to, as this issue is still up for grabs :)

**Comment by josephinex** [comment]
@chowyb , I asked because I thought @sanjeevbitx is gonna work on this.

**Comment by sanjeevbitx** [comment]
@josephinex ,You can continue on this.
