### ISSUE TITLE
InstructorFeedbackResultsPageUiTest: Fix false positive assertion

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#7723]
In `testDownloadAction()`, there is a line: `assertFalse(reportUrl.equals(afterReportDownloadUrl));`. However, `reportUrl` is an AppUrl, `afterReportDownloadUrl` is a String, `equals` for AppUrl is not overridden. Thus, the expression is always false, even if both string expression could be the same.

**Comment by keerthikorivi** [comment]
Hi @leeyimin,

Can i work on this issue?

**Comment by leeyimin** [comment]
@keerthikorivi Go ahead :)

**Comment by keerthikorivi** [comment]
Hi,

Could you please point me to the project setup guide if there is any? 

Thanks,
Keerthi Korivi

**Comment by damithc** [comment]
> Could you please point me to the project setup guide if there is any?

@keerthikorivi it's somewhere in our developer documentation. Try to find it yourself. :-)

**Comment by keerthikorivi** [comment]
Thanks!

**Comment by AlexM9200** [comment]
Can I take this? It's been a 25 days and it hasn't been fixed by keerthikorivi.

**Comment by whipermr5** [comment]
@AlexM9200 Sure!
