### ISSUE TITLE
FeedbackRankRecipientsResponseDetails: Refactor getAnswerCsv

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#7724]
`getAnswerCsv` can be simplified by removing the use of `StringBuilder`.

**Comment by ahsanbagwan** [comment]
I would like to take this up. However, I'm not understanding why the method has an unused parameter. Is it expected to return `answer` as is?

**Comment by arjunsuri** [comment]
is this issue still open?

**Comment by LiHaoTan** [comment]
@arjunsuri Please don't go around everywhere asking if the first timer issues are still open.  Whether the issues are available are no longer relevant to you. Please read the `README` if you haven't done so.
