### ISSUE TITLE
Admin: create instructor: enhance current tests to check for success and fail status when adding instructor

### ISSUE THREAD

**Issue by LiHaoTan** [TEAMMATES/teammates#7728]
The tests currently do not check the status when adding the instructor.

This may result in a status of a fail when adding an instructor is successful.

See regression: https://github.com/TEAMMATES/teammates/pull/7484

**Comment by miderleta** [comment]
Is this still a valid issue?

**Comment by wkurniawan07** [comment]
This is properly done in V7.
