### ISSUE TITLE
Constants: Sync frontend and backend constants

### ISSUE THREAD

**Issue by LiHaoTan** [TEAMMATES/teammates#7731]
The current approach involves copy pasting of constants from `Const.java` to `const.js` and is error prone since we are essentially repeating code.

See: [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)  for more information.

**Comment by Surya-06** [comment]
@LiHaoTan  Hey could I take up this issue??

**Comment by whipermr5** [comment]
@Surya-06 You are always free to, but do read this first: [issues.md#difficulty-level-d](https://github.com/TEAMMATES/teammates/blob/master/docs/issues.md#difficulty-level-d)

**Comment by Surya-06** [comment]
@whipermr5 Just gone through it , seems like the issue is for commiters and not contributors.

**Comment by wkurniawan07** [comment]
The only way I can think to solve this is using `.properties` file. Java can read this easily and Webpack has loaders which can load `.properties` file into JS objects, JSON or otherwise.

**Comment by Shashwat-Garg** [comment]
Hello, I am new to open source. I would like to work on this issue, but I can't find the const.es6 file.
Please direct me. :)
