### ISSUE TITLE
InstructorAttributes: Check validity for instructor role

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#7734]
Currently, Instructors are able to change the value of instructor role to one which is not well defined through editing the post requesting manually. A validity check can be added to prevent that from happening.

**Comment by damithc** [comment]
I've lowered the priority because this is a 'garbage in, garbage out' situation. i.e. I'm assuming the user's deliberate misuse of the feature will hurt the user but not us. If it hurts us, we should up the priority. :-)
