### ISSUE TITLE
Rename staticAnalysis.md -> static-analysis.md

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#7742]
For consistency with the way the other documents are named. Also involves updating links to it in the other documentation files, if any.

**Comment by SimonOsipov** [comment]
Am i right, this issue is closed?

**Comment by mpek6d** [comment]
Could I take this one?

**Comment by lazy-sunshine** [comment]
I resolved the issue,please merge the PR

**Comment by whipermr5** [comment]
@lazy-sunshine Please follow our conventions first as linked by the bot :)

**Comment by lazy-sunshine** [comment]
Made changes according to the conventions
