### ISSUE TITLE
Remove `appengineStop` task from CI build scripts

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#7743]
I don't see the need to run `appengineStop` since the entire VM is destroyed after the build completes anyway. The task adds an unnecessary 10 seconds to the build time.

To fix, remove [these lines](https://github.com/TEAMMATES/teammates/blob/38b810a566559cf1d84094cdad08ebca5e78a436/.travis.yml#L55-L57) from `.travis.yml` and [these lines](https://github.com/TEAMMATES/teammates/blob/38b810a566559cf1d84094cdad08ebca5e78a436/appveyor.yml#L32-L34) from `appveyor.yml`.

**Comment by shivakrishna9** [comment]
@whipermr5 Can I work on it? Or is it assigned to anybody?

**Comment by whipermr5** [comment]
@shivakrishna9 Go ahead! :)
