### ISSUE TITLE
Disable JavaScript caching for Firefox: property not found

### ISSUE THREAD

**Issue by amarlearning** [TEAMMATES/teammates#7744]
Under the [Firefox section](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#using-firefox) in the [development.md](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md) file replace the `network.http.use-cache` with `browser.cache.disk.enable`.

**Comment by whipermr5** [comment]
Oops; didn't see this before creating #7745 😅 I'll leave that one open instead as the instructions are different (instead of replacing, both should be kept as I believe the older key is for older versions of Firefox e.g. 38, which we do support). Thanks for the report!
