### ISSUE TITLE
development.md: update instructions for disabling Firefox cache

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#7745]
The key `network.http.use-cache` is for older versions of Firefox and cannot be found in Firefox 46.

The [instructions](https://github.com/TEAMMATES/teammates/blob/b65f1ab5110302b49e5affc04090ee652e320359/docs/development.md#using-firefox) should be updated to also include `browser.cache.disk.enable` which is found in newer versions of Firefox. Note: both keys should be included because the older key is used in older versions of Firefox.

**Comment by marboleda** [comment]
Hi, I am interested in working on this issue.
