### ISSUE TITLE
New Contributor Self Intro: Marco Arboleda

### ISSUE THREAD

**Issue by marboleda** [TEAMMATES/teammates#7750]
- **Link to my fork:** https://github.com/marboleda/teammates

**Screenshot of changes made (as seen on the UI)**

![intro](https://user-images.githubusercontent.com/30060106/28129608-edb4dae0-6701-11e7-8872-e5c50352d587.png)

I changed the color of the text "Student peer evaluations..." from orange to blue.

**Short self-introduction**
Hi, my name is Marco and I just graduated with a degree in Computer Science and Mathematics. Since I literally finished school less than a month ago, I am still in the process of looking for a job. However, I have had previous experience working as a technical support worker.
I am very new to working on Open Source projects so I am hoping to learn a lot and make meaningful contributions to this project!

**Comment by whipermr5** [comment]
Hey Marco, welcome to TEAMMATES! I see you've already submitted a PR for a `d.FirstTimers` issue; that's good! You may move on to `d.Contributors` issues after completing that one :)
