### ISSUE TITLE
process.md: update command to run static analysis

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#7754]
The command was changed from `./gradlew staticAnalysis` to `./gradlew lint` in #7024; however, `process.md` was not updated.

Update the one occurrence of the command in `process.md` to fix this issue.

**Comment by srpurwaha201** [comment]
is this issue still open?

**Comment by arjunsuri** [comment]
is this issue still available?

**Comment by LiHaoTan** [comment]
@arjunsuri yes this issue is still available but not to you. Please see: https://github.com/TEAMMATES/teammates/issues/7724#issuecomment-334459796
