### ISSUE TITLE
InstructorFeedbackEditPage pageobject: fix typo in method name

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7760]
A method in [InstructorFeedbackEditPage](https://github.com/TEAMMATES/teammates/blob/master/src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java#L361) is named as `getRubicSubQuestionBox` when it should correctly be named as `getRubricSubQuestionBox`.

Use IDE refactor tools to refactor the method name to the correct one.

**Comment by billmiller2** [comment]
@VamsiSangam I have read through the contribution docs and set up my local TEAMMATES environment.  Is it alright if I make this fix and submit a pull request?
