### ISSUE TITLE
Use `Strings.isNullOrEmpty` instead of rolling our own `StringHelper.isEmpty`

### ISSUE THREAD

**Issue by LiHaoTan** [TEAMMATES/teammates#7765]
~We should use Guava's `Strings.isNullOrEmpty` instead of creating our own `StringHelper.isEmpty`.~

~While the implementation is simple and unlikely to cause any problems, the overhead incurred in writing the tests was wasted. Furthermore, `isNullOrEmpty` is a better name than `isEmpty`.~

~EDIT:
As an example, in `StudentProfileAttributes#generateUpdateMessageForStudent`:~

~Change `StringHelper.isEmpty(shortName)` to `Strings.isNullOrEmpty(shortName)`~

---
This issue is currently being re-considered and will be updated when a conclusion has been reached.

The discussion of the issue begins here: https://github.com/TEAMMATES/teammates/pull/8013#issuecomment-326744059

Some possible reasons why this issue is to be rendered invalid so a related new issue is to be created:
https://github.com/TEAMMATES/teammates/pull/8013#issuecomment-335065025

**Comment by damithc** [comment]
Perhaps do one as an example and spawn some first timer issues for the rest?

**Comment by LiHaoTan** [comment]
@damithc I added an example, there are only 14 instances where this needs to be changed so it should be quite simple. In fact, this method was only added recently and honestly, I don't think it should even be used anyway.

**Comment by keerthikorivi** [comment]
Hi @damithc, @LiHaoTan 

Can I take up this issue?

Thanks,
Keerthi Korivi.

**Comment by LiHaoTan** [comment]
@damithc can this be a `d.FirstTimers`?

**Comment by damithc** [comment]
> can this be a d.FirstTimers?

Yes. Done.

**Comment by LiHaoTan** [comment]
@keerthikorivi Sorry for the late response, yes you can go ahead.

**Comment by keerthikorivi** [comment]
@LiHaoTan  sure. Thanks :)

**Comment by keerthikorivi** [comment]
Hi @LiHaoTan 

I am running into this issue [https://github.com/TEAMMATES/teammates/issues/7819](url). Could you please help me with this?

Thanks,
Keerthi Korivi.

**Comment by HirdayGupta** [comment]
@keerthikorivi Since I do not see your introduction issue in the tracker, I would recommend that you read our [New Contributor Orientation Guide](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md) first. (Specifically the [Orientation Task List](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md#orientation-task-list) section). Once you have completed the steps mentioned there, feel free to take this issue up as your `d.FirstTimers` issue. :)
