### ISSUE TITLE
instructorFeedbackEdit: fix visibility checkboxes not responsive after discarding changes

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7784]
The current question backup mechanism involves taking a backup of the HTML in `.panel-body` and restoring it back if the instructor wants to discard changes. This mechanism has a bug.

When we restore the changes, we are merely overriding the HTML inside `.panel-body`. Due to this "override raw HTML" mechanism, certain event handlers are lost. Ex. all event handlers for `input` tags seem to vanish. An example scenario is, for custom visibility options, we execute some logic during `onchange` to ensure there's a correct selection of check-boxes.

![unjt4hxzc5](https://user-images.githubusercontent.com/11662001/28280237-b90d10f8-6b40-11e7-9ec4-a595809dd6d4.gif)

In the above GIF, deselecting `Can see answer` checkbox automatically deselects the entire row. But this logic vanishes when we use a restored version of the question.

This is just a tiny example. From what I have seen all JS events on `input` tags are lost when the question is restored. This can cause problems in many areas. We need to come up with another mechanism or enhance existing mechanism so that JS events are not lost.

**Comment by chowyb** [comment]
Most likely, this can be resolved by #3998. However, as it may be possible to resolve this in a different manner, I'll leave this issue open.
