### ISSUE TITLE
Student: MOTD: include only body of fetched HTML resource file

### ISSUE THREAD

**Issue by amarlearning** [TEAMMATES/teammates#7794]
**Issue:**
Unrelated content like `meta tag`, `favicon tag` and `title tag` found inside `student-motd` in the Student submit feedback page. _[screenshot]_

![screenshot from 2017-07-19 02-52-26](https://user-images.githubusercontent.com/9383897/28341738-8974523c-6c32-11e7-8e28-ba331ad0d309.png)

**Reason:**
Looked into the code and found that `student-motd` get's its data from [`fetchMotd`](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/dev/js/main/studentMotd.es6#L4) function via `GET` request.

On printing, the data that's `student-motd` get's from [`fetchMotd`](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/dev/js/main/studentMotd.es6#L4) function is _[screenshot]_
![screenshot from 2017-07-19 03-39-34](https://user-images.githubusercontent.com/9383897/28342035-eaed9978-6c33-11e7-9a10-c9b7f977094a.png)

**Solution:**
We should modify the [`fetchMotd`](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/dev/js/main/studentMotd.es6#L4) function to this 
```javascript
function fetchMotd(motdUrl, motdContentSelector, motdContainerSelector) {
    $.ajax({
        type: 'GET',
        url: `${window.location.origin}/${motdUrl}`,
        success(data) {
            const Bodydata = data.replace('<body', '<body><div id="body"')
                                 .replace('</body>','</div></body>');
            $(motdContentSelector).html($(Bodydata).filter('#body'));
            $(motdContentSelector).html(data);
        },
        error() {
            $(motdContainerSelector).html('');
        },
    });
}
```
This updated `fetchMotd` on success will only return the data present inside the `Body element` to `student-motd` container.

**Comment by whipermr5** [comment]
The string replacement seems hackish. Maybe use a regex? https://stackoverflow.com/questions/6195615/get-contents-of-body-body-within-a-string

**Comment by amarlearning** [comment]
Working on this
