### ISSUE TITLE
Trouble importing Project into Eclipse

### ISSUE THREAD

**Issue by oneoffaccount** [TEAMMATES/teammates#7800]
- Operating System: Windows 10
- JDK Version: 1.7
- Eclipse: 4.4.2

Hello, I'm new to Github and I'm trying to get Teammates installed on my computer so that I can make contributions. 

I'm on the section called "Setting up the Dev Server" (http://rtd-trial.readthedocs.io/en/latest/settingUp/#setting-up-the-dev-server) and I'm stuck on steps 8, 9 and 10.

I'm not even sure what steps 8 and 9 are trying to say or what to do with them.  Step 8 doesn't have any instructions with it, it's just a file path.  Step 9 is talking about it being a command, but it looks like it is just a configuration file to me, and I can't find it in the repository anyways.

So I skipped those steps and tried to import teammates as indicated in step 10.  But Eclipse says that there are no projects found to import.   Any help will be appreciated.  

![teammatesimportprojectproblem](https://user-images.githubusercontent.com/30274033/28385533-aa53d452-6c85-11e7-8e2b-b791e46498ae.png)

**Comment by uxxSam** [comment]
I followed the IDE-usage guide here:
https://github.com/TEAMMATES/teammates/blob/master/docs/ide-usage.md

You should be able to import the project after running the commend:
> ./gradlew setupEclipse

**Comment by chowyb** [comment]
@oneoffaccount the link you have provided appears to be an outdated version of our documentation. May I ask how you happened to find that link?

In the meantime, you can follow the link that @uxxSam provided, however it might be better to start from https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md instead, as there may be some other steps in that file which is not reflected in the old documentation.

**Comment by oneoffaccount** [comment]
Lol, oops.  I got to http://rtd-trial.readthedocs.io/en/latest/process/ by searching "what does "d.firsttimers" mean on github" and then clicked on the "settingUp" link.  I should have realized it wasn't the correct version of your documentation.  Thanks for the correct link!
