### ISSUE TITLE
JSP Errors: getting error marks when there are no actual errors.

### ISSUE THREAD

**Issue by adityavhegde** [TEAMMATES/teammates#7803]
Hi all, 

I have been recently getting this on my eclipse IDE. These small 'x' marks indicate there is some error : 
![image](https://user-images.githubusercontent.com/10449636/28399363-962aa078-6cda-11e7-81c5-a3f58e7d8cbf.png)

However, when I actually open the files, there seems to be no errors. 

![image](https://user-images.githubusercontent.com/10449636/28399382-b3f09a2c-6cda-11e7-8f77-8d77776865aa.png)

I have set the validation for JSP correctly as per the documentation: 
![image](https://user-images.githubusercontent.com/10449636/28399422-e42a9242-6cda-11e7-8b44-582b3417f084.png)

I have tried all steps from here, but to no success: https://stackoverflow.com/questions/2975168/eclipse-what-are-these-jsp-errors 

This is probably not a big issue, as everything works fine. However, I would want to know why it is happening.

**Comment by HirdayGupta** [comment]
@adityavhegde It might be helpful if you could post a screenshot of the `markers` tab from Eclipse.

**Comment by adityavhegde** [comment]
@HirdayGupta 
I had a look at the `markers` tab (did not know of its existence). The error was something like 'JSP files require a JDK' (I don't remember it exactly). 
There was some problem with the installed jdk. Followed  (https://github.com/TEAMMATES/teammates/blob/master/docs/ide-usage.md) to solve the problem.
