### ISSUE TITLE
EmailGenerator: Refactor feedback sessions related email templates

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#7804]
Currently, there are many different email templates for change in feedback session status, with minimal difference in their content. They can be better refactored to use a single template to reduce the complexity of EmailGenerator, and to simplify the process when updating the emails' content.

**Comment by HirdayGupta** [comment]
Working on this.

**Comment by HirdayGupta** [comment]
~~Working on this.~~

EDIT: Decided against working on this as @damithc sir mentioned that reviewer availability will be lower than usual these next few weeks and I just realised I would need a lot of input while working on this.

**Comment by AnaghHegde** [comment]
I would like work on this. As @HirdayGupta said in the [comment](https://github.com/TEAMMATES/teammates/pull/7867#pullrequestreview-53082290) i will first solve this issue then i will move to other issue.

**Comment by wkurniawan07** [comment]
Closing as this is not a priority right now
