### ISSUE TITLE
teammates.test.cases.browsertests.AllJsTests.executeJsTests test fails when i run gradlew build

### ISSUE THREAD

**Issue by keerthikorivi** [TEAMMATES/teammates#7819]
Hi All,

I am a new contributor currently working on my first task. AllJsTests always fails when I build the application even on the existing code base without any changes. Could some one let me know if they see this issue as well? Please let me know if I am missing something. I made sure I have the specified Firefox version and I have the auto update disabled.

Thanks,
Keerthi Korivi.

**Comment by whipermr5** [comment]
Have you run `npm run build`?

**Comment by keerthikorivi** [comment]
@whipermr5 Yes i did.

**Comment by HirdayGupta** [comment]
@keerthikorivi Could you tell us the exact command you used that got you to the error? And if it is an AllJsTests error we are dealing with, then the browser window that opens with the results of the Unit tests should show some portions in red. If you could post screenshots of those red portions, it would  help us work out the exact issue.

**Comment by keerthikorivi** [comment]
@HirdayGupta sure. 

I run gradlew test -Dtest.single=AllJsTests

![image](https://user-images.githubusercontent.com/17730078/28550505-ebf12fc0-70a6-11e7-92ea-5b859ed1caad.png)

Below are the browser results

![image](https://user-images.githubusercontent.com/17730078/28550527-14d2bb66-70a7-11e7-9eae-45bb9c3416e9.png)

**Comment by whipermr5** [comment]
@keerthikorivi Did you manage to resolve the issue?
