### ISSUE TITLE
Instructor: download results: don't display header if no responses

### ISSUE THREAD

**Issue by LimeTheCoder** [TEAMMATES/teammates#7823]
Currently, if no responses for a question in CSV file response header still appearing.

![image](https://user-images.githubusercontent.com/8873908/28503655-9b75d20a-7013-11e7-9180-a233142d59fb.png)

It's better instead of the header to display a message which will indicate that no responses for given question.

**Comment by damithc** [comment]
Um, I think this is fine? Reason: Headers provide some information about what _will_ appear in the file eventually, plus it's simpler (in the code) to keep it this way. What do you think?

**Comment by LimeTheCoder** [comment]
For me, that was a little bit confusing that header appears but no rows with information. But still I agree with your point of view that header, in that case, needs to exist too due provided reason.
