### ISSUE TITLE
GateKeeper: Assertions used wrongly

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [TEAMMATES/teammates#7834]
Methods in `GateKeeper`: `isInstructor()` and `isStudent()` both call `Assumption.assertNotNull(Object)` to verify that `userService.getCurrentUser()` do not return a null value. 

This is not the right use of assertions. Assertions are only used to verify preconditions and postconditions of calling a method.

Let’s remove the assertions in `isInstructor()` and `isStudent()`, and teach `AccountsLogic#isAccountAnInstructor(String)` and `StudentsLogic#isStudentInAnyCourse(String)` to do the precondition checks instead.

**Comment by wkurniawan07** [comment]
Closing as explained in #7996.
