### ISSUE TITLE
StudentProfileAttributes: make constructor private

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [TEAMMATES/teammates#7836]
The empty constructor of `StudentProfileAttributes` is package-private.

When other classes try to initialise `StudentProfileAttributes` using this constructor, they have to use a workaround method by calling `.builder().build()`. There are multiple instances of this workaround being called in the codebase.

Let’s make the empty constructor of `StudentProfileAttributes` `public` so that callers do not have to use a workaround to initialise it.

**Comment by wkurniawan07** [comment]
Just leaving a note here that exposing constructor goes against the idea of builder pattern itself.

**Comment by Zhiyuan-Amos** [comment]
Ah I see. That way, should we make it private then, since only the `Builder` calls the constructor? Then we can leave a comment inside the constructor that making this constructor public violates the builder pattern.

Alternatively, I think a better idea would be to remove the empty constructor from `StudentProfileAttributes`, and to let the initialization be done inside `Builder` instead.

**Comment by LimeTheCoder** [comment]
> That way, should we make it private then, since only the Builder calls the constructor?

In that case, it won't be possible to access constructor from static context of Builder class.

> Alternatively, I think a better idea would be to remove the empty constructor from StudentProfileAttributes, and to let the initialization be done inside Builder instead.

If you remove empty package-private constructor then will be used default constructor with public access level instead.

**Comment by Zhiyuan-Amos** [comment]
> In that case, it won't be possible to access constructor from static context of Builder class.

Ah yes, what was I even thinking. Thanks! 👍 

> If you remove empty package-private constructor then will be used default constructor with public access level instead.

Yes you are right, I missed this out as well. I'm thinking how about we make a private constructor which doesn't do anything:
```
private StudentProfileAttributes() {
    // prevents initialization. Initialization should be done through builder.
}
```

That way, we can shift the assigning of the variables (currently in the constructor) to be the responsibility of the Builder instead.

**Comment by wkurniawan07** [comment]
Leaving a note here that there is a legitimate reason for the constructor being package instead of private: https://github.com/TEAMMATES/teammates/pull/7602#discussion_r124708178

(although honestly I don't really like that PMD rule)

**Comment by Zhiyuan-Amos** [comment]
> there is a legitimate reason for the constructor being package instead of private

I see! Can we do something like this then?

```
StudentProfileAttributes() {
    // constructor should not be called
}
```

```
public Builder() {
    withGoogleId("");
    withShortName("");
    withEmail("");
    withInstitute("");
    withNationality("");
    withGender("other");
    withMoreInfo("");
    withPictureKey("");
    withModifiedDate(new Date());
}
```

I.e. We can transfer the init's logic into the `Builder` instead.

**Comment by wkurniawan07** [comment]
Closing as explained in #7996.
