### ISSUE TITLE
GateKeeper: Remove verifyNotNull(…)

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [TEAMMATES/teammates#7840]
`verifyNotNull(Object, String)` is a precondition check which checks whether the `Object` parameter is null. If it is null, an `UnauthorizedAccessException` with the error message `"Trying to access system using a non-existent entity"` will be thrown. 

This doesn’t seem right as the check simply checks whether the variable is null or not; there is no connotation of unauthorised access.

Let’s change callers to use Guava’s `checkNotNull(Object, String)` (see #7730) instead, and let’s remove `verifyNotNull(…)`.

**Comment by whipermr5** [comment]
I believe null variables at these points of the code do connote unauthorised access, e.g. due to tampering of POST parameters.

**Comment by wkurniawan07** [comment]
Closing as explained in #7996.
