### ISSUE TITLE
Instructor: view course: change Delete button color to red

### ISSUE THREAD

**Issue by stanislous** [TEAMMATES/teammates#7841]
Changing the colour of the delete button in Instructor: edit course page. And it would be attractive and readable. 

![screenshot 810](https://user-images.githubusercontent.com/20964806/28839948-ee0668e4-7712-11e7-98dc-d692d085f938.png)

**Comment by damithc** [comment]
We can give it a try and see if it looks better. We don't want to make it too eye-catching either, given that it is not the main action in this form. On a related note, I notice taht the button at the bottom is struck to the drop-down just above it :-p
