### ISSUE TITLE
Sample course: first session: use consistent phrasing

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7847]
Questions in the sample sessions are phrased inconsistently, using both 'you' and 'my' to refer to the respondent

Current:
![image](https://user-images.githubusercontent.com/1673303/28599344-6b08d408-71dc-11e7-9513-423e94a3aae9.png)

Suggestion:
Rephrase the first question as `My estimate of how much each team member contributed`

Even better if we can rephrase all questions to use `You` because it is easier to provide instructions to the respondent when using imperative mood.

**Comment by amarlearning** [comment]
Taking this one

**Comment by amarlearning** [comment]
@damithc the sample questions are created using data from `InstructorSampleData.json` and changes will be visible only in new instructor's account.

**Comment by damithc** [comment]
You are right @amarlearning We need to fix this in the sample course as well as the standard feedback session questions (if it's flawed in both places).
