### ISSUE TITLE
Website home page: add to user quotes

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7854]
Where to add:
![image](https://user-images.githubusercontent.com/1673303/28624586-1f82d7f2-724c-11e7-8115-12d2a16c1594.png)

What to add:
![image](https://user-images.githubusercontent.com/1673303/28624622-42cc8ac8-724c-11e7-906d-33e28001e0a2.png)
`- Faculty user, UK`

![image](https://user-images.githubusercontent.com/1673303/28624675-6de2139a-724c-11e7-833c-167e655182f9.png)
`- Faculty user, Singapore`

**Comment by kyleaolson** [comment]
I'll take this.

**Comment by dikshaa42** [comment]
should i do this?

**Comment by aforbe2** [comment]
I'd like to take this issue if possible.
