### ISSUE TITLE
Rubric questions: allow simple edits to rubric choices

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7860]
Currently, simple edits to rubric choices, such as correcting a typo, will need the deletion of existing responses. Modify implementation such that instructor can make simple edits to rubric choices without the need to delete existing responses. So briefly, only adding/deleting rows/columns and swapping columns must lead to deletion of existing responses.

[Discussion](https://github.com/TEAMMATES/teammates/pull/7415#issuecomment-317026870).

**Comment by damithc** [comment]
This is not urgent. One part of this issue is to look at the back-end implementation to identify which kind of changes compromise the integrity of the existing data. For example, if the back-end is solid, adding a row should not invalidate existing data.

**Comment by wkurniawan07** [comment]
Closing due to infeasibility. Even correcting typos can warrant change in responses. Consider
```
Which one of your team members do you recommend as team lead?
``` 
vs
```
Which one of your team members do you not recommend as team lead?
```
