### ISSUE TITLE
New contributor self intro Kyle Olson

### ISSUE THREAD

**Issue by kyleaolson** [TEAMMATES/teammates#7864]
A) https://teammates-kyleaolson.appspot.com/
B) https://github.com/kyleaolson/teammates
C) Reformatted contact section and updated link to GitHub repo from text to image.
![image](https://user-images.githubusercontent.com/8674997/28654371-55db9732-7259-11e7-83e9-c11c979b6b67.png)
D) Hello! I'm a techie from Houston, TX that currently works as a full-stack developer for a Fortune 500 financial services company. I currently work on a small team developing an internal application built on AngularJS and Spring Framework. I'm wanting to help out to get familiar with open source development and to broaden my skills with a different stack than I'm used to. Teammates seems like one of the best communities to start as a newbie in open source so I'm excited to get started!

**Comment by HirdayGupta** [comment]
Hi @kyleaolson, Welcome to TEAMMATES!

Good job on correctly setting up your developer environment. You can start off your contribution by tackling an issue labelled `d.FirstTimers`. These are simple issues and fixes (like typos, etc) that have been earmarked to orient newcomers to our workflow. You can find the `d.FirstTimers` issues [here](https://github.com/TEAMMATES/teammates/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20label%3Ad.FirstTimers%20). :)
