### ISSUE TITLE
Student: submit 'distribute points' question: fill empty entries as 0

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7875]
Current: 
empty entries are allowed and considered as zero
![image](https://user-images.githubusercontent.com/1673303/28749756-c0721442-7504-11e7-9d43-d1681793e4df.png)

Suggested:
A use suggested that empty entries should be auto-filled with `0`. This can be done at the point the javascript determines the total is correct but there are empty entries

**Comment by amarlearning** [comment]
working on this

**Comment by amarlearning** [comment]
@damithc we can also the default value to `0` by just adding the `value` attribute to the `input[type='number']` tag. something like this:-

```html
<input type='number' value='0'>
```
Now when the student open the page for submiting response, it looks something like this _[screenshot]_
![screenshot from 2017-07-30 09-16-38](https://user-images.githubusercontent.com/9383897/28750424-eccf9430-7507-11e7-88d7-3590e63e35bb.png)

I think this should be a `first-timer issue`, if not then I can do this.

**Comment by damithc** [comment]
@amarlearning If you set all values to 0 by default, it will not add up to the required number and will block the form being submitted? That means users cannot submit responses to other questions unless they submit this question.

**Comment by amarlearning** [comment]
> If you set all values to 0 by default

By that I mean, when the form loads the default value of the input will be `0`, but the student can edit the fields while filling up the feedback form. No change will be noticed in the behavior of the code, everything will work fine.

Like this did just now _[screenshot]_, All values were set to `0` by default, I just changed one value and moved to another question.
![screenshot from 2017-07-30 09-51-01](https://user-images.githubusercontent.com/9383897/28750574-f9b65ce2-750c-11e7-961a-2dd64ac1fc8d.png)

**Comment by damithc** [comment]
The student should be able to submit the form with answers to other questions but not this question. If you fill it up with 0's from the start, the student is forced to edit this question either to remove all 0's or make it add up to the required sum, right?

**Comment by damithc** [comment]
The point is, empty cells means 'unanswered' and the student can leave it as 'unaswered' without further action. If you fill it up with zeros by default, the question becomes 'answered' without any action from the user, and we don't want that.

**Comment by amarlearning** [comment]
> If you fill it up with zeros by default, the question becomes 'answered' without any action

Just noticed that :sweat_smile:, thanks for the explanation.
