### ISSUE TITLE
HTML: Use `charset` attribute instead of `http-equiv` attribute to specify encoding

### ISSUE THREAD

**Issue by LiHaoTan** [TEAMMATES/teammates#7878]
Let's replace all
```html
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
```
with
```html
<meta charset="utf-8">
```

---
While our [HTML style guide](https://oss-generic.github.io/process/codingStandards/CodingStandard-Html.html) did not specifically prefer either to specify encoding, the style guide should be updated to prefer `charset`.

Although the standard did not specify which is to preferred, their examples use the charset attribute as well.

```html
<!DOCTYPE HTML>
<HTML LANG="EN">
 <HEAD>
  <META CHARSET="UTF-8">
  <BASE HREF="https://www.example.com/">
  <TITLE>An application with a long head</TITLE>
  <LINK REL="STYLESHEET" HREF="default.css">
  <LINK REL="STYLESHEET ALTERNATE" HREF="big.css" TITLE="Big Text">
  <SCRIPT SRC="support.js"></SCRIPT>
  <META NAME="APPLICATION-NAME" CONTENT="Long headed application">
 </HEAD>
 <BODY>
 ...
```
https://html.spec.whatwg.org/multipage/semantics.html#the-head-element
https://www.w3.org/TR/html5/document-metadata.html#the-meta-element

Furthermore, in [Google's HTML/CSS Style Guide](https://google.github.io/styleguide/htmlcssguide.html#General_Meta_Rules):
> Specify the encoding in HTML templates and documents via \<meta charset="utf-8">. Do not specify the encoding of style sheets as these assume UTF-8.

The community is also in consensus that `charset` is preferred.
https://stackoverflow.com/questions/4696499/meta-charset-utf-8-vs-meta-http-equiv-content-type

MDN web docs also recommends using `charset`
> The <meta> element with a charset attribute is a synonym for the pre-HTML5 \<meta http-equiv="Content-Type" content="text/html; charset=IANAcharset">, where IANAcharset contains the value of the equivalent charset attribute. This syntax is still allowed, although no longer recommended.

https://developer.mozilla.org/en/docs/Web/HTML/Element/meta

**Comment by stanislous** [comment]
Can I work on this?

**Comment by whipermr5** [comment]
@felixinjapan are you still working on this?

**Comment by felixinjapan** [comment]
Sorry, please go ahead. @stanislous @whipermr5
