### ISSUE TITLE
teammatesCommon.css: Remove `@charset 'UTF-8';` 

### ISSUE THREAD

**Issue by LiHaoTan** [TEAMMATES/teammates#7881]
The standards committee recommend that

> Stylesheet authors should author their stylesheets in UTF-8, and ensure that either an HTTP header (or equivalent method) declares the encoding of the stylesheet to be UTF-8, or that the referring document declares its encoding to be UTF-8. (In HTML, this is done by adding a \<meta charset=utf-8> element to the head of the document.)

https://drafts.csswg.org/css-syntax-3/#determine-the-fallback-encoding

This is made clearer with their recommendations here:
> You can use @&#8203;charset or HTTP headers to declare the encoding of your style sheet, but you only need to do so if your style sheet contains non-ASCII characters and, for some reason, you can't rely on the encoding of the HTML and the associated style sheet to be the same.

https://www.w3.org/International/tutorials/tutorial-char-enc/

> You should always use UTF-8 as the character encoding of your style sheets and your HTML pages, and declare that encoding in your HTML. If you do that, there is no need to declare the encoding of your style sheet.

https://www.w3.org/International/questions/qa-css-charset

---
Moreover, the syntax used for `@charset` is incorrect, as it requires double quotes.

> Otherwise, check the byte stream. If the first 1024 bytes of the stream begin with the hex sequence
40 63 68 61 72 73 65 74 20 22 XX* 22 3B
where each XX byte is a value between 016 and 2116 inclusive or a value between 2316 and 7F16 inclusive, then get an encoding for the sequence of XX bytes, interpreted as ASCII.

https://drafts.csswg.org/css-syntax-3/#determine-the-fallback-encoding

**Mapping of bytes**

| 40    | 63 | 68 | 61 | 72 | 73 | 65 | 74 | 20 | 22 | XX* | 22 | 3B |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
|@|   c | h | a | r | s | e | t | \<space> | " | \<charset> | " | ; |

**Comment by felixinjapan** [comment]
Hi, I would like to take care of this ticket.
