### ISSUE TITLE
Instructor: edit instructors: give a way to create multiple instructors in one step

### ISSUE THREAD

**Issue by dikshaa42** [TEAMMATES/teammates#7882]
Teammates have a feature of adding multiple instructor names in one go. So, we can enhance that feature by allowing the user to upload a file which will have specified format. It will be easy for the users rather than copy pasting.

**Comment by LimeTheCoder** [comment]
I thought about that too, nice idea!

**Comment by whipermr5** [comment]
I suspect @damithc would prefer a web UI to uploading a file. Something similar to #7882 would be good. However, priority will probably be low as I don't think multiple instructors are added often?

**Comment by damithc** [comment]
Yes, I prefer something similar to 'enroll students' page.
Yes, some users have asked for an easier way to create multiple instructors. One complication is that custom instructors can contain lot of details, so this feature probably won't cover instructors with custom settings.

**Comment by damithc** [comment]
Probably we should do #7225 first. Putting this on hold in favor of #7225

**Comment by dikshaa42** [comment]
Hi all, Thanks for appreciating this. Please, I want to make this enhancement.

**Comment by wkurniawan07** [comment]
Closing as this is not a priority right now
