### ISSUE TITLE
Trim leading whitespace from HTML output

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#7884]
Viewing the source of any TEAMMATES page reveals lots of unnecessary whitespace in the HTML:
![screen shot 2017-07-31 at 3 35 35 pm](https://user-images.githubusercontent.com/6811428/28767381-0d4088ba-7606-11e7-9747-19c30cd2999a.png)

~~This is due to every directive in our `jsp` and `tag` files taking up a newline each. To fix, add the `trim-directive-whitespaces` directive to `src/main/webapp/WEB-INF/web.xml` as detailed here: https://stackoverflow.com/a/20100278~~ Edit: this directive seems to be ignored by Google's runtime.

**Comment by wkurniawan07** [comment]
@whipermr5 can confirm that it actually works in `web.xml`? I'm aware of this trick since long ago but for some reason did not manage to get it work via `web.xml`; it works if added as individual directives in each JSP/tag files.

**Comment by whipermr5** [comment]
@wkurniawan07 Oops, you're right 😅

**Comment by whipermr5** [comment]
I guess it'd suffice to add the directive to `page.tag` and `staticPage.tag`.

**Comment by wkurniawan07** [comment]
FWIW, adding the following to every JSP/tag file:
```jsp
<%@ page trimDirectiveWhitespaces="true" %>
<%-- or --%>
<%@ tag trimDirectiveWhitespaces="true" %>
```
will achieve what is intended.
While this necessitates repetition and is prone to the case of "forget to include this directive in some files", it does not affect correctness and thus non-inclusion is not so much of an issue.

**Comment by wkurniawan07** [comment]
I would say it is. It will only be a dirty work now when every single JSP/tag file needs to be equipped with that directive. New ones can be enforced afterwards and will most definitely be copied from existing ones. (let's admit it, who would make a new JSP/tag file from zero?)
Besides, even missed, it will only be a performance problem and not correctness problem.

**Comment by whipermr5** [comment]
Additional info for fixing this: https://github.com/TEAMMATES/teammates/pull/8164#issuecomment-345533776

**Comment by OrionStar25** [comment]
I'd like to work on this issue.
Am I expected to do [this](https://github.com/TEAMMATES/teammates/pull/8164#issuecomment-345533776) only and for all the files? Please guide me @whipermr5

**Comment by whipermr5** [comment]
@OrionStar25 That is to fix the failing tests which is part of the solution. You can submit a PR and we can take a look :)

**Comment by man-of-code** [comment]
@whipermr5 I would like to try fixing this issue.
Could you tell me where to start?

**Comment by whipermr5** [comment]
@man-of-code Check out all the comments so far as well as the history of #8164.

**Comment by man-of-code** [comment]
@whipermr5 Thank you. I'll be submitting a PR shortly.

**Comment by ongspxm** [comment]
hi, anyone working on this? I can trawl through the files to make the changes using [this](https://github.com/TEAMMATES/teammates/pull/8164#issuecomment-345533776) if this issue is still open.

**Comment by damithc** [comment]
> hi, anyone working on this? I can trawl through the files to make the changes using this if this issue is still open.

Go ahead @ongspxm
