### ISSUE TITLE
New contributor self intro: Jon Vanderlaan

### ISSUE THREAD

**Issue by vandy56** [TEAMMATES/teammates#7891]
- https://teammates-jon.appspot.com
- https://github.com/vandy56/teammates

**Screenshot of changes made (as seen on the UI)**
<img width="1195" alt="screen shot 2017-08-02 at 8 05 49 am" src="https://user-images.githubusercontent.com/26888281/28878007-a66f1322-7763-11e7-8d8a-d15bd9f625a1.png">
I removed the ellipses from the headline (Student peer evaluations/feedback, shareable instructor comments, and more!) and from a subheadline (6,777,638 feedback entries submitted so far), as using ellipses is poor style in headlines.

**Short self-introduction**
My name is Jon Vanderlaan and I'm pretty new to software development. I'm currently a student at the University of Illinois at Springfield's online computer science program. I hope to contribute to Java code (since it's what I know best right now), but I also hope to learn more about the entire process and contribute wherever needed.

Nice to meet you!

**Comment by whipermr5** [comment]
Hey Jon, welcome to TEAMMATES! Good job setting everything up correctly! I see you've already submitted a PR for a `d.FirstTimers` issue; that's good! While waiting for it to be reviewed, feel free to take a look at `d.Contributors` issues if you're bored :)
