### ISSUE TITLE
Instructor: Edit Course Details: change Delete buttons color to red

### ISSUE THREAD

**Issue by stanislous** [TEAMMATES/teammates#7896]
Changing the colour of the delete button in Instructor: edit course details page. it would be attractive and readable.

![screenshot 817](https://user-images.githubusercontent.com/20964806/28892537-f52c82f0-77eb-11e7-90f1-0cd3a32fc873.png)

**Comment by stanislous** [comment]
@damithc can I do this?

**Comment by whipermr5** [comment]
I actually have a suggestion: move the delete button to inside the panel, just like the view course panel. A red button seems less out of place there (but this is quite subjective). Not sure what @damithc prefers?

**Comment by LiHaoTan** [comment]
I think it is also subjective whether the delete button should be changed to red. After all, it is very striking.

It's like `edit` and `delete` should have equal standing, but when `delete` is red, the user will be more likely to first notice it.

It also seems I have rarely seen red delete buttons nowadays on UIs.

More importantly, my opinion here though is that it seems the benefits for changing the delete button is not clear so we shouldn't change it, not to mention it has the potential to be detrimental.

**Comment by damithc** [comment]
Yup, I have reservation about making this button red too. Closing.
