### ISSUE TITLE
Update user map for July 2017

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7898]
Similar to #7215 
New data to consider:

Country | Institute
-- | --
Australia | Australian National University
Australia | St Paul's Anglican Grammar School
Brazil | Universidade Estadual de Maringá
Canada | Dalhousie
Canada | Sheridan College
Canada | University of Guelph
Denmark | DHI
El Salvador | Escuela Superior de Economía y Negocios
France | EMLYON Business School
Germany | Stuttgart Media University
India | KBP COE SATARA
Kazakhstan | Method Coding School
Mexico | UNAM
Netherlands | Avans University of Applied Sciences
Netherlands | Eindhoven University of Technology
New Zealand | Massey University
New Zealand | University of Auckland
Pakistan | Aga Khan University Hospital
Philippines | EKR
Puerto Rico | Carlos Albizu University
Singapore | Australian International School Singapore
Singapore | River Valley High School
Singapore | Singapore Institute of Technology
Singapore | Singapore Polytechnic
Singapore | sport.gov.sg
Spain | Geneva Business School Barcelona Campus
Taiwan | NKFUST
UK | Hult International Business School
UK | Kingston University
UK | Liverpool John Moores University
UK | Newcastle University
UK | University of Huddersfield
UK | University of Portsmouth
UK | University of Warwick
USA | Amazon
USA | CalBaptist University
USA | Carly Thompson Temp University
USA | Claremont Colleges
USA | Cotton Creek Elementary
USA | Dayton Regional STEM School
USA | Duke University
USA | Jacksonville Christian Academy
USA | Keiser University
USA | Kendall College of Art and Design
USA | Lake Sumter State College
USA | Middle Creek High School
USA | Northeastern University
USA | Ohio University
USA | Penn State University
USA | Quinnipiac University
USA | Southern Connecticut State University
USA | Southern Oregon University
USA | St. Magarets School
USA | The University of Memphis
USA | University of Cincinnati
USA | University of Dallas
USA | University of South Carolina Aiken
USA | University of South Florida
USA | Van Buren Elementary
USA | Volusia Online Learning
USA | Wellesley College
USA | Xavier University of Louisiana

**Comment by dikshaa42** [comment]
i will take up this issue :)

**Comment by dikshaa42** [comment]
Hi @damithc,
Is Kingston University London, UK and Kingston University, UK both different?

**Comment by damithc** [comment]
> Is Kingston University London, UK and Kingston University, UK both different?

Not sure @dikshaa42 . Do some Google around and decide yourself :-)

**Comment by damithc** [comment]
@dikshaa42 also note that I removed an email address that was erroneously included in the original list as an institute.

**Comment by sowmyadvn** [comment]
@damithc I see that this issue is not referenced yet. I am a first-timer here. Can I give it a try?

**Comment by damithc** [comment]
> @damithc I see that this issue is not referenced yet. I am a first-timer here. Can I give it a try?

Sure @sowmyadvn
