### ISSUE TITLE
HTML: Remove all instances of `meta` element with attribute `http-equiv` of value `X-UA-Compatible` 

### ISSUE THREAD

**Issue by LiHaoTan** [TEAMMATES/teammates#7903]
An example of a `meta` element to be removed would be `<meta http-equiv="X-UA-Compatible" content="IE=8">`

We do not need or want to render anything in an IE's legacy document mode.

Additional resources: [When to use legacy document modes]( https://msdn.microsoft.com/en-us/library/jj676917(v=vs.85).aspx)

**Comment by dipikaisdbest** [comment]
Hi Is this still open? Could I grab it?

**Comment by LiHaoTan** [comment]
@dipikaisdbest yes it is still open

**Comment by dipzzzz** [comment]
Is this issue still live?

**Comment by whipermr5** [comment]
@dipzzzz Yes; there is no currently open PR for it that follows our contribution guidelines.

**Comment by jungeunyoon** [comment]
Could I take this issue please?

**Comment by loisgh** [comment]
I'll be happy to for this and follow contribution guidlines.

**Comment by arjunsuri** [comment]
is this issue still open?

**Comment by LiHaoTan** [comment]
@arjunsuri yes but it seems that you have already completed a `d.FirstTimers` issue so you should not be doing more than one of these.

**Comment by arjunsuri** [comment]
So, which issue I should take considering I am still a newbie in open source development.

**Comment by LiHaoTan** [comment]
As mentioned in https://github.com/TEAMMATES/teammates/issues/7724#issuecomment-334459796, please go through the `README` and if you still have any questions you can post it on the issue tracker. However, please don't randomly jump into asking questions without bothering to understand the process.

**Comment by whipermr5** [comment]
Hey @arjunsuri, try taking a look at issues with the label `d.Contributors` :)

**Comment by shaharyar-shamshi** [comment]
Is this still open if not then suggest another issue which I can solve as I am new to this organisation

**Comment by LiHaoTan** [comment]
@shaharyar-shamshi yes this issue is still open :)

**Comment by wkurniawan07** [comment]
@LiHaoTan if this issue is pretty much about removing IE8 support, you can extend it a bit to include removing [HTML5 shim and respond.js](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/WEB-INF/tags/page.tag#L22-L25). What do you think?

**Comment by LiHaoTan** [comment]
@wkurniawan07 No I wasn't removing IE8 support. Though while I would love to, I am not sure what the proportion of the users on TEAMMATES is using Internet Explorer as well.

The global overall usage of IE8 usage is still pretty high, but I'm guessing it may be due to enterprises using it. I'm not sure if that means most TEAMMATES users use IE or not.

Though I suppose if we know the proportion of the IE users without tracking info, we can drop IE8 support? But I guess we would do that along with upgrading to BootStrap 4, JQuery 3 and any other libraries that can't be upgraded because of IE8?

**Comment by wkurniawan07** [comment]
@LiHaoTan we have formally dropped support for IE8 and below since long ago (there is a JS function to check minimum browser version somewhere, just find it).

**Comment by LiHaoTan** [comment]
@wkurniawan07 ah my apologies, I found it, wasn't aware that TEAMMATES wasn't supposed to be supporting since the start of the history altogether (since 2012).

But what's even weirder is that that check is only done on the homepage, and it doesn't even work. Somehow I thought I saw it before too but forgot about it 😅 

What is supposed to be the correct behavior here? This also means that we have been supporting IE8 unknowingly or knowingly?

**Comment by wkurniawan07** [comment]
Browser support has not been touched for many years now (it was never a priority), and I have to agree that the way it is done now is problematic, if even working in the first place.
But given that we actually have a stand that only IE9 and above are supported, the correct behavior should be no `http-equiv` meta (i.e. this issue), no [HTML5 shim and respond.js](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/WEB-INF/tags/page.tag#L22-L25), and no [IE8-specific CSS rule](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/stylesheets/teammatesCommon.css#L737).
