### ISSUE TITLE
New contributor self intro: Amruthaluri Kiran Kumar

### ISSUE THREAD

**Issue by kiranml1** [TEAMMATES/teammates#7905]
Forked Repo Link: [https://github.com/kiranml1/teammates](https://github.com/kiranml1/teammates)

**Screenshots of changes made (as seen on the UI)**
**![image](https://user-images.githubusercontent.com/2797515/28968858-aef39a58-793f-11e7-9dd0-9b9c96f43652.png)**
I changed login link colors on header section of the page into white color.

Short self-introduction 
My name is Kiran and am a Front end developer with 4 years of software development experience from India. I'm interested in contributing in open source and wanted to expand my experience and exposure. I hope to contribute in Front end side of the project and maintain quality standards as documented. 

Looking forward to work with you all!

**Comment by amarlearning** [comment]
Hi @kiranml1, welcome to TEAMMATES! You can start by fixing a [`d.FirstTimers`](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue, then those labeled [`d.Contributors`](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors).
