### ISSUE TITLE
New contributor self intro :Melkysalem F B Silva

### ISSUE THREAD

**Issue by MelkyFB** [TEAMMATES/teammates#7908]
Hello All, I hope I can help y'all with TEAMMATES issues:
My Fork: https://github.com/MelkyFB/teammates
Role: Frontend Developer

Intro: I'm Melkysalem Fernandes Batista da Silva, BSc, Brazilian, I work with Java, Javascript and NodeJS for 4 years, I'm interested in contribute to Open Source projects because I like the Open Source Ideology and I want to expand my way to develop.

**Screenshots of changes made (as seen on the UI)**
![Screenshots of changes made (as seen on the UI)](https://user-images.githubusercontent.com/19755071/28999856-98503abe-7a2e-11e7-817c-c77a8805f77d.png)
_Changed the Login Link Color to #EEE and the Title to #333_

**Comment by amarlearning** [comment]
Hi @MelkyFB, welcome to TEAMMATES! You can start by fixing a [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue, then those labeled [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors).
