### ISSUE TITLE
InstructorFeedbackEditPage: add documentation for selectConstSumPointsOptions method

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7910]
The `selectConstSumPointsOptions()` method in `InstructorFeedbackEditPage` is used to switch between the points distribution scheme for const sum question. Though the method is understandable, the arguments to pass to the method is still a mystery even after looking at the code -

```java
public void selectConstSumPointsOptions(String pointsOption, int questionNumber) {
    markRadioButtonAsChecked(
           browser.driver.findElement(By.id("constSumPoints" + pointsOption + "-" + questionNumber)));
}
```

One would have to check the templates or inspect HTML to find out the ID of the radio buttons and deduce the value for the String parameter. It would be very helpful to devs if we added a small documentation string above this method -

```java
/**
 * Selects the points distribution scheme for a const sum question.
 * 
 * @param pointsOption Value of "Total" will select total number of points for all options points distribution scheme,
 *                     or "PerOption" will select number of points per option points distribution scheme.
 * @param questionNumber question number of the const sum question.
 */
```

**Comment by kmr0018** [comment]
I would like to take this as my first PR.

**Comment by VamsiSangam** [comment]
Sure @kmr0018 ! Go ahead. You can comment here if you are having any trouble. Also I recommend you to go through our [contributor's orientation guide](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md) which will help you to setup Teammates on your dev PC.
