### ISSUE TITLE
Student submission page: add loading text to submit button

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7911]
When a student clicks `Submit Feedback` button at the end of submission page, it becomes like this -

![submit](https://user-images.githubusercontent.com/11662001/28997414-a1d902b6-7a31-11e7-8e21-574569ed1f99.JPG)

We could add loading text such as `Submitting` to make it look better. Changing [this](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/dev/js/main/feedbackSubmissionsEdit.es6#L1028) line in `feedbackSubmissionsEdit.es6` from
```js
addLoadingIndicator($submissionButton, '');
```
to
```js
addLoadingIndicator($submissionButton, 'Submitting ');
```

will do the job.

**Comment by ihsavru** [comment]
I'm taking this one :)

**Comment by VamsiSangam** [comment]
@damithc sir, I think this should be a `d.FirstTimers` issue, the fix is just a few characters and I'm sure this wont need god mode.

@ihsavru please hold a little, while we finalize the difficulty of this issue.

**Comment by damithc** [comment]
> @damithc sir, I think this should be a d.FirstTimers issue

Done. 👍

**Comment by VamsiSangam** [comment]
@ihsavru sorry for the confusion :sweat_smile: . This issue is now reserved for the first timers. You can start working on a [`d.Contributors`](https://github.com/TEAMMATES/teammates/issues?q=is%3Aissue+is%3Aopen+label%3Ad.Contributors) issue of your choice.

**Comment by viraj071** [comment]
Can I take this ?

**Comment by VamsiSangam** [comment]
Sure @viraj071 ! Go ahead.
