### ISSUE TITLE
New contributor self intro: Viraj

### ISSUE THREAD

**Issue by viraj071** [TEAMMATES/teammates#7913]
- **Link to my fork:** e.g. https://github.com/viraj071/teammates

**Screenshot of changes made (as seen on the UI)**
<img width="1440" alt="screen shot 2017-08-05 at 11 18 22 pm" src="https://user-images.githubusercontent.com/5512789/29001117-7a912fc8-7a34-11e7-8a39-01517c4a353e.png">
Changed the button color for "Request a Free Instructor Account"

**Short self-introduction**
Hi, My name is Viraj. I am a backend developer with a couple of years of experience. I am interested in contributing to OSS and TeamMates will be a good start to contributing to something meaningful.

**Comment by amarlearning** [comment]
Hi @viraj071, welcome to TEAMMATES! You can start by fixing a [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue, then those labeled [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors).

**Comment by Surya-06** [comment]
hi there @amarlearning , i am a contributor but i do not find issues related much to java and most of them are related to json , could you help me in finding some issues based on Java . I am new to open source and would be grateful to accept any suggestions.

Cheers.

**Comment by amarlearning** [comment]
@Surya-06  you can take up this issue: (_Instructor: edit question: receiver is instructors: support specifying a max number of recipients #7512_)

And as @leeyimin said, _"Not many java related issues are labeled with t-Java so you have probably had to click on them to find out what they are about."_

As your question is not related to this issue, I would suggest you open a separate issue for that. Yes, we use issues for discussions.
