### ISSUE TITLE
Create an Abstract SuperClass for *CourseJoinAuthenticatedActions

### ISSUE THREAD

**Issue by HirdayGupta** [TEAMMATES/teammates#7917]
Suggested by @chowyb in https://github.com/TEAMMATES/teammates/pull/7902#pullrequestreview-54341776

That PR was trying to add a method that applied to both `Instructor` and `Student` `CourseJoinAuthenticatedActionClasses`. Since the code was quite common, the original approach had been to create a utility method in the `Action.java` parent class. However, as pointed out by @chowyb, `Action.java` should only include methods that are used by _more than a few_ actions. 

Hence, this Issue deals with adding a new `Abstract` Super class for both the *CourseJoinAuthenticatedActions. The scope of this PR also includes putting any other functionality that is common between the two classes in this new Super Class. The new class may be called `CourseJoinAuthenticatedAbstractAction` (again, suggested by @chowyb).

After this issue is solved, PR #7902 will be rewritten.

**Comment by HirdayGupta** [comment]
Working on this.

**Comment by HirdayGupta** [comment]
After spending some time trying to move common functionality to this new abstract class, I think it might be cleaner/easier to not shift around any functionality. There is definitely a need for an `AbstractAction` class for the changes in #7902, but it does not need to be done in a separate PR. This is because it is too hard to put common functionality in this new Class (making the mere creation of an abstract superclass with just one method straightforward and doable in #7902 itself). The difficulty arises partly from the lack of common functionality (just a common category of steps) and partly from the lack of a consistent structure across the classes.

For the record, my solution to this was to add empty abstract functions in the new abstract class called `verifyUserPriveleges`, `joinUserToCourse`, and `setStatusMessageToAdminOrUser`. (These methods seemed to be the basic steps in both the action classes). I did this because I couldn't find any common code that I could extract between the two classes, just common steps. 

The reason I abandoned this was because of complications arising due to differences between how the errors at each step were dealt with and also because I wasn't sure if this approach was even good enough to be worth the effort to fix the errors. (because there was no precedent for this approach).

Before I close this issue, I would be grateful if a senior dev (perhaps @chowyb) could just read through this message and tell me if the solution I had suggested was worth implementing or not. Thanks! :)

**Comment by chowyb** [comment]
@HirdayGupta yep, looks fine to close this issue. I was initially concerned that if this was done as a separate issue, it may not do much if there was actually no code in common between the two classes (which appears to be the case here).

As for adding abstract methods, this may not be well suited for the purposes of this class (at least based on the description provided), as no code relies on these abstract methods being implemented (unlike `execute()` in `Action` class) in order to do different things. Declaring these methods therefore forces any subclass to implement these methods (even if it is done by implementing a stub method), even though they may never be used.

**Comment by HirdayGupta** [comment]
Thanks for the clarification @chowyb. Closing this issue :)
