### ISSUE TITLE
Instructor: home page: fix sort by date

### ISSUE THREAD

**Issue by HirdayGupta** [TEAMMATES/teammates#7919]
Noticed while working on #1297.

On the Instructor Home Page, in the table of Sessions displayed, the sorting by date buttons do not work as expected if any one session in the list has start date or end date with a `12 NOON`time. 

This error happens because JS fails to parse this as a date object (which is essential for sorting by date to work. See the [`sortDate` comparator in `sortBy.js`](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/dev/js/common/sortBy.js#L83))

Since 12 NOON is the ideal way to display the time to the user, we may have to include a separate data-attribute containing the time in a format that is always JS parsable (ideally the ISO8601 format). Perhaps something like what was done in #7715. (See: [this diff](https://github.com/TEAMMATES/teammates/pull/7715/files#diff-8ed3a79a64da103b6ee4bcaa7100f0abR37)).

I'll leave it up to the senior devs to decide if the scope of this issue includes adding this datetime data attribute in ISO8601 format to all HTML elements that display date. (This might make solving #1701 easier).

**Comment by HirdayGupta** [comment]
> I'll leave it up to the senior devs to decide if the scope of this issue includes adding this datetime data attribute in ISO8601 format to all HTML elements that display date. (This might make solving #1701 easier).

Requesting confirmation on this before I start work on this issue.

**Comment by HirdayGupta** [comment]
Working on this now.

**Comment by wwhayato** [comment]
まだまださっぱりわかりませんが、クリアな気持ちで、励みます

**Comment by Shashwat-Garg** [comment]
@HirdayGupta Are you still working on this issue ?

**Comment by nidhi98gupta** [comment]
@damithc I would like to work on this issue.

**Comment by damithc** [comment]
> @damithc I would like to work on this issue.

Go ahead @nidhi98gupta
