### ISSUE TITLE
New contributor self intro Thien Bui

### ISSUE THREAD

**Issue by ducthienbui97** [TEAMMATES/teammates#7921]
- **Link to my fork:** e.g. https://github.com/ducthienbui97/teammates

**Screenshot of changes made (as seen on the UI)**
Actually not so much, I have just changed the color of login text from green to white, and I think it's look much better.
![capture](https://user-images.githubusercontent.com/10867758/29119125-42097fae-7d48-11e7-87f1-3b54dcd9f878.PNG)

**Short self-introduction**
I'm Thien Bui,  a computer science student at University of Wollongong, Australia. I'm looking to get involved in open source community. And I think I can learn something from this project.

**Comment by amarlearning** [comment]
Hi @ducthienbui97, welcome to TEAMMATES! You can start by fixing a [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue, then those labeled [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors).
