### ISSUE TITLE
Help Request: Exception thrown when running dev server in eclipse

### ISSUE THREAD

**Issue by AlexM9200** [TEAMMATES/teammates#7923]
- **Operating System: Windows 10
- **JDK Version: 1.7
- **Eclipse / IntelliJ Version (if applicable): Eclipse Neon.3
- **Firefox / Chrome Version (where applicable): Chrome 59.0.3071.115 

**What I was trying to do / What I need help with**
I set everything up and ran the project as a web application but got a few errors and I can't run localhost:8888. I get a message saying HTTP Error, Reason: SERVICE_UNAVAILABLE. I can run the server from the command line and that works fine. Also, when I run the project in eclipse it says "there are errors in the workspace, do I wish to continue?". Would it be because I don't have eclipse installed? I'm just running it from a folder.

**Attempts to resolve the problem**
I cleaned the project, refreshed the project, tried to see what code was causing the exception. Any help would be appreciated. Thanks.

**Comment by whipermr5** [comment]
Do screenshot some of the errors shown in Eclipse.

**Comment by AlexM9200** [comment]
![image](https://user-images.githubusercontent.com/21268058/29164102-585b8cfc-7db6-11e7-8e60-516e61d088af.png)
![image](https://user-images.githubusercontent.com/21268058/29164136-6fe20e96-7db6-11e7-9558-c1bea6c2eba4.png)
![image](https://user-images.githubusercontent.com/21268058/29164185-8cf7389e-7db6-11e7-92d4-8f9dc220e6b0.png)

**Comment by whipermr5** [comment]
Have you followed all the steps in [ide-usage.md](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-usage.md)? Do screenshot the `Problems` view too.
