### ISSUE TITLE
New Contributor self intro Alex Matthews

### ISSUE THREAD

**Issue by AlexM9200** [TEAMMATES/teammates#7927]
Hi I'm a 3rd year software development student from Carlow, Ireland. I want to get some experience with contributing to open source and I think this is the perfect project. Keep up the great work guys.

My Fork: https://github.com/AlexM9200/teammates

Screenshot of changes made:

![image](https://user-images.githubusercontent.com/21268058/29169175-89f7efa8-7dca-11e7-9919-d79f688bc20b.png)

I just made the names bold to make them stand out more and I think it looks better.

**Comment by amarlearning** [comment]
Hi @AlexM9200, welcome to TEAMMATES! You can start by fixing a [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue, then those labeled [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors).
