### ISSUE TITLE
CSS files: fix coding standard violations

### ISSUE THREAD

**Issue by amarlearning** [TEAMMATES/teammates#7931]
Some of the CSS files are not following the CSS Coding Standard as defined by TEAMMATES [here](https://docs.google.com/document/d/1wA9paRA9cS7ByStGbhRRUZLEzEzimrNQjIDPVqy1ScI/pub).
***
| | File Name  | Following Coding Standard not Followed  |
| ------------ | ------------ | ------------ |
| :white_large_square: | [adminAccountDetails.css](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/stylesheets/adminAccountDetails.css)  | [Naming Standards](https://docs.google.com/document/d/1wA9paRA9cS7ByStGbhRRUZLEzEzimrNQjIDPVqy1ScI/pub#h.8aauk3v0ixn6), [Order of attributes](https://docs.google.com/document/d/1wA9paRA9cS7ByStGbhRRUZLEzEzimrNQjIDPVqy1ScI/pub#h.cdhasngawcmb)  |
| :white_large_square: | [datepicker.css](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/stylesheets/datepicker.css)  |    [Order of attributes](https://docs.google.com/document/d/1wA9paRA9cS7ByStGbhRRUZLEzEzimrNQjIDPVqy1ScI/pub#h.cdhasngawcmb) |
| :white_large_square: | [instructorCourseEnroll.css](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/stylesheets/instructorCourseEnroll.css)  | [Naming Standards](https://docs.google.com/document/d/1wA9paRA9cS7ByStGbhRRUZLEzEzimrNQjIDPVqy1ScI/pub#h.8aauk3v0ixn6), [Order of attributes](https://docs.google.com/document/d/1wA9paRA9cS7ByStGbhRRUZLEzEzimrNQjIDPVqy1ScI/pub#h.cdhasngawcmb)  |
| :white_large_square: | [omniComment.css](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/stylesheets/omniComment.css)  | [Order of attributes](https://docs.google.com/document/d/1wA9paRA9cS7ByStGbhRRUZLEzEzimrNQjIDPVqy1ScI/pub#h.cdhasngawcmb), [Hexadecimal Notation](https://google.github.io/styleguide/htmlcssguide.html#Hexadecimal_Notation)  |
| :white_check_mark: | [printview.css](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/stylesheets/printview.css "printview.css")  | **Looks good** |
| :white_large_square: | [teammatesCommon.css](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/stylesheets/teammatesCommon.css "teammatesCommon.css")  | [Naming Standards](https://docs.google.com/document/d/1wA9paRA9cS7ByStGbhRRUZLEzEzimrNQjIDPVqy1ScI/pub#h.8aauk3v0ixn6), [Order of attributes](https://docs.google.com/document/d/1wA9paRA9cS7ByStGbhRRUZLEzEzimrNQjIDPVqy1ScI/pub#h.cdhasngawcmb), [Hexadecimal Notation](https://google.github.io/styleguide/htmlcssguide.html#Hexadecimal_Notation)  |
***

**Comment by damithc** [comment]
Thanks for the report @amarlearning Can one of the @TEAMMATES/seniordevs investigate further and confirm?

**Comment by whipermr5** [comment]
Confirmed.

**Comment by amarlearning** [comment]
@damithc If this is not a <kbd>d.FirstTimers</kbd> issue, I would like to take this one! :sweat_smile:

**Comment by wkurniawan07** [comment]
@amarlearning I will caution you first that the naming standard violations will be very painful to fix.

**Comment by amarlearning** [comment]
@wkurniawan07 aware of that :smile:

**Comment by damithc** [comment]
> @damithc If this is not a d.FirstTimers issue, I would like to take this one!

Not a `FirstTimers` issue. Can take if you want.

**Comment by wkurniawan07** [comment]
@amarlearning if you feel like it, you can fix this one very blatant violation: "We only have one CSS file for the entire website".

**Comment by amarlearning** [comment]
> if you feel like it, you can fix this one very blatant violation

While I was going through the `TM CSS Coding Standard` guide, I marked this _["We only have one CSS file for the entire website"]_ an issue.

But after reading "[_In the future if we have more files, CSS file includes must be done using <link> tags in the HTML/JSP files and NOT using @import in other CSS files._]" this, I changed my mind.

@wkurniawan07 Do you really think that's an issue?

**Comment by wkurniawan07** [comment]
It is. There is no clear separation on which files need to be separated right now, and at the current state such separation creates more confusion than benefits (it already happens right now, am I right?).

**Comment by amarlearning** [comment]
> and at the current state such separation creates more confusion than benefits

@wkurniawan07 exactly. I think we should divide the CSS into three sections `Admin`, `Instructor`, `Student`. This way we can minimize the loading time of every page because the file size will not be too big.

If we combine all the CSS into one file i.e. `teammatesCommon.css`, then the CSS file size will be too high which will affect the loading time of web pages. 

Let me know what you think

**Comment by wkurniawan07** [comment]
> If we combine all the CSS into one file i.e. teammatesCommon.css, then the CSS file size will be too high which will affect the loading time of web pages.

Only the initial loading time will be affected. All subsequent loads will simply load cached CSS file.

**Comment by amarlearning** [comment]
> Only the initial loading time will be affected. All subsequent loads will simply load cached CSS file.

@wkurniawan07 great :+1: 

I want to divide this issue into three seperate PRs:

1. For fixing the coding standards of `adminAccountDetails.css`, `datepicker.css`,  `instructorCourseEnroll.css` and `omniComment.css`

2. For fixing the coding standards of `teammatesCommon.css`.

3. To fix `"We only have one CSS file for the entire website"`

**Comment by wkurniawan07** [comment]
@amarlearning I'd rather you fix everything not naming related in one PR first, then fixing all naming violations in at least one PR. If you're familiar enough with the code base you would understand why.

**Comment by whipermr5** [comment]
Effort tracker, to be updated as each PR is merged:

| PR | Effort |
| - | - |
| #7969 | 2 |
