### ISSUE TITLE
Rubric question: fix cancel question feature

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7933]
Steps to reproduce bug -

1. Add a new rubric question.
2. Enable weights.
3. Add some random weights. (Optional)
4. Cancel adding the new question.
5. Add a new rubric question again. The new question displayed won't have a `Weights` checkbox, and the input fields for weights are vanished.

![1](https://user-images.githubusercontent.com/11662001/29242486-c920223a-7fab-11e7-8426-75ee7cee1537.JPG)

Expected behavior - `Weights` checkbox should be visible and enabled. Also the input fields for weights should also be visible (preferably with values if entered in step 3).

**Comment by uxxSam** [comment]
Working on this
