### ISSUE TITLE
Bug: MCQ and MSQ question: fix cancel question feature

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7934]
Steps to reproduce bug -

1. Add a new MCQ question.
2. Enable `Generate options from` checkbox.
3. Select an option (`Students`, `Teams`, `Instructors`). (Optional)
4. Cancel adding the new question.
5. Add a new MCQ question again. The new question displayed will have the `Generate options from` checkbox enabled, but the option selecting disabled. Input fields for manual options input are visible.

![2](https://user-images.githubusercontent.com/11662001/29242598-ab8c8518-7fad-11e7-8dd7-864c7ba81a30.JPG)

Justification - If the instructor doesn't notice this and fills in the options manually and saves the question, then the manually added options are not considered, `Generate options from` gets saved.

Expected behavior - Drop-down to select `Generate options from` must be enabled (preferably with the option if selected in step 3). Input fields for manual options input should be hidden.

Scope of issue - This bug exists for MCQ and MSQ question types. Add fixes for both.

**Comment by ahsanbagwan** [comment]
I'll be working on this.

**Comment by whipermr5** [comment]
@ahsanbagwan You can remove [this line](https://github.com/TEAMMATES/teammates/blob/a7309a5de74cdef035904d6dff563ce5454d2873/webpack-main.config.js#L50) and re-run `npm run build` to get non-minified files. More info: https://github.com/TEAMMATES/teammates/issues/7532#issuecomment-309023124

**Comment by ahsanbagwan** [comment]
@whipermr5 That helped to add breakpoints in Chrome developer tools. Thanks a bunch.

On the issue front, while debugging the `if` conditional [here](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/dev/js/main/instructorFeedbackEdit.es6#L520) selects the `else` block once the question is cancelled and same type is selected from the new dropdown.

I'm wondering if the ID of the element mentioned [here](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/dev/js/main/instructorFeedbackEdit.es6#L514) is a typo. Is it so?

**Comment by dabbler011** [comment]
@VamsiSangam @ahsanbagwan @whipermr5 can i work on this issue?

**Comment by tshradheya** [comment]
Is anyone working on this? Or can I take up this issue?

**Comment by sukanta-27** [comment]
@tshradheya I am in no authority to say this but, IMO, you have 5 open PRs, you should wait for at least 1-2 of them to get merged before taking up new issues as, if you open PRs for 6-7 issues at the same time and simultaneously work on them, then it might be difficult for other developers to find a issue to work on.

**Comment by dabbler011** [comment]
@whipermr5 @VamsiSangam @damithc I suppose bug is there not only for MCQ and MSQ type questions. For instance while adding any type of question Description is filled and then Adding is cancelled, now add any type of new question Description is retained. Is this a required feature or this shall also be fixed?
