### ISSUE TITLE
Replace 'disabled' attributes from HTML anchor tags

### ISSUE THREAD

**Issue by HirdayGupta** [TEAMMATES/teammates#7943]
Noticed while working on #6634.

A lot of our HTML anchor tags (`<a>`) use the `disabled` attribute to disable clicks on the link. However, according to the dev docs, the `disabled` property is not compatible with the anchor tag. (Sources: [StackOverflow Question](https://stackoverflow.com/questions/18711317/is-disabled-a-valid-attribute-for-an-anchor-tag) and [W3 docs](https://dev.w3.org/html5/html-author/#the-a-element))

So far, I have found the following tag files use the disabled property erroneously:

- feedbackSessionActions.tag
- feedbackSessionPublishButton.tag
- expandCollapseButton.tag
- remindButton.tag
- studentsTable.tag
- studentList.tag
- feedbackResponseCommentRow.tag
- rowActions.tag

**Comment by sujeet14108** [comment]
Will work on this.

**Comment by HirdayGupta** [comment]
@sujeet14108 Note that this issue entails not only removing the `disabled` attribute but also coming up with a suitable alternative.

**Comment by Shels1909** [comment]
Hi I would like to work on this. I think I have a possible alternative for using the html disabled attribute, but want to make sure first that it is in fact viable. The method of disabling the anchor tag follows a similar structure with an if statement: `<c:if test="${not actions.publishButton.actionAllowed || actions.privateSession}"> disabled</c:if>`

From what I've read, disabling an anchor tag with `href="/" onclick="return false;"` is a better practice. My first quick fix was: ` <c:if test="${not actions.allowedToRemind || actions.privateSession}">
            href="/" onclick="return false;" 
        </c:if>`

This fixes the issue of disabling the anchor tag link itself, but the button is still clickable. Adding the bootstrap `.disabled` class however will disable the button using `pointer-events: none`. As an example here is what it looks like all put together for the Remind button on the Instructor home page:

` <a
        <c:if test="${not actions.allowedToRemind || actions.privateSession}">
            href="/" onclick="return false;" class="btn btn-default btn-xs btn-tm-actions session-remind-for-test disabled"
        </c:if>
        class="btn btn-default btn-xs btn-tm-actions session-remind-for-test"
        href="${actions.remindLink}"
        data-fsname="${actions.fsName}"
    > 
        Remind
    </a>
`

I am new to TEAMMATES, so if there is anyway I can communicate my thoughts and ideas better please let me know. Thanks!

**Comment by junkiattan** [comment]
@HirdayGupta 

I would like to take up this issue. Will be submitting a pull request soon
