### ISSUE TITLE
Admin: activity log: use table columns for [Role][Action][Google ID][Name][Email]

### ISSUE THREAD

**Issue by stanislous** [TEAMMATES/teammates#7949]
This look like messy. Therefore creating a table with column and keep attributes separately, will be better
to the users.
![screenshot 842](https://user-images.githubusercontent.com/20964806/29354021-ccb2ce4e-8289-11e7-9513-fdcadae4274a.png)

**Comment by whipermr5** [comment]
Note that this is an admin page, not an instructor page - is only used by one user, the TEAMMATES admin (@damithc). Also, I'm not sure that presenting the data in a table makes it more readable. Could you show a screenshot of your intended changes?

**Comment by damithc** [comment]
@stanislous I agree the UI can be improved, but not worth the effort because the sole user (i.e. me) is fine with the current UI. :-)
