### ISSUE TITLE
AppPage: waitForModalPresence: improve stability

### ISSUE THREAD

**Issue by HirdayGupta** [TEAMMATES/teammates#7959]
The InstructorCourseStudentDetailsEditPageUiTest seems to fail quite often due to `NoSuchElementExceptions`. Should locate the cause and increase the success rate.

It doesn't always cause build failures but sometimes remains as a false symptom on an already failing build (eg: https://travis-ci.org/TEAMMATES/teammates/builds/266035690#L2100)

**Comment by wkurniawan07** [comment]
Function is stable now
