### ISSUE TITLE
FeedbackRankQuestionUiTest: refactor variable names

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7960]
All `Feedback*QuestionUiTest` classes have these variables -

``` java
private String courseId;
private String feedbackSessionName;
```

which are used for tests. Only in `FeedbackRankQuestionUiTest`, these variables have been declared by different names -

```java
private String instructorCourseId;
private String instructorEditFsName;
```

Refactor these variable names in `FeedbackRankQuestionUiTest` for consistency. Use IDE refactor tools for this.

**Comment by AlexM9200** [comment]
Can I work on this?

**Comment by VamsiSangam** [comment]
This is a `d.FirstTimer` level issue. Please have a look at other `d.Contributors` issues.

**Comment by varshav21** [comment]
hi i would really like to take up this issue.Can you guide me on how to get started?
