### ISSUE TITLE
Remove excess space in courseTable.tag

### ISSUE THREAD

**Issue by HirdayGupta** [TEAMMATES/teammates#7961]
In [this line](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/WEB-INF/tags/instructor/home/courseTable.tag#L17) of courseTable.tag, there are two spaces after the `<th`. Reduce this to one space and fix indentation of remaining attributes of that tag accordingly.

Possible tags: `d.FirstTimers`, `a-CodeQuality`.

**Comment by 13472889991** [comment]
How do i start this?
