### ISSUE TITLE
Help Request: compilation problem: not all the classes compile 

### ISSUE THREAD

**Issue by hukh** [TEAMMATES/teammates#7973]
**Operating System: Ubuntu 16.04 LTS
- **JDK Version: 1.8
- **Eclipse / IntelliJ Version (if applicable): not used
- **Firefox / Chrome Version (where applicable): not used

**What I was trying to do / What I need help with**
I trying to compile the classes and test classes and run the tests for some of the reversions. I need to compile the project for the reversion that had bugs and get the both reversions ( with bug and after fixing the bug). This something related to my research. I am not running the project to use as product. I just need to compile and run the tests.

The problem is when I tried to compile the project some of the classes do not compile. Mostly the classes in the pageobjects and driver directories. So when the test is running it showing error (such as)

         java.lang.NoClassDefFoundError: teammates/test/pageobjects/InstructorSearchPage

because the .class file is not in build/classes directory.
I am using command line and gradle 3.5.

Is this part of the project or I missing something? do I have to add code to compile these classes?

**Comment by wkurniawan07** [comment]
@hukh we're yet to support JDK 1.8. Change to JDK 1.7 and see if your problem still persists.
