### ISSUE TITLE
Instructor: Help page and sample course: Remove sexist example

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7980]
A user objected to the example comment `Alice is a good girl coder.` in the InstructorHelpPage as it sounds sexist. Let's replace it with something more politically correct.

**Comment by chowyb** [comment]
There is also an instance of this in the sample course for new instructors, however changing this other instance will likely require use of GodMode (and is not suited for a first timer issue):

```json
"value": "Nice work Alice! You are a very good girl coder! :)"
```

**Comment by damithc** [comment]
Lets remove both at the same time. Upped the level to `Contributors`.

**Comment by davel37** [comment]
Working on this.
