### ISSUE TITLE
Instructor home: fix panel collapsing upon click of dropdown menu caret

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#7981]
As discovered by @damithc, clicking directly on the down caret in the dropdown menus within the panel border causes the entire panel to collapse, instead of displaying the dropdown menu as expected. All four dropdown menus (Students, Instructors, Sessions and Course) are affected. The problem has probably been around since #7389 was merged.

![pasted image at 2017_08_10 12_55 pm](https://user-images.githubusercontent.com/6811428/29610566-2e71402c-882d-11e7-8296-adb50c77c9a9.png)

**Comment by AlexM9200** [comment]
I'll work on this if that's ok

**Comment by whipermr5** [comment]
@AlexM9200 Sure!

**Comment by damithc** [comment]
This can create a bad first impression on new users if they stumble onto it when they use TEAMMATES the first time. Upping the priority.
