### ISSUE TITLE
New contributor self intro Ngoc Vo

### ISSUE THREAD

**Issue by ngocvtdev** [TEAMMATES/teammates#7985]
- Link to my fork: https://github.com/ngocvtdev/teammates
- Screenshot:
![image](https://user-images.githubusercontent.com/24991670/29674214-b137d522-891b-11e7-93d2-8521a719f2f4.png)
 I have changed the color of login button, remove the image at bottom left of main tag in homepage and add box-shadow css.

- My name is Ngoc Vo. I'm a java developer in Viet Nam, I have some background in build back-end service use java, thrift, redis, MySQL and front-ent with basic html, javascript.
I want to contribute to opensource to help other people and learn more about programming.

**Comment by LimeTheCoder** [comment]
Hi, @ngocvtdev, welcome to Teammates! Good job on setting up the dev environment and completing orientation guide. You can start by working on [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue and then move on to [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors) issues. Good luck :)
