### ISSUE TITLE
InstructorStudentRecords: Avoid using jquery object multiple times, extract as variable

### ISSUE THREAD

**Issue by AlexM9200** [TEAMMATES/teammates#7991]
When using a jQuery object multiple times (as is the case here for $(entry)), it is preferable to extract the jQuery object as a variable first (prefixing the variable name with a $ to indicate it is a jQuery object), and then reuse that variable in later calls eg:

Expected:

         const $entry = $(e.target); 
         const courseId = $entry.data('courseid'); 
         const studentEmail = $entry.data('studentemail'); 
         const googleId = $entry.data('googleid'); 
         const fsName = $entry.data('fsname');

Current:
[teammates/src/main/webapp/dev/js/main/instructorStudentRecords.es6](url)
Lines 42 to 46

        const entry = e.target;
        const courseId = $(entry).data('courseid');
        const studentEmail = $(entry).data('studentemail');
        const googleId = $(entry).data('googleid');
        const fsName = $(entry).data('fsname');

The main difference between declaring entry = e.target, followed by using $(entry) later, and declaring $entry = $(e.target) and reusing $entry would be efficiency (no need to create the same object multiple times in the latter case).

@amarlearning I used your issue as a template since it's the same issue in a different file. Hope you don't mind.

**Comment by wkurniawan07** [comment]
This issue is subsumed under #7987.
