### ISSUE TITLE
EntityAttributes: Improve addNonEmptyError(String, List<String>)

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [TEAMMATES/teammates#7995]
`addNonEmptyError(String error, List<String> errors)` appends `error` to
`errors` if `error` is a non-empty string. Callers have to create their
own `List<String>` and pass it into this method repeatedly when checking 
for multiple possible errors.

This is unnecessary.

Let's improve this method by adding a `List<String> errors` field in 
`EntityAttribute` and update the method signature to become 
`addNonEmptyError(String)`. The string with error will be appended to the
new field. Let's also implement `EntityAttribute#getErrors()` so that
callers can retrieve the list of errors. The getter method should
return a defensive copy so that callers cannot update the list in
`EntityAttribute`.

Following this implementation, the list of errors may be repeated if 
`getInvalidityInfo()` is called on the same entity object multiple times.
Let's implement a Template pattern in `EntityAttribute`:

```
public final List<String> getInvalidityInfo() {
	resetErrorsList();
	populateErrorsList();
}

private void resetErrorsList() {
	errors = new ArrayList<>();
}

public abstract void populateErrorsList();
```

Side note: I'm not sure whether this is over-engineering, to resolve a simple issue like that.

**Comment by wkurniawan07** [comment]
Closing as explained in #7996.
