### ISSUE TITLE
EntityAttributes: Remove invalid information methods

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [TEAMMATES/teammates#7996]
Note: Perhaps this issue may require further discussion. If this issue is resolved, then we can close #7995.

Subclasses of `EntityAttributes` can be initalised with invalid values.

This results in a need to verify after initialisation of entities on
whether they are valid or not. For example, in `StudentsLogic`:
```
StudentAttributes originalStudent = getStudentForEmail(student.course, originalEmail);
...
if (!student.isValid()) {
    throw new InvalidParametersException(student.getInvalidityInfo());
} 
```

Let's teach constructors of subclasses to verify that the values passed
in are valid. The constructors can also collect all the values that are
invalid and throw it as a checked Exception. Then, we can remove invalid 
information methods such as `isValid()`, `getInvalidityInfo()` and 
`addNonEmptyError(String, List<String>)`.

**Comment by wkurniawan07** [comment]
@Zhiyuan-Amos, while the issue (and similar ones you opened) may be valid, I'm intending to close all of them now for the reason that the increase in code/design quality does not seem significant. Unlike the other project you're maintaining where code/design quality is the focus, here there is an actual product concerned and given the limited resources we have, if we want to work on this kind of stuff, we have to make sure that it is worth the trouble and the opportunity cost. Marginal increase in code/design quality can hardly be justified if the same resource can be utilised for more important stuffs such as improving performance and usability.

That is not to say I reject this kind of issue entirely; if you open this kind of issue and send a PR immediately (e.g. not more than 2 days) afterwards, I will be glad to accept. It becomes a problem when this kind of issue stays and clogs up the issue tracker. Hope you understand.

**Comment by Zhiyuan-Amos** [comment]
Noted with thanks! ^^ Apologies; thought I was free to finish this up quickly, but ended up being busy with other projects.
