### ISSUE TITLE
Message of the day: fix the missing animated gif 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7998]
There's supposed to be an animated gif here. Seems to be missing.
v5.110

**Comment by uxxSam** [comment]
Working on this

**Comment by wkurniawan07** [comment]
@damithc This is not something within dev's power. The missing gif is sourced from <http://www.comp.nus.edu.sg/~pptlabs/img/zoom-to-area.gif>, and that is what needs to be fixed.

**Comment by damithc** [comment]
> @damithc This is not something within dev's power. The missing gif is sourced from http://www.comp.nus.edu.sg/~pptlabs/img/zoom-to-area.gif, and that is what needs to be fixed.

Thanks for finding the cause. I'll follow up with the PowerPointLabs team to restore that gif.

**Comment by damithc** [comment]
@uxxSam please note my previous comment.

**Comment by uxxSam** [comment]
@damithc I see, thanks for letting me know.

**Comment by damithc** [comment]
Update: the missing gif has been restored. All good now.
