### ISSUE TITLE
GetStudentsAction: prevent access by instructors without view students privileges

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#8000]
Instructors can still access the list of students of a course they do not have privilege to as InstructorStudentListAjaxPageAction does not perform the necessary privilege check.

**Comment by HirdayGupta** [comment]
Working on this.

**Comment by madanalogy** [comment]
Hello, I would like to pick this up. I will go through the previously submitted PR and work from there. I expect to open a PR on this issue in a couple of days

**Comment by xpdavid** [comment]
@madanalogy Note that the result page is not migrated yet in V7. You can pick some `d.*` issue to begin with.

**Comment by jayasting98** [comment]
Hello, I think I can work on this issue.
