### ISSUE TITLE
InstructorFeedbackResultsPage: add section displaying options for instructors

### ISSUE THREAD

**Issue by LimeTheCoder** [TEAMMATES/teammates#8002]
As @damithc mentioned in #7815 it will be good to provide the option for question display view that will define behavior during choosing which responses are related to chosen section and which are not.
Here 4 options:
1) Only giver in section -> all responses where giver in chosen section will be included
2) Only recipient in section ->  all responses where recipient in chosen section will be included
3) Both giver and recipient in section -> only responses where both giver and recipient in chosen section will be marked as related to this section
4) Giver or recipient in section -> responses where giver or recipient in chosen section will be displayed

**Comment by joanneong** [comment]
I would like to give this a shot. Although it seems like quite a big change, @LimeTheCoder seems to have been doing a pretty good job so I will be able to reference his previous pull request and hopefully bring this issue to a close.

**Comment by jacoblipech** [comment]
@joanneong Do you mind if I take over this issue?

@damithc Any suggestion how you want it to look? I am thinking of adding a spinner below the `section` spinner. Alternatively is to add more drop down options other the current `section` spinner but I think it may be more confusing.
<img width="935" alt="screen shot 2018-06-25 at 11 25 57 am" src="https://user-images.githubusercontent.com/28522090/41828947-a8fda096-786a-11e8-8453-80a28eb8c0cc.png">

**Comment by damithc** [comment]
> @damithc Any suggestion how you want it to look? I am thinking of adding a spinner below the section spinner. Alternatively is to add more drop down options other the current section spinner but I think it may be more confusing.

A separate drop down sounds good. May be show/enable it only if a specific section is chosen?

**Comment by jacoblipech** [comment]
<img width="568" alt="screen shot 2018-07-03 at 3 50 18 pm" src="https://user-images.githubusercontent.com/28522090/42206199-00969df2-7ed9-11e8-91ca-e66bfb399d2b.png">

@damithc Do you think this can do this trick? Or maybe a multiple level dropdown menu like below? 

<img width="387" alt="screen shot 2018-07-03 at 3 52 46 pm" src="https://user-images.githubusercontent.com/28522090/42206273-3b56ecb2-7ed9-11e8-9372-811249af5f95.png">

Currently there is no javaScript implemented for `filterEditModal.tag`. Following the previous idea, it will take quite some effort to implement javaScript so as to populate another spinner when a specific section is chosen. On the bright side, this can help to solve the inconsistency of checkbox as well #8726.

**Comment by damithc** [comment]
Both proposed solutions feel like, well, workarounds. :-p
I guess we have to bite the bullet and implement the needed logic in java script.
Another acceptable alternative could be to show the third drop-down all the time.

**Comment by jacoblipech** [comment]
I guess the workaround didn't pass... Sure. I will aim to add javaScript logic to this panel.

**Comment by damithc** [comment]
Actually, you can seriously consider leaving the third dropdown permanently visible. e.g.,

**If showing only a section:**
  [Show response if the giver is in the selected section]
  [Show respones if the evaluee is in the selected section]
  [Show response only if both are in the selected section]

**Comment by jacoblipech** [comment]
@damithc Following your suggestion, it will look something like this in the Edit View Panel. I am just wondering if it will be misleading to instructors as it will always be there. Should I proceed with this?

<img width="473" alt="screen shot 2018-07-04 at 5 09 25 pm" src="https://user-images.githubusercontent.com/28522090/42268056-2cc46556-7fad-11e8-8116-94bdcbb2db44.png">
<img width="475" alt="screen shot 2018-07-04 at 5 09 32 pm" src="https://user-images.githubusercontent.com/28522090/42268057-2d0ed244-7fad-11e8-9515-9cde9b976256.png">

**Comment by damithc** [comment]
I'm willing to live with it :-p. Ideally it should be hidden/disabled when not applicable but that can be done as a future enhancement.
BTW, you can use a bigger modal and make all three dropdowns the same size.
