### ISSUE TITLE
Problems installing TestNG

### ISSUE THREAD

**Issue by olya-chuchuk** [TEAMMATES/teammates#8005]
- **Operating System:Windows 10**
- **JDK Version: JDK 1.7**
- **Eclipse : 4.6.2**

I was trying to set up eclipse for working with the teammates project using this guide https://github.com/TEAMMATES/teammates/blob/master/docs/ide-usage.md. I am stuck in getting TestNG plugin installed. I tried to install it via _Help->Install New Software_ , in "Work with" I pasted "http://beust.com/eclipse" and got the following error:
![default](https://user-images.githubusercontent.com/29196642/29753470-ebdacbba-8b7a-11e7-85d5-2550e666bc9d.png)
Then I found it in Eclipse Marketplace and got the same error. I also tried to change _Window->Preferences->General->Network Connection->Active Provider_ from Native to Direct - still didn't work. I tried to go to _Window->Preferences->Install/Update->Available Software Sites_ and tried to reload  "http://beust.com/eclipse" site. Got the following:
![default](https://user-images.githubusercontent.com/29196642/29753506-ae8da10a-8b7b-11e7-82ff-841699b825c0.png)

Could you please help me with this issue as I really want to become a contributor for your project=)
Thank you.

**Comment by wkurniawan07** [comment]
Hi @olya-chuchuk, this looks like a general Eclipse error to me. See if finding your own solution in Google/StackOverflow works 🙂
