### ISSUE TITLE
Update aboutUs page to reflect Aug 2017 team structure

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8008]
@HirdayGupta @VamsiSangam @sujeet14108 @LimeTheCoder @Mynk96 @amarlearning can you post here suitable photos to be used in the [About Us](http://teammatesv4.appspot.com/about.jsp) page?

Requirements: clean background (no need to remove background), shoulders visible, 
Preferred: informally dressed, smiling :-)

**Comment by HirdayGupta** [comment]
@damithc Sir, would [this](https://user-images.githubusercontent.com/18088721/29763673-c7175c90-8bf1-11e7-951d-562e704b2ce3.png) be okay?

**Comment by VamsiSangam** [comment]
Is [this pic](https://avatars1.githubusercontent.com/u/11662001?v=4&s=460) ok sir? It is the same as my current GitHub pic.

**Comment by amarlearning** [comment]
Sir will this work? :sweat_smile: 
![9383897_burned](https://user-images.githubusercontent.com/9383897/29768051-603f613c-8c02-11e7-9605-a212fda1b07c.jpg)

**Comment by sujeet14108** [comment]
Here is the [pic](https://user-images.githubusercontent.com/9781422/29774539-615fa12c-8c1f-11e7-8c28-b13e6f5abe9a.jpg) :)

**Comment by damithc** [comment]
> Here is the pic :)

@sujeet14108 shoulders need to be visible.

**Comment by damithc** [comment]
> Sir, is this image fine?

@Mynk96 too blurry/noisy. I should be able to extract you from the background cleanly, which requires a relatively clean image.

**Comment by wkurniawan07** [comment]
@LiHaoTan you should, too

**Comment by damithc** [comment]
> @LiHaoTan you should, too

yup.

**Comment by damithc** [comment]
@sujeet14108 @LimeTheCoder @Mynk96  reminder

**Comment by sujeet14108** [comment]
@damithc check this [pic](https://user-images.githubusercontent.com/9781422/30046135-f9c88f1c-9225-11e7-836c-5db353dac09c.jpg) :sweat_smile:

**Comment by Mynk96** [comment]
@damithc Check this pic ![img_4893](https://user-images.githubusercontent.com/17481466/30111553-bae034b0-932b-11e7-8665-2bb801a66ec6.JPG)

**Comment by Mynk96** [comment]
@damithc check this [pic](https://user-images.githubusercontent.com/17481466/30111618-019dd754-932c-11e7-88bf-089af018b854.JPG) :)

**Comment by wkurniawan07** [comment]
@LimeTheCoder let's not forget to post your photo here

**Comment by damithc** [comment]
I've attached the processed photos. Need to resize though.

@LimeTheCoder please upload your photo soon. Otherwise we wont be able to include you in the page.

![sujeet](https://user-images.githubusercontent.com/1673303/30905401-42aeb246-a3a7-11e7-893b-dc154b0b033c.png)
![vamsi](https://user-images.githubusercontent.com/1673303/30905406-42ea9e78-a3a7-11e7-91ea-3dca89ce1891.png)
![amar](https://user-images.githubusercontent.com/1673303/30905405-42d9e70e-a3a7-11e7-8c15-068890e0813c.png)
![hirday](https://user-images.githubusercontent.com/1673303/30905566-c2d22336-a3a7-11e7-9255-52a65e251434.png)
![mayank](https://user-images.githubusercontent.com/1673303/30905403-42ceef66-a3a7-11e7-8af0-be69a4ee95d1.png)
![lihao](https://user-images.githubusercontent.com/1673303/30906165-8db6a6ac-a3a9-11e7-9972-4d6c52110686.png)

**Comment by damithc** [comment]
* Move Hong Jin, Josephine, Jun Hao, and Thyagesh to 'past members' as they haven't been active that much in recent times.
* Wilson --> Project Mentor
* Yuan Bin --> Project Lead
* John, Thenaesh, Yi Min --> Area Lead 
* Li Hao --> Senior Developer
* Amar Prakash Pandaey, Hirday Gupta, Mayank Harsani, Sujeet, Vamsi Sangam,   --> major contributor
* Yong Jie, Lakmal, Serhii, Tarun --> move to past members
* Taras Sakharchuk : to be added as major contributor if photo is uploaded

**Comment by LimeTheCoder** [comment]
Guys, really sorry for the delay here. I'll deliver photo within next few days.

**Comment by damithc** [comment]
Yes, we can go ahead with the update. 
If there is no photo, we can add @LimeTheCoder into a section that already have others without photo. e.g. `Past committers`.
I don't want to use placeholders because it gives a bad impression that we are unable to get photos from our developers.

**Comment by wkurniawan07** [comment]
> I don't want to use placeholders because it gives a bad impression that we are unable to get photos from our developers.

Not necessarily, at least for me. As evident right now, we have tried albeit with no success. Some people may also want to stay unidentifiable by face and we have to respect such request if it ever happens (although I don't think @LimeTheCoder here is one such case). The point is that I don't believe placeholders correlate to "bad impressions".
Also, "past committers don't have photo" is just a coincidence. When the current committers become past committers, that statement no longer applies.

**Comment by damithc** [comment]
Good point: some developers may not want their photo on the page.  
I'd really rather not use the egghead image in the page though, as it ruins the page and gives it an 'incomplete' feeling. If at all, we can list those people at the bottom of the respective list, without a dummy photo, so that it blends in and isn't the first thing to catch attention of a casual viewer.

**Comment by wkurniawan07** [comment]
@LimeTheCoder any chance you can send us photo soon?
