### ISSUE TITLE
Rank recipients: support min/max number of choices

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#8009]
Add support for minimum/maximum options to be ranked for Rank (recipients) type question.

**Comment by wkurniawan07** [comment]
@VamsiSangam any timeline on when this will be worked on? Ideally, all "support min/max number of choices" PRs will be released under the same milestone.

**Comment by VamsiSangam** [comment]
I was planning to do this after #7509 gets merged, because there's a quite a lot of code I can use from that PR.

**Comment by wkurniawan07** [comment]
@VamsiSangam you should not wait; you can start doing the work now and after #7509 is eventually merged you will simply push the works for this issue.

**Comment by wkurniawan07** [comment]
Hi @VamsiSangam, shall we proceed with this one?

**Comment by VamsiSangam** [comment]
Yes, working on this.

**Comment by VamsiSangam** [comment]
I have a doubt here. What should we do when the recipient is `Giver's team members` or `Giver's team members and giver`? In this scenario, the number of recipients depends upon the giver, so how can we limit the values the instructor gives inside the minimum/maximum options to be ranked input box?

Eg., suppose the recipient is `Giver's team members and giver`, and the instructor has set the minimum options to be ranked to 4. What if there's a team with only 3 members?

**Comment by damithc** [comment]
> Eg., suppose the recipient is Giver's team members and giver, and the instructor has set the minimum options to be ranked to 4. What if there's a team with only 3 members?

I think the team size should override the min/max as necessary. e.g. `max=4` really means, `4 or team size, whichever is lower`. Similarly for min. Will that work?

**Comment by VamsiSangam** [comment]
I understand the `max=4` case, but what should happen when `min = 4, team size = 3`?

**Comment by damithc** [comment]
Similar: take `specified min or team size, whichever is lower`

**Comment by VamsiSangam** [comment]
Sir then in that case, the student would have to rank all the options, is this the expected behavior?

**Comment by damithc** [comment]
> Sir then in that case, the student would have to rank all the options, is this the expected behavior?

Yes. I can't think of any other viable alternative.
