### ISSUE TITLE
Issue in setting up the project in Eclipse

### ISSUE THREAD

**Issue by tulikarai** [TEAMMATES/teammates#8010]
**Windows 10**
- **JDK7**
- **Eclipse Neon:**
- **Firefox / Chrome Version (where applicable):**

**Setup project in Eclipse**

**Comment by tulikarai** [comment]
I follow all the steps as given in the document to setup TEAMMATES project in Eclipse, but after clean and build it still showing 852 errors

**Comment by Somashekhark** [comment]
Hi,
 Even i am getting the Error after Importing from the Git Hub 
 Error in the package itself,please let me what i have to do to resolve and run  successfully
![image](https://user-images.githubusercontent.com/16729363/29803680-367ba650-8c9b-11e7-9682-7804899e9a7e.png)

**Comment by tulikarai** [comment]
does it matter if my workspace directory of eclipse is different from the project root directory ?
eclipse workspace directory : c:
project root directory : c:/git/teammates

**Comment by wkurniawan07** [comment]
@tulikarai 

> after clean and build it still showing 852 errors

Can you post a screenshot of the errors shown here?

> does it matter if my workspace directory of eclipse is different from the project root directory ?

It does not because my own Eclipse workspace directory and TEAMMATES project root directory is different.

**Comment by wkurniawan07** [comment]
@Somashekhark, do open up your own issue in order not to clog up other person's issue thread. I will answer your question here just this one time: you should not import the project directly from GitHub. Follow the steps given in our [project setup document](https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md) as well as [IDE setup document](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-usage.md).
