### ISSUE TITLE
New contributor self intro kwilsono

### ISSUE THREAD

**Issue by kwilsonO** [TEAMMATES/teammates#8012]
a. No staging server yet, just local.
b. https://github.com/kwilsonO/teammates/tree/tinker

![teammatesscreenshot](https://user-images.githubusercontent.com/7905659/29830972-ba33415e-8cb1-11e7-8188-86e0e17e0d72.png)

d. Short Bio/Intro:

My name is Kyle Wilson, I'm 24, I'm a back end developer, and I have some free time so figured I'd find an open source project to contribute to!

**Was planning on trying to pick up and get a PR in for #7765. Seemed achievable!

**Comment by kwilsonO** [comment]
https://github.com/TEAMMATES/teammates/pull/8013

**Comment by whipermr5** [comment]
Hey Kyle, welcome to TEAMMATES! Good job setting everything up the dev server! I see you've already submitted a PR for a `d.FirstTimers` issue; that's good! While waiting for it to be reviewed, feel free to take a look at `d.Contributors` issues if you're bored :)
