### ISSUE TITLE
Move `static-analysis.md` from root folder to `docs/`

### ISSUE THREAD

**Issue by AlexM9200** [TEAMMATES/teammates#8016]
static-analysis.md was accidently moved into the root folder. It should be moved back into the docs folder.

**Comment by LiHaoTan** [comment]
@AlexM9200 it seems all links to the static analysis documentation is broken, i.e.
`docs/README.md`
`docs/development.md`
`docs/usage.md`.

Though we should rather put it another way, the static analysis document is in the wrong folder. Can you update your issue description accordingly?

**Comment by eei34** [comment]
Sorry, first timer...

**Comment by wkurniawan07** [comment]
I was the one reviewing that PR, my bad for this 😓
