### ISSUE TITLE
New contributor self intro @eei34

### ISSUE THREAD

**Issue by eei34** [TEAMMATES/teammates#8019]
Link: https://github.com/eei34/teammates
UI Modification:

![image](https://user-images.githubusercontent.com/31013163/29998734-a952321c-9000-11e7-842a-b4677406f6b0.png)

My name is Eva, I recently graduated with a degree in MIS. I am looking to start a career in software development. I look forward to contributing!

**Comment by LimeTheCoder** [comment]
Hello, @eei34, welcome to Teammates! You can start with [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue and after that try to work on [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors) issues. Good luck!

**Comment by eei34** [comment]
Hi @LimeTheCoder. So excited to get started! Thanks!
