### ISSUE TITLE
setting-up.md: IntelliJ IDEA: remove `experimental; limited support` status

### ISSUE THREAD

**Issue by LiHaoTan** [TEAMMATES/teammates#8022]
IntelliJ IDEA configuration should be considered stable by now. While there are still improvements that can be made to improve the setup, the current setup should not pose any problems for development.

**Comment by damithc** [comment]
Yup, I've been using it all this time and it's pretty stable now. 👍

**Comment by zandraaperjesi** [comment]
Hi, first timer here. Can I claim this issue?

**Comment by LiHaoTan** [comment]
@zandraaperjesi sure please go ahead.

You are right that mentioning full support will become useless, it should be easy to infer that it should be removed as well. 😄

**Comment by zandraaperjesi** [comment]
@LiHaoTan right, I removed the Eclipse status as well. :)

also this migth be off topic, but when following the projects process.md, at Step 3/ 2, about syncing with the main repo, when using `git checkout -b 3942-remove-unnecessary-println` for switching back to your branch git gives an error, that the branch already exists, isn't it supposed to be just git checkout branch-name without the -b?

**Comment by wkurniawan07** [comment]
> the branch already exists, isn't it supposed to be just `git checkout branch-name` without the `-b`?

@zandraaperjesi you're exactly right on that, good catch!

**Comment by whipermr5** [comment]
@zandraaperjesi Thanks! Could you help us open a new issue about fixing the wrong command?

**Comment by zandraaperjesi** [comment]
@whipermr5 I would love to help, however I don't know how to. Could you point me somewhere where I could read about how to open an issue properly? :)
