### ISSUE TITLE
Instructor: home page: fix action buttons going out of table

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8025]
![image](https://user-images.githubusercontent.com/1673303/30094672-32c40e2e-9300-11e7-93e7-fa1e9540a914.png)

**Comment by stanislous** [comment]
Can I work on this?

**Comment by VamsiSangam** [comment]
Sure, please go ahead.

**Comment by VamsiSangam** [comment]
@damithc sir, on which page is this issue occurring? Instructor homepage seems fine on my up-to-date master branch -

![capture](https://user-images.githubusercontent.com/11662001/30096957-b8f66c56-92f8-11e7-9355-6e67e209def6.JPG)

**Comment by damithc** [comment]
> @damithc sir, on which page is this issue occurring? Instructor homepage seems fine on my up-to-date master branch -

It's the home page, on your #7509 branch. It's possible that the problem depends on the contents of the table.

**Comment by VamsiSangam** [comment]
It is not occurring on my #7509 branch as well sir.

**Comment by damithc** [comment]
Let's wait to see if recur. It's not a major problem anyway if it doesn't happen to everybody.

**Comment by whipermr5** [comment]
It happens to me too. I think it's like that on smaller resolutions?

**Comment by LiHaoTan** [comment]
It occurs for me as well, though I suspect it occurs on all resolutions though I'm not sure why @VamsiSangam is not able to replicate it, can you refresh your cache?

![image](https://user-images.githubusercontent.com/13617389/30146819-d4476e40-93cc-11e7-8c61-2c266130811a.png)

**Comment by VamsiSangam** [comment]
The UI defect does not happen in my Firefox but occurs on my Chrome.
