### ISSUE TITLE
New contributor self introduction: Gaurav

### ISSUE THREAD

**Issue by gaurav122197** [TEAMMATES/teammates#8027]
Link to my fork: https://github.com/gaurav122197/teammates
I am Gaurav Khandelwal, a Computer Science and Engineering undergraduate. I am looking forward to contributing to this project.

**Comment by whipermr5** [comment]
Hello @gaurav122197, welcome to TEAMMATES! After completing the steps in the [orientation guide](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md), feel free to work on a `d.FirstTimers` issue, then move on to `d.Contributors` issues :)
