### ISSUE TITLE
feedbackSubmissionsEdit.es6: remove unnecessary if condition

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#8035]
In the `validateMsqQuestions()` method of `feedbackSubmissionsEdit.es6`, an `if` statement has been put near [this line](https://github.com/TEAMMATES/teammates/blob/master/src/main/webapp/dev/js/main/feedbackSubmissionsEdit.es6#L656) -

```js
if (numOfSelectedChoices === 1
        && $(`input[name="responsetext-${qNum}-${recipientIndex}"][value=""]`).prop('checked')) {
    // Selecting "None of the above" as the only option is a valid response
    recipientIndex += 1;
    continue;
}
```

This `if` condition was meant for selecting `None of the above` options when min/max options for MSQ questions were enabled.

According to the current implementation, we are not even displaying `None of the above` option when min select-able options is enabled, this `if` condition can be removed safely.

**Comment by AlexM9200** [comment]
Can I take this?

**Comment by VamsiSangam** [comment]
By difficulty level, this is a `d.FirstTimers` issue. Please take up a [`d.Contributors`](https://github.com/TEAMMATES/teammates/issues?q=is%3Aissue+is%3Aopen+label%3Ad.Contributors) issue of your choice :blush:

**Comment by AlexM9200** [comment]
No problem 😁

**Comment by AnmolGrewal** [comment]
So to do this, you pull and fix the issue and make a push request?

**Comment by whipermr5** [comment]
@AnmolGrewal Have a look at [process.md](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md) and other documentation in the same folder :)

**Comment by PJozeph** [comment]
can i handle it ?

**Comment by shivarajnesargi** [comment]
Can I handle it?

**Comment by whipermr5** [comment]
Everyone is free to submit a PR anytime they're ready :) We'll accept the one that best follows our requirements.

**Comment by jnisky** [comment]
Ok I made my first attempt at fixing this issue. Take a look.
