### ISSUE TITLE
new contributor problem

### ISSUE THREAD

**Issue by shaharyar-shamshi** [TEAMMATES/teammates#8038]
I am very eager to contribute in the teammates project and setting up the enviroment for it but following error occured can anyone help me
I have followed each step in Settingup.md but when I move to development.md and run command  sh ./gradlew appengineRun
It give the error of build failed 
for whole of the the error follow the following link
[https://docs.google.com/document/d/1vXYXDLop-eMq-Ki3wDA5l_LCP8OK4-JKa1FUrvuXwJ8/edit?usp=sharing](url)
 can anyone help how to resolve it so that I can move forward towards contribution

**Comment by whipermr5** [comment]
For future reference, this is the output shown in your link:
```
:appengineDownloadSdk
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not resolve com.google.appengine.tools:appengine-gcs-client:0.6.
  Required by:
      project :
   > Could not resolve com.google.appengine.tools:appengine-gcs-client:0.6.
      > Could not get resource 'https://repo1.maven.org/maven2/com/google/appengine/tools/appengine-gcs-client/0.6/appengine-gcs-client-0.6.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/com/google/appengine/tools/appengine-gcs-client/0.6/appengine-gcs-client-0.6.pom'.
            > repo1.maven.org: Temporary failure in name resolution
```

Looks like a temporary network error; have you tried several times?

**Comment by shaharyar-shamshi** [comment]
I am trying since last two days still the same result

**Comment by shaharyar-shamshi** [comment]
problem is solved Actually my terminal was not able to connect to proxy server my badluck
