### ISSUE TITLE
error while setting in eclipse ide

### ISSUE THREAD

**Issue by shaharyar-shamshi** [TEAMMATES/teammates#8051]
when I set up the enviroment in Eclipse Ide the method of AppPage.java 
public static LoginPage createCorrectLoginPageType(Browser browser) {
        return getNewPageInstance(browser, TestProperties.isDevServer() ? DevServerLoginPage.class : GoogleLoginPage.class);
    }
gave the Error

**Comment by whipermr5** [comment]
You need to follow the IDE setup [instructions](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-usage.md#eclipse-ide) exactly (choose JDK 1.7, not 1.8).

**Comment by dipzzzz** [comment]
Use correct JDK with your setup.
