### ISSUE TITLE
Update user map for Aug 2017

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8056]
Similar to #7424 

Institutions to add:

Australia | Monash University
-- | --
Australia | Queensland University of Technology
Australia | University of New South Wales
Australia | University of Melbourne
Brazil | IFRJ
Brazil | Universidade Catolica de Brasilia
Brazil | University of Brasilia
Canada | Cégep du Vieux-Montréal
Canada | Centennial College
Canada | Centennial College
Canada | Fleming College
Canada | Ryerson University
Colombia | Universidad del Norte
Finland | Pihlajamäen ala-asteen koulu
Germany | Hertie School of Governance
Germany | Philipps-Universität Marburg
Germany | Stuttgart Media University
Malaysia | HELP University
Malaysia | Universiti Tunku Abdul Rahman
Malaysia | University of Malaya
Mauritius | Afrian Leadership University
Mexico | UAS
Netherlands | Eindhoven University of Technology
Netherlands | Leiden University College
New Zealand | Eastern Institute of Technology
New Zealand | Massey University
New Zealand | University of Auckland
New Zealand | University of Auckland
New Zealand | University of Canterbury
Norway | Høgskolen i Oslo og Akershus
Philippines | De la Salle University
Philippines | Miriam College
Singapore | CWSS
Singapore | Nanyang Polytechnic
Singapore | Ngee Ann Polytechnic
Singapore | Singapore Institute of Technology
Singapore | Singapore Polytechnic
Singapore | SUTD
South Africa | University of Johannesburg
Sweden | Jönköping International Business School
Thailand | Thammasat University
Turkey | Credemy
UK | City of London School for Girls
UK | University College London
UK | University of Bradford
UK | University of Portsmouth
USA | AGS
USA | Arizona State University
USA | Bettendorf High School
USA | Bryant University
USA | C/3-13IN Basic Training
USA | CCSD59
USA | Central Oregon Community College
USA | Chaffey College
USA | CSU Sacramento
USA | Elon University
USA | Florida International University
USA | George Washington University
USA | Georgia Tech
USA | Georgia Tech
USA | Harvey Mudd College
USA | Indiana State University
USA | Indiana State University
USA | Jackson Heights Middle School
USA | Medical College of Wisconsin
USA | Medical College of Wisconsin
USA | Miami University
USA | Miami University
USA | Michigan State University
USA | Michigan State University
USA | Mississippi State University
USA | Montclair High School
USA | Nevada State College
USA | New England Insitute of Technology
USA | New Mexico State Univeristy
USA | North Carolina State University
USA | Northeastern University
USA | Northern Arizona University
USA | Northwestern College
USA | PACE
USA | Pitzer College
USA | Presbyterian Christian School
USA | San Diego State University
USA | Seattle Academy of Arts and Sciences
USA | Southeast Community College
USA | Southern Illinois University Edwardsville
USA | Spring Hill College
USA | University at Albany
USA | University at Albany, SUNY
USA | University if Minnesota
USA | University of Alabama at Birmingham
USA | University of California Berkeley
USA | University of Dallas
USA | University of Florida
USA | University of Kentucky
USA | University of Maryland, College Park
USA | University of Massachusetts Boston
USA | University of Minnesota
USA | University of North Carolina at Charlotte
USA | University of South Dakota
USA | University of Texas at Arlington
USA | University of Texas at Austin
USA | University of the Incarnate Word
USA | University of Washington
USA | University of West Florida
USA | West Chester University
USA | Western Carolina University
USA | Western Kentucky University
USA | William Penn University
USA | Worcester State University

**Comment by g3chenyigmailcom** [comment]
Can I do this, please?

**Comment by whipermr5** [comment]
@g3chenyigmailcom Sure; just follow our [process](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md).

**Comment by dipzzzz** [comment]
can i take this issue?

**Comment by ashu-beckham** [comment]
assign it to me.

**Comment by whipermr5** [comment]
@ashu-beckham There's already an ongoing PR for this; you may want to pick another issue :)

**Comment by SiddharathGupta** [comment]
@whipermr5 Can you please suggest me a first-timer issue? I am interested in working on this issue as well.

**Comment by whipermr5** [comment]
@SiddharathGupta #7754 is easy and yet quite an important fix :)

**Comment by dipzzzz** [comment]
can someone please help me in solving this issue?How do I solve this issue?

**Comment by dipzzzz** [comment]
@damithc sir can you please help me in solving this issue.I am got getting this.I am bit afraid to make changes because if something goes wrong with me it will affect our project and i dont want this to happen.

**Comment by SiddharathGupta** [comment]
Alright, I will do this.
