### ISSUE TITLE
New contributor self intro Florian DIGNE

### ISSUE THREAD

**Issue by fdigne** [TEAMMATES/teammates#8062]
Issue Title: New Contributor Self-Intro: [your real name]

Copy-and-paste the following template to the issue tracker and fill it in with relevant details:

- **Link to my app: http://4-18-dot-teammates-floriandigne.appspot.com
- **Link to my fork:** e.g. https://github.com/fdigne/teammates

**Screenshot of changes made (as seen on the UI)**

![capture d ecran 2017-09-29 a 14 30 20](https://user-images.githubusercontent.com/25439995/31015966-0cfa6e38-a523-11e7-8a29-1d61e198baef.png)

**Short self-introduction**
Hello, 

My "real" name is Florian Digne. I'm graduating an Engineer Diploma (last year of studies). I would like to contribute to Teammates to increase my skills in development (see my Linked In profile at https://www.linkedin.com/in/florian-digne-5a2796115/ 
Thank you for giving me some issues to look after.
Florian.

**Comment by chowyb** [comment]
Hi @fdigne,

Welcome to TEAMMATES! Feel free to work on a `d.FirstTimers` issue to start off, then move on to `d.Contributors` issues 😄
