### ISSUE TITLE
student's sign up . so that other students can also check for available courses

### ISSUE THREAD

**Issue by rajatrj** [TEAMMATES/teammates#8064]

**Comment by whipermr5** [comment]
Hello @rajatrj, could you elaborate more?

**Comment by rajatrj** [comment]
i am emphasizing on sign up of general user so that students from various universities could register themselves with teammates and they could provide their teacher's  email and feedback and it could be directly sent to teacher by anonymous means .. (issues of big data may arise )

**Comment by damithc** [comment]
Interesting feature suggestion @rajatrj 
But it's not in the scope of our product vision. Thanks for the suggestion anyway. 👍
