### ISSUE TITLE
issue regarding setting up a development environment

### ISSUE THREAD

**Issue by dipzzzz** [TEAMMATES/teammates#8066]
Is there any video to see"HOW TO SET UP TEAMMATES DEVELOPMENT ENVIRONMENT"so that a newbie  can know whether he/she has set up a right teammates development environment?

**Comment by whipermr5** [comment]
There is no video, but there are clear steps to follow in our docs. Do take some time to read them.
https://github.com/TEAMMATES/teammates/tree/master/docs
