### ISSUE TITLE
inquiry about membership

### ISSUE THREAD

**Issue by dipzzzz** [TEAMMATES/teammates#8069]
my name is not yet included in the "members"list of Teammates.Please someone add me to the "members"list of TEAMMATES so that i can contribute to TEAMMATES.My full name is DEEPIKA KAMLESH TIWARI.Can I contribute to TEAMMATES without my name in members list?will it be legal to do so?

**Comment by thenaesh** [comment]
Hi Deepika, the members group is reserved for regular contributors, so that it is easy to assign them issues. You don't need to be part of the group to contribute. Feel free to pick one of the issues labelled `d.FirstTimers` and have a go!

**Comment by dipzzzz** [comment]
thank you @thenaesh
