### ISSUE TITLE
process.md: fix git command for switching branch in step 3 / 2

### ISSUE THREAD

**Issue by zandraaperjesi** [TEAMMATES/teammates#8076]
**Description of feature/enhancement**
In process.md **Step 3: Fix the issue** / 2. the instruction for switching branch tells you to type
`git checkout -b 3942-remove-unnecessary-println`
however it should be
`git checkout 3942-remove-unnecessary-println`

**Justification**
This typo could be quite confusing for someone who is not familiar with git. Fixing it would make it easier to follow the process guidelines for new contributors.

**Comment by eliotw** [comment]
I'll do this.
