### ISSUE TITLE
Student: submit responses: give a clearer indication of submission failure

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8085]
There are several cases of students complaining that their submission was never recorded but there was no indication of any problem. 
Suggested:
1. Determine what's the current behavior if the submission failed
2. If the current behavior is not clear enough, tweak it to give a better indication of failure.

**Comment by uxxSam** [comment]
Hi, I would like to take a look into this issue.

**Comment by uxxSam** [comment]
UPDATE: 
After a week of investigation, I was not able to reproduce the situation described above. If the Internet went down while the student is trying to submit a response, he will see a page that says cannot connect to the server instead seeing no indication of the problem. I'm wondering if there is more detail about how this issue occurred from the students. 

Currently we do not have any indication of submission failure to the user. FeedbackSubmissionEditSaveAction.java shows the user a warning message if there is error (invalid response) in the response and a success message if the new response is saved without error. If the user sees a success message, his response should have been saved. 

I'm not sure where to go from here. Any advice will be appreciated, thanks!

**Comment by damithc** [comment]
Thanks for investigating the issue @uxxSam 
It is possible that students closed the browser after a few seconds without waiting for a failure/success message.

You can try this: load submission page. shutdown server. try to submit.

The other possibility is that the server is overloaded at the time of the submission and the connection times out. But I'm not sure how to reproduce it. 

Perhaps we can make the button text more informative? e.g. `Submitting... Please wait for confirmation`

**Comment by damithc** [comment]
No longer applicable. This problem was most likely caused by #8156 which mislead students to think they submitted when their click only triggered the tooltip
