### ISSUE TITLE
Rank recipients: remove unnecessary feedback paths

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#8087]
For Rank (recipients) question, it doesn't make sense to have feedback paths where the recipient is `Self` or `None`. Remove/disable these feedback paths for rank recipients.

**Comment by VamsiSangam** [comment]
Working on this.

**Comment by LuLechuan** [comment]
Hi, since the PR related to this issue by @VamsiSangam  has been closed for a while, can I work on this issue? Thanks!

**Comment by damithc** [comment]
> Hi, since the PR related to this issue by @VamsiSangam has been closed for a while, can I work on this issue? Thanks!

Sure @LuLechuan
