### ISSUE TITLE
Convert *.es6 back to *.js

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#8099]
Previously, it was necessary as the `*.es6` files were placed in the same directory as the transpiled `*.js` files. Now that the pre-transpiled files are placed somewhere, this is no longer necessary.
Also, `*.es6` is not a standard practice for naming JS files and they don't benefit from syntax highlighting from IDEs and text editors.

**Comment by LiHaoTan** [comment]
@wkurniawan07 IntelliJ does recognize `.es6` as an extension but `.js` is definitely the norm.
