### ISSUE TITLE
New Contributor Self-Intro: Adam Stefaniak

### ISSUE THREAD

**Issue by goodengrish** [TEAMMATES/teammates#8101]
Hello,

I am Adam Stefaniak, a student at the Faculty of Sciences Jean Perrin in Lens (Université d'Artois: http://www.univ-artois.fr/), studying computer science. I am at the moment at my 4th year (one year remaining).

I am writing this because three of my colleagues and myself are working under the tutelage of Daniel LeBerre, who is a professor and searcher, respectively at the Faculty of Sciences Jean Perrin and the CRIL (further informations are provided here: http://www.cril.univ-artois.fr/~leberre/).

We had to choose an open source project and work on it.
Among our work to provide to our professor, we have to answer different questions each week concerning the TEAMMATES project and try (at the end of the semester) to give a technical contribution.

I hope someone can help me and my friends by answering some of our questions in order to fulfil our professor request.

My question for this week is: Is there a way to know TEAMMATES project's timeline (with key dates) ?

Thank you in advance,

Adam Stefaniak.

**Comment by wkurniawan07** [comment]
Hi @goodengrish, welcome to TEAMMATES!

This is a rather interesting request and probably the first of its kind here, but I'll try my best to accommodate.

For starter, allow me to clarify one thing first. When you asked for "timeline", what kind of details are you looking for? Is it the user-facing features (e.g. new features/improvements added from time to time), the developer-facing features (e.g. adopting new technology/framework/architecture etc.), the business side (e.g. achieving 100K users by certain date), or others?

**Comment by goodengrish** [comment]
Hello @wkurniawan07, thank you :)

Actually we need to know the main technical changes (developer-facing features), the main functional changes(user-facing features) and the milestones of the project (for example, the big features which added great changes in the use of TEAMMATES).

Is that possible for you to provide me an answer from the start of the project ?

Thank you in advance for your answer (I know my request is pretty tough !).

**Comment by damithc** [comment]
@goodengrish you may want to clarify with your prof exactly how you are supposed to answer these questions. Simply forwarding these questions to us doesn't sound like a good way to learn. May be you are supposed to find answers by studying the project history and available documentation? Otherwise it looks a bit like students asking others to do their homework :-p

**Comment by goodengrish** [comment]
@damithc This is our third week studying the project, and yes we are studying TEAMMATES by ourselves. I asked if someone could help me with this question because I am struggling finding the milestones of the project.
For the moment this is the only question we have issues to answer.

For you to clarify, I attached the file with all the questions.
[skeleton.txt](https://github.com/TEAMMATES/teammates/files/1385347/skeleton.txt)

**Comment by damithc** [comment]
Understood @goodengrish 
As for milestones, we do not have concrete deadlines. We reach milestones as and when we can, based on available resources. Some of our current focus areas are: 
* improving performance, fault tolerance, UX
* migrating to Java 8, keeping up with updates to the underlying Google App Engine platform, 
* adding LTI support

**Comment by goodengrish** [comment]
Okay, thank you for answer.
This will be useful for our group :)
