### ISSUE TITLE
New contributor self intro Nathan Baihly

### ISSUE THREAD

**Issue by ncbaihly** [TEAMMATES/teammates#8103]
Here is the link to my deployed app: https://teammates-nathan.appspot.com/

Link to my fork: https://github.com/TEAMMATES/teammates (see branch tinker for changes)

I made some styling changes to add a little contrast to the login buttons to hopefully make them stand out a little more. 

![teammates-tinker](https://user-images.githubusercontent.com/3604022/31589220-0c5d0890-b1cc-11e7-915f-d57e09ade87a.png)

Hello, my name is Nathan Baihly, I graduated this past spring with a BS in Computer Science. I've always wanted to contribute to an open source project and this project seems to fit my interests and skills pretty well. 

Thanks!

**Comment by whipermr5** [comment]
Hey Nathan, welcome to TEAMMATES! Good job setting everything up correctly! You can get your feet wet by working on a `d.FirstTimers` issue, then move on to `d.Contributors` issues :)
