### ISSUE TITLE
Testing using Firefox: fail to load URL sometimes

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8105]
When running tests using Firefox, I frequently end up in a state like this. 

![image](https://user-images.githubusercontent.com/1673303/31595129-18103b4e-b26c-11e7-93b1-6499bb8062d0.png)

It looks like a timing issue. Sometimes the same test can proceed to load the URL correctly.

I tried using FF45.0 and FF46.01 with similar problems. I'm using Windows 10. In the end I ended up using Chrome.

**Comment by tshradheya** [comment]
Does this still happen frequently? 
For me its usually the first page and then it goes on to load the expected URL all times.

I investigated a bit and found that downgrading to 43.0 might work or adding a couple of lines helps[cant test this as I haven't come across this issue before]

**Comment by damithc** [comment]
> Does this still happen frequently?

I've been using Chrome for a while now. Will try firefox next time.

**Comment by Ayush517** [comment]
Any suggestions on how to replicate this issue?

**Comment by damithc** [comment]
@wkurniawan07 should we close this as E2E testing is likely to change in V7?

**Comment by wkurniawan07** [comment]
Yes, this should be closed for now.
