### ISSUE TITLE
StudentCourseJoinConfirmationPageUiTest: fix Google login

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8106]
I had to try more than 20 times (alternating between Firefox and Chorme) to get this test to pass once against the live server. 
v5.112

**Comment by whipermr5** [comment]
Was the failure due to the same NPE as in https://github.com/TEAMMATES/teammates/issues/7950#issuecomment-332198768?

**Comment by damithc** [comment]
No, it was browser automation issues. Not clicking the button, not entering the password etc.

**Comment by damithc** [comment]
Still hard to pass. v6.0.1
