### ISSUE TITLE
Instructor: enroll students: leading spaces in email should be trimmed internally

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8108]
v5.112:
A user reported that enrollment fails if there is a leading space in front of the email address.
![image](https://user-images.githubusercontent.com/1673303/31648101-88be6b54-b33e-11e7-868f-337ff4fb82fa.png)

**Comment by wkurniawan07** [comment]
#7457

**Comment by whipermr5** [comment]
`C2` `A0` indeed corresponds to the non-breaking space ([link](https://en.wikipedia.org/wiki/Non-breaking_space)). Relevant part of the code:
https://github.com/TEAMMATES/teammates/blob/a446786d53aa235b020d6dfdea1ca64562a595d6/src/main/java/teammates/common/datatransfer/StudentAttributesFactory.java#L96-L109

The 5 fields (team, name, email, comment, section) depend on `StringHelper.removeExtraSpace` to remove leading/trailing spaces; however, the method does not trim those and hence, they may potentially contain leading/trailing non-breaking spaces. It's easy to implement a fix ([link](https://stackoverflow.com/questions/28295504/how-to-trim-no-break-space-in-java)); however, what should the correct behaviour be? That kind of space is a special character, and while it's probably illegal for email addresses, I'm wondering if there are situations where users might genuinely want them to be part of the input for team/name/comment/section.

**Comment by damithc** [comment]
I suspect leading/trailing nbsp is guaranteed to be an unintended error. What do you think?

**Comment by LiHaoTan** [comment]
I don't know if we should handle all types of whitespaces but if we do I would prefer we using something like from Guava to make sure we are handling the whitespaces correctly.

[CharMatcher](http://google.github.io/guava/releases/snapshot-jre/api/docs/com/google/common/base/CharMatcher.html)

Also, [Comparison of several definitions of "whitespace"](https://goo.gl/Y6SLWx), extracted from Guava docs.

**Comment by wkurniawan07** [comment]
@LiHaoTan your suggestion is precisely why I suggested `StringHelper` to be a facade class.

**Comment by damithc** [comment]
One more case reported today.
