### ISSUE TITLE
Update user map for Sep 2017

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8112]
Similar to #7424 etc.

New entries to consider:

Australia | Swinburne University of Technology
-- | --
Australia | University of Canberra
Belgium | UHasselt
Brazil | Uniritter
Canada | Cegep Heritage
Canada | Collège Ahuntsic
Canada | École de Technologie Supérieure
Canada | SAIT
Canada | Wilfrid Laurier University
Canada | Sheridan College
China | Qingdao No. 1 International School of Shandong Province
China | Shanghai American School - Puxi Campus
Egypt | ELAMAL School
France | Lille Catholic University
Hong Kong | The Chinese University of Hong Kong
Hungary | Eötvös Loránd University
Indonesia | Universitas Indonesia
Ireland | Dublin Institute of Technology
Ireland | NUI Galway
Ireland | University College Cork
Maldives | Villa College
Netherlands | Eindhoven University of Technology
Netherlands | Herman Brood Academie
Netherlands | Leiden University
Netherlands | Open University of the Netherlands
New Zealand | Massey University
New Zealand | University of Otago
New Zealand | University of Auckland
Philippines | De La Salle University
Philippines | Miriam College Middle School
Philippines | The Quantum Academy
Singapore | National Institute of Education
Singapore | Ngee Ann Polytechnic
Singapore | Temasek Polytechnic
South Africa | The University of the Witwatersrand
Sweden | Gothenburg University
Switzerland | La Cote International School
Taiwan | National Taiwan University
Turkey | mersin üniversitesi
UK | Kingston University
UK | Leeds Trinity University
UK | Northumbria University
UK | University College London
USA | Brigham Young University
USA | Brigham Young University, Idaho
USA | Carroll University
USA | Central Oregon Community College
USA | Clackamas Educational Service District
USA | Clark High School
USA | Drew University
USA | Fullerton College
USA | George Mason University
USA | Georgia Southern University
USA | Harvard-Westlake Middle School
USA | Hughes STEM High School
USA | Illinois State University
USA | Indiana State University
USA | Indiana University
USA | Ithaca College
USA | James Madison University
USA | John D. O'Bryant School of Math and Science
USA | Keypath Education
USA | Mabelle B. Avery
USA | Medical College of Wisconsin
USA | Miami University - Oxford
USA | Michigan State University
USA | New Mexico State University
USA | Northeastern University
USA | Northern Arizona University
USA | Northland Community & Technical College
USA | Penn State University
USA | Portland Community College
USA | Purdue University Northwest
USA | Regis University
USA | Samuel Merritt University
USA | Superior Central
USA | Temple University
USA | Texas A&M College of Pharmacy
USA | Thiel College
USA | Thomas Ewing Junior High
USA | University at Albany
USA | University at Albany, SUNY
USA | University of Colorado Boulder
USA | University of Maryland Eastern Shore
USA | University of Minnesota
USA | University of Nebraska Kearney
USA | University of New Hampshire
USA | University of North Carolina at Charlotte
USA | University of Oregon
USA | University of Sheffield
USA | University of South Carolina
USA | University of South Dakota
USA | University of Southern California
USA | University of Wisconsin Madison
USA | Villanova University
USA | Virginia Tech
USA | Wheatland High School
USA | Xavier University of Louisiana
USA | Kennesaw State
USA | Northeastern University

**Comment by adiparab14** [comment]
Can I pick this up?

**Comment by whipermr5** [comment]
@adiparab14 Sure!

**Comment by adiparab14** [comment]
Ok. I am picking this up.
