### ISSUE TITLE
Dev docs: mention when to use GodMode

### ISSUE THREAD

**Issue by ncbaihly** [TEAMMATES/teammates#8115]
Currently for a new contributor approaching this project, there is no mention about why someone would want to use [GodMode](https://github.com/TEAMMATES/teammates/blob/master/docs/godmode.md) or how to use it in the Development Workflow documentation or other introductory documentation. 

The one mention I could find was in [Development Guidelines Page](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md) and even then it just has a link to the GodMode page and nothing about when someone would need to use it. 

So the task would be to maybe add a small comment explaining the basic idea of GodMode and why someone would want to use it along with a link to the [GodMode page](https://github.com/TEAMMATES/teammates/blob/master/docs/godmode.md) in the [Development Workflow page](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md) or maybe another page that's suitable or expanding on the mention of it in the [Development Guidelines Page](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md)

**Comment by shaharyar-shamshi** [comment]
I am eager to work on this issue

**Comment by damithc** [comment]
Can one of the @TEAMMATES/seniordevs fix this? While the fix is easy, knowing where to apply the fix may need a high-level knowledge of the whole workflow.
