### ISSUE TITLE
Improve error.png

### ISSUE THREAD

**Issue by DimitarGadzhev** [TEAMMATES/teammates#8118]
**Description of feature/enhancement**
Improve the image "error.png"

**Justification**
Benefits for users with more comfort view.

**Comment by chowyb** [comment]
Needs more details.

What exactly is meant by "improve", and how do you define a "more comfort view"?

**Comment by chowyb** [comment]
@DimitarGadzhev any updates here?

**Comment by DimitarGadzhev** [comment]
Task is done. I make a PR.

**Comment by chowyb** [comment]
@DimitarGadzhev providing a PR with a changed image is not sufficient for this; I need to know why there was a need to change the image to begin with, and why this change will benefit users.
