### ISSUE TITLE
Investigating the reliability of feedback submission in V7

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8120]
Seems there is a regular stream of failures, possibly when many students try to submit at the same time. Some students even complaining that TEAMMATES wiped out what they submitted.
I've also noticed that this action takes far too long to complete, even at best of times.
This is one area we need to improve as our userbase increases.

**Comment by damithc** [comment]
sometimes students say some of the responses were wiped out. At other times all responses are wiped out. Not sure if it is a case of responses not being saved or overwritten by empty responses.

**Comment by whipermr5** [comment]
From server logs, it is very likely a javascript issue. All the logged cases I've examined so far show that the responses were always correctly loaded when the user loaded the submission edit page, but the POST parameters were somehow empty during the actual submission save. Probably related to #7796 too.

**Comment by xpdavid** [comment]
Architecture in V7 for feedback submission has changed (more concurrency + less work per API request = "strong scaling"). Will come back to the issue if it still persist in V7.

**Comment by wkurniawan07** [comment]
> Architecture in V7 for feedback submission has changed (more concurrency + less work per API request = "strong scaling").

It stands to reason that this is no longer an issue in V7.
