### ISSUE TITLE
New contributor introduction

### ISSUE THREAD

**Issue by ibodi** [TEAMMATES/teammates#8122]
Link to my fork: https://github.com/ibodi/teammates

Hello!
My name is Bohdan Shcherbak. I am a student of the University of Wroclaw. I want to gain precious experience of working on open source project. I'd like to be a backend developer and write in java.
I don't know where to get a link to my app and what that and  "**Link to my app:** e.g. https://teammates-username.appspot.com" means. I haven't done any changes to anything yet, but I look forward to doing so.

**Comment by whipermr5** [comment]
Hey Bohdan, welcome to TEAMMATES! Do follow phases B and C of the [orientation guide](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md#phase-b-set-up-locally). You'll understand where to get the link to your app after deploying to a staging server. After that, you can get your feet wet by working on a `d.FirstTimers` issue, then move on to `d.Contributors` issues :)
