### ISSUE TITLE
Could not determine java version from '9.0.1'.

### ISSUE THREAD

**Issue by ibodi** [TEAMMATES/teammates#8123]
Operating System: macOS High Sierra
JDK Version: 9.0.1

When I was trying to follow the instructions here https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md, I faced some problems:
1) Why should I install JDK 1.7? I have the latest java version installed 
<img width="438" alt="screen shot 2017-10-25 at 13 03 01" src="https://user-images.githubusercontent.com/19334520/31995499-e348ed50-b984-11e7-84ce-c3b58dbd1352.png">
And it's version seems to be extraordinarily later than 1.7.

2) When I was trying to do "git branch -u upstream/master", I got this kind of error:
<img width="499" alt="screen shot 2017-10-25 at 13 05 53" src="https://user-images.githubusercontent.com/19334520/31995597-63aa2d6a-b985-11e7-85c3-50e83e2a35c4.png">
Honestly, I don't understand what this command is supposed to do. And I feel that in order to understand this I would have to put a bit of effort to learn git basics more deeply.

3) When I was trying to do  "./gradlew appengineDownloadSdk", I got this 
<img width="557" alt="screen shot 2017-10-25 at 13 07 47" src="https://user-images.githubusercontent.com/19334520/31995625-8b1aa5aa-b985-11e7-944a-ea93ed856d94.png">
I haven't found any useful (or understandable) information on the topic.

**Comment by whipermr5** [comment]
> Why should I install JDK 1.7? I have the latest java version installed

The Google App Engine Standard runtime we're using only supports Java 7. The GAE Java 8 runtime only just became generally available a month ago ([link](https://cloudplatform.googleblog.com/2017/09/Java-8-on-App-Engine-Standard-environment-is-now-generally-available.html)), and we're in the process of [migrating](https://github.com/TEAMMATES/teammates/projects/2).

> When I was trying to do "git branch -u upstream/master", I got this kind of error:

You didn't add the remote name `upstream` as instructed in step 2.

> When I was trying to do "./gradlew appengineDownloadSdk", I got this

This will probably go away once you've installed JDK 7.
