### ISSUE TITLE
Const.java, InstructorSampleData.json: fix invalid date format

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#8124]
Change all instances of `00:00 AM` to `12:00 AM`. See https://github.com/TEAMMATES/teammates/pull/8094#discussion_r147037350.

**Comment by AnnaGMiguel** [comment]
Hi @whipermr5 I am new in this project, can I pick this up?

**Comment by whipermr5** [comment]
@AnnaGMiguel Sorry, looks like someone else has submitted a PR. Feel free to submit a PR for any other issue! We don't require asking :)
