### ISSUE TITLE
Instructor: feedback results: fix broken auto-highlighting of table

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#8128]
In `instructorFeedbackResultsPage`, when using the `Click here` link to view the results in a modal, the user needs to manually click on the `Select Table` button to highlight the table.

However, while reviewing #8116, I noticed these lines of code:
https://github.com/TEAMMATES/teammates/blob/c0d3afa4f0eb060ff66815f1839711eee6e7bacd/src/main/webapp/dev/js/common/instructorFeedbackResults.js#L292-L295

The current behaviour is that instead of the content being auto-highlighted, the AJAX gif loader is highlighted instead. The gif subsequently gets replaced by the table, and the highlighting disappears. It seems that auto-highlighting was originally intended but probably subsequently broken when re-implementing the table with AJAX.

To fix, delete those lines and add a line `selectElementContents(content.get(0));` to the bottom of the AJAX success block instead, after `ajaxStatus.html(data.ajaxStatus);`:
https://github.com/TEAMMATES/teammates/blob/c0d3afa4f0eb060ff66815f1839711eee6e7bacd/src/main/webapp/dev/js/common/instructorFeedbackResults.js#L46-L48

**Comment by torbenbru** [comment]
Hey @whipermr5 , I'd like to contribute to this too but can't seem to find a JDK 1.7 to run the tests and see if the new Code works as it isn't supported anymore. With an updated version of the Java 9 JDK the build fails with "Could not determine java version from '9.0.1'.". Where can I gt the 1.7 JDK?

**Comment by whipermr5** [comment]
Hey @torbenbru, unfortunately, each person is only allowed to work on one `d.FirstTimers` issue. You may move on to `d.Contributors` issues :) As for JDK 1.7, a simple Google search should lead you to the official download page.

**Comment by Rajat-dhyani** [comment]
hey @whipermr5 , I'd like to contribute to this issue. If it's not already taken?

**Comment by whipermr5** [comment]
@Rajat-dhyani Go ahead :)

**Comment by Rajat-dhyani** [comment]
Thanks, @whipermr5. Right now I am reading contribution guide. Will get back to you on this soon :)

**Comment by Abhishek-Trivedi** [comment]
I have tried to remove this issue. Tell me if I could do some more changes. :)
