### ISSUE TITLE
Update user map for Oct 2017

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8138]
Similar to #7424 

Entries to consider

Australia | Edith Cowan University
-- | --
Australia | Monash University
Australia | Swinburne
Australia | University of Melbourne
Austria | Uni Salzburg
Belgium | BA Botaniek
Belgium | Guldensporencollege
Belgium | Hasselt University
Brazil | EnglishPlus
Brazil | PONTIFICIA UNIVERSIDADE CATOLICA DE MINAS GERAIS
Brazil | Universidade Federal do Rio Grande do Sul
Canada | Algonquin College
Canada | École de technologie supérieur
Canada | Queen's University
Canada | University of Calgary
Canada | University of Ontario Institute of Technology
Canada | Wildfid Laurier University
Canada | Wilfrid Laurier
Chile | Pontificia Universidad Católica de Chile
Czech Republic | Masaryk University
Denmark | Absalon
Ireland | Dundalk Institute of Technology
Italy | Università Cattolica del Sacro Cuore
Latvia | Stockholm School of Economics in Riga
Mexico | Universidad de las Américas Puebla
Nethelrands | Eindhoven University of Technology
Nethelrands | Hogeschool Utrecht
Nethelrands | Rotterdam Business School
Netherlands | Delft University of Technology
Netherlands | Fontys International Business School
Netherlands | Saxion University of Applied Science
Netherlands | Technische Universiteit Eindhoven
New Zealand | Massey University
New Zealand | Unitec
Philippines | aGreatlife
Philippines | Oneself
Philippines | University of San Carlos
Philippines | University of the Philippines
Poland | Jagiellonian University
Singapore | James Cook University
Singapore | Ngee Ann Polytechnic
Singapore | Singapore Institute of Technology
Singapore | Singapore Polytechnic
Spain | IE University
Spain | University of Cádiz
Thailand | Mahidol University
UK | Brunel University London
UK | Brunel University London
UK | Imperial College London
UK | University College London
UK | University of Huddersfield
UK | University of Kent
USA | California State University San Marcos
USA | Anderson University
USA | ARROW TRANS CORP
USA | Bartlett High School
USA | Benedictine College
USA | BOOKER T. WASHINGTON HIGH SCHOOL
USA | California State University, Los Angeles
USA | California State University, San Marcos
USA | Charles Page High School
USA | Charlotte Mecklenburg Schools
USA | Colorado State University - Pueblo
USA | Columbia University
USA | Cornell University
USA | CrossRoads Intermediate School
USA | Decatur Middle School
USA | DePaul University
USA | EL PASO INDEPENDENT SCHOOL DISTRICT
USA | Grand Valley State University
USA | Harvard University
USA | Indiana State University
USA | Indiana University
USA | Indiana University of Pennsylvania
USA | Johns Hopkins Bloomberg School of Public Health
USA | Kent State Univrsity
USA | Lee University
USA | Lick-Wilmerding High School
USA | Massachusetts Institute of Technology
USA | Medical College of Wisconsin
USA | Monte Vista Christian High School
USA | NC State University
USA | New Mexico State University
USA | North Carolina State University
USA | Northern Arizona University
USA | Old Dominion University
USA | Pasadena City College
USA | Penn Valley Community College
USA | Portland State University
USA | Purdue University
USA | Radford University
USA | Salado High School
USA | St. Louis University
USA | State University of New York Albany
USA | University at Albany
USA | University at Albany, SUNY
USA | University at Buffalo
USA | University of Colorado
USA | University of Colorado Boulder
USA | University of Illinois at Urbana-Champaign
USA | University of Iowa
USA | University of Kansas
USA | University of North Florida
USA | University of South Dakota
USA | University of South Florida
USA | University of Southern California
USA | University of Utah
USA | University of Washington
USA | University of Wisconsin Madison
USA | West Chester Area School District
USA | Wheelock College
USA | William & Mary

**Comment by KshitijKythe** [comment]
I'm new to open source, Can I work on this??

**Comment by chowyb** [comment]
@KshitijKythe yes, feel free to do so 😄 you may wish to have a look at our contributing guidelines before submitting your pull request however.

**Comment by KshitijKythe** [comment]
Thanks a lot. Will do. :)
