### ISSUE TITLE
Update weekly backup code

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#8139]
https://github.com/TEAMMATES/teammates/blob/188f585479612ab07808d571104056073f512c1d/src/main/webapp/WEB-INF/cron.xml#L27

Whether the backup code works/not or is ideal/not is out of question, but at the current state, three problems exist in this line:
- `Comment` has been decommissioned long ago.
- `Student` has been changed to `CourseStudent` even before that; this would mean student entities have never been backed up for a very long time.
- `Account` is absent; this means account entities are never backed up.

**Comment by damithc** [comment]
To add, the backup not only cost about 10-15 extra dollars each, it also throws some map reduce errors in the process. We  need to look for a better way to do backup/restore, which is not going to be easy.
