### ISSUE TITLE
Admin: masquerade mode: allow viewing of profile pictures for any course

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8140]
v5.112

![image](https://user-images.githubusercontent.com/1673303/32485666-2deb7c1a-c3df-11e7-86b1-aa2583ee5a48.png)

**Comment by whipermr5** [comment]
It's showing up fine for me on the live server.

**Comment by damithc** [comment]
> It's showing up fine for me on the live server.

@whipermr5 check the following course on live server. If you can see the photos (I can't), the problem can be limited to the masquerade mode

![image](https://user-images.githubusercontent.com/1673303/34067728-d077dad0-e268-11e7-9fcc-679ea4e303de.png)

**Comment by whipermr5** [comment]
@damithc Yes; I can see the images fine. It is also working fine in masquerade mode on my staging server. What does the HTML for the images look like on the live server?

**Comment by damithc** [comment]
Example (photo does not exist and shown as broken link - your CS2101 course):
`<img id="profilePic" src="/page/studentProfilePic?studentemail=DE147FD55CDEC30E912C0C0DE10BBDB8C36C0DB53BC4D58A51AD7EFCACDAFC50&amp;courseid=8209C88FC46B453D71CAB6A0D279887B" class="profile-pic" data-toggle="modal">`

Example (photo exists and image shown correctly -- your CS2103 course)
`<img id="profilePic" src="/page/studentProfilePic?studentemail=DE147FD55CDEC30E912C0C0DE10BBDB8C36C0DB53BC4D58A51AD7EFCACDAFC50&amp;courseid=97A8AE8BF35802588DBE476425C39797" class="profile-pic" data-toggle="modal">`

**Comment by wkurniawan07** [comment]
> Example (photo does not exist and shown as broken link - your CS2101 course):
> `<img id="profilePic" src="/page/studentProfilePic?studentemail=DE147FD55CDEC30E912C0C0DE10BBDB8C36C0DB53BC4D58A51AD7EFCACDAFC50&amp;courseid=8209C88FC46B453D71CAB6A0D279887B" class="profile-pic" data-toggle="modal">`

This example does not fit the issue title -- it is not the "default image".
In case there is an assumption that "if an image cannot be found, fall back to the default image", there is no such thing.

**Comment by damithc** [comment]
@whipermr5 so you see the default image or the actual photos for this specific course?

**Comment by whipermr5** [comment]
The first URL (CS2101) redirects to the default image ([this](https://teammatesv4.appspot.com/images/profile_picture_default.png) URL). The second URL (CS2103) shows the actual photo.

**Comment by whipermr5** [comment]
If you visit the image URLs directly, does it result in an unauthorised error page (`User is not in the course that student belongs to`)?

**Comment by whipermr5** [comment]
I can reproduce the problem for courses that the admin is not an instructor/student of; it seems that the issue is not new though. Currently no special privileges are granted to the admin for the viewing of profile pictures.

**Comment by damithc** [comment]
I see. If the problem is limited to admin, we can treat it as low priority.

**Comment by whipermr5** [comment]
I believe this is simple enough to be a first timer issue. Hint: modify `StudentProfilePictureAction`; look for the part that has a reference to GateKeeper.

**Comment by czarska** [comment]
I would like to try to work on this issue.

**Comment by whipermr5** [comment]
@czarska Go ahead :)

**Comment by tran-tien-dat** [comment]
I would like to take up this issue since @czarska has not been active for a while.

**Comment by tran-tien-dat** [comment]
After investigation, I discover that the root of the problem is not because Admin is not given special privileges to view the profile pictures, but rather, the 'nominal' account, which is supposed to be the student's account when Admin is in masquerading mode is not tracked properly for this request.

**Comment by czarska** [comment]
I’m working on this issue :( I wasn’t active because I was waiting for an answer is it still free

**Comment by tran-tien-dat** [comment]
@czarska Sorry I have already submitted a PR to fix this
