### ISSUE TITLE
New contributor self intro - Orinn Williams

### ISSUE THREAD

**Issue by orinn248** [TEAMMATES/teammates#8144]
- Link to my fork: https://github.com/orinn248/teammates.gits

![image](https://user-images.githubusercontent.com/31255676/32682245-87ac7902-c641-11e7-90a7-817277d7d3de.png)

Hey, I'm happy to be getting my feet wet in the open-source world by contributing to TEAMMATES. I'm here as part of Software Development and Testing course that I am taking right now.

I chose TEAMMATES because of the well established workflow and guidelines that are provided. To all that have worked hard to put together this framework, I applaud you because I've reviewed numerous projects online and TEAMMATES is one of the best to plug into.

Thanks for reading and have a good day.

P.S. I was listening to Whitney Houston while working on this which is where my UI change came from.

**Comment by whipermr5** [comment]
Hey Orinn, welcome to TEAMMATES! Good job setting everything up the dev server! Interesting UI change 😂 I see you've already submitted a PR for a `d.FirstTimers` issue; that's good! It should be ready for merging once you rename the title according to our [guidelines](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr). After that you may proceed to work on `d.Contributors` issues :)

**Comment by orinn248** [comment]
Thank you! Title has been updated.
