### ISSUE TITLE
Instructor: edit question: remove the need to click edit button multiple times

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8148]
v5.112 (but I noticed this even in previous versions)

I noticed that when editing question, sometimes I need to click on the `edit` button 2-3 times before the question becomes editable. It is not always reproducible though. 

Browser: Chrome on Windows

**Comment by bqnguyen94** [comment]
It appeared sometimes the clicking event of the `edit` button registered the inner `span` element of the button, which is the pencil glyphicon, instead of the `anchor` element, leading to the erratic behaviour.

**Comment by damithc** [comment]
> It appeared sometimes the clicking event of the edit button registered the inner span element of the button, which is the pencil glyphicon, instead of the anchor element, as the event's target, leading to the erratic behaviour.

Good detective work @bqnguyen94 👍

**Comment by bqnguyen94** [comment]
Seems like the problem can be reproduced by pointing the mouse on the pencil glyphicon while clicking the `edit` button. Clicking onto the word `edit` itself doesn't cause the issue.
