### ISSUE TITLE
Upgrade Selenium to 3.x

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#8150]
With Java 8 not being a blocking issue anymore, we are ready to migrate to Selenium 3.

**Comment by tshradheya** [comment]
Upgrading to Selenium 3.x, would make `Geckodriver.exe` be downloaded compulsorily. Is that fine?

Should I go ahead with it?

**Comment by wkurniawan07** [comment]
That is part of the expected work.

**Comment by tshradheya** [comment]
Okay. Thanks 👍

**Comment by tshradheya** [comment]
I have a query. On looking at the TEAMMATES documentation, it says only firefox version till `46.0.1` is supported. I am currently on that version and after integrating `geckodriver` , i am unable to make the webdriver open.
 
![image](https://user-images.githubusercontent.com/12574756/35220802-a7d7e77a-ffb2-11e7-9fb7-04ae61b067b4.png)


On looking up the `geckodriver` [releases ](https://github.com/mozilla/geckodriver/releases) it says the following:

![image](https://user-images.githubusercontent.com/12574756/35220878-0c1812aa-ffb3-11e7-9bdd-bc4d9044c5ef.png)

I am assuming the web driver will only work after i update my mozilla( I haven't tried that yet).
Just wanted to check what is the reason behind limiting the version to `46.0.1`? Is it fine if we use the latest version of firefox for testing? Or are we limited to using till `46.0.1` currently?

**Comment by tshradheya** [comment]
@LiHaoTan So can I assume its fine for us to update to a newer version of Firefox (i.e. `46.0.1` + ?)

**Comment by LiHaoTan** [comment]
@tshradheya definitely, otherwise there would be no way to upgrade to Selenium 3.

**Comment by tshradheya** [comment]
Query. 

In the `.travis.yml` ,  I wanted to know how the firefox path is transferred to `TestProperties` ?
I want to use the similar method to export the absolute path of `geckodriver` and use it to `setProperty` of the System

**Comment by whipermr5** [comment]
> Just wanted to check what is the reason behind limiting the version to 46.0.1?

I believe it's precisely because we're using Selenium 2.x, which doesn't support later versions of Firefox. It'd be great if you're successful in upgrading to Selenium 3.x so we can finally use the latest Firefox.

**Comment by wkurniawan07** [comment]
Resolved in V7.
