### ISSUE TITLE
New Contributor Self Intro Minsung Joh

### ISSUE THREAD

**Issue by jms5049** [TEAMMATES/teammates#8151]
->Link to Your Fork
https://github.com/jms5049/teammates

->A Screenshot of the Change You Did (As Seen On the UI)
<img width="1440" alt="2017-11-13 8 44 06" src="https://user-images.githubusercontent.com/26538414/32724301-1614002e-c8b4-11e7-8a6d-ef8f84e8c7fa.png">

changed color green into orange,
on hover the button turns into dim orange

->Your Real Name and a Short Self-Intro
Hello my name is Minsung Joh.
I am university student and major in Computer Science Engineering in South Korea.
'Teammate' is my first experience getting involved in the open source and hope to have great time.

**Comment by chowyb** [comment]
Hi @jms5049,

Welcome to TEAMMATES! You may wish to start by taking on one of our `d.FirstTimers` issues, before moving on to `d.Contributors` issues :)
