### ISSUE TITLE
New Contributor Self Intro Eunjeong Jang

### ISSUE THREAD

**Issue by cs801458j** [TEAMMATES/teammates#8152]
->Link to Your Fork: 
https://github.com/cs801458j/teammates

->A Screenshot of the Change You Did (As Seen On the UI)
![image](https://user-images.githubusercontent.com/19684904/32730689-3b56df34-c8cb-11e7-94f5-f791a6cc9e5e.png)

When continuously reducing the width, The letters in the 'Request a Free Instructor Account' button will flood out of the button. So I added overflow attribute on the button. 

->Your Real Name and a Short Self-Intro
Hello, my name is Eunjeong Jang 
I am university student and major in Computer Science Engineering in South Korea.
Recently, my friends and I were looking for a project to contribute. 
I think it is very good chance to us to meet this TEAMMATES project and We want to contribute to this project.

**Comment by chowyb** [comment]
Hi @cs801458j,

Welcome to TEAMMATES! You may wish to start by taking on one of our `d.FirstTimers` issues, before moving on to `d.Contributors` issues :)
