### ISSUE TITLE
Unresovled Servlet Class error in Project setup 

### ISSUE THREAD

**Issue by sukanta-27** [TEAMMATES/teammates#8153]
**Operating System:** Windows 8.1
- **JDK Version:** 1.8
- **Eclipse / IntelliJ Version (if applicable):** Eclipse Oxygen 1a Release (4.7.1a)

I was setting up the project in Eclipse Oxygen, and I came across the `Unresolved Servlet Class` error in web.xml file.
Here is the screenshot of the error : 

![screenshot 236](https://user-images.githubusercontent.com/10681755/32769465-fcf51036-c941-11e7-994b-34cf289bcfed.png)

I followed the Setting_up.md and the IDE installation guide and went through it more than 3 times to find out why this error is occuring. But could not find it. Maybe I am missing something trivial. 
I also read some answers in StackOverFlow related to these kind of issues and it mentioned that `servlet-api.jar` should be included in the library of the project, but in my project it does.

Here is the Java build path library screenshot:
![screenshot 237](https://user-images.githubusercontent.com/10681755/32769617-a987b772-c942-11e7-9cc5-4406c37dcc4c.png)

How can I solve this issue?

**Comment by chowyb** [comment]
@wkurniawan07 not sure if this is caused by the recent shift to Java 8.

@sukanta-27 just to check, are you using JDK 1.8 and not JRE 1.8? Unfortunately the build path says "JRE" even when a JDK is used, so I'd just like to be sure.

**Comment by wkurniawan07** [comment]
@sukanta-27 it looks like you tried to deploy the app via command line before? That error comes from `build` folder which is not a cause of concern.

**Comment by sukanta-27** [comment]
@chowyb Yes, I'm using JDK 1.8.

![screenshot 238](https://user-images.githubusercontent.com/10681755/32787449-8ec83a9e-c97c-11e7-82f6-480b868b49e2.png)

I also went through the troubleshooting-guide.md and found a similar Error. 

> ERROR: Eclipse complains "NewClass cannot be resolved to a type", "The import some.package.NewClass cannot be resolved", or "The method someMethod() from the type ExistingClass refers to the missing type NewClass" after syncing with master branch.
SOLUTION: This is likely because the dependencies have changed. Refer to [this document](https://github.com/TEAMMATES/teammates/blob/master/docs/dependencies.md) for steps to update your local dependencies configuration.

But I am not sure if I should Update a library or Add one.

**Comment by sukanta-27** [comment]
@wkurniawan07  I am not sure I did. From forking the repo to IDE setup I did exactly what was in the guide.

> @sukanta-27 it looks like you tried to deploy the app via command line before? That error comes from build folder which is not a cause of concern.

Okay then. Does that mean I can work on the project without this error affecting in any manner?
 Thank you by the way @chowyb  @wkurniawan07  for the reply.

**Comment by wkurniawan07** [comment]
@sukanta-27 that directory `build/staged-app` can only appear on very specific demand. Do you recall running `gradlew.bat appengineStage` or `gradlew.bat appengineDeploy` before? The chance of it happening if you follow the setup guides exactly is slim at best.

> Does that mean I can work on the project without this error affecting in any manner?

Yes, those "errors" are as good as non-existent.

**Comment by sukanta-27** [comment]
@wkurniawan07  The  only gradlew.bat command I remember running was to create the configuration file `gradlew.bat createConfigs`. and one time only `gradlew.bat` by mistake. which I terminated and ran the createConfigs command.

> Yes, those "errors" are as good as non-existent.

Okay, Thank you.

**Comment by whipermr5** [comment]
@sukanta-27 I believe you can just delete the entire `build` folder, then clean and build in Eclipse. The Eclipse project build folder is set to `build-eclipse`, so `build` should not even show up unless building from the command line.

**Comment by sukanta-27** [comment]
@whipermr5  Okay, will do just that. Thank you.

**Comment by sukanta-27** [comment]
@whipermr5 Deleting the `build` folder resolved it. 

![screenshot 239](https://user-images.githubusercontent.com/10681755/32840102-a8344872-ca3c-11e7-9419-cb9adc5d3c7b.png)
