### ISSUE TITLE
InstructorLogicTest - Refactor try-catch blocks to improve code quality

### ISSUE THREAD

**Issue by orinn248** [TEAMMATES/teammates#8162]
**Description of feature/enhancement**
Upon reviewing the logic test suite, I noticed that some test cases perform excess try-catch blocks to test null parameters. For try-catch blocks that test null parameters, I will refactor the test to place the try-catch block within a loop and pass in an array to improve code quality and code coverage percentages.  Thus far, I have addressed this in teammates.test.cases.logic.InstructorLogicTest.Java.

**Justification**
This concept can be repeated for future logic test including CoursesLogicTest which performs similar try-catch blocks for null parameters.  This will increase the code coverage for test that use the try-catch method.

**Existing similar features and their shortcomings**
Currently, try-catch blocks are duplicated to test null parameters. This can be avoided. A snap shot is attached.

![image](https://user-images.githubusercontent.com/31255676/32986585-abd9ecde-cca3-11e7-8391-7c2be9d2e7a9.png)

**Comment by orinn248** [comment]
Submitted pull request for issue

**Comment by damithc** [comment]
Closing as per my comment in #8165
