### ISSUE TITLE
New contributor self intro Dominik Traczyk

### ISSUE THREAD

**Issue by Naitoreivun** [TEAMMATES/teammates#8167]
**Fork repo:** https://github.com/Naitoreivun/teammates
**Changes:
Before:**
![before](https://user-images.githubusercontent.com/11821294/32998201-5157cea6-cd99-11e7-9a20-c3f9d61bf331.PNG)
**After:**
![after](https://user-images.githubusercontent.com/11821294/32998215-6690568a-cd99-11e7-9e13-d33a5e724906.PNG)

I've pulled user id to the right to make it more readable (imo). Actually I wanted to create 'copy to clipboard' button for link that is generated after new instructor creation, but I met some troubles and I gave up after few hours :/ So only this.

**Personal info:**
I'm Dominik Traczyk and I study Theoretical Computer Science at Jagiellonian University in Poland. I'm also Junior Software Developer (mainly Java + JS frameworks like Angular and React). It's gonna be my first open source project so I'm looking forward to facing new challenges.

**Comment by whipermr5** [comment]
Hey Dominic, welcome to TEAMMATES! Good job setting up the dev server correctly! The change looks good! 👍 You can get your feet wet by working on a `d.FirstTimers` issue, then move on to `d.Contributors` issues :)
