### ISSUE TITLE
Remove method getInstructorsForEmail(String)

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#8168]
Remove the method `getInstructorsForEmail(String)` from `Logic`, `InstructorsLogic`, and `InstructorsDb`, and the corresponding unit tests as it is not used anywhere.

**Comment by sukanta-27** [comment]
I will like to work on it.

**Comment by Benjineer** [comment]
Interested too

**Comment by pawanakhil** [comment]
https://github.com/pawanakhil/teammates/commit/d81bd5d0c633f94ff587a0a3d9841e6956bb1ccf 

Removed getInstructorsForEmail(string) method
