### ISSUE TITLE
static-analysis.md: fix CheckStyle and PMD Eclipse plugin link

### ISSUE THREAD

**Issue by sukanta-27** [TEAMMATES/teammates#8173]
**Environment**

Tested in : Firefox 46.0<br>Chrome Version 62.0.3202.94

**Steps to reproduce**
While installing the plugins from the [static-analysis](https://github.com/TEAMMATES/teammates/blob/master/docs/static-analysis.md) file, I noticed that the download link in `Configuring PMD Eclipse plugin` under `PMD` gives `403 Forbidden` error.
![screenshot 249](https://user-images.githubusercontent.com/10681755/33160860-c93edab4-d045-11e7-99c5-c9270416276f.png)

**Expected behaviour**
This link should lead to a site that is accessible by everyone.

**Actual behaviour**
![screenshot 248](https://user-images.githubusercontent.com/10681755/33160884-f7632dbe-d045-11e7-8155-c2fc132909f1.png)

**Comment by sukanta-27** [comment]
@whipermr5 @wkurniawan07 As we are low on `d.firstTimer` issues, can this be considered as one?

and if it is not a `d.firstTimer` issue, then can I work on it?

**Comment by sukanta-27** [comment]
**Link that can serve the purpose :** https://marketplace.eclipse.org/content/eclipse-pmd

**Comment by whipermr5** [comment]
Yes; this can be considered a first timer issue. Thanks for reporting it! 👍

**Comment by wkurniawan07** [comment]
@sukanta-27 Eclipse download links are not necessarily navigable via Web browser. I don't think it will give a problem, but have you checked that the said link works when trying to download the said PMD plugin?
One more thing, also confirm that the PMD plugin in that link is the same that is described in the docs. Don't ask me why, but there are multiple PMD plugins for Eclipse in the wild.

**Comment by whipermr5** [comment]
Yes; it seems the site has moved from http://www.acanda.ch/eclipse-pmd/release/latest/ to http://acanda.github.io/eclipse-pmd/, which does link to the plugin at https://marketplace.eclipse.org/content/eclipse-pmd (it's also the most up-to-date PMD plugin [listed](https://marketplace.eclipse.org/search/site/pmd)). The Eclipse Marketplace link is good as it's less likely to change compared to the author's website.

**Comment by sukanta-27** [comment]
@wkurniawan07 I went through the doc file, but could not find any exact version number specified for PMD.

And I downloaded the PMD plugin from Eclipse MarketPlace itself (from the link I provided), and didn't encounter any issues while setting up. But I don't know if it will cause any problems in the future or not.

But while I was working on #8168 , pmd was working fine and pointed out the getInstructorEntitiesForEmail() method which was not being used. So, I think this version can do the job.

**Comment by wkurniawan07** [comment]
@sukanta-27, the problem is not "this version can do the job". The difference in the PMD plugins goes way beyond just version numbers. It is quite a luck that the one you found in the Marketplace is the same as the one in the docs, but it's good since Marketplace links is more resilient to changes.

**Comment by wkurniawan07** [comment]
FWIW I finally remember where I get the current link from: http://acanda.github.io/eclipse-pmd/getting-started.html. In other words, nothing has changed.

**Comment by sukanta-27** [comment]
@wkurniawan07 Oops! I was really not aware of this process 😅: 

>  An alternative way to install the plugin on Eclipse 3.7 (and later) is via the plugin update site http://www.acanda.ch/eclipse-pmd/release/latest.

> 1. In Eclipse go to Help > Install new software...
> 2. Add a new installation site and use http://www.acanda.ch/eclipse-pmd/release/latest as the location.
> 3. Select the plugin Eclipse PMD.
> 4. Finish the installation by accepting the license and restarting Eclipse.

No wonder I was getting a 403 Forbidden error. 
So, should we keep this issue open or close it?

**Comment by jakshay1991** [comment]
@sukanta-27  I followed the same process mentioned at []( http://acanda.github.io/eclipse-pmd/getting-started.html) and was able to install the plugin. Though i am not able to access the url [](http://www.acanda.ch/eclipse-pmd/release/latest) directly. 

<img width="868" alt="screen shot 2017-12-06 at 3 13 25 pm" src="https://user-images.githubusercontent.com/21007930/33655193-693d7604-da98-11e7-8a14-38e8365b59dc.png">

**Comment by sukanta-27** [comment]
@jakshay1991 Yes, this is expected. 

> let me know if we can update the static-analysis file with given link.

I think we should. We can also change the link in the `static-analysis` file to the [getting-started](http://acanda.github.io/eclipse-pmd/getting-started.html) link.

@whipermr5 @wkurniawan07 for your opinion.

**Comment by whipermr5** [comment]
Yes, we can still change it for the reason stated above:

> it's good since Marketplace links is more resilient to changes
