### ISSUE TITLE
Instructor: course details: fix broken auto-highlighting of table

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#8174]
Same as #8128, but for the course details page. Delete these lines:
https://github.com/TEAMMATES/teammates/blob/f0dd51db12cedecc02fbf4149116165a45139a54/src/main/webapp/dev/js/main/instructorCourseDetails.js#L103-L106

Then add `selectElementContents(content.get(0));` after these lines: https://github.com/TEAMMATES/teammates/blob/f0dd51db12cedecc02fbf4149116165a45139a54/src/main/webapp/dev/js/main/instructorCourseDetails.js#L49-L50

**Comment by annu025** [comment]
Can I take this up?

**Comment by whipermr5** [comment]
@annu025 Go ahead :)

**Comment by annu025** [comment]
[Referring here](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md) to install Google App Engine. Under Plugins, I do not see a way to install this framework. Could you please help me here? I am using community edition of IntelliJ to work on this issue. 

Please let me know if I am missing anything. @whipermr5 

Thanks.

**Comment by whipermr5** [comment]
@annu025 Have you followed the instructions in [ide-usage.md](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-usage.md)?
