### ISSUE TITLE
Use 'Evaluee/recipient' in student submission UI

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8176]
At some point we changed the feedback submission form to use the term _Evaluee_ instead of _Recipient_. However, some parts of the UI still uses the old term, this sentence for example:
> Instructors in this course can see your response, the name of the recipient, and your name.

We need to use the new term everywhere.

**Comment by LiHaoTan** [comment]
Additional context: The change from  _Recipient_ to  _Evaluee_ was decided in #7812.

**Comment by KshitijKythe** [comment]
Can I work on this? @damithc

**Comment by sukanta-27** [comment]
Can I take this? @damithc @LiHaoTan

**Comment by LiHaoTan** [comment]
@KshitijKythe @sukanta-27 we don't require that you ask when taking up an issue. However, it's common courtesy to not work on something else someone is working on.

Given that @KshitijKythe have decided to work on this issue first, @sukanta-27, it might be better for you to take up another issue. If you do feel strongly that you want to work on this issue, you could discuss it with @KshitijKythe

**Comment by sukanta-27** [comment]
@LiHaoTan Okay. 
@KshitijKythe Have you already started working on it?

**Comment by KshitijKythe** [comment]
@sukanta-27 yes I have. If I can't finish it off soon, I'll be sure to hand it off to you. :)

**Comment by sukanta-27** [comment]
@KshitijKythe Okay :)

**Comment by sukanta-27** [comment]
@KshitijKythe Any updates? 
It's been 20 days and you haven't submitted a PR yet, so, just wondering if you are still working on this or not.

**Comment by KshitijKythe** [comment]
sukanta-27 sorry, I've been busy on some other stuff. You go ahead and raise a PR.

**Comment by KshitijKythe** [comment]
@sukanta-27 Hey, my apologies, I've been busy with some other stuff, you go ahead and raise a PR. Just a pointer, some static pages like instructorHelp.jsp and features.jsp have many hits for 'recipient'. So just confirm with the core members where all it needs to change. Sorry for the delay.

**Comment by sukanta-27** [comment]
@KshitijKythe Thank you for the tip. I really appreciate that. :smile: I will start working on it.

**Comment by sukanta-27** [comment]
@damithc @LiHaoTan Sir, to be clear, There are many variables with the word 'recipient' in it. like `recipientType` ,`FEEDBACK_QUESTION_CONSTSUMTORECIPIENTS`, do they need to change to `Evaluee` as well, (like `evalueeType` and `FEEDBACK_QUESTION_CONSTSUMTOEVALUEES`)  or just the parts which are shown in the UI.

**Comment by damithc** [comment]
> There are many variables with the word 'recipient' in it. like recipientType ,FEEDBACK_QUESTION_CONSTSUMTORECIPIENTS, do they need to change to Evaluee as well, (like evalueeType and FEEDBACK_QUESTION_CONSTSUMTOEVALUEES) or just the parts which are shown in the UI.

@sukanta-27 Let's do the user-visible ones first. Changing it internally can be separate issue.

**Comment by sukanta-27** [comment]
@damithc Okay, I am already on it.

**Comment by wkurniawan07** [comment]
@damithc it may be just me, but `giver-evaluee` does not sound like a good pair. It's either `giver-recipient` or `evaluator-evaluee`. In fact I find the term `evaluee` rather weird because it is really not commonly used in everyday English.
Which brings me to this question: In #7812, why change "To" to "evaluee" instead of "recipient"?

**Comment by damithc** [comment]
> giver-evaluee does not sound like a good pair.

@wkurniawan07 that's true. 

The root cause is that TEAMMATES try to cater for two basic functions: doing _evaluations_ (evaluator-evaluee) and giving _feedback_ (giver-receiver)

The reason we changed `receiver` --> `evaluaee` is because a user commented that respondents get confused when they see `recipient` for questions that the person being evaluated is not supposed to _receive_ anything.

Options:
1. use `evaluator-evaluee` as this seems to fit both feedback and evaluations
2. use `giver/evaluator-receiver/evaluee` but this will take extra space
3. pick the correct term based on question type. This option is too complex.
4. keep current `giver-evaluee` 
    1. Use `evaluee` everywhere
    1. Use `evaluee` only in student views
    1. Use `evaluee/recipient` only in student views
5. go back to `giver-receiver`
6. use `respondent-evaluee`
7. ...?

What do you think? 4.ii or 4.iii seem the easier and closest to current situation.

**Comment by sukanta-27** [comment]
@damithc @wkurniawan07  Sir, as I am working on this, and has already replaced `recipient` to `evaluee` in `Features.jsp` (there was 1 hit) and `InstructorHelp` page (there were 60 hits), I am just curious to know, why only replace the words in "Student views" (if they are to be replaced at all), I mean why not replace it in instructor views as well? 

and FWIW If I had to choose I think option 1 is good. `evaluator-evaluee` is a good pair. :smile:

**Comment by damithc** [comment]
> I am just curious to know, why only replace the words in "Student views" (if they are to be replaced at all), I mean why not replace it in instructor views as well?

We used `giver/receiver` exclusively before, both in UI and backend. Changing it to something else everywhere is non-trivial. It's not simply a matter of search-and-replace.
The confusion with the term 'recipient' is related to students only, even more specifically, in the submission form. If we use option 4.iii (i.e. simply add `/evaluee`), it solves the problem with minimal change.

**Comment by sukanta-27** [comment]
@damithc Okay, I will work with option 4.iii

**Comment by damithc** [comment]
This is the current status (and the discrepancy):
![image](https://user-images.githubusercontent.com/1673303/34138671-adf9e3dc-e4ab-11e7-9192-356147fd6d51.png)

One way to fix this as follows, which also improves the UI (by removing the repetition `Evaluee`):
![image](https://user-images.githubusercontent.com/1673303/34139158-1f1e4402-e4ae-11e7-9f96-7fa53e8dafe7.png)

@TEAMMATES/seniordevs what do you think?

**Comment by sukanta-27** [comment]
@damithc 
**Update:**
I have changed the UI as suggested. [Screenshot]
![screenshot 273](https://user-images.githubusercontent.com/10681755/34321171-e0e6dc74-e82e-11e7-91d9-07ca0c0fc47a.png)

But apparently moving the `Evaluee/Recipient` from `response.tag` to `questionWithResponses.tag` also created this problem. [Screenshot] below.
![screenshot 274](https://user-images.githubusercontent.com/10681755/34321196-378fcd6a-e82f-11e7-9ac3-ad7a160bc15e.png)

Trying to fix this. :sweat_smile:

**Comment by damithc** [comment]
> I have changed the UI as suggested.

@sukanta-27 UI looks good. 👍
