### ISSUE TITLE
Dev docs: mention the need for npm run build

### ISSUE THREAD

**Issue by nbiswal** [TEAMMATES/teammates#8178]
Hello TEAMMATES,

While trying to setup TEAMMATES in our local machines we followed the steps provided in the "Development Guidelines" of TEAMMATES documentation. 

After the installation process was done in the dev server, while following the guidelines for "Logging in to a TEAMMATES instance", we tried adding a new instructor in the adminhome page. However it did not work as the submit button was not enabled. Also we could not locate any instructions in the documentation on how to resolve it. 
So we researched the problem and came up with the solution to add “**npm run build**” first and then try adding the instructor to the dev server from the Admin Home page. This detail needs to be added to the "**Development Guidelines**" of the TEAMMATES project documentation under “As Instructor” after the instructor enters his/her credentials so that new users don’t face any issue while testing for adding new instructors in the dev server.

Thanks
Team Mavericks(Niluja Biswal, Neeharica Kodali, Durgabhavani Peta, Kasi Viswanath)
University Of Nebraska,Omaha

**Comment by wkurniawan07** [comment]
@nbiswal thanks for the report.
This is a known limitation of the current documentation. In fact, the command `npm run build` should be run before starting the dev server and before deploying if there are changes to any JavaScript files (this includes being built for the first time), not limited to just when adding new instructors.

**Comment by nbiswal** [comment]
@wkurniawan07 thanks for the quick reply.
You are right we did execute the command "npm run build" before starting the dev server as well as before deploying the JavaScript Files but we still got the issue while adding new instructors. So do you think this can be added to the documentation guidelines under "Logging in to a TEAMMATES instance" so that new testers do not face this issue in future.

**Comment by wkurniawan07** [comment]
> we still got the issue while adding new instructors

That is not possible if you have run the said command. Did you possibly start the dev server _before_ running that command and then running it afterwards?

> So do you think this can be added to the documentation guidelines under "Logging in to a TEAMMATES instance"

It definitely needs to be mentioned somewhere, but not under that section. As I mentioned before, it is a thing to do before starting the dev server and before deploying if there are changes to any JavaScript files (this includes being built for the first time), _not limited to just when adding new instructors_.

**Comment by damithc** [comment]
> This is a known limitation of the current documentation. In fact, the command npm run build should be run before starting the dev server and before deploying if there are changes to any JavaScript files (this includes being built for the first time), not limited to just when adding new instructors.

@wkurniawan07 can do a quick fix for this?
