### ISSUE TITLE
IDE setup guide: Intellij: mention that JSP plugin should be enabled.

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8179]
As I was trying to set the code indentation level for JSP, I realized I need to enable the `Java Server Pages Integration` plugin for `JSP` to appear under _Code Style_ settings.

**Comment by LiHaoTan** [comment]
@damithc that's strange. That should be enabled by default. Do you recall disabling it?

> In relation to IntelliJ IDEA, plugins may be attributed to one of the following categories:

> - Plugins bundled with the IDE. These plugins are installed and enabled by default. You can disable unnecessary bundled plugins, but you cannot uninstall them.

https://www.jetbrains.com/help/idea/plugins.html

**Comment by damithc** [comment]
> That should be enabled by default. Do you recall disabling it?

I don't recall, but I may have. Let's see if anyone else report the same problem.

**Comment by damithc** [comment]
Closing for now.
