### ISSUE TITLE
Instructor create session: default questions: replace 'contribution question' 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8184]
Suggestion: In the default session template, replace the 'contribution question' with a simpler 'distribute points' type question. 

Suggested replacement question:
![image](https://user-images.githubusercontent.com/1673303/36838157-5d32cc0a-1d79-11e8-81f9-77dcc560fb33.png)

Reason: Although the former is more optimized for the purpose, it also generates too many support requests because users gets confused about how the question type works.

**Comment by joanneong** [comment]
I will like to work on this issue since I have been delving into `distribute points` type questions recently.

**Comment by joanneong** [comment]
Just to clarify, am I right to assume that the placeholder text should not be in the Description box when I replace it with the details in the image?

I.e. Like this:

![image](https://user-images.githubusercontent.com/24493463/37040611-3d23f9b4-2195-11e8-9c46-c057f0082dfb.png)

**Comment by damithc** [comment]
> @damithc Just to clarify, am I right to assume that the placeholder text should not be in the Description box when I replace it with the details in the image?

Yes, the screenshot looks correct.

**Comment by NicolasCwy** [comment]
I'll be working on this

**Comment by NicolasCwy** [comment]
To clarify, do we want to create a new template (optimised version that replaces the contribution question with the distribution question) as done in the previous PR or is replacing it preferred?

**Comment by damithc** [comment]
> To clarify, do we want to create a new template (optimised version that replaces the contribution question with the distribution question) as done in the previous PR or is replacing it preferred?

I wouldn't mind creating a new template altogether (if can be done without a lot of duplication), in case some existing users want to keep using the old template. Perhaps `team peer evaluation (percentage-based)` and ``team peer evaluation (point-based)`?


> Would we also have to change the sample sessions generated for instructor account creation too? Else I can revert the changes in my PR as well.

Perhaps we can tweak it to have both type of questions? e.g., One question on contribution to the presentation and another for contribution to documentation?
