### ISSUE TITLE
New Contributor Self Intro : Omar Ali

### ISSUE THREAD

**Issue by 3esawe** [TEAMMATES/teammates#8186]
Hello! My name is Omar Ali and I am a student of Network Engineering . I am looking to better understand the process of contributing to an open source project. I have a good java background .I found TEAMMATES one of the recommended open source project in google . so I'm really exciting about the experiment in open source project and I hope that I can learn a lot from this experiment about the process of open source project .  I have not made any UI changes , and I don't have the links 
Thank you!

**Comment by LiHaoTan** [comment]
Hi Omar, welcome to TEAMMATES! You can get your feet wet by working on a `d.FirstTimers` issue, then move on to `d.Contributors` issues. :)
