### ISSUE TITLE
Instructor Search Bar Enhancement 

### ISSUE THREAD

**Issue by jessleary96** [TEAMMATES/teammates#8187]
**Description of feature/enhancement**
Enhance the search bar feature from the Instructors account in regard to searching for text that is surrounded by tags. 

For example, in the first image below, when there are spaces between the tag and the text to search, the search will still return the correct search results. However, in the second image, when there are no spaces between the tags and text to search, the search will return "No results found." 

First Screenshot: Search with spaces between tags and the text one is searching (correct results)

![searchbar1](https://user-images.githubusercontent.com/31485697/33388908-489e7f18-d4ff-11e7-8819-65bb475925ca.png)

Second Screenshot: Search with no spaces between tags and the text one is searching (incorrect results)

![searchbar2](https://user-images.githubusercontent.com/31485697/33388917-4d10b50c-d4ff-11e7-804c-243a0a295cdd.png)

Search engines such as Google ignore tags and return accurate results.

**Justification**
This enhancement will allow for a more precise search engine.

**Comment by damithc** [comment]
That's a useful enhancement @jessleary96. Thanks for the suggestion. I don't think it is worth implementing though. We don't expect users to have tags in their search strings.

**Comment by jessleary96** [comment]
Thank you @damithc for the feedback!

**Comment by damithc** [comment]
Closing for the time being due to low priority.
