### ISSUE TITLE
Instructor Text/Background Color Enhancement 

### ISSUE THREAD

**Issue by jessleary96** [TEAMMATES/teammates#8188]
**Description of feature/enhancement**
As an instructor, when you create a new feedback session there is an instructions text box where the instructor can put instructions for the session. When one hovers over different text and background color options, this choice is not then hi-lighted to indicate which choice you are hovering over.

This screenshot below shows the area I am referring to. 

![hilight](https://user-images.githubusercontent.com/31485697/33391328-a099bea6-d506-11e7-96ae-71378fe3797d.png)

This enhancement would include adding a hi-light feature over the text or background color that the user's cursor is hovering over.

**Justification**
This will make the application more user friendly and easier for the user to see what text or background color option they are hovering over. Applications such as Microsoft Word have this hi-lighting feature in place.

**Comment by damithc** [comment]
Yes, that might be useful. Thanks for the suggestion @jessleary96  We are using a third-party library for the rich-text feature; it is unlikely that we'll modify the library to implement that feature.

**Comment by jessleary96** [comment]
Thank you @damithc for the feedback!

**Comment by damithc** [comment]
Closing for the time being due to low priority.
