### ISSUE TITLE
Instructor: help page: remove link-style formatting from sub-titles

### ISSUE THREAD

**Issue by jessleary96** [TEAMMATES/teammates#8190]
Description of feature/enhancement
Within the help document, various subtitles show up with a blue line underlining/highlighting them as if they are a hyperlink to click on and retrieve more information from. This could present confusion for users who may think they are missing additional information or be looking for a link to follow. 

Attached below are two screenshots that show the hi-lighting area I am referring to.

![help1](https://user-images.githubusercontent.com/31485697/33411651-d31df4de-d554-11e7-9f9b-27b320f5728d.png)

![help2](https://user-images.githubusercontent.com/31485697/33411658-d934e350-d554-11e7-98ed-4c941d9d4a77.png)

The enhancement would remove this hi-lighting/underlining when hovering over a subtitle. 

Justification
This will make the application more user friendly and easier for the user to understand.

**Comment by damithc** [comment]
Good suggestion @jessleary96 
Some additional info for the benefit of the person attempting to fix this issue:
Examples of problematic headings:
![image](https://user-images.githubusercontent.com/1673303/34067571-833a7a56-e264-11e7-9a2c-f67837132d63.png)
This problem doesn't appear in the help page for students (i.e. `/instructorHelp.jsp`)

**Comment by craaaa** [comment]
I'll take this!

**Comment by craaaa** [comment]
Hi @damithc, I noticed a few inconsistencies in `instructorHelp.jsp` while changing the link tags:
- Linebreaks are not consistent between paragraphs (e.g. some used 2 `<br>`s while other lines used 3).
- Use of `h3` and `h4` tags was also not standardized across the document - for instance, the `Archiving` section uses `h3` tags for question headings, while the `FAQ` section just uses `<b>`.

Should they be standardized?

**Comment by damithc** [comment]
> Should they be standardized?

Sure @craaaa
