### ISSUE TITLE
New contributor self intro [Barbara Rodriguez]

### ISSUE THREAD

**Issue by bjrodrig** [TEAMMATES/teammates#8191]
**Link to my fork:** e.g. https://github.com/bjrodrig/teammates

**Screenshot of changes made (as seen on the UI)**
<img width="943" alt="home page with light orange" src="https://user-images.githubusercontent.com/29617046/33433258-e3093616-d5a8-11e7-9001-dfea3cb61b71.PNG">
Changed font color of "Student peer evaluations/feedback..." to light orange.

**Short self-introduction**
My real name is Barbara Rodriguez. I am attending University of Maryland in January 2018 to get a bachelors degree in Computer Science. I want to contribute to TEAMMATES to learn quality coding practices and to practice coding in a professional environment.

**Comment by LiHaoTan** [comment]
Hi Barbara, welcome to TEAMMATES! I see you have tinkered with the project. You can get your feet wet by working on a `d.FirstTimers` issue, then move on to `d.Contributors` issues. :)

**Comment by bjrodrig** [comment]
Thanks LiHao!
