### ISSUE TITLE
New contributor self intro: Paweł Bąk

### ISSUE THREAD

**Issue by baczus0** [TEAMMATES/teammates#8192]
Fork repo: https://github.com/baczus0/teammates
Changes:

![](https://i.imgur.com/8M0I1GN.png)

Changed `<input type="text">` to `<textarea>` to allow to see more rows in admin email logs.

I'm Paweł Bąk form Poland. I study Theoretical Computer Science at Jagiellonian University in Cracow and I work as Java Developer.  It is my first open source project and I'm glad to start contributing it.

**Comment by LiHaoTan** [comment]
Hi Paweł, welcome to TEAMMATES! Looks like a useful change. You can get your feet wet by working on a `d.FirstTimers` issue, then move on to `d.Contributors` issues. :)
