### ISSUE TITLE
New contributor self intro: Anubhav

### ISSUE THREAD

**Issue by achaudhary997** [TEAMMATES/teammates#8194]
Fork Repo: https://github.com/achaudhary997/teammates
Changes:
![image](https://user-images.githubusercontent.com/19773496/33655599-803b7972-da99-11e7-8a96-229205cbd28c.png)

Added a scroll to Top link in the bottom right of the instruction page to allow the user to go back to the top. These were there before but they were at the end of each section and some sections were quiet long so it was tough to find the scroll to top link.

I'm Anubhav Chaudhary from India. I study Computer Science and Engineering at Indraprastha Institute of Information Technology, Delhi. Have worked on Java projects as a freelancer. This is my first open-source project and I look forward to contributing to it.

**Comment by sukanta-27** [comment]
Hi @achaudhary997 

Welcome to TEAMMATES! You may wish to start by taking on one of our `d.FirstTimers` issues, before moving on to `d.Contributors` issues :)
