### ISSUE TITLE
Help Request: 38 Failed Tests

### ISSUE THREAD

**Issue by keoren3** [TEAMMATES/teammates#8196]
Hello,

- Operating System: Windows 7
- JDK Version: 1.8
- Eclipse Version: Eclipse OXYGEN
- Firefox Version: 46.0

**What I was trying to do / What I need help with**
I was resolving test failures.
I think i have some kind of a problem with the Encoding, but I can't seem to solve it.
I added a few screen shots of what is wrong at the end of the post.
needless to say that I ran this more than a few times.

**Attempts to resolve the problem**
searched the problem in the 'Developer Troubleshooting Guide', but couldn't find anything.
then..
I checked the encoding - UTF-8 as should be.
Changed the language on windows from my native language to English.
Added Spanish keyboard (thought it would help, it didn't).

I'm new here, this is all new for me, please be patient - I'm doing my best.
Thank you very much!
Oren.

![37 fails](https://user-images.githubusercontent.com/34122776/33797905-7e4689a0-dd18-11e7-8fc6-907fd101dbd1.JPG)
![an example](https://user-images.githubusercontent.com/34122776/33797906-806a25b6-dd18-11e7-9955-f0a7a99c2a38.JPG)
![another example](https://user-images.githubusercontent.com/34122776/33797907-83b34252-dd18-11e7-8496-3dd0608baf95.JPG)
![last one](https://user-images.githubusercontent.com/34122776/33797908-85c19e72-dd18-11e7-87a7-f78772676110.JPG)

**Comment by sukanta-27** [comment]
@keoren3 I was facing a similar issue, and apparently only setting the project specific text encoding to `UTF-8` was not solving it. I changed the workspace preference text encoding to `UTF-8` and it solved this issue. 

Can you please check if your `Window ->Preference -> General -> Workspace -> Text file encoding` settings is this or not?
![screenshot 263](https://user-images.githubusercontent.com/10681755/33799814-39919994-dd59-11e7-9bbf-9ce9a802d0fd.png)

if not then change the settings accordingly and run the tests again. And let me know if the issue resolves or not.

**Comment by keoren3** [comment]
I can't tell you how much I appreciate your help!
Thank you very much.

I actually tried looking in Window -> Preference, but I couldn't find where to change the encoding.

Thanks again!

**Comment by damithc** [comment]
Thanks for helping @sukanta-27 👍
