### ISSUE TITLE
Help Request: [Execution failed for task ':appengineStage' .]

### ISSUE THREAD

**Issue by keoren3** [TEAMMATES/teammates#8199]
- **Operating System: Windows 7**
- **JDK Version: 1.8**
- **Eclipse Version (if applicable): Oxygen.1a Release (4.7.1a)**
- **Firefox Version (where applicable): 4.60**

**What I was trying to do / What I need help with**
I am trying to Deploy to a staging server on the 'Google Cloud Platform'
I tried running this command:
`./gradlew appengineDeploy`
I got this error:
"FAILURE: Build failed with an exception"
Here is a screenshot:
![capture](https://user-images.githubusercontent.com/34122776/33911545-6af9c6d4-df9b-11e7-99b1-f459bac5b4a7.JPG)

**Attempts to resolve the problem**
Made sure the engine is running in the Eclipse.
Made sure the cloud shell is connected.
Made sure the settings were o.k.
Then I tried looking into the files:
"build.properties" and "appengine-web.xml", but couldn't find any clue to :appengineStage.
then I tried searching the issue tracker.
then I tried entering help.gradle.org
Sadly, couldn't find anything.

Any help would be great,
Thank you,
Oren.

**Comment by wkurniawan07** [comment]
@keoren3 unfortunately, the screenshot you sent did not really help. I will need some more information in order to help.

> Made sure the engine is running in the Eclipse.

What exactly do you mean by above?

> Made sure the cloud shell is connected.

What "cloud shell" are you talking about?

> Made sure the settings were o.k.

How are you making sure that the settings are OK? Which "settings" are involved here in the first place?

Also, it may help if you can run the command with `--stacktrace` flag and paste the output here.

**Comment by keoren3** [comment]
Hi,

First of all, thank you for your comment, I highly appreciate it.
So I was working by this manual:

https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#deploying-to-a-staging-server

I did all the stages before, and I got to the section "Deploying to a staging server".
And I'm a bit stuck now.

> Made sure the engine is running in the Eclipse:
I meant that I started the server in the eclipse as shown down here:

![eclipse_running](https://user-images.githubusercontent.com/34122776/34006033-9a8ea958-e105-11e7-89e0-d1e239aa3f9b.JPG)

> Made sure the cloud shell is connected:

I mean that I'm authenticated in the Google Cloud SDK Shell:
![authorize google account](https://user-images.githubusercontent.com/34122776/34006200-2d1119be-e106-11e7-9044-c08f76bddea3.JPG)

> Made sure the settings were o.k.:

I was talking about the templates of the files "appengine-web.xml" and "build.properties".

I'm adding a zip file that contains the error in a .txt file with the flag --stacktrace:
[ERROR.zip](https://github.com/TEAMMATES/teammates/files/1562342/ERROR.zip)

I tried to be as specific as I can, if there is any information missing, please tell me and I'll add it.

Thank again!
Oren.

**Comment by wkurniawan07** [comment]
@keoren3 I see "java.lang.RuntimeException: Cannot get the System Java Compiler. Please use a JDK, not a JRE." in the logs; can you check if your `PATH` variable (`echo %PATH%`) contains a JRE? It should be a JDK instead.

**Comment by keoren3** [comment]
> @keoren3 I see "java.lang.RuntimeException: Cannot get the System Java Compiler. Please use a JDK, not a JRE." in the logs; can you check if your PATH variable (echo %PATH%) contains a JRE? It should be a JDK instead.

Probably a dumb question, but how am I supposed to change it?
is it here?:
![jre-jdk](https://user-images.githubusercontent.com/34122776/34071746-f3549fc8-e283-11e7-9767-007753586bdb.JPG)

But as you can see, the path is to the JDK folder.
I also checked here:
![check2](https://user-images.githubusercontent.com/34122776/34071756-1f3dd6c2-e284-11e7-858e-4c87e37a5470.JPG)

But it seems to be o.k.

Or am I supposed to change something in a settings file?
I'm new to this and probably missing something.
Thanks again for the help,
Oren.

**Comment by wkurniawan07** [comment]
@keoren3 All the settings in Eclipse are not relevant when running `./gradlew appengineDeploy` with command line. Changing `PATH` variable is a rather risky action so I will not recommend it unless you're exactly sure what you're doing. Instead, you should change [this line in your gradle.properties file](https://github.com/TEAMMATES/teammates/blob/master/gradle.template.properties#L9).

But from the screenshots you posted I see that you have successfully deployed your own application to your staging server. I'm curious, do you still need to deploy again with the Gradle command?

**Comment by keoren3** [comment]
Well, I don't really know what the staging server is, I'm trying to figure things out as I go (still a computer science student).

I tried changing the line you said, but it still doesn't work.
is there something wrong here?
![capture](https://user-images.githubusercontent.com/34122776/34078345-2be89b3a-e321-11e7-9eee-0bbacdbb685b.JPG)

Can I just skip this stage and it won't affect me in the future, or at least not in the near future?

**Comment by wkurniawan07** [comment]
@keoren3 I doubt this is the problem, but it could be the trailing slash (`/`). See if removing it works. Of course, I assume that the folder `C:/Program Files/Java/jdk1.8.0_151` exists. If it still does not work, you can post the stack trace again here (it should be a different stack trace this time).

> Can I just skip this stage and it won't affect me in the future

This step in fact is not even necessary if you just want to work on your local environment. Also you can successfully deploy with Eclipse, which effectively does the same thing when the need ever arises.

**Comment by keoren3** [comment]
It still didn't work, but I think I'll just continue.
I'm sure that eventually, after using the system and working with it a little, I'll know better how to take care of these kind of problems.
Right now I feel that I'm just wasting your time, waiting for you to hand me the solution, and I don't think that is the correct way.

Thank you very much for your time, I appreciate it very much!
