### ISSUE TITLE
Student view results: Fix anonymity breach for self-feedback questions

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8203]
Question setting:
![image](https://user-images.githubusercontent.com/1673303/34023590-b171f87a-e180-11e7-9bce-e6c6d82d2493.png)

What students see:
![image](https://user-images.githubusercontent.com/1673303/34023576-a2d303c2-e180-11e7-9abc-2bf23d885816.png)

If there is another anonymous question, students can figure out who gave each responses (because we use the same anonymous ID for all responses from the same student)

**Comment by damithc** [comment]
@TEAMMATES/seniordevs this needs an urgent fix as there is one user who cannot publish results due to this.

**Comment by wkurniawan07** [comment]
@damithc how exactly should this be remedied? "we use the same anonymous ID for all responses from the same student" is actually a conscious decision (#5228). This becomes somewhat like conflicting requirements.

**Comment by damithc** [comment]
@wkurniawan07 note that the giver's team members should not be able to see giver or receiver name (they should see the response only) yet we show the receiver name.

On a related note, I think we should reverse the decision to have matching random identifiers and go back to fully random identifiers. In fact I deployed a hot fix to do exactly that which mitigates the problem in this issue (although the root cause is a different bug).

**Comment by xpdavid** [comment]
@damithc 

> Note that the giver's team members should not be able to see giver or receiver name (they should see the response only) yet we show the receiver name.

This is because of the line https://github.com/xpdavid/teammates/blob/master/src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java#L842. If the question type is SELF feedback, we would show recipients' name anyway. 

So I think the discussion would be back to whether we should bring random identifiers for anonymous students.

**Comment by damithc** [comment]
> This is because of the line https://github.com/xpdavid/teammates/blob/master/src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java#L842. If the question type is SELF feedback, we would show recipients' name anyway.

I think that line possibly has a bug. The intention of the setting below is clearly for team members to see the answer without seeing giver or recipient name (both boxes are unticked). 
![image](https://user-images.githubusercontent.com/1673303/34069491-7c974368-e28d-11e7-8412-4643a292519c.png)

i.e. team members should be something like 
```
from: anonymous student 1234
to: anonymous student 1234

I did my work.
```

**Comment by xpdavid** [comment]
@damithc If we remove the condition that "if a question is self-feedback, we would show recipients' name anyway", we would get the following result and it is as expected.

![image](https://user-images.githubusercontent.com/13977235/34079234-732be554-e364-11e7-9921-92b161e234d0.png)
(In this case, it is not possible to figure out the name from the identifier)

I have rerun the full test suite after the removal of the condition and it seems like there is no regression. We can fix it by doing this.

**Comment by damithc** [comment]
Good work @xpdavid 
One slight concern is that `SELF` is an internal term which should not (ideally) show up in the UI. Dig around a bit more to see if it can be avoided too?

**Comment by xpdavid** [comment]
@damithc We could do the same things as giver name:
![image](https://user-images.githubusercontent.com/13977235/34079665-e9ab81e6-e36c-11e7-86be-816134a1f19f.png)
(In this case, since it is self-feedback question, it doesn't matter to show the same identifier for recipient and giver)

**Comment by xpdavid** [comment]
Just run `git blame` and find a problem. We cannot simply do the same things as giver name because of #5228. Maybe we could change it to `Anonymous`?

By the way, if we can fix the issue about the 'fixed' random identifier for the same person in anonymous feedback, all these issues would gone :p

**Comment by damithc** [comment]
> Just run git blame and find a problem. We cannot simply do the same things as giver name because of #5228. Maybe we could change it to Anonymous?
> By the way, if we can fix the issue about the 'fixed' random identifier for the same person in anonymous feedback, all these issues would gone :p

Ignore that for now (it affects any question whose answer might contain identifying information, not just self-feedback).  We'll fix that separately, but need to fix soon.

By the way, why does `To` is missing the word `student`?

**Comment by xpdavid** [comment]
@damithc fixed, will send a PR soon
![image](https://user-images.githubusercontent.com/13977235/34159152-2d55c25c-e503-11e7-8cff-bbede2e1047f.png)

**Comment by damithc** [comment]
Um, now the random number is missing from the `To` field? Shouldn't it be,
```
To: Anonymous student 1234
From: Anonymous student 1234
```
Or did you leave out the random number from `To` because it is the same as the one in `From`?

**Comment by xpdavid** [comment]
@damithc because of the #5228. I don't want to break the 'promise' exist in the current programme.

**Comment by damithc** [comment]
> @damithc because of the #5228. I don't want to break the 'promise' existed in the current programme.

Omitting the random number doesn't help. Students know this question is a self-feedback question which implies it is the same random number whether we show it or not. But not to worry about it because I have applied a hot fix on the live server to make it fully random. I'll keep using that patch until #5228 is fixed in the master branch.
