### ISSUE TITLE
New contributor self intro: Adrian Siwiec

### ISSUE THREAD

**Issue by pierreSquared** [TEAMMATES/teammates#8205]
Forked repository: https://github.com/pierreSquared/teammates

Added colons after names of the fields in Student Details Page.

Screenshot: 
![screenshot from 2017-12-15 16-55-22](https://user-images.githubusercontent.com/12675382/34050108-fc0ddc6c-e1b9-11e7-918c-5eb187a81761.png)

My name is Adrian Siwiec, I'm a Computer Science student from Jagiellonian University, Poland. Previously interned as Java and C# developer, also did a couple of projects in Java. It's the first open-source project I'm going to contribute to, I hope to do some good work and learn a lot :)

**Comment by damithc** [comment]
Welcome to TEAMMATES @pierreSquared Looking forward to your first contribution.
