### ISSUE TITLE
New contributor self intro: Joanne Ong

### ISSUE THREAD

**Issue by joanneong** [TEAMMATES/teammates#8207]
- **Link to my app:** e.g. https://teammates-joanne.appspot.com
- **Link to my fork:** e.g. https://github.com/joanneong/teammates

**Screenshot of changes made (as seen on the UI)**
**Before:**
<img width="555" alt="before" src="https://user-images.githubusercontent.com/24493463/34100733-65e75152-e41e-11e7-9176-930a22f44bac.png">

**After:**
<img width="553" alt="after" src="https://user-images.githubusercontent.com/24493463/34100738-6ba22860-e41e-11e7-876a-d50b4acebedd.png">

The screenshots above show the changes to the Admin Activity Log page, in particular, the references panel that admins can press on to learn how to search through the activity log. Although the entries in the suggestions table were already color-coded, I have further ordered the entries alphabetically, which can make it easier for the admin to find their desired request.

**Short self-introduction**
I am Joanne Ong, currently a year 2 computer science undergraduate at National University of Singapore (NUS). I am looking to contribute to teammates mainly because (i) I am trying for CS3281/82 and (ii) this is my first involvement with an OSS, and there will definitely be a lot to learn from this. I am not sure if this self-intro is necessary for NUS students, but following the Contributor Orientation Guide has led me to this. To my dismay, after reading through all the documentation and finally being ready to start on some work, it seems that all the issues labelled `d.FirstTimers` have been taken/ covered by an opened PR. Can I check if this means that interested contributors should skip the first-timers step, and attempt a contributor's issue?

**Comment by damithc** [comment]
Welcome to TEAMMATES @joanneong 

> Can I check if this means that interested contributors should skip the first-timers step, and attempt a contributor's issue?

Yes you can 👍
