### ISSUE TITLE
New contributor self intro: Pan Haozhe

### ISSUE THREAD

**Issue by Haozhe321** [TEAMMATES/teammates#8212]
link to my app: [https://teammates-haozhe.appspot.com](url) 
link to my fork: [https://github.com/Haozhe321/teammates](url)

UI- before:
<img width="1118" alt="teammate_ui_before" src="https://user-images.githubusercontent.com/26651556/34158955-66a80c3c-e502-11e7-9028-bb293b90598d.png">

UI- after:
<img width="1105" alt="teammate_ui_after" src="https://user-images.githubusercontent.com/26651556/34158981-7cda8200-e502-11e7-89dd-370354fb83f4.png">

Initially, not all the origanisations are being linked. So I created links for all of them for 2 reasons. 
1) Make the acknowledges look more consistent
2) Provide convenience to those who want to access the pages of the organisations

**Self Introduction:** 
Hi everyone, my name is Haozhe. I'm from NUS, currently a Y2 CS student. I am planning to enrol in CS3281/82 next semester, and TEAMMATES looks promising so here I am. This is the first time I'm contributing to OSS. Very excited and looking forward to learning new stuff along the way!

**Comment by sukanta-27** [comment]
Hi @Haozhe321 

Welcome to TEAMMATES! You may wish to start by taking on one of our `d.FirstTimers` issues, before moving on to `d.Contributors` issues :)
