### ISSUE TITLE
Java: Use Java 7 try-with-resources for AutoCloseable resources

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#8213]
Stuffs like [this](https://github.com/TEAMMATES/teammates/blob/master/src/test/java/teammates/test/driver/FileHelper.java#L23-L32):
```java
BufferedReader br = new BufferedReader(new FileReader(filePath));
Scanner sc = new Scanner(br);
try {
    return sc.useDelimiter("\\Z").next();
} finally {
    sc.close();
    br.close();
}
```
can be modified to use the [try-with-resources statement](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html):
```java
try (Scanner sc = new Scanner(new BufferedReader(new FileReader(filePath)))) {
    return sc.useDelimiter("\\Z").next();
}
```
The benefit is two-fold: makes the code shorter and also closes the linked resources without fail, although admittedly I cannot say for sure what will happen if the resources do leak.

There are more than 10 places in the code base where this can be applied. Some common [`AutoCloseable`](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html) resources are `FileWriter`, `BufferedWriter`, `PrintWriter`, `FileOutputStream`, `OutputStreamWriter`, `Scanner`, `FileReader`, `BufferedReader`, `FileInputStream`, `InputStreamReader`.

**Comment by lucniner** [comment]
Hi @wkurniawan07 ,
I had a look at the issue, but mainly found try catch blocks with exception types which do not implement `java.lang.AutoCloseable`, which is necessary for your proposed changes. As far as I can tell, there is one code block beside your mentioned one, which could be changed, but then the semantics of that block would change (handling of the non existing file) [see here](https://github.com/TEAMMATES/teammates/blob/7f6c17a7f4d8ae3740d97f68916bd99b967058ce/src/client/java/teammates/client/scripts/OfflineBackup.java#L397-L415).

> The benefit is two-fold: makes the code shorter and also closes the linked resources without fail, although admittedly I cannot say for sure what will happen if the resources do leak.

If by that you mean, what happens, when there is for example an `IOException` then the resouce would still be closed. Have a look at the try-with-resource documentation, paragraph after the code example [here](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html)

**Comment by wkurniawan07** [comment]
@lucniner thanks for your input. I believe you just have not looked hard enough, or maybe you are looking for the wrong things. I'm not sure what you meant by "exception types which do not implement `java.lang.AutoCloseable`" though because exceptions _do not_ implement `AutoCloseable` in the first place.

> As far as I can tell, there is one code block beside your mentioned one, which could be changed, but then the semantics of that block would change (handling of the non existing file)

That is because you tried to change the whole try-catch block. Try-with-resources does not reach that far; `File` is not one such `AutoClosable` resource. But that code block can benefit from try-with-resources, although not in the way that you previously thought.

> If by that you mean, what happens, when there is for example an IOException then the resource would still be closed.

That is the benefit of try-with-resources statement, which I already mentioned in "closes the linked resources without fail". What I am not sure of (and perhaps not really worth it to find out) is what will happen if I do not use try-with-resources and do not close the resources.

**Comment by judeibe** [comment]
I will give this try.

**Comment by upatidar7** [comment]
Hey, i would like to work on this, it would be my first open source contribution.

**Comment by upatidar7** [comment]
#8308

**Comment by upatidar7** [comment]
Please review it #8308

**Comment by whipermr5** [comment]
Effort tracker, to be updated as each PR is merged:

| PR | Effort |
| - | - |
| #8308 | 2 |

**Comment by sprea** [comment]
Is this still open? I guess I found all of them fixed.

**Comment by wkurniawan07** [comment]
@sprea right now there are at least 6 more instances that can benefit from try-with-resources.

**Comment by lightt77** [comment]
@wkurniawan07  I am a newbie to this project and would like to work on this.Is it okay?

**Comment by wkurniawan07** [comment]
@lightt77 feel free to, no need to ask.

**Comment by shresthabarsha** [comment]
Is this issue still open? I'd like to work on it and make my first contribution

**Comment by wkurniawan07** [comment]
@shresthabarsha it's still open and you're free to work on it.
