### ISSUE TITLE
Java: Use Java 8 map.putIfAbsent and map.computeIfAbsent

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#8215]
Context: Someone wants to add a key-value pair to a map if the key-value pair does not exist.

Pre-Java 8:
```java
if (!map.containsKey(key)) {
    map.put(key, value);
}
```
Java 8:
```java
// If value is independent of key
map.putIfAbsent(key, value);

// If value is dependent of key
map.computeIfAbsent(key, key -> process(key));
```

For this one there are more than 20 places. Have to fix no less than 20 to qualify for a valid PR.

**Comment by wenmogu** [comment]
i can take this!

**Comment by SivagurunathanV** [comment]
If this hasn't been fixed yet, I would like to work on it, starting today. Thank you!

**Comment by whipermr5** [comment]
Effort tracker, to be updated as each PR is merged:

| PR | Effort |
| - | - |
| #8226 | 4 |

**Comment by mau0727** [comment]
Hello,
I was looking into #8226.
So is this considered resolved now ?

**Comment by wkurniawan07** [comment]
@mau0727 no; there are still quite a lot of places that can benefit from `putIfAbsent` and `computeIfAbsent`, although they are admittedly harder to find than the ones already resolved in #8226.

**Comment by gthd** [comment]
I would really like to search and fix the remaining.

**Comment by kathandp98** [comment]
I am a beginner, and I want to contribute to open source in java. I found this project interesting. 
Can someone suggest me where to start within this project and contribute?
Thank you.

**Comment by wenmogu** [comment]
Hi @kathandp98 thx for wanting to contribute. I noticed that you have not introduced yourself to our contributor community yet:) I suggest that you can take a look at [this document](https://github.com/TEAMMATES/teammates/blob/master/docs/CONTRIBUTING.md) if you just started with this project. This document will give you a step-by-step guide on how to start as a contributor.

If you have done all the steps required in that documentation, you can start contributing to issues labelled with the blue tag `d.FirstTimers`. Those issues are mostly about replacement of code (just like this one) or editing some other minor mistakes within the codebase. Hope you enjoy this project.

**Comment by whipermr5** [comment]
@wenmogu The self-introduction is no longer a requirement as of b8b73c189237a45de9e200d72e28859003f7c865 (#8602). But yes, that document is an excellent place to start 👍

**Comment by kathandp98** [comment]
@wenmogu  and @whipermr5 .Thanks for the reply. I will follow up the steps, and again if I will have doubts, I will post the comment. i will try my best to learn and contribute.

**Comment by pedrolarben** [comment]
Hi, I want to contribute to the project and I have been working on this issue. I have look to the whole code and I have found just 6 pieces of code where I can use _.putIfAbsent_, _.computeIfAbsent_. or _.computeIfPresent_. 
Should I do a Pull Request with these changes?

**Comment by wenmogu** [comment]
@pedrolarben yes sure. There r a lot of places for change. Just make sure what you find is not something in the ongoing PR for this issue :)

**Comment by pedrolarben** [comment]
@wenmogu cool. I'm going to create a PR with different changes of the ongoing PR :)

**Comment by JonathanGin52** [comment]
Hey, I am also new to opensource projects and would love to contribute! Is this issue resolved?

**Comment by wenmogu** [comment]
Hello @JonathanGin52 welcome to TEAMMATES :) yep this issue is almost resolved, you can try your hand on other first timer issues

**Comment by JonathanGin52** [comment]
@wenmogu Thanks for the greeting 😄, I'll be sure to check out the other issues

**Comment by miderleta** [comment]
Hi, Is this issue resolved. I would like to help as well.

**Comment by prab2112** [comment]
Is this issue resolved? I would like to help as well.

**Comment by reeshabhkumarranjan** [comment]
Is this issue still open?
