### ISSUE TITLE
Java: Use Java 8 map.forEach to iterate through map entries

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#8216]
Pre-Java 8:
```java
for (Map.Entry<String, String> entry : map.entrySet()) {
    String key = entry.getKey();
    String value = entry.getValue();
    process(key, value);
}
```
Java 8:
```java
map.forEach((key, value) -> {
    process(key, value);
});
```

A lot of places where this can be applied. Have to fix no less than 20 to qualify for a valid PR.

Note that this issue is limited to maps only. While `list.forEach(item -> { ... })` exists, there is no clear benefit over `for (String item : list) { ... }`.

**Comment by joanneong** [comment]
Got it. Let me take this as a warm-up to Java 8 and re-familiarise myself with Intelli's shortcuts.

**Comment by deydebaditya** [comment]
Okay! I'll take on this as my warm up and getting to understand the code base for further contributions to TEAMMATES.

**Comment by HoussamGHAZALA** [comment]
Hello @joanneong is this issue fixed by someone ?

**Comment by joanneong** [comment]
Hello @HoussamGHAZALA , this issue has already been closed :) Please look for another open issue to work on :)
