### ISSUE TITLE
Java: Use Java 8 lambda as comparators

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#8217]
Pre-Java 8 method of sorting a list:
```java
// natural order
Collections.sort(list);

// reverse order
Collections.sort(list);
Collections.reverse(list);
// alternatively
Collections.sort(list, Collections.reverseOrder());

// custom order
Collections.sort(list, new Comparator<String>() {
    @Override
    public int compare(String s1, String s2) {
        ...
    }
});
```
Java 8:
```java
// natural order
list.sort(null);

// reverse order
list.sort(Comparator.reverseOrder());

// custom order
list.sort((s1, s2) -> {
    ...
});
// custom order previously using only compareTo
list.sort(Comparator.comparing(obj -> obj.attribute));
// alternatively
list.sort(Comparator.comparing(CustomClass::getAttribute));
```
There are very likely ~100 places where this can be applied. Have to fix no less than 30 to qualify for a valid PR, and not more than ~~10~~ 1/3 of the number fixed can be trivial/non-custom ones.

**Comment by LuLechuan** [comment]
Can I take this issue? Thanks

**Comment by LuLechuan** [comment]
Hi, should I change this as well since it appears in some files?

For replacing chain comparisons in Java8 with Comparator.thenComparing()

Pre-Java 8 method of chain sorting:

int result = o1.first.compareTo(o2.first); 
if (result == 0) result = o1.second.compareTo(o2.second); 
if (result == 0) result = o1.third - o2.third; 
return result; 

Java 8:
objs.sort(Comparator.comparing((Obj o) -> o.first).thenComparing(o -> o.second).thenComparingInt(o -> o.third));

Should I change those as well for consistency?

**Comment by wkurniawan07** [comment]
@LuLechuan you're very welcome to. Just remember to meet the minimum numbers of fix required.

**Comment by tshradheya** [comment]
I will be doing all necessary changes in the /storage directory as I have noticed @LuLechuan hasn't done that yet in his PR

**Comment by tshradheya** [comment]
@LuLechuan I will also be doing the /client directory

**Comment by LuLechuan** [comment]
@tshradheya Sure.

**Comment by tshradheya** [comment]
@LuLechuan I noticed that you are already working on other directories than the ones I mentioned. Is there something which you would want me to work on?

**Comment by LuLechuan** [comment]
@tshradheya Hi, sorry for the late reply! I think some tests use sorting methods you can have a check through that. In addition, you can work on any files that I did not change.

**Comment by tshradheya** [comment]
Great. I have covered everything in my PR that you haven't done in your PR
