### ISSUE TITLE
New contributor self intro: Lu Lechuan

### ISSUE THREAD

**Issue by LuLechuan** [TEAMMATES/teammates#8220]
- Link to my app: https://6-0-0-dot-teammates-lechuan.appspot.com
- Link to my fork: https://github.com/LuLechuan/teammates/tree/tinker

- UI before change: 
<img width="960" alt="intructorhelpui before" src="https://user-images.githubusercontent.com/28507005/34192857-7ce0adea-e58b-11e7-84e5-b5a59f141045.PNG">
- UI after change:
<img width="960" alt="intructorhelpui after" src="https://user-images.githubusercontent.com/28507005/34192862-8588bfa0-e58b-11e7-8dc7-60f94ec93df5.PNG">
Initially, for the instructor help page, all the lists of questions are displayed and it is a bit hard to search for the desired one. Therefore, I have added a toggle function which can show/hide the small branches of the questions. Users would be able to search for the desired questions easily as they can just skip reading certain branches.

**Self-Introduction:**
This is Lu Lechuan, a year 2 computer science student from National University of Singapore. I am willing to contribute to TEAMMATES because of the following reasons:
1) I would like to cherish the opportunity to take the modules CS3281 and CS3282
2) This is the first time I am involved in a OSS project, I would like to take this chance to enhance my skills in working with a big project with a lot of excellent developers.
Thank you!

**Comment by sukanta-27** [comment]
Hi @LuLechuan 

Welcome to TEAMMATES! You may wish to start by taking on one of our `d.FirstTimers` issues, before moving on to `d.Contributors` issues :)

**Comment by LuLechuan** [comment]
Sure, thanks!
