### ISSUE TITLE
Help Request: I encounter JavaScript build problems while setting up my IDE (Eclipse).

### ISSUE THREAD

**Issue by deydebaditya** [TEAMMATES/teammates#8221]
- **Operating System:** Windows 10 (x64)
- **JDK Version:** 1.8
- **Eclipse Version:** Oxygen.1a Release (4.7.1a)
- **Firefox Version:** 57.0.2 (64 bit) 

**What I need help with**

I was trying to set up the project for starting off with contributing. I was in the process of setting up Eclipse IDE for the ease of development, and was following every instruction as stated in https://github.com/TEAMMATES/teammates/blob/master/docs/ide-usage.md , but I get the following error during the build process after I've set up the Eclipse IDE as per the instructions given in the link.

The stack trace of the errors I get are attached as file.
![screenshot 9](https://user-images.githubusercontent.com/11532634/34212703-267f6e86-e5c3-11e7-8114-4d397e652d47.png)

I would be grateful if I can get help regarding this. I am enthusiastic to start off with my contributions to this project and resolve issues in it.

**Attempts to resolve the problem**

I have tried cleaning the project, scrapping it off and starting afresh. I have even tried to build it with JDK versions 1.9, but nothing seems to work.

**Comment by wkurniawan07** [comment]
@deydebaditya there is one crucial step that you missed. Hint: take a look at the folder in which all the errors come from.

**Comment by deydebaditya** [comment]
@wkurniawan07 I've already added the rules to node_modules folder in Eclipse > Preferences for the JavaScript code style rules. Am I missing out on something more?

**Comment by deydebaditya** [comment]
@wkurniawan07 Thanks for the hint. I found the problem, I had mistakenly double tapped on the "Build" for validation, so it remain checked for JavaScript. I'll get started with TEAMMATES now.
