### ISSUE TITLE
New contributor self intro: Cara Leong

### ISSUE THREAD

**Issue by craaaa** [TEAMMATES/teammates#8225]
Hi all! I'm Cara. I'm here right now because I'm applying for CS3281/2, but actually mostly because open source work sounds really interesting and fulfilling and I am really excited to jump into a project with a bigg(er) codebase!

- My [app](https://teammates-cara.appspot.com)
- My [fork](https://github.com/craaaa/teammates)
- My UI change: I added `<div class="bs-example">` tags around examples in sections where these were missing in `instructorHelp.jsp` :)

![screenshot from 2017-12-20 22-17-19](https://user-images.githubusercontent.com/12183503/34214110-700018ee-e5dc-11e7-8c02-b079df47f00d.png)

**Comment by damithc** [comment]
Welcome to TEAMMATES @craaaa  :smile:
Good job setting up. :+1:
We look forward to your PRs to come.
