### ISSUE TITLE
New Contributor Self-Intro: Debaditya Dey

### ISSUE THREAD

**Issue by deydebaditya** [TEAMMATES/teammates#8228]
- **Link to my app:** Will deploy it soon, currently facing Internet connectivity issues, upload failing.
- **Link to my fork:** https://github.com/deydebaditya/teammates

**Screenshot of changes made (as seen on the UI)**
I've added the navigation bar to the help pages, for ease of navigation of users.

**UI Before:**
![screenshot 12](https://user-images.githubusercontent.com/11532634/34243482-03426912-e647-11e7-8c5b-351f3a08027f.png)

**UI After:**
![screenshot 11](https://user-images.githubusercontent.com/11532634/34243486-0cfb5d9c-e647-11e7-8fbc-624597f01c95.png)

**Short self-introduction**

Hi! I'm Debaditya Dey, currently pursuing a degree of "Bachelors of Engineering" in the discipline of "Computer Science and Engineering" from Government College of Engineering, Aurangabad, Maharashtra, India. I'm originally from Kolkata, India.
I've always been interested in Software Development and I recently started off with open source and have been loving it since then. I've coded various projects throughout the years, some of which are hosted as public repositories on my GitHub. I've been coding in JAVA for long and I thought of looking for open source projects to contribute, which had the requirement of JAVA, when i stumbled upon TEAMMATES and it caught my attention. Having looked at the project and the issues, I got very interested and I immediately wanted to work on TEAMMATES and build features for it and resolve issues so that this project can grow more with my small contributions to it, during the course of which I hope to learn more and contribute better and in higher frequencies in the upcoming days.
I'm also a musician and I play the keyboard and the guitar. I love songs of almost any genre, which catches my attention, but I'm a slow rock/ jazz person in the morning. 
I can't wait to contribute and get to know and learn from all the awesome people worldwide who are contributing to this project. :)

**Comment by damithc** [comment]
Welcome to TEAMMATES @deydebaditya :smile:
We look forward to your PRs to come.
