### ISSUE TITLE
New contributor Self intro - Shradheya Thakre

### ISSUE THREAD

**Issue by tshradheya** [TEAMMATES/teammates#8231]
**Link to my app:** https://teammates-shradheya.appspot.com/

**Link to my fork:** https://github.com/tshradheya/teammates

Minor UI Change done: Made bullet type interface in _Terms Of Use_ page to improve readability.

Before:

![image](https://user-images.githubusercontent.com/12574756/34257477-19a8e23e-e66b-11e7-9ea5-51422aaa86e6.png)

After: 

![image](https://user-images.githubusercontent.com/12574756/34257496-2c44f0fe-e66b-11e7-89c3-c4c5561d746d.png)

Self Intro: I am Shradheya Thakre, an international student in Year 2, Computer Science in NUS. This is my first time contributing to an OSS project. I will be doing CS3281&2 in the following semester. I currently have mixed feeling of fear ( cause this is a big project I will be working on) and excited ( cause I will get to learn a lot of new things and gain worthy experience). So looking forward to this experience.

P.S. All `d.FirstTimers` issues have an open PR in progress, so I was wondering what do I start off with?

**Comment by damithc** [comment]
Welcome to TEAMMATES  :smile:
Good job setting up. :+1:
We look forward to your PRs to come. You can work on a `d.Contributor` issue if there are no `d.FirstTimer` issues left.
