### ISSUE TITLE
New contributor self intro: Wen Xin

### ISSUE THREAD

**Issue by wenmogu** [TEAMMATES/teammates#8234]
- link to my fork: https://github.com/wenmogu/teammates/tree/tinker

- The UI change I made: I removed all the nonfunctional/unnecessary hyperlinks in the titles and questions in instructor help page. 

Before change:
![ui-before](https://user-images.githubusercontent.com/28526038/34263158-822668f2-e6a9-11e7-8c3b-9dd77ede3cf8.png)

After change:
![ui-after](https://user-images.githubusercontent.com/28526038/34263171-89f372be-e6a9-11e7-91a3-c728704f8cdd.png)

- Hello everyone, I m Wen Xin, a Year 2 CS student from NUS who is interested in taking CS3281/82 next sem. This is my first time trying to get involved in such a big project. Hope I can do something for this community.

**Comment by damithc** [comment]
Welcome to TEAMMATES @wenmogu  :smile:
Good job setting up. :+1:
We look forward to your PRs to come.
