### ISSUE TITLE
Instructor: help page: make style of sections consistent

### ISSUE THREAD

**Issue by craaaa** [TEAMMATES/teammates#8237]
**Description of feature/enhancement**
Noticed stylistic inconsistencies in `instructorHelp.jsp` while working on #8224. For example:

- Paragraph spacing using `<br>` tags not consistent -- should perhaps use `<p>`?
- Inconsistent use of heading styles and numbering (compare FAQ and Sections)
- Missing example divs around some examples

Some examples of the inconsistencies:
![screen shot 2017-12-22 at 1 57 11 am](https://user-images.githubusercontent.com/12183503/34268500-e7baf3ba-e6bb-11e7-810f-ff725cd4134e.png)

**Justification**
Stylistic consistency will help readers identify logical sections in the text and more easily find the information they are looking for.

**Comment by harhur** [comment]
I can take this! Hoping that it will be good experience for my first PR.

**Comment by Fatehsandhu** [comment]
@craaaa Hey, I am a student learning about open source development at Seneca College in Toronto. Is it possible if you can assign this to me and I would love to contribute? Thanks a lot

**Comment by pranjaljn97** [comment]
@craaaa @damithc 
Hey, I am new to this project and getting acquainted with the community. 
Is this issue still unresolved? if yes, Assign me I would love to fix this issue.
Thank You

**Comment by damithc** [comment]
@pranjaljn97 there don't seem to be any open PRs for this issue yet. It is open and there for the taking.

**Comment by nidhi98gupta** [comment]
@damithc I would like to work on this issue.
