### ISSUE TITLE
setting-up.md: Fix tracking of upstream repository instructions

### ISSUE THREAD

**Issue by tshradheya** [TEAMMATES/teammates#8241]
For new contributors while setting up they might face difficulty before executing this command below.

(setting-up.md)

![img_20171223_154506](https://user-images.githubusercontent.com/12574756/34319647-88d8494a-e7f8-11e7-8acf-9184ea97a427.png)

The person needs to do `git fetch upstream` before setting your master branch to track the upstream's master branch as the branches of upstream haven't been fetched before setting it to be tracked

**Comment by kevinLamKB** [comment]
hello all, i don't see anyone working on this yet, so i'd like to take this issue.
