### ISSUE TITLE
 New issue New contributor self intro: Akshat Jain

### ISSUE THREAD

**Issue by dabbler011** [TEAMMATES/teammates#8243]
Link to app: https://teammates-akshat.appspot.com/
Link to repo: https://github.com/dabbler011/teammates/tree/Tinker
![ss](https://user-images.githubusercontent.com/24551629/34321478-ef7f3b3a-e835-11e7-88c3-29b8ecaef0cc.png)
Changed font of paragraphs to monospace.

I am Akshat Jain, I study Computer Science at IIIT Lucknow in India. I am looking forward to contribute in this project to improve my coding skills.

**Comment by shaharyar-shamshi** [comment]
Welcome to The Teammates We will be very glad for your contribution . To get your hand Wet with Teammates Code base you can solve any of **d.FirstTimer** issue were you will get fimilar with little bit of coding strategy and you will get further benefit while solving other issues
