### ISSUE TITLE
New contributor self intro: Kevin Lam

### ISSUE THREAD

**Issue by kevinLamKB** [TEAMMATES/teammates#8245]
- **Link to my app:** https://teammates-kevinlam.appspot.com
- **Link to my fork:** https://github.com/kevinLamKB/teammates/tree/tinker

**Screenshot of changes made (as seen on the UI)**
I noticed that the text alignment under [Comments](http://teammatesv4.appspot.com/instructorHelp.jsp#editComments) in the instructor help page was slightly off so i adjusted it to conform with all of the other sections in the help page.

**Before:**
![before2](https://user-images.githubusercontent.com/29567388/34322887-9ff59d8c-e86e-11e7-8ba7-741b921efbb3.png)

**After:**
![after3](https://user-images.githubusercontent.com/29567388/34322895-ca0d3bca-e86e-11e7-90bb-d378c8cdac5b.png)

**Short self-introduction**
Hi everyone, i am Kevin, year 3 student in Applied Maths/CS in NUS. I'm interested in joining CS3281/82 next sem, and at the same time am excited to be part of building on a big project such as TEAMMATES and learning from this experience. I hope to be able to make useful contributions during my stay here!

**Comment by damithc** [comment]
Welcome to TEAMMATES  :smile:
Good job setting up. :+1:
We look forward to your PRs to come. We recommend you start with a `d.FirstTimer` issue or a `d.Contributor` issue.
