### ISSUE TITLE
New Contributor Self-Intro: Nguyen Quoc Bao

### ISSUE THREAD

**Issue by bqnguyen94** [TEAMMATES/teammates#8246]
- **Link to my app:** https://teammates-quocbao.appspot.com
- **Link to my fork:** https://github.com/bqnguyen94/teammates

**Screenshot of changes made (as seen on the UI)**
![My teammates](https://i.imgur.com/P9nL2XW.png "Teammates screenshot 1")
I changed the buttons to be more flat-styled.

**Short self-introduction**

I am Quoc Bao, year 3 Computer Science student. I want to contribute to TEAMMATES because I want to gain experience working on a big project.

**Comment by damithc** [comment]
Welcome to TEAMMATES @bqnguyen94  :smile:
Good job setting up. :+1:
We look forward to your PRs to come. We recommend you start with a `d.FirstTimer` issue or a `d.Contributors` issue.
