### ISSUE TITLE
Java: Use Java 8 map.getOrDefault

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#8250]
Context: Someone wants to get the value associated to a key from a map, or a default value otherwise, but does not want to apply that mapping to the map afterwards.

Pre-Java 8:
```java
String s;
if (map.containsKey(key)) {
    s = map.get(key);
} else {
    // map.put(key, "Some default value"); <- if this one is not commented out, it becomes computeIfAbsent
    s = "Some default value";
}
```
Java 8:
```java
String s = map.getOrDefault(key, "Some default value");
```
About 20 places to fix.

**Comment by bqnguyen94** [comment]
I would like to take this!

**Comment by bqnguyen94** [comment]
Using Eclipse file search I could only find 7 instances of `map.containsKey` being replaceable by `map.getOrDefault`. Am I missing something?

**Comment by wkurniawan07** [comment]
Instances like [this](https://github.com/TEAMMATES/teammates/blob/master/src/main/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetails.java#L403-L406) can benefit from `getOrDefault`. I’ll leave it to you to figure out how.

**Comment by bqnguyen94** [comment]
I think I've got it. Thank you for the hint!
