### ISSUE TITLE
Improve introduction in the testing section

### ISSUE THREAD

**Issue by mrkagelui** [TEAMMATES/teammates#8254]
There is some incomplete and inaccurate information in the introduction of the testing section.

Let's improve it. Improvement suggestions can be found in #8255.

**Comment by OrionStar25** [comment]
I'd like to take up this issue.  We could add this information

> TEAMMATES automated testing requires Firefox or Chrome (works on Windows and OS X). It is recommended to use Firefox 46.0 as this is the browser used in CI build (Travis/AppVeyor).
before "Building Javascript Files" as they will have the required browser to work with from the very beginning. 
This would also result in a smoother flow. Please guide me on this.

**Comment by mrkagelui** [comment]
Hi @OrionStar25 I'm a first timer myself 😄 @LiHaoTan and I have been discussing in the PR referenced, feel free to join the discussion I think.

**Comment by Brybro** [comment]
@LiHaoTan - May I ask what is left to complete for this issue?
