### ISSUE TITLE
New contributor self intro Ong Ka-Shing

### ISSUE THREAD

**Issue by ongks** [TEAMMATES/teammates#8256]
- **Link to my app:** https://teammates-ongks.appspot.com/
- **Link to my fork:** https://github.com/ongks/teammates/

![image](https://user-images.githubusercontent.com/15803084/34342319-49ff02e0-e9e7-11e7-909e-feccef03227d.png)

I restructured the features page such that the features are shown as rows of two. This is because there is plenty of whitespace around each feature, which I felt could be filled up by rearranging the layout of the page.

**Short self-introduction**
Hi! I am Ka-Shing, a Yr 3 Computer Science student from NUS. I am interested in contributing to TEAMMATES as I find this a valuable opportunity to learn how to work with a huge codebase and as well as to gain experience from contributing to an open source project.

**Comment by damithc** [comment]
Welcome to TEAMMATES @ongks  :smile:
Good job setting up. :+1:
We look forward to your PRs to come. We recommend you start with a `d.FirstTimer` issue or a `d.Contributors` issue.
