### ISSUE TITLE
Help Request: Unable to start dev server behind university's proxy

### ISSUE THREAD

**Issue by gaurab4163** [TEAMMATES/teammates#8261]
- **Operating System:**
Windows 8.1

- **JDK Version:**
jdk1.8.0_151

-**What I was trying to do / What I need help with**

I was trying to set up the project, but when I run the following code:
`gradlew.bat appengineStart` or `gradlew appengineRun`, I get an error. This happened when I worked on my university's internet behind a proxy.

Then I tried running the same command connecting to my phone's hotspot on proxy-free internet. It worked!

-**Attempts to resolve the problem**
I tried searching for gcloud proxy config setting but couldn't find one. And I am pretty sure I have correctly configured my Git CMD's proxy settings. Anyone knows how to configure the proxy settings? Because it's very inconvenient for me to always use my phone's data.

The error I got I was:
`FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not resolve com.google.api-client:google-api-client-appengine:[1.19,2.0)
.
  Required by:
      project : > com.google.appengine.tools:appengine-gcs-client:0.7
   > Could not resolve com.google.api-client:google-api-client-appengine:[1.19,2
.0).
      > Failed to list versions for com.google.api-client:google-api-client-appe
ngine.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/g
oogle/api-client/google-api-client-appengine/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/google/api-client/
google-api-client-appengine/maven-metadata.xml'.
               > jcenter.bintray.com
> Could not resolve com.google.http-client:google-http-client:[1.19.0,2.0).
  Required by:
      project : > com.google.appengine.tools:appengine-gcs-client:0.7
   > Skipped due to earlier error
> Could not resolve com.google.http-client:google-http-client-jackson2:[1.19,2.0
).
  Required by:
      project : > com.google.appengine.tools:appengine-gcs-client:0.7
   > Skipped due to earlier error
> Could not resolve com.google.oauth-client:google-oauth-client:1.22.0.
  Required by:
      project : > com.google.appengine.tools:appengine-gcs-client:0.7 > com.goog
le.apis:google-api-services-storage:v1-rev108-1.22.0 > com.google.api-client:goo
gle-api-client:1.22.0
   > Skipped due to earlier error
> Could not resolve com.google.http-client:google-http-client-jackson2:1.22.0.
  Required by:
      project : > com.google.appengine.tools:appengine-gcs-client:0.7 > com.goog
le.apis:google-api-services-storage:v1-rev108-1.22.0 > com.google.api-client:goo
gle-api-client:1.22.0
   > Skipped due to earlier error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 14s
1 actionable task: 1 executed
`

**Comment by whipermr5** [comment]
https://docs.gradle.org/current/userguide/build_environment.html#sec:accessing_the_web_via_a_proxy

**Comment by gaurab4163** [comment]
Note: Not sure if I should open a different issue for this.

I did that
 `systemProp.http.proxyHost=172.30.0.12
systemProp.http.proxyPort=3128
systemProp.http.nonProxyHosts=*.nonproxyrepos.com|localhost


systemProp.https.proxyHost=172.30.0.12
systemProp.https.proxyPort=3128
systemProp.https.nonProxyHosts=*.nonproxyrepos.com|localhost`

but I am not sure if that is what made it work, since I tried a lot of different things to RUN it(eg: killing the process using 8080 port, used eclipse ide, etc.). It worked fine so many times until I restarted my computer. After restart, I get this message
in CMD
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':appengineStart'.
> com.google.cloud.tools.appengine.cloudsdk.internal.process.ProcessRunnerExcept
ion: Timed out waiting for the success message: '.*(Dev App Server is now runnin
g|INFO:oejs\.Server:main: Started).*'

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to
get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s
5 actionable tasks: 1 executed, 4 up-to-date`


In ECLIPSE
`Could not resolve artifact com.google.appengine:appengine-api-1.0-sdk:jar:1.9.59
Could not transfer artifact com.google.appengine:appengine-api-1.0-sdk:jar:1.9.59 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org`

so with little experience I had gained, i deleted the "repository" folder in "C:\Users\gaurab\.m2" folder. And I couldn't get it to run behind university's proxy until I connected to mobile's hotspot. The dev server started running but still repository folder wasn't created until I started eclipse, which updated Maven dependencies and only then, repository folder was created.

Now is there any way to download that folder behind a university's proxy without use of phone's hotspot?

**Comment by whipermr5** [comment]
> I did that
> `systemProp.http.proxyHost=172.30.0.12
> systemProp.http.proxyPort=3128
> systemProp.http.nonProxyHosts=*.nonproxyrepos.com|localhost
> 
> systemProp.https.proxyHost=172.30.0.12
> systemProp.https.proxyPort=3128
> systemProp.https.nonProxyHosts=*.nonproxyrepos.com|localhost`

In which file did you add these lines?

**Comment by gaurab4163** [comment]
in `gradle.properties` file in located in cloned teammates folder.

C:\Users\gaurab\Desktop\teammate\teammates\gradle.properties

isn't that where it's supposed to be written?

**Comment by gaurab4163** [comment]
Ok, this is driving me insane but I somehow got it to work and it works **sometimes**

Despite behind a university proxy, I completely deleted the proxy entries in `gradle.properties` file and disabled the proxy in internet connection from control panel. That somehow made it work!!

Stopped and re-started dev server multiple times and it worked every single time... until I restarted my computer.

Tried to re-run the dev server and didn't work for 7-8 times straight but worked for the 9th time **MAGICALLY**, even though I **didn't change anything**

Below are the log messages.. Please comment if you can spot some difference and find out exactly how it worked. Otherwise you can close this issue. I would just bang my head against the wall everytime until it magically works :(

**Log message for first 7-8 times(when it didn't work)**


`> Task :appengineStart
Putting task artifact state for task ':appengineStart' into context took 0.0 sec
s.
Up-to-date check for task ':appengineStart' took 0.008 secs. It is not up-to-dat
e because:
  Output property 'devAppServerLoggingDir' file C:\Users\gaurab\Desktop\teammate
\teammates\build\dev-appserver-out\dev_appserver.out has changed.
submitting command: C:\Program Files\Java\jdk1.8.0_151\jre\bin\java.exe -Xss2m -
Dfile.encoding=UTF-8 -Ddatastore.backing_store=appengine-generated/local_db.bin
-Dblobstore.backing_store=appengine-generated -Duse_jetty9_runtime=true -D--enab
le_all_permissions=true -Dappengine.sdk.root=C:\Users\gaurab\Downloads\google cl
oud sdk\google-cloud-sdk\platform\google_appengine\google\appengine\tools\java -
cp C:\Users\gaurab\Downloads\google cloud sdk\google-cloud-sdk\platform\google_a
ppengine\google\appengine\tools\java\lib\appengine-tools-api.jar com.google.appe
ngine.tools.development.DevAppServerMain --port=8080 --allow_remote_shutdown --d
isable_update_check --no_java_agent C:\Users\gaurab\Desktop\teammate\teammates\b
uild\exploded-teammates

2017-12-28 18:20:00.131:INFO:oejs.Server:main: jetty-9.3.18.v20170406
:appengineStart (Thread[Task worker for ':' Thread 2,5,main]) completed. Took 20
.132 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':appengineStart'.
> com.google.cloud.tools.appengine.cloudsdk.internal.process.ProcessRunnerExcept
ion: Timed out waiting for the success message: '.*(Dev App Server is now runnin
g|INFO:oejs\.Server:main: Started).*'

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to
get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
5 actionable tasks: 1 executed, 4 up-to-date`


**Log message when it worked without changing anything**


`> Task :appengineStart
Putting task artifact state for task ':appengineStart' into context took 0.0 sec
s.
Up-to-date check for task ':appengineStart' took 0.005 secs. It is not up-to-dat
e because:
  Task has failed previously.
submitting command: C:\Program Files\Java\jdk1.8.0_151\jre\bin\java.exe -Xss2m -
Dfile.encoding=UTF-8 -Ddatastore.backing_store=appengine-generated/local_db.bin
-Dblobstore.backing_store=appengine-generated -Duse_jetty9_runtime=true -D--enab
le_all_permissions=true -Dappengine.sdk.root=C:\Users\gaurab\Downloads\google cl
oud sdk\google-cloud-sdk\platform\google_appengine\google\appengine\tools\java -
cp C:\Users\gaurab\Downloads\google cloud sdk\google-cloud-sdk\platform\google_a
ppengine\google\appengine\tools\java\lib\appengine-tools-api.jar com.google.appe
ngine.tools.development.DevAppServerMain --port=8080 --allow_remote_shutdown --d
isable_update_check --no_java_agent C:\Users\gaurab\Desktop\teammate\teammates\b
uild\exploded-teammates

2017-12-28 20:32:01.640:INFO:oejs.Server:main: jetty-9.3.18.v20170406
2017-12-28 20:32:11.678:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed
 time=9418ms
2017-12-28 20:32:12.506:INFO:oejsh.ContextHandler:main: Started c.g.a.t.d.j.DevA
ppEngineWebAppContext@82ea68c{/,file:///C:/Users/gaurab/Desktop/teammate/teammat
es/build/exploded-teammates/,AVAILABLE}{C:\Users\gaurab\Desktop\teammate\teammat
es\build\exploded-teammates}
2017-12-28 20:32:12.522:INFO:oejs.AbstractConnector:main: Started NetworkTraffic
SelectChannelConnector@babafc2{HTTP/1.1,[http/1.1]}{localhost:8080}
2017-12-28 20:32:12.522:INFO:oejs.Server:main: Started @13829ms

> Task :appengineStart
Dev App Server output written to : C:\Users\gaurab\Desktop\teammate\teammates\bu
ild\dev-appserver-out\dev_appserver.out

:appengineStart (Thread[Task worker for ':',5,main]) completed. Took 14.181 secs
.

BUILD SUCCESSFUL in 27s
Dec 28, 2017 3:02:12 PM com.google.appengine.tools.development.AbstractModule st
artup
INFO: Module instance default is running at http://localhost:8080/
5 actionable tasks: 1 executed, 4 up-to-date
Dec 28, 2017 3:02:12 PM com.google.appengine.tools.development.AbstractModule st
artup
INFO: The admin console is running at http://localhost:8080/_ah/admin
Dec 28, 2017 8:32:12 PM com.google.appengine.tools.development.DevAppServerImpl
doStart
INFO: Dev App Server is now running`

**Comment by wkurniawan07** [comment]
@gaurab4163 I'm not addressing the root cause but can you check if adding this line [here](https://github.com/TEAMMATES/teammates/blob/master/build.gradle#L278) helps:
```patch
        port = 8080
+       startSuccessTimeout = 40
        jvmFlags = ["-Xss2m", "-Dfile.encoding=UTF-8",
```
