### ISSUE TITLE
New contributor self intro Chng Zhi Xuan

### ISSUE THREAD

**Issue by Chng-Zhi-Xuan** [TEAMMATES/teammates#8264]
- [link to my fork](https://github.com/Chng-Zhi-Xuan/teammates)

**Screenshot of UI Change**

![teammates ui change](https://user-images.githubusercontent.com/31084833/34376560-4bbb6600-eb27-11e7-84cb-dec09b3d813d.PNG)

I changed the green accents on the site to be more consistent with the 2 major color accents that TEAMMATES like to use (blue / light orange). I also modified the login buttons to darken upon hovering over them to make the buttons feel responsive.

**Self Introduction**

Hi, I'm Chng Zhi Xuan, currently a Y2 undergrad in NUS computer science. Would like to take a step up from CS2103 10K LoC project to something more substantial and gain invaluable experience that can be applied to on-going OSS in the real world. Currently interested in cryptography projects like GNU, looking forward to contribute to TEAMMATES!

**Comment by sukanta-27** [comment]
Hi @Chng-Zhi-Xuan 

Welcome to TEAMMATES! You may wish to start by taking on one of our `d.FirstTimers` issues, before moving on to `d.Contributors` issues :)
