### ISSUE TITLE
Java: Use streams to improve code readability in teammates.common.datatransfer.questions.*

### ISSUE THREAD

**Issue by ongks** [TEAMMATES/teammates#8266]
As described in issue #7838, there are many methods in most classes under ./src/main/java/teammates/common/datatransfer/questions/ which also use loops. I would like to propose to simplify them to use Java 8 streams.

I read through the past comments on the issue and agree that it would indeed be beneficial for future developers in that they improve code readability. 

I would like to seek approval before starting work. @damithc @thenaesh @LiHaoTan

**Comment by damithc** [comment]
@ongks Perhaps give some examples?

**Comment by wkurniawan07** [comment]
Given that the move to Java 8 is very recent, there's definitely a lot of Java 8 features that can be freshly utilised in order to improve readability or even performance. Streams, functional interfaces, default/static methods in interface, `Optional`s, Date/Time API are just some examples on top of the issues I have opened. And it's not just in that particular folder; it's everywhere across the code base.

**Comment by ongks** [comment]
Having read up on Java 8 streams, I would like to make reference to [FeedbackRubricQuestionDetails.java](https://github.com/TEAMMATES/teammates/blob/master/src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java). Specifically, methods [isValidDescriptionSize](https://github.com/TEAMMATES/teammates/blob/ec17959c24a78942ff97584819b9285e2fcb1342/src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java#L187) & [getRubricChoices](https://github.com/TEAMMATES/teammates/blob/ec17959c24a78942ff97584819b9285e2fcb1342/src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java#L137) can be refactored to use streams.

As an example of for loops which perform boolean checks iteratively, the isValidDescriptionSize can be refactored from
```
private static boolean isValidDescriptionSize() {
  if (rubricDescriptions.size() != numOfRubricSubQuestions) {
    return false;
  }
  for (int i = 0; i < rubricDescriptions.size(); i++) {
    if (rubricDescriptions.get(i).size() != numOfRubricChoices) {
       return false;
    }
  }
  return true;
}
```
to
```
private static boolean isValidDescriptionSize() {
  if (rubricDescriptions.size() != numOfRubricSubQuestions) {
    return false;
  }
  return IntStream.range(0, rubricDescriptions.size())
                .anyMatch(i -> rubricDescriptions.get(i).size() != numOfRubricChoices);
}
```

<br />

Another example is constructing a new list using streams, as seen in the getRubricChoices method from
```
private static List<String> getRubricChoices(Map<String, String[]> requestParameters, int numOfRubricChoices) {
  List<String> rubricChoices = new ArrayList<>();
  for (int i = 0; i < numOfRubricChoices; i++) {
    String choice = HttpRequestHelper.getValueFromParamMap(requestParameters,
                       Const.ParamsNames.FEEDBACK_QUESTION_RUBRIC_CHOICE + "-" + i);
    if (choice != null) {
       rubricChoices.add(choice);
    }
  }
  return rubricChoices;
}
```
to
```
private static List<String> getRubricChoices(Map<String, String[]> requestParameters, int numOfRubricChoices) {
  return IntStream.range(0, numOfRubricChoices)
                .mapToObj(i -> HttpRequestHelper.getValueFromParamMap(requestParameters,
                        Const.ParamsNames.FEEDBACK_QUESTION_RUBRIC_CHOICE + "-" + i))
                .filter(s -> s != null)
                .collect(Collectors.toList());
}
```

**Comment by gaurav122197** [comment]
There are various code instances such as [InstructorCourseEnrollPageDataGenerator.java](https://github.com/TEAMMATES/teammates/blob/master/src/client/java/teammates/client/scripts/scalabilitytests/InstructorCourseEnrollPageDataGenerator.java) which can be refactored using streams.
Would like to work on this issue to improve code readability for the future contributors after getting affirmation from @wkurniawan07 @damithc @ongks.

**Comment by tong72** [comment]
@damithc @wkurniawan07 I was wondering if this issue is still up for grabs. Thanks.

**Comment by wkurniawan07** [comment]
Closing as most of the code being discussed have been removed.
