### ISSUE TITLE
New contributor self intro - Gaurab Manandhar

### ISSUE THREAD

**Issue by gaurab4163** [TEAMMATES/teammates#8268]
**Link to my app**  :  https://teammates-gaurab.appspot.com/
**Link to my fork**  :  https://github.com/gaurab4163/teammates

**Change done**  : Added bullet interface in "Contacts" page to distinguish various contact points more easily

Before:

![before](https://user-images.githubusercontent.com/15228997/34420633-adf68c0a-ec30-11e7-88fe-8c115d65dbfd.jpg)

After:

![after](https://user-images.githubusercontent.com/15228997/34420642-b8c90176-ec30-11e7-9fbf-9f8417ab616b.jpg)

Self Intro: I am Gaurab Manandhar, currently studying Computer Science in year 3 at NIT Warangal, India, although I am originally from Nepal. I have spent past 3 days in only setting up the project, faced numerous difficulties(eg: working behind university's proxy) as I have never done something like this before. So, when it finally worked, the feeling is just inexplicable. Hoping to contribute more with same zeal in future. Peace!

**Comment by damithc** [comment]
Welcome to TEAMMATES @gaurab4163  :smile:
Good job setting up. :+1:
We look forward to your PRs to come. We recommend you start with a `d.FirstTimer` issue or a `d.Contributors` issue.
