### ISSUE TITLE
New contributor self intro - Tan Te Juin Lester

### ISSUE THREAD

**Issue by lestertj** [TEAMMATES/teammates#8272]
- **Link to my app:** https://teammates-lester.appspot.com
- **Link to my fork:** https://github.com/lestertj/teammates

- **Change done:** Added links to external parties in acknowledgements

**Screenshot of changes made (as seen on the UI)**
<img width="1212" alt="screen shot 2017-12-31 at 3 24 53 pm" src="https://user-images.githubusercontent.com/20982701/34460077-e49605c8-ee3e-11e7-9008-8a2fa9d2f221.png">

**Short self-introduction**
Lester here, 3rd year CS student in NUS. I'll be taking CS3281/3282 this coming semester. I look forward to contributing to TEAMMATES :)

**Comment by damithc** [comment]
Welcome to TEAMMATES @lestertj  :smile:
Good job setting up. :+1:
We look forward to your PRs to come. We recommend you start with a `d.FirstTimer` issue or a `d.Contributors` issue.
