### ISSUE TITLE
Java: Use Java 8 Lambda expressions to replace instances of iterators.

### ISSUE THREAD

**Issue by Chng-Zhi-Xuan** [TEAMMATES/teammates#8273]
**Description of feature/enhancement**

We can remove any usage of iterators in the project code by taking advantage Java 8 new methods that were added to iterable interface. Notably `forEach` and `removeIf` are used in my proposed enhancement.

**Justification**

__Benefit to developers__
1. Removing dependencies on the iterator library. (one less import statement)
2. Taking advantage of Java 8 libraries for more readable and shorter code.

**Example of one change below:**

BEFORE
```
Iterator<String> itr = strList.iterator();
while (itr.hasNext()) {
    santizedStrList.add(sanitizeForCsv(itr.next()));
}
```

AFTER

```
strList.forEach(string -> sanitizedStrList.add(sanitizeForCsv(string)));
```

I found several instances and have refactored accordingly. I would like to ask If I may go ahead and submit a PR for this issue (Have passed all CI tests locally). Thank you!

**Comment by damithc** [comment]
> I would like to ask If I may go ahead and submit a PR for this issue (Have passed all CI tests locally). 

Go ahead @Chng-Zhi-Xuan

**Comment by wkurniawan07** [comment]
- `removeIf` was supposedly worked on in #8214, maybe that is just a missed instance.
- `forEach` for maps has been worked on in #8223, but this one has quite a large number of instances so it is possible that the PR deliberately did not fix everything to be fixed.
- `forEach` for lists, on the other hand, has no significant advantage over `for (... : ...)` so don't put too much efforts on this.

**Comment by ss3681755** [comment]
Can I work on this issue?

**Comment by whipermr5** [comment]
Effort tracker, to be updated as each PR is merged:

| PR | Effort |
| - | - |
| #8274 | 1 |

**Comment by manic-coder** [comment]
Can I work on this issue? It's unclear what remains to be done. I'm a first-timer, so please guide me.

**Comment by LiHaoTan** [comment]
@manic-coder You should try looking for iterators that can benefit from the replacement with aggregate operations (e.g. `forEach` and `filter`).

**Comment by wkurniawan07** [comment]
Actually, this issue very specifically targets at `java.util.Iterator`, all of which have been replaced in #8274, so this issue should not be open any more.
Changing for-loops to streams whenever there is non-trivial benefit (i.e. not just for the sake of using `.forEach`) is very much welcome, but it is another issue altogether.

**Comment by kavya1990** [comment]
Hi,
will share few useful information on [lambda expression in java](http://beyondcorner.com/java-8-lambda-expression-features-tutorial-examples/)
use cases of java 8 on iterators
1. Java 8 lambda expression are mainly used to execute a block of code later, once or multiple times.

2. In Boolean expressions we can use lambda expression.

Example: (List list) -> list.isEmpty()

3. Using lambda expression we can Create a new objects.

Example: () -> new pet(“dog”, 13)

4. we can also used as consuming from an object.

Example: (Pet p) -> { System.out.println(p.getAgeMonths()); }

5. A lambda expression used to Select or extract from an object.

Example: (String s) -> s.length()

6. It produce a single value by performing computation on two values.

Example: (int a, int b) -> a * b

7. we can Compare two objects using lambda expression.

Example: (Pet  p1, Pet p2) -> p1.getAgeMonths().compareTo(p2.getAgeMonths())
