### ISSUE TITLE
Add test for checkIfEmptyRow method in StringHelper.java

### ISSUE THREAD

**Issue by thenaesh** [TEAMMATES/teammates#8279]
**Description of feature/enhancement**

There is currently no test for `checkIfEmptyRow` in StringHelper.java, and the tests pass even with a wrong implementation.

**Justification**

Catches bugs when refactoring that section, as well as reviewer lapses (demonstrated in #8258).

**Comment by asinghal084** [comment]
Hi! I would like to work on this problem if it's open!

**Comment by pierreSquared** [comment]
I would like to work on this issue.
