### ISSUE TITLE
New contributor self intro Shubham Singh

### ISSUE THREAD

**Issue by ss3681755** [TEAMMATES/teammates#8282]
**Link to my app:** http://teammates-singh.appspot.com
**Link to my fork:** https://github.com/ss3681755/teammates
**Change done:** Increased the gap between feature divs on homepage.

**BEFORE**

![screenshot from 2018-01-04 16-43-52](https://user-images.githubusercontent.com/19855394/34562015-67d7464c-f144-11e7-8531-6a9788219625.png)

**AFTER**

![screenshot from 2018-01-04 16-44-30](https://user-images.githubusercontent.com/19855394/34562045-8d7e3e50-f144-11e7-9eda-30c537fe127c.png)

I am pursuing my B.Tech in Computer Science from National Institute of Technology, Uttarakhand(India). I am a GSOC-2018 aspirant and willing to contribute to teammates :)

**Comment by xpdavid** [comment]
Hi @ss3681755, thank you for joining us and see you around :P

You can start your first PR by solving the [`d.FirstTimers`](https://github.com/TEAMMATES/teammates/issues?q=is%3Aissue+is%3Aopen+label%3Ad.FirstTimers) issue :)
