### ISSUE TITLE
Help Request: 5 Failing tests

### ISSUE THREAD

**Issue by nidhi98gupta** [TEAMMATES/teammates#8283]
- Operating System: Ubuntu 17.10
- JDK Version: 1.8
- IntelliJ Version 2017.3
- Firefox Version: 46.0

**What I was trying to do / What I need help with**
I have installed old version of firefox beside the latest version using below guide.
[https://askubuntu.com/questions/770740/how-to-install-an-old-version-of-firefox-side-by-side-to-default-version-without](url).
I changed the default browser of intelliJ so that it uses old version.
[https://www.jetbrains.com/help/idea/web-browsers.html](url)

I am stuck at phase B, step 3 (TESTING).
App gets locally hosted in old version, but when tests are running, latest version of blank firefox instances open up.
Following are the tests that are failing:
![ci-tests](https://user-images.githubusercontent.com/24381442/34565167-c1a8884e-f17f-11e7-95a5-d1c0eb669891.png)
![local-tests](https://user-images.githubusercontent.com/24381442/34565187-cf9cc730-f17f-11e7-9fa8-640837a71199.png)

CI Tests
sequential-ui-tests [https://pastebin.com/A685rRR2](url)
occassional-ui-tests 
parallel-ui-tests
Local Tests
baseClassSetup [https://pastebin.com/6vpvTVQK](url)

**Attempts to resolve the problem**
All have the common Exception: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms.
Browser version is 46.0 as required and states in troubleshooting guide.
I also searched online and found that it is a selenium driver problem. Some suggested to update browser.
Please guide me.
Thanks

**Comment by LiHaoTan** [comment]
@nidhi98gupta There are many reasons this could be so, did you continue to re-run the failing tests?

**Comment by wkurniawan07** [comment]
@nidhi98gupta have you tried updating the Firefox path in `test.properties` file?

**Comment by nidhi98gupta** [comment]
@wkurniawan07 @LiHaoTan Updating the firefox path in `test.properties` file solved the problem. Thanks a lot!
