### ISSUE TITLE
New contributor self intro Nidhi Gupta

### ISSUE THREAD

**Issue by nidhi98gupta** [TEAMMATES/teammates#8284]
Deployed App:  [https://teammates-nidhi.appspot.com](url)
Fork:  [https://github.com/nidhi98gupta/teammates](url)

**Added the bullet points to Terms of Use Page.**
Before:
![old](https://user-images.githubusercontent.com/24381442/34638118-51a90d62-f2eb-11e7-8cda-cfba85e649d8.png)
After:
![new](https://user-images.githubusercontent.com/24381442/34638122-673515a4-f2eb-11e7-9613-7f158754e19d.png)

Hi, My name is Nidhi Gupta. I am pursuing my BTech in Computer Science from DA-IICT. India. Looking forward to contribute and learn from this project. :)

**Comment by sukanta-27** [comment]
Hi @nidhi98gupta 

Welcome to TEAMMATES. You may wish to start by taking on one of our `d.FirstTimers` issues, before moving on to `d.Contributors` issues :)

**Comment by nidhi98gupta** [comment]
@damithc I am aiming to be part of GSoC '18 with TEAMMATES. 
I have a question regarding the Project : Recycle Bin. 
Will using filter() on entity reads be reasonable in terms of billing costs? I mean is database reads more preferable than database writes?

**Comment by damithc** [comment]
> Will using filter() on entity reads be reasonable in terms of billing costs? I mean is database reads more preferable than database writes?

@nidhi98gupta just now I downgraded the priority of that project idea. Reason: While the feature is needed very much, it requires some research to be done first. For GSoC, we'd rather give a higher priority to projects that don't need that much research.
