### ISSUE TITLE
Need Help: Shortage of d.firstTimers

### ISSUE THREAD

**Issue by nidhi98gupta** [TEAMMATES/teammates#8285]
I need direction on how can I contribute.

I was looking for a d.FirstTimers coding bug to work on. There are 11 open issues, in which one is docs enhancement and all of the others have a contributor working on it.

I am not sure where to start from. Can you give me some directions on how to start contributing or what I can do meanwhile. Should I just go through the codebase and familiarize myself with the project more, and try to find a issue myself? Any help will be appreciated.

**Comment by LiHaoTan** [comment]
@nidhi98gupta You can start with a `d.Contributors` as well :).

**Comment by wkurniawan07** [comment]
@nidhi98gupta there are at least 2 free `d.FirstTimers` issues right now. You're welcome to start with `d.Contributors` as well, or any issue, really. Just be warned that the labels are there/not there for good reasons.
