### ISSUE TITLE
New contributor self intro [Niharika Shrivastava]

### ISSUE THREAD

**Issue by OrionStar25** [TEAMMATES/teammates#8286]
a) Link to fork : https://github.com/OrionStar25/teammates/tree/tinker
b) A screenshot of the change I did (as seen on the UI) : 
       Added a 'Back To Top' button for the homepage on the bottom right corner
![screenshot from 2018-01-06 20-24-25](https://user-images.githubusercontent.com/28835849/34640812-c7e50bd8-f2f1-11e7-819c-e2505b95ba2d.png)

c) Intro : Hello, I'm Niharika Shrivastava and I'm studying IT in Indian Institute of Information Technology, Allahabad. I have experience in many coding languages and look forward to better my code writing quality, learn new technologies and finish work within deadlines by contributing more in open source projects.

**Comment by amarlearning** [comment]
Hi @OrionStar25  welcome to TEAMMATES! You can start by fixing a [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue, then those labeled [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.Contributors).
