### ISSUE TITLE
Update user map for Dec 2017

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8292]
Similar to #7424 

Date: End of Dec 2017

Entries to consider adding

Australia | University of New South Wales
-- | --
Belgium | Erasmushogeschool Brussel
Belgium | Hasselt University
Belgium | Howest
Belgium | UNamur
Belgium | Universiteit Antwerpen
Belgium | Universiteit Antwerpen
Brazil | Federal University of Bahia
Canada | Canadian Urban Transit Research and Innovation Consortium
Canada | Carleton University
Canada | McGill University
Canada | New York Institute of Technology
Canada | New York Institute of Technology
Canada | Queen's University
Canada | Sir William Gage Middle School
Canada | University of Lethbridge
Canada | University of Toronto Mississauga
Canada | University of Waterloo
Canada | University of Windsor
Colombia | Cooperative University of Colombia
France | EM Lyon
France | Grenoble Ecole de Management
France | IESEG
France | IESEG
France | sup'biotech
France | EM Lyon
Greece | University of Applied Sciences of Thessaly
India | National Institute of Technology, Uttarakhand
Indonesia | Institut Teknologi Bandung
Indonesia | Universitas Padjadjaran
Ireland | University college dublin
Ireland | University College of Dublin
Italy | Bocconi University
Korea | Solbridge International School of Business
Malaysia | International IslamIc University Malaysia
Malaysia | Universiti Teknologi Petronas
Netherlands | Eindhoven University of Technology
Netherlands | Fontys
Netherlands | Juridische Hogeschool Avans&Fontys
Netherlands | NHTV
Netherlands | Vrije Universiteit Amsterdam
New Zealand | University of Auckland
Philippines | University of St. La Salle
Portugal | School of Education Porto (ESE)
Singapore | Nanyang Technological University
Singapore | Singapore Institute of Technology
Spain | University of Deusto
UK | Bradford
UK | University of Arkansas at Little Rock
UK | University of Bath
UK | University of Portsmouth
USA | Arizona State University
USA | Austin Community College
USA | Baylor University
USA | Bridgewater State University
USA | Cabrini University
USA | California State University San Marcos
USA | Central Oregon Community College
USA | Davenport University
USA | Drexel University
USA | Florida International University
USA | Florida State University
USA | Georgetown University
USA | Golf Platoon
USA | Granada Middle School
USA | Harvard Extension School
USA | Las Positas College
USA | Lebanon Valley College
USA | Montana State University
USA | Navasota High School
USA | North Carolina A&T State University
USA | Northeastern University
USA | Northeastern University
USA | Providence College
USA | Riverview Opportunity Center
USA | Siena College
USA | The New School
USA | University at Albany
USA | University at Buffalo
USA | University of Alabama at Birmingham
USA | University of Bridgeport
USA | University of California Santa Barbara
USA | University of Colorado, Boulder
USA | University of Delaware
USA | University of Florida
USA | University of Illinois
USA | University of Iowa
USA | University of Minnesota - Carlson
USA | University of North Carolina
USA | University of North Carolina Greensboro
USA | University of Northern Arizona
USA | University of Virginia
USA | University of Washington
USA | University of Washington
USA | Virginia Tech
USA | Walnut Hills High School
USA | Washington State University
USA | Weber State University
USA | West Chester University
USA | William Woods Univeristy
USA | Xavier University

**Comment by nbyer** [comment]
Hi, I'm a recent CS grad looking to get involved. Would I be able to take care of this? It would be my first contribution.

**Comment by priyanshugandhi** [comment]
Hello, I am Priyanshu Gandhi and I'm studying CS in RGPV University. I am a GSOC-2018 aspirant and willing to contribute to teammates. I would like to work on this issue.

**Comment by jimmyshephard** [comment]
Sure about the University of Arkansas at Little Rock in UK?

**Comment by bira91** [comment]
Can i work on this issue for my first time issue?

**Comment by whipermr5** [comment]
@jimmyshephard Thanks; I did add a comment about it in #8295.

@bira91 @dishant-sheth is already working on it, though you can if you really want to (we'll merge the first PR to reach acceptable quality).
