### ISSUE TITLE
Error while executing task findbugsMain

### ISSUE THREAD

**Issue by huai99** [TEAMMATES/teammates#8294]
**Issue Title:** [Error while executing gradle task findbugsMain]

```
When I run './gradlew build', it was executing fine until it reaches the task findbugsMain 
and it fails. The error that shown is as below:
```
![teammates issue](https://user-images.githubusercontent.com/26456025/34781043-c8bcc142-f65f-11e7-875b-1d8b6f9b5e32.png)

Any help or suggestions will be appreciated !

**Comment by wkurniawan07** [comment]
I have never seen that exception occurring before so I cannot pinpoint the exact cause. While running the `./gradlew build` command, does `compileJava` and `checkstyleMain` run and succeed?

Anyway, what are you running `./gradlew build` for?

**Comment by huai99** [comment]
Actually I notice the error while  I am running ```./gradlew lint ```, ```findbugsMain``` and ```findbugsTest``` failed together, I believe I am running in the same environment as everyone else, I am using JDK1.8, is there any specific configuration that I could provide that you might think will be helpful?

**Comment by wkurniawan07** [comment]
Does `checkstyleMain` and/or `checkstyleTest` fail? The exception certainly looks interesting and should not happen.

**Comment by huai99** [comment]
No, both of them pass and the only thing fails is these two tasks, I have tried to remove the whole project and re-setup, but the problem persist. I am using Ubuntu, wondering if anyone using the same OS faces this problem.

**Comment by huai99** [comment]
This turns out to be a careless mistake of mine, I have configure the my IDE to use JDK 1.8, but the gradle task is using JDK 1.9 from my OS PATH variable, and the class in the production source are in JDK 1.8 so I guess that is why the error ```No classes found to analyze``` is happening.

I have solved it by changing the Java home directory in ```gradle.properties``` to JDK 1.8. Sorry for the careless mistakes.
