### ISSUE TITLE
Replace all instances of `Const#EOL` with `System#lineSeparator()`

### ISSUE THREAD

**Issue by LiHaoTan** [TEAMMATES/teammates#8299]
It is preferable not to use a constant for a line separator and the standard library offers a much better alternative.

**Comment by ManognaMutyala** [comment]
I am new to open source contribution and I would like to work on this.Could you please help me with the specific modules to look for the above issue?

**Comment by LiHaoTan** [comment]
@ManognaMutyala You need to replace all instances and a simple search and replace should suffice.

**Comment by xpdavid** [comment]
@LiHaoTan I think we have it in `Const.java`.

```java
public static final String EOL = System.getProperty("line.separator");
```

**Comment by LiHaoTan** [comment]
@xpdavid yeah, just that it technically does almost the same thing as `System#lineSeparator()`.

**Comment by wkurniawan07** [comment]
`System.lineSeparator()` is a Java 7 technique. Given that TEAMMATES started just slightly before Java 7 went GA, using `Const` may be a legacy reason. Using `System.lineSeparator()` directly is justified here.

**Comment by Shashwat-Garg** [comment]
Is anyone assigned to this issue?

**Comment by xpdavid** [comment]
@Shashwat-Garg There is a PR for this issue https://github.com/TEAMMATES/teammates/pull/8337. You can find other issues to work on.

**Comment by man-of-code** [comment]
Is this issue closed ?

**Comment by shivanshsoni** [comment]
I am a first-timer. Can I work on this issue??

**Comment by LiHaoTan** [comment]
@shivanshsoni Sure, go ahead!
