### ISSUE TITLE
static-analysis.md: update instructions on running PMD in Eclipse

### ISSUE THREAD

**Issue by shivamtrip53** [TEAMMATES/teammates#8306]
- **Operating System**: ubuntu 16.04 LTS 64 bit
- **JDK Version**: openJDK 1.8.0_151
- **Eclipse Version** : Oxygen (4.7.2)
- **Firefox / Chrome Version**: Not Applicable

**What I was trying to do / What I need help with**
I am  trying to do following
   "To run PMD analysis using the Eclipse PMD plugin, right click on the project under Project Explorer and select PMD > Check Code"
I am not able to find PMD option, though i can find FindBugs and CheckStyle.

![screenshot from 2018-01-13 19-03-11](https://user-images.githubusercontent.com/25117137/34906504-0a968f08-f895-11e7-8282-adc8141ee6ff.png)

I tried to find them by clicking Window -> Show View -> Other . But here too i can only find CheckStyle and FindBugs

![screenshot from 2018-01-13 19-14-06](https://user-images.githubusercontent.com/25117137/34906574-24b6eae4-f896-11e7-961d-697700c96758.png)

**Attempts to resolve the problem**

I made sure that i configured the xml files.
![screenshot from 2018-01-13 19-27-06](https://user-images.githubusercontent.com/25117137/34906669-dddd3e28-f897-11e7-83b1-8e761172442f.png)

**Comment by wkurniawan07** [comment]
Indeed it looks like the option is removed from the new PMD plugin. Thanks for reporting @shivamtrip53! You need not worry because the fact that you have set up this plugin correctly means PMD analysis would have run in your project anyway.

**Comment by junkiattan** [comment]
@whipermr5 I'm new to Teammates and would like to start on this as my first PR! 

Just to check so do I change "To run PMD analysis using the Eclipse PMD plugin, right click on the project under Project Explorer and select PMD > Check Code" to "PMD analysis is automated when Eclipse PMD plugin is installed successfully. Simply review the report in the PMD Perspective view under Violations Overview." or should I change it to something else?

**Comment by whipermr5** [comment]
@junkiattan Sounds good!

**Comment by man-of-code** [comment]
@whipermr5 Is this issue still up for grabs?
If so, I would like to claim this one!

**Comment by junkiattan** [comment]
@man-of-code I am already taking this up! Thank you for asking though;)

**Comment by junkiattan** [comment]
@whipermr5 I have submitted a pull request;)

**Comment by shivamtrip53** [comment]
@junkiattan I am not able to find Violations Overview. Can you show the screenshot displaying Violations Overview or the the position where I am supposed to find it.

**Comment by wkurniawan07** [comment]
@junkiattan, are you sure of the instructions? Violations Overview is a feature of the older PMD plugin, which is the very reason why this issue was raised in the first place.

[The correct way to locate the violations is described in the project homepage](https://acanda.github.io/eclipse-pmd/).

**Comment by junkiattan** [comment]
@wkurniawan07 @shivamtrip53 Ah sincerely sorry. I believe it should be the "Problems View" in Eclipse. I tried taking reference from the original and made a mistake.

"PMD analysis is automated when Eclipse PMD plugin is installed successfully. In addition, any discovered problems would also be logged in the Eclipse Problems View."

Is this new edit good to go? Ill await your approval before I submit a change;)

**Comment by wkurniawan07** [comment]
@junkiattan Some minor suggestions:
PMD analysis is automated when Eclipse PMD plugin is installed successfully. ~~In addition,~~ ~~any~~ **All** discovered problems ~~would also be logged~~ **can be viewed** ~~in~~ **under** the Eclipse Problems View.

Also, Eclipse Problems View groups messages by error level (error/warning/info) so it may not be the best alternative. A better alternative may be Eclipse Markers View, which groups messages by the reporting tool.

**Comment by junkiattan** [comment]
@wkurniawan07 

Consolidating your edits as well as the additional inputs, the finalized suggestion is as follows:

> PMD analysis is automated when Eclipse PMD plugin is installed successfully. All discovered problems can be viewed under the Eclipse Problems View or the Eclipse Markers View.

Is this good to go?

**Comment by wkurniawan07** [comment]
@junkiattan can go ahead.
