### ISSUE TITLE
Help Request: Connection refused on ./gradlew createConfigs

### ISSUE THREAD

**Issue by Anupam-dagar** [TEAMMATES/teammates#8307]
- **Operating System:** Ubuntu Gnome 16.04
- **JDK Version:** 1.8

**What I was trying to do **
I was running ```./gradlew createConfigs``` and got a connection refused error.I use proxy and it is properly setup.
![screenshot from 2018-01-14 14-03-00](https://user-images.githubusercontent.com/21174572/34914203-be0cfd62-f933-11e7-950c-116918140415.png)

**Attempts to resolve the problem**
I tried reapplying my proxy settings.

**Comment by LiHaoTan** [comment]
It appears the most probable cause is that you have not setup your proxy settings correctly. 

Unfortunately, there's no way we can verify that for you as the proxy settings for everyone differs. Have you looked at https://docs.gradle.org/4.4.1/userguide/build_environment.html#sec:accessing_the_web_via_a_proxy?

If you run `./gradlew`, it should fail with the same error so you might want to try accessing Gradle without a proxy (e.g. with cellular data).

**Comment by Anupam-dagar** [comment]
i resolved by using cellular data :)
