### ISSUE TITLE
New contributor self intro Yuki Kuroshima

### ISSUE THREAD

**Issue by YukiKuroshima** [TEAMMATES/teammates#8309]
a) link to your app (if you deployed to your staging server in Phase C)
[https://6-0-0-dot-teammates-yuki.appspot.com/](https://6-0-0-dot-teammates-yuki.appspot.com/)

b) link to your fork
[https://github.com/YukiKuroshima/teammates](https://github.com/YukiKuroshima/teammates)

c) a screenshot of the change you did (as seen on the UI)
## Before
![screen shot 2018-01-14 at 9 29 55 pm](https://user-images.githubusercontent.com/12422309/34929445-c2d88f42-f978-11e7-9e5d-b38377a1de07.png)
## After
<img width="960" alt="screen shot 2018-01-14 at 10 04 36 pm" src="https://user-images.githubusercontent.com/12422309/34929447-c85a8510-f978-11e7-99b8-6a4320182635.png">
Note: Find students button has been centerized.

d) your real name and a short self-intro
Hello, I am Yuki Kuroshima. I am a computer science from San Jose State Unversity in California, United States.
I cannot wait to contribute to this awesome project!

**Comment by whipermr5** [comment]
Hey Yuki, welcome to TEAMMATES! Good job setting everything up correctly! You can get your feet wet by working on a `d.FirstTimers` issue, then move on to `d.Contributors` issues :)

**Comment by YukiKuroshima** [comment]
Thank you!
