### ISSUE TITLE
Enhancement: Improve Email Layout by using buttons for links

### ISSUE THREAD

**Issue by tshradheya** [TEAMMATES/teammates#8312]
**Description of feature/enhancement**

When sending emails to student/instructor, instead of sending the raw link, we could send a button which redirects to the link when the button is clicked.
Something similar to the below: 
---
![image](https://user-images.githubusercontent.com/12574756/35085531-06b5707a-fc64-11e7-8c8b-44ce437fd3f8.png)
---

**Justification**

Through using buttons, we don't explicitly show the link and moreover, it improves the interface of email.

Hoping to get some feedback on this enhancement and would like to take it up if the enhancement is accepted to be implemented by the senior developers

**Comment by damithc** [comment]
I don't mind having something like that if it is not too hard to do.

**Comment by tshradheya** [comment]
Okay. Then I will

**Comment by damithc** [comment]
Closing now. Will reopen later if needed.
