### ISSUE TITLE
JasperException on attempted login - initial setup

### ISSUE THREAD

**Issue by jimmyshephard** [TEAMMATES/teammates#8313]
- **Mac OSX High Sierra**
- **JDK Version: 1.8.0.121**
- **Eclipse: *Neon*
- **Chrome Version:* 63*

**What I was trying to do / What I need help with**
Setting up teammates, I have the server running but I cannot logon because of an exception due to offensive JSTL expression on the UI.

Steps to reproduce:
- Request URL: http://localhost:8080/admin/adminHomePage 
- Console error is shown: **org.apache.jasper.JasperException: /WEB-INF/tags/admin/navBar.tag(21,12) The function getClass must be used with a prefix when a default namespace is not specified**

**Attempts to resolve the problem**
Attempting to see how the expression needs to to be modified to supply a namespace and what that would be,  file WEB-INF/tags/admin/navBar.tag has several of this expression _test="${fn:contains(**data.getClass()**, 'AdminHomePage')}"_
 ,would appreciate some help in figuring what needs to change or what I could have missed on setup

**Comment by LiHaoTan** [comment]
@jimmyshephard I suspect you are not running the app using the Java 8 runtime. If you are migrating, you should refer to #8149.

**Comment by jimmyshephard** [comment]
Thanks @LiHaoTan, that helped me. App was running on Java 7 runtime
