### ISSUE TITLE
New contributor self intro Rajat Dwivedi

### ISSUE THREAD

**Issue by bira91** [TEAMMATES/teammates#8315]
- [**Link to my app**](http://www.teammates-rajatd.appspot.com)
- [**Link to my fork**](https://github.com/TEAMMATES/teammates)

**Screenshot of changes made (as seen on the UI)**
![screen shot 2018-01-20 at 12 21 26 am](https://user-images.githubusercontent.com/29452802/35169640-266ca752-fd55-11e7-8a56-3f550a8fc812.png)

Hi everyone, my name is Rajat Dwivedi. I am an undergrad student of Computer science at the Indian Institute of Information Technology Una (IIITU). I like to learn and work with new web technologies .I have been intrigued by open source software and have tried to make some contributions to some small projects. I look forward to gain more insight into the world of open source by contributing to bigger projects like Teammates.

**Comment by sukanta-27** [comment]
Hi @bira91 

Welcome to TEAMMATES! You may wish to start by taking on one of our `d.FirstTimers` issues, before moving on to `d.Contributors` issues :)
