### ISSUE TITLE
Instructor Help: add missing number in numbered list

### ISSUE THREAD

**Issue by wenmogu** [TEAMMATES/teammates#8317]
There is one pointer in bold that does not have number label in front. This format does not align with other pointers in this section.

![image](https://user-images.githubusercontent.com/28526038/35178812-4fdf995e-fdc9-11e7-9759-3af23d7d5cd9.png)

**Comment by Crphang** [comment]
Can I take up this issue as my first?

**Comment by damithc** [comment]
> Can I take up this issue as my first?

Sure
