### ISSUE TITLE
New Contributor Self-Intro: Phang Chun Rong

### ISSUE THREAD

**Issue by Crphang** [TEAMMATES/teammates#8319]
- **Link to my app: http://6-0-0-dot-teammates-crphang.appspot.com**
- **Link to my fork: https://github.com/Crphang/teammates**

**Screenshot of changes made (as seen on the UI)**

After
![screen shot 2018-01-20 at 10 21 26 am](https://user-images.githubusercontent.com/4986717/35179029-ea40ac6a-fdcc-11e7-9df4-890bac33f43a.png)

Before
![screen shot 2018-01-20 at 10 27 53 am](https://user-images.githubusercontent.com/4986717/35179031-f393abc8-fdcc-11e7-9824-a46c832ce8da.png)

Aligned feedback button to the left to be more consistent with other pages.

**Short self-introduction**
I am Chun Rong, contributing to teammates as part of CS3282 main project

**Comment by whipermr5** [comment]
Hey Chun Rong, welcome to TEAMMATES! Good job setting everything up correctly! You can get your feet wet by working on a `d.FirstTimers` issue, then move on to `d.Contributors` issues :)
