### ISSUE TITLE
Instructor: add ranking question: leave min/max boxes empty by default

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8320]
When an instructor is adding a _ranking_ type question, the min/max boxes are pre-filled with `1`. 
![image](https://user-images.githubusercontent.com/1673303/35179261-b21fcdc0-fdd1-11e7-82bf-5ec780a06e70.png)

Perhaps we should leave the boxes empty to eliminate any room for misinterpretation of the number?

**Comment by Crphang** [comment]
I can work on this.

Should we consider having placeholder text instead of pre-filled numbers like "e.g. 1" within those boxes?

**Comment by damithc** [comment]
It's a number field. I don't think you can set it to a non-number text.

**Comment by bqnguyen94** [comment]
I believe what @Crphang meant was to remove the `value` attribute of `input` tag and add a `placeholder` attribute with "e.g. 1" or something similar.

**Comment by Crphang** [comment]
The placeholder would look like that. The  "e.g." should help remove the ambiguity of the initial number 1.


![screen shot 2018-01-20 at 2 34 36 pm](https://user-images.githubusercontent.com/4986717/35180634-34167726-fdef-11e7-9a6c-231bb9612c14.png)

**Comment by damithc** [comment]
> The placeholder would look like that. The "e.g." should help remove the ambiguity of the initial number 1.

Looks good. Ensure that the code works if a user ticked the option but didn't enter any value, and ensure that that situation is covered in tests. It may have been overlooked earlier because previously the value was pre-filled.

**Comment by dabbler011** [comment]
@Crphang are you still working on this issue or shall I take up this one?

**Comment by Crphang** [comment]
@dabbler011 I'm currently working on it! Thanks for reaching out first!

**Comment by Crphang** [comment]
I hope to clarify the expected user experience. Suppose the user left the field blank, is it better to post-fill the min/max options with 1 (compared to pre-filling like before) within the app logic (`InstructorFeedbackQuestionAddAction`) or will it be neater to prompt the user of the empty field for the user to fill in?

**Comment by damithc** [comment]
How about we leave the field empty by default, but when the user ticks the checkbox, we auto-fill it to `1`? Does that make sense? Notwithstanding, I guess we still have to ensure the field is not empty at the point of submission because the user can delete the value we auto-filled.

**Comment by Crphang** [comment]
I am thinking that that might make the user experience the same as before (with pre-filling 1). But this should be do-able.

On the other hand to ensure the field is not empty, I added a front end validation if the user clicks `save` with the field being empty (Will add browser test for this). This could also reduce the need to pre-fill.

![image](https://user-images.githubusercontent.com/4986717/35480543-36dca7e8-044b-11e8-8d17-312e1a515049.png)

**Comment by damithc** [comment]
> I am thinking that that might make the user experience the same as before (with pre-filling 1). But this should be do-able.

The difference is previously the field is pre-filled but the check box is not selected which is an inconsistent state (although harmless).
