### ISSUE TITLE
Remove Instructor Short Name when adding single instructor by administrator

### ISSUE THREAD

**Issue by Haozhe321** [TEAMMATES/teammates#8321]
**Description of feature/enhancement**
When adding multiple instructors, there is no "Short Name" to be added for the instructors; but when adding single instructors it is compulsory to include Short Name else the instructor can't be added. After adding the instructors, the Short Name displayed at the bottom of the page is the same as the full name. I suggest adding a column to add Short Name for instructors. 

**Justification**

The same benefit for using Short Name when adding a single instructor will apply(for example, instructors will not be referred by their full name in the email sent to them). This also makes the processing of adding new instructors more consistent.

![image](https://user-images.githubusercontent.com/26651556/35179257-90235b42-fdd1-11e7-8401-c65a11322844.png)

**Comment by damithc** [comment]
Actually, we can get rid of the short name altogether. It's used only in the invitation email sent e.g. `hi John`. We can use the full name for that too.

**Comment by Haozhe321** [comment]
Okay I can work on removing that field
