### ISSUE TITLE
Fix AppVeyor failure due to Guava version

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#8324]
Cause of problem: Guava version `23.6-jre` does not play well with AppVeyor environment, as seen from the [latest AppVeyor build](https://ci.appveyor.com/project/damithc/teammates/build/1.0.744).

Solution: downgrade to the latest workable version.

**Comment by whipermr5** [comment]
Perhaps the latest Selenium will work with the latest Guava. #8150
