### ISSUE TITLE
Instructor Help: integrate documentation for contribution questions

### ISSUE THREAD

**Issue by joanneong** [TEAMMATES/teammates#8328]
**Description of feature/enhancement**

In the instructor help page, the faq for contribution questions contain links to an external Google Drive document:

![contribquestion](https://user-images.githubusercontent.com/24493463/35185875-bf6a986c-fe02-11e7-9ded-afba3b13788e.png)
The Google Drive document:
<img width="300" alt="screen shot 2018-01-21 at 12 56 56 am" src="https://user-images.githubusercontent.com/24493463/35185884-fdac541c-fe02-11e7-8b9c-806ad32124ea.png">

I propose merging this scheme into the instructor help page and tidying up the documentation for this section (e.g. with better formatting, better examples etc.).

**Justification**

Such a change will primarily benefit instructors. This is because instructors are more likely to be referring to the faq section.

By making this change:
- the documentation can be accessed from a single source (the instructor help page) without linking to an external page on Google Drive
- the documentation will be less cluttered since the Google Drive document contains many other irrelevant information and is not even up to date with the latest version of teammates
- the documentation can be formatted in a more consistent style (i.e. in line with the rest of instructor help page)

![systemspec](https://user-images.githubusercontent.com/24493463/35186016-43c5efd8-fe05-11e7-8f6b-6b42d443aad2.png)

Such a change will also benefit developers who want to update the documentation for contribution questions since new developers will not have write access to the Google Drive file (?).

**Comment by wkurniawan07** [comment]
@joanneong Using GDrive for documentation has been deprecated for quite some time already. You're definitely welcome to migrate it to proper JSP and check it into the version control of this repo.
However, integrating everything to the instructor help page may not be the best course of action since (1) the instructor help page is already very long and (2) the FAQ is quite technical and may not be interesting for anyone.

**Comment by wkurniawan07** [comment]
> Do you think it is better to have it in a separate page then, just for technical details?

That sounds about right to me.

**Comment by joanneong** [comment]
Got it. I will give it a shot in these few days and see how it turns out.
