### ISSUE TITLE
Code Enhancement: fix unnecessary for-loop

### ISSUE THREAD

**Issue by wenmogu** [TEAMMATES/teammates#8334]
**Description of feature/enhancement**
I notice that at class `FeedbackRankRecipientsQuestionDetails` method `getNormalisedRankForEachResponse`, there is a for-loop looping the parameter `responses` of this method. Practically, this for-loop converts `responses` from a List to a Map, with the same content.
However, this loop is called for every `giver`. E.g. if there are 10 people ranked others in this session, then this conversion of `responses` will be carried out 10 times, which is a waste of resources. 

![image](https://user-images.githubusercontent.com/28526038/35195987-f63a2286-ff06-11e7-8fd3-cf1dde0226e1.png)

**Justification**
I believe one conversion is enough for the use of all `givers`, since the resultant Map is not modified anywhere in the code.

**Comment by damithc** [comment]
@wenmogu  are you working on this? If it is a simple fix, may be update the description to explain your proposed solution and let a new contributor do it?

**Comment by wenmogu** [comment]
Ooooops I thought this issue was already closed along with #8400... yeah I ve already fixed it along with #8400...

**Comment by damithc** [comment]
> Ooooops I thought this issue was already closed along with #...

Got it. If a PR fixes multiple issues, you can indicate that with  something like `Fixes #1234 Fixes #5678`
