### ISSUE TITLE
Help Request: Unable to build the JavaScript files for the application's use

### ISSUE THREAD

**Issue by shivamtrip53** [TEAMMATES/teammates#8341]
- **Operating System:**  ubuntu 16.04 LTS 64 bit
- **JDK Version:** openJDK 1.8.0_151
- **Eclipse Version :**  Oxygen (4.7.2)
- **Firefox / Chrome Version :**  Not Applicable

**What I was trying to do / What I need help with**
I was trying to run following command to build the JavaScript files for the application's use:

            npm run build

The following output was generated.
![screenshot from 2018-01-23 00-43-48](https://user-images.githubusercontent.com/25117137/35239533-c22dfda2-ffd6-11e7-8fdf-a7c24051a8b6.png)

**Attempts to resolve the problem**
Firstly, I  Uninstalled completely nodejs and npm.

sudo apt remove nodejs npm

After that , I reinstalled it by:
for Node.js 9:

curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
sudo apt-get install -y nodejs

Then, again i ran following command:

 npm run build

Following output was generated.
![screenshot from 2018-01-23 00-51-55](https://user-images.githubusercontent.com/25117137/35239865-abb75036-ffd7-11e7-921d-2704befab72b.png)

**Comment by LiHaoTan** [comment]
@shivamtrip53 Have you ran `npm install`?

**Comment by shivamtrip53** [comment]
@LiHaoTan  After running the command you mentioned, I again ran
      npm run build
This time it worked.
Thanx
