### ISSUE TITLE
New Contributor Self-Intro: Ali

### ISSUE THREAD

**Issue by Ali96kz** [TEAMMATES/teammates#8346]
Link to my work: https://github.com/Ali96kz/teammates
![screen](https://user-images.githubusercontent.com/15236829/35290715-37af19a8-0095-11e8-96bb-515ae90bec5d.PNG)
    My fullname is Zhagparov Ali. I am from Kazakhstan. I am educating in final course at university. I want to contribute to teammate because it's beginner friendly and as I see project with good architecture. 
    About my skills. I have one year job experience as Junior Java Developer. I think I well in java core, hibernate, jpql, spring, selenium and junit. 
    At the first time I want to wright an automatated or unit tests.
 Thanks for attention. I hope you will take me to your community.

**Comment by shaharyar-shamshi** [comment]
Welcome to the teammates I would like to to suggest you to go for the issue labelled as d.firsttimer to get your hand wet and then proceed to d.contributor labelled issue
