### ISSUE TITLE
Instructor Add/Edit Feedback Session: Submission opening time earlier than current time

### ISSUE THREAD

**Issue by Haozhe321** [TEAMMATES/teammates#8353]
**Environment**

`master` branch at commit 7d15ccc

**Steps to reproduce**
1. Login as instructor
2. Add a new feedback session
3. Set the "Submission opening time" to be earlier than the current date and time
4. (Optional) Set the "Submission end time" to be earlier than the current date and time too. 

**Expected behaviour**
Warning that session opening time cannot be earlier than current time 

**Actual behaviour**
Feedback session has been added.

**Note**
Although this issue is to report Submission opening time earlier than current time, Submission closing time being earlier than current time could also be an issue. 

![image](https://user-images.githubusercontent.com/26651556/35372676-33ac1828-01d6-11e8-8712-b4881ece2d66.png)

**Comment by damithc** [comment]
This is intended. As there is no open/close function for users to open/end sessions, users are allowed to use any open/end time to control the status of the session. e.g., if the user wants to close a session immediately, he can set the close time to a past time. The only restriction is the end time should be _after_ the open time.

**Comment by Haozhe321** [comment]
@damithc I see. It sounds like a useful thing to have. Should a button be created for instructors to close a session immediately? Because the current way of closing it immediately seems like a hack, and many of them may not know how to use this method of closing sessions. 

Or a note could be added onto the existing one to let them know that they can set the closing time earlier than current time to close a session immediately(with reference to the picture below). This makes the page look messier though.
![image](https://user-images.githubusercontent.com/26651556/35378438-c4d3384c-01ed-11e8-8f56-e2360ac9e612.png)

**Comment by damithc** [comment]
It's not that easy to support a 'open now' features because we can only open a session at the start of the hour (because the required cron jobs only run at the start of the hour). Although the current way is not ideal, I can't think of an easy fix. On the positive side, most users will simply set a start and end time in future and it will work as expected.  The flexibility to set times in the past is just an extra thing that people can use if they need that flexibility.

**Comment by damithc** [comment]
Closing to focus on higher priority issues. Could be reopened later.
