### ISSUE TITLE
Instructor: add rank question: prevent input field from shrinking when enabled

### ISSUE THREAD

**Issue by bqnguyen94** [TEAMMATES/teammates#8355]
**Environment**

`master` branch at commit [`18aefe8`](https://github.com/TEAMMATES/teammates/commit/18aefe85e42847d6bf14d172e70fec43b0a7c0ea)
Browser: Chrome on macOS High Sierra

**Steps to reproduce**
- Login as instructor
- Go to instructor home page, click edit on any feedback session
- Go to bottom of page, click `Add New Question`, choose either `Rank 'options' question` or `Rank 'recipients' question`, tick on either `Minimum number of options a respondent must rank` or `Maximum number of options a respondent can rank`, the corresponding input field will shrink

**Expected behaviour**
The input fields should not shrink when enabled

**Actual behaviour**
The input fields shrink when enabled

**Possible cause**
When the input field is enabled, the `max` attribute is added to it. The field now has both `min` and `max` attributes and the size of the field is then changed to fit the amount of digits specified by `max` (see angular/material#7349).

**Proposed solution**
Set the `step` attribute of input field to `any` so that the input field does not try to fit the maximum length of input.

**Comment by Shashwat-Garg** [comment]
Hello, I would like to work on this issue.

**Comment by reddysridhar53** [comment]
Shall I pick this one?
