### ISSUE TITLE
Instructor session: Disable remind button when submission has closed 

### ISSUE THREAD

**Issue by Haozhe321** [TEAMMATES/teammates#8358]
**Environment**

`master` branch at commit 18aefe8

**Steps to reproduce**
1. Login as instructor. 
2. Create a session/use an existing session, close the session but unpublish the result.

**Expected behaviour**
The remind button should not be clickable since the session is already closed.

**Actual behaviour**
The remind button is clickable because it is currently dependent on whether the results are published. If you publish the result, the remind button becomes unclickable, regardless of whether the session is closed or not. 

![image](https://user-images.githubusercontent.com/26651556/35424102-55be53f2-028c-11e8-8f35-a65b5a6e160c.png)

**Comment by Haozhe321** [comment]
looking into this

**Comment by sukanta-27** [comment]
@Haozhe321 Just a suggestion, Your PR name should be exactly the same as the issue title. You can also change the issue title as the PR name looks more accurate.

**Comment by Haozhe321** [comment]
@sukanta-27 thanks!
