### ISSUE TITLE
Help Request: Build Error / java: reference to until is ambiguous

### ISSUE THREAD

**Issue by nidhi98gupta** [TEAMMATES/teammates#8361]
Operating System: Ubuntu 17.10
 JDK Version: 1.8
 IntelliJ Version 2017.3
 Firefox Version: 46.0

**What I was trying to do / What I need help with**
I was trying to build project and it throwed up error.
`/home/nidhi/teammates/src/test/java/teammates/test/pageobjects/GoogleLoginPage.java
Error:(100, 13) java: reference to until is ambiguous
  both method until(com.google.common.base.Predicate<T>) in org.openqa.selenium.support.ui.FluentWait and method <V>until(com.google.common.base.Function<? super T,V>) in org.openqa.selenium.support.ui.FluentWait match`

It working all fine before installing plugins for checkstyle test in intelliJ. 
Also I didn't make any changes in GoogleLoginPage.java

**Attempts to resolve the problem**
I found this online [https://stackoverflow.com/questions/42421148/wait-untilexpectedconditions-doesnt-work-any-more-in-selenium](url)
I copied the build.gradle from this repository and pasted it in mine, just to be sure of dependencies.
I also did invalidate cache/restart in intelliJ.

**Comment by tshradheya** [comment]
The `until()` function is in[ Line 102](https://github.com/TEAMMATES/teammates/blob/master/src/test/java/teammates/test/pageobjects/GoogleLoginPage.java#L102) however it seems like you are getting the error in Line 100. 
Are you sure you haven't changed anything in `GoogleLoginPage.java`?
Maybe you could pull from the master and check if everything works fine

**Comment by nidhi98gupta** [comment]
@tshradheya Thanks. One of the import statements was missing.
