### ISSUE TITLE
404 The requested resource () is not available

### ISSUE THREAD

**Issue by dynastykaiserlord123** [TEAMMATES/teammates#8363]
I tried running teammates in glassfish with the url http://localhost:8080/teammates/index.jsp but it keeps returning 404. What am I doing wrong here?
![screenshot 17](https://user-images.githubusercontent.com/33665087/35468479-983d2342-02d3-11e8-92a8-6a3d06fdf5f3.png)
![screenshot 18](https://user-images.githubusercontent.com/33665087/35468480-98557582-02d3-11e8-9c98-870ed1c0b592.png)

**Comment by LiHaoTan** [comment]
@dynastykaiserlord123 We don't support Glassfish in TEAMMATES. Please try to take your time looking at our [Contributor Orientation Guide](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md) first :).
