### ISSUE TITLE
Instructor: edit rank questions: make status message span both label and input

### ISSUE THREAD

**Issue by joanneong** [TEAMMATES/teammates#8364]
**Description of feature/enhancement**

As discussed in #7899 , it would be good to make the status message span both label and input for rank questions as well.

Here is what a rank question currently looks like:

<img width="822" alt="screen shot 2018-01-27 at 3 14 44 pm" src="https://user-images.githubusercontent.com/24493463/35469666-d7baf5e8-0374-11e8-8c17-719d242f18dd.png">

**Justification**

This is because a similar UI change has been done for contribution questions (as per #8259 ), so making this change for rank questions as well will provide a more uniform UI for users (both instructors and students).

**Comment by jimmyshephard** [comment]
Would like to work on this.

**Comment by amarlearning** [comment]
I am taking this one :)

**Comment by wkurniawan07** [comment]
@amarlearning, welcome back, but I'd appreciate if you can take a look at your open PRs first. If you're no longer interested in them, you can close them and work on this one. Alternatively, you may instead choose to work on the project you have abandoned long time ago: #7568.

**Comment by joanneong** [comment]
@jimmyshephard hmm...I am afraid that the answer seems to be no. This is because the purpose of this issue is to allow for rank questions to have a style consistent with distribute points questions, but what you are suggesting will differ from the distribute points questions style.

You can refer to https://github.com/TEAMMATES/teammates/pull/8259#issuecomment-360829690 to see the current style of the distribute points questions. Alternatively, you can create a new distribute points question after updating your `master` branch to see its current style.

Let me know if you are no longer interested in working on this issue, because I will take it up if that is the case.

**Comment by jimmyshephard** [comment]
Thanks for the clarification @joanneong , I still want to do this. Will take a look and the comment

**Comment by praXin** [comment]
Hi @joanneong If the issue is still open, I would like to look into it.

**Comment by SavidBasnyat** [comment]
Hi all, I am a first time contributor, looking for some good open first issues to work on. When I created rank questions and distribute points questions, rank questions still had style inconsistent with distribute points questions. So, I was wondering if this issue was still open and needed to be fixed? Thank you.

**Comment by halfwhole** [comment]
Hi @SavidBasnyat, thanks for your interest! There's certainly been a good deal of changes in the frontend/UI over these years.

For reference, here's how the status message currently looks for a distribute points question:
<img width="495" alt="Screenshot 2021-11-10 at 4 32 11 PM" src="https://user-images.githubusercontent.com/41856541/141077838-a1abc9ef-4de6-4099-9196-b97b866279d3.png">

And for a ranking question:
<img width="518" alt="Screenshot 2021-11-10 at 4 32 33 PM" src="https://user-images.githubusercontent.com/41856541/141077885-8067c47e-774b-4981-b09c-9d4955c2523e.png">
 
The positioning of the status message for the two types of questions above are definitely not the same, but personally I'm not sure if this still warrants fixing, after all that's changed. @damithc would you have a preference for where to position the status message for the ranking question?

**Comment by fsgmhoward** [comment]
Looks like that this issue has not been updated for sometime. I will try to push a PR for this.
