### ISSUE TITLE
Instructor: Session: Disable submit button after session is closed

### ISSUE THREAD

**Issue by sukanta-27** [TEAMMATES/teammates#8368]
**Description of enhancement:**
- Login as `Instructor`
- Go to `Home` or `Session`
- take any `session` that is `Closed`, the `submit` button is still active. Clicking that leads to the submission page with the warning ` The feedback session is currently not open for submissions`.

We can disable the `submit` button after the session is closed.

**[Screenshot]:**
![screenshot 313](https://user-images.githubusercontent.com/10681755/35480564-a0125264-0408-11e8-8988-4531a3a90389.png)

**Justification**
We can't submit new responses after a session is closed, so keeping the `submit` button active doesn't add any value. And as we use the same feature for `Remind` button after a session gets published (And after #8358 closes, will get disabled after a sessioin closes), we can do the same for the `Submit` button.

**Comment by sukanta-27** [comment]
Working on this.

**Comment by Ali96kz** [comment]
Can I take this issue?

**Comment by sukanta-27** [comment]
@Ali96kz I am working on this. But thank you for asking first!
