### ISSUE TITLE
Request of information

### ISSUE THREAD

**Issue by Akarsh-TS** [TEAMMATES/teammates#8370]
Hello teammates,this is Akarsh T S and i want to know how can i contribute towards building and upgrading user interfaces.I know in detail of html,css,javascript,scss.
So with this I want to use my knowledge to contribute to the organistation.
My email:ts.akarsh@gmail.com

**Comment by sukanta-27** [comment]
@Akarsh-TS You can refer to our [Orientation guide](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md) that has all the necessary information and a [task list](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md#orientation-task-list) that will help you to start contributing.

**Comment by shaharyar-shamshi** [comment]
@Akarsh-TS you can set up the project on your local system by reading documents and then select any of d.firsttimer issue to get your an idea of teammates codebase and then proceed to d.contributor issue
