### ISSUE TITLE
Eclipse setup: refresh before cleaning the project for the first time

### ISSUE THREAD

**Issue by junkiattan** [TEAMMATES/teammates#8388]
Referring to the [instructions](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-setup.md) for setting up in Eclipse under _Project Setup_,

> Clean the project for all changes to take effect. Ensure that there are no errors. Warnings are generally fine and can be ignored.

it is mentioned in Steps 4 to clean the project and ensure that there were no errors. However after I followed all the steps I still had ~5010 errors. It was only after I refreshed my gradle project and cleaned again that all errors were solved. 

**What I did**
Refresh Gradle Project under Project Explorer -> teammates (right-click) -> Gradle -> Refresh Gradle Project

It would be better if this additional note is included in the instructions to get new contributors to refresh dependencies in case they still encounter errors after Step 4

**Comment by wkurniawan07** [comment]
@junkiattan Let me get this straight: the dependencies are not added to the project when you imported it for the first time?

**Comment by junkiattan** [comment]
@wkurniawan07 I think that they were added in, but after changing the settings in Step 3, somehow it was not reflected in the Problems View after a clean operation.

I discussed the error with @LiHaoTan and showed him my problem view as shown below.

<img width="960" alt="error" src="https://user-images.githubusercontent.com/16800272/35682114-84d57f18-079a-11e8-9cf1-74e6d3ec65ad.png">

Not sure why but all errors were resolved simply by refreshing the gradle project

**Comment by wkurniawan07** [comment]
Ah this looks like something that a Refresh (F5, not refreshing the project) can resolve. Syncing stuffs like this is one of Eclipse's weak points.

**Comment by junkiattan** [comment]
@wkurniawan07  shall I close this issue then?

**Comment by wkurniawan07** [comment]
@junkiattan Adding two words "**`Refresh` and** `Clean`" does not seem to hurt. You can submit a simple fix like that.
