### ISSUE TITLE
Instructor home page: Fix broken panel buttons

### ISSUE THREAD

**Issue by sukanta-27** [TEAMMATES/teammates#8391]
**Environment**

`master`  branch at 03917c8c2d250ff2fe84726e7ae66354169e53d4

**Steps to reproduce**
- Login as `Instructor`
- In `Home`, press any of the buttons  `sessions`, `course`, `Instructors`, `Students` <br>
![screenshot 333](https://user-images.githubusercontent.com/10681755/35722098-d66e3502-07ec-11e8-91c6-dd342cd42240.png)

**Expected behaviour**
A drop down menu should appear. Like in case of `Sessions -> ADD`

**Actual behaviour**
The panel collapses

**Comment by whipermr5** [comment]
Related to #8340. Original discussion: https://github.com/TEAMMATES/teammates/issues/8381#issuecomment-362447594
