### ISSUE TITLE
AdminActivityLogPageUiTest failing against live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8394]
Activity log format seems to be messed up. This is what I see after running the test suite against the live server:

![image](https://user-images.githubusercontent.com/1673303/35766472-6f7d77da-0914-11e8-93c5-99ef427e7437.png)

**Comment by damithc** [comment]
@xpdavid can you help investigate?

**Comment by xpdavid** [comment]
@damithc I cannot reproduce the error locally :( It's better to have the HTML source code of the messed up page if possible.

**Comment by wkurniawan07** [comment]
@damithc Does the test fail or it just does not look right? I have tried and neither of those seems to hold, both local and staging.

**Comment by sukanta-27** [comment]
Could not reproduce the error locally either.

**Comment by damithc** [comment]
> @damithc Does the test fail or it just does not look right? I have tried and neither of those seems to hold, both local and staging.

Both. I checked the latest logs in the live server and seems to be fine. Seems to be a temporary issue. I'll reopen if it happens again.
