### ISSUE TITLE
ide-setup.md: Typo under text encoding: change HTML to XML

### ISSUE THREAD

**Issue by amarlearning** [TEAMMATES/teammates#8397]
In the `ide-setup.md` file, under the `Project Setup` section. I think there should be `XML` in place of `HTML`.

[screenshot]
![ide-setup md](https://user-images.githubusercontent.com/9383897/35771509-bf554c58-0953-11e8-8e62-0978d1446ef3.jpg)

**Comment by wkurniawan07** [comment]
Thanks for the report @amarlearning. You can submit a quick fix for this.
