### ISSUE TITLE
Help Request: Understand how student login and masquerade mode work

### ISSUE THREAD

**Issue by joanneong** [TEAMMATES/teammates#8398]
**What I was trying to do / What I need help with**
I was working on issue #8395 when I tried to understand the points calculation scheme behind contribution questions in teammates. 

To this end, I did the following:
1. From the homepage, do an `Instructor Login` using `test@example.com` as the instructor email
2. Go to Search, and type `Charlie Davis`
3. See that the status is `Joined`, and that the email is `charlie.d.tmms@gmail.tmt`
4. Log out of instructor account
5. From the homepage, do a `Student Login` using `charlie.d.tmms@gmail.tmt`
6. See that "Ooops! Your Google account is not known to TEAMMATES"
7. From the homepage, do an Admin Login using `test@example.com` as the admin email
8. Go to `/admin/adminHomePage`
9. Search `Charlie Davis`
10. Click on the Google ID `charlie.d.tmms.sampleData`
11. Login as `Charlie Davis` in masquerade mode

This confused me since I was under the impression that Charlie Davis would have an account with TEAMMATES since he has joined a course in TEAMMATES with his Google account. Besides, his email can be found when doing a search using the admin account, and he even has a profile in masquerade mode.

**Attempts to resolve the problem**
I tried to read the documentation to find out more about masquerade mode (`develop.md`) and student login (`/studentHelp.jsp`). I also tried to register a new student account with teammates.

Unfortunately I am still not too sure about this. As such, can I check the following:
1. does Charlie Davis actually have an account registered with TEAMMATES, or is the profile automatically generated? Why can't I login as a student with his email account?
2. is there further documentation for masquerade mode for admin/developers? I could only find passing mention of masquerade mode in `development.md` but it does not detail what the masquerade mode does/does not do

**Comment by damithc** [comment]
As these are dummy accounts used in the sample course, it is possible the 'joined' state is faked by the code that creates sample courses. As `charlie.d.tmms@gmail.tmt` Google account does not exist, it is not possible for such a person to have joined TEAMMATES anyway. 
On a related note, it is useful to document how to use the masquerade mode. Admin can use that mode to masquerade another user by adding `?user=username` to the URL.  e.g. `https://teammatesv4.appspot.com/page/instructorHomePage?user=johndoe`

**Comment by joanneong** [comment]
Ah, I see. There is actually documentation now on the masquerade mode in `development.md` (albeit a one-liner comment):

![masquerademodedocumentation](https://user-images.githubusercontent.com/24493463/35779261-fc758b50-0a04-11e8-9d5f-aa3dd2de2203.png)

So I guess it is fine. But I must admit that I did not consider the possibility that the 'Joined' state could have been hardcoded, so thank you for enlightening me!
