### ISSUE TITLE
Homepage Login: allow instructor and student login with leading and trailing whitespace

### ISSUE THREAD

**Issue by joanneong** [TEAMMATES/teammates#8399]
**Description of feature/enhancement**

I was testing TEAMMATES with different instructor and student email addresses when I accidentally tried to login with a valid email address but a single trailing whitespace. This redirected me to the page "Ooops! Your Google account is not known to TEAMMATES" (for student login) and "You are not authorized to view this page." (for instructor login).

I realised that this applies to valid email addresses with leading and trailing whitespaces. As a result, I wonder if it is possible to login students and instructors successfully given valid email addresses with leading/trailing whitespaces.

Of course, if there are any security concerns associated with such a move, I am happy to close this issue.

**Justification**

Students and instructors can possibly benefit from such a change since accidentally including whitespaces during login will not redirect to error pages.

**Comment by damithc** [comment]
Um, which login page are you referring to? TEAMMATES login page is handled by Google.

**Comment by joanneong** [comment]
I meant this page:

<img width="1280" alt="screen shot 2018-02-04 at 5 12 20 pm" src="https://user-images.githubusercontent.com/24493463/35776002-0214fe82-09cf-11e8-90e2-31a66db57398.png">

which can be reached by clicking on `Student Login` in the homepage's navbar:

![studentlogin](https://user-images.githubusercontent.com/24493463/35776075-9e320782-09d0-11e8-8737-40e13417f861.png)

 The same goes for instructor login.

**Comment by damithc** [comment]
That page is just for developers only (it's only available in the dev server). In the actual app, login is handled by Google authentication service.
