### ISSUE TITLE
Instructor: copy sessions: fix inconsistency in instructions

### ISSUE THREAD

**Issue by Haozhe321** [TEAMMATES/teammates#8403]
Given that users can only copy from one session(only radio button could be selected, "sessions" should be changed to "session". 

**Steps to reproduce**
1. Login as instructor
2. Go to `Sessions` page
3. Click on "Copy from previous feedback sessions"
![image](https://user-images.githubusercontent.com/26651556/35808249-2bfad9c8-0ac0-11e8-9551-62babc655f22.png)

Resulting page, error in red box:
![image](https://user-images.githubusercontent.com/26651556/35808082-b087616c-0abf-11e8-899f-202b31798aec.png)

**Comment by wkurniawan07** [comment]
@Haozhe321 w.r.t. the screenshot, can you check what this "Copy" actually does:
- Copy all the questions but leave the setting of the new session fresh
- Copy the session in its entirety, i.e. including the setting

If it is the first case, then the header "copying a previous session" needs to be fixed. If the second case, then it's more apt to change "sessions/questions" -> "setting and questions" instead.

**Comment by Haozhe321** [comment]
@wkurniawan07 if "settings" refer to 
![image](https://user-images.githubusercontent.com/26651556/35952018-ebfec99c-0cb8-11e8-8d12-8f9672d7e0b1.png)
then yes these settings(i.e. exact same opening and closing time) are copied over, together with the questions. I believe the latter change that you mentioned is applicable here. BTW, should I change to "settings" instead of "setting"?
