### ISSUE TITLE
Help Request : Create app on GAE

### ISSUE THREAD

**Issue by shivamtrip53** [TEAMMATES/teammates#8407]
- **Operating System:** Not Required
- **JDK Version:** Not Required
- **Eclipse  Version :** Not Required
- **Firefox Version :** Not Required

**What I was trying to do / What I need help with**
In the document "development.md"
  Can tell me exactly how to reach this step "Create your own app on GAE"? I mean do I have to pay after 12 months
![screenshot from 2018-02-06 23-16-23](https://user-images.githubusercontent.com/25117137/35875117-53652052-0b94-11e8-8579-2a3e5a23e80a.png)

What should I write in business name?
![screenshot from 2018-02-06 23-22-50](https://user-images.githubusercontent.com/25117137/35875295-c9d738c4-0b94-11e8-871b-1986f3368a33.png)n

If I don't have card no. , does this mean i can't contribute ?
![screenshot from 2018-02-06 23-25-21](https://user-images.githubusercontent.com/25117137/35875378-1169c6d4-0b95-11e8-8473-c0f639fe5034.png)

**Attempts to resolve the problem**

**Comment by sukanta-27** [comment]
Setting up the staging server is not a mandatory task, and most of the issue do not require you to deploy the app in the staging server (unless it is explicitly mentioned in the issue itself), and most of it can be done on the dev server itself.

Although to start contributing you must complete this [task list](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md#orientation-task-list)

**Comment by whipermr5** [comment]
It'll continue to be free after 12 months unless you're exceeding the monthly usage quotas. I believe there is a personal account type?

**Comment by sukanta-27** [comment]
@whipermr5 There may also be a problem with using a GAE app which I came across , and that is

![screenshot 247](https://user-images.githubusercontent.com/10681755/35903417-00504d04-0bd7-11e8-9a44-1daf9a79ef1c.png)

Free account allows <= 10 queue entries
Paid account allows <= 100 queue entries.

But There is one way around this problem which @wkurniawan07 has mentioned in https://github.com/TEAMMATES/teammates/issues/6363#issuecomment-272698976, but for this a credit card number is needed.

**Comment by whipermr5** [comment]
Yes; you need to link your credit card for the limit to be increased. I meant that they will not charge your linked credit card after 12 months, as long as your usage remains within the free quota. As he suggested, can set the spending limit to 0.

**Comment by wkurniawan07** [comment]
Let me just get this straight: right now you need a credit card even to deploy *anything*, much less with more than 10 task queue entries, right? Reference: https://github.com/TEAMMATES/teammates/issues/6691#issuecomment-283680985

**Comment by sukanta-27** [comment]
@wkurniawan07 Maybe that's not the case. I have an GCP account, and have deployed the teammates project to the staging server. Though I don't use the staging server as I think the project is not completely deployed because of the error stated above. (I don't have a credit card no,)

[This](http://teammates-sukanta.appspot.com/) is the link to my staging server. 

And this is what my billing section looks like : 
![screenshot 348](https://user-images.githubusercontent.com/10681755/35915187-d0c1564c-0bfd-11e8-9e06-1b0fe86ab13d.png)
![screenshot 347](https://user-images.githubusercontent.com/10681755/35915195-d6bb726c-0bfd-11e8-969c-e765019250c2.png)

**Comment by wkurniawan07** [comment]
@sukanta-27 do you happen to have this GCP account since some time before mid-2016?

**Comment by sukanta-27** [comment]
@wkurniawan07 I created the account in GCP (Or rather used my google account to sign in) in NOV 2016, while I was following the orientation task list.

**Comment by shivamtrip53** [comment]
@whipermr5 , @wkurniawan07,  @sukanta-27,  Google has mentioned reason for why they are forcing users to enter credit card no. 
Its just to **ensure** that you are **not a robot**. 
![screenshot from 2018-02-07 23-23-04](https://user-images.githubusercontent.com/25117137/35932572-f75cb5de-0c5d-11e8-8972-145c73fb2e34.png)

**Comment by sukanta-27** [comment]
@shivamtrip53  First sign into your google account. And then can you check if you can simply sign into the GCP using the `Sign In` button instead of clicking `Try It Free`

**Comment by shivamtrip53** [comment]
@sukanta-27 Though `Try It Free` is not a mandatory thing to do for deploying the app, but still I'm not able to deploy my app on staging server and receiving the following error when I try to run `gcloud auth login` followed by `./gradlew appengineDeployAll`.
![screenshot from 2018-02-09 14-40-23](https://user-images.githubusercontent.com/25117137/36020103-850d8aa8-0da7-11e8-9437-12ffa92f80c0.png)

**Comment by tshradheya** [comment]
When using GCP for free and without putting your card details, it doesn't support `queues`( i think there is a limit of 10 which can be changed in `queue.yaml`). 

I am using the similar way and get Build Failed everytime, however it has actually deployed the app and you can access it by going to the link

**Comment by sukanta-27** [comment]
@shivamtrip53 This is the same error I mentioned in https://github.com/TEAMMATES/teammates/issues/8407#issuecomment-363680407. 
As @tshradheya mentioned, though you are getting the build failure, you can check if your app is deployed or not. Chances are it has.

**Comment by shivamtrip53** [comment]
@tshradheya , @sukanta-27 , Yes, it has been deployed.
