### ISSUE TITLE
FeedbackSession: repurpose legacy timeZone field

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#8410]
Right now, the double field `timeZoneDouble` is used to store the UTC offset, while the int field `timeZone` is marked as legacy and not used. This field can be repurposed for storing the time zone ID string required to unblock #84.

**Comment by tran-tien-dat** [comment]
Just some clarification: So the plan is to remove both `timeZone` and `timeZoneDouble` from a feedback session, and change the logic to use the course's `timeZone` field instead?

**Comment by whipermr5** [comment]
Not yet; that would be the last stage, when DST is fully up. For the first stage, the plan is to remove `timeZoneDouble` and store a string in `timeZone` that corresponds to the currently-stored offset.

**Comment by tran-tien-dat** [comment]
Is the middle part really necessary? Storing offset timezone as UTC+9 etc.
can be converted to a ZoneId and used the in the same way throughout the
same way as the geographic timezone, since the ZoneId class abstracts away
the DST rules already.

**Comment by tran-tien-dat** [comment]
I see. So the reason is socialnot technical. Thanks for clarifying.
