### ISSUE TITLE
Instructor: edit session: multiple choice questions: support generating options for all other students

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8412]
Current:
A session can multiple choice questions (single answer or multiple answer) where the options can be generated from the list of all students in the course. 
Suggested:
In some cases, we may want to exclude self from the list. i.e., provide another option `students (excluding self)`

![image](https://user-images.githubusercontent.com/1673303/35924955-6ae38c7a-0c5f-11e8-839e-4d48362db470.png)

**Comment by Haozhe321** [comment]
I'll take a look at this. Should `FeedbackMcqQuestionDetails` and `FeedbackMcqResponseDetails` be the 2 classes I start with?

**Comment by tshradheya** [comment]
I had a bit of look into this. What I noticed is that, when the question is created by the instructor, the list of all students is added to the `List<String> mcqChoices`.

If we need to show all students except the giver, my solution was to remove(hide) the option of the giver while loading the feedback submission form for the user. Although this sounds more like a workaround than an actual solution.

**Comment by bqnguyen94** [comment]
@Haozhe321 I and @tshradheya think you can work directly with `FeedbackSubmissionEditPageData`, maybe filter the `recipientOptionsForQuestion` using `StudentAttributes`.

**Comment by tshradheya** [comment]
I tried some methods to not show the giver option and this way seemed to work.[ Pull Request](https://github.com/tshradheya/teammates/pull/2)

I haven't created new option but made changes for the `student` himself for MCQ questions only. 
The changes are just to try out if it works and there are lot more changes to make( like making it work for Preview, moderation and other areas)

**Comment by Haozhe321** [comment]
@tshradheya are you planning to work on this issue? Because there's no point for us to work on the same issue.

**Comment by tshradheya** [comment]
I haven't really done any substantial work, so I don't mind if you wanna take up this issue. 

I had just done the changes cause I had been thinking about how the options could be tweaked for feedback submission and that's why I made a PR which I thought might help you if you want to work on this issue. Although I don't mind picking up this issue :P

**Comment by Haozhe321** [comment]
I've started on this issue, so yea I would like to work on it haha. Thanks!

**Comment by tshradheya** [comment]
Sure go ahead 👍
