### ISSUE TITLE
FeedbackSessionQuestionTypeTest.json: fix malformed question metadata

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#8418]
Discovered while looking into https://github.com/TEAMMATES/teammates/issues/8415#issuecomment-364003271. The test data of one question is malformed (it's an MSQ question with `msqChoices` but `numOfMcqChoices` instead of `numOfMsqChoices` in the metadata):
https://github.com/TEAMMATES/teammates/blob/85faa7829f4edf19383b033e2d59825652b4b835/src/test/resources/data/FeedbackSessionQuestionTypeTest.json#L711

To investigate whether there are other similar cases, and why the deserialisation does not fail.

**Comment by bqnguyen94** [comment]
Seems to me that no where does `FeedbackQuestionAttributes::metaData` get checked semantically when `DataBundle` is used.

**Comment by tshradheya** [comment]
I just investigated this and found that the `jsonid` : `qn2InSession2InCourse1` which has the MSQ question is never referenced and hence serialization does not fail.

https://github.com/TEAMMATES/teammates/blob/85faa7829f4edf19383b033e2d59825652b4b835/src/test/resources/data/FeedbackSessionQuestionTypeTest.json#L706-L712

I think we can proceed to fix this and add some tests using it.

**Comment by tshradheya** [comment]
On searching where I could add a test for the question, I couldn't find any, cause the place where the question has been used is in `InstructorFeedbackEditSaveActionTest.java` where it doesn't require checking of `numOfMsqChoices` for submission.

The actual `testAndExecuteProcess()` test in `InstructorFeedbackQuestionEditTest` has been done very comprehensively with other msq question from the dataBundle

**Comment by whipermr5** [comment]
I guess we can just do the simple fix `numOfMcqChoices` -> `numOfMsqChoices` then.
