### ISSUE TITLE
AccountAttributes: Add test cases for getCopy()

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#8419]
`AccountAttributesTest` does not test the method at all. Therefore, if there is any change to this method, the failure (if any) would be reflected in integration tests, which is not the correct way.

Need to add some test cases for `getCopy()` in `AccountAttributesTest`, especially when `studentProfile` is `null`.

**Comment by igniteeng000** [comment]
I am new to open source contribution and I would like to work on this.Could you please help me with the specific modules to look for the above issue?

**Comment by tshradheya** [comment]
You will have to look at the `getCopy()` method in `AccountAttributes.java`

The tests should be added in `AccountAttributesTest.java`
