### ISSUE TITLE
Static Analysis Tools : Explore SonarQube

### ISSUE THREAD

**Issue by tshradheya** [TEAMMATES/teammates#8430]
As suggested in the **Project Ideas**, having SonarQube for the project would be a good improvement.
I am currently exploring the tool to see its features.

Any thoughts/feedback?

**Comment by LiHaoTan** [comment]
It might be possible to integrate, replace and improve many static analysis tools we are currently using.

And we can get rid of issues like:
https://github.com/TEAMMATES/teammates/blob/f6a641453158a8323bc806cbd751d35123ab2cca/src/main/webapp/stylesheets/teammatesCommon.css#L1482-L1485

Anyway, related: #6535

**Comment by wkurniawan07** [comment]
Let's keep SonarQube to #6535.
