### ISSUE TITLE
InstructorFeedbackEditPage: include question type help in lightbox

### ISSUE THREAD

**Issue by craaaa** [TEAMMATES/teammates#8431]
**Description of feature/enhancement**
![image](https://user-images.githubusercontent.com/12183503/36060028-7bb3ce34-0e7b-11e8-9b55-3d48656d0e41.png)
At the moment, clicking the info button (shown above) when trying to add a new question in the Edit Feedback Session screen opens `instructorHelp.jsp#fbQuestionTypes` in a new tab. While this is workable, it might be more beneficial to instructors' workflow to have information on question types available on the same page, for example in a lightbox as shown below:
![peek 2018-02-10 15-45](https://user-images.githubusercontent.com/12183503/36060021-436be8fe-0e7b-11e8-9444-ef6922cfe079.gif)

**Justification**
Instructors will benefit from not having to navigate away from the page to learn more about question types. The current info button opens a new tab in the background. This impedes workflow as the user must navigate away from the page, read the information, then navigate back to the page to continue. Users may also get distracted by the (vey comprehensive) information available on `instructorHelp.jsp`.

Moreover, we are already using lightboxes in other parts of the site when displaying additional information; we should standardize what behaviour is expected when the user clicks on the information icon (i.e. lightbox vs. new tab).

To be fair, the question type help is quite long and elaborate, and may not fit well in a lightbox -- we may want to look into including a condensed version instead.

**Comment by damithc** [comment]
Good suggestion. We need to figure out how to implement it without duplication of instructions in two places.

**Comment by wenmogu** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/28526038/36353594-5618ede2-1503-11e8-8a45-49cf1ae56ba7.png)

![image](https://user-images.githubusercontent.com/28526038/36353604-77cd4596-1503-11e8-8707-44a4534abe53.png)

For the pic above I extracted the info for that specific type of question and reused it in both `InstructorHelp` and that modal.

**Comment by craaaa** [comment]
I was thinking of a single light box to replace the info button that is currently there, but this seems like it could be a good solution too. It is more succinct, which is helpful since the question type help section is pretty long. Can you stage the changes?

Also, when you say extracted do you mean that both pages refer to the same source?

**Comment by damithc** [comment]
Some things to note:
* An instructor may need to see details of multiple question types to decide which type fits her needs. That scenario favors showing info of all question types in one page, possibly with a hyperlinked table of contents at the top. 
* Having read the explanations and having chosen a question type, the instructor still may want to refer the details of the question type while filling out the question details. This scenario favors opening the details in a new window/tab rather than as a modal.
* It may be useful to have an info icon for each type in the drop down (e.g., it can open the help in a new window but auto-scroll to the relevant question type) as proposed in the screenshot above, if there is no danger of the user clicking on the info icon when she means to choose the question type instead.

**Comment by wenmogu** [comment]
What about this:
![image](https://user-images.githubusercontent.com/28526038/36498743-37431c0c-177a-11e8-9ffe-084006963a96.png)
^in comparison to the first design, theres no info sign from each list item (and this is the original design of the website  i.e. i dont touch it at all)

![image](https://user-images.githubusercontent.com/28526038/36498799-68851f36-177a-11e8-93ec-0d55ee2dfe68.png)
^clicking on the info button in the first pic will give this modal

![image](https://user-images.githubusercontent.com/28526038/36498847-95969270-177a-11e8-8fa8-1cf13018d768.png)
^some detail of the roadmap modal

![image](https://user-images.githubusercontent.com/28526038/36498892-b470457e-177a-11e8-8208-df30b52773fe.png)
^clicking on each question type will give a modal containing the corresponding help info. Clicking the arrow sign will lead the user back to the roadmap modal

**Comment by wenmogu** [comment]
> Also, when you say extracted do you mean that both pages refer to the same source?
@craaaa Yes, it means I extract the help info for each question type into tags, and use them in both `instructorHelpSessions.jsp`(the new tab help page) and ``newQuestionForm.tag` (the new question forms appear in the page in the above pics)

**Comment by whipermr5** [comment]
@wenmogu +1 to the extraction of tags! :+1: https://github.com/TEAMMATES/teammates/issues/7604#issuecomment-311557171

**Comment by damithc** [comment]
I'm still not sure a modal is the way to go. for one thing, our UI mockups in the help page are meant to display in a full width page. They may not fit a modal window nicely. For another, it is hard to go back and forth between the help page and the actual form if you open it as a modal window. I think opening in a new window/tab is better.

**Comment by craaaa** [comment]
@damithc Which parts of the question help information do you think users would want to refer back to? There's usually just a few lines of explanation text followed by a sample question to show the format of the question. The sample question shown is identical to what the user will see once they add the question, so we're not sure which additional information in the help page users may need to refer to once they choose and add a question.

For us, the expected use case of the info button is for users to preview what each question type will look like before they choose to add a question -- once they choose to add the question, the information to fill out the question should be available in the question form itself.

**Comment by damithc** [comment]
> @damithc Which parts of the question help information do you think users would want to refer back to? There's usually just a few lines of explanation text followed by a sample question to show the format of the question. The sample question shown is identical to what the user will see once they add the question, so we're not sure which additional information in the help page users may need to refer to once they choose and add a question.
> 
> For us, the expected use case of the info button is for users to preview what each question type will look like before they choose to add a question -- once they choose to add the question, the information to fill out the question should be available in the question form itself.

Yes, that seems to be the case. And yes, if we can make all the information available in the form itself, there is no need to refer back to the help page.  We can proceed with the modal approach and provide an additional link to open the full help page in a new tab.

**Comment by thikhinab** [comment]
Hi! I would like to work on this issue. May I have a rough idea on the starting point of the UI. What I have understood from  the quoted, a possible solution is to have easy access links/icons next to each question type. This link would open a new tab to the help/instructions given for the particular question at the `Setting up Questions` section.

> Some things to note:
> 
>     * An instructor may need to see details of multiple question types to decide which type fits her needs. That scenario favors showing info of all question types in one page, possibly with a hyperlinked table of contents at the top.
> 
>     * Having read the explanations and having chosen a question type, the instructor still may want to refer the details of the question type while filling out the question details. This scenario favors opening the details in a new window/tab rather than as a modal.
> 
>     * It may be useful to have an info icon for each type in the drop down (e.g., it can open the help in a new window but auto-scroll to the relevant question type) as proposed in the screenshot above, if there is no danger of the user clicking on the info icon when she means to choose the question type instead.

**Comment by damithc** [comment]
> Hi! I would like to work on this issue. May I have a rough idea on the starting point of the UI. What I have understood from the quoted, a possible solution is to have easy access links/icons next to each question type. This link would open a new tab to the help/instructions given for the particular question at the `Setting up Questions` section.

Yes @thikhinab , that's my current thinking. Other views welcome.

**Comment by thikhinab** [comment]
@damithc Understood prof! Will come up with working solution!
