### ISSUE TITLE
InstructorFeedbackResultsPage: make span scrollable to fit the table to copy

### ISSUE THREAD

**Issue by joanneong** [TEAMMATES/teammates#8437]
**Description of feature/enhancement**

In the instructor feedback results page, instructors can directly copy the data in the page to an excel spreadsheet if non-english characters are not displayed properly in the downloaded file:

![image](https://user-images.githubusercontent.com/24493463/36069688-aa549170-0f29-11e8-9d02-330918b03e09.png)

However, if there are feedback and comments given by students/instructors, the resulting table protrudes from the given span:

![image](https://user-images.githubusercontent.com/24493463/36069727-db0a002a-0f29-11e8-8185-e1d3907bf793.png)

The span can be made scrollable in order to fit the entire table within the span.

**Justification**

By allowing the table to fit within the span, it will improve the look of the table. Additionally, it will make the table more readable for instructors (particularly the alternating transparent rows) so that they can take a look at the data before copying to their excel spreadsheet.

**Comment by lightt77** [comment]
I would like to work on this one...

**Comment by joanneong** [comment]
@lightt77 Since you are new to TEAMMATES, it is recommended that you try a `d.FirstTimers` issue first before moving on to a `d.Contributors` issue like this one :)

**Comment by shivanshsoni** [comment]
@joanneong I would like to work on this issue....Is it possible?

**Comment by lightt77** [comment]
@joanneong  Okay, I'll do that first.

**Comment by joanneong** [comment]
@shivanshsoni Since you have already tried a `d.FirstTimers` issue, feel free to give this a shot :)

**Comment by shivanshsoni** [comment]
ok :-)

**Comment by Shashwat-Garg** [comment]
@shivanshsoni Are you working on this issue ?

**Comment by Shashwat-Garg** [comment]
@joanneong Can we add it to the stylesheet to make changes ?
I've tried it and it works.
Should I proceed with a PR, or should I try it some other way ?

**Comment by joanneong** [comment]
@Shashwat-Garg You can go ahead and open a pull request first, and we will see how to proceed from there :)

**Comment by wkurniawan07** [comment]
Closing as the modal to show table has been deprecated.
