### ISSUE TITLE
New contributor self intro : lightt77

### ISSUE THREAD

**Issue by lightt77** [TEAMMATES/teammates#8438]
- **Link to my fork:** 
https://github.com/lightt77/teammates

**Screenshot of changes made (as seen on the UI)**
![img1](https://user-images.githubusercontent.com/20469489/36070006-993cd0e8-0f18-11e8-92cb-1ac1ae1a7d6a.PNG)

**Short self-introduction**

I am Abhishek Satam, a fresh EE grad with 6 months industry experience and a newbie to the open-source world.This is my first open source commit.I wanted to test the open-source waters and this project looked like a good starting point.

**Comment by joanneong** [comment]
Welcome to TEAMMATES :) It would be good for you to get to know the codebase first by attempting a `d.FirstTimers` issue before proceeding on to `d.Contributor` issues :)
