### ISSUE TITLE
New contributor self intro : shivanshsoni

### ISSUE THREAD

**Issue by shivanshsoni** [TEAMMATES/teammates#8439]
Link to my Fork:
https://github.com/shivanshsoni/teammates

Self-intro:
I am Shivansh Soni,  ECE student of the 3rd year at NIT Hamirpur. I have good experience in Java and I love open source. So, I want to use that experience to solve issues of teammates and make the user experience better. I want to be a part of this organisation for GSOC 2018. I hope I will make it.

Some pull requests opened by me: 
issue #8299:- https://github.com/TEAMMATES/teammates/pull/8420
issue #8421:- https://github.com/TEAMMATES/teammates/pull/8435

**Comment by joanneong** [comment]
Welcome to TEAMMATES. Nice to see that you have already tried your hand at a `d.FirstTimers` issue, so feel free to move on to `d.Contributors` issues :)

**Comment by shivanshsoni** [comment]
Thanks :-)
