### ISSUE TITLE
Instructor: view results: fix incorrect labeling of 'Expand Students' button

### ISSUE THREAD

**Issue by nidhi98gupta** [TEAMMATES/teammates#8442]
Steps:
1. Make sure you're on the view Giver > Recipient > Question
2. Click Expand all sections. 
3. Now collapse students in one of the groups.
4. Then collapse all sections.
5. If we now expand all sections again then students will also be in expanded state but the button will be in "Expand Students" state and clicking it will not change anything since student panels are already in expanded state.

![expand](https://user-images.githubusercontent.com/24381442/36072163-d8685e36-0f40-11e8-9e9e-c45f442cca85.png)

Expected behavior:
When we click "Expand all section" button, student panel button should show "Collapse students".

**Comment by nidhi98gupta** [comment]
Working on fixing this.

**Comment by sukanta-27** [comment]
Isn't it more of a `d.FirstTimers` issue?

**Comment by nidhi98gupta** [comment]
@damithc Apologies for delay in replying. I missed your comment. Actually I have solved both the issues in this PR only. :sweat_smile:

**Comment by wkurniawan07** [comment]
No longer valid as the buttons do not exist anymore
