### ISSUE TITLE
Help Request: Tests failing due to time format and decimal

### ISSUE THREAD

**Issue by KevKos** [TEAMMATES/teammates#8444]
- **Operating System:** Arch Linux
- **JDK Version:** 8
- **Eclipse / IntelliJ Version (if applicable):** Oxygen 2
- **Firefox / Chrome Version (where applicable):** FF 45

**What I was trying to do / What I need help with**

I was following the guidelines to setup the project and I am now stuck with passing the tests. Every time I get around 30 failed tests. All of them failing due to incorrect date/time format or different decimal. 

I use my system with german localization so expected  `Wed, 30 Dec 2015, 12:00 NOON` is `Mi, 30 Dez 2015, 12:00 NOON` on my system. Just like where `3.5` is expected, my system uses `3,5`.

![image](https://user-images.githubusercontent.com/23256864/36078734-f0525cc4-0f7a-11e8-922c-69aa9f7d35ad.png)

Does anybody know how to resolve this issue on Linux? Maybe without changing localization system wide?

**Comment by darrenwee** [comment]
Hi! Can you type `locale` into a Terminal and copy the output here so I can reproduce your environment? I think I have an idea of how to fix this but I'll need to test it.

**Comment by KevKos** [comment]
Hello,

sorry for the delay. Here's the output of `locale` .

`LANG=de_DE.utf8`
`LC_CTYPE="de_DE.utf8"`
`LC_NUMERIC="de_DE.utf8"`
`LC_TIME="de_DE.utf8"`
`LC_COLLATE="de_DE.utf8"`
`LC_MONETARY="de_DE.utf8"`
`LC_MESSAGES="de_DE.utf8"`
`LC_PAPER="de_DE.utf8"`
`LC_NAME="de_DE.utf8"`
`LC_ADDRESS="de_DE.utf8"`
`LC_TELEPHONE="de_DE.utf8"`
`LC_MEASUREMENT="de_DE.utf8"`
`LC_IDENTIFICATION="de_DE.utf8"`
`LC_ALL=`

**Comment by KevKos** [comment]
Thanks for the hint. Solved the problem by starting eclipse with custom environment variables via shell.

So, `LANG=en_US.UTF-8 ./eclipse` starts eclipse with US english locales while my system remains german.

**Comment by darrenwee** [comment]
Glad to hear it, @KevKos! I'll open an issue to deal with this using the gradle build script so we can have a more consistent building experience for future contributers!
