### ISSUE TITLE
Remove private sessions

### ISSUE THREAD

**Issue by sukanta-27** [TEAMMATES/teammates#8447]
**Description of feature/enhancement:** As according to the discussion in https://github.com/TEAMMATES/teammates/pull/8408#issuecomment-364850538, we should remove the `Private` session feature.

**Justification:**

As pointed out by @damithc sir, this feature is not widely used. Apart from that, `Private` sessions also give rise to issues like #8406, #8411.

**Original Discussion :** https://github.com/TEAMMATES/teammates/pull/8408#issuecomment-364770482

**Comment by sukanta-27** [comment]
Taking up this issue.

**Comment by sukanta-27** [comment]
@damithc  Sir, regarding the UI change in Feedback Session Form. Is this UI change okay?
**[UI before]**
![screenshot 358](https://user-images.githubusercontent.com/10681755/36345872-4d8c39d2-142b-11e8-9d16-30f343a76604.png)
<br>**[UI after]**
![screenshot 359](https://user-images.githubusercontent.com/10681755/36345876-55aca6ec-142b-11e8-90e8-40da30fcc1a2.png)

**Comment by damithc** [comment]
> Is this UI change okay?

@sukanta-27 yes, looks good.

**Comment by sukanta-27** [comment]
**Note:** It is taking longer than usual for me to open a PR for this issue, as I am currently exploring the `Project Ideas` for my GSoC proposal. I will send a PR for this issue within 1-2 days. Sorry for the delay.

**Comment by sukanta-27** [comment]
@damithc Sir, I have a query.
How should we deal with the private sessions that are already present in the system, and have a `null` opening time or closing time?
I was thinking how about assigning the current time to the sessions which have `startTime == null` as the start time and for the sessions that have null endTime we can assign a date one week ahead of the current time?

**Comment by damithc** [comment]
> I was thinking how about assigning the current time to the sessions which have startTime == null as the start time and for the sessions that have null endTime we can assign a date one week ahead of the current time?

hmm... I think assigning them in a time far in future (like 100 year ahead) may be safer?  Otherwise, these sessions can trigger emails which will be a nasty surprise to the users.

**Comment by sukanta-27** [comment]
@damithc Okay. two more queries. 

>I think assigning them in a time far in future (like 100 year ahead) may be safer?

1.This should be done by running a migration script before deploying the new version right?
2. I should delete all the tests for `PRIVATE` sessions, and there test data?

**Comment by damithc** [comment]
1. Yes
2. Yes
