### ISSUE TITLE
Instructor: edit session: 'distribute points' questions: support 'some variation required' option

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8449]
In 'distribute points' questions, we support an option that requires all entries to be different from each other. This option may be 'too aggressive' for some users. It is good if we can support an option to 'require some variations'.

![image](https://user-images.githubusercontent.com/1673303/36188540-a4f16054-1187-11e8-8f2d-580f2afef932.png)

For example, we can insert a drop-down in to the current option:
- [ ] [`Every option` | `At least some options`] `to receive a different number of points`

**Comment by joanneong** [comment]
I will try to work on this.
