### ISSUE TITLE
Instructor: edit session: 'distribute points' questions: support min/max

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8450]
![image](https://user-images.githubusercontent.com/1673303/36188605-0e1c3a72-1188-11e8-9aa2-81805787d2df.png)

In 'distribute points' questions, we can support specifying min and max number of points a respondent is allowed to allocate to any option. This will allow users to control the variation of entries within a certain range.

**Comment by Crphang** [comment]
I can work on this

**Comment by gildas15** [comment]
Please can you assign this issue to me

**Comment by gildas15** [comment]
I want to work on it

**Comment by wkurniawan07** [comment]
@gildas15 this issue is blocked by something right now. Try to find something else to work on?

**Comment by thikhinab** [comment]
If no one is working on this issue, may I attempt to solve this?
