### ISSUE TITLE
Instructor: feedback edit page: MSQ maximum options changes and saves without notification to user 

### ISSUE THREAD

**Issue by Haozhe321** [TEAMMATES/teammates#8453]
noticed this while working on #8412

**Environment**
`master` branch at 1cad352

**Steps to reproduce**
1. Create a new MSQ question
2. Either create the options or generate options from list of students/team/instructors
3. **in the box for** `Maximum number of options a respondent is allowed to select`, **key in a number that is higher than the number of options in step 2**
4. Save the question

In the SS below, I gave a maximum choice of 100 which is larger than the number of students
![image](https://user-images.githubusercontent.com/26651556/36195891-e4cbebf0-11a9-11e8-8627-61c876866a6a.png)

**Expected behaviour**
Warning message that notifies the user that the number he/she put in is larger than the number of choices possible. Then ask them to put in a new number. Perhaps a message informing them of the upperbound will also help.  

For example, this is being displayed in response to illegal value for minimum value when you press "Save", and the saving action is blocked. Same could be done for the maximum number. 
![image](https://user-images.githubusercontent.com/26651556/36196798-c983dc06-11ac-11e8-815d-b6fff005858b.png)

**Actual behaviour**
The field for `Maximum number of options a respondent is allowed to select` changes automatically to the maximum possible choices without notifying the user, and the question is saved. 
![image](https://user-images.githubusercontent.com/26651556/36195923-fbc7697e-11a9-11e8-84a2-4e70d830e770.png)

**Why this matters**
If a user keys in the wrong maximum number, it is possible that they are doing it for the wrong question, or had a wrong impression of the total number of choices for the msq. In such instances, they should be notified, instead of the system allowing such errors to pass.

**Comment by nidhi98gupta** [comment]
@Haozhe321 @damithc I would like to take up this issue.

**Comment by Haozhe321** [comment]
@nidhi98gupta sure :)

**Comment by sukanta-27** [comment]
@damithc Just checked, this issue also happens in the case of `Rank (options)` and `Rank (recipients)` questions. Should we fix this in this issue only or should I create a new issue?
