### ISSUE TITLE
Instructor: add options (Rank and Distribute Points) question: add more options inputs not appearing

### ISSUE THREAD

**Issue by Crphang** [TEAMMATES/teammates#8463]
**Environment**

Ran in development environment.
Master branch

**Steps to reproduce**

1. Edit session
1. Click `new question` => `add rank options question`.
1. Cancel question
1. Add `new question` => `add rank recipients question`
1. Cancel question
1. Add `new question` => `add rank options question`

**Expected behaviour**

The UI appearing should be consistent on both attempts of adding rank options.

**Actual behaviour**

First attempt of adding rank options:

![image](https://user-images.githubusercontent.com/4986717/36338949-9359eb16-13f5-11e8-9c5a-298646a3e79c.png)

Second attempt of adding rank options (after adding rank recipient questions):

![image](https://user-images.githubusercontent.com/4986717/36338954-ab77ef2c-13f5-11e8-9e2c-49d9e48250ec.png)

The options on the left does not appear.

Similar problem happens for Distribute Points (Options) question, more details shown in @sukanta-27 comment below.

**Comment by bqnguyen94** [comment]
I'm on it

**Comment by gaurav122197** [comment]
@Crphang , @bqnguyen94 I do not seem to reproduce the problem. Even though after trying the above-mentioned steps my UI seems to be consistent.
Is there anything that I am missing?

**Comment by sukanta-27** [comment]
@Crphang @bqnguyen94 Could reproduce this bug. Don't know if any of you noticed it, but these steps are not necessary. `1->4->5->6` seems to work as well.

>2.Click new question => add rank options question.<br>3. Cancel question

**Comment by Crphang** [comment]
I think distribute (options) questions has the same problem, could be similar code causing it.

**Comment by sukanta-27** [comment]
@Crphang In my system, for distribute (Options) : 
**[UI before]**
![screenshot 355](https://user-images.githubusercontent.com/10681755/36343879-e600e0cc-1409-11e8-8957-7d58e383ab1c.png)

**[UI after]**
![screenshot 357](https://user-images.githubusercontent.com/10681755/36343881-f41ecb74-1409-11e8-86f8-93b5e236360a.png)

**Comment by gaurav122197** [comment]
@Crphang @bqnguyen94 @sukanta-27 I think the problem reproduces when we add Rank (recipient) question and then add Rank (options) question otherwise the UI seems to be consistent when following the above-mentioned steps of @Crphang .
Help me if I am missing something.

**Comment by bqnguyen94** [comment]
The problem is toggling `rank recipient` question form hides `rank-option-table` element, and it remains hidden even if its parent element is shown later on.
