### ISSUE TITLE
Instructor: edit question: distribute question options vs recipients tooltip (UI). 

### ISSUE THREAD

**Issue by crphang** [TEAMMATES/teammates#8465]
**Description of feature/enhancement**

Currently, the tooltip for total points to distribute in 'Distribute points (among options)' should be describing options which is correct. On the other hand, the tooltip for total points to distribute in 'Distribute points (among options)' should be describing distributing points among recipients but it is now describing about distributing it among options.

Distribute in options:
![image](https://user-images.githubusercontent.com/4986717/36340096-aab8916c-140f-11e8-8ad9-ca3c819b9b01.png)

Distribute in recipients:
Still mentioning about distributing it in options.
![image](https://user-images.githubusercontent.com/4986717/36340098-cbd6f4ba-140f-11e8-912c-6e85a38fdee4.png)

We can change the tooltip for the Distribute Question (for recipients) to talk about recipient instead of option.

**Justification**

Instructors will benefit when by having less confusion with the type of question they are actually selecting.

This can be a `d.FirstTimers` issue.

**Comment by wkurniawan07** [comment]
@Crphang are you sure of the steps to reproduce? According to my investigation, the tooltip for the distribute points among recipients question is always like that all along.

**Comment by Crphang** [comment]
The steps to reproduce is trivial (they are like that all along since the code points to the same constant). Basically just looking at two different questions and the fact that they have same tooltip even though they are different question types.

**Comment by wkurniawan07** [comment]
The thing is, the way this report is presented makes it seems like one needs to perform a specific series of steps in order to reproduce it. Also, this is actually more suitable under feature/enhancement request.

**Comment by Crphang** [comment]
Yes, I think it can be more confusing by having the portion of steps to reproduce. I will change it to make it clearer 😄

**Comment by tshradheya** [comment]
I think we can add a `d.FirstTimers` tag on this as suggested by @Crphang  cause I there are some new contributors who were searching for `d.FirstTimers` issue

**Comment by ryanmccauley211** [comment]
I would like to take this on as my first issue!

**Comment by shaharyar-shamshi** [comment]
@ryanmccauley211 you can take up this issue Looking forward to have  pull request from you

**Comment by EvilJorge** [comment]
If this is not still being worked on, I would like to take this on as my first issue.

**Comment by laurensdegilde** [comment]
Is this still open? Happy to fix it today.

**Comment by Crphang** [comment]
@laurensdegilde go ahead and make a pull request. It is still open.

**Comment by gildas15** [comment]
Please can I work on this issue

**Comment by kanwarpreet25** [comment]
Is it still open?

**Comment by bezalelBU** [comment]
I believe I have fixed this issue. May I submit PR?

![tm-8465-fix 6](https://user-images.githubusercontent.com/59073587/101675568-33a45a80-3a17-11eb-99c4-8e5a973b33c0.png)

**Comment by rrtheonlyone** [comment]
@bezalelBU yes please go ahead
