### ISSUE TITLE
New contributor self intro: Tan Heng Yeow

### ISSUE THREAD

**Issue by tanhengyeow** [TEAMMATES/teammates#8466]
- **Link to my app (with deployed changes):** https://teammates-tanhengyeow.appspot.com/terms.jsp
- **Link to my fork:**  https://github.com/tanhengyeow/teammates/tree/tinker

**Screenshot of changes made (as seen on the UI)**

![image](https://user-images.githubusercontent.com/25320782/36344568-ae443f46-1457-11e8-9abf-a58964a28957.png)

**Short self-introduction**
Hi everyone, I am a Y2 NUS Computer Science undergraduate. I hope to bring about positive changes by contributing to TEAMMATES while learning from other like-minded contributors as well. I aim to become a long-term contributor with the intention of joining NUS-OSS internship, CS3281/2 and/or GSoC in the future. Look forward to the journey ahead!

**Comment by sukanta-27** [comment]
Hi @tanhengyeow 
Welcome to TEAMMATES. You can start contributing by taking one of our `d.FirstTimers` issues, before moving onto the `d.Contributors` issues.

**Comment by tanhengyeow** [comment]
Hi @sukanta-27 

Thank you! I realized all `d.FirstTimers` issues are either resolved or have a open PR. Do I still work on any of them regardless?

**Comment by LiHaoTan** [comment]
@tanhengyeow You can also start with a `d.Contributors` :). Feel free to start with an easier one if you like.
