### ISSUE TITLE
Feedback Session: Remove 'Never Publish' option

### ISSUE THREAD

**Issue by sukanta-27** [TEAMMATES/teammates#8468]
**Environment:**
`master` branch.
Don't know if this is a bug or intentional. So, went along with the bug template.
**Steps to reproduce:**
- Login as `Instructor`
- Create a new session, set a Opening time so earlier than current time, to get a `Open` session
- Set the option `Responses visible from` to `Never`. 
- Now go back to `Home` or `Sessions`, and find the session you created in the session table
- Open the drop down button in `Results` action, or go to Results page and click `Publish Results`

**Expected behaviour:** There should be a error message that the session can not be published as the session is set to never get published. Or, the `Publish Results` button should be disabled.

**Actual behaviour:** The session gets successfully published.

I think the proper steps to publish results for these kind of sessions should be, `Edit` -> `Responses visible from` -> Any option other than `Never` -> `Save Changes`.

**Comment by whipermr5** [comment]
This was an unintentional side effect of #8094 (see https://github.com/TEAMMATES/teammates/pull/8408#issuecomment-364468574). Anyway, private sessions are about to be removed: #8447.

**Comment by sukanta-27** [comment]
@whipermr5 Need to clarify two things.
I checked out commits before #8094, and this issue seems to persist. sessions that are not private can be published even though the `Response visible from` to `Never`! 
How is this related to private sessions? (Is the `Never` option mentioned above only applicable to `Private` sessions?) <br>And if that is the case, should I remove the `Response visitble from`->`Never` option too, (Screenshot of the current changes are shown in : https://github.com/TEAMMATES/teammates/issues/8447#issuecomment-366473655)?

**Comment by wkurniawan07** [comment]
@sukanta-27, that option only guarantees that the session will not be automatically published after a certain timestamp. Nothing stops anyone with sufficient permission to manually publish the session at any time.

**Comment by damithc** [comment]
> But, can't that be accomplished by the option Publish manually as well? Then, what is the use point of having this option?

Technically, yes. I guess we decided to have the 'never' option to better match user intentions. It's a bit unintuitive for a user who doesn't intend to publish at all to choose 'publish manually'.

**Comment by sukanta-27** [comment]
@damithc So Sir, can we implement a feature where, if a user tries to publish the session that has been set to never get published, he/she will receive an error (Like `Can not publish a session that is set to never publish, change the 'Response Visible Time' to a option other than 'Never' to publish this session`), or a warning message (Like `The session is set to never get published, are you sure you want to publish it?`), so that a user who does not want a particular session to get published, doesn't accidentally publish the session!

**Comment by damithc** [comment]
> @damithc So Sir, can we implement a feature where, if a user tries to publish the session that has been set to never get published, he/she will receive an error (Like Can not publish a session that is set to never publish, change the 'Response Visible Time' to a option other than 'Never' to publish this session), or a warning message (Like The session is set to never get published, are you sure you want to publish it?), so that a user who does not want a particular session to get published, doesn't accidentally publish the session!

Yes, that can be useful to prevent accidental publishing, as long as it can be implemented easily. We don't want to increase code base too much as a result of adding features that we can live without.

**Comment by sukanta-27** [comment]
>Yes, that can be useful to prevent accidental publishing, as long as it can be implemented easily. We don't want to increase code base too much as a result of adding features that we can live without.

@damithc I haven't started working on it yet, so don't know about the implementation difficulty as of yet. But, can I work on this and see how this turns out?

**Comment by sukanta-27** [comment]
@damithc Instead of going with the warning message I guess it would be better to go with the error message, as warning messages can be easily ignored (clicking the OK button without looking into the message, specially for those who are using the system for a while). For the UI change, can we use something like this? (If yes then I can submit a PR for further review)

**Screenshot:**
![screenshot 363](https://user-images.githubusercontent.com/10681755/36358082-0f73ec96-1500-11e8-86a3-6189c137d693.png)

**Comment by whipermr5** [comment]
> @whipermr5 Need to clarify two things.
> I checked out commits before #8094, and this issue seems to persist. sessions that are not private can be published even though the Response visible from to Never!
> How is this related to private sessions? (Is the Never option mentioned above only applicable to Private sessions?) 
> And if that is the case, should I remove the Response visitble from->Never option too, (Screenshot of the current changes are shown in : #8447 (comment))?

Oops I mixed this up with `Session visible from`; my bad 😅

> @damithc So Sir, can we implement a feature where, if a user tries to publish the session that has been set to never get published, he/she will receive an error (Like Can not publish a session that is set to never publish, change the 'Response Visible Time' to a option other than 'Never' to publish this session), or a warning message (Like The session is set to never get published, are you sure you want to publish it?), so that a user who does not want a particular session to get published, doesn't accidentally publish the session!

I feel the warning option is better. The error adds an additional step for users who actually want something published but selected the wrong option when creating the session or simply changed their mind after creating the session. If they dismiss the warning, it is reasonable to assume that they read it. They can always unpublish the session if they made a mistake.

**Comment by damithc** [comment]
> They can always unpublish the session if they made a mistake.

Given that, perhaps we just leave it as is? If we add a warning/error here, in addition to having more code to maintain, we add time to tests which is a permanent cost.

**Comment by whipermr5** [comment]
Then I'd suggest merging the `Never` and `Publish Manually` option into one, e.g. `Never (or publish manually)`.

**Comment by whipermr5** [comment]
On second thoughts, I feel that changing the heading from `Responses visible from` to `Automatically publish responses` would be better:
<img width="543" alt="screen shot 2018-02-19 at 6 01 51 pm" src="https://user-images.githubusercontent.com/6811428/36372157-2216ab5a-159f-11e8-8fb7-35540292be83.png">

**Comment by whipermr5** [comment]
In a similar vein, the `Session visible from` heading can be improved to `Make session visible`:
<img width="542" alt="screen shot 2018-02-19 at 6 08 40 pm" src="https://user-images.githubusercontent.com/6811428/36372454-1582d8ea-15a0-11e8-9dc0-915d2ebe5fbc.png">

This reads much better IMHO.

**Comment by sukanta-27** [comment]
@whipermr5 I think this will be better, as `Automatically publish responses` seems more accurate in this context. Same goes for `Make session visible`. If asked, I would love to do this. :smile:

**Comment by damithc** [comment]
UI design is not an exact science; hard to get right or even agree on the best design.

I'm a bit vary of designing the UI to match how the app processes things rather than how the user thinks about things. As a user I'm thinking "I'll publish the results at a later time". It's an additional step for me to also figure out "hey, that's the same as choosing 'Never' now and clicking the 'Publish' button later" (or something of the sort). i.e., the close we can get to user intention, the easier it feels to use. 

I'm also wary of combining things just because they are processed the same way. I use a banking app that has an option `Transfer now / SLIIP` or something like that. Although I understand it means one or the other, I always hesitate a moment before choosing that option because I have no idea what `SLIIP` is; I feel a bit annoyed to even having to read that word with which I don't have any business. This kind of thing (e.g., choosing an option that  has some unrelated thing in it) adds anxiety to users, especially non-techie users, and makes the app less user-friendly, I think.

Of course, we also have to factor in complexity of implementation. At times we may have to choose the design that simplifies the code rather than user experience.

**Comment by sukanta-27** [comment]
I agree with what Prof. @damithc said, that users may get a little confused if they see the word `Automatically` and no `Publish manually` option. 
I can suggest a few ways to deal with this issue : 
1. Leave everything as it is. But with a little modification. (`from` followed by `At` sounds a bit weird IMO)
![screenshot 364](https://user-images.githubusercontent.com/10681755/36377440-12675248-156f-11e8-83e6-762a826826e2.png)
2. Merge two options with something like `Never (Publish later)` or `Never (Publish manually)` (Something like this)
![screenshot 365](https://user-images.githubusercontent.com/10681755/36378029-1ddbd480-1571-11e8-88e7-84cc6a121fa8.png)

3. Remove the option `Never` completely. As the tooltip for the option `Never` and the function doesn't match at all. 
![screenshot 366](https://user-images.githubusercontent.com/10681755/36378036-2824160a-1571-11e8-8af3-27e819c9f382.png)

And after removing private session in #8447 The option `Session visible time -> Never` will also be removed. see : https://github.com/TEAMMATES/teammates/issues/8447#issuecomment-366473655 

@whipermr5 @damithc waiting for your view on this.

**Comment by damithc** [comment]
Option 2 reads better, but option 3 is simpler to read. @whipermr5, what do you think?

**Comment by sukanta-27** [comment]
@whipermr5 Waiting for your view on https://github.com/TEAMMATES/teammates/issues/8468#issuecomment-366681607

**Comment by whipermr5** [comment]
What about option 3 but change `Publish manually` to `Next time` so it reads better?

**Comment by sukanta-27** [comment]
@whipermr5 I think it has the possibility to confuse a lot of users. I mean `Next time` doesn't imply that the user will have to publish the session manually later? Users generally set this option while creating a new session, or editing it. Isn't it possible that the user will get confused by reading the term `Next time`, and may think he/she may has to edit the session in a later stage to set up a publish time (or something like that)?

**Comment by whipermr5** [comment]
What about `Not now (publish manually)` or just `Not now` with `Publish manually` as a tooltip?

**Comment by sukanta-27** [comment]
@whipermr5 I liked the `Not now` with `Publish manually` as a tooltip option. `Not now (publish manually)` is a little verbose for a radio button title. Isn't it?

**Comment by damithc** [comment]
> @whipermr5 I liked the Not now with Publish manually as a tooltip option. Not now (publish manually) is a little verbose for a radio button title. Isn't it?

I think we should have the `Publish manually` as the main text. It's too important to relegate to the tool tip.

**Comment by sukanta-27** [comment]
@damithc Okay, sir. I will make the changes accordingly.

**Comment by sukanta-27** [comment]
@damithc Sir, just to be clear, you are suggesting not to change the `Publish manually` text at all, right?
Or, are you suggesting we should keep the word `Not now (Publish manually)` [Therefore not to completely remove the word publish manually]?

**Comment by damithc** [comment]
Let's try `Not now (Publish manually)`
