### ISSUE TITLE
Update user map for Jan 2018

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8473]
Similar to #8295

Entries to consider

Australia | Queensland University of Technology
-- | --
Australia | University of Melbourne
Belgium | Ghent University
Belgium | Sint-Pieterscollege
Belgium | Thomas More Vorselaar
Brazil | Federal university RN, UFRN
Brazil | Universidade Federal do Rio Grande do Sul
Canada | Dalhousie
Canada | Heritage College
Canada | Mennonite Bretheren Colligiate Institute
Canada | Okanagan College
Canada | Queen's University
Canada | Simon Fraser University
Canada | University of Lethbridge
France | Cooperative University of Colombia
Germany | EBS University
Hong Kong | The Education University of Hong Kong
Italy | Catholic University Milan
Moldova | George Cosbuc Lyceum
Netherlands | Deltion College
Netherlands | Edulia
Netherlands | Van Hall Larenstein University of Applied Sciences
New Zealand | Massey University
New Zealand | Massey University
New Zealand | University of Auckland
Philippines | Mapua University
Russia | Skoltech
Saudi Arabia | King Fahd University of Petroleum and Minerals
Singapore | Institute of Technical Education
Singapore | Nanyang Polytechnic
Singapore | Nanyang Technological University
Singapore | Raffles Institution
Singapore | University of Glasgow
South Africa | Stellenbosch University
South Korea | SolBridge international School of Business
Spain | La Miranda
Spain | Universidad Carlos III de Madrid
Taiwan | National Taiwan University
Taiwan | National Taiwan University
UK | Kingston University London
UK | Unbiversity of Greenwich
UK | University of Bath
UK | University of Greenwich
UK | University of Sussex
USA | Agnes Scott College
USA | Belmont College
USA | Boston University
USA | Brigham Young University, Idaho
USA | Caledonia Middle School
USA | California State University, Fullerton
USA | Christopher Newport University
USA | Clemson University
USA | Cleveland State University
USA | Cleveland State University
USA | Colorado School of Mines
USA | Concordia High School
USA | Drexel University
USA | Duke University
USA | Duquesne University
USA | Flagship Computing and Analytics
USA | Gallaudet University
USA | James Madison University
USA | Kansas State University
USA | Kennesaw State University
USA | Kentucky Wesleyan College
USA | Medical College of Wisconsin
USA | Michigan State University
USA | Midland University
USA | New Mexico State University
USA | Northeastern University
USA | Northern Arizona University
USA | Ohio University
USA | Ohio University
USA | Republic Middle School
USA | Salem State University
USA | San Jose State University
USA | San Jose State University
USA | Siena College
USA | STEM School Highlands Ranch
USA | Tennessee Technological University
USA | Texas A&M University
USA | Texas Tech University
USA | UNC Charlotte
USA | University at Albany
USA | University of Colorado Boulder
USA | University of Connecticut
USA | University of Detroit Mercy
USA | University of Georgia
USA | University of Illinois
USA | University of Maryland
USA | University of Maryland
USA | University of Massachusetts, Amherst
USA | University of Memphis
USA | University of Michigan
USA | University of Minnesota Twin Cities
USA | University of Oregon
USA | University of Southern California
USA | University of Tampa
USA | Valley Academy of Arts and Sciences
USA | Virginia Commonwealth University
Vietnam | HCMC International University

**Comment by tanhengyeow** [comment]
I am a new contributor and would like to work on this :)

**Comment by SamVenkatesh** [comment]
I'm new here and I'd like to start contributing. Can I work on this?

**Comment by hoshikitsunoda** [comment]
Hello, I'm a first-timer. I'd love to work on this one!

**Comment by tshradheya** [comment]
@hoshikitsunoda There is already a PR open for this issue. You could try to look up some other `d.FirstTimers` or an easier `d.Contributors` issue to work on

**Comment by tonystark007** [comment]
I am new and want to contribute. Can I join?

**Comment by Crphang** [comment]
@tonystark007 There's already a PR for this issue. If you want to start contributing to this organisation, you can start by introducing yourself as described in the orientation guide. In general we do not assign issue to people, so you can check whether a PR is already done or whether others have already asked to work on the issue.
