### ISSUE TITLE
Instructor: add session: show number of chars left for session name input 

### ISSUE THREAD

**Issue by wenmogu** [TEAMMATES/teammates#8475]
**Description of feature/enhancement**
Currently when creating a new session, the Session Name input field limits the max number of characters for this input to 38 characters, which is easily reached. The user is prevented from typing more characters inside but there is no warning for it. 

**Justification**
A warning can enhance the user experience.

**Comment by GarrettCarrott** [comment]
Has anyone started working on this issue? If not I don't mind giving a crack at it.

**Comment by whipermr5** [comment]
@GarrettCarrott Take a look at the references above. There is an ongoing PR.
