### ISSUE TITLE
New Contributor Self-Intro : Shashwat Garg

### ISSUE THREAD

**Issue by Shashwat-Garg** [TEAMMATES/teammates#8478]
Link to my Fork: https://github.com/Shashwat-Garg/teammates

Self-intro:
I am Shashwat Garg, CSE student currently in the 2nd year at Indian Institute of Technology Mandi. I aspire to work hard in open source, and I have a good experience in Java, JS, HTML, CSS etc. I wish to use my experience to help solve issues for teammates and make the experience for everyone better. I wish to be a part of this organisation for GSOC 2018. I hope I will stand on your expectations.

A pull request opened by me, that got eventually merged:
issue #7706 :- #8401

**Comment by sukanta-27** [comment]
Hi @Shashwat-Garg 
Welcome to TEAMMATES. As you have already completed your `d.FirstTimers` issue, feel free to grab any of our `d.Contributors` issue to work on. :)
