### ISSUE TITLE
Give a way for students to request submission/results links to be resent

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8490]
It will be helpful if students have a way to request TEAMMATES to resend submission/results links, similar to the 'recover password' features of other apps. It will save instructors and admin the trouble of dealing with students who didn't receive the email, deleted it by mistake, etc.

We'll probably have to protect it using CAPTCHA or something similar to prevent abuse.

**Comment by LuLechuan** [comment]
A work flow for this feature:
1. The student login to his/her account
2. The student requests for resend of submission/results links
3. The student selects the corresponding feedback session. The options of feedback sessions will only show if the student is included and the sessions are open (for submission) or result is already out
4. Request sends to the server.
5. Server looks through the database to find out the particular submission or result
6. Server generates a confirmation email and send to the student
7. The student logins in to his/her email to verify the request
8. Server resend the link

Please correct me if the flow is not desirable.
Will work on this.

**Comment by LuLechuan** [comment]
For safer confirmation, the confirmation email can provide students with a few name options which includes the student's teammates and some random name. The server will only proceed if the student chooses the correct options.

**Comment by tshradheya** [comment]
Just a small query, if the student logs into his/her account, isn't he able to see all his sessions for al courses and edit/view the session and its results?

**Comment by damithc** [comment]
> For safer confirmation, the confirmation email can provide students with a few name options which includes the student's teammates and some random name. The server will only proceed if the student chooses the correct options.

Let's go with just a captcha (or something similar) for now to thwart bots and see if we need further safeguards. Most other apps don't go beyond that. :-) 
It may be useful to throttle requests for the same email (e.g., ignore requests for the same email if there was a similar request in the past hour), but that requires saving data in the database which increases our cost.

**Comment by damithc** [comment]
> Just a small query, if the student logs into his/her account, isn't he able to see all his sessions for allcourses and edit/view the session and its results?

Yes, but most students don't join using their Google account as there is no need to do so.

**Comment by damithc** [comment]
> A work flow for this feature:
> 
> The student login to his/her account
> The student requests for resend of submission/results links
> The student selects the corresponding feedback session. The options of feedback sessions will only show if the student is included and the sessions are open (for submission) or result is already out
> Request sends to the server.
> Server looks through the database to find out the particular submission or result
> Server generates a confirmation email and send to the student
> The student logins in to his/her email to verify the request
> Server resend the link
> Please correct me if the flow is not desirable.
> Will work on this.

This is for students who don't have a TEAMMATES account.
What I'm thinking is,
1. Student goes to 'request for link' page.
2. Student goes through 'I'm not a bot' verification.
3. Student enters email address
4. TEAMMATES sends all links (or we can limit to links related to past 1 month) to the given email address

**Comment by LuLechuan** [comment]
Hi prof, just a clarification. The student still needs to choose the corresponding course and feedback session while the serve needs to check whether the student is inside this feedback session (in this way it is more than the captcha) so that this function will not be abused by the outsiders. Is that correct?

**Comment by damithc** [comment]
> Hi prof, just a clarification. The student still needs to choose the corresponding course and feedback session while the serve needs to check whether the student is inside this feedback session (in this way it is more than the captcha) so that this function will not be abused by the outsiders. Is that correct?

I don't think there is a need for that. Basically, we don't want to expose our own data to the user in any way even if the data we expose is harmless. Besides, it saves us a few database reads.

**Comment by LuLechuan** [comment]
Ok, will start to implement that

**Comment by LuLechuan** [comment]
@damithc Hi prof, just to clarify. Will it be better to send the links of the feedback sessions that include the student (via checking the email he sent) instead of sending all the feedback sessions in the recent one month? In this case he won't be able to view the links to the feedback sessions that he does not participate in, so information is not leak. This would not waste some database as well.

**Comment by damithc** [comment]
> Will it be better to send the links of the feedback sessions that include the student (via checking the email he sent) instead of sending all the feedback sessions in the recent one month?

I meant links for all sessions in the last month that is relevant to the student (based on the given email) Given a link is unique to the student, we can send only the links that belong to that student anyway.

**Comment by LuLechuan** [comment]
Ok sure!

**Comment by madanalogy** [comment]
Am I right to assume that this is no longer an issue considering that #9447 has already been merged?

**Comment by xpdavid** [comment]
Nope. #9610 is still pending.

**Comment by wkurniawan07** [comment]
This is now finished.
