### ISSUE TITLE
Enhancement: Instructor: All Records of Student: Improve UI

### ISSUE THREAD

**Issue by tshradheya** [TEAMMATES/teammates#8492]
**Steps to reproduce to see the following page**

1. Log in as instructor
1. Go to `Students` tab.
1. Click on `Select All` to see all students
1. Click on `All Records` for any particular student

You will notice the following page:

![image](https://user-images.githubusercontent.com/12574756/36419314-7ebb104e-166c-11e8-87c3-ed7362654aa6.png)

**Enhancement:**

- For `More Info` of the student, the heading and the data given by student both are shown in same font size and style. This could be improved by making the `More Info` look different( if possible as a header separated from the box)

**Comment by GarrettCarrott** [comment]
Heya! First time contributor to this Teammates project. Really excited to get started. However, I'm having an issue in regards to adding an instructor on the Dev server. After following the instructions and hitting the "add instructor" button, it seems that nothing happens.  I'm wondering if this is a common issue, or am I just being stupid?  

![image](https://user-images.githubusercontent.com/3783933/36461924-27628968-1675-11e8-88f4-e447bb40ef95.png)

**Comment by tshradheya** [comment]
You possibly must have missed [this part](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#building-javascript-files) while setting up the project. Doing this should resolve the problem.

>  Is there a specific way I can request this issue?
You can post on the issue to take it up considering there is no open PR and no one has already been assigned to it. Since this issue has no PR open , you can take it up if you wish to :)

**Comment by GarrettCarrott** [comment]
Oh, duh! I totally forgot to run npm build run. No wonder it was having trouble finding the js folder. Thank you so much! And I do believe I will take up this issue. Thank you so much for your help. :)

**Comment by GarrettCarrott** [comment]
Ok! I finished working on the issue, now I'm going to be trying to make my commit. It was just a couple lines anyways, but let me know if the issue looks resolved on your end!

**Comment by tshradheya** [comment]
Great. Go ahead and create your PR. Also a attach a screenshot of the part you changed

**Comment by GarrettCarrott** [comment]
Done and done! The pull request has been created.
