### ISSUE TITLE
development.md: As Instructor: Remove `Short Name` from credentials of Instructor in Setting up guide

### ISSUE THREAD

**Issue by tshradheya** [TEAMMATES/teammates#8495]
**Steps to Reprocude** 
1. README.md - > `Contributor Orientation Guide`
2. Click on `Development Guidelines document` of Step 3 of Phase B
3. `ShortName` for user present in step 2 of [document](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#as-instructor)

![image](https://user-images.githubusercontent.com/12574756/36463757-c9d6a404-1706-11e8-916b-a668c11dd992.png)

**Fix**

As we have got rid of `Short Name` for instructor in #8344, the setting up documents need to be updated to fit this and hence remove it from the document as well

P.S. This can be a `d.FirstTimer` issue

**Comment by wkurniawan07** [comment]
Too trivial to be a first timer. @tshradheya just submit a fix yourself.
