### ISSUE TITLE
AccountAttributes: Add test cases for builder

### ISSUE THREAD

**Issue by craaaa** [TEAMMATES/teammates#8496]
We recently added a builder for `AccountAttributes` (#8382) but the added builder class isn't covered by tests (see `StudentProfileAttributesTest` for examples of possible unit tests). We should add tests to ensure that construction works.

**Comment by tshradheya** [comment]
If you aren't working on this already, I can take it up since I had worked on #8382 to add a builder pattern for `AccountAttributes`

**Comment by damithc** [comment]
> If you aren't working on this already, I can take it up since I had worked on #8382 to add a builder pattern for AccountAttributes

Is this suitable for new contributors? If so, you can review the PR when it comes in.

**Comment by tshradheya** [comment]
> Is this suitable for new contributors?

Should be suitable considering they can have a look at tests of other builder patterns used, for e.g. `CourseAttributes` , `StudentProfileAttributes` and get a good idea of what to do.
>  If so, you can review the PR when it comes in.

Sounds good to me  :)

**Comment by damithc** [comment]
@tshradheya can list here the classes that have similar tests for the new contributor to follow?

**Comment by tshradheya** [comment]
Here is a list of few tests done for builder pattern which can be used for reference. 

- [StudentAttributesTest.java](https://github.com/TEAMMATES/teammates/blob/master/src/test/java/teammates/test/cases/datatransfer/StudentAttributesTest.java)
- [StudentProfileAttributesTest.java](https://github.com/TEAMMATES/teammates/blob/master/src/test/java/teammates/test/cases/datatransfer/StudentProfileAttributesTest.java)
- [InstructorAttributesTest.java](https://github.com/TEAMMATES/teammates/blob/master/src/test/java/teammates/test/cases/datatransfer/InstructorAttributesTest.java)
- [FeedbackSessionAttributesTest.java](https://github.com/TEAMMATES/teammates/blob/master/src/test/java/teammates/test/cases/datatransfer/FeedbackSessionAttributesTest.java)
- [CourseAttributesTest.java](https://github.com/TEAMMATES/teammates/blob/master/src/test/java/teammates/test/cases/datatransfer/CourseAttributesTest.java)

Although the tests will be very similar to the ones above. In AccountAttributes, the `.build()` sanitizes all data members, which is something that would need to be taken care of

https://github.com/TEAMMATES/teammates/blob/d55382c0bf2720ee77dc96f5cb7c079884afb915/src/main/java/teammates/common/datatransfer/attributes/AccountAttributes.java#L110-L122

**Comment by lightt77** [comment]
I am a first timer.Can I work on this?

**Comment by tshradheya** [comment]
@lightt77 Yes. Feel free to take this up

**Comment by lightt77** [comment]
@tshradheya Can you please review my PR?(#8551)

**Comment by tshradheya** [comment]
@lightt77 Will do. 
Note: Avoid referencing issue number in commit messages as it spams the thread
