### ISSUE TITLE
StudentFeedbackResultsPage: move additional information about work distribution to lightbox

### ISSUE THREAD

**Issue by craaaa** [TEAMMATES/teammates#8498]
**Description of enhancement**
Move additional information about how to interpret work distribution answers into a lightbox.

**Justification**
At the moment, additional information is hidden in the heading. If we are trying to standardize how additional information is presented (see #8431), we should pick a style and stick to it.
![peek 2018-02-21 14-14](https://user-images.githubusercontent.com/12183503/36465826-fc484752-1711-11e8-88cd-f50fa86cc521.gif)
Two other minor points: the link text can be rephrased if we don't want to switch to a lightbox, perhaps to "more info". In addition, the link to find out more is a very similar colour to the background, so it's a bit hard to spot.

**Comment by damithc** [comment]
I agree that the question heading is not the best place to show additional info, what with the dark blue background and all.

**Comment by craaaa** [comment]
Thoughts on how to proceed:
1. Move information on calculation and use in grading to `studentHelp.jsp` and duplicate them in a modal (accessible by clicking on the info button in screenshot below)
1. Move information on how to interpret the results into tooltips -- shown in gif below
![peek 2018-02-27 20-22](https://user-images.githubusercontent.com/12183503/36728497-e5c95bb2-1bfb-11e8-9600-ed3a9116ba1d.gif)

The two tooltips currently read:
- "My view": Compare 'my view' with 'team's view' to see if your perception is similar to team's perception
- "of me": The average contribution your team members attributed to you, excluding the contribution you attributed to yourself

Thoughts on this approach?

**Comment by damithc** [comment]
> Thoughts on this approach?

Looks like it could work. Can give it a try.

Some caveats about using tooltips (may not apply to this scenario):
* The amount of info (and formatting) we can show in a tool tip is limited. We might run into difficulties if in future we need to show more information.
* When we break up info into bits and distribute them into multiple places, we don't have a place to describe info that concerns multiple concepts. e.g., what's the difference between X and Y?
* If the same tooltip is repeated many times in the page, it increases the page size which increases our costs. e.g., `N/A`. Might not be an issue for student pages, but can be an issue for instructor pages, possibly even doubling the page size. Evan a small increase multiplied by thousands of page loads can add up to something significant over time.

**Comment by whipermr5** [comment]
Also note that tooltips are disabled on touch devices.

**Comment by craaaa** [comment]
Thanks all for your help! @damithc @whipermr5 

> The amount of info (and formatting) we can show in a tool tip is limited. We might run into difficulties if in future we need to show more information.

This is definitely something to consider; I was a bit hesitant about putting the "how to read" information in a tooltip, but @wenmogu mentioned that it would be good to be able to understand the information on the same page as the results.

> Also note that tooltips are disabled on touch devices.

Perhaps we could keep the tooltips and have a more verbose/expanded version of the explanation in the modal? Am open to other suggestions as well, if anyone has any! In the meantime, will post screenshots of the UI in the PR soon.
