### ISSUE TITLE
Instructor: enroll students in course: update link to sample spreadsheet

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8500]
Place to update: An instructor can reach this page by attempting to enroll students in a course
![image](https://user-images.githubusercontent.com/1673303/36475927-4976b926-1737-11e8-95be-99c5ecfb818e.png)

New link to use: `https://docs.google.com/spreadsheets/d/1ZThkUnOW9CSM6a9nDWzchh0UOsPU2s9eyVWb5LG5iMk/edit?usp=sharing`

Reason: the previous spreadsheet has some fake emails. The new one uses `*@example.com` instead. Unable to update the current spreadsheet values because the person who created the spreadsheet is no longer reachable.

Other things to update:
* Change these from `email.com` to `example.com`
![image](https://user-images.githubusercontent.com/1673303/36476446-dfcf4568-1738-11e8-9856-3f0b5db824c7.png)

**Comment by wkurniawan07** [comment]
Tangentially related: why use Google sheets to store this though? Building a small spreadsheet-like interface with [handsontable](https://handsontable.com/) can achieve the same objective, and especially so if we're going to move towards spreadsheet-like interface for enrolling later on.

**Comment by damithc** [comment]
> Tangentially related: why use Google sheets to store this though? Building a small spreadsheet-like interface with handsontable can achieve the same objective, and especially so if we're going to move towards spreadsheet-like interface for enrolling later on.

That works too, and definitely the way to go _after_ we have moved to a spreadsheet-like interface and the dependency is already in. At the moment this seems like the simplest solution.
