### ISSUE TITLE
Enhancement: Submission confirmation email: include submission details

### ISSUE THREAD

**Issue by tshradheya** [TEAMMATES/teammates#8503]
I have picked up this issue from the `Project Ideas`

**Description of feature/enhancement**

Adding more details to the Submission confirmation email for 
e.g. Giving them details if they have attempted all question and have left any unanswered.

*I am open to adding more confirmation details, but not able to think of anymore. Would be helpful if the senior devs could give more details of they had while thinking of this enhancement.*

**Justification**
Students will benefit as they can see the unanswered questions.

**Comment by damithc** [comment]
It can include the answers too. BTW, I remember adding an issue for this sometime back.

**Comment by Crphang** [comment]
I believe this is the one: [#5721](https://github.com/TEAMMATES/teammates/issues/5721)

**Comment by tshradheya** [comment]
Duplicate of #5721. I will close this issue
