### ISSUE TITLE
Student and Instructor View: Incomplete display of messages in various areas

### ISSUE THREAD

**Issue by wenmogu** [TEAMMATES/teammates#8505]
**Environment**

`master` branch at commit 3a330e66

**Steps to reproduce**
![image](https://user-images.githubusercontent.com/28526038/36522328-eec1eadc-17d6-11e8-9820-070ad7f40b26.png)
1. instructor: type an excessively long question title for some session
2. student: edit response for that session 

**Expected behaviour**
The question title should be complete during student edit

**Actual behaviour**
![image](https://user-images.githubusercontent.com/28526038/36522265-9285c91e-17d6-11e8-888c-45a578fca588.png)

**Comment by tanhengyeow** [comment]
Should we limit the word count of the question title or stretch the question title during student edit to fit the excessively long question?

**Comment by damithc** [comment]
> Should we limit the word count of the question title or stretch the question title during student edit to fit the excessively long question?

My guess is this a problem of a word being longer than the page width.  We can limit the question length, but that would be a different issue.

**Comment by wenmogu** [comment]
I feel that limiting the work count is a convenient but it does not tackle the root cause. Personally I think a full display, and then a recommended length for the question would be better.

**Comment by Progyan1997** [comment]
@wenmogu Wrapping up words around span element can do the trick!

**Comment by wenmogu** [comment]
Question update: 
On the instructor side, the long question title also causes some display problem during copying of the questions: 
![capture](https://user-images.githubusercontent.com/28526038/36799253-afe8f588-1ce7-11e8-96c3-7576c95856a3.PNG)

**Comment by nidhi98gupta** [comment]
@wenmogu @damithc Same behavior is observed when adding feedback form instructions.
![aaaaa](https://user-images.githubusercontent.com/24381442/37095291-757c7e20-223b-11e8-826a-c3ddad662998.png)

I guess using word wrap will solve it.

**Comment by damithc** [comment]
@Progyan1997 best not to refer to issue numbers in your commit messages. If you do, Github spams the issue thread with cross references to your commits, as you can see above.

**Comment by Progyan1997** [comment]
@damithc I will keep that in mind. Sorry for the inconvenience.

**Comment by Progyan1997** [comment]
@nidhi98gupta Yes that was my approach. But unfortunately (!) it make some UI test fail. I would be glad if you help me out with it.

**Comment by wenmogu** [comment]
Hi @Progyan1997 pls take note that do not put issue number in your commit message. Else there will be spams as you can see above.

**Comment by jacoblipech** [comment]
Hi can I work on this issue since @Progyan1997 has deleted his branch for his PR.

**Comment by wenmogu** [comment]
Hello @jacoblipech so sorry for the late reply. Yes pls go ahead!
