### ISSUE TITLE
New Contributor Self-Intro : Komal Parmaar

### ISSUE THREAD

**Issue by ParmaarK** [TEAMMATES/teammates#8507]
Link to my Fork: https://github.com/ParmaarK/teammates

Self-intro:
I am Komal Parmaar, Working as a software engineer at Evive Softwares since past 1 year. I aspire to work in open source, and I have a good experience in Java. Wishing to solve as many issues as i can and improve Teammates. Hope to be an integral part of teammates community. 

Pull request done by me:
https://github.com/TEAMMATES/teammates/pull/7651
https://github.com/TEAMMATES/teammates/pull/7863

I have setup my system to run the project. Screenshot attached.
![screen shot 2018-02-22 at 2 56 00 pm](https://user-images.githubusercontent.com/26712793/36530862-381b4646-17e2-11e8-88e6-faa4e4bb2e6a.png)

**Comment by sukanta-27** [comment]
Hi @ParmaarK,
Welcome to TEAMMATES. I see you have already solved two issues before. So, you can start contributing by selecting any of our issues labled `d.Contributors` that does not have a open PR. Looking forward to your contribution.
