### ISSUE TITLE
Instructor: feedback edit page: align tooltip to fit label for rank (recipients) question

### ISSUE THREAD

**Issue by joanneong** [TEAMMATES/teammates#8509]
**Description of feature/enhancement**

As an instructor, creating a rank (recipients) question can produce the following:

![image](https://user-images.githubusercontent.com/24493463/36556203-574529ee-183f-11e8-85f2-6556eac989d3.png)

Here, the tooltip is obviously not aligned with the label which it is referring to. This can be a `d.firstTimers` issue since it should be a relatively simple fix.

**Comment by gaurab4163** [comment]
I would like to work in this issue.

**Comment by joanneong** [comment]
@gaurab4163 Unfortunately as @VirinchiSainath has already opened a pull request for this issue recently, I would recommend that you find another issue to work on. For example, consider [this issue](https://github.com/TEAMMATES/teammates/issues/8528) or search for the `d.FirstTimers` tag :)

**Comment by pmanjunath29** [comment]
My apologies for asking this question, but if a PULL request has already been raised, why does the issue still show as unassigned. I am new to open source contribution, so forgive me if it is a naive question.
Thanks

**Comment by joanneong** [comment]
@pmanjunath29 Please feel free to take this up if you want to - the pull request has been closed due to inactivity :)

**Comment by douihechmaha** [comment]
Hi @joanneong , I am a new contributer and i want to work on this issue if it is possible .thank you :)

**Comment by douihechmaha** [comment]
thank you @sukanta-27. Ok ,i will ask @pmanjunath29 if he can let me fix this issue :) .

**Comment by douihechmaha** [comment]
Hi @sukanta-27 , i have made some modifications locally to fix this issue. And i would like to test but i have not an instructor account yet. Is there any way to test  on dev server without an instructor account ?

If not, I have just sent an 'instructor account' request with my official mail (knowing that i am just a university student).  is it the right way to get the account?

thank you.

**Comment by sukanta-27** [comment]
@douihechmaha 
You don't need to send any requests for instructor account, you can set up an account in Dev server by following [this](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#logging-in-to-a-teammates-instance) process. 

P.S. It is a good idea to read the whole document not just the part I mentioned as it contains a lot of information that are helpful to new contributors.

**Comment by douihechmaha** [comment]
@sukanta-27 ,
I am already following the same steps . I logged in as an administrator, and put credentials for an instructor as shown in the example .but the button 'Add instructor' doesn't work for me: When I click
![screenshot from 2018-04-23 03-14-49](https://user-images.githubusercontent.com/24609502/39102697-7ca4bb38-46a6-11e8-8f22-ac42412ee04f.png)
 nothing happened.

**Comment by sukanta-27** [comment]
@douihechmaha Can you confirm that you ran `npm run build`? If you haven't, can you run the command and then restart the Dev server to check if the problem goes away?

**Comment by douihechmaha** [comment]
@sukanta-27 I did what you told me and the button 'add instructor' works .the instructor is successfully created .
but when I open the join link i have 404 error. and when I tried to log in as this (created) instructor ,it doesn't work . 
![screenshot from 2018-04-23 14-28-07](https://user-images.githubusercontent.com/24609502/39126761-7cdb191e-4703-11e8-880a-705d3bf08069.png)

**Comment by sukanta-27** [comment]
@douihechmaha change `https://teammates-john.appspot.com` part in the join Link's URL to `http://localhost:8080/`

**Comment by whipermr5** [comment]
Or, you can update to the latest master, restart the dev server and simply click on the link. #8801 has taken care of this.

**Comment by douihechmaha** [comment]
thanks @sukanta-27,it works . @whipermr5 ,okey

**Comment by douihechmaha** [comment]
Hi ,I fixed the issue(look at the attached image ).
![screenshot from 2018-04-25 01-39-37](https://user-images.githubusercontent.com/24609502/39219582-b48612aa-482b-11e8-9ceb-fc44cb5d79d7.png)

I just have one problem. when I did modifications on the project* ,these modifications do not appear on the wanted page [http://localhost:8080/page/instructorFeedbackEditPage?courseid=2018Semester2&fsname=FeedBack+for+presentation+1&editsessiondetails=true&user=douihech.maha](url)
 So what I did is to inspect the page and add the modifications there (just to test if they work).
and now I would like to write these modifications in the project and try them.

*PS: I did these steps :
           0- I wrote modifications in the project
           1- run the command : npm run build
           2- run the command : ./gradlew appengineRun
           3- clean compile of the project with gradle
           4- open the internet page in local mode

**Comment by douihechmaha** [comment]
Any help please ? 
if I was not clear I can explain again.

**Comment by douihechmaha** [comment]
Hi,
I would like to explain to you how i figure out the problem :
The problem was in the file called 'feedbackQuestionRankRecipientsEditFormTemplate.html'
In this project you used a spatial organization called Bootstrap grid (which is a 12-column split proportional to the width of the window, we can organize the content of this grid ;we can insert an element, for example, a container of width 6 columns.
but you inserted a container of size 12 columns, which contains a sentence that occupies only half of the container. This explains why the tooltip refers to the end of the text (which is half container)
I realized also that there were html tags <div> that close in the wrong place and I fixed them.
finally,I would like to do a pull request .


I am ready for Pull Request if that is possible .

**Comment by joanneong** [comment]
@douihechmaha If you feel like you are ready to make a pull request, go ahead and open one against teammate's master branch :) Do remember to follow the procedure [here](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr).

**Comment by heisenberg-2505** [comment]
Hi, I have noticed that almost all the first timers issue have open pull requests. I am new to open source and really want to contribute to this project. Is there any way I can help?

**Comment by sukanta-27** [comment]
Hi @heisenberg-2505, Welcome to TEAMMATES!
This issue does not have a open PR. You can start with this if you want.

**Comment by heisenberg-2505** [comment]
Thanks a lot! If I have any other doubts about the project, what is the best way to reach you and the team?

**Comment by sukanta-27** [comment]
>If I have any other doubts about the project, what is the best way to reach you and the team?

@heisenberg-2505 The best way to reach me or any other team member is through the issue tracker itself. In case you have a problem you can create an issue for that.

**Comment by heisenberg-2505** [comment]
Which test do I have to run and get them to pass before moving onto fixing the issue?

![screenshot from 2018-08-13 19-58-52](https://user-images.githubusercontent.com/21108937/44038126-a9a8c9d6-9f33-11e8-8877-68e11641c8f7.png)

**Comment by joanneong** [comment]
@heisenberg-2505 Try to run all tests. You can refer to [this document](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#testing). Personally, I think just running all tests via IntelliJ is the fastest way

**Comment by tshradheya** [comment]
Running `All Tests` might take too long
Run the `CI Test` configuration which should come automatically there in the dropdown of `Run`

**Comment by heisenberg-2505** [comment]
Hi, 
I have fixed the issue and made the code changes for it. So I need to test it before submitting a PR?
If I have to test it, then do I need to test it first in God mode?

**Comment by heisenberg-2505** [comment]
Hi, 
I ran the localTests first with GodMode enabled and then ran them again after disabling the GodMode.
The build was successful both times.
Do I need to run the CI tests as well?

**Comment by sukanta-27** [comment]
@heisenberg-2505 It takes a good amount of time (on average 30 mins) for the ciTests to run, if you want to then you can run ciTests on your system before submitting a PR, but remember that only run GodMode on the tests **that are failing due to the changes you made**. Running GodMode on all the tests may result in some unrelated changes.

**Comment by heisenberg-2505** [comment]
Thanks a lot.
The change in the UI looks like this now.

![changetoui](https://user-images.githubusercontent.com/21108937/44144685-1b824712-a0a6-11e8-9f9e-d93a4af215ca.png)

Should I create a pull request against the master branch of your repository?

**Comment by sukanta-27** [comment]
@heisenberg-2505 No. Create a PR against `TEAMMATES` master branch.

**Comment by heisenberg-2505** [comment]
Hi, the travis ci build is failing.
How to resolve this problem?

**Comment by LiHaoTan** [comment]
To add to @sukanta-27's point.

Generally speaking, the workflow is as follows:
* Make sure your setup is correct by first running all tests locally
* Everytime you submit a PR Travis will run the tests again, and tests that require changes will fail
* By looking at the tests that fail on Travis, determine if you need to make changes to tests or run GodMode.
* However, there are times when you should re-run all tests locally and it will depend on the situation. This will require your personal judgment on the situation to make.

In this case, you can see that many tests on Travis have failed, I suggest it is probably that you re-run all tests locally and ensure they pass before continuing.

**Comment by heisenberg-2505** [comment]
Correct me if I am wrong but what I gather from reading the documentation and your comments is - 
1. First run all the tests with godmode disabled.
2. Then run all the failed tests with godmode enabled.
3. Then run all the failedtests with godmode d disabled.
4. Finally run all the tests to confirm that nothing is broken.

**Comment by LiHaoTan** [comment]
You are roughly correct but it should be more of:
1. Run all the tests with Godmode disabled. (This is a one-time setup you should have done initially to ensure a correct setup such as if your environment matches TEAMMATES' environment)
2. Run the failed tests (that Travis shows) with Godmode enabled.

Not all tests that fail on Travis is due to Godmode so if you know the tests are not failing due to Godmode there is no point running them with Godmode enabled because it won't do anything (Don't worry about this initially, as you gain experience with the project you should be able to identify easily which tests are Godmode related which are not, running tests with Godmode enabled will not cause tests unrelated to Godmode will not have any effect).

3. Re-run the failed tests without GodMode to ensure that they are passing, if they are not passing it is likely that the tests require modification not due to Godmode. In that case, you have to check if you should be modifying the tests for new logic or that your logic is incorrect so the tests are failing.

There is no step 4 but sometimes you need to run all tests locally because of various reasons but not limited to:
* You want to run tests in a different kind of environment that Travis cannot produce.
* Travis is failing to catch an error that should have been caught.

**Comment by heisenberg-2505** [comment]
The problem I am facing is my ci Tests are failing. But when I try to run failedTests it shows the following output.

![failedtests](https://user-images.githubusercontent.com/21108937/44165811-56443400-a0e7-11e8-8a08-21afad06fb0c.png)

**Any help will be appreciated.**

**Comment by LiHaoTan** [comment]
@heisenberg-2505 Did you run CI Tests locally? If you did not, you will not be able to see any failed tests locally. Originally, our build script will call `generateFailedCmd` and show you the command to download the failed tests but it seems like it's broken for some time (looks like we need to fix it).

Also, is there a file `test-output/testng-failed.xml`?

**Comment by heisenberg-2505** [comment]
Yes I ran the CI tests locally.
What should I do now?

**Comment by LiHaoTan** [comment]
> Also, is there a file `test-output/testng-failed.xml`?

Try `./gradlew failedTests --rerun-tasks`.

**Comment by heisenberg-2505** [comment]
No, I could not find any occurrence of the file testng-failed.xml?
Can you please specify the full path, where this file is supposed to be? Just to be sure.

**Comment by heisenberg-2505** [comment]
> **./gradlew failedTests --rerun-tasks**

Ran this command and it produced more or less the same result as before.

![failedsol1](https://user-images.githubusercontent.com/21108937/44215960-6a447000-a191-11e8-9116-24306cc68297.png)

**Comment by LiHaoTan** [comment]
Relative to your project root there should `test-output/testng-failed.xml`. Are you sure there are failing tests when running CI tests? Because it should generate the file `testng-failed.xml` and if you don't have that file there will be no effect when running failed tests.

On a side note, I suggest you use an IDE to run the tests. The command line has its set of advantages but requires you to understand what you are doing.

**Comment by heisenberg-2505** [comment]
> Are you sure there are failing tests when running CI tests?

When running the tests using terminal ci tests are failing.

> On a side note, I suggest you use an IDE to run the tests. 

I will use the IDE to run the tests and get back to you.

Will the file be located at **/teammates/test-output/testing-failed.xml**?

**Comment by heisenberg-2505** [comment]
I ran the tests using IDE, some 40 CI tests failed, but when I ran the failed tests using the IDE it showed that it had no tests to run.
What to do now?

**Comment by LiHaoTan** [comment]
Are you using Eclipse or IntelliJ? If you are using Eclipse I believe it should work correctly.

On IntellIJ however our workflow currently has a missing step where failed tests are not saved, but you can always use IntelliJ's built-in to re-run failed tests (https://www.jetbrains.com/help/idea/rerunning-tests.html).

**Comment by heisenberg-2505** [comment]
Thanks a lot. I am currently using IntelliJ, should I switch to Eclipse?

**Comment by LiHaoTan** [comment]
There is no need to, you can still re-run failed tests? (https://www.jetbrains.com/help/idea/rerunning-tests.html)

**Comment by LiHaoTan** [comment]
> all the tests of this step cannot be run.

I'm afraid I'm not getting what you are saying. If the tests runs and fails it's because of various reasons like mentioned below? You are supposed to figure out why the tests are breaking by walking through the logic. If there is something you don't understand you should give some details otherwise it's hard for anyone to provide input.

> Re-run the failed tests without GodMode to ensure that they are passing, if they are not passing it is likely that the tests require modification not due to Godmode. In that case, you have to check if you should be modifying the tests for new logic or that your logic is incorrect so the tests are failing.

**Comment by heisenberg-2505** [comment]
What I'm not getting is why the tests are failing when I've only changed a small html file?

**Comment by Ayush517** [comment]
Hi, I've seemed to solve the issue on my environment with all tests passing. I've attached the screenshots of the tests. What should I do next?
<img width="1058" alt="e2e tests" src="https://user-images.githubusercontent.com/31190928/53070541-7f65d700-3505-11e9-97e4-c7534ceffbc5.png">
<img width="1059" alt="component tests" src="https://user-images.githubusercontent.com/31190928/53070542-7ffe6d80-3505-11e9-9447-41398c71eff9.png">

**Comment by joanneong** [comment]
Hi @Ayush517 , you can proceed to create a pull request to share your work with the team :) Refer to this [link](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr) for more details.

**Comment by Jellybeano** [comment]
would like to check if this is still a valid issue? since the tooltip no longer seems to exist on the latest version of TEAMMATES.

**Comment by damithc** [comment]
> would like to check if this is still a valid issue? since the tooltip no longer seems to exist on the latest version of TEAMMATES.

This particular tooltip doesn't seem to add much value anyway. If it's no longer there, we can close this issue.
