### ISSUE TITLE
Remove unnecessary @SuppressWarnings("PMD.UnusedPrivateMethod")

### ISSUE THREAD

**Issue by sukanta-27** [TEAMMATES/teammates#8510]
The bug that was returning false positives in PMD has been resolved. 
**See:** https://github.com/pmd/pmd/issues/521

I think we can remove these SuppressWarnings now.

https://github.com/TEAMMATES/teammates/blob/898c5c994bab4258957404762303dce24bca9282/src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java#L498

https://github.com/TEAMMATES/teammates/blob/898c5c994bab4258957404762303dce24bca9282/src/main/java/teammates/logic/core/FeedbackSessionsLogic.java#L2029

**To be done:** After #8511

**Comment by sukanta-27** [comment]
Seems too trivial for a `d.FirstTimers` issue, will send a fix for this.

**Comment by sukanta-27** [comment]
Submitting a PR as this seems too trivial for a FirstTimer issue.

**Comment by wkurniawan07** [comment]
This issue is unnecessary; this can (and should) be done when upgrading to new PMD, whenever that time is.

**Comment by sukanta-27** [comment]
Moved to : #8511
