### ISSUE TITLE
Upgrade to PMD 6.x.x

### ISSUE THREAD

**Issue by sukanta-27** [TEAMMATES/teammates#8511]
**Description of feature/enhancement:**
PMD 6.0.1 released on 21-January-2018. So, we can upgrade to that. 

**Justification**

It is the latest version.

**Existing similar features and their shortcomings:**
One of the shortcomings is the false positive for Private Methods (#8510) 

**As #8512 and this issue is closely related, I think there is no point in keeping two issues. So, for pmd ruleset modification specifics, see #8512**

**Comment by tshradheya** [comment]
Can I work on this and simultaneously also resolve the referenced issues?

**Comment by sukanta-27** [comment]
@tshradheya Thank you for asking first. Acutally I have all the work done. Was working on it for some time which is why discovered the #8512 issues. :sweat_smile:

**Comment by wkurniawan07** [comment]
I'm very aware of the new PMD; despite all its goodness, it's still missing one critical piece: the Eclipse support.

**Comment by sukanta-27** [comment]
@wkurniawan07 Oops! Missed that. :sweat_smile:

**Comment by wkurniawan07** [comment]
Actually we shouldn't let Eclipse be a blocker for this. Until Eclipse has the support for it, we can keep a separate, frozen config based on what we have right now, and use a new config file to move forward with the new PMD.
