### ISSUE TITLE
New contributor self intro : Virinchi Sainath

### ISSUE THREAD

**Issue by VirinchiSainath** [TEAMMATES/teammates#8523]
Link to my fork: https://github.com/VirinchiSainath/teammates

PR: #8522 

I am Virinchi Sainath. I am student in IUPUI, Indianapolis. Found this awesome repo on GSOC website. Hope I will work on this project for GSOC 2018. Thank you for the awesome documentation.

**Comment by sukanta-27** [comment]
Hi @VirinchiSainath 
Welcome to TEAMMATES. I see you have already submitted your first PR, so after the `d.FirstTimers` issue, you can work on `d.Contributors` issues. Looking forward to your contribution.
