### ISSUE TITLE
Fix objectify.LoadException during live server testing

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8525]
V6.3.0
Found these errors in the log while running the test suite against the live server. Possibly some test data in the wrong format?
```
com.googlecode.objectify.LoadException: Error loading FeedbackSession("Fourth Session%IFSubmitUiT.CS2104"): At path 'timeZone': Don't know how to translate UTC+08:00 to a number
```

**Comment by whipermr5** [comment]
I believe this happens only when an instance running the previous release i.e. V6.2.x tries to load data that has been migrated to the new format (V6.3.x is not backwards compatible due to #8455). So it shouldn't happen any more now that all instances are running V6.3.x?

**Comment by damithc** [comment]
I see. Thanks for checking. Closing.
