### ISSUE TITLE
Instructor: search: rename tick box to be more accurate

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8526]
Steps: login as an instructor and go to the search page

Current:
![image](https://user-images.githubusercontent.com/1673303/36627395-f175ec54-197c-11e8-8532-9cebc385cb86.png)

Suggested: this option widens the search to questions, responses, and comments on responses. Let's rename it to `questions, responses, comments on responses`. As it is a long name, we can swap the two options so that `students` option comes first.

**Comment by ChameeraD** [comment]
I am working on this.

**Comment by prakharcipher** [comment]
I'd like to fix this up right now.

**Comment by Bzdeco** [comment]
It seems like it still hasn't been done, I would like to do it as my first contribution in here (and also in open source projects world :smile: )
