### ISSUE TITLE
Instructor: view results: make the explanation of the view more informative

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8528]
Current:
![image](https://user-images.githubusercontent.com/1673303/36627919-fdf8f22a-1984-11e8-8d8c-717b5054e337.png)

Suggestion:
1. Use an ascii arrow `→` rather than `>` (both in this view, and in the drop down menu)
2. Give a more precise tooltip based on the value e.g., `Group responses by giver, then by recipient, and then by question`

**Comment by gaurab4163** [comment]
I would like to work on this issue, if it is still open andunassigned.

**Comment by heniam1** [comment]
hey new contributor her. How can i work on this?

**Comment by SamithDB** [comment]
@damithc Is this still open? I like to work on this.

**Comment by joanneong** [comment]
@gaurab4163 Are you still working on this? If not either @heniam1 or @SamithDB will start to work on this!

**Comment by J-Eisen** [comment]
@joanneong @damithc Guess I'm adding on to the queue. If @gaurab4163, @heniam1, or @SamithDB haven't taken it on, I'd be happy to work on it!

**Comment by joanneong** [comment]
@J-Eisen please go ahead, it seems like there hasn't been progress on this yet :P

**Comment by Clarke92** [comment]
Hi there, is this issue still available, because i would really love to fix one for you guys!

**Comment by joanneong** [comment]
@J-Eisen Are you still working on this?

**Comment by J-Eisen** [comment]
Yep! Should be submitting the PR today.

**Comment by J-Eisen** [comment]
Hey @joanneong. I'm clearly missing something here. Build is still failing from a missing html update. Looks like InstructorFeedbackEditPageUiTest is failing since the instructorFeedbackResultsAjaxByQuestion isn't matching with the updated html files. I've run ciTests with godmode on both through eclipse and terminal but the files don't seem to update. Maybe I'm not implementing godmode correctly? Or could I have missed something in one of the java files?

**Comment by KING-SID** [comment]
Hey is this issue still open? If so, I would like to take it up! 

_P.s I am working towards GSoC 2019 with TEAMMATES_

**Comment by saranyadmdrn** [comment]
is this issue still open for contribution?

**Comment by g-lilian** [comment]
Hi, first time contributor here. May I know how to access the page with the mouseover tooltip? In the demo session, I only see the dropdown list. I'm logged in as an admin.
![Screenshot_1](https://user-images.githubusercontent.com/50647023/101122888-81435080-362e-11eb-9342-1279791465c1.jpg)

**Comment by madanalogy** [comment]
> Hi, first time contributor here. May I know how to access the page with the mouseover tooltip? In the demo session, I only see the dropdown list. I'm logged in as an admin.

That should be the correct page, the UI has changed since the issue was first filed. The issue is still relevant however, as you can tell from the dropdown menu
