### ISSUE TITLE
Instructor: remind particular students: give a 'send me a copy' tick box

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8529]
Current:
![image](https://user-images.githubusercontent.com/1673303/36628726-711697aa-1988-11e8-8208-217aefe132d6.png)

Suggestion: Give a 'send me a copy' option which can be ticked by default. If the user unticks it, we should not send a copy to the instructor.

**Comment by tshradheya** [comment]
I would like to take this up

**Comment by damithc** [comment]
> I would like to take this up
@tshradheya FYI, I think @bqnguyen94 is working on a related issue (about resending links for results), and there are a few other issues that goes with this one. You can decide among yourselves whether to divide the work and peer review each other other or leave one person to do the whole lot.

**Comment by tshradheya** [comment]
I investigated this and #8531.

When reminding **only particular students**, then no instructor is notified that the students have received an email. However, if **remind all students** option is done then all instructors are notified.

I have written code to solve #8531 so that instead of all instructors of the course, only the instructor requesting for reminding is sent the notification.


Coming to this issue, since no instructor is anyway sent the email during `remind particular students`, it doesn't make sense to add a special checkbox. Instead, we can just send to the instructor who has requested for the particular students to be reminded.

Prof @damithc , your views?

**Comment by damithc** [comment]
> Coming to this issue, since no instructor is any way sent the email during remind particular students, it doesn't make sense to add a special checkbox. Instead, we can just send to the one instructor who has requested for the particular students to be reminded.

yes let's do that.

**Comment by whipermr5** [comment]
> Coming to this issue, since no instructor is any way sent the email during remind particular students, it doesn't make sense to add a special checkbox. Instead, we can just send to the one instructor who has requested for the particular students to be reminded.

Now with #8535, the instructor does get the email when reminding particular students. Shouldn't this issue stand? This issue is about making that email optional, right?

**Comment by tshradheya** [comment]
@whipermr5 Yes, with #8535, whether instructor is reminding all or particular students, the requesting instructor will get notified.

>This issue is about making that email optional, right?

Yeah, the reason why I mentioned #8535 fixes this issue is because Prof @damithc 
 agreed to this https://github.com/TEAMMATES/teammates/issues/8529#issuecomment-368277769
and I felt it then fixes this issue cause we no longer need to add a checkbox but we plan to notify requesting no matter what (unlike before when no one was notified)

If the checkbox is still a requirement I can remove the part of fixing this issue and keep this issue open

**Comment by whipermr5** [comment]
I still feel this issue shouldn't be tagged as closed from #8535. It can be manually closed if we decide that we no longer need it.

**Comment by tshradheya** [comment]
>It can be manually closed if we decide that we no longer need it.

@whipermr5 Agreed.

**Comment by itishrishikesh** [comment]
Hi,

Can I work on this?

If Yes - Is there a document for email troubleshooting, I created a test account with SendGrid & have set parameters in `build.properties` accordingly.

Thank you!

**Comment by jianhandev** [comment]
@damithc do we still want this 'send me a copy' option? If yes, I'll let @itishrishikesh take this issue.

**Comment by damithc** [comment]
> @damithc do we still want this 'send me a copy' option? If yes, I'll let @itishrishikesh take this issue.

Yes, I think we can proceed with this if easy to do (the payback is low). However, we can ditch it if it requires extensive changes, such as changes to the backend API.

**Comment by jianhandev** [comment]
> I created a test account with SendGrid & have set parameters in `build.properties` accordingly but I am not receiving emails

The dev server is using an empty email service - that might be the reason. Try testing it out on [staging  environment](https://github.com/TEAMMATES/teammates-ops/blob/master/platform-guide.md#deploying-to-a-staging-server)?

**Comment by wkurniawan07** [comment]
> extensive changes, such as changes to the backend API.

Changing backend API does not necessarily mean it's going to be "extensive".

> Try testing it out on [staging environment](https://github.com/TEAMMATES/teammates-ops/blob/master/platform-guide.md#deploying-to-a-staging-server)?

Not necessary; you can always modify the code such that the dev server uses the email service you wanted. But at the same time, you don't really need to test with actual email service; if you can make sure that the email service is being called (look at the logs written, write tests to confirm this), then it already counts as the job done.

**Comment by jianhandev** [comment]
@itishrishikesh as explained by @wkurniawan07, you can also test your implementation without setting up staging environment. Minimally, you should write tests to confirm that the email service is called.

**Comment by xyliew25** [comment]
Hi all. As a first-timer and also assigned by @wkurniawan07, I would like to take up this issue.

Currently, I have two proposed solutions as follows:
1. Modify `FeedbackSessionRespondentRemindRequest` to include an additional boolean property, e.g. `sendMeACopy`, and do a check on this value during assignment of `instructorToNotify` in `FeedbackSessionRemindParticularUsersEmailWorkerAction`.
2. Include the requesting instructor in the existing `usersToRemind` property of `FeedbackSessionRespondentRemindRequest` and remove the logic of generating feedback session reminder emails for `instructorToNotify`.

Personally, I prefer the first solution, although most probably more changes are required as there will be a change in the backend API, I feel it is a cleaner solution.

Any views?

**Comment by wkurniawan07** [comment]
2 is not going to work. The email sent to notified instructor is not the same as the email sent to original recipients.

**Comment by samuelfangjw** [comment]
> Personally, I prefer the first solution, although most probably more changes are required as there will be a change in the backend API, I feel it is a cleaner solution.

I would go with solution 1. `sendMeACopy` is not the best name for this boolean field though, something along the lines of `sendCopyToInstructor` might be better?
