### ISSUE TITLE
Instructor: remind students: collapse the two options into one

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8530]
Current:

![image](https://user-images.githubusercontent.com/1673303/36628846-1f851c26-1989-11e8-868d-743478d2ad6f.png)

![image](https://user-images.githubusercontent.com/1673303/36628829-e11d5dea-1988-11e8-8845-5be131f6938f.png)

Suggestion:
In the modal opened up by `Remind particular students` menu option, give these tick boxes on top:
- [ ] `all submitted`
- [ ] `all yet to submit`

Ticking/unticking these tick boxes should select/unselect all relevant recipients in the list below.

After that, remove the two menu options in the button and convert it from a menu-button to a regular button, clicking of which should open the modal dialog updated above. That way, although we now have only one button, it gives the user more flexibility that before.

**Comment by bqnguyen94** [comment]
I'm working on this

**Comment by bqnguyen94** [comment]
@damithc is it expected for the remind particular students modal to have checkboxes of all unsubmitted students to be checked when the modal finishes loading? I found the following code, but it's not working:
https://github.com/TEAMMATES/teammates/blob/222bd21b0e33ae68a215229df134ba345a22cce7/src/main/webapp/dev/js/common/remindModal.js#L5-L16

**Comment by damithc** [comment]
> @damithc is it expected for the remind particular students modal to have checkboxes of all unsubmitted students to be checked when the modal finishes loading? I found the following code, but it's not working:

I don't have a memory of such a feature. In any case, we don't need such a thing in future. Can get rid of the code if not used.

**Comment by tshradheya** [comment]
@bqnguyen94 Don't get rid of that code. 

That code is used here: ( As mentioned in comment of the code `// if clicked button is on no-response panel, then populate check boxes otherwise not `

![image](https://user-images.githubusercontent.com/12574756/36767890-866f32b4-1c77-11e8-9162-bb843ded1863.png)

On clicking `Remind all` in `Results` page if Instructor, It automatically checks the checkbox of those who have not submitted yet

![image](https://user-images.githubusercontent.com/12574756/36767924-b60cc32e-1c77-11e8-9b8e-cd47884ebdce.png)

**Comment by jacoblipech** [comment]
@damithc As we are doing migration, referencing to #8823 which is an issue of later date. I will simply follow the same layout but collapsing the two options into one?

**Comment by damithc** [comment]
> @damithc As we are doing migration, referencing to #8823 which is an issue of later date. I will simply follow the same layout but collapsing the two options into one?

Sure.

> Currently, simply click on remind allows the default option of reminding all students without needing to look at the list in the modal. Not sure too sure if this is more popular or looking at the modal with the student info is more popular?

I don't mind keeping it the current way too, especially because users are familiar with it. In that case, rename the option to `Remind all yet to submit`
