### ISSUE TITLE
Instructor: remind students: send email copies only to requesting instructor

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8531]
![image](https://user-images.githubusercontent.com/1673303/36628846-1f851c26-1989-11e8-868d-743478d2ad6f.png)

Current: when an instructor send a reminder to a student(s), a copy of the email is sent to all instructors of the course.

Suggested: send the email to only the instructor who is sending the reminder, not all instructors of the course.

Reason: sending copies to all instructors a bit 'spamy'.

**Comment by tshradheya** [comment]
Working on this which is related to #8529.
