### ISSUE TITLE
New Contributor Self Intro : Kartik Setia

### ISSUE THREAD

**Issue by kartset** [TEAMMATES/teammates#8534]
Link to my fork: [https://github.com/kartset/teammates](https://github.com/kartset/teammates)

Hi, I am Kartik Setia. I'm currently doing my engineering in Computer Science from Amrita School Of Engineering, Kerala, India. I want to contribute to Teammates. I've tried to set up the development environment but I am having some trouble while executing the command ./gradlew appengineStart

![screenshot from 2018-02-24 21-16-07](https://user-images.githubusercontent.com/30878021/36632154-b129cac2-19a8-11e8-91b4-2da9903931f8.png)

**Comment by tshradheya** [comment]
It shows `address already in use`.

Maybe try running `gradlew appengineStop` and then try again?

**Comment by kartset** [comment]
Thanks for the advice. It works! 

![screenshot from 2018-02-24 21-16-07](https://user-images.githubusercontent.com/30878021/36632280-c6adf24a-19aa-11e8-8dbf-6432bbbd21a9.png)

![screenshot from 2018-02-24 21-35-41](https://user-images.githubusercontent.com/30878021/36632278-c164e56e-19aa-11e8-96f3-c417d3b9758b.png)

**Comment by kartset** [comment]
Thanks for the advice. It works!!

![screenshot from 2018-02-24 21-35-41](https://user-images.githubusercontent.com/30878021/36632290-04f1978c-19ab-11e8-9f17-ece0b7f9b30f.png)
