### ISSUE TITLE
Instructor: view results: fix typo in the tooltip of 'Expand Students' button

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8536]
There's a typo in Tool Tip of Expand-Collapse Button in  instructorResultsFeedbackPage when sorted by Giver > Recipient > Question as shown below.
![typo1](https://user-images.githubusercontent.com/24381442/36071733-735ac15c-0f39-11e8-82cb-d75f41291b45.png)

Reported by @nidhi98gupta 

Should be `Expand or collapse`

**Comment by OlhaHn** [comment]
I will take it

**Comment by prakharcipher** [comment]
I'd like to fix this. Kindly guide me through the source file for this. Thanks.

**Comment by OlhaHn** [comment]
@prakharcipher you can take it

**Comment by nidhi98gupta** [comment]
@damithc @prakharcipher I have already solved the issue in #8442.

**Comment by yatri1609** [comment]
Is this still open or has it been already solved in issue #8442? @damithc

**Comment by tshradheya** [comment]
@yatri1609 Now that you have already attempted a `d.FirstTimer` issue, you should move on to `d.Contributors` issues to work on more challenging stuff

**Comment by yatri1609** [comment]
@tshradheya  Okay thank you :-)

**Comment by xpdavid** [comment]
The issue still exist as #8442 is not solved.

**Comment by PranavBhatia** [comment]
I am working on this issue, can you please tell me the file in which this typo exists?

**Comment by laurensdegilde** [comment]
Is this issue still open? Happy to taken it.

**Comment by Jesse-Penber** [comment]
I would like to take this! Submitting pull request in a bit.

**Comment by Jesse-Penber** [comment]
I attempted to find the source HTML for this to fix it but was unable to find the specified "Expand Students" button text and hover text. It is not in instructorFeedbackResultsSortGiverRecipientQuestion.html as specified; I've gone through all of the instructorFeedbackResultsSort HTML without finding it.

**Comment by Rahman2600** [comment]
Can I work on this?

**Comment by joncros** [comment]
Rahman2600, I already have an open pull request that should solve this. It is just waiting for code review.
