### ISSUE TITLE
New contributor self intro Ujjwal Gupta

### ISSUE THREAD

**Issue by gupta-ujjwal** [TEAMMATES/teammates#8538]
**Link to my fork** : [https://github.com/gupta-ujjwal/teammates](url)

I modified the contact section of the UI slightly.  

**Before**:
![screenshot from 2018-02-22 23-50-42](https://user-images.githubusercontent.com/22260630/36639330-b4c72444-1a30-11e8-8c10-8bcdee437b77.png)

**After**
![screenshot from 2018-02-25 13-10-17](https://user-images.githubusercontent.com/22260630/36639327-a14c847c-1a30-11e8-8036-622f4738e87b.png)

I am Ujjwal Gupta ,a second year student, pursuing B tech with major in CS . I want to contribute in teammates in every possible way that i can. I have experience with web and app development. And i also have an ample practical experience in JAVA.

Looking forward to contribute and learn.

**Comment by Crphang** [comment]
Hi @gupta-ujjwal welcome to TEAMMATES. You can start contributing by taking up a `d.FirstTimers` issue, before moving onto `d.Contributors` issues.

**Comment by gupta-ujjwal** [comment]
Ok @Crphang
