### ISSUE TITLE
Instructor: home page: give menu option to edit a course

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8541]
Current:
![image](https://user-images.githubusercontent.com/1673303/36649483-78f46f3c-1ad8-11e8-9bef-4a9bebab76fd.png)

Suggested: Give an `Edit` menu option. It can behave same as `Instructors` → `View/Edit` menu option (because the resulting page has a panel for editing course name).

**Comment by gaurav122197** [comment]
@damithc Sir, I will be working on this issue.

**Comment by dabbler011** [comment]
@damithc I am taking up this issue.

**Comment by gaurav122197** [comment]
@dabbler011 I was engrossed in my sessional exams that's why I was unable to submit a PR. I started doing work on the issue, if fail to submit by the weekend you could take up the issue.
