### ISSUE TITLE
Unable to add instructor

### ISSUE THREAD

**Issue by gupta-ujjwal** [TEAMMATES/teammates#8544]
I am new to open source projects . I am unable to add an instructor on my dev server . 
The button **Add instructor ** is not active.
![screenshot from 2018-02-26 19-59-18](https://user-images.githubusercontent.com/22260630/36676327-631e8586-1b31-11e8-83ae-71d409ad9929.png)

I guess this issue is due to the js files . Can anyone help me on how to fix it.

**Comment by sukanta-27** [comment]
Did you run `npm run build` while setting up? Go through the [development](https://github.com/sukanta-27/teammates/blob/master/docs/development.md) document once more.

**Comment by gupta-ujjwal** [comment]
I am sorry i was not able to reply earlier due to some reasons. I did run npm run build and also went through the development document again. But still the problem is there.

**Comment by whipermr5** [comment]
Restart the server after `npm run build`.

**Comment by gupta-ujjwal** [comment]
Thanks @whipermr5 . This time it worked.
