### ISSUE TITLE
New contributor self intro: Sun Shengran

### ISSUE THREAD

**Issue by dalessr** [TEAMMATES/teammates#8549]
Link to my fork: https://github.com/dalessr/teammates

The change I did for UI:
![teammates_ui](https://user-images.githubusercontent.com/22449685/36714901-e65f0f36-1bce-11e8-9e3b-97b929cb43a7.png)

My name is Sun Shengran, Information Security Year 2 student from NUS. I would like to contribute in TEAMMATES because this is an awesome project and I am quite interested. I am currently applying for the summer internship for this project.

Thank you and look forward to making more contributions.

**Comment by sukanta-27** [comment]
Hi @dalessr 
Welcome to TEAMMATES. You can start contributing by picking any of our `d.FirstTimers` issues, before moving on to slightly more difficult `d.Contributors` issues. Looking forward to your contribution.

**Comment by dalessr** [comment]
Okay. Thank you @sukanta-27
