### ISSUE TITLE
Content not allowed in prolog

### ISSUE THREAD

**Issue by davel37** [TEAMMATES/teammates#8552]
- **Operating System**: Windows (x64)
- **JDK Version**: 1.8.0.144
- **Eclipse**: Oxygen

**What I was trying to do / What I need help with**
After running fine, and passing tests in both Eclipse and from the cmd, I'm now getting "content not allowed in prolog" errors, when trying to run the CiTests.

**Attempts to resolve the problem**
 Two days trying :-) google, and stackoverflow not providing much insight into this particular error.
![screenshot 193](https://user-images.githubusercontent.com/18369575/36727255-e23fbd7c-1bbc-11e8-9e16-4d3832d787ad.png)

**Comment by sukanta-27** [comment]
@davel37 Can give some more information? Like what were you working on? What are the exact steps you took to resolve this? (So that we can emit those solutions)

**Comment by sukanta-27** [comment]
Can check that you have not accidentally modified any of the xml files (like `appengine-web.xml`)?

[This](https://stackoverflow.com/questions/3030903/content-is-not-allowed-in-prolog-when-parsing-perfectly-valid-xml-on-gae) thread has some insight on this error. And to quote it: 

>Another possible scenario that causes this is when anything comes before the XML document type declaration. i.e you might have something like this in the buffer:
`helloworld<?xml version="1.0" encoding="utf-8"?>`  
or even a space or special character.

**Comment by wkurniawan07** [comment]
@davel37 if you're using MinGW, you may want to run `./gradlew` instead of the batch file version. See if that gets rid of the error.

**Comment by davel37** [comment]
Thanks guys for those tips, no luck yet. Actually, I wasn't making any changes at the time the errors appeared so thats made it a little more confusing. Actually my Teammates in Eclipse is running about 5 errors now, all surrounding the import of packages  (imports cannot be resolved) like:

com.google.appengine.tools.remoteapi.RemoteApiInstaller;
com.google.appengine.tools.development.testing.LocalServiceTestHelper;
com.google.appengine.tools.development.testing.LocalDatastoreServiceTestConfig;
com.google.appengine.api.log.dev.LocalLogService;

I'm assuming these packages should be in my appengine-api-1.0-sdk-1.9.62.jar? but I'm not seeing them there (I've dowloaded it again too).  Apologies if this is a trival issue to fix that I`m missing, I've been away from Teammates for a while so maybe my brain is a bit rusty still :-)

**Comment by wkurniawan07** [comment]
@davel37 if you run `locale` from that shell, what is the output?

**Comment by davel37** [comment]
Thanks for the suggestion. I had checked the settings alright to make sure I had switched to UTF-8 in eclipse as per the documentation.

locale:

LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=

**Comment by sukanta-27** [comment]
@davel37 Any updates? Did you solve this issue?

**Comment by davel37** [comment]
@sukanta-27 Was studying for an interview so had to leave it for a few days.  Working again :-) .Thanks for your tips/suggestions, still not 100% sure what caused it, but a corrupted Eclipse workspace is a possibility.

**Comment by davel37** [comment]
f
