### ISSUE TITLE
New Contributor self Intro : Shaharyar shamshi

### ISSUE THREAD

**Issue by shaharyar-shamshi** [TEAMMATES/teammates#8555]
Link to my fork -- https://github.com/shaharyarshamshi/teammates
I am shaharyar shamshi 3rd year undergraduate student at Indian Institute of Information technology ,Una
I know it is too late to introduce  myself to teammates as I am working with teammates for more than 2 months . And Have 1 successful merge #8119 And Currently working on pull request #8533 (which is ongoing ) and #8208 (which is to be reviewed by @wkurniawan07  Sir) .
instead of working parallely on many issues I concentrated on 1 issue at the time and created pull request for that (i.e. #8208  )  so that I could get more knowledge about coding style , how different components interact with each other in working of a platform and what level of perfection teammates require which would help in giving perfect work while solving more issues parallely in future 
I am dedicated to be part of teammates till  my undergraduation completes which is nearly more than 1 and a half  year.

As this year I am aiming for internship if I would be selected for Gsoc under the banner of Teammates or selected for summer internship program of Teammates this would be added benefit for me And I promise to deliver perfect work as working under one pull request at a time made me lot more fimilar with codebase of Teammates .

**Comment by craaaa** [comment]
Hi @shaharyar-shamshi, welcome (officially) to TEAMMATES!
Do continue working on `d.Contributors` issues. Looking forward to your contribution.
