### ISSUE TITLE
New Contributor self Intro - Olha Hnatik

### ISSUE THREAD

**Issue by OlhaHn** [TEAMMATES/teammates#8556]
Hi!

My name is Olha and I'm a third student student of Jagiellonian University.

Link to my fork: https://github.com/OlhaHn/teammates
Changes I have made: 
![changes](https://user-images.githubusercontent.com/18572964/36747634-ce095988-1bf5-11e8-8583-7e2650c52aa6.png)

I added a tooltip for the button "Remind all"
Link to the changes: https://github.com/OlhaHn/teammates/tree/master

**Comment by craaaa** [comment]
Hi @OlhaHn, welcome to TEAMMATES!
You can start contributing by picking any of our `d.FirstTimers` issues, before moving on to slightly more difficult `d.Contributors` issues. Looking forward to your contribution.

**Comment by damithc** [comment]
@OlhaHn the tool tip you added seems to be useful. If you want you can create an issue and submit a PR for if.

**Comment by OlhaHn** [comment]
@damithc 
Hi, I tried to do it but I got "Travis CI build failed" because of changes in HTML. 
https://github.com/TEAMMATES/teammates/pull/8559

How can I fix such things?

**Comment by sukanta-27** [comment]
@OlhaHn You will have to run [GodMode](https://github.com/sukanta-27/teammates/blob/master/docs/godmode.md).
