### ISSUE TITLE
Feedback Path: Predefined Combinations: Disable number field when not selected

### ISSUE THREAD

**Issue by sukanta-27** [TEAMMATES/teammates#8573]
**Environment:**
`master` branch

**Steps to reproduce:**
- Login as instructor
- create a new session or edit a existing one
- click on `Add New Question`
- Select any option (e.g- essay)
- Under `Feedback Path` selected `Other Predefined Combinations...`
- Set any feedback path (e.g like in the screenshot below)
![screenshot 394](https://user-images.githubusercontent.com/10681755/36890825-4cbb8b2c-1df7-11e8-8af3-3addc89f862e.png)
- The number field in `The maximum number of *` is editable even when the radio button is not selected. (It is to be noted that setting the value without selecting the radio button doesn't save the changes)

**Expected behaviour:** The field should be disabled and only get enabled if the radio button is selected.

**Actual behaviour:** The field is enabled irrespective of which radio button is selected.

**Comment by sukanta-27** [comment]
@damithc Sir, can take a look at it? I guess this can be a `d.Contributors` issue.

**Comment by OlhaHn** [comment]
@sukanta-27 I have already solved that, so I would like to create a PR for that.

**Comment by sukanta-27** [comment]
@OlhaHn Go ahead. :+1:

**Comment by pPris** [comment]
Hi, I tried exploring this but I was unable to reproduce this. The issue seems to be fixed? (The mouse also turns into a 🚫 icon when you try to edit the number field.)

![image](https://user-images.githubusercontent.com/49683462/123138863-1bae9880-d488-11eb-8405-3ae207237771.png)

**Comment by damithc** [comment]
Yes, seems to be fixed. Thanks for checking @pPris
