### ISSUE TITLE
Review datastore backup mechanism

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#8583]
The current backup cron job uses the Cloud Datastore Admin module, which is set to be decommissioned. Let's investigate the new managed export and import feature: https://cloudplatform.googleblog.com/2018/02/fully-managed-export-and-import-with-Cloud-Datastore-now-generally-available.html

**Comment by wkurniawan07** [comment]
Closing; issue moved to `teammates-ops`.
