### ISSUE TITLE
New Contributor self Intro - Labirinto

### ISSUE THREAD

**Issue by Labirinto** [TEAMMATES/teammates#8588]
Link to my fork: https://github.com/Labirinto/teammates

I changed the background color of "Sort By:"  tag in the instructor's menu just to check, if everything works correctly.
![screenshot from 2018-03-04 12-30-04](https://user-images.githubusercontent.com/10048366/36945165-301567e0-1faa-11e8-85ef-d4113229a2a2.png)

Hi. My name is Lev. I'm a third-year student of computer science at Jagiellonian University. And I only begin my journey in open source projects.

**Comment by sukanta-27** [comment]
Hi @Labirinto, Welcome to TEAMMATES. You can start contributing by taking one of our `d.FirstTimers` issues before moving on to `d.Contributors` issues. Also remember to go through our [process](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md) guideline.
