### ISSUE TITLE
Student Profile: add a 'Upload/Edit Photo' tooltip

### ISSUE THREAD

**Issue by Labirinto** [TEAMMATES/teammates#8589]
This tooltip will show size and formats of a photo. It would be easier for a student to look for available photos to submit.

There is a similar tooltip (shown in the screenshot below), but it also can be changed. For example, the new tooltip will look like this 'Upload a profile picture. Max size: 5MB .png .jpg'.
![profile picture](https://user-images.githubusercontent.com/10048366/36945517-c4b4760c-1faf-11e8-8bef-e8212609e7d6.png)

**Comment by Labirinto** [comment]
If this issue looks legit, I will work on it

**Comment by damithc** [comment]
> If this issue looks legit, I will work on it

Go ahead @Labirinto

**Comment by Labirinto** [comment]
@damithc 
While running ./gradlew lint  I get the following exception:
"Could not determine the dependencies of task ':compileTestJava'.
> Could not create service of type AnnotationProcessorDetector using JavaGradleScopeServices.createAnnotationProcessorDetector()."

Can you please help me, what could it be?

**Comment by sukanta-27** [comment]
@Labirinto 
Did you go through the [setting-up](https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md) document while setting up the project?

**Comment by Labirinto** [comment]
@sukanta-27 yes. I did it again, now 'npm install' command gives the following output: 
"
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
"

**Comment by sukanta-27** [comment]
@wkurniawan07 @damithc @whipermr5 

Guess there is a regression in the npm itself.
For reference : https://github.com/npm/npm/issues/19877

**Comment by sukanta-27** [comment]
@Labirinto 
What is your output for `npm -v` and `node -v`?

**Comment by Labirinto** [comment]
@sukanta-27  npm -v: 5.6.0
node -v: v8.9.4

**Comment by sukanta-27** [comment]
@Labirinto Yup. There is a regression in npm itself. 
Did you run `npm install` before or are you just running it after I pointed you to the setting up document?

**Comment by Labirinto** [comment]
@sukanta-27 . I did, and then it worked. I've just fixed this npm problem with this command:
"npm install --save-dev eslint eslint-config-airbnb eslint-plugin-jsx-a11y eslint-plugin-import eslint-plugin-react"
Then "./gradlew createConfigs"

But "./gradlew appengineStart" still gives the following output:
"
Could not determine the dependencies of task ':compileJava'.
> Could not create service of type AnnotationProcessorDetector using JavaGradleScopeServices.createAnnotationProcessorDetector().
"

**Comment by sukanta-27** [comment]
@Labirinto Can create an issue with [Help](https://github.com/TEAMMATES/teammates/blob/master/.github/template-helpRequest.md) template, so that these we can have some more information? Also provide the stackTrace?

**Comment by theIOTman** [comment]
Hello, I followed **Contributor Orientation Guide** step by step. But in phase B, I can not make it has fewer than 5 failing test cases. Tha failing test cases is 6.
The message from IntelliJ is:

> Test ignored.

> Test ignored.

> Test ignored.

> Test ignored.

> Mar 08, 2018 9:35:23 AM > com.google.appengine.api.datastore.dev.LocalDatastoreServicecleanupActiveServices
> INFO: scheduler shutting down.

Any help ?

**Comment by tshradheya** [comment]
Not a problem, 5 is just a tentative number.

Try re-running only those 6 test cases and see if few of them pass.
Did you try running `gradlew ciTests` ? It reruns the failed tests up to 4 times and after that, all tests should pass

**Comment by gthd** [comment]
I would like to work on this issue.

**Comment by sukanta-27** [comment]
@gthd  there is already an open PR for this issue, you can find another `d.FirstTimers` issue to work on.

**Comment by gthd** [comment]
ok sorry I didn't notice.

**Comment by jimmy51997** [comment]
@sukanta-27 ....I have finished working on this issue, I have run all the tests and they ran successfully.....the next step is to try pushing the changes to the master branch, right?

**Comment by sukanta-27** [comment]
@jimmy51997  Yes. :+1:

**Comment by jimmy51997** [comment]
when i try to push the changes to the main repo...it says "unable to access 'https://github.com/TEAMMATES/teammates.git/': The requested URL returned error: 403".
![push](https://user-images.githubusercontent.com/24703162/39930086-5de95f18-5557-11e8-8616-f890c4a36a28.png)

Do i need to issue a pull request first??

@sukanta-27

**Comment by Crphang** [comment]
@jimmy51997 you can take a look at our process guide https://github.com/TEAMMATES/teammates/blob/master/docs/process.md

**Comment by jimmy51997** [comment]
yes @Crphang , that is what I am following now....it says to push changes to remote in point 4 of step 3. That's what I am trying to do.

**Comment by Crphang** [comment]
@jimmy51997 It seems like you're not pushing to your fork.

**Comment by jimmy51997** [comment]
I should have my own version of project on my git-hub account....and I should be pushing there?? Is that what you mean?? @Crphang

**Comment by YaroslavGnatyuk** [comment]
Could you help me? I found in a guide how to run a single test. But I want to run a single test in debugging. How can I do it?
