### ISSUE TITLE
'Session closing soon' reminder: ensure emails sent

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8595]
I have encountered a few cases where the 'session closing' alert was not sent (based on sendgrid logs and app engine logs) but our datastore states it was sent.
![image](https://user-images.githubusercontent.com/1673303/37012158-2d9107f6-212e-11e8-974d-bb8245dd2ca6.png)

**Comment by damithc** [comment]
Happened in one of my own courses too. Need to look through the code to see if there is a hole in the logic. Also, need to improve logging so that it is easy to see in the logs when alerts are sent out for a session.

**Comment by whipermr5** [comment]
Was looking through the logic for this method, which is run whenever a session is updated:
https://github.com/TEAMMATES/teammates/blob/49386feafec7ca2cb6fdeca32ad1112d4fda962f/src/main/java/teammates/logic/core/FeedbackSessionsLogic.java#L2355-L2380

`sentClosingEmail` can legitimately be set to true even if the closing emails were not sent, e.g. if the session end time was brought forward to before the current time. That is expected. However, seems like it can also be set to true if a closed session (for which the closed email was already sent) is later re-opened to a time more than 24 hours after the current time. For such a session, only the session closed email will be sent, not the session closing email - not sure if that behaviour is correct?

**Comment by whipermr5** [comment]
If such a session is saved again, however, the flag gets set to false - very strange behaviour (but the logic has existed for a long time now).

**Comment by damithc** [comment]
1. We wanted to avoid sending 'session closing' email if a 'session opening' email for the same session was sent within last 24 hours, to reduce alert fatigue.
2. If a session open/close time was updated, in some cases we need to send the alerts again. 

May be the code for above logic has some holes? As the 'session closing' email is not critical to users, it is possible that it worked only partially for a long time without being detected.

**Comment by damithc** [comment]
I'm still encountering this problem. The 'session closing' email was not sent out for one of my sessions today.

**Comment by wkurniawan07** [comment]
- No occurrence in recent times
- #10901 makes this far harder to trace
