### ISSUE TITLE
InstructorFeedbackSession: Make validation for submission times stricter

### ISSUE THREAD

**Issue by joanneong** [TEAMMATES/teammates#8597]
**Environment**

`master` branch at commit 49386fe

**Steps to reproduce**
This can be reproduced either when adding a new feedback session, or when editing an existing feedback session. However, the error is the same for both scenarios, and affects both the submission start time and end time.

1. Go to the form which allows instructors to specify the submission start time and submission end time.

For adding a new feedback session:

<img width="1280" alt="screen shot 2018-03-06 at 10 23 29 pm" src="https://user-images.githubusercontent.com/24493463/37037398-2a86ba88-218d-11e8-9981-12851bb69d76.png">

For editing an existing feedback session:

<img width="1275" alt="screen shot 2018-03-06 at 10 23 20 pm" src="https://user-images.githubusercontent.com/24493463/37037427-381d3168-218d-11e8-9870-4451e1d97853.png">

2. Click on the `Submission opening time`/ `Submission closing time` input box. Choose a date from the date picker that appears.

3. Click on the `Submission opening time`/ `Submission closing time` input box again, and type some random digits/characters in the input box.

4. Create feedback session/ save the session details.

5. Session is created/ updated successfully.

The erroneous details persist and are displayed even if you access another page before re-accessing the session.

For example:

<img width="1277" alt="screen shot 2018-03-06 at 10 30 15 pm" src="https://user-images.githubusercontent.com/24493463/37037783-042c3d94-218e-11e8-9599-dd364dbeea89.png">

**Expected behaviour**

It does not make sense for a time field to be displayed as something like `Thu, 08 Mar, 2018029sfhlh40`. Instead, either (i) the input box should only accept values via the date picker, (ii) the form should display an error message when the erroneous dates are parsed, or (iii) the system should automatically trim and remove the additional numbers/strings and display only the correct date.

**Comment by whipermr5** [comment]
Hmm, we need to make `InstructorFeedbackAbstractAction#extractFeedbackSessionData` throw `InvalidParametersException` too. Right now invalid dates are simply treated as `null` when creating the `FeedbackSessionAttributes` from user input. Looks like @darrenwee's point was very valid: https://github.com/TEAMMATES/teammates/pull/8428#discussion_r167438664

**Comment by whipermr5** [comment]
> (iii) the system should automatically trim and remove the additional numbers/strings and display only the correct date

I think it does; the frontend is just not updating as it uses AJAX. A refresh should show a valid date.

**Comment by joanneong** [comment]
@whipermr5 Hmm I tested it out again and recorded it:

![strange behaviour](https://user-images.githubusercontent.com/24493463/37050032-bd77590e-21ad-11e8-82d5-22919c6055dd.gif)

It seems like changes were made to the times but....

**Comment by damithc** [comment]
Block submission if the date in the text box does not correspond to a valid date?

**Comment by wkurniawan07** [comment]
No longer valid
