### ISSUE TITLE
Instructor: Edit session : Distribute (Options) question : Points per option button stays hidden

### ISSUE THREAD

**Issue by sukanta-27** [TEAMMATES/teammates#8603]
**Environment**
`master` branch

**Steps to reproduce**
- Login as Instructor
- Create/Edit a sessioin
- Add a `Distribute points (among recipients) question` and cancel it
- Add a `Distribute points (among options) question` 

**Expected behaviour:**
The UI for `Distribute points (among options) question` should be consistent like this : 
![screenshot 404](https://user-images.githubusercontent.com/10681755/37064843-7247ec26-2196-11e8-81ca-e337b117b40c.png)

**Actual behaviour:**
![screenshot 403](https://user-images.githubusercontent.com/10681755/37064854-803623de-2196-11e8-8564-943765724eba.png)

**Cause:** When we add the among recipient question we hide `constSumOption_Option` and show `constSumOption_Recipient` but while adding among options question we do not show `constSumOption_Option` again, so it stays hidden. (The same problem as #8463)

**Note:** I unintentionally reported this bug in https://github.com/TEAMMATES/teammates/issues/8463#issuecomment-366458152, but apparently all of us concentrated on the options only and ignored this.

**Comment by Vivek1012** [comment]
i am working on it!

**Comment by sukanta-27** [comment]
@Vivek1012  I already have an open PR for it.

**Comment by Vivek1012** [comment]
Thanks for response! 
i leave it then :)
