### ISSUE TITLE
Student: submit responses: tick email confirmation option if the form is empty

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8606]
Current: the email confirmation tick box is unticked by default.
![image](https://user-images.githubusercontent.com/1673303/37069345-f041971a-21ed-11e8-92fc-4f52a859d979.png)

Suggested: if the form is empty at loading, we can assume it is a first time submission, and tick the tickbox by default. 

Reason: it is ok to send the confirmation by default to first-time submission. That email will serve as proof of submission for students who claimed they submitted.

**Comment by tanhengyeow** [comment]
I'll like to attempt this issue :smile:

**Comment by damithc** [comment]
> I'll like to attempt this issue

Go ahead 👍

**Comment by shaharyar-shamshi** [comment]
@damithc Sir I don't think that we need to add test case here if that is the case then just changing one file is enough to produce the require change ?

**Comment by damithc** [comment]
> @damithc Sir I don't think that we need to add test case here if that is the case then just changing one file is enough to produce the require change ? i.e. to make checkbox for sending mail default checked in this file

It is always good to have a test to cover every feature. How deeply we will test a feature depends on cost-benefit-risk trade-offs.
