### ISSUE TITLE
Help Request: CI Test Procedure

### ISSUE THREAD

**Issue by Progyan1997** [TEAMMATES/teammates#8610]
- **Commit SHA:** 4819e48 (Ref: Pull Request #8516 )
- **Operating System:** CentOS 7
- **JDK Version:** OpenJDK 0.8
- **Google Cloud SDK Version:** Any
- **Eclipse / IntelliJ Version (if applicable):**
- **Firefox / Chrome Version (if applicable):**

**What I was trying to do / What I need help with**
I am trying to understand the CI test procedure. I am new to Java Server development, though have good experience with language. In my last commit, I tried to make some UI changes and that resulted into build failure.

**Attempts to resolve the problem**
I have gone through few files in [src/test/java/teammates/test/pageobjects](https://github.com/TEAMMATES/teammates/tree/master/src/test/java/teammates/test/pageobjects) but still have not got a good idea of how it being done.

**Comment by bqnguyen94** [comment]
`src/test/java/teammates/test/pageobjects` literally contains "page objects" - objects that represent respective pages, but only for testing.
To clarify, what kind of UI changes are you trying to make and what are the steps you took? And what do you mean by "resulted into build failure"?

**Comment by Progyan1997** [comment]
@bqnguyen94 I simply added a new class to exiting HTML element, and hence failing UI tests. I need to update test pages for the same as well to work it out. But I still not having a clear picture of which files need to be modified.

**Comment by nidhi98gupta** [comment]
Did you try running failed tests in God Mode to update expected html files?

**Comment by bqnguyen94** [comment]
I see. For UI tests, we rely on pre-existing HTML files to verify the content of the pages being tested. These pre-existing HTML files are in `src/test/resources/pages/`. A typical test (`src/test/java/teammates/test/cases/browsertests/*UiTest.java`) uses `src/test/java/teammates/test/pageobjects/AppPage.java::verifyHtmlMainContent` to compare the resulting page with a model HTML file for discrepancies. Any time a change to UI is made, the relevant model HTML files need to be updated. We use `God Mode` for this (see [here](https://github.com/TEAMMATES/teammates/blob/master/docs/godmode.md)).
Personally, I would run `All tests`, then repeatedly run the `Failed tests` suite a few times, now that only the relevant tests are failing (hopefully), I would then run them again with `God Mode`. Afterwards, it is important to turn off `God Mode` and check the resulting HTML files.

**Comment by Progyan1997** [comment]
@bqnguyen94 I think I'm now getting an idea. Can you specify a bit more one the process.
What I got so far:
* Make the UI change
* Run CI (?) Test
* Make sure only that particular UI test fails
* Enable God Mode
* Run CI (?) Test

**Comment by bqnguyen94** [comment]
Well depends on what changes you make their maybe more than 1 test that fails, but generally that's what I would do. Afterward though still need to check and see no unintended changes were made by `God Mode`.
