### ISSUE TITLE
Instructor: Edit Session: MSQ: Address the case where a number field is left blank

### ISSUE THREAD

**Issue by sukanta-27** [TEAMMATES/teammates#8611]
- **Environment**: `master` branch at 49386feafec7ca2cb6fdeca32ad1112d4fda962f

**Steps to reproduce:**
- Login as Instructor
- Create/Edit a session
- Add a MSQ question
- Check either max/min number of options box
- Delete the value in number field
- Save the changes

**Expected behaviour:** There should be a status message asking the user to insert a value

**Actual behaviour:** An error page when trying to save the changes
![screenshot 386](https://user-images.githubusercontent.com/10681755/37126289-4094c1ae-2268-11e8-9e67-4590fdce235b.png)

**Additional info**

The error is caused by `java.lang.NumberFormatException: For input string: ""`, so we should take this into account and add a status message as IMO a user is more likely to leave a field blank than entering 0.

**Comment by LiHaoTan** [comment]
Related: https://github.com/TEAMMATES/teammates/issues/8320#issuecomment-359150575

@Crphang I believe you will be resolving this right?

**Comment by Crphang** [comment]
I've resolved this for rank options/recipients and added a backend validation layer for those. But that is to ensure that a new feature works correctly. I think @sukanta-27 you can work on this for msq questions and reference #8320 for the similar backend validations and tests that are added.

Having a warning popup works as @Haozhe321 suggested works, but like it can be consistent to show a flash message in this function `checkFeedbackQuestion` of `InstructorFeedbackEdit.js`. The function has been used to show flash messages for various fields like `questionTitle`.

![image](https://user-images.githubusercontent.com/4986717/37244244-d1730bae-24c0-11e8-807b-eeef346ef558.png)

**Comment by sukanta-27** [comment]
>I think @sukanta-27 you can work on this for msq questions and change the issue title accordingly and reference #8320 for the similar backend validations and tests that are added.

Sounds good to me.

**Comment by sukanta-27** [comment]
I will start working on it after some of my current PRs are done, and as GSoC application period starts from tomorrow, it may take some days for me to get to it. In the mean time if someone wants to grab this issue, they are free to do so. Just let me know beforehand.

**Comment by sukanta-27** [comment]
Taking this up.
