### ISSUE TITLE
New contributor self intro Mauricio Solis

### ISSUE THREAD

**Issue by mau0727** [TEAMMATES/teammates#8614]
https://github.com/mau0727/teammates.git

![screen shot 2018-03-08 at 9 29 58 pm](https://user-images.githubusercontent.com/36412466/37187427-3b4d2d02-2318-11e8-92bf-b634aa878403.png)

Mauricio Solis 

Hello, 

I am a Costa Rican that recently graduated from school.
I was looking for a project to get involved with open source code and get  real-world experience.
and I got caught in love with this project because of the professionalism and the organization of it.
It makes you want to follow the steps because it actually invites new developers to get closer to open source.
I hope I can be useful here, and I can wait to start contributing 

Thank you

**Comment by shaharyar-shamshi** [comment]
@mau0727  welcome to the Teammates we are looking forward for contribution from you I would suggest you _to start with  d.firsttimer issue to get an idea of codebase then move to d.contributor issue to which is relatively tougher than d.firsttimer issue
