### ISSUE TITLE
New contributor self intro Luan N. Pham

### ISSUE THREAD

**Issue by theIOTman** [TEAMMATES/teammates#8615]
**A:** [Link to my app](https://teammates-theiotman.appspot.com)

**B:** [Link to my fork](https://github.com/theIOTman/teammates)

**C:** For my UI change, I simply added one hello line into index page. They change red when a mouse is hovered over:
**Before:**
![image](https://user-images.githubusercontent.com/27758502/37204437-6511c2d2-23c3-11e8-924e-44b3f810e5a0.png)

**After:**
![image](https://user-images.githubusercontent.com/27758502/37204471-7a7f2da8-23c3-11e8-9b10-375dbf0e3336.png)

**D:** 
**Intro:** @luanpham107
Hello everyone, my full mane is Luan N. Pham. Currently, I'm a software engineer working with the embedded system. While researching about IOT (internet of thing) I found that web technology is very interested. I think that contributes to an opensource project help me and another learn a lot. I love to write clean code and have a deep understanding of any line of code.

**Issue with staging server**:
Although my google account is authenticated with GEA I still can not use it to register it for an instructor account. Please, response! 
Nice to meet you!
![image](https://user-images.githubusercontent.com/27758502/37205120-246272c4-23c6-11e8-93ab-19a5fa3ebc00.png)

**Comment by tran-tien-dat** [comment]
Hi @LuanPham107, Welcome to TEAMMATES. We look forward to your contributions.

>  Although my google account is authenticated with GEA I still can not use it to register it for an instructor account. Please, response!

Can you provide more details, i.e. what exact steps did you do?

**Comment by whipermr5** [comment]
The steps for creating an instructor account can be found in the [development.md](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#logging-in-to-a-teammates-instance) document.

**Comment by LuanPham107** [comment]
I have followed this document [deploying-to-a-staging-server](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#deploying-to-a-staging-server).

1. Here is what were modified inside build.properties (I modified 3 lines of code: app.url, app.gcs.bucketname, app.crashreport.email)
```
app.url=https\://teammates-theiotman.appspot.com

app.gcs.bucketname=teammates-theiotman.appspot.com

app.backdoor.key=samplekey

app.encryption.key=5360b12f6a07af7be93437d215f72fca

app.persistence.checkduration=4000

app.crashreport.email = luan.sys@gmail.com

app.student.motd.url = test-student-motd.html

app.email.senderemail = Admin@teammates-john.appspotmail.com

app.email.sendername = TEAMMATES Admin

app.email.replyto = teammates@comp.nus.edu.sg

app.email.service = javamail

app.sendgrid.apikey =

app.mailgun.apikey =

app.mailgun.domainname =

app.mailjet.apikey =

app.mailjet.secretkey =
```

2. Here is what were modified inside src/main/webapp/WEB-INF/appengine-web.xml
`    <application>teammates-theiotman</application>`

**Comment by tran-tien-dat** [comment]
@LuanPham107 Do you mean that you could not log in as an Administrator, or do you mean that you could log in but could not create an instructor account? Can you give a more exact description for this sentence of yours:

> I still can not use it to register it for an instructor account

as well as the context of the screenshot

![](https://user-images.githubusercontent.com/27758502/37205120-246272c4-23c6-11e8-93ab-19a5fa3ebc00.png)

E.g. what's the URL you are trying to access, what you are trying to log in as, what have you done before that which makes you think it should work, etc.

**Comment by LuanPham107** [comment]
I tried to log in at [https://teammates-theiotman.appspot.com/admin/adminHomePage](https://teammates-theiotman.appspot.com/admin/adminHomePage) and the message returned as I mentioned above. But everything is ok with this local address: `https:localhost:8080/admin/adminHomePage.` I can log in using test@example.com, create instructor, courses,.. 
Could please tell me why ? I'm very new to web technology.

**Comment by tshradheya** [comment]
To log into `https://teammates-theiotman.appspot.com/admin/adminHomePage` you need to use the google account with which you made the google app on GCP.

**Comment by whipermr5** [comment]
After creating an instructor, you need to use the join link before the instructor can login, but change the hostname part of the link (details in the doc I linked).

**Comment by tran-tien-dat** [comment]
@LuanPham107 So it means that you couldn't log in as an Administrator. Do you have multiple account and the account that you are currently logged in is not the one you used to deploy teammates (the `theiotman` account)?

**Comment by LuanPham107** [comment]
Thank to @tshradheya @tran-tien-dat @whipermr5 ,
You are right, I removed my 2nd account and using **theiotman** account. Problem is resolved.
