### ISSUE TITLE
Tests fail on the dev server

### ISSUE THREAD

**Issue by gthd** [TEAMMATES/teammates#8619]
**Operating System: Windows 10

- JDK Version:1.8
- Eclipse / IntelliJ Version (if applicable): IntelliJ IDEA
- Firefox / Chrome Version (where applicable): Firefox 46.0

**

**What I was trying to do / What I need help with**
I get 19 tests failed when running the CI tests, although Local Tests pass. I have searched the previous issues and read the #7650, so I understand that the problem is related to npm run build. However, I have deleted the node modules folder from my root, I have run again npm install and then npm run build and the problem remains. Below you can find screenshots of the problems:

![issue](https://user-images.githubusercontent.com/15031826/37247508-d1a5e0d4-24c4-11e8-8b19-668cc13122af.PNG)
![issue2](https://user-images.githubusercontent.com/15031826/37247514-d7a165bc-24c4-11e8-96ec-c70de809b4b6.PNG)

**Comment by tanhengyeow** [comment]
Have you tried stopping and starting your dev server after running `npm install` and `npm run build` ?

**Comment by gthd** [comment]
Thank you very much !!
I stopped and run again the dev server and the problem was solved. 
Unfortunately, I have another problem now: 
![issue](https://user-images.githubusercontent.com/15031826/37252873-fe4b0322-2531-11e8-9531-789cc9f51795.PNG)
I am using firefox 46.0. 
Yesterday when running the tests I didn't have this problem .. 
I have done some research, read the https://support.mozilla.org/el/kb/firefox-cant-load-websites-other-browsers-can and followed all steps specified but I still can't fix the error.

**Comment by gthd** [comment]
Problem solved. In the test.properties file, the default for mozilla firefox path is C:\\Program Files (x86)\\Mozilla Firefox 12\\firefox.exe and for the firefox I am using the path is C:\\Program Files\\Mozilla Firefox\\firefox.exe. Actually in the C:\\Program Files (x86)\\Mozilla Firefox there is only a folder for the plugins

**Comment by gthd** [comment]
Can you please explain to me the following error:
![issue](https://user-images.githubusercontent.com/15031826/37254654-5300115c-2549-11e8-98d7-11a31b6c2ed0.PNG)
What I understand is that teammates.test.pageobjects.AppPage$1@6a1df4b6 could not be located after 15 sec and therefore it raised an org.openqa.selenium.TimeoutException. But what are some possible reasons for not being able to locate it ?

**Comment by Crphang** [comment]
@gthd Is the error deterministic? Like does it happen everytime you run it? Try running a single test `./gradlew test -Dtest.single=MashupPageUiTest`.

**Comment by gthd** [comment]
Hi Crphang, I run the gradlew.bat test -Dtest.single=MashupPageUiTest. The result is the following
![issue4](https://user-images.githubusercontent.com/15031826/37254777-44d84cf0-254b-11e8-8fd6-c18efca2bfb4.PNG)

**Comment by Crphang** [comment]
Seems like the test is passing. It might be because of other reasons that the ui test fails; ui-tests could be unstable, especially when you run parallel ciTests. The failure might not necessarily be due to your code.
