### ISSUE TITLE
Have standardized code for hashCode and equals

### ISSUE THREAD

**Issue by dutta14** [TEAMMATES/teammates#8621]
**Environment**: 
All

**Description of feature/enhancement**
Use` Objects.hash` for `hashCode()` calculation, and `Objects.equals` for `equals()` calculation.

**Justification**

Developers: provide a standardized way to achieve hashing.

**Existing similar features and their shortcomings**

For example, in `teammates.common.datatransfer.attributes.FeedbackQuestionAttributes`, the `hashCode()` method is currently:

```
@Override
public int hashCode() {
    final int prime = 31;
    int result = 1;

    result = prime * result + (courseId == null ? 0 : courseId.hashCode());

    result = prime * result + (creatorEmail == null ? 0 : creatorEmail.hashCode());

    result = prime * result + (feedbackSessionName == null ? 0 : feedbackSessionName.hashCode());

    result = prime * result + (giverType == null ? 0 : giverType.hashCode());

    result = prime * result + numberOfEntitiesToGiveFeedbackTo;

    result = prime * result + questionNumber;

    result = prime * result + (questionMetaData == null ? 0 : questionMetaData.hashCode());

    result = prime * result + (questionDescription == null ? 0 : questionDescription.hashCode());

    result = prime * result + (questionType == null ? 0 : questionType.hashCode());

    result = prime * result + (recipientType == null ? 0 : recipientType.hashCode());

    result = prime * result + (showGiverNameTo == null ? 0 : showGiverNameTo.hashCode());

    result = prime * result + (showRecipientNameTo == null ? 0 : showRecipientNameTo.hashCode());

    result = prime * result + (showResponsesTo == null ? 0 : showResponsesTo.hashCode());

    return result;
}
```

can be changed to:
```
@Override
public int hashCode() {
     return Objects.hash(courseId, creatorEmail, feedbackSessionName, giverType, numberOfEntitiesToGiveFeedbackTo,
                questionNumber, questionMetaData, questionDescription, questionType, recipientType, showGiverNameTo,
                showRecipientNameTo, showResponsesTo);
}
```

Similarly, the `equals()` method is:
```
@Override
public boolean equals(Object obj) {
    if (this == obj) {
        return true;
    }

    if (obj == null) {
        return false;
    }

    if (getClass() != obj.getClass()) {
        return false;
    }

    FeedbackQuestionAttributes other = (FeedbackQuestionAttributes) obj;

    if (courseId == null) {
        if (other.courseId != null) {
            return false;
        }
    } else if (!courseId.equals(other.courseId)) {
        return false;
    }

  ...

    if (showResponsesTo == null) {
        if (other.showResponsesTo != null) {
            return false;
        }
    } else if (!showResponsesTo.equals(other.showResponsesTo)) {
        return false;
    }

    return true;
}
```

can be changed to:
```
@Override
public boolean equals(Object obj) {
    if (this == obj) {
        return true;
    }

    if (obj == null) {
        return false;
    }

    if (getClass() != obj.getClass()) {
        return false;
    }

    FeedbackQuestionAttributes other = (FeedbackQuestionAttributes) obj;

    return Objects.equals(this.courseId, other.courseId) &&
            Objects.equals(this.creatorEmail, other.creatorEmail) && ...
            Objects.equals(this.showResponsesTo, other.showResponsesTo);
```

This makes it more readable, and does not change the functionality of the code.

**Comment by wkurniawan07** [comment]
@dutta14 Can give example of places where this can be applied?

**Comment by dutta14** [comment]
@wkurniawan07 
In `teammates.common.util.Version`:
```
@Override
public int hashCode() {
    return toString().hashCode();
}
```
can be changed to:
```    
@Override
public int hashCode() {
    return Objects.hash(originalRepresentation, major, minor, patch, isRcVersion);
}
```

Similar changes to be made in `FeedbackQuestionAttributes` and `InstructorPrivileges`.

**Comment by dutta14** [comment]
Note: This change does not affect the current behavior because internally, `Objects.hash` does the same operation with the same prime number (31).

**Comment by dutta14** [comment]
@wkurniawan07, edited my issue comment.

**Comment by LiHaoTan** [comment]
@dutta14 if we were to want to improve this, we should probably be using [AutoValue](https://github.com/google/auto/tree/master/value).

**Comment by dutta14** [comment]
I personally don't prefer AutoValue because it implements its own method for hashCode() instead of using the Java built-in, and also creates getters that are not consistent with Java naming. (E.g. it produces method xyz() instead of getXyz()).

**Comment by LiHaoTan** [comment]
@dutta14 I would appreciate if you spend a little more thought evaluating solutions :).

> I personally don't prefer AutoValue because it implements its own method for hashCode() instead of using the Java built-in

Have you wondered why they don't use the standard library for implementation? For control? For flexibility? Are there grounds for using an alternative solution from the standard library if it is well-maintained and easier to use?

And is this the right to focus on implementation details or should we focus on the contract?

Also: https://github.com/google/auto/blob/master/value/userguide/why.md

> and also creates getters that are not consistent with Java naming

Are getters in Java necessarily a good thing? C# has properties, Kotlin added data classes and Java has JavaBeans which functions like properties in some places.

And the obligatory: https://github.com/google/auto/blob/master/value/userguide/howto.md#-use-or-not-use-javabeans-style-name-prefixes

---
And have you understood the rationale behind `AutoValue`?

> Value classes are extremely common in Java projects. These are classes for which you want to treat any two instances with suitably equal field values as interchangeable. That's right: we're talking about those classes where you wind up implementing equals, hashCode and toString in a bloated, repetitive, formulaic yet error-prone fashion.

> Writing these methods the first time is not too bad, with the aid of a few helper methods and IDE templates. But once written they continue to burden reviewers, editors and future readers. Their wide expanses of boilerplate sharply decrease the signal-to-noise ratio of your code... and they love to harbor hard-to-spot bugs.

https://github.com/google/auto/blob/master/value/README.md

**Comment by dutta14** [comment]
@LiHaoTan, on reading some more, it does seem to be a nice option. They prefer to use their own `hashCode()` which is a modification of Java's in-built, the modification being using a larger prime number and XORing the values.

I agree getters are not always a good option, however in the current code, `hashCode()` and `equals()` are implemented in only 3 classes: `FeedbackQuestionAttributes`, `InstructorPrivileges` and `Version`, and each class already implements its getters, so I guess the philosophy we need to decide is how pervasive this change should be if it is made. I've used [lombok](https://projectlombok.org/features/all) in the past which does something similar, but allows us to selectively choose which features we want to use (constructors, getters/setters, hashCode/equals etc.) To cleanup the code, one could argue that we remove all constructors, getters, setters, hashCode, equals, as well as use `NonNull` on method parameters to remove the initial if-null-then-do-nothing code.

If in future scope, we would have more value classes, then I guess it is a good idea to use `AutoValue` or `lombok` for this project as a dependency.

**Comment by LiHaoTan** [comment]
Lombok has its own set of caveats (lots of magic).

And the fact that we only have `hashCode` and `equals` in 3 classes does not mean that we only have 3 value classes.

If we want to take it that there are only 3 classes where the implementation must change, then the benefit is minimal, we have to write this code once and then swap over to `AutoValue` in the future? That's just wasted time for the implementer and reviewers.

> To cleanup the code, one could argue that we remove all constructors, getters, setters, hashCode, equals, as well as use NonNull on method parameters to remove the initial if-null-then-do-nothing code.

This is going too far (too much work unless it's something you want to do). The biggest problem with value classes are namely just `equals`, `hashCode` and `toString`

**Comment by dutta14** [comment]
@LiHaoTan, So I started with the issue, to see if it works properly or not. But unfortunately, my build fails because the auto-generated methods cannot be found during the tests. Not sure how to proceed.

**Comment by wkurniawan07** [comment]
@dutta14 I guess you'd have noticed by now that simply injecting Lombok will not work.

**Comment by dutta14** [comment]
@wkurniawan07 So I made the changes, not using lombok, currently used the standard Java rules to implement proper methods for equals and hashCode.

**Comment by wkurniawan07** [comment]
Closing as this does not have that much value-add and there is no bandwidth to attend to this.
