### ISSUE TITLE
New contributor self intro Georgios Theodorou

### ISSUE THREAD

**Issue by gthd** [TEAMMATES/teammates#8624]
My fork: https://github.com/gthd/teammates
My change: 
I put in italics the e-mail.
![change](https://user-images.githubusercontent.com/15031826/37255834-b9831ea4-255a-11e8-8fb6-00710a8e8779.PNG) 

Hi! My name is George and I am a final year student of management science and technology at Athens University of Economics and Business, Greece. This is the first time I engage with open source software, but I have found it very intriguing !!

**Comment by Crphang** [comment]
@gthd welcome to Teammates. You can pick up a `d.firstTimer` issue before moving on to `d.contributor` issue.
