### ISSUE TITLE
Help Request: IntelliJ IDEA 'Cannot resolve symbol' error for standart Java classes

### ISSUE THREAD

**Issue by Artyom-Ganev** [TEAMMATES/teammates#8625]
I succefully imported project using this instruction https://github.com/TEAMMATES/teammates/blob/master/docs/ide-setup.md#intellij-idea 
but have had 'Cannot resolve symbol' errors for standart Java classes imports. Caches Invalidation didn't help.
![2018-03-11 23-01-50](https://user-images.githubusercontent.com/13161268/37257916-a4b21dec-2580-11e8-9ab7-a969d23619dd.png)

**Comment by Haozhe321** [comment]
@Artyom-Ganev 
Try this: click on "gradle" on the right side of your intellij toolbar. After which, click on the refresh symbol. 
![image](https://user-images.githubusercontent.com/26651556/37323142-bb2b4318-26bc-11e8-9ed3-d36de7fd98ae.png)

Let us know if it works for you!

**Comment by Artyom-Ganev** [comment]
It didn't help. Are the settings correct?
![2018-03-17 15-06-32](https://user-images.githubusercontent.com/13161268/37555188-d2b7b936-29f4-11e8-9b82-93da761d153c.png)

**Comment by Artyom-Ganev** [comment]
I tried to run tests and got Error:java: Fatal Error: Unable to find package java.lang in classpath or bootclasspath
![2018-03-17 15-41-52](https://user-images.githubusercontent.com/13161268/37555539-c471a1ac-29f9-11e8-88dd-dcb274021168.png)

Soulution is here
https://stackoverflow.com/questions/3049433/intellij-gives-fatal-error-unable-to-find-package-java-lang-in-classpath-or-boo

> Somehow the JDK language jars were removed from the classpath. All I had to do was reapply the JSDK home path.
> 
> Goto: File -> Project Structure -> Platform Settings -> SDKs Re-apply the JSDK home path.
> 
> Doing this added about 15 jars to the classpath. Apparently these are important for compiling.

**Comment by Haozhe321** [comment]
Did you try the solution in the stackoverflow answer? Still doesn't work?

**Comment by Artyom-Ganev** [comment]
I tried and it works
