### ISSUE TITLE
Instructor: remind particular students: show sorted student list

### ISSUE THREAD

**Issue by bqnguyen94** [TEAMMATES/teammates#8630]
**Description of feature/enhancement**

Current:
<img width="1289" alt="screen shot 2018-03-12 at 5 12 02 pm" src="https://user-images.githubusercontent.com/11720085/37274931-d57bd092-2618-11e8-9e4b-8e47998cb78f.png">
<img width="885" alt="screen shot 2018-03-12 at 5 12 15 pm" src="https://user-images.githubusercontent.com/11720085/37275243-96f3d814-2619-11e8-9990-c3cd8c6ce0a2.png">

Suggestion:
In the modal opened up by `Remind particular students` menu option, by default show student list sorted by `Team` > `Student Name` for each of `not responded` and `responded` categories.

**Justification**

Sorted student list helps instructors to locate specific students faster.

**Comment by lightt77** [comment]
Hi, I would like to work on this issue..

**Comment by bqnguyen94** [comment]
@lightt77 sure go ahead! We don't require contributors to ask for permission to take up issues :)

**Comment by lightt77** [comment]
okay :)
