### ISSUE TITLE
Instructor: Edit session: Rubric question: add front-end validation for empty weights

### ISSUE THREAD

**Issue by sukanta-27** [TEAMMATES/teammates#8631]
- **Environment**: `master` branch

**Description of feature/enhancement:** Currently in `Rubric` questions, if we select `weights` and leave a weight cell blank, then we get the following error.
![screenshot 441](https://user-images.githubusercontent.com/10681755/37286344-915b84da-25f9-11e8-9a14-a96ecbc56416.png)

Though this is what is expected, but this validation is done in `FeedbackRubricQuestionDetails` with the method `validateQuestionDetails()`.
https://github.com/TEAMMATES/teammates/blob/4416b4db657cdf6993fd298d51cc7e3a7d630c66/src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java#L990-L993
This leads to a problem that when we click `save changes`, if any field is invalid we lose all the changes made in the question. We can move/add this validation to `checkFeedbackQuestion` of `InstructorFeedbackEdit.js` and use a flash message to check if the input of the weights are valid or not, like we do for question title (What @Crphang suggested for MSQ questions in https://github.com/TEAMMATES/teammates/issues/8611#issuecomment-372041507).

**Justification:** As we know, setting up a rubric question takes more effort than any other question type, losing all the changes due to a empty field may lead to unsatisfactory user experience.

**Existing similar features and their shortcomings:** Addressed in the description.

**Comment by sukanta-27** [comment]
**Additionally:** 
https://github.com/TEAMMATES/teammates/blob/4416b4db657cdf6993fd298d51cc7e3a7d630c66/src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java#L973-L981

This code was commented out in #2815 (specifically in https://github.com/TEAMMATES/teammates/commit/5d6aabb0e0f1366974cddcbe6689f2cb643f23a6), we should delete this code, as at this point it is nothing more than dead code. 

@damithc Should this be a part of this issue only, or should I create a new issue for `d.FirstTimers`?

**Comment by damithc** [comment]
> @damithc Should this be a part of this issue only, or should I create a new issue for d.FirstTimers?

It can be part of this issue. Too trivial to be a separate issue.

**Comment by damithc** [comment]
@sukanta-27 in this issue you are proposing to do client-side validation for Rubric question details, am I right?

**Comment by sukanta-27** [comment]
@damithc Yes sir.

**Comment by sukanta-27** [comment]
@LiHaoTan Yes, we can also do that. 
@damithc Sir. Your thoughts on this issue?
