### ISSUE TITLE
Feedback for GSoC proposal Draft

### ISSUE THREAD

**Issue by sukanta-27** [TEAMMATES/teammates#8634]
I have shared a draft of my GSoC proposal for this organization for the project **Questions+**. Kindly provide feedback. Also please notify me if there is any problem in viewing the draft or accessing any of the links attached in the draft.

**Comment by damithc** [comment]
Will do. Remind if you don't receive feedback in a couple of days :-)

**Comment by sukanta-27** [comment]
@damithc okay sir. :smile:

**Comment by Progyan1997** [comment]
@damithc I am not getting any response either. :disappointed:

**Comment by shaharyar-shamshi** [comment]
@damithc Sir I have shared my Proposal on Question+ and Recycle Bin Kindly give Feedback on it for Improvement

**Comment by damithc** [comment]
Comments added to all three.

**Comment by nidhi98gupta** [comment]
@damithc Sir, I have shared draft of my GSoC proposal on Comments for Responses. Kindly provide feedback.
Also I want to submit one more proposal on Coverage Boost (Java).
It would be helpful if you could share some past incidences of problems due to incorrect/incomplete tests related to Java.

**Comment by damithc** [comment]
@nidhi98gupta I have commented in your proposal draft.

**Comment by gaurav122197** [comment]
@damithc I have submitted my proposal for Recycle Bin. Kindly give feedback for further improvement.

**Comment by damithc** [comment]
> @damithc Sir, I have submitted my proposal for Recycle Bin. Kindly give feedback for further improvement.
> Please also notify if there is any problem in viewing the proposal.

Added comments.

**Comment by digib0y** [comment]
I submitted my draft proposal for rework of the TEAMMATES Website. Can you please take a look?

**Comment by jacoblipech** [comment]
Sir, I have submitted my proposal for a self proposed idea for GSoC. It would be helpful if you can give some feedbacks about it. Thank You.

**Comment by mg14777** [comment]
Hello Sir, I recently submitted a proposal on project Usability Hero. I would be great if I can get some feedback as well.

**Comment by damithc** [comment]
> Hello Sir, I recently submitted a proposal on project Usability Hero. I would be great if I can get some feedback as well.

@mg14777 Unable to add comments to your draft as you shared it in 'view only' mode.

**Comment by damithc** [comment]
> I submitted my draft proposal for rework of the TEAMMATES Website. Can you please take a look?

@digib0y Comment added to your draft proposal.

**Comment by damithc** [comment]
> Sir, I have submitted my proposal for a self proposed idea for GSoC. It would be helpful if you can give some feedbacks about it. Thank You.

@jacoblipech comments added to your draft proposal.

**Comment by mg14777** [comment]
@damithc Thanks for letting me know. I've changed it. Sorry for the inconvenience

**Comment by damithc** [comment]
> @damithc Thanks for letting me know. I've changed it. Sorry for the inconvenience

@mg14777 comments added to your proposal draft.

**Comment by nidhi98gupta** [comment]
@damithc Sir, I have submitted another proposal on Coverage Boost (Java), which is my second preference, first being Comments for Responses. Kindly provide feedback.

**Comment by damithc** [comment]
@sukanta-27 @nidhi98gupta comments added for both.

**Comment by gaurav122197** [comment]
@damithc Sir, kindly review my draft on Recycle Bin.

**Comment by damithc** [comment]
@gaurav122197 @nashmia-riaz comments added

**Comment by kyngyi** [comment]
@damithc Sir, I have shared a draft proposal for one of the ideas, kindly take a look and it would be appreciated if you could share your feedback. Thank you

**Comment by damithc** [comment]
@kyngyi comments added to the draft

**Comment by gaurav122197** [comment]
@damithc  Sir, please provide feedback on the Recycle Bin draft.

**Comment by damithc** [comment]
> @damithc Sir, please provide feedback on the Recycle Bin draft.

@gaurav122197 done

**Comment by gaurav122197** [comment]
@damithc Sir, a little more help needed regarding the draft feedback. 
Thank You, Sir.

**Comment by sukanta-27** [comment]
@damithc  Sir, made a lot of changes in my draft for the project **Comments on Responses**, if possible kindly provide feedback before I make the final submission.

**Comment by damithc** [comment]
> @damithc Sir, made a lot of changes in my draft for the project Comments on Responses, if possible kindly provide feedback before I make the final submission.

@sukanta-27 Comments added

**Comment by jsroyal** [comment]
Hi! I've submitted the draft of my proposal. Would you please @damithc provide some feedback.

**Comment by sukanta-27** [comment]
Closing as the student application period for Google summer of code 2018 is over.
