### ISSUE TITLE
Instructor: help page: improve content

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8635]
Fix grammar, rephrase for easier reading, add missing info, etc.

**Comment by damithc** [comment]
@craaaa you may want to start doing this independent of @wenmogu's work. She can de-conflict later if necessary. But you can do this as a series of small PRs for easier reviewing/merging e.g., add missing info first. Today a user commented that the help page doesn't explain how to extend a deadline

**Comment by craaaa** [comment]
Will do! Do also let me know if there are any additional frequently asked questions that should be added to the help page.

**Comment by damithc** [comment]
Another FAQ is whether TEAMMATES is free or do we plan to charge fees in future. The answer should be along the lines of, 
>TEAMMATES is funded by education grants and is free for both instructors and students. 
At  the moment we have no plans to commercialize TEAMMATES or offer paid services. In the unlikely event the free service is terminated, users will be informed at least one semester in advance.

**Comment by craaaa** [comment]
@damithc am almost done with reworking the existing questions and would like to move on to adding new questions. Can you shed some light on any particular areas that instructors frequently find unclear?

**Comment by damithc** [comment]
Some questions that comes to my mind:
* _When_ do students get to see responses?
* Can I change the visibility settings after the session has started? - Yes, but not recommended.
* Can students edit responses after they have submitted?
* Can I set a question as compulsory? - Not at the moment. But can mention in the question description that it is a compulsory question (not enforced).
* Can I extend the deadline? 
* Can I extend the deadline to specific students? - Not at the moment. But can ask the student to view the submission page and send you the responses via email, which you can submit on behalf of the student (give more info on how to do that).
* Can I see when a student tried to access the submission page? - Not at the moment. If there is such a need, contact us and we'll try to find that information for you.
