### ISSUE TITLE
[GSoC] ibodi, new contributor

### ISSUE THREAD

**Issue by ibodi** [TEAMMATES/teammates#8649]
Hello. My name is Bogdan, but you better call me ibodi. I would love to contribute to TEAMMATES as my GSoC project. I have selected the Questions project among others. This is my first time participating in GSoC, so I feel a bit lost. I've started wandering whether I may just copy-paste the project idea from the Ideas page and send it as my final proposal.

What should I start with if I want to participate?

**Comment by shaharyar-shamshi** [comment]
@ibodi welcome to Teammates I recommend you to before giving any idea just Solve few Issue start with d.firsttimer then move further with any other issue like d.contributor 
Regarding Idea If you want to  submit idea from the idea page select any idea and make a proposal what changes you would like to implement let us suppose you selected the idea of Question+ then suggest any improvement you would like to amke in existing question type . looking forward for your Contribution. you can mention me in comment if you need any help I will be happy to help you

**Comment by damithc** [comment]
@ibodi we have instructional documentation for new contributors as well as for GSoC applicants. Do have a look at them.
