### ISSUE TITLE
Help Requested:Addition of extra changes 

### ISSUE THREAD

**Issue by shaharyar-shamshi** [TEAMMATES/teammates#8650]
Today I just updated my branch through the update Branch button in my open pull request no. #8596 #8562  #8208 this led to addition of too many extra changes somewhat approx more 150 file changes in each pull request I tried a lot to revert merge then again do merging but this did not helped me Can anyone help me

**Comment by wkurniawan07** [comment]
@shaharyar-shamshi this is a general Git problem, and as such should not be asked here. I will simply tell that reverting a merge is generally a bad idea, and you may need to do a hard reset to the point before it all happened, fix/merge/... accordingly, and do a force push.
