### ISSUE TITLE
Instructor: edit session: multiple choice questions: support generating options for all other teams

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8661]
Similar to #8412 but for 'all other teams' instead of 'all other students'

**Comment by nashmia-riaz** [comment]
Hello. I would like to work on this issue.

**Comment by nashmia-riaz** [comment]
Hello. 
From what I gather, in the screenshot below, Team 1 should not be an option as Alice Betsy is on Team 1. Is that correct? 
![Screenshot](https://user-images.githubusercontent.com/13387692/37624952-e34e42a8-2beb-11e8-8a78-266e4d8ae51e.png)

**Comment by tshradheya** [comment]
Yes you are right.
Yoi can refer to #8445 PR which does this same thing but for students
