### ISSUE TITLE
[GSoC] What if I am not familiar with the technologies?

### ISSUE THREAD

**Issue by ibodi** [TEAMMATES/teammates#8667]
For GSoC I chose the Question+ project. What if I am not familiar with the technologies? I mean Google Cloud Platform, App Engine, Selenium, TestNG, even my Git skills are very primitive. Should I apply if my experience is quite limited?

**Comment by shaharyar-shamshi** [comment]
@ibodi Gsoc is learning platform even we are also student and don't know many stuff feel free to give your proposal you have lot of time to learn stuff and learning by doing is best strategy feel free to contribute and ask question

**Comment by damithc** [comment]
Yes, learning is part of the process. There is no need to know all related technologies from the start. The more important thing is to show that you can learn things fast.
