### ISSUE TITLE
Could not determine java version from '9.0.1'.

### ISSUE THREAD

**Issue by ibodi** [TEAMMATES/teammates#8671]
OS: Mac OS High Sierra

Hello, I am trying to import the project to my Eclipse instance. I follow instruction given here: .
[https://github.com/TEAMMATES/teammates/blob/master/docs/ide-setup.md](url)

I went to File → Import....
Selected Existing Gradle Project under Gradle. Clicked Next >.
Set the Project root directory to /Users/ibodi/MyDocs/teammates. Clicked Next >.
Ticked Override workspace settings and choose Gradle wrapper. Clicked Finish and got an error:

org.gradle.tooling.GradleConnectionException: Could not create an instance of Tooling API implementation using the specified Gradle distribution 'https://services.gradle.org/distributions/gradle-3.5-all.zip'.
...
Caused by: java.lang.IllegalArgumentException: Could not determine java version from '9.0.1'.
...

What am I doing wrong?

**Comment by wkurniawan07** [comment]
@ibodi, two things:
- Gradle 3.5 suggests that you have used a very old version of the code base, dated even before [we moved to Java 8](https://github.com/TEAMMATES/teammates/releases/tag/V6.0.0). Do update your fork to keep in sync with the latest code base.
- You have asked the exact same question back in #8123 and got an answer (albeit outdated now). Essentially, do read up our [setting up guide](https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md).

**Comment by craaaa** [comment]
Hi @ibodi, hope that you have had success setting up your dev environment. If you need further help, do reopen this issue or open another issue.
