### ISSUE TITLE
InstructorHelp: Fix inconsistent indentation for different sections

### ISSUE THREAD

**Issue by joanneong** [TEAMMATES/teammates#8675]
- **Environment**: `master` branch at commit 8a974ee

A typical section in the instructor help page should look like this:

<img width="1278" alt="screen shot 2018-03-19 at 12 42 33 am" src="https://user-images.githubusercontent.com/24493463/37568472-838792d8-2b10-11e8-9951-e25ad07b9ca1.png">

However, the later sections (from "Profiles" onwards) look like this:

<img width="1279" alt="screen shot 2018-03-19 at 12 43 03 am" src="https://user-images.githubusercontent.com/24493463/37568477-90520372-2b10-11e8-9a0c-d00cbb890c00.png">

Although it cannot really be seen from the screen captures, these later sections are at a different indentation level (headers and content) from the preceding sections.

**Expected behaviour**

Since the sections are at the same level within the instructor help page, they should have the same amount of indentation as well for a consistent UI.

**Additional info**

Given that the [instructor help page is set to undergo some drastic changes](https://github.com/TEAMMATES/teammates/issues/8504), is it worth making this a legit `d.FirstTimers` issue to work on?

@craaaa , can I have your input on this?

**Comment by craaaa** [comment]
Yep, noticed this too! I don't think it's that worth it though, since we will likely be moving away from displaying questions as a list.

**Comment by sukanta-27** [comment]
@craaaa 
>We will likely be moving away from displaying questions as a list,

Just out of curiosity, what do you mean by this?

**Comment by craaaa** [comment]
@sukanta-27 As part of #8504, I'm thinking of making some design changes to `instructorHelp.jsp` so it will be more easy to skim for answers. Some possible changes are using accordions or collapsed sections, or moving content into multiple separate pages. Doing so will require reorganizing the section structure, so changes made to fix this issue are likely to be overwritten.

**Comment by craaaa** [comment]
Closing as the issue will be fixed alongside #8635.
