### ISSUE TITLE
Help Request: How JS Minification Works

### ISSUE THREAD

**Issue by nashmia-riaz** [TEAMMATES/teammates#8684]
Hello, prestigious dev team of Teammates!

I am a student from Pakistan, currently looking forward to applying for GSoC 2018.

I am trying to fix an issue and I think I understand most of the code flow. However, I am having trouble figuring out how the js in dev/js/main ends up getting minified and ultimately used in the webapp/js.

Could someone please explain this to me? I did refer to the 'Documentation for Developers' but couldn't find anything related to this. Please bear with me since I am new to JSP & JSTL.

**Comment by Crphang** [comment]
The Javascript files are minified when you run `npm run build`. Take a look at https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#building-javascript-files which describes that. If you really want to know how it is done, you can take a look at the webpack configuration in `webpack-main.config.js` file

**Comment by nashmia-riaz** [comment]
@Crphang Thank you so much. This is very helpful 👍
