### ISSUE TITLE
TEAMMATES application for mobile platform

### ISSUE THREAD

**Issue by abhishekd08** [TEAMMATES/teammates#8693]
We should develop an Mobile Application of TEAMMATES

Currently, this platform is available only as a web application.

It will become very comfortable and easy for students, instructors as well as developers to make use of our Software Solution if they can access it on their mobile.
We should develop an application of TEAMMATES for Android as well as IOS platform.

The ultimate aim of all of us is to create something by using which the work of some people in the society becomes easy and that is what this idea is all about

In the current scenario, when an student or instructor or developer want to access TEAMMATES platform he/she has to open it in the browser and it is not that great experience or convenient on a web browser on any phone.

So the point is that if we can give them something easy or more convenient on the phone then we should.

I am a student and I want to contribute to this project in Google Summer of code program. Please let me know if I can contribute by developing an android application of TEAMMATES. Thank you

**Comment by abhishekd08** [comment]
I will send a proper application for Google Summer of Code program if you confirm that android application of TEAMMATES can be developed. Thank You.

**Comment by damithc** [comment]
We don't plan to develop a mobile app for TEAMMATE anytime soon @abhishekd08
