### ISSUE TITLE
Help Request: Why are my lint tests failing?

### ISSUE THREAD

**Issue by nashmia-riaz** [TEAMMATES/teammates#8694]
When I run 'npm run lint:js', it results in an error for every single .js file in dev/js. The resulting error is something like this:

error  Casing of ../main/instructorCourseEnrollPage does not match the underlying filesystem  import/no-unresolved

In addition to this, the webpack-main.config.js has the same error as well. The ./gradlew lint test, however, does pass. The error occurs on my local unmodified master branch. I have tried running npm install and npm run build, tried running the server again but in any case, I keep getting a massive list of errors on npm lint:js only.

What is the possible reason for this? And how can it be resolved?

**Comment by shaharyar-shamshi** [comment]
Just run npm run lint

**Comment by sukanta-27** [comment]
@nashmia-riaz It is probably a bug in `eslint-plugin-import` (https://github.com/benmosher/eslint-plugin-import/issues/720), but it should not occur after `V2.8.0`. Can you confirm that you have the updated `master` branch?

**Comment by wkurniawan07** [comment]
@nashmia-riaz can you report using a proper [help request template](https://github.com/TEAMMATES/teammates/blob/master/.github/ISSUE_TEMPLATE/help-request.md)? Right now there are quite a lot of missing information if we are to troubleshoot. Also, while may not be written on that template, but do write down your Node.js version as well.

**Comment by nashmia-riaz** [comment]
@sukanta-27 I am up to date with the master. Upon further tinkering, I have found out that the tests do pass in cmd, just not in powershell or git shell (which i was using earlier). So, I assume that the problem is local.

@wkurniawan07 apologies about not using the template earlier as I think the problem is with configurations on my machine.
Commit SHA: e4078943a
Operating System: Windows 10
JDK Version: 1.8.0
Google Cloud SDK Version: 186.0.0
Eclipse / IntelliJ Version (if applicable): IntelliJ IDEA 2017.3.3 (Ultimate Edition)
Firefox / Chrome Version (if applicable): 
Node.js version: 5.6.0

**Comment by wkurniawan07** [comment]
@nashmia-riaz I may have an idea of what's happening, but does this still happen?
Also can I check that `5.6.0` is your Node.js version, not your NPM version?

**Comment by nashmia-riaz** [comment]
@wkurniawan07 I recently reset my laptop in hopes that it was a configuration issue on my machine, but it didn't go away. 
I assume this is the correct way to check npm version (screenshot attached).
![capture](https://user-images.githubusercontent.com/13387692/38263445-915e7612-3789-11e8-81d1-40546aa3975d.PNG)
