### ISSUE TITLE
AdminActivityLogPage: incorrect log message for change of course time zone

### ISSUE THREAD

**Issue by darrenwee** [TEAMMATES/teammates#8695]
**Environment**: 
`master` @ a88f169

**Steps to reproduce**
1. Edit an existing course and change its timezone
2. Open up the admin activity log @ `/admin/adminActivityLogPage`
3. Observe that the edit action was not logged correctly; it says that the course name was changed even if it was not touched.

**Expected behaviour**
The log message should be something like
```
Course time zone for Course [CS9999] edited.
Old time zone: America/Recife
New time zone: Africa/Nairobi
```

**Actual behaviour**
The log message says the course name was edited, even if it was not touched.
```
Course name for Course [CS9999] edited.
New name: Darren is great
```

**Gif of actions to reproduce**
![adminactivitylog-loggingbug](https://user-images.githubusercontent.com/12949331/37751916-8ba0da6c-2d6b-11e8-9e4e-5da5ea14385e.gif)

**Comment by nashmia-riaz** [comment]
Hello. I would like to work on this issue. 
I think editing instructorCourseEditSaveAction to fetch the course before changes are saved for it, and comparing to send the appropriate status message to admin would fix the issue. Please let me know if I should proceed.
