### ISSUE TITLE
Keep comment search documents up-to-date

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#8704]
Root cause of #8702 - see https://github.com/TEAMMATES/teammates/pull/8698#issuecomment-375829424. Results in outdated search results.

The only time comment search documents are ever updated/deleted is when comments are individually edited/deleted, and this is done at the action level! Updating/deletion of responses, questions, sessions and courses does not result in updating/deletion of corresponding comment search documents, resulting in lots of outdated/orphaned documents, leading to outdated search results.

Updates to documents should be done at the logic level and should follow updates to responses, questions, sessions and courses closely.

**Comment by nidhi98gupta** [comment]
I would like to work upon this.

**Comment by xpdavid** [comment]
Batch operations are not synced:

`updateGiverEmailOfFeedbackResponseComments()` and `updateLastEditorEmailOfFeedbackResponseComments()`
