### ISSUE TITLE
Session reminder emails: mention editing responses

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8708]
**Description of feature/enhancement**

Reminder emails sent to respondents have the following phrase:
>To submit your feedback for the above session, please go to this Web address ...

Suggestion: rephrase as
>To submit your feedback for the above session (or to edit/view responses submitted earlier), please go to this Web address ...

**Justification**
Some students contact us with requests such as 'I submitted already. Can you check if it was saved?'. The revised phrasing might reduce such support requests.

**Comment by jacoblipech** [comment]
I will take this issue :)

**Comment by shamlymackey** [comment]
I can do this issue, may I know the name of the source file please?

**Comment by wenmogu** [comment]
Hi @shamlymachey, since the aim of the first timer issues is to make u familiarize yourself with the codebase, you are supposed to trace the code yourself and find out where is the place you need to change. 
Maybe you want to start with a global search for the keywords and see what you can get.

**Comment by shamlymackey** [comment]
@wenmogu Thank you very much! Will do!

**Comment by tshradheya** [comment]
@shreyag12 Seems like you have already worked on a `d.firstTimers` issue.

You can proceed to try out the `d.Contributors` issue. We dont recommend doing more than one `d.FirstTimers` issue

**Comment by shreyag12** [comment]
Ok. Sure @tshradheya

**Comment by tshradheya** [comment]
@Vaggelis-Malandrakis Yes. You can go ahead and resolve this :)

**Comment by Vaggelis-Malandrakis** [comment]
Found a solution which can be implemented easily and without changing a lot but instead of

> To submit your feedback for the above session (or to edit/view responses submitted earlier), please go to this Web address ...

I implemented

> To submit (or edit/view) your feedback for the above session, please go to this Web address ...

which I believe is to the point and fully compatible with the suggested solution and solves the problem.

Can I proceed to pull request?
