### ISSUE TITLE
AccountAttributesTest: fix instability due to modified timestamp comparison

### ISSUE THREAD

**Issue by mg14777** [TEAMMATES/teammates#8709]
- **Environment**:  [cd9a536](https://github.com/TEAMMATES/teammates/commit/cd9a5365cfed580bae5d1bf15f2994a921e31f03)

**Description of feature/enhancement**

This is an enhancement to the build process

As pointed out by @bqnguyen94 also, currently ```AccountAttributeTest::testSanitizeForSaving``` as shown below

https://github.com/TEAMMATES/teammates/blob/dbca7a2531c4cfccec4deac0d3569ac58298a7e8/src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java#L114-L126

fails sometimes (CI tests) at line 125 during comparison of ```StudentProfileAttributes``` because ```modifiedDate``` parameter is created using ```Instant.now()``` as shown below:

https://github.com/TEAMMATES/teammates/blob/dbca7a2531c4cfccec4deac0d3569ac58298a7e8/src/main/java/teammates/common/datatransfer/attributes/StudentProfileAttributes.java#L36-L46

**Justification**

If we mock the system time we can bypass this which will be beneficial to developers in future.

**Comment by whipermr5** [comment]
Simply set the modified date via `withModifiedDate` while creating the test data:
https://github.com/TEAMMATES/teammates/blob/cd9a5365cfed580bae5d1bf15f2994a921e31f03/src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java#L304-L319
