### ISSUE TITLE
AdminActivityLogPage: fix inconsistent StudentProfilePage Load message

### ISSUE THREAD

**Issue by nashmia-riaz** [TEAMMATES/teammates#8717]
- **Environment**: 
`master` branch at commit cd9a536

**Steps to reproduce**
1. Log in as student and open profile page.
2. Log out and log in as admin.
3. View activity log.

**Expected behaviour**
A consistent message that perhaps says:

```
studentProfile Page Load 
Profile: test
```
where test is the googleid of the student.

**Actual behaviour**
Currently, it displays the entire json which is ugly and inconsistent with the rest of the messages.

![actual](https://user-images.githubusercontent.com/13387692/37919896-b36291ea-313e-11e8-8bfb-64bc74f822c5.png)

**Additional info**
This bug is similar to #8707 and #8695.

**Comment by gthd** [comment]
Hi @nashmia-riaz  I would like to fix this issue if this is ok.

**Comment by nashmia-riaz** [comment]
Sure. Go ahead! :)
