### ISSUE TITLE
Rename ambiguous method isChangesRequiresResponseDeletion -> shouldChangesRequireResponseDeletion

### ISSUE THREAD

**Issue by Haozhe321** [TEAMMATES/teammates#8721]
The method `isChangesRequiresResponseDeletion` checks if changes to a question requires the deletion of responses. The method returns a boolean value. 

For example, this method is called at line 301 below. 
https://github.com/TEAMMATES/teammates/blob/847de291e580ffbe3f9c50b329bb29acce5818a7/src/main/java/teammates/common/datatransfer/attributes/FeedbackQuestionAttributes.java#L295-L302

Rename all instances of this method to  `ifChangesRequireResponseDeletion` for better clarity.

**Comment by Haozhe321** [comment]
That sounds good as well!

**Comment by shamlymackey** [comment]
Hey! I would like to try this, but just to make it clear, all I have to do is change each instances of this method right? Is it possible for you to provide me with one example please? Thanks!

**Comment by Haozhe321** [comment]
@shamlymackey that's right. The example is provided in the issue description above. Do a global search and replace all instances of the method name.

**Comment by shamlymackey** [comment]
@Haozhe321 Sorry for the multiple questions, but just want clarity since I am fairly new to this. Is "teammates/src/main/java/teammates/common/datatransfer/attributes/FeedbackQuestionAttributes.java" the only file I need to change?

**Comment by Haozhe321** [comment]
@shamlymackey There's already a PR for this issue referenced above. But if you want to find out how it's done, you can take a look at that PR.
