### ISSUE TITLE
Run script to delete orphaned comment search documents

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#8729]
Related to #8698. Script from #8703 should be run before deploying V6.5.0 to delete orphaned search documents that use the old date format and are incompatible with the search system.

**Comment by damithc** [comment]
So, I should pull the latest master and run the script against live server?

**Comment by whipermr5** [comment]
@damithc Yes.

**Comment by damithc** [comment]
Done.
```
Total number of scoreddocuments: 14909
Number of affected scoreddocuments: 2466
Number of updated scoreddocuments: 2466
```
