### ISSUE TITLE
Fix indentation for test resource html pages to avoid irrelevant changes

### ISSUE THREAD

**Issue by tshradheya** [TEAMMATES/teammates#8744]
Issue title: Correct indentation of test resources webpage

- **Environment**: Current master branch 76ab9a02fb1c42b93e50adaf62ebeb59338a75cf

**Steps to reproduce**
1. Run GodMode which changes any of the mentioned files.

1. More details:
https://github.com/TEAMMATES/teammates/pull/8677/files#r178455003
I am assuming Godmode indents the HTML page as well. And I guess this page wasn't indented properly initially causing these changes to be made in around 4 HTML pages whenever Godmode changes anything else in these test resource web pages.

**Expected behavior**

These changes should not be made when running Godmode

**Actual behavior**

Indentation changes are made which are irrelevant to the PR

As far as I have noticed, the following files need to be indented correctly:
- studentFeedbackSubmitPageFullyFilled.html
- studentFeedbackSubmitPageModified.html
- studentFeedbackSubmitPageOpen.html
- studentFeedbackSubmitPagePartiallyFilled.html
- unregisteredStudentFeedbackSubmitPageOpen.html
- unregisteredStudentFeedbackSubmitPagePartiallyFilled.html

**Comment by tshradheya** [comment]
@whipermr5 I am confused as to how the indentation is done for GodMode? Are there any rules that are specified for HTML?

Because if new contributors do this [process ](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-setup.md#project-setup-1)while setting up IDE, and then use Ctrl+Shift+I to indent [in intellij] more changes are made as the rules are different.

Current setting in my intellij[I guess its default] is that children of tbody are not supposed to be indented, however, all current instances have it indented and moreover even godmode wants children of tbody to be indented

**Comment by wkurniawan07** [comment]
@tshradheya Godmode has no regards for IDE indentation whatsoever and precisely because the objective is uniformity in as much cases as possible, if not all possible cases, so don't even try to auto-indent those HTML files with any IDE.

**Comment by whipermr5** [comment]
Yup the cause of this issue is probably manual changes made to those HTML files such that the HTML differs from godmode output, but still passes the HTML comparison. I believe the indentation logic can be found in `HtmlHelper`.

**Comment by whipermr5** [comment]
@wkurniawan07 I encountered this issue too when working on #8687; had to manually discard the indentation changes to avoid them showing up in the changeset, so I'd say it's a valid issue.
