### ISSUE TITLE
Instructor: existing feedback sessions with fixed offsets: reduce occurrence of confirmation modals

### ISSUE THREAD

**Issue by joanneong** [TEAMMATES/teammates#8748]
- **Environment**: `master` branch at commit dc85dd0

**Steps to reproduce**

After TEAMMATES have switched to auto-detecting the geographical time-zone, instructors are reminded of this new feature when they start a new feedback session/ when they first edit a feedback session.

<img width="1280" alt="screen shot 2018-04-03 at 1 30 45 pm" src="https://user-images.githubusercontent.com/24493463/38231032-58577eae-3743-11e8-8dcb-952801f1480f.png">

1. In the Instructor Sessions page, pick an existing feedback session that was created before this new feature was implemented.
2. Edit the feedback session.
3. Add/delete a question.
4. Observe that the confirmation modal above appears every single time a question is added/deleted.

<img width="1280" alt="screen shot 2018-04-03 at 1 17 44 pm" src="https://user-images.githubusercontent.com/24493463/38230845-8ee95650-3742-11e8-87f5-b2d604acfa05.png">

**Justification**
Although the feature works well for new feedback sessions created after the feature was implemented, it is annoying for existing feedback sessions as the modal will appear after every single question edit. The behaviour of the modal should be consistent - the modal should only appear once when you first access a feedback session.

P/S Can someone check if this issue is reproducible on their copy of TEAMMATES?

**Comment by damithc** [comment]
The modal goes away after saving the session once?

**Comment by sukanta-27** [comment]
Checked. @joanneong I suppose you have not saved the session. Once you save the session, it will go away.

**Comment by damithc** [comment]
Perhaps we should tweak the dialog such that  the options are `Correct` and `Not correct. I will modify it manually` and the first option saves the session automatically? Would that be a better UX? @whipermr5 what do you think?

**Comment by whipermr5** [comment]
@damithc Sounds good; I will implement that.

**Comment by whipermr5** [comment]
Closing as the confirmation modal will be removed in #8759.
