### ISSUE TITLE
Instructor: add a cancel button to terminate the process of adding instructor

### ISSUE THREAD

**Issue by wenmogu** [TEAMMATES/teammates#8754]
Currently there is no cancel button for the user to exit the process of adding new instructor.

![image](https://user-images.githubusercontent.com/28526038/38286154-61800ea2-37f6-11e8-8d06-f99bac9f61a9.png)

It would be nice if there is a cancel button just like the one which shows up when adding a new question. 

![image](https://user-images.githubusercontent.com/28526038/38286205-a230ac90-37f6-11e8-808b-b4d0cd934f47.png)

- **Environment**: 
`master` branch at cbbfc98fee

**Comment by Vaggelis-Malandrakis** [comment]
Is this issue still open?

**Comment by sukanta-27** [comment]
Hi @Vaggelis-Malandrakis,
There is already an open PR for this issue, you can find another issue to work on.
