### ISSUE TITLE
Firefox: version 46.0.1 causing styling issue

### ISSUE THREAD

**Issue by LuLechuan** [TEAMMATES/teammates#8763]
In the developer guide, it is stated that "only Firefox between versions 38.0.5 and 46.0.1 are supported". However, when the Firefox version is 46.0.1. One of the test `commonJsTest` is failing due to the following line:
![image](https://user-images.githubusercontent.com/28507005/38462116-9ceaf392-3b13-11e8-9500-d1b90f154326.png)
As I change the Firefox version to 46.0, the test passed.

**Comment by wkurniawan07** [comment]
Adding a note that this would probably be a non-issue after #8749.

**Comment by wkurniawan07** [comment]
Fixed in V7
