### ISSUE TITLE
Exception by ControllerServlet when logging in as instructor

### ISSUE THREAD

**Issue by Vaggelis-Malandrakis** [TEAMMATES/teammates#8771]
Hi. I have successfully installed and run the application but yesterday that I tried to run the app at the localhost when I was trying to login as an instructor an exception appeared.

`Apr 12, 2018 1:33:10 PM teammates.common.util.Logger info`
`INFO: Request received : [GET] http://localhost:8080/page/instructorHomePage:{}`
`Apr 12, 2018 1:33:10 PM teammates.common.util.Logger info`
`INFO: User agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36 OPR/52.0.2871.40`
`Apr 12, 2018 1:33:10 PM teammates.common.util.Logger info`
`INFO: URL received : [GET] http://localhost:8080/page/instructorHomePage`
`Apr 12, 2018 1:33:17 PM teammates.common.util.Logger severe`
`SEVERE: Unexpected exception caught by ControllerServlet :` 
`org.apache.jasper.JasperException: /jsp/instructorHome.jsp (line: 15, column: 2) No tag "resendPublishedEmailModal" defined in tag library imported with prefix "ti"`

Do you know how I can fix it?

PS. I have pulled all the latest updates.

**Comment by whipermr5** [comment]
Have you restarted the dev server after pulling?

**Comment by Vaggelis-Malandrakis** [comment]
Problem still exits. Should I delete all the project and install it again?

**Comment by whipermr5** [comment]
That should work, though it's a last resort.

**Comment by Vaggelis-Malandrakis** [comment]
Ok I'll follow the whole procedure from the beginning.

**Comment by Vaggelis-Malandrakis** [comment]
Works perfect! Thank you!
