### ISSUE TITLE
Student: submit feedback: feedback button not greyed out when there are no recipients for any questions

### ISSUE THREAD

**Issue by tanhengyeow** [TEAMMATES/teammates#8772]
Noticed this bug when verifying if #3659 is fixed.

**Steps to reproduce**
1. Add a session as an instructor to a course with one or more questions having **only** the following:
 `Feedback Path`: `Students in this course will give feedback on -> Giver's team members`
2. Add a student with no team members to the same course.
3. Attempt to submit feedback as the student.

**Expected behaviour**
`Submit feedback` button should be greyed out since the student do not have any questions to answer.

**Actual behaviour**
`Submit feedback` button is not greyed out and student can submit their feedback.

**Environment**:  
`master` branch at commit eb92be306463d20c022770df2034412a1093eecb

**Comment by tanhengyeow** [comment]
Working on this!

**Comment by joanneong** [comment]
@tanhengyeow I do not actually see a problem with this. Right now, when we add such a question to such a course, the student sees this:

![image](https://user-images.githubusercontent.com/24493463/38714951-3df2f28a-3f0b-11e8-9532-3f6ab9d87826.png)

So let's say the instructor sets up a course for multiple teams, with one/some teams having a single member. In that case, those teams should be able to submit the feedback as well in case the instructor wants to see who has "done" the feedback survey.

@damithc Any thoughts on this?

**Comment by tanhengyeow** [comment]
Hi @joanneong @damithc 

Thanks for the feedback :smile: 

Let me walkthrough a scenario where it might confuse both instructors and students:

1. Instructor creates a course with the following teams and students:
![couse details](https://user-images.githubusercontent.com/25320782/38720670-bbbb7ae8-3f29-11e8-84f6-a798318ce9dc.png)

2. Instructor creates a feedback session in the course with one or more questions having only the following, `Feedback Path: Students in this course will give feedback on -> Giver's team members`. Instructor proceeds to view the session results (state where no students have submitted any responses):
![session results](https://user-images.githubusercontent.com/25320782/38720711-e4d1a164-3f29-11e8-82a7-b3afc8c8928e.png)

3. A student with no team members tries to submit feedback and is able to:
![harsha student](https://user-images.githubusercontent.com/25320782/38720766-1743703c-3f2a-11e8-96a7-5d9ee30fa5a3.png)

4. Instructor views session results (state where only `harsha` submitted responses). Notice that the only indication that `harsha` has submitted responses is due to the fact that he is missing from `Participants who have not responded any question`:
![session results after](https://user-images.githubusercontent.com/25320782/38720811-3983e1fe-3f2a-11e8-8e20-5abffc28871e.png)

5. A student with team members tries to submit feedback and is able to (intended):
![tom](https://user-images.githubusercontent.com/25320782/38720837-53f46158-3f2a-11e8-968d-6e0982d3f0fc.png)

6. Instructor views session results (state where both `harsha` and `tom` submitted responses).
![instructor view after](https://user-images.githubusercontent.com/25320782/38720859-67cd0aae-3f2a-11e8-87af-4fff9b073b85.png)

Potential confusion that arise includes:
1. Instructors might be confused on the fact that everyone has submitted responses but responses don't show up for students that fit under this profile. The proposed fix would alert instructors that questions in this feedback session does not fit the profile of some students. Instructors will be alerted through 2 different ways:
    1. When they see that the student has not submitted responses under `Participants who have not responded any question`
    2. When the student tells them that they can't submit feedback due to the button being greyed out.

2. In the case where students ticks the `Send me a confirmation email` box, an unnecessary email would be sent to them when they click on `Submit feedback`. This would be more common when #8606 has been fixed, which ticks the confirmation box by default when the student has not answered any questions.

I'm fine if this issue is too trivial to be fixed, might be just me who thinks it should be fixed :laughing: 

P.S The proposed fix in the PR will not grey out the `Submit Feedback` button when there are other types of questions in the feedback session with different feedback paths that allow students with no team members to answer.

**Comment by tshradheya** [comment]
Personally, I think this issue is too trivial.

Mainly because, if an instructor really goes for this feedback path: `Feedback Path: Students in this course will give feedback on -> Giver's team members`  **for all questions in a feedback session**, he would have ensured that all his teams are of `size > 1`.

Moreover, I doubt if TEAMMATES has received any feedback from any instructor who got confused because of this case, so it's not very necessary to fix it.

**Comment by damithc** [comment]
You are right @tanhengyeow it can lead to confusions as you have described. In fact sometimes students get into a team-of-one by mistake due to slight typos in team name which can lead to this scenario. Nevertheless, I don't think it is worth fixing at this point as we have a lot more issues that are more useful to fix. Still, it is good that we discussed this and we have a record of the discussion. We can take a revisit the issue in future if circumstances change.

**Comment by tanhengyeow** [comment]
Noted! Appreciate the discussion! @joanneong @damithc @tshradheya :pray:
