### ISSUE TITLE
AccountAttributes: Remove HTML sanitization before saving for googleId, name, institute

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#8779]
As per #8774, sanitization of Google ID will be performed during rendering if required.

Currently, a valid Google ID containing `<>"/'&` (possible for a Google account with a non-Gmail email) would become an invalid Google ID after sanitization, leading to failure when trying to persist an account with such a Google ID.

**Comment by shaharyar-shamshi** [comment]
Sir as I have solved one type of similar issue and currently working on one more issue of similar type . Can I work on this issue also ?

**Comment by whipermr5** [comment]
@shaharyar-shamshi Sure!

**Comment by ChooJeremy** [comment]
I'll work on this. since it's been a couple of months since the last update.
