### ISSUE TITLE
New instructors: set the time zone of the sample course to match user

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8787]
Steps:
1. Admin creates a new instructor
2. New instructor joins TEAMMATES
3. Upon joining, new instructor is given a sample course 

Current: sample course is in UTC timezone
Suggested: set the timezone to user's time zone

Reason: Sample curse is used to create a first impression, it's nice if the time zone is set correctly.

**Comment by mg14777** [comment]
@damithc I will take this issue

**Comment by tanhengyeow** [comment]
Hi @mg14777 

Still working on this?

**Comment by mg14777** [comment]
@tanhengyeow Not at the moment. If you want to take this go ahead.

**Comment by samuelfangjw** [comment]
Hi! May I try working on this issue?

**Comment by damithc** [comment]
> Hi! May I try working on this issue

Sure @samuelfangjw you can give it a try.
