### ISSUE TITLE
Instructor: edit session: allow making session visible from a future date 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8790]
v6.5.1

Steps:
1. Login as instructor
2. Edit an existing session
3. Try to set 'session visible time' of an existing session that is not open yet

Expected: allowed to choose a date that is up to the session opening date
Actual: only allowed to choose a date that is up to today

![image](https://user-images.githubusercontent.com/1673303/38842490-e2ae86a4-421c-11e8-8de3-f5a072f5159b.png)

I also noticed that if I edit the session opening date, the problem goes away and the 'visible date' picker unlocks future dates.

**Comment by damithc** [comment]
it's possible that it went undetected for long because it's a rarely used feature. Even when someone tried to use it, they may have encountered this problem and given it up thinking that its their fault or that's how it's meant to me. Even the user who contacted me today about this was not sure if it was a bug or if she was doing something wrong. Furthermore, the problem doesn't happen if the start date is edited first, which is the usual practice. I guess no need to hot fix, as long as we fix it by next release.

**Comment by whipermr5** [comment]
I'm okay with hotfixing it actually; I haven't merged #8789 back into master yet (in anticipation of more hotfixes haha).
