### ISSUE TITLE
Instructor: edit session: show a spinner while saving session

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8792]
v6.5.1

Steps:
1. Login as instructor
1. Edit session details
1. Save

![image](https://user-images.githubusercontent.com/1673303/38842793-704c8ece-421e-11e8-9151-156930f02c41.png)

Current: The `save changes` button stays active and can be clicked multiple times while the saving is in progress
Suggested: Disable the button while the saving is in progress and show a spinner e.g., `saving...`. I believe we do a similar thing in other places.

**Comment by shaharyar-shamshi** [comment]
Sir I am working on this by adopting the appraoch of autocorrection

**Comment by HoussamGHAZALA** [comment]
Hi @davel37 , are you still working on this issue or can i take it ?

**Comment by davel37** [comment]
Was on holidays till today, so just started. Hoping to create the pull request by Monday 😃
