### ISSUE TITLE
FeedbackRankQuestionUiTest.json: Fix data for Tests

### ISSUE THREAD

**Issue by tshradheya** [TEAMMATES/teammates#8794]
Problem spotted in #8710.

The `FeedbackRankQuestionUiTest.json` has a problem in the data used for the test case.

These are the four students which are in the data. 
**Alice and Benny** belong to _Team1_ and **Charlie and Danny** belong to _Team2_.
https://github.com/TEAMMATES/teammates/blob/6157ad411338974355998471d034523472c2d191/src/test/resources/data/FeedbackRankQuestionUiTest.json#L100-L136

However for responses to question 3 which has `recipientType `of the question is `OWN_TEAM_MEMBERS_INCLUDING_SELF`, 
https://github.com/TEAMMATES/teammates/blob/6157ad411338974355998471d034523472c2d191/src/test/resources/data/FeedbackRankQuestionUiTest.json#L617-L643

There exists a response from Benny to Charlie[who are in different team]
https://github.com/TEAMMATES/teammates/blob/6157ad411338974355998471d034523472c2d191/src/test/resources/data/FeedbackRankQuestionUiTest.json#L976-L988

We need to fix the data and change test cases accordingly to avoid breaking anything and have correct data

**Comment by jimmy51997** [comment]
@tshradheya ...is this issue still open?? I would like to work on it.

**Comment by tshradheya** [comment]
There is already an open PR which has done most of the work already

**Comment by jimmy51997** [comment]
@tshradheya how to know that there is an open PR on any issue??

**Comment by tshradheya** [comment]
It will be referenced in the issue thread with the same title as the issue

E.g.
![image](https://user-images.githubusercontent.com/12574756/39848568-3f337e1e-543a-11e8-9572-71329a79910b.png)
