### ISSUE TITLE
Refactoring in RemoteApiClient.java class

### ISSUE THREAD

**Issue by douihechmaha** [TEAMMATES/teammates#8795]
#code Enhancement
I have found ,currently,  this block of code ,i think we should move it  out of this class. it should be written in another new  class.
![codetechnique](https://user-images.githubusercontent.com/24609502/38961144-80b7f38a-4367-11e8-8efd-51e9249fcd2a.png)

**Comment by sukanta-27** [comment]
Hi @douihechmaha, Welcome to TEAMMATES.

 Please use a proper issue template in your issue description to provide us more information. Your issue description is unclear.

If this is a feature request then please follow [this](https://github.com/TEAMMATES/teammates/blob/master/.github/ISSUE_TEMPLATE/feature-request.md) template
in case of a bug report follow [this](https://github.com/TEAMMATES/teammates/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) template.

**Comment by douihechmaha** [comment]
Hi @sukanta-27 ,thanks for your comment.

Context : In fact, it is not the job of RemoteApiClient.java to determine if one is in local (.isDevServer) or normal mode. 

Solution : I suggest putting this block of code in an apart class.so when we get in RemoteApiClient.java class we know already whether we are in local or normal mode.

PS:this is only for Code quality enhancement .

**Comment by wkurniawan07** [comment]
@douihechmaha, I'm not convinced that your suggestion works. Why is it so important that "when we get in `RemoteApiClient.java` class we know already whether we are in local or normal mode"? Can you give a concrete example and a solid reasoning on why your design will be better?

**Comment by wkurniawan07** [comment]
@douihechmaha Closing due to lack of information. Feel free to reopen/request for reopen when more information can be provided.
