### ISSUE TITLE
Warn if cookies are disabled

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#8799]
The current design depends on the session object for status message passing and token verification. Since the session object depends on cookies, status message passing and token verification will fail if cookies are not enabled. We can display a prominent warning if cookies are detected to be disabled, similar to the warning shown when JavaScript is disabled.

**Comment by Niladri45** [comment]
Hi, 
I would like to work on this issue. Let me know how to proceed for the same.

**Comment by wkurniawan07** [comment]
Resolved in V7.
