### ISSUE TITLE
“gradlew setupEclipse” throws an error?

### ISSUE THREAD

**Issue by pragin** [TEAMMATES/teammates#8810]
- **Commit SHA:** 
- **Operating System:** OS X El Capitan
- **JDK Version:** Idk 1.8.0_60
- **Node.js Version:** v10.0.0
- **Google Cloud SDK Version:** 199.0.0
- **Eclipse / IntelliJ Version (if applicable):** Eclipse Oxygen Java EE  IDE
- **Firefox / Chrome Version (if applicable):**

**What I was trying to do / What I need help with**
Hi, I am following [https://github.com/TEAMMATES/teammates/blob/master/docs/ide-setup.md]() guide to setup Eclipse IDE for a project from Github. I have successfully installed the required plugins mentioned in the guide.But when i run 

> ./gradlew setupEclipse

 it throws the following error:

![screen shot 2018-04-30 at 18 46 49](https://user-images.githubusercontent.com/17234402/39444755-b38082da-4cb0-11e8-8d32-526702f4091b.png)

So, I ran `gradlew tasks` the following output was given:

![screen shot 2018-04-30 at 19 00 13](https://user-images.githubusercontent.com/17234402/39444842-f2e62eca-4cb0-11e8-8bb4-f736add2ce44.png)

which did not have the "setupEclipse" option!

**Attempts to resolve the problem**

I tried to go through the issues on Teammates projects issues section to find similar errors, unfortunately, nothing match the one I am facing. I deleted the cloned project and cloned it again to see if things work still no luck.

I also tried [https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md](). That did not help either :(

Can someone explain me why is this happening and how can I successfully set up the IDE , please?

**Comment by wkurniawan07** [comment]
@pragin I checked your forked repo and it has not been updated since mid 2016, a lot of things have changed since then. Do sync your fork with the latest.

**Comment by pragin** [comment]
@wkurniawan07 thanks for pointing that out. To be honest I deleted the old repository from my PC and Mac then tried to fork before I opened up this issue but still it did not work. I tried to clear my cache, deleted the local repository and tried cloning "Eureka" it worked :). Thanks
