### ISSUE TITLE
InstructorFeedbackSessionsPageUiTest: New Session start and end with past date

### ISSUE THREAD

**Issue by shaharyar-shamshi** [TEAMMATES/teammates#8811]
Level : critical
Description:
New session is start and ended on may 1st 2018 so every test case that run after that will automatically fail as instead of Awaiting session is closed.

**Comment by tshradheya** [comment]
More details here:

[Travis Log Line 2631]( https://travis-ci.org/TEAMMATES/teammates/builds/373550686#L2631)
