### ISSUE TITLE
Update user map for April 2018

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8814]
To be done after (and similar to) #8755

New entries to consider:

Australia | Curtin University
-- | --
Australia | Charles Sturt University
Australia | Melbourne Business School
Australia | Monash University
Australia | Southern Cross University
Australia | Swinburne
Australia | Swinburne University of Technology
Australia | University of Melbourne
Australia | University of South Australia
Australia | University of Technology Sydney
Belgium | Sint-Lievenscollege Antwerpen
Canada | Cégep de Saint-Jérôme
Canada | École de technologie supérieure
Canada | George Brown College
Canada | Kwantlen Polytechnic University
Canada | Luther College
Canada | Okanagan College
Canada | University of British Columbia
Canada | University of Toronto Scarborough
China | Yi Dian Zi Xun
Colombia | Colegio Nueva Granada
Denmark | IBC
France | université de savoie
France | University of Paris 7
Indonesia | Perbanas Institute
Japan | International University of Japan (IUJ)
Kazakhstan | Nazarbayev University
Korea | Michuhol High School
Malaysia | Universiti Malaysia Perlis
Malaysia | Universiti Tenaga Nasional
Netherlands | Saxion
Netherlands | Saxion University of Applied Sciences
New Zealand | University of Auckland
New Zealand | Victoria University of Wellington
Saudi Arabia | King Fahd University of Petroleum and Minerals
Singapore | Damai Secondary School
Singapore | Jurong Junior College
Singapore | Nanyang Polytechnic
Singapore | Nanyang Technological University
Singapore | Ngee Ann Polytechnic
Singapore | Singapore Institute of Technology
Singapore | Singapore Polytechnic
Sweden | Chalmers University
UK | The Royal Veterinary College
UK | Univeristy of Manchester
UK | University of Bradford
USA | Arroyo High School
USA | Astor School
USA | Belmont University
USA | Chattahoochee High School
USA | DePaul University
USA | Duke University
USA | Florida International University
USA | Floyd College and Career Academy
USA | Fort Lewis College
USA | Grandview High School
USA | Hult International Business School
USA | Kennesaw State University
USA | Lafayette High School
USA | Lake Forest College
USA | Lander University
USA | Marquette University
USA | MassBay Community College
USA | Miami University
USA | Michigan Technological University
USA | Missouri State University
USA | Mountain Home Public School
USA | New Mexico State University
USA | North Carolina State University
USA | North Dakota State University
USA | Northeastern University
USA | Northern Arizona University
USA | Oak Creek High School
USA | Oakland University
USA | Ohio State University
USA | Parker University
USA | Regis University
USA | Rio Hondo Community College
USA | Rochester Institute of Technology
USA | San Diego State University
USA | San Francisco State University
USA | Seven Lakes High School
USA | Southern Oregon University
USA | Southern Oregon University
USA | Spring Lake Park High School
USA | Sutton Elementary School
USA | Syracuse University
USA | Texas A&M University
USA | The University of Texas Rio Grande Valley
USA | University at Albany
USA | University of California, Irvine
USA | University of Chicago
USA | University of Chicago
USA | University of Cincinnati
USA | University of Hawaii
USA | University of Kansas
USA | University of Kentucky
USA | University of Louisiana at Lafayette
USA | University of Mass, Lowell
USA | University of Minnesota
USA | University of North Carolina
USA | University of North Carolina at Wilmington
USA | University of North Florida
USA | University of Oregon
USA | University of South Dakota
USA | University of Southern California
USA | University of Virginia
USA | University of Washington
USA | Villanova University
USA | Violet Fairweather-Baker
USA | Washington and Lee University
USA | Washington State University
USA | Webster University
USA | Western Washington University
USA | Xavier University of Louisiana

**Comment by shekhar-anshu** [comment]
I want to take it up @damithc. A good one to start with.

**Comment by shekhar-anshu** [comment]
Ok @jimmy51997 , in that case please go ahead.

**Comment by jimmy51997** [comment]
okk... @shekhar-anshu

**Comment by shekhar-anshu** [comment]
There are two entries, which one to keep?
```
"University of Technology Sydney",
"University of Technology, Sydney",
```.
@damithc

**Comment by damithc** [comment]
> There are two entries, which one to keep?

Check their own website to see which one they use.

**Comment by Zilchchipmunk** [comment]
Hello, i am new here. I am familiar with java and would like to contribute but i am not sure what to do here.

**Comment by tomignarri** [comment]
Hello, am I allowed to submit a change even if it isn't assigned to me? I would like to just for the sake of practice.

**Comment by Mudra01** [comment]
hello, I am new to open source. I am a bit familiar with java and would like to work on this issue. Could you guide me through?

**Comment by sark01** [comment]
There has been no further activity on this issue, is it okay if I take it up?

**Comment by tomignarri** [comment]
Absolutely

**Comment by n1ckyb** [comment]
If no one is picking this up can I take a look? 
@sark01 Can you confirm if you're picking this up or not?

**Comment by cbb692** [comment]
Hey all,

It seems like people picking this up kinda died. I'm working on clearing them out right now, but wanted to clarify a few things before making a push to save time for everyone:

1) Under Belgium, there is the new Sint-Lievenscollege to be added. There is presently one in the system without a specific location, but it has a space in between "Lievens" and "College". Just wanna confirm if the space should be removed. Google says yes, but I might be missing something.

2) For the Japanese Uni listed above, do we want to include the "(IUJ)" or not? A minor point, but just want to confirm since it seemed a little out-of-place to me at first glance.

Thanks and sorry for the nitpicking.
