### ISSUE TITLE
Cant find the proper files to modify for an issue (#8589)

### ISSUE THREAD

**Issue by jimmy51997** [TEAMMATES/teammates#8819]
- **Commit SHA: 8973e8e7402d20f6f097511f5668aba894f56718** 
- **Operating System: Win 10**
- **JDK Version:jdk 1.8.0_171**
- **Node.js Version: v8.11.1**
- **Google Cloud SDK Version: 200.0.0**

**What I was trying to do / What I need help with 
I was looking for the file containing the source code for the page student profile that opens when we click on the profile tab of a student. I can't find the file. can anyone tell me the file name or where can i find it??**

**Attempts to resolve the problem
I thought the file name would be studentProfilePage.html but i couldn't find any such file except that in src/main/test/resources/pages . I don't think that's the actual source file of the page .**

**Comment by sukanta-27** [comment]
@jimmy51997 It will be better if you start by first reading the documentations and figuring out the project structures and how TEAMMATES function. The [Design](https://github.com/TEAMMATES/teammates/blob/master/docs/design.md) documentation will be a great place to start.

Also as I mentioned above, figuring out which files to modify is part of solving the issue. So, you should try figuring out by yourself, it will help you in the long run.

**P.S.** Use the issue tracker for help requests, bug reports and feature updates. For queries related to a particular issue like this one, the best place for discussion is that particular issue thread itself (In this case, #8589). There is no need to create a separate issue for it.

**Comment by jimmy51997** [comment]
@sukanta-27 okk...I am trying.

**Comment by jimmy51997** [comment]
@sukanta-27 .....the Design documentation you pointed out didn't help a bit.....honestly speaking, it was too tough for me to understand.

**Comment by nidhi98gupta** [comment]
@jimmy51997 You can try searching for keywords in the codebase to find where and how exactly it is used.
For eg. here you can search for `Upload a profile picture` i.e. the wordings of the tooltip you want to change.

**Comment by jimmy51997** [comment]
ohkk...thanks @nidhi98gupta
