### ISSUE TITLE
Instructors: sessions page: fix 'resend link to view results' 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8822]
v6.5.1, Chrome

Steps: Login as instructor, go to the 'sessions' page and try to resend links to a published session.

![image](https://user-images.githubusercontent.com/1673303/39967929-0592b6ec-56f7-11e8-9079-e901ce5ee1d7.png)

Expected: a modal opens up to select recipients

Actual: nothing happens

This feature seems to work on the instructor home page but on in the sessions page.

**Comment by nidhi98gupta** [comment]
@damithc I would like to take up this issue.

**Comment by damithc** [comment]
> @damithc I would like to take up this issue.

Sure @nidhi98gupta
