### ISSUE TITLE
Instructor: remind particular students: give a way to mass select

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8823]
Current: instructors can choose `Remind` -> `Remind particular students` to send reminders to specific students.

Suggested: In the modal that opens up, give check boxes to select/unselect groups of students. 
`[ ] all  [ ] all not submitted`
![image](https://user-images.githubusercontent.com/1673303/39967998-754ac780-56f8-11e8-8f33-8e56f5515dc5.png)

**Comment by jacoblipech** [comment]
@damithc I will be working on this issue
