### ISSUE TITLE
When I try to configure it is showing two configurations. 

### ISSUE THREAD

**Issue by smanaqvi83** [TEAMMATES/teammates#8826]
Whenever I try to configure the project for Google Cloud I get the two configurations, I have followed exact instructions that were given on the setting up.md.
![capture](https://user-images.githubusercontent.com/6833890/39987564-914bd3d0-577e-11e8-901f-4d476d60e17d.PNG)

And even if I try to run it with only selecting google cloud, there is no artifact shown in google cloud configuration, there is no artifact shown in the google cloud configuration in intelliJ idea. 
![noartifact](https://user-images.githubusercontent.com/6833890/39987841-3dc39418-577f-11e8-87c5-141084594200.PNG)

**Comment by tshradheya** [comment]
Instead of just selecting `Google cloud` and clicking `Okay`, you should wait for syncing to finish and then you won't find the second option

Wait for the entire syncing/indexing to over and then click on `Configure` again ( In events centre)

**Comment by smanaqvi83** [comment]
Tried it several times. Even when indexing is totally done.
