### ISSUE TITLE
Instructor: view results: fix bug: sorting results by team is broken

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8837]
v6.5.1, Windows 10, Chrome, live server

Steps:
1. Login as instructor
1. Go to the results of a session. Expand results of a question and sort individual responses by giver team

Problem: the table gets messed up, as follows.

![image](https://user-images.githubusercontent.com/1673303/40238949-3fe96eaa-5ae7-11e8-8c20-f657baee058e.png)

Other observations: seem to affect only some type of questions. Didn't observe the problem in contribution questions.

**Comment by tshradheya** [comment]
Working on it
