### ISSUE TITLE
Instructor: creating a session: the question editing halfway disappears after error message

### ISSUE THREAD

**Issue by jacoblipech** [TEAMMATES/teammates#8839]
Environment: master branch

While adding a question, when an error message pops up, the entire question which you are working on disappears. As shown below:
![question disappears after error message](https://user-images.githubusercontent.com/28522090/40339405-f1ce2558-5dac-11e8-9362-108ac03d0f44.gif)

Same problem for Rubric (options) Question and Distribute Points (among options) Question. Ideally, I think the error message should only appear on top of the question you are working on, and you can continue editing the question afterwards.

**Comment by wkurniawan07** [comment]
No longer an issue as page is not reloaded after saving (with error or not).
