### ISSUE TITLE
Instructor: Feedback Session: Add a new session template with sample questions.

### ISSUE THREAD

**Issue by sukanta-27** [TEAMMATES/teammates#8850]
- **Environment**: 
`master` branch

**Description of feature/enhancement:**
Add a new session template with sample questions. 

For the new session template I have made two sample templates where each template focuses on one aspect of team peer evaluation. I have added two zip files, both containing two webpages, one is `submit feedback` form and the other is `Instructor Edit session` page (this is to show the specific feedback paths that are good for each questions).

- Template One focuses on **Team dynamics**. It contains 5 questions four of which are open ended questions related to team dynamics.
[Template_one.zip](https://github.com/TEAMMATES/teammates/files/2050758/Template_one.zip)

- Template two focuses specifically on peer evaluation containing no open ended questions but only **performance based questions** which the instructors can use if their concern is mainly performance statistics.
[Template_two.zip](https://github.com/TEAMMATES/teammates/files/2050770/Template_two.zip)

I have tried keeping each template short as a long feedback form with lots of questions may discourage students (they may not give a lot of thought on each question if they see a lot of questions).

More discussion is needed in finalising which template to add and what sample questions will suit the instructor's needs best. 
 
**Justification**

Adding a new template with sample questions will give instructors more choices to choose from.

**Comment by damithc** [comment]
@sukanta-27 were the questions based on some other source/publications?

**Comment by sukanta-27** [comment]
@damithc Sir, a reminder.

**Comment by damithc** [comment]
> @damithc Sir, a reminder.

Received. Will get back soon.

**Comment by damithc** [comment]
Your templates have good questions. 👍 

The two you have proposed are alternatives for peer evaluations of a team project, for which we already have a template. I don't think users will know who to choose among multiple templates used for the same situation. If at all, we should give templates for different situations. e.g., peer evaluations of class presentations, peer feedback for class participation, student feedback for lesson, etc.

Another thing we can do is to provide a set of preset questions to choose from so that instructors can mix and match the questions to their situation. I'll open that as a separate issue as its a separate feature altogether.

**Comment by sukanta-27** [comment]
> If at all, we should give templates for different situations. e.g., peer evaluations of class presentations, peer feedback for class participation, student feedback for lesson, etc.

@damithc should I create templates for these? Can any of the questions in the above two template work in the suggested templates? Like can we use the rubric question or any other team project based questions for the template `peer feedback for class participation` (we may have to rephrase the questions a little bit to fit in the suggested situations)? Also, can you give an example for `class presentations` question? (I have a little confusion in that :sweat_smile: )

**Comment by damithc** [comment]
> should I create templates for these?
Yes, we can try doing one first. Note that there is an ongoing PR that modifies the current list of templates. Ideally, we should merge that first.

> Also, can you give an example for class presentations question?

This is a case where students (individually or as teams) do a presentation to the class. Example questions:

1. (ranking question): choose the top 3 presentations
2. (rubric) Evaluate presentations on these criteria
3. (essay) What did you like about the presentation?
4. (essay) Your suggestions to improve the presentation
5. (scale) Overall quality of the presentation
6. (scale) Usefulness of the presentation

**Comment by damithc** [comment]
@sukanta-27 shall we put this on hold for a while. Next week is going to be busy for mentors as GSoC students try to wrap up their work -- perhaps best not to start whole new features during this period. It's ok not to do this under your GSoC as long as you have done enough other work.

**Comment by sukanta-27** [comment]
> shall we put this on hold for a while?

@damithc I am okay with that. But I will like to have some feedback from @xpdavid and @bqnguyen94 on this too.

@xpdavid @bqnguyen94 Should we put this on hold until GSoC period ends? Will that be okay?

**Comment by bqnguyen94** [comment]
> shall we put this on hold for a while?

I am ok with this too 👍

**Comment by xyliew25** [comment]
Hi @damithc and all, so now we are adding new session templates based on situations, e.g. class presentations, class participation, lessons, etc., instead, right?

> This is a case where students (individually or as teams) do a presentation to the class. Example questions:
> (ranking question): choose the top 3 presentations
> (rubric) Evaluate presentations on these criteria
> (essay) What did you like about the presentation?
> (essay) Your suggestions to improve the presentation
> (scale) Overall quality of the presentation
> (scale) Usefulness of the presentation

If so, then I shall start with this?

**Comment by damithc** [comment]
@xyliew25 I'm still not sure if we want to spend time doing this, given the instructor is the one in the best position to set up questions to match their use cause. Even when creating a session to evaluate presentations, the questions will vary based on many things e.g., team or individual presentations, how many presentations per round (all present or only some present in each round), graded or not, objective of the presentation, etc.

Let me put this on hold for now.

**Comment by wkurniawan07** [comment]
If we don't wish to spend time on this, we better put a close. It can always be reopened.
