### ISSUE TITLE
Student: submit responses: use a more friendly way to choose evaluee

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8867]
Current: we use a drop-down box to choose the evaluee where the name of the evaluee is shown in alphabetical order
![image](https://user-images.githubusercontent.com/1673303/40877714-008f82c6-66b8-11e8-979b-e254c93ec0c9.png)

Problem: when choosing evaluees from the whole course (if the evaluee of the feedback path of the question is `students in the course`), the drop down can be long and the user needs to know the exact name of the evaluee to be able to locate it.

Suggested: show section and team and order by section/team so that it is easier to select the intended recipient. e.g.,
`Tutorial 1 : Team 1: Adam Smith`
`Tutorial 1 : Team 1: Jean Wong`

Better yet if that can be given as an option in the UI i.e., a check box for `sort by section/team`

It is also useful if the dropdown has a typehead-like behavior where the user can type some part of the evaluee name to locate the evaluee.

**Comment by mg14777** [comment]
@damithc I had a suggestion here. Would it be better to change the dropdown to a text box with autocomplete functionality ? The options will still be augmented with section and team info but the user will now type in keywords (team/section/student name) and presented with filtered choices.

**Comment by damithc** [comment]
> Would it be better to change the dropdown to a text box with autocomplete functionality ?

That requires the user to remember the spelling of at least some part of the name of each target evaluee. That may not always be the case. Intuitively, the drop down is the right widget here because it is a case of 'select from finite fixed choices'. It's just that we can make it friendlier to use.

**Comment by damithc** [comment]
To give some context, I have a similar case in my course and my workaround is to add the team name as a prefix to the name of students to force the team name to appear in the dropdown. When this issue is done, I hope I don't have to do that workaround any more.

**Comment by thikhinab** [comment]
May I know if this issue still persists with UI changes? If so what are the new UI requirements to be met.

**Comment by damithc** [comment]
> May I know if this issue still persists with UI changes? If so what are the new UI requirements to be met.

@thikhinab for a start, I think we can do the following:

> Problem: when choosing evaluees from the whole course (if the evaluee of the feedback path of the question is `students in the course`), the drop down can be long and the user needs to know the exact name of the evaluee to be able to locate it.
> 
> Suggested: show section and team and order by section/team so that it is easier to select the intended recipient. e.g., 
>`Tutorial 1 : Team 1: Adam Smith`
> `Tutorial 1 : Team 1: Jean Wong`

**Comment by thikhinab** [comment]
@damithc  Noted prof. Will work on it and update you.
