### ISSUE TITLE
StudentProfileAttributesTest: fix instability due to modified timestamp comparison

### ISSUE THREAD

**Issue by tshradheya** [TEAMMATES/teammates#8871]
- **Environment**:  [cd9a536](https://github.com/TEAMMATES/teammates/commit/cd9a5365cfed580bae5d1bf15f2994a921e31f03)

**Description of feature/enhancement**

This is an enhancement to the build process

`toEntity()` does not use the original modified date so we need to ensure they are the same.

**Comment by wkurniawan07** [comment]
Closing as the comparison of modified date has been removed.
