### ISSUE TITLE
Instructor: comment on responses: support entering comments for each response from view GQR

### ISSUE THREAD

**Issue by nidhi98gupta** [TEAMMATES/teammates#8872]
- **Environment**: `master` branch

**Description of feature/enhancement**
Instructor currently can only add comments from 3/5 views. This is enhancement to current comments feature i.e instructor should be able to add comment from Giver-Question-Recipient view.

**Comment by nidhi98gupta** [comment]
@damithc I have added a column for comments in GQR view.
![gqr](https://user-images.githubusercontent.com/24381442/41407167-3d2929a2-6fec-11e8-9da3-92bda8afba95.png)
I have a question. Is it a good idea to add `Moderate Response` button as well with `Add Comment` button. (Though we already have `Moderate Response` button at the top of every panel). 
If we don't put `Moderate Response` button in every row, then some of the table cells will remain empty. (Like last two rows of image)

**Comment by damithc** [comment]
> have a question. Is it a good idea to add Moderate Response button as well with Add Comment button. (Though we already have Moderate Response button at the top of every panel).

No objections.
