### ISSUE TITLE
Instructor: edit session: give a way to duplicate a question

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8876]
Suggestion: give a way to create a duplicate of a question in the same session
![image](https://user-images.githubusercontent.com/1673303/40955518-1f48638e-68bd-11e8-9c6e-172a128863e6.png)

Justification: it is possible for a session to have several variation of the same question

**Comment by damithc** [comment]
> If I am getting this right, does the duplicate button gives a list of questions from the same session to choose from instead of all available questions like copy button. Am I right?

In this case there is no need to choose from a list of questions. User clicks the 'duplicate' button on the question that needs to be duplicated.

**Comment by damithc** [comment]
And yes, the duplication happens within the session being edited.
e.g.,
1. Create an empty session.
2. Create a new question to evaluate creativity.
3. Duplicate the previous question and modify the copy to evaluate punctuality in a similar way to the first question.
...

**Comment by sukanta-27** [comment]
Oh! I misunderstood the functionality. Yes, that will be helpful, as navigating the required question from copy question button is sometimes very tiresome.
