### ISSUE TITLE
Instructor: add question to session: provide sample questions to choose from

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8877]
Suggestion: When adding new questions to a session, we can provide an option `Choose from sample questions` where the user get to select from a bunch of ready-made questions.

![image](https://user-images.githubusercontent.com/1673303/40955995-5071143a-68c0-11e8-8f3d-fd7e5879f457.png)

Justification:
* Reduces the work to be done by instructors as they can create questions by modifying sample questions to match their needs.
* Serves as a way to educate users about the various questions types we have and different ways they can be used. 

Things to note:
* This is a major feature. Needs to be done by someone reasonably familiar with the sessions feature.
* There is some overlap between this and the instructors help page (as both will have sample questions).

**Comment by jacoblipech** [comment]
@damithc I'd like to work on this issue. 

Currently when instructors create a session, there is an option to create `session using templates` and there are 5 sample questions from it. Upon clicking on `Choose from sample`, do you want a modal to be popped up where the instructor can choose to select from the sample questions and add any of these questions to the session?

**Comment by damithc** [comment]
> Upon clicking on Choose from sample, do you want a modal to be popped up where the instructor can choose to select from the sample questions and add any of these questions to the session?

Yes, that's what I had in mind. Other suggestions welcome.

**Comment by jacoblipech** [comment]
@damithc I have a question on the design of the code. When populating the template questions which are stored in a `json` file format, is it necessary to load them using a AJAX request similar to #5567?

I read up on AJAX and it seems like AJAX has a better performance and reduce traffic between client and server but less secure. Currently, there are only 5 sample questions so I think an AJAX request may be unnecessary but I presume more template questions will be added so an AJAX request would be better? 

What is your take on this?

**Comment by damithc** [comment]
I don't think there's any need to use AJAX for loading sample questions, at least not at this stage.
