### ISSUE TITLE
Instructor: edit student details: resend past links to the new email not working

### ISSUE THREAD

**Issue by tanhengyeow** [TEAMMATES/teammates#8880]
**Environment**: 
`master` branch @ 7e957b5

**Steps to reproduce**
1. Login as instructor
2. Go to sample course/any courses with past sessions
3. Edit a student
4. Change the email of the student to a valid email
5. Click `Yes, save changes and resend links` when the modal box pops up
![image](https://user-images.githubusercontent.com/25320782/41024600-47bbfd22-69a2-11e8-9236-c28ad4bf31a2.png)

**Expected behavior** 
- Instructor course details page showing the following status box: 
![image](https://user-images.githubusercontent.com/25320782/41024211-314e8574-69a1-11e8-8457-a3634d67792d.png)

- Actual email sent out in staging/production environment to the new valid email. Example below:
![image](https://user-images.githubusercontent.com/25320782/41024292-70844a8a-69a1-11e8-9201-03ad124278b9.png)

**Actual behaviour**
- Instructor course details page showing the following status box: 
![image](https://user-images.githubusercontent.com/25320782/41024329-8ac7e320-69a1-11e8-8604-29ea6dc0be2e.png)

- **No** email is being sent out (tested in my staging server).

**Additional info**

@damithc I figured out what caused the issue. If you can replicate this and think it is worth fixing, I can submit a PR for this asap.

**Comment by damithc** [comment]
Looks like it's not working in the live server either. Good catch @tanhengyeow
