### ISSUE TITLE
Trouble Setting up Development Environment (npm install issue)

### ISSUE THREAD

**Issue by Dave-Crosslin** [TEAMMATES/teammates#8885]
- **Commit SHA:** 
- **Operating System: Linux Mint Sonya**
- **JDK Version: 1.8.0_171**
- **Node.js Version: 8.11.2**
- **Google Cloud SDK Version: 204.0.0**
- **app-engine-java 1.9.64**
- **app-engine-python 1.9.70**
- **bq 2.0.34**
- **core 2018.06.04**
- **gsutil 4.31**
- **Eclipse / IntelliJ Version (if applicable): 4.6.3**
- **Firefox / Chrome Version (if applicable):**

**What I was trying to do / What I need help with**
Hello! I am setting up the development environment for TeamMates and on #3 of Step 3 which is:

3. Run this command to download the necessary tools for JavaScript development:

npm install

Verification: A folder named node_modules should be added to the project root directory.
---------------------------------------------------------------------------------------------------------------------
I get this message in my terminal when I try to run npm install:
![screenshot from 2018-06-09 18-27-17](https://user-images.githubusercontent.com/34947783/41196635-0ed70434-6c13-11e8-856b-f8c75fafd4a0.png)

I have searched for help in understanding the meaning of the message and how to fix this, but I have not been able to find the solution. I have checked through the open and closed issues here and on various other sites.I verified that each tool necessary is installed up to this point in the Develepmont Environment setup guide and I have listed those at the top. It may also be worth mentioning that I tried the next procedure, #4 of Step 3 and got the error:

bash: ./gradlew: No such file or directory

If there is any more relevant information that I could give to aid in solving this problem please tell me.
Any help getting this set up would be greatly appreciated! I look forward to contributing to TeamMates.

**Comment by tshradheya** [comment]
You need to run npm install in the directory wherr you forked Teammates repo. `npm install` uses the pacakage.json file to install the required dependencies.

So go to the location where teammates is cloned in your local PC and run the command there

**Comment by Dave-Crosslin** [comment]
Thank you! That solved this issue, Development Environment appears to be set up.
