### ISSUE TITLE
I would like to help migrate this project to spring framework, could we please have some issues created for it?

### ISSUE THREAD

**Issue by nvnmandadhi** [TEAMMATES/teammates#8887]

**Comment by damithc** [comment]
@nvnmandadhi at the moment we don't have any plans to move in that direction.

**Comment by nvnmandadhi** [comment]
Oh, okay. No worries. I would like to contribute to this project, is browsing through the issues an only option?

**Comment by damithc** [comment]
> Oh, okay. No worries. I would like to contribute to this project, is browsing through the issues an only option?

That's the recommended option. 🙂
