### ISSUE TITLE
Instructor: edit course details: add a cancel button to terminate the process of editing course

### ISSUE THREAD

**Issue by tanhengyeow** [TEAMMATES/teammates#8892]
**Environment**: 
`master` branch @ 472e202cb9fdcb6ec29fcf80b45d07d1e137ef9e

**Current scenario of editing course details**:
![current](https://user-images.githubusercontent.com/25320782/41334713-26c888de-6f19-11e8-9b85-561181fbbb2a.gif)

**Proposed suggestion**:
It would be ideal if we have a cancel button to terminate the process of editing course. This allows a more consistent UX with the current behavior of editing an existing instructor as shown below.

![good to have](https://user-images.githubusercontent.com/25320782/41334786-59b06b04-6f19-11e8-9139-3443206d0780.gif)

**Comment by damithc** [comment]
@tanhengyeow do you think this is suitable for first-timers?

**Comment by tanhengyeow** [comment]
@damithc It might a little harder than a first-timer issue as the feature spans the full system. #8756 is a rough estimate of the scale involved.

**Comment by czarska** [comment]
I'm a first-timer but if there are no free issues labeled as d.first-timers, I would like to try to work on it

**Comment by tshradheya** [comment]
@czarska Go ahead 👍 You can refer to #8756 which was also about adding a `Cancel` button

**Comment by czarska** [comment]
I have a problem because every time I'm trying to add new instructor I get 'Cannot send Ajax Request!' error. Am I doing something wrong?

**Comment by tanhengyeow** [comment]
@czarska Make sure you ran `npm install` as shown [here](https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md#step-3-set-up-project-specific-settings-and-dependencies) and also check that you have built your javascript files as shown [here](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#building-javascript-files).

**Comment by czarska** [comment]
I've started all over agian and now It works, thanks. Do we need test?

**Comment by tanhengyeow** [comment]
It is always ideal to add tests for new behavior. How comprehensive the tests are depend on cost benefit analysis. You may want to take a look at some existing tests on how the behavior of buttons are tested.

**Comment by madanalogy** [comment]
This has been resolved by #9949
