### ISSUE TITLE
Testing: unstable behaviour in CI Config.APP_URL can be null sometimes

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#8898]
`readAppUrl()` cannot get environment object in GAE properly and result in the following excpeiton
```
java.lang.AssertionError: MalformedURLException for [null/page/instructorCourseJoin]: no protocol: null/page/instructorCourseJoin
	at teammates.common.util.Assumption.fail(Assumption.java:61)
	at teammates.common.util.Url.<init>(Url.java:22)
	at teammates.common.util.AppUrl.<init>(AppUrl.java:9)
	at teammates.common.util.Config.getAppUrl(Config.java:134)
	at teammates.test.cases.browsertests.AdminHomePageUiTest.testCreateInstructorAction(AdminHomePageUiTest.java:88)
	at teammates.test.cases.browsertests.AdminHomePageUiTest.testAll(AdminHomePageUiTest.java:53)
	...
```

- **Environment**: `master` branch at commit d521d365adbc619d02d7b32b631e1b17153ba353. 

**Steps to reproduce**
- Set up Local Server
- Run **only** `AdminEmailPageUiTest`
- Exception above will be thrown

**Expected behaviour**
- Test should pass

**Actual behaviour**
- Exception throw

**Additional info**
In `BaseComponentTestCase`, we set up GAE simulation and `EnvironmentAttributesWithApplicationHostnameSet`. Therefore `Config.readAppUrl` can successfully read the host name which is fine (all action tests will pass). If a test doesn't use `gaeSimulation.setup();`, the hostname will not be set and `Config.APP_URL` will be `null`. Subsequent call to `Config.getAppUrl()` will cause the above exception.

My guess why the bug is not obvious to find: In CI environment, TestNG will reuse thread to execute test. If we are lucky, we get the thread where `gaeSimulation.setup();` is called and the hostname is set -> no error. It is happened that previously all tests which use `Config.getAppUrl()` get the "lucky" thread. 

Suggested solution:
Move the hostname setup logic to `BaseTestCaseWithMinimalGaeEnvironment`. Make all test cases which use `Config.getAppUrl()` to extend `BaseTestCaseWithMinimalGaeEnvironment`

**Comment by sukanta-27** [comment]
Will work on it.
