### ISSUE TITLE
Instructor: Edit distribute points question: reorder options using drag and drop

### ISSUE THREAD

**Issue by mg14777** [TEAMMATES/teammates#8915]
**Current**
In order to reorder options user needs to copy text between options
![image](https://user-images.githubusercontent.com/11634699/41678876-411f0f18-74c4-11e8-8032-96dff97bdb44.png)

**Suggested**
Ability to drag and drop option boxes to move them around
Similar to [#8889](https://github.com/TEAMMATES/teammates/pull/8889)

**Comment by samuelfangjw** [comment]
<img width="1215" alt="Screenshot 2022-01-20 at 2 54 35 AM" src="https://user-images.githubusercontent.com/60355570/150195959-511aa437-b3c6-49cd-b013-61bc77759bbc.png">

This feature seems to have been implemented already! I believe it's ok to close @madanalogy.

**Comment by madanalogy** [comment]
Thanks for the catch!
