### ISSUE TITLE
Instructor: view results: questions for ranking: show rank within team

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8918]
Context: Instructor viewing results of a session that has a question for ranking items (e.g., rank team members based on technical competence)

Current: In question stats, we show overall ranking of the students/items based on all rankings received

Suggested: In addition, also show ranking within the team when that makes sense e.g., Amy, Ben, Charlie is ranked 3, 23, 56 within the course but ranked 1, 2, 3 within the team.

Justification: Some instructors might base their grade on the rank within the team. Currently, they have to do an extra step to figure out the rank within the team.

Notes: the stat can be included in the downloaded csv as well

**Comment by SriSaiAnkitBasava** [comment]
i would like to work on this

**Comment by Dhiraj240** [comment]
@damithc Sir, i would like to work on this.

**Comment by vivekbhatnagar** [comment]
> Justification: Some instructors might base their grade on the rank within the team. Currently, they have to do an extra step to figure out the rank within the team.

Small typo here :  Some instructors might base their grade on the rank within the **course** [not team].

@damithc : suggest please.

**Comment by rrtheonlyone** [comment]
@damithc is this still a relevant issue?

If the table is like this:
<img width="445" alt="rankings_table_teammates" src="https://user-images.githubusercontent.com/10579415/50069804-a1da2c00-0206-11e9-9430-9dd98e18f545.PNG">

We are looking for a change (like a checkbox etc.) that allows for ranking by team as well is it? (or an additional statistics - e.g. ranking in team)

**Comment by damithc** [comment]
> We are looking for a change (like a checkbox etc.) that allows for ranking by team as well is it? (or an additional statistics - e.g. ranking in team)

@rrtheonlyone it can be an extra column in the table
