### ISSUE TITLE
Instructor: edit session: give more control over which stats are shown to result viewers

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8919]
Current: instructors can choose to make responses, give name, evaluee name, of a question visible to students but they do not have control over which stats to be shown.

Suggested: allow instructors to choose which stats are made visible to others

Justification: some instructors may want students to see the individual responses received, but not the overall stats

Notes:
* This enhancement is applicable to many question types. Can be done one at a time.

**Comment by JeremyJohson** [comment]
I would like to work on this issue

**Comment by wkurniawan07** [comment]
@damithc I don’t think this suggestion works. Stats are calculated based on the displayed response, so from the list of responses displayed, it is not difficult for anyone to work out the stats we displayed. The only thing we do is automating the process.

**Comment by damithc** [comment]
> @damithc I don’t think this suggestion works. Stats are calculated based on the displayed response, so from the list of responses displayed, it is not difficult for anyone to work out the stats we displayed. The only thing we do is automating the process.

Yes, that's true. Only makes sense if we show overall stats, but I'm not sure it's a direction we want to go. For one thing, calculation overall stats is expensive.
