### ISSUE TITLE
improve setting-up.md documentation

### ISSUE THREAD

**Issue by cybersol795** [TEAMMATES/teammates#8920]
The initial development environment setup documentations has some space for improvement. It can be written in shorter and clearer sentences.

**Comment by cybersol795** [comment]
If the owners of this project approve, I can make the revisions and create a pull request.

**Comment by tshradheya** [comment]
Could you provide more details on how you plan to improve the documentation? Maybe then we can decide if the proposed revisions are necessary or not.

**Comment by cybersol795** [comment]
Sure. I was reading the documentation and thought why not break long sentences into short sentences to make them easier to follow, fix typos and writing mistakes and so forth. 
The goal is not to significantly alter the technical aspect of the instructions but to only add to the clarity of the sentences.

**Comment by cybersol795** [comment]
Example,
Original:
Add a remote name (e.g `upstream`) for the main repo for your repo to keep in sync with, and then fetch the remote-tracking branches from the main repo.
Revised:
Add a remote name (e.g `upstream`) for your copy of the main repo and fetch the remote-tracking branches from the main repo to keep it in sync with your copy.
I can make revisions and create a PR for you so you can decide to reject or approve some of the them.

**Comment by tshradheya** [comment]
Although the suggestion seems valid but currently there is no need for such a PR. However, you can contribute to an `d.firstTimer` issue for e.g. #8921 to get started

**Comment by cybersol795** [comment]
Actually, I should have mentioned this earlier that I would love to contribute to other issues, however, I am contributing with the purpose of practicing how to revise and improve technical documentation for our technical writing course in university. It will really help me if you allow me to edit the documentation part of this project, but if you would rather not have that part changed yet it is completely understandable.

**Comment by tshradheya** [comment]
@cybersol795 In that case go ahead and create a PR. We can decide as to what is necessary while reviewing the PR. :+1:

**Comment by damithc** [comment]
@cybersol795 indeed we welcome any improvements to our docs.
