### ISSUE TITLE
Instructor: view results: add missing space and icon for 'Edit' link

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8921]
Context: an instructor viewing results of a session

Current:
![image](https://user-images.githubusercontent.com/1673303/41953417-34f3c0dc-7a08-11e8-9002-8b8b7b77b0b6.png)

Suggestion:
Add a space before the `[Edit]` link. We can also add an icon before the word `Edit` too.

**Comment by ah91086** [comment]
I can take this one on!

**Comment by SriSaiAnkitBasava** [comment]
i would like to take this.

**Comment by tanhengyeow** [comment]
@SriSaiAnkitBasava Since there is already an open PR for this issue, take a look into other issues marked `d.FirstTimers`. If there aren't any available at the moment, you can look into other `d.Contributors` issues.
