### ISSUE TITLE
Instructor Feedback Results Page: Inconsistent behaviour between results downloaded and shown

### ISSUE THREAD

**Issue by jacoblipech** [TEAMMATES/teammates#8929]
While trying to work on issue #8002, I found out an inconsistency problem in the `InstructorFeedbackResultsPage` when viewing the data on the webpage and after downloading. 

Currently, when populating the results by selecting sections such as `Tutorial Group 2`, it only shows 1 response as seen below. (Both `givers` and `recipients` have to be from `Tutorial Group 2`)
<img width="762" alt="screen shot 2018-07-02 at 3 33 41 pm" src="https://user-images.githubusercontent.com/28522090/42150863-b64113f2-7e0d-11e8-98ab-4ac33cbf9163.png">

However, when I download the data, 4 responses are shown instead. (In this case, only the `givers` have to be from `Tutorial Group 2`)
<img width="934" alt="screen shot 2018-07-02 at 3 33 51 pm" src="https://user-images.githubusercontent.com/28522090/42150891-c7861892-7e0d-11e8-9477-306453089aca.png">

Upon investigating, each individual question panel on the website is loaded by AJAX upon clicking while the downloaded file uses the data loaded onto the page from the start. Hence these two different ways to filter the data by `section`, caused this inconsistency. 

I feel that the default way to populate data should follow the latter one where only the `givers` have to be the selected `section`. @damithc What do you think?

**Comment by damithc** [comment]
> I feel that the default way to populate data should follow the latter one where only the givers have to be the selected section. @damithc What do you think?

Yes, let's make it consistent.

**Comment by tshradheya** [comment]
Verified this inconsistency. Good catch @jacoblipech 

But we need to define what we mean by "consistent". I feel the behavior of showing response only if giver and recipient are both from the same tutorial group makes more sense especially for "group by question" setting. 
Because if you do "group by GQR" then you can see reponses of when giver is in "tutorial group 2" and giving reponses to anyone else which already makes sense.


Maybe we should change the filtering process for downloaded data than changing for what to read from database

@damithc ?

**Comment by jacoblipech** [comment]
@tshradheya I figured it may be subjective what the instructor would want to see by filtering the `section`. Hence I am working on #8002 to remove the ambiguity. 

I will ensure that the downloadable data and data shown be consistent after filtering. I was hoping to make it consistent first so that future developers may take note of this issue. I think both way works for now but I can adjust accordingly.

**Comment by damithc** [comment]
> @tshradheya I figured it may be subjective what the instructor would want to see by filtering the section. Hence I am working on #8002 to remove the ambiguity.

yes, that works too.

On a related note, I don't think we should use 'both giver and receiver in the same section' as the default. If we do, cross-section responses cannot be seen under the giver's section or the receiver's section. This is going to be a problem when the course is too big to support the 'all sections' view. In that case the instructor doesn't have any way to view cross-section responses.
