### ISSUE TITLE
Instructor: Feedback Session: Improve display of more information for advanced settings

### ISSUE THREAD

**Issue by mg14777** [TEAMMATES/teammates#8932]
**Description of feature/enhancement**
Improve the display of helpful information for tweaking advanced settings while creating a new feedback session.

**Current**
Most of the information is delivered through tooltips which are verbose. 
![image](https://user-images.githubusercontent.com/11634699/42174478-675d6710-7e1a-11e8-9d02-a8ec0fb96f2f.png)

![image](https://user-images.githubusercontent.com/11634699/42174527-93415102-7e1a-11e8-8271-f06238585f69.png)

Using a dedicated `More Info` link for such settings will be more user friendly. The information can be displayed as a modal.

**Comment by damithc** [comment]
This is a valid point. one advantage of tool tips is that they don't need additional links/icons in the UI, which helps to reduce UI clutter. We should use modals only when the tooltip option doesn't fit. Another option is to use a more powerful tooltip/popover mechanism that allows rich text formatting.

**Comment by mg14777** [comment]
@damithc Does using a modal like this look good ?

![adv_settings_modal1](https://user-images.githubusercontent.com/11634699/43365138-ef1968d8-931f-11e8-8e28-2748e3df97ec.gif)

![image](https://user-images.githubusercontent.com/11634699/43365140-f3c92fd0-931f-11e8-95b5-de7795331a1a.png)

**Comment by damithc** [comment]
Generally OK. Some comments:

* Best not to format `Note`, `At` and `Submission opening time` the same way. `Note` is different from the other two.
Something like this?
>**Options**:
>* `At`: ...
>* `Submission opening time`: ...

* Users don't normally use the phrase _custom date_. That's a programmer term.

**Comment by wkurniawan07** [comment]
No longer applicable; current tooltips in the said place are simple.
