### ISSUE TITLE
Instructor: edit student details: email contains raw template literals after resending past links to the new email 

### ISSUE THREAD

**Issue by tanhengyeow** [TEAMMATES/teammates#8935]
**Environment**: 
`master` branch

**Steps to reproduce**
1. Login as instructor
2. Go to sample course/any courses with past sessions
3. Edit a student
4. Change the email of the student to a valid email
5. Click `Yes, save changes and resend links` when the modal box pops up
![image](https://user-images.githubusercontent.com/25320782/41024600-47bbfd22-69a2-11e8-9236-c28ad4bf31a2.png)

**Expected behaviour**

- No raw template literals at highlighted area:

![image](https://user-images.githubusercontent.com/25320782/42210689-3c6a133a-7ee4-11e8-8fdb-ddb857dc00f3.png)

**Actual behaviour**

- Raw template literals at highlighted area:

![image](https://user-images.githubusercontent.com/25320782/42210783-77938b4e-7ee4-11e8-882a-ab8540d22165.png)

**Additional info**
- Whole process tested in staging server.
- @damithc is this reproducible in the production server? I've found out what's causing the issue.

**New updates**

This case is only reproducible when an instructor changes a student's email who has not joined a course using his/her googleID to another valid email.

**Comment by tanhengyeow** [comment]
@damithc Don't think so as the commits after `v6.6.0` didn't deal with email generation. Is it reproducible on your staging server? Also, should I still submit a fix for this since the production server isn't affected?

**Comment by damithc** [comment]
Go ahead and submit a fix. If possible, a test too so that we can confirm the problem exists and the PR fixes the problem.
