### ISSUE TITLE
Duplicated HTML ID attribute in a single HTML page

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#8941]
While reviewing #8897.

We have many duplicated ID attributes in a single page, which makes the page not HTML standard compliant. 

Haven't count the occurrences of the duplications. May need serious refactor to remove them.

Impact: Not critical as our JS won't use the duplicate ID to select element.

Please discuss here before actual refactor goes.

**Comment by dalessr** [comment]
I've changed some in #8928 , but there are still some duplicate IDs (i.e. instructorHelpSessions.jsp). I think this usually happens in JSP files due to copying & pasting similar codes.

**Comment by Michaellin250** [comment]
Is this issue closed?

**Comment by xpdavid** [comment]
Should be resolved in V7 (current master)

**Comment by wkurniawan07** [comment]
Fixed in V7
