### ISSUE TITLE
Instructor: Feedback Session: question number drop down menu

### ISSUE THREAD

**Issue by ah91086** [TEAMMATES/teammates#8942]
I'm not sure if this is a non-issue, but if it isn't, I'd like to take it on. 

**Current:**  When editing a session you're given the option to change the question number only if the edit button has been pressed, so having a disabled drop down menu option that is identical to when it isn't disabled is somewhat misleading.
<img width="962" alt="screen shot 2018-07-02 at 4 41 44 pm" src="https://user-images.githubusercontent.com/20053947/42403926-d2174392-8139-11e8-8edf-6d3f44b0d349.png">

**Suggesting:** Having the questions look like this before the edit button is pressed, and then having the drop down menu option appear when the edit button is pressed.
<img width="1006" alt="screen shot 2018-07-02 at 4 41 37 pm" src="https://user-images.githubusercontent.com/20053947/42403932-df3fa2b2-8139-11e8-9ea8-70cd1265aca4.png">

**Comment by damithc** [comment]
@ah91086 go ahead 👍 

We can also have a dot/colon after question number e.g., **Question 1: Is this good?**
