### ISSUE TITLE
Update user map as at Jun 2018

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8943]
To be done after #8814 

Covers new users from May-June 2018

New entries to consider:

Country| University
-- | --
Australia | Deakin University
Australia | Dungog High School
Australia | Monash University
Australia | RMIT University
Australia | University of Technology Sydney
Bangladesh | American International University-Bangladesh
Belgium | Universiteit Hasselt
Brazil | Universidade Anhembi Morumbi
Brazil | Universidade Federal da Bahia
Brazil | Universidade Federal de São João del-Rei
Canada | Argyle School
Canada | Laval University
Canada | Schulich School of Business, York University
Canada | Simon Fraser University
Chile | Universidad Adolfo Ibañez
Chile | USM
China | TsingHua Universtiy High School International
Cyprus | University of Cyprus
Hong Kong | HKU School of Professional and Continuing Education
Hong Kong | The University of Hong Kong
Hong Kong | The University of Hong Kong
India | JK Lakshmipat University
Indonesia | Universitas Pendidikan Indonesia
Korea | Soongduk Middle School
Malaysia | ASIA SCHOOL OF BUSINESS
Malaysia | Universiti Teknologi Malaysia
Malaysia | Universiti Tenaga Nasional
Malaysia | University Malaya
Mexico | CETYS
Mexico | ITESM
Netherlands | Avans University of applied sciences
Netherlands | Fontys
Netherlands | Hogeschool Utrecht
Netherlands | HvA
Netherlands | mboRijnland
Netherlands | Saxion University of Applied Sciences
New Zealand | University of Auckland
New Zealand | University of Otago
Oman | Sultan Qaboos University
Portugal | University of Minho
Portugal | University of Trás-os-Montes e Alto Douro
Russia | Tomsk State University
Singapore | Institute of Technical Education
Singapore | Weave
Spain | IE University
Thailand | King Mongkut's University of Technology Thonburi
UK | East Tennessee State University
UK | Kingston University
UK | Plymouth University
UK | Royal Veterinary College
UK | Swansea University
UK | University of Bath
UK | University of Bradford
UK | University of Portsmouth
UK | University of Sheffield
USA | American International School of Utah
USA | Atlantic Technical College & Technical High School
USA | Belmont University
USA | Brigham Young University - Idaho
USA | California Polytechnic State University
USA | California State University, Fresno
USA | California State University, Long Beach
USA | Central Carolina Community College
USA | Central Connecticut State University
USA | Central Michigan University
USA | College America
USA | College of the Holy Cross
USA | Cornell University
USA | Drexel University
USA | duPont Manual High School
USA | East Tennessee State University
USA | El-Abbadi Charter Academy
USA | Frontier Nursing University
USA | Gann Academy
USA | Georgia Institute of Technology
USA | Gulliver Schools
USA | Immaculata Catholic School
USA | Ithaca College
USA | Ithaca College
USA | Kansas State University
USA | Kennesaw State University
USA | Lawrence Technological University
USA | Lincoln-Sudbury Regional High School
USA | Louisiana State University
USA | Maryville University St. Louis
USA | Methuen High School
USA | Milwaukee School of Engineering
USA | Mounds View Public Schools
USA | Nazareth College
USA | New York Institute of Technology
USA | Northeastern University
USA | Ohio University
USA | Purdue University
USA | Saline High School
USA | Santa Clara University
USA | St. Philip's College, Alamo Colleges District
USA | Thales University
USA | The University of North Carolina at Charlotte
USA | UC Berkeley
USA | University at Buffalo
USA | University of California Irvine
USA | University of California, Los Angeles
USA | University of California, San Diego
USA | University of Florida
USA | University of Hartford
USA | University of Illinois, Urbana-Champaign
USA | University of Iowa
USA | University of Michigan
USA | University of Minnesota
USA | University of North Carolina at Chapel Hill
USA | University of South Alabama
USA | University of Southern California
USA | University of Texas Rio Grande Valley
USA | University of the Incarnate Word
USA | Virginia Commonwealth University
USA | West Virginia University
USA | LECOM
USA | Miami Dade College - Kendall
USA | Plymouth University
USA | Uniformed Services University

**Comment by tomignarri** [comment]
I'd like to take this on.

**Comment by tshradheya** [comment]
@tomignarri Go ahead 👍

**Comment by tshradheya** [comment]
Since the PR for #8814 isn't progressing fast, I am okay with you doing #8814 as long as you follow up after every review at a quick pace. Also make sure to not the same mistakes that were done in #8821

**Comment by ooxaam** [comment]
Hi, Can I pick this task ?

**Comment by n1ckyb** [comment]
Hi, if no one is picking this up, can I pick it up?

**Comment by jsaroya** [comment]
Hello, I'm a first timer and interested in working on this.

**Comment by sleethma** [comment]
First time contributor, can I take this one?

**Comment by mihirg008** [comment]
Can I take to solve this problem?
