### ISSUE TITLE
Instructor: Delete sessions successfully even the instructor does not have privilege

### ISSUE THREAD

**Issue by dalessr** [TEAMMATES/teammates#8963]
**Environment:**
`master` branch

**Description:**
Set instructor's privilege as: custom - can edit/delete course, but cannot create/edit/delete sessions. In this case, even though the instructor is not allowed to delete a session (`delete` button is disabled in Instructor Feedback Sessions Page), he can still achieve that by deleting a course from Instructor Home/Courses Page. The reason is that, when deleting a course, the corresponding sessions/instructors/students will also be deleted directly in `CoursesLogic.java` without checking for privileges on those entities.

![teammates-image-1](https://user-images.githubusercontent.com/22449685/42735688-46cbebb8-888b-11e8-829e-cec918e81208.png)

**Justification:**
Though in most cases if an instructor is allowed to modify a course, usually he should also be allowed to modify the corresponding sessions/instructors/students inside, but this is indeed an issue since we have given users this kind of option.

Open for suggestions :)

**Comment by damithc** [comment]
The issue is indeed valid. We can force-tie session permissions to course permissions to prevent this "nonsensical" permission setting, but probably not worth the effort. Putting on hold.

**Comment by damithc** [comment]
l
