### ISSUE TITLE
InstructorHomePageUiTest & InstructorCoursesPageUiTest failing on 'recycling-bin' branch

### ISSUE THREAD

**Issue by dalessr** [TEAMMATES/teammates#8971]
**Environment**
`recycling-bin` branch

**Comment by tshradheya** [comment]
Can you also investigate why `InstructorCoursesPageUiTest` is failing in AppVeyorBuild. 

[Build](https://ci.appveyor.com/project/damithc/teammates/build/1.0.1063)

**Comment by dalessr** [comment]
@tshradheya Okay testing on it now

**Comment by dalessr** [comment]
@tshradheya I think the problem is that WebElement.click() [fails](https://community.atlassian.com/t5/Answers-Developer-Questions/Selenium-WebElement-click-does-not-actually-click-element/qaq-p/561928) in Selenium web driver.
