### ISSUE TITLE
Instructor: delete course: rephrase message shown when there are no more courses left

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8980]
v6.7.0

Steps: 
1. Login as an instructor
2. Delete courses until no courses are left

Current status message shown after the last course has been deleted:
![image](https://user-images.githubusercontent.com/1673303/43126197-a33f9c12-8f5e-11e8-84fc-3705d38b48c7.png)

Suggested: rephrase as `You do not seem to have any courses. Use the form above to create a course.`

Reason: the current phrasing is not accurate as the instructor could have created courses and deleted them later.

**Comment by senguttuvan** [comment]
Hi. I'd like to work on this!
