### ISSUE TITLE
Instructor: delete session: rename buttons in alert message to match question being asked

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8981]
v6.7.0

Steps:
1. Login as an instructor
2. Delete a session

Current alert shown:
![image](https://user-images.githubusercontent.com/1673303/43126509-78b1d66c-8f5f-11e8-82d0-97feafc89629.png)

Suggested:
Rename buttons to `No, cancel the operation` and `Yes` to match the question being asked in the alert.

**Comment by AmineToualbi** [comment]
Hi, 

I would like to try myself to that.

**Comment by AmineToualbi** [comment]
After spending my whole afternoon trying to download the Google Cloud plug-in, I haven't been able to do it. It seems to be a certificate problem & the many solutions I tried didn't get me anywhere. Anyone can pick this issue up, I'm sorry.

**Comment by mg14777** [comment]
@AmineToualbi Still working on this ?

**Comment by YaroslavGnatyuk** [comment]
Hi guys, I found solution for this issue. Can I post it?

**Comment by dalessr** [comment]
@YaroslavGnatyuk You can follow the steps [here](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#fixing-issues) to create a PR for it :)

**Comment by dalessr** [comment]
> As far as I can see this hasn't been completed yet.
Could i please contribute in here?

@k4iz3n1994 Since the PR for this issue isn't progressing fast, you can work on this. You may want to look through #9009 to see what we expect.

**Comment by k4iz3n1994** [comment]
Hi, I am indeed taking this issue just to confirm!

**Comment by k4iz3n1994** [comment]
Ready for review https://github.com/TEAMMATES/teammates/pull/9056

**Comment by laurensdegilde** [comment]
Is this still open? Happy to take it!
