### ISSUE TITLE
Instructor Login Impossible

### ISSUE THREAD

**Issue by AmineToualbi** [TEAMMATES/teammates#8984]
Hi, 

I just joined this project recently. I set up everything & the app runs smoothly on my computer. 

I am trying to log in as an instructor but I can't do it. I am following the steps described here: https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#logging-in-to-a-teammates-instance

I tried logging in as the admin & adding the instructor. When I try to find a join link, I don't see it & when I try to log in with the email I've given, it doesn't work. 

I get this message: 

<img width="1280" alt="screen shot 2018-07-25 at 20 31 06" src="https://user-images.githubusercontent.com/29878624/43234410-df9a8d2a-9049-11e8-85ed-b062c1badd50.png">

I'd appreciate any help so that I can get into my first issue.

**Comment by jacoblipech** [comment]
<img width="938" alt="screen shot 2018-07-26 at 10 55 26 am" src="https://user-images.githubusercontent.com/28522090/43238825-6e69f39c-90c2-11e8-974c-b35af9b1de66.png">

Did you see a join link like the one above when you first created the instructor? 

Upon clicking it, you will be directed to the course confirmation page. However as you are logged in as `admin` at the moment, so you need to copy the join link and log out as admin. After logging out of `admin`, you can paste the join link and log in as the new instructor added to confirm as instructor.

**Comment by AmineToualbi** [comment]
I do not have that link. 

Here is what I have no matter how many times I press the "Add Instructor" button.

<img width="1280" alt="screen shot 2018-07-25 at 23 45 28" src="https://user-images.githubusercontent.com/29878624/43240516-e3b5c562-9064-11e8-8e44-45faa08fea6d.png">

What could be happening wrong?

**Comment by dalessr** [comment]
@AmineToualbi If you scroll down can you see an error message?

**Comment by AmineToualbi** [comment]
@dalessr No, not really. There's nothing down there. You can see the white part is because I am trying to scroll down. 

<img width="1280" alt="screen shot 2018-07-25 at 23 53 40" src="https://user-images.githubusercontent.com/29878624/43240752-0a024730-9066-11e8-81e2-5bfb529c95c1.png">

**Comment by damithc** [comment]
Do you see any errors in the TEAMMATES web server console?

**Comment by damithc** [comment]
Perhaps you can post here the output of the console in which you started the server?It'll help others to debug the problem. Before copying the output here, remember to click the `Add Instructor` button once.

**Comment by AmineToualbi** [comment]
I do not get any error when I press the button. However, I have stuff showing up when I access the admin page before. 

`INFO: TEAMMATESLOG|||adminHomePage|||adminHomePage|||true|||Admin|||Unknown|||test@example.com|||Unknown|||Admin Home Page Load|||/admin/adminHomePage|||test@example.com%2018072612393055|||20
Jul 26, 2018 12:39:30 AM com.google.appengine.tools.development.jetty9.LocalResourceFileServlet doGet
WARNING: No file found for: /js/googleAnalytics.js
Jul 26, 2018 12:39:30 AM com.google.appengine.tools.development.jetty9.LocalResourceFileServlet doGet
WARNING: No file found for: /js/adminHome.js`

**Comment by dalessr** [comment]
Hmm...seems that you didn't [build JavaScript files](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#building-javascript-files) properly.

Stop the dev server and try entering the following commands in the root directory:
```
$ npm install
$ npm update
$ npm run dev
$ npm run lint
```
If there's no error showing in the console, start the dev server and try again :)

**Comment by AmineToualbi** [comment]
Here is what I get when I run those commands. 

<img width="596" alt="screen shot 2018-07-26 at 01 02 26" src="https://user-images.githubusercontent.com/29878624/43242578-dd60cef4-906f-11e8-9076-b47b1753f737.png">

After ignoring this & running the commands, I still get the same warnings. 

Any clue?

**Comment by AmineToualbi** [comment]
I had to restart my whole IDE after the commands & it works now! 

Thank you very much, can't wait to start working on my first issue. 👍
