### ISSUE TITLE
Warn if browser is not compatible with TEAMMATES

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9011]
It seems some of our features don't work in some Browsers e.g., IE
Should we detect the Browser and show a warning if the one detected is not known to be compatible to our code? i.e., Chrome, FF, Safari(?)

Reason: users using incompatible Browsers might think TEAMMATES is broken and ditch it without contacting us for help

**Comment by mg14777** [comment]
@damithc can you give an example of the features under consideration ?

**Comment by damithc** [comment]
No precise info. it's just that there were many cases where the user says something doesn't work and things starts working after they switch to chrome or firefox (the two browsers we use for testing). As we don't test on other browsers, there's always a chance that something doesn't work in them.

**Comment by mg14777** [comment]
hmm ok i'll have a look

**Comment by damithc** [comment]
I remember we had this long ago. Didn't realize we still have this. In any case, we need to upgrade the version numbers.  Furthermore, I was thinking of doing the reverse. i.e., detecting if they are using a recent version of Chrome or Firefox and giving a friendly warning 'TEAMMATES is best used in Chrome or Firefox' if they aren't.

**Comment by mg14777** [comment]
> detecting if they are using a recent version of Chrome or Firefox and giving a friendly warning 'TEAMMATES is best used in Chrome or Firefox' if they aren't

Should we update the existing script to do the same and add further enhancements ?

**Comment by damithc** [comment]
> Should we update the existing script to do the same and add further enhancements ?

Yes, I guess so.

**Comment by mg14777** [comment]
@damithc How does this look ?

![image](https://user-images.githubusercontent.com/11634699/43642140-441bda58-971e-11e8-8130-afaa391d7b17.png)

**Comment by damithc** [comment]
This should be enough.
`{{info icon here}} Please note that TEAMMATES works best in recent versions of Chrome or Firefox.`

**Comment by mg14777** [comment]
Oh and what should we update the version numbers to ?

**Comment by damithc** [comment]
> Oh and what should we update the version numbers to ?

@LiHaoTan what do you think?

**Comment by wkurniawan07** [comment]
Resolved in V7.
