### ISSUE TITLE
UI tests against live server: update automated login to match new Google login page

### ISSUE THREAD

**Issue by tshradheya** [TEAMMATES/teammates#9015]
Google has introduced a new login page that doesn't match with our current login script used by UI tests.

More information on #8997

**Comment by tshradheya** [comment]
Continuing conversation here.

@xpdavid, I think Google is sometimes even loading sign in which was used before #7251 was merged.

As shown in the screenshot, the `id` if `identifierTextBox` is `Email` which was used before(2 versions back?).

<img width="999" alt="screen shot 2018-08-02 at 9 21 10 pm" src="https://user-images.githubusercontent.com/12574756/43595431-4ebe1310-969a-11e8-9039-9fb525981ca0.png">

I am assuming that even the location from where I access matters and I am currently accessing from India :P

**Comment by xpdavid** [comment]
I guess it my due the network speed. In my school I can always get the new login page while in my home I sometimes get the old login page like the one above.

I believe the URL for the two login page are different. Maybe we could look into that.
