### ISSUE TITLE
Help Request: CI testing - occasional tests suite failing 

### ISSUE THREAD

**Issue by senguttuvan** [TEAMMATES/teammates#9024]
**Details**
./gradlew failedTests (equivalent - run from eclipse)
os.name: 'Windows 10'
java.version: '1.8.0_181' JDK - 8.0.1810.3
node.js: 8.11.3
Eclipse Version: Oxygen.3a Release (4.7.3a) Build id: 20180405-1200
Chrome : Version 67.0.3396.99 (Official Build) (64-bit)

**What I was trying to do / What I need help with**
I recently setup the project and tried to run the test suite before contributing. Some CI tests are failing with below signature-

Step which you are stuck -Running CI test suite
Failing test - teammates.test.cases.browsertests.TableSortTest
[image](https://user-images.githubusercontent.com/9861832/43693788-cdc39e90-98e4-11e8-9e64-13b800a4ad1b.png)

Expected -
15{*}0{*}-13.5{*}2{*}-2{*}-1.3{*}10.01{*}24{*}1{*}10.7{*}3{*}33{*}10.35{*}-0.001{*}10.3{*}

Actual -
<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml"><head>
    <meta charset="utf-8" />
    <title>Table Sorting Test Page - TEAMMATES</title>
    <link type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@3.1.1/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@3.1.1/dist/css/bootstrap-theme.min.css" rel="stylesheet" />
    <link type="text/css" href="/stylesheets/teammatesCommon.css" rel="stylesheet" />
  </head>

  <body>
..............

**Attempts to resolve the problem**
None - as this is my first time and so didn't want to touch any code

**Comment by sukanta-27** [comment]
@senguttuvan some tests may fail in the first try, rerun the failing test a few times to see if it passes or not.

**Comment by sukanta-27** [comment]
@senguttuvan some tests may fail in the first try, rerun the failing test a few times to see if it passes or not.

**Comment by senguttuvan** [comment]
@sukanta-27 yes I did rerun the test quite a bunch of times. However I don't see any changes in the result.
