### ISSUE TITLE
Data Persistence: Why using getByID in Objectify still cannot achieve strong consistency

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9025]
According to the documentation of google datastore: https://cloud.google.com/datastore/docs/articles/balancing-strong-and-eventual-consistency-with-google-cloud-datastore/#eventual-consistency-in-cloud-datastore, using key to access an object should give strong consistency. However, even we use ID to access entity in #8924, we still get https://github.com/TEAMMATES/teammates/issues/8452#issuecomment-406491726 error. Need to find out why.

**Comment by xpdavid** [comment]
Write a script to check this:

```java
        InstructorsDb db = new InstructorsDb();
        int count = 0;
        int fail = 0;

        db.deleteInstructorsForCourse("xp.test.course");

        SecureRandom ran = new SecureRandom();
        for (int i = 0; i < 100; i++) {
            String email = String.format("xp.xiaopu@gmail%d", ran.nextInt());

            Instructor testInstructor = new Instructor("xp.test", "xp.test.course", false, "XP", email,
                    "test", true, "XP", "");
            Instant save = Instant.now();
            ObjectifyService.ofy().save().entity(testInstructor).now();
            ObjectifyService.ofy().clear();
            Instant called = Instant.now();
            InstructorAttributes actual = db.getInstructorById("xp.test.course", email);
            ObjectifyService.ofy().clear();
            if (actual == null) {
                fail++;
            }
            count++;
            resp.getWriter().write(String.format("%d\n", called.toEpochMilli() - save.toEpochMilli()));
        }

        resp.getWriter().write("\nTotal Tries: " + count);
        resp.getWriter().write("\nFail Tries: " + fail);

        if (req.getParameter("test") != null) {
            db.deleteInstructorsForCourse("xp.test.course");
        }
```

Deployed into GAE

output
```
143 49 76 49 50 66 166 78 93 124 160 79 78 69 51 98 154 47 51 50 99 81 
53 50 100 52 48 55 50 52 76 52 50 49 53 76 51 133 51 51 51 50 49 50 48 
80 52 47 131 75 50 74 48 58 81 80 51 76 50 49 48 51 59 49 98 50 51 50 
75 73 99 51 52 66 81 79 50 53 52 50 235 51 51 52 48 61 50 76 50 52 49 
50 147 49 129 49 81 67 48 58 

Total Tries: 100 Fail Tries: 0
```

Entities really have been created in Datastore. The two calls (read and write) only have around 50ms interval. It seems that access by ID really achieve strong consistency. Still don't know why #8452 happen.

**Comment by damithc** [comment]
> @damithc Can check if #8452 happen recently.

No cases in last month.

**Comment by xpdavid** [comment]
Just come out with a possible scenario for #8452, very likely to be true I believe.

![image](https://user-images.githubusercontent.com/1673303/43118268-ba9d5df6-8f43-11e8-8c0e-c30de677dd4f.png)
Guess: The second last mail sending action is not the consequence the of last instructor add action. 

A user could enter an instructor and find out that the email is wrong. He will need to delete the instructor because he cannot change the email. 
![image](https://user-images.githubusercontent.com/13977235/45019369-bf6ff500-b05e-11e8-8287-2ff795e1cefa.png)

Then, he will add again (causing the last action). However, the send email task for the previously wrong email has been scheduled and executed as the second last action.
