### ISSUE TITLE
Instructor: delete all courses permanently: specify courses being deleted 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9038]
v6.9.0
Current:
![image](https://user-images.githubusercontent.com/1673303/43988028-f3d32316-9d5e-11e8-80b3-7fb8d6711ce5.png)

Problem: The message sounds like all courses are being deleted, which can scare the user.

Suggested: Rephrase to mention 'all courses in the recycle bin'. Even better if the number of courses can be mentioned. Still better if the courses can be listed.

**Comment by damithc** [comment]
@dalessr can do this one?

**Comment by dalessr** [comment]
![9038-image-1](https://user-images.githubusercontent.com/22449685/43990347-9fba0644-9d8d-11e8-8114-2a786e92e938.png)

@damithc Any inputs on this UI?

**Comment by damithc** [comment]
> Any inputs on this UI?

Looks good. May be rephrase the dialog title as well?

**Comment by dalessr** [comment]
`Confirm deleting all courses in Recycle Bin`?
