### ISSUE TITLE
Instructor: Edit Feedback Session: Add drag and drop feature for question option weights

### ISSUE THREAD

**Issue by mg14777** [TEAMMATES/teammates#9040]
**Description of feature/enhancement**
Add drag and drop feature for question option weights similar to one added for question options in [8889](https://github.com/TEAMMATES/teammates/pull/8889)
![image](https://user-images.githubusercontent.com/11634699/43991425-34f49138-9d8a-11e8-850b-0b1aeaa366a5.png)

**Comment by damithc** [comment]
To clarify, we don't need an independent drag-and-drop for weights per se. We need weights to be dragged along with the option as if the two are one element, as opposed to the current solution where the option is dragged and then the weight auto-adjusts as a second step.

**Comment by mg14777** [comment]
@damithc thanks for the clarification sir. i was under the assumption that weights need to be draggable independently. On second thoughts i think the cleanest way to do it would be to merge option and weight elements together in one container. In other words each option and its corresponding weight need to be wrapped as a single element. 

That would require quite a few changes if I am not wrong since the current logic treats options and weights as two independent lists and updates them separately. @sukanta-27 can confirm my assumptions. I was trying to see if there's something already provided by jquery API but haven't found anything so far. There's an option to connect lists but that allows users to drag from one list and drop to another which isn't what we want.

I had a question here though. This doesn't exactly give users the ability to reorder weights ? For instance, if a user wants to flip the weights of two options he would still have to manually change them ?

In any case I think its best to merge [8889](https://github.com/TEAMMATES/teammates/pull/8889) before commencing this one.

**Comment by pPris** [comment]
This issue might have been fixed too

https://user-images.githubusercontent.com/49683462/123841633-5ca02480-d942-11eb-8b2d-95ea4521ba9f.mp4

**Comment by damithc** [comment]
> This issue might have been fixed too

@pPris thanks for checking. Yes, I think the current status of the feature is good enough.
