### ISSUE TITLE
Investigate StudentHomePageUiTest and StudentProfilePage UiTest

### ISSUE THREAD

**Issue by tshradheya** [TEAMMATES/teammates#9041]
We have some questions left unanswered, but some of them are long-term and may not be as important:

- Parallel tests should not interfere with each other, and sequential tests should not interfere with parallel tests and vice versa.
- Testing with real accounts is definitely important but how many tests would need this? Should we instead do such testing in isolation and then also ensure that we have an abstraction of an account and the difference between a logged in account vs a masqueraded one is tested for and that the abstraction should not leak. Most other tests will then be guaranteed to be decoupled if all of them use masqueraded accounts.
- Each test removing its own data on teardown is a lot simpler to reason about but mainly because of costs we end up making it complicated. Is the cost overhead worth the developer time?

**Comment by wkurniawan07** [comment]
No longer relevant in V7.
