### ISSUE TITLE
Student: disable functionality to add comment in frontend if student has not answer question

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9042]
Due to our database design constraint, a comment from feedback participant should be associated with its corresponding feedback response. This implies: student should not be able to add comment if he/she has not answer the question yet.

The frontend UI currently enable this behaviour but it is just that the backend will ignore the comments from students.
https://github.com/TEAMMATES/teammates/blob/c8ed16c1d43da5c3ecc9b77b65aeb0e8278c29cd/src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSubmitPageUiTest.java#L326-L340

**Comment by damithc** [comment]
It is even better if respondents can comment without answering a question, for example, to explain why they are unable to answer.  But that can be a separate enhancement altogether.

**Comment by wkurniawan07** [comment]
Fixed in V7
