### ISSUE TITLE
Adding new instructor 

### ISSUE THREAD

**Issue by s3701799** [TEAMMATES/teammates#9043]
Hi, 

I just cloned this project recently as part of my assignment from a repository created by my educator. I have followed the steps on getting this project running and it works perfectly. 

I tried to add a new instructor through the application and it failed. You can find the image below as it says 'Cannot send Ajax Request!' after clicking the Add Instructor button. 

![issue](https://user-images.githubusercontent.com/41710124/44002364-b1aeef70-9e84-11e8-967e-3c413d9b48e7.jpg)

Console Message after Adding instructor: 
![console problem message](https://user-images.githubusercontent.com/41710124/44002370-c65d17bc-9e84-11e8-839c-30f36a8378c0.jpg)

I noticed that i have couple of problems found in the project from eclipse as well. 

Eclipse Problem messages: 
![eclipse problem message](https://user-images.githubusercontent.com/41710124/44002377-e5931b5e-9e84-11e8-8698-facb179672fc.jpg)

I'd appreciate any help given

**Comment by dalessr** [comment]
@s3701799 Can you check that the date/time format in your system is set as `English (Singapore)`?

**Comment by s3701799** [comment]
@dalessr the format for my system is English (Malaysia)

**Comment by dalessr** [comment]
Hmm...`English (Malaysia)` should be fine. But let's just try changing it to `English (Singapore)` first.

In your cloned repo, delete folder `node_modules`, and enter the following commands in the root directory:
```
$ npm install
$ npm update
$ npm run dev
```
Then restart your dev server & try adding new instructor again.

**Comment by s3701799** [comment]
@dalessr I did exactly as you said and i still cant add a new instructor, it still says "Cannot send Ajax Request!"

Console message:
![issue 2](https://user-images.githubusercontent.com/41710124/44027864-5a37a0c2-9f3b-11e8-8668-3e3dcce130e1.jpg)

**Comment by s3701799** [comment]
I get this message when i enter the './gradlew appengineRun' command

Execution failed for task ':compileJava'.
> Cannot find System Java Compiler. Ensure that you have installed a JDK (not ju         st a JRE) and configured your JAVA_HOME system variable to point to the accordin         g directory.

Is this the problem?

**Comment by dalessr** [comment]
Should be. Did you specify the path in the system variable?

![9043-image-1](https://user-images.githubusercontent.com/22449685/44029075-9d2beeea-9f2e-11e8-8e5e-f75865431378.png)

**Comment by s3701799** [comment]
![image](https://user-images.githubusercontent.com/41710124/44029412-966267a8-9f40-11e8-8f7a-3ab920d7d473.png)

Yeah i did.

**Comment by s3701799** [comment]
Okay i got it working already, thanks for your help @dalessr
