### ISSUE TITLE
Run script to migrate rubric question weight from 1-d list to 2-d list

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9045]
Related to #9008

`DataMigrationForRubricQuestionsWithWeightsAttached.java` in the current master branch should be run in order to do the migration.

**Comment by xpdavid** [comment]
Confirmed, please don't run the script right now :( @damithc

**Comment by xpdavid** [comment]
Checked and run against my own staging server. Looks fine.
Ready to be run @damithc

**Comment by damithc** [comment]
Ran the script. Output:

Total number of keys: 12717
Number of affected keys: 1082
Number of updated keys: 1082
