### ISSUE TITLE
InstructorHelpPageUiTest failing on AppVeyor master

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9052]
Master 56190f722d79c647e426db2a739d82f6fc6cd5b5

https://ci.appveyor.com/project/damithc/teammates/build/1.0.1112

**Comment by xpdavid** [comment]
Maybe @mg14777 can also help?

**Comment by mg14777** [comment]
@xpdavid new content has been added to `instructorHelpSessions.jsp` which is affecting the search results. Will update the html files right now

**Comment by xpdavid** [comment]
It is quite interesting that Travis doesn't fail.
