### ISSUE TITLE
TimeHelper.java: combine methods 'formatDateForInstructorCoursesPage' & 'formatDateForInstructorSessionsPage' into 'formatDateForInstructorPages'

### ISSUE THREAD

**Issue by dalessr** [TEAMMATES/teammates#9053]
**Environment:**
`master` branch at commit https://github.com/TEAMMATES/teammates/commit/56190f722d79c647e426db2a739d82f6fc6cd5b5

**Comment by IAmPramod** [comment]
@dalessr is anyone working on this issue?

**Comment by IAmPramod** [comment]
@dalessr Sure, I will start working on it then.

**Comment by IAmPramod** [comment]
@dalessr PR is open for review.
