### ISSUE TITLE
Testing: Use correct EXPECTED_SNIPPET_SIGN_IN in GoogleLoginPage

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9059]
<strike>It seems like the google login page sometimes has `Sign in - Google accounts` instead of expected `Sign in - Google Accounts` (Typo in Google Side :P)

![image](https://user-images.githubusercontent.com/13977235/44300021-a95df700-a332-11e8-98ed-6b2d73a569b6.png)

Our automated test will fail if the title is not matched. 

Maybe should do case-insensitive comparison between expected and actual?</strike>

![image](https://user-images.githubusercontent.com/13977235/45606429-9f393080-ba77-11e8-84d9-15deb83bc395.png)

It seems that Google has changed the title and the behaviour become consistent. 

The title should be `Sign in – Google accounts`.

**Comment by IAmPramod** [comment]
@xpdavid we should convert expected and actual string to lower case and then compare.

**Comment by LiHaoTan** [comment]
I don't agree with this. Suppose we want to keep this simple without changing how we detect the login page we should instead check for the two particular titles instead of doing a case-insensitive comparison.

**Comment by xpdavid** [comment]
Yep. Can define another expected title for more strict verification.

**Comment by shivam3746** [comment]
Hello , May I solve this issue please

**Comment by shivam3746** [comment]
I am a d.Contributor i.e First Timer.

**Comment by xpdavid** [comment]
@shivam3746 I am not sure whether google has normalized the behavior or not.

**Comment by xpdavid** [comment]
The issue need to be fixed soon.

**Comment by carsonshoupe** [comment]
Hello.  I am a first time contributor and would like to resolve this issue.  I have the development environment set up and am ready to write the relevant code.

**Comment by xpdavid** [comment]
@carsonshoupe Sure, go ahead and submit a PR 👍

**Comment by xpdavid** [comment]
You need have a staging server to reproduce the error.

 > Which one is it so I can see if my changes resolve the issue.

Actually, all automated UI tests against staging server (not local server).

**Comment by carsonshoupe** [comment]
@xpdavid Okay.  So I cannot reproduce the error?  If so, should I just go ahead and submit the pull request?

**Comment by xpdavid** [comment]
I think the issue is quite straight forward if you understand it correctly. You can submit an PR.

**Comment by xpdavid** [comment]
I think the issue is quite straight forward if you understand it correctly. You can submit an PR.
