### ISSUE TITLE
Run script to remove unused rubricWeights attribute

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9061]
Post-action after #9045
Related to #9028

`DataMigrationForRubricQuestionToRemoveLegacyWeightList.java` in the current master branch should be run in order to do the migration.

**Comment by sukanta-27** [comment]
@damithc Sir, a reminder for this.

**Comment by damithc** [comment]
Oops. Missed this earlier. Will run on Saturday.
