### ISSUE TITLE
Fix unstable testToEntity() in StudentProfileAttributesTest

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9065]
As `modifiedDate` is not carried to `StudentProfile` in `.toEntity()`, therefore, there should not be such verification in the method.

```
assertEquals(expectedEntity.getModifiedDate().toString(), actualEntity.getModifiedDate().toString());
```

As `modifiedDate` is set to `now` in `.toEntity()`, if the test execute fast, it can pass.

**Comment by tshradheya** [comment]
Reference: https://github.com/TEAMMATES/teammates/pull/8988/commits/75174e6d3a9600a69382955d28ef6fa61f5686cc

**Comment by nmmarzano** [comment]
So basically the whole test will pass or fail depending on how close together `classSetup()` and this test execute, regardless of the actual entities' `getModifiedDate()` return value?

**Comment by xpdavid** [comment]
@nmmarzano I don't think so

Should be how close the first statement below and the thrid statement below execute. 
```
StudentProfile expectedEntity = createStudentProfileFrom(profile);
StudentProfileAttributes testProfile = StudentProfileAttributes.valueOf(expectedEntity);
StudentProfile actualEntity = testProfile.toEntity();
```

**Comment by nmmarzano** [comment]
Right, `createStudentProfileFrom(StudentProfileAttributes profile)` basically calls `new` on `StudentProfile` so the modified date is also set to `now`, I missed that.
Would it be okay to just remove that check then? It would hide the fact that `toEntity()` is setting the `modifiedDate` by also calling `new StudentProfile(...)`, is that correct behaviour that shouldn't be checked for or an actual bug that would be hidden by modifying this test?

**Comment by xpdavid** [comment]
> Would it be okay to just remove that check then? 

Sure. Go ahead an submit a PR. 👍 🎉

**Comment by nmmarzano** [comment]
I will then! Is it needed to assign me the issue?
