### ISSUE TITLE
Fix unstable test in FeedbackSessionsDbTest

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9067]
https://github.com/TEAMMATES/teammates/blob/635bdc89f3a3163ebcdb98f2df72a0dd378ebca3/src/test/java/teammates/test/cases/storage/FeedbackSessionsDbTest.java#L321-L333

We are creating an valid `feedbackSession` through this method. 

If the test execute too fast.... (quite ironic as #9065 says the test execute too slow XD). `Instant.now()` can return the same value (as the accuracy is to millisecond) and the validation in DB will fail as we have some requirements for in `FeedbackSessionAttributes#getInvalidityInfo()` for time (sample below).

```
ci-tests > component-tests > teammates.test.cases.storage.FeedbackSessionsDbTest.testUpdateFeedbackSession FAILED
    teammates.common.exception.InvalidParametersException at FeedbackSessionsDbTest.java:283
```

**Comment by xpdavid** [comment]
Hi @giannisal, someone is working on it right now as you can see from PR reference. Maybe you could try #9065 instead?

**Comment by IAmPramod** [comment]
@xpdavid this issue can be closed as this is resolved by PR https://github.com/BP-21/teammates/pull/1

**Comment by xpdavid** [comment]
Hmmm. You should submit PR against the main repo instead of your own repo. XD

**Comment by IAmPramod** [comment]
@BP-21 Please do the needful. Your changes looks good. Raise the PR against the main repo

**Comment by wkurniawan07** [comment]
@IAmPramod, I'd appreciate it if you look at the surroundings first before raising any comment. @BP-21 has done that in #9069.

**Comment by IAmPramod** [comment]
@wkurniawan07 Apologies. There are so many PR's against this issue and I haven't looked at all of them,

**Comment by felixneto** [comment]
Hi Guys that issue was fixed ?

**Comment by idannik** [comment]
Hey, I am also new to opensource projects and would love to contribute! Is this issue resolved?

**Comment by Jamparan** [comment]
Is this issue fixed? I would like to work on it

**Comment by jtankw3** [comment]
Hello, I believe this issue has already been fixed and can be closed as seen from the below code snippet:
https://github.com/TEAMMATES/teammates/blob/9c3dfaad9f6be96709deceffd18d5d82d7e916d2/src/test/java/teammates/test/cases/storage/FeedbackSessionsDbTest.java#L702-L712

**Comment by LeMikaelF** [comment]
@jtankw3  that's weird. `git log | grep 9067` and `git log | grep "unstable test"` show no relevant commits. I would also like to work on this, could someone confirm the status of the issue?

**Comment by zishxn** [comment]
Hi, is this issue still open?
