### ISSUE TITLE
Instructor: enroll students: blank lines processed by back-end during enrollment

### ISSUE THREAD

**Issue by tanhengyeow** [TEAMMATES/teammates#9071]
**Environment**: 
`master branch`

**Steps to reproduce**
1. Copy rows of student entries from external sources e.g. Microsoft Excel. Sample data shown below:

![image](https://user-images.githubusercontent.com/25320782/44443860-8ec69f00-a60c-11e8-9a0f-ab7faf2db23a.png)

2. Paste the content into the `New Students` spreadsheet using `Ctrl + V` or `Cmd + V`:

![image](https://user-images.githubusercontent.com/25320782/44443896-adc53100-a60c-11e8-854e-9dd0253c67a7.png)

3. Click the `Enroll students` button.

**Expected behaviour**
1. Success enrollment. Example shown below:

![image](https://user-images.githubusercontent.com/25320782/44443917-cb929600-a60c-11e8-88f4-3c8d6825397f.png)

**Actual behaviour**
1. Blank lines processed by back-end during enrollment:

![image](https://user-images.githubusercontent.com/25320782/44443941-e82ece00-a60c-11e8-8bd7-cfa5b519d78d.png)

**Additional info**
1. This is due to potential line feeds/carriage returns during the process of copying data from external sources.
2. This causes the backend method `getRequestParamValue` to read in the line feeds/carriage returns, resulting in student entries to be read separated rows. Example shown below:

![image](https://user-images.githubusercontent.com/25320782/44444094-a7838480-a60d-11e8-87cc-1d15f8d91606.png)

**Comment by damithc** [comment]
On a somewhat related note, aren't we supposed to ignore blank lines anyway?

**Comment by tanhengyeow** [comment]
@damithc 

Yes, the front-end now currently does this:
1. Filter empty rows first
2. Send the non-empty lines to the backend

However, in this case, there were unexpected line feeds/carriage returns due to copying from other sources, thus the unexpected empty lines weren't filtered at this point.

This resulted in the back-end returning the error messages shown in the description after checking the relevant enroll line. The hotfix I'm submitting now takes care of all the line feeds and carriage returns.

**Comment by xpdavid** [comment]
@damithc  Done. Released as [V6.10.1](https://github.com/TEAMMATES/teammates/releases/tag/V6.10.1).

**Comment by damithc** [comment]
I've deployed v6.10.1

**Comment by damithc** [comment]
Thanks for the quick fix and quick release @tanhengyeow @xpdavid
