### ISSUE TITLE
Update AboutUs page to reflect the team at Aug 2018

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9075]
New committers, can you post here suitable photos to be used in the [About Us](http://teammatesv4.appspot.com/about.jsp) page?

Requirements: clean background (no need to remove background), shoulders visible (passport-style photos not suitable), 
Preferred: informally dressed, smiling :-)

**Comment by xpdavid** [comment]
Welcome! Recently joined committers!

@dalessr @mg14777 @nidhi98gupta @sukanta-27 @tanhengyeow @jacoblipech

And for existing committers, if you want to have a photo associated with you. You can also post it here.

@darrenwee @joanneong @bqnguyen94 @LuLechuan @tshradheya @wenmogu @Crphang @tran-tien-dat @Haozhe321 @craaaa

**Comment by damithc** [comment]
> @damithc Is this photo fine?

Yes, I think so. We'll try that one and get back to you if it doesn't work.

**Comment by tshradheya** [comment]
Photo: [Shrad_Image](https://user-images.githubusercontent.com/12574756/44588682-62ce2980-a784-11e8-9644-a36fa8937416.jpeg)

**Comment by damithc** [comment]
@tshradheya we need both shoulders to be visible

**Comment by tshradheya** [comment]
[New Image](https://user-images.githubusercontent.com/12574756/44590185-82ffe780-a788-11e8-9503-9ff607cd33cf.jpg)

Let me know if this is fine :)

**Comment by damithc** [comment]
> New Image
> 
> Let me know if this is fine :)

Yes that looks suitable

**Comment by dalessr** [comment]
[image_shengran](https://user-images.githubusercontent.com/22449685/44594679-8089a600-a7f9-11e8-8d2d-370c17564034.jpg)

**Comment by bqnguyen94** [comment]
@damithc is [my current avatar](https://avatars1.githubusercontent.com/u/11720085?s=460&v=4) suitable?

**Comment by sukanta-27** [comment]
@damithc Sir, is this [image](https://user-images.githubusercontent.com/10681755/44598839-030e6780-a7f2-11e8-89c5-a970ab91b311.JPG) suitable?

**Comment by mg14777** [comment]
@damithc sir, does this [image](https://user-images.githubusercontent.com/11634699/44599797-11aa4e00-a7f5-11e8-8f92-cde0189e356e.jpg) look good ?

**Comment by jacoblipech** [comment]
@damithc is my [current avatar](https://avatars3.githubusercontent.com/u/28522090?s=400&u=0c0ea287f4f2515c8c1383ca706091cb9835fc79&v=4) acceptable too?

**Comment by damithc** [comment]
@dalessr @sukanta-27 @mg14777 @jacoblipech @bqnguyen94 Yes, they seem OK. I'll get back to you if there is any problem.

**Comment by tanhengyeow** [comment]
@damithc Is this [image](https://scontent-sit4-1.xx.fbcdn.net/v/t1.0-9/12227013_10154460101833357_173219303789071714_n.jpg?_nc_cat=0&oh=1ceda80986fc7b89d94a773279a2bfba&oe=5C3A6567) suitable?

**Comment by joanneong** [comment]
Here is [my picture](https://user-images.githubusercontent.com/24493463/44627887-8eaa0480-a968-11e8-9fd9-0f5b864a5a22.png). Thanks!

**Comment by tran-tien-dat** [comment]
@damithc is my [current avatar](https://avatars3.githubusercontent.com/u/8559368?s=400&u=e32865fd8b95ce35ae8b931d14dc19d45875121a&v=4) suitable?

**Comment by damithc** [comment]
> @damithc is my [current avatar](https://avatars3.githubusercontent.com/u/8559368?s=400&u=e32865fd8b95ce35ae8b931d14dc19d45875121a&v=4) suitable?

Yes, that should work.

**Comment by wenmogu** [comment]
@damithc does [this pic](https://user-images.githubusercontent.com/28526038/46538657-3518ec00-c8bd-11e8-819d-2718a9483f37.png) looks ok

**Comment by Crphang** [comment]
@damithc is my [current avatar](https://avatars0.githubusercontent.com/u/4986717?s=460&v=4) okay?

**Comment by IAmPramod** [comment]
@damithc Is my [current avatar](https://avatars0.githubusercontent.com/u/2184241?s=400&u=871c8733192629bdf1172b3e4ebe6b38f89fe84e&v=4) is ok?

**Comment by wkurniawan07** [comment]
@IAmPramod, this issue is only targeted to recently promoted committers.

**Comment by damithc** [comment]
@wenmogu the background is not clean enough to be removed cleanly. Can take a selfie against a clean background such as a white wall?
@Crphang yes, looks suitable.
