### ISSUE TITLE
Run script to delete orphaned StudentProfile

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9076]
`DataMigrationForOrphanedStudentProfile.java` in the current master branch should be run in order to do the migration.

@damithc Can I first have a look at the console output when `isPreview()` is `true`?

As this script employees a new data migration framework, it is better for us to preview it first before we actually run it. In addition, can also take this chance to let you know how to stop and resume the script :D.

**Comment by damithc** [comment]
BTW, how do I resume from a previous run that was terminated prematurely?

**Comment by xpdavid** [comment]
You can copy the cursor position web safe string from the console output. Let's say the last one in the console input:
`ClISTGoNc350ZWFtbWF0ZXN2NHI7CxIHQWNjb3VudCINMzI0NjU2NDMwM2x4cwwLEg5TdHVkZW50UHJvZmlsZSINMzI0NjU2NDMwM2x4cwwYACAA`

Replace it with empty string here in the script.
```
    @Override
    protected String getLastPositionOfCursor() {
        return "";
    }
```

Do you think if it necessary to make the steps automatically? The decision to make it manually right now is to give more controls to the developers.

**Comment by damithc** [comment]
> Do you think if it necessary to make the steps automatically? The decision to make it manually right now is to give more controls to the developers.

Got it. No need to make it automatic, but may want to document this somewhere.

**Comment by xpdavid** [comment]
@damithc Any updates?

**Comment by damithc** [comment]
> @damithc Any updates?

Oh, you want me to run it for real? Not just in preview mode?

**Comment by xpdavid** [comment]
Yes but I need first take a look at the output in the preview mode. What is the last part of the console output?

**Comment by damithc** [comment]
> Yes but I need first take a look at the output in the preview mode. What is the last part of the console output?

Oh, I didn't run it till the end. Will do tomorrow and post here.

**Comment by damithc** [comment]
It timed out after 35k entities. I resumed from the place it terminated earlier. Still going on.

**Comment by damithc** [comment]
>Preview Completed!
Total number of StudentProfiles: 26280
Number of affected StudentProfiles: 0
Number of updated StudentProfiles: 0

Should I run it in non-preview mode?

**Comment by xpdavid** [comment]
I think no need. We don't have entity to migrate/delete and we can safely remove the legacy code 🎉

**Comment by xpdavid** [comment]
Close issue now as there is no affected entity 🎉
