### ISSUE TITLE
Data Migration: FeedbackResponseComment commentGiverType and isCommentFromFeedbackParticipant

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9083]
Data migration initiated by PR #8830 

- [x] Merged code that work for both the old and new versions of the data schema.
- [x] Released a version containing the above in [V6.8.0](https://github.com/TEAMMATES/teammates/releases/tag/V6.8.0)
- [x] Created a client script to migrate all data following the old schema to the new schema in PR #9099.
- [x] Ran the script against the live site.
- [ ] Removed the code that is specifically tailored for the old data schema in PR #11344.

**Comment by xpdavid** [comment]
@nidhi98gupta You need create a client script to migrate all comment.

**Comment by nidhi98gupta** [comment]
Yes, I have university exams this week. I will make a PR next week.
