### ISSUE TITLE
Instructor edit email of student: send the correct link to student

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9090]
v6.10.1

Steps:
1. Login as instructor
2. Edit email of a student
3. Choose to resend links when prompted

Problem: the links received by student doesn't work (probably outdated).

**Comment by damithc** [comment]
This is probably a long-time bug. I've received reports of this problem from time to time but did not realized it is actually a bug.

**Comment by xpdavid** [comment]
Investigating....

**Comment by xpdavid** [comment]
The `registrationKey` is not updated accordingly when student email is updated. Fixing.

**Comment by damithc** [comment]
> The issue is fixed right? @damithc

Yup. 👍

**Comment by xpdavid** [comment]
🎉
