### ISSUE TITLE
Logic.java: Clean up unused methods.

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9096]
There are several unused methods (or methods only used in test) in `Logic.java`. See if we can remove them as well as their correspoding methods `*Db`.

**Comment by xpdavid** [comment]
Be prepared as some methods are used in tests. You need find some alternative ways for them.

**Comment by IAmPramod** [comment]
@xpdavid Yeah, I saw that. I will start working on this.

**Comment by IAmPramod** [comment]
@xpdavid Ready for review.

**Comment by carsonshoupe** [comment]
Hi @IAmPramod.  Do you plan to open another PR for this issue?

**Comment by IAmPramod** [comment]
@carsonshoupe yes, that will be better.

**Comment by IAmPramod** [comment]
@xpdavid started working on this now.
