### ISSUE TITLE
Searching: Same session name in different courses will produce malformed results

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9103]
- **Environment**: `master`

**Steps to reproduce**

- Create two different courses.
- Create one session in two different courses with the same name
- Submit some feedback responses as students in both sessions
- Add a comment with the same content as instructors to feedback response in different sessions
- Go to `instructorSearchPage` and search for the comment you just entered.

![search instructor](https://user-images.githubusercontent.com/13977235/45023877-28a93580-b06a-11e8-95ff-0c7fb1533afa.png)

**Expected behaviour**

- Results should display in two separated sessions.

**Actual behaviour**

- Results displayed in one session.

**Additional info**

https://github.com/TEAMMATES/teammates/blob/290443f86eaf741c9fda0670070b8fd6c269ad90/src/main/java/teammates/storage/search/FeedbackResponseCommentSearchDocument.java#L303-L324

Session name is not unique in the whole DB. Should use (session name + courseID)

**Comment by xpdavid** [comment]
Hi @sukanta-27, interested in doing this issue?

**Comment by joanneong** [comment]
@xpdavid Can I help with this? I am trying to get myself involved with teammates again :) I will try to get a PR up by this coming Tuesday

**Comment by xpdavid** [comment]
@joanneong 🎉 Sure
