### ISSUE TITLE
problem in 3 commands in step 3: set up project-specific setting and dependencies (google cloud SDK)

### ISSUE THREAD

**Issue by fatimah5** [TEAMMATES/teammates#9105]
Issue title: Help Request: [set up project-specific setting and dependencies (google cloud SDK) ]

- install.bat --path-update true
'install.bat' is not recognized as an internal or external command,
operable program or batch file.

- npm install
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\ASUS\AppData\Local\Google\Cloud SDK\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\ASUS\AppData\Local\Google\Cloud SDK\package.json'
npm WARN Cloud SDK No description
npm WARN Cloud SDK No repository field.
npm WARN Cloud SDK No README data
npm WARN Cloud SDK No license field.

- gradlew.bat createConfigs
'gradlew.bat' is not recognized as an internal or external command,
operable program or batch file.

- **Problem:** Result of running these 3 commands
- **Operating System:** Windows X64
- **JDK Version:** jdk-8u181
- **Node.js Version:** 8.11.4
- **Google Cloud SDK Version:** 214.0.0
- **Eclipse / IntelliJ Version (if applicable):** IntelliJ IDEA 2018.2.2 x64
- **Firefox / Chrome Version (if applicable):** chrome Version 68.0.3440.106

**What I was trying to do / What I need help with**
I were setting up the project, I faced problem in 3 commands in step 3: set up project-specific setting and dependencies (google cloud SDK) knowing that the “gcloud” command works. Thank you.

**Attempts to resolve the problem**
I tried many times to resolve this problem by change the command as written in the documentation of the official google cloud SDK website, and I searched on the internet about this problem.

**Comment by xpdavid** [comment]
- You need to execute `install.bat --path-update true` under the folder where you download the SDK.

- You need to execute `npm install` and `gradlew.bat createConfigs` under the folder where you clone the repo.

**Comment by fatimah5** [comment]
Dose that mean I have to make a copy of SDK shell to these folders, and then execute the commands? because I tried this many times but nothing has been change!

**Comment by xpdavid** [comment]
You can put the SDK folder anywhere you want, you just need to `install.bat` to get `gcloud` command in your shell.

**Comment by fatimah5** [comment]
yes, the `gcloud` command is working.

Thank you.

**Comment by xpdavid** [comment]
🎉 Looking forward to your first PR 😄
