### ISSUE TITLE
unable to select folder node_modules for JavaScript and JSON validation.

### ISSUE THREAD

**Issue by ShafqatShafi** [TEAMMATES/teammates#9106]
I was trying to set validation for javascript and JSON. But after following the steps when I click the 
'select folder' it does not show the URL to that folder and nor does is enable 'Next' or 'Finish' button. 

And for that reason, I'm getting errors in JSON and js files.

Note: My clone project is in one directory and my eclipse workspace is in another directory.
(eg: project directory: E:\Teammates\teammates and eclipse workspace: E:\Eclipse-Workspace)

**Comment by xpdavid** [comment]
Are you trying to setup static analysis tool? https://github.com/TEAMMATES/teammates/blob/master/docs/static-analysis.md#tool-stack

**Comment by ShafqatShafi** [comment]
@xpdavid No, I'm following the "Project Setup" guideline at this URL: "https://github.com/TEAMMATES/teammates/blob/master/docs/ide-setup.md".
And I was facing this problem under "Validation" section.
But I have successfully completed all the steps in the "ide-setup" guideline. Now I'm on to the "development" guideline.
Actually, I uncheck the Build option for JavaScript Validation and JSON Validator. This solved it for me.
Thanks, Shafqat Shafi.

**Comment by xpdavid** [comment]
Good to hear that 👍 Looking forward to your first PR 🎉
