### ISSUE TITLE
Help Request : [Wrong order for new common.datatransfer.attributes [ImportOrder]]

### ISSUE THREAD

**Issue by s3588689** [TEAMMATES/teammates#9107]
- 186fa7d9c26670cbe9923a4375b2292e31f6fbf2
- Ubuntu 18.04
- JDK 10.0.2
- Node.js v10.7.0
- gcloud 210.0.0
- Firefox 46.0.1

Hi Guys, here is my error when I am trying to build the project with gradle. What I am trying to do is create a student forum entity based on the InstructorFeedbackSessions and so a lot of the code is based off of that. I have added all the necessary classes in the storage modules but I'm not sure what I'm missing because there is no error when compiling and the datastore is not appearing in the admin page. Will you please help me if I am missing anything. Or do I have to build the whole project again to see the changes? 

The files I think are required are: 
forumSessionAttributes.java
forumSessionDb.java
forumSessionEntity.java
forumSessionSearch.java

Thanks for any help in advanced.

**Comment by xpdavid** [comment]
It's an error by CheckStyle static analysis tool.

You need to make your import order follow the order specified in `teammates-checkstyle.xml`. :)

**Comment by s3588689** [comment]
Thank you for replying!

I am having another issue with the CheckStyle static analysis tool;

[ant:checkstyle] [ERROR] src../ForumQuestionDetails.java:3:8 Unused Import
- java.util.Comparator. [UnusedImports]

 I feel like I've missed something obvious here.

Thanks in advance for the help!

Tim

**Comment by xpdavid** [comment]
You need to remove unused import.

BTW, it seems that you are working on a new feature/refactor. Please create a issue for discussion before implementation.

**Comment by xpdavid** [comment]
Closed as the problem solved 🎉
