### ISSUE TITLE
Openhub link for Teammates doesn't work!

### ISSUE THREAD

**Issue by iMB24** [TEAMMATES/teammates#9111]
I tried accessing the openhub link - https://www.openhub.net/p/teammatesonline, to learn more about this project but it's gives a error with the message "This website is under heavy load (queue full)."

**Comment by iMB24** [comment]
I can host the contents of the website in another service if anyone's willing to provide the content.

**Comment by wkurniawan07** [comment]
This issue does not belong in this repository. OpenHub is a third-party service provider which we do not even pay.
