### ISSUE TITLE
Suggestion for student feedback page minor UI overflow issue

### ISSUE THREAD

**Issue by davidchoo12** [TEAMMATES/teammates#9115]
Under question 5 of the student feedback page, each of the dropdown and table rows are displayed like this: (notice the overflow of the table on the right)
![image](https://user-images.githubusercontent.com/7817101/45229695-2a3c5d00-b2f9-11e8-9a55-a8b819e32bf0.png)

The html code is as follows
![image](https://user-images.githubusercontent.com/7817101/45231459-9c637080-b2fe-11e8-8942-fa982eb0cf4d.png)

**Additional info**
Suggested simple changes:
- Set parent `<div>` classes: `col-sm-12 col-md-10 col-md-offset-1`
- Set children `<div>`s classes: `form-group`
- Remove "(Student):" text before the `<label>` tag
- Set the text of the default selected `<option>` to "Select a student" or something informative

![image](https://user-images.githubusercontent.com/7817101/45231428-83f35600-b2fe-11e8-9f43-8589a4e93e21.png)

Once changes are applied, it should look like the top one of the following image:
![image](https://user-images.githubusercontent.com/7817101/45231505-c026b680-b2fe-11e8-8473-e8b502d3dbb7.png)

**Comment by hidingmode** [comment]
Another design nitpick. The form submit button states there is a saving feature. I thought it meant there is a save button somewhere so that I can save first before submitting. I only found out after submitting that it meant I can edit my responses after submission.
So perhaps, change the tooltip to "You can edit your responses after submission at any time before the deadline"
![image](https://user-images.githubusercontent.com/7817101/46660367-7543db80-cbe9-11e8-8966-dbc294c373c4.png)

**Comment by css911** [comment]
@hidingmode hello, I am new to the community, can I try to solve this problem.

**Comment by css911** [comment]
@hidingmode Sir can you please guide me on how can i reproduce the issue. It will really help me while solving my first issue.

**Comment by css911** [comment]
@dalessr Sir, I was trying to reproduce overflow issue on my local machine but was not able to produce it could you please help me. it would mean a lot.

ScreenShot.
![image](https://user-images.githubusercontent.com/24544436/48737933-6d119e00-ec75-11e8-9f96-515aeb69380d.png)

In was not getting the dropdown menu about which @hidingmode sir. talked. Please sir can you help me to solve this issue.

**Comment by hidingmode** [comment]
I'm not part of the dev team.

My school uses this project to collect peer evaluation from the students and I'm just a student user. The screenshots are taken from the form my lecturer sent me.

**Comment by wkurniawan07** [comment]
Fixed in V7
