### ISSUE TITLE
Instructor: delete course/session: remove the term 'soft-delete' from UI

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9117]
v6.11.0

I noticed the term 'soft-delete' in the UI while running UI tests. I don't think that's a term meaningful to users.

Suggested: replace with another term such as 'deleted' or 'in the recycle bin'

**Comment by Chris211313** [comment]
I'll take care of this one as a first issue :)

**Comment by jasminelambxo** [comment]
can i give this a go ?

**Comment by damithc** [comment]
> can i give this a go ?

Sure, go ahead @jasminelambxo

**Comment by jasminelambxo** [comment]
> > can i give this a go ?
> 
> Sure, go ahead @jasminelambxo

i cant see where the issue is aploagies

**Comment by moziliar** [comment]
@kumarav1nash it doesn't seem like anyone is working on the issue. Go ahead!

**Comment by kumarav1nash** [comment]
@damithc please review this code

**Comment by damithc** [comment]
> @damithc please review this code

@kumarav1nash if you have submitted a PR for this issue, that PR will go through our regular review process, which can take several days to complete.

**Comment by kumarav1nash** [comment]
ok
