### ISSUE TITLE
FeedbackResponseCommentsLogicTest: Fix verification for test

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9119]
https://github.com/TEAMMATES/teammates/blob/51e4279ad8e098ed25d01b5a332a7d5b514d858a/src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java#L71-L96

The test uses a existing comment in DB and create a new duplicate comment with the same `commentText` in the DB. It then tries to verify whether the creation is successful or not. However, the verification will always pass as there is a existing comment (the comment which the test is copied) in DB (we check existence of comment by using `commentText`. (In test case, we make sure the `commentText` is unique)).

**Comment by n1ckyb** [comment]
Can I take a look?

**Comment by xpdavid** [comment]
@n1ckyb Hi, Welcome! You should find any firstTimer issue to try first before targeting contributors issue.

**Comment by IAmPramod** [comment]
@n1ckyb hi, are you working on this?

**Comment by rrtheonlyone** [comment]
I would like to take this up!

@xpdavid Can I clarify on what actually should be the expected result when a duplicate comment is added? (e.g. will it just ignore the duplicate?)

**Comment by xpdavid** [comment]
You should take a look at `frcLogic.createFeedbackResponseComment(frComment);` to know the expected behaviour
