### ISSUE TITLE
Links in tooltips are unaccessible

### ISSUE THREAD

**Issue by hidingmode** [TEAMMATES/teammates#9126]
Links in tooltips (popups that appear on hover) cannot be reached since the tooltips disappear when unhovered.

Example from https://nus-cs2103-ay1819s1.github.io/cs2103-website/se-book-adapted/chapters/revisionControl.html
![Example](https://i.gyazo.com/c6836ac43432c2682e56cd8f94870a37.gif)

**Expected behaviour**
Maybe the tooltop can stay visible for a bit before fading out like in https://stackoverflow.com/a/16663648/4858751

**Comment by xpdavid** [comment]
Guess you should create the issue against https://github.com/MarkBind/markbind instead.
