### ISSUE TITLE
Update the maintainer guide with instructions on how to update the timezone data

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9129]
Basically there are two files that need to be updated:

- `src/main/resources/tzdb.dat` for back-end

https://www.oracle.com/technetwork/java/javase/tzupdater-readme-136440.html

- `src/main/webapp/data/moment-timezone-with-data-2013-2023.min.js` for front-end

https://momentjs.com/timezone/

**Comment by wkurniawan07** [comment]
@xpdavid this doesn't have anything to do with the migration; just do it when you have the time to.

**Comment by xpdavid** [comment]
Hmm, if we decide to format time in front-end. This documentation would be useless. In addition, I also hesitate to introduce this additional maintenance burden.

**Comment by wkurniawan07** [comment]
Maintenance burden is not the question right now. Is this crucial for the system's correctness?

**Comment by xpdavid** [comment]
Not that much. The timezone database does not update that often (only 3-4 times a year). We are now behind 2 version of the latest updated timezone info (I can submit a PR later to update them).

There should be a person who keep track of the updates of timezone and update the two files accordingly. This is where the maintenance burden comes from. That's why I am asking if we can push the formatting to the V7 project in #9128

**Comment by xpdavid** [comment]
Just release we cannot get rid of updating `tz database` in backend (e.g. Sending email need it). Will look into how to make the process automatically and submit PR for the updating process.

**Comment by wkurniawan07** [comment]
@xpdavid don't worry too much about making it "automatic" right now. The focus now is to get the routine to work first.
