### ISSUE TITLE
Upgrade to Objectify V6

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9131]
Should upgrade to Objectify V6 once the following prerequisites complete:

- Google begin to deprecated accessing Datastore using the old set of API. 
    - Can track from here https://cloud.google.com/appengine/docs/standard/java/datastore/creating-entities or any public notification

- The new set of API provided by Google is ready. Currently V6 is using the new set of API with the following limitations https://github.com/objectify/objectify/wiki/FrequentlyAskedQuestions#i-am-using-gae-standard-should-i-use-objectify-v5-or-v6: (once this limitations are solved or we can tolerate the limitations, we are ready to go)
    - Not yet any way to enqueue tasks as part of a datastore transaction _-> not critical as we don't have use case of this_
    - Memcached integration requires your own memecached server (no integrated GAE offering yet) _-> we need cache service to boot datastore performance_
    - Performance may suffer; in particular, per-request latency _-> Our performance cannot suffer further XD_

Currently I am preparing all the things we need to do to ensure smooth transition from V5 to V6.
- #9082 
- #9127 

Things need to be done when upgrade.

- Upgrade dependency in `build.gradle` (one line modification)
- Change `BaseEntity$InstantTranslatorFactory` to translate from `com.google.cloud.Timestamp` to `java.time.Instant` (easy code modification)
- Use `IllegalImport` (with no exception) instead of macker rule to forbid import of `java.time.Date`. (easy static analysis config file modification)

WIP

**Comment by Labirinto** [comment]
Please assign this ticket to me

**Comment by madanalogy** [comment]
Continued in #10955
