### ISSUE TITLE
Instructor: rename buttons in alert message to match question being asked

### ISSUE THREAD

**Issue by tanhengyeow** [TEAMMATES/teammates#9134]
**Environment**: 
`master` branch

**Description of feature/enhancement**
Similar to #8981. 

Follow the conversation in #9009 and identify appropriate areas to rename the buttons in the respective alert message(s).

**Comment by tanhengyeow** [comment]
@fatimah5 Sure! Please go ahead and do so.

**Comment by fatimah5** [comment]
That's what I did.
1. Run 'Google App Engine Standard Local Server' Src> test> resources > pages > adminHomePage.html
2. After the opened in the browser > login as instructor > enter the email as shown in the image. 

Problem: After I clicked login nothing happened!

![image](https://user-images.githubusercontent.com/41271008/45922300-807ad580-be8d-11e8-9ffd-3102461ad211.png)

**Comment by fatimah5** [comment]
If you can help me, I just want to figure out how to solve this issue. In which page and line is the problem exist?

Thank you

**Comment by tanhengyeow** [comment]
There's a proper setup guide to get TEAMMATES running. Refer to this [guide](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#managing-the-dev-server) for more details :)

**Comment by fatimah5** [comment]
yes, I'm working on it.

**Comment by bhumisaxena0223** [comment]
Hey @fatimah5, if you are not working on this, can I post a solution for this issue?

**Comment by fatimah5** [comment]
I'm working, I just reported a bug, and I'll solve this issue once the issue of bug solved.

**Comment by laurensdegilde** [comment]
Is this still open? Happy to take it.

**Comment by xpdavid** [comment]
@laurensdegilde Hi, Welcome! As long as there  is no existing open PR, feel free to contribute.

**Comment by laurensdegilde** [comment]
@xpdavid this seems fixed. You merged the PR for this issue in #8981

**Comment by mihirg008** [comment]
I would like to work on this issue if it's still open.

**Comment by crownedlake** [comment]
@tanhengyeow hi, is this issue still open?

**Comment by tanhengyeow** [comment]
@crownedlake Yes it is, if there are no ongoing active PRs for an issue, feel free to take an issue up.

**Comment by martinoamigo** [comment]
@tanhengyeow Hello! I believe this fixes the issue

**Comment by crownedlake** [comment]
@martinoamigo Please ask if anyone else was working on the same issue, I was about to submit a PR after reading all the Teammates workflow and PR guidelines.

**Comment by martinoamigo** [comment]
@crownedlake Sorry about that, didn't realize anyone was still working on this.

**Comment by crownedlake** [comment]
@martinoamigo It is fine, most of the things in your PR is exactly same. So don't think there is a need for me to PR. 
Lets wait for someone to review yours. :smile:
