### ISSUE TITLE
EntityAttributes: Make getBackupIdentifier() message more meaningful

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9136]
Ideally, `getBackupIdentifier()` should produce messages that will help developers to identify modified entities easily.

https://github.com/TEAMMATES/teammates/blob/98ef745d7a243f2330014a5ccbf059a3ee905a7a/src/main/java/teammates/common/datatransfer/attributes/AccountAttributes.java#L206-L209

The above is not helpful at all. 

In addition, I think we should name it as `getBackupMessage()` rather than `Identifier` as it is used as `log.info(entityToSaveAttributesForLogging.getBackupIdentifier());`

Another thing we can do is to push the method to `BaseEntity` instead as all DB manipulate entity instead entityAttribute. But, let's fix the message first before we move to the next step.

**Comment by Labirinto** [comment]
I would like to work on this issue, please

**Comment by saturator22** [comment]
Hi there,
I think that i got your point @xpdavid and i would like to contribute with my solution according to the architecture, i cannot push my repo due to permission denied, can someone add me to this task ?

**Comment by saturator22** [comment]
@xpdavid I think that i got your point, i would like to work on this issue
