### ISSUE TITLE
FeedbackResponseCommentAttributes: getIdentificationString() should return the identifier of the attribute

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9137]
https://github.com/TEAMMATES/teammates/blob/98ef745d7a243f2330014a5ccbf059a3ee905a7a/src/main/java/teammates/common/datatransfer/attributes/EntityAttributes.java#L35-L39

As indicates above, `getIdentificationString()` should only return string that is sufficient to identify the attribute (i.e. a field combination that makes the attribute unique among others).

**Comment by Labirinto** [comment]
I would like to work on this issue, please

**Comment by Labirinto** [comment]
I would like to work on this issue, please

**Comment by kjayashr** [comment]
I am a first timer. I am also looking at this issue.
Thanks

**Comment by kjayashr** [comment]
I am a first timer. I am assuming,

 Option A: feedbackResponseCommentId + courseId+ feedbackSessionName+ feedbackQuestionId + commentGiver+ feedbackResponseId 
should be detailed enough to uniquely identify by just having a look at it. 

Do you think any other fields not necessary here?

My option B. Would be:  feedbackSessionName+ feedbackResponseCommentId 

Please let me know what shall I go with?

**Comment by xpdavid** [comment]
`feedbackResponseId + createdAt + giverEmail` should be the correct combination (Take a look at `FeedbackResponseCommentsDb#getEntityQueryKey`s). Note that an instructor can give multiple comment for a response.

**Comment by kjayashr** [comment]
Yes. Thank you. I should have thought more functionally. feedbackResponseId + createdAt + giverEmail should be enough.

**Comment by idannik** [comment]
Hey, I am also new to opensource projects and would love to contribute! Is this issue resolved?

**Comment by xpdavid** [comment]
@idannik Hi welcome, please note that there is an existing PR for this issue. You may want to try other issues :)
