### ISSUE TITLE
CourseAttributesTest: fix unstable testBuilderWithDeletedAt()

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9139]
https://github.com/TEAMMATES/teammates/blob/98ef745d7a243f2330014a5ccbf059a3ee905a7a/src/test/java/teammates/test/cases/datatransfer/CourseAttributesTest.java#L51-L61

When `builder` is called, `createdAt` is set to `Instant.now()`. If the test executes a bit slow, it will fail as `Instant.now()` is different when `L59` is called.

@dalessr Do we need that assertion? Can we remove it or use `assertNotNull()`?

**Comment by Labirinto** [comment]
Please assign this ticket to me.

**Comment by kyusufA** [comment]
We need to comment it out because it is not testing anything it is comparing two times which won't be equal unless i am missing something.

**Comment by xpdavid** [comment]
> We need to comment it out 

Can just remove the line actually 💯

**Comment by kyusufA** [comment]
I wanted to remove the line but I do not have permission to push the changes.

**Comment by kyusufA** [comment]
can I get permission please

**Comment by wkurniawan07** [comment]
@kyusufA you're free to work on your fork and submit a PR here.

**Comment by dalessr** [comment]
@xpdavid Opps think I made a mistake here. Should be `validCreatedAt` instead of `Instant.now()`.

**Comment by xpdavid** [comment]
> Should be validCreatedAt instead of Instant.now().

Not really, the `createdAt` doesn't supply to the builder.

I think we can just remove the assertion there are it is testing `deletedAt` but not `createdAt `

**Comment by pratikadola** [comment]
Hi, is the issue still open to work on? If so I'd like to give it a shot :)

**Comment by xpdavid** [comment]
@pratikadola You are free to work on it since there is no update from @kyusufA in the current PR.

**Comment by pratikadola** [comment]
#9158 https://github.com/TEAMMATES/teammates/pull/9158

**Comment by pratikadola** [comment]
# #9158 

> @pratikadola You are free to work on it since there is no update from @kyusufA in the current PR.

#9158

**Comment by xpdavid** [comment]
@kyusufA Your PR is not CI green and we doesn't hear you for several days. If you want to continue to do it, you may want to coordinate with @pratikadola.

**Comment by kyusufA** [comment]
sure

**Comment by pratikadola** [comment]
#9158 - Are there any issues with this PR? If not can we close the issue?

**Comment by feysalikbal** [comment]
#9158 needs a review.
