### ISSUE TITLE
InstructorFeedbackSession: Fix data persistence for sessions with recycled names

### ISSUE THREAD

**Issue by joanneong** [TEAMMATES/teammates#9148]
- **Environment**: 
`master` branch at commit f725f72

**Steps to reproduce**
There are two variants:

First version:
1. Create a new session
2. Submit a response for the session
3. Delete the session **permanently**
4. Create a new session with the same session name in the same course
5. The new feedback session template has too many questions, and some questions warn about existing responses:

<img width="1123" alt="screen shot 2018-09-22 at 11 19 39 pm" src="https://user-images.githubusercontent.com/24493463/45918738-13336880-bebe-11e8-80f5-750687fc46f2.png">

Interestingly, you can't see anything in the "Session Results" for this variant.

Second version:
1. Create a new session
2. Submit a response for the session
3. Add a comment for the response
4. Delete the session **permanently**
5. Create a new session with the same session name in the same course
6. The template is wrong. Additionally, if you see the "Session Results", you can see the response from the previously deleted session! Searching for keywords in the response/comment will also produce results in the search page.

**Expected behaviour**
Session data should be deleted entirely from the database once the session is permanently deleted. 

**Actual behaviour**
Data from deleted sessions persist and can be recovered by creating a new session with the same name in the same course. The starting time and ending time need not be the same.

**Additional info**
I am not sure if there is some caching happening internally. It would be good if someone investigates and verifies this.

**Comment by joanneong** [comment]
@xpdavid You might want to take a look at this as well... 😭

**Comment by damithc** [comment]
There was a case of a user complaining that her session ended up with wrong questions. Could be a result of this issue.

**Comment by xpdavid** [comment]
I didn't expect that question deletion logic get back the feedback session somehow (If the session is soft-deleted, it will never get that session and the cascade deletion logic fail silently).

Confirm it is a bug :(

Will release together with V6.12.1.

**Comment by xpdavid** [comment]
Fixed in `release` and changes merged back to `master`
