### ISSUE TITLE
Add more SpotBugs rules

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9152]
SpotBugs is adopted in #9149 and only some rules have been adopted.

Need to do some experiments to find new candidates and enforce the rule in our code base.

https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html

Please also give some justifications if certain rules need to be enforced :)

**Comment by IAmPramod** [comment]
@xpdavid, I think following rules should be added. This is not a exhaustive list but we can add more to this.

- NP_BOOLEAN_RETURN_NULL
- Method might drop exception (DE_MIGHT_DROP)
- Method might ignore exception (DE_MIGHT_IGNORE)
- Covariant compareTo() method defined (CO_SELF_NO_OBJECT)
- IC_SUPERCLASS_USES_SUBCLASS_DURING_INITIALIZATION
- Enum field is public and mutable (ME_MUTABLE_ENUM_FIELD)
- SE_NO_SUITABLE_CONSTRUCTOR
- SE_NO_SERIALVERSIONID

**Comment by IAmPramod** [comment]
@xpdavid are we good to start on this or do we need to add more rules?

**Comment by xpdavid** [comment]
Would be good to explore more of them first.
