### ISSUE TITLE
Add Docker Support

### ISSUE THREAD

**Issue by acheaito** [TEAMMATES/teammates#9165]
Add Docker Support to Teammates

- **Environment**:  `master` branch at commit ad120e6

**Description of feature/enhancement**
Containerizing Teammates with Docker allows anyone to start a local server without setting up a dev environment

**Justification**
Makes it much more likely for prospect users to try out Teammates locally

**Existing similar features and their shortcomings**
Server can be set up by following the documentation, but that takes several installations and configuration steps

**Comment by wkurniawan07** [comment]
Resolved in #9166.
