### ISSUE TITLE
Running adminHomePage.html Page

### ISSUE THREAD

**Issue by fatimah5** [TEAMMATES/teammates#9170]
Firefox version: 48.0

I run the src>main>test>resources> pages> adminHomePage.html

This what appears!

![image](https://user-images.githubusercontent.com/41271008/46373660-398e9c00-c654-11e8-8d54-a012b3aa7cba.png)

**Comment by xpdavid** [comment]
@fatimah5 Please follow our bug-report issue template if you think this is a bug.

**Comment by xpdavid** [comment]
Duplicated in #9181 

Feel free to re-peon if this is not duplicated issue.
