### ISSUE TITLE
Testing: Fix integrity of test data for FeedbackResponseComment

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9174]
https://github.com/TEAMMATES/teammates/blob/92b7744ffafb7162535eacde0051904cdff13659/src/test/resources/data/AllAccessControlUiTest.json#L1070-L1085

There is no response with `feedbackResponseId` = `3%student1InCourse1.access@gmail.tmt%student1InCourse1.access@gmail.tmt` in the `.json` file. Need to change the id to refer to the real response in the `.json` file.

Part of the fixes has been introduced in #9153.

Aside for the `AllAccessControlUiTest.json`, there are other `.json` files which has comment linked to a non-existent response. Need to fix them also.

**Comment by cbb692** [comment]
If this is still an issue, I can maybe pick this up. For reference, I believe the response that goes along with this particular example is:

`"response1ForQ3S1C1": {
      "feedbackSessionName": "First feedback session",
      "courseId": "idOfTypicalCourse1.access",
      "feedbackQuestionId": "3",
      "feedbackQuestionType": "TEXT",
      "giver": "instructor1@course1.tmt",
      "recipient": "%GENERAL%",
      "responseMetaData": "Good work, keep it up!",
      "giverSection": "None",
      "recipientSection": "None"
    }`

I believe the formula we're using is:

`this.feedbackResponseId = feedbackQuestionId + "%" + giverEmail + "%" + receiver;`

from storage/entity/FeedbackResponse.java? So we'd get 

`3%instructor1@course1.tmt%%GENERAL%`

If not, let me know where I'm wrong.

**Comment by xpdavid** [comment]
@cbb692 Yes. That should be the correct convention.

**Comment by xpdavid** [comment]
>  Since the comments do not directly link to any given question

Comments has a field called `feedbackQuestionId` linked to the question entity.

**Comment by cbb692** [comment]
I could very well be missing something here again, but I'm going through FeedbackSessionQuestionTypeTest and stumbled upon a feedbackResponseComment for "comment1OnR3Q1S1C2" (lines 1544 - 1558). 

The only reference to 'Q1S1C2' in the file is on line 1374. However, there is only the first response, whereas the comments represent responses 2 and 3. Not sure how we want to approach situations like this (if they even are problems).

It seems like, to me, the options are to:

1) Change the title/information of the feedbackResponseComment to point to a response that does exist

2) Create new responses that properly match what is in the fRC

3) Delete the fRCs (almost certainly the wrong option, I would expect)

Let me know A) if I'm actually spotting a problem and B) if it is a problem, how I/someone should fix those particular issues. This seems slightly different than the issue originally mentioned (fixing up the IDs for the fRCs), so I could understand opening a different issue to keep things separated. 

Thanks and sorry for the trouble.

**Comment by xpdavid** [comment]
You should not identify the relationship based on the naming e.g. `comment1OnR3Q1S1C2`, `response1ForQ1S1C2`. This name will no be persisted in the database.

```java
    "comment1OnR3Q1S1C2": {
      "courseId": "FSQTT.idOfTypicalCourse1",
      "feedbackSessionName": "MCQ Session",
      "feedbackQuestionId": "1",
      "commentGiver": "student1InCourse1@gmail.tmt",
      "giverSection": "None",
      "receiverSection": "None",
      "feedbackResponseId": "1%student3InCourse1@gmail.tmt%student3InCourse1@gmail.tmt",
      "showCommentTo": [],
      "showGiverNameTo": [],
      "commentGiverType": "STUDENTS",
      "isVisibilityFollowingFeedbackQuestion": true,
      "isCommentFromFeedbackParticipant": true,
      "createdAt": "2016-01-01T23:59:00Z",
      "commentText": "Student 3 comment"
    },
```
If you try to find the response with `"feedbackResponseId": "1%student3InCourse1@gmail.tmt%student3InCourse1@gmail.tmt",`, it actually exist.

```
    "response3ForQ1S1C1": {
      "feedbackSessionName": "MCQ Session",
      "courseId": "FSQTT.idOfTypicalCourse1",
      "feedbackQuestionId": "1",
      "feedbackQuestionType": "MCQ",
      "giver": "student3InCourse1@gmail.tmt",
      "recipient": "student3InCourse1@gmail.tmt",
      "responseMetaData": "{\"answer\":\"It's perfect\",\"otherFieldContent\":\"\",\"questionType\":\"MCQ\"}"
    },
```

**Comment by Adoby7** [comment]
To fix a wrong `feedbackResponseComment`. Do we simply refer it to a random `feedbackResponse`,  or we need to follow some rule, such as each `response` should have limited number of `comments`?

**Comment by xpdavid** [comment]
`or we need to follow some rule, such as each response should have limited number of comments?`

We don't have this constraint.

`Do we simply refer it to a random feedbackResponse`

I believe the information is lost during several refactors. Use `git blame` and examine test code to "guess" the actual response.
