### ISSUE TITLE
Some minor tweaks for the website UI (home page)

### ISSUE THREAD

**Issue by riyadhctg** [TEAMMATES/teammates#9176]
I am suggesting few UI tweaks for the website from a user perspective:

**Footer**
Currently there is no footer in the website. Footer is generally useful for copyright notice etc. From a UX perspective, it might be useful to have a plain, text-based navigation menu on the footer along with easy access to social contacts. An example for clarification:
![image](https://user-images.githubusercontent.com/3258642/46575955-a45e1100-c98d-11e8-9ca3-a843b811c4d5.png)

**User Testimonial**
It's very uncommon to see 'user feedback' right after the feature image or main carousel, especially followed by the other components that looks the same: 
![image](https://user-images.githubusercontent.com/3258642/46576058-97422180-c98f-11e8-8019-c9884b98c555.png)
This testimonial component also appears to be little out of place as its content is changing without any visible difference between this and the following components. Typically, this type of change is indicated by something that tells the user to expect the change. For instance, the little dots in typical bootstrap theme carousels. My suggestion is to have it as the last component in this section (before footer), and to have a separate design for this component. Based on the current design, a simple alternative will be to have a horizontally centered style with something (e.g. dots) to indicate to change (this is secondary). In addition, basic HTML5/CSS3 based transition animations might be used for better result. I feel we don't need a thumbnail image for this component.

**Not for profit image**
The image used for the 'Not for Profit' component in the home page probably looks more like 'for profit'. I am not sure if I am looking at it from a wrong angle - but it just looks like something that promotes business deal etc. Just the 'handshake' would have been nicer. 

I am sure these are not priority items as they are primarily related to the website that is not even the actual product itself. However, if these issues are worth fixing, and the current contributors are busy with more serious issues, I will be happy to work on them. Thanks

**Comment by laurenmayers** [comment]
I'd like to work on the footer if no one else has started this?

**Comment by damithc** [comment]
These ideas are worth consideration. Thanks @riyadhctg 
For now, let us put this on hold as it is not a priority.

**Comment by wkurniawan07** [comment]
Closing as this is not a priority right now
