### ISSUE TITLE
running the page after login -bug-

### ISSUE THREAD

**Issue by fatimah5** [TEAMMATES/teammates#9181]
- **Environment**: Google App Engine Standard Local Server, `master` branch 

**Expected behavior**
Run the page of admin, instructor, or student after login.

**Actual behaviour**
This page and message shown up.
![image](https://user-images.githubusercontent.com/41271008/46640150-e626bd00-cb2f-11e8-8ef5-84266df3fa25.png)

**Additional info**

I run src > test > resources > pages > adminHomePage

**Comment by xpdavid** [comment]
Can you provide the corresponding log for the error?

**Comment by xpdavid** [comment]
Closed due to inactivity. Feel free to open it if the error still cannot be resolved.
