### ISSUE TITLE
FeedbackResponsesLogicTest.java: Make use of `assertEquals` consistent

### ISSUE THREAD

**Issue by joanneong** [TEAMMATES/teammates#9191]
- **Environment**: `master` branch of commit 70cdecc8f578d9687b7254046441370d674228f7

**Expected behaviour**

In JUnit, the `assertEquals` statement takes in two parameters: expected and actual output. This means that the first argument should be the value that we hope to see versus the second argument which is what the program actually outputs.

**Actual behaviour**

However, in this test you can see instances like:

![image](https://user-images.githubusercontent.com/24493463/46912265-45a72180-cfa3-11e8-8f5e-376a8e56d0a1.png)

**Additional info**

It would be good to make the usage consistent, because the corresponding error message produced can be quite misleading. For example, if we are expecting to see `2` as an output, but the program produces `3` instead, the error message should tell us clearly so. However, since the `assertEquals` statement is written in a different format, you can get something like:

![image](https://user-images.githubusercontent.com/24493463/46912280-9159cb00-cfa3-11e8-96bc-79ebc1ef98f3.png)

which can potentially mislead and confuse developers.

**Comment by damithc** [comment]
Looks like a case of swapping the two parameters by mistake. Happens often because we tend to think 'get the actual value and compare with the expected' rather than the other way around. Possibly a flaw in JUnit API design to choose an unintuitive parameter order.

Anyway, this mistake might be there in other test classes as well.

**Comment by wkurniawan07** [comment]
This is not anyone's fault; in the past, there are mixture of usages of [`org.testng.Assert.assert*`](https://static.javadoc.io/org.testng/testng/6.9.4/org/testng/Assert.html) (first parameter is `actual`) , [`org.testng.AssertJUnit.assert*`](https://static.javadoc.io/org.testng/testng/6.9.4/org/testng/AssertJUnit.html) (first parameter is `expected`, and [`org.junit.Assert.assert*`](http://junit.sourceforge.net/javadoc/org/junit/Assert.html) (first parameter is `expected`). It gradually moved towards "the first parameter is `expected`" and only few days ago I put in the rule that all assertions must come from `org.junit.Assert`, but inevitably, there are remains of the practices where the first parameter was still `actual`.

**Comment by cbb692** [comment]
I've got everything switched for the noted class. Would it be better to wait until I go through everything to submit a PR or should I just send what I have for now and get to the rest when I can?

**Comment by xpdavid** [comment]
If your fixes to this issue are completed, go ahead. :)

**Comment by cbb692** [comment]
As I mentioned in the PR, some shenanigans occurred when I was trying to put everything together in regards to another issue I swept through yesterday. Let me know if you want me to start from scratch to more thoroughly follow protocol. Sorry for clogging up everyone's notification feed.

**Comment by cbb692** [comment]
The PR should be good for a thorough pass if anyone has time to go over it.
