### ISSUE TITLE
Sort school names for userMapData.json

### ISSUE THREAD

**Issue by cbb692** [TEAMMATES/teammates#9207]
As per the issues discussed in #9190 , someone needs to go through userMapData.json and confirm the ordering for all lines with the following rule in mind:

When comparing school names A and B, remove all whitespace and symbols (namely, hyphens) from both names, then sort alphabetically.

If we look at an example from the current file, we have "Northwest High School" followed by "Northwestern College". To determine which should actually be first, remove white space and symbols to be left with "NorthwestHighSchool" and "NorthwesternCollege". Afterwards, compare the two strings. Since the 'h' in "High School" comes after the 'e' in "ern", we need to swap the two. 

Repeat this for all lines in the file.

**Comment by cbb692** [comment]
I'm happy to take charge on this, although this could very well be labeled as a good first task, so up to project leads.

**Comment by damithc** [comment]
> I'm happy to take charge on this, although this could very well be labeled as a good first task, so up to project leads.

Thanks for posting this issue @cbb692 Let's leave this to a first timer. Perhaps you can help with reviewing incoming PRs for this issue?.

**Comment by cbb692** [comment]
Sure that's fine with me. I'll keep an eye on it.

**Comment by kollonqv** [comment]
Hi, I'm happy to do it.

**Comment by wkurniawan07** [comment]
Sorry for jumping in the bandwagon, and rather late for that matter.

The rules proposed are reasonable, but this kind of information will get lost over time and is also not very value-adding. Why not just use JSON's natural ordering? A short script to sort all the values in the countries list should not be any longer than 10-20 lines.

**Comment by Mirnal1409** [comment]
I am new to this. Can I start to solve this issue. @cbb692

**Comment by cbb692** [comment]
We've already got two people handling it so it might make sense to look elsewhere. Sorry :(

**Comment by agjay96** [comment]
@cbb692 Can I look into this issue and I'll finish it within few days.

**Comment by monmanuela** [comment]
Hi, I'd like to work on this please
