### ISSUE TITLE
Update user map as at Oct 2018

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9225]
To be done after #9144

New entries to consider:

Australia | Swinburne University of Technology
-- | --
Australia | The University of Sydney
Australia | Torrens University
Australia | University of Sydney
Australia | Western Sydney University - The College
Austria | University of Innsbruck
Belgium | Busleyden Atheneum Campus Zandpoort
Belgium | Hasselt University
Belgium | St. Franciscusinstituut
Belgium | Universiteit Antwerpen
Brazil | ETE FMC
Cambodia | Kate Westbrook
Canada | École de technologie supérieure
Canada | École Secondaire St-François Xavier
Canada | École Technologique Supérieure
Canada | Heritage College
Canada | Kwantlen Polytechnic University
Canada | Massey Secondary School
Canada | Queen's University
Canada | SAIT
Canada | Université du Québec à Montréal
Canada | University of Calgary
Canada | University of Regina
Canada | University of Waterloo
China | Fuzhou University
China | Shanghai American School
Colombia | ICESI University
Colombia | Universidad del Norte
Colombia | Universidad del Norte
Colombia | Universidad Icesi
Denmark | Aarhus University
Denmark | Copenhagen Business School
Denmark | Syddansk Universitet
El Salvador | Universidad Centroamericana José Simeón Cañas
Fiji | University of the South Pacific
Finland | The Finnish Diakonia School
Finland | University of Oulu
France | Atraki
France | CentraleSupélec, Paris-Saclay University
France | chu-toulouse.fr
France | IESEG School of Management
France | IESEG School of Management
France | Université de Lorraine
France | University of Lorraine
Germany | Friedrich-Alexander-University Erlangen-Nuremberg
Germany | Hochschule Zittau Görlitz
Germany | Netbina
Germany | Technical University of Kaiserslautern
Germany | Technische Berufliche Schule 1 Bochum
Greece | Athens University of Economics and Bussines
Guatemala | Universidad Panamericana
Hong Kong | American International Scghool
Hong Kong | HKBUAS Wong Kam Fai Secondary and Primary School
Hong Kong | Hong Kong University of Science and Technology
Hong Kong | Victoria Shanghai Academy
Iceland | Reykjavik University
Ireland | Dublin Institute of Technology
Ireland | University College Dublin
Japan | Ibaraki Prefectural Koga Secondary School
Japan | Tokai University
Kazakhstan | al-Farabi KazNU
Kenya | ALX
Malaysia | Taylor's University
Malaysia | Technology College Sarawak
Malaysia | Universiti Malaysia Perlis
Malaysia | Universiti Teknologi Petronas
Malaysia | University of Reading Malaysia
Malaysia | UTMSPACE
Nederland | HAN University of Applied Sciences
Nederland | Hogeschool Utrecht
Netherlands | Erasmus University Rotterdam
Netherlands | Hogeschool van Arnhem en Nijmegen
Netherlands | Zadkine
New Zealand | Manukau Institute of Technology
Norway | Norges teknisk-naturvitenskapelige universitet
Oman | Sultan Qaboos University
Philippines | A Great Life
Philippines | Ateneo de Davao University
Philippines | Ateneo Graduate School of Business
Philippines | De La Salle Lipa
Philippines | De La Salle Zobel School
Philippines | University of Santo Tomas
Portugal | Instituto Politécnico de Setúbal
Portugal | University of Minho
Singapore | ERC Institute
Singapore | Raffles College of Higher Education
Singapore | Taylor & Francis
Sint Maarten | American University of the Caribbean
South Africa | Cape Peninsula University of Technology
South Africa | Groote Schuur High School
South Africa | Madlenya Academic Smiths (PTY) Ltd
South Africa | Stellenbosch University
South Africa | University of Johannesburg
Spain | CES Don Bosco
Spain | UNIVERSIDAD COMPLUTENSE
Switzerland | Université de Genève
Taiwan | Ming Chuan University
Turkey | Bogazici University
Turkey | Marmara University
UAE | University of Wollongong Dubai
Uganda | Andela
UK | Anglia Ruskin University
UK | Aston Medical School
UK | Kingston University, London
UK | University of Manchester
UK | University of Sussex
USA | Abilene Christian University
USA | AICDC Withdrawal Management
USA | Amherst College
USA | Appalachian State University
USA | Arabia Mountain High School
USA | Art Institute of Austin
USA | Auburn University
USA | Bainbridge High School
USA | Baltimore City Community College
USA | Bentley University
USA | Birmingham-Southern College
USA | Brainerd High School
USA | Brenau University
USA | Brigham Young University-Idaho
USA | California Polytechnic State University
USA | California State Polytechnic University Pomona
USA | California State University San Marcos
USA | California State University Stanislaus
USA | Cartersville Middle School
USA | Cartersville Middle School
USA | Catoctin High School
USA | Chineseshooters.com
USA | City University of New York
USA | Clark University
USA | Cleveland State University
USA | Collin College Frisco
USA | Concordia University Ann Arbor
USA | Conservatory Green Middle School
USA | Corning-Painted Post High School
USA | Des Moines Area Community College
USA | Dr. Albert Einstein Academy
USA | Drexel University
USA | Duke University
USA | East Carolina University
USA | Elizabethtown Community and Technical College
USA | Florida Institute of Technology
USA | Florida International University
USA | Fort Hays State University
USA | Foster High School
USA | Georgetown University
USA | Gower Middle School
USA | Gower Middle School
USA | Gustavus Adolphus College
USA | Hamilton College
USA | Hamline University
USA | Hawaii Pacific University
USA | Heritage Park High School
USA | Iowa State University
USA | Iowa State University of Science and Technology
USA | Kansan University
USA | Kansas Christian College
USA | Kapolei High School
USA | Kennesaw State University
USA | La Salle University
USA | Lamar Middle School
USA | Lee's Summit North High School
USA | Lindenwood University
USA | Long Island University
USA | Montclair State University
USA | Mountain View College
USA | New Mexico State University
USA | North Middle School
USA | Northmont High School
USA | Ohio University
USA | Oregon Institute of Technology
USA | Oregon State University
USA | Pasadena City College
USA | Phillip O Berry
USA | Point Park University
USA | Princeton University
USA | Pulaski High School
USA | Queens University of Charlotte
USA | Regis University
USA | Rensselaer Polytechnic Institute
USA | Richmond High School
USA | Rochester Institute of Technology
USA | Saint Joseph's University
USA | San Diego State University
USA | Santa Clara County Office of Education
USA | SCSDB
USA | Siena College
USA | Southern Illinois University Edwardsville
USA | State University of New York at Oneonta
USA | SUNY Ulster
USA | Syracuse High School
USA | Texas State University, San Marcos
USA | The Chicago School of Professional Psychology
USA | The College of New Jersey
USA | The Ohio State University
USA | Tufts University
USA | UC-Berkeley
USA | UMass Boston
USA | United States Military Academy
USA | United States Military Academy West Point
USA | United States Naval Academy
USA | University at Albany
USA | University at Albany
USA | University of Akron
USA | University of Alaska Anchorage
USA | University of California, Los Angeles
USA | University of Colorado Boulder
USA | University of Connecticut
USA | University of Florida
USA | University of Florida
USA | University of Georgia
USA | University of Illinois at Urbana-Champaign
USA | University of Illinois at Urbana-Champaign
USA | University of Kansas
USA | University of Louisville
USA | University of Minnesota
USA | University of Missouri - Columbia
USA | University of Missouri-Kansas City
USA | University of Mount Union
USA | University of North Carolina
USA | University of North Carolina at Charlotte
USA | University of Rhode Island
USA | University of San Diego
USA | University of San Francisco
USA | University of South Alabama
USA | University of South Carolina Aiken
USA | University of South Florida
USA | University of Southern California
USA | University of St. Thomas, Houston
USA | University of Texas at Dallas/JSOM/ISOM
USA | University of Texas at El Paso
USA | University of Texas at San Antonio
USA | University of Tulsa
USA | University of Utah
USA | University of Washington
USA | University of Wisconsin-Madison
USA | University Prep
USA | US Army Medical Department Center and School
USA | Virginia Common Wealth University
USA | West Covina High School
USA | West Virginia University
USA | Western Michigan University
USA | Western Washington University
USA | Xavier University
USA | Youngstown State University
Vietnam | Can Tho University

**Comment by BeckhamL** [comment]
Hi, I am a first time contributor. I made the changes but when I made the PR, it fails the travis test and I'm not sure why.

**Comment by Mirnal1409** [comment]
Hi, I am also first time coontributor can i work on this . @damithc

**Comment by BeckhamL** [comment]
@Mirnal1409 I've completed it and submitted a PR already
