### ISSUE TITLE
Unable to clear ciTests both locally and on travis

### ISSUE THREAD

**Issue by css911** [TEAMMATES/teammates#9238]
- **Commit SHA:** 
7135af998e661c157ceb3cdfc61a0536d75d27cc

- **Operating System:**
16.04.1-Ubuntu 

- **JDK Version:**
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

- **Node.js Version:**
v10.13.0

- **Google Cloud SDK Version:**
Google Cloud SDK 225.0.0
alpha 2018.11.09
app-engine-java 1.9.68
app-engine-python 1.9.80
beta 2018.11.09
bq 2.0.37
core 2018.11.09
gsutil 4.34
kubectl 2018.11.09

- **Eclipse / IntelliJ Version (if applicable):**
Not Applicable using terminal.

- **Firefox / Chrome Version (if applicable):**
Mozilla Firefox 45.0

**What I was trying to do / What I need help with**
I was trying to resolve issue #9115 and had called for 2 PR request after solving the problem. But the travis citest is failing both online and on local machine as well.

By going through various previous issues i was able to solve some of the failing cases but still few are remaining.

**Attempts to resolve the problem**

1. Checked previous reported issues.
2. Gone through the troubleshooting page.
3. cloned the master repository again and ran the ciTest locally but still i am not able to clear the ./gradlew ciTest (the fresh clone is also not clearing the tests)

**Stack trace**
mangala@mangala-Inspiron-15-7000-Gaming:~/teammates$ ./gradlew ciTests

> Task :testTry4

Failed suite [Failed suite [Failed suite [ci-tests]]] > parallel-ui-tests(failed)(failed)(failed) > teammates.test.cases.browsertests.InstructorFeedbackSessionsPageUiTest.testMiscellaneous PASSED

Failed suite [Failed suite [Failed suite [ci-tests]]] > parallel-ui-tests(failed)(failed)(failed) > teammates.test.cases.browsertests.InstructorCoursesPageUiTest.allTests PASSED

org.gradle.internal.serialize.PlaceholderException: expected:<2018[e
Africa/Abidjan
0
Africa/Accra
0
Africa/Addis_Ababa
180
********** In between entries of countries is been deleted to decrease the size.
Europe/Vatican
60
Europe/Vienna
60
Europe/Vilnius
120
Europe/Volgograd
24]0
Europe/Warsaw
60
E...>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at teammates.test.cases.BaseTestCase.assertEquals(BaseTestCase.java:149)
        at teammates.test.cases.browsertests.TimezoneSyncerTest.testFrontendBackendTimezoneDatabasesAreConsistent(TimezoneSyncerTest.java:40)
        ...

Failed suite [Failed suite [Failed suite [ci-tests]]] > parallel-ui-tests(failed)(failed)(failed) > teammates.test.cases.browsertests.TimezoneSyncerTest.testFrontendBackendTimezoneDatabasesAreConsistent FAILED
    org.junit.ComparisonFailure at TimezoneSyncerTest.java:40

org.gradle.internal.serialize.PlaceholderException: Timed out after 15 seconds waiting for presence of element located by: By.xpath: //div[@id='course-1']//tr[@id='session4']//td[1]
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'mangala-Inspiron-15-7000-Gaming', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-39-generic', java.version: '1.8.0_191'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=45.0, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: c0b04f01-5927-4f31-9f85-42a1862e1b1d
        at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
        at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:261)
        at teammates.test.pageobjects.AppPage.waitFor(AppPage.java:224)
        at teammates.test.pageobjects.AppPage.waitForElementPresence(AppPage.java:447)
        at teammates.test.pageobjects.InstructorHomePage.getElementText(InstructorHomePage.java:373)
        at teammates.test.pageobjects.InstructorHomePage.getEvaluationRowId(InstructorHomePage.java:348)
        at teammates.test.pageobjects.InstructorHomePage.getViewResponseLink(InstructorHomePage.java:199)
        at teammates.test.cases.browsertests.InstructorHomePageUiTest.testShowFeedbackStatsLink(InstructorHomePageUiTest.java:99)
        at teammates.test.cases.browsertests.InstructorHomePageUiTest.allTests(InstructorHomePageUiTest.java:58)
        ...

Failed suite [Failed suite [Failed suite [ci-tests]]] > parallel-ui-tests(failed)(failed)(failed) > teammates.test.cases.browsertests.InstructorHomePageUiTest.allTests FAILED
    org.openqa.selenium.TimeoutException at InstructorHomePageUiTest.java:99
        Caused by: org.openqa.selenium.NoSuchElementException at InstructorHomePageUiTest.java:99
            Caused by: org.openqa.selenium.NoSuchElementException

java.lang.AssertionError: The timezone database version is not up-to-date for more than 20 days, please update them according to the maintenance guide.
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at teammates.test.cases.BaseTestCase.assertTrue(BaseTestCase.java:121)
        at teammates.test.cases.browsertests.TimezoneSyncerTest.testTimezoneDatabasesAreUpToDate(TimezoneSyncerTest.java:63)
        ...

Failed suite [Failed suite [Failed suite [ci-tests]]] > parallel-ui-tests(failed)(failed)(failed) > teammates.test.cases.browsertests.TimezoneSyncerTest.testTimezoneDatabasesAreUpToDate FAILED
    java.lang.AssertionError at TimezoneSyncerTest.java:63

5 tests completed, 3 failed

> Task :testTry4 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':testTry4'.
> There were failing tests

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 9s
16 actionable tasks: 9 executed, 7 up-to-date

**Comment by css911** [comment]
Or should i create the PR for #9115 even if the travis test are failing.

**Comment by xpdavid** [comment]
You forget to run Godmod. Please follow our dev guide on how to do it.

For `TimezoneSyncerTest`, maybe you can try to delete the build folder and run the test again?

**Comment by css911** [comment]
Steps which i carried out.

1. I tried out the godmode. I ran test in the godmode then turned it off and then again ran the test.

2. for the timezone error i deleted the build folder and ran the tests. The timezone error still persists.

3. I retraced the dev guidelines once again.

    a).Clone the project 

    b).I already had jdk and python, node, google sdk install. checked their versions.

    c). ran the command ./install.sh --path-update true in the sdk folder.

    e) App engine java was also installed.

    f) i setuped my repository accoring to the step 2 in the dev guide.

    g)Step 3 performed Set up project-specific settings and dependencies.

    h) Managing the dev server.

    i)Login as Admin created a single instructor and a student.

     j) Testing Using Firefox in god mode and then shutting down god mode and running the test again.

     g) i have also executed gcloud auth login command and had created a project id for the project. I had made changes to build.properties file as well as it was asked to get in GAE setup.

	ScreenShot.

**Comment by xpdavid** [comment]
You only need to run godmod on the failed test. They should pass with godMod and then pass in the subsequent run. You should expect some `.html` changes in your `git status`.

Not sure what had happened in `TimezoneSyncerTest`. Maybe you can ignore it and send a PR directly.

**Comment by css911** [comment]
Thank you so much @xpdavid . Really sorry to bother you so much. I have raised a PR. please review it. Can you please also assign a new issue to solve. Thank you once again :)
