### ISSUE TITLE
Data Migration: Convert HTMLSanitized Data in StudentAttributes

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9247]
Data migration initiated by PR [Unknown] (Related commit https://github.com/TEAMMATES/teammates/commit/ffaf5f88089234ce7ef504ab5471b38be1f96d72).

Related to #4588 

The `DataMigrationForSanitizedDataInStudentAttributes` should be run to Convert HTMLSanitized Data in StudentAttributes

- [x] Merged code that work for both the old and new versions of the data schema.
- [x] Released a version containing the above in [VERY OLD VERSION].
- [x] Created a client script to migrate all data following the old schema to the new schema in https://github.com/TEAMMATES/teammates/commit/ffaf5f88089234ce7ef504ab5471b38be1f96d72 & PR #9232.
- [ ] Ran the script against the live site.
- [ ] Removed the code that is specifically tailored for the old data schema in PR #.

**Comment by wkurniawan07** [comment]
Closing (see #4588 for reasons)
