### ISSUE TITLE
Remove keepUpdateTimestamp in FeedbackQuestion

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9249]
`keepUpdateTimestamp` is only set to `true` in test case and it is always `false` in production code.

For data migration script, we will use the Objectify API directly. Thus, this field also does not help in this case.

**Comment by scelestus1** [comment]
I'm quite new to contributing to OSS projects, but I'd like to give this one a stab, if you don't mind. Thanks!
