### ISSUE TITLE
Remove keepUpdateTimestamp in CourseStudent

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9250]
`keepUpdateTimestamp` <strike>is only set to `true` in test case and it</strike> is always `false` in production code.

For data migration script, we will use the Objectify API directly. Thus, this field also does not help in this case.

**Comment by peterr101** [comment]
Hi, I am new to open source contributions but would like to take on this issue - is that possible?

**Comment by bmw2621** [comment]
Id like to try this.  But I cant find were the variable is set to true.  Ive searched the entire project.

**Comment by xpdavid** [comment]
@bmw2621 Yes. It is always false.

**Comment by aman-coolinc1** [comment]
Hi i would like to take up this issue, please clarify the problem statement as i am new to this.

**Comment by aman-coolinc1** [comment]
Hi @xpdavid , I found that the transient boolean variable keepUpdateTimestamp is always true for test code, and always false for Production code.
As i am not clear on what has to be done to resolve the issue, can you please provide more details.

**Comment by css911** [comment]
Hello @aman-coolinc1, A PL has been generated for this issue. please go through other issues.
