### ISSUE TITLE
Remove/Replace methods *WithoutDocument in StudentsDb

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9251]
In StudentsDb, almost all methods except GET have the second version - `*WithoutDocument`/`*WithoutSearchability`. It seems that those methods are only used in tests.

In test case, we are safe to use the original version (i.e. It is totally fine to put the document) as action test are independent from each others and the local database emulator will be cleared after each action test.

P.S. Not sure if all of them can be removed/replaced. Any contributor who take this should investigate the problem throughly.

**Comment by akash1994deep** [comment]
I am working on this issue.

**Comment by priyamalM** [comment]
I am working on this issue and made a pull request as well. :D
