### ISSUE TITLE
Javadoc: Fix Inspection Results report by IntelliJ

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9252]
![image](https://user-images.githubusercontent.com/13977235/49329219-a40d7b00-f5b6-11e8-8978-2c93c68fe907.png)

![image](https://user-images.githubusercontent.com/13977235/49329230-bd162c00-f5b6-11e8-9ada-0852ed15dcc7.png)

**Comment by softgengaurav** [comment]
@xpdavid , Can i work on this issue?

**Comment by AndrewMacmillan87** [comment]
@xpdavid does this issue still need resolving? I am trying to get involved with open-source this is my first crack at it. Can I work on this?

**Comment by xpdavid** [comment]
@AndrewMacmillan87 Go ahead as long as the issue is open.

**Comment by AndrewMacmillan87** [comment]
There's a reference to the same issue saying that you closed itn1 day ago due to inactivity. It says its an open issue at the top though... which file does it refer to? InstructorFeedbackResponseCommentDeleteAction.java?

**Comment by wkurniawan07** [comment]
@AndrewMacmillan87, you're referring to a PR attempt for this issue which has (presumably) been abandoned. The issue itself is still very much open.
As for which files need changing, I'm afraid the onus is on you to find out.

**Comment by Michaellin250** [comment]
Is this issue closed? I want to get started with open source projects.

**Comment by nkshschdv** [comment]
Hi @xpdavid , Could you please review ?

**Comment by thelizzerd** [comment]
It still shows this issue as open, was it ever resolved?
