### ISSUE TITLE
contributor Mba Sob Gildas

### ISSUE THREAD

**Issue by gildas15** [TEAMMATES/teammates#9259]
Before opening a new issue, please check that no existing issue covers the same topic.

Go to the "Preview" tab and click on the relevant issue type to be redirected to the appropriate template.

- [Bug reports](?template=bug-report.md)
- [Feature/enhancement requests, enhancement to build process](?template=feature-request.md)
- [Help requests](?template=help-request.md)
- [Data migration](?template=data-migration.md)

For other tasks (e.g. refactoring, adding tests, fixing typo), there is no template to follow. Simply provide a clear issue title and description of the work to be done.

If you are reporting a security vulnerability, due to the sensitive nature of such a report, you are kindly requested to refrain from opening a new issue.
Instead, submit your report by emailing the team at teammates@comp.nus.edu.sg.

**Comment by gildas15** [comment]
Please I am Mba Sob Gildas. and I would like to contribute to this project

**Comment by wkurniawan07** [comment]
Welcome @gildas15! You're free to chip in to any open issues that you're interested in. Recommended to start with those labelled `d.FirstTimers` or `d.Contributors`.

**Comment by gildas15** [comment]
ok tanks

Le mar. 4 déc. 2018 à 07:44, Wilson Kurniawan <notifications@github.com> a
écrit :
