### ISSUE TITLE
Case Study on TEAMMATES

### ISSUE THREAD

**Issue by walkers019** [TEAMMATES/teammates#9275]
Hello everyone,
I’m a computer science student from TUM (technical university of Munich – Germany) and currently working on a case study for a seminar paper. It would be really nice if you could help me, it will only take you up to 10 minutes! 

I need comparative values to this question:
Please name the 10 most important classes of TEAMMATES, which you would recommend to a new developer for his training period.
So the 10 most important classes you have to look at and understand before starting to develop for TEAMMATES.

Thanks a lot in advance!
Lena

**Comment by damithc** [comment]
@walkers019 there is no general answer to that question. We have a 'Contributor Orientation Guide' for new contributors. All the best for your study.
