### ISSUE TITLE
javax/activation/DataSource:NoClassDefFoundError: Help Request: getting errors when try to deploy the app using terminal instead of deploying it with IDE

### ISSUE THREAD

**Issue by priyamalM** [TEAMMATES/teammates#9291]
- Commit SHA:*7b80803426283868e310b5eb71be90f6788d4855*
- Operating System:*Mac Os sierra*
- JDK Version:*1.8*
- Node.js Version:*v8.10.0*
- Google Cloud SDK Version:*228.0.0*
- Eclipse / IntelliJ Version (if applicable):*2017.3.5(build 173.4674.33)*
- Firefox / Chrome Version (if applicable):*chrome*

I was trying to deploy the app locally using the command `appengineRun` and `appengineStart` Both
and got an error saying 
```
SEVERE: Unexpected exception caught by ControllerServlet : 
java.lang.NoClassDefFoundError: javax/activation/DataSource
```

when trying to insert a new Instructor to the system but I was able to get rid of the issue after deploying the app using IntelliJ googleAppEnging plugin. am I missing something or should I add additional configurations when trying to deploy the app using the terminal?
![screen shot 2018-12-28 at 11 07 58 pm](https://user-images.githubusercontent.com/14792739/50523369-d1860f80-0af5-11e9-81c8-d0a923b2c546.png)

**Attempts to resolve the problem**

got this issue fixed after running the app from IntelliJ googleAppEngine plugin.

**Comment by wkurniawan07** [comment]
@priyamalM do you still face this problem?

**Comment by priyamalM** [comment]
@wkurniawan07 i am still getting this issue.

**Comment by xpdavid** [comment]
@priyamalM Delete `build` folder and try again?
