### ISSUE TITLE
Potential NullPointerException

### ISSUE THREAD

**Issue by aravinth2094** [TEAMMATES/teammates#9293]
**Steps to reproduce**
Pass null to isWhiteSpace function

**Expected behaviour**
return boolean value

**Actual behaviour**
throws NullPointerException

**Comment by xpdavid** [comment]
Is is necessary to add the null check?

**Comment by aravinth2094** [comment]
The function caller should not be alarmed with an exception if he passes the wrong value for a trivial operation.

**Comment by xpdavid** [comment]
1. I don't think `null` should be considered as a whitespace.

2. We are not a API library so I think it is fine to leave it there. After all, if we want to make every method NPE-free, it is a lot of work and it does not worth the benefit.

3. No production code would trigger the NPE (I am not sure about this, need your investigation)

**Comment by aravinth2094** [comment]
Agreed! :+1:
