### ISSUE TITLE
Mobile usability issues in the landing page

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9296]
Mobile usability issues reported by Google:
![image](https://user-images.githubusercontent.com/1673303/50554160-7e2be100-0cf0-11e9-97d9-e8689466e29d.png)

We may want to fix these because Google is said to be lowering the search rank of websites that have usability problems.

**Comment by wkurniawan07** [comment]
No use doing this now since V7:
- Brings about new UI courtesy of Bootstrap 4, and
- Changes the front-end to single-page application which will bring an entire new set of problem for SEO

**Comment by damithc** [comment]
In that case we can wait till V7. I think this issue is specific to the landing page though. Google won't be able to access the other pages.

**Comment by wkurniawan07** [comment]
Closing as:
- Not a priority at the moment
- Probably will be part of #9357 anyway
