### ISSUE TITLE
Instructor account creation localy

### ISSUE THREAD

**Issue by gildas15** [TEAMMATES/teammates#9299]
Good  evening here please I need help, I have setup the project localy on my machine But I am unable to create an instructor account for myself locally to go through the app. I need help

**Comment by tanhengyeow** [comment]
Hi @gildas15 

Do you mind posting the steps you took that lead to the issues you're facing? Ideally, screenshots on error logs would assist us in helping you.

**Comment by gildas15** [comment]
I had the following error when I try to login as an instructor locally. 
![instructor](https://user-images.githubusercontent.com/36203062/50658343-f6183680-0f90-11e9-9086-239c643610cf.png)

**Comment by gildas15** [comment]
I just want to go through the app

**Comment by tanhengyeow** [comment]
@gildas15 Have you followed this [part](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#logging-in-to-a-teammates-instance) of the docs?

If you did and still face the same error, could you post the error logs present in your console?

**Comment by gildas15** [comment]
ok thanks

**Comment by ChooJeremy** [comment]
I experienced the same issue as well. This error occurs if you perform the following:
* Click on instructor login at the top right 
* Check the sign as Administrator checkbox
* Click the Log In button.

The next page is similar to the screenshot as attached above.
The problem appears to be that admins do not have instructor privileges, so they are denied access to the instructor pages.
The problem does not occur if the following steps are done instead:
* Visit /admin/adminHomePage
* You are then redirected to the login page.
* Check the sign as Administrator checkbox
* Click the Log In button.

**Comment by xpdavid** [comment]
Hi @ChooJeremy and @gildas15, you need to go to `/admin/admiHomePage` (**login as admin**) to create an instructor and join the course. After that, you can use the `Instructor Login` link.

**Comment by gildas15** [comment]
ok thanks

**Comment by gildas15** [comment]
please get a look of this error that I have on my console
![console](https://user-images.githubusercontent.com/36203062/50725853-74451c00-10fc-11e9-909b-d13b3afddc6a.png)

**Comment by xpdavid** [comment]
I think you did not run `npm run build` :)

**Comment by gildas15** [comment]
ok thanks

**Comment by gildas15** [comment]
I succeded

**Comment by gildas15** [comment]
Please can I share the feature I will to work on here or I should start working on the issues to solve

**Comment by xpdavid** [comment]
We recommend you to start from some firstTimer issue :)

**Comment by gildas15** [comment]
Please the system does not send invitation links. I don't know why

**Comment by xpdavid** [comment]
The email service won't work in the local development environment.

**Comment by gildas15** [comment]
Please as the email don't work locally to send invitation link to student, I don't know how to access the student view of the application.

**Comment by gildas15** [comment]
Please this are the only question type that show, was that suppose to be like that
![question](https://user-images.githubusercontent.com/36203062/51982521-2a96e980-248e-11e9-94c0-9cfa90bb4e3b.png)

**Comment by xpdavid** [comment]
We are doing migration from SSR to angular. For full feature, please refer to the release branch.

**Comment by gildas15** [comment]
ok thanks
