### ISSUE TITLE
Update user map for Nov-Dec 2018

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9304]
To be done after #9225

New entries to consider:

Country | University
-- | --
Australia | Bond University
Australia | Griffith University
Australia | University of Western Australia
Belgium | AP Hogeschool
Belgium | AP University College
Belgium | HoGent
Belgium | KSO Glorieux
Belgium | Sint-Lodewijkscollege
Belgium | Universite Libre de Bruxelles
Brazil | Centro Universitário Integrado
Brazil | Federal University of Technology - Paraná
Cameroon | Catholic University Institute of Buea
Canada | Calgary Arts Academy
Canada | Humber College
Canada | Kwantlen Polytechnic University
Canada | McGill university
Canada | Memorial University of NL
Canada | Mohawk College
Canada | Ryerson University
Canada | Sheridan College
Canada | Thames Valley District School Board
Canada | Trent University
Canada | UBC - Vancouver
Canada | Université de Sherbrooke
Canada | University of Lethbridge
Canada | University of Manitoba
Canada | University of Waterloo
China | Moonshotacademy
Cyprus | University of Cyprus
Egypt | American University in Cairo
Egypt | AUC
Egypt | Non-profit initiative for Peace Building and Education
Egypt | The American University in Cairo
El Salvador | Universidad Centroamericana José Simeón Cañas
France | Audencia
France | Neoma Business School
France | SKEMA Business School
Germany | South Westphalia University of Applied Sciences
Germany | University of Duisburg-Essen
Germany | University of Potsdam
Honduras | DelCampo school
Honduras | The American School of Tegucigalpa
Hong Kong | Community College of City University
Hong Kong | St Hilary's School
India | PICT
Indonesia | Universitas Indonesia
Ireland | Dublin Institute of Technology
Ireland | National University of Ireland, Galway
Ireland | Trinity College Dublin
Ireland | University College Dublin
Ireland | University College Dublin
Italy | Politecnico di Milano
Kenya | Andela
Korea | Seoul National University
Lebanon | American University of Beirut
Malaysia | UniSZA
Malaysia | Universiti Sains Malaysia
Malaysia | Universiti Sains Malaysia
Malaysia | Universiti Teknologi Malaysia
Malaysia | Universiti Teknologi MARA
Malaysia | Universiti Utara Malaysia
Malaysia | University of Malaya
Malaysia | University of Technology
México | CETYS
Netherlands | Avans
Netherlands | PCOU Willibrord
Netherlands | Saxion  University of Applied Sciences
Netherlands | Technische Universiteit Eindhoven
Netherlands | University of Amsterdam
New Zealand | University of Auckland
Oman | Sultan Qaboos University
Peru | National University of San Agustin
Peru | UNSA
Philippines | De La Salle Lipa
Philippines | De La Salle Lipa Inc.
Philippines | De La Salle Medical & Health Sciences Institute
Phillipines | ANGELES UNIVERSITY FOUNDATION
Portugal | Instituto Superior Técnico
Portugal | University of Minho
Saudi Arabia | Al-Imam University
Saudi Arabia | Imam Abdulrahman bin Faisal University
Saudi Arabia | King Fahd University of Petroleum and Minerals
Saudi Arabia | Taif University
Singapore | National Institute of Education
Singapore | National University of Singapore
Singapore | Ngee Ann Polytechnic
Singapore | Presbyterian High School
Singapore | Singapore American School
Singapore | Singapore Institute of Technology
Singapore | Singapore Polytechnic
Singapore | United World College South East Asia
South Africa | Sedibeng College
South Korea | Changwon National University
South Korea | Chungnam National University
South Korea | KAIST
South Korea | NLCS Jeju
Spain | IES G Torrente Ballester
Sweden | Jönköping University
Thailand | Thammasat University
Thailand | Ubon Ratchathani University
UAE | AXA Insurance
UAE | Brighton College Abu Dhabi
UAE | Zayed University
UK | Blackboard Academy
UK | Huddersfield University
UK | LSBU
UK | Queen's University Belfast
UK | Sheffield Hallam University
UK | University of Bradford
UK | University of Dundee
UK | University of Huddersfield
UK | University of Portsmouth
UK | University of the West of England
UK | University of York
USA | Academies @ Englewood
USA | Arizona State University
USA | Army Logistics University
USA | Army Logistics University
USA | Art Institute of San Antonio
USA | Belmont University
USA | Bentley University
USA | Bryant University
USA | California State University, Fullerton
USA | Carmel Christian School
USA | Central Connecticut State University
USA | Chapman University
USA | Clarkson University
USA | Colby College
USA | Coleman Middle School
USA | Denver Public Schools
USA | Duke University
USA | Duke University
USA | Emergent Academy
USA | Fairfield University
USA | Fairmont State University
USA | Florida International University
USA | Fort Lewis College
USA | Fort Lewis College
USA | Frontier Nursing University
USA | George Bush High School
USA | Georgia Southern University
USA | Grady High School
USA | Grand Valley State University
USA | Hazleton Area High School
USA | Hazleton Area High School
USA | Hillsborough Community College
USA | Indiana State University
USA | Indiana University
USA | Iowa State University
USA | Ivy Tech Community College
USA | jpmorgan2@plymouth.edu
USA | Kennesaw State University
USA | Laing Middle School
USA | Lewis University
USA | Lincoln Jr High School
USA | Long Island University
USA | Marion Military Institute
USA | McKendree Univeristy
USA | Medical College of Wisconsin
USA | Merrimack College
USA | Merrimack College
USA | Methodist University
USA | Miami University
USA | Miami University
USA | Moorpark College
USA | New Jersey City University
USA | Northeastern University
USA | Ohio State University
USA | Oklahoma State University
USA | Penn Brook Elementary School
USA | Perot Museum of Nature and Science
USA | Plymouth State University
USA | Plymouth State University
USA | Prairie View A&M University
USA | Purdue University
USA | Quinnipiac University
USA | Rensselaer Polytechnic Institute
USA | Roanoke College
USA | San Diego State University
USA | San Diego State University
USA | San Francisco State University
USA | Solanco High School
USA | Southern Oregon University
USA | St. Philip's College
USA | SUNY New Paltz
USA | Texas Tech University
USA | Towson University
USA | Tulane University
USA | Union High School
USA | University at Albany
USA | University at Albany
USA | University at Buffalo
USA | University Charter School
USA | University of Akron
USA | University of Central Missouri
USA | University of Chicago
USA | University of Colorado Boulder
USA | University of Dayton
USA | University of Florida
USA | University of Georgia
USA | University of Kansas
USA | University of Louisiana at Lafayette
USA | University of Massachusetts Boston
USA | University of Michigan
USA | University of Nebraska
USA | University of Nebraska Kearney
USA | University of Nebraska-Lincoln
USA | University of New Hampshire
USA | University of North Carolina
USA | University of San Francisco
USA | University of Southern California
USA | University of St. Thomas-Houston
USA | University of Tampa
USA | University of Texas at El Paso
USA | University of Washington
USA | University of Wisconsin Stevens Point
USA | University of Wisconsin, Green bay
USA | Virginia Commonwealth University
USA | West Georgia Technical College
USA | Western New England University
USA | Wright State University
USA | Saint Louis University

**Comment by Manish-Giri** [comment]
I can take this up.

**Comment by amrut-prabhu** [comment]
Hi @Manish-Giri, thanks for your interest in TEAMMATES!
However, as mentioned in the issue description, we'd like to resolve #9225 first (and #9144 before that). 
I suggest that you look into some other [first timers issue](https://github.com/TEAMMATES/teammates/labels/d.FirstTimers) instead of this one :)

**Comment by Manish-Giri** [comment]
Hi @amrut-prabhu 

My mistake, I should have made myself clearer. I meant I'm happy to wait until #9225 and #9144 are resolved, and then I could work on this. But I'll search for other issues.

**Comment by okasha30495** [comment]
Hey @damithc 

Im actually interested on working on this issue as well or #9225 and #9144 , but could you tell me how to actually test the code once the JSON has been all updated?

**Comment by damithc** [comment]
> Im actually interested on working on this issue as well or #9225 and #9144 , but could you tell me how to actually test the code once the JSON has been all updated?

Start the dev server, load the relevant page manually, and check visually. there is no automated test for this page.
