### ISSUE TITLE
IntelliJ IllegalArgumentException on starting local web server

### ISSUE THREAD

**Issue by ChooJeremy** [TEAMMATES/teammates#9306]
- **Environment**: `master` branch at commit 7b80803426283868e310b5eb71be90f6788d4855

**Steps to reproduce**
I followed the steps in the following articles:
* [Setting up](https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md)
* [Set up IntelliJ](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-setup.md)
* [Set up Static Analysis tools](https://github.com/TEAMMATES/teammates/blob/master/docs/static-analysis.md)
* [Starting the dev server with IntelliJ](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md) i.e. `Run -> Run` and choosing `Google App Engine Standard Local Server` 

**Expected behaviour**
The dev server starts up at localhost:8080.

**Actual behaviour**
IntelliJ fails with the following message:
```
Error running 'Google App Engine Standard Local Server'
	Error running Google App Engine Dev Server.
	Exception occurred : java.lang.IllegalArgumentException
	Exception message : Argument for @NotNull parameter 'process' of com/intellij/execution/process/OSProcessHandler.<init> must not be null
```

**Additional info**

If the server is started with the command line instead (`./gradlew appengineStart` or `./gradlew appengineRun`), then there is no such error.
To resolve this issue, go to `Tools -> Google Cloud Tools -> Add App Engine Support -> Google App Engine Standard`. Under the Choose Module prompt, select `teammates` and click `OK`. In the next Add Google App Engine Standard Framework prompt, check all of the following libraries:
* Servlet API
* JSP Standard Tag Library (JSTL)
* App Engine API
    * Cloud Endpoints Frameworks for App Engine
    * Objectify

Then click on OK. Wait for indexing to complete, and then re-compile.

I am thinking of adding this into the documentation, but I'm not sure where it would go. If this affects all users, perhaps [IDE setup](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-setup.md) is a good choice. If others aren't experiencing this problem, then perhaps it could go under the [Troubleshooting guide](https://github.com/TEAMMATES/teammates/blob/master/docs/troubleshooting-guide.md). 

I'm also not sure if all of the items (Servlet API, JSTL, App Engine API, Cloud Endpoints, Objectify) need to be checked. I know that Servlet is definitely used, and I believe JSP and Objectify is used within the project as well.

**Comment by wkurniawan07** [comment]
> If the server is started with the command line instead (`./gradlew appengineStart` or `./gradlew appengineRun`), then there is no such error.

Irrelevant here; this error is IntelliJ-specific.

Also, maybe you skipped this step of setup?

> Click on `Configure` and ensure that only the `Google App Engine Standard` framework is shown, then click `OK`. If there are other frameworks shown, click `Cancel` and wait until indexing is completed, then try again.

**Comment by ChooJeremy** [comment]
I definitely did that step, I remember deselecting web from the list of options and leaving only Google App Engine Standard within the list. After clicking ok, it simply closes. (No option to tick libraries or anything like that)

**Comment by wkurniawan07** [comment]
@ChooJeremy can you follow [this template](https://github.com/TEAMMATES/teammates/issues/new?template=help-request.md) instead? There's not enough information here and also this cannot be classified as a bug in the first place.

**Comment by ChooJeremy** [comment]
Sure. It's not really a help request though, the problem is resolved on my end. I just wondered if you guys would want to add how I resolved it to FAQ or something.



- **Commit SHA:** 4936d15bbf19c60ec2ba43103149c1c0b62a2177
- **Operating System:** Windows 10
- **JDK Version:** 1.8
- **Node.js Version:** v10.15.0
- **Google Cloud SDK Version:** 228.0.0
- **Eclipse / IntelliJ Version (if applicable):** IntelliJ IDEA Ultimate 2018.3.2

**What I was trying to do / What I need help with**



Attempting to [start the dev server with IntelliJ](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md) i.e. Run -> Run and choosing `Google App Engine Standard Local Server` resulted in the following error:
```
Error running 'Google App Engine Standard Local Server'
	Error running Google App Engine Dev Server.
	Exception occurred : java.lang.IllegalArgumentException
	Exception message : Argument for @NotNull parameter 'process' of com/intellij/execution/process/OSProcessHandler.<init> must not be null
```

**Attempts to resolve the problem**

To resolve this issue, go to Tools -> Google Cloud Tools -> Add App Engine Support -> Google App Engine Standard. Under the Choose Module prompt, select teammates and click OK. In the next Add Google App Engine Standard Framework prompt, check all of the following libraries:

* Servlet API
* JSP Standard Tag Library (JSTL)
* App Engine API
    * Cloud Endpoints Frameworks for App Engine
    * Objectify

Then click on OK. Wait for indexing to complete, and then re-compile.

**Comment by wenmogu** [comment]
I agree that we should add it in. I encountered this problem a few times. Although google gives me the answer, it will be helpful if we add it into the [troubleshooting guide](https://github.com/TEAMMATES/teammates/blob/master/docs/troubleshooting-guide.md).

**Comment by wkurniawan07** [comment]
No longer relevant
