### ISSUE TITLE
ide-setup.md: improve IntelliJ indentation guideline

### ISSUE THREAD

**Issue by jeffreyjhaywood** [TEAMMATES/teammates#9311]
ide-setup.md: Indentation guideline misinformation

- **Environment**:  Live V6.2.0, master branch

**Steps to reproduce**
N/A. Gramattical error in documentation.

**Expected behaviour**
Should list the languages Java, Javascript, CSS, and XML separately from HTML, JSON and JSP due to them having different indentation requirements.

**Actual behaviour**
All of the stated languages are listed together. Documentation is misleading.

**Additional info**

 I can edit the documentation to be more clear.

**Comment by reeshabhkumarranjan** [comment]
I too had difficulty in understanding the indentations numbers.

**Comment by AkshitOstwal** [comment]
i would like to solve this issue , can I.
