### ISSUE TITLE
Getting "Framework detected" every time I open IntelliJ IDE.

### ISSUE THREAD

**Issue by reeshabhkumarranjan** [TEAMMATES/teammates#9313]
- **Commit SHA:** 
- **Operating System: Windows 10**
- **JDK Version: 1.8.0_191**
- **Node.js Version: v10.15.0**
- **Google Cloud SDK Version: 229.0.0**
- **Eclipse / IntelliJ Version (if applicable) IntelliJ IDEA 2018.3.2:**
- **Firefox / Chrome Version (if applicable): Google Chrome 71.0.3578.98**

**What I was trying to do / What I need help with**

I am new to this project, and I followed [this document](https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md). Finally, I set up the static analysis tools as per the [guide here](https://github.com/TEAMMATES/teammates/blob/master/docs/static-analysis.md). However, every time I am opening IntelliJ, I am getting this message:
![image](https://user-images.githubusercontent.com/25811225/50900653-d921ae80-143b-11e9-892e-761248888daf.png)

Should I click `Configure`? However, I already clicked `Configure` when this message popped for the first time when setting up IntelliJ for this project (x. subpoint point of 1st point of [this documentation](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-setup.md#project-setup-1)) I am not clicking `Configure` again because this documentation says to click `Configure` only when only **Google App Engine** framework is the only framework detected. Here, both **Web** and **Google App Engine** frameworks are appearing/detected.

**Attempts to resolve the problem**

I did not attempt to resolve the problem, fearing that I might end up in an even worse state.

**Comment by wkurniawan07** [comment]
Have you consulted [this document](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-setup.md#intellij-idea)?

**Comment by reeshabhkumarranjan** [comment]
> Have you consulted [this document](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-setup.md#intellij-idea)?

Yes, I told in my issue description that I have referred that document.

**Comment by wkurniawan07** [comment]
Why do you not try? At this stage even if you do something wrong the cost of re-setting up is very low.

**Comment by reeshabhkumarranjan** [comment]
Okay, I will try it then.

> Why do you not try? At this stage even if you do something wrong the cost of re-setting up is very low.

Okay, I will try it then.

**Comment by reeshabhkumarranjan** [comment]
> Why do you not try? At this stage even if you do something wrong the cost of re-setting up is very low.

Okay, I will try it then.

**Comment by wkurniawan07** [comment]
Closing as it looks like the problem has been resolved.
