### ISSUE TITLE
Hello all , I am new to open source community ,would love to start my journey from here ,please guide me .

### ISSUE THREAD

**Issue by AkshitOstwal** [TEAMMATES/teammates#9328]
# HELLO  ALL
I am totally new to open source i would like to contribute to this project for GSoC 2019 as well .
this project drew my attention as i really like the idea behind it.
I would love to start my journey from this project Please guide me How to ?
I know C ,C++,JAVA , MYSql ,learnning python right now , have past experiences of many hackathons .

**Comment by tanhengyeow** [comment]
Hi @AkshitOstwal 

Please look through the [docs](https://github.com/TEAMMATES/teammates/blob/master/docs/CONTRIBUTING.md) to get started :) Feel free to post any issues/questions you have along the way.
