### ISSUE TITLE
Need help:to get started

### ISSUE THREAD

**Issue by Arpitpundir** [TEAMMATES/teammates#9330]
hii, i am new here, so if anybody could help me to get started that would be really helpfull, i know javascript, i just wanna know what tech teammates is using, so that i can learn it and start contributing and any other advice for a gsoc aspirant  would be appreciated?

**Comment by xpdavid** [comment]
Hi @Arpitpundir 

Please look through the [docs](https://github.com/TEAMMATES/teammates/blob/master/docs/CONTRIBUTING.md) to get started :) Feel free to post any issues/questions you have along the way.
