### ISSUE TITLE
development.md: Fix Firefox E2E setup misinformation

### ISSUE THREAD

**Issue by amrut-prabhu** [TEAMMATES/teammates#9336]
development.md#using-firefox: Mentions "chromedriver executable" under geckodriver setup.

- **Environment**: 
`master` branch at commit d81f75e

**Steps to reproduce**
N/A. Small error in documentation.

**Expected behaviour**
Should state that the geckodriver executable path should be added.

**Actual behaviour**
"Specify the path to the **chromedriver** executable in test.geckodriver.path"

**Additional info**

I can edit the documentation to fix this simple error.

**Comment by wkurniawan07** [comment]
Must be tardiness on my part when updating the documents. @amrut-prabhu please be welcomed to.
