### ISSUE TITLE
could not set up developing enviroment , step 3,npm install and angular CLI client

### ISSUE THREAD

**Issue by AkshitOstwal** [TEAMMATES/teammates#9341]
- **Commit SHA: ba91074b70129892364b3a6df8e0b3c15c75eae5 ** 
- **Operating System:windows 10**
- **JDK Version: java version "1.8.0_192"**
- **Node.js Version:v11.7.0**
- **Google Cloud SDK Version:230.0.0**
- **Eclipse / IntelliJ Version (if applicable):intellij 2018.3.3**
- **Firefox / Chrome Version (if applicable):**

** step 3 of setting up enviroment**
error while running this code 

`C:\Users\akshi>npm install -g @angular/cli@6`
`npm ERR! Unexpected end of JSON input while parsing near '....5.1","mv":"^2.1.1","'`

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     C:\Users\akshi\AppData\Roaming\npm-cache\_logs\2019-01-19T13_18_54_410Z-debug.log`

and also while npm install in directory

`E:\win softwares\github\teammates>npm install`
`npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.`
`npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).`
`npm ERR! Unexpected end of JSON input while parsing near '...3.1"},"bin":{"rimraf"'`

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     C:\Users\akshi\AppData\Roaming\npm-cache\_logs\2019-01-19T13_16_14_882Z-debug.log`

**Attempts to resolve the problem**
tried "  `npm install -g npm-check-updates` "before 1 st error also
tried " `npm init` " before 2nd error also
but couldnt rectify error

 THANKS IN ADVANCE

**Comment by xpdavid** [comment]
Network error? Or Error in NodeJS itself. If you search `npm ERR! Unexpected end of JSON input while parsing near` on Google. You will find a bunch of possible solution. You can first try that.

**Comment by AkshitOstwal** [comment]
done that , issue soved thanks @xpdavid
