### ISSUE TITLE
Status messages and error messages can be missed by users

### ISSUE THREAD

**Issue by ChooJeremy** [TEAMMATES/teammates#9346]
- **Environment**: `master` branch at commit ba91074b70129892364b3a6df8e0b3c15c75eae5

**Steps to reproduce**
* Login as instructor
* Go to edit a feedback session page. Sample URL: localhost:4200/web/instructor/sessions/edit?fsname=First%20team%20feedback%20session&courseid=_courseID_
* Click edit, then click save on the first question

**Expected behaviour**
* Any resulting status message appears nearby the question, where it is easily viewable for the user.

**Actual behaviour**
* The status message appears at the very top of the page instead.

**Additional info**

* You can retrieve course IDs from localhost:8080/_ah/admin/datastore?&kind=FeedbackSession&order=\_\_key\_\_

**Comment by tanhengyeow** [comment]
Hi @Gaurav-Punjabi 

Thanks for your interest. However, we would recommend new contributors to attempt `d.FirstTimers` issues to get yourself started. 

Also, this feature is labelled `c.Epic` so it might be a little complex for new comers to attempt. Even so, you are welcome to post suggestions on your approach to solve this issue for discussion :)

**Comment by ChooJeremy** [comment]
@wkurniawan07 Is the modal dialog in then? If not, I can implement that was well.

It shouldn't be too hard to implement snackbars or modal dialogs as a service (similar to status message service right now) and implement them for usage in their individual pages. However, this would also cause status messages to be inconsistent in how it's being shown to the user.

**Comment by wkurniawan07** [comment]
> Is the modal dialog in then

@ChooJeremy modal dialog is already provided out of the box by `ng-bootstrap`. You only need to import the `NgbModal` service. The one that I showed up there is a very specific component I created for the purpose of error reporting.

> However, this would also cause status messages to be inconsistent in how it's being shown to the user.

You don't need to worry about consistency when the standard is not even put in place yet.

**Comment by amrut-prabhu** [comment]
Btw the error reporting modal needs to wrap text

![image](https://user-images.githubusercontent.com/29021586/54932221-66fa3980-4f55-11e9-8c11-fca4553b5a85.png)
