### ISSUE TITLE
1 steps missing while While starting the dev server with Intellij in Developement.md

### ISSUE THREAD

**Issue by AkshitOstwal** [TEAMMATES/teammates#9352]
- **Environment**: basic developement in Intellij , master branch

**Steps to reproduce**
N.A documentation error

**Expected behaviour**
adding configuration while running Google App Engine Standard Local Server for first time in Intellij
like : under Artifact to deploy select teammate.war(exploded)

**Actual behaviour**
no/partial configuration step given

**Additional info**

**Comment by AkshitOstwal** [comment]
and i have solved this issue please go through my first PR

**Comment by xpdavid** [comment]
The `.war` is automatically selected when configuring [`Frameworks detected: Google App Engine Standard, Angular CLI frameworks are detected.`](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-setup.md#project-setup-1)?

**Comment by AkshitOstwal** [comment]
no it is not automatically selected by default , i have recently done my first time dev server starting.
it was not selected by default and ,error was showing with popup " java.nullpoint.exception".

**Comment by xpdavid** [comment]
Do you have a screenshot for the selection? I cannot reproduce the issue as there is only one option here.

![image](https://user-images.githubusercontent.com/13977235/51473463-65768e80-1db7-11e9-8edb-1af143fabb24.png)

**Comment by AkshitOstwal** [comment]
you cant reproduce it in already configured App Engine Server
but you may reproduce it by:
goto `Run` -> `Edit Configuration` ->`+`
add new `Google App Engine Standard Local Server` configuration.

![image](https://user-images.githubusercontent.com/33562295/51475470-67852100-1da8-11e9-9ac7-fc6a8cdae4cd.png)
 you can see here that ` Artifact to deploy` is by default not selected , and an error messsage is showing below.
and when you run that it will show 
![image](https://user-images.githubusercontent.com/33562295/51475687-22152380-1da9-11e9-8abd-944227239cfd.png)
this popup also.

after clicking on continue anyway we get this error below
![image](https://user-images.githubusercontent.com/33562295/51475821-8fc14f80-1da9-11e9-88ee-2d0491d0d84d.png)

**Comment by xpdavid** [comment]
Let's see if other people get the same problem.

**Comment by AkshitOstwal** [comment]
hey @xpdavid  i would like to know how much time does it take to review the PR , and also i have made changes in my `master` branch and added my PR with it too ,so can i still solve other issues till this PR is merged ? (i think it might affect this PR to)
sorry if this is a naive question , i m new to open source.

**Comment by xpdavid** [comment]
The issue is in pending status as more information is need. Therefore, your PR is on hold.

> i have made changes in my master branch

You should not do that. Please read our contribution guide carefully.

> i still solve other issues

You are welcome to.
