### ISSUE TITLE
Fix path for userMapData.json in sort-usermap.js

### ISSUE THREAD

**Issue by RonakLakhotia** [TEAMMATES/teammates#9354]
Incorrect file path specified in sort-usermap.js due to recent migration.

- **Environment**: 
`master` branch at commit https://github.com/TEAMMATES/teammates/commit/f1246060d9d0d9de64a0ebb1ded01e3b8c151a04
**Steps to reproduce**
N/A. 

**Expected behaviour**
Correct file path specified should be `./src/web/data/userMapData.json`

**Actual behaviour**
Current file path is `./src/web/assets/data/userMapData.json`

**Additional info**

I can correct the the file path in the sort-usermap.js file

**Comment by wkurniawan07** [comment]
It's not exactly outdated, it's me being careless when updating the path. Please be welcomed to correct it.
