### ISSUE TITLE
Improve UI for loading indicators

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#9356]
Previously, in V6, moving to another page means refreshing the entire view and usually browsers give that indication (i.e. `Loading http://localhost:8080/page/somePage...`), and when the page is served, all data has been included in it. In the few places where AJAX is used, loading indicators/spinners/... are used and replaced with data after the data load finished.

In V7, since we are adopting SPA architecture, moving to another page still means refreshing the entire view however it will be almost-instantaneous (as compared to its V6 counterpart) and it will take some time for the new page to be populated with data. We need some kind of loading indicator for all places where this takes place, which will be much more as compared to V6.

**Comment by xpdavid** [comment]
Is it like this https://element.eleme.io/#/en-US/component/loading#full-screen-loading (just a idea, but we are not using elementUI)?

**Comment by wkurniawan07** [comment]
No, full screen loading is what fits (and could/should have been implemented in) V6.

**Comment by xpdavid** [comment]
Then https://element.eleme.io/#/en-US/component/loading#loading-inside-a-container might fit. We can write a directive (https://angular.io/guide/attribute-directives) in Angular to do this.

**Comment by tanhengyeow** [comment]
2 observations:
1. When one clicks the `Sessions` tab located on the navbar, there is a brief moment of showing a warning box before the whole page is shown. I suspect other places might face this issue, if the page needs to wait a little longer for the initial load (or even on slow networks) due to the API call.
2. The `Login` snippet on the top right of the page should also be improved, i.e. show a small loading bar before deciding to display “Login” or the logged-in username.

**Comment by damithc** [comment]
> 1. When one clicks the `Sessions` tab located on the navbar, there is a brief moment of showing a warning box before the whole page is shown. I suspect other places might face this issue, if the page needs to wait a little longer for the initial load (or even on slow networks) due to the API call.

I too noticed it in several places.

**Comment by wkurniawan07** [comment]
> 1. When one clicks the `Sessions` tab located on the navbar, there is a brief moment of showing a warning box before the whole page is shown.

This is precisely the second paragraph of the issue is about: "We need some kind of loading indicator for all places where [the new page is populated with data] takes place"

**Comment by monmanuela** [comment]
I'll work on this!

**Comment by monmanuela** [comment]
To find out which parts of TM are affected, I throttled my internet speed to slow 3G and test it out. Here are some observations (only for instructor pages so far):
- `/web/instructor/home`: Will show a big warning box, and then the page with no table of courses, then a few seconds later, the table of courses
![image](https://user-images.githubusercontent.com/35655790/53563527-44137a00-3b8f-11e9-8160-7e96ab9f732d.png)
![image](https://user-images.githubusercontent.com/35655790/53563454-06aeec80-3b8f-11e9-9f6c-7159ba1ca0e7.png)
![image](https://user-images.githubusercontent.com/35655790/53563522-3f4ec600-3b8f-11e9-9463-862e95260302.png)

- `/web/instructor/course`: Will show a big warning box, then "no records found", then only the full course table will appear
![image](https://user-images.githubusercontent.com/35655790/53563582-6a391a00-3b8f-11e9-8d0c-f3defbe0e698.png)
On Delete/Restore/Archive/Unarchive course: page freezes for ~2s before showing any response

- `/web/instructor/sessions`: Will show a big warning box, then "no active course", then the feedback sessions will appear
![image](https://user-images.githubusercontent.com/35655790/53563618-8d63c980-3b8f-11e9-8b03-bc1b6918d20d.png)
On Delete/Restore feedback session: page freezes for ~2s before showing any response

- `/web/instructor/search`
Upon searching for a student: page freezes for ~2s before showing any response
