### ISSUE TITLE
JSP Error while importing project

### ISSUE THREAD

**Issue by jgolatkar** [TEAMMATES/teammates#9359]
After importing project in Eclipse and following every step given in Setup guide, I am getting following errors:
_Can not find the tag library descriptor for "http://java.sun.com/jsp/jstl/core_ 
- **Windows 10**
- **JDK Version: 1.8**
- **Google Cloud SDK Version : 230.0.0**
- **Eclipse Version : Photon 2018-12 (4.10.0)**

**What I was trying to do / What I need help with**

![screenshot 24](https://user-images.githubusercontent.com/14250174/51576134-16962b00-1e83-11e9-9dc6-7751d248e183.png)

**Comment by wkurniawan07** [comment]
JSP/JSTL is no longer used. You can proceed as if none of the JSP problems exist.

**Comment by jgolatkar** [comment]
In that case, would be better to remove these lines if it's not gonna break anything  or a note regarding it in documentation?

**Comment by jgolatkar** [comment]
imported project in IntelliJ ..seems to be working fine so far.. thus , closing this issue

**Comment by sowmyadvn** [comment]
I am facing similar issue @jgolatkar,@wkurniawan07 but the errors are different. It is quite confusing that nothing is mentioned about it in the setup guide.  Please help. 
![image](https://user-images.githubusercontent.com/22230078/55263506-7f58a580-522e-11e9-8ed9-373c59e7f259.png)
Thanks.

**Comment by jgolatkar** [comment]
@sowmyadvn I changed my IDE to IntelliJ , which did not give the same errors on import.  What IDE are you using?
