### ISSUE TITLE
Remove removeIrrelevantVisibilityOptions in FeedbackQuestionAttributes

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9361]
The method is there because some visibility settings do not make sense under certain giver/recipient type (e.g. It does not make sense to talk about RECEIVER_TEAM_MEMBERS when recipientType === NONE). 

The removal of inapplicable visibility settings is done in frontend https://github.com/TEAMMATES/teammates/blob/090401c4a612475edfbbe85df2bcc055c9b01c64/src/web/services/visibility-state-machine.ts#L54.

I think we can remove the check in backend:

1. The frontend will always send valid settings to backend. Even if the users (which is an instructor) call the API directly, it won't hurt anyone but himself. 

2. Less code duplication.

3. The current check in backend is not as completed as frontend.

**Comment by Adoby7** [comment]
I think I can try this. However, is it an appropriate change? I think the backend API should be independent (i.e. doesn't know whether input is valid), so it needs to handle invalid input appropriately

**Comment by xpdavid** [comment]
> However, is it an appropriate change? I think the backend API should be independent (i.e. doesn't know whether input is valid), so it needs to handle invalid input appropriately

That's why the issue is labeled as `ToInvestigate`

**Comment by wkurniawan07** [comment]
Closing; this is part of back-end validation which cannot be skipped.
