### ISSUE TITLE
Replace responseMetaData with responseDetails in FeedbackResponseAttributes

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9362]
The `responseMetaData` in `FeedbackResponseAttributes` contains serialised JSON string of `FeedbackResponseDetails`. 

This storage implementation detail should be hidden in the `FeedbackResponsesDb` rather than being carried together with the DTO. That is, the `FeedbackResponseAttributes` returned by the DB should already contains the deserialised  `FeedbackResponseDetails` object.

Code example:
```java
public String responseMetaData;
// should be replace to
public FeedbackResponseDetails responseDetails;
```

Note that the `.json` (for testing) will also need to be updated.

**Comment by Adoby7** [comment]
I may try this issue, and is it related to #9363 ?

**Comment by xpdavid** [comment]
They are independent.

**Comment by Adoby7** [comment]
Could you assign this issue to me? Thanks!

**Comment by gildas15** [comment]
Please I am about to solve this issue
