### ISSUE TITLE
Replace questionMetaData with questionDetails in FeedbackQuestionAttributes

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9363]
The `questionMetaData` in `FeedbackQuestionAttributes` contains serialised JSON string of FeedbackQuestionDetails.

This storage implementation detail should be hidden in the `FeedbackQuestionsDb` rather than being carried together with the DTO. That is, the `FeedbackQuestionAttributes` returned by the DB should already contains the deserialised `FeedbackQuestionDetails` object.

Code example:
```
public String questionMetaData;
// should be replaced to
public FeedbackQuestionDetails questionDetails;
```

Note that the `.json` (for testing) will also need to be updated.

**Comment by jgolatkar** [comment]
@xpdavid yes, i am aware of it and i can guess it by looking at e.8 lol. but it will be good learning opportunity to know more about this project because i am looking forward participate in GSoC this year.
