### ISSUE TITLE
Tidy up UI design for some system messages

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#9366]
There are several messages that will be displayed to user regardless of page, depending on condition:

- Unsupported browser, disabled cookies (they are separate)
  <img width="1434" alt="screen shot 2019-01-25 at 1 18 50 am" src="https://user-images.githubusercontent.com/7261051/51695946-3f631f80-203f-11e9-99c3-08ee57856df3.png">
  They need to be displayed more properly (UI tidy up) and perhaps some rewording.

- Unknown/invalid user in any non-static page:
  <img width="1429" alt="screen shot 2019-01-25 at 1 21 08 am" src="https://user-images.githubusercontent.com/7261051/51696109-ac76b500-203f-11e9-90d5-cb9092060e3a.png">
  Which pales in comparison with the V6 counterpart:
  <img width="1175" alt="screen shot 2019-01-25 at 1 22 04 am" src="https://user-images.githubusercontent.com/7261051/51696110-ac76b500-203f-11e9-83be-3ad8ca7b51d9.png">
  The above screenshot, however, is only applicable to student in V6. V7 can take it one step further and make it applicable to all non-static pages.

**Comment by rrtheonlyone** [comment]
I can try and work on this issue!

**Comment by wkurniawan07** [comment]
This can be considered done for now.
