### ISSUE TITLE
Update script sort-usermap to remove duplicates in userMapData.json

### ISSUE THREAD

**Issue by monmanuela** [TEAMMATES/teammates#9369]
There is a duplicate institute in the `userMapData.json`

- **Environment**: `master` branch at commit e7db05

**Steps to reproduce**
NIL

**Expected behaviour**
There should not be any duplicate institute in the json file

**Actual behaviour**
There are 2 "Hasselt University" in the json file

**Additional info**

I'll update the sort-usermap script to remove duplicates too.

**Comment by Gaurav-Punjabi** [comment]
Can i solve this issue?
