### ISSUE TITLE
Standardize footer design

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#9373]
Currently V7's footer is still the placeholder created during the initial page skeleton design:
<img width="1262" alt="screen shot 2019-01-26 at 1 12 45 am" src="https://user-images.githubusercontent.com/7261051/51761248-959b9580-2107-11e9-9ef7-58aae61ff6bf.png">

However, V6 does not fare that much better since it is wildly varying from page to page:
- Static front pages
  <img width="1171" alt="screen shot 2019-01-26 at 1 08 42 am" src="https://user-images.githubusercontent.com/7261051/51761126-35a4ef00-2107-11e9-960a-672d30b38e8c.png">
- Data-serving pages
  <img width="1133" alt="screen shot 2019-01-26 at 1 09 13 am" src="https://user-images.githubusercontent.com/7261051/51761127-35a4ef00-2107-11e9-8947-e64c5d3a3246.png">
- Help pages
  <img width="1144" alt="screen shot 2019-01-26 at 1 09 25 am" src="https://user-images.githubusercontent.com/7261051/51761128-363d8580-2107-11e9-819f-8a708af63f3b.png">
- Error pages
  <img width="1169" alt="screen shot 2019-01-26 at 1 09 41 am" src="https://user-images.githubusercontent.com/7261051/51761129-363d8580-2107-11e9-87b6-17e9264fb6db.png">

Need to standardize the footer design. Let's use the design used in V6's data-serving pages, i.e.
- Application version
- `[for {institute name}]` (only when applicable)
- Send feedback

"Hosted on Google App Engine" does not value-add even if shown, so it can be dropped.

**Comment by monmanuela** [comment]
I'll work on the footer design
