### ISSUE TITLE
Replace Macker with ArchUnit

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#9386]
Currently, we're using [Macker](https://github.com/andrena/macker) to check for architectural integrity, e.g. which packages cannot import which packages. However, Macker as a project is dead and is very unlikely to support Java 11 and beyond.

We need a new tool with the same/similar capability that is still actively developed/maintained, e.g.:
- [CheckStyle's `ImportControl` rule](http://checkstyle.sourceforge.net/config_imports.html#ImportControl)
- [ArchUnit](https://github.com/TNG/ArchUnit)

**Comment by xpdavid** [comment]
Tried `CheckStyle's ImportControl rule` one year ago :P. Missing some critical features. May want to start with `ArchUnit` first.
