### ISSUE TITLE
Not able to run the front-end dev server

### ISSUE THREAD

**Issue by crownedlake** [TEAMMATES/teammates#9389]
- **Commit SHA:**  5de3876aa2b3a73853b45a4825871c7d3b89b03b
- **Operating System:** Ubuntu 18.04.1 LTS
- **JDK Version:** 1.8.0_191
- **Node.js Version:** v10.14.2
- **Google Cloud SDK Version:** 231.0.0
- **Eclipse / IntelliJ Version (if applicable):**
- **Firefox / Chrome Version (if applicable):**

**What I was trying to do / What I need help with**
I am setting up the local development environment and have followed the setting up document properly. While following the development.md document I am not able to start the dev-server front-end.

When trying to do `./gradlew generateTypes` I am shown this error:

* What went wrong:
Task 'generateTypes' not found in root project 'teammates'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Attempts to resolve the problem**
I tried doing everthing from scratch and checking all the dependencies a couple of time, but looks like I am missing some configuration files.

I tried doing `./gradlew buildDependents` but an error was again incurred.

I also tried going through previous questions around dev server but couldn't come to a solution.

Hope someone helps me soon.
Thanks in advance

**Comment by jacoblipech** [comment]
Hi @crownedlake did you face any other problem during the set up process? Also, can you do an `git pull` from the master to ensure that you are on the latest version of teammates.

**Comment by wkurniawan07** [comment]
@crownedlake, if your repo is the same as what I see here https://github.com/crownedlake/teammates (and it tallies with the commit SHA you wrote above), you need to sync it with the latest `master` branch. A lot has changed, and very particularly, the movement from JSP to Angular.

**Comment by crownedlake** [comment]
> Hi @crownedlake did you face any other problem during the set up process? Also, can you do an `git pull` from the master to ensure that you are on the latest version of teammates.

Hi @jacoblipech I did `git pull` before setting the environment.

**Comment by crownedlake** [comment]
> @crownedlake, if your repo is the same as what I see here https://github.com/crownedlake/teammates (and it tallies with the commit SHA you wrote above), you need to sync it with the latest `master` branch. A lot has changed, and very particularly, the movement from JSP to Angular.

Hi @wkurniawan07 I have not updated my forked repo but i did 'git pull' from teammates master repo in my local system before setting up, though I will try again by updating my forked repo and proceeding as per the document

**Comment by crownedlake** [comment]
## I have updated the repo and followed all the steps again, and happily the front end dev server looks fine ##
I have a new problem while starting the backend server. 
Getting the 404 not found error. Help needed.

**Comment by crownedlake** [comment]
So it looks like i have to start front end and back end dev server separately for the application to work fine. Closing this. Thanks for the help guys :smile:
