### ISSUE TITLE
Show default picture as profile photo for student who is yet to join

### ISSUE THREAD

**Issue by jacoblipech** [TEAMMATES/teammates#9405]
- **Environment**: local server at `V7.0.0`, `master` branch at commit `ede259e`.

**Steps to reproduce**
Go to student search page and search for a yet to join student.

**Expected behaviour**
Logically, a student with `yet to join` tag should have a default profile picture or not clickable profile picture. It should not be the error message as shown in the current behaviour below when clicked on `View Photo`.
![image](https://user-images.githubusercontent.com/28522090/52399341-e7282500-2af6-11e9-85eb-f05eeafe042e.png)

**Actual behaviour**
In `V6.0` a student profile with `yet to join` tag generates a default picture when clicked on the `View Photo`.
![image](https://user-images.githubusercontent.com/28522090/52399226-8f89b980-2af6-11e9-9321-f563802d123d.png)

**Additional info**
Consider showing a default picture when clicked on or disable the ability to click `View Photo` for `yet to join` students.

**Comment by rrtheonlyone** [comment]
I can take this issue.

**Comment by monmanuela** [comment]
I'll work on this!
