### ISSUE TITLE
Inconsistent button styling in Instructor courses page

### ISSUE THREAD

**Issue by monmanuela** [TEAMMATES/teammates#9411]
- **Environment**: Local server at `V7.0.0`, `master` branch at commit `3bc7b6a`

**Steps to reproduce**
Go to instructor courses page (`/web/instructor/courses`)

**Expected behaviour**
The buttons under `Action(s)` should be styled according to Bootstrap 4's styling, just like the other pages.
![image](https://user-images.githubusercontent.com/35655790/52517053-03030680-2c70-11e9-8679-c0f0dda2970c.png)
(Taken from the instructor sessions page)

**Actual behaviour**
The buttons don't have the expected Bootstrap styling.
![image](https://user-images.githubusercontent.com/35655790/52517076-41002a80-2c70-11e9-9c1f-98fa8bc76b00.png)
![image](https://user-images.githubusercontent.com/35655790/52581185-0ca18f80-2e65-11e9-807b-c48182d1e42c.png)

**Additional info**

Instead of using `<a type="button">`, consider using `<button>`

**Comment by wkurniawan07** [comment]
This page was migrated in a rather hurried manner, so there are more UI/UX issues here. Another one is the confirmation when permanently deleting courses, which (wrongly) uses traditional HTML alert rather than Bootstrap alert.

**Comment by monmanuela** [comment]
@wkurniawan07 I can open another issue for that. This seems suitable as a first timer issue, so I'd rather keep this one simple.
