### ISSUE TITLE
Link Recovery: Provide a method for students to request submissions links to be resent

### ISSUE THREAD

**Issue by junming403** [TEAMMATES/teammates#9412]
TEAMMATES emails a unique link to each user that they can use to submit responses or view results. In some cases users delete that email by accident or cannot find it again in their inbox. It would be good to provide a way for users to request TEAMMATES to resend the link.

Provide a method for students to request submissions links to be resent. The request submission page needs to be protected using something like Captcha to avoid abuse. There should be some mechanism to prevent over-use of this feature by a user too.
As TEAMMATES uses email address to identify users, the user can specify which email the links should be sent to. It is fine to send all relevant links to the provided email address.
Provide a way for the admin to regenerate new submission links for a student. This is for cases where the student shares the submission link with others by mistake.

**Comment by damithc** [comment]
@junming403 note that someone else attempted this issue sometime back. You may want to dig up that PR to see if anything can be reused.

**Comment by damithc** [comment]
Here it is #8490

**Comment by junming403** [comment]
Thank you prof, I will check.

**Comment by junming403** [comment]
User flow from last issue.

* Student goes to 'request for link' page.
* Student goes through 'I'm not a bot' verification.
* Student enters email address
* TEAMMATES sends all links (or we can limit to links related to past 1 month) to the given email address

I feel send all links to the email address might not be a good idea. First, user might not want to all the links. Secondly, it will spam user. Can we provide a secret link through email where users can see all their historical/ongoing feedback sessions? Thus they can selectively select links to be resent. 

Thus the user flow will be something like:
* Student goes to 'request for link' page.
* Student goes through 'I'm not a bot' verification.
* Student enters email address
* TEAMMATES send a link(contains a key, thus is private to the user) to the user given email.
* User opens the link and see the list of feedback sessions he participated as this email. 
* User selectively require to resend links(or maybe not, they can directly go to the feedback session)

**Comment by damithc** [comment]
Indeed your proposed approach is more elegant 👍. The downside: it requires more code, more work from the user, and more work on TEAMMATES servers (i.e., cost us more money).
Let's go with the simpler approach first? Note it is meant to send all links in one email, not one email per link.

**Comment by junming403** [comment]
I see, I will go with the simpler approach first. Thank you prof for the feedback.

**Comment by wkurniawan07** [comment]
> it requires more code, ~~more work from the user~~, and more work on TEAMMATES servers (i.e., cost us more money)

I have to disagree here. The work required to list the feedback sessions cannot add that much complication/server load if those feedback sessions have to be retrieved when sending the email containing all links in the first place.

But all other factors considered, the simpler approach should be the way to go for now.
