### ISSUE TITLE
Error in showing student detail of a yet to join student

### ISSUE THREAD

**Issue by monmanuela** [TEAMMATES/teammates#9416]
**Environment**: Local server at `V7.0.0`, `master` branch at commit `3bc7b6a`

**Steps to reproduce**
- Login as an instructor
- Search for a student who is yet to join
- Under `Action(s)`, click the `View` button

**Expected behaviour**
![image](https://user-images.githubusercontent.com/35655790/52522284-1e94fe00-2cbe-11e9-8fc3-73e3683da9aa.png)
In V6, the page shows a warning and the enrollment details of the student

**Actual behaviour**
![image](https://user-images.githubusercontent.com/35655790/52522290-3076a100-2cbe-11e9-9121-1ffa74894274.png)
Error in fetching the student detail

**Comment by damithc** [comment]
On another note, `null` is a programmer term that should not appear in a user-facing text.
