### ISSUE TITLE
Throw exception for negative integers of recommended length

### ISSUE THREAD

**Issue by RonakLakhotia** [TEAMMATES/teammates#9417]
- **Environment**: 
Local server at `V7.0.0`, `master` branch at commit 1edff91d7c04b49b50d270081617d3b2f69b919a

**Steps to reproduce**

1. Login as instructor
2. Navigate to edit feedback sessions page
3. Click on edit for an essay type question.
4. Enter a negative integer value for `Recommended Length` and click save.

**Expected behaviour**

* System notifies the user that negative integers are not permissible values for recommended length or negative integers are not allowed to be entered

**Actual behaviour**

* System shows a success message.

**Additional info**

<img width="1248" alt="screenshot 2019-02-09 at 11 29 19 pm" src="https://user-images.githubusercontent.com/28557842/52522690-a9c4c280-2cc3-11e9-8ad3-c16f4f0d214a.png">
<img width="1211" alt="screenshot 2019-02-09 at 11 29 33 pm" src="https://user-images.githubusercontent.com/28557842/52522693-b1846700-2cc3-11e9-8d6a-61d88553401d.png">

I can work on this

**Comment by RonakLakhotia** [comment]
Also as @damithc pointed out in #9416, the user-facing text displayed on entering a decimal number is not appropriate for the end users.

<img width="1271" alt="screenshot 2019-02-10 at 5 30 34 pm" src="https://user-images.githubusercontent.com/28557842/52532059-d9260e80-2d59-11e9-94d2-ba5b4fd080c1.png">

**Comment by wkurniawan07** [comment]
> the user-facing text displayed on entering a decimal number is not appropriate for the end users.

This is a known infrastructure problem, as described in #9421.

**Comment by gildas15** [comment]
please I want to work on this issue. can you assign it to me

**Comment by RonakLakhotia** [comment]
@gildas15 I have already started working on this issue, can you find another issue to work on?

**Comment by gildas15** [comment]
ok no problem
