### ISSUE TITLE
Separate user-facing and admin-facing error message in middleware layer

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#9421]
This complements #9346 in improving user-friendliness of error message.

In V6, all exceptions encountered in the servlet layer will result in redirect to preset error page.

In V7, due to the REST-ful architecture, redirections are not ideal anymore, and the error message is returned as the API response. However, in its initial design, the error message is identical to the error message thrown in the logic layer, which more often than not is developer-friendly but not user-friendly.

Need to implement a simple improvement to the API servlet where the error message for user is separate from the error message for admin.

**Comment by wkurniawan07** [comment]
Situation:
- If the error message is constructed individually by the action class via `new JsonResult(message, statusCode)` instead of the catch blocks inside `WebApiServlet`, that message will be returned to the front-end. This one we cannot argue.
- If the error message is constructed automatically by `WebApiServlet` based on the catch blocks, then we can modify the message depending on the suitability.

Here are the different scenarios:

- `404` or `405` from `ActionMappingException`
  - Chances of it happening in the front-end is very slim (close to 0% if there is no developer mistake), and the error message consists of no sensitive information. No harm to return the developer-facing message.
- `400` due to `InvalidHttpParameterException` or `InvalidHttpRequestBodyException`
  - Again, slim chance of this happening in the front-end. May need to obscure the error message to the user to prevent leakage of internal working (although arguably this is an open source project and everything is already "leaked"). _Return generic error message_.
- `403` due to `UnauthorizedAccessException`
  - Will be somewhat a security breach if user knows what access control s/he was missing (e.g. "Instructor privilege is required"), albeit s/he is unlikely to do anything about his/her own credentials. _Return generic unauthorized message_.
- `404` due to `EntityNotFoundException`
  - It is as useful to the user to know that the entity cannot be found as it is to the system admin. Can return the same developer-facing message.
- `504` due to `DeadlineExceededException` or `DatastoreTimeoutException`
  - User does not (or should not?) need to know details. _Return generic timeout message_, admin will get the severe log.
- `500` due to other `Throwable`s
  - User does not (or should not?) need to know details. _Return generic error message_, admin will get the severe log.

Texts in italics show the required changes. @xpdavid what do you think?

**Comment by xpdavid** [comment]
Looks good. One doubt.

> `400` due to `InvalidHttpParameterException` or `InvalidHttpRequestBodyException` -> Return generic error message.

There is an assumption here. The frontend will always do validation correctly and prevent request from sending if validation does not pass. In some cases where the frontend fails to do validation, user will get generic error which is not helpful (maybe in this case it is considered as a bug and the error report modal will pop-up?).
