### ISSUE TITLE
Links in the Instructor help page to other questions cards do not work

### ISSUE THREAD

**Issue by AyushChatto** [TEAMMATES/teammates#9423]
To recreate:- Open Instructor Help Page and try to click on any links that should lead to a section on the same page. These include the links to the question sections at the top, as well as the links in answers to other answers.

**Comment by AyushChatto** [comment]
The links on the top have been replaced by a side nav in pull request #9428 . The links within answers remain dead, however.

**Comment by aishaadambek** [comment]
Hello team!

I managed to reproduce the issue and I am now looking into it.

Hope I will have some results soon!
