### ISSUE TITLE
Instructor home page: fix sorting by creation date

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9433]
Instructor home page: the default sorting order (by creating date) does not seem to put the most recent course on top
![image](https://user-images.githubusercontent.com/1673303/52720535-c114f000-2fe2-11e9-9e90-55a0535a0356.png)

**Comment by jacoblipech** [comment]
I will look into this!

**Comment by damithc** [comment]
Another issue I noticed is that all panels seem to auto-expand. Only the latest 3 courses should auto-expand.

**Comment by Ayush517** [comment]
Is this issue fixed? The pull request seems to have passed all the checks but it's still not merged. Can I start working on this if it's not solved?

**Comment by wkurniawan07** [comment]
@Ayush517 just because a PR is not merged does not mean it's not being worked on, and just because a PR pass all checks does not mean it's ready to be merged.

**Comment by Ayush517** [comment]
Ok. I am new here, so I don't know much about these things. Sorry
