### ISSUE TITLE
GetTimeZonesDataActionTest: fix brittle asserts for time zone offsets

### ISSUE THREAD

**Issue by darrenwee** [TEAMMATES/teammates#9434]
The asserts that use New York and Sydney's time zones are brittle as these two time zones observe daylight savings, meaning the absolute offset from UTC is not consistent throughout the year.

https://github.com/TEAMMATES/teammates/blob/82f8d4299515ce20bbbdf07296519d5f60e12f92/src/test/java/teammates/test/cases/webapi/GetTimeZonesActionTest.java#L42-L49

Change these asserts to use time zones in the `Etc` group (e.g. `Etc/GMT-5`) instead as these offsets cannot change by definition.

New York's clocks will spring forward by one hour on 10 March 2019, while Sydney's clocks will spring backward by one hour on 7 April 2019. This test will begin failing then.

**Comment by mzhrbbs** [comment]
Is this issue still open, If yes can I work on it. I am a first timer in open source contributions. Thanks

**Comment by darrenwee** [comment]
@mzhrbbs hi! We are about to close #9455 to fix this issue, so it's a good idea to try the other first timer issues instead. Thank you for your interest!

https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers
