### ISSUE TITLE
Submit button on student sessions submission page not working

### ISSUE THREAD

**Issue by RonakLakhotia** [TEAMMATES/teammates#9439]
- **Environment**: 

* Local server at `* V7.0.0`, `master` branch at commit a018a980b8b31f08b167752a448c750347bbabdd

**Steps to reproduce**

1) Start a new submission for a new session as a student.

2) Fill out the questions.

3) Click on submit button

**Expected behaviour**

* Success message should be displayed

**Actual behaviour**

* Page does not show any message to the user

**Comment by xpdavid** [comment]
The underlying problem is that GSON fails to serialise child class of `FeedbackResponseDetails`.

![image](https://user-images.githubusercontent.com/13977235/52800239-4ae1bd80-30b6-11e9-9a92-1781554c5224.png)

Seems like an unspecific behaviour in GSON. We need implement `JsonDeserializer`.
