### ISSUE TITLE
Cannot load `Session with different question types`

### ISSUE THREAD

**Issue by Adoby7** [TEAMMATES/teammates#9458]
- **Environment**: 
* master at [05be9b6c9fa21be9966aeab76af7c51dff6de533](https://github.com/TEAMMATES/teammates/commit/05be9b6c9fa21be9966aeab76af7c51dff6de533)

**Steps to reproduce**
1. Login with an instructor account
2. Try to edit the session: `Session with different question types`

**Expected behaviour**
The information of session and each question should be correctly loaded into the page

**Actual behaviour**
Session information is not loaded, and cannot edit either.

Some questions are correctly loaded and editable, but some are not.

**Additional info**
Session information not loaded
![image](https://user-images.githubusercontent.com/25312978/52928603-9b3d7180-337b-11e9-8125-7364621556e2.png)

Questions that are correctly loaded
![image](https://user-images.githubusercontent.com/25312978/52928672-fec79f00-337b-11e9-83eb-00b44a767481.png)

Question that are not correctly loaded, and edit button missing
![image](https://user-images.githubusercontent.com/25312978/52928692-1d2d9a80-337c-11e9-81d6-33520d723d9d.png)

**Comment by xpdavid** [comment]
We have not completed the phase 2 migration yet (#9382). So the page with different types of questions will break.
