### ISSUE TITLE
Hamburger menu does not collapse

### ISSUE THREAD

**Issue by amrut-prabhu** [TEAMMATES/teammates#9459]
- **Environment**:
`master` branch at commit 05be9b6c9. 

**Steps to reproduce**
1. Go to TEAMMATES home page in a small or medium size window 
2. Click on hamburger menu 
3. Click any of the options in the menu

**Expected behaviour**
The hamburger menu collapses after clicking a hyperlink.

**Actual behaviour**
The hamburger menu stays open and obstructs the content.

<img src="https://user-images.githubusercontent.com/29021586/52932977-ac42ae80-338c-11e9-8109-5aac2c7021bf.gif" width="500">

**Additional information**
Applicable to student, instructor and admin pages as well

**Comment by harshagrwl** [comment]
Hi @amrut-prabhu 
I would like to work on this issue.

**Comment by amrut-prabhu** [comment]
Hi @harshagrwl, please go ahead. Let us know if you run into any problems :)

**Comment by harshagrwl** [comment]
Hello @amrut-prabhu 
I am not able to start the dev server on my local machine. I am encountering a npm error.

![screenshot from 2019-02-25 19-51-51](https://user-images.githubusercontent.com/43218240/53343692-f8669380-3936-11e9-9e4a-218fe652e84a.png)

**Comment by amrut-prabhu** [comment]
@harshagrwl Have you followed the [setting up guide](https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md#step-2-install-necessary-tools-and-languages) completely? In particular, the part about `If you want to develop front-end, you need to install the following:`

If not, please do so and install the necessary dependencies
