### ISSUE TITLE
Preview as Student and Preview as Instructor buttons not functional

### ISSUE THREAD

**Issue by RonakLakhotia** [TEAMMATES/teammates#9460]
- **Environment**: 

* master at 05be9b6c9fa21be9966aeab76af7c51dff6de533

**Steps to reproduce**
* Navigate to instructor sessions edit page.
* Scroll to the bottom of the page and click on "Preview as Student" or "Preview as Instructor"

**Expected behaviour**

* Should display the session as would be visible to a student/instructor

**Actual behaviour**

* No message/page is displayed

![image](https://user-images.githubusercontent.com/28557842/52937527-4b21d780-339a-11e9-98f8-46328de35d3c.png)

**Comment by xpdavid** [comment]
Not implemented. Will do along with the API consolidation.

**Comment by xpdavid** [comment]
Closed as it is fixed in #9507 and #9500
