### ISSUE TITLE
Focus state of nav bar item results in bad readability 

### ISSUE THREAD

**Issue by amrut-prabhu** [TEAMMATES/teammates#9461]
- **Environment**: 
local branch with base at `master` branch commit a018a98

**Steps to reproduce**
1. Open a drop down menu in the nav bar
2. Click and drag one of the items

**Expected behaviour**
The selected item should still be visible

**Actual behaviour**
The contrast between the text colour and resultant background colour makes the text unreadable

![20190218_18h40_55](https://user-images.githubusercontent.com/29021586/52945667-3ac72800-33ad-11e9-9a44-64272e06e788.gif)

**Additional info**

Add a css style for `dropdown-item:focus` state in `page-component.scss`

**Comment by wkurniawan07** [comment]
@amrut-prabhu since you know the solution, you should just take this issue.
