### ISSUE TITLE
Add validation check for "Not Sure" criteria in Contribution question

### ISSUE THREAD

**Issue by RonakLakhotia** [TEAMMATES/teammates#9467]
- **Environment**: 

* master at 0640c17080d1abe2cf887dc06f4242ea0fa625ea

**Steps to reproduce**

* Create a new session as an instructor/navigate to instructor session edit page and edit an instructor.
* Uncheck the option "Allow response giver to select 'Not Sure' as the answer" in team contribution question and save.
* Log in as student and start submission of a session.
* You can select "Not Sure" as an option in team contribution question.

**Expected behaviour**

* An error message displayed or the option should not be available to be selected/

**Actual behaviour**

* Students can select "Not sure"

**Additional info**

<img width="1258" alt="screenshot 2019-02-19 at 5 05 58 pm" src="https://user-images.githubusercontent.com/28557842/53003198-66a7e380-3469-11e9-91ed-7c1d4738ce48.png">

<img width="1279" alt="screenshot 2019-02-19 at 5 05 17 pm" src="https://user-images.githubusercontent.com/28557842/53003212-6e678800-3469-11e9-921b-0054d6c04048.png">

**Comment by wkurniawan07** [comment]
Can this choice be persisted to the back end?

**Comment by RonakLakhotia** [comment]
Not entirely sure, will have look into the code

**Comment by wkurniawan07** [comment]
If back-end rejects the value, then it works as expected and it's just a minor UI inconvenience.

**Comment by RonakLakhotia** [comment]
Will look into this.

**Comment by xpdavid** [comment]
It seems like backend dose not have such verification. Not sure about the backend in V6 @RonakLakhotia Please check.

**Comment by RonakLakhotia** [comment]
The issue is only valid for v7. Backend in v6 rejects the value and the UI is in sync with the expected behaviour.

**Comment by xpdavid** [comment]
> Backend in v6 rejects the value

Are you sure about this? Where do you find the verification logic? You can modify the HTML code to submit not sure answer even the option is not there in V6.

**Comment by RonakLakhotia** [comment]
> You can modify the HTML code to submit not sure answer even the option is not there in V6

Did not take this into consideration.

**Comment by RonakLakhotia** [comment]
There does not seem to be any verification logic in v6, you are right .
