### ISSUE TITLE
Questions not showing in "Add New Question" for new session

### ISSUE THREAD

**Issue by Ayush517** [TEAMMATES/teammates#9470]
- **Commit SHA: 8c5637bc84b433f86715d3ef5632505a44549dcc** 
- **Operating System:MacOS Mojave Version 10.14.3**
- **JDK Version:1.8.0_191-b12**
- **Node.js Version:v10.15.1**
- **Google Cloud SDK Version:234.0.0**
- **IntelliJ Version:Build #IU-183.5429.30**
- **Chrome Version:72.0.3626.109**

**I was trying to replicate issue #8465 and see the files associated with the issue. While creating a new session through my instructor, I tried adding new question related to distribute points (among recipients) but was unable to do so.**

<img width="1680" alt="screenshot 2019-02-19 at 5 59 52 pm" src="https://user-images.githubusercontent.com/31190928/53015248-99a1a580-3470-11e9-8b74-97cae8740e0e.png">

**Attempts to resolve the problem : Tried resetting the entire cloned repo as well as all the libraries and installations associated.**

**Comment by wkurniawan07** [comment]
This is a known issue related to #9382. You need not be alarmed.

**Comment by Ayush517** [comment]
So, how do I replicate the issue on my laptop? Without replication, I won't be able to do anything.

**Comment by wkurniawan07** [comment]
This is not something that needs resolution (or rather, the resolution can only be done by someone who is already very, very familiar with the system).

**Comment by Ayush517** [comment]
So, how should I proceed for issue #8465 now?

**Comment by wkurniawan07** [comment]
I have put that issue on hold. You can find something else to work on.

**Comment by Ayush517** [comment]
okay :)
