### ISSUE TITLE
Add front-end tests for all Angular components in v7

### ISSUE THREAD

**Issue by AyushChatto** [TEAMMATES/teammates#9480]
To add test cases (testing the business logic with usual testing and HTML generation with snapshot testing) on all frontend `spec.ts` files

**Comment by MrJDavidT** [comment]
Hello,

Is this issue still available? I would like to try it.

**Comment by madanalogy** [comment]
> Hello,
> 
> Is this issue still available? I would like to try it.

Yeap, just find a `spec.ts` file without test cases and add tests. You can refer to other frontend test files that are already populated with tests

**Comment by madanalogy** [comment]
Issue is more clearly outlined in #10920
