### ISSUE TITLE
Side nav in instructor help page is unresponsive

### ISSUE THREAD

**Issue by monmanuela** [TEAMMATES/teammates#9490]
- **Environment**: `V7`, `master` branch at commit `b10ae83`

**Steps to reproduce**
1. Go to the instructor help page
2. Resize your browser window, or open the dev console
3. Side nav is half covered or is not be able to be seen at all

**Expected behaviour**
The rest of the page is responsive, so the side nav should be responsive too

**Actual behaviour**
Upon opening chrome dev console, side nav is half covered:
![image](https://user-images.githubusercontent.com/35655790/53290399-50d64d80-37de-11e9-9bc9-da49b9a8b657.png)

Upon resizing the browser window, side nav can't be seen:
![image](https://user-images.githubusercontent.com/35655790/53290509-d1e21480-37df-11e9-829f-102fc5da3329.png)

**Comment by AigerimAibassova** [comment]
Hi, can I take this one?
