### ISSUE TITLE
Convert FieldValidator to a utility class

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#9493]
The `FieldValidator` class right now is implemented as a standard initialize-able class that can supposedly hold data. However, it is used as a utility class and contains no internal data that is being mutated.

Therefore it should be designed as a utility class, i.e. all methods are static, the class is `final`, and the constructor is `private`.

**Comment by VinodKumarWagh** [comment]
@wkurniawan07 may I work on this?

**Comment by amrut-prabhu** [comment]
Hi @VinodKumarWagh , please go ahead. Let us know if you face any problems 

And remember to follow the [development workflow](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#fixing-issues) :)

**Comment by VinodKumarWagh** [comment]
@amrut-prabhu  the java file has no constructor in it.

**Comment by amrut-prabhu** [comment]
@VinodKumarWagh Every Java class has a [constructor](https://qr.ae/TUfVXV).
So, you can think about what changes need to be made to make it a utility class (see [this](https://stackoverflow.com/questions/25223553/how-can-i-create-an-utility-class) and [this](https://qr.ae/TUfV7I)).

**Comment by VinodKumarWagh** [comment]
@amrut-prabhu  I have updated the file according to that file(TimeHelper.java) only!

**Comment by VinodKumarWagh** [comment]
@amrut-prabhu I am creating a new pull request for this issue.
