### ISSUE TITLE
Instructor: Add cancel button when editing an existing session.

### ISSUE THREAD

**Issue by RonakLakhotia** [TEAMMATES/teammates#9495]
- **Environment**

Branch: master, commit 83a956eb0ff049e709de078ad2af4da8178366be

**Description of feature/enhancement**
Currently, when editing the session the workflow is as follows.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/28557842/53298563-d43d8080-386a-11e9-88f2-a4d2a7afda73.gif)

It may be more useful to add a cancel/discard changes button instead of having a "save" and "save changes" button.

**Comment by martinoamigo** [comment]
@RonakLakhotia May I work on this? I noticed this issue as well

**Comment by RonakLakhotia** [comment]
Sure go ahead! Let us know if you need any help.

**Comment by RonakLakhotia** [comment]
@martinoamigo also make not similar workflow in the instructor course edit page, while editing course details.

**Comment by martinoamigo** [comment]
@RonakLakhotia unfortunately I didn't get around to the instructor course edit page, but the session edit is ready for review

**Comment by nodermatt** [comment]
I saw that there had been a lot of discussion in the PR for this issue but no more mentioning of the cancel button for the instructor course edit page. Should I submit a separate PR for that work?

**Comment by madanalogy** [comment]
> I saw that there had been a lot of discussion in the PR for this issue but no more mentioning of the cancel button for the instructor course edit page. Should I submit a separate PR for that work?

This issue is for the editing of a session. Editing a course already has a cancel button. That being said, the PR submitted for this issue appears to have gone stale, you're welcome to continue where the previous author left off.
