### ISSUE TITLE
Hey! I am looking to contribute to TEAMMATES as part of GSOC'19. Having gone through the Wiki containing the list of current ideas, a particular project titled "Message of the Day" piqued  my interest. I have gone through the contribution steps and guidelines, and would love to get involved with this particular project. Where can I start from? Thanks! :)

### ISSUE THREAD

**Issue by schezfaz** [TEAMMATES/teammates#9505]
- [Help requests](?template=help-request.md)

**Comment by amrut-prabhu** [comment]
Hi @schezfaz, thanks for your interest in TEAMMATES!
You can start by fixing a [first timer issue](https://github.com/teammates/teammates/issues?q=is%3Aissue+is%3Aopen+label%3Ad.FirstTimers) to get used to the workflow (though there don't seem to be many available right now :/) .
You can then take up some small issues to get used to navigating around the codebase and slowly work your way up :)
