### ISSUE TITLE
Instructor: Course Details: Improve UI

### ISSUE THREAD

**Issue by tanhengyeow** [TEAMMATES/teammates#9508]
**Environment**:
`master` branch

**Steps to reproduce**
1. Go to `web/instructor/courses/details?courseid=<valid course id with students>`
2. Observe screenshot posted:
![image](https://user-images.githubusercontent.com/25320782/53423779-f414a600-3a1c-11e9-8913-174bfc1c6233.png)

**Things to fix**:
1. Remove the extra `Students` div
2. Align the `student-list-component` with the card body.

**Comment by FredAmartey** [comment]
Hi, id like to jump on this. Just started getting into open source and contributions. Can you point me in the direction of the file or files I should be looking at?

**Comment by tanhengyeow** [comment]
@FredAmartey You can refer to our [docs](https://github.com/TEAMMATES/teammates/blob/master/docs/CONTRIBUTING.md) to get started with the project, if you haven't done so.

Finding the related files to change is part of the learning process, especially when the scope involved here is relatively small.

**Comment by ritisha2000** [comment]
Hello, if it is still possible, may I work on this issue?

**Comment by tanhengyeow** [comment]
@ritisha2000 Please do so, refer to the comment above to get started.

**Comment by ritisha2000** [comment]
I have started work on this issue but before I make changes to the file I wanted to clarify if I understood the issue. I have understood that the whole student section (the blue header and the list of the students) needs to be deleted. But I am unsure as to what needs to be aligned.

**Comment by tanhengyeow** [comment]
Hi @ritisha2000 

For example, in the picture, with reference to the card body, there is some padding towards the left of the table. The padding shouldn't exist.
![image](https://user-images.githubusercontent.com/25320782/54847780-472b0180-4d1a-11e9-8525-56995759534b.png)
