### ISSUE TITLE
Student list component: Change button style to match other tables

### ISSUE THREAD

**Issue by tanhengyeow** [TEAMMATES/teammates#9509]
**Environment**: 
`master` branch

**Description of feature/enhancement**
The student list component's buttons look like this currently:
![image](https://user-images.githubusercontent.com/25320782/53424731-b022a080-3a1e-11e9-9458-2350b56c0001.png)

It should match the button style in places like:
1. Instructor home page:
![image](https://user-images.githubusercontent.com/25320782/53424678-95502c00-3a1e-11e9-8cb2-eb9075cfff3b.png)

2. Instructor course page:
![image](https://user-images.githubusercontent.com/25320782/53424692-9e40fd80-3a1e-11e9-832c-e9f5db659e48.png)

**Justification**
This promotes consistency and it doesn't make sense to have different button styles for the student list component.

**Comment by monmanuela** [comment]
Looking at the screenshots, I think it's a good idea to standardize the table headers as well (background color, font color), for the same reason we want to standardize the buttons :)

**Comment by tanhengyeow** [comment]
Valid point, but `/web/instructor/students` is currently using it this way (refer below), so the standard blue present in other table headers wouldn't fit too well here :)
![image](https://user-images.githubusercontent.com/25320782/53425796-ad28af80-3a20-11e9-9402-446eb2532470.png)

**Comment by AigerimAibassova** [comment]
Hi! Can I take this issue?

**Comment by monmanuela** [comment]
@AigerimAibassova Go ahead! Refer to the [docs](https://github.com/TEAMMATES/teammates/blob/master/docs/CONTRIBUTING.md) and feel free to ask questions :)
