### ISSUE TITLE
Instructor: Course Page/Student List Component: Implement sorting for table headers

### ISSUE THREAD

**Issue by tanhengyeow** [TEAMMATES/teammates#9510]
**Environment**: 
`master` branch

**Description of feature/enhancement**
Allow instructors to sort entries in tables located in the instructor course page and also the student list component.

**Comment by pbrahmbhatt3** [comment]
can I work on it?

**Comment by tanhengyeow** [comment]
@pbrahmbhatt3 Hi! Thanks for your interest in this issue. For first timers, we would advice working on `d.firstTimers` issues. However, if you are confident on solving this issue, please go ahead.

**Comment by martinoamigo** [comment]
@pbrahmbhatt3 I could take this on if you'd like!

**Comment by pbrahmbhatt3** [comment]
I am working on it currently. Thank you for asking though :) @martinoamigo

**Comment by pbrahmbhatt3** [comment]
@tanhengyeow How can I login in to the application? Locally I would need to log in as an instructor.

**Comment by pbrahmbhatt3** [comment]
@tanhengyeow  Can you tell me how do we want the student list component to be sorted? Sorted by what? Thank you. :)

**Comment by tanhengyeow** [comment]
Hi @pbrahmbhatt3 

In v6 of our application, we have sorting for `Section`, `Team`, `Student Name`, `Status` and `Email`.  Basically, everything that we see in the `student-list-component` where we have the sorting headers:
![image](https://user-images.githubusercontent.com/25320782/55301789-e1085200-5470-11e9-9a2e-8267d580ce2c.png)


Those headers are there right now but they don't have any sorting functionality. It would nice to have the logic implemented.

**Comment by erjillsison** [comment]
Hi, is this still being worked on? May I work on this?
