### ISSUE TITLE
Instructor: Course Edit Page: Show better success message

### ISSUE THREAD

**Issue by tanhengyeow** [TEAMMATES/teammates#9514]
**Environment**: 
`master` branch

**Steps to reproduce:**
1. Go to `/web/instructor/courses/edit?courseid=<valid course id>`
2. Edit the course details and click `Save changes`
3. Observe success message:
![image](https://user-images.githubusercontent.com/25320782/53538990-bca41780-3b4a-11e9-8152-dd5bf9b5118c.png)

**Ideal result:**
The success message can be improved by showing a simple message instead, similar to what we have in v6:
![image](https://user-images.githubusercontent.com/25320782/53539018-dba2a980-3b4a-11e9-9323-2774b3ccc537.png)

**Comment by Nitin96Bisht** [comment]
@tanhengyeow I would like to work on this.

**Comment by tanhengyeow** [comment]
@Nitin96Bisht Please go ahead :) You can refer to our [docs](https://github.com/TEAMMATES/teammates/blob/master/docs/CONTRIBUTING.md) to get started with the project, if you haven't done so.

**Comment by recepinanc** [comment]
Hey @tanhengyeow! I also would like to work on this. Looks like this issue is not assigned to anybody, but @Nitin96Bisht also indicated interest on this issue. Is that OK for me to start working on this?

**Comment by monmanuela** [comment]
Hi @recepinanc, there's already an open PR for this, so do look into other `d.FirstTimers` issue :) If the last person who indicated interest in the issue has been quite inactive for some time, feel free to work on the issue and open a PR.

**Comment by recepinanc** [comment]
Hi @monmanuela, thank you for your response, I will keep that in mind. Cheers!

**Comment by monmanuela** [comment]
@recepinanc Feel free to take this issue if you are still interested :) The previous PR is closed.

**Comment by dRadest** [comment]
I'm interested in working on this, if it's open

**Comment by tanhengyeow** [comment]
@dRadest As long as there are no active PRs ongoing, feel free to take it up :)
