### ISSUE TITLE
Instructor Course: Fix restoring a deleted course functionality

### ISSUE THREAD

**Issue by monmanuela** [TEAMMATES/teammates#9516]
- **Environment**: V7, master branch at `31bd48c`

**Steps to reproduce**
Go to `/web/instructor/courses`
Delete a course (it will move to the Deleted Courses table)
Click the `Restore` button to restore that course (not `Restore All`)
Failure alert saying "Resource with URI /webapi/instructor/courses/restore is not found." will be shown

**Expected behaviour**
The course should be restored

**Actual behaviour**
![image](https://user-images.githubusercontent.com/35655790/53561721-93a37700-3b8a-11e9-9afb-521ad3af0a7e.png)

**Comment by wkurniawan07** [comment]
Looks like a victim of out-of-sync between the API consolidation and the front-end. @monmanuela can send in a quick fix?

**Comment by monmanuela** [comment]
@wkurniawan07 I'll work on it
