### ISSUE TITLE
Document API layer design principles/policies

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#9517]
In our [design document](https://github.com/TEAMMATES/teammates/blob/master/docs/design.md), we have documented policies for logic layer and storage layer implementations (they are somewhat outdated now, but this is not the issue).

The API layer (`teammates.ui.webapi.*`) has sufficiently matured and has gone through a handful of design changes/improvements. We shall document these principles and policies for future developers.

Some of the stuffs that are worth mentioning (not exhaustive):
- Prefer multiple REST calls over single RPC calls
- Authentication and security, including information hiding and usage of `Intent` to route different users to different access control check and even execution path
- How the front-end "borrows" the typing information from the API layer
- Complete separation of concern between access control check and execution
- POST/PUT requests use body instead of parameters to contain the request details
- Timestamp information is communicated via milliseconds from epoch and timezone ID (if required)

**Comment by xpdavid** [comment]
Draft:

#### Policies

RESTFul API Endpoints:
- Design endpoints for resources. For example, `FeedbackSession` is a resource. The corresponding endpoint is `/session`. We use `GET`, `POST`, `PUT`, `DELETE` HTTP methods to get, create, update and delete the resource respectively. 
    - The endpoint information is automatically synced to `api-endpoints.ts` in the frontend.
- Prefer multiple REST calls over single RPC (Remote Procedure Call) calls.
- Create data transfer objects (DTO) in `output` and `request` package for RESTFul API communication.
    - The URL parameters are used to identify a specific resource for an endpoint. The actually attributes of the resource reside inside the body of the HTTP request/response.
    - The schemas of those DTOs are automatically synced to `api-output.ts` and `api-request.ts` in the frontend.
- Preprocess data sent to/sent by the frontend to hide complications.
    - For example, timestamp is passed to the frontend as UNIX epoch milliseconds while it is represented as `Instant` in the backend.
    - Some constructors in the `output` package contain logic to hide 'hacks' in the backend.
    - Some getter/setter in the `request` package contain logic to cater the conventions in the backend.
- Put access control related logic in `checkSpecificAccessControl()` and leave `execute()` for action execution logic.
- In the case that an endpoint is served for multiple purposes, use `Intent` to distinguish the intent for the request. For example, instructors can access `/session` with intent `INSTRUCTOR_SUBMISSION` or `FULL_DETAIL`.
- In the case that some fields should be hidden in the API response, create methods in the DTOs created in the `output` package to hide them.
