### ISSUE TITLE
Unable to serve profile picture

### ISSUE THREAD

**Issue by RonakLakhotia** [TEAMMATES/teammates#9519]
- **Environment**
V7 at master , e5e97c4ddb5917dd065e363cd07cbeb36ca1dfc7

**Steps to reproduce**

1. Go to the student profile page.
2. Upload a profile picture.

**Expected behavior**

* Picture is uploaded successfully.

**Actual behaviour**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/28557842/53575502-a464e480-3bac-11e9-8d28-07ba7be74934.gif)

**Comment by wkurniawan07** [comment]
Regression from #9502. Picture is uploaded; it's the serving part that's problematic.
