### ISSUE TITLE
Instructor: Course Edit Details: Unable to edit/add instructor

### ISSUE THREAD

**Issue by tanhengyeow** [TEAMMATES/teammates#9520]
**Environment**:
`master` branch

**Steps to reproduce**

Go to `/web/instructor/courses/edit?courseid=<valid course id>`

1. First bug:
- Edit an instructor and click `Save changes`. Nothing happens. 

2. Second bug:
- Click `Add New Instructor`, fill in some details and click `Add Instructor`
- Following error faced:
![image](https://user-images.githubusercontent.com/25320782/53581200-15f66000-3bb8-11e9-9d9c-9293f8ba3c1a.png)

**Comment by wkurniawan07** [comment]
@tanhengyeow I've located the regressing code change. Two-liner change. Just do it.

**Comment by Gomaa** [comment]
I followed teammates dev documentation, and my work space is just ready for work. Is it possible to get assigned to this issue?

**Comment by monmanuela** [comment]
Hi @Gomaa , there's already an [open PR](https://github.com/TEAMMATES/teammates/pull/9524) to fix this issue. Feel free to look at other [first timer issues](https://github.com/TEAMMATES/teammates/issues?q=is%3Aissue+is%3Aopen+label%3Ad.FirstTimers) to work on :)
