### ISSUE TITLE
Instructor Course Enroll page: Improve UI for enrollment table

### ISSUE THREAD

**Issue by monmanuela** [TEAMMATES/teammates#9530]
- **Environment**: `master` branch

**Steps to reproduce**
1. Go to `/web/instructor/courses`
2. Create a new course if there isn't any
3. Click the `Enroll` button
4. Put in some details of students to be enrolled (can copy paste from the example under `More info`)
5. `Enrollment Results` table will appear
![image](https://user-images.githubusercontent.com/35655790/53676671-91ebc780-3ce0-11e9-87b3-0891b0668428.png)

**Expected behaviour**
- If the header background color is blue or teal, font color should be white for better readability
- If the header background color is grey, font color should remain black
- The table entries should not be bold

The styling should look like this:
![image](https://user-images.githubusercontent.com/35655790/53676946-05430880-3ce4-11e9-8904-0ded821458f5.png)

**Comment by pbrahmbhatt3** [comment]
can I work on this?

**Comment by monmanuela** [comment]
Hi @pbrahmbhatt3 , go ahead! Do refer to the [docs](https://github.com/TEAMMATES/teammates/blob/master/docs/CONTRIBUTING.md) and ask if you have any questions 😄

**Comment by Aarabhi2017** [comment]
Is this still being worked on?

**Comment by monmanuela** [comment]
@Aarabhi2017 Since the previous person seems inactive, feel free to work on this :)

**Comment by amrut-prabhu** [comment]
@monmanuela In the scope of this issue's title, the enrollment table `Existing Students` can also be improved. 
- It flickers when clicked when the table is empty.
- I feel that the `No existing students in course.` message can be presented in a better way.
- If there are existing students, the table should not have empty rows at the bottom (since they can't be edited anyways).
- If student(s) are enrolled and the `Existing Students` has been opened, a page refresh is required to update it.
- Clicking the `Enroll Students` button doesn't provide any feedback to the user since the success/error message is shown at the top of the page (which may be missed unless you scroll to the top of the page)
- The error message itself can be updated to be more user friendly.

I think we need to create new issues for these, but do you think some of these can be added in this firstTimers issue?

**Comment by monmanuela** [comment]
@amrut-prabhu Thanks for pointing these out!

> * `Existing Students` card flickers when clicked if the table is empty.
> * I feel that the `No existing students in course.` message can be presented in a better way.
> * If there are existing students, the table should not have empty rows at the bottom (since they can't be edited anyways).
> * If student(s) are enrolled and the `Existing Students` has been opened, a page refresh is required to update it.

The issues mentioned above are valid concerns related to UI/UX. I checked the code though, it doesn't seem to have an easy fix. It needs more research into `Handsontable`, so I don't see it as a first timer issue. @tanhengyeow, git blame says that you worked on it last time, so maybe you can advise further?

> * Clicking the `Enroll Students` button doesn't provide any feedback to the user since the success/error message is shown at the top of the page (which may be missed unless you scroll to the top of the page)
> * The error message itself can be updated to be more user friendly.

This is part of #9346 and I'm working on it :)

**Comment by tanhengyeow** [comment]
Hi @amrut-prabhu 

Thanks for pointing out your observations! They are valid and indeed they require some thoughts before we proceed on fixing them. Some of these issues have been pointed out in some other issues but it's good we reiterate them and keep track of them here:

We can tackle the easy ones first such as this below:
> I feel that the No existing students in course. message can be presented in a better way.

Any better suggestions?

> If student(s) are enrolled and the Existing Students has been opened, a page refresh is required to update it.

Refer to https://github.com/TEAMMATES/teammates/pull/9340#issuecomment-455873486 

> If there are existing students, the table should not have empty rows at the bottom (since they can't be edited anyways).

Reason for this is that Handsontable (HOT) requires a fixed number of rows to display. If there are only 1-3 rows (assuming there are only 1-3 students), it looks kinda odd that the HOT's height is only X pixels, compared to the enroll HOT presented directly below it.

> Existing Students card flickers when clicked if the table is empty.

Valid point that I've not really looked much into. PRs/suggestions welcome :)

> Clicking the Enroll Students button doesn't provide any feedback to the user since the success/error message is shown at the top of the page (which may be missed unless you scroll to the top of the page)
The error message itself can be updated to be more user friendly.

For @monmanuela, you can kind of leave this section to the later part as there are plans to refactor the backend API to return enroll messages in a better way, refer #8985. Showing the current chunk of error messages in a snackbar isn't that user friendly either.

**Comment by amrut-prabhu** [comment]
@monmanuela @tanhengyeow Thanks for your replies.

> I feel that the No existing students in course. message can be presented in a better way.
Any better suggestions?

I'm no UI expert by any means, but from my experience as an end user, how about we display the message in the expanded card (like the 2nd one below)?

![2019-03-24_22h03_36](https://user-images.githubusercontent.com/29021586/54880696-9ee47c80-4e82-11e9-8082-c9bbec6010d5.jpg)

**Comment by pbrahmbhatt3** [comment]
Hi @monmanuela 

I was trying to run the TEAMMATES on my local machine.
When I try npm run start, It builds successfully but it never stops loading(I cannot see any data). I have followed the steps given in the document. Any idea on where I might be going wrong?

**Comment by monmanuela** [comment]
Hi @pbrahmbhatt3, seems that you're facing the same issue as [this](https://github.com/TEAMMATES/teammates/issues/9541#issuecomment-470061472). Have you run the backend (`./gradlew appengineStart`)? This is because `npm run start` only runs the frontend :)

**Comment by pbrahmbhatt3** [comment]
It works! Is this issue still open? If yes I would like to work on it.

**Comment by monmanuela** [comment]
@pbrahmbhatt3 Yes, go ahead. This issue only requires small changes in `instructor-course-enroll-page` so it shouldn't take very long :)
