### ISSUE TITLE
Instructor: Course Edit Page: Blinking tooltip upon hover

### ISSUE THREAD

**Issue by tanhengyeow** [TEAMMATES/teammates#9531]
**Environment**: 
`master` branch

**Steps to reproduce**
1. Go to `/web/instructor/courses/edit?courseid=<valid course id>`
2. Click `Edit` for an instructor 
3. Hover your cursor over the `Delete button`

**Expected behaviour**
The tooltip is shown normally.

**Actual behaviour**
The tooltip blinks continuously.

**Comment by martinoamigo** [comment]
I wasn't able to reproduce this behavior on Chrome or Safari. Am I looking at the right spot?

![Screen Shot 2019-03-28 at 7 40 39 PM](https://user-images.githubusercontent.com/25358466/55199768-84b3e280-5191-11e9-949e-2c2b623afd26.png)

**Comment by tanhengyeow** [comment]
Hi @martinoamigo 

Thanks for looking into this! You have to hover your cursor directly over the Thrash icon OR the `Delete` word.

In Chrome, the tooltip with text blinks continuously. In Firefox, the cursor (hand sign, refer to the right side of the image) blinks continuously.
![image](https://user-images.githubusercontent.com/25320782/55205128-925a7e00-520c-11e9-8720-2fc171786ba9.png)

**Comment by martinoamigo** [comment]
That's odd, I still don't see it in Chrome (which I just now updated). I've tried multiple zooms and locations in the button. Here is another screenshot with the cursor visible:
![Screen Shot 2019-03-29 at 9 44 53 AM](https://user-images.githubusercontent.com/25358466/55237299-3db50400-5208-11e9-91d3-108c5d2ce9e6.png)

**Comment by amrut-prabhu** [comment]
Btw I also noticed this in the instructor home page (`/web/instructor/home`) and instructions sessions page (`web/instructor/sessions`).

![20190331_01h33_07](https://user-images.githubusercontent.com/29021586/55279585-09029300-5355-11e9-98ef-b69aa07dc02f.gif)

This behaviour is not consistently experienced. For example, the button is rendered on the next line sometimes, and doesn't suffer from this issue
<img width="960" alt="2019-03-24_16h16_17" src="https://user-images.githubusercontent.com/29021586/54876915-d4717180-4e52-11e9-9728-dd4f46323286.png">

**Comment by martinoamigo** [comment]
Strangely enough I can't seem to reproduce this issue on my Mac. I guess I'll just leave it to someone who can :)

On another note, I'm thinking the remind button should be in line on `/web/instructor/home`, similar to how it is on `web/instructor/sessions`. Another issue perhaps?

**Comment by wkurniawan07** [comment]
This has been fixed.
