### ISSUE TITLE
Deleting the last instructor in the course leaves a dangling course object in the database.

### ISSUE THREAD

**Issue by ChooJeremy** [TEAMMATES/teammates#9534]
- **Environment**: master branch at commit 2429ab644d751ff8e2fc310cd6dc854f40992868

**Steps to reproduce**
* Login as instructor _A_
* create a course _B_.
* Login as admin
* Visit http://localhost:4200/web/admin/accounts?instructorid=A (For example, http://localhost:4200/web/admin/accounts?instructorid=test@example.com)
* Choose to delete instructor _A_ from course _B_

**Actual behavior**
* Deletion success. Course _B_ now has no instructor associated to it, so it basically becomes a dangling course object in the database with no way to access it.

**Expected behaviour**
Perhaps change it so that deleting the last instructor from a course isn't possible? This would allow utilizing the same functionality for an instructor - if an instructor tries to delete himself from a course in which he's the only instructor, that fails with the message `The instructor you are trying to delete is the last instructor in the course. Deleting the last instructor from the course is not allowed.` 

**Additional info**
Looking for feedback on if you want this feature or not @damithc

**Comment by mattlim1207** [comment]
If no one is working on this/if this is still relevant, I can take it.

**Comment by mattlim1207** [comment]
I can take this up if still relevant

**Comment by zhaojj2209** [comment]
Hello, feel free to submit a PR for this!

**Comment by mattlim1207** [comment]
Ran into a bit of a wall with E2E testing where a test fails, do all E2E tests need to pass?  A few tests fail both with and without my modifications, and from my limited knowledge, the change I made should have absolutely no affect on it.
