### ISSUE TITLE
Instructor Help Page: Tooltips should link to specific sections in the help page

### ISSUE THREAD

**Issue by tanhengyeow** [TEAMMATES/teammates#9537]
**Environment**:
`master` branch

**Description of feature/enhancement**
All the tooltips in the app should link to the specific section of the instructor help page. Right now, clicking on the tooltips show users the top of the help page by default. 

An example is in `/web/instructor/sessions`:
![image](https://user-images.githubusercontent.com/25320782/53740250-c0c79080-3ece-11e9-92c5-40b9e9923ab4.png)

**Justification**
Users would not need to scroll/find the section after clicking on the tooltip.

**Comment by okasha30495** [comment]
I would like to fix this issue!

**Comment by tanhengyeow** [comment]
@okasha30495 Please do so, refer to our contributing guidelines to get started :)

**Comment by okasha30495** [comment]
Thank you @tanhengyeow, I've already solved a d.firstTimers which was updating the UserMap issues fixed (9144, 9225, 9304, and 9533), and now I'm just waiting for it to be reviewed.

**Comment by tanhengyeow** [comment]
@okasha30495 Cool! Please go ahead and work on this issue :)
