### ISSUE TITLE
Setting up development environment document enhancement 

### ISSUE THREAD

**Issue by pbrahmbhatt3** [TEAMMATES/teammates#9540]
A link to install Python2.7 and JDK 1.8 should be provided in the Setting up development environment.

**Comment by wkurniawan07** [comment]
What is the use? Those two tools are far too commonly used and the most straightforward of Google search will already point you to the resources.

**Comment by pbrahmbhatt3** [comment]
The document has a link to download google SDK so I thought it will be a good idea to include the links for Python and JDK. It will make it easier and faster.

**Comment by wkurniawan07** [comment]
Google Cloud SDK is a rather specialized library. The two items you mentioned are programming languages which one is expected to know (albeit not the case for Python) prior to contributing. There's a big difference.

**Comment by pbrahmbhatt3** [comment]
I think its a good idea to include the links. As a developer I would want a document to have links to the software I have to download.

**Comment by wkurniawan07** [comment]
We don't wish to spoon-feed contributors with information that is most readily available with one Google search. If one struggles to install those tools or any other necessary tool, chances are s/he is going to struggle many times more when actually contributing code; especially if not having the language installed means one is not familiar with the language.

Also, those links can change in the future and we don't want an extra burden of having to adapt when it happens.

**Comment by nodermatt** [comment]
This discussion has been stale for over a year. @pbrahmbhatt3 have you got other ideas on how to improve the dev environment setup doc? Otherwise, this issue can be closed IMHO.
