### ISSUE TITLE
Local Project setup Build Failed

### ISSUE THREAD

**Issue by danielmaia19** [TEAMMATES/teammates#9541]
- **Commit SHA:** N/A
- **Operating System:** Linux Mint 19.1 (Tessa)
- **JDK Version:** 1.8
- **Node.js Version:** 8.10.0
- **Google Cloud SDK Version:** 237.0.0
- **Eclipse / IntelliJ Version (if applicable):** Intellij 2018.3
- **Firefox / Chrome Version (if applicable):**  Chrome 72.0.3626.121

I am new to the development community, and this is the first time I am contributing to a OSS.

**What I was trying to do / What I need help with**

I have completed the setup  going through the setup guide specified in the Contribution document, but I am getting a build error. I went through each step and everything was done without errors. When I ran ./gradlew appengineStart I get the message on the image below:

![screenshot from 2019-03-05 21-41-25](https://user-images.githubusercontent.com/22798680/53839465-722dfb00-3f8f-11e9-8345-200836a703fa.png)

When I ran the test in Intellij oer 200 of them failed.

**Attempts to resolve the problem**

I have removed all the files and re-installed it all from scratch but still get the same error.

**Comment by rrtheonlyone** [comment]
Thank you for your interest in contributing to teammates! As per mentioned in our developer guide at https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md did you run `./gradlew createConfigs` first?

**Comment by danielmaia19** [comment]
Great! Build was successful. Thank you!
I did run it before and still got the issue before I did the whole process from the beginning.

Now, I am getting the error when I last got the build successful and thats error 404 when navigating to http://localhost:8080? Have you come across this error?

**Comment by jacoblipech** [comment]
@danielmaia19 As mentioned in the development guide, you will have to run `./gradlew generateTypes` and `npm run build` for the dev server http://localhost:8080 to serve both the front-end and the back-end of the application.

Alternatively, we recommend you to run `./gradlew generateTypes` and `npm run start` to access the front end of the application at http://localhost:4200.

**Comment by danielmaia19** [comment]
I have managed to get the page to show up but just shows the loading icon in the middle of the screen and thats it.

**Comment by monmanuela** [comment]
@danielmaia19 Which page are you at? It's likely to be caused by [this issue](https://github.com/TEAMMATES/teammates/issues/9542).

**Comment by danielmaia19** [comment]
Uhhh! sort of the same. Mine however, shows the menu with the loading icon

![screenshot from 2019-03-06 10-14-55](https://user-images.githubusercontent.com/22798680/53873666-bf928280-3ff8-11e9-8625-52dddaebc72c.png)

**Comment by monmanuela** [comment]
@danielmaia19 Since the navbar appears, maybe you have not run the back-end yet. Follow the [instructions to run the back-end server here](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#managing-the-dev-server-back-end)

**Comment by danielmaia19** [comment]
I just resolved the issue, it was actually related to the node.js

It wasnt able to run because I did not have the latest version. So i did _sudo apt-get update_ then re-ran the ./gradlew appengineStart for the backend and it worked. 

Thanks guys for helping out! :smile:
