### ISSUE TITLE
Cannot load any public page

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9542]
**Environment**: 061f8456b51553e16b905811d2ecc7531c9a3140

**Steps to reproduce**

Visit `/web/sessions/result` or `/web/sessions/submission`

**Expected behaviour**

There should be something showing up even there is no URL parameter.

**Actual behaviour**

![image](https://user-images.githubusercontent.com/13977235/53868599-5ed36c00-4031-11e9-9913-fff78307a318.png)

Empty page.

**Additional info**

Regression from https://github.com/TEAMMATES/teammates/pull/9527 @monmanuela  :P `PublicPageComponent` will always have `isFetchingAuthDetails` === `true`. Actually, setting this value to `true` by default is problematic. We cannot assume every single page to be initialised with a fetching auth details request. It should be `false` by default and setting it to `true` when a page is actually sending the request.

**Comment by monmanuela** [comment]
Oh right, sorry! Will send the fix.
