### ISSUE TITLE
Adding Instrutor Results Action Buttons Cramped up

### ISSUE THREAD

**Issue by danielmaia19** [TEAMMATES/teammates#9545]
I was hoping if its ok to contribute to this issue to resolve it? When adding a instructor, on the results page, the action buttons are cramped up if the name names are too long
- **Environment**: 
Local Development server.

**Steps to reproduce**
Add a instructor with long name, email address, and university

**Expected behaviour**
Results page the action buttons are cramped up

**Actual behaviour**
Buttons should be side by side as if the details above were shorter

**Additional info**

![screenshot from 2019-03-06 11-06-05](https://user-images.githubusercontent.com/22798680/53877197-6fb7b980-4000-11e9-8b1a-02b697973695.png)

**Comment by monmanuela** [comment]
@danielmaia19 Sure, go ahead 😃

**Comment by stroupjason** [comment]
first-timer here. Is this still an open issue?

**Comment by danielmaia19** [comment]
Yes, its still open. I haven't had the chance to get around to it yet.

**Comment by stroupjason** [comment]
Perfect, I'll take this one - I'll try my best to get it done!

**Comment by hppranaav** [comment]
@monmanuela Is it appropriate to split the contents of the email field onto 2 lines through hyphenating them?

**Comment by monmanuela** [comment]
@hppranaav I think splitting at the domain name sounds good, but only when necessary. But I'm open to any suggestions :)

**Comment by Karthik-SS** [comment]
Hi there! I am a first time contributor, is this issue resolved? Please let me know.

**Comment by dodgees** [comment]
I intend to take this on.
