### ISSUE TITLE
Adding 'git init' to the Developers Instructions

### ISSUE THREAD

**Issue by kwchan19** [TEAMMATES/teammates#9548]
**Environment**:  
```master``` branch

**Description of feature/enhancement**
The 'step-by-step' instructions are not very clear to new developers that are beginners to ```git```.  If you currently follow the exact instructions, you will receive this error: 
```fatal: Not a git repository (or any of the parent directories): .git``` 

I suggest adding ```cd teammates-master``` and ```git init``` before adding the remote name.

**Justification**

Developers that are new to ```git``` will benefit from this. Instead of searching for ways to fix the error, I suggest just putting the above in the instructions.

**Comment by rrtheonlyone** [comment]
I am not sure as to why this is needed. The instructions do tell you to fork the repo and use that right?

Here is a guide to work with a fork: https://help.github.com/en/articles/fork-a-repo

**Comment by wkurniawan07** [comment]
> The 'step-by-step' instructions are not very clear to new developers that are beginners to `git`.

> Instead of searching for ways to fix the error, I suggest just putting the above in the instructions.

This is a general git knowledge, not TEAMMATES-specific knowledge. If "beginners to git" is the problem, then the solution is to learn git first, not to put irrelevant information in this repo.
