### ISSUE TITLE
Contact Page: Adding an Email Contact Form

### ISSUE THREAD

**Issue by kwchan19** [TEAMMATES/teammates#9550]
**Environment**: 
```master```

**Description of feature/enhancement**

![image](https://user-images.githubusercontent.com/37305130/53923893-d9a78180-4047-11e9-87f2-08eb061088d7.png)
I would like to add an email contact form on this page, instead of just pasting the link of the email address there.

**Justification**

It will give an easier access to the users that need help or are inquiring any questions.

**Comment by damithc** [comment]
Hmmm... not sure if that is worth the effort.

**Comment by kwchan19** [comment]
It doesn't take that long, i think it just makes the page look better.

**Comment by damithc** [comment]
> It doesn't take that long, i think it just makes the page look better.

Neither are good enough reasons :-) Is there any real value to the user?

**Comment by amrut-prabhu** [comment]
@kwchan19 Actually this may make it harder to ask for help, depending on the situation. What if the user wants to put a few screenshots or attachments in the email?

It won't necessarily be as simple as just adding a text input email form.
