### ISSUE TITLE
Instructor: Correct wrong colors and ensure consistency between modal boxes

### ISSUE THREAD

**Issue by tanhengyeow** [TEAMMATES/teammates#9551]
**Environment**:
`master` branch

**Steps to reproduce/Expected behavior**
The modal boxes present in the instructor pages are inconsistent and some have wrong colors. Below are a few examples. There might be more.
1. `/web/instructor/home`
- `Course` -> `Archive` 
![image](https://user-images.githubusercontent.com/25320782/53936808-17f37e00-40e6-11e9-9cec-fe778be02f50.png)
- `Course` -> Header's `Delete` & Row's `Delete`
![image](https://user-images.githubusercontent.com/25320782/53936853-41140e80-40e6-11e9-8570-0bef2d96fb52.png)
![image](https://user-images.githubusercontent.com/25320782/53936905-6a349f00-40e6-11e9-884e-7e3c2fc51bf5.png)
2. `/web/instructor/courses`
- `Course`'s row -> `Delete`
![image](https://user-images.githubusercontent.com/25320782/53936979-9cde9780-40e6-11e9-8d65-c93f00f20afc.png)
3. `/web/instructor/courses/details?courseid=inst.exa-demo`
- Row's `delete (`student-list-component`)
![image](https://user-images.githubusercontent.com/25320782/53937028-ceeff980-40e6-11e9-8b7b-7b7c8d517831.png)

Also, some modal boxes have excess padding and should be removed. Example below:
![image](https://user-images.githubusercontent.com/25320782/53937201-66ede300-40e7-11e9-9cfa-955c90967b6c.png)

**Expected behavior**
1. Warning modal boxes should be using the same yellow hex code
2. Delete modal boxes should be using the same red hex code
3. Archive/normal message modal boxes should be using the same blue hex code

**Comment by ritisha2000** [comment]
May I work on this issue?

**Comment by tanhengyeow** [comment]
@ritisha2000 Sure you can, but I would advice merging in your first PR first :) The Travis build is still failing.

**Comment by ritisha2000** [comment]
Okay thank you
