### ISSUE TITLE
Instructor: Standardise look/behavior for Recycle Bin

### ISSUE THREAD

**Issue by tanhengyeow** [TEAMMATES/teammates#9554]
**Environment**:
`master` branch

**Steps to reproduce**
The recycle bins of courses and sessions look and behave differently (one is able to expand & collapse while the other can't) now. They should look/behave similarly.
![image](https://user-images.githubusercontent.com/25320782/54039531-22a13680-41fe-11e9-836b-1cb9722fbe59.png)
![image](https://user-images.githubusercontent.com/25320782/54039544-292fae00-41fe-11e9-8edc-87aa0efc5488.png)

**Comment by ariendy** [comment]
I would like to work on this.

**Comment by amrut-prabhu** [comment]
Hi @ariendy , please go ahead! Remember to follow our [process](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#fixing-issues) and let us know if you run into any problems :)

**Comment by Barbado2017** [comment]
Is it possible for me to work on this as well?

**Comment by tanhengyeow** [comment]
@Barbado2017 I would suggest you to look into other issues labeled `d.FirstTimers` as @ariendy as expressed interest to work on this one. There are plenty to choose from so no worries :) 

You can also try other issues too if you're feeling ambitious.
