### ISSUE TITLE
Join dialog shown to students: clarify option to proceed without registering

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9556]
v6.16

Current: when a student clicks on an access link to view/submit responses, the following message is shown if the browser is already logged in to a Google account
![image](https://user-images.githubusercontent.com/1673303/54065340-848f8980-425a-11e9-8375-7407a576cc26.png)

Problem: it's not very clear that there is an option to proceed without registering

Suggestion: revise the dialog to clarify the two options. 
* We can change the button color from red to blue (or green) as the option is not a 'danger' option.
* We can rephrase button options to `Use Google account abc to access this course` and `Access course without using the Google account`.
* Further rephrasing to the dialog text
* ...

Other implications: we might need two different dialogs: one for those coming via a 'join' link and one for those coming via a 'submit'/'view' link

**Comment by ithompson4** [comment]
Hello @damithc. Can I work on this issue?

**Comment by damithc** [comment]
> Hello @damithc. Can I work on this issue?

@xpdavid @wkurniawan07 what do you think? The screenshot above is from V6.

**Comment by wkurniawan07** [comment]
I need to confirm the issue. This particular user flow is re-written in V7.

**Comment by wkurniawan07** [comment]
@ithompson4 meanwhile, you can try other issues labelled `d.FirstTimers` if this is your first time contributing here.

**Comment by xpdavid** [comment]
The workflow is a bit different in V7.

**For course join link:**

![image](https://user-images.githubusercontent.com/13977235/54261847-c0eb1e80-45a7-11e9-8419-1b4d24130fc0.png)

There is only one button. We can do some improvements as @damithc has suggested.

**For session submission/result link:**

User is not forced to join (even they have a google account logged in) while they are given an option to join the course in the page.

![image](https://user-images.githubusercontent.com/13977235/54262073-4a9aec00-45a8-11e9-9fbe-174a4275f9ec.png)

**Comment by wkurniawan07** [comment]
@damithc the user flow is different here so the issue no longer holds. Either that, or a new issue is in order.

V6:
- No logged in user: show submission/result page as is
- Logged in user, the student entity has no Google ID associated: asks for Google ID confirmation (as per screenshot)
- Logged in user, the student entity's Google ID matches: redirect to logged-in equivalent of the submission/result page
- Logged in user, the student entity's Google ID matches: redirect to "The link you provided belongs to a different user"

V7:
All cases: show submission/result page as is, no attempt to redirect whatsoever.

**Comment by damithc** [comment]
> V7:
> All cases: show submission/result page as is, no attempt to redirect whatsoever.

I think this is fine. 👍

**Comment by damithc** [comment]
Closing issue as no longer applicable in V7.
