### ISSUE TITLE
Backend validation for empty MCQ options not implemented.

### ISSUE THREAD

**Issue by RonakLakhotia** [TEAMMATES/teammates#9562]
In v7, there is no backend validation if all MCQ options are empty. While in v6, an error is thrown if MCQs entered are all empty.

**Comment by wkurniawan07** [comment]
@RonakLakhotia but support for MCQ has not been migrated in the first place?

**Comment by RonakLakhotia** [comment]
I am working on the support for MCQ questions. While validating for the question details for MCQ type questions, I noticed the bug. The backend validates other scenarios like minimum two MCQs should be entered but does not take the case when all MCQs are empty

**Comment by wkurniawan07** [comment]
You can't have a bug if the feature is not even supported in the first place.
