### ISSUE TITLE
Fix unstable FeedbackQuestionAttributesTest

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9565]
- **Environment**: da079783605f64265d6ba9324e79768ad613a844

**Steps to reproduce**

![image](https://user-images.githubusercontent.com/13977235/54110127-8bb1c580-441b-11e9-8905-fb789effc3b2.png)

1. Run `FeedbackQuestionAttributesTest#testToEntity()`.
2. It will fail if the execution of the test is slow.

**Expected behaviour**
1. The test should pass no matter how slow/fast the test is executed.

**Actual behaviour**
1. It fails sometimes.

**Additional info**
Probably we should just assert not null for `getCreatedAt` and `getUpdatedAt`.

**Comment by Barbado2017** [comment]
Is it okay if I work on this?

**Comment by ChooJeremy** [comment]
@Barbado2017 Sure, go ahead! If you haven't set up your local repo, you can follow [this guide](https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md) to get started.
