### ISSUE TITLE
Confusing user flow in Student Profile upload photo feature

### ISSUE THREAD

**Issue by monmanuela** [TEAMMATES/teammates#9573]
- **Environment**: `master` branch, commit `ba5b2ef`

**Steps to reproduce**
- Go to Student Profile page
- Click `Upload/Edit Photo`
- Click `Browse` and choose a picture
- Click `Upload Picture`

**Expected behaviour**
The new picture should appear in the modal so that it can be cropped and edited, but the old photo should remain in the background

**Actual behaviour**
The old photo is already replaced by the new photo even before I click `Save Edited Photo`

**Additional info**

I think a better flow would be after choosing the new photo, the new photo should appear in the cropper immediately. Then, the `Upload Picture` button can be removed and saving the changes can be done by clicking `Save Edited Photo`.

**Comment by xpdavid** [comment]
After #9575, need investigate on whether this issue is valid or not.

**Comment by damithc** [comment]
> After #9575, need investigate on whether this issue is valid or not.

Looks like no longer valid. Closing.
