### ISSUE TITLE
Clicking Save Edited Photo does not close the modal in Student Profile page

### ISSUE THREAD

**Issue by monmanuela** [TEAMMATES/teammates#9574]
- **Environment**: Environment: master branch, commit ba5b2ef

**Steps to reproduce**
- Go to Students Profile page
- Click `Upload/Edit Photo`, choose a new photo
- Click `Save Edited Photo`

**Expected behaviour**
The photo should be changed and the modal should be closed

**Actual behaviour**
The modal remains open although the photo is changed
![image](https://user-images.githubusercontent.com/35655790/54340038-73d37f00-4671-11e9-8be8-79fe07bce789.png)

**Comment by hedglenrm** [comment]
Is it ok if I work on this issue?

**Comment by sil3nthill** [comment]
hello  i would like to fix this if its ok !

**Comment by monmanuela** [comment]
Hi @sil3nthill, thank you for your interest in contributing to TEAMMATES! However, there's already an open PR for this (#9588) so please look into other issues to prevent duplicate work 😄
