### ISSUE TITLE
Change error message for Instructor Course Details Ajax failure

### ISSUE THREAD

**Issue by AyushChatto** [TEAMMATES/teammates#9584]
The current error message for an Ajax failure is `'Failed to load. Please reopen modal.'`. Since modal is a technical term, it should not be used for anything facing the client, and must be replaced with a better error message. 

- **Environment**: 
v7.0

**Comment by devotion-it** [comment]
Hi @AyushChatto. I would like to work on this issue?

**Comment by AyushChatto** [comment]
@devotion-it go for it :) Do familiarise yourself with our contributors guide :)

**Comment by devotion-it** [comment]
Hi @AyushChatto  just wanted to inform you that i submitted a PR for this issue.
