### ISSUE TITLE
No user feedback for empty search results on Admin page

### ISSUE THREAD

**Issue by amrut-prabhu** [TEAMMATES/teammates#9585]
- **Environment**: 
`master` branch at commit `9542ad8`.

**Steps to reproduce**
1. Log in as Admin
2. Go to Admin Search page
3. Search for some random string (which will not return any results from the backend)

**Expected behaviour**
There is some message informing the user that no results were found

**Actual behaviour**

There is no feedback to the user:
<img width="960" alt="2019-03-19_23h36_04" src="https://user-images.githubusercontent.com/29021586/54619586-cf51a280-4a9f-11e9-8c90-b6e4f0d978bb.png">

**Additional Notes**
The instructor search page displays a relevant message at the top of the page
<img width="960" alt="2019-03-19_23h40_23" src="https://user-images.githubusercontent.com/29021586/54620039-8a7a3b80-4aa0-11e9-9fc8-2b54f0fc23b8.png">

**Comment by Davileal** [comment]
I can get this issue.
