### ISSUE TITLE
Add feature to regenerate student's session links

### ISSUE THREAD

**Issue by amrut-prabhu** [TEAMMATES/teammates#9604]
**Description of feature/enhancement**
Provide a way for to regenerate session links for a student. This is for cases where the student shares a submission link with others by mistake.

---
**Proposed Admin Workflow:**

1. Admin searches for a student by name in the admin search page
1. Admin expands the student result to view feedback session links
1. Admin clicks the `Regenerate` button for a course. Admin confirms the action in the pop-up modal.

**Result:**
New submission and report links for all the feedback sessions in that course are generated. An email is sent to the student (CCed to admin). Original submission and report content are moved to the corresponding new link.
Original links becomes invalid.

---

**Comment by wkurniawan07** [comment]
@amrut-prabhu, are you sure of the workflow? As far as I know, there is no way to regenerate just one submission link...

**Comment by amrut-prabhu** [comment]
@wkurniawan07 Oh, right. All the submission and report links of the student will have to change. I've updated the workflow

**Comment by princejha95** [comment]
Hi, I am interested in working on the project. Can i be a part of this project ?

**Comment by amrut-prabhu** [comment]
Hi @princejha95, thanks for your interest in TEAMMATES!

However, as you can see above, there PR #9610 has already been made to fix this issue.

As you are new to the project, perhaps it would be better for you to fix a [first timer issue](https://github.com/teammates/teammates/issues?q=is%3Aissue+is%3Aopen+label%3Ad.FirstTimers) before trying to work on a larger (and tougher) `c.Epic` issues like this one.

> NoClassDefFoundError caught by WebApiServlet

Not sure about this right now

> Currently i have tried hitting the session link recovery API. Can anyone please help me out so that i can understand the complete flow of how session link recovery actually works ?

If you're asking about the flow from a user perspective, you can refer to the GIFs in the PR description of #9447

Let us know if you need help with anything else

**Comment by princejha95** [comment]
Sure. I will try to fix bugs which has first timer tag. But i am facing one problem. When i am trying to use debugger in intellij using remote debug, then the request does not stop at the breakpoint set by me.

So could yo please guide me how to suspend the request at the breakpoint set by me ? I have tried almost everything but nothing is working for me.

**Comment by amrut-prabhu** [comment]
@princejha95 Can you try running it in Debug mode from IntelliJ itself instead of remote debug?

![image](https://user-images.githubusercontent.com/29021586/56556992-10236680-65cc-11e9-91cf-01cce9ab042f.png)

**Comment by princejha95** [comment]
Can you send the configuration set for the Google App Engine Standard Local
Server ?

**Comment by amrut-prabhu** [comment]
@princejha95 If I'm not mistaken, it should be configured automatically once you set up the project as outlined in our setup guide. Here's my configuration

<img width="818" alt="2019-04-25_00h09_22" src="https://user-images.githubusercontent.com/29021586/56675403-8c15cf80-66ee-11e9-98d0-f130aa9474a3.png">

**Comment by princejha95** [comment]
I have Google App Engine Deployment and stackdriver but not what u have
shown. I have followed the instructions given in the project for
installation but its not showing in my intellij. I have cloud code plugins
installed in my intellij.
