### ISSUE TITLE
Improve students card in Instructor Student Page

### ISSUE THREAD

**Issue by amrut-prabhu** [TEAMMATES/teammates#9606]
- **Environment**: `master` branch at commit 9c97b9c3.

**Steps to reproduce**
1. Go to the `/web/instructor/students`page
1. Click on one of the courses

**Expected behaviour**
The DOWN arrow and UP arrow should be switched, i.e., show DOWN arrow when students are hidden, and UP arrow when the card is open.

**Actual behaviour**
The arrows do not correspond to the actions.

![20190324_13h06_19](https://user-images.githubusercontent.com/29021586/54876783-9e32f280-4e50-11e9-8084-a2bd92c197ba.gif)

**Comment by homps** [comment]
Hi :wave:
I'll pick up this fix if that's ok.

**Comment by amrut-prabhu** [comment]
Hi @homps, go ahead. Refer to our [process](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#fixing-issues) and let us know if you face any problems :)

**Comment by HeinKhantZaw** [comment]
Hello everyone! I am new to GitHub and I have Java and C++ experience. Can anyone help me understand how I can contribute to this project and guide me towards solving this issue.

**Comment by amrut-prabhu** [comment]
Hi @HeinKhantZaw , thanks for your interest in contributing to TEAMMATES!

To set up TEAMMATES on your computer, you can follow the setup instructions, starting from [this document](https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md). After that, you can refer to [our process](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#fixing-issues) to understand how to contribute.

FYI, this specific issue requires some knowledge of HTML, and Angular/TypeScript (note that it is labelled as `a-UIX`). You can try taking up another [first timer issue](https://github.com/TEAMMATES/teammates/labels/d.FirstTimers) since another person has already submitted a fix for this issue. 

Hope that helps :) Welcome to open source development!
