### ISSUE TITLE
Keep course students card stationary when expanded in Instructor Student Page

### ISSUE THREAD

**Issue by amrut-prabhu** [TEAMMATES/teammates#9616]
- **Environment**: `master` branch at commit 9c97b9c3.

**Steps to reproduce**
1. Go to the `/web/instructor/students`page
1. Click on one of the courses

**Expected behaviour**
The course card should stay at the same position on the screen.

**Actual behaviour**
The course card generally moves down and is not at the same position on the screen.

![20190324_13h06_19](https://user-images.githubusercontent.com/29021586/54876783-9e32f280-4e50-11e9-8084-a2bd92c197ba.gif)

**Additional info**
This occurs due to a list of details (like students) being added to the filter on the top of the page in a not so user-friendly way. If there are a lot of students in the course, the expanded card(s) will be moved way below the displayed screen.
This can also be problematic when differentiating between students that have the same email address across different courses .
<img width="679" alt="image (1)" src="https://user-images.githubusercontent.com/29021586/54969970-4c5aab80-4fbb-11e9-8be3-7c2f484df03f.png">

**Comment by amrut-prabhu** [comment]
2 approaches that can be used to fix this:

- Autoscroll to the position of the course card after it is clicked.

- Restructure the way that the filters are displayed so that this problem doesn't occur. It can use dropdowns instead. The root level options should only contain options similar to the ones under `Courses`. It look something like this (note that the content shown in not finalised, just for illustration):
  
  ![image (2)](https://user-images.githubusercontent.com/29021586/54971258-867a7c00-4fc0-11e9-9d05-1d369e5bda6a.jpg)

**Comment by rrtheonlyone** [comment]
Hi @amrut-prabhu, I am currently working on simplifying the logic for this same page.

Like you pointed out, we have to look into a different way to handle the filtering. Showing all the student emails may lead to the box growing really large.

@damithc @wkurniawan07 @xpdavid Can we look into a different method to do the filtering? Like just one row of dropdowns instead of a box?

**Comment by damithc** [comment]
Sorry I didn't mention this earlier. I'm OK with removing this part (shown in the screenshot below) entirely if there is consent from others. While it is a useful feature, acting as a mailing list is not within the core mission of TEAMMATES. The instructors can depend on their main LMS for that functionality. Still, I'm OK both ways.

![image](https://user-images.githubusercontent.com/1673303/54985111-2947f000-4feb-11e9-82c8-5270e1dee79b.png)
