### ISSUE TITLE
compile errors and unable to build the project

### ISSUE THREAD

**Issue by Rafaila98** [TEAMMATES/teammates#9622]
Problem with building the project due to Java compile errors and start AppEngine  
- **Commit SHA:**  2429ab644d751ff8e2fc310cd6dc854f40992868

- **Operating System:** Windows 10
- **JDK Version:** 1.8.0_121
- **Node.js Version:** v10.15.3
- **Google Cloud SDK Version:** 240.0.0
- **Eclipse Version :** 2018-09(4.9.0)

**What I was trying to do / What I need help with**
 1.  Build failed with the command "./gradlew appengineStart"
![image](https://user-images.githubusercontent.com/32717035/55231140-6cdc6d00-522a-11e9-8447-12e86a3cb79e.png)

2.   The taglibs in jsp pages cannot be compiled and running AppEngine cannot start
![image](https://user-images.githubusercontent.com/32717035/55230340-356cc100-5228-11e9-8605-f9d8c9d6e728.png)

**Attempts to resolve the problem**
 Firstly, I'd noticed that I had node 11 version and I thought that this was the problem.  But, now all are on set, these problems  still exist. 
The libraries I have checked are still available.

**Comment by AyushChatto** [comment]
Have you tried running `./gradlew generateTypes` first?

**Comment by Rafaila98** [comment]
Hello @AyushChatto. Thanks for answering. I already tried it and here are the results:

![image](https://user-images.githubusercontent.com/32717035/55315136-5de8fb00-5474-11e9-9b19-c55dba8b4b76.png)

In a linux mint machine everything is running ok but in Windows something's wrong.

**Comment by wkurniawan07** [comment]
@Rafaila98, when you run `./gradlew dependencies`, is there an entry that looks like `javax.servlet:javax.servlet-api:...`? If there is, what is the version number associated with it?

Node.js version has nothing to do with this.

**Comment by Rafaila98** [comment]
Hello @wkurniawan07. 
+--- javax.servlet:javax.servlet-api:3.1.0
