### ISSUE TITLE
Instructor Home Page: Inconsistent behaviour in sort by date action for courses

### ISSUE THREAD

**Issue by jacoblipech** [TEAMMATES/teammates#9629]
**Steps to reproduce**
Log in to Instructor Home Page.
Click on sort by Feedback Session or click sort by creation_date as highlighted in the attached image below.

**Current behaviour**
It does not populate the feedback sessions / courses in the correct order as shown below.
![Screenshot 2019-04-01 at 1 39 09 AM](https://user-images.githubusercontent.com/28522090/55292583-3ddb1c80-541f-11e9-928a-887abde1c5f8.png)

**Expected behaviour**
Supposed to populate according to descending or ascending order of the date correctly.

**Additional info**
I did a minor investigation. As the sorting is by string to string comparison, I think the current format of the date for comparison needs to be changed in order to have accurate string to string comparison

**Comment by martinoamigo** [comment]
I'll take this one!

**Comment by wkurniawan07** [comment]
> As the sorting is by string to string comparison

@jacoblipech, this is the error that needs to be rectified, not to "hack" the date format to be sorting-friendly.

**Comment by jacoblipech** [comment]
@martinoamigo Go ahead and take this issue. Feel free to let me know here if you require any assist or reproducing the error!

As mentioned by @wkurniawan07 you should aim to solve the sort by course creation date and sort by feedback session creation date.

**Comment by martinoamigo** [comment]
It seems that the sort is correct, although the example feedback session dates are in different years. For example, if I hover over each date I can see which year it is from, and that they are sorted correctly.

Possible solutions: I can add the year to the display for clarity, or change the examples to be in 2019. Maybe both?

**Comment by jacoblipech** [comment]
@martinoamigo Sorry for the late reply. Verified on this as well and you are right 👍 My bad for missing out the year part! I think since there is already a tooltip, it is not necessary to show the year.

However, after some digging, I found that the problem still exists in sort by courses. The sorting algorithm is correct but the problem lies in the format the `creationDate` is sent to frontend for sorting.

For sessions, it takes into account the exact time stamp when doing the sorting so it is correct but for courses, only the date is populated so it is not consistent when sorting courses of the same date. 

Would you still like to work on this? If not I can send in an easy fix. The problem lies in `CourseData`.

**Comment by martinoamigo** [comment]
@jacoblipech No worries, I don't need to work on this. Happy to help where I could, feel free to send in the quick fix 👍
