### ISSUE TITLE
Instructor set non-visible feedback session is visible to students

### ISSUE THREAD

**Issue by ChooJeremy** [TEAMMATES/teammates#9630]
- **Environment**: `master` branch at commit 3455dda7e4e2d854471b1664548f76f002bfd4b9.

**Steps to reproduce**
1. Login as instructor..
2. Instructor creates a feedback session. Set feedback session visible time to after today.
![image](https://user-images.githubusercontent.com/4904988/55306070-68f85700-5485-11e9-8c97-dd4c3c552fe5.png)
3. Login as student with access to the feedback session

**Expected behaviour**
Feedback session should not be visible

**Actual behaviour**
Feedback session is visible.
![image](https://user-images.githubusercontent.com/4904988/55305971-08691a00-5485-11e9-9748-3d94b79b2797.png)

**Additional info**

This is regression from v6.  In v6, it is clear that only 1 of the feedback session is visible:
2 feedback sessions created:
![image](https://user-images.githubusercontent.com/4904988/55305016-fb4a2c00-5480-11e9-89b9-6a1678419b94.png)
Only 1 is visible to the student:
![image](https://user-images.githubusercontent.com/4904988/55305028-08ffb180-5481-11e9-9db4-75cc93eab390.png)

**Comment by swood049** [comment]
May I have a go at this one?

**Comment by ChooJeremy** [comment]
@swood049 Sure. Before you start you may want to verify if this issue even still exists - it's a pretty old issue.

**Comment by AdithyaNarayan** [comment]
It seems like this issue does not exist anymore at commit be7f0b6. Not sure at which commit it was fixed, but it does not occur anymore.

Also, a point to note is that there is a new feature in v7 that enables instructors to make the feedback session visible to all students before the feedback session is open for student responses. Hence, it is possible that the issue was reported when the opening date was set to the future and not the visibility date.

**Comment by damithc** [comment]
> Also, a point to note is that there is a new feature in v7 that enables instructors to make the feedback session visible to all students before the feedback session is open for student responses. Hence, it is possible that the issue was reported when the opening date was set to the future and not the visibility date.

Thanks for the investigation @AdithyaNarayan This feature was present in V6 as well. As to if the bug is really fixed now, let's wait for @ChooJeremy (or someone else) to cross check.

**Comment by ChooJeremy** [comment]
Yup, issue seems to have been resolved.
