### ISSUE TITLE
Feedback sessions with # or ? in their name can't be edited.

### ISSUE THREAD

**Issue by ChooJeremy** [TEAMMATES/teammates#9642]
Other potential characters may cause this problem as well.

- **Environment**: `master` branch at commit 3455dda7e4e2d854471b1664548f76f002bfd4b9.

**Steps to reproduce**
1. Login as an instructor.
2. Create a new feedback session with # in the name (i.e. test #9642)
3. Click edit on the new feedback session.

**Expected behaviour**
The feedback session edit page loads

**Actual behaviour**
It doesn't load.
![image](https://user-images.githubusercontent.com/4904988/55496086-dd431e00-5670-11e9-96ea-2e820acc6a14.png)

**Additional info**

This error occurs even after applying the fix from #9638 .
The server outputs the error log: 
`WARNING: UnauthorizedAccessException caught by WebApiServlet: Trying to access system using a non-existent feedback session entity`
The error appears to be from the frontend not sending the character `#` or `?` in the query (and anything after it)

**Comment by TheDheeraj007** [comment]
Hello! This issue looks interesting. Can I work on this issue?

**Comment by ChooJeremy** [comment]
Sure, go ahead! Usually we recommend starting with a first timer issue, but since there isn't one right now feel free to start working on this.

**Comment by dodgees** [comment]
It looks like there hasn't been any activity on this issue. Mind if I pick it up?

**Comment by ChooJeremy** [comment]
I don't mind - Go ahead :)

**Comment by hcwong** [comment]
If this is inactive I would like to take it

**Comment by hcwong** [comment]
It's probably the issue with URL special characters. I'm thinking of decoding/encoding the strings properly and also preventing future session names from having such characters.

**Comment by ChooJeremy** [comment]
Looks inactive - go ahead.
