### ISSUE TITLE
TimezoneSyncerTest may fail due to class loader ordering of tzdb.dat

### ISSUE THREAD

**Issue by umar-ehsan** [TEAMMATES/teammates#9645]
- **Environment**:  `master` branch at commit 31bd48c995b8aee60dfa6c2bbb53d32ce8f81772. 

OS: Windows 10 (Running tests and server using command line)

**Steps to reproduce**

After setting up dev environment, run the commands:

Front end dev server:
npm run start

Back-end dev server:
gradlew.bat appengineStart 

Then run the e2e tests:

gradlew.bat e2eTests --stacktrace

**Expected behaviour**

All tests pass and the page contains synced time zone information

**Actual behaviour**

e2e test for "TimezoneSyncerTest.java" fails in "testFrontendBackendTimezoneDatabasesAreConsistent".

The localhost:4200/web/admin/timezone page has conflicting information between java time zones and moment time zones

**Additional info**

![temp](https://user-images.githubusercontent.com/23662678/55599415-b266d180-5725-11e9-8312-1ebecdde9742.PNG)
![temp2](https://user-images.githubusercontent.com/23662678/55599416-b266d180-5725-11e9-937c-75a11b253464.PNG)

![temp3](https://user-images.githubusercontent.com/23662678/55599441-d0343680-5725-11e9-9543-6138c2d841f7.PNG)

**Comment by wkurniawan07** [comment]
@umar-ehsan, this is a known issue with unfortunately no workaround yet as of now. You can ignore this test failure.
