### ISSUE TITLE
Viewing photos of students on course details page shows error message

### ISSUE THREAD

**Issue by RonakLakhotia** [TEAMMATES/teammates#9649]
**Steps to reproduce**

* Sign in as an instructor and navigate to courses page.
* Click on `View` for any one of the course
* Click on `View photo` for a student

**Actual behavior

* "Request not valid message displayed"

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/28557842/55667013-3d141180-5889-11e9-9512-d13f1d33e226.gif)

**Comment by aishaadambek** [comment]
Hi @RonakLakhotia,

unfortunately, with the steps you specified, the bug is **not reproducible anymore**. Student photos can be viewed normally.  

I suspect that the bug has been fixed already. If It probably makes sense to close the issue.

Thanks! :)
