### ISSUE TITLE
Error messages not shown on entering invalid answers on submission page

### ISSUE THREAD

**Issue by RonakLakhotia** [TEAMMATES/teammates#9654]
**Steps to reproduce**

* Log in as student
* Navigate to submission page of any session
* Answer a question with an invalid value

**Expected behavior**

* An message is shown explicitly telling the user what the error is

**Actual behavior**

* No message describing the error is shown

**Additional info**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/28557842/55682442-04963580-5966-11e9-8f18-e08b8880d3c2.gif)

**Comment by hppranaav** [comment]
@RonakLakhotia Hey!, i have contributed to a couple of beginner issues at teammates. I would like to work on this issue if possible.

**Comment by RonakLakhotia** [comment]
@hppranaav sure go ahead!
