### ISSUE TITLE
Instructor: resend result link: cannot tick checkbox in Chrome

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9656]
V6.16.2

A user reported that when trying to resend results link to a student, the check boxes cannot be ticked. She is using Chrome.

![image](https://user-images.githubusercontent.com/1673303/55702369-fe0cca00-5a08-11e9-93db-491a97b58788.png)

I was able to reproduce in my Chrome (Windows) too. Seems to work in Firefox though.

**Comment by damithc** [comment]
Seems to happen for sending of submission links too, which makes the problem rather serious. This was working before. Broken due to an update to Chrome?

**Comment by xpdavid** [comment]
Confirmed also in Mac - Chrome Version 73.0.3683.103 (Official Build) (64-bit)

Looks like the checkbox is not clickable inside a label.
![image](https://user-images.githubusercontent.com/13977235/55703917-82f9e280-5a0d-11e9-90b5-48e38f74f798.png)

Updated:
Looks like it is really specific to this version of Chrome.

If Canary (https://www.google.com/intl/en_sg/chrome/canary/) (version ahead of official Chorme) is used (Version 75.0.3755.0 (Official Build) canary (64-bit)), it works.

**Comment by damithc** [comment]
Thanks for the investigation @xpdavid Easy to fix?

**Comment by xpdavid** [comment]
Looks like this is caused by CSS although I don't know what's wrong with the CSS.
```
.table-column-no-float {
    float: none !important;
}
```
As shown below, if we disable it, the checkbox is clickable.
![Jietu20190410-214650-HD](https://user-images.githubusercontent.com/13977235/55884469-b2aa1580-5bda-11e9-8e24-ae5acf6137b9.gif)


@wkurniawan07 Any idea?

**Comment by damithc** [comment]
Still broken. Any idea if this is recognized as a Chrome bug?

**Comment by xpdavid** [comment]
Looks like the bug is fixed? Just updated my Chrome to the newest version and the checkbox works now.

**Comment by damithc** [comment]
> Looks like the bug is fixed? Just updated my Chrome to the newest version and the checkbox works now.

Yes. 👍
