### ISSUE TITLE
Improve look of dropdown options in team contribution question

### ISSUE THREAD

**Issue by amrut-prabhu** [TEAMMATES/teammates#9657]
- **Environment**: `master` branch at commit 87a87e9e.

**Steps to reproduce**:
1. Go to the submission page of a feedback session that has a team contribution question. (eg. `/web/student/sessions/submission?courseid=test.exa-demo&fsname=Second%20team%20feedback%20session`)
2. Open the team contribution question's dropdown options

**Expected behaviour**
The colours of the options should be consistent with that of v6. `Equal share + ...` should be green, `Equal share - ...` should be red, and the remaining should be grey.

<img width="164" alt="2019-04-10_11h41_42" src="https://user-images.githubusercontent.com/29021586/55850396-b90ea200-5b86-11e9-9f1d-ae111168b1d1.png"><img width="172" alt="2019-04-10_11h41_52" src="https://user-images.githubusercontent.com/29021586/55850391-b744de80-5b86-11e9-992c-94fbeaf000dd.png">

**Actual behaviour**
The colour of all the dropdown options is that of the option that was selected.

<img width="350" alt="2019-04-10_11h41_14" src="https://user-images.githubusercontent.com/29021586/55850424-d93e6100-5b86-11e9-8e9f-0aa369bb0f60.png"><img width="342" alt="2019-04-10_11h41_31" src="https://user-images.githubusercontent.com/29021586/55850427-dba0bb00-5b86-11e9-8a33-5bf59b3f9e81.png">

**Additional notes:**
While we're at it, the width of the dropdown in v7 can be reduced to look like the one in v6.

**Comment by arturolc** [comment]
Hi, @amrut-prabhu I would like to work on this issue. I am barely getting started with Open Source contributions, so any mentorship is appreciated! :)
