### ISSUE TITLE
Nav bar items need to be clicked twice to open page in new tab

### ISSUE THREAD

**Issue by amrut-prabhu** [TEAMMATES/teammates#9669]
- **Environment**:  `master` branch at commit e360fc0c5

**Steps to reproduce**
1. Go to any page that has navbar items (eg. `web/front/home`)
2. Hold `ctrl` on the keyboard (or equivalent key for Mac) and click on a nav bar item.

**Expected behaviour**
The page corresponding to the nav bar item opens in a new background tab.

**Actual behaviour**
The page does not open. A second click is required for the expected behaviour to occur

![20190413_05h57_41](https://user-images.githubusercontent.com/29021586/56068527-c3f94a80-5db1-11e9-8c34-38f1d2681cec.gif)

**Comment by PanagiotisBatsikouras** [comment]
Hello, I find your project very interesting and I would like to contribute. May I take up this issue as a new contributor?

**Comment by ValeriaCobianISW** [comment]
Hi @amrut-prabhu , are you working on this issue? I would like to contribute. :smiley:

**Comment by amrut-prabhu** [comment]
Hi @ValeriaCobianISW , no, I'm not working on this right now. Feel free to take it up 
Remember to refer to [our development workflow](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-2-start-clean-from-a-new-branch) :)
