### ISSUE TITLE
Remove unused variables in Const.ResourceURIs

### ISSUE THREAD

**Issue by ChooJeremy** [TEAMMATES/teammates#9674]
- **Environment**: `master` branch at commit a384354b8ecf3cb87006184185724f16560cf14b.

With the change from v6 to v7, the API team has been hard at work consolidating endpoints to convert them to more general endpoints, removing specialized endpoints made specifically to serve a single page.

However, with this change some old endpoints have had their URL listed in Const.ResourceURIs but have not been removed yet. A good starting task would be to remove them to clean up unused variables in Const and make it neater.

If you're using IntelliJ, it is easy to identify these unused variables, because they would be greyed out from IntelliJ's static analysis tools. They can just be directly removed. 

![image](https://user-images.githubusercontent.com/4904988/56150265-166c7e00-5fe1-11e9-9428-acf6a94a2786.png)

**Comment by sunny2121** [comment]
Hi, I'm interested in this project and hope to contribute to it. Can I work on this? I might have time this weekend.

**Comment by ChooJeremy** [comment]
@sunny2121 Sure, go ahead!

**Comment by sunny2121** [comment]
@ChooJeremy Thank you!

**Comment by eliasmaia** [comment]
Hi @sunny2121 

From which files we need to remove those unused variables?

**Comment by eliasmaia** [comment]
![ddiiff](https://user-images.githubusercontent.com/15288848/56222906-30d74380-6043-11e9-94ff-73e15fa67a2e.PNG)

I don't see greyed out lines or so. Am I looking at the right place @ChooJeremy ?

**Comment by ChooJeremy** [comment]
@eliasmaia 

That is the right file and place. You might need to wait a while for IntelliJ to perform indexing before they will show up. If they're still not showing up, you might not have it enabled. You can enable it under

File --> Settings --> Editor --> Inspections --> Java --> Declaration Redundancy --> Unused Declaration (In Windows, there should be something similar for other OS)
![image](https://user-images.githubusercontent.com/4904988/56259757-cc7db800-6106-11e9-92ff-af593d75d4c9.png)

If none of those are working for you, you might be able to get it working by forcing an inspection under Analyze -> Inspect Code -> Inspect Whole Scope.

**Comment by eliasmaia** [comment]
Hi @ChooJeremy 

I guess someone has already removed the unused variables, because I tried both approaches you suggested, but none worked out.

**Comment by ChooJeremy** [comment]
Hey @eliasmaia, I just checked and can verify that the unused variables are still there.

In the worse case scenario, you can use the Find usages tool to verify all of them independently, but that will be very time consuming on your end.

**Comment by hppranaav** [comment]
@ChooJeremy Hi!, I would like to take up this issue and hopefully contribute.
