### ISSUE TITLE
Cannot archive courses in the instructor home page

### ISSUE THREAD

**Issue by junming403** [TEAMMATES/teammates#9675]
<img width="1070" alt="4CD56C5290CFECABCDDA0DC5334279D4" src="https://user-images.githubusercontent.com/28641786/56208451-c4306900-6083-11e9-829d-7cfb2eb4fdfe.png">
<img width="1065" alt="8B9BD7F49F8F8C8F6CA3344B7EAA0A3B" src="https://user-images.githubusercontent.com/28641786/56208457-c692c300-6083-11e9-8b65-3e2c41f3a038.png">

I suspect this is due to imcomplete api migration.

**Comment by junming403** [comment]
@ChooJeremy  Any thoughts?

**Comment by jacoblipech** [comment]
I have been facing E2E tests failure for archive action because of this as well. I think the `archiveCourse` function in `instructor-home-page.component.ts` is not populated yet?
