### ISSUE TITLE
Instructor: Course Page: Improve status message after archiving a course

### ISSUE THREAD

**Issue by tanhengyeow** [TEAMMATES/teammates#9678]
**Environment**: 
`master` branch

**Description of feature/enhancement**
The status message after archiving a course is too lengthy:
![image](https://user-images.githubusercontent.com/25320782/56335488-45484700-61cf-11e9-840a-8746f802f098.png)

We can make the message more concise. The message from v6 serves as good inspiration:
![image](https://user-images.githubusercontent.com/25320782/56335502-5abd7100-61cf-11e9-9aac-2afd9c83b913.png)

**Justification**
Reduce eye tracking and the lengthy message doesn't add that much value.

**Comment by braedonaschmidt** [comment]
Hi, I'd like to give this a shot! Do you know what file contains this status message?

**Comment by tanhengyeow** [comment]
@braedonaschmidt Please go ahead! As finding the related file to change is part of the learning process, I wouldn't tell you what the exact file as this is a relatively simple fix :) 

But 1 hint I can provide is that you should look something along the lines of "Instructor Course".

**Comment by MrHuntix** [comment]
Hi, I'd like to give this a try. 
Just one question i.e. is a simple message like  'The course has been archived.It will not appear in the home page anymore' enough or does the course name also have to appear in the message for example 'The course ${courseName} has been archived.It will not appear in the home page anymore' where ${courseName} is the name of the selected course?
