### ISSUE TITLE
Instructor: Preview Sessions Submission Page's navbar covers some content on the page

### ISSUE THREAD

**Issue by tanhengyeow** [TEAMMATES/teammates#9679]
**Environment**: 
`master` branch

**Steps to reproduce**
1. Create an instructor with a lengthy name e.g. "dsadadasdsadadsadsadadasdsadadasdsadadsadsadadasdsadadasdsadadsadsadadasdsadadasdsadadsadsadadasdsad"
2. Edit a Feedback Session
3. Preview the session submission results with the instructor that has lengthy name e.g.
![image](https://user-images.githubusercontent.com/25320782/56338140-6e6ed480-61db-11e9-846c-e7daac13d55a.png)

**Expected behaviour**
The content on the page shouldn't be covered e.g.
![image](https://user-images.githubusercontent.com/25320782/56338163-8d6d6680-61db-11e9-8e93-b72c68c90caf.png)

**Actual behaviour**
Some content on the page is covered e.g.
![image](https://user-images.githubusercontent.com/25320782/56338173-965e3800-61db-11e9-8a2e-202d4fef4b4f.png)

**Additional info**
This is because the current page is using `class="navbar fixed-top ...."`. We should explore something that is more responsive.

**Comment by hcwong** [comment]
seems inactive - i'll assign myself.
