### ISSUE TITLE
cannot find module api-output 

### ISSUE THREAD

**Issue by HarikumarG** [TEAMMATES/teammates#9681]
ERROR in src/web/app/components/copy-session-modal/copy-session-modal.component.
ts(3,24): error TS2307: Cannot find module '../../../types/api-output'.
src/web/app/components/error-report/error-report.component.ts(3,36): error TS230
7: Cannot find module '../../../types/api-request'.
src/web/app/components/question-edit-form/feedback-path.pipe.ts(2,41): error TS2
307: Cannot find module '../../../types/api-output'.
src/web/app/components/question-edit-form/question-edit-form-model.ts(7,8): erro
r TS2307: Cannot find module '../../../types/api-output'.
src/web/app/components/question-edit-form/question-edit-form.component.ts(10,8):
 error TS2307: Cannot find module '../../../types/api-output'.
src/web/app/components/question-edit-form/visibility-setting.pipe.ts(2,40): erro
r TS2307: Cannot find module '../../../types/api-output'.
src/web/app/components/question-responses/single-response/single-response.compon
ent.ts(6,8): error TS2307: Cannot find module '../../../../types/api-output'.
src/web/app/components/question-submission-form/question-submission-form-model.t
s(8,8): error TS2307: Cannot find module '../../../types/api-output'.
src/web/app/components/question-submission-form/question-submission-form.compone
nt.ts(9,8): error TS2307: Cannot find module '../../../types/api-output'.
src/web/app/components/question-submission-form/recipient-type-name.pipe.ts(2,41
): error TS2307: Cannot find module '../../../types/api-output'.
src/web/app/components/question-text-with-info/question-text-with-info.component
.ts(2,63): error TS2307: Cannot find module '../../../types/api-output'.
src/web/app/components/question-types/question-additional-info/constsum-question
-additional-info.component.ts(2,52): error TS2307: Cannot find module '../../../
../types/api-output'.
src/web/app/components/question-types/question-additional-info/contribution-ques
tion-additional-info.component.ts(2,53): error TS2307: Cannot find module '../..
/../../types/api-output'.
src/web/app/components/question-types/question-additional-info/mcq-question-addi
tional-info.component.ts(5,8): error TS2307: Cannot find module '../../../../typ
es/api-output'.
src/web/app/components/question-types/question-additional-info/msq-question-addi
tional-info.component.ts(5,8): error TS2307: Cannot find module '../../../../typ
es/api-output'.
src/web/app/components/question-types/question-additional-info/num-scale-questio
n-additional-info.component.ts(2,55): error TS2307: Cannot find module '../../..
/../types/api-output'.
src/web/app/components/question-types/question-additional-info/question-addition
al-info.ts(2,41): error TS2307: Cannot find module '../../../../types/api-output
'.
src/web/app/components/question-types/question-additional-info/rank-options-ques
tion-additional-info.component.ts(2,52): error TS2307: Cannot find module '../..
/../../types/api-output'.
src/web/app/components/question-types/question-additional-info/rank-recipients-q
uestion-additional-info.component.ts(2,55): error TS2307: Cannot find module '..
/../../../types/api-output'.
src/web/app/components/question-types/question-additional-info/rubric-question-a
dditional-info.component.ts(2,47): error TS2307: Cannot find module '../../../..
/types/api-output'.
src/web/app/components/question-types/question-additional-info/text-question-add
itional-info.component.ts(2,45): error TS2307: Cannot find module '../../../../t
ypes/api-output'.
src/web/app/components/question-types/question-edit-answer-form/contribution-que
stion-edit-answer-form.component.ts(6,8): error TS2307: Cannot find module '../.
./../../types/api-output'.
src/web/app/components/question-types/question-edit-answer-form/mcq-question-edi
t-answer-form.component.ts(6,8): error TS2307: Cannot find module '../../../../t
ypes/api-output'.
src/web/app/components/question-types/question-edit-answer-form/msq-question-edi
t-answer-form.component.ts(5,8): error TS2307: Cannot find module '../../../../t
ypes/api-output'.
src/web/app/components/question-types/question-edit-answer-form/num-scale-questi
on-edit-answer-form.component.ts(6,8): error TS2307: Cannot find module '../../.
./../types/api-output'.
src/web/app/components/question-types/question-edit-answer-form/question-edit-an
swer-form.ts(2,66): error TS2307: Cannot find module '../../../../types/api-outp
ut'.
src/web/app/components/question-types/question-edit-answer-form/rank-options-que
stion-edit-answer-form.component.ts(2,88): error TS2307: Cannot find module '../
../../../types/api-output'.
src/web/app/components/question-types/question-edit-answer-form/text-question-ed
it-answer-form.component.ts(6,8): error TS2307: Cannot find module '../../../../
types/api-output'.
src/web/app/components/question-types/question-edit-details-form/contribution-qu
estion-edit-details-form.component.ts(2,53): error TS2307: Cannot find module '.
./../../../types/api-output'.
src/web/app/components/question-types/question-edit-details-form/mcq-question-ed
it-details-form.component.ts(6,8): error TS2307: Cannot find module '../../../..
/types/api-output'.
src/web/app/components/question-types/question-edit-details-form/msq-question-ed
it-details-form.component.ts(3,69): error TS2307: Cannot find module '../../../.
./types/api-output'.
src/web/app/components/question-types/question-edit-details-form/num-scale-quest
ion-edit-details-form.component.ts(2,55): error TS2307: Cannot find module '../.
./../../types/api-output'.
src/web/app/components/question-types/question-edit-details-form/question-edit-d
etails-form.component.ts(2,41): error TS2307: Cannot find module '../../../../ty
pes/api-output'.
src/web/app/components/question-types/question-edit-details-form/rank-options-qu
estion-edit-details-form.component.ts(3,52): error TS2307: Cannot find module '.
./../../../types/api-output'.
src/web/app/components/question-types/question-edit-details-form/text-question-e
dit-details-form.component.ts(2,45): error TS2307: Cannot find module '../../../
../types/api-output'.
src/web/app/components/question-types/question-instruction/rank-options-question
-instruction.component.ts(2,52): error TS2307: Cannot find module '../../../../t
ypes/api-output'.
src/web/app/components/question-types/question-response/constsum-question-respon
se.component.ts(5,8): error TS2307: Cannot find module '../../../../types/api-ou
tput'.
src/web/app/components/question-types/question-response/contribution-question-re
sponse.component.ts(5,8): error TS2307: Cannot find module '../../../../types/ap
i-output'.
src/web/app/components/question-types/question-response/mcq-question-response.co
mponent.ts(5,8): error TS2307: Cannot find module '../../../../types/api-output'
.
src/web/app/components/question-types/question-response/msq-question-response.co
mponent.ts(5,8): error TS2307: Cannot find module '../../../../types/api-output'
.
src/web/app/components/question-types/question-response/num-scale-question-respo
nse.component.ts(5,8): error TS2307: Cannot find module '../../../../types/api-o
utput'.
src/web/app/components/question-types/question-response/question-response.ts(2,6
6): error TS2307: Cannot find module '../../../../types/api-output'.
src/web/app/components/question-types/question-response/rank-options-question-re
sponse.component.ts(5,8): error TS2307: Cannot find module '../../../../types/ap
i-output'.
src/web/app/components/question-types/question-response/rank-recipients-question
-response.component.ts(5,8): error TS2307: Cannot find module '../../../../types
/api-output'.
src/web/app/components/question-types/question-response/rubric-question-response
.component.ts(5,8): error TS2307: Cannot find module '../../../../types/api-outp
ut'.
src/web/app/components/question-types/question-response/text-question-response.c
omponent.ts(5,8): error TS2307: Cannot find module '../../../../types/api-output
'.
src/web/app/components/session-edit-form/session-edit-form-model.ts(8,8): error
TS2307: Cannot find module '../../../types/api-output'.
src/web/app/components/session-edit-form/session-edit-form.component.ts(12,8): e
rror TS2307: Cannot find module '../../../types/api-output'.
src/web/app/components/session-edit-form/submission-status-name.pipe.ts(2,49): e
rror TS2307: Cannot find module '../../../types/api-output'.
src/web/app/components/sessions-table/publish-status-tooltip.pipe.ts(2,46): erro
r TS2307: Cannot find module '../../../types/api-output'.
src/web/app/components/sessions-table/resend-results-link-to-student-modal/resen
d-results-link-to-student-modal.component.ts(5,53): error TS2307: Cannot find mo
dule '../../../../types/api-request'.
src/web/app/components/sessions-table/send-reminders-to-student-modal/send-remin
ders-to-student-modal.component.ts(5,53): error TS2307: Cannot find module '../.
./../../types/api-request'.
src/web/app/components/sessions-table/sessions-table-model.ts(1,86): error TS230
7: Cannot find module '../../../types/api-output'.
src/web/app/components/sessions-table/sessions-table.component.ts(3,87): error T
S2307: Cannot find module '../../../types/api-output'.
src/web/app/components/sessions-table/sessions-table.component.ts(4,53): error T
S2307: Cannot find module '../../../types/api-request'.
src/web/app/components/sessions-table/student-list-info-base-modal.component.ts(
3,81): error TS2307: Cannot find module '../../../types/api-output'.
src/web/app/components/sessions-table/student-list-info-base-modal.component.ts(
4,53): error TS2307: Cannot find module '../../../types/api-request'.
src/web/app/components/sessions-table/submission-status-tooltip.pipe.ts(2,49): e
rror TS2307: Cannot find module '../../../types/api-output'.
src/web/app/components/teammates-common/publish-status-name.pipe.ts(2,46): error
 TS2307: Cannot find module '../../../types/api-output'.
src/web/app/components/teammates-common/question-type-name.pipe.ts(2,38): error
TS2307: Cannot find module '../../../types/api-output'.
src/web/app/components/teammates-common/submission-status-name.pipe.ts(2,49): er
ror TS2307: Cannot find module '../../../types/api-output'.
src/web/app/components/visibility-messages/visibility-entity-name.pipe.ts(6,8):
error TS2307: Cannot find module '../../../types/api-output'.
src/web/app/error-message-output.ts(1,31): error TS2307: Cannot find module '../
types/api-output'.
src/web/app/pages-admin/admin-home-page/admin-home-page.component.ts(3,26): erro
r TS2307: Cannot find module '../../../types/api-output'.
src/web/app/pages-admin/admin-page.component.ts(6,26): error TS2307: Cannot find
 module '../../types/api-output'.
src/web/app/pages-admin/admin-search-page/admin-search-page.component.ts(5,37):
error TS2307: Cannot find module '../../../types/api-output'.
src/web/app/pages-admin/admin-sessions-page/admin-sessions-page.component.ts(7,7
1): error TS2307: Cannot find module '../../../types/api-output'.
src/web/app/pages-admin/admin-timezone-page/admin-timezone-page.component.ts(4,2
7): error TS2307: Cannot find module '../../../types/api-output'.
src/web/app/pages-help/session-links-recovery/session-links-recovery-page.compon
ent.ts(7,46): error TS2307: Cannot find module '../../../types/api-output'.
src/web/app/pages-instructor/instructor-course-details-page/instructor-course-de
tails-page.component.ts(10,31): error TS2307: Cannot find module '../../../types
/api-output'.
src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-
page.component.ts(13,39): error TS2307: Cannot find module '../../../types/api-o
utput'.
src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-
page.component.ts(14,41): error TS2307: Cannot find module '../../../types/api-r
equest'.
src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enr
oll-page.component.ts(6,30): error TS2307: Cannot find module '../../../types/ap
i-output'.
src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-cour
se-student-edit-page.component.ts(8,31): error TS2307: Cannot find module '../..
/../types/api-output'.
src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-cour
se-student-edit-page.component.ts(9,38): error TS2307: Cannot find module '../..
/../types/api-request'.
src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-
form.component.ts(7,24): error TS2307: Cannot find module '../../../../types/api
-output'.
src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.com
ponent.ts(9,84): error TS2307: Cannot find module '../../../types/api-output'.
src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component
.ts(18,8): error TS2307: Cannot find module '../../../types/api-output'.
src/web/app/pages-instructor/instructor-page.component.ts(5,26): error TS2307: C
annot find module '../../types/api-output'.
src/web/app/pages-instructor/instructor-session-base-page.component.ts(15,8): er
ror TS2307: Cannot find module '../../types/api-output'.
src/web/app/pages-instructor/instructor-session-base-page.component.ts(16,53): e
rror TS2307: Cannot find module '../../types/api-request'.
src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-ot
her-sessions-modal/copy-questions-from-other-sessions-modal-model.ts(1,34): erro
r TS2307: Cannot find module '../../../../types/api-output'.
src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-ot
her-sessions-modal/copy-questions-from-other-sessions-modal.component.ts(3,34):
error TS2307: Cannot find module '../../../../types/api-output'.
src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edi
t-page.component.ts(28,8): error TS2307: Cannot find module '../../../types/api-
output'.
src/web/app/pages-instructor/instructor-session-edit-page/template-question-moda
l/template-question-modal.component.ts(4,34): error TS2307: Cannot find module '
../../../../types/api-output'.
src/web/app/pages-instructor/instructor-session-result-page/instructor-session-r
esult-page.component.ts(10,8): error TS2307: Cannot find module '../../../types/
api-output'.
src/web/app/pages-instructor/instructor-sessions-page/copy-from-other-sessions-m
odal/copy-from-other-sessions-modal-model.ts(1,33): error TS2307: Cannot find mo
dule '../../../../types/api-output'.
src/web/app/pages-instructor/instructor-sessions-page/copy-from-other-sessions-m
odal/copy-from-other-sessions-modal.component.ts(3,41): error TS2307: Cannot fin
d module '../../../../types/api-output'.
src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.c
omponent.ts(26,8): error TS2307: Cannot find module '../../../types/api-output'.

src/web/app/pages-instructor/instructor-sessions-page/sessions-permanent-deletio
n-confirm-modal/sessions-permanent-deletion-confirm-modal.component.ts(3,33): er
ror TS2307: Cannot find module '../../../../types/api-output'.
src/web/app/pages-instructor/student-list/student-list.component.ts(9,31): error
 TS2307: Cannot find module '../../../types/api-output'.
src/web/app/pages-session/session-result-page/session-result-page.component.ts(1
1,8): error TS2307: Cannot find module '../../../types/api-output'.
src/web/app/pages-session/session-submission-page/session-submission-page.compon
ent.ts(22,8): error TS2307: Cannot find module '../../../types/api-output'.
src/web/app/pages-static/static-page.component.ts(4,26): error TS2307: Cannot fi
nd module '../../types/api-output'.
src/web/app/pages-student/student-page.component.ts(5,26): error TS2307: Cannot
find module '../../types/api-output'.
src/web/app/pages-student/student-profile-page/student-profile-page.component.ts
(9,72): error TS2307: Cannot find module '../../../types/api-output'.
src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal
/upload-edit-profile-picture-modal.component.ts(10,46): error TS2307: Cannot fin
d module '../../../../types/api-output'.
src/web/app/user-join-page.component.ts(6,28): error TS2307: Cannot find module
'../types/api-output'.
src/web/environments/environment.prod.ts(1,24): error TS2307: Cannot find module
 './config'.
src/web/environments/environment.ts(1,24): error TS2307: Cannot find module './c
onfig'.
src/web/services/account.service.ts(3,60): error TS2307: Cannot find module '../
types/api-output'.
src/web/services/account.service.ts(4,38): error TS2307: Cannot find module '../
types/api-request'.
src/web/services/course.service.ts(3,80): error TS2307: Cannot find module '../t
ypes/api-output'.
src/web/services/course.service.ts(4,80): error TS2307: Cannot find module '../t
ypes/api-request'.
src/web/services/feedback-questions.service.ts(13,8): error TS2307: Cannot find
module '../types/api-output'.
src/web/services/feedback-questions.service.ts(14,78): error TS2307: Cannot find
 module '../types/api-request'.
src/web/services/feedback-responses.service.ts(12,8): error TS2307: Cannot find
module '../types/api-output'.
src/web/services/feedback-responses.service.ts(13,78): error TS2307: Cannot find
 module '../types/api-request'.
src/web/services/feedback-sessions.service.ts(5,58): error TS2307: Cannot find m
odule '../types/api-output'.
src/web/services/feedback-sessions.service.ts(6,76): error TS2307: Cannot find m
odule '../types/api-request'.
src/web/services/student-profile.service.ts(3,47): error TS2307: Cannot find mod
ule '../types/api-output'.
src/web/services/student-profile.service.ts(4,45): error TS2307: Cannot find mod
ule '../types/api-request'.
src/web/services/student.service.ts(3,26): error TS2307: Cannot find module '../
types/api-output'.
src/web/services/timezone.service.ts(8,65): error TS2307: Cannot find module '..
/types/api-output'.
src/web/services/visibility-state-machine.ts(1,65): error TS2307: Cannot find mo
dule '../types/api-output'.
src/web/types/default-question-structs.ts(23,8): error TS2307: Cannot find modul
e './api-output'.
src/web/types/instructor-privilege.ts(1,37): error TS2307: Cannot find module '.
/api-output'.

**Comment by tanhengyeow** [comment]
@HarikumarG Have you run `./gradlew generateTypes`. You can refer to this [section](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#managing-the-dev-server-front-end) of the docs to read up more on it :)

**Comment by HarikumarG** [comment]
Thanks @tanhengyeow  But i got another error . I have searched in google but couldn't able to solve . I can't able to understand what exactly i have to configue . Kindly please help me . 

C:\Angular\teammates>gradlew appengineStart
> Task :appengineStart FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':appengineStart'.
> The Google Cloud SDK could not be found in the customary locations and no path
 was provided.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
5 actionable tasks: 1 executed, 4 up-to-date

**Comment by tanhengyeow** [comment]
@HarikumarG Have you looked through the setup guide? Based on the information you provided, the issue might be your environment not recognizing Google Cloud SDK, which was stated in this [step](https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md#step-2-install-necessary-tools-and-languages) of the setup guide.

**Comment by tanhengyeow** [comment]
I would recommend reading the [Contribution Guidelines](https://github.com/TEAMMATES/teammates/blob/master/docs/CONTRIBUTING.md) in detail and if there are any steps that are unclear, feel free to sound out to the community 😄

**Comment by HarikumarG** [comment]
Again thanks brother. But i still struggling with my setup . I have read the setup guide and in step 2 , I had java already and python 3.7 now i have changed to python 2.7 and while installing .bat file i am getting this error . 

C:\Users\Harikumar G\Downloads\Google cloud sdk\google-cloud-sdk>install.bat --p
ath-update true
Welcome to the Google Cloud SDK!
ERROR: gcloud failed to load: Error when calling the metaclass bases
    Cannot create a consistent method resolution
order (MRO) for bases MutableMapping, CommentedBase, ordereddict
    gcloud_main = _import_gcloud_main()
    import googlecloudsdk.gcloud_main
    from googlecloudsdk.calliope import base
    from googlecloudsdk.calliope import display
    from googlecloudsdk.core.resource import resource_printer
    from googlecloudsdk.core.resource import yaml_printer
    from googlecloudsdk.core.yaml import dict_like
    from googlecloudsdk.core import yaml_location_value
    from ruamel import yaml
    from ruamel.yaml.main import *  # NOQA
    from ruamel.yaml.loader import BaseLoader, SafeLoader, Loader, RoundTripLoad
er  # NOQA
    from ruamel.yaml.constructor import (
    from ruamel.yaml.comments import *                               # NOQA
    class CommentedMap(MutableMapping, ordereddict, CommentedBase):
    cls = super(ABCMeta, mcls).__new__(mcls, name, bases, namespace)
    Cannot create a consistent method resolution

This usually indicates corruption in your gcloud installation or problems with y
our Python interpreter.

Please verify that the following is the path to a working Python 2.7 executable:

    C:\Python27\python.exe

If it is not, please set the CLOUDSDK_PYTHON environment variable to point to a
working Python 2.7 executable.

If you are still experiencing problems, please reinstall the Cloud SDK using the
 instructions here:
    https://cloud.google.com/sdk/
Traceback (most recent call last):
  File "C:\Users\Harikumar G\Downloads\Google cloud sdk\google-cloud-sdk\\bin\bo
otstrapping\install.py", line 12, in <module>
    import bootstrapping
  File "C:\Users\Harikumar G\Downloads\Google cloud sdk\google-cloud-sdk\bin\boo
tstrapping\bootstrapping.py", line 46, in <module>
    from googlecloudsdk.core.updater import update_manager
  File "C:\Users\Harikumar G\Downloads\Google cloud sdk\google-cloud-sdk\lib\goo
glecloudsdk\core\updater\update_manager.py", line 35, in <module>
    from googlecloudsdk.core import yaml
  File "C:\Users\Harikumar G\Downloads\Google cloud sdk\google-cloud-sdk\lib\goo
glecloudsdk\core\yaml.py", line 29, in <module>
    from googlecloudsdk.core import yaml_location_value
  File "C:\Users\Harikumar G\Downloads\Google cloud sdk\google-cloud-sdk\lib\goo
glecloudsdk\core\yaml_location_value.py", line 39, in <module>
    from ruamel import yaml
  File "C:\Users\Harikumar G\Downloads\Google cloud sdk\google-cloud-sdk\lib\thi
rd_party\ruamel\yaml\__init__.py", line 85, in <module>
    from ruamel.yaml.main import *  # NOQA
  File "C:\Users\Harikumar G\Downloads\Google cloud sdk\google-cloud-sdk\lib\thi
rd_party\ruamel\yaml\main.py", line 19, in <module>
    from ruamel.yaml.loader import BaseLoader, SafeLoader, Loader, RoundTripLoad
er  # NOQA
  File "C:\Users\Harikumar G\Downloads\Google cloud sdk\google-cloud-sdk\lib\thi
rd_party\ruamel\yaml\loader.py", line 10, in <module>
    from ruamel.yaml.constructor import (
  File "C:\Users\Harikumar G\Downloads\Google cloud sdk\google-cloud-sdk\lib\thi
rd_party\ruamel\yaml\constructor.py", line 21, in <module>
    from ruamel.yaml.comments import *                               # NOQA
  File "C:\Users\Harikumar G\Downloads\Google cloud sdk\google-cloud-sdk\lib\thi
rd_party\ruamel\yaml\comments.py", line 642, in <module>
    class CommentedMap(MutableMapping, ordereddict, CommentedBase):
  File "C:\Python27\lib\abc.py", line 86, in __new__
    cls = super(ABCMeta, mcls).__new__(mcls, name, bases, namespace)
TypeError: Error when calling the metaclass bases
    Cannot create a consistent method resolution
order (MRO) for bases MutableMapping, ordereddict, CommentedBase
