### ISSUE TITLE
Resolve TinyMCE conflicts with Snapshot tests

### ISSUE THREAD

**Issue by AyushChatto** [TEAMMATES/teammates#9688]
Currently, the tinyMCE library generates an `id="tiny-angular_<insert number>` here each time the snapshot test runs, with the number being changed each time. This, of course, makes the snapshot tests useless, since the test checks for consistency between the original and the generated snapshot. We need to explore options that will allow tinyMCE to still be tested via snapshot tests, or find alternatives.

**Comment by dvrylc** [comment]
I believe this issue can be closed, following the implementation I documented in https://github.com/TEAMMATES/teammates/pull/9910#issuecomment-574006203.

**Comment by xpdavid** [comment]
Yup, but it looks like we can move one step further to generalize the setup to an export. https://stackoverflow.com/questions/56171685/export-beforeall-and-afterall-in-jest

**Comment by dvrylc** [comment]
@xpdavid I can't seem to find a good place for the helper, is it ok to create a new directory `src/web/test-helpers`?
