### ISSUE TITLE
Instructor: resend links to specific students: fails for large classes

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9693]
V6 (but may be applicable to V7 too)

![image](https://user-images.githubusercontent.com/1673303/56550341-eceebc00-65b7-11e9-9f65-97490681099c.png)

This feature fails if the instructor tries to resend reminders to a large number of students.

Possibly the request length exceeds the permissible length for a http request?

**Comment by wkurniawan07** [comment]
In which stage does it fail, e.g. does even clicking the button cause something wrong, or it happens only when the students are already selected and the reminders (supposedly) sent?

**Comment by damithc** [comment]
> In which stage does it fail, e.g. does even clicking the button cause something wrong, or it happens only when the students are already selected and the reminders (supposedly) sent?

At the second stage.

**Comment by wkurniawan07** [comment]
The second stage is resolved in V7 for sure.

**Comment by damithc** [comment]
> The second stage is resolved in V7 for sure.

Great to hear that. Closing.
