### ISSUE TITLE
Instructor: enroll students: loading existing students doesn't work in masquerade mode

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9694]
V6

![image](https://user-images.githubusercontent.com/1673303/56550758-1bb96200-65b9-11e9-878f-be08b70689d0.png)

Problem: loading existing students doesn't work in masquerade mode (i.e., admin masquerading as a user)

**Comment by swood049** [comment]
Hi, I am a college student studying software engineering, and for one of my classes I need to attempt a contribution for a bug on an open source project (I find this project extremely interesting). I have never made a pull request before, but I am very proficient in HTML, CSS, JavaScript, and Java (plus a little Angular). I have already set up my environment to the specifications listed in docs. May I give this one a go?

**Comment by swood049** [comment]
I have come across a roadblock: is there an simple way to replicate the error in the local environment?

**Comment by madanalogy** [comment]
> I have come across a roadblock: is there an simple way to replicate the error in the local environment? I am trying to access masquerade mode, but I am not certain what the username for any given instructor is.

You will likely need to create a course, then populate it with instructors. Doing this in the development environment is quite involved however. Additionally, just note that this is not a straightforward issue. Since it's your first time contributing to this project, I would recommend you take a look at the issues tagged as `good first issue` or `Hacktoberfest` currently.

**Comment by swood049** [comment]
> 
> You will likely need to create a course, then populate it with instructors. Doing this in the development environment is quite involved however. Additionally, just note that this is not a straightforward issue. Since it's your first time contributing to this project, I would recommend you take a look at the issues tagged as `good first issue` or `Hacktoberfest` currently.

Your recommendation is noted, and I will keep my eyes peeled for `good first issue` or `Hacktoberfest` that is not yet claimed, requested, or have an active pull request.

**Comment by swood049** [comment]
Upon investigation, I was able to create 2 different users, and use masquerade mode to solve this problem, but I cannot replicate it (see screenshot below). I have to assume that it was fixed somewhere between here and when this was first noted, and I suggest further investigation (hopefully closing the issue).
![image](https://user-images.githubusercontent.com/38500060/97865288-f7733100-1cd7-11eb-8ce9-6a300bbf7fbd.png)

**Comment by wkurniawan07** [comment]
Not valid anymore
