### ISSUE TITLE
Instructor: enroll students: Incorrect message when adding new students to a new course 

### ISSUE THREAD

**Issue by Pengyuz** [TEAMMATES/teammates#9703]
- **Environment**: `master` branch

**Steps to reproduce**
1. log in as an Instructor 
2. create a new course without students
3. go to course enroll page and click on "Existing Students" panel, it should show message "No Existing Student in course."
4. add one student to the course, and click on the "Existing Students" panel, the message doesn't disappear

**Expected behaviour**
Message "No Existing Student in course." should disappear when add new students in a new course.

**Actual behaviour**
![Screenshot 2019-05-21 at 11 39 12](https://user-images.githubusercontent.com/31039759/58066970-384bb880-7bbe-11e9-9601-992acefe2625.png)

**Comment by Adoby7** [comment]
Just a reminder, you can put the SHA-1 digest in the "environment" to indicate the problem present up to which commit
