### ISSUE TITLE
Student: Upload/Edit Photo: Confusing error message shown when uploading empty photo

### ISSUE THREAD

**Issue by crizyli** [TEAMMATES/teammates#9704]
- **Environment**: `master` branch

**Steps to reproduce**
1. log in as a student
2. go to the profile page
3. click Delete Photo if there is an existing photo
4. click Upload/Edit Photo
5. do not choose any photo and click Upload Image

**Expected behaviour**
Show the user an understandable error message

**Actual behaviour**
![hunt](https://user-images.githubusercontent.com/28641908/58066816-857b5a80-7bbd-11e9-97ad-50723568e907.PNG)

**Comment by rrtheonlyone** [comment]
Hi there,

Thanks for pointing out this issue. I believe you need to add an additional check to make sure the profile photo itself is not empty before sending the request.

Would you like to work on this?

**Comment by crizyli** [comment]
> Hi there,
> 
> Thanks for pointing out this issue. I believe you need to add an additional check to make sure the profile photo itself is not empty before sending the request.
> 
> Would you like to work on this?

Sure, I am going to work on that.
