### ISSUE TITLE
Rich text box: Unable to put text box in focus when clicked anywhere but the top-most line of the box

### ISSUE THREAD

**Issue by erjillsison** [TEAMMATES/teammates#9705]
![click](https://user-images.githubusercontent.com/22665593/58068040-4a2f5a80-7bc2-11e9-8e3f-d5aee2546848.gif)

- **Environment**: 
`master` branch at commit 18040a23ac6a5db5c0a251a7a0d7bfb19db468fb

**Steps to reproduce**
1. Go to any rich text box e.g in an essay type question of a feedback session.
2. Click the bottom part of the box

**Expected behaviour**
The text box is in focus and user is able to input text. User should be able to click anywhere within the box.

**Actual behaviour**
Text box is not in focus. To put the text box in focus, the user has to click the top-most line of the box.

**Comment by xpdavid** [comment]
@erjillsison I am in charge of migrating rich-text editor in the V6 migration. I also noticed this problem when migrating while there is no easy solution to me at that time.
