### ISSUE TITLE
Add New Feedback Session: Default selected course ID in the form is incorrect

### ISSUE THREAD

**Issue by erjillsison** [TEAMMATES/teammates#9707]
- **Environment**: 
`master` branch at commit 18040a23ac6a5db5c0a251a7a0d7bfb19db468fb

**Steps to reproduce**

1. Log in as instructor
2. Under any course header that is not the first, click **Sessions** then **Add**
![image](https://user-images.githubusercontent.com/22665593/58069489-fd4e8280-7bc7-11e9-8f66-90749997ae3e.png)

3. The selected course ID defaults to the first course.
![image](https://user-images.githubusercontent.com/22665593/58069538-266f1300-7bc8-11e9-8b40-be4b167f763e.png)

**Expected behaviour**
The selected course ID should be the same as where the **Sessions** button was clicked from.

**Actual behaviour**
The selected course ID defaults to the first course alphabetically.

**Comment by Raul9595** [comment]
Can I work on this ?

**Comment by xpdavid** [comment]
@Raul9595 I have assigned this issue to @erjillsison. Can you find other FirstTimer issues to work on?
