### ISSUE TITLE
Resolve console warning raised by TinyMCE

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9720]
- **Environment**: a49c676224611d7a83baf87711e41a5f1002b70b

**Steps to reproduce**
Visit any page that use TinyMCE.

**Expected behaviour**
No warning in console.

**Actual behaviour**
![image](https://user-images.githubusercontent.com/13977235/58383796-65a8c400-800d-11e9-91cc-78454da956fa.png)

**Additional info**
We recently upgraded the TinyMCE plugin. This should be the follow-up of the upgrade.

**Comment by RonMosenzon** [comment]
Hi, I am new to opensource and I want to give it a shot. Can I try this?
