### ISSUE TITLE
Help Request:[  Error while managing the dev-server] > com.google.cloud.tools.appengine.cloudsdk.internal.process.ProcessRunnerException: Timed out waiting for the success message: '.*(Dev App Server is now running|INFO:oejs\.Server:main: Started).*'

### ISSUE THREAD

**Issue by Adibhat108** [TEAMMATES/teammates#9729]
Followed all steps in for setting up dev-environment and eclipse IDE.
`E:\files\projects\TEAMMATES>gradlew appengineStart
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.4.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Task :appengineStart
May 29, 2019 11:27:11 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
May 29, 2019 11:27:15 AM com.google.appengine.tools.development.SystemPropertiesManager setSystemProperties
INFO: Overwriting system property key 'java.util.logging.config.file', value 'C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\java\config\sdk\logging.properties' with value 'WEB-INF/logging.properties' from 'E:\files\projects\TEAMMATES\build\exploded-TEAMMATES\WEB-INF\appengine-web.xml'
2019-05-29 11:27:15.455:INFO::main: Logging initialized @4800ms to org.eclipse.jetty.util.log.StdErrLog
2019-05-29 11:27:15.516:WARN:oejs.AbstractConnector:main: Ignoring deprecated socket close linger time
2019-05-29 11:27:17.602:INFO:oejs.Server:main: jetty-9.4.14.v20181114; built: 2018-11-14T21:20:31.478Z; git: c4550056e785fb5665914545889f21dc136ad9e6; jvm 1.8.0_144-b01

> Task :appengineStart FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':appengineStart'.
> com.google.cloud.tools.appengine.cloudsdk.internal.process.ProcessRunnerException: Timed out waiting for the success message: '.*(Dev App Server is now running|INFO:oejs\.Server:main: Started).*'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 42s
5 actionable tasks: 1 executed, 4 up-to-date

E:\files\projects\TEAMMATES>
E:\files\projects\TEAMMATES>`

**Comment by xpdavid** [comment]
Probability issue with JVM/Gradle/OS as shown in the message `Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.`

**Comment by JimGalvan** [comment]
I am getting the same issue..
