### ISSUE TITLE
Student Enroll: Error when enrolling students with empty Section Name

### ISSUE THREAD

**Issue by erjillsison** [TEAMMATES/teammates#9730]
- **Environment**: 
`master` branch at commit 5eff2f4d0819f8910f95f8da04ca2d60b1eb0bb4

**Steps to reproduce**
1. Go to /web/instructor/courses/enroll?courseid=ANY_VALID_COURSE_ID
2. Try to add a student with valid input under **Team**, **Name** and **Email** but leave the **Section** empty.
3. Observe the error message.
![longmessage](https://user-images.githubusercontent.com/22665593/58540852-c82bdb00-822c-11e9-9703-530dcfac7d76.png)

**Expected behaviour**
Since the error message states that **Section** and **Comments** are optional, either enrollment should have succeeded or error message should not mention that **Section** is optional.

**Actual behaviour**
An error message will be shown and the student will not be enrolled.

**Additional info**
![error](https://user-images.githubusercontent.com/22665593/58541285-bb5bb700-822d-11e9-8b62-b1ee9ae2ecc0.gif)

**Comment by Adoby7** [comment]
Thanks for spotting the bug @erjillsison . Yes, the specification is that `Section` is an optional field. The solution is that a default section name should be provided if section is empty, refer to the constructor of `StudentAttributes`. 
![image](https://user-images.githubusercontent.com/25312978/58551094-e0f2bb80-8241-11e9-83de-328746c88e14.png) However, the same abstraction should also be done in database layer of student, and that's the solution of this issue.
