### ISSUE TITLE
Feedback Session Edit: Common feedback paths in the drop down list not clickable

### ISSUE THREAD

**Issue by crizyli** [TEAMMATES/teammates#9732]
- **Environment**: `master` branch at commit [5eff2f4](https://github.com/TEAMMATES/teammates/commit/5eff2f4d0819f8910f95f8da04ca2d60b1eb0bb4)

**Steps to reproduce**
1. go to any feedback session edit page and edit one question
2. in the Feedback Path section, click the drop-down list and click the common feedback path combinations options

**Expected behaviour**
The options in the drop-down list should be clickable and the feedback path is set to that clicked option

**Actual behaviour**
The options are not clickable

**Additional info**
Also, there are some display issues. 
In Feedback Path section, it shows `Custom Visibility Options` after selecting `Other predefined combinations...` in the drop-down
In the Visibility section, the drop-down list title is the same as that in Feedback Path section

**Comment by xpdavid** [comment]
#9721 will fix this. @crizyli Can you confirm?

**Comment by crizyli** [comment]
Yes, #9721 fixed this issue, except the improper display names

**Comment by xpdavid** [comment]
> In the Visibility section, the drop-down list title is the same as that in Feedback Path section

So you are saying after `Other predefined combinations...`, what is the expected behaviour?

**Comment by crizyli** [comment]
![Capture](https://user-images.githubusercontent.com/28641908/58858534-49c2b380-86da-11e9-9b7d-1351a8d52d94.PNG)
As shown in the snapshot, the two red underlined should be something like `Custom Feedback Path` and `Custom Visibility Options` respectively.

**Comment by xpdavid** [comment]
Fixed in #9721
