### ISSUE TITLE
Instructor: Courses/Enroll: Unable to update Section name of student

### ISSUE THREAD

**Issue by erjillsison** [TEAMMATES/teammates#9747]
- **Environment**: 

`master` branch at commit 1302ea06ea723385d310e4d844bab669cd931859

**Steps to reproduce**
1. Navigate to /instructor/courses/enroll?courseid=ANY_VALID_COURSE_ID
2. Ensure that it has at least one student and their **Team** name is **unique** in the course. e.g:

Section | Team | Name | Email
-- | -- | -- | --
A | Team 1 | Some name | Email@email.com

3. In the enroll page, under **New Students**, try to modify the existing student's section name. e.g:

Section | Team | Name | Email
-- | -- | -- | --
B | Team 1 | Some name | Email@email.com

**Expected behaviour**
The student's section name will be updated to "B".

**Actual behaviour**
Observe the error message below. This should not be an error because sections A and B do not exist concurrently and what we're trying to do here is to transfer Team 1 from section A to B.
![image](https://user-images.githubusercontent.com/22665593/59012742-df8d4880-886a-11e9-96c3-daa56d0014a8.png).

**Additional info**
Editing the section name through the **Edit Student Details** page works unlike the above.

**Comment by TheDheeraj007** [comment]
Hello, first timer here. Can I work on this issue?

**Comment by erjillsison** [comment]
@TheDheeraj007 Hello! Unfortunately, there is already a PR for this issue. You can try working on an issue labelled as `d.FirstTimers`
