### ISSUE TITLE
Improve upon status messages (snackbars)

### ISSUE THREAD

**Issue by erjillsison** [TEAMMATES/teammates#9748]
- **Environment**: 
`master` branch at commit 1302ea06ea723385d310e4d844bab669cd931859

**Description of enhancement**
- ~~Status messages (can be success, warning or error messages) should be displayed longer.~~
- ~~The snackbars should be dismissible i.e add a dismiss button.~~
- ~~Multiple snackbars should be stackable and not replace the currently displayed one.~~

After reading up a bit more, the above suggestions are NOT ideal.
See https://material.io/design/components/snackbars.html#.

Error and warning messages that are lengthy (examples below) should instead be displayed as a dialog that are persistent until dismissed.

**Justification**
- Error messages such as the one below take too long to read and will disappear before reading through everything.
![image](https://user-images.githubusercontent.com/22665593/59013893-cb971600-886d-11e9-95d9-cf4c534798a2.png)

- A warning message like the one below HAS to be read before the user should be able to continue.
![image](https://user-images.githubusercontent.com/22665593/59042550-3a479400-88ad-11e9-8c05-0eab92b9c6a6.png)

**Comment by cbhhargava** [comment]
Banners are an option. But having different behaviors just based on length doesn't seem that consistent. Need to have well defined label or factor to justify it. I'm new to the project and was just going through open issues.

**Comment by xpdavid** [comment]
I don't think the issue is from the style of the status message itself. For example,

> A warning message like the one below HAS to be read before the user should be able to continue.

One should use a modal instead of a status message.
