### ISSUE TITLE
Enroll Students Page: Duplicate Empty list item in error when same email exists

### ISSUE THREAD

**Issue by pollysobeck** [TEAMMATES/teammates#9756]
When adding students via the new students spreadsheet on the enroll students page, an error occurs when more than one student in the list has the same email address. This error contains an extra list bullet item with no text in it (see screenshot under Actual Behavior)

 **Environment**: Live Server V6.16.2

**Steps to reproduce**
1. Log in as an Instructor
2. Find an active class and click on Enroll Button to enroll students for the course
3. Add more than one student with different information other than the email (i.e. email should be same for more than one student)
4. Observe Error that multiple students have same email address - there will be an extra bullet point

**Expected behaviour**
![image](https://user-images.githubusercontent.com/26610793/59152691-3d05ce80-89fe-11e9-8f71-fc079c5db1ef.png)

**Actual behaviour**
![image](https://user-images.githubusercontent.com/26610793/59152710-81916a00-89fe-11e9-9cf4-3f67fe346c5c.png)

**Comment by xpdavid** [comment]
I believe the UI will be changed in V7.

**Comment by wkurniawan07** [comment]
Fixed in V7
