### ISSUE TITLE
Feedback Session Edit: Feedback path not set correctly using 'Other predefined combinations'

### ISSUE THREAD

**Issue by crizyli** [TEAMMATES/teammates#9758]
- **Environment**: `master` branch at commit 4346f6f3d5ef8bf9570ab088a9835709f13ca99f.

**Steps to reproduce**
1. log in as an instructor and go to session page
2. edit a session and add a new question in it
3. for `Feedback Path` section, choose `Other predefined combinations...`. under `Who will give the feedback:`, change to `instructors in this course` and observe that `Who the feedback is about:` changes to `Giver (Self feedback)`, do not edit this field and
4. click `Save Changes`

**Expected behaviour**
feedback path should be set to `instructors in this course` will five feedbacks to `Giver (Self feedback)`

**Actual behaviour**
The feedback path is not set correctly, can verify it by previewing as one instructor and observe the question added not shown.

**Additional info**
This is due to the type for the recipient is not updated as giver type changes.

**Comment by xpdavid** [comment]
Your fix takes care of the situation where `giverType` makes `recipientType` invalid. Is it possible that `recipientType` can make `giverType` invalid?

**Comment by crizyli** [comment]
I think it is not, since the default giverType is student and it has all
kinds of recipientTypes, change the recipientType will not make giverType
invalid.

Xiao Pu <notifications@github.com>于2019年6月13日 周四下午2:22写道：
