### ISSUE TITLE
Feedback Session Edit: Button names should be more appropriate

### ISSUE THREAD

**Issue by crizyli** [TEAMMATES/teammates#9761]
- **Environment**: `master` branch

In the feedback session question edit page,
![Capture](https://user-images.githubusercontent.com/28641908/59175820-833b6900-8b89-11e9-8e07-ecfd75b33976.PNG)

As shown in the snapshot, the three red underlined should be something more appropriate like Custom Feedback Path, Custom Visibility Options, and Other visibility options respectively.

**Comment by nidamunir** [comment]
Can I work on it?

**Comment by crizyli** [comment]
@nidamunir Sure. You can!

**Comment by josharsh** [comment]
Does this only require a change in UI?

**Comment by crizyli** [comment]
@josharsh Yes, it is.

**Comment by xpdavid** [comment]
Typo due copy-paste :P Can be easily fixed.

**Comment by mytemp1776** [comment]
Hey guys, i have fixed this but not able to push my branch to git. Getting the below permission error - 
```
remote: Permission to TEAMMATES/teammates.git denied to mytemp1776.
fatal: unable to access 'https://github.com/TEAMMATES/teammates.git/': The requested URL returned error: 403 
```
Can anyone help ? TIA

**Comment by xpdavid** [comment]
Hi @parvbansal , please follow https://github.com/TEAMMATES/teammates/blob/master/docs/process.md to send PR. You should not (and also does not have permission) to push to the main repo.

**Comment by parvbansal** [comment]
Thanks @xpdavid but i guess @dare892 has already raised a PR for this so i will find something else for my first open source contribution.

**Comment by dvrylc** [comment]
Hi there, seems like the previous PR was closed due to inactivity. Can I take this?
