### ISSUE TITLE
EmailSendingException in live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9762]
**Environment**: V6, live server

I'm seeing this error in our logs occasionally
>Error Message: teammates.common.util.Logger severe: Error while sending email via servlet: 
teammates.common.exception.EmailSendingException: Remote host closed connection during handshake
at teammates.logic.core.EmailSenderService.sendEmail(EmailSenderService.java:26)
at teammates.logic.api.EmailSender.sendEmail(EmailSender.java:42)
at teammates.ui.automated.SendEmailWorkerAction.execute(SendEmailWorkerAction.java:56)
at teammates.ui.automated.AutomatedServlet.doPost(AutomatedServlet.java:46)

How much damage is implied by this error? e.g., failed to send 1 email or many emails?
Is the damage permanent? e.g., is there a retry mechanism to compensate?

**Comment by damithc** [comment]
Another email related error I occasionally get:

>Error Message: teammates.common.util.Logger severe: Error while sending email via servlet: 
teammates.common.exception.EmailSendingException: Request returned status Code 504Body:
504
Ngnix - Gateway Timeout

**Comment by wkurniawan07** [comment]
- Those errors very likely (99% confidence) come from Sendgrid. As reliable as they are, they are not 100% foolproof.
- One of this report means one email failed to be sent
- The send email worker is configured for 5 times retry per email:
  https://github.com/TEAMMATES/teammates/blob/185145bc6f73a794c0248f7d44928db24f735d01/src/main/webapp/WEB-INF/queue.xml#L81-L93
