### ISSUE TITLE
Modals: Move modals to the center of the page

### ISSUE THREAD

**Issue by erjillsison** [TEAMMATES/teammates#9767]
- **Environment**: 

**Description of feature/enhancement**
Currently, modals are placed at the top of the page. As a side effect of a recent commit 2999868d97d357472742ff61032d1ab2db57ecee, a portion of a modal is blocked by the nav bar.
![image](https://user-images.githubusercontent.com/22665593/59259532-907d5400-8c6c-11e9-86ff-299bc00f1331.png)
Instead of fixing it by placing modals in front of the navbar, move the modal pop up to the vertical center of the page.

**Justification**
It's visually better to place modals at the center of the screen as it requires the user's full attention. For example, 
![image](https://user-images.githubusercontent.com/22665593/59259478-76437600-8c6c-11e9-9692-90c61e3a01be.png)

**Comment by emilvidmark** [comment]
Can I be assigned to this ticket? I would like to take a look at it :-)

**Comment by mitcheesta** [comment]
I'll work on this issue

**Comment by xpdavid** [comment]
@mitcheesta Note that there is already an ongoing PR to this issue.

**Comment by mitcheesta** [comment]
@xpdavid Okay thanks, I wasn't sure about the status of it.

**Comment by sivaranjanidev** [comment]
Does this issue is still open to work

**Comment by shahan27** [comment]
Please let me know if this is still open. I would gladly look into this. :)

**Comment by LeMikaelF** [comment]
The [relevant PR](https://github.com/TEAMMATES/teammates/pull/9768) has been pending for 8 months now, so... not sure what this means for first-timers...

**Comment by surili220** [comment]
Is this issue still open?
