### ISSUE TITLE
Student course detail page: Standardize picture size and title length

### ISSUE THREAD

**Issue by crizyli** [TEAMMATES/teammates#9773]
- **Environment**:  `master` branch at commit ad2d071317e2b1c70139daf43148219cf859f0db

**Steps to reproduce**
1. login as a student who has teammates, some teammates have their profile photo whose size is large
2. click the `View team` button in home page

**Actual behaviour**
![Captureccccccc](https://user-images.githubusercontent.com/28641908/59498636-63c57880-8ec8-11e9-9e17-192c4c19ff90.PNG)

**Expected behaviour**
the picture and title length should be standardized so that the details of students are aligned.

**Comment by Ajax-Light** [comment]
Hey, is this issue still open?

**Comment by Ajax-Light** [comment]
If so , I'd like to work on it

**Comment by NikhilPrasad0497** [comment]
Hi, i am just a beginner and i want to start contributing to Open source. will it be okay if i try this??

**Comment by hcwong** [comment]
Idm looking into this, but I'm not sure how to edit profile pic of other students on dev 🤣 ?  I only know how to edit it for the current student.
