### ISSUE TITLE
Student/Submission: Some question forms for cetain question types are not disabled when viewing a closed submission

### ISSUE THREAD

**Issue by erjillsison** [TEAMMATES/teammates#9776]
- **Environment**: 
`master` at commit ad2d071317e2b1c70139daf43148219cf859f0db

**Steps to reproduce**

1. As an instructor, create a feedback session with the following question types
    - MCQ
    - MSQ
    - Ranking
2. As a student, fill up the feedback session forms
3. As an instructor, close the feedback session by setting the deadline to a date before the current
4. As a student, view the closed submission

**Expected behaviour**
All forms should be greyed out and disabled and I should not be able to change my answers.

**Actual behaviour**
The options for the forms are still changable.

**Additional info**
This bug is not serious because although I can edit my answers on a closed session, I'm unable to submit that edited feedback.

**Comment by xpdavid** [comment]
#9721 should fix these for MSQ/MCQ. The disabled attribute is not used properly in the template https://github.com/TEAMMATES/teammates/pull/9721/files#diff-f13b3a5fbdb57841d7dfc0f11d8523edL6

**Comment by erjillsison** [comment]
I'll make a PR for the ranking question type

**Comment by xpdavid** [comment]
Fixed in master 4fb70a93119b887e4c6ccb7a70894994060d309c
