### ISSUE TITLE
Add sponsor info to V6

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9781]
TEAMMATES server cost are currently borne by NUS. In return, we are required to display their name as the sponsor. This needs to be added to V6 as well.

**Current footer:**
![image](https://user-images.githubusercontent.com/1673303/59667015-98973f80-91e8-11e9-8802-399745b3ce0a.png)
![image](https://user-images.githubusercontent.com/1673303/59667156-d72cfa00-91e8-11e9-98ed-199b7f1884d0.png)

**Requested change:**
Before login:
><sub>Sponsored by [School of Computing, National University of Singapore](). ([**Become a sponsor**]())</sub>

After login:
><sub>for ABC School<br>Sponsored by [School of Computing, National University of Singapore](). ([**Become a sponsor**]())</sub>

---
Add to the `Contact Us` page:

**Becoming a sponsor**: If you are interested to sponsor the TEAMMATES service for a period of time, please contact us at the above email address for details.

**Comment by xpdavid** [comment]
Fixed in #9787
