### ISSUE TITLE
Cache in Travis is not fetched properly

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9782]
- **Environment**: ad2d071317e2b1c70139daf43148219cf859f0db

**Steps to reproduce**

Go to Travis build process, look at the `Setting up build cache`.

**Expected behaviour**

https://travis-ci.org/TEAMMATES/teammates/jobs/546608857

**Actual behaviour**

https://travis-ci.org/TEAMMATES/teammates/jobs/547125797

**Additional info**

Looks like Travis has changed their caching logic. @wkurniawan07 will complain to them :P

**Comment by IAmPramod** [comment]
@xpdavid is this issue resolved after PR merge?

**Comment by xpdavid** [comment]
Nope. The PR only fix it by not using cache.

**Comment by wkurniawan07** [comment]
No longer relevant because `npm ci` makes cache redundant.
