### ISSUE TITLE
Courses/Edit: Deleting any instructor will delete yourself from the course

### ISSUE THREAD

**Issue by erjillsison** [TEAMMATES/teammates#9789]
- **Environment**: 
`master` branch at commit a1ca379b54ad2ab2d2a509d54129809a61605dc6

**Steps to reproduce**
Prereq: Have a course with at least 2 instructors with co-owner access level
1. Go to courses/edit?courseid=ANY_VALID_COURSE_ID
2. Delete any instructor that is not yourself

**Expected behaviour**
Instructor will be deleted

**Actual behaviour**
You will be deleted from the course and will be unable to access the course again

**Comment by xpdavid** [comment]
@erjillsison Instructor edit page is buggy in V7. @junming403 will take in charge of refactoring it. You may want to work with him.

**Comment by erjillsison** [comment]
I'll fix this issue in the meantime
