### ISSUE TITLE
Instructor/Courses/Details: Status in student list showing as "Unknown"

### ISSUE THREAD

**Issue by erjillsison** [TEAMMATES/teammates#9793]
- **Environment**: 
`master` branch at commit 30f56ffea3016decff6026cc46bb03e346ab7ffd

**Steps to reproduce**
1. Go to courses/details?courseid=ANY_VALID_COURSE_ID
2. Look at the entry under "Status" header in the student list

**Expected behaviour**
Should be either "Joined" or "Yet to Join"

**Actual behaviour**
Shows as Uknown

**Additional info**
Regression from PR #9777. 

Course details page should be updated to use the new REST endpoints.

**Comment by erjillsison** [comment]
@xpdavid I believe INSTRUCTOR_COURSE_DETAILS is outdated?

**Comment by xpdavid** [comment]
Yup. It should be removed and replaced with the new REST endpoints.
