### ISSUE TITLE
MCQ: Prevent duplicate options in MCQ

### ISSUE THREAD

**Issue by erjillsison** [TEAMMATES/teammates#9795]
- **Environment**: 
`master` branch at commit 30f56ffea3016decff6026cc46bb03e346ab7ffd

**UPDATE**
I realised the options I set are the same and that caused the problem. Perhaps the issue should be "Prevent duplicate options in MCQ" instead.

**Steps to reproduce**
~~1. Go to an unanswered MCQ question in a session~~
~~2. Select any option besides the first option~~

**Expected behaviour**
~~Option you select is selected~~

**Actual behaviour**
~~The first option will be selected~~

**Comment by nusjzx** [comment]
How are we going to instruct the user to correct it? For example: set focus to the `input` element until they change it to a non-duplicate option. Or any other way? @erjillsison

**Comment by erjillsison** [comment]
Perhaps can make do with a status message for now similar to how the other errors are handled.
E.g.,
![image](https://user-images.githubusercontent.com/22665593/63483368-ba55c100-c4ce-11e9-8e32-961d048929c1.png)

**Comment by xpdavid** [comment]
Yup. We can first just write a backend validation logic.

For the frontend, we still need some time to come out with the best way to do form validation #9419, therefore, we can just leave it there first.
