### ISSUE TITLE
Tinymce rich text box editor too long.

### ISSUE THREAD

**Issue by Pengyuz** [TEAMMATES/teammates#9799]
- **Environment**:  master

**Steps to reproduce**
1. Go to any page contain rich text box editor.
2. Click on the editor, toolbar will show up.

**Expected behaviour**
Appropriate length.

**Actual behaviour**
Toolbar extends to the border of the page.

**Comment by xpdavid** [comment]
Last time you told me this issue can be resolved by resetting the browser's cache?

**Comment by Pengyuz** [comment]
After I reinstall my the project using latest angular module, the problem is solved. When install the angular CLI, using command `npm install -g @angular/cli`(the command in the guide is `npm install -g @angular/cli@7`). I think the module tinymce-angular in the angular modules is updated and the problem is solved.

**Comment by wkurniawan07** [comment]
That's because the latest Angular is Angular 8. If you want to go down that path, there are a few more things you need to do than just upgrading the CLI. But `@tinymce/tinymce-angular` library has `>=6.0.0 <9.0.0` version specifier for `@angular` which means you shouldn't need to update the Angular version.

**Comment by xpdavid** [comment]
This is a known bug from https://github.com/tinymce/tinymce/issues/4819. Can be fixed by upgrading the dependency in package.json to ` "tinymce": "^5.0.8",`

**Comment by marloncalvo** [comment]
Is this still a relevant issue?
I was looking around the instructor/student rich text boxes and was not prompted with the aforementioned bug.

This is what I see:
![Screenshot from 2019-08-25 20-31-16](https://user-images.githubusercontent.com/29384504/63658375-0b3c1280-c778-11e9-9e80-682559f7f35c.png)

Note: I am using AngularCLI 7.3.9.

**Comment by xpdavid** [comment]
`"tinymce": "^5.0.4"` means any version that is above or equal to 5.0.4 will work. So it could be 5.0.4, 5.0.8 or the latest version depends on how `npm` resolve it.

**Comment by marloncalvo** [comment]
Oh, I see. That parameter syntax just requires a minimum version.
Which makes sense, since I see that my tinymc version is 5.0.14.

I'll do some testing for 5.0.8 then, thanks.
