### ISSUE TITLE
Add in masquerade mode

### ISSUE THREAD

**Issue by crizyli** [TEAMMATES/teammates#9804]
**Description of feature/enhancement**
Currently, in V7, the masquerade mode is not added.
Allow admin to impersonate as instructors or students to view and edit data.

**Possible solutions**
1. In each page, when need to send http request, first check if there is `user` present in `queryParams` in the url, if there is, then add `user: this.user` to the request's paramsMap, then send this masquerade request, otherwise, send the normal request.
2. add an optional parameter `user?` for HttpRequestService's get, put, update and delete method, and build the HttpParams there as in solution 1.
3. add a MasqueradeModeService to handle masquerade requests, but it still requires existence checks of `user` in each page.

May I have some suggestions for better solutions? @wkurniawan07 @xpdavid

**Comment by xpdavid** [comment]
We can have two services.

`MasqueradeModeService` and `HttpRequestService`. `MasqueradeModeService` is stateful while `HttpRequestService` is stateless. 

`HttpRequestService` depends on `MasqueradeModeService`. `HttpRequestService` will ask `MasqueradeModeService` to see if we need append user param to REST request. `MasqueradeModeService` depends on `RouterService` (i.e. It tries to get user param from the URL)..  `MasqueradeModeService` will store the identity (i.e. googleID) of the current user being masqureaded.
