### ISSUE TITLE
Submission page: Fix typo/grammatically incorrect error message

### ISSUE THREAD

**Issue by erjillsison** [TEAMMATES/teammates#9806]
- **Environment**: 
`master` branch at commit 30f56ffea3016decff6026cc46bb03e346ab7ffd

**Steps to reproduce**
1. Fill up a form incorrectly. e.g in MSQ fill up both the "None of the above" option and another option (this is also a bug as seen in #9805)
2. Submit the page

"Some questions do not saved" is shown instead of "Some questions were not saved".

![image](https://user-images.githubusercontent.com/22665593/60415043-9e3f4d00-9c0c-11e9-9907-63552901514f.png)

**Comment by damithc** [comment]
On a related note, it is better to use icon fonts (e.g., fontawesome) rather than emoji (e.g., ❗️ ) because emoji appearance depends on the browser.
