### ISSUE TITLE
Consider to add lombok to the project

### ISSUE THREAD

**Issue by adavid9** [TEAMMATES/teammates#9808]
Hi I have a suggestion, what about replacing all getters/setters in the entities classes with simple `@Data` annotation, did anyone consider to add Lombok to the project? Maybe we could use it, then we could get rid of many lines of code. Maybe previously there was a suggestion like that, I do not know, because today I forked the project, so I am totally new in it. This is only my suggestion, because first of all when I opened the project I realized that there is no Lombok.

**Comment by xpdavid** [comment]
@adavid9 Hi, if u use IntelliJ, Ctril+N will generate getter and setter automatically?

**Comment by adavid9** [comment]
@xpdavid Hi, when using lombok there is no need to generate getters and setters. The compiler does it for you in the runtime. For developer is important only to install lombok plugin and enable pre processor in your IDE. With lombok we could get rid of all getters and setters that are no need, so we could make the code easier to read for the entities.

**Comment by xpdavid** [comment]
> For developer is important only to install lombok plugin and enable pre processor in your IDE.

I do see an additional step during the setup process. In addition, any new developers need to learn lombok I think.

> With lombok we could get rid of all getters and setters that are no need

Personally, I am OK with additional getters and setters. They are not that annoying when reading code. Besides, our "data" class is not pure data class. We do have some abstractions (i.e. additional logic) in the setter and getter methods.

**Comment by adavid9** [comment]
@xpdavid Actually learning lombok is unnecessary, the most important annotation is just `@Data`. I am totally fine with your opinion I just gave a sugesttion if you think there is no need to use it, okay.

**Comment by wkurniawan07** [comment]
Not to be done anytime soon.
