### ISSUE TITLE
Natural sort for tables

### ISSUE THREAD

**Issue by erjillsison** [TEAMMATES/teammates#9819]
- **Environment**: 
`master` branch at commit e4700402dcc9a3ae6193d2501b069da096d6c47a

Currently, sorting is done alphabetically by default. However, if there are multi-digit numbers in the labels, the sorting is not intuitive e.g "Team 11" will come first before "Team 2".

But natural sorting can't be applied to all labels with numbers e.g course IDs where the first digit indicates the level and there's a variable number of digits. Say, CS1010 is before CS202.

Have to explore where to place natural sorting and how to implement it.

**Comment by joelact** [comment]
Hello  erjillsison,

I found a way to do natural sort without changing that much the code.
Link ref: https://stackoverflow.com/questions/2802341/javascript-natural-sort-of-alphanumerical-strings

I would like to do some refactoring in the code to create a sorting service and continuing working on this project.

Best regards mate.

**Comment by xpdavid** [comment]
Hi @joelact , please refactor them one by one (as per PR). Create a new issue if necessary.
