### ISSUE TITLE
Student result: Feedback made on behalf of team showing as anonymous

### ISSUE THREAD

**Issue by erjillsison** [TEAMMATES/teammates#9823]
...even with the visibility set to `Visible to recipient and instructors`

- **Environment**: 
`master` branch at commit a3e909210ccd21c653ae09f04e618cb06c36c418

**Steps to reproduce**
1. As an instructor, create a feedback session with a question set with feedback path: `Teams in this course -> Other students in the course` and visibility option: `Visible to recipient and instructors`
2. As a student, submit feedback for the above question.
3. As an instructor, publish the session.
4. Log in again as a student and view the results.

**Expected behaviour**
Since the visibility is not set to anonymous, the giver(which should be the student's team name) and recipient name should be shown for the student.

**Actual behaviour**
Giver and recipient showing as anonymous

**Comment by sandysingh11918** [comment]
Is this issue still open? I would like to contribute.

**Comment by madanalogy** [comment]
Resolved by #10135
