### ISSUE TITLE
Combine table action buttons into a dropdown

### ISSUE THREAD

**Issue by erjillsison** [TEAMMATES/teammates#9830]
- **Environment**: 
`master` branch at commit 4fb70a93119b887e4c6ccb7a70894994060d309c

**Description of feature/enhancement**
Combine the action buttons found in the sessions table in the instructor home page. Might be better to leave the most used buttons (Result? Submit?) outside of the drop-down menu.

This is the current look of the course table from the home page.

![image](https://user-images.githubusercontent.com/22665593/61774624-d6136c00-ae29-11e9-8cc4-c0e44a6ec201.png)

Combining the buttons will save some space so that each row will not take an additional line and will reduce visual clutter.

**Cons:**
Requires an additional click to do an action

**Pros:**
Less visual noise
Saves space

**Suggested look:**
![image](https://user-images.githubusercontent.com/22665593/61843626-052fe900-aecf-11e9-901f-0ad1228e63a4.png)

While we're at it, update the look of the table with the following changes:
- Set contents to nowrap
- Set cell width to content width
- Highlight row on hover
- Combine action buttons to a dropdown
- Change button colours to have higher contrast

**Comment by erjillsison** [comment]
**Feedback Sessions page**

**Current:**
![image](https://user-images.githubusercontent.com/22665593/61777981-808e8d80-ae30-11e9-9bbd-5b64c0efdd24.png)
**Updated**
![image](https://user-images.githubusercontent.com/22665593/61778069-a3b93d00-ae30-11e9-919e-28d3eeeeb807.png)

**Comment by erjillsison** [comment]
@Nagureddy Yes, the issue is still open. However, there's already an open PR that addresses it.

**Comment by hcwong** [comment]
can i take this, seems inactive?

**Comment by wkurniawan07** [comment]
Will not be doing this.
