### ISSUE TITLE
Inconsistent labelling of recycle bin

### ISSUE THREAD

**Issue by erjillsison** [TEAMMATES/teammates#9832]
- **Environment**: 
`master` branch at commit 4fb70a93119b887e4c6ccb7a70894994060d309c

See below:

**Instructor courses page**
![image](https://user-images.githubusercontent.com/22665593/61690788-b6fad880-ad5c-11e9-91ef-db3f0049874b.png)

**Instructor sessions page**
![image](https://user-images.githubusercontent.com/22665593/61690795-bd895000-ad5c-11e9-833d-ff561e4e9b6a.png)

**Comment by Vaironl** [comment]
Hi, mind if I take this?
