### ISSUE TITLE
Modal: Clicking a link in the navbar while a modal is open does not close the modal

### ISSUE THREAD

**Issue by erjillsison** [TEAMMATES/teammates#9836]
- **Environment**: 
`master` branch at commit 4fb70a93119b887e4c6ccb7a70894994060d309c

**Steps to reproduce**
1. Go to any page with an action that opens a modal e.g in instructor home page, delete a session
2. Once the modal is open, click on any link in the navbar e.g 'Courses'

**Expected behaviour**
Modal is dismissed.

**Actual behaviour**
Modal remains open

**Comment by Diana-Ramos** [comment]
Hi, I'm currently working on this issue if it is okay
