### ISSUE TITLE
Remove unused endpoint STUDENT_COURSE

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9842]
The frontend does not use `/student/course` anymore, it can be safely removed.

**Comment by adithyaChander** [comment]
Hey, can I please take this up ?

**Comment by xpdavid** [comment]
Sure

**Comment by adithyaChander** [comment]
Thanks. Will work on this

**Comment by stephanie-gredell** [comment]
@adithyaChander Are you still working on this? I'd like to give it a go if you're not.

**Comment by rhu2001** [comment]
@xpdavid I'd also like to give this a go. Is that fine?

**Comment by nusjzx** [comment]
@xpdavid I'll take this issue, as rhu closed the PR?

**Comment by Erik-D-Mueller** [comment]
Is this issue closed then?

**Comment by dhuang612** [comment]
doesn't seem to the pr was closed not merged.

**Comment by isa3bel** [comment]
can I contribute to this?

**Comment by RizkyRajitha** [comment]
im a first timer 
if i remove path from this file , will it fix the issue

https://github.com/TEAMMATES/teammates/blob/master/src/web/app/pages-student/student-pages.module.ts

**Comment by xpdavid** [comment]
Let's make it clear. The frontend does not use the backend API `/webapi/student/course` anymore.
