### ISSUE TITLE
JVM default Locale should be set to parse the datetime 

### ISSUE THREAD

**Issue by nusjzx** [TEAMMATES/teammates#9850]
`parseInstant` method in `TimeHelper` class is using `DateTimeFormatter.ofPattern` to create format pattern which uses the JVM default locale. For locale like Japan Korea, and China, it cannot parse the date time string correctly

- **Environment**:  `master` branch at commit #9832 

**Steps to reproduce**
1. You can either change operating system locale, which is JVM default scale, or  add `Locale.setDefault(Locale.CHINESE);` in `parseInstant` method  in `src\main\java\teammates\common\util\TimeHelper.java`
2. start the app engine 
3.login as administrator and add instructors

**Expected behaviour**
should add the instructors correctly

**Actual behaviour**
![image](https://user-images.githubusercontent.com/24241939/63221712-9a3aa080-c162-11e9-9026-89822b0e17a3.png)
![image](https://user-images.githubusercontent.com/24241939/63221740-13d28e80-c163-11e9-965a-7e427186f0a4.png)

**Comment by nusjzx** [comment]
@damithc Although there is a solution in trouble shooting, which was to change the date system default date time format. We can actually handle this configuration in code, instead of let the developer change their default settings individually.

**Comment by wkurniawan07** [comment]
@nusjzx The dev troubleshooting guide is severely outdated. That aside, configuration inside code is very much preferred over tampering with dev's local machine.
