### ISSUE TITLE
Intellij IDE

### ISSUE THREAD

**Issue by kashu1209** [TEAMMATES/teammates#9878]
hello , 
Please help me in opening the project in Ide.
Actually i am not familiar with python and i know basics of frontend development
but i can do far better in java so if you can please tell me which file to open so i can run and see results on ide itself.
Thanks

Regards
kashish
maggukashish01@gmail.com

**Comment by rutvij2811** [comment]
https://github.com/TEAMMATES/teammates/blob/master/docs/ide-setup.md
This should help you with setting up the IDE.

**Comment by kashu1209** [comment]
> https://github.com/TEAMMATES/teammates/blob/master/docs/ide-setup.md
> This should help you with setting up the IDE.

Thanks brother for this!

**Comment by kashu1209** [comment]
Hello,
while doing project setup its not showing any frame works detected.[](url)

**Comment by amarlearning** [comment]
@kashu1209 which IntelliJ version you are using?

**Comment by mrjoshi0147** [comment]
Whenever I am opening my IDE it is showing this error  "Could not initialize class org.codehaus.groovy.classgen.Verifier"
