### ISSUE TITLE
Feedback grid not within borders, minor defect.

### ISSUE THREAD

**Issue by briyanii** [TEAMMATES/teammates#9882]
**Environment**: 
Firefox 69.0.3 (64-bit)
The peer evaluation form for CS2103T peer evaluation feedback.

**Steps to reproduce**
Open the form by pressing edit forum

**Expected behaviour**
I assume that the content should be within the borders.

**Actual behaviour**
The grid for multiple choice response does not stay within the grid because the dropdown menu to choose the person the response is directed at is beside the grid as shown in the screenshot below.
<img width="1672" alt="Content not within borders" src="https://user-images.githubusercontent.com/44989270/66698166-23f38e00-ed0e-11e9-8d99-ad8e3ec64883.png">

**Comment by wkurniawan07** [comment]
Fixed in V7
