### ISSUE TITLE
Students can still access courses that are in the recycle bin

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9884]
v6.16.3, live version

A user reported that students can still access courses that are in the recycle bin

**Comment by niqiukun** [comment]
Not sure about the cause in v6, but in v7 students can still access/submit/edit their feedback sessions when the course is soft-deleted. There is currently no check for course status when getting feedback questions. Is this an intended behaviour?

**Comment by damithc** [comment]
Sounds like a but. That is not the intended behavior.

**Comment by xpdavid** [comment]
Related to #9124

**Comment by sandysingh11918** [comment]
I would like to work if the issue is still open.

**Comment by stapletonce** [comment]
Is this bug still open?

**Comment by wkurniawan07** [comment]
Not valid anymore
