### ISSUE TITLE
Student cannot delete own comment given to response

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9885]
v6.16.3, live version

A student reported that a comment he added for his own responses cannot be deleted. When he tried to delete, it returned an error.

**Comment by nusjzx** [comment]
Prof, Is there any other information about the question type and feedback path?

**Comment by damithc** [comment]
It is a case of students giving feedback to team members. Here's a screenshot.
![image](https://user-images.githubusercontent.com/1673303/67618148-db63c680-f81d-11e9-941b-044bca30ec8a.png)

**Comment by nusjzx** [comment]
I cannot reproduce this issue. Following the same question type and feedback path, I'm able to delete the comment as a student

**Comment by damithc** [comment]
@nusjzx Are you using V7 or V6?

**Comment by nusjzx** [comment]
> @nusjzx Are you using V7 or V6?
I'm using v6, v7 doesn't have this function yet

**Comment by damithc** [comment]
I see. Let's leave it alone for now as it affects V6 only and not a critical problem.

**Comment by wkurniawan07** [comment]
Not valid anymore
