### ISSUE TITLE
Login Dropdown List is Not Positioned Properly 

### ISSUE THREAD

**Issue by ethanwc15** [TEAMMATES/teammates#9886]
- **Environment**: 
Angular Live Development Server is listening on localhost. 
TEAMMATES Version 7.0.0

**Steps to reproduce**
1. Open your browser with the local host link.
2. Click Login on the top right of the window.
3. View the drop-down list for student and instructor.

**Expected behaviour**
The login drop-down list for student and instructor should be aligned properly on the right hand side. Text should not be covered up by the scrolling bar on the right-hand side of the screen. It seems the slider bar wasn't accounted for when positioning the drop down list for student and instructor.

**Actual behaviour**
The login drop-down list for student and instructor is slightly off to the right to where the text, specifically the instructor text, is being hidden by the scrolling bar.

**Additional info**
It seems that there needs to be some re-positioning for the drop-down with HTML?
Screenshot of defect on UI:
![image](https://user-images.githubusercontent.com/55211466/68057442-e3ab7e00-fcc3-11e9-8511-b2f63dbde502.png)

**Comment by xpdavid** [comment]
Yup. I also notice this while developing. @ethanwc15 Feel free to submit a fix.

**Comment by ethanwc15** [comment]
Great, thank you! We are going to start looking into it soon.

**Comment by ethanwc15** [comment]
@xpdavid We created a fix and are in the process of a pull request as we speak.

**Comment by xpdavid** [comment]
Might be fixed with upgrade from #9863

**Comment by xpdavid** [comment]
Not fixed after #9863. Remove `OnHold`

**Comment by madanalogy** [comment]
@DyllanSowersTR will you be reopening your PR for this issue? If not then I would like to work on it
