### ISSUE TITLE
Sample course: do not assume the instructor is male

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9891]
The sample course creation seem to assume the instructor is male as some of the sample comments use `he`. We can avoid such pronouns as it would look odd if the instructor is female.

**Comment by daekoon** [comment]
Hello, I would like to work on this issue. Can I have more details regarding this? What is the "same data creation" referring to?

**Comment by damithc** [comment]
> Can I have more details regarding this? What is the "same data creation" referring to?

Corrected. It should be _sample course creation_. This refers to the creation of a sample course when TEAMMATES creates an instructor account (an admin feature).

**Comment by snickercop** [comment]
I couldn't find this particular instance but I found a couple of stray "he's" and fixed them... is that helpful?
