### ISSUE TITLE
hey guys!, I'm radesh a newbie, I'm here to contribute to the open source coomunity, And I felt that TEAMMATES is the best choice for me.My Skill set:- HTML,CSS,JQUERY,JAVASCRIPT,BOOTSTRAP,PHP,AJAX.And im learning node js and angular js for backend.I would be very happy to work on beginner issues.Help me with getting started THANK YOU.

### ISSUE THREAD

**Issue by Radesh-kumar** [TEAMMATES/teammates#9900]
Before opening a new issue, please check that no existing issue covers the same topic.

Go to the "Preview" tab and click on the relevant issue type to be redirected to the appropriate template.

- [Bug reports](?template=bug-report.md)
- [Feature/enhancement requests, enhancement to build process](?template=feature-request.md)
- [Help requests](?template=help-request.md)
- [Data migration](?template=data-migration.md)

For other tasks (e.g. refactoring, adding tests, fixing typo), there is no template to follow. Simply provide a clear issue title and description of the work to be done.

If you are reporting a security vulnerability, due to the sensitive nature of such a report, you are kindly requested to refrain from opening a new issue.
Instead, submit your report by emailing the team at teammates@comp.nus.edu.sg.

**Comment by ChooJeremy** [comment]
Hi @Radesh-kumar 

Please look through the [docs](https://github.com/TEAMMATES/teammates/blob/master/docs/CONTRIBUTING.md) to get started :) Feel free to post any issues/questions you have along the way.

For your first issue, I would recommend getting started with a first timer issue, as those are generally localized and do not require knowledge of a large part of the codebase.

**Comment by xpdavid** [comment]
Yup, @Radesh-kumar you can follow @ChooJeremy 's suggestions.
