### ISSUE TITLE
Replace src/web/types/gender.ts with Gender in api-output.ts

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9902]
TODO: as stated exactly in the title.

Goal:
- We can benefit from the auto-sync of API output types between frontend and backend.
- One can also learn how `./gradlew generateTypes` sync API request/response type between frontend and backend.

**Comment by laazo** [comment]
Hullo, I would like to pick this issue up. Is there anyone looking at it?

**Comment by tiuweehan** [comment]
Hi @laazo, may I clarify if you are working on this issue?

**Comment by laazo** [comment]
Sure, please clarify for me

**Comment by tiuweehan** [comment]
@laazo sorry if there was a misunderstanding, I was checking if you are currently attempting to solve this issue. If not, I intend to work on it.

**Comment by laazo** [comment]
@tiuweehan no problem. You can go ahead and work on it

**Comment by tiuweehan** [comment]
@laazo thanks for clarifying!
