### ISSUE TITLE
Replace src/web/app/pages-instructor/student-profile/student-profile.ts with StudentProfile in api-output.ts

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9903]
To be done after #9902 

TODO:
- More efforts need to convert component `ts` files, html files and test files to adopt the type.

Goal:
- We can benefit from the auto-sync of API output types between frontend and backend.

**Comment by tiuweehan** [comment]
Hi, can I take this issue?

**Comment by tiuweehan** [comment]
The `StudentProfile` type in `api-output.ts` is missing the `pictureKey` field `student-profile.ts`. 

Should I replace all occurences of `StudentProfile` with `StudentProfile & StudentProfilePictureResults`, or create a new type e.g. `StudentProfileWithPictureKey`?

![image](https://user-images.githubusercontent.com/39181981/72416594-03761c80-37b2-11ea-94db-e470e745b93a.png)

![image](https://user-images.githubusercontent.com/39181981/72416575-f5c09700-37b1-11ea-82c9-c8db7189c402.png)

**Comment by xpdavid** [comment]
This is a contributor issue so it is not that straight-forward as firstTimer issue. Think about it: Do you need pictureKey? Is there any place where pictureKey is used? If so, can we get rid of it? How?

**Comment by tiuweehan** [comment]
`StudentProfile` is used in the following components (on frontend side):
- `InstructorHelpStudentsSectionComponent`:
It is used as the type for variable `exampleStudentProfile`. This variable is passed to the `StudentProfileComponent`.

-  `StudentProfileComponent`:
It is used as the type for variable `studentProfile`. This variable is passed to `student-profile.component.html`, but the field `pictureKey` is never used.

- `StudentProfileStubComponent`:
It is used as the type for variable `studentProfile` in the test files `instructor-course-student-details-page.component.spec` and `instructor-help-students-section.component.spec`. The variable is also passed to `StudentProfileComponent`

It seems to me that the type `StudentProfile` is only used in `StudentProfileComponent`, and the field `pictureKey` is never used at all. Can I conclude that it is safe to just remove the `pictureKey` field?
