### ISSUE TITLE
Auto-sync API request type: Intent

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9915]
Just realize we could do something further beyond #9196 

There is an `Intent` class in the backend (JAVA) and `intent.ts` interface and in the frontend (TypeScript). They have the same structure and we should make use of the `./gradlew generateTypes` to auto-sync them.

Note that `Intent.java` should be in `request` package.

**Comment by YuetChan** [comment]
Can I give it a try?
