### ISSUE TITLE
Loading bar persists when courses of the student are soft-deleted

### ISSUE THREAD

**Issue by niqiukun** [TEAMMATES/teammates#9917]
**Environment**: 
`master` branch at commit https://github.com/TEAMMATES/teammates/pull/9897/commits/59c356e84ccfbf5863797fb5ca80270be506ff41.

**Steps to reproduce**
Create a new course, enroll a student, and move the course to the recycle bin. Then login as the student and navigate to the student's home page.

**Expected behaviour**
Display a message showing no courses available for the student.

**Actual behaviour**
The top progress bar persists and there is no error message.
![image](https://user-images.githubusercontent.com/5328196/72659418-4a565300-39fa-11ea-9247-c3d76f6ce2de.png)

**Comment by Rinita-De** [comment]
Hi, I am interested in working on this issue. Please let me know if I can pick it up.

**Comment by rafaelbalanquet** [comment]
Hello! Our team would like to claim this issue.
@team

**Comment by aishaadambek** [comment]
Hello team!

I completed all the tasks in the Contributor orientation guide and **got the Dev Green**. 
I have reproduced the bug and **I am now ready to contribute**.

I started working on the issue and will hopefully soon have some results! 

Let me know if anything else can be done beyond the Development Workflow document.
