### ISSUE TITLE
Remove HttpRequestService dependency from StudentListComponent

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9918]
Reason: `StudentListComponent` is a component and is supposed to be used in multiple places. Thus, it should not be associated with a specific API request fire against the backend. All API request should be made by the corresponding pages which use it.

**Comment by madanalogy** [comment]
Hello, I would like to work on this. To remove `HttpRequestService` dependency I will be moving student deletion to `StudentService`, will be submitting a PR shortly.

**Comment by xpdavid** [comment]
Hi @madanalogy , you not only need to move it to `StudentService` but also to move the invocation of method to its corresponding page.

**Comment by madanalogy** [comment]
> Hi @madanalogy , you not only need to move it to `StudentService` but also to move the invocation of method to its corresponding page.

Have moved it to `CourseService` instead to prevent unnecessary coupling to `StudentService`. 

Also, method invocation now functions as an emitter to be handled by the implementing component (see PR). I'm not too sure if this was the right way to go about it (I'm new to angular) so if there's any comments/feedback just let me know thanks!
