### ISSUE TITLE
Remove HttpRequestService dependency from UploadEditProfilePictureModalComponent

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9919]
Same Reason: Reason:`UploadEditProfilePictureModalComponent` is a component and is supposed to be used in multiple places (although the reason is less convincing here as the modal is only used once. Nevertheless, let's just follow the convention). Thus, it should not be associated with a specific API request fire against the backend. All API request should be made by the corresponding pages which use it.

**Comment by tiuweehan** [comment]
I would like to take this issue, but I think there are a few approaches. Which do you think will be the most suitable? (or maybe there are better alternative approaches?)

**Approach 1**
1. Move `getPictureProfile()` from `upload-edit-profile-picture-modal.component.ts` to `student-profile-page.component.ts`
2. Pass the return value of type `Observable<Blob>` as an `@Input` to `upload-edit-profile-picture-modal.component.ts`
3. Subscribe to the `Observable<Blob>` from within `upload-edit-profile-picture-modal.component.ts`

**Approach 2**
1. Move `getPictureProfile()` from `upload-edit-profile-picture-modal.component.ts` to `student-profile-page.component.ts`
2. Subscribe to the `Observable<Blob>` from within `student-profile-page.component.ts`
3. When the callback function of `Observable<Blob>` is triggered, open the modal and pass the `resp` as `@Input` to `upload-edit-profile-picture-modal.component.ts`

**Approach 3**
1. Move `getPictureProfile()` from `upload-edit-profile-picture-modal.component.ts` to `student-profile-page.component.ts`
2. Subscribe to the `Observable<Blob>` from within `student-profile-page.component.ts`
3. Open the modal
4. When the callback function of `Observable<Blob>` is triggered, pass the `resp` as `@Input` to `upload-edit-profile-picture-modal.component.ts`

**Comment by xpdavid** [comment]
I think Approach 2 is the most appropriate one.

Approach 1:
You don't want to pass `Observable<Blob>` to child component. In other word, there is no need for child component to **observe** what is happening in the parent component. In contrast, you want to reverse the workflow. When something happens in the parent component, you want to update the child component in the parent component (usually done by `[property]=xxx` binding).

BTW, you can also remove `profilePicLink`. Looks like it is unused.

Approach 3:
This is just a design consideration. Maybe we don't want user to see empty picture when the modal is open.
