### ISSUE TITLE
staging server error: 404 Not Found

### ISSUE THREAD

**Issue by mrturkmen06** [TEAMMATES/teammates#9929]
- **Commit SHA:** 
- **Operating System:** MacOS Catalina 10.15.2
- **JDK Version:**  1.8.0
- **Node.js Version:** v12.12.0
- **Google Cloud SDK Version:** 1.9.77
- **IntelliJ Version (if applicable):**
- **Firefox / Chrome Version (if applicable):**

**What I was trying to do / What I need help with**
I am trying to deploy teammates to staging server where I have created app on Google cloud and set project id as described in deploying [documentation](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#deploying-to-a-staging-server). However, I am receiving __Error:Not Found__ response from the application url. 

**Attempts to resolve the problem**
Re-deploy and control all the settings by following descriptions which are given on deploying to staging server documentation yet I have received same response from server (__Error: Not Found__)

I have checked [previous issue](https://github.com/TEAMMATES/teammates/issues/6306) which is related to same topic however it does not point to my situation.

**Comment by xpdavid** [comment]
@mrturkmen06 You need to run `npm run build` to compile the frontend to the production-ready code.

**Comment by mrturkmen06** [comment]
@xpdavid  Thanks a lot !!
