### ISSUE TITLE
Migration to new RESTful search endpoints

### ISSUE THREAD

**Issue by hcwong** [TEAMMATES/teammates#9946]
This endpoint migration aims to migrate the endpoints for search to call the individual entities instead of calling the endpoints by user status (Admin, Instructor, Student)

- **Environment**: 

**Justification**
Our search queries have become too long and has busted GAE's limit. See #4345.

**Existing similar features and their shortcomings**
We can't make long queries

## Progress Update

- [ ] Backend  
  - [ ] Student
  - [ ] Instructor
  - [ ] Course 
  - [ ] Link
  - [ ] Session
- [ ] Frontend
  - [ ] Search/join Admin 
  - [ ] Search/join Instructor

**Comment by xpdavid** [comment]
For those who are interested, please discuss with me (better) or your mentor for possible design before sending PR. We don't want you effort being wasted. :)

**Comment by hcwong** [comment]
This is a RFC btw: so open to all suggestions

**Comment by xpdavid** [comment]
Just for those who are working on this:
Question to answer first before writing ANY code:
- How many new endpoints will you add? Is it RESTFul?
- Do we need to change the search logic? Do we need data migration?
- What is the request format? 
- What is the response format? 
- Will the design satisfy the current requirement and be scalable enough to eliminate the issue mentioned?
