### ISSUE TITLE
Deploying to server other than google cloud 

### ISSUE THREAD

**Issue by mrturkmen06** [TEAMMATES/teammates#9947]
- **Operating System:** MacOS Mojave
- **JDK Version:** 1.8.0_241
- **Node.js Version:** v12.12.0
- **Google Cloud SDK Version:**  276.0.0
- **IntelliJ Version (if applicable):**
- **Firefox / Chrome Version (if applicable):**

**What I was trying to do / What I need help with**
I would like to know that is there any possible way to deploy the application to my own server rather than GAE. The reason of it that, it charges a lot of money even though I deployed it with instance type F1. (default)

**Comment by wkurniawan07** [comment]
@mrturkmen06 it is currently not possible.
