### ISSUE TITLE
Use TypeScript Utility types

### ISSUE THREAD

**Issue by tiuweehan** [TEAMMATES/teammates#9963]
I think it might be good if we can refactor to use some TypeScript [Utility types](https://www.typescriptlang.org/docs/handbook/utility-types.html).

For example, I notice that `{ [key: string]: string }` is a commonly used type in the application. It might be cleaner to use `Record<string,string>` instead.

That's my observation for now, I'm sure there are other utility classes which could be useful, such as Partials for a subset of an existing type.

**Comment by awpathum** [comment]
Can you mention the file names plaese?

**Comment by xpdavid** [comment]
Good idea
