### ISSUE TITLE
Refactor Course Add & Edit into Single Form

### ISSUE THREAD

**Issue by madanalogy** [TEAMMATES/teammates#9976]
There are a lot of similarities between the [`add-course-form`](https://github.com/TEAMMATES/teammates/tree/master/src/web/app/pages-instructor/instructor-courses-page/add-course-form) and the course edit portion of the [`instructor-course-edit-page`](https://github.com/TEAMMATES/teammates/tree/master/src/web/app/pages-instructor/instructor-course-edit-page). I'm thinking we could abstract out the form template and utilise them in both components for improved code quality.

**Comment by xpdavid** [comment]
Yup. You can take a look at how other ADD/EDIT form achieve that.

**Comment by madanalogy** [comment]
For anyone interested in tackling this, I'd recommend doing so after #9975 and #9820 are resolved.

**Comment by e-nayana** [comment]
I would love to work on this. But I have to wait until [#9975](https://github.com/TEAMMATES/teammates/pull/9975) and [#9820](https://github.com/TEAMMATES/teammates/pull/9820) are resolved

**Comment by ziqing26** [comment]
I would like to work on this issue and start with investigating other similar forms.

**Comment by thikhinab** [comment]
May I attempt to work on this issue, if no one else is?

**Comment by ziqing26** [comment]
> May I attempt to work on this issue, if no one else is?

@thikhinab Hello, yes you may work on it as there is no open PR yet.

**Comment by thikhinab** [comment]
@ziqing26 Noted with thanks!
