### ISSUE TITLE
Join confirmation sent to instructors: include a link to TEAMMATES

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9986]
Request received from a user:
When an instructor clicks on a 'join' link sent by TEAMMATES, they receive an email confirming that they have registered for the course. Perhaps the email can also contain a clickable link of TEAMMATES for instructors to easily reach TEAMMATES from that email?

**Comment by amarlearning** [comment]
@damithc I would like to take this one :smile:

**Comment by damithc** [comment]
Welcome back @amarlearning Go ahead.

**Comment by amarlearning** [comment]
@damithc any suggestion, where should I add the teammates link in email?

**Comment by damithc** [comment]
> @damithc any suggestion, where should I add the teammates link in email?

Can have a look at the current email and suggest some possibilities?

**Comment by amarlearning** [comment]
```
<p>Hello, ${userName}</p>

<p>
  Thank you for registering as ${userType} in the course: <strong>[${courseId}] ${courseName}</strong>
  with the Google ID: <strong>${googleId}</strong>.
</p>

**ADD IT HERE**

<p>
  In case you have been registered to the wrong course, been incorrectly registered, or
  if you need any help or clarifications regarding TEAMMATES, please email us at ${supportEmail}.
</p>

<p>
  Regards,
  <br>TEAMMATES Team.
</p>
```
@damithc I think we should add the teammate's link over there.

**Comment by damithc** [comment]
How about just hyperlink `<strong>[${courseId}] ${courseName}</strong>`?

**Comment by amarlearning** [comment]
a hyperlink around this `<strong>[${courseId}] ${courseName}</strong>` ?

**Comment by damithc** [comment]
Yes, that seems like a logical place for the instructor to click, to reach TEAMMATES.

**Comment by amarlearning** [comment]
@damithc I think giving teammates `homepage link` around the `course` is not good because once they click on the link they might be expecting the `course page` instead of `homepage`.

**Comment by damithc** [comment]
> And if we give `course link` around `course id` then after logging it is not redirecting to the course page automatically.

That's true. I'm OK to add it as a separate link too.
