### ISSUE TITLE
Migrate GetCourseEnrollStudentsAction to GetStudentsAction

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9989]
`GetCourseEnrollStudentsAction` is not RESTFul-compliant which should be migrated in #9595. 

One can check migration requirements in that issue.  

Hint: The functionalities of the endpoint is the same as `/students`.

**Comment by AdamPanag** [comment]
Hello, I am a new contributor and I have chosen TEAMMATES  as the OSS that I will contribute for my university course "Software Engineering in Practise". I would like to work on this issue, but I am open to work to any other issue that you can assign to me.

**Comment by sandysingh11918** [comment]
is this issue still open? i would like to work on that
