### ISSUE TITLE
Typo in the pop-up message of the button "Send Invite"

### ISSUE THREAD

**Issue by AdamPanag** [TEAMMATES/teammates#9996]
![typo-issue-teammates](https://user-images.githubusercontent.com/44143668/77484981-aee7c100-6e34-11ea-88f2-9bb77e4ad985.png)

- **Environment**:  The screenshot is from an instructor's account in the Student List page.

- **Expected behaviour**: I think that the right message should be "...using his/her Google Account..."
and "...without joining, but a..."

I would like to work on this issue!

**Comment by AdamPanag** [comment]
Hello, I can work on this!

**Comment by damithc** [comment]
Go ahead @AdamPanag
